SELECT 
    CASE WHEN PIPE_CATALOG_NAME = 'WATERLAKE_${var.ENVIRONMENT}' THEN
            REGEXP_REPLACE(PIPE_SCHEMA_NAME,'^INTEGRATION_','')
        ELSE
            REGEXP_REPLACE(REGEXP_REPLACE(PIPE_NAME,'^.*PIPE_',''),'_.*','') 
    END AS "SOURCE", 
    PIPE_CATALOG_NAME AS "DATABASE", 
    PIPE_SCHEMA_NAME AS "SCHEMA", 
    PIPE_NAME  AS "OBJECT",
    CASE WHEN STATUS = 'Loaded' THEN 'SUCCEEDED'
        WHEN STATUS = 'Load failed' THEN 'FAILED'
        ELSE STATUS
    END AS "STATUS",
    CASE WHEN STATUS = 'Loaded' THEN 1 ELSE 0 END AS "SUCCESS",
    CASE WHEN STATUS = 'Load failed' THEN 1 ELSE 0 END AS "FAILED",
    FIRST_ERROR_MESSAGE AS "ERROR MESSAGE",
    COUNT(*) AS "TOTAL"
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY 
WHERE PIPE_CATALOG_NAME IN ('${var.ENVIRONMENT}_WCC_DATAWAREHOUSE', 'WATERLAKE_${var.ENVIRONMENT}')
      AND PIPE_SCHEMA_NAME <> 'LOGGING'
      AND "SOURCE" = :source_system
      AND LAST_LOAD_TIME = :daterange  
GROUP BY "SOURCE",
      "DATABASE",
      "SCHEMA",
      "OBJECT",
      "STATUS", 
      "ERROR MESSAGE"
UNION ALL
SELECT DISTINCT 
    CASE WHEN PIPE_CATALOG_NAME = 'WATERLAKE_${var.ENVIRONMENT}' THEN
            REGEXP_REPLACE(PIPE_SCHEMA_NAME,'^INTEGRATION_','')
        ELSE
            REGEXP_REPLACE(REGEXP_REPLACE(PIPE_NAME,'^.*PIPE_',''),'_.*','') 
    END AS "SOURCE", 
    PIPE_CATALOG_NAME AS "DATABASE", 
    PIPE_SCHEMA_NAME AS "SCHEMA", 
    '' AS "OBJECT",
    'FAILED' AS "STATUS",
    0 AS "SUCCESS",
    0 AS "FAILED",
    '' AS "ERROR MESSAGE",   
    0 AS "TOTAL"
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY 
WHERE PIPE_CATALOG_NAME IN ('${var.ENVIRONMENT}_WCC_DATAWAREHOUSE', 'WATERLAKE_${var.ENVIRONMENT}')
  AND PIPE_SCHEMA_NAME <> 'LOGGING'
  AND "SOURCE" = :source_system
  AND LAST_LOAD_TIME = :daterange  
;