CREATE OR REPLACE TABLE TARGET_LN.LN_TFFAM830(
            abdf integer, 
            abdf_kw varchar, 
            adpc numeric(38, 17), 
            compnr integer, 
            cost_1 numeric(38, 17), 
            cost_2 numeric(38, 17), 
            cost_3 numeric(38, 17), 
            curd date, 
            deleted boolean, 
            depr_1 numeric(38, 17), 
            depr_2 numeric(38, 17), 
            depr_3 numeric(38, 17), 
            dtty integer, 
            dtty_kw varchar, 
            jobn integer, 
            last date, 
            ltdd_1 numeric(38, 17), 
            ltdd_2 numeric(38, 17), 
            ltdd_3 numeric(38, 17), 
            ltdr_1 numeric(38, 17), 
            ltdr_2 numeric(38, 17), 
            ltdr_3 numeric(38, 17), 
            ltdu integer, 
            meth varchar, 
            meth_ref_compnr integer, 
            prop varchar, 
            prop_ref_compnr integer, 
            rcst_1 numeric(38, 17), 
            rcst_2 numeric(38, 17), 
            rcst_3 numeric(38, 17), 
            sequencenumber integer, 
            susp integer, 
            susp_kw varchar, 
            timestamp datetime, 
            tkey integer, 
            tkey_ref_compnr integer, 
            unit integer, 
            user varchar, 
            username varchar, 
            ytdd_1 numeric(38, 17), 
            ytdd_2 numeric(38, 17), 
            ytdd_3 numeric(38, 17), 
            ytdr_1 numeric(38, 17), 
            ytdr_2 numeric(38, 17), 
            ytdr_3 numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 