CREATE OR REPLACE TABLE TARGET_LN.LN_TFACP251(
            amth_1 numeric(38, 17), 
            amth_2 numeric(38, 17), 
            amth_3 numeric(38, 17), 
            aprp integer, 
            apry integer, 
            buex integer, 
            buex_kw varchar, 
            ccur varchar, 
            compnr integer, 
            data datetime, 
            dbmo integer, 
            dbmo_kw varchar, 
            deleted boolean, 
            finl integer, 
            finl_kw varchar, 
            iamt numeric(38, 17), 
            icom integer, 
            idoc integer, 
            ifbp varchar, 
            ifbp_ref_compnr integer, 
            imrf object, 
            iqan numeric(38, 17), 
            ityp varchar, 
            loco integer, 
            orno varchar, 
            otyp integer, 
            otyp_kw varchar, 
            pdfd integer, 
            pdfd_kw varchar, 
            pdif numeric(38, 17), 
            pono integer, 
            pric integer, 
            pric_kw varchar, 
            ratd datetime, 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rcno varchar, 
            rseq integer, 
            rtyp varchar, 
            sequencenumber integer, 
            shpm varchar, 
            shpm_otyp_orno_pono_sqnb_loco_rcno_rseq_ref_compnr integer, 
            sqnb integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 