CREATE OR REPLACE TABLE TARGET_LN.LN_TPPSS020(
            apdt datetime, 
            basn integer, 
            bsta integer, 
            bsta_kw varchar, 
            compnr integer, 
            cprj varchar, 
            cprj_dbsn_ref_compnr integer, 
            cprj_ref_compnr integer, 
            crdt datetime, 
            dbsn integer, 
            deleted boolean, 
            dsca object, 
            lmus varchar, 
            lupd datetime, 
            sequencenumber integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 