CREATE OR REPLACE TABLE TARGET_LN.LN_TFFAM710(
            acnp integer, 
            acnp_kw varchar, 
            bdad integer, 
            bdad_kw varchar, 
            bnbv integer, 
            bnbv_kw varchar, 
            calb integer, 
            calb_kw varchar, 
            capp integer, 
            capp_kw varchar, 
            compnr integer, 
            conv integer, 
            conv_kw varchar, 
            cper numeric(38, 17), 
            dbpt numeric(38, 17), 
            deleted boolean, 
            depl integer, 
            depl_kw varchar, 
            desc object, 
            didt integer, 
            didt_kw varchar, 
            disp integer, 
            disp_kw varchar, 
            dprc integer, 
            dprc_kw varchar, 
            face integer, 
            face_kw varchar, 
            famt integer, 
            famt_kw varchar, 
            fcal integer, 
            fcal_kw varchar, 
            fcom integer, 
            fcom_kw varchar, 
            ffin integer, 
            ffin_kw varchar, 
            fixa_1 numeric(38, 17), 
            fixa_2 numeric(38, 17), 
            fixa_3 numeric(38, 17), 
            foth integer, 
            foth_kw varchar, 
            fspe integer, 
            fspe_kw varchar, 
            fsta integer, 
            fsta_kw varchar, 
            fstd integer, 
            fstd_kw varchar, 
            gfac numeric(38, 17), 
            intr numeric(38, 17), 
            life integer, 
            meth varchar, 
            nygf integer, 
            perc numeric(38, 17), 
            post integer, 
            post_kw varchar, 
            rdgf numeric(38, 17), 
            rndy integer, 
            rndy_kw varchar, 
            rtty integer, 
            rtty_kw varchar, 
            sbsv integer, 
            sbsv_kw varchar, 
            sequencenumber integer, 
            silp integer, 
            silp_kw varchar, 
            stcp integer, 
            stcp_kw varchar, 
            swsl integer, 
            swsl_kw varchar, 
            taxt integer, 
            taxt_kw varchar, 
            timestamp datetime, 
            type integer, 
            type_kw varchar, 
            updt integer, 
            updt_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 