CREATE OR REPLACE TABLE TARGET_LN.LN_TFACP270(
            amnt numeric(38, 17), 
            amth_1 numeric(38, 17), 
            amth_2 numeric(38, 17), 
            amth_3 numeric(38, 17), 
            buid varchar, 
            cact varchar, 
            ccur varchar, 
            clss integer, 
            compnr integer, 
            cprj varchar, 
            cspa varchar, 
            cuni varchar, 
            dbcr integer, 
            dbcr_kw varchar, 
            dcom integer, 
            deleted boolean, 
            docn integer, 
            fcom integer, 
            guid varchar, 
            idtc varchar, 
            ktrn integer, 
            ktrn_kw varchar, 
            nuni numeric(38, 17), 
            obre varchar, 
            ocmp integer, 
            rbid varchar, 
            rbon varchar, 
            reco integer, 
            reco_kw varchar, 
            recs integer, 
            rpon integer, 
            sequencenumber integer, 
            timestamp datetime, 
            ttyp varchar, 
            txin integer, 
            txin_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 