CREATE OR REPLACE TABLE TARGET_LN.LN_TFACP245(
            boid varchar, 
            bonm varchar, 
            borf varchar, 
            cmnf varchar, 
            compnr integer, 
            cval numeric(38, 17), 
            cvlc varchar, 
            cvlc_ref_compnr integer, 
            deleted boolean, 
            fcpo integer, 
            imrf object, 
            lmat integer, 
            lmat_kw varchar, 
            loco integer, 
            loco_otyp_orno_pono_sqnb_ref_compnr integer, 
            maam numeric(38, 17), 
            maqu numeric(38, 17), 
            mpnr varchar, 
            mqpu numeric(38, 17), 
            mtch integer, 
            mtch_kw varchar, 
            omti integer, 
            omti_kw varchar, 
            orno varchar, 
            otbp varchar, 
            otyp integer, 
            otyp_kw varchar, 
            pono integer, 
            quan numeric(38, 17), 
            rcno varchar, 
            rdat datetime, 
            rgui varchar, 
            rqty numeric(38, 17), 
            rseq integer, 
            sbdt integer, 
            sbdt_kw varchar, 
            sdat datetime, 
            sequencenumber integer, 
            sfbl integer, 
            sfbl_kw varchar, 
            shpm varchar, 
            sqnb integer, 
            timestamp datetime, 
            toma integer, 
            toma_kw varchar, 
            trqn numeric(38, 17), 
            uppr integer, 
            uppr_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 