CREATE OR REPLACE TABLE TARGET_LN.LN_TPPTC311(
            aaoc_1 numeric(38, 17), 
            aaoc_2 numeric(38, 17), 
            aaoc_3 numeric(38, 17), 
            aaoc_4 numeric(38, 17), 
            aaos_1 numeric(38, 17), 
            aaos_2 numeric(38, 17), 
            aaos_3 numeric(38, 17), 
            aaos_4 numeric(38, 17), 
            adjm integer, 
            adjm_kw varchar, 
            amoc numeric(38, 17), 
            amoc_cntc numeric(38, 17), 
            amoc_dwhc numeric(38, 17), 
            amoc_prjc numeric(38, 17), 
            amoc_refc numeric(38, 17), 
            amos numeric(38, 17), 
            amos_cntc numeric(38, 17), 
            amos_dwhc numeric(38, 17), 
            amos_prjc numeric(38, 17), 
            amos_refc numeric(38, 17), 
            basn integer, 
            btdt datetime, 
            cact varchar, 
            ccal varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            cico varchar, 
            cico_rcmp integer, 
            clas varchar, 
            clas_ref_compnr integer, 
            cocu varchar, 
            cocu_ref_compnr integer, 
            cohc_1 numeric(38, 17), 
            cohc_2 numeric(38, 17), 
            cohc_3 numeric(38, 17), 
            cohc_4 numeric(38, 17), 
            compnr integer, 
            cona numeric(38, 17), 
            cona_cntc numeric(38, 17), 
            cona_dwhc numeric(38, 17), 
            cona_prjc numeric(38, 17), 
            cona_refc numeric(38, 17), 
            cotp integer, 
            cotp_kw varchar, 
            cpla varchar, 
            cprj varchar, 
            cprj_basn_ref_compnr integer, 
            cprj_ccal_ref_compnr integer, 
            cprj_cico varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_fcmp integer, 
            cprj_ref_compnr integer, 
            cprj_task varchar, 
            cptc varchar, 
            cptc_ref_compnr integer, 
            cptc_year_peri_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            cuti varchar, 
            cuti_ref_compnr integer, 
            deleted boolean, 
            dura numeric(38, 17), 
            emno varchar, 
            emno_ref_compnr integer, 
            exeq integer, 
            exeq_kw varchar, 
            item varchar, 
            item_ref_compnr integer, 
            lcaa_1 numeric(38, 17), 
            lcaa_2 numeric(38, 17), 
            lcaa_3 numeric(38, 17), 
            lcaa_4 numeric(38, 17), 
            lcos_cntc numeric(38, 17), 
            lcos_dwhc numeric(38, 17), 
            lcos_prjc numeric(38, 17), 
            lcos_refc numeric(38, 17), 
            lcta numeric(38, 17), 
            norm numeric(38, 17), 
            peri integer, 
            prca_1 numeric(38, 17), 
            prca_2 numeric(38, 17), 
            prca_3 numeric(38, 17), 
            prca_4 numeric(38, 17), 
            pric numeric(38, 17), 
            pric_cntc numeric(38, 17), 
            pric_dwhc numeric(38, 17), 
            pric_prjc numeric(38, 17), 
            pric_refc numeric(38, 17), 
            pris numeric(38, 17), 
            pris_cntc numeric(38, 17), 
            pris_dwhc numeric(38, 17), 
            pris_prjc numeric(38, 17), 
            pris_refc numeric(38, 17), 
            prsa_1 numeric(38, 17), 
            prsa_2 numeric(38, 17), 
            prsa_3 numeric(38, 17), 
            prsa_4 numeric(38, 17), 
            quan numeric(38, 17), 
            quan_base_time numeric(38, 17), 
            quan_buar numeric(38, 17), 
            quan_buln numeric(38, 17), 
            quan_bupc numeric(38, 17), 
            quan_buvl numeric(38, 17), 
            quan_buwg numeric(38, 17), 
            quan_ctut numeric(38, 17), 
            qutm numeric(38, 17), 
            ratc numeric(38, 17), 
            rats numeric(38, 17), 
            refr varchar, 
            rfin datetime, 
            rsta datetime, 
            rtca_1 numeric(38, 17), 
            rtca_2 numeric(38, 17), 
            rtca_3 numeric(38, 17), 
            rtca_4 numeric(38, 17), 
            rtsa_1 numeric(38, 17), 
            rtsa_2 numeric(38, 17), 
            rtsa_3 numeric(38, 17), 
            rtsa_4 numeric(38, 17), 
            sacu varchar, 
            sacu_ref_compnr integer, 
            scpf numeric(38, 17), 
            sequencenumber integer, 
            sern integer, 
            stat integer, 
            stat_kw varchar, 
            task varchar, 
            task_rcmp integer, 
            timestamp datetime, 
            tmud varchar, 
            tmud_ref_compnr integer, 
            unrt varchar, 
            unrt_ref_compnr integer, 
            user varchar, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 