CREATE OR REPLACE TABLE TARGET_LN.LN_TPPDM790(
            acmp integer, 
            aext varchar, 
            agty integer, 
            agty_kw varchar, 
            aloc varchar, 
            anbr varchar, 
            arch integer, 
            arch_kw varchar, 
            ardt datetime, 
            capp integer, 
            capp_kw varchar, 
            ccam varchar, 
            ccam_ref_compnr integer, 
            ccat varchar, 
            ccat_ref_compnr integer, 
            ccot varchar, 
            ccot_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            cfac varchar, 
            cfac_ref_compnr integer, 
            cmud varchar, 
            cmud_ref_compnr integer, 
            cobs varchar, 
            cobs_ref_compnr integer, 
            comp integer, 
            compnr integer, 
            copr numeric(38, 17), 
            coty integer, 
            coty_kw varchar, 
            cprj varchar, 
            creg varchar, 
            creg_ref_compnr integer, 
            csec varchar, 
            csec_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            dldt datetime, 
            dscb object, 
            espt numeric(38, 17), 
            fddt datetime, 
            intp integer, 
            intp_kw varchar, 
            invm integer, 
            invm_kw varchar, 
            ipin integer, 
            ipin_kw varchar, 
            itbp varchar, 
            itbp_ref_compnr integer, 
            kopr integer, 
            kopr_kw varchar, 
            kptm integer, 
            kptm_kw varchar, 
            mprj varchar, 
            ncmp integer, 
            ofbp varchar, 
            ofbp_ref_compnr integer, 
            padr varchar, 
            padr_ref_compnr integer, 
            pfbp varchar, 
            pfbp_ref_compnr integer, 
            psdt datetime, 
            psta integer, 
            psta_kw varchar, 
            ptcs numeric(38, 17), 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rdat datetime, 
            rept numeric(38, 17), 
            rers numeric(38, 17), 
            rfcu object, 
            rtyp varchar, 
            rtyp_ref_compnr integer, 
            scun integer, 
            scun_kw varchar, 
            seab object, 
            seak object, 
            sequencenumber integer, 
            stdt datetime, 
            tbdg integer, 
            tbdg_kw varchar, 
            timestamp datetime, 
            tmpl integer, 
            tmpl_kw varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            txtn integer, 
            txtn_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 