CREATE OR REPLACE TABLE TARGET_LN.LN_TFGLD482(
            admm integer, 
            admm_kw varchar, 
            alam integer, 
            alam_kw varchar, 
            amnt numeric(38, 17), 
            amth_1 numeric(38, 17), 
            amth_2 numeric(38, 17), 
            amth_3 numeric(38, 17), 
            bpid varchar, 
            btno integer, 
            buid varchar, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            crdt datetime, 
            crus varchar, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            dbcr integer, 
            dbcr_kw varchar, 
            deleted boolean, 
            dim1 varchar, 
            dim2 varchar, 
            dim3 varchar, 
            dim4 varchar, 
            dim5 varchar, 
            dim6 varchar, 
            dim7 varchar, 
            dim8 varchar, 
            dim9 varchar, 
            dm10 varchar, 
            dm11 varchar, 
            dm12 varchar, 
            docn integer, 
            eibc_1 integer, 
            eibc_2 integer, 
            eibc_3 integer, 
            eibc_kw_1 varchar, 
            eibc_kw_2 varchar, 
            eibc_kw_3 varchar, 
            fcom integer, 
            fprd integer, 
            fyer integer, 
            glcu integer, 
            glcu_kw varchar, 
            guid varchar, 
            idtc varchar, 
            idtc_ref_compnr integer, 
            leac varchar, 
            lino integer, 
            mscd varchar, 
            msvs integer, 
            nuni numeric(38, 17), 
            obre varchar, 
            ocmp integer, 
            podt datetime, 
            pous varchar, 
            prin integer, 
            prin_kw varchar, 
            ratd datetime, 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rbid varchar, 
            rbon varchar, 
            rbon_ref_compnr integer, 
            rpon integer, 
            rprd integer, 
            rtyp varchar, 
            ryer integer, 
            secd varchar, 
            sequencenumber integer, 
            seva varchar, 
            sint integer, 
            sint_kw varchar, 
            tcmp integer, 
            timestamp datetime, 
            tprd integer, 
            trdt datetime, 
            ttyp varchar, 
            tyer integer, 
            username varchar, 
            usgr varchar, 
            usgr_ref_compnr integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 