CREATE OR REPLACE TABLE TARGET_LN.LN_TDPUR301(
            aemq integer, 
            aemq_kw varchar, 
            bamt numeric(38, 17), 
            bamt_dtwc numeric(38, 17), 
            bamt_lclc numeric(38, 17), 
            bamt_rfrc numeric(38, 17), 
            bamt_rpc1 numeric(38, 17), 
            bamt_rpc2 numeric(38, 17), 
            bpcl varchar, 
            bpcl_ref_compnr integer, 
            bptc varchar, 
            bptc_ref_compnr integer, 
            cadr varchar, 
            cadr_ref_compnr integer, 
            caga numeric(38, 17), 
            caga_dtwc numeric(38, 17), 
            caga_lclc numeric(38, 17), 
            caga_rfrc numeric(38, 17), 
            caga_rpc1 numeric(38, 17), 
            caga_rpc2 numeric(38, 17), 
            camt numeric(38, 17), 
            camt_dtwc numeric(38, 17), 
            camt_lclc numeric(38, 17), 
            camt_rfrc numeric(38, 17), 
            camt_rpc1 numeric(38, 17), 
            camt_rpc2 numeric(38, 17), 
            ccon varchar, 
            ccon_ref_compnr integer, 
            ccty varchar, 
            ccty_cvat_ref_compnr integer, 
            ccty_ref_compnr integer, 
            cdat datetime, 
            cdec varchar, 
            cdec_ref_compnr integer, 
            cdf_cdsc object, 
            cdf_clmt numeric(38, 17), 
            cdf_comt numeric(38, 17), 
            cdf_idet varchar, 
            cdf_ramt numeric(38, 17), 
            cdf_refe object, 
            cdf_sctg varchar, 
            ceno varchar, 
            citt varchar, 
            citt_ref_compnr integer, 
            cltp integer, 
            cltp_kw varchar, 
            cmnf varchar, 
            cmnf_ref_compnr integer, 
            cncd varchar, 
            cofc varchar, 
            cofc_ref_compnr integer, 
            compnr integer, 
            cono varchar, 
            cono_ref_compnr integer, 
            cons integer, 
            cons_kw varchar, 
            cpgp varchar, 
            cpgp_ref_compnr integer, 
            crit object, 
            crrf integer, 
            crrf_kw varchar, 
            csqn integer, 
            csts integer, 
            csts_kw varchar, 
            cuqp varchar, 
            cuqp_ref_compnr integer, 
            cvat varchar, 
            cvqp numeric(38, 17), 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            dsch integer, 
            dsch_kw varchar, 
            edat datetime, 
            effn integer, 
            effn_ref_compnr integer, 
            exmt integer, 
            exmt_kw varchar, 
            gamt_dtwc numeric(38, 17), 
            gamt_lclc numeric(38, 17), 
            gamt_rfrc numeric(38, 17), 
            gamt_rpc1 numeric(38, 17), 
            gamt_rpc2 numeric(38, 17), 
            gamt_trnc numeric(38, 17), 
            iaga numeric(38, 17), 
            iaga_dtwc numeric(38, 17), 
            iaga_lclc numeric(38, 17), 
            iaga_rfrc numeric(38, 17), 
            iaga_rpc1 numeric(38, 17), 
            iaga_rpc2 numeric(38, 17), 
            icap integer, 
            icap_kw varchar, 
            icyp integer, 
            icyp_kw varchar, 
            ieva integer, 
            ieva_kw varchar, 
            iqab integer, 
            iqab_kw varchar, 
            item varchar, 
            item_ref_compnr integer, 
            leng numeric(38, 17), 
            mpnr varchar, 
            mpnr_cmnf_ref_compnr integer, 
            mqtl numeric(38, 17), 
            namt_dtwc numeric(38, 17), 
            namt_lclc numeric(38, 17), 
            namt_rfrc numeric(38, 17), 
            namt_rpc1 numeric(38, 17), 
            namt_rpc2 numeric(38, 17), 
            namt_trnc numeric(38, 17), 
            ncmp integer, 
            ncmp_ref_compnr integer, 
            obpr integer, 
            obpr_kw varchar, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            owno object, 
            paft integer, 
            paft_kw varchar, 
            poff varchar, 
            poff_ref_compnr integer, 
            pono integer, 
            ptpa varchar, 
            ptpa_ref_compnr integer, 
            qiap numeric(38, 17), 
            qicl numeric(38, 17), 
            qicl_buar numeric(38, 17), 
            qicl_buln numeric(38, 17), 
            qicl_bupc numeric(38, 17), 
            qicl_butm numeric(38, 17), 
            qicl_buvl numeric(38, 17), 
            qicl_buwg numeric(38, 17), 
            qicl_trnu numeric(38, 17), 
            qiec numeric(38, 17), 
            qifi numeric(38, 17), 
            qigc numeric(38, 17), 
            qigc_buar numeric(38, 17), 
            qigc_buln numeric(38, 17), 
            qigc_bupc numeric(38, 17), 
            qigc_butm numeric(38, 17), 
            qigc_buvl numeric(38, 17), 
            qigc_buwg numeric(38, 17), 
            qigc_trnu numeric(38, 17), 
            qigi numeric(38, 17), 
            qigi_buar numeric(38, 17), 
            qigi_buln numeric(38, 17), 
            qigi_bupc numeric(38, 17), 
            qigi_butm numeric(38, 17), 
            qigi_buvl numeric(38, 17), 
            qigi_buwg numeric(38, 17), 
            qigi_trnu numeric(38, 17), 
            qiiv numeric(38, 17), 
            qiiv_buar numeric(38, 17), 
            qiiv_buln numeric(38, 17), 
            qiiv_bupc numeric(38, 17), 
            qiiv_butm numeric(38, 17), 
            qiiv_buvl numeric(38, 17), 
            qiiv_buwg numeric(38, 17), 
            qiiv_trnu numeric(38, 17), 
            qima numeric(38, 17), 
            qimf numeric(38, 17), 
            qimi numeric(38, 17), 
            qogo numeric(38, 17), 
            qogo_buar numeric(38, 17), 
            qogo_buln numeric(38, 17), 
            qogo_bupc numeric(38, 17), 
            qogo_butm numeric(38, 17), 
            qogo_buvl numeric(38, 17), 
            qogo_buwg numeric(38, 17), 
            qogo_invu numeric(38, 17), 
            qomn numeric(38, 17), 
            qomx numeric(38, 17), 
            qoor numeric(38, 17), 
            qoor_buar numeric(38, 17), 
            qoor_buln numeric(38, 17), 
            qoor_bupc numeric(38, 17), 
            qoor_butm numeric(38, 17), 
            qoor_buvl numeric(38, 17), 
            qoor_buwg numeric(38, 17), 
            qoor_invu numeric(38, 17), 
            qual integer, 
            qual_kw varchar, 
            rcod varchar, 
            rcod_ref_compnr integer, 
            rcsi varchar, 
            rcsi_ref_compnr integer, 
            revi varchar, 
            rpdr integer, 
            rpdr_kw varchar, 
            sbdt integer, 
            sbdt_kw varchar, 
            sbim integer, 
            sbim_kw varchar, 
            sbmt varchar, 
            sbmt_ref_compnr integer, 
            scus integer, 
            scus_kw varchar, 
            sdat datetime, 
            sdsc integer, 
            sdsc_kw varchar, 
            sequencenumber integer, 
            sfad varchar, 
            sfad_ref_compnr integer, 
            sfbp varchar, 
            sfbp_ref_compnr integer, 
            sfcn varchar, 
            sfcn_ref_compnr integer, 
            site varchar, 
            site_ref_compnr integer, 
            subc integer, 
            subc_kw varchar, 
            subs varchar, 
            subs_ref_compnr integer, 
            thic numeric(38, 17), 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            txtt integer, 
            txtt_ref_compnr integer, 
            username varchar, 
            widt numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 