CREATE OR REPLACE TABLE TARGET_LN.LN_TPPTC230(
            acln integer, 
            amoc numeric(38, 17), 
            amos numeric(38, 17), 
            btdt datetime, 
            cact varchar, 
            ccal varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            cocu varchar, 
            cocu_ref_compnr integer, 
            cofc varchar, 
            cofc_ref_compnr integer, 
            compnr integer, 
            cona numeric(38, 17), 
            copy integer, 
            copy_kw varchar, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cpla_cact_sero_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            ctrg varchar, 
            ctrg_ref_compnr integer, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            deleted boolean, 
            dfrc integer, 
            dfrc_kw varchar, 
            dura numeric(38, 17), 
            emno varchar, 
            emno_ref_compnr integer, 
            eplf numeric(38, 17), 
            espp varchar, 
            freq numeric(38, 17), 
            guid varchar, 
            lino integer, 
            norm numeric(38, 17), 
            orno varchar, 
            prsr integer, 
            prsr_kw varchar, 
            quan numeric(38, 17), 
            ratc numeric(38, 17), 
            rats numeric(38, 17), 
            rfac varchar, 
            rfin datetime, 
            rsta datetime, 
            rtcc_1 numeric(38, 17), 
            rtcc_2 numeric(38, 17), 
            rtcc_3 numeric(38, 17), 
            rtcs_1 numeric(38, 17), 
            rtcs_2 numeric(38, 17), 
            rtcs_3 numeric(38, 17), 
            rtfc_1 integer, 
            rtfc_2 integer, 
            rtfc_3 integer, 
            rtfs_1 integer, 
            rtfs_2 integer, 
            rtfs_3 integer, 
            sacu varchar, 
            sacu_ref_compnr integer, 
            sequencenumber integer, 
            sern integer, 
            sero integer, 
            slnk integer, 
            slnk_kw varchar, 
            snsb integer, 
            stat integer, 
            stat_kw varchar, 
            task varchar, 
            timestamp datetime, 
            tmud varchar, 
            trts integer, 
            trts_kw varchar, 
            tsrl integer, 
            tsrl_kw varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            unrt varchar, 
            unrt_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 