CREATE OR REPLACE TABLE TARGET_LN.LN_TSCTM136(
            alco_1 numeric(38, 17), 
            alco_2 numeric(38, 17), 
            alco_3 numeric(38, 17), 
            alco_cntc numeric(38, 17), 
            alco_dwhc numeric(38, 17), 
            alco_refc numeric(38, 17), 
            alqu numeric(38, 17), 
            alqu_buar numeric(38, 17), 
            alqu_buln numeric(38, 17), 
            alqu_bupc numeric(38, 17), 
            alqu_buvl numeric(38, 17), 
            alqu_buwg numeric(38, 17), 
            alqu_invu numeric(38, 17), 
            alsa numeric(38, 17), 
            alsa_dwhc numeric(38, 17), 
            alsa_homc numeric(38, 17), 
            alsa_refc numeric(38, 17), 
            alsa_rpc1 numeric(38, 17), 
            alsa_rpc2 numeric(38, 17), 
            amnt numeric(38, 17), 
            amnt_dwhc numeric(38, 17), 
            amnt_homc numeric(38, 17), 
            amnt_refc numeric(38, 17), 
            amnt_rpc1 numeric(38, 17), 
            amnt_rpc2 numeric(38, 17), 
            camt_1 numeric(38, 17), 
            camt_2 numeric(38, 17), 
            camt_3 numeric(38, 17), 
            camt_cntc numeric(38, 17), 
            camt_dwhc numeric(38, 17), 
            camt_refc numeric(38, 17), 
            ccmp varchar, 
            ccmp_ref_compnr integer, 
            cctp varchar, 
            cctp_ref_compnr integer, 
            cfln integer, 
            compnr integer, 
            cotp integer, 
            cotp_kw varchar, 
            cseq integer, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            dspc integer, 
            dspc_kw varchar, 
            ealc_1 numeric(38, 17), 
            ealc_2 numeric(38, 17), 
            ealc_3 numeric(38, 17), 
            ealc_cntc numeric(38, 17), 
            ealc_dwhc numeric(38, 17), 
            ealc_refc numeric(38, 17), 
            eals numeric(38, 17), 
            eals_dwhc numeric(38, 17), 
            eals_homc numeric(38, 17), 
            eals_refc numeric(38, 17), 
            eals_rpc1 numeric(38, 17), 
            eals_rpc2 numeric(38, 17), 
            eaqu numeric(38, 17), 
            eaqu_buar numeric(38, 17), 
            eaqu_buln numeric(38, 17), 
            eaqu_bupc numeric(38, 17), 
            eaqu_butm numeric(38, 17), 
            eaqu_buvl numeric(38, 17), 
            eaqu_buwg numeric(38, 17), 
            eaqu_invu numeric(38, 17), 
            item varchar, 
            item_ref_compnr integer, 
            nrbt integer, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            pric_1 numeric(38, 17), 
            pric_2 numeric(38, 17), 
            pric_3 numeric(38, 17), 
            pris numeric(38, 17), 
            quan numeric(38, 17), 
            quan_buar numeric(38, 17), 
            quan_buln numeric(38, 17), 
            quan_bupc numeric(38, 17), 
            quan_buvl numeric(38, 17), 
            quan_buwg numeric(38, 17), 
            quan_invu numeric(38, 17), 
            sequencenumber integer, 
            spco_1 numeric(38, 17), 
            spco_2 numeric(38, 17), 
            spco_3 numeric(38, 17), 
            spco_cntc numeric(38, 17), 
            spco_dwhc numeric(38, 17), 
            spco_refc numeric(38, 17), 
            spqu numeric(38, 17), 
            spsa numeric(38, 17), 
            spsa_dwhc numeric(38, 17), 
            spsa_homc numeric(38, 17), 
            spsa_refc numeric(38, 17), 
            spsa_rpc1 numeric(38, 17), 
            spsa_rpc2 numeric(38, 17), 
            term integer, 
            term_cfln_cctp_cotp_nrbt_ref_compnr integer, 
            term_cfln_ref_compnr integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 