CREATE OR REPLACE TABLE TARGET_LN.LN_TPPDM615(
            blbl integer, 
            blbl_kw varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            cccr varchar, 
            cccr_ref_compnr integer, 
            ccfu integer, 
            ccfu_kw varchar, 
            ccir varchar, 
            ccir_ref_compnr integer, 
            ccsr varchar, 
            ccsr_ref_compnr integer, 
            ccts varchar, 
            cofc varchar, 
            cofc_ref_compnr integer, 
            compnr integer, 
            cprj varchar, 
            cprj_ccts varchar, 
            cprj_ref_compnr integer, 
            cprj_task varchar, 
            ctrg varchar, 
            ctrg_ref_compnr integer, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            cvat varchar, 
            cvat_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            dfrc integer, 
            dfrc_kw varchar, 
            dfri integer, 
            dfri_kw varchar, 
            dfrs integer, 
            dfrs_kw varchar, 
            dfts varchar, 
            dfts_ref_compnr integer, 
            eplf numeric(38, 17), 
            ltrc datetime, 
            ltri datetime, 
            ltrs datetime, 
            norm numeric(38, 17), 
            prre integer, 
            prre_kw varchar, 
            ratc numeric(38, 17), 
            rati numeric(38, 17), 
            rats numeric(38, 17), 
            rcmc_1 numeric(38, 17), 
            rcmc_2 numeric(38, 17), 
            rcmc_3 numeric(38, 17), 
            rfac varchar, 
            rimc_1 numeric(38, 17), 
            rimc_2 numeric(38, 17), 
            rimc_3 numeric(38, 17), 
            rsmc_1 numeric(38, 17), 
            rsmc_2 numeric(38, 17), 
            rsmc_3 numeric(38, 17), 
            seak object, 
            sequencenumber integer, 
            task varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            unrt varchar, 
            unrt_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 