CREATE OR REPLACE TABLE TARGET_LN.LN_WHWMD215(
            compnr integer, 
            cwar varchar, 
            cwar_item_ref_compnr integer, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            hstd datetime, 
            item varchar, 
            item_ref_compnr integer, 
            lsid datetime, 
            ltdt datetime, 
            qall numeric(38, 17), 
            qblk numeric(38, 17), 
            qbpl numeric(38, 17), 
            qcal numeric(38, 17), 
            qchd numeric(38, 17), 
            qcis numeric(38, 17), 
            qcit numeric(38, 17), 
            qcom numeric(38, 17), 
            qcor numeric(38, 17), 
            qcpr numeric(38, 17), 
            qcrj numeric(38, 17), 
            qgit numeric(38, 17), 
            qhib numeric(38, 17), 
            qhnd numeric(38, 17), 
            qhrj numeric(38, 17), 
            qint numeric(38, 17), 
            qlal numeric(38, 17), 
            qnal numeric(38, 17), 
            qnbl numeric(38, 17), 
            qnbp numeric(38, 17), 
            qnhd numeric(38, 17), 
            qnit numeric(38, 17), 
            qnor numeric(38, 17), 
            qnrj numeric(38, 17), 
            qoal numeric(38, 17), 
            qoor numeric(38, 17), 
            qord numeric(38, 17), 
            sequencenumber integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 