CREATE OR REPLACE TABLE TARGET_LN.LN_WHINH220(
            acpn integer, 
            acpn_kw varchar, 
            acvt integer, 
            acvt_kw varchar, 
            addt datetime, 
            adin varchar, 
            atse varchar, 
            atse_ref_compnr integer, 
            bcko integer, 
            bcko_kw varchar, 
            bflh integer, 
            bflh_kw varchar, 
            bgxc integer, 
            bgxc_kw varchar, 
            blck integer, 
            blck_kw varchar, 
            casi varchar, 
            casi_ref_compnr integer, 
            cdck integer, 
            cdck_kw varchar, 
            circ object, 
            clot varchar, 
            cncl integer, 
            cncl_kw varchar, 
            comp integer, 
            compnr integer, 
            corn object, 
            csvc varchar, 
            csvc_ref_compnr integer, 
            csvl numeric(38, 17), 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            dlpt varchar, 
            dtag varchar, 
            effn integer, 
            effn_ref_compnr integer, 
            fact varchar, 
            fcco varchar, 
            fcco_ref_compnr integer, 
            fisc integer, 
            fisc_kw varchar, 
            fmln integer, 
            fmor varchar, 
            fprj varchar, 
            fprj_ref_compnr integer, 
            fspa varchar, 
            fstl varchar, 
            gefo integer, 
            gefo_kw varchar, 
            gnld varchar, 
            hstq integer, 
            hstq_kw varchar, 
            huid varchar, 
            huwt integer, 
            huwt_kw varchar, 
            ifbp varchar, 
            ifbp_ref_compnr integer, 
            imcs varchar, 
            inup integer, 
            inup_kw varchar, 
            iown integer, 
            iown_kw varchar, 
            ipay integer, 
            ipay_kw varchar, 
            iscn integer, 
            iscn_kw varchar, 
            istr integer, 
            istr_kw varchar, 
            item varchar, 
            item_atse_ref_compnr integer, 
            item_clot_ref_compnr integer, 
            item_ref_compnr integer, 
            iubw integer, 
            iubw_kw varchar, 
            lsel integer, 
            lsel_kw varchar, 
            lsta integer, 
            lsta_kw varchar, 
            masp integer, 
            masp_kw varchar, 
            oarq integer, 
            oarq_kw varchar, 
            ocur varchar, 
            ocur_ref_compnr integer, 
            oorg integer, 
            oorg_kw varchar, 
            oorg_orno_oset_ref_compnr integer, 
            orno varchar, 
            orpr numeric(38, 17), 
            orun varchar, 
            orun_ref_compnr integer, 
            oset integer, 
            ovfp integer, 
            ovfp_kw varchar, 
            ovlp integer, 
            ovlp_kw varchar, 
            owns integer, 
            owns_kw varchar, 
            paym integer, 
            paym_kw varchar, 
            pddt datetime, 
            pkdb integer, 
            pkdb_kw varchar, 
            pkdf varchar, 
            pkdf_ref_compnr integer, 
            pono integer, 
            prdt datetime, 
            prio integer, 
            prjp integer, 
            prjp_kw varchar, 
            qacp numeric(38, 17), 
            qact numeric(38, 17), 
            qadp numeric(38, 17), 
            qadv numeric(38, 17), 
            qapp numeric(38, 17), 
            qapr numeric(38, 17), 
            qcad numeric(38, 17), 
            qcap numeric(38, 17), 
            qcnl numeric(38, 17), 
            qcnp numeric(38, 17), 
            qnpu numeric(38, 17), 
            qnse numeric(38, 17), 
            qnsh numeric(38, 17), 
            qnsp numeric(38, 17), 
            qoop numeric(38, 17), 
            qoor numeric(38, 17), 
            qopu numeric(38, 17), 
            qord numeric(38, 17), 
            qoro numeric(38, 17), 
            qorp numeric(38, 17), 
            qova numeric(38, 17), 
            qovd numeric(38, 17), 
            qovp numeric(38, 17), 
            qpic numeric(38, 17), 
            qpip numeric(38, 17), 
            qprv numeric(38, 17), 
            qpss numeric(38, 17), 
            qpsv numeric(38, 17), 
            qrej numeric(38, 17), 
            qrel numeric(38, 17), 
            qrep numeric(38, 17), 
            qreq numeric(38, 17), 
            qrpu numeric(38, 17), 
            qrsc numeric(38, 17), 
            qrsp numeric(38, 17), 
            qscl numeric(38, 17), 
            qscp numeric(38, 17), 
            qshp numeric(38, 17), 
            qspu numeric(38, 17), 
            refe object, 
            refs object, 
            revi varchar, 
            rorg integer, 
            rorg_kw varchar, 
            rorn varchar, 
            rowc integer, 
            rowc_ref_compnr integer, 
            rown varchar, 
            rown_ref_compnr integer, 
            rpon integer, 
            rqpu numeric(38, 17), 
            rseq integer, 
            rush integer, 
            rush_kw varchar, 
            scon integer, 
            scon_kw varchar, 
            seqn integer, 
            sequencenumber integer, 
            serl varchar, 
            shrt integer, 
            shrt_kw varchar, 
            spcn varchar, 
            ssts integer, 
            ssts_kw varchar, 
            stad varchar, 
            stad_dlpt_ref_compnr integer, 
            sups integer, 
            sups_kw varchar, 
            tact varchar, 
            tcco varchar, 
            tcco_ref_compnr integer, 
            timestamp datetime, 
            tprj varchar, 
            tprj_ref_compnr integer, 
            tspa varchar, 
            tstl varchar, 
            txtn integer, 
            txtn_ref_compnr integer, 
            ubin integer, 
            ubin_kw varchar, 
            username varchar, 
            uwop integer, 
            uwop_kw varchar, 
            wmss integer, 
            wmss_kw varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 