CREATE OR REPLACE TABLE TARGET_LN.LN_WHINA127(
            amnt_1 numeric(38, 17), 
            amnt_2 numeric(38, 17), 
            amnt_3 numeric(38, 17), 
            compnr integer, 
            cpcp varchar, 
            cpcp_ref_compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            hour numeric(38, 17), 
            inwp integer, 
            inwp_kw varchar, 
            item varchar, 
            item_cwar_trdt_seqn_inwp_vpdt_vseq_ref_compnr integer, 
            item_ref_compnr integer, 
            seqn integer, 
            sequencenumber integer, 
            timestamp datetime, 
            trdt datetime, 
            username varchar, 
            vpdt datetime, 
            vseq integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 