CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_ASSETVALUATION_ASSVALUE(
            ACCDEPREC numeric(38, 10), 
            ACQDATE datetime, 
            ACQTYPE varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSVALKEY integer, 
            BGTKEY integer, 
            BGTKEY2 integer, 
            BGTKEY3 integer, 
            BGTNO varchar, 
            BOOKID varchar, 
            CAPTLDATE datetime, 
            CAPTLEXP numeric(38, 10), 
            CATEGORY varchar, 
            CLASS varchar, 
            COMPKEY integer, 
            COMPTYPE integer, 
            DATALAKE_DELETED boolean, 
            DEPRECRATE numeric(38, 10), 
            DEPRECTYPE integer, 
            DEPRECYTD numeric(38, 10), 
            DEPRESIDLF numeric(38, 10), 
            DISJOURNALDATE datetime, 
            DISPBGTKEY integer, 
            DISPBGTNO varchar, 
            DISPDATE datetime, 
            DISPDESC varchar, 
            DISPVAL numeric(38, 10), 
            EXPLIFE numeric(38, 10), 
            INITCOST numeric(38, 10), 
            INSUREVAL numeric(38, 10), 
            ISDISPOSED varchar, 
            LINEARFROMFT numeric(38, 10), 
            LINEARFROMM numeric(38, 10), 
            LINEARTOFT numeric(38, 10), 
            LINEARTOM numeric(38, 10), 
            MAINTEXP numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            PROFITLOSS numeric(38, 10), 
            RESIDLIFE numeric(38, 10), 
            RESIDVAL numeric(38, 10), 
            REVALAMT numeric(38, 10), 
            RWATTRKEY integer, 
            RWATTRTYPE varchar, 
            TAXVAL numeric(38, 10), 
            TOBESOLDDATE datetime, 
            TOBESOLDDESC varchar, 
            VALDATE datetime, 
            VARIATION_ID integer, 
            WRITEDNVAL numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 