CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_METERMANAGEMENT_WATER_READINGEXPORTMETERDETAIL(
            ACCOUNTNUMBER varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESS varchar, 
            COMPKEY integer, 
            DELETED boolean, 
            EXCEPTIONEXPORTDATE datetime, 
            EXCEPTIONFILENAME varchar, 
            EXPORTTYPEEXCEPTION integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            POSITION integer, 
            READINGEXPORTMETERDTLKEY integer, 
            READINGEXPORTROUTEDTLKEY integer, 
            ROUTEKEY integer, 
            SEQUENCENUMBER integer, 
            STATUS integer, 
            UNHANDLEDEXCEPDESC varchar, 
            USEREXCEPTIONKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 