CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_ADJUSTMENT(
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADJTYPESUKEY integer, 
            ADJUSTEDBY varchar, 
            ADJUSTMENTDTTM datetime, 
            ADJUSTMENTKEY integer, 
            ADJUSTMENTREASON varchar, 
            ADJUSTMENTSCOUNT integer, 
            AMOUNT numeric(38, 10), 
            APPROVALAMOUNT numeric(38, 10), 
            APPROVALLEVEL integer, 
            BILLTYPEKEY integer, 
            COMMENTSKEY integer, 
            DELETED boolean, 
            FULLYPAIDSTAT varchar, 
            LINEITEMKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            PARENTADJUSTMENTKEY integer, 
            PENALTYKEY integer, 
            PRIORITY varchar, 
            PROPERTYBASEDFLAG varchar, 
            STATUS varchar, 
            STATUSBY varchar, 
            STATUSDATE datetime, 
            TRANSACTIONDESIGNATOR integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 