CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_FEETYPE(
            ACCTPREFIX varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ATCOSTUSEDFOR integer, 
            AUTOPAY varchar, 
            CDRPRODUCTFAMILY integer, 
            DELETED boolean, 
            DESTBGTNOKEY integer, 
            DPDESC varchar, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            FEECLASS integer, 
            FEECODE varchar, 
            FEEDESC varchar, 
            FEEGROUP varchar, 
            FEETYPEKEY integer, 
            INITIALDEPFEETYPEKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            ORDERING integer, 
            PAYMENTMETHODFLAG integer, 
            PAYORD integer, 
            PORTALDESCRIPTION varchar, 
            REFUNDABLE varchar, 
            SRCBGTNOKEY integer, 
            SURC varchar, 
            USEINJOBESTIMATION varchar, 
            VARIATION_ID integer, 
            VERSIONDATEBIND varchar, 
            VERSIONDATEMONIKER varchar, 
            WAIVABLE varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 