CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_BUILDING_BLDGCOND(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APBLDGCONDKEY integer, 
            APBLDGCONDTYPEKEY integer, 
            APBLDGKEY integer, 
            APPLDBY varchar, 
            APPLDDTTM datetime, 
            APRV varchar, 
            APRVBY varchar, 
            APRVDTTM datetime, 
            APRVED varchar, 
            ASSIGNED varchar, 
            CMPTRGEN varchar, 
            DELETED boolean, 
            MODBY varchar, 
            MODDTTM datetime, 
            SUPREQD varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 