CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPROJ_XPROJCOMPRVWPRECONDP(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPROJREVDTLKEY integer, 
            DELETED boolean, 
            ENGAUDITREQ varchar, 
            ENGAUDITREQREASON varchar, 
            ENGEPAASSESS varchar, 
            ENGFINALWALKOVER varchar, 
            ENGFINALWALKOVERREASON varchar, 
            ENGPRECONONSITE varchar, 
            ENGPRECONONSITEREASON varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            ONSITEMEETACTUALDATE datetime, 
            ONSITEMEETSCHEDDATE datetime, 
            PASSTOADVISOR varchar, 
            PASSTOTECHNICIAN varchar, 
            TECHAUDITREQ varchar, 
            TECHAUDITREQREASON varchar, 
            TECHFINALWALKOVER varchar, 
            TECHFINALWALKOVERREASON varchar, 
            TECHPRECONONSITE varchar, 
            TECHPRECONONSITEREASON varchar, 
            VARIATION_ID integer, 
            WASTEWATERCONNECTIONTYPE varchar, 
            XPROJCOMPRVWPRECONDPKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 