CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PLANNING_PLANPLCONDINHERITRULE(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLANPLCONDINHERITRULEKEY integer, 
            BLDGINHERITFRMLAKEY integer, 
            CDSYSTEMAPPLTYPE integer, 
            DATALAKE_DELETED boolean, 
            INHERITFRMLA integer, 
            INHERITRULETYPE integer, 
            INHERITTITLE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PLANINHERITFRMLAKEY integer, 
            PROJINHERITFRMLAKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 