CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_EMPLOYEE(
            ADDBY varchar, 
            ADDDTTM datetime, 
            BNFTRATE numeric(38, 10), 
            BUDGETKEY integer, 
            CONTACTKEY integer, 
            CREWLDR varchar, 
            DELETED boolean, 
            DEPT varchar, 
            EMERGINFO varchar, 
            EMERGNAME1 varchar, 
            EMERGNAME2 varchar, 
            EMERGNAME3 varchar, 
            EMERGPHN1 varchar, 
            EMERGPHN2 varchar, 
            EMERGPHN3 varchar, 
            EMERGREL1 varchar, 
            EMERGREL2 varchar, 
            EMERGREL3 varchar, 
            EMPID varchar, 
            EXPDATE datetime, 
            HIREDATE datetime, 
            INSPFLAG varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PINAUTHCODE varchar, 
            RATE numeric(38, 10), 
            SECT varchar, 
            SUPR varchar, 
            SUPRFLAG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 