CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_METERMANAGEMENT_WATER_CYCLEROUTEAVGCONSUMPTIONRUN(
            ACCOUNTCLASS varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            CYCLEROUTEAVGCONSKEY integer, 
            DELETED boolean, 
            MODBY varchar, 
            MODDTTM datetime, 
            PERIODFROM datetime, 
            PERIODTO datetime, 
            PROCESSINGFLAG varchar, 
            READINGCYCLE varchar, 
            SCHEDULEKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 