CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_PAYMENTREVERSALREASON(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ALERTDAYS integer, 
            ALERTDEFINITIONKEY integer, 
            BACKCOLOR integer, 
            CODE varchar, 
            CREDITRATINGPOINTSCODE varchar, 
            DELETED boolean, 
            DESCRIPT varchar, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            FORTRANSFERPAYMENTFLAG varchar, 
            LOGTYPE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NSFDEFAULTFLAG varchar, 
            NSFEXCEPTIONFLAG varchar, 
            NSFTYPEFLAG varchar, 
            OVERRIDENSFFEEFLAG varchar, 
            SENDNOTICEFLAG varchar, 
            TEXTCOLOR integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 