CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLBILLING_LOADPAYMENT(
            ACCOUNTNUMBER varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            AMOUNT numeric(38, 10), 
            BATCHKEY integer, 
            DELETED boolean, 
            FILEEXTENSION varchar, 
            FILENAME varchar, 
            LOADPAYMENTKEY integer, 
            METHOD varchar, 
            MISCREFNO varchar, 
            MISCTYPE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            OTHER1 varchar, 
            OTHER2 varchar, 
            OTHER3 varchar, 
            PAYMENTDATE varchar, 
            RECORDCOUNT integer, 
            RECORDTYPE varchar, 
            SOURCETYPE varchar, 
            STATUS varchar, 
            STATUSMESG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 