CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_RATETABLE_RATETBL(
            ADDBY varchar, 
            ADDDTTM datetime, 
            CYCLEDAYS integer, 
            DELETED boolean, 
            EFFDATE datetime, 
            FINALCYCLEDAYS integer, 
            FORMULA integer, 
            FORMULALAST varchar, 
            ISPRORATED varchar, 
            MAXIMUMCHARGE numeric(38, 10), 
            MINIMUMCHARGE numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            NEWEFFECTIVEDATE datetime, 
            NUMBEROFDECIMALS integer, 
            PERCENTINCREASE numeric(38, 10), 
            RATECODEKEY integer, 
            RATETBLKEY integer, 
            USEFORPRORATING integer, 
            USEOVERAGE varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 