CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_WATER_COMPWMC(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            BGTNO varchar, 
            BUDGETKEY integer, 
            COMPKEY integer, 
            COMPONENT integer, 
            DATALAKE_DELETED boolean, 
            DISTRICT varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            GISSTATIC integer, 
            INSTDATE datetime, 
            LOC varchar, 
            MAPNO varchar, 
            MFGDATE datetime, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            OWN varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PURCDATE datetime, 
            SERNO varchar, 
            SERVSTAT varchar, 
            SUBAREA varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            VARIATION_ID integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 