CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_DELINQUENCYRUN(
            ACCOUNTAREA varchar, 
            ACCOUNTBILLINGCYCLE varchar, 
            ACCOUNTCLASS varchar, 
            ACCOUNTGROUP varchar, 
            ACCOUNTSUBGROUP varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            AUTODECANDRESOLVEFLAG varchar, 
            BILLTYPEKEY integer, 
            COMMITNUMBER integer, 
            DELETED boolean, 
            DELINQUENCYPROCESSTYPE varchar, 
            DELINQUENCYRUNKEY integer, 
            ENDADVANCEMENTRUN datetime, 
            ENDENTRYRUN datetime, 
            INITIATEDBY varchar, 
            INITIATEDTTM datetime, 
            LASTINVOCATIONSTATUS integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NUMBEROFADVANCEDACCOUNTS integer, 
            NUMBEROFENTRYACCOUNTS integer, 
            NUMBEROFEXCEPTIONS integer, 
            PROCESSINGFLAG varchar, 
            SCHEDULEKEY integer, 
            STARTADVANCEMENTRUN datetime, 
            STARTENTRYRUN datetime, 
            TOTALNUMBEROFACCOUNTS integer, 
            VARIATION_ID integer, 
            WATERMETERADDRESSROUTEKEY integer, 
            WATERMETERREADINGCYCLE varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 