CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_BUILDING_BLDGLOG(
            ADDBY varchar, 
            ADDBYPORTALUSR varchar, 
            ADDDTTM datetime, 
            APBLDGINSPKEY integer, 
            APBLDGKEY integer, 
            APBLDGLOGKEY integer, 
            APBLDGREVIEWKEY integer, 
            DATALAKE_DELETED boolean, 
            LOGTYPE varchar, 
            MODBY varchar, 
            MODBYPORTALUSR varchar, 
            MODDTTM datetime, 
            STARTBY varchar, 
            STARTDTTM datetime, 
            STOPBY varchar, 
            STOPDTTM datetime, 
            TOTALTIME numeric(38, 10), 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 