CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_JOURNAL(
            ACCOUNTINGPERIOD integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            AMOUNT numeric(38, 10), 
            CREDITBUDGETNUMBERKEY integer, 
            DEBITBUDGETNUMBERKEY integer, 
            DELETED boolean, 
            DESCRIPTION varchar, 
            FISCALYEAR integer, 
            JOURNALKEY integer, 
            JOURNALRUNKEY integer, 
            JOURNALSUMMARYKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MULTIDISTRIBUTIOLNALFLAG varchar, 
            ORIGIN varchar, 
            TAXINCLUSIVEFLAG varchar, 
            TRANSACTIONBY varchar, 
            TRANSACTIONDTTM datetime, 
            TRANSACTIONNUMBER integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 