CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_ASSETVALUATION_ASSVALRUNLINKWO(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSVALKEY integer, 
            ASSVALRUNKEY integer, 
            COMPLETEDDATETIME datetime, 
            DATALAKE_DELETED boolean, 
            HISTKEY integer, 
            ISADJUSTMENT varchar, 
            LINKASSVALWOKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            TOTCOST numeric(38, 10), 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 