CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDR_CDRBILLOUTPUTLINEITEMEX(
            ACCOUNTKEY integer, 
            ACCOUNTNUMBER varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BILLKEY integer, 
            BILLRUNNUMBER integer, 
            CDRBILLOUTPUTLINEITEMEXKEY integer, 
            DATALAKE_DELETED boolean, 
            FEECODE varchar, 
            FEEDESC varchar, 
            FEEREFERENCE varchar, 
            FEETYPEKEY integer, 
            LINEITEM varchar, 
            LINEITEMDESC varchar, 
            LINEITEMKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            QTY numeric(38, 10), 
            TOTALAMOUNT numeric(38, 10), 
            VALUE numeric(38, 10), 
            VARIATION_ID integer, 
            WAIVED varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 