CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PROJECT_PROJCOND(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLDBY varchar, 
            APPLDDTTM datetime, 
            APPROJCONDKEY integer, 
            APPROJCONDTYPEKEY integer, 
            APPROJKEY integer, 
            APRV varchar, 
            APRVBY varchar, 
            APRVDTTM datetime, 
            APRVED varchar, 
            ASSIGNED varchar, 
            CMPTRGEN varchar, 
            DELETED boolean, 
            MODBY varchar, 
            MODDTTM datetime, 
            SUPREQD varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 