CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CASHIERING_REGISTERTRANSACTION(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSOCIATEDEMPLOYEE varchar, 
            CLEANUPSESSIONID varchar, 
            CONTACT integer, 
            DELETED boolean, 
            DRWRKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            RECEIPTNUMBER varchar, 
            REFTRANNO integer, 
            REGKEY integer, 
            REGTRANNO integer, 
            STATUS varchar, 
            TRANAMT numeric(38, 10), 
            TRANBY varchar, 
            TRANDTTM datetime, 
            TRANPAYER varchar, 
            TRANTYPE varchar, 
            VARIATION_ID integer, 
            VOIDBY varchar, 
            VOIDDTTM datetime, 
            VOIDREAS varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 