CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XAPPLICANTDP(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDR1 varchar, 
            APBLDGAPPLDTLKEY integer, 
            CAPACITY varchar, 
            CITY varchar, 
            CONAME varchar, 
            DATALAKE_DELETED boolean, 
            EMAIL varchar, 
            FIRSTNAME varchar, 
            LASTNAME varchar, 
            MOBILE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            ONSITEADDRESSLINE1 varchar, 
            ONSITECITY varchar, 
            ONSITECOMPANYNAME varchar, 
            ONSITEEMAILADDRESS varchar, 
            ONSITEFIRSTNAME varchar, 
            ONSITELASTNAME varchar, 
            ONSITEMOBILE varchar, 
            ONSITEPHONENUMBER varchar, 
            ONSITEPOSTALCODE varchar, 
            ONSITESUBURB varchar, 
            ONSITETITLE varchar, 
            PHONENUMBER varchar, 
            SUBURB varchar, 
            TITLE varchar, 
            VARIATION_ID integer, 
            XAPPLICANTDPKEY integer, 
            ZIP varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 