CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PLANNING_PLANPLCOND(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLANKEY integer, 
            APPLANPLCONDKEY integer, 
            APPLANSTATUSKEY integer, 
            AUTOSTATUSFRMKEY integer, 
            BLDGAUTOSTATUSFRMKEY integer, 
            CONDTEXTCHANGED varchar, 
            CONDTITLE varchar, 
            CONDTYPE integer, 
            DEFFERREDMILESTONE integer, 
            DELETED boolean, 
            DEPARTMENT varchar, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            INHERITRULEKEY integer, 
            MILESTONEDATE datetime, 
            MILESTONERULE integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            ORIGINAPKEY integer, 
            ORIGINCDRTYPE integer, 
            PARENTAPKEY integer, 
            PARENTCDRTYPE integer, 
            PLANAUTOSTATUSFRMKEY integer, 
            PLANCONDNO integer, 
            PLCONDTYPE integer, 
            PROJAUTOSTATUSFRMKEY integer, 
            STATUSBY varchar, 
            STATUSDATE datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 