CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_RATETABLE_RATETABLEDETAIL(
            ADDBY varchar, 
            ADDDTTM datetime, 
            BRANCHKEY integer, 
            CONVERSIONFACTOR numeric(38, 10), 
            CYCLEDAYS integer, 
            DELETED boolean, 
            EFFECTIVEDATE datetime, 
            EFFECTIVETODATE datetime, 
            FINALCYCLEDAYS integer, 
            FORMULAKEY integer, 
            ISRATECHANGEPRORATIONDISABLED varchar, 
            MAXIMUMCHARGE numeric(38, 10), 
            MINIMUMCHARGE numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            MONIKER varchar, 
            NODENAME varchar, 
            NODESOURCE varchar, 
            NUMBEROFSTEPS integer, 
            PARENTVALUE integer, 
            PRORATEBASEFLAG varchar, 
            PRORATECYCLEBILLS varchar, 
            PRORATESTEPSFLAG varchar, 
            RANGEVALUE varchar, 
            RATEFORSTEP1 numeric(38, 10), 
            RATEFORSTEP10 numeric(38, 10), 
            RATEFORSTEP2 numeric(38, 10), 
            RATEFORSTEP3 numeric(38, 10), 
            RATEFORSTEP4 numeric(38, 10), 
            RATEFORSTEP5 numeric(38, 10), 
            RATEFORSTEP6 numeric(38, 10), 
            RATEFORSTEP7 numeric(38, 10), 
            RATEFORSTEP8 numeric(38, 10), 
            RATEFORSTEP9 numeric(38, 10), 
            RATEPERUNIT integer, 
            RATESTEP1 numeric(38, 10), 
            RATESTEP10 numeric(38, 10), 
            RATESTEP2 numeric(38, 10), 
            RATESTEP3 numeric(38, 10), 
            RATESTEP4 numeric(38, 10), 
            RATESTEP5 numeric(38, 10), 
            RATESTEP6 numeric(38, 10), 
            RATESTEP7 numeric(38, 10), 
            RATESTEP8 numeric(38, 10), 
            RATESTEP9 numeric(38, 10), 
            RATETABLEDETAILKEY integer, 
            RATETABLESETUPKEY integer, 
            RATETYPE integer, 
            RECURRINGFLAG varchar, 
            ROUNDPRORATESTEPS varchar, 
            ROUNDUP varchar, 
            SORTORDER integer, 
            UOM varchar, 
            USEFORPRORATING integer, 
            USEOVERAGE varchar, 
            VALUE numeric(38, 10), 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 