create or replace TABLE DIM_BILL_TYPE (
	BILL_TYPE_SID NUMBER(38,0) NOT NULL autoincrement,
	BILL_TYPE_KEY NUMBER(38,0),
	BILL_TYPE VARCHAR(8),
	BILL_TYPE_DESCRIPTION VARCHAR(30),
	ETL_SOURCE_DATETIME TIMESTAMP_NTZ(9),
	ETL_RECORD_CREATED TIMESTAMP_NTZ(9),
	ETL_RECORD_UPDATED TIMESTAMP_NTZ(9),
	primary key (BILL_TYPE_SID)
);