<<<<<<< HEAD
CREATE OR REPLACE PROCEDURE "ICARE_LOAD_ALL_TABLES"()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
<<<<<<< HEAD
AS '

var result = "";

snowflake.execute( {sqlText: "begin transaction;"} );

try {



snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ICARE_ACTIONS_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ICARE_ACTIONS_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ICARE_CASES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ICARE_CASES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ILLNESSES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ILLNESSES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_INJURIES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_INJURIES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_CLOSE_CALL_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_CLOSE_CALL_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_GENERAL_WORKPLACE_INSPECTION_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_GENERAL_WORKPLACE_INSPECTION_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_HAZARD_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_HAZARD_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_MEDICAL_APPOINTMENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_MEDICAL_APPOINTMENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_PAIN_OR_DISCOMFORT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_PAIN_OR_DISCOMFORT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_PERMIT_AUDIT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_PERMIT_AUDIT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_SITE_WALK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_SITE_WALK_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_WELLBEING_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_WELLBEING_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_WORKSAFE_ENGAGEMENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_WORKSAFE_ENGAGEMENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_EVENT_LOCATION_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_EVENT_LOCATION_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_INCIDENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_INCIDENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SN_HR_CORE_PROFILE_RESPONSE_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SN_HR_CORE_PROFILE_RESPONSE_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SYS_USER_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SYS_USER_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SYS_USER_GROUP_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SYS_USER_GROUP_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_TASK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_TASK_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_CONTRACTOR_STATISTIC SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_CONTRACTOR_STATISTIC_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_EMERGENCY_DRILL_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_EMERGENCY_DRILL_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_FEEDBACK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_FEEDBACK_API_JSON;

;`

} );



snowflake.execute( {sqlText: "commit;"} );

result = "Succeeded";

}

catch (err) {

snowflake.execute( {sqlText: "rollback;"} );

return "Failed: " + err; // Return a success/error indicator.

}

return result;

=======
CREATE OR REPLACE PROCEDURE "ICARE_LOAD_ALL_TABLES"()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '

var result = "";

snowflake.execute( {sqlText: "begin transaction;"} );

try {



snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ICARE_ACTIONS_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ICARE_ACTIONS_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ICARE_CASES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ICARE_CASES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ILLNESSES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ILLNESSES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_INJURIES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_INJURIES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_CLOSE_CALL_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_CLOSE_CALL_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_GENERAL_WORKPLACE_INSPECTION_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_GENERAL_WORKPLACE_INSPECTION_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_HAZARD_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_HAZARD_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_MEDICAL_APPOINTMENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_MEDICAL_APPOINTMENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_PAIN_OR_DISCOMFORT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_PAIN_OR_DISCOMFORT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_PERMIT_AUDIT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_PERMIT_AUDIT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_SITE_WALK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_SITE_WALK_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_WELLBEING_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_WELLBEING_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_WORKSAFE_ENGAGEMENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_WORKSAFE_ENGAGEMENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_EVENT_LOCATION_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_EVENT_LOCATION_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_INCIDENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_INCIDENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SN_HR_CORE_PROFILE_RESPONSE_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SN_HR_CORE_PROFILE_RESPONSE_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SYS_USER_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SYS_USER_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SYS_USER_GROUP_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SYS_USER_GROUP_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_TASK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_TASK_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_CONTRACTOR_STATISTIC SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_CONTRACTOR_STATISTIC_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_EMERGENCY_DRILL_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_EMERGENCY_DRILL_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_FEEDBACK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_FEEDBACK_API_JSON;

;`

} );



snowflake.execute( {sqlText: "commit;"} );

result = "Succeeded";

}

catch (err) {

snowflake.execute( {sqlText: "rollback;"} );

return "Failed: " + err; // Return a success/error indicator.

}

return result;

>>>>>>> master
=======
AS '

var result = "";

snowflake.execute( {sqlText: "begin transaction;"} );

try {



snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ICARE_ACTIONS_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ICARE_ACTIONS_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ICARE_CASES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ICARE_CASES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_ILLNESSES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_ILLNESSES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_ALL_INJURIES_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_ALL_INJURIES_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_CLOSE_CALL_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_CLOSE_CALL_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_GENERAL_WORKPLACE_INSPECTION_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_GENERAL_WORKPLACE_INSPECTION_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_HAZARD_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_HAZARD_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_MEDICAL_APPOINTMENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_MEDICAL_APPOINTMENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_PAIN_OR_DISCOMFORT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_PAIN_OR_DISCOMFORT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_PERMIT_AUDIT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_PERMIT_AUDIT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_SITE_WALK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_SITE_WALK_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_WELLBEING_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_WELLBEING_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_WORKSAFE_ENGAGEMENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_WORKSAFE_ENGAGEMENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_EVENT_LOCATION_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_EVENT_LOCATION_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_INCIDENT_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_INCIDENT_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SN_HR_CORE_PROFILE_RESPONSE_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SN_HR_CORE_PROFILE_RESPONSE_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SYS_USER_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SYS_USER_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_SYS_USER_GROUP_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_SYS_USER_GROUP_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_TASK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_TASK_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_CONTRACTOR_STATISTIC SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_CONTRACTOR_STATISTIC_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_EMERGENCY_DRILL_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_EMERGENCY_DRILL_API_JSON;

;`

} );

snowflake.execute( {sqlText:

` INSERT INTO TARGET_ICARE.ICARE_CASE_FEEDBACK_API SELECT *,current_timestamp() AS ETL_LOAD_DATETIME FROM DATAHUB_LANDING.vw_ICARE_CASE_FEEDBACK_API_JSON;

;`

} );



snowflake.execute( {sqlText: "commit;"} );

result = "Succeeded";

}

catch (err) {

snowflake.execute( {sqlText: "rollback;"} );

return "Failed: " + err; // Return a success/error indicator.

}

return result;

>>>>>>> 0bb0bb681d733ad3feed422102d26c2339b0cce7
';