CREATE OR REPLACE TABLE DATAHUB_TARGET.EAM_R5MAILEVENTS(
                        MAE_CODE varchar(30),
                        MAE_TEMPLATE varchar(18),
                        MAE_DATE datetime(0),
                        MAE_SEND varchar(1),
                        MAE_RSTATUS varchar(4),
                        MAE_ERROR varchar(255),
                        MAE_PARAM1 varchar(4000),
                        MAE_PARAM2 varchar(4000),
                        MAE_PARAM3 varchar(4000),
                        MAE_PARAM4 varchar(4000),
                        MAE_PARAM5 varchar(4000),
                        MAE_PARAM6 varchar(4000),
                        MAE_PARAM7 varchar(4000),
                        MAE_PARAM8 varchar(4000),
                        MAE_PARAM9 varchar(4000),
                        MAE_PARAM10 varchar(4000),
                        MAE_PARAM11 varchar(4000),
                        MAE_PARAM12 varchar(4000),
                        MAE_PARAM13 varchar(4000),
                        MAE_PARAM14 varchar(4000),
                        MAE_PARAM15 varchar(4000),
                        MAE_UPDATECOUNT numeric(38, 0),
                        MAE_ATTRIBPK varchar(30),
                        MAE_EWSURL varchar(255),
                        MAE_EMAILRECIPIENT varchar(1000),
                        MAE_PTFSEND varchar(1),
                        MAE_PTFERROR varchar(255),
                        MAE_DOCRENTITY varchar(4),
                        MAE_DOCPK varchar(100),
                        MAE_EMAILERRCOUNT numeric(10, 0),
                        MAE_PTFERRCOUNT numeric(10, 0),
                        MAE_LASTSAVED datetime(0)
                        ,etl_load_datetime timestamp,
                          etl_load_metadatafilename varchar(255),
                           ETL_LASTSAVED datetime(0),
			ETL_DELETED boolean
                    );