-- DATAHUB_STAGING.STG90_IPS_SM_BILLING_EXTRACT definition

create or replace TABLE DATAHUB_STAGING.STG90_IPS_SM_BILLING_EXTRACT (
	ROUTE VARCHAR(16),
	READING_DATE DATE,
	METER VARCHAR(50),
	REGISTER_NUMBER NUMBER(1,0),
	READING FLOAT,
	READ_TYPE VARCHAR(1),
	REASON_UNREAD VARCHAR(10),
	READER VARCHAR(10),
	NOTES VARCHAR(300),
	READING_TYPE VARCHAR(8)
);