CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5DOCKLINES(
            DKL_ACD numeric(38, 10), 
            DKL_BIN varchar, 
            DKL_CLASS varchar, 
            DKL_CLASS_ORG varchar, 
            DKL_COUNTED varchar, 
            DKL_COUNTQTY numeric(38, 10), 
            DKL_DCKCODE varchar, 
            DKL_DIRECT varchar, 
            DKL_INSPDATE datetime, 
            DKL_INSPECT varchar, 
            DKL_INSPECTEDQTY numeric(38, 10), 
            DKL_INSPECTOR varchar, 
            DKL_INSPREJQTY numeric(38, 10), 
            DKL_INSPRSTATUS varchar, 
            DKL_INSPSTATUS varchar, 
            DKL_LASTSAVED datetime, 
            DKL_LINE numeric(38, 10), 
            DKL_LINERSTATUS varchar, 
            DKL_LINESTATUS varchar, 
            DKL_LOCATION varchar, 
            DKL_LOT varchar, 
            DKL_MANLOT varchar, 
            DKL_MANLOTEXP datetime, 
            DKL_MANUFACTPART varchar, 
            DKL_MANUFACTURER varchar, 
            DKL_MOBILEDATEUPDATED datetime, 
            DKL_MRC varchar, 
            DKL_OBJECT varchar, 
            DKL_OBJECT_ORG varchar, 
            DKL_OBRTYPE varchar, 
            DKL_OBTYPE varchar, 
            DKL_ORDER varchar, 
            DKL_ORDER_ORG varchar, 
            DKL_ORDLINE numeric(38, 10), 
            DKL_PART varchar, 
            DKL_PART_ORG varchar, 
            DKL_PERSON varchar, 
            DKL_PRINT numeric(38, 10), 
            DKL_RECVCODE varchar, 
            DKL_RECVQTY numeric(38, 10), 
            DKL_REJREASON varchar, 
            DKL_REPAIRCONDITION varchar, 
            DKL_REPAIRPRICE numeric(38, 10), 
            DKL_RETNCODE varchar, 
            DKL_RETNQTY numeric(38, 10), 
            DKL_SCRAPQTY numeric(38, 10), 
            DKL_SERIAL varchar, 
            DKL_UDFCHAR01 varchar, 
            DKL_UDFCHAR02 varchar, 
            DKL_UDFCHAR03 varchar, 
            DKL_UDFCHAR04 varchar, 
            DKL_UDFCHAR05 varchar, 
            DKL_UDFCHAR06 varchar, 
            DKL_UDFCHAR07 varchar, 
            DKL_UDFCHAR08 varchar, 
            DKL_UDFCHAR09 varchar, 
            DKL_UDFCHAR10 varchar, 
            DKL_UDFCHAR11 varchar, 
            DKL_UDFCHAR12 varchar, 
            DKL_UDFCHAR13 varchar, 
            DKL_UDFCHAR14 varchar, 
            DKL_UDFCHAR15 varchar, 
            DKL_UDFCHAR16 varchar, 
            DKL_UDFCHAR17 varchar, 
            DKL_UDFCHAR18 varchar, 
            DKL_UDFCHAR19 varchar, 
            DKL_UDFCHAR20 varchar, 
            DKL_UDFCHAR21 varchar, 
            DKL_UDFCHAR22 varchar, 
            DKL_UDFCHAR23 varchar, 
            DKL_UDFCHAR24 varchar, 
            DKL_UDFCHAR25 varchar, 
            DKL_UDFCHAR26 varchar, 
            DKL_UDFCHAR27 varchar, 
            DKL_UDFCHAR28 varchar, 
            DKL_UDFCHAR29 varchar, 
            DKL_UDFCHAR30 varchar, 
            DKL_UDFCHKBOX01 varchar, 
            DKL_UDFCHKBOX02 varchar, 
            DKL_UDFCHKBOX03 varchar, 
            DKL_UDFCHKBOX04 varchar, 
            DKL_UDFCHKBOX05 varchar, 
            DKL_UDFDATE01 datetime, 
            DKL_UDFDATE02 datetime, 
            DKL_UDFDATE03 datetime, 
            DKL_UDFDATE04 datetime, 
            DKL_UDFDATE05 datetime, 
            DKL_UDFNUM01 numeric(38, 10), 
            DKL_UDFNUM02 numeric(38, 10), 
            DKL_UDFNUM03 numeric(38, 10), 
            DKL_UDFNUM04 numeric(38, 10), 
            DKL_UDFNUM05 numeric(38, 10), 
            DKL_UPDATECOUNT numeric(38, 10), 
            DKL_UPDATED datetime, 
            DKL_UPDUSER varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 