CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5ADJUSTMENTS(
            ADJ_CODE varchar, 
            ADJ_DESC varchar, 
            ADJ_LASTSAVED datetime, 
            ADJ_NOTUSED varchar, 
            ADJ_ORG varchar, 
            ADJ_RATE numeric(38, 10), 
            ADJ_STWO varchar, 
            ADJ_UDFCHAR01 varchar, 
            ADJ_UDFCHAR02 varchar, 
            ADJ_UDFCHAR03 varchar, 
            ADJ_UDFCHAR04 varchar, 
            ADJ_UDFCHAR05 varchar, 
            ADJ_UDFCHAR06 varchar, 
            ADJ_UDFCHAR07 varchar, 
            ADJ_UDFCHAR08 varchar, 
            ADJ_UDFCHAR09 varchar, 
            ADJ_UDFCHAR10 varchar, 
            ADJ_UDFCHAR11 varchar, 
            ADJ_UDFCHAR12 varchar, 
            ADJ_UDFCHAR13 varchar, 
            ADJ_UDFCHAR14 varchar, 
            ADJ_UDFCHAR15 varchar, 
            ADJ_UDFCHAR16 varchar, 
            ADJ_UDFCHAR17 varchar, 
            ADJ_UDFCHAR18 varchar, 
            ADJ_UDFCHAR19 varchar, 
            ADJ_UDFCHAR20 varchar, 
            ADJ_UDFCHAR21 varchar, 
            ADJ_UDFCHAR22 varchar, 
            ADJ_UDFCHAR23 varchar, 
            ADJ_UDFCHAR24 varchar, 
            ADJ_UDFCHAR25 varchar, 
            ADJ_UDFCHAR26 varchar, 
            ADJ_UDFCHAR27 varchar, 
            ADJ_UDFCHAR28 varchar, 
            ADJ_UDFCHAR29 varchar, 
            ADJ_UDFCHAR30 varchar, 
            ADJ_UDFCHKBOX01 varchar, 
            ADJ_UDFCHKBOX02 varchar, 
            ADJ_UDFCHKBOX03 varchar, 
            ADJ_UDFCHKBOX04 varchar, 
            ADJ_UDFCHKBOX05 varchar, 
            ADJ_UDFDATE01 datetime, 
            ADJ_UDFDATE02 datetime, 
            ADJ_UDFDATE03 datetime, 
            ADJ_UDFDATE04 datetime, 
            ADJ_UDFDATE05 datetime, 
            ADJ_UDFNUM01 numeric(38, 10), 
            ADJ_UDFNUM02 numeric(38, 10), 
            ADJ_UDFNUM03 numeric(38, 10), 
            ADJ_UDFNUM04 numeric(38, 10), 
            ADJ_UDFNUM05 numeric(38, 10), 
            ADJ_UPDATECOUNT numeric(38, 10), 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 