CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5ENTITYPARTS(
            EPA_ASMLEVEL varchar, 
            EPA_CODE varchar, 
            EPA_COMMENT varchar, 
            EPA_COMPLEVEL varchar, 
            EPA_ENTITY varchar, 
            EPA_LASTSAVED datetime, 
            EPA_PART varchar, 
            EPA_PARTLOCATION varchar, 
            EPA_PART_ORG varchar, 
            EPA_PK varchar, 
            EPA_QTY numeric(38, 10), 
            EPA_RENTITY varchar, 
            EPA_RTYPE varchar, 
            EPA_SYSLEVEL varchar, 
            EPA_TYPE varchar, 
            EPA_UOM varchar, 
            EPA_UPDATECOUNT numeric(38, 10), 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 