CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5ACTCHECKLISTS(
            ACK_ACT numeric(38, 10), 
            ACK_ADJUSTED varchar, 
            ACK_ASMLEVEL varchar, 
            ACK_ASPECT varchar, 
            ACK_CASETASK varchar, 
            ACK_CODE varchar, 
            ACK_COLOR varchar, 
            ACK_COMPLETED varchar, 
            ACK_COMPLEVEL varchar, 
            ACK_COMPLOCATION varchar, 
            ACK_CONDITION varchar, 
            ACK_CONDITION_AS_FOUND varchar, 
            ACK_DEFMAINT varchar, 
            ACK_DESC varchar, 
            ACK_DIRECTION varchar, 
            ACK_ENABLENONCONFORMITIES varchar, 
            ACK_ENTITYKEY varchar, 
            ACK_ENTITYORG varchar, 
            ACK_EVENT varchar, 
            ACK_FINALOCCURRENCE varchar, 
            ACK_FINDING varchar, 
            ACK_FOLLOWUP varchar, 
            ACK_FOLLOWUPACT numeric(38, 10), 
            ACK_FOLLOWUPEVENT varchar, 
            ACK_FORMULA varchar, 
            ACK_FROMGEOREF varchar, 
            ACK_FROMJOBPLAN varchar, 
            ACK_FROMJOBPLANREV numeric(38, 10), 
            ACK_FROMPOINT numeric(38, 10), 
            ACK_FROMREFDESC varchar, 
            ACK_FROM_HORIZONTAL_OFFSET numeric(38, 10), 
            ACK_FROM_HORIZONTAL_OFFSETTYPE varchar, 
            ACK_FROM_HORIZONTAL_OFFSETUOM varchar, 
            ACK_FROM_LATITUDE numeric(38, 10), 
            ACK_FROM_LONGITUDE numeric(38, 10), 
            ACK_FROM_OFFSET numeric(38, 10), 
            ACK_FROM_OFFSET_DIRECTION varchar, 
            ACK_FROM_OFFSET_PERCENTAGE numeric(38, 10), 
            ACK_FROM_REFERENCE numeric(38, 10), 
            ACK_FROM_RELATIONSHIP_TYPE varchar, 
            ACK_FROM_VERTICAL_OFFSET numeric(38, 10), 
            ACK_FROM_VERTICAL_OFFSETTYPE varchar, 
            ACK_FROM_VERTICAL_OFFSETUOM varchar, 
            ACK_FROM_XCOORDINATE numeric(38, 10), 
            ACK_FROM_YCOORDINATE numeric(38, 10), 
            ACK_GOOD varchar, 
            ACK_GROUP_LABEL varchar, 
            ACK_HIDEFOLLOWUP varchar, 
            ACK_HIDELINEARFIELDS varchar, 
            ACK_JOB varchar, 
            ACK_LASTSAVED datetime, 
            ACK_LOTO varchar, 
            ACK_MATLIST varchar, 
            ACK_MAXSLIDERVALUE numeric(38, 10), 
            ACK_MEASUREMENTRESP varchar, 
            ACK_METRICFRACTIONSLIDER varchar, 
            ACK_MINSLIDERVALUE numeric(38, 10), 
            ACK_MOBILEDATEUPDATED datetime, 
            ACK_NO varchar, 
            ACK_NONCONFORMITY varchar, 
            ACK_NONCONFORMITYFOUND varchar, 
            ACK_NONCONFORMITYTYPE varchar, 
            ACK_NONCONFORMITYTYPE_ORG varchar, 
            ACK_NOTES varchar, 
            ACK_NOT_APPLICABLE varchar, 
            ACK_OBJECT varchar, 
            ACK_OBJECTLEVEL varchar, 
            ACK_OBJECT_ORG varchar, 
            ACK_OCCURRENCE numeric(38, 10), 
            ACK_OK varchar, 
            ACK_PARENTKEY varchar, 
            ACK_PART varchar, 
            ACK_PARTCONDITION varchar, 
            ACK_PART_ORG varchar, 
            ACK_POINT varchar, 
            ACK_POINTTYPE varchar, 
            ACK_POOR varchar, 
            ACK_POSSIBLEFINDINGS varchar, 
            ACK_POSSIBLE_CONDS_AS_FOUND varchar, 
            ACK_POSSIBLE_DIRECTIONS varchar, 
            ACK_POSSIBLE_NA_OPTIONS varchar, 
            ACK_POSSIBLE_SEVERITIES varchar, 
            ACK_READING varchar, 
            ACK_REFERENCE varchar, 
            ACK_RELATIONSHIP_TYPE varchar, 
            ACK_RENTITY varchar, 
            ACK_REPAIRSNEEDED varchar, 
            ACK_REQUIREDTOCLOSE varchar, 
            ACK_RESOLUTION varchar, 
            ACK_RESPONSIBILITY varchar, 
            ACK_ROUTESEQUENCE numeric(38, 10), 
            ACK_SEQUENCE numeric(38, 10), 
            ACK_SEVERITY varchar, 
            ACK_SRCCALCULATEDVALUE varchar, 
            ACK_SYSLEVEL varchar, 
            ACK_TASK varchar, 
            ACK_TASKCHECKLISTCODE varchar, 
            ACK_TOGEOREF varchar, 
            ACK_TOLERANCECRNONCONFORMITY varchar, 
            ACK_TOLERANCESEVERITY varchar, 
            ACK_TOLERANCE_NCF_TYPE varchar, 
            ACK_TOLERANCE_NCF_TYPE_ORG varchar, 
            ACK_TOPOINT numeric(38, 10), 
            ACK_TOREFDESC varchar, 
            ACK_TO_HORIZONTAL_OFFSET numeric(38, 10), 
            ACK_TO_HORIZONTAL_OFFSETTYPE varchar, 
            ACK_TO_HORIZONTAL_OFFSETUOM varchar, 
            ACK_TO_LATITUDE numeric(38, 10), 
            ACK_TO_LONGITUDE numeric(38, 10), 
            ACK_TO_OFFSET numeric(38, 10), 
            ACK_TO_OFFSET_DIRECTION varchar, 
            ACK_TO_OFFSET_PERCENTAGE numeric(38, 10), 
            ACK_TO_REFERENCE numeric(38, 10), 
            ACK_TO_RELATIONSHIP_TYPE varchar, 
            ACK_TO_VERTICAL_OFFSET numeric(38, 10), 
            ACK_TO_VERTICAL_OFFSETTYPE varchar, 
            ACK_TO_VERTICAL_OFFSETUOM varchar, 
            ACK_TO_XCOORDINATE numeric(38, 10), 
            ACK_TO_YCOORDINATE numeric(38, 10), 
            ACK_TYPE varchar, 
            ACK_UOM varchar, 
            ACK_UPDATECOUNT numeric(38, 10), 
            ACK_UPDATED datetime, 
            ACK_UPDATEDBY varchar, 
            ACK_VALUE numeric(38, 10), 
            ACK_YES varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 