CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5HOME(
            HOM_CODE varchar, 
            HOM_CURVALUE numeric(38, 10), 
            HOM_DESC varchar, 
            HOM_ERROR varchar, 
            HOM_EWSDATASPYID numeric(38, 10), 
            HOM_EWSFUNCTION varchar, 
            HOM_FUNCTION varchar, 
            HOM_GEN varchar, 
            HOM_GROUPBYTEXT varchar, 
            HOM_HISTORY varchar, 
            HOM_KPITYPE varchar, 
            HOM_LASTSAVED datetime, 
            HOM_MAX numeric(38, 10), 
            HOM_MIN numeric(38, 10), 
            HOM_NORMSCORE numeric(38, 10), 
            HOM_NOTUSED varchar, 
            HOM_NXTUPDATE datetime, 
            HOM_OPERATOR varchar, 
            HOM_PARENT varchar, 
            HOM_RADIUSPERCENTAGE numeric(38, 10), 
            HOM_ROLLUPTYPE varchar, 
            HOM_SQLCODE varchar, 
            HOM_TYPE varchar, 
            HOM_UDFCHAR01 varchar, 
            HOM_UDFCHAR02 varchar, 
            HOM_UDFCHAR03 varchar, 
            HOM_UDFCHAR04 varchar, 
            HOM_UDFCHAR05 varchar, 
            HOM_UDFCHAR06 varchar, 
            HOM_UDFCHAR07 varchar, 
            HOM_UDFCHAR08 varchar, 
            HOM_UDFCHAR09 varchar, 
            HOM_UDFCHAR10 varchar, 
            HOM_UDFCHKBOX01 varchar, 
            HOM_UDFCHKBOX02 varchar, 
            HOM_UDFCHKBOX03 varchar, 
            HOM_UDFCHKBOX04 varchar, 
            HOM_UDFCHKBOX05 varchar, 
            HOM_UDFDATE01 datetime, 
            HOM_UDFDATE02 datetime, 
            HOM_UDFDATE03 datetime, 
            HOM_UDFDATE04 datetime, 
            HOM_UDFDATE05 datetime, 
            HOM_UDFNUM01 numeric(38, 10), 
            HOM_UDFNUM02 numeric(38, 10), 
            HOM_UDFNUM03 numeric(38, 10), 
            HOM_UDFNUM04 numeric(38, 10), 
            HOM_UDFNUM05 numeric(38, 10), 
            HOM_UDFNUM06 numeric(38, 10), 
            HOM_UDFNUM07 numeric(38, 10), 
            HOM_UDFNUM08 numeric(38, 10), 
            HOM_UDFNUM09 numeric(38, 10), 
            HOM_UDFNUM10 numeric(38, 10), 
            HOM_UOM varchar, 
            HOM_UPDATE datetime, 
            HOM_UPDATECOUNT numeric(38, 10), 
            HOM_UPDFREQ numeric(38, 10), 
            HOM_VALUE numeric(38, 10), 
            HOM_WHERECLAUSE varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 