CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5DEVICES(
            DEV_CATEGORY varchar, 
            DEV_CATFLAG varchar, 
            DEV_CODE varchar, 
            DEV_DESC varchar, 
            DEV_DESTINATION varchar, 
            DEV_DRIVER varchar, 
            DEV_LASTLOGINDATE datetime, 
            DEV_LASTSAVED datetime, 
            DEV_MODE varchar, 
            DEV_NOTUSED varchar, 
            DEV_ORG varchar, 
            DEV_ORIENTATION varchar, 
            DEV_RTYPE varchar, 
            DEV_SPECIAL varchar, 
            DEV_TYPE varchar, 
            DEV_UPDATECOUNT numeric(38, 10), 
            DEV_UPDATED datetime, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 