CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5ELECSIGN(
            ELS_CERTIFYNUM varchar, 
            ELS_CERTIFYTYPE varchar, 
            ELS_CODE varchar, 
            ELS_DATE datetime, 
            ELS_ENTCODE varchar, 
            ELS_ENTCODE2 varchar, 
            ELS_ENTITY varchar, 
            ELS_EXTERNALDATE datetime, 
            ELS_LASTCHANGED varchar, 
            ELS_LASTSAVED datetime, 
            ELS_ORG varchar, 
            ELS_PARENT varchar, 
            ELS_SIGNTYPE varchar, 
            ELS_SIGNTYPEDESC varchar, 
            ELS_STATUS varchar, 
            ELS_USER varchar, 
            ELS_USERDESC varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 