CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_BUILDING_BLDGFAILED AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APBLDGFAILKEY, 
        APBLDGINSPKEY, 
        CMPLDTTM, 
        DELETED, 
        FAILED, 
        LOC, 
        MODBY, 
        MODDTTM, 
        STATUS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        VIOLDTTM, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_BUILDING_BLDGFAILED
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APBLDGFAILKEY, 
        APBLDGINSPKEY, 
        CMPLDTTM, 
        DELETED, 
        FAILED, 
        LOC, 
        MODBY, 
        MODDTTM, 
        STATUS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        VIOLDTTM, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_BUILDING_BLDGFAILED;