CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCODES_FEECODES AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CODE, 
        DATALAKE_DELETED, 
        DESCRIPT, 
        EFFDATE, 
        EXPDATE, 
        MODBY, 
        MODDTTM, 
        RATE, 
        UOM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCODES_FEECODES
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CODE, 
        DATALAKE_DELETED, 
        DESCRIPT, 
        EFFDATE, 
        EXPDATE, 
        MODBY, 
        MODDTTM, 
        RATE, 
        UOM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCODES_FEECODES;