CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLTRADEBILLOUTPUT_TRADEBILLOUTPUTTASKLOG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        BILLKEY, 
        COMMENTS, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        TRADEBILLOUTPUTTASKLOGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLTRADEBILLOUTPUT_TRADEBILLOUTPUTTASKLOG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        BILLKEY, 
        COMMENTS, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        TRADEBILLOUTPUTTASKLOGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLTRADEBILLOUTPUT_TRADEBILLOUTPUTTASKLOG;