CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCRM_XBILLINGDATAAUDITGD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CHANGEDBY, 
        CHANGEDDATETIME, 
        CHANGEDVALUE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        ORIGINALVALUE, 
        TYPE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBILLINGDATAAUDITGDKEY, 
        XBILLINGDATADPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCRM_XBILLINGDATAAUDITGD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CHANGEDBY, 
        CHANGEDDATETIME, 
        CHANGEDVALUE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        ORIGINALVALUE, 
        TYPE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBILLINGDATAAUDITGDKEY, 
        XBILLINGDATADPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCRM_XBILLINGDATAAUDITGD;