CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_ACCTHISTUSAGEDETAIL AS 
    SELECT 
        ACCOUNTSERVICE, 
        ACCTHISTUSAGEDETAILKEY, 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        LINEITEM, 
        MODBY, 
        MODDTTM, 
        USAGE, 
        USAGEDATE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_ACCTHISTUSAGEDETAIL
    UNION ALL 
    SELECT 
        ACCOUNTSERVICE, 
        ACCTHISTUSAGEDETAILKEY, 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        LINEITEM, 
        MODBY, 
        MODDTTM, 
        USAGE, 
        USAGEDATE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_ACCTHISTUSAGEDETAIL;