CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCRM_XRETAILAUDITDP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        SERVNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XRETAILAUDITDPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCRM_XRETAILAUDITDP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        SERVNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XRETAILAUDITDPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCRM_XRETAILAUDITDP;