CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRPROJ_XPROJNETCONQUOTEDP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJREVDTLKEY, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        QUOTEDUEDATE, 
        SENDTOCUSTOMER, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJNETCONQUOTEDPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPROJ_XPROJNETCONQUOTEDP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJREVDTLKEY, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        QUOTEDUEDATE, 
        SENDTOCUSTOMER, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJNETCONQUOTEDPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRPROJ_XPROJNETCONQUOTEDP;