CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_BILLTYPEDIRECTDEBITSETUP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        BILLTYPEDIRECTDEBITSUKEY, 
        BILLTYPEKEY, 
        COMBINEAMOUNT, 
        DELETED, 
        EXTRACTAMOUNTCRITERIA, 
        INCLUDEUNBILLED, 
        MAXAMOUNT, 
        MODBY, 
        MODDTTM, 
        REFBALTHRUEXTRDATE, 
        REFRESHEXTRACTAMOUNT, 
        USEDDSETUPDEFAULT, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_BILLTYPEDIRECTDEBITSETUP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        BILLTYPEDIRECTDEBITSUKEY, 
        BILLTYPEKEY, 
        COMBINEAMOUNT, 
        DELETED, 
        EXTRACTAMOUNTCRITERIA, 
        INCLUDEUNBILLED, 
        MAXAMOUNT, 
        MODBY, 
        MODDTTM, 
        REFBALTHRUEXTRDATE, 
        REFRESHEXTRACTAMOUNT, 
        USEDDSETUPDEFAULT, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_BILLTYPEDIRECTDEBITSETUP;