CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLASSETWATER_XMETERPROCESSRUNKEYS AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        ESTIMATEREADINGKEY, 
        LASTBATCHKEY, 
        LASTIMPORTACTIVITYKEY, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XMETERPROCESSRUNKEYSKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLASSETWATER_XMETERPROCESSRUNKEYS
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        ESTIMATEREADINGKEY, 
        LASTBATCHKEY, 
        LASTIMPORTACTIVITYKEY, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XMETERPROCESSRUNKEYSKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLASSETWATER_XMETERPROCESSRUNKEYS;