CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_APTRN AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        ADJREAS, 
        APFEEKEY, 
        APKEY, 
        APPAYKEY, 
        APRFNDTRNNO, 
        APTRNNO, 
        AUTH, 
        BGTNOKEY, 
        CDRPRODFAMILY, 
        COMMENTS, 
        DELETED, 
        DSCFEEKEY, 
        MODBY, 
        MODDTTM, 
        NEEDSJOURNAL, 
        REFTRNNO, 
        TRNAMT, 
        TRNBY, 
        TRNDTTM, 
        TRNTYPE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XFRAPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_APTRN
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        ADJREAS, 
        APFEEKEY, 
        APKEY, 
        APPAYKEY, 
        APRFNDTRNNO, 
        APTRNNO, 
        AUTH, 
        BGTNOKEY, 
        CDRPRODFAMILY, 
        COMMENTS, 
        DELETED, 
        DSCFEEKEY, 
        MODBY, 
        MODDTTM, 
        NEEDSJOURNAL, 
        REFTRNNO, 
        TRNAMT, 
        TRNBY, 
        TRNDTTM, 
        TRNTYPE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XFRAPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_APTRN;