CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRBUILD_XBUILDWOINSP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APBLDGINSPDTLKEY, 
        DATALAKE_DELETED, 
        HVCLEARANCE, 
        MAINSLOCATEDMARKED, 
        MODBY, 
        MODDTTM, 
        OBERVEOHSCOMPLIANCE, 
        PILESFOUNDATIONEXCAVATED, 
        PILESFOUNDATIONMARKED, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WORKSCOMPLETED, 
        XBUILDWOINSPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDWOINSP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APBLDGINSPDTLKEY, 
        DATALAKE_DELETED, 
        HVCLEARANCE, 
        MAINSLOCATEDMARKED, 
        MODBY, 
        MODDTTM, 
        OBERVEOHSCOMPLIANCE, 
        PILESFOUNDATIONEXCAVATED, 
        PILESFOUNDATIONMARKED, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WORKSCOMPLETED, 
        XBUILDWOINSPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRBUILD_XBUILDWOINSP;