CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRBUILD_XBUILDAPPRESUBMITGRID AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        DESCRIPTION, 
        MODBY, 
        MODDTTM, 
        ONHOLDCODE, 
        ONHOLDCOMMENTS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDAPPRESUBMITDPKEY, 
        XBUILDAPPRESUBMITGRIDKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDAPPRESUBMITGRID
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        DESCRIPTION, 
        MODBY, 
        MODDTTM, 
        ONHOLDCODE, 
        ONHOLDCOMMENTS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDAPPRESUBMITDPKEY, 
        XBUILDAPPRESUBMITGRIDKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRBUILD_XBUILDAPPRESUBMITGRID;