CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_RESPONSIBLEPARTYLOG AS 
    SELECT 
        ACCOUNTKEY, 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        EFFDATE, 
        EXPDATE, 
        IDKEY, 
        MODBY, 
        MODDTTM, 
        RESPONSIBLEPARTYKEY, 
        RESPONSIBLEPARTYLOGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_RESPONSIBLEPARTYLOG
    UNION ALL 
    SELECT 
        ACCOUNTKEY, 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        EFFDATE, 
        EXPDATE, 
        IDKEY, 
        MODBY, 
        MODDTTM, 
        RESPONSIBLEPARTYKEY, 
        RESPONSIBLEPARTYLOGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_RESPONSIBLEPARTYLOG;