CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRPROJ_XPROJCONSULTDP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJAPPLDTLKEY, 
        ASSESSMENTTYPE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        REASONFORREQUEST, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJCONSULTDPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPROJ_XPROJCONSULTDP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJAPPLDTLKEY, 
        ASSESSMENTTYPE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        REASONFORREQUEST, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJCONSULTDPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRPROJ_XPROJCONSULTDP;