CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_PLANNING_PLANEMP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPLANEMPKEY, 
        APPLANKEY, 
        CAPACITY, 
        DATALAKE_DELETED, 
        EMPID, 
        FROMDTTM, 
        MODBY, 
        MODDTTM, 
        TODTTM, 
        TOTALHRS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PLANNING_PLANEMP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPLANEMPKEY, 
        APPLANKEY, 
        CAPACITY, 
        DATALAKE_DELETED, 
        EMPID, 
        FROMDTTM, 
        MODBY, 
        MODDTTM, 
        TODTTM, 
        TOTALHRS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_PLANNING_PLANEMP;