CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_BUILDING_BLDGAPPLDETAILLOG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APBLDGAPPLDTLKEY, 
        BLDGAPPLDETAILLOGKEY, 
        DELETED, 
        DTLMODBY, 
        DTLMODDTTM, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_BUILDING_BLDGAPPLDETAILLOG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APBLDGAPPLDTLKEY, 
        BLDGAPPLDETAILLOGKEY, 
        DELETED, 
        DTLMODBY, 
        DTLMODDTTM, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_BUILDING_BLDGAPPLDETAILLOG;