CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRPLAN_XPLANAPTIMELINEDP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        PLANAPPLDETAILKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPLANAPTIMELINEDPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPLAN_XPLANAPTIMELINEDP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        PLANAPPLDETAILKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPLANAPTIMELINEDPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRPLAN_XPLANAPTIMELINEDP;