CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_RESOURCES_CREDITRATINGSETUP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CREDITRATINGSETUPKEY, 
        DATALAKE_DELETED, 
        LATEPAYMENTPOINTSCODE, 
        LOOKBACKPERIODDAYS, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_CREDITRATINGSETUP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CREDITRATINGSETUPKEY, 
        DATALAKE_DELETED, 
        LATEPAYMENTPOINTSCODE, 
        LOOKBACKPERIODDAYS, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_RESOURCES_CREDITRATINGSETUP;