CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_LINEITEMTRACKEDREAD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        LINEITEMKEY, 
        LINEITEMTRACKEDREADKEY, 
        MODBY, 
        MODDTTM, 
        SEWERTRACKEDREADINGKEY, 
        STORMTRACKEDREADING, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WATERTRACKEDREADING, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_LINEITEMTRACKEDREAD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        LINEITEMKEY, 
        LINEITEMTRACKEDREADKEY, 
        MODBY, 
        MODDTTM, 
        SEWERTRACKEDREADINGKEY, 
        STORMTRACKEDREADING, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WATERTRACKEDREADING, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_LINEITEMTRACKEDREAD;