CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_METERMANAGEMENT_WATER_USGESTEXCEPTION AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        EXCEPTIONDESCRIPTION, 
        MODBY, 
        MODDTTM, 
        READINGKEY, 
        USGESTEXCEPTIONKEY, 
        USGESTHISTKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_METERMANAGEMENT_WATER_USGESTEXCEPTION
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        EXCEPTIONDESCRIPTION, 
        MODBY, 
        MODDTTM, 
        READINGKEY, 
        USGESTEXCEPTIONKEY, 
        USGESTHISTKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_METERMANAGEMENT_WATER_USGESTEXCEPTION;