CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_PROJECT_PROJMODEL AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJKEY, 
        BASEMODELKEY, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        MODELTITLE, 
        MODELTYPE, 
        PROJMODELKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PROJECT_PROJMODEL
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJKEY, 
        BASEMODELKEY, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        MODELTITLE, 
        MODELTYPE, 
        PROJMODELKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_PROJECT_PROJMODEL;