CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_METERMANAGEMENT_WATER_USAGEESTIMATESETUP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CALCORDER, 
        CONDFRMLA, 
        DELETED, 
        DESCRIPTION, 
        MODBY, 
        MODDTTM, 
        USGESTFRMLA, 
        USGESTGRP, 
        USGESTID, 
        USGESTSKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_METERMANAGEMENT_WATER_USAGEESTIMATESETUP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CALCORDER, 
        CONDFRMLA, 
        DELETED, 
        DESCRIPTION, 
        MODBY, 
        MODDTTM, 
        USGESTFRMLA, 
        USGESTGRP, 
        USGESTID, 
        USGESTSKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_METERMANAGEMENT_WATER_USAGEESTIMATESETUP;