CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_PROJECT_PROJAPL AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APLTY, 
        APPROJAPLKEY, 
        APPROJKEY, 
        CAPACITY, 
        CNTCTKEY, 
        DATALAKE_DELETED, 
        EFFDATE, 
        EXPDATE, 
        MODBY, 
        MODDTTM, 
        PRIM, 
        RESPACCOUNTHOLDERFLAG, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PROJECT_PROJAPL
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APLTY, 
        APPROJAPLKEY, 
        APPROJKEY, 
        CAPACITY, 
        CNTCTKEY, 
        DATALAKE_DELETED, 
        EFFDATE, 
        EXPDATE, 
        MODBY, 
        MODDTTM, 
        PRIM, 
        RESPACCOUNTHOLDERFLAG, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_PROJECT_PROJAPL;