CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CORE_BATCHPROCESSING_USEREXCEPTION AS 
    SELECT 
        ACCOUNTKEY, 
        ADDBY, 
        ADDDTTM, 
        BATCHPROCESSEXCEPTIONKEY, 
        DELETED, 
        LINEITEMSETUPKEY, 
        MODBY, 
        MODDTTM, 
        RUNKEY, 
        USEREXCEPTIONKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CORE_BATCHPROCESSING_USEREXCEPTION
    UNION ALL 
    SELECT 
        ACCOUNTKEY, 
        ADDBY, 
        ADDDTTM, 
        BATCHPROCESSEXCEPTIONKEY, 
        DELETED, 
        LINEITEMSETUPKEY, 
        MODBY, 
        MODDTTM, 
        RUNKEY, 
        USEREXCEPTIONKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CORE_BATCHPROCESSING_USEREXCEPTION;