CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRPROJ_XPROJCONSENQDP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJAPPLDTLKEY, 
        DELETED, 
        ESTNORESHH, 
        MODBY, 
        MODDTTM, 
        NEIGHBOURINGDEVS, 
        PRIORDEVCORR, 
        TOTALDEVAREAHA, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WASTEWATERCOMMENTS, 
        WATERSUPPLYCOMMENTS, 
        XPROJCONSENQDPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPROJ_XPROJCONSENQDP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJAPPLDTLKEY, 
        DELETED, 
        ESTNORESHH, 
        MODBY, 
        MODDTTM, 
        NEIGHBOURINGDEVS, 
        PRIORDEVCORR, 
        TOTALDEVAREAHA, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WASTEWATERCOMMENTS, 
        WATERSUPPLYCOMMENTS, 
        XPROJCONSENQDPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRPROJ_XPROJCONSENQDP;