CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_APBILLACCTCHNGLOG AS 
    SELECT 
        ACCTCHANGETRANSFERTYPE, 
        ADDBY, 
        ADDDTTM, 
        APBILLACCTCHNGLOGKEY, 
        APKEY, 
        DELETED, 
        FROMBILLACCTKEY, 
        MODBY, 
        MODDTTM, 
        TOBILLACCTKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XFERTRNFLAG, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_APBILLACCTCHNGLOG
    UNION ALL 
    SELECT 
        ACCTCHANGETRANSFERTYPE, 
        ADDBY, 
        ADDDTTM, 
        APBILLACCTCHNGLOGKEY, 
        APKEY, 
        DELETED, 
        FROMBILLACCTKEY, 
        MODBY, 
        MODDTTM, 
        TOBILLACCTKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XFERTRNFLAG, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_APBILLACCTCHNGLOG;