CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_PLANNING_PLANCOND(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLANCONDKEY integer, 
            APPLANCONDTYPEKEY integer, 
            APPLANKEY integer, 
            APPLDBY varchar, 
            APPLDDTTM datetime, 
            APRV varchar, 
            APRVBY varchar, 
            APRVDTTM datetime, 
            APRVED varchar, 
            ASSIGNED varchar, 
            CMPTRGEN varchar, 
            DELETED boolean, 
            MODBY varchar, 
            MODDTTM datetime, 
            SUPREQD varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 