CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLCDRBUILD_XMDADDRESSGD(
            ADDBY varchar, 
            ADDDTTM datetime, 
            CT varchar, 
            CUSTOMERREFERENCE varchar, 
            DATALAKE_DELETED boolean, 
            DEVCONTPAID varchar, 
            DP varchar, 
            FLOORAREALT65M2 varchar, 
            HOUSENO varchar, 
            LOT varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            POSTCODE varchar, 
            STREETNAME varchar, 
            STTYPE varchar, 
            SUBURB varchar, 
            UNIT varchar, 
            VARIATION_ID integer, 
            XBUILDMULCONNECTIONSKEY integer, 
            XMDADDRESSGDKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 