CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLCDRPROJ_XPROJPRECONDP(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPROJAPPLDTLKEY integer, 
            BILLPAYER varchar, 
            CONSTRUCTIONSTAGE varchar, 
            CT varchar, 
            DATALAKE_DELETED boolean, 
            DP varchar, 
            EPANUMBER varchar, 
            LOT varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NEIGHBOURHOOD varchar, 
            STAGE varchar, 
            SUPERLOT varchar, 
            VARIATION_ID integer, 
            XPROJPRECONDPKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 