CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_PLANNING_PLANAPPLDETAILTYPE(
            ACCESSID integer, 
            ADDBY varchar, 
            ADDCONDFRMLA integer, 
            ADDDTTM datetime, 
            APPLANDEFNKEY integer, 
            APPLANPROCESSSTATEKEY integer, 
            CLASSNAME varchar, 
            DATALAKE_DELETED boolean, 
            DESCRIPT varchar, 
            DISPLAY integer, 
            DISPLAYORDER integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            MODBY varchar, 
            MODDTTM datetime, 
            PLANAPPLDETAILTYPEKEY integer, 
            PORTALDETAILPAGEAREA integer, 
            PORTALDETAILPAGEPLACEMENT integer, 
            STARTAPPLFLAG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 