CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_PLANNING_PLANSTATUSLOG(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLANKEY integer, 
            APPLANPROCESSSTATEKEY integer, 
            APPLANSTATLOGKEY integer, 
            CMPTRGEN varchar, 
            DATALAKE_DELETED boolean, 
            MODBY varchar, 
            MODDTTM datetime, 
            PLANAPPLSTATUS varchar, 
            STAT varchar, 
            STATUSBY varchar, 
            STATUSDTTM datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 