CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_ACCOUNTSERVICE(
            AACCALCULATIONDT datetime, 
            AACEXCEPTION integer, 
            AACMONTHLYAVERAGE numeric(38, 10), 
            ACCOUNTKEY integer, 
            ACCOUNTSERVICEKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESSSERVICEKEY integer, 
            AREA varchar, 
            COMMENTSKEY integer, 
            CONSUMPTIONPERCENTAGE numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            IMPERVIOUSPERCENTAGE numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            SERVICECLASS1 varchar, 
            SERVICECLASS2 varchar, 
            SERVICEFIELD1VALUE numeric(38, 10), 
            SERVICEFIELD2VALUE numeric(38, 10), 
            SERVICEFIELD3VALUE numeric(38, 10), 
            SERVICEOPTIONSKEY integer, 
            STARTDTTM datetime, 
            STATUS varchar, 
            STATUSDTTM datetime, 
            STOPDTTM datetime, 
            SUSPENDFROMDATE datetime, 
            SUSPENDTODATE datetime, 
            VARIATION_ID integer, 
            WINAVGCALDATE datetime, 
            WINTERAVG numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 