CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLBILLING_MIGSERVICES(
            ACCOUNTNUMBER varchar, 
            ACCOUNTSERVICEKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESSKEY1 integer, 
            ADDRESSKEY2 integer, 
            ADDRESSKEY3 integer, 
            ADDRESSKEY4 integer, 
            ADDRESSKEY5 integer, 
            ADDRESSKEY6 integer, 
            ADDRESSKEY7 integer, 
            ANNUALFIX integer, 
            BILLABLEPERC numeric(38, 10), 
            BILLABLEPERC1 numeric(38, 10), 
            BILLABLEPERC2 numeric(38, 10), 
            BILLABLEPERC3 numeric(38, 10), 
            BILLABLEPERC4 numeric(38, 10), 
            BILLABLEPERC5 numeric(38, 10), 
            BILLABLEPERC6 numeric(38, 10), 
            BILLABLEPERC7 numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            LASTBILLDATE varchar, 
            MIGSERVICESKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MULTI varchar, 
            NUMMETERS integer, 
            POSITION1 integer, 
            POSITION2 integer, 
            POSITION3 integer, 
            POSITION4 integer, 
            POSITION5 integer, 
            POSITION6 integer, 
            POSITION7 integer, 
            PRICINGPLAN varchar, 
            READDATE1 datetime, 
            READDATE2 datetime, 
            READDATE3 datetime, 
            READDATE4 datetime, 
            READDATE5 datetime, 
            READDATE6 datetime, 
            READDATE7 datetime, 
            SRVTYPE varchar, 
            STARTDATE datetime, 
            STARTKEY1 integer, 
            STARTKEY2 integer, 
            STARTKEY3 integer, 
            STARTKEY4 integer, 
            STARTKEY5 integer, 
            STARTKEY6 integer, 
            STARTKEY7 integer, 
            STATUSMESG varchar, 
            SUBFLAG1 varchar, 
            SUBFLAG2 varchar, 
            SUBFLAG3 varchar, 
            SUBFLAG4 varchar, 
            SUBFLAG5 varchar, 
            SUBFLAG6 varchar, 
            SUBFLAG7 varchar, 
            VARIATION_ID integer, 
            WTRDATA1 varchar, 
            WTRDATA2 varchar, 
            WTRDATA3 varchar, 
            WTRDATA4 varchar, 
            WTRDATA5 varchar, 
            WTRDATA6 varchar, 
            WTRDATA7 varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 