CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_QUANTITYITEM(
            ADDBY varchar, 
            ADDDTTM datetime, 
            DEFAULTFLAG varchar, 
            DEFAULTQTY integer, 
            DELETED boolean, 
            DESCRIPTION varchar, 
            DISPLAYORDER integer, 
            INCRLINKTEXT varchar, 
            MAXQTY integer, 
            MINQTY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NUMERICFIELDTEXT varchar, 
            POSTINCRLINKTEXT varchar, 
            QUANTITYFIELDKEY integer, 
            QUANTITYITEMKEY integer, 
            RADIOBUTTONTEXT varchar, 
            TITLE varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 