CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_ASSETMANAGEMENT_WATER_COMPWMTR(
            ACCTNO varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            AVGMONUSG numeric(38, 10), 
            AVGMONUSGUOM varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            BYPASS varchar, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            COMPONENT integer, 
            DATALAKE_DELETED boolean, 
            DISTRICT varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            GISSTATIC integer, 
            HIGHREG integer, 
            INSTDATE datetime, 
            INTKEY integer, 
            LASTREADINGEXSCHDKEY integer, 
            LASTREADINGIMSCHDKEY integer, 
            LOC varchar, 
            LOWREG integer, 
            MAINKEY integer, 
            MAPNO varchar, 
            METERSZ numeric(38, 10), 
            METERSZUOM varchar, 
            MFGDATE datetime, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            OUTFORACTIVITYFLAG varchar, 
            OWN varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PRESZONE varchar, 
            PURCDATE datetime, 
            SEGKEY integer, 
            SERNO varchar, 
            SERVSTAT varchar, 
            SITEKEY integer, 
            SLKEY integer, 
            SRVTYPE varchar, 
            SUBAREA varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            USGDATE datetime, 
            USGTOT numeric(38, 10), 
            USGTOTUOM varchar, 
            VARIATION_ID integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 