CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_ACCTTRAN(
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADJUSTMENTKEY integer, 
            APPFEEKEY integer, 
            COMMENTSKEY integer, 
            DATALAKE_DELETED boolean, 
            DEPOSITTRANSACTIONKEY integer, 
            INTERNALFLAG varchar, 
            LINEITEMKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NEEDSJOURNAL varchar, 
            ONEOFFCHARGEKEY integer, 
            PAYKEY integer, 
            PENALTYKEY integer, 
            REFTRANNO integer, 
            REFUNDKEY integer, 
            SOURCEKEY integer, 
            SOURCETYPE integer, 
            TRANAMT numeric(38, 10), 
            TRANBY varchar, 
            TRANDATE datetime, 
            TRANNO integer, 
            TRANSACTIONDESIGNATOR integer, 
            TRANSACTIONTYPE integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 