CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLCRM_XBILLINGDATADP(
            ACCOUNTCLASS varchar, 
            ACCOUNTCREATEDATE datetime, 
            ACTIONTYPEDESC varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESS varchar, 
            APPNO varchar, 
            CONTACTID varchar, 
            CONTACTKEY integer, 
            CONTRACTORREFNO varchar, 
            CREATEACCOUNT varchar, 
            CREWID varchar, 
            CT varchar, 
            CUSTOMERSIDE varchar, 
            DELETED boolean, 
            DISCONNECTIONDATE datetime, 
            DISCONNECTIONTYPE varchar, 
            DP varchar, 
            EMPLOYEEID varchar, 
            ESTDAILYWATERDEMAND numeric(38, 10), 
            FLOWATTHEMETER numeric(38, 10), 
            GISXCOORD numeric(38, 10), 
            GISYCOORD numeric(38, 10), 
            GISZCOORD numeric(38, 10), 
            INITIALMETERREADING numeric(38, 10), 
            LOCATIONDESCRIPTION varchar, 
            LOT varchar, 
            METERINSTALLATIONPHOTO varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            MULTIMETERACCOUNT varchar, 
            NEWMETERID varchar, 
            NEWMETERINSTALLDATE datetime, 
            NEWMETERSIZE varchar, 
            OLDMETERID varchar, 
            OLDMETERREADING numeric(38, 10), 
            OWNERCUSTOMER varchar, 
            PHONENUMBER varchar, 
            PIPEDAIMETER integer, 
            PIPELENGTH numeric(38, 10), 
            PRICEPLAN varchar, 
            REJECTBYBILLS varchar, 
            REJECTREASON varchar, 
            SERIALNO varchar, 
            SERVICELINEMATERIAL varchar, 
            SERVNO integer, 
            SMS varchar, 
            SUBMITTEDASBUILT varchar, 
            USELASTBILLEDREAD varchar, 
            VARIATION_ID integer, 
            WORKORDERMETERID varchar, 
            WORKORDERNO varchar, 
            WORKTYPEDESC varchar, 
            WSLSIDE varchar, 
            XBILLINGDATADPKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 