CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_DELINQUENCYMSALERT(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ALERTKEY integer, 
            APPLYTOACCOUNT varchar, 
            APPLYTOCONTACT varchar, 
            BELOWRESOLUTION varchar, 
            CONDITIONFORMULA integer, 
            DECREMENTRESOLUTION varchar, 
            DELETED boolean, 
            DISPLAYORDER integer, 
            INCREMENTRESOLUTION varchar, 
            MILESTONEALERTKEY integer, 
            MILESTONEKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            PAIDOFFRESOLUTION varchar, 
            PERFORMON varchar, 
            REASON varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 