CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLCODES_CONNWORKITEMS(
            ADDBY varchar, 
            ADDDTTM datetime, 
            BACKFLOW varchar, 
            CODE varchar, 
            DELETED boolean, 
            DESCRIPT varchar, 
            DISCONNECTION varchar, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            METERINSTALLATION varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            RELOCATION varchar, 
            SERVICELINEINSTALLATION varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 