CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_LINEITEM(
            ACCOUNTSERVICEKEY integer, 
            ACTUALAMT numeric(38, 10), 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BILLKEY integer, 
            BUDGETEDAMOUNTFLAG varchar, 
            COMMENTSKEY integer, 
            DATALAKE_DELETED boolean, 
            DISCOUNTEXPIREDATE datetime, 
            LINEITEMAMT numeric(38, 10), 
            LINEITEMKEY integer, 
            LINEITEMSETUPKEY integer, 
            LINEITEMUNITS numeric(38, 10), 
            LINEITEMUSAGE numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            PAIDSTAT varchar, 
            PENALIZEDFLAG varchar, 
            PENALTYDATE datetime, 
            PENALTYPAYORDER integer, 
            PENDTYPE varchar, 
            PRINCIPALPAYORDER integer, 
            PRINTORDER integer, 
            PRINTTEXT varchar, 
            VARIANTFLAG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 