CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_ADDRESSSERVICEPOSITION(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESSSERVICEKEY integer, 
            ADDRKEY integer, 
            ADDRSRVPOSITIONKEY integer, 
            ASSETTYPE integer, 
            CONSUMPTIONPERCENTAGE numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            METERREGISTERUSE integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            POSITION integer, 
            SUBTRACTIVEFLAG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 