CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_USE_USECOND(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLDBY varchar, 
            APPLDDTTM datetime, 
            APRV varchar, 
            APRVBY varchar, 
            APRVDTTM datetime, 
            APRVED varchar, 
            APUSECONDKEY integer, 
            APUSECONDTYPEKEY integer, 
            APUSEKEY integer, 
            ASSIGNED varchar, 
            CMPTRGEN varchar, 
            DELETED boolean, 
            MODBY varchar, 
            MODDTTM datetime, 
            SUPREQD varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 