CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_METERMANAGEMENT_WATER_READINGIMPORTROUTEDETAIL(
            ADDBY varchar, 
            ADDDTTM datetime, 
            DATALAKE_DELETED boolean, 
            IMPORTEXCLFLAG varchar, 
            IMPORTFILENAME varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NOOFMETERS integer, 
            READINGEXPORTROUTEDTLKEY integer, 
            READINGIMPORTACTIVITYKEY integer, 
            READINGIMPORTROUTEDTLKEY integer, 
            READINGIMPORTROUTEKEY integer, 
            RERUNFLAG varchar, 
            ROUTEKEY integer, 
            STARTDTTM datetime, 
            STATUS integer, 
            STOPDTTM datetime, 
            UNHANDLEDEXCEPDESC varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 