CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_ASSETMANAGEMENT_SEWER_COMPSND(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            DATALAKE_DELETED boolean, 
            DISTFRND numeric(38, 10), 
            DISTFRNDUOM varchar, 
            DISTRICT varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            FRND varchar, 
            GISSTATIC integer, 
            INSTDATE datetime, 
            INTKEY integer, 
            LOC varchar, 
            MAINKEY integer, 
            MAPNO varchar, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            OWN varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            SEGKEY integer, 
            SERNO varchar, 
            SERVSTAT varchar, 
            SITEKEY integer, 
            SUBAREA varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            VARIATION_ID integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 