CREATE OR REPLACE SECURE VIEW ${buildvar.env}_WBP_SHARE.DATAHUB_SHARED_WBP.VWS_SEWER_SERVICE_LINE
AS
SELECT 
  A1."ACQTYPE" AS "Acquistion Type"
, A2."ADDRKEY" AS "Address"
, A2."COMPKEY" AS "CompKey"
, A1."COSTCENTRE" AS "Cost Centre Code"
, 'TBD' AS "Cost Centre Description"
, A1."CRITICALITY" AS "Criticality Code"
, 'TBD' AS "Criticality Description"
, A2."UNITDESC" AS "Description"
, A2."DIAM" AS "Diameter"
, A1."FORDISPOSAL" AS "Disposal Reason"
, A1."DRAWINGNO" AS "Drawing No"
, A1."DRAWINGNOREF" AS "Drawing No Ref"
, A2."BGTNO" AS "Equipment No"
, A2."EXPDATE" AS "Expire Date"
, A2."AREA" AS "Facility Code"
, 'TBD' AS "Facility Description"
, A2."INSTDATE" AS "Installed"
, A2."ASBLT" AS "Legacy Key"
, A2."PIPELEN" AS "Length"
, A1."MODELNO" AS "Model #"
, A2."OWN" AS "Ownership Code"
, 'TBD' AS "Ownership Description"
, A2."PIPETYPE" AS "Pipe Type"
, A2."MAPNO" AS "Position"
, A2."SUBAREA" AS "Process Code"
, 'TBD' AS "Process Description"
, A1."SAFETYCRITICAL" AS "Safety Critical Element"
, A2."UNITID" AS "Service Line ID"
, A2."UNITTYPE" AS "Service Line Type"
, 'TBD' AS "Service Line Type Description"
, A2."SERVSTAT" AS "Service Status"
, A2."LOC" AS "Set Code"
, 'TBD' AS "Set Description"
, A2."SURF" AS "Surface Cover Code"
, 'TBD' AS "Surface Cover Description"
, A2."DISTRICT" AS "System Code"
, 'TBD' AS "System Description"
, 'TBD' AS "Sub-Type"
, ad."NZHOUSENO" AS "Street Number"
, CONCAT(ad."NZSTNAME",' ',ad."NZSTTYPE") AS "Street Name"
, ad."NZSUBURB" AS "City"
, ad."NZPOSTCODE" AS "Postal Code"

, A1.MAKE					                        AS "Make"
, A1.ZONECATCHMENT            						AS "Water Zone/Sewer Catchment"
, XSEWERSERVICELINE.DIAMEXT                			AS "Diameter External (mm)"
, XSEWERSERVICELINE.DIAMINT                			AS "Diameter Internal (mm)"
, XSEWERSERVICELINE.INVLEVEL                     	AS "Invert Level (M)"
, XSEWERSERVICELINE.PRESSURERATING                  AS "Pressure Rating (kPa)"
, XSEWERSERVICELINE.STIFFRATING                     AS "Stiffness Rating (SN)"
, A1.WARRANTYEND             						AS "Warranty End Date"
, A1.WARRANTYSTART            					    AS "Warranty Start Date"
, XSEWERSERVICELINE.CONSTMETHOD                     AS "Construction Method"
, XSEWERSERVICELINE.DESIGNRESILIENCE                AS "Design Resilience"
, XSEWERSERVICELINE.QUAKEDESIGN                     AS "Earthquake Design Level"
, XSEWERSERVICELINE.EXTCOAT                 		AS "External Coating"
, XSEWERSERVICELINE.FUNCAREA                  		AS "Functional Area"
, XSEWERSERVICELINE.GRDLEVEL                     	AS "Ground Level"
, XSEWERSERVICELINE.INTLINING                  		AS "Internal Lining"
, XSEWERSERVICELINE.JTTYPE                       	AS "Joint Method"
, XSEWERSERVICELINE.LOCALITY                        AS "Locality"
, XSEWERSERVICELINE.MEDIATYPE                       AS "Media Type"
, XSEWERSERVICELINE.PHOTO3D                         AS "Photo/3D Model"

FROM
  "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET"."IPS_ASSETMANAGEMENT_SEWER_COMPSSL" as A2
  INNER JOIN "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET"."IPS_WSLASSETS_XALLASSETSDP02" as A1 ON A2.COMPKEY = A1.COMPKEY AND A1.BUSINESSAREA IN ('WBC','WBE','WBW')
  LEFT OUTER JOIN "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET"."IPS_PROPERTY_ADDRESS" as ad ON ad.ADDRKEY = a2.ADDRKEY AND ad.OPTA = 'WBP'
  LEFT OUTER JOIN "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET".IPS_WSLASSETSSEWER_XSEWERSERVICELINE AS XSEWERSERVICELINE ON A2.COMPKEY = XSEWERSERVICELINE.COMPKEY 
  WHERE A2.BLDGFLOOR = 1003;