CREATE OR REPLACE SECURE VIEW ${buildvar.env}_WBP_SHARE.DATAHUB_SHARED_WBP.VWS_SEWER_MANHOLE
AS
SELECT 
  A2."COMPKEY" AS "CompKey"
, A2."ADDRKEY" AS "Address"
, A2."BGTNO" AS "Equipment No"
, A2."UNITDESC" AS "Description"
, A1."DRAWINGNO" AS "Drawing No"
, A1."DRAWINGNOREF" AS "Drawing No Ref"
, A2."ASBLT" AS "Legacy Key"
, A2."AREA" AS "Facility Code"
, 'TBD' AS "Facility Description"
, A2."SUBAREA" AS "Process Code"
, 'TBD' AS "Process Description"
, A2."DISTRICT" AS "System Code"
, 'TBD' AS "System Description"
, A2."LOC" AS "Set Code"
, 'TBD' AS "Set Description"
, A2."MAPNO" AS "Position"
, A2."UNITTYPE" AS "Unit Type Code"
, 'TBD' AS "Unit Type Description"
, A2."UNITID" AS "Manhole ID"
, A1."MODELNO" AS "Model #"
, A2."SURF" AS "Surface Cover Code"
, 'TBD' AS "Surface Cover Description"
, A2."WALLTYPE" AS "Wall Material Code"
, 'TBD' AS "Wall Material Description"
, A2."BARLDIAM" AS "Barrel Diameter"
, A2."MHDPTH" AS "Depth"
, A2."DROPMH" AS "Drop Manhole"
, A2."INSTDATE" AS "Installed"
, A1."ACQTYPE" AS "Acquistion Type"
, A1."CRITICALITY" AS "Criticality Code"
, 'TBD' AS "Criticality Description"
, A1."SAFETYCRITICAL" AS "Safety Critical Element"
, A2."SERVSTAT" AS "Service Status"
, A2."OWN" AS "Ownership Code"
, 'TBD' AS "Ownership Description"
, A1."COSTCENTRE" AS "Cost Centre Code"
, 'TBD' AS "Cost Centre Description"
, A2.CVRDIAM AS "Cover Diameter"
, A2."EXPDATE" AS "Expire Date"
, A1."FORDISPOSAL" AS "Disposal Reason"
, ad."NZHOUSENO" AS "Street Number"
, CONCAT(ad."NZSTNAME",' ',ad."NZSTTYPE") AS "Street Name"
, ad."NZSUBURB" AS "City"
, ad."NZPOSTCODE" AS "Postal Code"

, A1.MAKE AS Make
, A1.ZONECATCHMENT  AS "Water Zone/Sewer Catchment"
, XSEWERMANHOLES.BOLTDOWN AS "Boltdown"
, CVRTYPE AS "Cover Type"
, XSEWERMANHOLES.DIAMEXT AS "Diameter External (mm)"
, XSEWERMANHOLES.DIAMINT AS "Diameter Internal (mm)"
, XSEWERMANHOLES.HINGED AS "Hinged "
, XSEWERMANHOLES.INVLEVEL AS "Invert Level (M)"
, DROPMH AS "Is Drop Manhole"
, XSEWERMANHOLES.LidLevel AS "Lid Level (M)"
, XSEWERMANHOLES.Lockable AS "Lockable"
, XSEWERMANHOLES.Removable AS "Removable"
, XSEWERMANHOLES.SubTypeFeatures AS "SubType Features"
, A1.WARRANTYEND AS "Warranty End Date"
, A1.WARRANTYSTART AS "Warranty Start Date"
, XSEWERMANHOLES.DesignResilience AS "Design Resilience"
, XSEWERMANHOLES.QuakeDesign AS "Earthquake Design Level"
, XSEWERMANHOLES.FallProtect AS "Fall Protection"
, XSEWERMANHOLES.FuncArea AS "Functional Area"
, XSEWERMANHOLES.GRDLEVEL AS "Ground Level"
, XSEWERMANHOLES.INTLINING AS "Internal Lining"
, XSEWERMANHOLES.LoadRating AS "Load Rating (kN)"
, XSEWERMANHOLES.Locality AS "Locality"
, XSEWERMANHOLES.MediaType AS "Media Type"
, XSEWERMANHOLES.Photo3D AS "Photo/3D Model"

FROM
  "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET"."IPS_ASSETMANAGEMENT_SEWER_COMPSMH" as A2
  INNER JOIN "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET"."IPS_WSLASSETS_XALLASSETSDP02" as A1 ON A2.COMPKEY = A1.COMPKEY AND A1.BUSINESSAREA IN ('WBC','WBE','WBW')
  LEFT OUTER JOIN "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET"."IPS_PROPERTY_ADDRESS" as ad ON ad.ADDRKEY = a2.ADDRKEY AND ad.OPTA = 'WBP'
  LEFT OUTER JOIN "${buildvar.env}_WCC_DATAWAREHOUSE"."DATAHUB_TARGET".IPS_WSLASSETSSEWER_XSEWERMANHOLES AS XSEWERMANHOLES ON A2.COMPKEY = XSEWERMANHOLES.COMPKEY 
  WHERE A2.BLDGFLOOR = 1003;
 

