CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TDSLS400 AS SELECT
                        src:acdt::datetime AS acdt, 
                        src:adin::varchar AS adin, 
                        src:agen::integer AS agen, 
                        src:agen_kw::varchar AS agen_kw, 
                        src:airp::integer AS airp, 
                        src:airp_kw::varchar AS airp_kw, 
                        src:akcd::varchar AS akcd, 
                        src:akcd_ref_compnr::integer AS akcd_ref_compnr, 
                        src:bgrb::integer AS bgrb, 
                        src:bgrb_kw::varchar AS bgrb_kw, 
                        src:bgrq::integer AS bgrq, 
                        src:bgrq_kw::varchar AS bgrq_kw, 
                        src:bkyn::integer AS bkyn, 
                        src:bkyn_kw::varchar AS bkyn_kw, 
                        src:bpcl::varchar AS bpcl, 
                        src:bpcl_ref_compnr::integer AS bpcl_ref_compnr, 
                        src:bppr::varchar AS bppr, 
                        src:bppr_ref_compnr::integer AS bppr_ref_compnr, 
                        src:bptx::varchar AS bptx, 
                        src:bptx_ref_compnr::integer AS bptx_ref_compnr, 
                        src:cbrn::varchar AS cbrn, 
                        src:cbrn_ref_compnr::integer AS cbrn_ref_compnr, 
                        src:ccrs::varchar AS ccrs, 
                        src:ccrs_ref_compnr::integer AS ccrs_ref_compnr, 
                        src:ccty::varchar AS ccty, 
                        src:ccur::varchar AS ccur, 
                        src:ccur_ref_compnr::integer AS ccur_ref_compnr, 
                        src:cdec::varchar AS cdec, 
                        src:cdec_ref_compnr::integer AS cdec_ref_compnr, 
                        src:cfdt::datetime AS cfdt, 
                        src:cfrw::varchar AS cfrw, 
                        src:cfrw_ref_compnr::integer AS cfrw_ref_compnr, 
                        src:chrq::integer AS chrq, 
                        src:chrq_kw::varchar AS chrq_kw, 
                        src:clyn::integer AS clyn, 
                        src:clyn_kw::varchar AS clyn_kw, 
                        src:cofc::varchar AS cofc, 
                        src:cofc_rcmp::integer AS cofc_rcmp, 
                        src:cofc_ref_compnr::integer AS cofc_ref_compnr, 
                        src:compnr::integer AS compnr, 
                        src:corg::integer AS corg, 
                        src:corg_kw::varchar AS corg_kw, 
                        src:corn::object AS corn, 
                        src:cosn::varchar AS cosn, 
                        src:cpay::varchar AS cpay, 
                        src:cpay_ref_compnr::integer AS cpay_ref_compnr, 
                        src:cpls::varchar AS cpls, 
                        src:cpls_ref_compnr::integer AS cpls_ref_compnr, 
                        src:cprj::varchar AS cprj, 
                        src:cprj_ref_compnr::integer AS cprj_ref_compnr, 
                        src:crby::varchar AS crby, 
                        src:crcd::varchar AS crcd, 
                        src:crcd_ref_compnr::integer AS crcd_ref_compnr, 
                        src:crdt::datetime AS crdt, 
                        src:creg::varchar AS creg, 
                        src:creg_ref_compnr::integer AS creg_ref_compnr, 
                        src:crep::varchar AS crep, 
                        src:crep_ref_compnr::integer AS crep_ref_compnr, 
                        src:crht::integer AS crht, 
                        src:crht_ref_compnr::integer AS crht_ref_compnr, 
                        src:crin::integer AS crin, 
                        src:crin_kw::varchar AS crin_kw, 
                        src:cror::integer AS cror, 
                        src:cror_kw::varchar AS cror_kw, 
                        src:crrq::integer AS crrq, 
                        src:crrq_kw::varchar AS crrq_kw, 
                        src:crst::integer AS crst, 
                        src:crst_kw::varchar AS crst_kw, 
                        src:crte::varchar AS crte, 
                        src:crte_ref_compnr::integer AS crte_ref_compnr, 
                        src:ctcd::varchar AS ctcd, 
                        src:ctcd_ref_compnr::integer AS ctcd_ref_compnr, 
                        src:cvyn::integer AS cvyn, 
                        src:cvyn_kw::varchar AS cvyn_kw, 
                        src:cwar::varchar AS cwar, 
                        src:cwar_ref_compnr::integer AS cwar_ref_compnr, 
                        src:ddat::datetime AS ddat, 
                        src:ddtc::datetime AS ddtc, 
                        src:delc::varchar AS delc, 
                        src:delc_ref_compnr::integer AS delc_ref_compnr, 
                        src:deleted::boolean AS deleted, 
                        src:ehis::integer AS ehis, 
                        src:ehis_kw::varchar AS ehis_kw, 
                        src:esin::integer AS esin, 
                        src:esin_kw::varchar AS esin_kw, 
                        src:fcrt::integer AS fcrt, 
                        src:fcrt_kw::varchar AS fcrt_kw, 
                        src:fdpt::varchar AS fdpt, 
                        src:fdpt_ref_compnr::integer AS fdpt_ref_compnr, 
                        src:frin::integer AS frin, 
                        src:frin_kw::varchar AS frin_kw, 
                        src:futo::integer AS futo, 
                        src:futo_kw::varchar AS futo_kw, 
                        src:hdst::integer AS hdst, 
                        src:hdst_kw::varchar AS hdst_kw, 
                        src:hism::integer AS hism, 
                        src:hism_kw::varchar AS hism_kw, 
                        src:hiss::integer AS hiss, 
                        src:hiss_kw::varchar AS hiss_kw, 
                        src:infr::integer AS infr, 
                        src:infr_kw::varchar AS infr_kw, 
                        src:inpl::varchar AS inpl, 
                        src:inpl_ref_compnr::integer AS inpl_ref_compnr, 
                        src:itad::varchar AS itad, 
                        src:itad_ref_compnr::integer AS itad_ref_compnr, 
                        src:itbp::varchar AS itbp, 
                        src:itbp_ref_compnr::integer AS itbp_ref_compnr, 
                        src:itcn::varchar AS itcn, 
                        src:itcn_ref_compnr::integer AS itcn_ref_compnr, 
                        src:lcrq::integer AS lcrq, 
                        src:lcrq_kw::varchar AS lcrq_kw, 
                        src:motv::varchar AS motv, 
                        src:motv_ref_compnr::integer AS motv_ref_compnr, 
                        src:mprm::integer AS mprm, 
                        src:mprm_kw::varchar AS mprm_kw, 
                        src:oamt::numeric(38, 17) AS oamt, 
                        src:odat::datetime AS odat, 
                        src:odis::numeric(38, 17) AS odis, 
                        src:odno::varchar AS odno, 
                        src:odty::integer AS odty, 
                        src:odty_kw::varchar AS odty_kw, 
                        src:ofad::varchar AS ofad, 
                        src:ofad_ref_compnr::integer AS ofad_ref_compnr, 
                        src:ofbp::varchar AS ofbp, 
                        src:ofbp_ref_compnr::integer AS ofbp_ref_compnr, 
                        src:ofcn::varchar AS ofcn, 
                        src:ofcn_ref_compnr::integer AS ofcn_ref_compnr, 
                        src:oref::object AS oref, 
                        src:orno::varchar AS orno, 
                        src:orno_cosn_ref_compnr::integer AS orno_cosn_ref_compnr, 
                        src:osor::varchar AS osor, 
                        src:osrp::varchar AS osrp, 
                        src:osrp_ref_compnr::integer AS osrp_ref_compnr, 
                        src:paym::varchar AS paym, 
                        src:pcod::varchar AS pcod, 
                        src:pcod_ref_compnr::integer AS pcod_ref_compnr, 
                        src:pfad::varchar AS pfad, 
                        src:pfad_ref_compnr::integer AS pfad_ref_compnr, 
                        src:pfbp::varchar AS pfbp, 
                        src:pfbp_ref_compnr::integer AS pfbp_ref_compnr, 
                        src:pfcn::varchar AS pfcn, 
                        src:pfcn_ref_compnr::integer AS pfcn_ref_compnr, 
                        src:pldd::varchar AS pldd, 
                        src:pldd_ref_compnr::integer AS pldd_ref_compnr, 
                        src:prdt::datetime AS prdt, 
                        src:prno::varchar AS prno, 
                        src:prno_ref_compnr::integer AS prno_ref_compnr, 
                        src:ptpa::varchar AS ptpa, 
                        src:ptpa_ref_compnr::integer AS ptpa_ref_compnr, 
                        src:ratd::datetime AS ratd, 
                        src:ratf_1::integer AS ratf_1, 
                        src:ratf_2::integer AS ratf_2, 
                        src:ratf_3::integer AS ratf_3, 
                        src:rats_1::numeric(38, 17) AS rats_1, 
                        src:rats_2::numeric(38, 17) AS rats_2, 
                        src:rats_3::numeric(38, 17) AS rats_3, 
                        src:ratt::varchar AS ratt, 
                        src:ratt_ref_compnr::integer AS ratt_ref_compnr, 
                        src:rcmp::integer AS rcmp, 
                        src:refa::object AS refa, 
                        src:refb::object AS refb, 
                        src:retr::varchar AS retr, 
                        src:retr_ref_compnr::integer AS retr_ref_compnr, 
                        src:revn::integer AS revn, 
                        src:rtyp::varchar AS rtyp, 
                        src:ruso::integer AS ruso, 
                        src:ruso_kw::varchar AS ruso_kw, 
                        src:sbim::integer AS sbim, 
                        src:sbim_kw::varchar AS sbim_kw, 
                        src:scon::integer AS scon, 
                        src:scon_kw::varchar AS scon_kw, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:shpm::varchar AS shpm, 
                        src:site::varchar AS site, 
                        src:site_ref_compnr::integer AS site_ref_compnr, 
                        src:sotp::varchar AS sotp, 
                        src:sotp_ref_compnr::integer AS sotp_ref_compnr, 
                        src:stad::varchar AS stad, 
                        src:stad_ref_compnr::integer AS stad_ref_compnr, 
                        src:stbp::varchar AS stbp, 
                        src:stbp_ref_compnr::integer AS stbp_ref_compnr, 
                        src:stcn::varchar AS stcn, 
                        src:stcn_ref_compnr::integer AS stcn_ref_compnr, 
                        src:timestamp::datetime AS timestamp, 
                        src:tprd::numeric(38, 17) AS tprd, 
                        src:tprd_dtwc::numeric(38, 17) AS tprd_dtwc, 
                        src:tprd_lclc::numeric(38, 17) AS tprd_lclc, 
                        src:tprd_rfrc::numeric(38, 17) AS tprd_rfrc, 
                        src:tprd_rpc1::numeric(38, 17) AS tprd_rpc1, 
                        src:tprd_rpc2::numeric(38, 17) AS tprd_rpc2, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:txtb::integer AS txtb, 
                        src:txtb_ref_compnr::integer AS txtb_ref_compnr, 
                        src:username::varchar AS username, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:orno,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:orno,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TDSLS400 as strm))