CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TPPPC305 AS SELECT
                        src:amhc_1::numeric(38, 17) AS amhc_1, 
                        src:amhc_2::numeric(38, 17) AS amhc_2, 
                        src:amhc_3::numeric(38, 17) AS amhc_3, 
                        src:amor::numeric(38, 17) AS amor, 
                        src:amor_cntc::numeric(38, 17) AS amor_cntc, 
                        src:amor_dwhc::numeric(38, 17) AS amor_dwhc, 
                        src:amor_homc::numeric(38, 17) AS amor_homc, 
                        src:amor_prjc::numeric(38, 17) AS amor_prjc, 
                        src:amor_refc::numeric(38, 17) AS amor_refc, 
                        src:amor_rpc1::numeric(38, 17) AS amor_rpc1, 
                        src:amor_rpc2::numeric(38, 17) AS amor_rpc2, 
                        src:bptc::varchar AS bptc, 
                        src:bptc_ref_compnr::integer AS bptc_ref_compnr, 
                        src:cact::varchar AS cact, 
                        src:ccco::varchar AS ccco, 
                        src:ccco_ref_compnr::integer AS ccco_ref_compnr, 
                        src:ccty::varchar AS ccty, 
                        src:ccty_cvat_ref_compnr::integer AS ccty_cvat_ref_compnr, 
                        src:ccty_ref_compnr::integer AS ccty_ref_compnr, 
                        src:ccur::varchar AS ccur, 
                        src:ccur_ref_compnr::integer AS ccur_ref_compnr, 
                        src:cdoc::object AS cdoc, 
                        src:cdru::datetime AS cdru, 
                        src:cdru_cser_ref_compnr::integer AS cdru_cser_ref_compnr, 
                        src:ceno::varchar AS ceno, 
                        src:cnln::varchar AS cnln, 
                        src:cntp::integer AS cntp, 
                        src:cntp_kw::varchar AS cntp_kw, 
                        src:comf::integer AS comf, 
                        src:comf_kw::varchar AS comf_kw, 
                        src:compnr::integer AS compnr, 
                        src:cono::varchar AS cono, 
                        src:cono_cnln_ref_compnr::integer AS cono_cnln_ref_compnr, 
                        src:cono_ref_compnr::integer AS cono_ref_compnr, 
                        src:cpla::varchar AS cpla, 
                        src:cprj::varchar AS cprj, 
                        src:cprj_cpla_cact_ref_compnr::integer AS cprj_cpla_cact_ref_compnr, 
                        src:cprj_cpro::varchar AS cprj_cpro, 
                        src:cprj_cspa_ref_compnr::integer AS cprj_cspa_ref_compnr, 
                        src:cprj_cstl_ref_compnr::integer AS cprj_cstl_ref_compnr, 
                        src:cprj_ref_compnr::integer AS cprj_ref_compnr, 
                        src:cpro::varchar AS cpro, 
                        src:cptc::varchar AS cptc, 
                        src:cptc_ref_compnr::integer AS cptc_ref_compnr, 
                        src:cptc_year_peri_ref_compnr::integer AS cptc_year_peri_ref_compnr, 
                        src:cptf::varchar AS cptf, 
                        src:cptf_fyea_fper_ref_compnr::integer AS cptf_fyea_fper_ref_compnr, 
                        src:cptf_ref_compnr::integer AS cptf_ref_compnr, 
                        src:crdf::integer AS crdf, 
                        src:crdf_kw::varchar AS crdf_kw, 
                        src:cser::integer AS cser, 
                        src:cspa::varchar AS cspa, 
                        src:cstl::varchar AS cstl, 
                        src:cstv::numeric(38, 17) AS cstv, 
                        src:cuvc::varchar AS cuvc, 
                        src:cuvc_ref_compnr::integer AS cuvc_ref_compnr, 
                        src:cvat::varchar AS cvat, 
                        src:cvat_ref_compnr::integer AS cvat_ref_compnr, 
                        src:deleted::boolean AS deleted, 
                        src:desc::object AS desc, 
                        src:drun::datetime AS drun, 
                        src:drun_serb_ref_compnr::integer AS drun_serb_ref_compnr, 
                        src:emno::varchar AS emno, 
                        src:emno_ref_compnr::integer AS emno_ref_compnr, 
                        src:entu::varchar AS entu, 
                        src:exmt::integer AS exmt, 
                        src:exmt_kw::varchar AS exmt_kw, 
                        src:exrs::varchar AS exrs, 
                        src:exrs_ref_compnr::integer AS exrs_ref_compnr, 
                        src:fcmp::integer AS fcmp, 
                        src:fcrt::integer AS fcrt, 
                        src:fcrt_kw::varchar AS fcrt_kw, 
                        src:fdoc::integer AS fdoc, 
                        src:flin::integer AS flin, 
                        src:fper::integer AS fper, 
                        src:frgd::datetime AS frgd, 
                        src:fsrl::integer AS fsrl, 
                        src:ftln::integer AS ftln, 
                        src:ftty::varchar AS ftty, 
                        src:fyea::integer AS fyea, 
                        src:guid::varchar AS guid, 
                        src:hccr_1::numeric(38, 17) AS hccr_1, 
                        src:hccr_2::numeric(38, 17) AS hccr_2, 
                        src:hccr_3::numeric(38, 17) AS hccr_3, 
                        src:idoc::integer AS idoc, 
                        src:iseq::integer AS iseq, 
                        src:itbp::varchar AS itbp, 
                        src:itbp_ref_compnr::integer AS itbp_ref_compnr, 
                        src:item::varchar AS item, 
                        src:item_ref_compnr::integer AS item_ref_compnr, 
                        src:itgd::varchar AS itgd, 
                        src:ityp::varchar AS ityp, 
                        src:koor::integer AS koor, 
                        src:koor_kw::varchar AS koor_kw, 
                        src:ltdt::datetime AS ltdt, 
                        src:nadv::integer AS nadv, 
                        src:ncmp::integer AS ncmp, 
                        src:nins::integer AS nins, 
                        src:ocmp::integer AS ocmp, 
                        src:ofbp::varchar AS ofbp, 
                        src:ofbp_ref_compnr::integer AS ofbp_ref_compnr, 
                        src:orno::varchar AS orno, 
                        src:peri::integer AS peri, 
                        src:pono::integer AS pono, 
                        src:potf::integer AS potf, 
                        src:potf_kw::varchar AS potf_kw, 
                        src:prdt::datetime AS prdt, 
                        src:rate_1::numeric(38, 17) AS rate_1, 
                        src:rate_2::numeric(38, 17) AS rate_2, 
                        src:rate_3::numeric(38, 17) AS rate_3, 
                        src:ratf_1::integer AS ratf_1, 
                        src:ratf_2::integer AS ratf_2, 
                        src:ratf_3::integer AS ratf_3, 
                        src:rdat::datetime AS rdat, 
                        src:rest::integer AS rest, 
                        src:rest_kw::varchar AS rest_kw, 
                        src:rfcr_1::integer AS rfcr_1, 
                        src:rfcr_2::integer AS rfcr_2, 
                        src:rfcr_3::integer AS rfcr_3, 
                        src:rgdt::datetime AS rgdt, 
                        src:rsst::integer AS rsst, 
                        src:rsst_kw::varchar AS rsst_kw, 
                        src:rtcr_1::numeric(38, 17) AS rtcr_1, 
                        src:rtcr_2::numeric(38, 17) AS rtcr_2, 
                        src:rtcr_3::numeric(38, 17) AS rtcr_3, 
                        src:rtyp::varchar AS rtyp, 
                        src:rtyp_ref_compnr::integer AS rtyp_ref_compnr, 
                        src:schd::integer AS schd, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:serb::integer AS serb, 
                        src:sern::integer AS sern, 
                        src:tetl::integer AS tetl, 
                        src:tetl_kw::varchar AS tetl_kw, 
                        src:timestamp::datetime AS timestamp, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:user::varchar AS user, 
                        src:username::varchar AS username, 
                        src:year::integer AS year, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:sern,
                src:cpro,
                src:cprj,
                src:cspa,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:sern,
                src:cpro,
                src:cprj,
                src:cspa,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TPPPC305 as strm))