CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TDPUR303 AS SELECT
                        src:cdis_1::varchar AS cdis_1, 
                        src:cdis_10::varchar AS cdis_10, 
                        src:cdis_11::varchar AS cdis_11, 
                        src:cdis_2::varchar AS cdis_2, 
                        src:cdis_3::varchar AS cdis_3, 
                        src:cdis_4::varchar AS cdis_4, 
                        src:cdis_5::varchar AS cdis_5, 
                        src:cdis_6::varchar AS cdis_6, 
                        src:cdis_7::varchar AS cdis_7, 
                        src:cdis_8::varchar AS cdis_8, 
                        src:cdis_9::varchar AS cdis_9, 
                        src:cofc::varchar AS cofc, 
                        src:compnr::integer AS compnr, 
                        src:cono::varchar AS cono, 
                        src:cono_pono_cofc_csqn_ref_compnr::integer AS cono_pono_cofc_csqn_ref_compnr, 
                        src:cpwc::integer AS cpwc, 
                        src:cpwc_kw::varchar AS cpwc_kw, 
                        src:csqn::integer AS csqn, 
                        src:cupp::varchar AS cupp, 
                        src:cupp_ref_compnr::integer AS cupp_ref_compnr, 
                        src:cvpp::numeric(38, 17) AS cvpp, 
                        src:deleted::boolean AS deleted, 
                        src:disc_1::numeric(38, 17) AS disc_1, 
                        src:disc_10::numeric(38, 17) AS disc_10, 
                        src:disc_11::numeric(38, 17) AS disc_11, 
                        src:disc_2::numeric(38, 17) AS disc_2, 
                        src:disc_3::numeric(38, 17) AS disc_3, 
                        src:disc_4::numeric(38, 17) AS disc_4, 
                        src:disc_5::numeric(38, 17) AS disc_5, 
                        src:disc_6::numeric(38, 17) AS disc_6, 
                        src:disc_7::numeric(38, 17) AS disc_7, 
                        src:disc_8::numeric(38, 17) AS disc_8, 
                        src:disc_9::numeric(38, 17) AS disc_9, 
                        src:dmth_1::integer AS dmth_1, 
                        src:dmth_10::integer AS dmth_10, 
                        src:dmth_11::integer AS dmth_11, 
                        src:dmth_2::integer AS dmth_2, 
                        src:dmth_3::integer AS dmth_3, 
                        src:dmth_4::integer AS dmth_4, 
                        src:dmth_5::integer AS dmth_5, 
                        src:dmth_6::integer AS dmth_6, 
                        src:dmth_7::integer AS dmth_7, 
                        src:dmth_8::integer AS dmth_8, 
                        src:dmth_9::integer AS dmth_9, 
                        src:dmth_kw_1::varchar AS dmth_kw_1, 
                        src:dmth_kw_10::varchar AS dmth_kw_10, 
                        src:dmth_kw_11::varchar AS dmth_kw_11, 
                        src:dmth_kw_2::varchar AS dmth_kw_2, 
                        src:dmth_kw_3::varchar AS dmth_kw_3, 
                        src:dmth_kw_4::varchar AS dmth_kw_4, 
                        src:dmth_kw_5::varchar AS dmth_kw_5, 
                        src:dmth_kw_6::varchar AS dmth_kw_6, 
                        src:dmth_kw_7::varchar AS dmth_kw_7, 
                        src:dmth_kw_8::varchar AS dmth_kw_8, 
                        src:dmth_kw_9::varchar AS dmth_kw_9, 
                        src:dsor::integer AS dsor, 
                        src:dsor_kw::varchar AS dsor_kw, 
                        src:dssc_1::varchar AS dssc_1, 
                        src:dssc_10::varchar AS dssc_10, 
                        src:dssc_11::varchar AS dssc_11, 
                        src:dssc_2::varchar AS dssc_2, 
                        src:dssc_3::varchar AS dssc_3, 
                        src:dssc_4::varchar AS dssc_4, 
                        src:dssc_5::varchar AS dssc_5, 
                        src:dssc_6::varchar AS dssc_6, 
                        src:dssc_7::varchar AS dssc_7, 
                        src:dssc_8::varchar AS dssc_8, 
                        src:dssc_9::varchar AS dssc_9, 
                        src:dtrm::integer AS dtrm, 
                        src:dtrm_kw::varchar AS dtrm_kw, 
                        src:elgb::integer AS elgb, 
                        src:elgb_kw::varchar AS elgb_kw, 
                        src:icap::integer AS icap, 
                        src:icap_kw::varchar AS icap_kw, 
                        src:ldam_1::numeric(38, 17) AS ldam_1, 
                        src:ldam_10::numeric(38, 17) AS ldam_10, 
                        src:ldam_11::numeric(38, 17) AS ldam_11, 
                        src:ldam_2::numeric(38, 17) AS ldam_2, 
                        src:ldam_3::numeric(38, 17) AS ldam_3, 
                        src:ldam_4::numeric(38, 17) AS ldam_4, 
                        src:ldam_5::numeric(38, 17) AS ldam_5, 
                        src:ldam_6::numeric(38, 17) AS ldam_6, 
                        src:ldam_7::numeric(38, 17) AS ldam_7, 
                        src:ldam_8::numeric(38, 17) AS ldam_8, 
                        src:ldam_9::numeric(38, 17) AS ldam_9, 
                        src:pbor::integer AS pbor, 
                        src:pbor_kw::varchar AS pbor_kw, 
                        src:pono::integer AS pono, 
                        src:prbk::varchar AS prbk, 
                        src:prbk_ref_compnr::integer AS prbk_ref_compnr, 
                        src:pric::numeric(38, 17) AS pric, 
                        src:prsg::varchar AS prsg, 
                        src:prsg_ref_compnr::integer AS prsg_ref_compnr, 
                        src:revn::integer AS revn, 
                        src:rsel::integer AS rsel, 
                        src:rsel_kw::varchar AS rsel_kw, 
                        src:sdat::datetime AS sdat, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:tapr::numeric(38, 17) AS tapr, 
                        src:timestamp::datetime AS timestamp, 
                        src:tpbk::varchar AS tpbk, 
                        src:tpbk_ref_compnr::integer AS tpbk_ref_compnr, 
                        src:tpbk_tpbl_ref_compnr::integer AS tpbk_tpbl_ref_compnr, 
                        src:tpbl::integer AS tpbl, 
                        src:txtr::integer AS txtr, 
                        src:txtr_ref_compnr::integer AS txtr_ref_compnr, 
                        src:username::varchar AS username, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:pono,
                src:csqn,
                src:compnr,
                src:cono,
                src:sdat,
                src:cofc,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:pono,
                src:csqn,
                src:compnr,
                src:cono,
                src:sdat,
                src:cofc  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TDPUR303 as strm))