CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_WHINH431 AS SELECT
                        src:acfl::integer AS acfl, 
                        src:aclr::integer AS aclr, 
                        src:aclr_kw::varchar AS aclr_kw, 
                        src:acti::object AS acti, 
                        src:addc::integer AS addc, 
                        src:addc_kw::varchar AS addc_kw, 
                        src:adin::varchar AS adin, 
                        src:adjs::integer AS adjs, 
                        src:adjs_kw::varchar AS adjs_kw, 
                        src:amnt::numeric(38, 17) AS amnt, 
                        src:aqty::numeric(38, 17) AS aqty, 
                        src:atse::varchar AS atse, 
                        src:atse_ref_compnr::integer AS atse_ref_compnr, 
                        src:atxt::integer AS atxt, 
                        src:atxt_ref_compnr::integer AS atxt_ref_compnr, 
                        src:bgxc::integer AS bgxc, 
                        src:bgxc_kw::varchar AS bgxc_kw, 
                        src:bolp::integer AS bolp, 
                        src:boml::integer AS boml, 
                        src:casi::varchar AS casi, 
                        src:casi_ref_compnr::integer AS casi_ref_compnr, 
                        src:cinv::integer AS cinv, 
                        src:circ::object AS circ, 
                        src:clot::varchar AS clot, 
                        src:compnr::integer AS compnr, 
                        src:cons::integer AS cons, 
                        src:cons_kw::varchar AS cons_kw, 
                        src:corn::object AS corn, 
                        src:csvc::varchar AS csvc, 
                        src:csvc_ref_compnr::integer AS csvc_ref_compnr, 
                        src:csvl::numeric(38, 17) AS csvl, 
                        src:ctyo::varchar AS ctyo, 
                        src:ctyo_ref_compnr::integer AS ctyo_ref_compnr, 
                        src:cuni::varchar AS cuni, 
                        src:cuni_ref_compnr::integer AS cuni_ref_compnr, 
                        src:cwar::varchar AS cwar, 
                        src:cwar_loca_ref_compnr::integer AS cwar_loca_ref_compnr, 
                        src:cwar_ref_compnr::integer AS cwar_ref_compnr, 
                        src:cwun::varchar AS cwun, 
                        src:cwun_ref_compnr::integer AS cwun_ref_compnr, 
                        src:darq::integer AS darq, 
                        src:darq_kw::varchar AS darq_kw, 
                        src:deleted::boolean AS deleted, 
                        src:dlpt::varchar AS dlpt, 
                        src:dphu::integer AS dphu, 
                        src:dphu_kw::varchar AS dphu_kw, 
                        src:dtxt::integer AS dtxt, 
                        src:dtxt_ref_compnr::integer AS dtxt_ref_compnr, 
                        src:effn::integer AS effn, 
                        src:effn_ref_compnr::integer AS effn_ref_compnr, 
                        src:fisc::integer AS fisc, 
                        src:fisc_kw::varchar AS fisc_kw, 
                        src:frsm::integer AS frsm, 
                        src:frsm_kw::varchar AS frsm_kw, 
                        src:grwt::numeric(38, 17) AS grwt, 
                        src:hubc::integer AS hubc, 
                        src:hubc_kw::varchar AS hubc_kw, 
                        src:huid::varchar AS huid, 
                        src:huid_ref_compnr::integer AS huid_ref_compnr, 
                        src:hupr::integer AS hupr, 
                        src:hupr_kw::varchar AS hupr_kw, 
                        src:iadj::integer AS iadj, 
                        src:iadj_kw::varchar AS iadj_kw, 
                        src:iadt::datetime AS iadt, 
                        src:idat::datetime AS idat, 
                        src:ilgd::datetime AS ilgd, 
                        src:invd::datetime AS invd, 
                        src:item::varchar AS item, 
                        src:item_clot_ref_compnr::integer AS item_clot_ref_compnr, 
                        src:item_ref_compnr::integer AS item_ref_compnr, 
                        src:itrd::datetime AS itrd, 
                        src:loca::varchar AS loca, 
                        src:manl::integer AS manl, 
                        src:manl_kw::varchar AS manl_kw, 
                        src:nspb::integer AS nspb, 
                        src:nspb_kw::varchar AS nspb_kw, 
                        src:ntwt::numeric(38, 17) AS ntwt, 
                        src:pbol::integer AS pbol, 
                        src:pbol_kw::varchar AS pbol_kw, 
                        src:pkdf::varchar AS pkdf, 
                        src:pmsk::varchar AS pmsk, 
                        src:pono::integer AS pono, 
                        src:psde::integer AS psde, 
                        src:psde_kw::varchar AS psde_kw, 
                        src:pwsq::integer AS pwsq, 
                        src:qadv::numeric(38, 17) AS qadv, 
                        src:qnpu::numeric(38, 17) AS qnpu, 
                        src:qnsh::numeric(38, 17) AS qnsh, 
                        src:qpic::numeric(38, 17) AS qpic, 
                        src:qppu::numeric(38, 17) AS qppu, 
                        src:qprv::numeric(38, 17) AS qprv, 
                        src:qrcp::numeric(38, 17) AS qrcp, 
                        src:qshp::numeric(38, 17) AS qshp, 
                        src:qspu::numeric(38, 17) AS qspu, 
                        src:recd::varchar AS recd, 
                        src:recd_ref_compnr::integer AS recd_ref_compnr, 
                        src:refe::object AS refe, 
                        src:refs::object AS refs, 
                        src:rowc::integer AS rowc, 
                        src:rowc_ref_compnr::integer AS rowc_ref_compnr, 
                        src:rown::varchar AS rown, 
                        src:rown_ref_compnr::integer AS rown_ref_compnr, 
                        src:rqty::numeric(38, 17) AS rqty, 
                        src:rseq::integer AS rseq, 
                        src:sarq::integer AS sarq, 
                        src:sarq_kw::varchar AS sarq_kw, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:serl::varchar AS serl, 
                        src:serp::integer AS serp, 
                        src:serp_kw::varchar AS serp_kw, 
                        src:shpm::varchar AS shpm, 
                        src:shpm_ref_compnr::integer AS shpm_ref_compnr, 
                        src:shst::integer AS shst, 
                        src:shst_kw::varchar AS shst_kw, 
                        src:shvl::integer AS shvl, 
                        src:shvl_kw::varchar AS shvl_kw, 
                        src:sppk::integer AS sppk, 
                        src:sppk_kw::varchar AS sppk_kw, 
                        src:ssqd::integer AS ssqd, 
                        src:stad::varchar AS stad, 
                        src:stad_dlpt_ref_compnr::integer AS stad_dlpt_ref_compnr, 
                        src:stad_ref_compnr::integer AS stad_ref_compnr, 
                        src:sttg::varchar AS sttg, 
                        src:tcst::integer AS tcst, 
                        src:tcst_kw::varchar AS tcst_kw, 
                        src:text::integer AS text, 
                        src:text_ref_compnr::integer AS text_ref_compnr, 
                        src:timestamp::datetime AS timestamp, 
                        src:ttyp::varchar AS ttyp, 
                        src:username::varchar AS username, 
                        src:worg::integer AS worg, 
                        src:worg_kw::varchar AS worg_kw, 
                        src:worn::varchar AS worn, 
                        src:worn_wpon_pwsq_ssqd_ref_compnr::integer AS worn_wpon_pwsq_ssqd_ref_compnr, 
                        src:wpon::integer AS wpon, 
                        src:wseq::integer AS wseq, 
                        src:wset::integer AS wset, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:shpm,
                src:pono,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:shpm,
                src:pono,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_WHINH431 as strm))