CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TCCOM120 AS SELECT
                        src:ackx::integer AS ackx, 
                        src:ackx_kw::varchar AS ackx_kw, 
                        src:afrb::integer AS afrb, 
                        src:afrb_kw::varchar AS afrb_kw, 
                        src:asbs::integer AS asbs, 
                        src:asbs_kw::varchar AS asbs_kw, 
                        src:bppr::varchar AS bppr, 
                        src:bppr_ref_compnr::integer AS bppr_ref_compnr, 
                        src:bpst::integer AS bpst, 
                        src:bpst_kw::varchar AS bpst_kw, 
                        src:bpus::varchar AS bpus, 
                        src:bpus_ref_compnr::integer AS bpus_ref_compnr, 
                        src:cadr::varchar AS cadr, 
                        src:cadr_ref_compnr::integer AS cadr_ref_compnr, 
                        src:cbps::varchar AS cbps, 
                        src:cbps_ref_compnr::integer AS cbps_ref_compnr, 
                        src:cbrn::varchar AS cbrn, 
                        src:cbrn_ref_compnr::integer AS cbrn_ref_compnr, 
                        src:cbtp::varchar AS cbtp, 
                        src:cbtp_ref_compnr::integer AS cbtp_ref_compnr, 
                        src:ccal::varchar AS ccal, 
                        src:ccal_ref_compnr::integer AS ccal_ref_compnr, 
                        src:ccnt::varchar AS ccnt, 
                        src:ccnt_ref_compnr::integer AS ccnt_ref_compnr, 
                        src:ccon::varchar AS ccon, 
                        src:ccon_ref_compnr::integer AS ccon_ref_compnr, 
                        src:cdec::varchar AS cdec, 
                        src:cdec_ref_compnr::integer AS cdec_ref_compnr, 
                        src:clan::varchar AS clan, 
                        src:clan_ref_compnr::integer AS clan_ref_compnr, 
                        src:clgr::varchar AS clgr, 
                        src:clgr_ref_compnr::integer AS clgr_ref_compnr, 
                        src:cofc::varchar AS cofc, 
                        src:compnr::integer AS compnr, 
                        src:cplp::varchar AS cplp, 
                        src:cplp_ref_compnr::integer AS cplp_ref_compnr, 
                        src:crdt::datetime AS crdt, 
                        src:creg::varchar AS creg, 
                        src:creg_ref_compnr::integer AS creg_ref_compnr, 
                        src:crrf::integer AS crrf, 
                        src:crrf_kw::varchar AS crrf_kw, 
                        src:deleted::boolean AS deleted, 
                        src:dlid::varchar AS dlid, 
                        src:dlpe::integer AS dlpe, 
                        src:dlpu::integer AS dlpu, 
                        src:dlpu_kw::varchar AS dlpu_kw, 
                        src:dset::varchar AS dset, 
                        src:dset_ref_compnr::integer AS dset_ref_compnr, 
                        src:encd::integer AS encd, 
                        src:encd_kw::varchar AS encd_kw, 
                        src:endt::datetime AS endt, 
                        src:frin::integer AS frin, 
                        src:frin_kw::varchar AS frin_kw, 
                        src:ifbp::varchar AS ifbp, 
                        src:ifbp_ref_compnr::integer AS ifbp_ref_compnr, 
                        src:itgr::varchar AS itgr, 
                        src:itgr_ref_compnr::integer AS itgr_ref_compnr, 
                        src:lcmp::integer AS lcmp, 
                        src:lcmp_ref_compnr::integer AS lcmp_ref_compnr, 
                        src:lmdt::datetime AS lmdt, 
                        src:lmus::varchar AS lmus, 
                        src:mcfr::integer AS mcfr, 
                        src:mcfr_kw::varchar AS mcfr_kw, 
                        src:mesv::integer AS mesv, 
                        src:mesv_kw::varchar AS mesv_kw, 
                        src:nasu::varchar AS nasu, 
                        src:nasu_ref_compnr::integer AS nasu_ref_compnr, 
                        src:ocus::varchar AS ocus, 
                        src:odis::numeric(38, 17) AS odis, 
                        src:otbp::varchar AS otbp, 
                        src:otbp_ref_compnr::integer AS otbp_ref_compnr, 
                        src:paft::integer AS paft, 
                        src:paft_kw::varchar AS paft_kw, 
                        src:potp::varchar AS potp, 
                        src:ptpa::varchar AS ptpa, 
                        src:ptpa_ref_compnr::integer AS ptpa_ref_compnr, 
                        src:raur::integer AS raur, 
                        src:raur_kw::varchar AS raur_kw, 
                        src:rdec::varchar AS rdec, 
                        src:rdec_ref_compnr::integer AS rdec_ref_compnr, 
                        src:retp::numeric(38, 17) AS retp, 
                        src:sbdt::integer AS sbdt, 
                        src:sbdt_kw::varchar AS sbdt_kw, 
                        src:sbil::integer AS sbil, 
                        src:sbil_kw::varchar AS sbil_kw, 
                        src:sbrf::varchar AS sbrf, 
                        src:sbvf::datetime AS sbvf, 
                        src:sbvt::datetime AS sbvt, 
                        src:scqq::integer AS scqq, 
                        src:scqq_kw::varchar AS scqq_kw, 
                        src:seak::object AS seak, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:sfbp::varchar AS sfbp, 
                        src:sfbp_ref_compnr::integer AS sfbp_ref_compnr, 
                        src:sigr::varchar AS sigr, 
                        src:spot::varchar AS spot, 
                        src:srtr::varchar AS srtr, 
                        src:srtr_ref_compnr::integer AS srtr_ref_compnr, 
                        src:stdt::datetime AS stdt, 
                        src:tefx::varchar AS tefx, 
                        src:telp::varchar AS telp, 
                        src:tfci::varchar AS tfci, 
                        src:tfcy::varchar AS tfcy, 
                        src:tfex::varchar AS tfex, 
                        src:tfln::varchar AS tfln, 
                        src:timestamp::datetime AS timestamp, 
                        src:tira::integer AS tira, 
                        src:tira_kw::varchar AS tira_kw, 
                        src:tlci::varchar AS tlci, 
                        src:tlcy::varchar AS tlcy, 
                        src:tlex::varchar AS tlex, 
                        src:tlln::varchar AS tlln, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:ucnd::integer AS ucnd, 
                        src:ucnd_kw::varchar AS ucnd_kw, 
                        src:user::varchar AS user, 
                        src:username::varchar AS username, 
                        src:vryn::integer AS vryn, 
                        src:vryn_kw::varchar AS vryn_kw, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:compnr,
                src:otbp,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:compnr,
                src:otbp  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TCCOM120 as strm))