CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TDSLS311 AS SELECT
                        src:adin::varchar AS adin, 
                        src:aitc::object AS aitc, 
                        src:bpcl::varchar AS bpcl, 
                        src:bpcl_ref_compnr::integer AS bpcl_ref_compnr, 
                        src:cbrn::varchar AS cbrn, 
                        src:cbrn_ref_compnr::integer AS cbrn_ref_compnr, 
                        src:ccof::varchar AS ccof, 
                        src:ccof_ref_compnr::integer AS ccof_ref_compnr, 
                        src:ccrf::object AS ccrf, 
                        src:ccrs::varchar AS ccrs, 
                        src:ccrs_ref_compnr::integer AS ccrs_ref_compnr, 
                        src:ccty::varchar AS ccty, 
                        src:ccur::varchar AS ccur, 
                        src:ccur_ref_compnr::integer AS ccur_ref_compnr, 
                        src:cdec::varchar AS cdec, 
                        src:cdec_ref_compnr::integer AS cdec_ref_compnr, 
                        src:cfrw::varchar AS cfrw, 
                        src:cfrw_ref_compnr::integer AS cfrw_ref_compnr, 
                        src:citm::object AS citm, 
                        src:citt::varchar AS citt, 
                        src:citt_ref_compnr::integer AS citt_ref_compnr, 
                        src:cofc::varchar AS cofc, 
                        src:cofc_ref_compnr::integer AS cofc_ref_compnr, 
                        src:compnr::integer AS compnr, 
                        src:cono::varchar AS cono, 
                        src:cono_pono_ccof_ref_compnr::integer AS cono_pono_ccof_ref_compnr, 
                        src:cono_ref_compnr::integer AS cono_ref_compnr, 
                        src:cons::integer AS cons, 
                        src:cons_kw::varchar AS cons_kw, 
                        src:corg::integer AS corg, 
                        src:corg_kw::varchar AS corg_kw, 
                        src:corn::object AS corn, 
                        src:cpay::varchar AS cpay, 
                        src:cpay_ref_compnr::integer AS cpay_ref_compnr, 
                        src:creg::varchar AS creg, 
                        src:creg_ref_compnr::integer AS creg_ref_compnr, 
                        src:csdt::datetime AS csdt, 
                        src:cvyn::integer AS cvyn, 
                        src:cvyn_kw::varchar AS cvyn_kw, 
                        src:cwar::varchar AS cwar, 
                        src:cwar_ref_compnr::integer AS cwar_ref_compnr, 
                        src:delc::varchar AS delc, 
                        src:delc_ref_compnr::integer AS delc_ref_compnr, 
                        src:deleted::boolean AS deleted, 
                        src:dest::integer AS dest, 
                        src:dest_kw::varchar AS dest_kw, 
                        src:edfb::datetime AS edfb, 
                        src:edrw::datetime AS edrw, 
                        src:effn::integer AS effn, 
                        src:effn_ref_compnr::integer AS effn_ref_compnr, 
                        src:excp::integer AS excp, 
                        src:excp_kw::varchar AS excp_kw, 
                        src:fcrt::integer AS fcrt, 
                        src:fcrt_kw::varchar AS fcrt_kw, 
                        src:fdpt::varchar AS fdpt, 
                        src:fdpt_ref_compnr::integer AS fdpt_ref_compnr, 
                        src:gdat::datetime AS gdat, 
                        src:hiss::integer AS hiss, 
                        src:hiss_kw::varchar AS hiss_kw, 
                        src:hold::integer AS hold, 
                        src:hold_kw::varchar AS hold_kw, 
                        src:itad::varchar AS itad, 
                        src:itad_ref_compnr::integer AS itad_ref_compnr, 
                        src:itbp::varchar AS itbp, 
                        src:itbp_ref_compnr::integer AS itbp_ref_compnr, 
                        src:item::varchar AS item, 
                        src:item_ref_compnr::integer AS item_ref_compnr, 
                        src:item_site_ref_compnr::integer AS item_site_ref_compnr, 
                        src:lasn::varchar AS lasn, 
                        src:lrdt::datetime AS lrdt, 
                        src:lsel::integer AS lsel, 
                        src:lsel_kw::varchar AS lsel_kw, 
                        src:lsid::varchar AS lsid, 
                        src:ltcs::integer AS ltcs, 
                        src:ltcs_kw::varchar AS ltcs_kw, 
                        src:motv::varchar AS motv, 
                        src:motv_ref_compnr::integer AS motv_ref_compnr, 
                        src:odis::numeric(38, 17) AS odis, 
                        src:ofad::varchar AS ofad, 
                        src:ofad_ref_compnr::integer AS ofad_ref_compnr, 
                        src:ofbp::varchar AS ofbp, 
                        src:ofbp_ref_compnr::integer AS ofbp_ref_compnr, 
                        src:ofcn::varchar AS ofcn, 
                        src:ofcn_ref_compnr::integer AS ofcn_ref_compnr, 
                        src:osch::varchar AS osch, 
                        src:osrp::varchar AS osrp, 
                        src:osrp_ref_compnr::integer AS osrp_ref_compnr, 
                        src:paym::varchar AS paym, 
                        src:pfad::varchar AS pfad, 
                        src:pfad_ref_compnr::integer AS pfad_ref_compnr, 
                        src:pfbp::varchar AS pfbp, 
                        src:pfbp_ref_compnr::integer AS pfbp_ref_compnr, 
                        src:plan::varchar AS plan, 
                        src:plan_ref_compnr::integer AS plan_ref_compnr, 
                        src:pono::integer AS pono, 
                        src:ptpa::varchar AS ptpa, 
                        src:ptpa_ref_compnr::integer AS ptpa_ref_compnr, 
                        src:qici::numeric(38, 17) AS qici, 
                        src:qicp::numeric(38, 17) AS qicp, 
                        src:qicr::numeric(38, 17) AS qicr, 
                        src:qics::numeric(38, 17) AS qics, 
                        src:qifa::numeric(38, 17) AS qifa, 
                        src:qifh::numeric(38, 17) AS qifh, 
                        src:qilr::numeric(38, 17) AS qilr, 
                        src:qira::numeric(38, 17) AS qira, 
                        src:qirh::numeric(38, 17) AS qirh, 
                        src:ratd::datetime AS ratd, 
                        src:ratf_1::integer AS ratf_1, 
                        src:ratf_2::integer AS ratf_2, 
                        src:ratf_3::integer AS ratf_3, 
                        src:rats_1::numeric(38, 17) AS rats_1, 
                        src:rats_2::numeric(38, 17) AS rats_2, 
                        src:rats_3::numeric(38, 17) AS rats_3, 
                        src:ratt::varchar AS ratt, 
                        src:ratt_ref_compnr::integer AS ratt_ref_compnr, 
                        src:revi::varchar AS revi, 
                        src:revn::integer AS revn, 
                        src:rsiu::integer AS rsiu, 
                        src:rsiu_kw::varchar AS rsiu_kw, 
                        src:rviu::integer AS rviu, 
                        src:rviu_kw::varchar AS rviu_kw, 
                        src:sbim::integer AS sbim, 
                        src:sbim_kw::varchar AS sbim_kw, 
                        src:schn::varchar AS schn, 
                        src:sctp::integer AS sctp, 
                        src:sctp_kw::varchar AS sctp_kw, 
                        src:sdsc::integer AS sdsc, 
                        src:sdsc_kw::varchar AS sdsc_kw, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:site::varchar AS site, 
                        src:site_ref_compnr::integer AS site_ref_compnr, 
                        src:sllr::varchar AS sllr, 
                        src:sllr_ref_compnr::integer AS sllr_ref_compnr, 
                        src:sodb::integer AS sodb, 
                        src:sodb_kw::varchar AS sodb_kw, 
                        src:stad::varchar AS stad, 
                        src:stad_ref_compnr::integer AS stad_ref_compnr, 
                        src:stat::integer AS stat, 
                        src:stat_kw::varchar AS stat_kw, 
                        src:stbp::varchar AS stbp, 
                        src:stbp_ref_compnr::integer AS stbp_ref_compnr, 
                        src:stcn::varchar AS stcn, 
                        src:stcn_ref_compnr::integer AS stcn_ref_compnr, 
                        src:strc::varchar AS strc, 
                        src:strc_ref_compnr::integer AS strc_ref_compnr, 
                        src:timestamp::datetime AS timestamp, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:ucms::integer AS ucms, 
                        src:ucms_kw::varchar AS ucms_kw, 
                        src:ucos::integer AS ucos, 
                        src:ucos_kw::varchar AS ucos_kw, 
                        src:username::varchar AS username, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:schn,
                src:sctp,
                src:revn,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:schn,
                src:sctp,
                src:revn,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TDSLS311 as strm))