CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_WHINR110 AS SELECT
                        src:atse::varchar AS atse, 
                        src:atse_ref_compnr::integer AS atse_ref_compnr, 
                        src:bfbp::varchar AS bfbp, 
                        src:boml::integer AS boml, 
                        src:bpid::varchar AS bpid, 
                        src:bpid_ref_compnr::integer AS bpid_ref_compnr, 
                        src:cact::varchar AS cact, 
                        src:ccco::varchar AS ccco, 
                        src:chan::varchar AS chan, 
                        src:chan_ref_compnr::integer AS chan_ref_compnr, 
                        src:cinv::integer AS cinv, 
                        src:clot::varchar AS clot, 
                        src:compnr::integer AS compnr, 
                        src:cons::integer AS cons, 
                        src:cons_kw::varchar AS cons_kw, 
                        src:cosv::integer AS cosv, 
                        src:cosv_kw::varchar AS cosv_kw, 
                        src:cprj::varchar AS cprj, 
                        src:cprj_ref_compnr::integer AS cprj_ref_compnr, 
                        src:cspa::varchar AS cspa, 
                        src:cstl::varchar AS cstl, 
                        src:ctrr::integer AS ctrr, 
                        src:ctrr_kw::varchar AS ctrr_kw, 
                        src:cwar::varchar AS cwar, 
                        src:cwar_ref_compnr::integer AS cwar_ref_compnr, 
                        src:deleted::boolean AS deleted, 
                        src:dlin::integer AS dlin, 
                        src:effn::integer AS effn, 
                        src:effn_ref_compnr::integer AS effn_ref_compnr, 
                        src:ilgd::datetime AS ilgd, 
                        src:invd::datetime AS invd, 
                        src:iseq::integer AS iseq, 
                        src:item::varchar AS item, 
                        src:item_ref_compnr::integer AS item_ref_compnr, 
                        src:itid::varchar AS itid, 
                        src:itrd::datetime AS itrd, 
                        src:itse::integer AS itse, 
                        src:koor::integer AS koor, 
                        src:koor_kw::varchar AS koor_kw, 
                        src:kost::integer AS kost, 
                        src:kost_kw::varchar AS kost_kw, 
                        src:lgdt::datetime AS lgdt, 
                        src:logn::varchar AS logn, 
                        src:oats::varchar AS oats, 
                        src:oats_ref_compnr::integer AS oats_ref_compnr, 
                        src:ocmp::integer AS ocmp, 
                        src:ocmp_ref_compnr::integer AS ocmp_ref_compnr, 
                        src:orno::varchar AS orno, 
                        src:ownr::varchar AS ownr, 
                        src:owns::integer AS owns, 
                        src:owns_kw::varchar AS owns_kw, 
                        src:phtr::integer AS phtr, 
                        src:phtr_kw::varchar AS phtr_kw, 
                        src:pono::integer AS pono, 
                        src:prjp::integer AS prjp, 
                        src:prjp_kw::varchar AS prjp_kw, 
                        src:prnt::integer AS prnt, 
                        src:prnt_kw::varchar AS prnt_kw, 
                        src:pyps::integer AS pyps, 
                        src:qaiu::numeric(38, 17) AS qaiu, 
                        src:qapu::numeric(38, 17) AS qapu, 
                        src:qhnd::numeric(38, 17) AS qhnd, 
                        src:qhnd_buar::numeric(38, 17) AS qhnd_buar, 
                        src:qhnd_buln::numeric(38, 17) AS qhnd_buln, 
                        src:qhnd_buvl::numeric(38, 17) AS qhnd_buvl, 
                        src:qhnd_buwg::numeric(38, 17) AS qhnd_buwg, 
                        src:qipu::numeric(38, 17) AS qipu, 
                        src:qstk::numeric(38, 17) AS qstk, 
                        src:qstk_buar::numeric(38, 17) AS qstk_buar, 
                        src:qstk_buln::numeric(38, 17) AS qstk_buln, 
                        src:qstk_buvl::numeric(38, 17) AS qstk_buvl, 
                        src:qstk_buwg::numeric(38, 17) AS qstk_buwg, 
                        src:rcln::integer AS rcln, 
                        src:rcno::varchar AS rcno, 
                        src:reco::integer AS reco, 
                        src:reco_kw::varchar AS reco_kw, 
                        src:reje::integer AS reje, 
                        src:reje_kw::varchar AS reje_kw, 
                        src:rowc::integer AS rowc, 
                        src:rowc_ref_compnr::integer AS rowc_ref_compnr, 
                        src:rown::varchar AS rown, 
                        src:rown_ref_compnr::integer AS rown_ref_compnr, 
                        src:seqn::integer AS seqn, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:serl::varchar AS serl, 
                        src:shpm::varchar AS shpm, 
                        src:shpo::integer AS shpo, 
                        src:site::varchar AS site, 
                        src:site_ref_compnr::integer AS site_ref_compnr, 
                        src:spcn::varchar AS spcn, 
                        src:srnb::integer AS srnb, 
                        src:tagn::varchar AS tagn, 
                        src:timestamp::datetime AS timestamp, 
                        src:trdt::datetime AS trdt, 
                        src:ttyp::varchar AS ttyp, 
                        src:username::varchar AS username, 
                        src:valm::integer AS valm, 
                        src:valm_kw::varchar AS valm_kw, 
                        src:vbas::integer AS vbas, 
                        src:vbas_kw::varchar AS vbas_kw, 
                        src:vwvg::integer AS vwvg, 
                        src:vwvg_kw::varchar AS vwvg_kw, 
                        src:wvgr::varchar AS wvgr, 
                        src:wvgr_ref_compnr::integer AS wvgr_ref_compnr, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:item,
                src:seqn,
                src:trdt,
                src:cwar,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:item,
                src:seqn,
                src:trdt,
                src:cwar,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_WHINR110 as strm))