CREATE OR REPLACE VIEW DATAHUB_EXTRACT.VW_STREAM_SM_MECHANICAL_METERS(
    ACCOUNTID,
    READINGTIME,
    WATERUSAGE,
    BILLINGPERIODFROMDATE,
    BILLINGPERIODTODATE,
    ISESTIMATE
) AS
SELECT 
    A.ACCOUNTNUMBER AS accountId,
    CONCAT(convert_timezone('UTC',(B.BILLPERTODATE)),'#',B.BILLKEY) AS ReadingTime,     
    SUM(C.CONVERTEDUNITS) * 1000 AS waterUsage,
    to_timestamp_ltz(convert_timezone('Pacific/Auckland',(B.BILLPERFRDATE))) as billingPeriodFromDate,
    to_timestamp_ltz(convert_timezone('Pacific/Auckland',(B.BILLPERTODATE))) as billingPeriodToDate,
    B.ESTIMATEFLAG AS isEstimate
FROM(
    SELECT B1.ACCOUNTKEY,B1.BILLKEY, B1.BILLPERFRDATE, B1.BILLPERTODATE, B1.ESTIMATEFLAG 
    FROM DATAHUB_TARGET.IPS_BILLING_BILL B1 
    WHERE NOT EXISTS (
        SELECT DISTINCT B2.BILLKEY 
        FROM DATAHUB_TARGET.IPS_BILLING_BILL B2 
        INNER JOIN DATAHUB_TARGET.IPS_BILLING_WATERTRACKEDREADING W ON 
            W.BILLKEY=B2.BILLKEY 
        INNER JOIN DATAHUB_TARGET.IPS_ASSETMANAGEMENT_WATER_METERREADING R ON 
            R.READINGKEY=W.READINGKEY 
        INNER JOIN DATAHUB_TARGET.IPS_ASSETMANAGEMENT_WATER_COMPWMTR M ON M.COMPKEY=R.COMPKEY
        WHERE M.UNITTYPE LIKE 'MTSRD%'
        AND B2.BILLKEY=B1.BILLKEY)
    AND B1.REVERSEFLAG='N' -- exclude reversed bills
    AND B1.BILLTYPEKEY=1002 -- exclude other bill types
    ) B 
INNER JOIN DATAHUB_EXTRACT.STREAM_SM_MECHANICAL_METERS L ON 
    L.BILLKEY=B.BILLKEY 
INNER JOIN DATAHUB_TARGET.IPS_BILLING_LINEITEMSETUP LS ON 
    LS.LINEITEMSETUPKEY=L.LINEITEMSETUPKEY 
INNER JOIN DATAHUB_TARGET.IPS_BILLING_LINEITEMRATE R ON 
    R.LINEITEMKEY=L.LINEITEMKEY 
INNER JOIN DATAHUB_TARGET.IPS_RESOURCES_RATETABLE_CALCULATIONDETAIL C ON 
    C.CALCULATIONDETAILKEY=R.CALCULATIONDETAILKEY 
INNER JOIN DATAHUB_TARGET.IPS_BILLING_ACCOUNT A 
    ON A.ACCOUNTKEY=B.ACCOUNTKEY 
WHERE LS.LINEITEM='Water' --water usage only
GROUP BY A.ACCOUNTNUMBER,
    B.BILLKEY,
    B.BILLPERFRDATE,
    B.BILLPERTODATE,
    B.ESTIMATEFLAG