CREATE OR REPLACE TABLE TARGET_LN.LN_TDPUR303(
            cdis_1 varchar, 
            cdis_10 varchar, 
            cdis_11 varchar, 
            cdis_2 varchar, 
            cdis_3 varchar, 
            cdis_4 varchar, 
            cdis_5 varchar, 
            cdis_6 varchar, 
            cdis_7 varchar, 
            cdis_8 varchar, 
            cdis_9 varchar, 
            cofc varchar, 
            compnr integer, 
            cono varchar, 
            cono_pono_cofc_csqn_ref_compnr integer, 
            cpwc integer, 
            cpwc_kw varchar, 
            csqn integer, 
            cupp varchar, 
            cupp_ref_compnr integer, 
            cvpp numeric(38, 17), 
            deleted boolean, 
            disc_1 numeric(38, 17), 
            disc_10 numeric(38, 17), 
            disc_11 numeric(38, 17), 
            disc_2 numeric(38, 17), 
            disc_3 numeric(38, 17), 
            disc_4 numeric(38, 17), 
            disc_5 numeric(38, 17), 
            disc_6 numeric(38, 17), 
            disc_7 numeric(38, 17), 
            disc_8 numeric(38, 17), 
            disc_9 numeric(38, 17), 
            dmth_1 integer, 
            dmth_10 integer, 
            dmth_11 integer, 
            dmth_2 integer, 
            dmth_3 integer, 
            dmth_4 integer, 
            dmth_5 integer, 
            dmth_6 integer, 
            dmth_7 integer, 
            dmth_8 integer, 
            dmth_9 integer, 
            dmth_kw_1 varchar, 
            dmth_kw_10 varchar, 
            dmth_kw_11 varchar, 
            dmth_kw_2 varchar, 
            dmth_kw_3 varchar, 
            dmth_kw_4 varchar, 
            dmth_kw_5 varchar, 
            dmth_kw_6 varchar, 
            dmth_kw_7 varchar, 
            dmth_kw_8 varchar, 
            dmth_kw_9 varchar, 
            dsor integer, 
            dsor_kw varchar, 
            dssc_1 varchar, 
            dssc_10 varchar, 
            dssc_11 varchar, 
            dssc_2 varchar, 
            dssc_3 varchar, 
            dssc_4 varchar, 
            dssc_5 varchar, 
            dssc_6 varchar, 
            dssc_7 varchar, 
            dssc_8 varchar, 
            dssc_9 varchar, 
            dtrm integer, 
            dtrm_kw varchar, 
            elgb integer, 
            elgb_kw varchar, 
            icap integer, 
            icap_kw varchar, 
            ldam_1 numeric(38, 17), 
            ldam_10 numeric(38, 17), 
            ldam_11 numeric(38, 17), 
            ldam_2 numeric(38, 17), 
            ldam_3 numeric(38, 17), 
            ldam_4 numeric(38, 17), 
            ldam_5 numeric(38, 17), 
            ldam_6 numeric(38, 17), 
            ldam_7 numeric(38, 17), 
            ldam_8 numeric(38, 17), 
            ldam_9 numeric(38, 17), 
            pbor integer, 
            pbor_kw varchar, 
            pono integer, 
            prbk varchar, 
            prbk_ref_compnr integer, 
            pric numeric(38, 17), 
            prsg varchar, 
            prsg_ref_compnr integer, 
            revn integer, 
            rsel integer, 
            rsel_kw varchar, 
            sdat datetime, 
            sequencenumber integer, 
            tapr numeric(38, 17), 
            timestamp datetime, 
            tpbk varchar, 
            tpbk_ref_compnr integer, 
            tpbk_tpbl_ref_compnr integer, 
            tpbl integer, 
            txtr integer, 
            txtr_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 