CREATE OR REPLACE TABLE TARGET_LN.LN_TPPSS210(
            compnr integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_pact_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cpla_sact_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            deleted boolean, 
            ffno varchar, 
            lead numeric(38, 17), 
            llpc integer, 
            pact varchar, 
            pcot integer, 
            pcot_kw varchar, 
            psen integer, 
            rest integer, 
            rest_kw varchar, 
            rltp integer, 
            rltp_kw varchar, 
            sact varchar, 
            scot integer, 
            scot_kw varchar, 
            sequencenumber integer, 
            ssen integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 