CREATE OR REPLACE TABLE TARGET_LN.LN_TPCTM100(
            acpn integer, 
            acpn_kw varchar, 
            adin varchar, 
            adtp integer, 
            adtp_kw varchar, 
            advn integer, 
            advn_kw varchar, 
            bcrp integer, 
            bcrp_kw varchar, 
            blcl varchar, 
            blcl_ref_compnr integer, 
            bnum varchar, 
            bver varchar, 
            cban varchar, 
            cbrn varchar, 
            cbrn_ref_compnr integer, 
            ccam varchar, 
            ccam_ref_compnr integer, 
            ccat varchar, 
            ccat_ref_compnr integer, 
            ccot varchar, 
            ccot_ref_compnr integer, 
            ccrs varchar, 
            ccrs_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            cfac varchar, 
            cfac_ref_compnr integer, 
            cidm varchar, 
            cidm_ref_compnr integer, 
            cinm varchar, 
            cinm_ref_compnr integer, 
            cmng varchar, 
            cmng_ref_compnr integer, 
            codt datetime, 
            cofc varchar, 
            cofc_ref_compnr integer, 
            compnr integer, 
            cono varchar, 
            cono_fcmp integer, 
            copr numeric(38, 17), 
            copr_dwhc numeric(38, 17), 
            copr_homc numeric(38, 17), 
            copr_refc numeric(38, 17), 
            copr_rpc1 numeric(38, 17), 
            copr_rpc2 numeric(38, 17), 
            coty integer, 
            coty_kw varchar, 
            cpay varchar, 
            cpay_ref_compnr integer, 
            cprj varchar, 
            cprj_bver_bnum_ref_compnr integer, 
            cprj_ref_compnr integer, 
            crby varchar, 
            crdt datetime, 
            creg varchar, 
            creg_ref_compnr integer, 
            crep varchar, 
            crep_ref_compnr integer, 
            csec varchar, 
            csec_ref_compnr integer, 
            cstg varchar, 
            cstg_ref_compnr integer, 
            csts integer, 
            csts_kw varchar, 
            ctyp integer, 
            ctyp_kw varchar, 
            deleted boolean, 
            desc object, 
            dfis varchar, 
            dfis_ref_compnr integer, 
            disc numeric(38, 17), 
            efdt datetime, 
            enip integer, 
            enip_kw varchar, 
            exdt datetime, 
            fcrt integer, 
            fcrt_kw varchar, 
            fdis integer, 
            fdis_kw varchar, 
            frvt numeric(38, 17), 
            guid varchar, 
            hbpc numeric(38, 17), 
            hldb integer, 
            hldb_kw varchar, 
            hrsn varchar, 
            hrsn_ref_compnr integer, 
            invm integer, 
            invm_kw varchar, 
            itad varchar, 
            itad_ref_compnr integer, 
            itbp varchar, 
            itbp_ref_compnr integer, 
            itcn varchar, 
            itcn_ref_compnr integer, 
            itod numeric(38, 17), 
            itod_dwhc numeric(38, 17), 
            itod_homc numeric(38, 17), 
            itod_refc numeric(38, 17), 
            itod_rpc1 numeric(38, 17), 
            itod_rpc2 numeric(38, 17), 
            ivam numeric(38, 17), 
            ivam_dwhc numeric(38, 17), 
            ivam_homc numeric(38, 17), 
            ivam_refc numeric(38, 17), 
            ivam_rpc1 numeric(38, 17), 
            ivam_rpc2 numeric(38, 17), 
            lcrs varchar, 
            lcrs_ref_compnr integer, 
            lmdt datetime, 
            lmus varchar, 
            lpad numeric(38, 17), 
            lpin numeric(38, 17), 
            ltti date, 
            ofad varchar, 
            ofad_ref_compnr integer, 
            ofbp varchar, 
            ofbp_ref_compnr integer, 
            ofcn varchar, 
            ofcn_ref_compnr integer, 
            osrp varchar, 
            osrp_ref_compnr integer, 
            paym varchar, 
            pcba numeric(38, 17), 
            pcwa numeric(38, 17), 
            pfad varchar, 
            pfad_ref_compnr integer, 
            pfbp varchar, 
            pfbp_ref_compnr integer, 
            pfcn varchar, 
            pfcn_ref_compnr integer, 
            pgpm integer, 
            pgpm_kw varchar, 
            plpc numeric(38, 17), 
            pmng varchar, 
            pmng_ref_compnr integer, 
            poin integer, 
            ppim varchar, 
            ppim_ref_compnr integer, 
            pppc numeric(38, 17), 
            prgm varchar, 
            prgm_ref_compnr integer, 
            prst integer, 
            prst_kw varchar, 
            prtx integer, 
            prtx_kw varchar, 
            ptpp varchar, 
            ptpp_ref_compnr integer, 
            ptsh numeric(38, 17), 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rdat datetime, 
            refb object, 
            refe object, 
            rtyp varchar, 
            rtyp_ref_compnr integer, 
            seak object, 
            sequencenumber integer, 
            styp varchar, 
            styp_ref_compnr integer, 
            text integer, 
            text_ref_compnr integer, 
            timestamp datetime, 
            tins integer, 
            tins_kw varchar, 
            ulpd integer, 
            ulpd_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 