CREATE OR REPLACE TABLE TARGET_LN.LN_TPPIN080(
            bpcl varchar, 
            bpcl_ref_compnr integer, 
            bptc varchar, 
            bptc_ref_compnr integer, 
            cact varchar, 
            ccty varchar, 
            ccty_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            ceno varchar, 
            cfln integer, 
            cinm varchar, 
            cinm_ref_compnr integer, 
            cnln varchar, 
            compnr integer, 
            cono varchar, 
            cono_cnln_ref_compnr integer, 
            cono_ref_compnr integer, 
            cpay varchar, 
            cpay_ref_compnr integer, 
            cprj varchar, 
            cprj_cpro varchar, 
            cprj_cspa_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cpro varchar, 
            cspa varchar, 
            cstg varchar, 
            cstg_ref_compnr integer, 
            cstv numeric(38, 17), 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            cvat varchar, 
            deleted boolean, 
            desc object, 
            exmt integer, 
            exmt_kw varchar, 
            exrs varchar, 
            exrs_ref_compnr integer, 
            famt numeric(38, 17), 
            famt_cntc numeric(38, 17), 
            famt_dwhc numeric(38, 17), 
            famt_homc numeric(38, 17), 
            famt_prjc numeric(38, 17), 
            famt_refc numeric(38, 17), 
            famt_rpc1 numeric(38, 17), 
            famt_rpc2 numeric(38, 17), 
            fcmp integer, 
            fprd datetime, 
            ftyp integer, 
            ftyp_kw varchar, 
            iamt numeric(38, 17), 
            iamt_cntc numeric(38, 17), 
            iamt_dwhc numeric(38, 17), 
            iamt_homc numeric(38, 17), 
            iamt_prjc numeric(38, 17), 
            iamt_refc numeric(38, 17), 
            iamt_rpc1 numeric(38, 17), 
            iamt_rpc2 numeric(38, 17), 
            idln integer, 
            idoc integer, 
            indt datetime, 
            invo integer, 
            invo_kw varchar, 
            ityp varchar, 
            ofcn varchar, 
            ofcn_ref_compnr integer, 
            paym varchar, 
            pbbl numeric(38, 17), 
            sequencenumber integer, 
            sidt datetime, 
            sprd datetime, 
            tact varchar, 
            tcst integer, 
            tcst_kw varchar, 
            text integer, 
            text_ref_compnr integer, 
            timestamp datetime, 
            toin integer, 
            toin_kw varchar, 
            trsl integer, 
            trsl_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 