CREATE OR REPLACE TABLE TARGET_LN.LN_TFFBS005(
            budg varchar, 
            budg_ref_compnr integer, 
            cbud varchar, 
            cbud_ref_compnr integer, 
            cbyr integer, 
            cbyr_cbud_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            dbud varchar, 
            dbud_ref_compnr integer, 
            dbyr integer, 
            dbyr_dbud_ref_compnr integer, 
            defi integer, 
            defi_kw varchar, 
            deleted boolean, 
            disb varchar, 
            disb_ref_compnr integer, 
            lmdt datetime, 
            pbud varchar, 
            pbud_ref_compnr integer, 
            pbyr integer, 
            pbyr_pbud_ref_compnr integer, 
            ratc_1 numeric(38, 17), 
            ratc_2 numeric(38, 17), 
            ratc_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            sequencenumber integer, 
            text integer, 
            text_ref_compnr integer, 
            timestamp datetime, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 