CREATE OR REPLACE TABLE TARGET_LN.LN_TTDPM510(
            comp integer, 
            comp_ref_compnr integer, 
            compnr integer, 
            deleted boolean, 
            dset varchar, 
            dset_ref_compnr integer, 
            pacc varchar, 
            pacc_dset_ref_compnr integer, 
            pacc_ref_compnr integer, 
            pubd integer, 
            pubd_kw varchar, 
            sequencenumber integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 