CREATE OR REPLACE TABLE TARGET_LN.LN_TPPPC231(
            amoc numeric(38, 17), 
            amos numeric(38, 17), 
            blbl integer, 
            blbl_kw varchar, 
            cact varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            cdf_sref object, 
            cdf_susr object, 
            cdoc object, 
            cdoc_ref_compnr integer, 
            cfpo integer, 
            cfpo_kw varchar, 
            cohd_1 numeric(38, 17), 
            cohd_2 numeric(38, 17), 
            cohd_3 numeric(38, 17), 
            compnr integer, 
            cper integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cptc varchar, 
            cptc_cyea_cper_ref_compnr integer, 
            cptc_ref_compnr integer, 
            cptf varchar, 
            cptf_fyea_fper_ref_compnr integer, 
            cptf_ref_compnr integer, 
            cpth varchar, 
            cpth_ref_compnr integer, 
            cpth_year_peri_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            cuni varchar, 
            curc varchar, 
            curc_ref_compnr integer, 
            curs varchar, 
            curs_ref_compnr integer, 
            cwgt varchar, 
            cwgt_ref_compnr integer, 
            cyea integer, 
            deleted boolean, 
            desc object, 
            emno varchar, 
            emno_ref_compnr integer, 
            entu varchar, 
            fcrt integer, 
            fcrt_kw varchar, 
            fdoc integer, 
            flin integer, 
            fper integer, 
            fsrl integer, 
            ftty varchar, 
            fyea integer, 
            guid varchar, 
            ifbp varchar, 
            ifbp_ref_compnr integer, 
            loco varchar, 
            ltdt datetime, 
            ncmp integer, 
            orno varchar, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            peri integer, 
            pono integer, 
            potf integer, 
            potf_kw varchar, 
            quan numeric(38, 17), 
            ratc numeric(38, 17), 
            rats numeric(38, 17), 
            rdas datetime, 
            rdat datetime, 
            rgdt datetime, 
            rper integer, 
            rtcc_1 numeric(38, 17), 
            rtcc_2 numeric(38, 17), 
            rtcc_3 numeric(38, 17), 
            rtcs_1 numeric(38, 17), 
            rtcs_2 numeric(38, 17), 
            rtcs_3 numeric(38, 17), 
            rtfc_1 integer, 
            rtfc_2 integer, 
            rtfc_3 integer, 
            rtfs_1 integer, 
            rtfs_2 integer, 
            rtfs_3 integer, 
            rtyp varchar, 
            rtyp_ref_compnr integer, 
            ryea integer, 
            sequencenumber integer, 
            serc integer, 
            serh integer, 
            sern integer, 
            srnb integer, 
            sttl integer, 
            sttl_kw varchar, 
            task varchar, 
            tetc integer, 
            tetc_kw varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 