CREATE OR REPLACE TABLE TARGET_LN.LN_TCMCS052(
            compnr integer, 
            cprj varchar, 
            deleted boolean, 
            dsca object, 
            dscb object, 
            dscc object, 
            dscd object, 
            isrv integer, 
            isrv_kw varchar, 
            pctr varchar, 
            plnk integer, 
            plnk_kw varchar, 
            seab object, 
            seak object, 
            sequencenumber integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 