CREATE OR REPLACE TABLE TARGET_LN.LN_TPPDM605(
            abpp integer, 
            abpp_kw varchar, 
            abrf integer, 
            abrf_kw varchar, 
            acgm integer, 
            acgm_kw varchar, 
            acmp integer, 
            acmp_kw varchar, 
            acpc numeric(38, 17), 
            aerf numeric(38, 17), 
            aext varchar, 
            agty integer, 
            agty_kw varchar, 
            anbr varchar, 
            aprp numeric(38, 17), 
            arpc numeric(38, 17), 
            arrl numeric(38, 17), 
            arrm integer, 
            arrm_kw varchar, 
            arrt numeric(38, 17), 
            ascd object, 
            avtp varchar, 
            avtp_ref_compnr integer, 
            bdmt integer, 
            bdmt_kw varchar, 
            bfpp integer, 
            bfpp_kw varchar, 
            bfrf integer, 
            bfrf_kw varchar, 
            btco integer, 
            btco_kw varchar, 
            btdt datetime, 
            btpr integer, 
            btpr_kw varchar, 
            capp integer, 
            capp_kw varchar, 
            carr varchar, 
            carr_ref_compnr integer, 
            ccal varchar, 
            ccam varchar, 
            ccam_ref_compnr integer, 
            ccat varchar, 
            ccat_ref_compnr integer, 
            ccdt datetime, 
            ccot varchar, 
            ccot_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            cdis varchar, 
            cdis_ref_compnr integer, 
            cfac varchar, 
            cfac_ref_compnr integer, 
            cfpr integer, 
            cfye integer, 
            cldr varchar, 
            cldr_ref_compnr integer, 
            cmog integer, 
            cmog_kw varchar, 
            cmpc integer, 
            cmpc_kw varchar, 
            cmud varchar, 
            cmud_ref_compnr integer, 
            cobs varchar, 
            cobs_ref_compnr integer, 
            cogc numeric(38, 17), 
            cogs integer, 
            cogs_kw varchar, 
            compnr integer, 
            copr numeric(38, 17), 
            coty integer, 
            coty_kw varchar, 
            cpla varchar, 
            cprj varchar, 
            cprj_ccal_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cpla_rsac_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cprq integer, 
            cprq_kw varchar, 
            creg varchar, 
            creg_ref_compnr integer, 
            crte varchar, 
            crte_ref_compnr integer, 
            crtp varchar, 
            crtp_ref_compnr integer, 
            csec varchar, 
            csec_ref_compnr integer, 
            cspa varchar, 
            cstg varchar, 
            cstg_ref_compnr integer, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            deleted boolean, 
            dlau datetime, 
            dldt datetime, 
            dsca object, 
            dscb object, 
            dscc object, 
            dscd object, 
            dwar varchar, 
            dwar_ref_compnr integer, 
            earf numeric(38, 17), 
            entu varchar, 
            espt numeric(38, 17), 
            fddt datetime, 
            guid varchar, 
            hbpc numeric(38, 17), 
            hdat datetime, 
            hsts integer, 
            hsts_kw varchar, 
            husr varchar, 
            igcd integer, 
            igcd_kw varchar, 
            inst varchar, 
            intp integer, 
            intp_kw varchar, 
            invm integer, 
            invm_kw varchar, 
            invr integer, 
            invr_kw varchar, 
            ipin integer, 
            ipin_kw varchar, 
            kopr integer, 
            kopr_kw varchar, 
            kptm integer, 
            kptm_kw varchar, 
            lcdt datetime, 
            lcla varchar, 
            lclg varchar, 
            lmdt datetime, 
            lmus varchar, 
            logc varchar, 
            logh varchar, 
            lpdt datetime, 
            ltrc datetime, 
            ltrs datetime, 
            lwha integer, 
            lwha_kw varchar, 
            lwhb integer, 
            lwhb_kw varchar, 
            lwhc integer, 
            lwhc_kw varchar, 
            lwhd integer, 
            lwhd_kw varchar, 
            lwta integer, 
            lwta_kw varchar, 
            lwtb integer, 
            lwtb_kw varchar, 
            lwtc integer, 
            lwtc_kw varchar, 
            mprj varchar, 
            ncmp integer, 
            njsp integer, 
            ofes varchar, 
            ofes_ref_compnr integer, 
            ofpr varchar, 
            ofpr_ref_compnr integer, 
            padr varchar, 
            padr_ref_compnr integer, 
            pcba numeric(38, 17), 
            pceq numeric(38, 17), 
            pcic numeric(38, 17), 
            pcit numeric(38, 17), 
            pcmp numeric(38, 17), 
            pcrd datetime, 
            pcsb numeric(38, 17), 
            pcts numeric(38, 17), 
            pcwa numeric(38, 17), 
            peri integer, 
            plcd integer, 
            plcd_kw varchar, 
            plgr varchar, 
            plgr_ref_compnr integer, 
            pmfc varchar, 
            pmfc_ref_compnr integer, 
            pmng varchar, 
            pmng_ref_compnr integer, 
            potp varchar, 
            potp_ref_compnr integer, 
            preq integer, 
            preq_kw varchar, 
            prgm varchar, 
            prgm_ref_compnr integer, 
            pric integer, 
            pric_kw varchar, 
            prit integer, 
            prit_kw varchar, 
            pror integer, 
            pror_kw varchar, 
            prpc numeric(38, 17), 
            prre integer, 
            prre_kw varchar, 
            prsb integer, 
            prsb_kw varchar, 
            prts integer, 
            prts_kw varchar, 
            pscd object, 
            pseq integer, 
            psic integer, 
            psit integer, 
            pssc integer, 
            psta integer, 
            pstf integer, 
            pstf_kw varchar, 
            psts integer, 
            psts_kw varchar, 
            ptcs numeric(38, 17), 
            pwar varchar, 
            pwar_ref_compnr integer, 
            ratc numeric(38, 17), 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rats numeric(38, 17), 
            rcmc_1 numeric(38, 17), 
            rcmc_2 numeric(38, 17), 
            rcmc_3 numeric(38, 17), 
            rdat datetime, 
            revl numeric(38, 17), 
            revr integer, 
            revr_kw varchar, 
            revt numeric(38, 17), 
            rfcu object, 
            ripr varchar, 
            ripr_ref_compnr integer, 
            rjct integer, 
            rjct_kw varchar, 
            rrtp varchar, 
            rrtp_ref_compnr integer, 
            rsac varchar, 
            rsip varchar, 
            rsmc_1 numeric(38, 17), 
            rsmc_2 numeric(38, 17), 
            rsmc_3 numeric(38, 17), 
            rsrv integer, 
            rtyp varchar, 
            rtyp_ref_compnr integer, 
            sadr varchar, 
            sadr_ref_compnr integer, 
            seak object, 
            sequencenumber integer, 
            stdt datetime, 
            stus integer, 
            stus_kw varchar, 
            tbdg integer, 
            tbdg_kw varchar, 
            timestamp datetime, 
            tmpl integer, 
            tmpl_kw varchar, 
            tpac varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            uobs integer, 
            uobs_kw varchar, 
            upal integer, 
            upal_kw varchar, 
            user varchar, 
            username varchar, 
            ussu integer, 
            ussu_kw varchar, 
            wipc numeric(38, 17), 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 