CREATE OR REPLACE TABLE TARGET_LN.LN_TPPDM643(
            ccco varchar, 
            ccco_ref_compnr integer, 
            compnr integer, 
            cprj varchar, 
            cprj_ref_compnr integer, 
            cpro varchar, 
            deleted boolean, 
            desc object, 
            seak object, 
            sequencenumber integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 