CREATE OR REPLACE TABLE TARGET_LN.LN_WHINR110(
            atse varchar, 
            atse_ref_compnr integer, 
            bfbp varchar, 
            boml integer, 
            bpid varchar, 
            bpid_ref_compnr integer, 
            cact varchar, 
            ccco varchar, 
            chan varchar, 
            chan_ref_compnr integer, 
            cinv integer, 
            clot varchar, 
            compnr integer, 
            cons integer, 
            cons_kw varchar, 
            cosv integer, 
            cosv_kw varchar, 
            cprj varchar, 
            cprj_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            ctrr integer, 
            ctrr_kw varchar, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            dlin integer, 
            effn integer, 
            effn_ref_compnr integer, 
            ilgd datetime, 
            invd datetime, 
            iseq integer, 
            item varchar, 
            item_ref_compnr integer, 
            itid varchar, 
            itrd datetime, 
            itse integer, 
            koor integer, 
            koor_kw varchar, 
            kost integer, 
            kost_kw varchar, 
            lgdt datetime, 
            logn varchar, 
            oats varchar, 
            oats_ref_compnr integer, 
            ocmp integer, 
            ocmp_ref_compnr integer, 
            orno varchar, 
            ownr varchar, 
            owns integer, 
            owns_kw varchar, 
            phtr integer, 
            phtr_kw varchar, 
            pono integer, 
            prjp integer, 
            prjp_kw varchar, 
            prnt integer, 
            prnt_kw varchar, 
            pyps integer, 
            qaiu numeric(38, 17), 
            qapu numeric(38, 17), 
            qhnd numeric(38, 17), 
            qhnd_buar numeric(38, 17), 
            qhnd_buln numeric(38, 17), 
            qhnd_buvl numeric(38, 17), 
            qhnd_buwg numeric(38, 17), 
            qipu numeric(38, 17), 
            qstk numeric(38, 17), 
            qstk_buar numeric(38, 17), 
            qstk_buln numeric(38, 17), 
            qstk_buvl numeric(38, 17), 
            qstk_buwg numeric(38, 17), 
            rcln integer, 
            rcno varchar, 
            reco integer, 
            reco_kw varchar, 
            reje integer, 
            reje_kw varchar, 
            rowc integer, 
            rowc_ref_compnr integer, 
            rown varchar, 
            rown_ref_compnr integer, 
            seqn integer, 
            sequencenumber integer, 
            serl varchar, 
            shpm varchar, 
            shpo integer, 
            site varchar, 
            site_ref_compnr integer, 
            spcn varchar, 
            srnb integer, 
            tagn varchar, 
            timestamp datetime, 
            trdt datetime, 
            ttyp varchar, 
            username varchar, 
            valm integer, 
            valm_kw varchar, 
            vbas integer, 
            vbas_kw varchar, 
            vwvg integer, 
            vwvg_kw varchar, 
            wvgr varchar, 
            wvgr_ref_compnr integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 