CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TDPUR400 AS SELECT
                        src:adin::varchar AS adin, 
                        src:akcd::varchar AS akcd, 
                        src:akcd_ref_compnr::integer AS akcd_ref_compnr, 
                        src:bgrb::integer AS bgrb, 
                        src:bgrb_kw::varchar AS bgrb_kw, 
                        src:bgrq::integer AS bgrq, 
                        src:bgrq_kw::varchar AS bgrq_kw, 
                        src:bpcl::varchar AS bpcl, 
                        src:bpcl_ref_compnr::integer AS bpcl_ref_compnr, 
                        src:bppr::varchar AS bppr, 
                        src:bppr_ref_compnr::integer AS bppr_ref_compnr, 
                        src:bptx::varchar AS bptx, 
                        src:bptx_ref_compnr::integer AS bptx_ref_compnr, 
                        src:cadr::varchar AS cadr, 
                        src:cadr_ref_compnr::integer AS cadr_ref_compnr, 
                        src:cbrn::varchar AS cbrn, 
                        src:cbrn_ref_compnr::integer AS cbrn_ref_compnr, 
                        src:ccon::varchar AS ccon, 
                        src:ccon_ref_compnr::integer AS ccon_ref_compnr, 
                        src:ccrs::varchar AS ccrs, 
                        src:ccrs_ref_compnr::integer AS ccrs_ref_compnr, 
                        src:ccty::varchar AS ccty, 
                        src:ccur::varchar AS ccur, 
                        src:ccur_ref_compnr::integer AS ccur_ref_compnr, 
                        src:cdec::varchar AS cdec, 
                        src:cdec_ref_compnr::integer AS cdec_ref_compnr, 
                        src:cdf_adat::datetime AS cdf_adat, 
                        src:cdf_ausr::varchar AS cdf_ausr, 
                        src:cdf_cprj::varchar AS cdf_cprj, 
                        src:cdf_cprj_ref_compnr::integer AS cdf_cprj_ref_compnr, 
                        src:cdf_crdt::datetime AS cdf_crdt, 
                        src:cdf_lmdt::datetime AS cdf_lmdt, 
                        src:cdf_lmus::varchar AS cdf_lmus, 
                        src:cdf_poid::varchar AS cdf_poid, 
                        src:cdf_usid::varchar AS cdf_usid, 
                        src:cfrw::varchar AS cfrw, 
                        src:cfrw_ref_compnr::integer AS cfrw_ref_compnr, 
                        src:chrq::integer AS chrq, 
                        src:chrq_kw::varchar AS chrq_kw, 
                        src:cofc::varchar AS cofc, 
                        src:cofc_ref_compnr::integer AS cofc_ref_compnr, 
                        src:comm::integer AS comm, 
                        src:comm_kw::varchar AS comm_kw, 
                        src:compnr::integer AS compnr, 
                        src:corg::integer AS corg, 
                        src:corg_kw::varchar AS corg_kw, 
                        src:cosn::varchar AS cosn, 
                        src:cotp::varchar AS cotp, 
                        src:cotp_ref_compnr::integer AS cotp_ref_compnr, 
                        src:cpay::varchar AS cpay, 
                        src:cpay_ref_compnr::integer AS cpay_ref_compnr, 
                        src:cplp::varchar AS cplp, 
                        src:cplp_ref_compnr::integer AS cplp_ref_compnr, 
                        src:crby::varchar AS crby, 
                        src:crcd::varchar AS crcd, 
                        src:crcd_ref_compnr::integer AS crcd_ref_compnr, 
                        src:crcl::integer AS crcl, 
                        src:crcl_kw::varchar AS crcl_kw, 
                        src:crdt::datetime AS crdt, 
                        src:creg::varchar AS creg, 
                        src:creg_ref_compnr::integer AS creg_ref_compnr, 
                        src:crht::integer AS crht, 
                        src:crht_ref_compnr::integer AS crht_ref_compnr, 
                        src:crin::integer AS crin, 
                        src:crin_kw::varchar AS crin_kw, 
                        src:cror::integer AS cror, 
                        src:cror_kw::varchar AS cror_kw, 
                        src:crrq::integer AS crrq, 
                        src:crrq_kw::varchar AS crrq_kw, 
                        src:ctcd::varchar AS ctcd, 
                        src:ctcd_ref_compnr::integer AS ctcd_ref_compnr, 
                        src:ctrj::varchar AS ctrj, 
                        src:ctrj_ref_compnr::integer AS ctrj_ref_compnr, 
                        src:cvyn::integer AS cvyn, 
                        src:cvyn_kw::varchar AS cvyn_kw, 
                        src:cwar::varchar AS cwar, 
                        src:cwar_ref_compnr::integer AS cwar_ref_compnr, 
                        src:ddat::datetime AS ddat, 
                        src:ddtc::datetime AS ddtc, 
                        src:deleted::boolean AS deleted, 
                        src:egen::integer AS egen, 
                        src:egen_kw::varchar AS egen_kw, 
                        src:etpc::integer AS etpc, 
                        src:etpc_kw::varchar AS etpc_kw, 
                        src:fdpt::varchar AS fdpt, 
                        src:fdpt_ref_compnr::integer AS fdpt_ref_compnr, 
                        src:hdst::integer AS hdst, 
                        src:hdst_kw::varchar AS hdst_kw, 
                        src:hism::integer AS hism, 
                        src:hism_kw::varchar AS hism_kw, 
                        src:hisp::integer AS hisp, 
                        src:hisp_kw::varchar AS hisp_kw, 
                        src:iafc::integer AS iafc, 
                        src:iafc_kw::varchar AS iafc_kw, 
                        src:iebp::integer AS iebp, 
                        src:iebp_kw::varchar AS iebp_kw, 
                        src:ifad::varchar AS ifad, 
                        src:ifad_ref_compnr::integer AS ifad_ref_compnr, 
                        src:ifbp::varchar AS ifbp, 
                        src:ifbp_ref_compnr::integer AS ifbp_ref_compnr, 
                        src:ifcn::varchar AS ifcn, 
                        src:ifcn_ref_compnr::integer AS ifcn_ref_compnr, 
                        src:issp::integer AS issp, 
                        src:issp_kw::varchar AS issp_kw, 
                        src:lccl::varchar AS lccl, 
                        src:lccl_ref_compnr::integer AS lccl_ref_compnr, 
                        src:lcrq::integer AS lcrq, 
                        src:lcrq_kw::varchar AS lcrq_kw, 
                        src:mcfr::integer AS mcfr, 
                        src:mcfr_kw::varchar AS mcfr_kw, 
                        src:oamt::numeric(38, 17) AS oamt, 
                        src:odat::datetime AS odat, 
                        src:odis::numeric(38, 17) AS odis, 
                        src:odno::varchar AS odno, 
                        src:odty::integer AS odty, 
                        src:odty_kw::varchar AS odty_kw, 
                        src:opor::varchar AS opor, 
                        src:orno::varchar AS orno, 
                        src:orno_cosn_ref_compnr::integer AS orno_cosn_ref_compnr, 
                        src:otad::varchar AS otad, 
                        src:otad_ref_compnr::integer AS otad_ref_compnr, 
                        src:otbp::varchar AS otbp, 
                        src:otbp_ref_compnr::integer AS otbp_ref_compnr, 
                        src:otcn::varchar AS otcn, 
                        src:otcn_ref_compnr::integer AS otcn_ref_compnr, 
                        src:paft::integer AS paft, 
                        src:paft_kw::varchar AS paft_kw, 
                        src:plnr::varchar AS plnr, 
                        src:plnr_ref_compnr::integer AS plnr_ref_compnr, 
                        src:prno::varchar AS prno, 
                        src:prno_ref_compnr::integer AS prno_ref_compnr, 
                        src:ptad::varchar AS ptad, 
                        src:ptad_ref_compnr::integer AS ptad_ref_compnr, 
                        src:ptbp::varchar AS ptbp, 
                        src:ptbp_ref_compnr::integer AS ptbp_ref_compnr, 
                        src:ptcn::varchar AS ptcn, 
                        src:ptcn_ref_compnr::integer AS ptcn_ref_compnr, 
                        src:ptpa::varchar AS ptpa, 
                        src:ptpa_ref_compnr::integer AS ptpa_ref_compnr, 
                        src:ragr::varchar AS ragr, 
                        src:ratc_dtwc::numeric(38, 17) AS ratc_dtwc, 
                        src:ratc_lclc::numeric(38, 17) AS ratc_lclc, 
                        src:ratc_rfrc::numeric(38, 17) AS ratc_rfrc, 
                        src:ratc_rpc1::numeric(38, 17) AS ratc_rpc1, 
                        src:ratc_rpc2::numeric(38, 17) AS ratc_rpc2, 
                        src:ratd::datetime AS ratd, 
                        src:ratf_1::integer AS ratf_1, 
                        src:ratf_2::integer AS ratf_2, 
                        src:ratf_3::integer AS ratf_3, 
                        src:ratp_1::numeric(38, 17) AS ratp_1, 
                        src:ratp_2::numeric(38, 17) AS ratp_2, 
                        src:ratp_3::numeric(38, 17) AS ratp_3, 
                        src:ratt::varchar AS ratt, 
                        src:ratt_ref_compnr::integer AS ratt_ref_compnr, 
                        src:raur::integer AS raur, 
                        src:raur_kw::varchar AS raur_kw, 
                        src:refa::object AS refa, 
                        src:refb::object AS refb, 
                        src:retr::varchar AS retr, 
                        src:retr_ref_compnr::integer AS retr_ref_compnr, 
                        src:revn::integer AS revn, 
                        src:rsta::integer AS rsta, 
                        src:rsta_kw::varchar AS rsta_kw, 
                        src:sbim::integer AS sbim, 
                        src:sbim_kw::varchar AS sbim_kw, 
                        src:sbmt::varchar AS sbmt, 
                        src:sbmt_ref_compnr::integer AS sbmt_ref_compnr, 
                        src:sclb::integer AS sclb, 
                        src:sclb_kw::varchar AS sclb_kw, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:sfad::varchar AS sfad, 
                        src:sfad_ref_compnr::integer AS sfad_ref_compnr, 
                        src:sfbp::varchar AS sfbp, 
                        src:sfbp_ref_compnr::integer AS sfbp_ref_compnr, 
                        src:sfcn::varchar AS sfcn, 
                        src:sfcn_ref_compnr::integer AS sfcn_ref_compnr, 
                        src:site::varchar AS site, 
                        src:site_ref_compnr::integer AS site_ref_compnr, 
                        src:sorn::object AS sorn, 
                        src:spss::varchar AS spss, 
                        src:spss_ref_compnr::integer AS spss_ref_compnr, 
                        src:timestamp::datetime AS timestamp, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:txtb::integer AS txtb, 
                        src:txtb_ref_compnr::integer AS txtb_ref_compnr, 
                        src:username::varchar AS username, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:orno,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:orno,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TDPUR400 as strm))