CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TSCTM136 AS SELECT
                        src:alco_1::numeric(38, 17) AS alco_1, 
                        src:alco_2::numeric(38, 17) AS alco_2, 
                        src:alco_3::numeric(38, 17) AS alco_3, 
                        src:alco_cntc::numeric(38, 17) AS alco_cntc, 
                        src:alco_dwhc::numeric(38, 17) AS alco_dwhc, 
                        src:alco_refc::numeric(38, 17) AS alco_refc, 
                        src:alqu::numeric(38, 17) AS alqu, 
                        src:alqu_buar::numeric(38, 17) AS alqu_buar, 
                        src:alqu_buln::numeric(38, 17) AS alqu_buln, 
                        src:alqu_bupc::numeric(38, 17) AS alqu_bupc, 
                        src:alqu_buvl::numeric(38, 17) AS alqu_buvl, 
                        src:alqu_buwg::numeric(38, 17) AS alqu_buwg, 
                        src:alqu_invu::numeric(38, 17) AS alqu_invu, 
                        src:alsa::numeric(38, 17) AS alsa, 
                        src:alsa_dwhc::numeric(38, 17) AS alsa_dwhc, 
                        src:alsa_homc::numeric(38, 17) AS alsa_homc, 
                        src:alsa_refc::numeric(38, 17) AS alsa_refc, 
                        src:alsa_rpc1::numeric(38, 17) AS alsa_rpc1, 
                        src:alsa_rpc2::numeric(38, 17) AS alsa_rpc2, 
                        src:amnt::numeric(38, 17) AS amnt, 
                        src:amnt_dwhc::numeric(38, 17) AS amnt_dwhc, 
                        src:amnt_homc::numeric(38, 17) AS amnt_homc, 
                        src:amnt_refc::numeric(38, 17) AS amnt_refc, 
                        src:amnt_rpc1::numeric(38, 17) AS amnt_rpc1, 
                        src:amnt_rpc2::numeric(38, 17) AS amnt_rpc2, 
                        src:camt_1::numeric(38, 17) AS camt_1, 
                        src:camt_2::numeric(38, 17) AS camt_2, 
                        src:camt_3::numeric(38, 17) AS camt_3, 
                        src:camt_cntc::numeric(38, 17) AS camt_cntc, 
                        src:camt_dwhc::numeric(38, 17) AS camt_dwhc, 
                        src:camt_refc::numeric(38, 17) AS camt_refc, 
                        src:ccmp::varchar AS ccmp, 
                        src:ccmp_ref_compnr::integer AS ccmp_ref_compnr, 
                        src:cctp::varchar AS cctp, 
                        src:cctp_ref_compnr::integer AS cctp_ref_compnr, 
                        src:cfln::integer AS cfln, 
                        src:compnr::integer AS compnr, 
                        src:cotp::integer AS cotp, 
                        src:cotp_kw::varchar AS cotp_kw, 
                        src:cseq::integer AS cseq, 
                        src:cuni::varchar AS cuni, 
                        src:cuni_ref_compnr::integer AS cuni_ref_compnr, 
                        src:deleted::boolean AS deleted, 
                        src:desc::object AS desc, 
                        src:dspc::integer AS dspc, 
                        src:dspc_kw::varchar AS dspc_kw, 
                        src:ealc_1::numeric(38, 17) AS ealc_1, 
                        src:ealc_2::numeric(38, 17) AS ealc_2, 
                        src:ealc_3::numeric(38, 17) AS ealc_3, 
                        src:ealc_cntc::numeric(38, 17) AS ealc_cntc, 
                        src:ealc_dwhc::numeric(38, 17) AS ealc_dwhc, 
                        src:ealc_refc::numeric(38, 17) AS ealc_refc, 
                        src:eals::numeric(38, 17) AS eals, 
                        src:eals_dwhc::numeric(38, 17) AS eals_dwhc, 
                        src:eals_homc::numeric(38, 17) AS eals_homc, 
                        src:eals_refc::numeric(38, 17) AS eals_refc, 
                        src:eals_rpc1::numeric(38, 17) AS eals_rpc1, 
                        src:eals_rpc2::numeric(38, 17) AS eals_rpc2, 
                        src:eaqu::numeric(38, 17) AS eaqu, 
                        src:eaqu_buar::numeric(38, 17) AS eaqu_buar, 
                        src:eaqu_buln::numeric(38, 17) AS eaqu_buln, 
                        src:eaqu_bupc::numeric(38, 17) AS eaqu_bupc, 
                        src:eaqu_butm::numeric(38, 17) AS eaqu_butm, 
                        src:eaqu_buvl::numeric(38, 17) AS eaqu_buvl, 
                        src:eaqu_buwg::numeric(38, 17) AS eaqu_buwg, 
                        src:eaqu_invu::numeric(38, 17) AS eaqu_invu, 
                        src:item::varchar AS item, 
                        src:item_ref_compnr::integer AS item_ref_compnr, 
                        src:nrbt::integer AS nrbt, 
                        src:otbp::varchar AS otbp, 
                        src:otbp_ref_compnr::integer AS otbp_ref_compnr, 
                        src:pric_1::numeric(38, 17) AS pric_1, 
                        src:pric_2::numeric(38, 17) AS pric_2, 
                        src:pric_3::numeric(38, 17) AS pric_3, 
                        src:pris::numeric(38, 17) AS pris, 
                        src:quan::numeric(38, 17) AS quan, 
                        src:quan_buar::numeric(38, 17) AS quan_buar, 
                        src:quan_buln::numeric(38, 17) AS quan_buln, 
                        src:quan_bupc::numeric(38, 17) AS quan_bupc, 
                        src:quan_buvl::numeric(38, 17) AS quan_buvl, 
                        src:quan_buwg::numeric(38, 17) AS quan_buwg, 
                        src:quan_invu::numeric(38, 17) AS quan_invu, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:spco_1::numeric(38, 17) AS spco_1, 
                        src:spco_2::numeric(38, 17) AS spco_2, 
                        src:spco_3::numeric(38, 17) AS spco_3, 
                        src:spco_cntc::numeric(38, 17) AS spco_cntc, 
                        src:spco_dwhc::numeric(38, 17) AS spco_dwhc, 
                        src:spco_refc::numeric(38, 17) AS spco_refc, 
                        src:spqu::numeric(38, 17) AS spqu, 
                        src:spsa::numeric(38, 17) AS spsa, 
                        src:spsa_dwhc::numeric(38, 17) AS spsa_dwhc, 
                        src:spsa_homc::numeric(38, 17) AS spsa_homc, 
                        src:spsa_refc::numeric(38, 17) AS spsa_refc, 
                        src:spsa_rpc1::numeric(38, 17) AS spsa_rpc1, 
                        src:spsa_rpc2::numeric(38, 17) AS spsa_rpc2, 
                        src:term::integer AS term, 
                        src:term_cfln_cctp_cotp_nrbt_ref_compnr::integer AS term_cfln_cctp_cotp_nrbt_ref_compnr, 
                        src:term_cfln_ref_compnr::integer AS term_cfln_ref_compnr, 
                        src:timestamp::datetime AS timestamp, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:username::varchar AS username, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:cseq,
                src:compnr,
                src:term,
                src:cfln,
                src:cotp,
                src:nrbt,
                src:cctp,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:cseq,
                src:compnr,
                src:term,
                src:cfln,
                src:cotp,
                src:nrbt,
                src:cctp  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TSCTM136 as strm))