CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TSSOC210 AS SELECT
                        src:acdt::datetime AS acdt, 
                        src:acdu::numeric(38, 17) AS acdu, 
                        src:acln::integer AS acln, 
                        src:actg::varchar AS actg, 
                        src:actg_ref_compnr::integer AS actg_ref_compnr, 
                        src:adfa::integer AS adfa, 
                        src:adfa_kw::varchar AS adfa_kw, 
                        src:adin::varchar AS adin, 
                        src:adtm::integer AS adtm, 
                        src:advl::numeric(38, 17) AS advl, 
                        src:aftm::datetime AS aftm, 
                        src:ains::integer AS ains, 
                        src:ains_kw::varchar AS ains_kw, 
                        src:aivl::numeric(38, 17) AS aivl, 
                        src:altn::integer AS altn, 
                        src:amod::numeric(38, 17) AS amod, 
                        src:appo::integer AS appo, 
                        src:appo_kw::varchar AS appo_kw, 
                        src:asgd::varchar AS asgd, 
                        src:asta::integer AS asta, 
                        src:asta_kw::varchar AS asta_kw, 
                        src:astm::datetime AS astm, 
                        src:atbl::integer AS atbl, 
                        src:atbl_kw::varchar AS atbl_kw, 
                        src:atpc::integer AS atpc, 
                        src:atpc_kw::varchar AS atpc_kw, 
                        src:atpd::datetime AS atpd, 
                        src:bfbp::varchar AS bfbp, 
                        src:bfbp_ref_compnr::integer AS bfbp_ref_compnr, 
                        src:bsch::varchar AS bsch, 
                        src:bsch_ref_compnr::integer AS bsch_ref_compnr, 
                        src:cadt::date AS cadt, 
                        src:camr::varchar AS camr, 
                        src:camr_ref_compnr::integer AS camr_ref_compnr, 
                        src:caro_1::varchar AS caro_1, 
                        src:caro_10::varchar AS caro_10, 
                        src:caro_2::varchar AS caro_2, 
                        src:caro_3::varchar AS caro_3, 
                        src:caro_4::varchar AS caro_4, 
                        src:caro_5::varchar AS caro_5, 
                        src:caro_6::varchar AS caro_6, 
                        src:caro_7::varchar AS caro_7, 
                        src:caro_8::varchar AS caro_8, 
                        src:caro_9::varchar AS caro_9, 
                        src:ccar::varchar AS ccar, 
                        src:ccar_ref_compnr::integer AS ccar_ref_compnr, 
                        src:cchl::integer AS cchl, 
                        src:cchl_ref_compnr::integer AS cchl_ref_compnr, 
                        src:ccll::varchar AS ccll, 
                        src:ccll_ref_compnr::integer AS ccll_ref_compnr, 
                        src:cctp::varchar AS cctp, 
                        src:cctp_ref_compnr::integer AS cctp_ref_compnr, 
                        src:cdis::varchar AS cdis, 
                        src:cdis_ref_compnr::integer AS cdis_ref_compnr, 
                        src:clst::varchar AS clst, 
                        src:clst_ref_compnr::integer AS clst_ref_compnr, 
                        src:cmea::varchar AS cmea, 
                        src:cmea_ref_compnr::integer AS cmea_ref_compnr, 
                        src:cncd::varchar AS cncd, 
                        src:come::varchar AS come, 
                        src:come_ref_compnr::integer AS come_ref_compnr, 
                        src:compnr::integer AS compnr, 
                        src:cova::numeric(38, 17) AS cova, 
                        src:cpor::integer AS cpor, 
                        src:cpor_kw::varchar AS cpor_kw, 
                        src:cprj::varchar AS cprj, 
                        src:cprj_ref_compnr::integer AS cprj_ref_compnr, 
                        src:cprl::varchar AS cprl, 
                        src:cprl_ref_compnr::integer AS cprl_ref_compnr, 
                        src:crac::varchar AS crac, 
                        src:crac_ref_compnr::integer AS crac_ref_compnr, 
                        src:crpu::integer AS crpu, 
                        src:crpu_kw::varchar AS crpu_kw, 
                        src:crtc::varchar AS crtc, 
                        src:crtc_ref_compnr::integer AS crtc_ref_compnr, 
                        src:csar::varchar AS csar, 
                        src:csar_ref_compnr::integer AS csar_ref_compnr, 
                        src:csco::varchar AS csco, 
                        src:csco_ref_compnr::integer AS csco_ref_compnr, 
                        src:cskt::varchar AS cskt, 
                        src:cskt_ref_compnr::integer AS cskt_ref_compnr, 
                        src:cspa::varchar AS cspa, 
                        src:cstn::varchar AS cstn, 
                        src:cstn_ref_compnr::integer AS cstn_ref_compnr, 
                        src:cstp::varchar AS cstp, 
                        src:cstp_ref_compnr::integer AS cstp_ref_compnr, 
                        src:cupr::integer AS cupr, 
                        src:cupr_ref_compnr::integer AS cupr_ref_compnr, 
                        src:cuxr::varchar AS cuxr, 
                        src:cuxr_ref_compnr::integer AS cuxr_ref_compnr, 
                        src:cvtm::datetime AS cvtm, 
                        src:dbfc::numeric(38, 17) AS dbfc, 
                        src:deleted::boolean AS deleted, 
                        src:desc::object AS desc, 
                        src:docn::varchar AS docn, 
                        src:docn_ref_compnr::integer AS docn_ref_compnr, 
                        src:eaod::numeric(38, 17) AS eaod, 
                        src:emno::varchar AS emno, 
                        src:emno_ref_compnr::integer AS emno_ref_compnr, 
                        src:erdt::datetime AS erdt, 
                        src:espr::numeric(38, 17) AS espr, 
                        src:estm::datetime AS estm, 
                        src:fcon::varchar AS fcon, 
                        src:fcon_ref_compnr::integer AS fcon_ref_compnr, 
                        src:inby::integer AS inby, 
                        src:inby_kw::varchar AS inby_kw, 
                        src:inpl::varchar AS inpl, 
                        src:inpl_ref_compnr::integer AS inpl_ref_compnr, 
                        src:item::varchar AS item, 
                        src:item_ref_compnr::integer AS item_ref_compnr, 
                        src:item_sern_ref_compnr::integer AS item_sern_ref_compnr, 
                        src:item_xrsr_ref_compnr::integer AS item_xrsr_ref_compnr, 
                        src:lcad::varchar AS lcad, 
                        src:lcad_ref_compnr::integer AS lcad_ref_compnr, 
                        src:lftm::datetime AS lftm, 
                        src:mepo::varchar AS mepo, 
                        src:mepo_ref_compnr::integer AS mepo_ref_compnr, 
                        src:micn::integer AS micn, 
                        src:micn_kw::varchar AS micn_kw, 
                        src:mvla::integer AS mvla, 
                        src:mvln::numeric(38, 17) AS mvln, 
                        src:nivl::numeric(38, 17) AS nivl, 
                        src:noun::integer AS noun, 
                        src:obpr::integer AS obpr, 
                        src:obpr_ref_compnr::integer AS obpr_ref_compnr, 
                        src:oftm::datetime AS oftm, 
                        src:orac::varchar AS orac, 
                        src:oras::integer AS oras, 
                        src:orno::varchar AS orno, 
                        src:orno_ref_compnr::integer AS orno_ref_compnr, 
                        src:orps::integer AS orps, 
                        src:ostm::datetime AS ostm, 
                        src:pbsm::integer AS pbsm, 
                        src:pbsm_kw::varchar AS pbsm_kw, 
                        src:pcac::varchar AS pcac, 
                        src:pcch::integer AS pcch, 
                        src:pcln::integer AS pcln, 
                        src:pcon::varchar AS pcon, 
                        src:pcon_pcch_ref_compnr::integer AS pcon_pcch_ref_compnr, 
                        src:pcon_ref_compnr::integer AS pcon_ref_compnr, 
                        src:pdvl::numeric(38, 17) AS pdvl, 
                        src:pftm::datetime AS pftm, 
                        src:pmtd::integer AS pmtd, 
                        src:pmtd_kw::varchar AS pmtd_kw, 
                        src:porg::integer AS porg, 
                        src:porg_kw::varchar AS porg_kw, 
                        src:prac::integer AS prac, 
                        src:prac_kw::varchar AS prac_kw, 
                        src:pris::numeric(38, 17) AS pris, 
                        src:prpr::integer AS prpr, 
                        src:prpr_ref_compnr::integer AS prpr_ref_compnr, 
                        src:pstm::datetime AS pstm, 
                        src:ptft::datetime AS ptft, 
                        src:ptst::datetime AS ptst, 
                        src:qtnl::integer AS qtnl, 
                        src:qtno::varchar AS qtno, 
                        src:qtno_revn_qtnl_altn_ref_compnr::integer AS qtno_revn_qtnl_altn_ref_compnr, 
                        src:revn::integer AS revn, 
                        src:rfpt::varchar AS rfpt, 
                        src:rltm::datetime AS rltm, 
                        src:rnyn::integer AS rnyn, 
                        src:rnyn_kw::varchar AS rnyn_kw, 
                        src:rown::varchar AS rown, 
                        src:rown_ref_compnr::integer AS rown_ref_compnr, 
                        src:rrqt::integer AS rrqt, 
                        src:sbit::varchar AS sbit, 
                        src:sbit_ref_compnr::integer AS sbit_ref_compnr, 
                        src:sear::object AS sear, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:sern::varchar AS sern, 
                        src:sfad::varchar AS sfad, 
                        src:sfad_ref_compnr::integer AS sfad_ref_compnr, 
                        src:skla::varchar AS skla, 
                        src:sklb::varchar AS sklb, 
                        src:sklc::varchar AS sklc, 
                        src:smto::integer AS smto, 
                        src:smto_kw::varchar AS smto_kw, 
                        src:ssta::integer AS ssta, 
                        src:ssta_kw::varchar AS ssta_kw, 
                        src:stad::varchar AS stad, 
                        src:stad_ref_compnr::integer AS stad_ref_compnr, 
                        src:stbp::varchar AS stbp, 
                        src:stbp_ref_compnr::integer AS stbp_ref_compnr, 
                        src:stcn::varchar AS stcn, 
                        src:stcn_ref_compnr::integer AS stcn_ref_compnr, 
                        src:subc::integer AS subc, 
                        src:subc_kw::varchar AS subc_kw, 
                        src:supm::integer AS supm, 
                        src:supm_kw::varchar AS supm_kw, 
                        src:timestamp::datetime AS timestamp, 
                        src:tmun::integer AS tmun, 
                        src:tmun_kw::varchar AS tmun_kw, 
                        src:trdi::numeric(38, 17) AS trdi, 
                        src:trdi_buln::numeric(38, 17) AS trdi_buln, 
                        src:trdu::numeric(38, 17) AS trdu, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:txtb::integer AS txtb, 
                        src:txtb_ref_compnr::integer AS txtb_ref_compnr, 
                        src:txtc::integer AS txtc, 
                        src:txtc_ref_compnr::integer AS txtc_ref_compnr, 
                        src:txtd::integer AS txtd, 
                        src:txtd_ref_compnr::integer AS txtd_ref_compnr, 
                        src:username::varchar AS username, 
                        src:vtbo::integer AS vtbo, 
                        src:vtbo_kw::varchar AS vtbo_kw, 
                        src:wrtp::integer AS wrtp, 
                        src:wrtp_kw::varchar AS wrtp_kw, 
                        src:wrty::varchar AS wrty, 
                        src:xrcu::varchar AS xrcu, 
                        src:xrcu_ref_compnr::integer AS xrcu_ref_compnr, 
                        src:xrnh::integer AS xrnh, 
                        src:xrnh_kw::varchar AS xrnh_kw, 
                        src:xrrt::numeric(38, 17) AS xrrt, 
                        src:xrsr::varchar AS xrsr, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:acln,
                src:compnr,
                src:orno,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:acln,
                src:compnr,
                src:orno  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TSSOC210 as strm))