CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_LN_TPPDM035 AS SELECT
                        src:blbl::integer AS blbl, 
                        src:blbl_kw::varchar AS blbl_kw, 
                        src:buni::integer AS buni, 
                        src:buni_kw::varchar AS buni_kw, 
                        src:ccco::varchar AS ccco, 
                        src:ccco_ref_compnr::integer AS ccco_ref_compnr, 
                        src:cccp::varchar AS cccp, 
                        src:cccp_ref_compnr::integer AS cccp_ref_compnr, 
                        src:ccde::varchar AS ccde, 
                        src:ccde_ref_compnr::integer AS ccde_ref_compnr, 
                        src:ccfu::integer AS ccfu, 
                        src:ccfu_kw::varchar AS ccfu_kw, 
                        src:ccsb::varchar AS ccsb, 
                        src:ccsp::varchar AS ccsp, 
                        src:ccsp_ref_compnr::integer AS ccsp_ref_compnr, 
                        src:ccur::varchar AS ccur, 
                        src:ccur_ref_compnr::integer AS ccur_ref_compnr, 
                        src:citg::varchar AS citg, 
                        src:citg_ref_compnr::integer AS citg_ref_compnr, 
                        src:compnr::integer AS compnr, 
                        src:cood::varchar AS cood, 
                        src:cood_ref_compnr::integer AS cood_ref_compnr, 
                        src:cpgp::varchar AS cpgp, 
                        src:cpgp_ref_compnr::integer AS cpgp_ref_compnr, 
                        src:cpgs::varchar AS cpgs, 
                        src:cpgs_ref_compnr::integer AS cpgs_ref_compnr, 
                        src:cppp::integer AS cppp, 
                        src:cppp_kw::varchar AS cppp_kw, 
                        src:csel::varchar AS csel, 
                        src:csel_ref_compnr::integer AS csel_ref_compnr, 
                        src:csgp::varchar AS csgp, 
                        src:csgp_ref_compnr::integer AS csgp_ref_compnr, 
                        src:csgs::varchar AS csgs, 
                        src:csgs_ref_compnr::integer AS csgs_ref_compnr, 
                        src:csig::varchar AS csig, 
                        src:csig_ref_compnr::integer AS csig_ref_compnr, 
                        src:csub::varchar AS csub, 
                        src:csub_rcmp::integer AS csub_rcmp, 
                        src:cuni::varchar AS cuni, 
                        src:cuni_ref_compnr::integer AS cuni_ref_compnr, 
                        src:cuti::varchar AS cuti, 
                        src:cuti_ref_compnr::integer AS cuti_ref_compnr, 
                        src:cvat::varchar AS cvat, 
                        src:cvat_ref_compnr::integer AS cvat_ref_compnr, 
                        src:deleted::boolean AS deleted, 
                        src:desc::object AS desc, 
                        src:dsbc::integer AS dsbc, 
                        src:dsbc_kw::varchar AS dsbc_kw, 
                        src:ltpc::datetime AS ltpc, 
                        src:ltpp::datetime AS ltpp, 
                        src:ltps::datetime AS ltps, 
                        src:oltm::integer AS oltm, 
                        src:osys::integer AS osys, 
                        src:osys_kw::varchar AS osys_kw, 
                        src:otbp::varchar AS otbp, 
                        src:otbp_ref_compnr::integer AS otbp_ref_compnr, 
                        src:pcmc_1::numeric(38, 17) AS pcmc_1, 
                        src:pcmc_2::numeric(38, 17) AS pcmc_2, 
                        src:pcmc_3::numeric(38, 17) AS pcmc_3, 
                        src:plid::varchar AS plid, 
                        src:plid_ref_compnr::integer AS plid_ref_compnr, 
                        src:ppmc_1::numeric(38, 17) AS ppmc_1, 
                        src:ppmc_2::numeric(38, 17) AS ppmc_2, 
                        src:ppmc_3::numeric(38, 17) AS ppmc_3, 
                        src:prby::integer AS prby, 
                        src:prby_kw::varchar AS prby_kw, 
                        src:pric::numeric(38, 17) AS pric, 
                        src:prip::numeric(38, 17) AS prip, 
                        src:pris::numeric(38, 17) AS pris, 
                        src:prre::integer AS prre, 
                        src:prre_kw::varchar AS prre_kw, 
                        src:psiu::integer AS psiu, 
                        src:psiu_kw::varchar AS psiu_kw, 
                        src:psmc_1::numeric(38, 17) AS psmc_1, 
                        src:psmc_2::numeric(38, 17) AS psmc_2, 
                        src:psmc_3::numeric(38, 17) AS psmc_3, 
                        src:pwgc::numeric(38, 17) AS pwgc, 
                        src:rdpt::varchar AS rdpt, 
                        src:rdpt_ref_compnr::integer AS rdpt_ref_compnr, 
                        src:seak::object AS seak, 
                        src:sequencenumber::integer AS sequencenumber, 
                        src:srtr::varchar AS srtr, 
                        src:srtr_ref_compnr::integer AS srtr_ref_compnr, 
                        src:svat::varchar AS svat, 
                        src:svat_ref_compnr::integer AS svat_ref_compnr, 
                        src:timestamp::datetime AS timestamp, 
                        src:txta::integer AS txta, 
                        src:txta_ref_compnr::integer AS txta_ref_compnr, 
                        src:txtp::integer AS txtp, 
                        src:txtp_ref_compnr::integer AS txtp_ref_compnr, 
                        src:txts::integer AS txts, 
                        src:txts_ref_compnr::integer AS txts_ref_compnr, 
                        src:username::varchar AS username, 
                        src:uset::varchar AS uset, 
                        src:uset_cuni_ref_compnr::integer AS uset_cuni_ref_compnr, 
                        src:uset_ref_compnr::integer AS uset_ref_compnr, 
                        src:usyn::integer AS usyn, 
                        src:usyn_kw::varchar AS usyn_kw, 
            CASE
                WHEN 'LN' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'LN' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:csub,
                src:compnr,
            src:sequencenumber
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:csub,
                src:compnr  ORDER BY 
            src:sequencenumber desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.LN_TPPDM035 as strm))