create or replace TABLE DIM_READ_SOURCE (
	READ_SOURCE_SID NUMBER(38,0) NOT NULL autoincrement,
	READ_SOURCE_CODE VARCHAR(10),
	READ_SOURCE_DESCRIPTION VARCHAR(300),
	ETL_SOURCE_DATETIME TIMESTAMP_NTZ(9),
	ETL_RECORD_CREATED TIMESTAMP_NTZ(9),
	ETL_RECORD_UPDATED TIMESTAMP_NTZ(9),
	constraint UNIQUE_READ_SOURCE_CODE unique (READ_SOURCE_CODE),
	primary key (READ_SOURCE_SID)
);