create or replace TABLE DIM_EMPLOYEE (
	EMPLOYEE_SID NUMBER(38,0) NOT NULL autoincrement,
	EMPLOYEE_CODE VARCHAR(12),
	EMPLOYEE_CONTACT_KEY NUMBER(38,0),
	EMPLOYEE_NAME VARCHAR(194),
	ETL_SOURCE_DATETIME TIMESTAMP_NTZ(9),
	ETL_RECORD_CREATED TIMESTAMP_NTZ(9),
	ETL_RECORD_UPDATED TIMESTAMP_NTZ(9),
	constraint UNIQUE_EMPLOYEE_CODE unique (EMPLOYEE_CODE),
	primary key (EMPLOYEE_SID)
);