create or replace TABLE DIM_READER_CODE (
	READER_CODE_SID NUMBER(38,0) NOT NULL autoincrement,
	READER_CODE VARCHAR(10),
	READER_CODE_DESCRIPTION VARCHAR(300),
	ETL_SOURCE_DATETIME TIMESTAMP_NTZ(9),
	ETL_RECORD_CREATED TIMESTAMP_NTZ(9),
	ETL_RECORD_UPDATED TIMESTAMP_NTZ(9),
	constraint UNIQUE_READER_CODE unique (READER_CODE),
	primary key (READER_CODE_SID)
);