create or replace TRANSIENT TABLE STG_DIM_READER_CODE (
	READER_CODE VARCHAR(10),
	READER_CODE_DESCRIPTION VARCHAR(300),
	ETL_SOURCE_DATETIME TIMESTAMP_NTZ(9),
	ETL_RECORD_CREATED TIMESTAMP_NTZ(9),
	ETL_RECORD_UPDATED TIMESTAMP_NTZ(9)
);