create or replace task DATAHUB_INTEGRATION.TASK_SM_CURATED_ALARMSEVENTS
	schedule='USING CRON 12/25 * * * * UTC'
	error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
	as INSERT INTO TARGET_SM.SM_CURATED_ALARMSEVENTS
	SELECT * FROM DATAHUB_INTEGRATION.VW_STREAM_SM_CURATED_ALARMSEVENTS;
alter task DATAHUB_INTEGRATION.TASK_SM_CURATED_ALARMSEVENTS resume;