{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT.SMGROUP on 2022-03-03T11:28:36.524',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['HOLIDAY'], type='varchar', alias='holiday') }},
        {{ trx_json_extract('src', ['PROJECT'], type='varchar', alias='project') }},
        {{ trx_json_extract('src', ['RESPONSIBILITY'], type='varchar', alias='responsibility') }},
        {{ trx_json_extract('src', ['SRC'], type='varchar', alias='src') }},
        {{ trx_json_extract('src', ['PRI'], type='varchar', alias='pri') }},
        {{ trx_json_extract('src', ['GROUPKEY'], type='int', alias='groupkey') }},
        {{ trx_json_extract('src', ['ACTKEY'], type='int', alias='actkey') }},
        {{ trx_json_extract('src', ['WEEKEND'], type='varchar', alias='weekend') }},
        {{ trx_json_extract('src', ['WEEKDAY'], type='varchar', alias='weekday') }},
        {{ trx_json_extract('src', ['RESCHEDBY'], type='varchar', alias='reschedby') }},
        {{ trx_json_extract('src', ['BUDGETKEY'], type='int', alias='budgetkey') }},
        {{ trx_json_extract('src', ['SCHEDGRP'], type='varchar', alias='schedgrp') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CYCLETO'], type='timestamp_ntz', alias='cycleto') }},
        {{ trx_json_extract('src', ['CYCLEFR'], type='timestamp_ntz', alias='cyclefr') }},
        {{ trx_json_extract('src', ['HOLD'], type='varchar', alias='hold') }},
        {{ trx_json_extract('src', ['SUSPDAYS'], type='int', alias='suspdays') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['WORKDAY'], type='varchar', alias='workday') }},
        {{ trx_json_extract('src', ['STANDARDWORKORDERKEY'], type='int', alias='standardworkorderkey') }},
        {{ trx_json_extract('src', ['SCHEDKEY'], type='int', alias='schedkey') }},
        {{ trx_json_extract('src', ['DATAGRP'], type='varchar', alias='datagrp') }},
        {{ trx_json_extract('src', ['MAINTTYPE'], type='varchar', alias='mainttype') }},
        {{ trx_json_extract('src', ['SCHEDDTTM'], type='timestamp_ntz', alias='scheddttm') }},
        {{ trx_json_extract('src', ['WORKDAYSONLY'], type='varchar', alias='workdaysonly') }},
        {{ trx_json_extract('src', ['TIMEINT'], type='int', alias='timeint') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ENDOFMON'], type='varchar', alias='endofmon') }},
        {{ trx_json_extract('src', ['ASSIGNED'], type='varchar', alias='assigned') }},
        {{ trx_json_extract('src', ['BGTNO'], type='varchar', alias='bgtno') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['TIMEUNIT'], type='varchar', alias='timeunit') }},
        {{ trx_json_extract('src', ['AUTH'], type='varchar', alias='auth') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['SUSPHRS'], type='int', alias='susphrs') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_smgroup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['schedkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
