{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_WATER.WATERMETERTYPE on 2021-07-09T15:15:00.487',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['LOWREGNUMBERDIALS'], type='int', alias='lowregnumberdials') }},
        {{ trx_json_extract('src', ['LOWREGNUMBERDECIMALS'], type='int', alias='lowregnumberdecimals') }},
        {{ trx_json_extract('src', ['CONFIGURATION'], type='varchar', alias='configuration') }},
        {{ trx_json_extract('src', ['HIGHREGNUMBERDECIMALS'], type='int', alias='highregnumberdecimals') }},
        {{ trx_json_extract('src', ['HIGHREGMULTIPLIER'], type='int', alias='highregmultiplier') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['HIGHREGNUMBERDIALS'], type='int', alias='highregnumberdials') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['UNITOFMEASURE'], type='varchar', alias='unitofmeasure') }},
        {{ trx_json_extract('src', ['CODE'], type='varchar', alias='code') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['DESCRIPT'], type='varchar', alias='descript') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['LOWREGMULTIPLIER'], type='int', alias='lowregmultiplier') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_water_watermetertype') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['code']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
