{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_RAILWAY.COMPRSEG on 2022-01-07T14:04:05.431',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TOREFUOM'], type='varchar', alias='torefuom') }},
        {{ trx_json_extract('src', ['COMPLEXKEY'], type='int', alias='complexkey') }},
        {{ trx_json_extract('src', ['LOADLIMIT'], type='int', alias='loadlimit') }},
        {{ trx_json_extract('src', ['ZCOORD'], type='float', alias='zcoord') }},
        {{ trx_json_extract('src', ['USGAREAKEY'], type='int', alias='usgareakey') }},
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['ELEVLOWUOM'], type='varchar', alias='elevlowuom') }},
        {{ trx_json_extract('src', ['GRADE'], type='float', alias='grade') }},
        {{ trx_json_extract('src', ['UNITID2'], type='varchar', alias='unitid2') }},
        {{ trx_json_extract('src', ['SUBAREA'], type='varchar', alias='subarea') }},
        {{ trx_json_extract('src', ['ELEVHIGH'], type='float', alias='elevhigh') }},
        {{ trx_json_extract('src', ['MEASVOLUOM'], type='varchar', alias='measvoluom') }},
        {{ trx_json_extract('src', ['FRREF'], type='float', alias='frref') }},
        {{ trx_json_extract('src', ['PERFREIGHT'], type='int', alias='perfreight') }},
        {{ trx_json_extract('src', ['UNITDESC'], type='varchar', alias='unitdesc') }},
        {{ trx_json_extract('src', ['INSTDATE'], type='timestamp_ntz', alias='instdate') }},
        {{ trx_json_extract('src', ['PERGROWTH'], type='int', alias='pergrowth') }},
        {{ trx_json_extract('src', ['SEGLEN'], type='float', alias='seglen') }},
        {{ trx_json_extract('src', ['FRREFUOM'], type='varchar', alias='frrefuom') }},
        {{ trx_json_extract('src', ['UNITTYPE'], type='varchar', alias='unittype') }},
        {{ trx_json_extract('src', ['OWN'], type='varchar', alias='own') }},
        {{ trx_json_extract('src', ['RAILKEY'], type='int', alias='railkey') }},
        {{ trx_json_extract('src', ['DESIGNVOL'], type='int', alias='designvol') }},
        {{ trx_json_extract('src', ['MEASVOL'], type='int', alias='measvol') }},
        {{ trx_json_extract('src', ['BUDGETKEY'], type='int', alias='budgetkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PRCLKEY'], type='int', alias='prclkey') }},
        {{ trx_json_extract('src', ['ASBLT'], type='varchar', alias='asblt') }},
        {{ trx_json_extract('src', ['BASETYPE'], type='varchar', alias='basetype') }},
        {{ trx_json_extract('src', ['PARLINENO'], type='varchar', alias='parlineno') }},
        {{ trx_json_extract('src', ['LOC'], type='varchar', alias='loc') }},
        {{ trx_json_extract('src', ['DESIGNVOLUOM'], type='varchar', alias='designvoluom') }},
        {{ trx_json_extract('src', ['SERVSTAT'], type='varchar', alias='servstat') }},
        {{ trx_json_extract('src', ['MAPNO'], type='varchar', alias='mapno') }},
        {{ trx_json_extract('src', ['ELEVHIGHUOM'], type='varchar', alias='elevhighuom') }},
        {{ trx_json_extract('src', ['UNITID'], type='varchar', alias='unitid') }},
        {{ trx_json_extract('src', ['BLDGROOM'], type='int', alias='bldgroom') }},
        {{ trx_json_extract('src', ['BASEDPTHUOM'], type='varchar', alias='basedpthuom') }},
        {{ trx_json_extract('src', ['YCOORD'], type='float', alias='ycoord') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['SEGLENUOM'], type='varchar', alias='seglenuom') }},
        {{ trx_json_extract('src', ['AREA'], type='varchar', alias='area') }},
        {{ trx_json_extract('src', ['TOREF'], type='float', alias='toref') }},
        {{ trx_json_extract('src', ['SITEKEY'], type='int', alias='sitekey') }},
        {{ trx_json_extract('src', ['LOADLIMITUOM'], type='varchar', alias='loadlimituom') }},
        {{ trx_json_extract('src', ['ADDRQUAL'], type='varchar', alias='addrqual') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['GISSTATIC'], type='int', alias='gisstatic') }},
        {{ trx_json_extract('src', ['RSTNKEY'], type='int', alias='rstnkey') }},
        {{ trx_json_extract('src', ['MEASDATE'], type='timestamp_ntz', alias='measdate') }},
        {{ trx_json_extract('src', ['XCOORD'], type='float', alias='xcoord') }},
        {{ trx_json_extract('src', ['EXPBY'], type='varchar', alias='expby') }},
        {{ trx_json_extract('src', ['ELEVLOW'], type='float', alias='elevlow') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['DISTRICT'], type='varchar', alias='district') }},
        {{ trx_json_extract('src', ['BGTNO'], type='varchar', alias='bgtno') }},
        {{ trx_json_extract('src', ['BLDGFLOOR'], type='int', alias='bldgfloor') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['BASEDPTH'], type='float', alias='basedpth') }},
        {{ trx_json_extract('src', ['SUBGRDSTRN'], type='varchar', alias='subgrdstrn') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_railway_comprseg') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
