{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_WATER.COMPWSU on 2022-01-07T14:04:32.545',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COMPLEXKEY'], type='int', alias='complexkey') }},
        {{ trx_json_extract('src', ['ZCOORD'], type='float', alias='zcoord') }},
        {{ trx_json_extract('src', ['THICKNESSUOM'], type='varchar', alias='thicknessuom') }},
        {{ trx_json_extract('src', ['USGAREAKEY'], type='int', alias='usgareakey') }},
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['CAPUM'], type='varchar', alias='capum') }},
        {{ trx_json_extract('src', ['DPTHUOM'], type='varchar', alias='dpthuom') }},
        {{ trx_json_extract('src', ['DIAM'], type='float', alias='diam') }},
        {{ trx_json_extract('src', ['SUBAREA'], type='varchar', alias='subarea') }},
        {{ trx_json_extract('src', ['WLEVUM'], type='varchar', alias='wlevum') }},
        {{ trx_json_extract('src', ['WATLEV'], type='float', alias='watlev') }},
        {{ trx_json_extract('src', ['HTUOM'], type='varchar', alias='htuom') }},
        {{ trx_json_extract('src', ['UNITDESC'], type='varchar', alias='unitdesc') }},
        {{ trx_json_extract('src', ['INSTDATE'], type='timestamp_ntz', alias='instdate') }},
        {{ trx_json_extract('src', ['OVERELEV'], type='float', alias='overelev') }},
        {{ trx_json_extract('src', ['SERNO'], type='varchar', alias='serno') }},
        {{ trx_json_extract('src', ['OVERELEVUOM'], type='varchar', alias='overelevuom') }},
        {{ trx_json_extract('src', ['UNITTYPE'], type='varchar', alias='unittype') }},
        {{ trx_json_extract('src', ['OWN'], type='varchar', alias='own') }},
        {{ trx_json_extract('src', ['GROUNDELEVUOM'], type='varchar', alias='groundelevuom') }},
        {{ trx_json_extract('src', ['BUDGETKEY'], type='int', alias='budgetkey') }},
        {{ trx_json_extract('src', ['PRESZONE'], type='varchar', alias='preszone') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PRCLKEY'], type='int', alias='prclkey') }},
        {{ trx_json_extract('src', ['ASBLT'], type='varchar', alias='asblt') }},
        {{ trx_json_extract('src', ['LOC'], type='varchar', alias='loc') }},
        {{ trx_json_extract('src', ['SERVSTAT'], type='varchar', alias='servstat') }},
        {{ trx_json_extract('src', ['MAPNO'], type='varchar', alias='mapno') }},
        {{ trx_json_extract('src', ['UNITID'], type='varchar', alias='unitid') }},
        {{ trx_json_extract('src', ['BLDGROOM'], type='int', alias='bldgroom') }},
        {{ trx_json_extract('src', ['YCOORD'], type='float', alias='ycoord') }},
        {{ trx_json_extract('src', ['MODELNO'], type='varchar', alias='modelno') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['THICKNESS'], type='float', alias='thickness') }},
        {{ trx_json_extract('src', ['DIAMUOM'], type='varchar', alias='diamuom') }},
        {{ trx_json_extract('src', ['AREA'], type='varchar', alias='area') }},
        {{ trx_json_extract('src', ['SITEKEY'], type='int', alias='sitekey') }},
        {{ trx_json_extract('src', ['CAP'], type='float', alias='cap') }},
        {{ trx_json_extract('src', ['ADDRQUAL'], type='varchar', alias='addrqual') }},
        {{ trx_json_extract('src', ['GROUNDELEV'], type='float', alias='groundelev') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['GISSTATIC'], type='int', alias='gisstatic') }},
        {{ trx_json_extract('src', ['POSITION'], type='int', alias='position') }},
        {{ trx_json_extract('src', ['XCOORD'], type='float', alias='xcoord') }},
        {{ trx_json_extract('src', ['EXPBY'], type='varchar', alias='expby') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['DISTRICT'], type='varchar', alias='district') }},
        {{ trx_json_extract('src', ['BGTNO'], type='varchar', alias='bgtno') }},
        {{ trx_json_extract('src', ['BLDGFLOOR'], type='int', alias='bldgfloor') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MFGKEY'], type='int', alias='mfgkey') }},
        {{ trx_json_extract('src', ['SEGKEY'], type='int', alias='segkey') }},
        {{ trx_json_extract('src', ['HT'], type='float', alias='ht') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['DPTH'], type='float', alias='dpth') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_water_compwsu') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
