{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT.ASSETGRP on 2022-01-07T14:05:04.211',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['GROUPKEY'], type='int', alias='groupkey') }},
        {{ trx_json_extract('src', ['ROUTETIME'], type='varchar', alias='routetime') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['GROUPDESC'], type='varchar', alias='groupdesc') }},
        {{ trx_json_extract('src', ['ACCTGRP'], type='varchar', alias='acctgrp') }},
        {{ trx_json_extract('src', ['ROUTEFLAG'], type='varchar', alias='routeflag') }},
        {{ trx_json_extract('src', ['GROUPID'], type='varchar', alias='groupid') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_assetgrp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['groupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
