{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_ASSETVALUATION.ASSVALUE on 2022-05-27T11:40:40.680',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DISJOURNALDATE'], type='timestamp_ntz', alias='disjournaldate') }},
        {{ trx_json_extract('src', ['DEPRECTYPE'], type='int', alias='deprectype') }},
        {{ trx_json_extract('src', ['VALDATE'], type='timestamp_ntz', alias='valdate') }},
        {{ trx_json_extract('src', ['COMPTYPE'], type='int', alias='comptype') }},
        {{ trx_json_extract('src', ['WRITEDNVAL'], type='float', alias='writednval') }},
        {{ trx_json_extract('src', ['TOBESOLDDATE'], type='timestamp_ntz', alias='tobesolddate') }},
        {{ trx_json_extract('src', ['BGTKEY'], type='int', alias='bgtkey') }},
        {{ trx_json_extract('src', ['DISPDESC'], type='varchar', alias='dispdesc') }},
        {{ trx_json_extract('src', ['RWATTRKEY'], type='int', alias='rwattrkey') }},
        {{ trx_json_extract('src', ['MAINTEXP'], type='float', alias='maintexp') }},
        {{ trx_json_extract('src', ['RWATTRTYPE'], type='varchar', alias='rwattrtype') }},
        {{ trx_json_extract('src', ['ACCDEPREC'], type='float', alias='accdeprec') }},
        {{ trx_json_extract('src', ['REVALAMT'], type='float', alias='revalamt') }},
        {{ trx_json_extract('src', ['DISPBGTKEY'], type='int', alias='dispbgtkey') }},
        {{ trx_json_extract('src', ['DISPBGTNO'], type='varchar', alias='dispbgtno') }},
        {{ trx_json_extract('src', ['DEPRECYTD'], type='float', alias='deprecytd') }},
        {{ trx_json_extract('src', ['TAXVAL'], type='float', alias='taxval') }},
        {{ trx_json_extract('src', ['CAPTLDATE'], type='timestamp_ntz', alias='captldate') }},
        {{ trx_json_extract('src', ['LINEARFROMM'], type='float', alias='linearfromm') }},
        {{ trx_json_extract('src', ['ACQTYPE'], type='varchar', alias='acqtype') }},
        {{ trx_json_extract('src', ['BGTKEY2'], type='int', alias='bgtkey2') }},
        {{ trx_json_extract('src', ['CATEGORY'], type='varchar', alias='category') }},
        {{ trx_json_extract('src', ['RESIDLIFE'], type='float', alias='residlife') }},
        {{ trx_json_extract('src', ['DISPVAL'], type='float', alias='dispval') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['DISPDATE'], type='timestamp_ntz', alias='dispdate') }},
        {{ trx_json_extract('src', ['EXPLIFE'], type='float', alias='explife') }},
        {{ trx_json_extract('src', ['CLASS'], type='varchar', alias='class') }},
        {{ trx_json_extract('src', ['BOOKID'], type='varchar', alias='bookid') }},
        {{ trx_json_extract('src', ['RESIDVAL'], type='float', alias='residval') }},
        {{ trx_json_extract('src', ['INSUREVAL'], type='float', alias='insureval') }},
        {{ trx_json_extract('src', ['DEPRESIDLF'], type='float', alias='depresidlf') }},
        {{ trx_json_extract('src', ['ACQDATE'], type='timestamp_ntz', alias='acqdate') }},
        {{ trx_json_extract('src', ['PROFITLOSS'], type='float', alias='profitloss') }},
        {{ trx_json_extract('src', ['LINEARTOFT'], type='float', alias='lineartoft') }},
        {{ trx_json_extract('src', ['INITCOST'], type='float', alias='initcost') }},
        {{ trx_json_extract('src', ['LINEARFROMFT'], type='float', alias='linearfromft') }},
        {{ trx_json_extract('src', ['BGTKEY3'], type='int', alias='bgtkey3') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['ISDISPOSED'], type='varchar', alias='isdisposed') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ASSVALKEY'], type='int', alias='assvalkey') }},
        {{ trx_json_extract('src', ['BGTNO'], type='varchar', alias='bgtno') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['TOBESOLDDESC'], type='varchar', alias='tobesolddesc') }},
        {{ trx_json_extract('src', ['DEPRECRATE'], type='float', alias='deprecrate') }},
        {{ trx_json_extract('src', ['LINEARTOM'], type='float', alias='lineartom') }},
        {{ trx_json_extract('src', ['CAPTLEXP'], type='float', alias='captlexp') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_assetvaluation_assvalue') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['assvalkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
