{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT.GRPINSPCOSTPEQ on 2022-01-07T14:03:52.623',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CHRGDTTM'], type='timestamp_ntz', alias='chrgdttm') }},
        {{ trx_json_extract('src', ['GRPINSPKEY'], type='int', alias='grpinspkey') }},
        {{ trx_json_extract('src', ['COMMENTS'], type='varchar', alias='comments') }},
        {{ trx_json_extract('src', ['COSTKEY'], type='int', alias='costkey') }},
        {{ trx_json_extract('src', ['CHRGDTTMTO'], type='timestamp_ntz', alias='chrgdttmto') }},
        {{ trx_json_extract('src', ['TOTCOST'], type='float', alias='totcost') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['EQTYPE'], type='varchar', alias='eqtype') }},
        {{ trx_json_extract('src', ['USAGE'], type='float', alias='usage') }},
        {{ trx_json_extract('src', ['RATE'], type='float', alias='rate') }},
        {{ trx_json_extract('src', ['SRCBGTKEY'], type='int', alias='srcbgtkey') }},
        {{ trx_json_extract('src', ['EQKEY'], type='int', alias='eqkey') }},
        {{ trx_json_extract('src', ['DSTBGTKEY'], type='int', alias='dstbgtkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['OPERATOR'], type='varchar', alias='operator') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_grpinspcostpeq') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['costkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
