{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_ASSETVALUATION.ASSREVAL on 2022-05-11T15:26:57.199',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['VALDTTM'], type='timestamp_ntz', alias='valdttm') }},
        {{ trx_json_extract('src', ['REVALKEY'], type='int', alias='revalkey') }},
        {{ trx_json_extract('src', ['ACCDEPREC'], type='float', alias='accdeprec') }},
        {{ trx_json_extract('src', ['REASON'], type='varchar', alias='reason') }},
        {{ trx_json_extract('src', ['NEWRESDVAL'], type='float', alias='newresdval') }},
        {{ trx_json_extract('src', ['JOBNO'], type='varchar', alias='jobno') }},
        {{ trx_json_extract('src', ['MARKETVAL'], type='float', alias='marketval') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['COND'], type='varchar', alias='cond') }},
        {{ trx_json_extract('src', ['VALUER'], type='varchar', alias='valuer') }},
        {{ trx_json_extract('src', ['EFFECTIVEDTTM'], type='timestamp_ntz', alias='effectivedttm') }},
        {{ trx_json_extract('src', ['REPLCCOST'], type='float', alias='replccost') }},
        {{ trx_json_extract('src', ['REVALMTHD'], type='int', alias='revalmthd') }},
        {{ trx_json_extract('src', ['ASSVALRUNKEY'], type='int', alias='assvalrunkey') }},
        {{ trx_json_extract('src', ['JOURNALVALUATIONRUN'], type='int', alias='journalvaluationrun') }},
        {{ trx_json_extract('src', ['JOURNALDATE'], type='timestamp_ntz', alias='journaldate') }},
        {{ trx_json_extract('src', ['NEWDEPRATE'], type='float', alias='newdeprate') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ASSVALKEY'], type='int', alias='assvalkey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DELETED'], type='int', alias='deleted') }},
        {{ trx_json_extract('src', ['NEWEXPLIFE'], type='float', alias='newexplife') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_assetvaluation_assreval') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['revalkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
