{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_ASSETVALUATION.ASSDEPRE on 2022-05-11T15:26:57.456',
    tags=['auto-generated', 'ips', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DEPRECAMT'], type='float', alias='deprecamt') }},
        {{ trx_json_extract('src', ['REVALFLAG'], type='varchar', alias='revalflag') }},
        {{ trx_json_extract('src', ['DEPRECTYPE'], type='int', alias='deprectype') }},
        {{ trx_json_extract('src', ['WRITEDNVAL'], type='float', alias='writednval') }},
        {{ trx_json_extract('src', ['BGTKEY'], type='int', alias='bgtkey') }},
        {{ trx_json_extract('src', ['PERIODADJDEPREC'], type='float', alias='periodadjdeprec') }},
        {{ trx_json_extract('src', ['ACCDEPREC'], type='float', alias='accdeprec') }},
        {{ trx_json_extract('src', ['RECLDEPKEY'], type='int', alias='recldepkey') }},
        {{ trx_json_extract('src', ['DEPRECYTD'], type='float', alias='deprecytd') }},
        {{ trx_json_extract('src', ['TOBESOLDFLAG'], type='varchar', alias='tobesoldflag') }},
        {{ trx_json_extract('src', ['RESIDLIFE'], type='float', alias='residlife') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['EXPLIFE'], type='float', alias='explife') }},
        {{ trx_json_extract('src', ['EFFECTIVEDTTM'], type='timestamp_ntz', alias='effectivedttm') }},
        {{ trx_json_extract('src', ['DEPRECKEY'], type='int', alias='depreckey') }},
        {{ trx_json_extract('src', ['DISPSLFLAG'], type='varchar', alias='dispslflag') }},
        {{ trx_json_extract('src', ['RESIDVAL'], type='float', alias='residval') }},
        {{ trx_json_extract('src', ['DEPRECDATE'], type='timestamp_ntz', alias='deprecdate') }},
        {{ trx_json_extract('src', ['ASSVALDATE'], type='timestamp_ntz', alias='assvaldate') }},
        {{ trx_json_extract('src', ['ACQDATE'], type='timestamp_ntz', alias='acqdate') }},
        {{ trx_json_extract('src', ['REVALFINALCOST'], type='float', alias='revalfinalcost') }},
        {{ trx_json_extract('src', ['ASSVALRUNKEY'], type='int', alias='assvalrunkey') }},
        {{ trx_json_extract('src', ['JOURNALDATE'], type='timestamp_ntz', alias='journaldate') }},
        {{ trx_json_extract('src', ['RECLNO'], type='int', alias='reclno') }},
        {{ trx_json_extract('src', ['BACKDATEADJFLAG'], type='varchar', alias='backdateadjflag') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ASSVALKEY'], type='int', alias='assvalkey') }},
        {{ trx_json_extract('src', ['BGTNO'], type='varchar', alias='bgtno') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DEPRECRATE'], type='float', alias='deprecrate') }},
        {{ trx_json_extract('src', ['CAPTLEXP'], type='float', alias='captlexp') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['DEPRECPERD'], type='float', alias='deprecperd') }},
        {{ trx_json_extract('src', ['ACCPERIOD'], type='int', alias='accperiod') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_assetvaluation_assdepre') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['depreckey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
