{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table ASSETMANAGEMENT_WATER.METERREADING on 2021-07-09T15:14:59.487',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['AUDITFLAG'], type='varchar', alias='auditflag') }},
        {{ trx_json_extract('src', ['FIELDNOTES'], type='varchar', alias='fieldnotes') }},
        {{ trx_json_extract('src', ['READING'], type='float', alias='reading') }},
        {{ trx_json_extract('src', ['NOREADFLAG'], type='varchar', alias='noreadflag') }},
        {{ trx_json_extract('src', ['READREAS'], type='varchar', alias='readreas') }},
        {{ trx_json_extract('src', ['PROBCODESRVREQNO'], type='int', alias='probcodesrvreqno') }},
        {{ trx_json_extract('src', ['CYCLE'], type='varchar', alias='cycle') }},
        {{ trx_json_extract('src', ['INSPKEY'], type='int', alias='inspkey') }},
        {{ trx_json_extract('src', ['BLUSAGECUBICFT'], type='float', alias='blusagecubicft') }},
        {{ trx_json_extract('src', ['HISTKEY'], type='int', alias='histkey') }},
        {{ trx_json_extract('src', ['HIGHREADING'], type='float', alias='highreading') }},
        {{ trx_json_extract('src', ['HIGHBLUSAGEINCUBICFEET'], type='float', alias='highblusageincubicfeet') }},
        {{ trx_json_extract('src', ['GRPPROJ'], type='int', alias='grpproj') }},
        {{ trx_json_extract('src', ['READINGKEY'], type='int', alias='readingkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['READVAL4'], type='varchar', alias='readval4') }},
        {{ trx_json_extract('src', ['READVAL3'], type='varchar', alias='readval3') }},
        {{ trx_json_extract('src', ['PROBBCODEWO'], type='int', alias='probbcodewo') }},
        {{ trx_json_extract('src', ['ESTMFLAG'], type='varchar', alias='estmflag') }},
        {{ trx_json_extract('src', ['READVAL1'], type='varchar', alias='readval1') }},
        {{ trx_json_extract('src', ['USAGE'], type='float', alias='usage') }},
        {{ trx_json_extract('src', ['HIGHUSAGE'], type='float', alias='highusage') }},
        {{ trx_json_extract('src', ['PROBLEMCODE'], type='varchar', alias='problemcode') }},
        {{ trx_json_extract('src', ['READDTTM'], type='timestamp_ntz', alias='readdttm') }},
        {{ trx_json_extract('src', ['HIGHBLUSAGE'], type='float', alias='highblusage') }},
        {{ trx_json_extract('src', ['FINALFLAG'], type='varchar', alias='finalflag') }},
        {{ trx_json_extract('src', ['READSRC'], type='varchar', alias='readsrc') }},
        {{ trx_json_extract('src', ['READERCODEWO'], type='int', alias='readercodewo') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['BLUSAGE'], type='float', alias='blusage') }},
        {{ trx_json_extract('src', ['CUSTPROB'], type='int', alias='custprob') }},
        {{ trx_json_extract('src', ['CORRFLAG'], type='varchar', alias='corrflag') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['READYFLAG'], type='varchar', alias='readyflag') }},
        {{ trx_json_extract('src', ['READBY'], type='varchar', alias='readby') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['READVAL2'], type='varchar', alias='readval2') }},
        {{ trx_json_extract('src', ['INITFLAG'], type='varchar', alias='initflag') }},
        {{ trx_json_extract('src', ['RDRCODESRVREQNO'], type='int', alias='rdrcodesrvreqno') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['READERCODE'], type='varchar', alias='readercode') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_assetmanagement_water_meterreading') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['readingkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
