{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.LINEITEMSETUP on 2021-07-09T15:14:58.639',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['INCLUDEINBUDGETEDAMOUNTFLAG'], type='varchar', alias='includeinbudgetedamountflag') }},
        {{ trx_json_extract('src', ['COMMENTSKEY'], type='int', alias='commentskey') }},
        {{ trx_json_extract('src', ['AUTOMATEDFLAG'], type='varchar', alias='automatedflag') }},
        {{ trx_json_extract('src', ['ROUNDTO'], type='float', alias='roundto') }},
        {{ trx_json_extract('src', ['TYPEINDICATOR'], type='int', alias='typeindicator') }},
        {{ trx_json_extract('src', ['TAXAREA'], type='varchar', alias='taxarea') }},
        {{ trx_json_extract('src', ['PROPERTYBASEDFLAG'], type='varchar', alias='propertybasedflag') }},
        {{ trx_json_extract('src', ['SETTLEMENTLINEITEMSETUPKEY'], type='int', alias='settlementlineitemsetupkey') }},
        {{ trx_json_extract('src', ['SERVICEOPTIONSKEY'], type='int', alias='serviceoptionskey') }},
        {{ trx_json_extract('src', ['APPLYDEPOSITFLAG'], type='varchar', alias='applydepositflag') }},
        {{ trx_json_extract('src', ['DESIGNATION'], type='varchar', alias='designation') }},
        {{ trx_json_extract('src', ['ONEOFFOPTIONINDICATOR'], type='int', alias='oneoffoptionindicator') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['BILLINGFAMILY'], type='int', alias='billingfamily') }},
        {{ trx_json_extract('src', ['FORTRANSFERFLAG'], type='varchar', alias='fortransferflag') }},
        {{ trx_json_extract('src', ['DONATIONFLAG'], type='varchar', alias='donationflag') }},
        {{ trx_json_extract('src', ['BUDGETBILLINGVARIANTFLAG'], type='varchar', alias='budgetbillingvariantflag') }},
        {{ trx_json_extract('src', ['APPROVALGROUP'], type='int', alias='approvalgroup') }},
        {{ trx_json_extract('src', ['LINEITEM'], type='varchar', alias='lineitem') }},
        {{ trx_json_extract('src', ['NUMBEROFPROMPTPAIDBILLS'], type='int', alias='numberofpromptpaidbills') }},
        {{ trx_json_extract('src', ['RATECHANGEALGORITHM'], type='int', alias='ratechangealgorithm') }},
        {{ trx_json_extract('src', ['INITIALDEPOSITCHARGEFLAG'], type='varchar', alias='initialdepositchargeflag') }},
        {{ trx_json_extract('src', ['CONDITIONFORMULAKEY'], type='int', alias='conditionformulakey') }},
        {{ trx_json_extract('src', ['QUANTITYBASEDFLAG'], type='varchar', alias='quantitybasedflag') }},
        {{ trx_json_extract('src', ['LINEITEMGROUP'], type='varchar', alias='lineitemgroup') }},
        {{ trx_json_extract('src', ['FORTRANSFERPAYMENTFLAG'], type='varchar', alias='fortransferpaymentflag') }},
        {{ trx_json_extract('src', ['DEFAULTQUANTITY'], type='int', alias='defaultquantity') }},
        {{ trx_json_extract('src', ['FEETYPEKEY'], type='int', alias='feetypekey') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['ISPRINTTEXTEDITABLE'], type='varchar', alias='isprinttexteditable') }},
        {{ trx_json_extract('src', ['PENALTYCODEKEY'], type='int', alias='penaltycodekey') }},
        {{ trx_json_extract('src', ['LINEITEMTYPE'], type='varchar', alias='lineitemtype') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['BBSETLFLAG'], type='varchar', alias='bbsetlflag') }},
        {{ trx_json_extract('src', ['LINEITEMSETUPKEY'], type='int', alias='lineitemsetupkey') }},
        {{ trx_json_extract('src', ['VALUEBASEDFLAG'], type='varchar', alias='valuebasedflag') }},
        {{ trx_json_extract('src', ['DEFAULTADJUSTMENTSETUPKEY'], type='int', alias='defaultadjustmentsetupkey') }},
        {{ trx_json_extract('src', ['SRVBASEDOPTIONINDICATOR'], type='int', alias='srvbasedoptionindicator') }},
        {{ trx_json_extract('src', ['APPROVALSCHEME'], type='int', alias='approvalscheme') }},
        {{ trx_json_extract('src', ['VALUEFORMULAKEY'], type='int', alias='valueformulakey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['DELINQUENCYEXEMPTFLAG'], type='varchar', alias='delinquencyexemptflag') }},
        {{ trx_json_extract('src', ['RATECODEKEY'], type='int', alias='ratecodekey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PRINTTEXT'], type='varchar', alias='printtext') }},
        {{ trx_json_extract('src', ['PROMPTPAIDPERIOD'], type='int', alias='promptpaidperiod') }},
        {{ trx_json_extract('src', ['TAXINCLUSIVEFLAG'], type='varchar', alias='taxinclusiveflag') }},
        {{ trx_json_extract('src', ['MULTIDISTRIBUTIOLNALFLAG'], type='varchar', alias='multidistributiolnalflag') }},
        {{ trx_json_extract('src', ['REBATEGROUP'], type='varchar', alias='rebategroup') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_lineitemsetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['lineitemsetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
