{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.PAYMENTREVERSALREASON on 2022-03-03T11:33:34.489',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CREDITRATINGPOINTSCODE'], type='varchar', alias='creditratingpointscode') }},
        {{ trx_json_extract('src', ['NSFDEFAULTFLAG'], type='varchar', alias='nsfdefaultflag') }},
        {{ trx_json_extract('src', ['ALERTDEFINITIONKEY'], type='int', alias='alertdefinitionkey') }},
        {{ trx_json_extract('src', ['NSFTYPEFLAG'], type='varchar', alias='nsftypeflag') }},
        {{ trx_json_extract('src', ['ALERTDAYS'], type='int', alias='alertdays') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['TEXTCOLOR'], type='int', alias='textcolor') }},
        {{ trx_json_extract('src', ['LOGTYPE'], type='varchar', alias='logtype') }},
        {{ trx_json_extract('src', ['FORTRANSFERPAYMENTFLAG'], type='varchar', alias='fortransferpaymentflag') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['CODE'], type='varchar', alias='code') }},
        {{ trx_json_extract('src', ['OVERRIDENSFFEEFLAG'], type='varchar', alias='overridensffeeflag') }},
        {{ trx_json_extract('src', ['NSFEXCEPTIONFLAG'], type='varchar', alias='nsfexceptionflag') }},
        {{ trx_json_extract('src', ['SENDNOTICEFLAG'], type='varchar', alias='sendnoticeflag') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['DESCRIPT'], type='varchar', alias='descript') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['BACKCOLOR'], type='int', alias='backcolor') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_paymentreversalreason') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['code']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
