{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.PAYSPECIFICBILL on 2021-07-09T15:15:03.166',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['BILLKEY'], type='int', alias='billkey') }},
        {{ trx_json_extract('src', ['ONEOFFCHARGEKEY'], type='int', alias='oneoffchargekey') }},
        {{ trx_json_extract('src', ['ADJUSTMENTKEY'], type='int', alias='adjustmentkey') }},
        {{ trx_json_extract('src', ['DEPOSITADJUSTMENTKEY'], type='int', alias='depositadjustmentkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LINEITEMKEY'], type='int', alias='lineitemkey') }},
        {{ trx_json_extract('src', ['PAYORDER'], type='int', alias='payorder') }},
        {{ trx_json_extract('src', ['PAYMENTKEY'], type='int', alias='paymentkey') }},
        {{ trx_json_extract('src', ['DEPOSITCHARGEKEY'], type='int', alias='depositchargekey') }},
        {{ trx_json_extract('src', ['PAYSPECIFICBILLKEY'], type='int', alias='payspecificbillkey') }},
        {{ trx_json_extract('src', ['CDRAPPLICATIONFEEKEY'], type='int', alias='cdrapplicationfeekey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ORIGPAYALLOCAMT'], type='float', alias='origpayallocamt') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_payspecificbill') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['payspecificbillkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
