{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.PENALTY on 2021-07-09T15:15:03.603',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CANCELREBILLRUN'], type='varchar', alias='cancelrebillrun') }},
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['TOTALAMOUNT'], type='float', alias='totalamount') }},
        {{ trx_json_extract('src', ['BILLKEY'], type='int', alias='billkey') }},
        {{ trx_json_extract('src', ['SCHEDULEKEY'], type='int', alias='schedulekey') }},
        {{ trx_json_extract('src', ['BILLTYPEKEY'], type='int', alias='billtypekey') }},
        {{ trx_json_extract('src', ['ROUTEKEY'], type='int', alias='routekey') }},
        {{ trx_json_extract('src', ['INITIATEDTTM'], type='timestamp_ntz', alias='initiatedttm') }},
        {{ trx_json_extract('src', ['STOPDTTM'], type='timestamp_ntz', alias='stopdttm') }},
        {{ trx_json_extract('src', ['WAIVEALLFLAG'], type='varchar', alias='waiveallflag') }},
        {{ trx_json_extract('src', ['REVERSEKEY'], type='int', alias='reversekey') }},
        {{ trx_json_extract('src', ['INITIATEDBY'], type='varchar', alias='initiatedby') }},
        {{ trx_json_extract('src', ['COMMITNUMBER'], type='int', alias='commitnumber') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['PROCESSFLAG'], type='varchar', alias='processflag') }},
        {{ trx_json_extract('src', ['PENASMDESC'], type='varchar', alias='penasmdesc') }},
        {{ trx_json_extract('src', ['RUNAVERAGE'], type='float', alias='runaverage') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LINEITEMKEY'], type='int', alias='lineitemkey') }},
        {{ trx_json_extract('src', ['RUNDATE'], type='timestamp_ntz', alias='rundate') }},
        {{ trx_json_extract('src', ['TOTALNUMBEROFACCOUNTS'], type='int', alias='totalnumberofaccounts') }},
        {{ trx_json_extract('src', ['ACCTSUBGRP'], type='varchar', alias='acctsubgrp') }},
        {{ trx_json_extract('src', ['ACCTGRP'], type='varchar', alias='acctgrp') }},
        {{ trx_json_extract('src', ['LASTINVOCATIONSTATUS'], type='int', alias='lastinvocationstatus') }},
        {{ trx_json_extract('src', ['PENALTYKEY'], type='int', alias='penaltykey') }},
        {{ trx_json_extract('src', ['NUMBEROFEXCEPTIONS'], type='int', alias='numberofexceptions') }},
        {{ trx_json_extract('src', ['BILLINGCYCLE'], type='varchar', alias='billingcycle') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['NUMBEROFACCOUNTS'], type='int', alias='numberofaccounts') }},
        {{ trx_json_extract('src', ['RUNTYPE'], type='varchar', alias='runtype') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_penalty') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['penaltykey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
