{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.COLLECTIONS on 2021-07-09T15:17:57.756',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['EXPORTEDFLAG'], type='varchar', alias='exportedflag') }},
        {{ trx_json_extract('src', ['INITIATEDBY'], type='varchar', alias='initiatedby') }},
        {{ trx_json_extract('src', ['COLLECTIONSAGENCYKEY'], type='int', alias='collectionsagencykey') }},
        {{ trx_json_extract('src', ['COLLECTIONSSTATUS'], type='varchar', alias='collectionsstatus') }},
        {{ trx_json_extract('src', ['COLLECTIONSDATE'], type='timestamp_ntz', alias='collectionsdate') }},
        {{ trx_json_extract('src', ['COLLECTIONSSTATUSDATE'], type='timestamp_ntz', alias='collectionsstatusdate') }},
        {{ trx_json_extract('src', ['COLLECTIONSCREDITOFFICER'], type='varchar', alias='collectionscreditofficer') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['COLLECTIONSKEY'], type='int', alias='collectionskey') }},
        {{ trx_json_extract('src', ['ISRESOLVED'], type='varchar', alias='isresolved') }},
        {{ trx_json_extract('src', ['RESOLUTION'], type='varchar', alias='resolution') }},
        {{ trx_json_extract('src', ['COLLECTIONSMETHOD'], type='varchar', alias='collectionsmethod') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['RESOLVEDDATE'], type='timestamp_ntz', alias='resolveddate') }},
        {{ trx_json_extract('src', ['RESOLVEDBY'], type='varchar', alias='resolvedby') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_collections') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['collectionskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
