{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.DIRECTDEBITSETUP on 2022-03-24T09:00:02.702',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FREQUENCYWEEKS'], type='varchar', alias='frequencyweeks') }},
        {{ trx_json_extract('src', ['PRENOTEEXTRACTDATEDAYS'], type='int', alias='prenoteextractdatedays') }},
        {{ trx_json_extract('src', ['REFRESHEXTRACTAMOUNT'], type='varchar', alias='refreshextractamount') }},
        {{ trx_json_extract('src', ['DIRECTDEBITCYCLE4DAY'], type='int', alias='directdebitcycle4day') }},
        {{ trx_json_extract('src', ['MINIMUMAMOUNT'], type='float', alias='minimumamount') }},
        {{ trx_json_extract('src', ['PRENOTENUMBEROFDAYS'], type='int', alias='prenotenumberofdays') }},
        {{ trx_json_extract('src', ['ACHFORMATFILE'], type='varchar', alias='achformatfile') }},
        {{ trx_json_extract('src', ['FREQUENCYDAYS'], type='varchar', alias='frequencydays') }},
        {{ trx_json_extract('src', ['DIRECTDEBITAMTCRITERIA'], type='varchar', alias='directdebitamtcriteria') }},
        {{ trx_json_extract('src', ['ACHOUTPUTDIRECTORY'], type='varchar', alias='achoutputdirectory') }},
        {{ trx_json_extract('src', ['PRENOTE'], type='varchar', alias='prenote') }},
        {{ trx_json_extract('src', ['FREQUENCYMONTHS'], type='varchar', alias='frequencymonths') }},
        {{ trx_json_extract('src', ['REFBALTHRUEXTRDATE'], type='varchar', alias='refbalthruextrdate') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['DIRECTDEBITCYCLE1DAY'], type='int', alias='directdebitcycle1day') }},
        {{ trx_json_extract('src', ['DIRECTDEBITCYCLE2DAY'], type='int', alias='directdebitcycle2day') }},
        {{ trx_json_extract('src', ['DIRECTDEBITCYCLE3DAY'], type='int', alias='directdebitcycle3day') }},
        {{ trx_json_extract('src', ['COMBINEAMOUNT'], type='varchar', alias='combineamount') }},
        {{ trx_json_extract('src', ['DIRECTDEBITCYCLENUMBER'], type='int', alias='directdebitcyclenumber') }},
        {{ trx_json_extract('src', ['MAXIMUMSUSPENSIONNUMBER'], type='int', alias='maximumsuspensionnumber') }},
        {{ trx_json_extract('src', ['ENABLEOTHERFLAG'], type='varchar', alias='enableotherflag') }},
        {{ trx_json_extract('src', ['MAXIMUMSUSPENSIONDAY'], type='int', alias='maximumsuspensionday') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['INCLUDEUNBILLED'], type='varchar', alias='includeunbilled') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MAXIMUMAMOUNT'], type='float', alias='maximumamount') }},
        {{ trx_json_extract('src', ['DIRECTDEBITSETUPKEY'], type='int', alias='directdebitsetupkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_directdebitsetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['directdebitsetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
