{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.QUANTITYFIELD on 2022-03-24T08:59:52.732',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['DISPLAYORDER'], type='int', alias='displayorder') }},
        {{ trx_json_extract('src', ['TOTALFIELDTEXT'], type='varchar', alias='totalfieldtext') }},
        {{ trx_json_extract('src', ['POSTINCRLINKTEXT'], type='varchar', alias='postincrlinktext') }},
        {{ trx_json_extract('src', ['SERVICEOPTIONSKEY'], type='int', alias='serviceoptionskey') }},
        {{ trx_json_extract('src', ['PROMPTTYPE'], type='int', alias='prompttype') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['QUANTITYFIELDKEY'], type='int', alias='quantityfieldkey') }},
        {{ trx_json_extract('src', ['MAXQTY'], type='int', alias='maxqty') }},
        {{ trx_json_extract('src', ['MOVEINPROMPT'], type='varchar', alias='moveinprompt') }},
        {{ trx_json_extract('src', ['DEFAULTQTY'], type='int', alias='defaultqty') }},
        {{ trx_json_extract('src', ['INCRLINKTEXT'], type='varchar', alias='incrlinktext') }},
        {{ trx_json_extract('src', ['DECRLINKTEXT'], type='varchar', alias='decrlinktext') }},
        {{ trx_json_extract('src', ['MOVEOUTNOTES'], type='varchar', alias='moveoutnotes') }},
        {{ trx_json_extract('src', ['TITLE'], type='varchar', alias='title') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['SHOWMINMAXRANGEFLAG'], type='varchar', alias='showminmaxrangeflag') }},
        {{ trx_json_extract('src', ['MINQTY'], type='int', alias='minqty') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_quantityfield') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['quantityfieldkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
