{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.DELINQUENCYMSALERT on 2022-03-03T11:33:19.515',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['BELOWRESOLUTION'], type='varchar', alias='belowresolution') }},
        {{ trx_json_extract('src', ['APPLYTOACCOUNT'], type='varchar', alias='applytoaccount') }},
        {{ trx_json_extract('src', ['DISPLAYORDER'], type='int', alias='displayorder') }},
        {{ trx_json_extract('src', ['MILESTONEALERTKEY'], type='int', alias='milestonealertkey') }},
        {{ trx_json_extract('src', ['ALERTKEY'], type='int', alias='alertkey') }},
        {{ trx_json_extract('src', ['REASON'], type='varchar', alias='reason') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['INCREMENTRESOLUTION'], type='varchar', alias='incrementresolution') }},
        {{ trx_json_extract('src', ['APPLYTOCONTACT'], type='varchar', alias='applytocontact') }},
        {{ trx_json_extract('src', ['PERFORMON'], type='varchar', alias='performon') }},
        {{ trx_json_extract('src', ['MILESTONEKEY'], type='int', alias='milestonekey') }},
        {{ trx_json_extract('src', ['CONDITIONFORMULA'], type='int', alias='conditionformula') }},
        {{ trx_json_extract('src', ['PAIDOFFRESOLUTION'], type='varchar', alias='paidoffresolution') }},
        {{ trx_json_extract('src', ['DECREMENTRESOLUTION'], type='varchar', alias='decrementresolution') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_delinquencymsalert') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['milestonealertkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
