{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.ACCOUNTDIRECTDEBITHISTORY on 2022-03-24T08:59:42.853',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['NEXTEXTRACTDATE'], type='timestamp_ntz', alias='nextextractdate') }},
        {{ trx_json_extract('src', ['TRANSMITDATE'], type='timestamp_ntz', alias='transmitdate') }},
        {{ trx_json_extract('src', ['DONATIONAMOUNT'], type='float', alias='donationamount') }},
        {{ trx_json_extract('src', ['DONATEFLAG'], type='varchar', alias='donateflag') }},
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['COMMENTSKEY'], type='int', alias='commentskey') }},
        {{ trx_json_extract('src', ['EXPIREDATE'], type='timestamp_ntz', alias='expiredate') }},
        {{ trx_json_extract('src', ['TRANSMITHOLD'], type='varchar', alias='transmithold') }},
        {{ trx_json_extract('src', ['EXTRACTDATE'], type='timestamp_ntz', alias='extractdate') }},
        {{ trx_json_extract('src', ['ACCOUNTDIRECTDEBITHISTKEY'], type='int', alias='accountdirectdebithistkey') }},
        {{ trx_json_extract('src', ['DIRECTDEBITSCHEDULEPLAN'], type='int', alias='directdebitscheduleplan') }},
        {{ trx_json_extract('src', ['IDENTITYBANKINGKEY'], type='int', alias='identitybankingkey') }},
        {{ trx_json_extract('src', ['LASTEXTRACTDATE'], type='timestamp_ntz', alias='lastextractdate') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['REFRESHBILLAMOUNT'], type='varchar', alias='refreshbillamount') }},
        {{ trx_json_extract('src', ['EXPIREREASON'], type='varchar', alias='expirereason') }},
        {{ trx_json_extract('src', ['EFFECTIVEDATE'], type='timestamp_ntz', alias='effectivedate') }},
        {{ trx_json_extract('src', ['DIRECDEBITCYCLE'], type='int', alias='direcdebitcycle') }},
        {{ trx_json_extract('src', ['DEBITREMAININGAMOUNT'], type='varchar', alias='debitremainingamount') }},
        {{ trx_json_extract('src', ['ACCOUNTDIRECTDEBITKEY'], type='int', alias='accountdirectdebitkey') }},
        {{ trx_json_extract('src', ['DEBITAMOUNT'], type='float', alias='debitamount') }},
        {{ trx_json_extract('src', ['DEBITFREQUENCY'], type='int', alias='debitfrequency') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['CONFIGUREDVALUE'], type='int', alias='configuredvalue') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_accountdirectdebithistory') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['accountdirectdebithistkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
