{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.JOURNALRUN on 2021-07-09T15:17:45.754',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['JOURNALRUNKEY'], type='int', alias='journalrunkey') }},
        {{ trx_json_extract('src', ['SCHEDULEKEY'], type='int', alias='schedulekey') }},
        {{ trx_json_extract('src', ['PROCESSINGFLAG'], type='varchar', alias='processingflag') }},
        {{ trx_json_extract('src', ['INITIATEDBY'], type='varchar', alias='initiatedby') }},
        {{ trx_json_extract('src', ['PROCWITHEXCEPTFLAG'], type='varchar', alias='procwithexceptflag') }},
        {{ trx_json_extract('src', ['COMMITNUMBER'], type='int', alias='commitnumber') }},
        {{ trx_json_extract('src', ['STARTOFRUNDTTM'], type='timestamp_ntz', alias='startofrundttm') }},
        {{ trx_json_extract('src', ['NUMBEROFDTPROCESSED'], type='int', alias='numberofdtprocessed') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ENDOFRUNDTTM'], type='timestamp_ntz', alias='endofrundttm') }},
        {{ trx_json_extract('src', ['INITIATEDDTTM'], type='timestamp_ntz', alias='initiateddttm') }},
        {{ trx_json_extract('src', ['AVGTRANPERMINUTE'], type='float', alias='avgtranperminute') }},
        {{ trx_json_extract('src', ['LASTINVOCATIONSTATUS'], type='int', alias='lastinvocationstatus') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['NUMBEROFATPROCESSED'], type='int', alias='numberofatprocessed') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_journalrun') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['journalrunkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
