{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.ACCOUNTALERT on 2025-01-30T11:48:16.412',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['ACCOUNTALERTKEY'], type='int', alias='accountalertkey') }},
        {{ trx_json_extract('src', ['ACCTALERTTYPE'], type='varchar', alias='acctalerttype') }},
        {{ trx_json_extract('src', ['INITIATEDBY'], type='varchar', alias='initiatedby') }},
        {{ trx_json_extract('src', ['DELINQUENCYMSALERTKEY'], type='int', alias='delinquencymsalertkey') }},
        {{ trx_json_extract('src', ['COMMENTS'], type='varchar', alias='comments') }},
        {{ trx_json_extract('src', ['REASON'], type='varchar', alias='reason') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['BANKRUPTCYKEY'], type='int', alias='bankruptcykey') }},
        {{ trx_json_extract('src', ['APPENDEDALERTTEXT'], type='varchar', alias='appendedalerttext') }},
        {{ trx_json_extract('src', ['ALERTDEFNKEY'], type='int', alias='alertdefnkey') }},
        {{ trx_json_extract('src', ['RESOLUTION'], type='varchar', alias='resolution') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['ACCOUNTDELINQUENCYKEY'], type='int', alias='accountdelinquencykey') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['RESOLVEDBY'], type='varchar', alias='resolvedby') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_accountalert') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['accountalertkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
