{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.MOVEINCUSTSEARCH on 2022-03-24T08:59:45.887',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['EMAILFLAG'], type='varchar', alias='emailflag') }},
        {{ trx_json_extract('src', ['PERFORMORDER'], type='int', alias='performorder') }},
        {{ trx_json_extract('src', ['FIRSTNAMEFLAG'], type='varchar', alias='firstnameflag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PHONEFLAG'], type='varchar', alias='phoneflag') }},
        {{ trx_json_extract('src', ['IDFLAG'], type='varchar', alias='idflag') }},
        {{ trx_json_extract('src', ['LICENSEFLAG'], type='varchar', alias='licenseflag') }},
        {{ trx_json_extract('src', ['MOVEINCUSTSEARCHKEY'], type='int', alias='moveincustsearchkey') }},
        {{ trx_json_extract('src', ['LASTNAMEFLAG'], type='varchar', alias='lastnameflag') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_moveincustsearch') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['moveincustsearchkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
