{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.LINEITEMPENALTYSTAGE on 2022-03-03T11:32:48.226',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PENALTYDATE'], type='timestamp_ntz', alias='penaltydate') }},
        {{ trx_json_extract('src', ['LINEITEMPENALTYSTAGEKEY'], type='int', alias='lineitempenaltystagekey') }},
        {{ trx_json_extract('src', ['PENALTYAMOUNT'], type='float', alias='penaltyamount') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['LINEITEMPENALTYKEY'], type='int', alias='lineitempenaltykey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DAILYNUMBEROFDAYS'], type='int', alias='dailynumberofdays') }},
        {{ trx_json_extract('src', ['PENALTYFREQUENCYKEY'], type='int', alias='penaltyfrequencykey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['LINEITEMAMOUNT'], type='float', alias='lineitemamount') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_lineitempenaltystage') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['lineitempenaltystagekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
