{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.LINEITEMPENDINGSTATES on 2022-03-03T11:32:47.925',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PAYMENTARRANGEMENTKEY'], type='int', alias='paymentarrangementkey') }},
        {{ trx_json_extract('src', ['LINEITEMPENDINGSTATESKEY'], type='int', alias='lineitempendingstateskey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['BANKRUPTCYKEY'], type='int', alias='bankruptcykey') }},
        {{ trx_json_extract('src', ['LINEITEMKEY'], type='int', alias='lineitemkey') }},
        {{ trx_json_extract('src', ['COLLECTIONSKEY'], type='int', alias='collectionskey') }},
        {{ trx_json_extract('src', ['DISPUTEKEY'], type='int', alias='disputekey') }},
        {{ trx_json_extract('src', ['PARCELLIENKEY'], type='int', alias='parcellienkey') }},
        {{ trx_json_extract('src', ['BUDGETBILLINGKEY'], type='int', alias='budgetbillingkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ADDRESSLIENKEY'], type='int', alias='addresslienkey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_lineitempendingstates') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['lineitempendingstateskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
