{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.JOURNALSETUP on 2022-03-24T09:00:03.699',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['JOURNALSETUPKEY'], type='int', alias='journalsetupkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['TRANSACTIONDESIGNATORDESC'], type='varchar', alias='transactiondesignatordesc') }},
        {{ trx_json_extract('src', ['CRBGTNOFRMLA'], type='int', alias='crbgtnofrmla') }},
        {{ trx_json_extract('src', ['DRBGTNOFRMLA'], type='int', alias='drbgtnofrmla') }},
        {{ trx_json_extract('src', ['TRANSACTIONTYPEDESC'], type='varchar', alias='transactiontypedesc') }},
        {{ trx_json_extract('src', ['TRANSACTIONDESIGNATOR'], type='int', alias='transactiondesignator') }},
        {{ trx_json_extract('src', ['TRANSACTIONTYPE'], type='int', alias='transactiontype') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_journalsetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['journalsetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
