{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.SERVICEFIELD on 2022-03-24T08:59:50.440',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['SERVICEFIELDKEY'], type='int', alias='servicefieldkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SETVALUEONADDRSERVFLAG'], type='varchar', alias='setvalueonaddrservflag') }},
        {{ trx_json_extract('src', ['MOVEINPROMPT'], type='varchar', alias='moveinprompt') }},
        {{ trx_json_extract('src', ['MOVEOUTNOTES'], type='varchar', alias='moveoutnotes') }},
        {{ trx_json_extract('src', ['TITLE'], type='varchar', alias='title') }},
        {{ trx_json_extract('src', ['VALIDATEVALUEFLAG'], type='varchar', alias='validatevalueflag') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DEFAULTVALUE'], type='float', alias='defaultvalue') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_servicefield') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['servicefieldkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
