{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.LINEITEMSETUPSERVICEDEFINITION on 2022-03-03T11:32:47.120',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['SERVICEDEFINITIONKEY'], type='int', alias='servicedefinitionkey') }},
        {{ trx_json_extract('src', ['SUBTOTAL'], type='float', alias='subtotal') }},
        {{ trx_json_extract('src', ['PRIMARYFLAG'], type='varchar', alias='primaryflag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['UNITOFMEASURE'], type='varchar', alias='unitofmeasure') }},
        {{ trx_json_extract('src', ['LINEITEMSETUPSERVDEFNKEY'], type='int', alias='lineitemsetupservdefnkey') }},
        {{ trx_json_extract('src', ['LINEITEMSETUPKEY'], type='int', alias='lineitemsetupkey') }},
        {{ trx_json_extract('src', ['VALUEFORMULAKEY'], type='int', alias='valueformulakey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_lineitemsetupservicedefinition') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['lineitemsetupservdefnkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
