{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.DEBITSCHEDULE on 2022-03-03T11:33:35.826',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['NEXTEXTRACTDATE'], type='timestamp_ntz', alias='nextextractdate') }},
        {{ trx_json_extract('src', ['BILLKEYS'], type='varchar', alias='billkeys') }},
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['PAYKEY'], type='int', alias='paykey') }},
        {{ trx_json_extract('src', ['EXTRACTDATE'], type='timestamp_ntz', alias='extractdate') }},
        {{ trx_json_extract('src', ['DEBITSCHEDULEKEY'], type='int', alias='debitschedulekey') }},
        {{ trx_json_extract('src', ['LASTEXTRACTDATE'], type='timestamp_ntz', alias='lastextractdate') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['DIRECTDEBITRUN'], type='int', alias='directdebitrun') }},
        {{ trx_json_extract('src', ['ACCOUNTDIRECTDEBITKEY'], type='int', alias='accountdirectdebitkey') }},
        {{ trx_json_extract('src', ['LATESTELIGIBLEBILL'], type='int', alias='latesteligiblebill') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_debitschedule') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['debitschedulekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
