{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.MOVEOUTSETUP on 2022-03-24T08:59:47.036',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['STAYINAREAPROMPT'], type='varchar', alias='stayinareaprompt') }},
        {{ trx_json_extract('src', ['LOGTYPECODE'], type='varchar', alias='logtypecode') }},
        {{ trx_json_extract('src', ['NEWACCTSRVSSECTORDER'], type='int', alias='newacctsrvssectorder') }},
        {{ trx_json_extract('src', ['MAXDAYSPASTTOALLOWMODIFY'], type='int', alias='maxdayspasttoallowmodify') }},
        {{ trx_json_extract('src', ['MOVEOUTSETUPKEY'], type='int', alias='moveoutsetupkey') }},
        {{ trx_json_extract('src', ['MOVETOADDRPROMPT'], type='varchar', alias='movetoaddrprompt') }},
        {{ trx_json_extract('src', ['NEWSRVFLAG'], type='varchar', alias='newsrvflag') }},
        {{ trx_json_extract('src', ['READINGREQUESTRESOLUTION'], type='varchar', alias='readingrequestresolution') }},
        {{ trx_json_extract('src', ['MOVEOUTDATEPROMPT'], type='varchar', alias='moveoutdateprompt') }},
        {{ trx_json_extract('src', ['COPYCNTCTSDEFAULTFLAG'], type='varchar', alias='copycntctsdefaultflag') }},
        {{ trx_json_extract('src', ['SHOWCANCELCNFRMCNTCTFLAG'], type='varchar', alias='showcancelcnfrmcntctflag') }},
        {{ trx_json_extract('src', ['CANCELLOGTYPE'], type='varchar', alias='cancellogtype') }},
        {{ trx_json_extract('src', ['CANCELCNFRMCNTCTSECTORDER'], type='int', alias='cancelcnfrmcntctsectorder') }},
        {{ trx_json_extract('src', ['MODMOVEOUTCNTCTSECTORDER'], type='int', alias='modmoveoutcntctsectorder') }},
        {{ trx_json_extract('src', ['SHOWMOVEINADDRALRTSFLAG'], type='varchar', alias='showmoveinaddralrtsflag') }},
        {{ trx_json_extract('src', ['ACCTPREFSECTORDER'], type='int', alias='acctprefsectorder') }},
        {{ trx_json_extract('src', ['CREATEACCTDEFAULTFLAG'], type='varchar', alias='createacctdefaultflag') }},
        {{ trx_json_extract('src', ['DIRECTDEBITPROMPT'], type='varchar', alias='directdebitprompt') }},
        {{ trx_json_extract('src', ['MAXTENANTINTERVALDAYS'], type='int', alias='maxtenantintervaldays') }},
        {{ trx_json_extract('src', ['BILLINGSTATUS'], type='varchar', alias='billingstatus') }},
        {{ trx_json_extract('src', ['MOVEOUTINSTRSECTORDER'], type='int', alias='moveoutinstrsectorder') }},
        {{ trx_json_extract('src', ['FOWARDCNTCTSECTORDER'], type='int', alias='fowardcntctsectorder') }},
        {{ trx_json_extract('src', ['MAXDAYSPASTTOALLOWCANCEL'], type='int', alias='maxdayspasttoallowcancel') }},
        {{ trx_json_extract('src', ['STAYINAREADEFAULTFLAG'], type='varchar', alias='stayinareadefaultflag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['MOVEINDATEPROMPT'], type='varchar', alias='moveindateprompt') }},
        {{ trx_json_extract('src', ['COPYWAFROMPREVACCTFLAG'], type='varchar', alias='copywafromprevacctflag') }},
        {{ trx_json_extract('src', ['SERVICESTATUS'], type='varchar', alias='servicestatus') }},
        {{ trx_json_extract('src', ['COPYCNTCTSPROMPT'], type='varchar', alias='copycntctsprompt') }},
        {{ trx_json_extract('src', ['FORWARDINFOSECTORDER'], type='int', alias='forwardinfosectorder') }},
        {{ trx_json_extract('src', ['CONFIRMCNTCTSECTORDER'], type='int', alias='confirmcntctsectorder') }},
        {{ trx_json_extract('src', ['MODIFYCONFIRMATIONMSGKEY'], type='int', alias='modifyconfirmationmsgkey') }},
        {{ trx_json_extract('src', ['CANCELREQUESTRESOLUTION'], type='varchar', alias='cancelrequestresolution') }},
        {{ trx_json_extract('src', ['MOVEOUTSRVINSTFLAG'], type='varchar', alias='moveoutsrvinstflag') }},
        {{ trx_json_extract('src', ['MODIFYLOGTYPE'], type='varchar', alias='modifylogtype') }},
        {{ trx_json_extract('src', ['CREATEACCTPROMPT'], type='varchar', alias='createacctprompt') }},
        {{ trx_json_extract('src', ['SHOWCONFIRMCNTCTINFOFLAG'], type='varchar', alias='showconfirmcntctinfoflag') }},
        {{ trx_json_extract('src', ['DELINQUENCYSCHEMEKEY'], type='int', alias='delinquencyschemekey') }},
        {{ trx_json_extract('src', ['CANCELCONFIRMATIONMSGKEY'], type='int', alias='cancelconfirmationmsgkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['FORWARDINFOPROMPT'], type='varchar', alias='forwardinfoprompt') }},
        {{ trx_json_extract('src', ['CANCELSERVICESSECTORDER'], type='int', alias='cancelservicessectorder') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['MODIFYSERVICESSECTORDER'], type='int', alias='modifyservicessectorder') }},
        {{ trx_json_extract('src', ['MODIFYMAXINTFORNEWREQUEST'], type='int', alias='modifymaxintfornewrequest') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_moveoutsetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['moveoutsetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
