{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.APPROVALSCHEME on 2022-03-24T08:59:55.779',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['POSTFINALAPPROVALFORMULA'], type='int', alias='postfinalapprovalformula') }},
        {{ trx_json_extract('src', ['PRIORITYORDER'], type='int', alias='priorityorder') }},
        {{ trx_json_extract('src', ['APPROVALSTYLE'], type='int', alias='approvalstyle') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SCHEMENAME'], type='varchar', alias='schemename') }},
        {{ trx_json_extract('src', ['APPROVALGROUP'], type='int', alias='approvalgroup') }},
        {{ trx_json_extract('src', ['APPROVALSCHEMEKEY'], type='int', alias='approvalschemekey') }},
        {{ trx_json_extract('src', ['POSTREJECTIONFORMULA'], type='int', alias='postrejectionformula') }},
        {{ trx_json_extract('src', ['EARLYREJECTIONFORMULA'], type='int', alias='earlyrejectionformula') }},
        {{ trx_json_extract('src', ['EARLYFINALAPPROVALFORMULA'], type='int', alias='earlyfinalapprovalformula') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['INITIALLEVELFORMULA'], type='int', alias='initiallevelformula') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_approvalscheme') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['approvalschemekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
