{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.FIXCHGSU on 2022-03-03T11:32:51.010',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE10'], type='timestamp_ntz', alias='billedthroughdate10') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE11'], type='timestamp_ntz', alias='billedthroughdate11') }},
        {{ trx_json_extract('src', ['FIXCHGSUKEY'], type='int', alias='fixchgsukey') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE2'], type='timestamp_ntz', alias='billedthroughdate2') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE6'], type='timestamp_ntz', alias='billedthroughdate6') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE1'], type='timestamp_ntz', alias='billedthroughdate1') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE8'], type='timestamp_ntz', alias='billedthroughdate8') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE4'], type='timestamp_ntz', alias='billedthroughdate4') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE9'], type='timestamp_ntz', alias='billedthroughdate9') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE12'], type='timestamp_ntz', alias='billedthroughdate12') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE5'], type='timestamp_ntz', alias='billedthroughdate5') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE3'], type='timestamp_ntz', alias='billedthroughdate3') }},
        {{ trx_json_extract('src', ['BILLEDTHROUGHDATE7'], type='timestamp_ntz', alias='billedthroughdate7') }},
        {{ trx_json_extract('src', ['FREQUENCY'], type='varchar', alias='frequency') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_fixchgsu') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['fixchgsukey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
