{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.SERVICEOPTIONS on 2021-07-09T15:15:00.846',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FIXEDCHGINADVANCEFLAG'], type='varchar', alias='fixedchginadvanceflag') }},
        {{ trx_json_extract('src', ['SERVICEDEFINITIONKEY'], type='int', alias='servicedefinitionkey') }},
        {{ trx_json_extract('src', ['SERVICECLASS1'], type='varchar', alias='serviceclass1') }},
        {{ trx_json_extract('src', ['SERVICEFIELD2KEY'], type='int', alias='servicefield2key') }},
        {{ trx_json_extract('src', ['SERVICETYPE'], type='varchar', alias='servicetype') }},
        {{ trx_json_extract('src', ['ASSETTYPE'], type='int', alias='assettype') }},
        {{ trx_json_extract('src', ['MOVEINCOLOR'], type='int', alias='moveincolor') }},
        {{ trx_json_extract('src', ['IMPERVIOUSAREAONLYFLAG'], type='varchar', alias='imperviousareaonlyflag') }},
        {{ trx_json_extract('src', ['DONOTPRORATEMOVEINFLAG'], type='varchar', alias='donotproratemoveinflag') }},
        {{ trx_json_extract('src', ['MOVEOUTSWOKEY'], type='int', alias='moveoutswokey') }},
        {{ trx_json_extract('src', ['TRADEWASTEFLAG'], type='varchar', alias='tradewasteflag') }},
        {{ trx_json_extract('src', ['MOVEOUTSRWOCONDITIONFORMULA'], type='int', alias='moveoutsrwoconditionformula') }},
        {{ trx_json_extract('src', ['BUILDERFLAG'], type='varchar', alias='builderflag') }},
        {{ trx_json_extract('src', ['MOVEINACTKEY'], type='int', alias='moveinactkey') }},
        {{ trx_json_extract('src', ['SERVICEOPTIONSKEY'], type='int', alias='serviceoptionskey') }},
        {{ trx_json_extract('src', ['WINTERAVGSETUPKEY'], type='int', alias='winteravgsetupkey') }},
        {{ trx_json_extract('src', ['AVAILABILITY'], type='varchar', alias='availability') }},
        {{ trx_json_extract('src', ['TRADEWASTEMAX'], type='int', alias='tradewastemax') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CLASS'], type='varchar', alias='class') }},
        {{ trx_json_extract('src', ['SERVICEFIELD3KEY'], type='int', alias='servicefield3key') }},
        {{ trx_json_extract('src', ['PRORATESERVICESTOPFLAG'], type='varchar', alias='prorateservicestopflag') }},
        {{ trx_json_extract('src', ['PRORATESERVICESTARTFLAG'], type='varchar', alias='prorateservicestartflag') }},
        {{ trx_json_extract('src', ['MOVEOUTLEARNMOREKBKEY'], type='int', alias='moveoutlearnmorekbkey') }},
        {{ trx_json_extract('src', ['TENANTFLAG'], type='varchar', alias='tenantflag') }},
        {{ trx_json_extract('src', ['METERTYPEFORMULA'], type='int', alias='metertypeformula') }},
        {{ trx_json_extract('src', ['WINTERAVGFLAG'], type='varchar', alias='winteravgflag') }},
        {{ trx_json_extract('src', ['MOVEINSRWOCONDITIONFORMULA'], type='int', alias='moveinsrwoconditionformula') }},
        {{ trx_json_extract('src', ['SERVICEFIELD1KEY'], type='int', alias='servicefield1key') }},
        {{ trx_json_extract('src', ['LEARNMOREKBKEY'], type='int', alias='learnmorekbkey') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['CONSGRAPHFLAG'], type='varchar', alias='consgraphflag') }},
        {{ trx_json_extract('src', ['SERVICECLASS2'], type='varchar', alias='serviceclass2') }},
        {{ trx_json_extract('src', ['CODE'], type='varchar', alias='code') }},
        {{ trx_json_extract('src', ['TRADEWASTERATE'], type='int', alias='tradewasterate') }},
        {{ trx_json_extract('src', ['OWNERFLAG'], type='varchar', alias='ownerflag') }},
        {{ trx_json_extract('src', ['MOVEINREQSKEY'], type='int', alias='moveinreqskey') }},
        {{ trx_json_extract('src', ['CONSUMPTIONPERCENTAGE'], type='float', alias='consumptionpercentage') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['MOVEOUTNOTES'], type='varchar', alias='moveoutnotes') }},
        {{ trx_json_extract('src', ['SERVICEDISTRICT'], type='varchar', alias='servicedistrict') }},
        {{ trx_json_extract('src', ['OUTPUTHISTORICALUSAGEFLAG'], type='varchar', alias='outputhistoricalusageflag') }},
        {{ trx_json_extract('src', ['MOVEINSWOKEY'], type='int', alias='moveinswokey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MOVEOUTACTKEY'], type='int', alias='moveoutactkey') }},
        {{ trx_json_extract('src', ['FREQUENCY'], type='varchar', alias='frequency') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['MOVEINNOTES'], type='varchar', alias='moveinnotes') }},
        {{ trx_json_extract('src', ['MOVEOUTREQSKEY'], type='int', alias='moveoutreqskey') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_serviceoptions') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['serviceoptionskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
