{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.DIRECTDEBITRUN on 2022-03-03T11:33:35.356',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CREATEACHFILE'], type='varchar', alias='createachfile') }},
        {{ trx_json_extract('src', ['SCHEDULEKEY'], type='int', alias='schedulekey') }},
        {{ trx_json_extract('src', ['NUMBEROFDEBITSCHEDULE'], type='int', alias='numberofdebitschedule') }},
        {{ trx_json_extract('src', ['BILLTYPEKEY'], type='int', alias='billtypekey') }},
        {{ trx_json_extract('src', ['PROCESSINGFLAG'], type='varchar', alias='processingflag') }},
        {{ trx_json_extract('src', ['COMMENTSKEY'], type='int', alias='commentskey') }},
        {{ trx_json_extract('src', ['ACHFORMATFILE'], type='varchar', alias='achformatfile') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['ACHOUTPUTDIRECTORY'], type='varchar', alias='achoutputdirectory') }},
        {{ trx_json_extract('src', ['EXTRACTTHROUGHDATE'], type='timestamp_ntz', alias='extractthroughdate') }},
        {{ trx_json_extract('src', ['ACHENTRYAMOUNT'], type='float', alias='achentryamount') }},
        {{ trx_json_extract('src', ['BILLRUNKEY'], type='int', alias='billrunkey') }},
        {{ trx_json_extract('src', ['ACHFILENAME'], type='varchar', alias='achfilename') }},
        {{ trx_json_extract('src', ['DIRECTDEBITRUNKEY'], type='int', alias='directdebitrunkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ACCTGRP'], type='varchar', alias='acctgrp') }},
        {{ trx_json_extract('src', ['LASTINVOCATIONSTATUS'], type='int', alias='lastinvocationstatus') }},
        {{ trx_json_extract('src', ['NUMBEROFBILLS'], type='int', alias='numberofbills') }},
        {{ trx_json_extract('src', ['PAYMENTBATCHCOUNT'], type='int', alias='paymentbatchcount') }},
        {{ trx_json_extract('src', ['PRENOTEBANKACCOUNTCOUNT'], type='int', alias='prenotebankaccountcount') }},
        {{ trx_json_extract('src', ['BILLINGCYCLE'], type='varchar', alias='billingcycle') }},
        {{ trx_json_extract('src', ['INCLUDEDEBITSCHEDULE'], type='varchar', alias='includedebitschedule') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['RERUN'], type='varchar', alias='rerun') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['NUMBEROFACCOUNTS'], type='int', alias='numberofaccounts') }},
        {{ trx_json_extract('src', ['NUMBEROFACHENTRIES'], type='int', alias='numberofachentries') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_directdebitrun') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['directdebitrunkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
