{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.BILLTYPEWRITEOFF on 2024-01-26T12:53:49.147',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COLLECTIONSALERT'], type='int', alias='collectionsalert') }},
        {{ trx_json_extract('src', ['LIENRESOLUTION'], type='varchar', alias='lienresolution') }},
        {{ trx_json_extract('src', ['BILLTYPEKEY'], type='int', alias='billtypekey') }},
        {{ trx_json_extract('src', ['COLLECTIONSSTATUS'], type='varchar', alias='collectionsstatus') }},
        {{ trx_json_extract('src', ['COLLECTIONSRESOLUTION'], type='varchar', alias='collectionsresolution') }},
        {{ trx_json_extract('src', ['DEFAULTADJUSTMENTCODE'], type='int', alias='defaultadjustmentcode') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['BILLTYPEWRITEOFFKEY'], type='int', alias='billtypewriteoffkey') }},
        {{ trx_json_extract('src', ['LIENSTATUS'], type='varchar', alias='lienstatus') }},
        {{ trx_json_extract('src', ['ADJUSTMENTREASON'], type='varchar', alias='adjustmentreason') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['LIENALERT'], type='int', alias='lienalert') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_billtypewriteoff') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['billtypewriteoffkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
