{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.DELINQUENCYSETUP on 2022-03-24T09:00:01.804',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COLLECTIONSRECORDFLAG'], type='varchar', alias='collectionsrecordflag') }},
        {{ trx_json_extract('src', ['BILLTYPEKEY'], type='int', alias='billtypekey') }},
        {{ trx_json_extract('src', ['DISPLAYORDER'], type='int', alias='displayorder') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ENTRYGROUPFORMULA'], type='int', alias='entrygroupformula') }},
        {{ trx_json_extract('src', ['DELINQUENCYSETUPKEY'], type='int', alias='delinquencysetupkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['DELINQUENCYSETUPNAME'], type='varchar', alias='delinquencysetupname') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_delinquencysetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['delinquencysetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
