{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.ACCOUNTNUMBER on 2022-03-24T08:59:43.035',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['SEGMENT1'], type='varchar', alias='segment1') }},
        {{ trx_json_extract('src', ['SEGMENT5'], type='varchar', alias='segment5') }},
        {{ trx_json_extract('src', ['ACCTNOGENSETUP'], type='int', alias='acctnogensetup') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CUSTOMERIDENTITY'], type='int', alias='customeridentity') }},
        {{ trx_json_extract('src', ['PRCLKEY'], type='int', alias='prclkey') }},
        {{ trx_json_extract('src', ['SEGMENT4'], type='varchar', alias='segment4') }},
        {{ trx_json_extract('src', ['PROPERTY'], type='int', alias='property') }},
        {{ trx_json_extract('src', ['ACCOUNTNUMBERKEY'], type='int', alias='accountnumberkey') }},
        {{ trx_json_extract('src', ['SEGMENT2'], type='varchar', alias='segment2') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['SEGMENT3'], type='varchar', alias='segment3') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_accountnumber') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['accountnumberkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
