{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table BILLING.LINEITEMRATE on 2022-03-03T11:32:47.373',
    tags=['auto-generated', 'ips', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FIXEDCHGPERIODDAYS'], type='int', alias='fixedchgperioddays') }},
        {{ trx_json_extract('src', ['ADDRESSSERVICEKEY'], type='int', alias='addressservicekey') }},
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['FIXEDCHGRATEPERPERIOD'], type='float', alias='fixedchgrateperperiod') }},
        {{ trx_json_extract('src', ['ONEOFFCHARGEKEY'], type='int', alias='oneoffchargekey') }},
        {{ trx_json_extract('src', ['BILLRUNKEY'], type='int', alias='billrunkey') }},
        {{ trx_json_extract('src', ['FIXEDCHGPERIODSINYEAR'], type='int', alias='fixedchgperiodsinyear') }},
        {{ trx_json_extract('src', ['FIXEDCHGTODATE'], type='timestamp_ntz', alias='fixedchgtodate') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LINEITEMKEY'], type='int', alias='lineitemkey') }},
        {{ trx_json_extract('src', ['ACCOUNTSERVICEKEY'], type='int', alias='accountservicekey') }},
        {{ trx_json_extract('src', ['FIXEDCHGNUMBERPERIODS'], type='int', alias='fixedchgnumberperiods') }},
        {{ trx_json_extract('src', ['FIXEDCHGCHARGEDAYS'], type='int', alias='fixedchgchargedays') }},
        {{ trx_json_extract('src', ['CALCULATIONDETAILKEY'], type='int', alias='calculationdetailkey') }},
        {{ trx_json_extract('src', ['DEPOSITCHARGEKEY'], type='int', alias='depositchargekey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['FIXEDCHGFROMDATE'], type='timestamp_ntz', alias='fixedchgfromdate') }},
        {{ trx_json_extract('src', ['LINEITEMRATEKEY'], type='int', alias='lineitemratekey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_billing_lineitemrate') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['lineitemratekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
