{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CASHIERING.CASHREGISTER on 2021-07-09T15:15:10.564',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ISSHOWRECEIPTAPPLET'], type='varchar', alias='isshowreceiptapplet') }},
        {{ trx_json_extract('src', ['ESCROWSETUP'], type='int', alias='escrowsetup') }},
        {{ trx_json_extract('src', ['ISPRINTSIGNATURESLIP'], type='varchar', alias='isprintsignatureslip') }},
        {{ trx_json_extract('src', ['MISCSETUP'], type='int', alias='miscsetup') }},
        {{ trx_json_extract('src', ['RECEIPTCOPIES'], type='int', alias='receiptcopies') }},
        {{ trx_json_extract('src', ['ISENDORSECHECK'], type='varchar', alias='isendorsecheck') }},
        {{ trx_json_extract('src', ['REGISTERGROUPSETUPKEY'], type='int', alias='registergroupsetupkey') }},
        {{ trx_json_extract('src', ['CHECKSETUP'], type='int', alias='checksetup') }},
        {{ trx_json_extract('src', ['REGKEY'], type='int', alias='regkey') }},
        {{ trx_json_extract('src', ['CASHSETUP'], type='int', alias='cashsetup') }},
        {{ trx_json_extract('src', ['REGTYPE'], type='varchar', alias='regtype') }},
        {{ trx_json_extract('src', ['SCANNERFORMULAKEY'], type='int', alias='scannerformulakey') }},
        {{ trx_json_extract('src', ['CREDITSETUP'], type='int', alias='creditsetup') }},
        {{ trx_json_extract('src', ['SUPERVISOR'], type='varchar', alias='supervisor') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ISUSINGREGISTERGROUP'], type='varchar', alias='isusingregistergroup') }},
        {{ trx_json_extract('src', ['LOC'], type='varchar', alias='loc') }},
        {{ trx_json_extract('src', ['CPUSERIAL'], type='varchar', alias='cpuserial') }},
        {{ trx_json_extract('src', ['MACID'], type='varchar', alias='macid') }},
        {{ trx_json_extract('src', ['DEBITSETUP'], type='int', alias='debitsetup') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['MACHINENAME'], type='varchar', alias='machinename') }},
        {{ trx_json_extract('src', ['PAYMENTTERMINALFORMULAKEY'], type='int', alias='paymentterminalformulakey') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['REGID'], type='varchar', alias='regid') }},
        {{ trx_json_extract('src', ['VALIDATEMACHINENAME'], type='varchar', alias='validatemachinename') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cashiering_cashregister') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['regkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
