{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CASHIERING.MERCHANTACCOUNT on 2022-06-01T05:10:27.487',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ENCRYPTCUSTPROP'], type='varchar', alias='encryptcustprop') }},
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['PREPCONFIGKEY'], type='int', alias='prepconfigkey') }},
        {{ trx_json_extract('src', ['ACCOUNTUSERNAME'], type='varchar', alias='accountusername') }},
        {{ trx_json_extract('src', ['EXPIREDATE'], type='timestamp_ntz', alias='expiredate') }},
        {{ trx_json_extract('src', ['PREPHANDLERKEY'], type='int', alias='prephandlerkey') }},
        {{ trx_json_extract('src', ['AUTHORIZEPAYMENTFORMULAKEY'], type='int', alias='authorizepaymentformulakey') }},
        {{ trx_json_extract('src', ['WEBFORMCONFIGKEY'], type='int', alias='webformconfigkey') }},
        {{ trx_json_extract('src', ['PAYMENTGATEWAYPROVIDER'], type='varchar', alias='paymentgatewayprovider') }},
        {{ trx_json_extract('src', ['ACCOUNTID'], type='varchar', alias='accountid') }},
        {{ trx_json_extract('src', ['ACCOUNTPASSWORD'], type='varchar', alias='accountpassword') }},
        {{ trx_json_extract('src', ['WEBFORMHANDLERKEY'], type='int', alias='webformhandlerkey') }},
        {{ trx_json_extract('src', ['REDIRECTURLCONFIGKEY'], type='int', alias='redirecturlconfigkey') }},
        {{ trx_json_extract('src', ['INQCONFIGKEY'], type='int', alias='inqconfigkey') }},
        {{ trx_json_extract('src', ['HOSTPORT'], type='int', alias='hostport') }},
        {{ trx_json_extract('src', ['VOIDCONFIGKEY'], type='int', alias='voidconfigkey') }},
        {{ trx_json_extract('src', ['INQREVERSEDCONFIGKEY'], type='int', alias='inqreversedconfigkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['REVERSEPAYMENTFORMULAKEY'], type='int', alias='reversepaymentformulakey') }},
        {{ trx_json_extract('src', ['MERCHANTACCOUNTKEY'], type='int', alias='merchantaccountkey') }},
        {{ trx_json_extract('src', ['PREAUTHHANDLERKEY'], type='int', alias='preauthhandlerkey') }},
        {{ trx_json_extract('src', ['EFFECTIVEDATE'], type='timestamp_ntz', alias='effectivedate') }},
        {{ trx_json_extract('src', ['PREAUTHORIZECONFIGKEY'], type='int', alias='preauthorizeconfigkey') }},
        {{ trx_json_extract('src', ['REDIRECTURLHANDLERKEY'], type='int', alias='redirecturlhandlerkey') }},
        {{ trx_json_extract('src', ['REVERSECONFIGKEY'], type='int', alias='reverseconfigkey') }},
        {{ trx_json_extract('src', ['CARDNUMBERFORMATOVR'], type='varchar', alias='cardnumberformatovr') }},
        {{ trx_json_extract('src', ['TIMEOUT'], type='int', alias='timeout') }},
        {{ trx_json_extract('src', ['INQHANDLERKEY'], type='int', alias='inqhandlerkey') }},
        {{ trx_json_extract('src', ['AUTHHANDLERKEY'], type='int', alias='authhandlerkey') }},
        {{ trx_json_extract('src', ['CARDNUMBERFORMAT'], type='int', alias='cardnumberformat') }},
        {{ trx_json_extract('src', ['INQREVERSEDHANDLERKEY'], type='int', alias='inqreversedhandlerkey') }},
        {{ trx_json_extract('src', ['VOIDAPPROVEDTRANSACTIONONLY'], type='varchar', alias='voidapprovedtransactiononly') }},
        {{ trx_json_extract('src', ['AUTHORIZECONFIGKEY'], type='int', alias='authorizeconfigkey') }},
        {{ trx_json_extract('src', ['ISECOMMERCE'], type='varchar', alias='isecommerce') }},
        {{ trx_json_extract('src', ['VOIDHANDLERKEY'], type='int', alias='voidhandlerkey') }},
        {{ trx_json_extract('src', ['ISCREDIT'], type='varchar', alias='iscredit') }},
        {{ trx_json_extract('src', ['HOSTADDR'], type='varchar', alias='hostaddr') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['PAYMENTPROCESSING'], type='int', alias='paymentprocessing') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ISCHECKING'], type='varchar', alias='ischecking') }},
        {{ trx_json_extract('src', ['ACCOUNTNAME'], type='varchar', alias='accountname') }},
        {{ trx_json_extract('src', ['ISDEBIT'], type='varchar', alias='isdebit') }},
        {{ trx_json_extract('src', ['REVERSEHANDLERKEY'], type='int', alias='reversehandlerkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cashiering_merchantaccount') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['merchantaccountkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
