{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CASHIERING.REGISTERTRANSACTION on 2021-07-09T15:15:15.014',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TRANAMT'], type='float', alias='tranamt') }},
        {{ trx_json_extract('src', ['VOIDBY'], type='varchar', alias='voidby') }},
        {{ trx_json_extract('src', ['ASSOCIATEDEMPLOYEE'], type='varchar', alias='associatedemployee') }},
        {{ trx_json_extract('src', ['VOIDDTTM'], type='timestamp_ntz', alias='voiddttm') }},
        {{ trx_json_extract('src', ['DRWRKEY'], type='int', alias='drwrkey') }},
        {{ trx_json_extract('src', ['REGKEY'], type='int', alias='regkey') }},
        {{ trx_json_extract('src', ['STATUS'], type='varchar', alias='status') }},
        {{ trx_json_extract('src', ['CONTACT'], type='int', alias='contact') }},
        {{ trx_json_extract('src', ['TRANTYPE'], type='varchar', alias='trantype') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['TRANPAYER'], type='varchar', alias='tranpayer') }},
        {{ trx_json_extract('src', ['RECEIPTNUMBER'], type='varchar', alias='receiptnumber') }},
        {{ trx_json_extract('src', ['TRANDTTM'], type='timestamp_ntz', alias='trandttm') }},
        {{ trx_json_extract('src', ['REFTRANNO'], type='int', alias='reftranno') }},
        {{ trx_json_extract('src', ['TRANBY'], type='varchar', alias='tranby') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['VOIDREAS'], type='varchar', alias='voidreas') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['REGTRANNO'], type='int', alias='regtranno') }},
        {{ trx_json_extract('src', ['CLEANUPSESSIONID'], type='varchar', alias='cleanupsessionid') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cashiering_registertransaction') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['regtranno']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
