{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CASHIERING.CASHDRAWER on 2021-07-09T15:15:10.075',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DEBITAMT'], type='float', alias='debitamt') }},
        {{ trx_json_extract('src', ['MISCCT'], type='int', alias='miscct') }},
        {{ trx_json_extract('src', ['CASHLIMITAMT'], type='float', alias='cashlimitamt') }},
        {{ trx_json_extract('src', ['STATDTTM'], type='timestamp_ntz', alias='statdttm') }},
        {{ trx_json_extract('src', ['ADJAMT'], type='float', alias='adjamt') }},
        {{ trx_json_extract('src', ['STOPDTTM'], type='timestamp_ntz', alias='stopdttm') }},
        {{ trx_json_extract('src', ['CASHIER'], type='varchar', alias='cashier') }},
        {{ trx_json_extract('src', ['DRWRKEY'], type='int', alias='drwrkey') }},
        {{ trx_json_extract('src', ['DEFAULTREGISTERGROUPKEY'], type='int', alias='defaultregistergroupkey') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['REGKEY'], type='int', alias='regkey') }},
        {{ trx_json_extract('src', ['ESCROWCT'], type='int', alias='escrowct') }},
        {{ trx_json_extract('src', ['OBGTNO'], type='int', alias='obgtno') }},
        {{ trx_json_extract('src', ['CTOUTDTTM'], type='timestamp_ntz', alias='ctoutdttm') }},
        {{ trx_json_extract('src', ['DRWRSTAT'], type='varchar', alias='drwrstat') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CASHINAMT'], type='float', alias='cashinamt') }},
        {{ trx_json_extract('src', ['CREDITCARDCOUNT'], type='int', alias='creditcardcount') }},
        {{ trx_json_extract('src', ['SBGTNO'], type='int', alias='sbgtno') }},
        {{ trx_json_extract('src', ['CASHOUTAMT'], type='float', alias='cashoutamt') }},
        {{ trx_json_extract('src', ['CTINDTTM'], type='timestamp_ntz', alias='ctindttm') }},
        {{ trx_json_extract('src', ['CTOUTBY'], type='varchar', alias='ctoutby') }},
        {{ trx_json_extract('src', ['DRWRNO'], type='varchar', alias='drwrno') }},
        {{ trx_json_extract('src', ['ESCROWAMT'], type='float', alias='escrowamt') }},
        {{ trx_json_extract('src', ['DEPAMT'], type='float', alias='depamt') }},
        {{ trx_json_extract('src', ['CREDITCARDAMOUNT'], type='float', alias='creditcardamount') }},
        {{ trx_json_extract('src', ['CTINBY'], type='varchar', alias='ctinby') }},
        {{ trx_json_extract('src', ['DEBITCT'], type='int', alias='debitct') }},
        {{ trx_json_extract('src', ['BATCHGROUP'], type='varchar', alias='batchgroup') }},
        {{ trx_json_extract('src', ['DRWRTYPE'], type='varchar', alias='drwrtype') }},
        {{ trx_json_extract('src', ['CHECKCT'], type='int', alias='checkct') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['CHECKAMT'], type='float', alias='checkamt') }},
        {{ trx_json_extract('src', ['MISCAMT'], type='float', alias='miscamt') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['CBATCHKEY'], type='int', alias='cbatchkey') }},
        {{ trx_json_extract('src', ['TRAYNO'], type='varchar', alias='trayno') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cashiering_cashdrawer') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['drwrkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
