{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CASHIERING.DRAWERGENERATION on 2022-06-01T05:10:27.939',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CASHLIMITAMT'], type='float', alias='cashlimitamt') }},
        {{ trx_json_extract('src', ['SRC'], type='varchar', alias='src') }},
        {{ trx_json_extract('src', ['DRWRGENKEY'], type='int', alias='drwrgenkey') }},
        {{ trx_json_extract('src', ['CASHIER'], type='varchar', alias='cashier') }},
        {{ trx_json_extract('src', ['DEFAULTREGISTERGROUPKEY'], type='int', alias='defaultregistergroupkey') }},
        {{ trx_json_extract('src', ['AUTOPOST'], type='varchar', alias='autopost') }},
        {{ trx_json_extract('src', ['REGKEY'], type='int', alias='regkey') }},
        {{ trx_json_extract('src', ['OBGTNO'], type='int', alias='obgtno') }},
        {{ trx_json_extract('src', ['BATCHSTAT'], type='varchar', alias='batchstat') }},
        {{ trx_json_extract('src', ['DRWRSTAT'], type='varchar', alias='drwrstat') }},
        {{ trx_json_extract('src', ['BATCHDESC'], type='varchar', alias='batchdesc') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CASHINAMT'], type='float', alias='cashinamt') }},
        {{ trx_json_extract('src', ['STOPTM'], type='timestamp_ntz', alias='stoptm') }},
        {{ trx_json_extract('src', ['SBGTNO'], type='int', alias='sbgtno') }},
        {{ trx_json_extract('src', ['BATCHGROUP'], type='varchar', alias='batchgroup') }},
        {{ trx_json_extract('src', ['STARTTM'], type='timestamp_ntz', alias='starttm') }},
        {{ trx_json_extract('src', ['DRWRTYPE'], type='varchar', alias='drwrtype') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cashiering_drawergeneration') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['drwrgenkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
