{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUILDING.BLDGEMP on 2022-03-03T11:34:34.181',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APBLDGKEY'], type='int', alias='apbldgkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['EMPID'], type='varchar', alias='empid') }},
        {{ trx_json_extract('src', ['FROMDTTM'], type='timestamp_ntz', alias='fromdttm') }},
        {{ trx_json_extract('src', ['CAPACITY'], type='varchar', alias='capacity') }},
        {{ trx_json_extract('src', ['TOTALHRS'], type='float', alias='totalhrs') }},
        {{ trx_json_extract('src', ['TODTTM'], type='timestamp_ntz', alias='todttm') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['APBLDGEMPKEY'], type='int', alias='apbldgempkey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_building_bldgemp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apbldgempkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
