{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_PLANNING.PLANPLCONDINHERITRULE on 2022-03-03T11:36:01.548',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APPLANPLCONDINHERITRULEKEY'], type='int', alias='applanplcondinheritrulekey') }},
        {{ trx_json_extract('src', ['INHERITTITLE'], type='varchar', alias='inherittitle') }},
        {{ trx_json_extract('src', ['CDSYSTEMAPPLTYPE'], type='int', alias='cdsystemappltype') }},
        {{ trx_json_extract('src', ['INHERITRULETYPE'], type='int', alias='inheritruletype') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['INHERITFRMLA'], type='int', alias='inheritfrmla') }},
        {{ trx_json_extract('src', ['PROJINHERITFRMLAKEY'], type='int', alias='projinheritfrmlakey') }},
        {{ trx_json_extract('src', ['PLANINHERITFRMLAKEY'], type='int', alias='planinheritfrmlakey') }},
        {{ trx_json_extract('src', ['BLDGINHERITFRMLAKEY'], type='int', alias='bldginheritfrmlakey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_planning_planplcondinheritrule') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['applanplcondinheritrulekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
