{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUSINESSLICENSE.LICENDR on 2021-07-09T15:15:38.064',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['ISSBY'], type='varchar', alias='issby') }},
        {{ trx_json_extract('src', ['ENDRPROCSTATE'], type='int', alias='endrprocstate') }},
        {{ trx_json_extract('src', ['INACTVBY'], type='varchar', alias='inactvby') }},
        {{ trx_json_extract('src', ['XFERBY'], type='varchar', alias='xferby') }},
        {{ trx_json_extract('src', ['ASSET'], type='int', alias='asset') }},
        {{ trx_json_extract('src', ['LINEARFROMM'], type='float', alias='linearfromm') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LOC'], type='varchar', alias='loc') }},
        {{ trx_json_extract('src', ['INACTVDTTM'], type='timestamp_ntz', alias='inactvdttm') }},
        {{ trx_json_extract('src', ['ISSDTTM'], type='timestamp_ntz', alias='issdttm') }},
        {{ trx_json_extract('src', ['BLDGROOM'], type='int', alias='bldgroom') }},
        {{ trx_json_extract('src', ['INITBY'], type='varchar', alias='initby') }},
        {{ trx_json_extract('src', ['APLICENDRTYPEKEY'], type='int', alias='aplicendrtypekey') }},
        {{ trx_json_extract('src', ['PROPERTY'], type='int', alias='property') }},
        {{ trx_json_extract('src', ['XFERLICKEY'], type='int', alias='xferlickey') }},
        {{ trx_json_extract('src', ['APLICENDRKEY'], type='int', alias='aplicendrkey') }},
        {{ trx_json_extract('src', ['LINEARTOFT'], type='float', alias='lineartoft') }},
        {{ trx_json_extract('src', ['CMPTRGEN'], type='varchar', alias='cmptrgen') }},
        {{ trx_json_extract('src', ['LINEARFROMFT'], type='float', alias='linearfromft') }},
        {{ trx_json_extract('src', ['INITDTTM'], type='timestamp_ntz', alias='initdttm') }},
        {{ trx_json_extract('src', ['ENDRSTATUS'], type='varchar', alias='endrstatus') }},
        {{ trx_json_extract('src', ['XFERDTTM'], type='timestamp_ntz', alias='xferdttm') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['PARCEL'], type='int', alias='parcel') }},
        {{ trx_json_extract('src', ['BLDGFLOOR'], type='int', alias='bldgfloor') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['APLICKEY'], type='int', alias='aplickey') }},
        {{ trx_json_extract('src', ['LINEARTOM'], type='float', alias='lineartom') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_businesslicense_licendr') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['aplicendrkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
