{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUSINESSLICENSE.LICSTATUSLOG on 2021-07-09T15:15:45.477',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ENDRSTAT'], type='varchar', alias='endrstat') }},
        {{ trx_json_extract('src', ['APLICPROCESSSTATEKEY'], type='int', alias='aplicprocessstatekey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APLICSTATLOGKEY'], type='int', alias='aplicstatlogkey') }},
        {{ trx_json_extract('src', ['STATUSBY'], type='varchar', alias='statusby') }},
        {{ trx_json_extract('src', ['STATUSDTTM'], type='timestamp_ntz', alias='statusdttm') }},
        {{ trx_json_extract('src', ['APLICENDRKEY'], type='int', alias='aplicendrkey') }},
        {{ trx_json_extract('src', ['CMPTRGEN'], type='varchar', alias='cmptrgen') }},
        {{ trx_json_extract('src', ['STAT'], type='varchar', alias='stat') }},
        {{ trx_json_extract('src', ['LICSTATUSCODE'], type='varchar', alias='licstatuscode') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['APLICKEY'], type='int', alias='aplickey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_businesslicense_licstatuslog') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['aplicstatlogkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
