{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_TRADELICENSE.TRADEPERIODICINSPSCHED on 2021-07-09T15:16:14.398',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APTRADEPERDINSPSUKEY'], type='int', alias='aptradeperdinspsukey') }},
        {{ trx_json_extract('src', ['AUTOASSIGNED'], type='varchar', alias='autoassigned') }},
        {{ trx_json_extract('src', ['TIMESCHEDKEY'], type='int', alias='timeschedkey') }},
        {{ trx_json_extract('src', ['APTRADEPERDINSPKEY'], type='int', alias='aptradeperdinspkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['HOLD'], type='varchar', alias='hold') }},
        {{ trx_json_extract('src', ['LASTSCHEDULED'], type='timestamp_ntz', alias='lastscheduled') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['APTRADEKEY'], type='int', alias='aptradekey') }},
        {{ trx_json_extract('src', ['APTRADEINSPKEY'], type='int', alias='aptradeinspkey') }},
        {{ trx_json_extract('src', ['NEXTSCHEDULED'], type='timestamp_ntz', alias='nextscheduled') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['APTRADEINSPTYPEKEY'], type='int', alias='aptradeinsptypekey') }},
        {{ trx_json_extract('src', ['ASSIGNTO'], type='varchar', alias='assignto') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_tradelicense_tradeperiodicinspsched') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['aptradeperdinspkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
