{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_USE.USEAPPL on 2021-07-09T15:16:26.023',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APPRJKEY'], type='int', alias='apprjkey') }},
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['ISSBY'], type='varchar', alias='issby') }},
        {{ trx_json_extract('src', ['XCOORDINATE'], type='float', alias='xcoordinate') }},
        {{ trx_json_extract('src', ['COODTTM'], type='timestamp_ntz', alias='coodttm') }},
        {{ trx_json_extract('src', ['NOPAGES'], type='int', alias='nopages') }},
        {{ trx_json_extract('src', ['APMODLKEY'], type='int', alias='apmodlkey') }},
        {{ trx_json_extract('src', ['PRI'], type='varchar', alias='pri') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['DECLVLTN'], type='float', alias='declvltn') }},
        {{ trx_json_extract('src', ['GROUPKEY'], type='int', alias='groupkey') }},
        {{ trx_json_extract('src', ['APNAME'], type='varchar', alias='apname') }},
        {{ trx_json_extract('src', ['TMPCOODTTM'], type='timestamp_ntz', alias='tmpcoodttm') }},
        {{ trx_json_extract('src', ['PROPOCCUPKEY'], type='int', alias='propoccupkey') }},
        {{ trx_json_extract('src', ['PLANREV'], type='varchar', alias='planrev') }},
        {{ trx_json_extract('src', ['PROPERTYCRANEDERRICK'], type='int', alias='propertycranederrick') }},
        {{ trx_json_extract('src', ['APUSEKEY'], type='int', alias='apusekey') }},
        {{ trx_json_extract('src', ['COOBY'], type='varchar', alias='cooby') }},
        {{ trx_json_extract('src', ['LINEARFROMM'], type='float', alias='linearfromm') }},
        {{ trx_json_extract('src', ['WORKTYPE'], type='varchar', alias='worktype') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PRCLKEY'], type='int', alias='prclkey') }},
        {{ trx_json_extract('src', ['APUSEPROCESSSTATEKEY'], type='int', alias='apuseprocessstatekey') }},
        {{ trx_json_extract('src', ['LOC'], type='varchar', alias='loc') }},
        {{ trx_json_extract('src', ['PROPERTYFACADE'], type='int', alias='propertyfacade') }},
        {{ trx_json_extract('src', ['USEAPPLSTATUS'], type='varchar', alias='useapplstatus') }},
        {{ trx_json_extract('src', ['YCOORDINATE'], type='float', alias='ycoordinate') }},
        {{ trx_json_extract('src', ['LSTACTDTTM'], type='timestamp_ntz', alias='lstactdttm') }},
        {{ trx_json_extract('src', ['ISSDTTM'], type='timestamp_ntz', alias='issdttm') }},
        {{ trx_json_extract('src', ['APUSEDEFNKEY'], type='int', alias='apusedefnkey') }},
        {{ trx_json_extract('src', ['BLDGROOM'], type='int', alias='bldgroom') }},
        {{ trx_json_extract('src', ['ACTLVLTN'], type='float', alias='actlvltn') }},
        {{ trx_json_extract('src', ['PROPERTYCONVEYANCE'], type='int', alias='propertyconveyance') }},
        {{ trx_json_extract('src', ['FINDTTM'], type='timestamp_ntz', alias='findttm') }},
        {{ trx_json_extract('src', ['PROPERTYMATERIAL'], type='int', alias='propertymaterial') }},
        {{ trx_json_extract('src', ['TMPCOOBY'], type='varchar', alias='tmpcooby') }},
        {{ trx_json_extract('src', ['APKEY'], type='int', alias='apkey') }},
        {{ trx_json_extract('src', ['USEAREA'], type='float', alias='usearea') }},
        {{ trx_json_extract('src', ['APNO'], type='varchar', alias='apno') }},
        {{ trx_json_extract('src', ['PROPERTYEQUIPMENT'], type='int', alias='propertyequipment') }},
        {{ trx_json_extract('src', ['LINEARTOFT'], type='float', alias='lineartoft') }},
        {{ trx_json_extract('src', ['NOPLANS'], type='int', alias='noplans') }},
        {{ trx_json_extract('src', ['PROPKEY'], type='int', alias='propkey') }},
        {{ trx_json_extract('src', ['LINEARFROMFT'], type='float', alias='linearfromft') }},
        {{ trx_json_extract('src', ['CAPACITY'], type='varchar', alias='capacity') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['ENDDTTM'], type='timestamp_ntz', alias='enddttm') }},
        {{ trx_json_extract('src', ['STAT'], type='varchar', alias='stat') }},
        {{ trx_json_extract('src', ['APDTTM'], type='timestamp_ntz', alias='apdttm') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['PROPERTYVESSEL'], type='int', alias='propertyvessel') }},
        {{ trx_json_extract('src', ['CALCVLTN'], type='float', alias='calcvltn') }},
        {{ trx_json_extract('src', ['ZCOORDINATE'], type='float', alias='zcoordinate') }},
        {{ trx_json_extract('src', ['BLDGFLOOR'], type='int', alias='bldgfloor') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['OCCUPANCYTYPE'], type='varchar', alias='occupancytype') }},
        {{ trx_json_extract('src', ['LINEARTOM'], type='float', alias='lineartom') }},
        {{ trx_json_extract('src', ['APBY'], type='varchar', alias='apby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['EXPDTTM'], type='timestamp_ntz', alias='expdttm') }},
        {{ trx_json_extract('src', ['BATCHKEY'], type='int', alias='batchkey') }},
        {{ trx_json_extract('src', ['FINBY'], type='varchar', alias='finby') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_use_useappl') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apusekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
