{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR.APPAYMENT on 2021-07-09T15:15:21.673',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['AMTCONF'], type='float', alias='amtconf') }},
        {{ trx_json_extract('src', ['PAYMENTDISTRIBUTION'], type='int', alias='paymentdistribution') }},
        {{ trx_json_extract('src', ['CHECKBANK'], type='varchar', alias='checkbank') }},
        {{ trx_json_extract('src', ['MISCREFNO'], type='varchar', alias='miscrefno') }},
        {{ trx_json_extract('src', ['CARDNAME'], type='varchar', alias='cardname') }},
        {{ trx_json_extract('src', ['PAYMENTMETHOD'], type='int', alias='paymentmethod') }},
        {{ trx_json_extract('src', ['COMMENTS'], type='varchar', alias='comments') }},
        {{ trx_json_extract('src', ['ESCROWTRNNO'], type='int', alias='escrowtrnno') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CARDBANK'], type='varchar', alias='cardbank') }},
        {{ trx_json_extract('src', ['CARDEXPDT'], type='timestamp_ntz', alias='cardexpdt') }},
        {{ trx_json_extract('src', ['CHECKNO'], type='varchar', alias='checkno') }},
        {{ trx_json_extract('src', ['CNTCTKEY'], type='int', alias='cntctkey') }},
        {{ trx_json_extract('src', ['MISCISSUED'], type='varchar', alias='miscissued') }},
        {{ trx_json_extract('src', ['CONFDTTM'], type='timestamp_ntz', alias='confdttm') }},
        {{ trx_json_extract('src', ['CARDTYPE'], type='varchar', alias='cardtype') }},
        {{ trx_json_extract('src', ['PAYAMT'], type='float', alias='payamt') }},
        {{ trx_json_extract('src', ['APPAYKEY'], type='int', alias='appaykey') }},
        {{ trx_json_extract('src', ['APKEY'], type='int', alias='apkey') }},
        {{ trx_json_extract('src', ['TAKENBY'], type='varchar', alias='takenby') }},
        {{ trx_json_extract('src', ['PAYMETHOD'], type='varchar', alias='paymethod') }},
        {{ trx_json_extract('src', ['MISCTYPE'], type='varchar', alias='misctype') }},
        {{ trx_json_extract('src', ['CARDAUTH'], type='varchar', alias='cardauth') }},
        {{ trx_json_extract('src', ['ESCROWNO'], type='varchar', alias='escrowno') }},
        {{ trx_json_extract('src', ['STAT'], type='varchar', alias='stat') }},
        {{ trx_json_extract('src', ['CHECKNAME'], type='varchar', alias='checkname') }},
        {{ trx_json_extract('src', ['CHECKID'], type='varchar', alias='checkid') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['CARDNO'], type='varchar', alias='cardno') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['SRCBGTNOKEY'], type='int', alias='srcbgtnokey') }},
        {{ trx_json_extract('src', ['REGTRANNO'], type='int', alias='regtranno') }},
        {{ trx_json_extract('src', ['ESCROWACCTKEY'], type='int', alias='escrowacctkey') }},
        {{ trx_json_extract('src', ['PAYDTTM'], type='timestamp_ntz', alias='paydttm') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_appayment') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['appaykey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
