{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_TRADELICENSE.TRADEPROCESSSTATE on 2021-07-09T15:16:12.556',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['INITIALSTATEFLAG'], type='varchar', alias='initialstateflag') }},
        {{ trx_json_extract('src', ['DISPLAYORDER'], type='int', alias='displayorder') }},
        {{ trx_json_extract('src', ['NEXTSTATEKEY'], type='int', alias='nextstatekey') }},
        {{ trx_json_extract('src', ['NEXTSTATEFRMLA'], type='int', alias='nextstatefrmla') }},
        {{ trx_json_extract('src', ['TRADELICSTATUS'], type='varchar', alias='tradelicstatus') }},
        {{ trx_json_extract('src', ['APTRADEDEFNKEY'], type='int', alias='aptradedefnkey') }},
        {{ trx_json_extract('src', ['LICEXPDATECALCREQD'], type='varchar', alias='licexpdatecalcreqd') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SETSTATDATE'], type='varchar', alias='setstatdate') }},
        {{ trx_json_extract('src', ['APTRADEPROCESSSTATEKEY'], type='int', alias='aptradeprocessstatekey') }},
        {{ trx_json_extract('src', ['STATDATETYPE'], type='int', alias='statdatetype') }},
        {{ trx_json_extract('src', ['COMPLETEDSTATEFLAG'], type='varchar', alias='completedstateflag') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['LICENSETYPE'], type='varchar', alias='licensetype') }},
        {{ trx_json_extract('src', ['CODE'], type='varchar', alias='code') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['STAT'], type='varchar', alias='stat') }},
        {{ trx_json_extract('src', ['ADDLICENSE'], type='varchar', alias='addlicense') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['LICNEXTRENEWDATECALCREQD'], type='varchar', alias='licnextrenewdatecalcreqd') }},
        {{ trx_json_extract('src', ['ISPUBLIC'], type='varchar', alias='ispublic') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_tradelicense_tradeprocessstate') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['aptradeprocessstatekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
