{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUILDING.BLDGPLCONDLOG on 2021-07-09T15:15:33.103',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CHANGEBY'], type='varchar', alias='changeby') }},
        {{ trx_json_extract('src', ['STATUS'], type='int', alias='status') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APPLANPLCONDKEY'], type='int', alias='applanplcondkey') }},
        {{ trx_json_extract('src', ['CHANGETYPE'], type='int', alias='changetype') }},
        {{ trx_json_extract('src', ['CHANGEDTTM'], type='timestamp_ntz', alias='changedttm') }},
        {{ trx_json_extract('src', ['APPLANPLCONDLOGKEY'], type='int', alias='applanplcondlogkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_building_bldgplcondlog') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['applanplcondlogkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
