{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUILDING.BLDGPROCSTATECHECK on 2022-03-03T11:34:42.566',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APBLDGPROCESSSTATEKEY'], type='int', alias='apbldgprocessstatekey') }},
        {{ trx_json_extract('src', ['DPDESC'], type='varchar', alias='dpdesc') }},
        {{ trx_json_extract('src', ['PORTALDESCRIPTION'], type='varchar', alias='portaldescription') }},
        {{ trx_json_extract('src', ['CHECKTITLE'], type='varchar', alias='checktitle') }},
        {{ trx_json_extract('src', ['INTERNALONLYFLAG'], type='varchar', alias='internalonlyflag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['EXCLUDEFROMPENDINGPORTAL'], type='varchar', alias='excludefrompendingportal') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['SHOWINPORTAL'], type='varchar', alias='showinportal') }},
        {{ trx_json_extract('src', ['CHECKTYPE'], type='int', alias='checktype') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['APBLDGPROCSTATECHKKEY'], type='int', alias='apbldgprocstatechkkey') }},
        {{ trx_json_extract('src', ['CHECKFRMLA'], type='int', alias='checkfrmla') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_building_bldgprocstatecheck') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apbldgprocstatechkkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
