{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_PROJECT.PROJCOND on 2022-03-03T11:36:41.003',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['SUPREQD'], type='varchar', alias='supreqd') }},
        {{ trx_json_extract('src', ['APPLDBY'], type='varchar', alias='appldby') }},
        {{ trx_json_extract('src', ['APPROJCONDKEY'], type='int', alias='approjcondkey') }},
        {{ trx_json_extract('src', ['APPROJKEY'], type='int', alias='approjkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APRV'], type='varchar', alias='aprv') }},
        {{ trx_json_extract('src', ['APRVED'], type='varchar', alias='aprved') }},
        {{ trx_json_extract('src', ['APPLDDTTM'], type='timestamp_ntz', alias='applddttm') }},
        {{ trx_json_extract('src', ['APPROJCONDTYPEKEY'], type='int', alias='approjcondtypekey') }},
        {{ trx_json_extract('src', ['CMPTRGEN'], type='varchar', alias='cmptrgen') }},
        {{ trx_json_extract('src', ['APRVBY'], type='varchar', alias='aprvby') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ASSIGNED'], type='varchar', alias='assigned') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['APRVDTTM'], type='timestamp_ntz', alias='aprvdttm') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_project_projcond') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['approjcondkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
