{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_PLANNING.PLANLOG on 2022-03-03T11:35:59.644',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TOTALTIME'], type='float', alias='totaltime') }},
        {{ trx_json_extract('src', ['STOPDTTM'], type='timestamp_ntz', alias='stopdttm') }},
        {{ trx_json_extract('src', ['APPLANKEY'], type='int', alias='applankey') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['APPLANREVIEWKEY'], type='int', alias='applanreviewkey') }},
        {{ trx_json_extract('src', ['STARTBY'], type='varchar', alias='startby') }},
        {{ trx_json_extract('src', ['APPLANINSPKEY'], type='int', alias='applaninspkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ADDBYPORTALUSR'], type='varchar', alias='addbyportalusr') }},
        {{ trx_json_extract('src', ['LOGTYPE'], type='varchar', alias='logtype') }},
        {{ trx_json_extract('src', ['MODBYPORTALUSR'], type='varchar', alias='modbyportalusr') }},
        {{ trx_json_extract('src', ['STOPBY'], type='varchar', alias='stopby') }},
        {{ trx_json_extract('src', ['APPLANLOGKEY'], type='int', alias='applanlogkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_planning_planlog') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['applanlogkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
