{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUSINESSLICENSE.LICREVIEWPROB on 2021-07-09T15:15:45.092',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PROBLEM'], type='varchar', alias='problem') }},
        {{ trx_json_extract('src', ['RECDT'], type='timestamp_ntz', alias='recdt') }},
        {{ trx_json_extract('src', ['APLICPROBKEY'], type='int', alias='aplicprobkey') }},
        {{ trx_json_extract('src', ['RECBY'], type='varchar', alias='recby') }},
        {{ trx_json_extract('src', ['RESDT'], type='timestamp_ntz', alias='resdt') }},
        {{ trx_json_extract('src', ['RESOLVECODE'], type='varchar', alias='resolvecode') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['RESBY'], type='varchar', alias='resby') }},
        {{ trx_json_extract('src', ['APLICREVIEWKEY'], type='int', alias='aplicreviewkey') }},
        {{ trx_json_extract('src', ['RESVER'], type='varchar', alias='resver') }},
        {{ trx_json_extract('src', ['RECVER'], type='varchar', alias='recver') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_businesslicense_licreviewprob') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['aplicprobkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
