{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUSINESSLICENSE.LICCONDTYPE on 2021-07-09T15:15:37.892',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['SUPREQD'], type='varchar', alias='supreqd') }},
        {{ trx_json_extract('src', ['DPDESC'], type='varchar', alias='dpdesc') }},
        {{ trx_json_extract('src', ['PORTALDESCRIPTION'], type='varchar', alias='portaldescription') }},
        {{ trx_json_extract('src', ['APLICPROCESSSTATEKEY'], type='int', alias='aplicprocessstatekey') }},
        {{ trx_json_extract('src', ['INTERNALONLYFLAG'], type='varchar', alias='internalonlyflag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CONDTYPE'], type='varchar', alias='condtype') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['APLICDEFNKEY'], type='int', alias='aplicdefnkey') }},
        {{ trx_json_extract('src', ['SHOWINPORTAL'], type='varchar', alias='showinportal') }},
        {{ trx_json_extract('src', ['ADDCONDFRMLA'], type='int', alias='addcondfrmla') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['DESCRIPT'], type='varchar', alias='descript') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['APLICCONDTYPEKEY'], type='int', alias='apliccondtypekey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ISPUBLIC'], type='varchar', alias='ispublic') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_businesslicense_liccondtype') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apliccondtypekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
