{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_USE.USEREVIEWTYPE on 2021-07-09T15:16:25.525',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ASSGNGRPFRMLA'], type='int', alias='assgngrpfrmla') }},
        {{ trx_json_extract('src', ['APUSEREVIEWTYPEKEY'], type='int', alias='apusereviewtypekey') }},
        {{ trx_json_extract('src', ['REVIEWTYPE'], type='varchar', alias='reviewtype') }},
        {{ trx_json_extract('src', ['DPDESC'], type='varchar', alias='dpdesc') }},
        {{ trx_json_extract('src', ['PORTALDESCRIPTION'], type='varchar', alias='portaldescription') }},
        {{ trx_json_extract('src', ['INTERNALONLYFLAG'], type='varchar', alias='internalonlyflag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APUSEPROCESSSTATEKEY'], type='int', alias='apuseprocessstatekey') }},
        {{ trx_json_extract('src', ['APUSEDEFNKEY'], type='int', alias='apusedefnkey') }},
        {{ trx_json_extract('src', ['PLANCOPYNO'], type='int', alias='plancopyno') }},
        {{ trx_json_extract('src', ['SUSPDAYS'], type='int', alias='suspdays') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['SHOWINPORTAL'], type='varchar', alias='showinportal') }},
        {{ trx_json_extract('src', ['WORKDAY'], type='varchar', alias='workday') }},
        {{ trx_json_extract('src', ['ADDCONDFRMLA'], type='int', alias='addcondfrmla') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['DESCRIPT'], type='varchar', alias='descript') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ISPUBLIC'], type='varchar', alias='ispublic') }},
        {{ trx_json_extract('src', ['DEPT'], type='varchar', alias='dept') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_use_usereviewtype') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apusereviewtypekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
