{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_CODEENFORCEMENT.CASELOG on 2021-07-09T15:15:50.992',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APCASEINSPKEY'], type='int', alias='apcaseinspkey') }},
        {{ trx_json_extract('src', ['TOTALTIME'], type='float', alias='totaltime') }},
        {{ trx_json_extract('src', ['STOPDTTM'], type='timestamp_ntz', alias='stopdttm') }},
        {{ trx_json_extract('src', ['APCASELOGKEY'], type='int', alias='apcaselogkey') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['STARTBY'], type='varchar', alias='startby') }},
        {{ trx_json_extract('src', ['APCASEREVIEWKEY'], type='int', alias='apcasereviewkey') }},
        {{ trx_json_extract('src', ['ACTIONHOUR'], type='int', alias='actionhour') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APCASEKEY'], type='int', alias='apcasekey') }},
        {{ trx_json_extract('src', ['ADDBYPORTALUSR'], type='varchar', alias='addbyportalusr') }},
        {{ trx_json_extract('src', ['LOGTYPE'], type='varchar', alias='logtype') }},
        {{ trx_json_extract('src', ['MODBYPORTALUSR'], type='varchar', alias='modbyportalusr') }},
        {{ trx_json_extract('src', ['STOPBY'], type='varchar', alias='stopby') }},
        {{ trx_json_extract('src', ['CASEVIOLKEY'], type='int', alias='caseviolkey') }},
        {{ trx_json_extract('src', ['CASEHEARKEY'], type='int', alias='casehearkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ACTIONMIN'], type='int', alias='actionmin') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_codeenforcement_caselog') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apcaselogkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
