{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_PLANNING.PLANREVIEWPROB on 2022-03-03T11:36:05.366',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PROBLEM'], type='varchar', alias='problem') }},
        {{ trx_json_extract('src', ['RECDT'], type='timestamp_ntz', alias='recdt') }},
        {{ trx_json_extract('src', ['EPLANREVIEWSOURCE'], type='int', alias='eplanreviewsource') }},
        {{ trx_json_extract('src', ['RECBY'], type='varchar', alias='recby') }},
        {{ trx_json_extract('src', ['RESDT'], type='timestamp_ntz', alias='resdt') }},
        {{ trx_json_extract('src', ['RESOLVECODE'], type='varchar', alias='resolvecode') }},
        {{ trx_json_extract('src', ['DOCUMENTTYPE'], type='varchar', alias='documenttype') }},
        {{ trx_json_extract('src', ['APPLANREVIEWKEY'], type='int', alias='applanreviewkey') }},
        {{ trx_json_extract('src', ['REVIEWCYCLE'], type='varchar', alias='reviewcycle') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APPLANPROBKEY'], type='int', alias='applanprobkey') }},
        {{ trx_json_extract('src', ['DOCUMENTID'], type='varchar', alias='documentid') }},
        {{ trx_json_extract('src', ['EPLANREVIEWMARKUPID'], type='varchar', alias='eplanreviewmarkupid') }},
        {{ trx_json_extract('src', ['DOCUMENTPROVIDERNAME'], type='varchar', alias='documentprovidername') }},
        {{ trx_json_extract('src', ['FILENAME'], type='varchar', alias='filename') }},
        {{ trx_json_extract('src', ['RESBY'], type='varchar', alias='resby') }},
        {{ trx_json_extract('src', ['RESVER'], type='varchar', alias='resver') }},
        {{ trx_json_extract('src', ['RECVER'], type='varchar', alias='recver') }},
        {{ trx_json_extract('src', ['EPLANREVIEWCOMMENTID'], type='varchar', alias='eplanreviewcommentid') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PAGEREFERENCE'], type='varchar', alias='pagereference') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_planning_planreviewprob') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['applanprobkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
