{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR.COMMONPLANCOPY on 2021-07-09T15:15:20.510',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COPYID'], type='varchar', alias='copyid') }},
        {{ trx_json_extract('src', ['CURRENTLOCDTTM'], type='timestamp_ntz', alias='currentlocdttm') }},
        {{ trx_json_extract('src', ['REVIEWER'], type='varchar', alias='reviewer') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CURRENTLOC'], type='varchar', alias='currentloc') }},
        {{ trx_json_extract('src', ['VERSION'], type='varchar', alias='version') }},
        {{ trx_json_extract('src', ['COPYSTATUS'], type='int', alias='copystatus') }},
        {{ trx_json_extract('src', ['PLANCOPYTYPE'], type='varchar', alias='plancopytype') }},
        {{ trx_json_extract('src', ['COMMONPLANCOPYKEY'], type='int', alias='commonplancopykey') }},
        {{ trx_json_extract('src', ['COPYNO'], type='int', alias='copyno') }},
        {{ trx_json_extract('src', ['CONTACTKEY'], type='int', alias='contactkey') }},
        {{ trx_json_extract('src', ['COPYSTATUSDTTM'], type='timestamp_ntz', alias='copystatusdttm') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['OUTSOURCE'], type='varchar', alias='outsource') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_commonplancopy') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['commonplancopykey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
