{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_CODEENFORCEMENT.CASECOND on 2021-07-09T15:15:48.802',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['SUPREQD'], type='varchar', alias='supreqd') }},
        {{ trx_json_extract('src', ['APCASECONDTYPEKEY'], type='int', alias='apcasecondtypekey') }},
        {{ trx_json_extract('src', ['APPLDBY'], type='varchar', alias='appldby') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APCASEKEY'], type='int', alias='apcasekey') }},
        {{ trx_json_extract('src', ['APRV'], type='varchar', alias='aprv') }},
        {{ trx_json_extract('src', ['APRVED'], type='varchar', alias='aprved') }},
        {{ trx_json_extract('src', ['APPLDDTTM'], type='timestamp_ntz', alias='applddttm') }},
        {{ trx_json_extract('src', ['CMPTRGEN'], type='varchar', alias='cmptrgen') }},
        {{ trx_json_extract('src', ['APCASECONDKEY'], type='int', alias='apcasecondkey') }},
        {{ trx_json_extract('src', ['APRVBY'], type='varchar', alias='aprvby') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ASSIGNED'], type='varchar', alias='assigned') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['APRVDTTM'], type='timestamp_ntz', alias='aprvdttm') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_codeenforcement_casecond') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['apcasecondkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
