{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CDR_BUSINESSLICENSE.LICREVIEW on 2021-07-09T15:15:44.155',
    tags=['auto-generated', 'ips', 'stage3']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COMPDTTM'], type='timestamp_ntz', alias='compdttm') }},
        {{ trx_json_extract('src', ['COMPBYPROVIDER'], type='int', alias='compbyprovider') }},
        {{ trx_json_extract('src', ['ISSBY'], type='varchar', alias='issby') }},
        {{ trx_json_extract('src', ['RELEVANTREVIEW'], type='varchar', alias='relevantreview') }},
        {{ trx_json_extract('src', ['STARTBYPROVIDER'], type='int', alias='startbyprovider') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['TYPENO'], type='int', alias='typeno') }},
        {{ trx_json_extract('src', ['ASSIGNTOPROVIDER'], type='int', alias='assigntoprovider') }},
        {{ trx_json_extract('src', ['STARTBY'], type='varchar', alias='startby') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['COMPBY'], type='varchar', alias='compby') }},
        {{ trx_json_extract('src', ['RESULT'], type='varchar', alias='result') }},
        {{ trx_json_extract('src', ['COMP'], type='varchar', alias='comp') }},
        {{ trx_json_extract('src', ['ISSDTTM'], type='timestamp_ntz', alias='issdttm') }},
        {{ trx_json_extract('src', ['SUSPDT'], type='timestamp_ntz', alias='suspdt') }},
        {{ trx_json_extract('src', ['ACTLTM'], type='float', alias='actltm') }},
        {{ trx_json_extract('src', ['RESULTDTTM'], type='timestamp_ntz', alias='resultdttm') }},
        {{ trx_json_extract('src', ['CMPTRGEN'], type='varchar', alias='cmptrgen') }},
        {{ trx_json_extract('src', ['APLICREVIEWKEY'], type='int', alias='aplicreviewkey') }},
        {{ trx_json_extract('src', ['RESULTBYPROVIDER'], type='int', alias='resultbyprovider') }},
        {{ trx_json_extract('src', ['SCHEDBY'], type='varchar', alias='schedby') }},
        {{ trx_json_extract('src', ['APLICREVIEWTYPEKEY'], type='int', alias='aplicreviewtypekey') }},
        {{ trx_json_extract('src', ['SCHEDDTTM'], type='timestamp_ntz', alias='scheddttm') }},
        {{ trx_json_extract('src', ['STARTED'], type='varchar', alias='started') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ASSIGNED'], type='varchar', alias='assigned') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['APLICKEY'], type='int', alias='aplickey') }},
        {{ trx_json_extract('src', ['RESULTGEN'], type='varchar', alias='resultgen') }},
        {{ trx_json_extract('src', ['DEPT'], type='varchar', alias='dept') }},
        {{ trx_json_extract('src', ['ASSIGNTO'], type='varchar', alias='assignto') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['RESULTBY'], type='varchar', alias='resultby') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_cdr_businesslicense_licreview') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['aplicreviewkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
