{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CORE_CORRESPONDENCE.CORRPROCESSSETUP on 2022-06-01T05:11:07.356',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ATTACHMENTREPORT'], type='varchar', alias='attachmentreport') }},
        {{ trx_json_extract('src', ['BODYREPORT'], type='varchar', alias='bodyreport') }},
        {{ trx_json_extract('src', ['SENDAFTERDAYS'], type='int', alias='sendafterdays') }},
        {{ trx_json_extract('src', ['EDMSETUP'], type='varchar', alias='edmsetup') }},
        {{ trx_json_extract('src', ['INCLUDEWEEKENDSCREATE'], type='varchar', alias='includeweekendscreate') }},
        {{ trx_json_extract('src', ['DOCUMENTTYPE'], type='int', alias='documenttype') }},
        {{ trx_json_extract('src', ['CORRDELIVERY'], type='int', alias='corrdelivery') }},
        {{ trx_json_extract('src', ['PRINTREPORT'], type='varchar', alias='printreport') }},
        {{ trx_json_extract('src', ['SCHEDULEDAFTERDAYS'], type='int', alias='scheduledafterdays') }},
        {{ trx_json_extract('src', ['CORRFILEPATH'], type='varchar', alias='corrfilepath') }},
        {{ trx_json_extract('src', ['EMAILBOCOMPONENT'], type='varchar', alias='emailbocomponent') }},
        {{ trx_json_extract('src', ['EMAILCOMPONENT'], type='varchar', alias='emailcomponent') }},
        {{ trx_json_extract('src', ['USECONTACTPREFERENCE'], type='varchar', alias='usecontactpreference') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SAVEDINFILESYSTEMFLAG'], type='varchar', alias='savedinfilesystemflag') }},
        {{ trx_json_extract('src', ['INCLUDEHOLIDAYSEMAIL'], type='varchar', alias='includeholidaysemail') }},
        {{ trx_json_extract('src', ['INCLUDEWEEKENDSEMAIL'], type='varchar', alias='includeweekendsemail') }},
        {{ trx_json_extract('src', ['ATTACHMENTCATALOG'], type='int', alias='attachmentcatalog') }},
        {{ trx_json_extract('src', ['VIEWREPORT'], type='varchar', alias='viewreport') }},
        {{ trx_json_extract('src', ['ATTACHTORECORD'], type='varchar', alias='attachtorecord') }},
        {{ trx_json_extract('src', ['CORRSETUPTYPE'], type='int', alias='corrsetuptype') }},
        {{ trx_json_extract('src', ['SCHEDULEFLAG'], type='varchar', alias='scheduleflag') }},
        {{ trx_json_extract('src', ['CONTENTASATTACHMENT'], type='varchar', alias='contentasattachment') }},
        {{ trx_json_extract('src', ['INCLUDEHOLIDAYSCREATE'], type='varchar', alias='includeholidayscreate') }},
        {{ trx_json_extract('src', ['DESCRIPT'], type='varchar', alias='descript') }},
        {{ trx_json_extract('src', ['DAYSTOSTORE'], type='int', alias='daystostore') }},
        {{ trx_json_extract('src', ['CORRPROCESSSETUPKEY'], type='int', alias='corrprocesssetupkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ATTACHMENTCONDITIONFORMULA'], type='int', alias='attachmentconditionformula') }},
        {{ trx_json_extract('src', ['SUBJECTREPORT'], type='varchar', alias='subjectreport') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['NAME'], type='varchar', alias='name') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_core_correspondence_corrprocesssetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['corrprocesssetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
