{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CORE_ACCESSCONTROL.ZACCUSR on 2021-09-13T17:52:19.611',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['NTUSRNAME'], type='varchar', alias='ntusrname') }},
        {{ trx_json_extract('src', ['ISREPORTAUTHOR'], type='varchar', alias='isreportauthor') }},
        {{ trx_json_extract('src', ['EXPDAYS'], type='int', alias='expdays') }},
        {{ trx_json_extract('src', ['USRKEY'], type='int', alias='usrkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['UNIQUEPWD'], type='varchar', alias='uniquepwd') }},
        {{ trx_json_extract('src', ['EMPID'], type='varchar', alias='empid') }},
        {{ trx_json_extract('src', ['AUTHCODE'], type='varchar', alias='authcode') }},
        {{ trx_json_extract('src', ['ROLEADMIN'], type='varchar', alias='roleadmin') }},
        {{ trx_json_extract('src', ['DATAGRP'], type='varchar', alias='datagrp') }},
        {{ trx_json_extract('src', ['USRNAME'], type='varchar', alias='usrname') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PASSEXPDTTM'], type='timestamp_ntz', alias='passexpdttm') }},
        {{ trx_json_extract('src', ['LOGINATTEMPTS'], type='int', alias='loginattempts') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_core_accesscontrol_zaccusr') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['usrkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
