{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CORE_DATALAKE.FACET on 2024-11-18T14:12:26.126',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FACETCONTEXT'], type='varchar', alias='facetcontext') }},
        {{ trx_json_extract('src', ['ISLINKED'], type='varchar', alias='islinked') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['FACETNAME'], type='varchar', alias='facetname') }},
        {{ trx_json_extract('src', ['ISDATACATALOGCREATED'], type='varchar', alias='isdatacatalogcreated') }},
        {{ trx_json_extract('src', ['FACETKEY'], type='int', alias='facetkey') }},
        {{ trx_json_extract('src', ['LICENSENAME'], type='varchar', alias='licensename') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_core_datalake_facet') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['facetkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
