{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CORE_BATCHPROCESSING.USEREXCEPTION on 2021-07-30T14:11:39.795',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['RUNKEY'], type='int', alias='runkey') }},
        {{ trx_json_extract('src', ['BATCHPROCESSEXCEPTIONKEY'], type='int', alias='batchprocessexceptionkey') }},
        {{ trx_json_extract('src', ['LINEITEMSETUPKEY'], type='int', alias='lineitemsetupkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['USEREXCEPTIONKEY'], type='int', alias='userexceptionkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_core_batchprocessing_userexception') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['userexceptionkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
