{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CRM.CRMLOGLINK on 2021-07-09T15:16:55.460',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['LOGTYPECODE'], type='varchar', alias='logtypecode') }},
        {{ trx_json_extract('src', ['ENABLED'], type='varchar', alias='enabled') }},
        {{ trx_json_extract('src', ['ISINCUSTOMERDETAILS'], type='varchar', alias='isincustomerdetails') }},
        {{ trx_json_extract('src', ['TABORDER'], type='int', alias='taborder') }},
        {{ trx_json_extract('src', ['ISINMYPROJECTS'], type='varchar', alias='isinmyprojects') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LINKTEXT'], type='varchar', alias='linktext') }},
        {{ trx_json_extract('src', ['ALLOWCOMMENTS'], type='varchar', alias='allowcomments') }},
        {{ trx_json_extract('src', ['REQUESTTYPE'], type='int', alias='requesttype') }},
        {{ trx_json_extract('src', ['LOGLINKKEY'], type='int', alias='loglinkkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['ISINPUBLICDETAILS'], type='varchar', alias='isinpublicdetails') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_crm_crmloglink') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['loglinkkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
