{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CRM.DETAILPAGE on 2024-10-10T10:04:10.915',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCESSIDUPDATE'], type='int', alias='accessidupdate') }},
        {{ trx_json_extract('src', ['TABPANEID'], type='varchar', alias='tabpaneid') }},
        {{ trx_json_extract('src', ['EXPIREDATE'], type='timestamp_ntz', alias='expiredate') }},
        {{ trx_json_extract('src', ['CLASSNAME'], type='varchar', alias='classname') }},
        {{ trx_json_extract('src', ['DISPLAYORDER'], type='int', alias='displayorder') }},
        {{ trx_json_extract('src', ['ACCESSIDADD'], type='int', alias='accessidadd') }},
        {{ trx_json_extract('src', ['PORTALPUBLICCONSTRAINT'], type='int', alias='portalpublicconstraint') }},
        {{ trx_json_extract('src', ['DISPLAYONLOAD'], type='varchar', alias='displayonload') }},
        {{ trx_json_extract('src', ['EVENTHANDLER'], type='int', alias='eventhandler') }},
        {{ trx_json_extract('src', ['DETAILPAGEKEY'], type='int', alias='detailpagekey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PORTALCUSTOMERCONSTRAINT'], type='int', alias='portalcustomerconstraint') }},
        {{ trx_json_extract('src', ['CLASSDESC'], type='varchar', alias='classdesc') }},
        {{ trx_json_extract('src', ['EFFECTIVEDATE'], type='timestamp_ntz', alias='effectivedate') }},
        {{ trx_json_extract('src', ['PORTALDETAILPAGEPLACEMENT'], type='int', alias='portaldetailpageplacement') }},
        {{ trx_json_extract('src', ['PORTALDETAILPAGEAREA'], type='int', alias='portaldetailpagearea') }},
        {{ trx_json_extract('src', ['ACCESSIDVIEW'], type='int', alias='accessidview') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['DISPLAY'], type='int', alias='display') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_crm_detailpage') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['detailpagekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
