{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table CRM.PROBDEFNGLOBAL on 2024-10-10T10:04:10.618',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CREATEDINLASTXMIN'], type='int', alias='createdinlastxmin') }},
        {{ trx_json_extract('src', ['RESOLVELINKEDREQUESTS'], type='varchar', alias='resolvelinkedrequests') }},
        {{ trx_json_extract('src', ['SEARCHRADIUS'], type='float', alias='searchradius') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PROBDEFNGLOBALKEY'], type='int', alias='probdefnglobalkey') }},
        {{ trx_json_extract('src', ['SAMEREQUESTTYPEFLG'], type='varchar', alias='samerequesttypeflg') }},
        {{ trx_json_extract('src', ['CORRPROCESSSETUP'], type='int', alias='corrprocesssetup') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['CHKDUPFLG'], type='varchar', alias='chkdupflg') }},
        {{ trx_json_extract('src', ['CHECKDUPLICATELOCALONLY'], type='varchar', alias='checkduplicatelocalonly') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['NOTIFYCUSTOMER'], type='varchar', alias='notifycustomer') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_crm_probdefnglobal') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['probdefnglobalkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
