{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table GIS.MIRCOMP on 2024-10-03T13:42:04.893',
    tags=['auto-generated', 'ips', 'stage4']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COMPTYPE'], type='int', alias='comptype') }},
        {{ trx_json_extract('src', ['UNITID2'], type='varchar', alias='unitid2') }},
        {{ trx_json_extract('src', ['UNITTYPE'], type='varchar', alias='unittype') }},
        {{ trx_json_extract('src', ['MIRID'], type='int', alias='mirid') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['UNITID1'], type='varchar', alias='unitid1') }},
        {{ trx_json_extract('src', ['PARLINENO'], type='varchar', alias='parlineno') }},
        {{ trx_json_extract('src', ['MAINCOMP2'], type='int', alias='maincomp2') }},
        {{ trx_json_extract('src', ['MAINCOMP1'], type='int', alias='maincomp1') }},
        {{ trx_json_extract('src', ['MIRCOMPKEY'], type='int', alias='mircompkey') }},
        {{ trx_json_extract('src', ['FEATUREID'], type='int', alias='featureid') }},
        {{ trx_json_extract('src', ['PRCLVER'], type='int', alias='prclver') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['LAYERNAME'], type='varchar', alias='layername') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PROPVER'], type='int', alias='propver') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_gis_mircomp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['mircompkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
