{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table INF_VALUATION_VALUATION.ASSVALRESERVEGD on 2024-10-07T10:09:05.507',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CLOSERESERVE'], type='float', alias='closereserve') }},
        {{ trx_json_extract('src', ['ACUMDEPB4REVAL'], type='float', alias='acumdepb4reval') }},
        {{ trx_json_extract('src', ['SOURCETYPE'], type='varchar', alias='sourcetype') }},
        {{ trx_json_extract('src', ['BALSHTBOOKVAL'], type='float', alias='balshtbookval') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['DISPDATE'], type='timestamp_ntz', alias='dispdate') }},
        {{ trx_json_extract('src', ['OPENWDV'], type='float', alias='openwdv') }},
        {{ trx_json_extract('src', ['OPENREPLCOST'], type='float', alias='openreplcost') }},
        {{ trx_json_extract('src', ['CAPEXP'], type='float', alias='capexp') }},
        {{ trx_json_extract('src', ['VALKEY'], type='int', alias='valkey') }},
        {{ trx_json_extract('src', ['RESERVEDATE'], type='timestamp_ntz', alias='reservedate') }},
        {{ trx_json_extract('src', ['OPENRESIDLIFE'], type='float', alias='openresidlife') }},
        {{ trx_json_extract('src', ['REMLIFE'], type='float', alias='remlife') }},
        {{ trx_json_extract('src', ['RUNNO'], type='int', alias='runno') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['VALUETODISPOSE'], type='float', alias='valuetodispose') }},
        {{ trx_json_extract('src', ['ASSVALRESERVEGDKEY'], type='int', alias='assvalreservegdkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['WDV'], type='float', alias='wdv') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ASSVALRESERVEKEY'], type='int', alias='assvalreservekey') }},
        {{ trx_json_extract('src', ['REVALREPLCOST'], type='float', alias='revalreplcost') }},
        {{ trx_json_extract('src', ['OPENRESERVE'], type='float', alias='openreserve') }},
        {{ trx_json_extract('src', ['MOVEMENT'], type='float', alias='movement') }},
        {{ trx_json_extract('src', ['OPENEXPLIFE'], type='float', alias='openexplife') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['OPENFYDATE'], type='timestamp_ntz', alias='openfydate') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_inf_valuation_valuation_assvalreservegd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['assvalreservegdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
