{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table METERMANAGEMENT_WATER.READINGIMPORTROUTEDETAIL on 2022-03-03T11:30:54.588',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ROUTEKEY'], type='int', alias='routekey') }},
        {{ trx_json_extract('src', ['STOPDTTM'], type='timestamp_ntz', alias='stopdttm') }},
        {{ trx_json_extract('src', ['STARTDTTM'], type='timestamp_ntz', alias='startdttm') }},
        {{ trx_json_extract('src', ['STATUS'], type='int', alias='status') }},
        {{ trx_json_extract('src', ['IMPORTFILENAME'], type='varchar', alias='importfilename') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['NOOFMETERS'], type='int', alias='noofmeters') }},
        {{ trx_json_extract('src', ['UNHANDLEDEXCEPDESC'], type='varchar', alias='unhandledexcepdesc') }},
        {{ trx_json_extract('src', ['READINGIMPORTACTIVITYKEY'], type='int', alias='readingimportactivitykey') }},
        {{ trx_json_extract('src', ['IMPORTEXCLFLAG'], type='varchar', alias='importexclflag') }},
        {{ trx_json_extract('src', ['READINGEXPORTROUTEDTLKEY'], type='int', alias='readingexportroutedtlkey') }},
        {{ trx_json_extract('src', ['READINGIMPORTROUTEDTLKEY'], type='int', alias='readingimportroutedtlkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['READINGIMPORTROUTEKEY'], type='int', alias='readingimportroutekey') }},
        {{ trx_json_extract('src', ['RERUNFLAG'], type='varchar', alias='rerunflag') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_metermanagement_water_readingimportroutedetail') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['readingimportroutedtlkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
