{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table METERMANAGEMENT_WATER.USGESTRULEGRP on 2022-03-03T11:30:56.910',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['USGESTRULEGRPID'], type='varchar', alias='usgestrulegrpid') }},
        {{ trx_json_extract('src', ['DEFAULTESTFORMULAKEY'], type='int', alias='defaultestformulakey') }},
        {{ trx_json_extract('src', ['HIGHCONDITIONFORMULAKEY'], type='int', alias='highconditionformulakey') }},
        {{ trx_json_extract('src', ['HIGHDEFAULTESTFORMULAKEY'], type='int', alias='highdefaultestformulakey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CONDITIONFORMULAKEY'], type='int', alias='conditionformulakey') }},
        {{ trx_json_extract('src', ['PARENTGROUPKEY'], type='int', alias='parentgroupkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['USGESTRULEGRPKEY'], type='int', alias='usgestrulegrpkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_metermanagement_water_usgestrulegrp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['usgestrulegrpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
