{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table METERMANAGEMENT_WATER.READINGIMPORTSETUP on 2022-03-03T11:30:55.344',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['READINGIMPORTSETUPKEY'], type='int', alias='readingimportsetupkey') }},
        {{ trx_json_extract('src', ['FORCEEXPORTSELECTIONFLAG'], type='varchar', alias='forceexportselectionflag') }},
        {{ trx_json_extract('src', ['SHOWFILEOPENDIALOGFLAG'], type='varchar', alias='showfileopendialogflag') }},
        {{ trx_json_extract('src', ['RECEIVERCODE'], type='varchar', alias='receivercode') }},
        {{ trx_json_extract('src', ['IMPORTFILETEMPLATE'], type='varchar', alias='importfiletemplate') }},
        {{ trx_json_extract('src', ['IMPORTRUNNUMBER'], type='int', alias='importrunnumber') }},
        {{ trx_json_extract('src', ['REJECTNONEXROUTE'], type='varchar', alias='rejectnonexroute') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PROCESSREADYTOBILLFLAG'], type='varchar', alias='processreadytobillflag') }},
        {{ trx_json_extract('src', ['RESOLVESRFLAG'], type='varchar', alias='resolvesrflag') }},
        {{ trx_json_extract('src', ['SENDERCODE'], type='varchar', alias='sendercode') }},
        {{ trx_json_extract('src', ['IMPEXPDAYS'], type='int', alias='impexpdays') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['IMPORTTYPE'], type='int', alias='importtype') }},
        {{ trx_json_extract('src', ['REJECTPRIORMETERREAD'], type='varchar', alias='rejectpriormeterread') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['IMPORTDIRPATH'], type='varchar', alias='importdirpath') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_metermanagement_water_readingimportsetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['readingimportsetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
