{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table METERMANAGEMENT_WATER.READINGIMPORTROUTE on 2022-03-03T11:30:54.881',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['READINGEXPORTROUTEKEY'], type='int', alias='readingexportroutekey') }},
        {{ trx_json_extract('src', ['ROUTEKEY'], type='int', alias='routekey') }},
        {{ trx_json_extract('src', ['RERUNALLOWEDFLAG'], type='varchar', alias='rerunallowedflag') }},
        {{ trx_json_extract('src', ['DIRECTORYPATH'], type='varchar', alias='directorypath') }},
        {{ trx_json_extract('src', ['EXCLUDEFROMIMPORTFLAG'], type='varchar', alias='excludefromimportflag') }},
        {{ trx_json_extract('src', ['IMPORTFILENAME'], type='varchar', alias='importfilename') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CYCLEIMPORTTYPE'], type='int', alias='cycleimporttype') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['READINGIMPORTROUTEKEY'], type='int', alias='readingimportroutekey') }},
        {{ trx_json_extract('src', ['READINGIMPORTSCHEDULEKEY'], type='int', alias='readingimportschedulekey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_metermanagement_water_readingimportroute') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['readingimportroutekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
