{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table PORTAL.MEMBERSHIP on 2022-06-01T05:10:49.319',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['LASTPASSWORDCHANGEDDATE'], type='timestamp_ntz', alias='lastpasswordchangeddate') }},
        {{ trx_json_extract('src', ['MEMBERSHIPKEY'], type='int', alias='membershipkey') }},
        {{ trx_json_extract('src', ['ACTIVATEDDATE'], type='timestamp_ntz', alias='activateddate') }},
        {{ trx_json_extract('src', ['PASSWORDHASH'], type='varchar', alias='passwordhash') }},
        {{ trx_json_extract('src', ['LOCKEDOUTDATE'], type='timestamp_ntz', alias='lockedoutdate') }},
        {{ trx_json_extract('src', ['USERNAME'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['FAILEDPASSWORDANSWERCOUNT'], type='int', alias='failedpasswordanswercount') }},
        {{ trx_json_extract('src', ['ISPWDRESETREQ'], type='varchar', alias='ispwdresetreq') }},
        {{ trx_json_extract('src', ['CONTACT'], type='int', alias='contact') }},
        {{ trx_json_extract('src', ['PASSWORDSALT'], type='varchar', alias='passwordsalt') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LASTLOGINDATE'], type='timestamp_ntz', alias='lastlogindate') }},
        {{ trx_json_extract('src', ['LASTPASSWORDRESETDATE'], type='timestamp_ntz', alias='lastpasswordresetdate') }},
        {{ trx_json_extract('src', ['PASSWORDANSWERHASH'], type='varchar', alias='passwordanswerhash') }},
        {{ trx_json_extract('src', ['APPROVEDDATE'], type='timestamp_ntz', alias='approveddate') }},
        {{ trx_json_extract('src', ['ISACTIVATED'], type='varchar', alias='isactivated') }},
        {{ trx_json_extract('src', ['PASSWORDANSWERSALT'], type='varchar', alias='passwordanswersalt') }},
        {{ trx_json_extract('src', ['ISAPPROVED'], type='varchar', alias='isapproved') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['ISLOCKEDOUT'], type='varchar', alias='islockedout') }},
        {{ trx_json_extract('src', ['FAILEDPASSWORDCOUNT'], type='int', alias='failedpasswordcount') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PARENTUSER'], type='int', alias='parentuser') }},
        {{ trx_json_extract('src', ['ACTIVATIONCODE'], type='varchar', alias='activationcode') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['PASSWORDQUESTION'], type='varchar', alias='passwordquestion') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_portal_membership') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['membershipkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
