{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table PORTAL.GLOBALTYPESETUP on 2022-06-01T05:10:50.312',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['SHOWRELATEDREQUEST'], type='varchar', alias='showrelatedrequest') }},
        {{ trx_json_extract('src', ['WIZARDPROJECTTYPE'], type='int', alias='wizardprojecttype') }},
        {{ trx_json_extract('src', ['SHOWRELATEDPLANNING'], type='varchar', alias='showrelatedplanning') }},
        {{ trx_json_extract('src', ['SHOWRELATEDCASE'], type='varchar', alias='showrelatedcase') }},
        {{ trx_json_extract('src', ['ALLOWADDRELATED'], type='varchar', alias='allowaddrelated') }},
        {{ trx_json_extract('src', ['ALLOWDELETERELATED'], type='varchar', alias='allowdeleterelated') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SHOWRELATEDPROJECT'], type='varchar', alias='showrelatedproject') }},
        {{ trx_json_extract('src', ['SHOWRELATEDBUILDING'], type='varchar', alias='showrelatedbuilding') }},
        {{ trx_json_extract('src', ['SHOWRELATEDUSE'], type='varchar', alias='showrelateduse') }},
        {{ trx_json_extract('src', ['GLOBALTYPESETUPKEY'], type='int', alias='globaltypesetupkey') }},
        {{ trx_json_extract('src', ['SHOWRELATEDBUSINESSLICENSE'], type='varchar', alias='showrelatedbusinesslicense') }},
        {{ trx_json_extract('src', ['PRODUCTFAMILY'], type='varchar', alias='productfamily') }},
        {{ trx_json_extract('src', ['SHOWRELATEDTRADELICENSE'], type='varchar', alias='showrelatedtradelicense') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_portal_globaltypesetup') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['globaltypesetupkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
