{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table PORTAL.SCENARIO on 2022-06-01T05:10:46.898',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PROJECTAPPLICATION'], type='int', alias='projectapplication') }},
        {{ trx_json_extract('src', ['CONFIGURATIONID'], type='varchar', alias='configurationid') }},
        {{ trx_json_extract('src', ['REQRECCOUNT'], type='int', alias='reqreccount') }},
        {{ trx_json_extract('src', ['SUBRECCOUNT'], type='int', alias='subreccount') }},
        {{ trx_json_extract('src', ['STATUS'], type='varchar', alias='status') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PROCESSID'], type='varchar', alias='processid') }},
        {{ trx_json_extract('src', ['MEMBERSHIP'], type='int', alias='membership') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['LASTSAVE'], type='timestamp_ntz', alias='lastsave') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['NAME'], type='varchar', alias='name') }},
        {{ trx_json_extract('src', ['SCENARIOKEY'], type='int', alias='scenariokey') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_portal_scenario') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['scenariokey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
