{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table PROPERTY.PARCEL on 2021-07-09T15:16:27.000',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PLANMEDIA'], type='varchar', alias='planmedia') }},
        {{ trx_json_extract('src', ['PRCLSTAT'], type='varchar', alias='prclstat') }},
        {{ trx_json_extract('src', ['PROPNOTE'], type='varchar', alias='propnote') }},
        {{ trx_json_extract('src', ['PRCLID'], type='varchar', alias='prclid') }},
        {{ trx_json_extract('src', ['SECTION'], type='varchar', alias='section') }},
        {{ trx_json_extract('src', ['LOTUM'], type='varchar', alias='lotum') }},
        {{ trx_json_extract('src', ['ATLASPAGE'], type='varchar', alias='atlaspage') }},
        {{ trx_json_extract('src', ['COUNTY'], type='varchar', alias='county') }},
        {{ trx_json_extract('src', ['LOTFRONTAG'], type='float', alias='lotfrontag') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PRCLNAME'], type='varchar', alias='prclname') }},
        {{ trx_json_extract('src', ['PRCLKEY'], type='int', alias='prclkey') }},
        {{ trx_json_extract('src', ['LOTSZ'], type='float', alias='lotsz') }},
        {{ trx_json_extract('src', ['LOTSHP'], type='varchar', alias='lotshp') }},
        {{ trx_json_extract('src', ['LEGALOWNER'], type='varchar', alias='legalowner') }},
        {{ trx_json_extract('src', ['VERSION'], type='int', alias='version') }},
        {{ trx_json_extract('src', ['MAPNO'], type='varchar', alias='mapno') }},
        {{ trx_json_extract('src', ['LNDPRICETY'], type='varchar', alias='lndpricety') }},
        {{ trx_json_extract('src', ['COMMELEM'], type='float', alias='commelem') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['LOT'], type='varchar', alias='lot') }},
        {{ trx_json_extract('src', ['AREA'], type='varchar', alias='area') }},
        {{ trx_json_extract('src', ['SUBOFKEY'], type='int', alias='subofkey') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['PRCLTYPE'], type='varchar', alias='prcltype') }},
        {{ trx_json_extract('src', ['TOWNSHIP'], type='varchar', alias='township') }},
        {{ trx_json_extract('src', ['BLOCK'], type='varchar', alias='block') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['LOTDPTH'], type='float', alias='lotdpth') }},
        {{ trx_json_extract('src', ['RANGE'], type='varchar', alias='range') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['CURRPRCL'], type='varchar', alias='currprcl') }},
        {{ trx_json_extract('src', ['SUBDIV'], type='varchar', alias='subdiv') }},
        {{ trx_json_extract('src', ['SUBDIVCODE'], type='varchar', alias='subdivcode') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_property_parcel') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['prclkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
