{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table PROPERTY.PROPERTYINFORMATION on 2021-07-09T15:16:27.441',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PLANMEDIA'], type='varchar', alias='planmedia') }},
        {{ trx_json_extract('src', ['PROPNOTE'], type='varchar', alias='propnote') }},
        {{ trx_json_extract('src', ['CITYOWNED'], type='varchar', alias='cityowned') }},
        {{ trx_json_extract('src', ['TAXBLOCK'], type='varchar', alias='taxblock') }},
        {{ trx_json_extract('src', ['MAPNUMBER'], type='varchar', alias='mapnumber') }},
        {{ trx_json_extract('src', ['NOTES'], type='varchar', alias='notes') }},
        {{ trx_json_extract('src', ['STATUS'], type='varchar', alias='status') }},
        {{ trx_json_extract('src', ['PROPNAME'], type='varchar', alias='propname') }},
        {{ trx_json_extract('src', ['COUNTY'], type='varchar', alias='county') }},
        {{ trx_json_extract('src', ['PROPTYPE'], type='varchar', alias='proptype') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SUBDIVISION'], type='varchar', alias='subdivision') }},
        {{ trx_json_extract('src', ['LANDMARK'], type='varchar', alias='landmark') }},
        {{ trx_json_extract('src', ['PROPID'], type='varchar', alias='propid') }},
        {{ trx_json_extract('src', ['LEGALOWNER'], type='varchar', alias='legalowner') }},
        {{ trx_json_extract('src', ['VERSION'], type='int', alias='version') }},
        {{ trx_json_extract('src', ['VACANT'], type='varchar', alias='vacant') }},
        {{ trx_json_extract('src', ['HEALTHAREA'], type='int', alias='healtharea') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['LOT'], type='varchar', alias='lot') }},
        {{ trx_json_extract('src', ['BOROUGH'], type='varchar', alias='borough') }},
        {{ trx_json_extract('src', ['AREA'], type='varchar', alias='area') }},
        {{ trx_json_extract('src', ['SPECIALPLACENAME'], type='varchar', alias='specialplacename') }},
        {{ trx_json_extract('src', ['PROPKEY'], type='int', alias='propkey') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['CURRPROP'], type='varchar', alias='currprop') }},
        {{ trx_json_extract('src', ['TAXEXEMPT'], type='varchar', alias='taxexempt') }},
        {{ trx_json_extract('src', ['LOFT'], type='varchar', alias='loft') }},
        {{ trx_json_extract('src', ['TOWNSHIP'], type='varchar', alias='township') }},
        {{ trx_json_extract('src', ['BLOCK'], type='varchar', alias='block') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['CENSUSTRACT'], type='int', alias='censustract') }},
        {{ trx_json_extract('src', ['SUBDIVDESC'], type='varchar', alias='subdivdesc') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_property_propertyinformation') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['propkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
