{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table PROPERTY.ADDRSTNZ on 2022-03-03T11:39:13.767',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['STTYPE'], type='varchar', alias='sttype') }},
        {{ trx_json_extract('src', ['STATE'], type='varchar', alias='state') }},
        {{ trx_json_extract('src', ['OSTNOHI'], type='int', alias='ostnohi') }},
        {{ trx_json_extract('src', ['ESTNOLO'], type='int', alias='estnolo') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['OSTNOLO'], type='int', alias='ostnolo') }},
        {{ trx_json_extract('src', ['STNAME'], type='varchar', alias='stname') }},
        {{ trx_json_extract('src', ['STNMKEY'], type='int', alias='stnmkey') }},
        {{ trx_json_extract('src', ['POSTCODE'], type='varchar', alias='postcode') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['SUBURB'], type='varchar', alias='suburb') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ESTNOHI'], type='int', alias='estnohi') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_property_addrstnz') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['stnmkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
