{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table RESOURCES.ESCROWTRN on 2022-03-03T11:26:07.623',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TRNDTTM'], type='timestamp_ntz', alias='trndttm') }},
        {{ trx_json_extract('src', ['ADJREAS'], type='varchar', alias='adjreas') }},
        {{ trx_json_extract('src', ['TRNBY'], type='varchar', alias='trnby') }},
        {{ trx_json_extract('src', ['ESCROWPAYKEY'], type='int', alias='escrowpaykey') }},
        {{ trx_json_extract('src', ['TRNTYPE'], type='int', alias='trntype') }},
        {{ trx_json_extract('src', ['TRNNO'], type='int', alias='trnno') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['TRNAMT'], type='float', alias='trnamt') }},
        {{ trx_json_extract('src', ['XFERREFTRNNO'], type='int', alias='xferreftrnno') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ESCROWACCTKEY'], type='int', alias='escrowacctkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_resources_escrowtrn') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['trnno']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
