{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table RESOURCES.ESCROWACCT on 2022-03-03T11:26:05.846',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DESCRIPTION'], type='varchar', alias='description') }},
        {{ trx_json_extract('src', ['ACCTSTATUSDTTM'], type='timestamp_ntz', alias='acctstatusdttm') }},
        {{ trx_json_extract('src', ['ESCROWACCTNO'], type='varchar', alias='escrowacctno') }},
        {{ trx_json_extract('src', ['ACCTTYPE'], type='varchar', alias='accttype') }},
        {{ trx_json_extract('src', ['ACCTSTATUSBY'], type='varchar', alias='acctstatusby') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CNTCTKEY'], type='int', alias='cntctkey') }},
        {{ trx_json_extract('src', ['MINBALVALUE'], type='float', alias='minbalvalue') }},
        {{ trx_json_extract('src', ['MAXBALVALUE'], type='float', alias='maxbalvalue') }},
        {{ trx_json_extract('src', ['LASTTRANDTTM'], type='timestamp_ntz', alias='lasttrandttm') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ESCROWACCTKEY'], type='int', alias='escrowacctkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['ACCTSTATUS'], type='int', alias='acctstatus') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_resources_escrowacct') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['escrowacctkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
