{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table RESOURCES.BUDGETNUMBER on 2021-07-09T15:16:27.915',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['BUDGETNUMBERKEY'], type='int', alias='budgetnumberkey') }},
        {{ trx_json_extract('src', ['SEGMENT14'], type='varchar', alias='segment14') }},
        {{ trx_json_extract('src', ['SEGMENT15'], type='varchar', alias='segment15') }},
        {{ trx_json_extract('src', ['SEGMENT8'], type='varchar', alias='segment8') }},
        {{ trx_json_extract('src', ['SEGMENT1'], type='varchar', alias='segment1') }},
        {{ trx_json_extract('src', ['SEGMENT5'], type='varchar', alias='segment5') }},
        {{ trx_json_extract('src', ['SEGMENT13'], type='varchar', alias='segment13') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SEGMENT7'], type='varchar', alias='segment7') }},
        {{ trx_json_extract('src', ['SEGMENT4'], type='varchar', alias='segment4') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['SEGMENT6'], type='varchar', alias='segment6') }},
        {{ trx_json_extract('src', ['CODE'], type='varchar', alias='code') }},
        {{ trx_json_extract('src', ['SEGMENT12'], type='varchar', alias='segment12') }},
        {{ trx_json_extract('src', ['SEGMENT10'], type='varchar', alias='segment10') }},
        {{ trx_json_extract('src', ['EFFDATE'], type='timestamp_ntz', alias='effdate') }},
        {{ trx_json_extract('src', ['SEGMENT2'], type='varchar', alias='segment2') }},
        {{ trx_json_extract('src', ['DESCRIPT'], type='varchar', alias='descript') }},
        {{ trx_json_extract('src', ['SEGMENT11'], type='varchar', alias='segment11') }},
        {{ trx_json_extract('src', ['SEGMENT9'], type='varchar', alias='segment9') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['SEGMENT3'], type='varchar', alias='segment3') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_resources_budgetnumber') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['budgetnumberkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
