{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table RESOURCES.EMPLOYEE on 2022-03-03T11:39:32.885',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['EMERGREL1'], type='varchar', alias='emergrel1') }},
        {{ trx_json_extract('src', ['HIREDATE'], type='timestamp_ntz', alias='hiredate') }},
        {{ trx_json_extract('src', ['CREWLDR'], type='varchar', alias='crewldr') }},
        {{ trx_json_extract('src', ['EMERGINFO'], type='varchar', alias='emerginfo') }},
        {{ trx_json_extract('src', ['EMERGREL2'], type='varchar', alias='emergrel2') }},
        {{ trx_json_extract('src', ['INSPFLAG'], type='varchar', alias='inspflag') }},
        {{ trx_json_extract('src', ['EMERGREL3'], type='varchar', alias='emergrel3') }},
        {{ trx_json_extract('src', ['BUDGETKEY'], type='int', alias='budgetkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['EMERGPHN2'], type='varchar', alias='emergphn2') }},
        {{ trx_json_extract('src', ['SUPR'], type='varchar', alias='supr') }},
        {{ trx_json_extract('src', ['BNFTRATE'], type='float', alias='bnftrate') }},
        {{ trx_json_extract('src', ['EMERGNAME1'], type='varchar', alias='emergname1') }},
        {{ trx_json_extract('src', ['RATE'], type='float', alias='rate') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['EMPID'], type='varchar', alias='empid') }},
        {{ trx_json_extract('src', ['CONTACTKEY'], type='int', alias='contactkey') }},
        {{ trx_json_extract('src', ['EMERGNAME3'], type='varchar', alias='emergname3') }},
        {{ trx_json_extract('src', ['SECT'], type='varchar', alias='sect') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['SUPRFLAG'], type='varchar', alias='suprflag') }},
        {{ trx_json_extract('src', ['EMERGPHN1'], type='varchar', alias='emergphn1') }},
        {{ trx_json_extract('src', ['PINAUTHCODE'], type='varchar', alias='pinauthcode') }},
        {{ trx_json_extract('src', ['DEPT'], type='varchar', alias='dept') }},
        {{ trx_json_extract('src', ['EMERGPHN3'], type='varchar', alias='emergphn3') }},
        {{ trx_json_extract('src', ['EMERGNAME2'], type='varchar', alias='emergname2') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_resources_employee') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['empid']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
