{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table RESOURCES_RATETABLE.CALCULATIONTABLE on 2021-07-09T15:16:59.294',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FORMULALAST'], type='varchar', alias='formulalast') }},
        {{ trx_json_extract('src', ['CALCULATIONTABLEKEY'], type='int', alias='calculationtablekey') }},
        {{ trx_json_extract('src', ['PRORATED'], type='varchar', alias='prorated') }},
        {{ trx_json_extract('src', ['FORMULANAME'], type='varchar', alias='formulaname') }},
        {{ trx_json_extract('src', ['MAXIMUMUSED'], type='varchar', alias='maximumused') }},
        {{ trx_json_extract('src', ['USAGEDAYS'], type='int', alias='usagedays') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['MAXIMUMCHARGE'], type='float', alias='maximumcharge') }},
        {{ trx_json_extract('src', ['CYCLEDAYS'], type='int', alias='cycledays') }},
        {{ trx_json_extract('src', ['MINIMUMCHARGE'], type='float', alias='minimumcharge') }},
        {{ trx_json_extract('src', ['USEFORPRORATING'], type='int', alias='useforprorating') }},
        {{ trx_json_extract('src', ['FORMULAUSED'], type='varchar', alias='formulaused') }},
        {{ trx_json_extract('src', ['RATETABLESETUPKEY'], type='int', alias='ratetablesetupkey') }},
        {{ trx_json_extract('src', ['MINIMUMUSED'], type='varchar', alias='minimumused') }},
        {{ trx_json_extract('src', ['USEOVERAGE'], type='varchar', alias='useoverage') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['FORMULAOUTPUT'], type='float', alias='formulaoutput') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['FORMULAINPUT'], type='float', alias='formulainput') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_resources_ratetable_calculationtable') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['calculationtablekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
