{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WORKMANAGEMENT.ACTDEFN on 2022-03-03T11:38:41.741',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ALLOWEXCHANGEFLAG'], type='varchar', alias='allowexchangeflag') }},
        {{ trx_json_extract('src', ['ACTIVITYCOST'], type='float', alias='activitycost') }},
        {{ trx_json_extract('src', ['APPROVALTYPE'], type='int', alias='approvaltype') }},
        {{ trx_json_extract('src', ['PORTALDESCRIPTION'], type='varchar', alias='portaldescription') }},
        {{ trx_json_extract('src', ['ADPUOM'], type='varchar', alias='adpuom') }},
        {{ trx_json_extract('src', ['ADP'], type='float', alias='adp') }},
        {{ trx_json_extract('src', ['ACTKEY'], type='int', alias='actkey') }},
        {{ trx_json_extract('src', ['UPDATEDINDEXES'], type='varchar', alias='updatedindexes') }},
        {{ trx_json_extract('src', ['ASSVALTYPE'], type='varchar', alias='assvaltype') }},
        {{ trx_json_extract('src', ['DUEDATEFIXEDFLAG'], type='varchar', alias='duedatefixedflag') }},
        {{ trx_json_extract('src', ['UNITCOST'], type='float', alias='unitcost') }},
        {{ trx_json_extract('src', ['UCUOM'], type='varchar', alias='ucuom') }},
        {{ trx_json_extract('src', ['VALUATIONTYPEFORMULAKEY'], type='int', alias='valuationtypeformulakey') }},
        {{ trx_json_extract('src', ['SWU'], type='float', alias='swu') }},
        {{ trx_json_extract('src', ['CATEGORY'], type='int', alias='category') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ACTDESC'], type='varchar', alias='actdesc') }},
        {{ trx_json_extract('src', ['DETAILPAGE'], type='varchar', alias='detailpage') }},
        {{ trx_json_extract('src', ['POTSERVREQ'], type='varchar', alias='potservreq') }},
        {{ trx_json_extract('src', ['ALLOWREMOVALFLAG'], type='varchar', alias='allowremovalflag') }},
        {{ trx_json_extract('src', ['APPWO'], type='float', alias='appwo') }},
        {{ trx_json_extract('src', ['ACTTYPE'], type='varchar', alias='acttype') }},
        {{ trx_json_extract('src', ['SUSPDAYS'], type='int', alias='suspdays') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['SHOWINPORTAL'], type='varchar', alias='showinportal') }},
        {{ trx_json_extract('src', ['STANDARDWORKORDERKEY'], type='int', alias='standardworkorderkey') }},
        {{ trx_json_extract('src', ['DUEDATESOURCE'], type='int', alias='duedatesource') }},
        {{ trx_json_extract('src', ['ALLOWSPOTINSPECTIONS'], type='varchar', alias='allowspotinspections') }},
        {{ trx_json_extract('src', ['ALLOWINSTALLFLAG'], type='varchar', alias='allowinstallflag') }},
        {{ trx_json_extract('src', ['WORKDAYSONLY'], type='varchar', alias='workdaysonly') }},
        {{ trx_json_extract('src', ['OUTOFSERV'], type='varchar', alias='outofserv') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ISPUBLIC'], type='varchar', alias='ispublic') }},
        {{ trx_json_extract('src', ['SHOWUSAGEDETAILS'], type='varchar', alias='showusagedetails') }},
        {{ trx_json_extract('src', ['ACTCODE'], type='varchar', alias='actcode') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['COMPFLAG'], type='varchar', alias='compflag') }},
        {{ trx_json_extract('src', ['SUSPHRS'], type='int', alias='susphrs') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_workmanagement_actdefn') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['actkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
