{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WORKMANAGEMENT.TASKDEFN on 2022-01-07T14:05:00.467',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TASKCODE'], type='varchar', alias='taskcode') }},
        {{ trx_json_extract('src', ['MINUTES'], type='int', alias='minutes') }},
        {{ trx_json_extract('src', ['PARENTACTIVITY'], type='int', alias='parentactivity') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['DAYS'], type='int', alias='days') }},
        {{ trx_json_extract('src', ['INDEXNO'], type='int', alias='indexno') }},
        {{ trx_json_extract('src', ['TASKDESC'], type='varchar', alias='taskdesc') }},
        {{ trx_json_extract('src', ['EXPDATE'], type='timestamp_ntz', alias='expdate') }},
        {{ trx_json_extract('src', ['HOURS'], type='int', alias='hours') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PROBABILITYOFUSE'], type='float', alias='probabilityofuse') }},
        {{ trx_json_extract('src', ['FIXEDCOSTFLAG'], type='varchar', alias='fixedcostflag') }},
        {{ trx_json_extract('src', ['TASKKEY'], type='int', alias='taskkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_workmanagement_taskdefn') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['taskkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
