{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WORKMANAGEMENT.COSTLABR on 2022-01-07T14:04:48.676',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CHRGDTTM'], type='timestamp_ntz', alias='chrgdttm') }},
        {{ trx_json_extract('src', ['RATEADD'], type='float', alias='rateadd') }},
        {{ trx_json_extract('src', ['SRC'], type='varchar', alias='src') }},
        {{ trx_json_extract('src', ['LEAVE'], type='varchar', alias='leave') }},
        {{ trx_json_extract('src', ['PAYTYPE'], type='varchar', alias='paytype') }},
        {{ trx_json_extract('src', ['BNFTMULT'], type='float', alias='bnftmult') }},
        {{ trx_json_extract('src', ['COMMENTS'], type='varchar', alias='comments') }},
        {{ trx_json_extract('src', ['COSTKEY'], type='int', alias='costkey') }},
        {{ trx_json_extract('src', ['HISTKEY'], type='int', alias='histkey') }},
        {{ trx_json_extract('src', ['CHRGDTTMTO'], type='timestamp_ntz', alias='chrgdttmto') }},
        {{ trx_json_extract('src', ['TOTCOST'], type='float', alias='totcost') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['BNFTRATE'], type='float', alias='bnftrate') }},
        {{ trx_json_extract('src', ['DSTBGTNO'], type='varchar', alias='dstbgtno') }},
        {{ trx_json_extract('src', ['HRLYADJ'], type='float', alias='hrlyadj') }},
        {{ trx_json_extract('src', ['USAGE'], type='float', alias='usage') }},
        {{ trx_json_extract('src', ['RATE'], type='float', alias='rate') }},
        {{ trx_json_extract('src', ['SRCBGTKEY'], type='int', alias='srcbgtkey') }},
        {{ trx_json_extract('src', ['EMPID'], type='varchar', alias='empid') }},
        {{ trx_json_extract('src', ['LABOR'], type='varchar', alias='labor') }},
        {{ trx_json_extract('src', ['DSTBGTKEY'], type='int', alias='dstbgtkey') }},
        {{ trx_json_extract('src', ['SRCBGTNO'], type='varchar', alias='srcbgtno') }},
        {{ trx_json_extract('src', ['TODTTM'], type='timestamp_ntz', alias='todttm') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['TASKKEY'], type='int', alias='taskkey') }},
        {{ trx_json_extract('src', ['RATEMULT'], type='float', alias='ratemult') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['JOBCLASS'], type='varchar', alias='jobclass') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_workmanagement_costlabr') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['costkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
