{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WORKMANAGEMENT.HISTLOG on 2022-01-07T14:04:54.406',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['HISTKEY'], type='int', alias='histkey') }},
        {{ trx_json_extract('src', ['LOGTODTTM'], type='timestamp_ntz', alias='logtodttm') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['HISTLOGKEY'], type='int', alias='histlogkey') }},
        {{ trx_json_extract('src', ['LOGBY'], type='varchar', alias='logby') }},
        {{ trx_json_extract('src', ['LOGFRDTTM'], type='timestamp_ntz', alias='logfrdttm') }},
        {{ trx_json_extract('src', ['LOGTYPE'], type='varchar', alias='logtype') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_workmanagement_histlog') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['histlogkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
