{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLASSETSSTORM.XSTORMNODE on 2024-10-03T13:42:00.315',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['WARRANTYEND'], type='timestamp_ntz', alias='warrantyend') }},
        {{ trx_json_extract('src', ['COSTCENTRE'], type='varchar', alias='costcentre') }},
        {{ trx_json_extract('src', ['SAFETYCRITICAL'], type='varchar', alias='safetycritical') }},
        {{ trx_json_extract('src', ['RELSTATUS'], type='varchar', alias='relstatus') }},
        {{ trx_json_extract('src', ['WARRANTYSTART'], type='timestamp_ntz', alias='warrantystart') }},
        {{ trx_json_extract('src', ['CRITICALITY'], type='varchar', alias='criticality') }},
        {{ trx_json_extract('src', ['RELGEOSP'], type='varchar', alias='relgeosp') }},
        {{ trx_json_extract('src', ['ACCELDEPREC'], type='varchar', alias='acceldeprec') }},
        {{ trx_json_extract('src', ['BUSINESSAREA'], type='varchar', alias='businessarea') }},
        {{ trx_json_extract('src', ['ACQTYPE'], type='varchar', alias='acqtype') }},
        {{ trx_json_extract('src', ['ZONECATCHMENT'], type='varchar', alias='zonecatchment') }},
        {{ trx_json_extract('src', ['RELDEPTH'], type='varchar', alias='reldepth') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['LINKEDASSET'], type='varchar', alias='linkedasset') }},
        {{ trx_json_extract('src', ['DISPOSALDESC'], type='varchar', alias='disposaldesc') }},
        {{ trx_json_extract('src', ['RELDIA'], type='varchar', alias='reldia') }},
        {{ trx_json_extract('src', ['XSTORMNODEKEY'], type='int', alias='xstormnodekey') }},
        {{ trx_json_extract('src', ['MODELNO'], type='varchar', alias='modelno') }},
        {{ trx_json_extract('src', ['CONFINEDSPACE'], type='varchar', alias='confinedspace') }},
        {{ trx_json_extract('src', ['MAKE'], type='varchar', alias='make') }},
        {{ trx_json_extract('src', ['RELOWN'], type='varchar', alias='relown') }},
        {{ trx_json_extract('src', ['RELMATL'], type='varchar', alias='relmatl') }},
        {{ trx_json_extract('src', ['PROJECTWISE'], type='varchar', alias='projectwise') }},
        {{ trx_json_extract('src', ['FORDISPOSAL'], type='varchar', alias='fordisposal') }},
        {{ trx_json_extract('src', ['DRAWINGNOREF'], type='varchar', alias='drawingnoref') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['RELDATE'], type='varchar', alias='reldate') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['ACCELDEPRECDESC'], type='varchar', alias='acceldeprecdesc') }},
        {{ trx_json_extract('src', ['PROJECTNO'], type='varchar', alias='projectno') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['DRAWINGNO'], type='varchar', alias='drawingno') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslassetsstorm_xstormnode') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xstormnodekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
