{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLASSETS.ASSLOCDELETED on 2021-09-28T14:04:56.004',
    tags=['auto-generated', 'ips', 'stage5']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['INSTDT'], type='timestamp_ntz', alias='instdt') }},
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['ASSLOCDELETEDKEY'], type='int', alias='asslocdeletedkey') }},
        {{ trx_json_extract('src', ['ORIGADDDTTM'], type='timestamp_ntz', alias='origadddttm') }},
        {{ trx_json_extract('src', ['ORIGMODBY'], type='varchar', alias='origmodby') }},
        {{ trx_json_extract('src', ['ASSLOCKEY'], type='int', alias='asslockey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['REMDT'], type='timestamp_ntz', alias='remdt') }},
        {{ trx_json_extract('src', ['ORIGMODDTTM'], type='timestamp_ntz', alias='origmoddttm') }},
        {{ trx_json_extract('src', ['ORIGADDBY'], type='varchar', alias='origaddby') }},
        {{ trx_json_extract('src', ['COMPKEY'], type='int', alias='compkey') }},
        {{ trx_json_extract('src', ['POSITION'], type='int', alias='position') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslassets_asslocdeleted') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['asslocdeletedkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
