{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLBILLING.SENDBILLTODELETED on 2021-11-03T15:20:17.331',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['DPC'], type='varchar', alias='dpc') }},
        {{ trx_json_extract('src', ['COUNTRY'], type='varchar', alias='country') }},
        {{ trx_json_extract('src', ['CASSBARCODE'], type='int', alias='cassbarcode') }},
        {{ trx_json_extract('src', ['ORIGMODBY'], type='varchar', alias='origmodby') }},
        {{ trx_json_extract('src', ['ORIGADDDTTM'], type='timestamp_ntz', alias='origadddttm') }},
        {{ trx_json_extract('src', ['STATE'], type='varchar', alias='state') }},
        {{ trx_json_extract('src', ['SEASCOUNTRY'], type='varchar', alias='seascountry') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SEASADDR1'], type='varchar', alias='seasaddr1') }},
        {{ trx_json_extract('src', ['ADDR2'], type='varchar', alias='addr2') }},
        {{ trx_json_extract('src', ['CITY'], type='varchar', alias='city') }},
        {{ trx_json_extract('src', ['SENDTOLINE1'], type='varchar', alias='sendtoline1') }},
        {{ trx_json_extract('src', ['EFFECTIVEDATE'], type='timestamp_ntz', alias='effectivedate') }},
        {{ trx_json_extract('src', ['CARRT'], type='varchar', alias='carrt') }},
        {{ trx_json_extract('src', ['SEASTODATE'], type='timestamp_ntz', alias='seastodate') }},
        {{ trx_json_extract('src', ['SEASZIP'], type='varchar', alias='seaszip') }},
        {{ trx_json_extract('src', ['ZIP'], type='varchar', alias='zip') }},
        {{ trx_json_extract('src', ['SENDBILLTODELETEDKEY'], type='int', alias='sendbilltodeletedkey') }},
        {{ trx_json_extract('src', ['DELIVERYOPTION'], type='int', alias='deliveryoption') }},
        {{ trx_json_extract('src', ['SEASCASSVER'], type='int', alias='seascassver') }},
        {{ trx_json_extract('src', ['SENDTOLINE2'], type='varchar', alias='sendtoline2') }},
        {{ trx_json_extract('src', ['LOT'], type='varchar', alias='lot') }},
        {{ trx_json_extract('src', ['ADDR1'], type='varchar', alias='addr1') }},
        {{ trx_json_extract('src', ['SEASCITY'], type='varchar', alias='seascity') }},
        {{ trx_json_extract('src', ['SEASADDR2'], type='varchar', alias='seasaddr2') }},
        {{ trx_json_extract('src', ['CASSVER'], type='int', alias='cassver') }},
        {{ trx_json_extract('src', ['ADDRESSCONTACTKEY'], type='int', alias='addresscontactkey') }},
        {{ trx_json_extract('src', ['ORIGMODDTTM'], type='timestamp_ntz', alias='origmoddttm') }},
        {{ trx_json_extract('src', ['SEASDPC'], type='varchar', alias='seasdpc') }},
        {{ trx_json_extract('src', ['SENDBILLTOKEY'], type='int', alias='sendbilltokey') }},
        {{ trx_json_extract('src', ['ORIGADDBY'], type='varchar', alias='origaddby') }},
        {{ trx_json_extract('src', ['SEASSTATE'], type='varchar', alias='seasstate') }},
        {{ trx_json_extract('src', ['SEASFROMDATE'], type='timestamp_ntz', alias='seasfromdate') }},
        {{ trx_json_extract('src', ['SEASLOT'], type='varchar', alias='seaslot') }},
        {{ trx_json_extract('src', ['SEASCARRT'], type='varchar', alias='seascarrt') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DELETED'], type='boolean', alias='deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslbilling_sendbilltodeleted') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['sendbilltodeletedkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
