{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCRM.XREADINGREVIEWSRDETAILS on 2024-10-10T10:04:15.463',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['MARKASANOMALY'], type='varchar', alias='markasanomaly') }},
        {{ trx_json_extract('src', ['TEST'], type='varchar', alias='test') }},
        {{ trx_json_extract('src', ['PHOTOREQUIRED'], type='varchar', alias='photorequired') }},
        {{ trx_json_extract('src', ['WATERMETER'], type='int', alias='watermeter') }},
        {{ trx_json_extract('src', ['MARKASNOREAD'], type='varchar', alias='markasnoread') }},
        {{ trx_json_extract('src', ['READINGKEY'], type='int', alias='readingkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['MARKASREADYTOBILL'], type='varchar', alias='markasreadytobill') }},
        {{ trx_json_extract('src', ['CHECKREADISCHARGEABLE'], type='varchar', alias='checkreadischargeable') }},
        {{ trx_json_extract('src', ['ISCHECKREADREQUEST'], type='varchar', alias='ischeckreadrequest') }},
        {{ trx_json_extract('src', ['SERVNO'], type='int', alias='servno') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['XREADINGREVIEWSRDETAILSKEY'], type='int', alias='xreadingreviewsrdetailskey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcrm_xreadingreviewsrdetails') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xreadingreviewsrdetailskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
