{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRPROJ.XAPPLICANTDP on 2022-03-03T11:36:51.901',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['XAPPLICANTDPKEY'], type='int', alias='xapplicantdpkey') }},
        {{ trx_json_extract('src', ['POSTALCODE'], type='varchar', alias='postalcode') }},
        {{ trx_json_extract('src', ['REFERENCENUMBER'], type='varchar', alias='referencenumber') }},
        {{ trx_json_extract('src', ['COMPANYNAME'], type='varchar', alias='companyname') }},
        {{ trx_json_extract('src', ['STREETNUMBER'], type='varchar', alias='streetnumber') }},
        {{ trx_json_extract('src', ['SAMEASAPPLICANT'], type='varchar', alias='sameasapplicant') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['EMAIL'], type='varchar', alias='email') }},
        {{ trx_json_extract('src', ['CITY'], type='varchar', alias='city') }},
        {{ trx_json_extract('src', ['MOBILENUMBER'], type='varchar', alias='mobilenumber') }},
        {{ trx_json_extract('src', ['LASTNAME'], type='varchar', alias='lastname') }},
        {{ trx_json_extract('src', ['CPE'], type='varchar', alias='cpe') }},
        {{ trx_json_extract('src', ['CAPACITY'], type='varchar', alias='capacity') }},
        {{ trx_json_extract('src', ['TITLE'], type='varchar', alias='title') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['FIRSTNAME'], type='varchar', alias='firstname') }},
        {{ trx_json_extract('src', ['STREETNAME'], type='varchar', alias='streetname') }},
        {{ trx_json_extract('src', ['SUBURB'], type='varchar', alias='suburb') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PHONENUMBER'], type='varchar', alias='phonenumber') }},
        {{ trx_json_extract('src', ['APPROJAPPLDTLKEY'], type='int', alias='approjappldtlkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['CPENGNUMBER'], type='varchar', alias='cpengnumber') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrproj_xapplicantdp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xapplicantdpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
