{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRBUILD.XBUILDFEESGD on 2022-03-03T11:34:29.910',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FEESNONDOMCODE'], type='varchar', alias='feesnondomcode') }},
        {{ trx_json_extract('src', ['FEESLOWPRESSCODE'], type='varchar', alias='feeslowpresscode') }},
        {{ trx_json_extract('src', ['FEEVALUE'], type='float', alias='feevalue') }},
        {{ trx_json_extract('src', ['FEESDOMCODE'], type='varchar', alias='feesdomcode') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['XBUILDFEESDPKEY'], type='int', alias='xbuildfeesdpkey') }},
        {{ trx_json_extract('src', ['XBUILDFEESGDKEY'], type='int', alias='xbuildfeesgdkey') }},
        {{ trx_json_extract('src', ['FEEQUANTITY'], type='float', alias='feequantity') }},
        {{ trx_json_extract('src', ['FEESWOCODE'], type='varchar', alias='feeswocode') }},
        {{ trx_json_extract('src', ['FEEUOM'], type='varchar', alias='feeuom') }},
        {{ trx_json_extract('src', ['CUSTOMERREFERENCE'], type='varchar', alias='customerreference') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['FEECODE'], type='varchar', alias='feecode') }},
        {{ trx_json_extract('src', ['FEEAMOUNT'], type='float', alias='feeamount') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrbuild_xbuildfeesgd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xbuildfeesgdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
