{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRPLAN.XPLANDPTASKDETAILSGD on 2022-03-03T11:35:51.810',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['XPLANDPTASKDETAILSGDKEY'], type='int', alias='xplandptaskdetailsgdkey') }},
        {{ trx_json_extract('src', ['DUEDATE'], type='timestamp_ntz', alias='duedate') }},
        {{ trx_json_extract('src', ['REVIEWTYPE'], type='varchar', alias='reviewtype') }},
        {{ trx_json_extract('src', ['TASKASSIGNEDTO'], type='varchar', alias='taskassignedto') }},
        {{ trx_json_extract('src', ['SCHEDULEDDATE'], type='timestamp_ntz', alias='scheduleddate') }},
        {{ trx_json_extract('src', ['XPLANDPACTIONLISTKEY'], type='int', alias='xplandpactionlistkey') }},
        {{ trx_json_extract('src', ['REVIEWID'], type='varchar', alias='reviewid') }},
        {{ trx_json_extract('src', ['NOTES'], type='varchar', alias='notes') }},
        {{ trx_json_extract('src', ['REVIEWCODE'], type='varchar', alias='reviewcode') }},
        {{ trx_json_extract('src', ['ACTIONID'], type='int', alias='actionid') }},
        {{ trx_json_extract('src', ['DETAILS'], type='varchar', alias='details') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['TASKASSIGNEDT1'], type='varchar', alias='taskassignedt1') }},
        {{ trx_json_extract('src', ['COMPLETEDDATE'], type='timestamp_ntz', alias='completeddate') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrplan_xplandptaskdetailsgd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xplandptaskdetailsgdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
