{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRBUILD.XAPPLICANTDP on 2022-03-03T11:34:29.294',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['XAPPLICANTDPKEY'], type='int', alias='xapplicantdpkey') }},
        {{ trx_json_extract('src', ['CONAME'], type='varchar', alias='coname') }},
        {{ trx_json_extract('src', ['ONSITECITY'], type='varchar', alias='onsitecity') }},
        {{ trx_json_extract('src', ['ONSITEMOBILE'], type='varchar', alias='onsitemobile') }},
        {{ trx_json_extract('src', ['ONSITEEMAILADDRESS'], type='varchar', alias='onsiteemailaddress') }},
        {{ trx_json_extract('src', ['ONSITETITLE'], type='varchar', alias='onsitetitle') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ONSITEFIRSTNAME'], type='varchar', alias='onsitefirstname') }},
        {{ trx_json_extract('src', ['EMAIL'], type='varchar', alias='email') }},
        {{ trx_json_extract('src', ['CITY'], type='varchar', alias='city') }},
        {{ trx_json_extract('src', ['ONSITESUBURB'], type='varchar', alias='onsitesuburb') }},
        {{ trx_json_extract('src', ['ZIP'], type='varchar', alias='zip') }},
        {{ trx_json_extract('src', ['APBLDGAPPLDTLKEY'], type='int', alias='apbldgappldtlkey') }},
        {{ trx_json_extract('src', ['ONSITEPOSTALCODE'], type='varchar', alias='onsitepostalcode') }},
        {{ trx_json_extract('src', ['ADDR1'], type='varchar', alias='addr1') }},
        {{ trx_json_extract('src', ['ONSITEADDRESSLINE1'], type='varchar', alias='onsiteaddressline1') }},
        {{ trx_json_extract('src', ['LASTNAME'], type='varchar', alias='lastname') }},
        {{ trx_json_extract('src', ['CAPACITY'], type='varchar', alias='capacity') }},
        {{ trx_json_extract('src', ['ONSITECOMPANYNAME'], type='varchar', alias='onsitecompanyname') }},
        {{ trx_json_extract('src', ['TITLE'], type='varchar', alias='title') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['FIRSTNAME'], type='varchar', alias='firstname') }},
        {{ trx_json_extract('src', ['SUBURB'], type='varchar', alias='suburb') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MOBILE'], type='varchar', alias='mobile') }},
        {{ trx_json_extract('src', ['PHONENUMBER'], type='varchar', alias='phonenumber') }},
        {{ trx_json_extract('src', ['ONSITELASTNAME'], type='varchar', alias='onsitelastname') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['ONSITEPHONENUMBER'], type='varchar', alias='onsitephonenumber') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrbuild_xapplicantdp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xapplicantdpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
