{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCRM.XMETERREVIEWGD on 2024-10-10T10:04:15.229',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['FIELDNOTES'], type='varchar', alias='fieldnotes') }},
        {{ trx_json_extract('src', ['CURRENTREAD'], type='float', alias='currentread') }},
        {{ trx_json_extract('src', ['LASTYEARDAILYAVG'], type='float', alias='lastyeardailyavg') }},
        {{ trx_json_extract('src', ['COMPAREREASON'], type='varchar', alias='comparereason') }},
        {{ trx_json_extract('src', ['PREVIOUSREAD'], type='float', alias='previousread') }},
        {{ trx_json_extract('src', ['READINGIMPORTACTIVITY'], type='int', alias='readingimportactivity') }},
        {{ trx_json_extract('src', ['ASSET'], type='int', alias='asset') }},
        {{ trx_json_extract('src', ['XMETERREVIEWGDKEY'], type='int', alias='xmeterreviewgdkey') }},
        {{ trx_json_extract('src', ['EXCEPTION'], type='varchar', alias='exception') }},
        {{ trx_json_extract('src', ['COMPAREOPTION'], type='int', alias='compareoption') }},
        {{ trx_json_extract('src', ['CURRENTREADDATE'], type='timestamp_ntz', alias='currentreaddate') }},
        {{ trx_json_extract('src', ['XMETERREVIEWDP'], type='int', alias='xmeterreviewdp') }},
        {{ trx_json_extract('src', ['READINGKEY'], type='int', alias='readingkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['READINGCYCLE'], type='varchar', alias='readingcycle') }},
        {{ trx_json_extract('src', ['CURRENTBILLABLE'], type='float', alias='currentbillable') }},
        {{ trx_json_extract('src', ['COMPAREUSAGE'], type='float', alias='compareusage') }},
        {{ trx_json_extract('src', ['LOW'], type='float', alias='low') }},
        {{ trx_json_extract('src', ['HIGH'], type='float', alias='high') }},
        {{ trx_json_extract('src', ['LASTYEARREAD'], type='float', alias='lastyearread') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DAILYAVERAGE'], type='float', alias='dailyaverage') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['READERCODE'], type='varchar', alias='readercode') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcrm_xmeterreviewgd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xmeterreviewgdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
