{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRBUILD.XBUILDIGCDP on 2023-10-26T15:06:58.302',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['XBUILDIGCDPKEY'], type='int', alias='xbuildigcdpkey') }},
        {{ trx_json_extract('src', ['STAGE'], type='varchar', alias='stage') }},
        {{ trx_json_extract('src', ['NEIGHBOURHOOD'], type='varchar', alias='neighbourhood') }},
        {{ trx_json_extract('src', ['DP'], type='varchar', alias='dp') }},
        {{ trx_json_extract('src', ['TENURE'], type='varchar', alias='tenure') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['FLOORAREALT65'], type='varchar', alias='floorarealt65') }},
        {{ trx_json_extract('src', ['APBLDGAPPLDTLKEY'], type='int', alias='apbldgappldtlkey') }},
        {{ trx_json_extract('src', ['LOT'], type='varchar', alias='lot') }},
        {{ trx_json_extract('src', ['SUPERLOT'], type='varchar', alias='superlot') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrbuild_xbuildigcdp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xbuildigcdpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
