{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRBUILD.XMDADDRESSGD on 2022-03-03T11:34:48.910',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['STTYPE'], type='varchar', alias='sttype') }},
        {{ trx_json_extract('src', ['DP'], type='varchar', alias='dp') }},
        {{ trx_json_extract('src', ['UNIT'], type='varchar', alias='unit') }},
        {{ trx_json_extract('src', ['FLOORAREALT65M2'], type='varchar', alias='floorarealt65m2') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CT'], type='varchar', alias='ct') }},
        {{ trx_json_extract('src', ['FLOORAREALT65'], type='varchar', alias='floorarealt65') }},
        {{ trx_json_extract('src', ['LOT'], type='varchar', alias='lot') }},
        {{ trx_json_extract('src', ['POSTCODE'], type='varchar', alias='postcode') }},
        {{ trx_json_extract('src', ['CUSTOMERREFERENCE'], type='varchar', alias='customerreference') }},
        {{ trx_json_extract('src', ['HOUSENO'], type='varchar', alias='houseno') }},
        {{ trx_json_extract('src', ['XBUILDMULCONNECTIONSKEY'], type='int', alias='xbuildmulconnectionskey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['STREETNAME'], type='varchar', alias='streetname') }},
        {{ trx_json_extract('src', ['SUBURB'], type='varchar', alias='suburb') }},
        {{ trx_json_extract('src', ['XMDADDRESSGDKEY'], type='int', alias='xmdaddressgdkey') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DEVCONTPAID'], type='varchar', alias='devcontpaid') }},
        {{ trx_json_extract('src', ['STREETTYPE'], type='varchar', alias='streettype') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrbuild_xmdaddressgd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xmdaddressgdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
