{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRBUILD.XBUILDCONTCOSTGD on 2022-03-03T11:34:25.529',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APPLICATIONNO'], type='varchar', alias='applicationno') }},
        {{ trx_json_extract('src', ['CHARGEITEM'], type='varchar', alias='chargeitem') }},
        {{ trx_json_extract('src', ['CHARGEDATE'], type='timestamp_ntz', alias='chargedate') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CHARGEITME'], type='varchar', alias='chargeitme') }},
        {{ trx_json_extract('src', ['USAGE'], type='float', alias='usage') }},
        {{ trx_json_extract('src', ['XBUILDCONTCOSTGDKEY'], type='int', alias='xbuildcontcostgdkey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['COST'], type='float', alias='cost') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['XBUILDCONTCOSTDPKEY'], type='int', alias='xbuildcontcostdpkey') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrbuild_xbuildcontcostgd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xbuildcontcostgdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
