{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDR.CDRBILLOUTPUTLINEITEMEX on 2023-03-07T04:53:55.863',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['TOTALAMOUNT'], type='float', alias='totalamount') }},
        {{ trx_json_extract('src', ['BILLKEY'], type='int', alias='billkey') }},
        {{ trx_json_extract('src', ['QTY'], type='float', alias='qty') }},
        {{ trx_json_extract('src', ['CDRBILLOUTPUTLINEITEMEXKEY'], type='int', alias='cdrbilloutputlineitemexkey') }},
        {{ trx_json_extract('src', ['FEEDESC'], type='varchar', alias='feedesc') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['VALUE'], type='float', alias='value') }},
        {{ trx_json_extract('src', ['LINEITEMKEY'], type='int', alias='lineitemkey') }},
        {{ trx_json_extract('src', ['ACCOUNTNUMBER'], type='varchar', alias='accountnumber') }},
        {{ trx_json_extract('src', ['LINEITEM'], type='varchar', alias='lineitem') }},
        {{ trx_json_extract('src', ['WAIVED'], type='varchar', alias='waived') }},
        {{ trx_json_extract('src', ['FEETYPEKEY'], type='int', alias='feetypekey') }},
        {{ trx_json_extract('src', ['FEEREFERENCE'], type='varchar', alias='feereference') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['FEECODE'], type='varchar', alias='feecode') }},
        {{ trx_json_extract('src', ['LINEITEMDESC'], type='varchar', alias='lineitemdesc') }},
        {{ trx_json_extract('src', ['QUANTITY'], type='float', alias='quantity') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['BILLRUNNUMBER'], type='int', alias='billrunnumber') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdr_cdrbilloutputlineitemex') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['cdrbilloutputlineitemexkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
