{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRPLAN.XPLANDPPROPINTAKE on 2022-03-03T11:35:49.817',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['PLANAPPLDETAILKEY'], type='int', alias='planappldetailkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PROPOSALNAME'], type='varchar', alias='proposalname') }},
        {{ trx_json_extract('src', ['XPLANDPPROPINTAKEKEY'], type='int', alias='xplandppropintakekey') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['DATEOFAPPLICATION'], type='timestamp_ntz', alias='dateofapplication') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrplan_xplandppropintake') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xplandppropintakekey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
