{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRBUILD.XCDRINITIALREVIEWDP on 2022-03-03T11:34:20.932',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CRITICALLINES'], type='varchar', alias='criticallines') }},
        {{ trx_json_extract('src', ['METERBOXTYPE'], type='varchar', alias='meterboxtype') }},
        {{ trx_json_extract('src', ['SIZEMETER'], type='varchar', alias='sizemeter') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['WASTEWATERINSTALLREQUIRED'], type='varchar', alias='wastewaterinstallrequired') }},
        {{ trx_json_extract('src', ['WATERMAINLOC'], type='varchar', alias='watermainloc') }},
        {{ trx_json_extract('src', ['WATERMAINSIZE'], type='int', alias='watermainsize') }},
        {{ trx_json_extract('src', ['PIPEMATERIAL'], type='varchar', alias='pipematerial') }},
        {{ trx_json_extract('src', ['ARBORIST'], type='varchar', alias='arborist') }},
        {{ trx_json_extract('src', ['WASTEWATERINSTALLTYPE'], type='varchar', alias='wastewaterinstalltype') }},
        {{ trx_json_extract('src', ['XCDRINITIALREVIEWDPKEY'], type='int', alias='xcdrinitialreviewdpkey') }},
        {{ trx_json_extract('src', ['TMP'], type='varchar', alias='tmp') }},
        {{ trx_json_extract('src', ['VACPITNO'], type='varchar', alias='vacpitno') }},
        {{ trx_json_extract('src', ['BACKFLOWTYPE'], type='varchar', alias='backflowtype') }},
        {{ trx_json_extract('src', ['WATERMAINMATERIAL'], type='varchar', alias='watermainmaterial') }},
        {{ trx_json_extract('src', ['SERVICELEAD'], type='varchar', alias='servicelead') }},
        {{ trx_json_extract('src', ['WATERMAINLOCATION'], type='varchar', alias='watermainlocation') }},
        {{ trx_json_extract('src', ['APBLDGREVDTLKEY'], type='int', alias='apbldgrevdtlkey') }},
        {{ trx_json_extract('src', ['METERBOXSIZE'], type='varchar', alias='meterboxsize') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MAINLOC'], type='varchar', alias='mainloc') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['DRAWINGNO'], type='varchar', alias='drawingno') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrbuild_xcdrinitialreviewdp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xcdrinitialreviewdpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
