{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRPROJ.XPROJEPARVWDP on 2022-03-03T11:36:31.723',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ENGEPAASSESS'], type='varchar', alias='engepaassess') }},
        {{ trx_json_extract('src', ['FINALWALKOVER'], type='varchar', alias='finalwalkover') }},
        {{ trx_json_extract('src', ['AUDITREQ'], type='varchar', alias='auditreq') }},
        {{ trx_json_extract('src', ['PRECONONSITEREASON'], type='varchar', alias='precononsitereason') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['PRECONONSITE'], type='varchar', alias='precononsite') }},
        {{ trx_json_extract('src', ['APPROJREVDTLKEY'], type='int', alias='approjrevdtlkey') }},
        {{ trx_json_extract('src', ['AUDITREQREASON'], type='varchar', alias='auditreqreason') }},
        {{ trx_json_extract('src', ['XPROJEPARVWDPKEY'], type='int', alias='xprojeparvwdpkey') }},
        {{ trx_json_extract('src', ['FINALWALKOVERREASON'], type='varchar', alias='finalwalkoverreason') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrproj_xprojeparvwdp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xprojeparvwdpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
