{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRPLAN.XPLANDPACTIONLISTGD on 2022-03-03T11:35:49.584',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['CREATEDATE'], type='timestamp_ntz', alias='createdate') }},
        {{ trx_json_extract('src', ['DUEDATE'], type='timestamp_ntz', alias='duedate') }},
        {{ trx_json_extract('src', ['XPLANDPACTIONLISTKEY'], type='int', alias='xplandpactionlistkey') }},
        {{ trx_json_extract('src', ['ACTIONOWNER'], type='varchar', alias='actionowner') }},
        {{ trx_json_extract('src', ['REVIEWID'], type='int', alias='reviewid') }},
        {{ trx_json_extract('src', ['ASSIGNEDTO'], type='varchar', alias='assignedto') }},
        {{ trx_json_extract('src', ['ASSIGNEDT1'], type='varchar', alias='assignedt1') }},
        {{ trx_json_extract('src', ['RESPONSIBLE'], type='varchar', alias='responsible') }},
        {{ trx_json_extract('src', ['ACTIONSTATUS'], type='varchar', alias='actionstatus') }},
        {{ trx_json_extract('src', ['ACTIONTYPE'], type='varchar', alias='actiontype') }},
        {{ trx_json_extract('src', ['DETAILS'], type='varchar', alias='details') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ACTIONNOTES'], type='varchar', alias='actionnotes') }},
        {{ trx_json_extract('src', ['COMPLETEDDATE'], type='timestamp_ntz', alias='completeddate') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['XPLANDPACTIONLISTGDKEY'], type='int', alias='xplandpactionlistgdkey') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrplan_xplandpactionlistgd') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xplandpactionlistgdkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
