{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCOMPLAINTS.COMPLAINTDETAILS on 2024-10-10T10:04:17.106',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['READING'], type='varchar', alias='reading') }},
        {{ trx_json_extract('src', ['MISREAD'], type='varchar', alias='misread') }},
        {{ trx_json_extract('src', ['CALCULATION'], type='varchar', alias='calculation') }},
        {{ trx_json_extract('src', ['ODUEACCT'], type='varchar', alias='odueacct') }},
        {{ trx_json_extract('src', ['ESTIMATE'], type='varchar', alias='estimate') }},
        {{ trx_json_extract('src', ['DISPUTE'], type='varchar', alias='dispute') }},
        {{ trx_json_extract('src', ['PRICE'], type='varchar', alias='price') }},
        {{ trx_json_extract('src', ['SPECFINAL'], type='varchar', alias='specfinal') }},
        {{ trx_json_extract('src', ['HARDSHIP'], type='varchar', alias='hardship') }},
        {{ trx_json_extract('src', ['ACCESSPROBS'], type='varchar', alias='accessprobs') }},
        {{ trx_json_extract('src', ['FLDSVC'], type='varchar', alias='fldsvc') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['COMPLAINTDETAILSKEY'], type='int', alias='complaintdetailskey') }},
        {{ trx_json_extract('src', ['CUSTDATA'], type='varchar', alias='custdata') }},
        {{ trx_json_extract('src', ['CHANGEOWN'], type='varchar', alias='changeown') }},
        {{ trx_json_extract('src', ['BILLINFO'], type='varchar', alias='billinfo') }},
        {{ trx_json_extract('src', ['WW'], type='varchar', alias='ww') }},
        {{ trx_json_extract('src', ['SERVNO'], type='int', alias='servno') }},
        {{ trx_json_extract('src', ['READER'], type='varchar', alias='reader') }},
        {{ trx_json_extract('src', ['COMMS'], type='varchar', alias='comms') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['ACCTSETUP'], type='varchar', alias='acctsetup') }},
        {{ trx_json_extract('src', ['PROCFAIL'], type='varchar', alias='procfail') }},
        {{ trx_json_extract('src', ['REFUND'], type='varchar', alias='refund') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcomplaints_complaintdetails') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['complaintdetailskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
