{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLCDRPROJ.XPROJCOMPRVWPRECONDP on 2022-03-03T11:36:29.579',
    tags=['auto-generated', 'ips', 'stage6']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TECHAUDITREQ'], type='varchar', alias='techauditreq') }},
        {{ trx_json_extract('src', ['ENGEPAASSESS'], type='varchar', alias='engepaassess') }},
        {{ trx_json_extract('src', ['TECHFINALWALKOVER'], type='varchar', alias='techfinalwalkover') }},
        {{ trx_json_extract('src', ['ENGFINALWALKOVERREASON'], type='varchar', alias='engfinalwalkoverreason') }},
        {{ trx_json_extract('src', ['ENGPRECONONSITE'], type='varchar', alias='engprecononsite') }},
        {{ trx_json_extract('src', ['ENGAUDITREQREASON'], type='varchar', alias='engauditreqreason') }},
        {{ trx_json_extract('src', ['ENGAUDITREQ'], type='varchar', alias='engauditreq') }},
        {{ trx_json_extract('src', ['ENGFINALWALKOVER'], type='varchar', alias='engfinalwalkover') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['APPROJREVDTLKEY'], type='int', alias='approjrevdtlkey') }},
        {{ trx_json_extract('src', ['ENGPRECONONSITEREASON'], type='varchar', alias='engprecononsitereason') }},
        {{ trx_json_extract('src', ['ONSITEMEETACTUALDATE'], type='timestamp_ntz', alias='onsitemeetactualdate') }},
        {{ trx_json_extract('src', ['TECHFINALWALKOVERREASON'], type='varchar', alias='techfinalwalkoverreason') }},
        {{ trx_json_extract('src', ['TECHAUDITREQREASON'], type='varchar', alias='techauditreqreason') }},
        {{ trx_json_extract('src', ['XPROJCOMPRVWPRECONDPKEY'], type='int', alias='xprojcomprvwprecondpkey') }},
        {{ trx_json_extract('src', ['TECHPRECONONSITEREASON'], type='varchar', alias='techprecononsitereason') }},
        {{ trx_json_extract('src', ['TECHPRECONONSITE'], type='varchar', alias='techprecononsite') }},
        {{ trx_json_extract('src', ['ONSITEMEETSCHEDDATE'], type='timestamp_ntz', alias='onsitemeetscheddate') }},
        {{ trx_json_extract('src', ['WASTEWATERCONNECTIONTYPE'], type='varchar', alias='wastewaterconnectiontype') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['PASSTOADVISOR'], type='varchar', alias='passtoadvisor') }},
        {{ trx_json_extract('src', ['PASSTOTECHNICIAN'], type='varchar', alias='passtotechnician') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslcdrproj_xprojcomprvwprecondp') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xprojcomprvwprecondpkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
