{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLINTERFACE.NOTIFICATIONSTAGING on 2022-03-03T11:32:53.653',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['KEYCOLUMN'], type='int', alias='keycolumn') }},
        {{ trx_json_extract('src', ['EPA'], type='varchar', alias='epa') }},
        {{ trx_json_extract('src', ['REVIEWASSIGNFULLNAME'], type='varchar', alias='reviewassignfullname') }},
        {{ trx_json_extract('src', ['REVIEWASSIGNEMAIL'], type='varchar', alias='reviewassignemail') }},
        {{ trx_json_extract('src', ['TEMPLATENAME'], type='varchar', alias='templatename') }},
        {{ trx_json_extract('src', ['REVIEWASSIGNDAYPHONE'], type='varchar', alias='reviewassigndayphone') }},
        {{ trx_json_extract('src', ['CATEGORY'], type='varchar', alias='category') }},
        {{ trx_json_extract('src', ['NOTIFICATIONSTAGINGKEY'], type='int', alias='notificationstagingkey') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['SUBJECT'], type='varchar', alias='subject') }},
        {{ trx_json_extract('src', ['FROMEMAIL'], type='varchar', alias='fromemail') }},
        {{ trx_json_extract('src', ['DOCUMENTID'], type='varchar', alias='documentid') }},
        {{ trx_json_extract('src', ['APPLICATIONTYPE'], type='varchar', alias='applicationtype') }},
        {{ trx_json_extract('src', ['CONTACTEMAILADDRESS'], type='varchar', alias='contactemailaddress') }},
        {{ trx_json_extract('src', ['REVIEWCOMPLETEFULLNAME'], type='varchar', alias='reviewcompletefullname') }},
        {{ trx_json_extract('src', ['USERTYPE'], type='varchar', alias='usertype') }},
        {{ trx_json_extract('src', ['CONTACTFULLNAME'], type='varchar', alias='contactfullname') }},
        {{ trx_json_extract('src', ['SOURCE'], type='varchar', alias='source') }},
        {{ trx_json_extract('src', ['APPLICATIONNUMBER'], type='varchar', alias='applicationnumber') }},
        {{ trx_json_extract('src', ['R4CURL'], type='varchar', alias='r4curl') }},
        {{ trx_json_extract('src', ['MONIKER'], type='varchar', alias='moniker') }},
        {{ trx_json_extract('src', ['REVIEWCOMPLETEEMAIL'], type='varchar', alias='reviewcompleteemail') }},
        {{ trx_json_extract('src', ['TITLE'], type='varchar', alias='title') }},
        {{ trx_json_extract('src', ['REVIEWERROLE'], type='varchar', alias='reviewerrole') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['TOEMAIL'], type='varchar', alias='toemail') }},
        {{ trx_json_extract('src', ['REVIEWCOMPLETEDAYPHONE'], type='varchar', alias='reviewcompletedayphone') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['NAME'], type='varchar', alias='name') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslinterface_notificationstaging') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['notificationstagingkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
