{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLINTERFACE.NONDOMESTICCONSTAGING on 2022-03-03T11:32:53.059',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['APBLDGKEY'], type='int', alias='apbldgkey') }},
        {{ trx_json_extract('src', ['POSTALCODE'], type='varchar', alias='postalcode') }},
        {{ trx_json_extract('src', ['FLAT'], type='varchar', alias='flat') }},
        {{ trx_json_extract('src', ['ENGINEERFULLNAME'], type='varchar', alias='engineerfullname') }},
        {{ trx_json_extract('src', ['DP'], type='varchar', alias='dp') }},
        {{ trx_json_extract('src', ['ONSITEFULLNAME'], type='varchar', alias='onsitefullname') }},
        {{ trx_json_extract('src', ['LEGALOWNERFULLNAME'], type='varchar', alias='legalownerfullname') }},
        {{ trx_json_extract('src', ['ONSITEMOBILE'], type='varchar', alias='onsitemobile') }},
        {{ trx_json_extract('src', ['APBLDGINSPKEY'], type='int', alias='apbldginspkey') }},
        {{ trx_json_extract('src', ['NONDOMESTICCONSTAGINGKEY'], type='int', alias='nondomesticconstagingkey') }},
        {{ trx_json_extract('src', ['HOUSENUMBER'], type='varchar', alias='housenumber') }},
        {{ trx_json_extract('src', ['ACTIONTYPE'], type='varchar', alias='actiontype') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CONTRACTOR'], type='varchar', alias='contractor') }},
        {{ trx_json_extract('src', ['APPLICATIONTYPE'], type='varchar', alias='applicationtype') }},
        {{ trx_json_extract('src', ['ONSITEEMAIL'], type='varchar', alias='onsiteemail') }},
        {{ trx_json_extract('src', ['LEGALOWNEREMAIL'], type='varchar', alias='legalowneremail') }},
        {{ trx_json_extract('src', ['LOT'], type='varchar', alias='lot') }},
        {{ trx_json_extract('src', ['APNO'], type='varchar', alias='apno') }},
        {{ trx_json_extract('src', ['REQUESTTYPE'], type='varchar', alias='requesttype') }},
        {{ trx_json_extract('src', ['LEGALOWNERMOBILE'], type='varchar', alias='legalownermobile') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['STREETNAME'], type='varchar', alias='streetname') }},
        {{ trx_json_extract('src', ['SUBURB'], type='varchar', alias='suburb') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['STREETTYPE'], type='varchar', alias='streettype') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslinterface_nondomesticconstaging') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['nondomesticconstagingkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
