{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLRESOURCES.XADDRESSGIS on 2022-03-03T11:39:38.306',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['INREDZONE'], type='varchar', alias='inredzone') }},
        {{ trx_json_extract('src', ['ADDRKEY'], type='int', alias='addrkey') }},
        {{ trx_json_extract('src', ['INPRESSUREDZONE'], type='varchar', alias='inpressuredzone') }},
        {{ trx_json_extract('src', ['IGCZONE'], type='varchar', alias='igczone') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['CONNECTIONTYPE'], type='varchar', alias='connectiontype') }},
        {{ trx_json_extract('src', ['CRITICALLINESAVAILABLE'], type='varchar', alias='criticallinesavailable') }},
        {{ trx_json_extract('src', ['HASSPECIALIGCAGREEMENT'], type='varchar', alias='hasspecialigcagreement') }},
        {{ trx_json_extract('src', ['XADDRESSGISKEY'], type='int', alias='xaddressgiskey') }},
        {{ trx_json_extract('src', ['INCOMBINEDAREA'], type='varchar', alias='incombinedarea') }},
        {{ trx_json_extract('src', ['WASTEWATERPIPELEVEL'], type='varchar', alias='wastewaterpipelevel') }},
        {{ trx_json_extract('src', ['ADDREXPIRED'], type='varchar', alias='addrexpired') }},
        {{ trx_json_extract('src', ['ARBORISTREQUIRED'], type='varchar', alias='arboristrequired') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['SERVICEAVAILABLE'], type='varchar', alias='serviceavailable') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['LEVELOFROAD'], type='varchar', alias='levelofroad') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslresources_xaddressgis') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['xaddressgiskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
