{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLTRADEBILLOUTPUT.TRADEBILLOUTPUTEXT on 2022-03-24T09:00:15.430',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['ACCOUNTKEY'], type='int', alias='accountkey') }},
        {{ trx_json_extract('src', ['BILLKEY'], type='int', alias='billkey') }},
        {{ trx_json_extract('src', ['PREVBILLAMT'], type='float', alias='prevbillamt') }},
        {{ trx_json_extract('src', ['MICRCHECKDIGIT'], type='varchar', alias='micrcheckdigit') }},
        {{ trx_json_extract('src', ['CUSTOMERREF'], type='varchar', alias='customerref') }},
        {{ trx_json_extract('src', ['DTLRCT'], type='timestamp_ntz', alias='dtlrct') }},
        {{ trx_json_extract('src', ['CHECKDIGIT'], type='varchar', alias='checkdigit') }},
        {{ trx_json_extract('src', ['DDFLAG'], type='varchar', alias='ddflag') }},
        {{ trx_json_extract('src', ['BILLRUNKEY'], type='int', alias='billrunkey') }},
        {{ trx_json_extract('src', ['TRADEBILLOUTPUTEXTKEY'], type='int', alias='tradebilloutputextkey') }},
        {{ trx_json_extract('src', ['ACCTCLASS'], type='varchar', alias='acctclass') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['ACCOUNTNUMBER'], type='varchar', alias='accountnumber') }},
        {{ trx_json_extract('src', ['BARCODECHECKDIGIT'], type='varchar', alias='barcodecheckdigit') }},
        {{ trx_json_extract('src', ['FILENAME'], type='varchar', alias='filename') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['BARCODEAMOUNT'], type='varchar', alias='barcodeamount') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wsltradebilloutput_tradebilloutputext') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['tradebilloutputextkey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
