{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='Generated by Infor IPS DataLake adoption from tenant WATERCARE_DEV table WSLVOC.VOCDETAILS on 2024-10-10T10:04:16.840',
    tags=['auto-generated', 'ips', 'stage7']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['VPT'], type='varchar', alias='vpt') }},
        {{ trx_json_extract('src', ['VFR'], type='varchar', alias='vfr') }},
        {{ trx_json_extract('src', ['VOCDETAILSKEY'], type='int', alias='vocdetailskey') }},
        {{ trx_json_extract('src', ['VSI'], type='varchar', alias='vsi') }},
        {{ trx_json_extract('src', ['VON'], type='varchar', alias='von') }},
        {{ trx_json_extract('src', ['VSL'], type='varchar', alias='vsl') }},
        {{ trx_json_extract('src', ['VSO'], type='varchar', alias='vso') }},
        {{ trx_json_extract('src', ['VPA'], type='varchar', alias='vpa') }},
        {{ trx_json_extract('src', ['VSQ'], type='varchar', alias='vsq') }},
        {{ trx_json_extract('src', ['VWF'], type='varchar', alias='vwf') }},
        {{ trx_json_extract('src', ['VPM'], type='varchar', alias='vpm') }},
        {{ trx_json_extract('src', ['VCO'], type='varchar', alias='vco') }},
        {{ trx_json_extract('src', ['VWO'], type='varchar', alias='vwo') }},
        {{ trx_json_extract('src', ['ADDBY'], type='varchar', alias='addby') }},
        {{ trx_json_extract('src', ['VPC'], type='varchar', alias='vpc') }},
        {{ trx_json_extract('src', ['VSA'], type='varchar', alias='vsa') }},
        {{ trx_json_extract('src', ['VPP'], type='varchar', alias='vpp') }},
        {{ trx_json_extract('src', ['VPB'], type='varchar', alias='vpb') }},
        {{ trx_json_extract('src', ['VPL'], type='varchar', alias='vpl') }},
        {{ trx_json_extract('src', ['VSK'], type='varchar', alias='vsk') }},
        {{ trx_json_extract('src', ['VCA'], type='varchar', alias='vca') }},
        {{ trx_json_extract('src', ['VSH'], type='varchar', alias='vsh') }},
        {{ trx_json_extract('src', ['VWA'], type='varchar', alias='vwa') }},
        {{ trx_json_extract('src', ['VCH'], type='varchar', alias='vch') }},
        {{ trx_json_extract('src', ['VFD'], type='varchar', alias='vfd') }},
        {{ trx_json_extract('src', ['VSR'], type='varchar', alias='vsr') }},
        {{ trx_json_extract('src', ['SERVNO'], type='int', alias='servno') }},
        {{ trx_json_extract('src', ['VPO'], type='varchar', alias='vpo') }},
        {{ trx_json_extract('src', ['VFO'], type='varchar', alias='vfo') }},
        {{ trx_json_extract('src', ['ADDDTTM'], type='timestamp_ntz', alias='adddttm') }},
        {{ trx_json_extract('src', ['VSE'], type='varchar', alias='vse') }},
        {{ trx_json_extract('src', ['MODBY'], type='varchar', alias='modby') }},
        {{ trx_json_extract('src', ['VWP'], type='varchar', alias='vwp') }},
        {{ trx_json_extract('src', ['VWN'], type='varchar', alias='vwn') }},
        {{ trx_json_extract('src', ['VWR'], type='varchar', alias='vwr') }},
        {{ trx_json_extract('src', ['MODDTTM'], type='timestamp_ntz', alias='moddttm') }},
        {{ trx_json_extract('src', ['VPI'], type='varchar', alias='vpi') }},
        {{ trx_json_extract('src', ['VARIATION_ID'], type='int', alias='variation_id') }},
        {{ trx_json_extract('src', ['DATALAKE_DELETED'], type='boolean', alias='datalake_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ips', 'ips_wslvoc_vocdetails') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['vocdetailskey']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['variation_id']) }}
