CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_EAM_R5COMPANIES AS SELECT
                        src:COM_ACCOUNTCODE::varchar AS COM_ACCOUNTCODE, 
                        src:COM_BUYER::varchar AS COM_BUYER, 
                        src:COM_CAPACITY::numeric(38, 10) AS COM_CAPACITY, 
                        src:COM_CLASS::varchar AS COM_CLASS, 
                        src:COM_CLASS_ORG::varchar AS COM_CLASS_ORG, 
                        src:COM_CODE::varchar AS COM_CODE, 
                        src:COM_CONTACT::varchar AS COM_CONTACT, 
                        src:COM_COSTCENTER::varchar AS COM_COSTCENTER, 
                        src:COM_CREATED::datetime AS COM_CREATED, 
                        src:COM_CURR::varchar AS COM_CURR, 
                        src:COM_CUSTOMER::varchar AS COM_CUSTOMER, 
                        src:COM_DESC::varchar AS COM_DESC, 
                        src:COM_EDINO::varchar AS COM_EDINO, 
                        src:COM_EMAIL::varchar AS COM_EMAIL, 
                        src:COM_FAX::varchar AS COM_FAX, 
                        src:COM_FOBPOINT::varchar AS COM_FOBPOINT, 
                        src:COM_FREIGHTTERMS::varchar AS COM_FREIGHTTERMS, 
                        src:COM_GROUPPURCHASINGORG1::varchar AS COM_GROUPPURCHASINGORG1, 
                        src:COM_GROUPPURCHASINGORG2::varchar AS COM_GROUPPURCHASINGORG2, 
                        src:COM_INTERFACE::datetime AS COM_INTERFACE, 
                        src:COM_IPACCOUNT::varchar AS COM_IPACCOUNT, 
                        src:COM_IPRESPONSE::varchar AS COM_IPRESPONSE, 
                        src:COM_IPVENDOR::numeric(38, 10) AS COM_IPVENDOR, 
                        src:COM_LANG::varchar AS COM_LANG, 
                        src:COM_LASTSAVED::datetime AS COM_LASTSAVED, 
                        src:COM_LASTSTATUSUPDATE::datetime AS COM_LASTSTATUSUPDATE, 
                        src:COM_LEADTIME::numeric(38, 10) AS COM_LEADTIME, 
                        src:COM_MAXORD::numeric(38, 10) AS COM_MAXORD, 
                        src:COM_MINORD::numeric(38, 10) AS COM_MINORD, 
                        src:COM_MINORITYGROUP::varchar AS COM_MINORITYGROUP, 
                        src:COM_NOTUSED::varchar AS COM_NOTUSED, 
                        src:COM_ORG::varchar AS COM_ORG, 
                        src:COM_OURCONT::varchar AS COM_OURCONT, 
                        src:COM_PARENT::varchar AS COM_PARENT, 
                        src:COM_PARENT_ORG::varchar AS COM_PARENT_ORG, 
                        src:COM_PAYBYMETHOD::varchar AS COM_PAYBYMETHOD, 
                        src:COM_PAYMENTTERMS::varchar AS COM_PAYMENTTERMS, 
                        src:COM_PEOPLE::varchar AS COM_PEOPLE, 
                        src:COM_PHONE::varchar AS COM_PHONE, 
                        src:COM_PURCHASESITE::varchar AS COM_PURCHASESITE, 
                        src:COM_SHIPVIA::varchar AS COM_SHIPVIA, 
                        src:COM_SOURCECODE::varchar AS COM_SOURCECODE, 
                        src:COM_SOURCESYSTEM::varchar AS COM_SOURCESYSTEM, 
                        src:COM_STATUS::varchar AS COM_STATUS, 
                        src:COM_TAX::varchar AS COM_TAX, 
                        src:COM_TYPE1099::varchar AS COM_TYPE1099, 
                        src:COM_UDFCHAR01::varchar AS COM_UDFCHAR01, 
                        src:COM_UDFCHAR02::varchar AS COM_UDFCHAR02, 
                        src:COM_UDFCHAR03::varchar AS COM_UDFCHAR03, 
                        src:COM_UDFCHAR04::varchar AS COM_UDFCHAR04, 
                        src:COM_UDFCHAR05::varchar AS COM_UDFCHAR05, 
                        src:COM_UDFCHAR06::varchar AS COM_UDFCHAR06, 
                        src:COM_UDFCHAR07::varchar AS COM_UDFCHAR07, 
                        src:COM_UDFCHAR08::varchar AS COM_UDFCHAR08, 
                        src:COM_UDFCHAR09::varchar AS COM_UDFCHAR09, 
                        src:COM_UDFCHAR10::varchar AS COM_UDFCHAR10, 
                        src:COM_UDFCHAR11::varchar AS COM_UDFCHAR11, 
                        src:COM_UDFCHAR12::varchar AS COM_UDFCHAR12, 
                        src:COM_UDFCHAR13::varchar AS COM_UDFCHAR13, 
                        src:COM_UDFCHAR14::varchar AS COM_UDFCHAR14, 
                        src:COM_UDFCHAR15::varchar AS COM_UDFCHAR15, 
                        src:COM_UDFCHAR16::varchar AS COM_UDFCHAR16, 
                        src:COM_UDFCHAR17::varchar AS COM_UDFCHAR17, 
                        src:COM_UDFCHAR18::varchar AS COM_UDFCHAR18, 
                        src:COM_UDFCHAR19::varchar AS COM_UDFCHAR19, 
                        src:COM_UDFCHAR20::varchar AS COM_UDFCHAR20, 
                        src:COM_UDFCHAR21::varchar AS COM_UDFCHAR21, 
                        src:COM_UDFCHAR22::varchar AS COM_UDFCHAR22, 
                        src:COM_UDFCHAR23::varchar AS COM_UDFCHAR23, 
                        src:COM_UDFCHAR24::varchar AS COM_UDFCHAR24, 
                        src:COM_UDFCHAR25::varchar AS COM_UDFCHAR25, 
                        src:COM_UDFCHAR26::varchar AS COM_UDFCHAR26, 
                        src:COM_UDFCHAR27::varchar AS COM_UDFCHAR27, 
                        src:COM_UDFCHAR28::varchar AS COM_UDFCHAR28, 
                        src:COM_UDFCHAR29::varchar AS COM_UDFCHAR29, 
                        src:COM_UDFCHAR30::varchar AS COM_UDFCHAR30, 
                        src:COM_UDFCHKBOX01::varchar AS COM_UDFCHKBOX01, 
                        src:COM_UDFCHKBOX02::varchar AS COM_UDFCHKBOX02, 
                        src:COM_UDFCHKBOX03::varchar AS COM_UDFCHKBOX03, 
                        src:COM_UDFCHKBOX04::varchar AS COM_UDFCHKBOX04, 
                        src:COM_UDFCHKBOX05::varchar AS COM_UDFCHKBOX05, 
                        src:COM_UDFDATE01::datetime AS COM_UDFDATE01, 
                        src:COM_UDFDATE02::datetime AS COM_UDFDATE02, 
                        src:COM_UDFDATE03::datetime AS COM_UDFDATE03, 
                        src:COM_UDFDATE04::datetime AS COM_UDFDATE04, 
                        src:COM_UDFDATE05::datetime AS COM_UDFDATE05, 
                        src:COM_UDFNUM01::numeric(38, 10) AS COM_UDFNUM01, 
                        src:COM_UDFNUM02::numeric(38, 10) AS COM_UDFNUM02, 
                        src:COM_UDFNUM03::numeric(38, 10) AS COM_UDFNUM03, 
                        src:COM_UDFNUM04::numeric(38, 10) AS COM_UDFNUM04, 
                        src:COM_UDFNUM05::numeric(38, 10) AS COM_UDFNUM05, 
                        src:COM_UPDATECOUNT::numeric(38, 10) AS COM_UPDATECOUNT, 
                        src:COM_UPDATED::datetime AS COM_UPDATED, 
                        src:_DELETED::boolean AS _DELETED, 
            CASE
                WHEN 'EAM' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'EAM' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:COM_CODE,
                src:COM_ORG,
            src:COM_LASTSAVED
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:COM_CODE,
                src:COM_ORG  ORDER BY 
            src:COM_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.EAM_R5COMPANIES as strm))