CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_EAM_R5DOCUMENTS AS SELECT
                        src:DOC_AGREEMENTTYPE::varchar AS DOC_AGREEMENTTYPE, 
                        src:DOC_CABINET::varchar AS DOC_CABINET, 
                        src:DOC_CLASS::varchar AS DOC_CLASS, 
                        src:DOC_CLASS_ORG::varchar AS DOC_CLASS_ORG, 
                        src:DOC_CODE::varchar AS DOC_CODE, 
                        src:DOC_CONTENT::varchar AS DOC_CONTENT, 
                        src:DOC_CONTROLNUMBER::varchar AS DOC_CONTROLNUMBER, 
                        src:DOC_DATEEFFECTIVE::datetime AS DOC_DATEEFFECTIVE, 
                        src:DOC_DATEEXPIRED::datetime AS DOC_DATEEXPIRED, 
                        src:DOC_DESC::varchar AS DOC_DESC, 
                        src:DOC_DMACHARGE::numeric(38, 10) AS DOC_DMACHARGE, 
                        src:DOC_DURATION::numeric(38, 10) AS DOC_DURATION, 
                        src:DOC_EXCLUDEPMWORKORDER::varchar AS DOC_EXCLUDEPMWORKORDER, 
                        src:DOC_EXPIR::datetime AS DOC_EXPIR, 
                        src:DOC_FILENAME::varchar AS DOC_FILENAME, 
                        src:DOC_FILESIZE::numeric(38, 10) AS DOC_FILESIZE, 
                        src:DOC_FILETYPE::varchar AS DOC_FILETYPE, 
                        src:DOC_FIXEDLABORAMOUNT::numeric(38, 10) AS DOC_FIXEDLABORAMOUNT, 
                        src:DOC_FIXEDLABORRATE::numeric(38, 10) AS DOC_FIXEDLABORRATE, 
                        src:DOC_FIXEDSTOCKAMOUNT::numeric(38, 10) AS DOC_FIXEDSTOCKAMOUNT, 
                        src:DOC_HIRCHARGE::numeric(38, 10) AS DOC_HIRCHARGE, 
                        src:DOC_IDMTYPE::varchar AS DOC_IDMTYPE, 
                        src:DOC_ISMOBILELOG::varchar AS DOC_ISMOBILELOG, 
                        src:DOC_ISPROFILEPICTURE::varchar AS DOC_ISPROFILEPICTURE, 
                        src:DOC_LABCHARGE::numeric(38, 10) AS DOC_LABCHARGE, 
                        src:DOC_LASTSAVED::datetime AS DOC_LASTSAVED, 
                        src:DOC_LOANERPROVIDED::varchar AS DOC_LOANERPROVIDED, 
                        src:DOC_LOCKUSER::varchar AS DOC_LOCKUSER, 
                        src:DOC_MANUFACTURER::varchar AS DOC_MANUFACTURER, 
                        src:DOC_MATCHARGE::numeric(38, 10) AS DOC_MATCHARGE, 
                        src:DOC_MAXLABORAMOUNT::numeric(38, 10) AS DOC_MAXLABORAMOUNT, 
                        src:DOC_MAXSTOCKAMOUNT::numeric(38, 10) AS DOC_MAXSTOCKAMOUNT, 
                        src:DOC_NOTUSED::varchar AS DOC_NOTUSED, 
                        src:DOC_ONSITEREPAIR::varchar AS DOC_ONSITEREPAIR, 
                        src:DOC_ORG::varchar AS DOC_ORG, 
                        src:DOC_ORIGCODE::varchar AS DOC_ORIGCODE, 
                        src:DOC_ORIGFILENAME::varchar AS DOC_ORIGFILENAME, 
                        src:DOC_ORIGIN::varchar AS DOC_ORIGIN, 
                        src:DOC_PAGES::numeric(38, 10) AS DOC_PAGES, 
                        src:DOC_PARENT::varchar AS DOC_PARENT, 
                        src:DOC_PARTLISTREQUIRED::varchar AS DOC_PARTLISTREQUIRED, 
                        src:DOC_RENEWALALERTEMAIL::varchar AS DOC_RENEWALALERTEMAIL, 
                        src:DOC_REVISION::datetime AS DOC_REVISION, 
                        src:DOC_REVNUMBER::varchar AS DOC_REVNUMBER, 
                        src:DOC_RMAREQUIRED::varchar AS DOC_RMAREQUIRED, 
                        src:DOC_RTYPE::varchar AS DOC_RTYPE, 
                        src:DOC_SERVICECHARGE::numeric(38, 10) AS DOC_SERVICECHARGE, 
                        src:DOC_SIZE::varchar AS DOC_SIZE, 
                        src:DOC_STARTDATEBASIS::varchar AS DOC_STARTDATEBASIS, 
                        src:DOC_SUPPLIER::varchar AS DOC_SUPPLIER, 
                        src:DOC_SUPPLIER_ORG::varchar AS DOC_SUPPLIER_ORG, 
                        src:DOC_THRESHOLD::numeric(38, 10) AS DOC_THRESHOLD, 
                        src:DOC_TITLE::varchar AS DOC_TITLE, 
                        src:DOC_TOOLCHARGE::numeric(38, 10) AS DOC_TOOLCHARGE, 
                        src:DOC_TYPE::varchar AS DOC_TYPE, 
                        src:DOC_UDFCHAR01::varchar AS DOC_UDFCHAR01, 
                        src:DOC_UDFCHAR02::varchar AS DOC_UDFCHAR02, 
                        src:DOC_UDFCHAR03::varchar AS DOC_UDFCHAR03, 
                        src:DOC_UDFCHAR04::varchar AS DOC_UDFCHAR04, 
                        src:DOC_UDFCHAR05::varchar AS DOC_UDFCHAR05, 
                        src:DOC_UDFCHAR06::varchar AS DOC_UDFCHAR06, 
                        src:DOC_UDFCHAR07::varchar AS DOC_UDFCHAR07, 
                        src:DOC_UDFCHAR08::varchar AS DOC_UDFCHAR08, 
                        src:DOC_UDFCHAR09::varchar AS DOC_UDFCHAR09, 
                        src:DOC_UDFCHAR10::varchar AS DOC_UDFCHAR10, 
                        src:DOC_UDFCHAR11::varchar AS DOC_UDFCHAR11, 
                        src:DOC_UDFCHAR12::varchar AS DOC_UDFCHAR12, 
                        src:DOC_UDFCHAR13::varchar AS DOC_UDFCHAR13, 
                        src:DOC_UDFCHAR14::varchar AS DOC_UDFCHAR14, 
                        src:DOC_UDFCHAR15::varchar AS DOC_UDFCHAR15, 
                        src:DOC_UDFCHAR16::varchar AS DOC_UDFCHAR16, 
                        src:DOC_UDFCHAR17::varchar AS DOC_UDFCHAR17, 
                        src:DOC_UDFCHAR18::varchar AS DOC_UDFCHAR18, 
                        src:DOC_UDFCHAR19::varchar AS DOC_UDFCHAR19, 
                        src:DOC_UDFCHAR20::varchar AS DOC_UDFCHAR20, 
                        src:DOC_UDFCHAR21::varchar AS DOC_UDFCHAR21, 
                        src:DOC_UDFCHAR22::varchar AS DOC_UDFCHAR22, 
                        src:DOC_UDFCHAR23::varchar AS DOC_UDFCHAR23, 
                        src:DOC_UDFCHAR24::varchar AS DOC_UDFCHAR24, 
                        src:DOC_UDFCHAR25::varchar AS DOC_UDFCHAR25, 
                        src:DOC_UDFCHAR26::varchar AS DOC_UDFCHAR26, 
                        src:DOC_UDFCHAR27::varchar AS DOC_UDFCHAR27, 
                        src:DOC_UDFCHAR28::varchar AS DOC_UDFCHAR28, 
                        src:DOC_UDFCHAR29::varchar AS DOC_UDFCHAR29, 
                        src:DOC_UDFCHAR30::varchar AS DOC_UDFCHAR30, 
                        src:DOC_UDFCHKBOX01::varchar AS DOC_UDFCHKBOX01, 
                        src:DOC_UDFCHKBOX02::varchar AS DOC_UDFCHKBOX02, 
                        src:DOC_UDFCHKBOX03::varchar AS DOC_UDFCHKBOX03, 
                        src:DOC_UDFCHKBOX04::varchar AS DOC_UDFCHKBOX04, 
                        src:DOC_UDFCHKBOX05::varchar AS DOC_UDFCHKBOX05, 
                        src:DOC_UDFDATE01::datetime AS DOC_UDFDATE01, 
                        src:DOC_UDFDATE02::datetime AS DOC_UDFDATE02, 
                        src:DOC_UDFDATE03::datetime AS DOC_UDFDATE03, 
                        src:DOC_UDFDATE04::datetime AS DOC_UDFDATE04, 
                        src:DOC_UDFDATE05::datetime AS DOC_UDFDATE05, 
                        src:DOC_UDFNUM01::numeric(38, 10) AS DOC_UDFNUM01, 
                        src:DOC_UDFNUM02::numeric(38, 10) AS DOC_UDFNUM02, 
                        src:DOC_UDFNUM03::numeric(38, 10) AS DOC_UDFNUM03, 
                        src:DOC_UDFNUM04::numeric(38, 10) AS DOC_UDFNUM04, 
                        src:DOC_UDFNUM05::numeric(38, 10) AS DOC_UDFNUM05, 
                        src:DOC_UPDATECOUNT::numeric(38, 10) AS DOC_UPDATECOUNT, 
                        src:DOC_UPLOADED::datetime AS DOC_UPLOADED, 
                        src:DOC_WARRANTY::varchar AS DOC_WARRANTY, 
                        src:DOC_WARRANTYTYPE::varchar AS DOC_WARRANTYTYPE, 
                        src:DOC_WARSTART::datetime AS DOC_WARSTART, 
                        src:_DELETED::boolean AS _DELETED, 
            CASE
                WHEN 'EAM' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'EAM' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:DOC_CODE,
            src:DOC_LASTSAVED
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:DOC_CODE  ORDER BY 
            src:DOC_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.EAM_R5DOCUMENTS as strm))