CREATE OR REPLACE VIEW DATAHUB_LANDING.VW_EAM_R5EQUIPMENTRANKINGHISTORY AS SELECT
                        src:ERH_AVAILABLECAPACITY::numeric(38, 10) AS ERH_AVAILABLECAPACITY, 
                        src:ERH_CAPACITYCODE::varchar AS ERH_CAPACITYCODE, 
                        src:ERH_CAPACITYRATING::numeric(38, 10) AS ERH_CAPACITYRATING, 
                        src:ERH_CONDITIONPROTOCOL::varchar AS ERH_CONDITIONPROTOCOL, 
                        src:ERH_CONDITIONRATING::numeric(38, 10) AS ERH_CONDITIONRATING, 
                        src:ERH_CONDSCOREEND::numeric(38, 10) AS ERH_CONDSCOREEND, 
                        src:ERH_CONDSCORESTART::numeric(38, 10) AS ERH_CONDSCORESTART, 
                        src:ERH_CONDSCORETHRESHOLD::numeric(38, 10) AS ERH_CONDSCORETHRESHOLD, 
                        src:ERH_CORRCONDITIONDATE::datetime AS ERH_CORRCONDITIONDATE, 
                        src:ERH_CORRCONDITIONREASON::varchar AS ERH_CORRCONDITIONREASON, 
                        src:ERH_CORRCONDITIONSCORE::numeric(38, 10) AS ERH_CORRCONDITIONSCORE, 
                        src:ERH_CORRCONDITIONUSAGE::numeric(38, 10) AS ERH_CORRCONDITIONUSAGE, 
                        src:ERH_CREATED::datetime AS ERH_CREATED, 
                        src:ERH_CREATEDBY::varchar AS ERH_CREATEDBY, 
                        src:ERH_DAILYUSAGEUOM::varchar AS ERH_DAILYUSAGEUOM, 
                        src:ERH_DATE::datetime AS ERH_DATE, 
                        src:ERH_DECAYCURVE::varchar AS ERH_DECAYCURVE, 
                        src:ERH_DECAYCURVE_ORG::varchar AS ERH_DECAYCURVE_ORG, 
                        src:ERH_DESIREDCAPACITY::numeric(38, 10) AS ERH_DESIREDCAPACITY, 
                        src:ERH_ENDOFUSEFULLIFE::datetime AS ERH_ENDOFUSEFULLIFE, 
                        src:ERH_FROMGEOREF::varchar AS ERH_FROMGEOREF, 
                        src:ERH_FROMPOINT::numeric(38, 10) AS ERH_FROMPOINT, 
                        src:ERH_FROMREFDESC::varchar AS ERH_FROMREFDESC, 
                        src:ERH_INDEX::varchar AS ERH_INDEX, 
                        src:ERH_LASTSAVED::datetime AS ERH_LASTSAVED, 
                        src:ERH_MTBFDAYS::numeric(38, 10) AS ERH_MTBFDAYS, 
                        src:ERH_MTBFRATING::numeric(38, 10) AS ERH_MTBFRATING, 
                        src:ERH_MTTRHRS::numeric(38, 10) AS ERH_MTTRHRS, 
                        src:ERH_MTTRRATING::numeric(38, 10) AS ERH_MTTRRATING, 
                        src:ERH_MUBF::numeric(38, 10) AS ERH_MUBF, 
                        src:ERH_MUBFRATING::numeric(38, 10) AS ERH_MUBFRATING, 
                        src:ERH_NUMBEROFFAILURES::numeric(38, 10) AS ERH_NUMBEROFFAILURES, 
                        src:ERH_OBJCODE::varchar AS ERH_OBJCODE, 
                        src:ERH_OBJORG::varchar AS ERH_OBJORG, 
                        src:ERH_PERFORMANCE::numeric(38, 10) AS ERH_PERFORMANCE, 
                        src:ERH_PERFORMANCEFORMULA::varchar AS ERH_PERFORMANCEFORMULA, 
                        src:ERH_PERFORMANCEFORMULA_ORG::varchar AS ERH_PERFORMANCEFORMULA_ORG, 
                        src:ERH_PK::varchar AS ERH_PK, 
                        src:ERH_PRIMARYUOM::varchar AS ERH_PRIMARYUOM, 
                        src:ERH_RANKINGCODE::varchar AS ERH_RANKINGCODE, 
                        src:ERH_RANKINGORG::varchar AS ERH_RANKINGORG, 
                        src:ERH_RANKINGREVISION::numeric(38, 10) AS ERH_RANKINGREVISION, 
                        src:ERH_RANKINGTYPE::varchar AS ERH_RANKINGTYPE, 
                        src:ERH_RISKLEVEL::varchar AS ERH_RISKLEVEL, 
                        src:ERH_SCORE::numeric(38, 10) AS ERH_SCORE, 
                        src:ERH_SERVICELIFE::numeric(38, 10) AS ERH_SERVICELIFE, 
                        src:ERH_SERVICELIFEUSAGE::numeric(38, 10) AS ERH_SERVICELIFEUSAGE, 
                        src:ERH_TOGEOREF::varchar AS ERH_TOGEOREF, 
                        src:ERH_TOPOINT::numeric(38, 10) AS ERH_TOPOINT, 
                        src:ERH_TOREFDESC::varchar AS ERH_TOREFDESC, 
                        src:ERH_UDFCHAR01::varchar AS ERH_UDFCHAR01, 
                        src:ERH_UDFCHAR02::varchar AS ERH_UDFCHAR02, 
                        src:ERH_UDFCHAR03::varchar AS ERH_UDFCHAR03, 
                        src:ERH_UDFCHAR04::varchar AS ERH_UDFCHAR04, 
                        src:ERH_UDFCHAR05::varchar AS ERH_UDFCHAR05, 
                        src:ERH_UDFCHAR06::varchar AS ERH_UDFCHAR06, 
                        src:ERH_UDFCHAR07::varchar AS ERH_UDFCHAR07, 
                        src:ERH_UDFCHAR08::varchar AS ERH_UDFCHAR08, 
                        src:ERH_UDFCHAR09::varchar AS ERH_UDFCHAR09, 
                        src:ERH_UDFCHAR10::varchar AS ERH_UDFCHAR10, 
                        src:ERH_UDFCHAR11::varchar AS ERH_UDFCHAR11, 
                        src:ERH_UDFCHAR12::varchar AS ERH_UDFCHAR12, 
                        src:ERH_UDFCHAR13::varchar AS ERH_UDFCHAR13, 
                        src:ERH_UDFCHAR14::varchar AS ERH_UDFCHAR14, 
                        src:ERH_UDFCHAR15::varchar AS ERH_UDFCHAR15, 
                        src:ERH_UDFCHAR16::varchar AS ERH_UDFCHAR16, 
                        src:ERH_UDFCHAR17::varchar AS ERH_UDFCHAR17, 
                        src:ERH_UDFCHAR18::varchar AS ERH_UDFCHAR18, 
                        src:ERH_UDFCHAR19::varchar AS ERH_UDFCHAR19, 
                        src:ERH_UDFCHAR20::varchar AS ERH_UDFCHAR20, 
                        src:ERH_UDFCHAR21::varchar AS ERH_UDFCHAR21, 
                        src:ERH_UDFCHAR22::varchar AS ERH_UDFCHAR22, 
                        src:ERH_UDFCHAR23::varchar AS ERH_UDFCHAR23, 
                        src:ERH_UDFCHAR24::varchar AS ERH_UDFCHAR24, 
                        src:ERH_UDFCHAR25::varchar AS ERH_UDFCHAR25, 
                        src:ERH_UDFCHAR26::varchar AS ERH_UDFCHAR26, 
                        src:ERH_UDFCHAR27::varchar AS ERH_UDFCHAR27, 
                        src:ERH_UDFCHAR28::varchar AS ERH_UDFCHAR28, 
                        src:ERH_UDFCHAR29::varchar AS ERH_UDFCHAR29, 
                        src:ERH_UDFCHAR30::varchar AS ERH_UDFCHAR30, 
                        src:ERH_UDFCHKBOX01::varchar AS ERH_UDFCHKBOX01, 
                        src:ERH_UDFCHKBOX02::varchar AS ERH_UDFCHKBOX02, 
                        src:ERH_UDFCHKBOX03::varchar AS ERH_UDFCHKBOX03, 
                        src:ERH_UDFCHKBOX04::varchar AS ERH_UDFCHKBOX04, 
                        src:ERH_UDFCHKBOX05::varchar AS ERH_UDFCHKBOX05, 
                        src:ERH_UDFDATE01::datetime AS ERH_UDFDATE01, 
                        src:ERH_UDFDATE02::datetime AS ERH_UDFDATE02, 
                        src:ERH_UDFDATE03::datetime AS ERH_UDFDATE03, 
                        src:ERH_UDFDATE04::datetime AS ERH_UDFDATE04, 
                        src:ERH_UDFDATE05::datetime AS ERH_UDFDATE05, 
                        src:ERH_UDFNUM01::numeric(38, 10) AS ERH_UDFNUM01, 
                        src:ERH_UDFNUM02::numeric(38, 10) AS ERH_UDFNUM02, 
                        src:ERH_UDFNUM03::numeric(38, 10) AS ERH_UDFNUM03, 
                        src:ERH_UDFNUM04::numeric(38, 10) AS ERH_UDFNUM04, 
                        src:ERH_UDFNUM05::numeric(38, 10) AS ERH_UDFNUM05, 
                        src:ERH_UPDATECOUNT::numeric(38, 10) AS ERH_UPDATECOUNT, 
                        src:ERH_UPDATED::datetime AS ERH_UPDATED, 
                        src:ERH_UPDATEDBY::varchar AS ERH_UPDATEDBY, 
                        src:ERH_USAGE::numeric(38, 10) AS ERH_USAGE, 
                        src:ERH_VARIABLERATING1::numeric(38, 10) AS ERH_VARIABLERATING1, 
                        src:ERH_VARIABLERATING2::numeric(38, 10) AS ERH_VARIABLERATING2, 
                        src:ERH_VARIABLERATING3::numeric(38, 10) AS ERH_VARIABLERATING3, 
                        src:ERH_VARIABLERATING4::numeric(38, 10) AS ERH_VARIABLERATING4, 
                        src:ERH_VARIABLERATING5::numeric(38, 10) AS ERH_VARIABLERATING5, 
                        src:ERH_VARIABLERATING6::numeric(38, 10) AS ERH_VARIABLERATING6, 
                        src:ERH_VARIABLERESULT1::numeric(38, 10) AS ERH_VARIABLERESULT1, 
                        src:ERH_VARIABLERESULT2::numeric(38, 10) AS ERH_VARIABLERESULT2, 
                        src:ERH_VARIABLERESULT3::numeric(38, 10) AS ERH_VARIABLERESULT3, 
                        src:ERH_VARIABLERESULT4::numeric(38, 10) AS ERH_VARIABLERESULT4, 
                        src:ERH_VARIABLERESULT5::numeric(38, 10) AS ERH_VARIABLERESULT5, 
                        src:ERH_VARIABLERESULT6::numeric(38, 10) AS ERH_VARIABLERESULT6, 
                        src:_DELETED::boolean AS _DELETED, 
            CASE
                WHEN 'EAM' = 'LN'
                THEN src:"deleted"::BOOLEAN
                WHEN 'EAM' = 'IPS'
                THEN src:"DATALAKE_DELETED"::BOOLEAN
                ELSE src:"_DELETED"::BOOLEAN
            END as ETL_DELETED,
            etl_load_datetime,
            etl_load_metadatafilename,
            ETL_RANK,
            IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) as ETL_RANK_TIMESTAMP
            FROM 
            (
            select 
                src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROWNUMBER as ETL_RANK
                from
                (
                    SELECT
    
                        
                src:ERH_PK,
            src:ERH_LASTSAVED
                ,src,
                etl_load_datetime,
                etl_load_metadatafilename,
                ROW_NUMBER() OVER (PARTITION BY 
                                        
                src:ERH_PK  ORDER BY 
            src:ERH_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
                FROM DATAHUB_LANDING.EAM_R5EQUIPMENTRANKINGHISTORY as strm))