create or replace view VW_MODEL_TRANSACTION_AUDIT(
	ACCOUNTKEY,
	SUM_OF_TXN_AMOUNT
) as

    SELECT 
        acc.ACCOUNT_KEY accountkey, 
        sum(h.TRANSACTION_AMOUNT) as SUM_OF_TXN_AMOUNT
    FROM 
        DATAHUB_ANALYTICS.FACT_ACCOUNT_TRANSACTION h
            INNER JOIN 
        DATAHUB_ANALYTICS.DIM_TRANSACTION_DATE TRANDATE ON h.TRANSACTION_DATE_SID =trandate.TRANSACTION_DATE_SID
            INNER JOIN 
        DATAHUB_ANALYTICS.DIM_CUSTOMER_ACCOUNT ACC ON h.ACCOUNT_SID =acc.account_sid
    WHERE 
        trandate.CALENDAR_DATE BETWEEN '1900-01-01' and '2022-03-31'
    GROUP BY acc.ACCOUNT_KEY;