CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5BOOKEDHOURS_DELETED(
                "BOO_ACD" numeric(38, 10), 
                "BOO_ACT" numeric(38, 10), 
                "BOO_BILLSUBLINE" varchar, 
                "BOO_CODE" varchar, 
                "BOO_CORRECTION" varchar, 
                "BOO_CORRECTIONDATE" datetime, 
                "BOO_COST" numeric(38, 10), 
                "BOO_DATE" datetime, 
                "BOO_DESC" varchar, 
                "BOO_ENTERED" datetime, 
                "BOO_EVENT" varchar, 
                "BOO_EVTALIAS" varchar, 
                "BOO_FLEETCHECKED" varchar, 
                "BOO_FLEETMARKUP" numeric(38, 10), 
                "BOO_GLTRANSFER" datetime, 
                "BOO_GLTRANSFERFLAG" varchar, 
                "BOO_HOURS" numeric(38, 10), 
                "BOO_INVOICE" varchar, 
                "BOO_INVOICELINE" numeric(38, 10), 
                "BOO_INVOICE_ORG" varchar, 
                "BOO_INVOICE_REVISION" numeric(38, 10), 
                "BOO_JECATEGORY" varchar, 
                "BOO_JESOURCE" varchar, 
                "BOO_LASTSAVED" datetime, 
                "BOO_MISC" varchar, 
                "BOO_MRC" varchar, 
                "BOO_OCRTYPE" varchar, 
                "BOO_OCTYPE" varchar, 
                "BOO_OFF" numeric(38, 10), 
                "BOO_ON" numeric(38, 10), 
                "BOO_ORDER" varchar, 
                "BOO_ORDER_ORG" varchar, 
                "BOO_ORDLINE" numeric(38, 10), 
                "BOO_ORIGHOURS" numeric(38, 10), 
                "BOO_ORIGTAXAMOUNT" numeric(38, 10), 
                "BOO_PERSON" varchar, 
                "BOO_RATE" numeric(38, 10), 
                "BOO_ROUTEPARENT" varchar, 
                "BOO_ROUTEREC" varchar, 
                "BOO_ROUTERTYPE" varchar, 
                "BOO_SPLITHOURS" varchar, 
                "BOO_TAXAMOUNT" numeric(38, 10), 
                "BOO_TRADE" varchar, 
                "BOO_TRANSCODE" varchar, 
                "BOO_TRANSGROUP" numeric(38, 10), 
                "BOO_TRANSORGID" numeric(38, 10), 
                "BOO_UDFCHAR01" varchar, 
                "BOO_UDFCHAR02" varchar, 
                "BOO_UDFCHAR03" varchar, 
                "BOO_UDFCHAR04" varchar, 
                "BOO_UDFCHAR05" varchar, 
                "BOO_UDFCHAR06" varchar, 
                "BOO_UDFCHAR07" varchar, 
                "BOO_UDFCHAR08" varchar, 
                "BOO_UDFCHAR09" varchar, 
                "BOO_UDFCHAR10" varchar, 
                "BOO_UDFCHAR11" varchar, 
                "BOO_UDFCHAR12" varchar, 
                "BOO_UDFCHAR13" varchar, 
                "BOO_UDFCHAR14" varchar, 
                "BOO_UDFCHAR15" varchar, 
                "BOO_UDFCHAR16" varchar, 
                "BOO_UDFCHAR17" varchar, 
                "BOO_UDFCHAR18" varchar, 
                "BOO_UDFCHAR19" varchar, 
                "BOO_UDFCHAR20" varchar, 
                "BOO_UDFCHAR21" varchar, 
                "BOO_UDFCHAR22" varchar, 
                "BOO_UDFCHAR23" varchar, 
                "BOO_UDFCHAR24" varchar, 
                "BOO_UDFCHAR25" varchar, 
                "BOO_UDFCHAR26" varchar, 
                "BOO_UDFCHAR27" varchar, 
                "BOO_UDFCHAR28" varchar, 
                "BOO_UDFCHAR29" varchar, 
                "BOO_UDFCHAR30" varchar, 
                "BOO_UDFCHKBOX01" varchar, 
                "BOO_UDFCHKBOX02" varchar, 
                "BOO_UDFCHKBOX03" varchar, 
                "BOO_UDFCHKBOX04" varchar, 
                "BOO_UDFCHKBOX05" varchar, 
                "BOO_UDFDATE01" datetime, 
                "BOO_UDFDATE02" datetime, 
                "BOO_UDFDATE03" datetime, 
                "BOO_UDFDATE04" datetime, 
                "BOO_UDFDATE05" datetime, 
                "BOO_UDFNUM01" numeric(38, 10), 
                "BOO_UDFNUM02" numeric(38, 10), 
                "BOO_UDFNUM03" numeric(38, 10), 
                "BOO_UDFNUM04" numeric(38, 10), 
                "BOO_UDFNUM05" numeric(38, 10), 
                "BOO_UNMATCHEDINVOICE" varchar, 
                "BOO_UNMATCHEDINVOICELINE" numeric(38, 10), 
                "BOO_UNMATCHEDINVOICE_ORG" varchar, 
                "BOO_UPDATECOUNT" numeric(38, 10), 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 