CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5CONTACTCENTEROPTIONS_DELETED(
                "COP_CHKDUPLICATEOPENREQ" varchar, 
                "COP_CHKRECURRINGCLOSEDREQ" varchar, 
                "COP_CLOSEABLE" varchar, 
                "COP_COPYCUSTOMERINFO" varchar, 
                "COP_DEFCONTACTSOURCE" varchar, 
                "COP_DEFFINDBY" varchar, 
                "COP_DEFFOLLOWUPSTATUS" varchar, 
                "COP_DEFOPENSTATUS" varchar, 
                "COP_DEFORGUSAGE" varchar, 
                "COP_DEFPORTALSOURCE" varchar, 
                "COP_DEFPORTALSTATUS" varchar, 
                "COP_DEFPORTALTYPE" varchar, 
                "COP_DEFTYPE" varchar, 
                "COP_DEFWOORG" varchar, 
                "COP_DEFWOSTATUS" varchar, 
                "COP_DEPTSTRUCTUREUSAGE" varchar, 
                "COP_EVENTTYPEFILTER" varchar, 
                "COP_HIGHLIGHTMAP" varchar, 
                "COP_IDEFEATURE" varchar, 
                "COP_INCLUDEPMWORKORDERS" varchar, 
                "COP_KBRESULTSPERPAGE" numeric(38, 10), 
                "COP_LASTSAVED" datetime, 
                "COP_MATCHSC" varchar, 
                "COP_MATCHSPC" varchar, 
                "COP_MINPENALTY" numeric(38, 10), 
                "COP_NEARADDRESS" varchar, 
                "COP_NEWCUSTOMERALLOWED" varchar, 
                "COP_ORG" varchar, 
                "COP_RECURRINGREQLOOKBACKDAYS" numeric(38, 10), 
                "COP_SCHEDULEWO" varchar, 
                "COP_SHOWCHILDREN" varchar, 
                "COP_SHOWPROVIDER" varchar, 
                "COP_SHOWSERVICECATEGORY" varchar, 
                "COP_SHOWSPC" varchar, 
                "COP_SHOWSUPPLIER" varchar, 
                "COP_SPCVALIDATION" varchar, 
                "COP_TOPTENLOOKBACK" numeric(38, 10), 
                "COP_UPDATECOUNT" numeric(38, 10), 
                "COP_UPDATED" datetime, 
                "COP_UPDATEDBY" varchar, 
                "COP_WOCLOSEDAYS" numeric(38, 10), 
                "COP_WODUPLICATECHECK" varchar, 
                "COP_WOHEADEROBJONLY" varchar, 
                "COP_WOOPENDAYS" numeric(38, 10), 
                "COP_WOSTATUSES" varchar, 
                "COP_WOTYPES" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 