CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5PERSONNEL_DELETED(
                "PER_ADDRESS" varchar, 
                "PER_ALIAS" varchar, 
                "PER_BIRTHDATE" datetime, 
                "PER_CAPACITY" numeric(38, 10), 
                "PER_CITY" varchar, 
                "PER_CLASS" varchar, 
                "PER_CLASS_ORG" varchar, 
                "PER_CODE" varchar, 
                "PER_COSTCODE" varchar, 
                "PER_COUNTRY" varchar, 
                "PER_CREATED" datetime, 
                "PER_CREATEDBY" varchar, 
                "PER_CUSTOMER" varchar, 
                "PER_CUSTOMER_ORG" varchar, 
                "PER_DESC" varchar, 
                "PER_DETERMINESCREWLOCATION" varchar, 
                "PER_DRIVERSLICENSE" varchar, 
                "PER_EMAILADDRESS" varchar, 
                "PER_EMERGENCYCONTACT" varchar, 
                "PER_EMERGENCYCONTACTPHNO" varchar, 
                "PER_FAX" varchar, 
                "PER_FLEETCUSTOMER" varchar, 
                "PER_FLEETCUSTOMER_ORG" varchar, 
                "PER_HIREDATE" datetime, 
                "PER_HOMEPHONENO" varchar, 
                "PER_INITIALS" varchar, 
                "PER_JOBTITLE" varchar, 
                "PER_LASTSAVED" datetime, 
                "PER_MOBILEPHONENO" varchar, 
                "PER_MRC" varchar, 
                "PER_NOTIFICATIONPREF" varchar, 
                "PER_NOTUSED" varchar, 
                "PER_OBJECT" varchar, 
                "PER_OBJECT_ORG" varchar, 
                "PER_ORG" varchar, 
                "PER_PARENT" varchar, 
                "PER_PAYROLLNO" varchar, 
                "PER_PHONE" varchar, 
                "PER_PROFILEPICTURE" varchar, 
                "PER_SCHEDULINGSESSIONID" varchar, 
                "PER_SCHEDULINGTYPE" varchar, 
                "PER_SECURITYBADGENO" varchar, 
                "PER_STATE" varchar, 
                "PER_SUPERVISOR" varchar, 
                "PER_TERMINATEDDATE" datetime, 
                "PER_TRADE" varchar, 
                "PER_TRADESPERSON" varchar, 
                "PER_UDFCHAR01" varchar, 
                "PER_UDFCHAR02" varchar, 
                "PER_UDFCHAR03" varchar, 
                "PER_UDFCHAR04" varchar, 
                "PER_UDFCHAR05" varchar, 
                "PER_UDFCHAR06" varchar, 
                "PER_UDFCHAR07" varchar, 
                "PER_UDFCHAR08" varchar, 
                "PER_UDFCHAR09" varchar, 
                "PER_UDFCHAR10" varchar, 
                "PER_UDFCHAR11" varchar, 
                "PER_UDFCHAR12" varchar, 
                "PER_UDFCHAR13" varchar, 
                "PER_UDFCHAR14" varchar, 
                "PER_UDFCHAR15" varchar, 
                "PER_UDFCHAR16" varchar, 
                "PER_UDFCHAR17" varchar, 
                "PER_UDFCHAR18" varchar, 
                "PER_UDFCHAR19" varchar, 
                "PER_UDFCHAR20" varchar, 
                "PER_UDFCHAR21" varchar, 
                "PER_UDFCHAR22" varchar, 
                "PER_UDFCHAR23" varchar, 
                "PER_UDFCHAR24" varchar, 
                "PER_UDFCHAR25" varchar, 
                "PER_UDFCHAR26" varchar, 
                "PER_UDFCHAR27" varchar, 
                "PER_UDFCHAR28" varchar, 
                "PER_UDFCHAR29" varchar, 
                "PER_UDFCHAR30" varchar, 
                "PER_UDFCHKBOX01" varchar, 
                "PER_UDFCHKBOX02" varchar, 
                "PER_UDFCHKBOX03" varchar, 
                "PER_UDFCHKBOX04" varchar, 
                "PER_UDFCHKBOX05" varchar, 
                "PER_UDFDATE01" datetime, 
                "PER_UDFDATE02" datetime, 
                "PER_UDFDATE03" datetime, 
                "PER_UDFDATE04" datetime, 
                "PER_UDFDATE05" datetime, 
                "PER_UDFNUM01" numeric(38, 10), 
                "PER_UDFNUM02" numeric(38, 10), 
                "PER_UDFNUM03" numeric(38, 10), 
                "PER_UDFNUM04" numeric(38, 10), 
                "PER_UDFNUM05" numeric(38, 10), 
                "PER_UPDATECOUNT" numeric(38, 10), 
                "PER_UPDATED" datetime, 
                "PER_UPDATEDBY" varchar, 
                "PER_URL" varchar, 
                "PER_USER" varchar, 
                "PER_WORKSPACEOCCUPANT" varchar, 
                "PER_ZIP" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 