CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5SERVICEPROBLEMCODES_DELETED(
                "SPB_AUTOCREATEWO" varchar, 
                "SPB_AUTOREQUESTCASE" varchar, 
                "SPB_CASECLASS" varchar, 
                "SPB_CASECLASS_ORG" varchar, 
                "SPB_CASEFOLLOWUPREQUIRED" varchar, 
                "SPB_CASEPRIORITY" varchar, 
                "SPB_CASETYPE" varchar, 
                "SPB_CLASS" varchar, 
                "SPB_CLASS_ORG" varchar, 
                "SPB_CODE" varchar, 
                "SPB_COSTCODE" varchar, 
                "SPB_DESC" varchar, 
                "SPB_EQPUSABILITY" varchar, 
                "SPB_EQPUSABILITY_ORG" varchar, 
                "SPB_ESTHOURS" numeric(38, 10), 
                "SPB_FOLLOWUPSERVICECODE" varchar, 
                "SPB_FOLLOWUPSERVICECODE_ORG" varchar, 
                "SPB_FOLLOWUPTIMING" varchar, 
                "SPB_FORFOLLOWUP" varchar, 
                "SPB_GENERAL" varchar, 
                "SPB_HAZARDMATERIAL" varchar, 
                "SPB_JOBPLAN" varchar, 
                "SPB_JOBTYPE" varchar, 
                "SPB_LASTSAVED" datetime, 
                "SPB_NOTUSED" varchar, 
                "SPB_OBJECT" varchar, 
                "SPB_OBJECT_ORG" varchar, 
                "SPB_ORG" varchar, 
                "SPB_PENALTYFACTOR" numeric(38, 10), 
                "SPB_PEOPLEREQ" numeric(38, 10), 
                "SPB_PERMFIXTURNAROUND" numeric(38, 10), 
                "SPB_PERMTURNAROUNDUNIT" varchar, 
                "SPB_PRIORITY" varchar, 
                "SPB_REGULATORY" varchar, 
                "SPB_SERVICEREQUESTPORTAL" varchar, 
                "SPB_STANDWORK" varchar, 
                "SPB_STDRESPTIME" numeric(38, 10), 
                "SPB_STDRESPTIMEUNIT" varchar, 
                "SPB_TASK" varchar, 
                "SPB_TEMPFIXTURNAROUND" numeric(38, 10), 
                "SPB_TEMPTURNAROUNDUNIT" varchar, 
                "SPB_TOTALESTCOST" numeric(38, 10), 
                "SPB_TRADE" varchar, 
                "SPB_UDFCHAR01" varchar, 
                "SPB_UDFCHAR02" varchar, 
                "SPB_UDFCHAR03" varchar, 
                "SPB_UDFCHAR04" varchar, 
                "SPB_UDFCHAR05" varchar, 
                "SPB_UDFCHAR06" varchar, 
                "SPB_UDFCHAR07" varchar, 
                "SPB_UDFCHAR08" varchar, 
                "SPB_UDFCHAR09" varchar, 
                "SPB_UDFCHAR10" varchar, 
                "SPB_UDFCHAR11" varchar, 
                "SPB_UDFCHAR12" varchar, 
                "SPB_UDFCHAR13" varchar, 
                "SPB_UDFCHAR14" varchar, 
                "SPB_UDFCHAR15" varchar, 
                "SPB_UDFCHAR16" varchar, 
                "SPB_UDFCHAR17" varchar, 
                "SPB_UDFCHAR18" varchar, 
                "SPB_UDFCHAR19" varchar, 
                "SPB_UDFCHAR20" varchar, 
                "SPB_UDFCHAR21" varchar, 
                "SPB_UDFCHAR22" varchar, 
                "SPB_UDFCHAR23" varchar, 
                "SPB_UDFCHAR24" varchar, 
                "SPB_UDFCHAR25" varchar, 
                "SPB_UDFCHAR26" varchar, 
                "SPB_UDFCHAR27" varchar, 
                "SPB_UDFCHAR28" varchar, 
                "SPB_UDFCHAR29" varchar, 
                "SPB_UDFCHAR30" varchar, 
                "SPB_UDFCHKBOX01" varchar, 
                "SPB_UDFCHKBOX02" varchar, 
                "SPB_UDFCHKBOX03" varchar, 
                "SPB_UDFCHKBOX04" varchar, 
                "SPB_UDFCHKBOX05" varchar, 
                "SPB_UDFDATE01" datetime, 
                "SPB_UDFDATE02" datetime, 
                "SPB_UDFDATE03" datetime, 
                "SPB_UDFDATE04" datetime, 
                "SPB_UDFDATE05" datetime, 
                "SPB_UDFNUM01" numeric(38, 10), 
                "SPB_UDFNUM02" numeric(38, 10), 
                "SPB_UDFNUM03" numeric(38, 10), 
                "SPB_UDFNUM04" numeric(38, 10), 
                "SPB_UDFNUM05" numeric(38, 10), 
                "SPB_UPDATECOUNT" numeric(38, 10), 
                "SPB_WOCLASS" varchar, 
                "SPB_WOCLASS_ORG" varchar, 
                "SPB_WOSTATUS" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 