create or replace pipe DATAHUB_INTEGRATION.PIPE_EAM_R5MAILURLMAPPING auto_ingest=true as
                         copy into DATAHUB_LANDING.EAM_R5MAILURLMAPPING
                    from (
 SELECT
$1,CURRENT_TIMESTAMP as ETL_LOAD_DATETIME,METADATA$FILENAME as ETL_LOAD_METADATAFILENAME
 FROM @DATAHUB_INTEGRATION.STAGE_EAM_R5MAILURLMAPPING(FILE_FORMAT => json_format));