
                         copy into DATAHUB_LANDING.EAM_R5RELIABILITYRANKINGLEVELS
                    from (
            SELECT
            $1,CURRENT_TIMESTAMP as ETL_LOAD_DATETIME,METADATA$FILENAME as ETL_LOAD_METADATAFILENAME
            FROM @DATAHUB_INTEGRATION.STAGE_EAM_R5RELIABILITYRANKINGLEVELS(FILE_FORMAT => json_format));