CREATE OR REPLACE TABLE DATAHUB_SOURCE_METADATA.MONITORING_REQUIRED_TABLES (
    SOURCE VARCHAR(30),
    TABLE_NAME VARCHAR(100),
    TABLE_DESCRIPTION VARCHAR(100),
    FREQUENCY_DAYS VARCHAR(100)
);