
                    
                create or replace view DATAHUB_TARGET_HISTORY.EAM_R5MAILEVENTS
                   as                       
                    SELECT
                        t.MAE_CODE,
                        t.MAE_TEMPLATE,
                        t.MAE_DATE,
                        t.MAE_SEND,
                        t.MAE_RSTATUS,
                        t.MAE_ERROR,
                        t.MAE_PARAM1,
                        t.MAE_PARAM2,
                        t.MAE_PARAM3,
                        t.MAE_PARAM4,
                        t.MAE_PARAM5,
                        t.MAE_PARAM6,
                        t.MAE_PARAM7,
                        t.MAE_PARAM8,
                        t.MAE_PARAM9,
                        t.MAE_PARAM10,
                        t.MAE_PARAM11,
                        t.MAE_PARAM12,
                        t.MAE_PARAM13,
                        t.MAE_PARAM14,
                        t.MAE_PARAM15,
                        t.MAE_UPDATECOUNT,
                        t.MAE_ATTRIBPK,
                        t.MAE_EWSURL,
                        t.MAE_EMAILRECIPIENT,
                        t.MAE_PTFSEND,
                        t.MAE_PTFERROR,
                        t.MAE_DOCRENTITY,
                        t.MAE_DOCPK,
                        t.MAE_EMAILERRCOUNT,
                        t.MAE_PTFERRCOUNT,
                        t.MAE_LASTSAVED,
                        t.ETL_LASTSAVED,
                        t.ETL_DELETED,
                        t.etl_load_datetime,
                      t.etl_load_metadatafilename
          
                     FROM DATAHUB_TARGET.EAM_R5MAILEVENTS as  t
					 union
					        SELECT
                        th.MAE_CODE,
                        th.MAE_TEMPLATE,
                        th.MAE_DATE,
                        th.MAE_SEND,
                        th.MAE_RSTATUS,
                        th.MAE_ERROR,
                        th.MAE_PARAM1,
                        th.MAE_PARAM2,
                        th.MAE_PARAM3,
                        th.MAE_PARAM4,
                        th.MAE_PARAM5,
                        th.MAE_PARAM6,
                        th.MAE_PARAM7,
                        th.MAE_PARAM8,
                        th.MAE_PARAM9,
                        th.MAE_PARAM10,
                        th.MAE_PARAM11,
                        th.MAE_PARAM12,
                        th.MAE_PARAM13,
                        th.MAE_PARAM14,
                        th.MAE_PARAM15,
                        th.MAE_UPDATECOUNT,
                        th.MAE_ATTRIBPK,
                        th.MAE_EWSURL,
                        th.MAE_EMAILRECIPIENT,
                        th.MAE_PTFSEND,
                        th.MAE_PTFERROR,
                        th.MAE_DOCRENTITY,
                        th.MAE_DOCPK,
                        th.MAE_EMAILERRCOUNT,
                        th.MAE_PTFERRCOUNT,
                        th.MAE_LASTSAVED,
                        th.ETL_LASTSAVED,
                        th.ETL_DELETED,
                        th.etl_load_datetime,
                      th.etl_load_metadatafilename
          
                     FROM DATAHUB_TARGET_HISTORY.EAM_DELETED_R5MAILEVENTS as  th ;
                     