
                    
                create or replace view DATAHUB_TARGET_HISTORY.EAM_R5DDDATASPY
                   as                       
                    SELECT
                        t.DDS_DDSPYNAME,
                        t.DDS_DDSPYID,
                        t.DDS_AUTORUN,
                        t.DDS_SCOPE,
                        t.DDS_ORGANIZATION,
                        t.DDS_UPDATESTAMP,
                        t.DDS_UPDATEBYUSER,
                        t.DDS_CREATEDSTAMP,
                        t.DDS_UPDATEABLE,
                        t.DDS_FILTERSTRXML,
                        t.DDS_SORTSTRXML,
                        t.DDS_FIELDLIST,
                        t.DDS_UPDATECOUNT,
                        t.DDS_DISPLAYROW,
                        t.DDS_OWNER,
                        t.DDS_GRIDID,
                        t.DDS_TYPE,
                        t.DDS_DEFAULTFLAG,
                        t.DDS_FIELDLIST_PORTLET,
                        t.DDS_CLIENTROWS,
                        t.DDS_PORTLETROWS,
                        t.DDS_HINTS,
                        t.DDS_BOTNAME,
                        t.DDS_USERFILTER,
                        t.DDS_SECURITYDATASPY,
                        t.DDS_MEKEY,
                        t.DDS_UPDATED,
                        t.DDS_DDSPYFILTER,
                        t.DDS_GLOBALDATASPY,
                        t.DDS_BLACKLISTVIOLATIONS,
                        t.DDS_LASTSAVED,
                        t.ETL_LASTSAVED,
                        t.ETL_DELETED,
                        t.etl_load_datetime,
                      t.etl_load_metadatafilename
          
                     FROM DATAHUB_TARGET.EAM_R5DDDATASPY as  t
					 union
					        SELECT
                        th.DDS_DDSPYNAME,
                        th.DDS_DDSPYID,
                        th.DDS_AUTORUN,
                        th.DDS_SCOPE,
                        th.DDS_ORGANIZATION,
                        th.DDS_UPDATESTAMP,
                        th.DDS_UPDATEBYUSER,
                        th.DDS_CREATEDSTAMP,
                        th.DDS_UPDATEABLE,
                        th.DDS_FILTERSTRXML,
                        th.DDS_SORTSTRXML,
                        th.DDS_FIELDLIST,
                        th.DDS_UPDATECOUNT,
                        th.DDS_DISPLAYROW,
                        th.DDS_OWNER,
                        th.DDS_GRIDID,
                        th.DDS_TYPE,
                        th.DDS_DEFAULTFLAG,
                        th.DDS_FIELDLIST_PORTLET,
                        th.DDS_CLIENTROWS,
                        th.DDS_PORTLETROWS,
                        th.DDS_HINTS,
                        th.DDS_BOTNAME,
                        th.DDS_USERFILTER,
                        th.DDS_SECURITYDATASPY,
                        th.DDS_MEKEY,
                        th.DDS_UPDATED,
                        th.DDS_DDSPYFILTER,
                        th.DDS_GLOBALDATASPY,
                        th.DDS_BLACKLISTVIOLATIONS,
                        th.DDS_LASTSAVED,
                        th.ETL_LASTSAVED,
                        th.ETL_DELETED,
                        th.etl_load_datetime,
                      th.etl_load_metadatafilename
          
                     FROM DATAHUB_TARGET_HISTORY.EAM_DELETED_R5DDDATASPY as  th ;
                     