create or replace TABLE ETL_LOG_INGESTION_PROCESS (
	LOG_ID NUMBER(38,0) autoincrement,
	PROCESS_EXECUTION_ID NUMBER(38,0) NOT NULL,
	PROCESS_NAME VARCHAR(50) NOT NULL,
	PROCESS_STATUS VARCHAR(20),
	START_DATETIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
	END_DATETIME TIMESTAMP_NTZ(9),
	EXECUTION_MESSAGE VARCHAR(256),
	INSERTED_ROWS NUMBER(38,0),
	UPDATED_ROWS NUMBER(38,0)
);