-- DATAHUB_EXTRACT.IPS_SM_BILLING_EXTRACT_HISTORY definition

create or replace TABLE DATAHUB_EXTRACT.IPS_SM_BILLING_EXTRACT_HISTORY (
    EXTRACT_ID NUMBER(38,0) autoincrement,
	ROUTE VARCHAR(16),
	READING_DATE NUMBER(38,0),
	METER VARCHAR(50),
	REGISTER_NUMBER NUMBER(1,0),
	READING FLOAT,
	READ_TYPE VARCHAR(1),
	REASON_UNREAD VARCHAR(10),
	READER VARCHAR(10),
	NOTES VARCHAR(300),
	READING_TYPE VARCHAR(8),
	ETL_LOAD_DATETIME TIMESTAMP_NTZ(9)
);