CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5ROLES_DELETED(
            ROL_ACTIVE varchar, 
            ROL_ADVREPAUTHOR varchar, 
            ROL_ADVREPCONSUMER varchar, 
            ROL_ANALYTICS varchar, 
            ROL_APPROVER varchar, 
            ROL_BARCODE varchar, 
            ROL_BUYER varchar, 
            ROL_CODE varchar, 
            ROL_CONNECTOR varchar, 
            ROL_DEFAULTORG varchar, 
            ROL_DESC varchar, 
            ROL_EWSFIRSTFUNC varchar, 
            ROL_FIRSTFUNC varchar, 
            ROL_GROUP varchar, 
            ROL_INVAPPVLIMIT numeric(38, 10), 
            ROL_INVAPPVLIMITNONPO numeric(38, 10), 
            ROL_LANG varchar, 
            ROL_LASTSAVED datetime, 
            ROL_LOCALE varchar, 
            ROL_MOBILE varchar, 
            ROL_MOBILEADM varchar, 
            ROL_MRC varchar, 
            ROL_PICAPPVLIMIT numeric(38, 10), 
            ROL_PORDAPPVLIMIT numeric(38, 10), 
            ROL_PORDAUTHAPPVLIMIT numeric(38, 10), 
            ROL_REQAPPVLIMIT numeric(38, 10), 
            ROL_REQAUTHAPPVLIMIT numeric(38, 10), 
            ROL_REQUESTOR varchar, 
            ROL_ROUTER varchar, 
            ROL_SUCCESSMSGTIMEOUT numeric(38, 10), 
            ROL_UPDATECOUNT numeric(38, 10), 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 