CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5DEFAULTPAGELAYOUT_DELETED(
            PLD_ATTRIBUTE varchar, 
            PLD_CASE varchar, 
            PLD_DDFIELDNAME varchar, 
            PLD_DDTABLENAME varchar, 
            PLD_DESTXPATH varchar, 
            PLD_ELEMENTID varchar, 
            PLD_ELEMENTTYPE varchar, 
            PLD_FIELDCONTAINER varchar, 
            PLD_FIELDCONTTYPE numeric(38, 10), 
            PLD_FIELDGROUP numeric(38, 10), 
            PLD_FIELDTYPE varchar, 
            PLD_JSPFILE varchar, 
            PLD_LASTSAVED datetime, 
            PLD_MAXLENGTH numeric(38, 10), 
            PLD_NUMBERTYPE varchar, 
            PLD_ONCHAINEDLOOKUP varchar, 
            PLD_ONCLASSCHANGE varchar, 
            PLD_ONLOOKUP varchar, 
            PLD_ONVALIDATE varchar, 
            PLD_OTHERATTRIBS varchar, 
            PLD_OTHERTAGS varchar, 
            PLD_PAGENAME varchar, 
            PLD_POSITIONINGROUP numeric(38, 10), 
            PLD_PRESENTINJSP varchar, 
            PLD_RESPONSEXPATH varchar, 
            PLD_SIZE numeric(38, 10), 
            PLD_SYSTEMATTRIBUTE varchar, 
            PLD_TABINDEX numeric(38, 10), 
            PLD_UPDATECOUNT numeric(38, 10), 
            PLD_XPATH varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 