create or replace procedure DATAHUB_INTEGRATION.SP_LN_TFGLD008()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TFGLD008_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TFGLD008 as target using (SELECT * FROM (SELECT 
            strm.acmp, 
            strm.acmp_ref_compnr, 
            strm.alat, 
            strm.alat_kw, 
            strm.atyp, 
            strm.atyp_kw, 
            strm.bfdt, 
            strm.blbp, 
            strm.blbp_kw, 
            strm.bloc, 
            strm.bloc_kw, 
            strm.budt, 
            strm.cdca, 
            strm.cdca_ref_compnr, 
            strm.cfic, 
            strm.cfic_ref_compnr, 
            strm.cfrs, 
            strm.cfrs_ref_compnr, 
            strm.compnr, 
            strm.ctar, 
            strm.ctar_kw, 
            strm.ctlm, 
            strm.ctlm_kw, 
            strm.cvat, 
            strm.cvat_ref_compnr, 
            strm.dbcr, 
            strm.dbcr_kw, 
            strm.dblm, 
            strm.dblm_kw, 
            strm.deleted, 
            strm.desc, 
            strm.dga1, 
            strm.dga1_ref_compnr, 
            strm.dga2, 
            strm.dga2_ref_compnr, 
            strm.dim1, 
            strm.dim1_kw, 
            strm.dim2, 
            strm.dim2_kw, 
            strm.dim3, 
            strm.dim3_kw, 
            strm.dim4, 
            strm.dim4_kw, 
            strm.dim5, 
            strm.dim5_kw, 
            strm.dim6, 
            strm.dim6_kw, 
            strm.dim7, 
            strm.dim7_kw, 
            strm.dim8, 
            strm.dim8_kw, 
            strm.dim9, 
            strm.dim9_kw, 
            strm.dla1, 
            strm.dla1_ref_compnr, 
            strm.dla2, 
            strm.dla2_ref_compnr, 
            strm.dm10, 
            strm.dm10_kw, 
            strm.dm11, 
            strm.dm11_kw, 
            strm.dm12, 
            strm.dm12_kw, 
            strm.dmsq, 
            strm.duac, 
            strm.duac_kw, 
            strm.etyp, 
            strm.etyp_kw, 
            strm.icom, 
            strm.icom_kw, 
            strm.icur, 
            strm.icur_kw, 
            strm.ifas, 
            strm.ifas_kw, 
            strm.injb, 
            strm.injb_kw, 
            strm.inta, 
            strm.inta_kw, 
            strm.iprj, 
            strm.iprj_kw, 
            strm.leac, 
            strm.ledc, 
            strm.lela, 
            strm.loco, 
            strm.mach, 
            strm.mach_kw, 
            strm.pcac, 
            strm.pcac_ref_compnr, 
            strm.perc, 
            strm.plac, 
            strm.plac_ref_compnr, 
            strm.pseq, 
            strm.sear, 
            strm.sear_ref_compnr, 
            strm.sequencenumber, 
            strm.skey, 
            strm.subl, 
            strm.tagp, 
            strm.tagp_ref_compnr, 
            strm.text, 
            strm.text_ref_compnr, 
            strm.timestamp, 
            strm.uni1, 
            strm.uni1_ref_compnr, 
            strm.uni2, 
            strm.uni2_ref_compnr, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.leac ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFGLD008 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.leac=src.leac) OR (target.leac IS NULL AND src.leac IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.acmp=src.acmp, 
                    target.acmp_ref_compnr=src.acmp_ref_compnr, 
                    target.alat=src.alat, 
                    target.alat_kw=src.alat_kw, 
                    target.atyp=src.atyp, 
                    target.atyp_kw=src.atyp_kw, 
                    target.bfdt=src.bfdt, 
                    target.blbp=src.blbp, 
                    target.blbp_kw=src.blbp_kw, 
                    target.bloc=src.bloc, 
                    target.bloc_kw=src.bloc_kw, 
                    target.budt=src.budt, 
                    target.cdca=src.cdca, 
                    target.cdca_ref_compnr=src.cdca_ref_compnr, 
                    target.cfic=src.cfic, 
                    target.cfic_ref_compnr=src.cfic_ref_compnr, 
                    target.cfrs=src.cfrs, 
                    target.cfrs_ref_compnr=src.cfrs_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.ctar=src.ctar, 
                    target.ctar_kw=src.ctar_kw, 
                    target.ctlm=src.ctlm, 
                    target.ctlm_kw=src.ctlm_kw, 
                    target.cvat=src.cvat, 
                    target.cvat_ref_compnr=src.cvat_ref_compnr, 
                    target.dbcr=src.dbcr, 
                    target.dbcr_kw=src.dbcr_kw, 
                    target.dblm=src.dblm, 
                    target.dblm_kw=src.dblm_kw, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.dga1=src.dga1, 
                    target.dga1_ref_compnr=src.dga1_ref_compnr, 
                    target.dga2=src.dga2, 
                    target.dga2_ref_compnr=src.dga2_ref_compnr, 
                    target.dim1=src.dim1, 
                    target.dim1_kw=src.dim1_kw, 
                    target.dim2=src.dim2, 
                    target.dim2_kw=src.dim2_kw, 
                    target.dim3=src.dim3, 
                    target.dim3_kw=src.dim3_kw, 
                    target.dim4=src.dim4, 
                    target.dim4_kw=src.dim4_kw, 
                    target.dim5=src.dim5, 
                    target.dim5_kw=src.dim5_kw, 
                    target.dim6=src.dim6, 
                    target.dim6_kw=src.dim6_kw, 
                    target.dim7=src.dim7, 
                    target.dim7_kw=src.dim7_kw, 
                    target.dim8=src.dim8, 
                    target.dim8_kw=src.dim8_kw, 
                    target.dim9=src.dim9, 
                    target.dim9_kw=src.dim9_kw, 
                    target.dla1=src.dla1, 
                    target.dla1_ref_compnr=src.dla1_ref_compnr, 
                    target.dla2=src.dla2, 
                    target.dla2_ref_compnr=src.dla2_ref_compnr, 
                    target.dm10=src.dm10, 
                    target.dm10_kw=src.dm10_kw, 
                    target.dm11=src.dm11, 
                    target.dm11_kw=src.dm11_kw, 
                    target.dm12=src.dm12, 
                    target.dm12_kw=src.dm12_kw, 
                    target.dmsq=src.dmsq, 
                    target.duac=src.duac, 
                    target.duac_kw=src.duac_kw, 
                    target.etyp=src.etyp, 
                    target.etyp_kw=src.etyp_kw, 
                    target.icom=src.icom, 
                    target.icom_kw=src.icom_kw, 
                    target.icur=src.icur, 
                    target.icur_kw=src.icur_kw, 
                    target.ifas=src.ifas, 
                    target.ifas_kw=src.ifas_kw, 
                    target.injb=src.injb, 
                    target.injb_kw=src.injb_kw, 
                    target.inta=src.inta, 
                    target.inta_kw=src.inta_kw, 
                    target.iprj=src.iprj, 
                    target.iprj_kw=src.iprj_kw, 
                    target.leac=src.leac, 
                    target.ledc=src.ledc, 
                    target.lela=src.lela, 
                    target.loco=src.loco, 
                    target.mach=src.mach, 
                    target.mach_kw=src.mach_kw, 
                    target.pcac=src.pcac, 
                    target.pcac_ref_compnr=src.pcac_ref_compnr, 
                    target.perc=src.perc, 
                    target.plac=src.plac, 
                    target.plac_ref_compnr=src.plac_ref_compnr, 
                    target.pseq=src.pseq, 
                    target.sear=src.sear, 
                    target.sear_ref_compnr=src.sear_ref_compnr, 
                    target.sequencenumber=src.sequencenumber, 
                    target.skey=src.skey, 
                    target.subl=src.subl, 
                    target.tagp=src.tagp, 
                    target.tagp_ref_compnr=src.tagp_ref_compnr, 
                    target.text=src.text, 
                    target.text_ref_compnr=src.text_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.uni1=src.uni1, 
                    target.uni1_ref_compnr=src.uni1_ref_compnr, 
                    target.uni2=src.uni2, 
                    target.uni2_ref_compnr=src.uni2_ref_compnr, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    acmp, 
                    acmp_ref_compnr, 
                    alat, 
                    alat_kw, 
                    atyp, 
                    atyp_kw, 
                    bfdt, 
                    blbp, 
                    blbp_kw, 
                    bloc, 
                    bloc_kw, 
                    budt, 
                    cdca, 
                    cdca_ref_compnr, 
                    cfic, 
                    cfic_ref_compnr, 
                    cfrs, 
                    cfrs_ref_compnr, 
                    compnr, 
                    ctar, 
                    ctar_kw, 
                    ctlm, 
                    ctlm_kw, 
                    cvat, 
                    cvat_ref_compnr, 
                    dbcr, 
                    dbcr_kw, 
                    dblm, 
                    dblm_kw, 
                    deleted, 
                    desc, 
                    dga1, 
                    dga1_ref_compnr, 
                    dga2, 
                    dga2_ref_compnr, 
                    dim1, 
                    dim1_kw, 
                    dim2, 
                    dim2_kw, 
                    dim3, 
                    dim3_kw, 
                    dim4, 
                    dim4_kw, 
                    dim5, 
                    dim5_kw, 
                    dim6, 
                    dim6_kw, 
                    dim7, 
                    dim7_kw, 
                    dim8, 
                    dim8_kw, 
                    dim9, 
                    dim9_kw, 
                    dla1, 
                    dla1_ref_compnr, 
                    dla2, 
                    dla2_ref_compnr, 
                    dm10, 
                    dm10_kw, 
                    dm11, 
                    dm11_kw, 
                    dm12, 
                    dm12_kw, 
                    dmsq, 
                    duac, 
                    duac_kw, 
                    etyp, 
                    etyp_kw, 
                    icom, 
                    icom_kw, 
                    icur, 
                    icur_kw, 
                    ifas, 
                    ifas_kw, 
                    injb, 
                    injb_kw, 
                    inta, 
                    inta_kw, 
                    iprj, 
                    iprj_kw, 
                    leac, 
                    ledc, 
                    lela, 
                    loco, 
                    mach, 
                    mach_kw, 
                    pcac, 
                    pcac_ref_compnr, 
                    perc, 
                    plac, 
                    plac_ref_compnr, 
                    pseq, 
                    sear, 
                    sear_ref_compnr, 
                    sequencenumber, 
                    skey, 
                    subl, 
                    tagp, 
                    tagp_ref_compnr, 
                    text, 
                    text_ref_compnr, 
                    timestamp, 
                    uni1, 
                    uni1_ref_compnr, 
                    uni2, 
                    uni2_ref_compnr, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.acmp, 
                    src.acmp_ref_compnr, 
                    src.alat, 
                    src.alat_kw, 
                    src.atyp, 
                    src.atyp_kw, 
                    src.bfdt, 
                    src.blbp, 
                    src.blbp_kw, 
                    src.bloc, 
                    src.bloc_kw, 
                    src.budt, 
                    src.cdca, 
                    src.cdca_ref_compnr, 
                    src.cfic, 
                    src.cfic_ref_compnr, 
                    src.cfrs, 
                    src.cfrs_ref_compnr, 
                    src.compnr, 
                    src.ctar, 
                    src.ctar_kw, 
                    src.ctlm, 
                    src.ctlm_kw, 
                    src.cvat, 
                    src.cvat_ref_compnr, 
                    src.dbcr, 
                    src.dbcr_kw, 
                    src.dblm, 
                    src.dblm_kw, 
                    src.deleted, 
                    src.desc, 
                    src.dga1, 
                    src.dga1_ref_compnr, 
                    src.dga2, 
                    src.dga2_ref_compnr, 
                    src.dim1, 
                    src.dim1_kw, 
                    src.dim2, 
                    src.dim2_kw, 
                    src.dim3, 
                    src.dim3_kw, 
                    src.dim4, 
                    src.dim4_kw, 
                    src.dim5, 
                    src.dim5_kw, 
                    src.dim6, 
                    src.dim6_kw, 
                    src.dim7, 
                    src.dim7_kw, 
                    src.dim8, 
                    src.dim8_kw, 
                    src.dim9, 
                    src.dim9_kw, 
                    src.dla1, 
                    src.dla1_ref_compnr, 
                    src.dla2, 
                    src.dla2_ref_compnr, 
                    src.dm10, 
                    src.dm10_kw, 
                    src.dm11, 
                    src.dm11_kw, 
                    src.dm12, 
                    src.dm12_kw, 
                    src.dmsq, 
                    src.duac, 
                    src.duac_kw, 
                    src.etyp, 
                    src.etyp_kw, 
                    src.icom, 
                    src.icom_kw, 
                    src.icur, 
                    src.icur_kw, 
                    src.ifas, 
                    src.ifas_kw, 
                    src.injb, 
                    src.injb_kw, 
                    src.inta, 
                    src.inta_kw, 
                    src.iprj, 
                    src.iprj_kw, 
                    src.leac, 
                    src.ledc, 
                    src.lela, 
                    src.loco, 
                    src.mach, 
                    src.mach_kw, 
                    src.pcac, 
                    src.pcac_ref_compnr, 
                    src.perc, 
                    src.plac, 
                    src.plac_ref_compnr, 
                    src.pseq, 
                    src.sear, 
                    src.sear_ref_compnr, 
                    src.sequencenumber, 
                    src.skey, 
                    src.subl, 
                    src.tagp, 
                    src.tagp_ref_compnr, 
                    src.text, 
                    src.text_ref_compnr, 
                    src.timestamp, 
                    src.uni1, 
                    src.uni1_ref_compnr, 
                    src.uni2, 
                    src.uni2_ref_compnr, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TFGLD008_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.acmp, 
            strm.acmp_ref_compnr, 
            strm.alat, 
            strm.alat_kw, 
            strm.atyp, 
            strm.atyp_kw, 
            strm.bfdt, 
            strm.blbp, 
            strm.blbp_kw, 
            strm.bloc, 
            strm.bloc_kw, 
            strm.budt, 
            strm.cdca, 
            strm.cdca_ref_compnr, 
            strm.cfic, 
            strm.cfic_ref_compnr, 
            strm.cfrs, 
            strm.cfrs_ref_compnr, 
            strm.compnr, 
            strm.ctar, 
            strm.ctar_kw, 
            strm.ctlm, 
            strm.ctlm_kw, 
            strm.cvat, 
            strm.cvat_ref_compnr, 
            strm.dbcr, 
            strm.dbcr_kw, 
            strm.dblm, 
            strm.dblm_kw, 
            strm.deleted, 
            strm.desc, 
            strm.dga1, 
            strm.dga1_ref_compnr, 
            strm.dga2, 
            strm.dga2_ref_compnr, 
            strm.dim1, 
            strm.dim1_kw, 
            strm.dim2, 
            strm.dim2_kw, 
            strm.dim3, 
            strm.dim3_kw, 
            strm.dim4, 
            strm.dim4_kw, 
            strm.dim5, 
            strm.dim5_kw, 
            strm.dim6, 
            strm.dim6_kw, 
            strm.dim7, 
            strm.dim7_kw, 
            strm.dim8, 
            strm.dim8_kw, 
            strm.dim9, 
            strm.dim9_kw, 
            strm.dla1, 
            strm.dla1_ref_compnr, 
            strm.dla2, 
            strm.dla2_ref_compnr, 
            strm.dm10, 
            strm.dm10_kw, 
            strm.dm11, 
            strm.dm11_kw, 
            strm.dm12, 
            strm.dm12_kw, 
            strm.dmsq, 
            strm.duac, 
            strm.duac_kw, 
            strm.etyp, 
            strm.etyp_kw, 
            strm.icom, 
            strm.icom_kw, 
            strm.icur, 
            strm.icur_kw, 
            strm.ifas, 
            strm.ifas_kw, 
            strm.injb, 
            strm.injb_kw, 
            strm.inta, 
            strm.inta_kw, 
            strm.iprj, 
            strm.iprj_kw, 
            strm.leac, 
            strm.ledc, 
            strm.lela, 
            strm.loco, 
            strm.mach, 
            strm.mach_kw, 
            strm.pcac, 
            strm.pcac_ref_compnr, 
            strm.perc, 
            strm.plac, 
            strm.plac_ref_compnr, 
            strm.pseq, 
            strm.sear, 
            strm.sear_ref_compnr, 
            strm.sequencenumber, 
            strm.skey, 
            strm.subl, 
            strm.tagp, 
            strm.tagp_ref_compnr, 
            strm.text, 
            strm.text_ref_compnr, 
            strm.timestamp, 
            strm.uni1, 
            strm.uni1_ref_compnr, 
            strm.uni2, 
            strm.uni2_ref_compnr, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.leac ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFGLD008 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.leac=src.leac) OR (target.leac IS NULL AND src.leac IS NULL)) 
                when matched then update set
                    target.acmp=src.acmp, 
                    target.acmp_ref_compnr=src.acmp_ref_compnr, 
                    target.alat=src.alat, 
                    target.alat_kw=src.alat_kw, 
                    target.atyp=src.atyp, 
                    target.atyp_kw=src.atyp_kw, 
                    target.bfdt=src.bfdt, 
                    target.blbp=src.blbp, 
                    target.blbp_kw=src.blbp_kw, 
                    target.bloc=src.bloc, 
                    target.bloc_kw=src.bloc_kw, 
                    target.budt=src.budt, 
                    target.cdca=src.cdca, 
                    target.cdca_ref_compnr=src.cdca_ref_compnr, 
                    target.cfic=src.cfic, 
                    target.cfic_ref_compnr=src.cfic_ref_compnr, 
                    target.cfrs=src.cfrs, 
                    target.cfrs_ref_compnr=src.cfrs_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.ctar=src.ctar, 
                    target.ctar_kw=src.ctar_kw, 
                    target.ctlm=src.ctlm, 
                    target.ctlm_kw=src.ctlm_kw, 
                    target.cvat=src.cvat, 
                    target.cvat_ref_compnr=src.cvat_ref_compnr, 
                    target.dbcr=src.dbcr, 
                    target.dbcr_kw=src.dbcr_kw, 
                    target.dblm=src.dblm, 
                    target.dblm_kw=src.dblm_kw, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.dga1=src.dga1, 
                    target.dga1_ref_compnr=src.dga1_ref_compnr, 
                    target.dga2=src.dga2, 
                    target.dga2_ref_compnr=src.dga2_ref_compnr, 
                    target.dim1=src.dim1, 
                    target.dim1_kw=src.dim1_kw, 
                    target.dim2=src.dim2, 
                    target.dim2_kw=src.dim2_kw, 
                    target.dim3=src.dim3, 
                    target.dim3_kw=src.dim3_kw, 
                    target.dim4=src.dim4, 
                    target.dim4_kw=src.dim4_kw, 
                    target.dim5=src.dim5, 
                    target.dim5_kw=src.dim5_kw, 
                    target.dim6=src.dim6, 
                    target.dim6_kw=src.dim6_kw, 
                    target.dim7=src.dim7, 
                    target.dim7_kw=src.dim7_kw, 
                    target.dim8=src.dim8, 
                    target.dim8_kw=src.dim8_kw, 
                    target.dim9=src.dim9, 
                    target.dim9_kw=src.dim9_kw, 
                    target.dla1=src.dla1, 
                    target.dla1_ref_compnr=src.dla1_ref_compnr, 
                    target.dla2=src.dla2, 
                    target.dla2_ref_compnr=src.dla2_ref_compnr, 
                    target.dm10=src.dm10, 
                    target.dm10_kw=src.dm10_kw, 
                    target.dm11=src.dm11, 
                    target.dm11_kw=src.dm11_kw, 
                    target.dm12=src.dm12, 
                    target.dm12_kw=src.dm12_kw, 
                    target.dmsq=src.dmsq, 
                    target.duac=src.duac, 
                    target.duac_kw=src.duac_kw, 
                    target.etyp=src.etyp, 
                    target.etyp_kw=src.etyp_kw, 
                    target.icom=src.icom, 
                    target.icom_kw=src.icom_kw, 
                    target.icur=src.icur, 
                    target.icur_kw=src.icur_kw, 
                    target.ifas=src.ifas, 
                    target.ifas_kw=src.ifas_kw, 
                    target.injb=src.injb, 
                    target.injb_kw=src.injb_kw, 
                    target.inta=src.inta, 
                    target.inta_kw=src.inta_kw, 
                    target.iprj=src.iprj, 
                    target.iprj_kw=src.iprj_kw, 
                    target.leac=src.leac, 
                    target.ledc=src.ledc, 
                    target.lela=src.lela, 
                    target.loco=src.loco, 
                    target.mach=src.mach, 
                    target.mach_kw=src.mach_kw, 
                    target.pcac=src.pcac, 
                    target.pcac_ref_compnr=src.pcac_ref_compnr, 
                    target.perc=src.perc, 
                    target.plac=src.plac, 
                    target.plac_ref_compnr=src.plac_ref_compnr, 
                    target.pseq=src.pseq, 
                    target.sear=src.sear, 
                    target.sear_ref_compnr=src.sear_ref_compnr, 
                    target.sequencenumber=src.sequencenumber, 
                    target.skey=src.skey, 
                    target.subl=src.subl, 
                    target.tagp=src.tagp, 
                    target.tagp_ref_compnr=src.tagp_ref_compnr, 
                    target.text=src.text, 
                    target.text_ref_compnr=src.text_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.uni1=src.uni1, 
                    target.uni1_ref_compnr=src.uni1_ref_compnr, 
                    target.uni2=src.uni2, 
                    target.uni2_ref_compnr=src.uni2_ref_compnr, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( acmp, acmp_ref_compnr, alat, alat_kw, atyp, atyp_kw, bfdt, blbp, blbp_kw, bloc, bloc_kw, budt, cdca, cdca_ref_compnr, cfic, cfic_ref_compnr, cfrs, cfrs_ref_compnr, compnr, ctar, ctar_kw, ctlm, ctlm_kw, cvat, cvat_ref_compnr, dbcr, dbcr_kw, dblm, dblm_kw, deleted, desc, dga1, dga1_ref_compnr, dga2, dga2_ref_compnr, dim1, dim1_kw, dim2, dim2_kw, dim3, dim3_kw, dim4, dim4_kw, dim5, dim5_kw, dim6, dim6_kw, dim7, dim7_kw, dim8, dim8_kw, dim9, dim9_kw, dla1, dla1_ref_compnr, dla2, dla2_ref_compnr, dm10, dm10_kw, dm11, dm11_kw, dm12, dm12_kw, dmsq, duac, duac_kw, etyp, etyp_kw, icom, icom_kw, icur, icur_kw, ifas, ifas_kw, injb, injb_kw, inta, inta_kw, iprj, iprj_kw, leac, ledc, lela, loco, mach, mach_kw, pcac, pcac_ref_compnr, perc, plac, plac_ref_compnr, pseq, sear, sear_ref_compnr, sequencenumber, skey, subl, tagp, tagp_ref_compnr, text, text_ref_compnr, timestamp, uni1, uni1_ref_compnr, uni2, uni2_ref_compnr, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.acmp, 
                    src.acmp_ref_compnr, 
                    src.alat, 
                    src.alat_kw, 
                    src.atyp, 
                    src.atyp_kw, 
                    src.bfdt, 
                    src.blbp, 
                    src.blbp_kw, 
                    src.bloc, 
                    src.bloc_kw, 
                    src.budt, 
                    src.cdca, 
                    src.cdca_ref_compnr, 
                    src.cfic, 
                    src.cfic_ref_compnr, 
                    src.cfrs, 
                    src.cfrs_ref_compnr, 
                    src.compnr, 
                    src.ctar, 
                    src.ctar_kw, 
                    src.ctlm, 
                    src.ctlm_kw, 
                    src.cvat, 
                    src.cvat_ref_compnr, 
                    src.dbcr, 
                    src.dbcr_kw, 
                    src.dblm, 
                    src.dblm_kw, 
                    src.deleted, 
                    src.desc, 
                    src.dga1, 
                    src.dga1_ref_compnr, 
                    src.dga2, 
                    src.dga2_ref_compnr, 
                    src.dim1, 
                    src.dim1_kw, 
                    src.dim2, 
                    src.dim2_kw, 
                    src.dim3, 
                    src.dim3_kw, 
                    src.dim4, 
                    src.dim4_kw, 
                    src.dim5, 
                    src.dim5_kw, 
                    src.dim6, 
                    src.dim6_kw, 
                    src.dim7, 
                    src.dim7_kw, 
                    src.dim8, 
                    src.dim8_kw, 
                    src.dim9, 
                    src.dim9_kw, 
                    src.dla1, 
                    src.dla1_ref_compnr, 
                    src.dla2, 
                    src.dla2_ref_compnr, 
                    src.dm10, 
                    src.dm10_kw, 
                    src.dm11, 
                    src.dm11_kw, 
                    src.dm12, 
                    src.dm12_kw, 
                    src.dmsq, 
                    src.duac, 
                    src.duac_kw, 
                    src.etyp, 
                    src.etyp_kw, 
                    src.icom, 
                    src.icom_kw, 
                    src.icur, 
                    src.icur_kw, 
                    src.ifas, 
                    src.ifas_kw, 
                    src.injb, 
                    src.injb_kw, 
                    src.inta, 
                    src.inta_kw, 
                    src.iprj, 
                    src.iprj_kw, 
                    src.leac, 
                    src.ledc, 
                    src.lela, 
                    src.loco, 
                    src.mach, 
                    src.mach_kw, 
                    src.pcac, 
                    src.pcac_ref_compnr, 
                    src.perc, 
                    src.plac, 
                    src.plac_ref_compnr, 
                    src.pseq, 
                    src.sear, 
                    src.sear_ref_compnr, 
                    src.sequencenumber, 
                    src.skey, 
                    src.subl, 
                    src.tagp, 
                    src.tagp_ref_compnr, 
                    src.text, 
                    src.text_ref_compnr, 
                    src.timestamp, 
                    src.uni1, 
                    src.uni1_ref_compnr, 
                    src.uni2, 
                    src.uni2_ref_compnr, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;