create or replace procedure DATAHUB_INTEGRATION.SP_LN_TDISA001()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TDISA001_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TDISA001 as target using (SELECT * FROM (SELECT 
            strm.acci, 
            strm.acci_kw, 
            strm.acom, 
            strm.acom_kw, 
            strm.actn, 
            strm.actn_kw, 
            strm.afrb, 
            strm.afrb_kw, 
            strm.alod, 
            strm.alod_kw, 
            strm.bfbp, 
            strm.bfbp_ref_compnr, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.cmgp, 
            strm.cmgp_ref_compnr, 
            strm.cncd, 
            strm.compnr, 
            strm.cpgs, 
            strm.cpgs_ref_compnr, 
            strm.cphl, 
            strm.cphl_kw, 
            strm.csgs, 
            strm.csgs_ref_compnr, 
            strm.cups, 
            strm.cups_ref_compnr, 
            strm.cuqi, 
            strm.cuqi_ref_compnr, 
            strm.cuqs, 
            strm.cuqs_ref_compnr, 
            strm.cvat, 
            strm.cvat_ref_compnr, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.deleted, 
            strm.item, 
            strm.item_ref_compnr, 
            strm.item_sfsi_ref_compnr, 
            strm.lcmp, 
            strm.lcmp_ref_compnr, 
            strm.lmsp, 
            strm.ltsp, 
            strm.mmtl, 
            strm.mmtp, 
            strm.mnra, 
            strm.prir, 
            strm.pris, 
            strm.pris_dtwc, 
            strm.pris_lclc, 
            strm.pris_rfrc, 
            strm.pris_rpc1, 
            strm.pris_rpc2, 
            strm.qidd, 
            strm.qimc, 
            strm.qimo, 
            strm.qpdd, 
            strm.qpmo, 
            strm.rbgp, 
            strm.rbgp_ref_compnr, 
            strm.rcom, 
            strm.rcom_kw, 
            strm.retw, 
            strm.retw_kw, 
            strm.scon, 
            strm.scon_kw, 
            strm.seak, 
            strm.sequencenumber, 
            strm.sfbp, 
            strm.sfbp_ref_compnr, 
            strm.sfsi, 
            strm.sfsi_ref_compnr, 
            strm.timestamp, 
            strm.tltp, 
            strm.tltp_kw, 
            strm.txts, 
            strm.txts_ref_compnr, 
            strm.umsp, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.item ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDISA001 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.item=src.item) OR (target.item IS NULL AND src.item IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.acci=src.acci, 
                    target.acci_kw=src.acci_kw, 
                    target.acom=src.acom, 
                    target.acom_kw=src.acom_kw, 
                    target.actn=src.actn, 
                    target.actn_kw=src.actn_kw, 
                    target.afrb=src.afrb, 
                    target.afrb_kw=src.afrb_kw, 
                    target.alod=src.alod, 
                    target.alod_kw=src.alod_kw, 
                    target.bfbp=src.bfbp, 
                    target.bfbp_ref_compnr=src.bfbp_ref_compnr, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.cmgp=src.cmgp, 
                    target.cmgp_ref_compnr=src.cmgp_ref_compnr, 
                    target.cncd=src.cncd, 
                    target.compnr=src.compnr, 
                    target.cpgs=src.cpgs, 
                    target.cpgs_ref_compnr=src.cpgs_ref_compnr, 
                    target.cphl=src.cphl, 
                    target.cphl_kw=src.cphl_kw, 
                    target.csgs=src.csgs, 
                    target.csgs_ref_compnr=src.csgs_ref_compnr, 
                    target.cups=src.cups, 
                    target.cups_ref_compnr=src.cups_ref_compnr, 
                    target.cuqi=src.cuqi, 
                    target.cuqi_ref_compnr=src.cuqi_ref_compnr, 
                    target.cuqs=src.cuqs, 
                    target.cuqs_ref_compnr=src.cuqs_ref_compnr, 
                    target.cvat=src.cvat, 
                    target.cvat_ref_compnr=src.cvat_ref_compnr, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.item=src.item, 
                    target.item_ref_compnr=src.item_ref_compnr, 
                    target.item_sfsi_ref_compnr=src.item_sfsi_ref_compnr, 
                    target.lcmp=src.lcmp, 
                    target.lcmp_ref_compnr=src.lcmp_ref_compnr, 
                    target.lmsp=src.lmsp, 
                    target.ltsp=src.ltsp, 
                    target.mmtl=src.mmtl, 
                    target.mmtp=src.mmtp, 
                    target.mnra=src.mnra, 
                    target.prir=src.prir, 
                    target.pris=src.pris, 
                    target.pris_dtwc=src.pris_dtwc, 
                    target.pris_lclc=src.pris_lclc, 
                    target.pris_rfrc=src.pris_rfrc, 
                    target.pris_rpc1=src.pris_rpc1, 
                    target.pris_rpc2=src.pris_rpc2, 
                    target.qidd=src.qidd, 
                    target.qimc=src.qimc, 
                    target.qimo=src.qimo, 
                    target.qpdd=src.qpdd, 
                    target.qpmo=src.qpmo, 
                    target.rbgp=src.rbgp, 
                    target.rbgp_ref_compnr=src.rbgp_ref_compnr, 
                    target.rcom=src.rcom, 
                    target.rcom_kw=src.rcom_kw, 
                    target.retw=src.retw, 
                    target.retw_kw=src.retw_kw, 
                    target.scon=src.scon, 
                    target.scon_kw=src.scon_kw, 
                    target.seak=src.seak, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sfbp=src.sfbp, 
                    target.sfbp_ref_compnr=src.sfbp_ref_compnr, 
                    target.sfsi=src.sfsi, 
                    target.sfsi_ref_compnr=src.sfsi_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.tltp=src.tltp, 
                    target.tltp_kw=src.tltp_kw, 
                    target.txts=src.txts, 
                    target.txts_ref_compnr=src.txts_ref_compnr, 
                    target.umsp=src.umsp, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    acci, 
                    acci_kw, 
                    acom, 
                    acom_kw, 
                    actn, 
                    actn_kw, 
                    afrb, 
                    afrb_kw, 
                    alod, 
                    alod_kw, 
                    bfbp, 
                    bfbp_ref_compnr, 
                    ccur, 
                    ccur_ref_compnr, 
                    cmgp, 
                    cmgp_ref_compnr, 
                    cncd, 
                    compnr, 
                    cpgs, 
                    cpgs_ref_compnr, 
                    cphl, 
                    cphl_kw, 
                    csgs, 
                    csgs_ref_compnr, 
                    cups, 
                    cups_ref_compnr, 
                    cuqi, 
                    cuqi_ref_compnr, 
                    cuqs, 
                    cuqs_ref_compnr, 
                    cvat, 
                    cvat_ref_compnr, 
                    cwar, 
                    cwar_ref_compnr, 
                    deleted, 
                    item, 
                    item_ref_compnr, 
                    item_sfsi_ref_compnr, 
                    lcmp, 
                    lcmp_ref_compnr, 
                    lmsp, 
                    ltsp, 
                    mmtl, 
                    mmtp, 
                    mnra, 
                    prir, 
                    pris, 
                    pris_dtwc, 
                    pris_lclc, 
                    pris_rfrc, 
                    pris_rpc1, 
                    pris_rpc2, 
                    qidd, 
                    qimc, 
                    qimo, 
                    qpdd, 
                    qpmo, 
                    rbgp, 
                    rbgp_ref_compnr, 
                    rcom, 
                    rcom_kw, 
                    retw, 
                    retw_kw, 
                    scon, 
                    scon_kw, 
                    seak, 
                    sequencenumber, 
                    sfbp, 
                    sfbp_ref_compnr, 
                    sfsi, 
                    sfsi_ref_compnr, 
                    timestamp, 
                    tltp, 
                    tltp_kw, 
                    txts, 
                    txts_ref_compnr, 
                    umsp, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.acci, 
                    src.acci_kw, 
                    src.acom, 
                    src.acom_kw, 
                    src.actn, 
                    src.actn_kw, 
                    src.afrb, 
                    src.afrb_kw, 
                    src.alod, 
                    src.alod_kw, 
                    src.bfbp, 
                    src.bfbp_ref_compnr, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.cmgp, 
                    src.cmgp_ref_compnr, 
                    src.cncd, 
                    src.compnr, 
                    src.cpgs, 
                    src.cpgs_ref_compnr, 
                    src.cphl, 
                    src.cphl_kw, 
                    src.csgs, 
                    src.csgs_ref_compnr, 
                    src.cups, 
                    src.cups_ref_compnr, 
                    src.cuqi, 
                    src.cuqi_ref_compnr, 
                    src.cuqs, 
                    src.cuqs_ref_compnr, 
                    src.cvat, 
                    src.cvat_ref_compnr, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.deleted, 
                    src.item, 
                    src.item_ref_compnr, 
                    src.item_sfsi_ref_compnr, 
                    src.lcmp, 
                    src.lcmp_ref_compnr, 
                    src.lmsp, 
                    src.ltsp, 
                    src.mmtl, 
                    src.mmtp, 
                    src.mnra, 
                    src.prir, 
                    src.pris, 
                    src.pris_dtwc, 
                    src.pris_lclc, 
                    src.pris_rfrc, 
                    src.pris_rpc1, 
                    src.pris_rpc2, 
                    src.qidd, 
                    src.qimc, 
                    src.qimo, 
                    src.qpdd, 
                    src.qpmo, 
                    src.rbgp, 
                    src.rbgp_ref_compnr, 
                    src.rcom, 
                    src.rcom_kw, 
                    src.retw, 
                    src.retw_kw, 
                    src.scon, 
                    src.scon_kw, 
                    src.seak, 
                    src.sequencenumber, 
                    src.sfbp, 
                    src.sfbp_ref_compnr, 
                    src.sfsi, 
                    src.sfsi_ref_compnr, 
                    src.timestamp, 
                    src.tltp, 
                    src.tltp_kw, 
                    src.txts, 
                    src.txts_ref_compnr, 
                    src.umsp, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TDISA001_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.acci, 
            strm.acci_kw, 
            strm.acom, 
            strm.acom_kw, 
            strm.actn, 
            strm.actn_kw, 
            strm.afrb, 
            strm.afrb_kw, 
            strm.alod, 
            strm.alod_kw, 
            strm.bfbp, 
            strm.bfbp_ref_compnr, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.cmgp, 
            strm.cmgp_ref_compnr, 
            strm.cncd, 
            strm.compnr, 
            strm.cpgs, 
            strm.cpgs_ref_compnr, 
            strm.cphl, 
            strm.cphl_kw, 
            strm.csgs, 
            strm.csgs_ref_compnr, 
            strm.cups, 
            strm.cups_ref_compnr, 
            strm.cuqi, 
            strm.cuqi_ref_compnr, 
            strm.cuqs, 
            strm.cuqs_ref_compnr, 
            strm.cvat, 
            strm.cvat_ref_compnr, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.deleted, 
            strm.item, 
            strm.item_ref_compnr, 
            strm.item_sfsi_ref_compnr, 
            strm.lcmp, 
            strm.lcmp_ref_compnr, 
            strm.lmsp, 
            strm.ltsp, 
            strm.mmtl, 
            strm.mmtp, 
            strm.mnra, 
            strm.prir, 
            strm.pris, 
            strm.pris_dtwc, 
            strm.pris_lclc, 
            strm.pris_rfrc, 
            strm.pris_rpc1, 
            strm.pris_rpc2, 
            strm.qidd, 
            strm.qimc, 
            strm.qimo, 
            strm.qpdd, 
            strm.qpmo, 
            strm.rbgp, 
            strm.rbgp_ref_compnr, 
            strm.rcom, 
            strm.rcom_kw, 
            strm.retw, 
            strm.retw_kw, 
            strm.scon, 
            strm.scon_kw, 
            strm.seak, 
            strm.sequencenumber, 
            strm.sfbp, 
            strm.sfbp_ref_compnr, 
            strm.sfsi, 
            strm.sfsi_ref_compnr, 
            strm.timestamp, 
            strm.tltp, 
            strm.tltp_kw, 
            strm.txts, 
            strm.txts_ref_compnr, 
            strm.umsp, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.item ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDISA001 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.item=src.item) OR (target.item IS NULL AND src.item IS NULL)) 
                when matched then update set
                    target.acci=src.acci, 
                    target.acci_kw=src.acci_kw, 
                    target.acom=src.acom, 
                    target.acom_kw=src.acom_kw, 
                    target.actn=src.actn, 
                    target.actn_kw=src.actn_kw, 
                    target.afrb=src.afrb, 
                    target.afrb_kw=src.afrb_kw, 
                    target.alod=src.alod, 
                    target.alod_kw=src.alod_kw, 
                    target.bfbp=src.bfbp, 
                    target.bfbp_ref_compnr=src.bfbp_ref_compnr, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.cmgp=src.cmgp, 
                    target.cmgp_ref_compnr=src.cmgp_ref_compnr, 
                    target.cncd=src.cncd, 
                    target.compnr=src.compnr, 
                    target.cpgs=src.cpgs, 
                    target.cpgs_ref_compnr=src.cpgs_ref_compnr, 
                    target.cphl=src.cphl, 
                    target.cphl_kw=src.cphl_kw, 
                    target.csgs=src.csgs, 
                    target.csgs_ref_compnr=src.csgs_ref_compnr, 
                    target.cups=src.cups, 
                    target.cups_ref_compnr=src.cups_ref_compnr, 
                    target.cuqi=src.cuqi, 
                    target.cuqi_ref_compnr=src.cuqi_ref_compnr, 
                    target.cuqs=src.cuqs, 
                    target.cuqs_ref_compnr=src.cuqs_ref_compnr, 
                    target.cvat=src.cvat, 
                    target.cvat_ref_compnr=src.cvat_ref_compnr, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.item=src.item, 
                    target.item_ref_compnr=src.item_ref_compnr, 
                    target.item_sfsi_ref_compnr=src.item_sfsi_ref_compnr, 
                    target.lcmp=src.lcmp, 
                    target.lcmp_ref_compnr=src.lcmp_ref_compnr, 
                    target.lmsp=src.lmsp, 
                    target.ltsp=src.ltsp, 
                    target.mmtl=src.mmtl, 
                    target.mmtp=src.mmtp, 
                    target.mnra=src.mnra, 
                    target.prir=src.prir, 
                    target.pris=src.pris, 
                    target.pris_dtwc=src.pris_dtwc, 
                    target.pris_lclc=src.pris_lclc, 
                    target.pris_rfrc=src.pris_rfrc, 
                    target.pris_rpc1=src.pris_rpc1, 
                    target.pris_rpc2=src.pris_rpc2, 
                    target.qidd=src.qidd, 
                    target.qimc=src.qimc, 
                    target.qimo=src.qimo, 
                    target.qpdd=src.qpdd, 
                    target.qpmo=src.qpmo, 
                    target.rbgp=src.rbgp, 
                    target.rbgp_ref_compnr=src.rbgp_ref_compnr, 
                    target.rcom=src.rcom, 
                    target.rcom_kw=src.rcom_kw, 
                    target.retw=src.retw, 
                    target.retw_kw=src.retw_kw, 
                    target.scon=src.scon, 
                    target.scon_kw=src.scon_kw, 
                    target.seak=src.seak, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sfbp=src.sfbp, 
                    target.sfbp_ref_compnr=src.sfbp_ref_compnr, 
                    target.sfsi=src.sfsi, 
                    target.sfsi_ref_compnr=src.sfsi_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.tltp=src.tltp, 
                    target.tltp_kw=src.tltp_kw, 
                    target.txts=src.txts, 
                    target.txts_ref_compnr=src.txts_ref_compnr, 
                    target.umsp=src.umsp, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( acci, acci_kw, acom, acom_kw, actn, actn_kw, afrb, afrb_kw, alod, alod_kw, bfbp, bfbp_ref_compnr, ccur, ccur_ref_compnr, cmgp, cmgp_ref_compnr, cncd, compnr, cpgs, cpgs_ref_compnr, cphl, cphl_kw, csgs, csgs_ref_compnr, cups, cups_ref_compnr, cuqi, cuqi_ref_compnr, cuqs, cuqs_ref_compnr, cvat, cvat_ref_compnr, cwar, cwar_ref_compnr, deleted, item, item_ref_compnr, item_sfsi_ref_compnr, lcmp, lcmp_ref_compnr, lmsp, ltsp, mmtl, mmtp, mnra, prir, pris, pris_dtwc, pris_lclc, pris_rfrc, pris_rpc1, pris_rpc2, qidd, qimc, qimo, qpdd, qpmo, rbgp, rbgp_ref_compnr, rcom, rcom_kw, retw, retw_kw, scon, scon_kw, seak, sequencenumber, sfbp, sfbp_ref_compnr, sfsi, sfsi_ref_compnr, timestamp, tltp, tltp_kw, txts, txts_ref_compnr, umsp, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.acci, 
                    src.acci_kw, 
                    src.acom, 
                    src.acom_kw, 
                    src.actn, 
                    src.actn_kw, 
                    src.afrb, 
                    src.afrb_kw, 
                    src.alod, 
                    src.alod_kw, 
                    src.bfbp, 
                    src.bfbp_ref_compnr, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.cmgp, 
                    src.cmgp_ref_compnr, 
                    src.cncd, 
                    src.compnr, 
                    src.cpgs, 
                    src.cpgs_ref_compnr, 
                    src.cphl, 
                    src.cphl_kw, 
                    src.csgs, 
                    src.csgs_ref_compnr, 
                    src.cups, 
                    src.cups_ref_compnr, 
                    src.cuqi, 
                    src.cuqi_ref_compnr, 
                    src.cuqs, 
                    src.cuqs_ref_compnr, 
                    src.cvat, 
                    src.cvat_ref_compnr, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.deleted, 
                    src.item, 
                    src.item_ref_compnr, 
                    src.item_sfsi_ref_compnr, 
                    src.lcmp, 
                    src.lcmp_ref_compnr, 
                    src.lmsp, 
                    src.ltsp, 
                    src.mmtl, 
                    src.mmtp, 
                    src.mnra, 
                    src.prir, 
                    src.pris, 
                    src.pris_dtwc, 
                    src.pris_lclc, 
                    src.pris_rfrc, 
                    src.pris_rpc1, 
                    src.pris_rpc2, 
                    src.qidd, 
                    src.qimc, 
                    src.qimo, 
                    src.qpdd, 
                    src.qpmo, 
                    src.rbgp, 
                    src.rbgp_ref_compnr, 
                    src.rcom, 
                    src.rcom_kw, 
                    src.retw, 
                    src.retw_kw, 
                    src.scon, 
                    src.scon_kw, 
                    src.seak, 
                    src.sequencenumber, 
                    src.sfbp, 
                    src.sfbp_ref_compnr, 
                    src.sfsi, 
                    src.sfsi_ref_compnr, 
                    src.timestamp, 
                    src.tltp, 
                    src.tltp_kw, 
                    src.txts, 
                    src.txts_ref_compnr, 
                    src.umsp, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;