create or replace procedure DATAHUB_INTEGRATION.SP_LN_TPPDM001()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TPPDM001_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TPPDM001 as target using (SELECT * FROM (SELECT 
            strm.aagt, 
            strm.aagt_kw, 
            strm.asct, 
            strm.asct_kw, 
            strm.cact, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.cpla, 
            strm.cprj, 
            strm.cprj_cpla_cact_ref_compnr, 
            strm.cprj_cpla_ref_compnr, 
            strm.cprj_ref_compnr, 
            strm.cprj_vers_ref_compnr, 
            strm.cspa, 
            strm.cspa_ref_compnr, 
            strm.ctng, 
            strm.ctng_ctsr_ref_compnr, 
            strm.ctng_ref_compnr, 
            strm.ctsr, 
            strm.dcty, 
            strm.dcty_kw, 
            strm.deleted, 
            strm.delt, 
            strm.delt_kw, 
            strm.dfet, 
            strm.dfet_kw, 
            strm.dflv, 
            strm.dflv_kw, 
            strm.dsct, 
            strm.dsct_kw, 
            strm.erng, 
            strm.erng_ersr_ref_compnr, 
            strm.erng_ref_compnr, 
            strm.ersr, 
            strm.ests, 
            strm.loco, 
            strm.mnvf, 
            strm.mnvf_kw, 
            strm.mpvw, 
            strm.mpvw_kw, 
            strm.ngrp, 
            strm.ngrp_ests_ref_compnr, 
            strm.ngrp_prsr_ref_compnr, 
            strm.ngrp_ref_compnr, 
            strm.olvl, 
            strm.potp, 
            strm.potp_ref_compnr, 
            strm.prim, 
            strm.prim_kw, 
            strm.prsr, 
            strm.pung, 
            strm.pung_pusr_ref_compnr, 
            strm.pung_ref_compnr, 
            strm.pusr, 
            strm.rlcr, 
            strm.rlcr_kw, 
            strm.rlgn, 
            strm.rlgn_kw, 
            strm.sequencenumber, 
            strm.serr, 
            strm.song, 
            strm.song_ref_compnr, 
            strm.song_sosr_ref_compnr, 
            strm.sosr, 
            strm.tgrp, 
            strm.tgrp_ref_compnr, 
            strm.tgrp_tpsr_ref_compnr, 
            strm.timestamp, 
            strm.tprf, 
            strm.tprf_kw, 
            strm.tpsr, 
            strm.tpte, 
            strm.tpte_ref_compnr, 
            strm.udac, 
            strm.udac_kw, 
            strm.udev, 
            strm.udev_kw, 
            strm.udpl, 
            strm.udpl_kw, 
            strm.udpr, 
            strm.udpr_kw, 
            strm.udsp, 
            strm.udsp_kw, 
            strm.username, 
            strm.vers, 
            strm.whng, 
            strm.whng_ref_compnr, 
            strm.whng_whsr_ref_compnr, 
            strm.whsr, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.loco ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPDM001 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.loco=src.loco) OR (target.loco IS NULL AND src.loco IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.aagt=src.aagt, 
                    target.aagt_kw=src.aagt_kw, 
                    target.asct=src.asct, 
                    target.asct_kw=src.asct_kw, 
                    target.cact=src.cact, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cpla=src.cpla, 
                    target.cprj=src.cprj, 
                    target.cprj_cpla_cact_ref_compnr=src.cprj_cpla_cact_ref_compnr, 
                    target.cprj_cpla_ref_compnr=src.cprj_cpla_ref_compnr, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cprj_vers_ref_compnr=src.cprj_vers_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cspa_ref_compnr=src.cspa_ref_compnr, 
                    target.ctng=src.ctng, 
                    target.ctng_ctsr_ref_compnr=src.ctng_ctsr_ref_compnr, 
                    target.ctng_ref_compnr=src.ctng_ref_compnr, 
                    target.ctsr=src.ctsr, 
                    target.dcty=src.dcty, 
                    target.dcty_kw=src.dcty_kw, 
                    target.deleted=src.deleted, 
                    target.delt=src.delt, 
                    target.delt_kw=src.delt_kw, 
                    target.dfet=src.dfet, 
                    target.dfet_kw=src.dfet_kw, 
                    target.dflv=src.dflv, 
                    target.dflv_kw=src.dflv_kw, 
                    target.dsct=src.dsct, 
                    target.dsct_kw=src.dsct_kw, 
                    target.erng=src.erng, 
                    target.erng_ersr_ref_compnr=src.erng_ersr_ref_compnr, 
                    target.erng_ref_compnr=src.erng_ref_compnr, 
                    target.ersr=src.ersr, 
                    target.ests=src.ests, 
                    target.loco=src.loco, 
                    target.mnvf=src.mnvf, 
                    target.mnvf_kw=src.mnvf_kw, 
                    target.mpvw=src.mpvw, 
                    target.mpvw_kw=src.mpvw_kw, 
                    target.ngrp=src.ngrp, 
                    target.ngrp_ests_ref_compnr=src.ngrp_ests_ref_compnr, 
                    target.ngrp_prsr_ref_compnr=src.ngrp_prsr_ref_compnr, 
                    target.ngrp_ref_compnr=src.ngrp_ref_compnr, 
                    target.olvl=src.olvl, 
                    target.potp=src.potp, 
                    target.potp_ref_compnr=src.potp_ref_compnr, 
                    target.prim=src.prim, 
                    target.prim_kw=src.prim_kw, 
                    target.prsr=src.prsr, 
                    target.pung=src.pung, 
                    target.pung_pusr_ref_compnr=src.pung_pusr_ref_compnr, 
                    target.pung_ref_compnr=src.pung_ref_compnr, 
                    target.pusr=src.pusr, 
                    target.rlcr=src.rlcr, 
                    target.rlcr_kw=src.rlcr_kw, 
                    target.rlgn=src.rlgn, 
                    target.rlgn_kw=src.rlgn_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.serr=src.serr, 
                    target.song=src.song, 
                    target.song_ref_compnr=src.song_ref_compnr, 
                    target.song_sosr_ref_compnr=src.song_sosr_ref_compnr, 
                    target.sosr=src.sosr, 
                    target.tgrp=src.tgrp, 
                    target.tgrp_ref_compnr=src.tgrp_ref_compnr, 
                    target.tgrp_tpsr_ref_compnr=src.tgrp_tpsr_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.tprf=src.tprf, 
                    target.tprf_kw=src.tprf_kw, 
                    target.tpsr=src.tpsr, 
                    target.tpte=src.tpte, 
                    target.tpte_ref_compnr=src.tpte_ref_compnr, 
                    target.udac=src.udac, 
                    target.udac_kw=src.udac_kw, 
                    target.udev=src.udev, 
                    target.udev_kw=src.udev_kw, 
                    target.udpl=src.udpl, 
                    target.udpl_kw=src.udpl_kw, 
                    target.udpr=src.udpr, 
                    target.udpr_kw=src.udpr_kw, 
                    target.udsp=src.udsp, 
                    target.udsp_kw=src.udsp_kw, 
                    target.username=src.username, 
                    target.vers=src.vers, 
                    target.whng=src.whng, 
                    target.whng_ref_compnr=src.whng_ref_compnr, 
                    target.whng_whsr_ref_compnr=src.whng_whsr_ref_compnr, 
                    target.whsr=src.whsr, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    aagt, 
                    aagt_kw, 
                    asct, 
                    asct_kw, 
                    cact, 
                    cofc, 
                    cofc_ref_compnr, 
                    compnr, 
                    cpla, 
                    cprj, 
                    cprj_cpla_cact_ref_compnr, 
                    cprj_cpla_ref_compnr, 
                    cprj_ref_compnr, 
                    cprj_vers_ref_compnr, 
                    cspa, 
                    cspa_ref_compnr, 
                    ctng, 
                    ctng_ctsr_ref_compnr, 
                    ctng_ref_compnr, 
                    ctsr, 
                    dcty, 
                    dcty_kw, 
                    deleted, 
                    delt, 
                    delt_kw, 
                    dfet, 
                    dfet_kw, 
                    dflv, 
                    dflv_kw, 
                    dsct, 
                    dsct_kw, 
                    erng, 
                    erng_ersr_ref_compnr, 
                    erng_ref_compnr, 
                    ersr, 
                    ests, 
                    loco, 
                    mnvf, 
                    mnvf_kw, 
                    mpvw, 
                    mpvw_kw, 
                    ngrp, 
                    ngrp_ests_ref_compnr, 
                    ngrp_prsr_ref_compnr, 
                    ngrp_ref_compnr, 
                    olvl, 
                    potp, 
                    potp_ref_compnr, 
                    prim, 
                    prim_kw, 
                    prsr, 
                    pung, 
                    pung_pusr_ref_compnr, 
                    pung_ref_compnr, 
                    pusr, 
                    rlcr, 
                    rlcr_kw, 
                    rlgn, 
                    rlgn_kw, 
                    sequencenumber, 
                    serr, 
                    song, 
                    song_ref_compnr, 
                    song_sosr_ref_compnr, 
                    sosr, 
                    tgrp, 
                    tgrp_ref_compnr, 
                    tgrp_tpsr_ref_compnr, 
                    timestamp, 
                    tprf, 
                    tprf_kw, 
                    tpsr, 
                    tpte, 
                    tpte_ref_compnr, 
                    udac, 
                    udac_kw, 
                    udev, 
                    udev_kw, 
                    udpl, 
                    udpl_kw, 
                    udpr, 
                    udpr_kw, 
                    udsp, 
                    udsp_kw, 
                    username, 
                    vers, 
                    whng, 
                    whng_ref_compnr, 
                    whng_whsr_ref_compnr, 
                    whsr, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.aagt, 
                    src.aagt_kw, 
                    src.asct, 
                    src.asct_kw, 
                    src.cact, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.cpla, 
                    src.cprj, 
                    src.cprj_cpla_cact_ref_compnr, 
                    src.cprj_cpla_ref_compnr, 
                    src.cprj_ref_compnr, 
                    src.cprj_vers_ref_compnr, 
                    src.cspa, 
                    src.cspa_ref_compnr, 
                    src.ctng, 
                    src.ctng_ctsr_ref_compnr, 
                    src.ctng_ref_compnr, 
                    src.ctsr, 
                    src.dcty, 
                    src.dcty_kw, 
                    src.deleted, 
                    src.delt, 
                    src.delt_kw, 
                    src.dfet, 
                    src.dfet_kw, 
                    src.dflv, 
                    src.dflv_kw, 
                    src.dsct, 
                    src.dsct_kw, 
                    src.erng, 
                    src.erng_ersr_ref_compnr, 
                    src.erng_ref_compnr, 
                    src.ersr, 
                    src.ests, 
                    src.loco, 
                    src.mnvf, 
                    src.mnvf_kw, 
                    src.mpvw, 
                    src.mpvw_kw, 
                    src.ngrp, 
                    src.ngrp_ests_ref_compnr, 
                    src.ngrp_prsr_ref_compnr, 
                    src.ngrp_ref_compnr, 
                    src.olvl, 
                    src.potp, 
                    src.potp_ref_compnr, 
                    src.prim, 
                    src.prim_kw, 
                    src.prsr, 
                    src.pung, 
                    src.pung_pusr_ref_compnr, 
                    src.pung_ref_compnr, 
                    src.pusr, 
                    src.rlcr, 
                    src.rlcr_kw, 
                    src.rlgn, 
                    src.rlgn_kw, 
                    src.sequencenumber, 
                    src.serr, 
                    src.song, 
                    src.song_ref_compnr, 
                    src.song_sosr_ref_compnr, 
                    src.sosr, 
                    src.tgrp, 
                    src.tgrp_ref_compnr, 
                    src.tgrp_tpsr_ref_compnr, 
                    src.timestamp, 
                    src.tprf, 
                    src.tprf_kw, 
                    src.tpsr, 
                    src.tpte, 
                    src.tpte_ref_compnr, 
                    src.udac, 
                    src.udac_kw, 
                    src.udev, 
                    src.udev_kw, 
                    src.udpl, 
                    src.udpl_kw, 
                    src.udpr, 
                    src.udpr_kw, 
                    src.udsp, 
                    src.udsp_kw, 
                    src.username, 
                    src.vers, 
                    src.whng, 
                    src.whng_ref_compnr, 
                    src.whng_whsr_ref_compnr, 
                    src.whsr,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TPPDM001_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.aagt, 
            strm.aagt_kw, 
            strm.asct, 
            strm.asct_kw, 
            strm.cact, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.cpla, 
            strm.cprj, 
            strm.cprj_cpla_cact_ref_compnr, 
            strm.cprj_cpla_ref_compnr, 
            strm.cprj_ref_compnr, 
            strm.cprj_vers_ref_compnr, 
            strm.cspa, 
            strm.cspa_ref_compnr, 
            strm.ctng, 
            strm.ctng_ctsr_ref_compnr, 
            strm.ctng_ref_compnr, 
            strm.ctsr, 
            strm.dcty, 
            strm.dcty_kw, 
            strm.deleted, 
            strm.delt, 
            strm.delt_kw, 
            strm.dfet, 
            strm.dfet_kw, 
            strm.dflv, 
            strm.dflv_kw, 
            strm.dsct, 
            strm.dsct_kw, 
            strm.erng, 
            strm.erng_ersr_ref_compnr, 
            strm.erng_ref_compnr, 
            strm.ersr, 
            strm.ests, 
            strm.loco, 
            strm.mnvf, 
            strm.mnvf_kw, 
            strm.mpvw, 
            strm.mpvw_kw, 
            strm.ngrp, 
            strm.ngrp_ests_ref_compnr, 
            strm.ngrp_prsr_ref_compnr, 
            strm.ngrp_ref_compnr, 
            strm.olvl, 
            strm.potp, 
            strm.potp_ref_compnr, 
            strm.prim, 
            strm.prim_kw, 
            strm.prsr, 
            strm.pung, 
            strm.pung_pusr_ref_compnr, 
            strm.pung_ref_compnr, 
            strm.pusr, 
            strm.rlcr, 
            strm.rlcr_kw, 
            strm.rlgn, 
            strm.rlgn_kw, 
            strm.sequencenumber, 
            strm.serr, 
            strm.song, 
            strm.song_ref_compnr, 
            strm.song_sosr_ref_compnr, 
            strm.sosr, 
            strm.tgrp, 
            strm.tgrp_ref_compnr, 
            strm.tgrp_tpsr_ref_compnr, 
            strm.timestamp, 
            strm.tprf, 
            strm.tprf_kw, 
            strm.tpsr, 
            strm.tpte, 
            strm.tpte_ref_compnr, 
            strm.udac, 
            strm.udac_kw, 
            strm.udev, 
            strm.udev_kw, 
            strm.udpl, 
            strm.udpl_kw, 
            strm.udpr, 
            strm.udpr_kw, 
            strm.udsp, 
            strm.udsp_kw, 
            strm.username, 
            strm.vers, 
            strm.whng, 
            strm.whng_ref_compnr, 
            strm.whng_whsr_ref_compnr, 
            strm.whsr, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.loco ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPDM001 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.loco=src.loco) OR (target.loco IS NULL AND src.loco IS NULL)) 
                when matched then update set
                    target.aagt=src.aagt, 
                    target.aagt_kw=src.aagt_kw, 
                    target.asct=src.asct, 
                    target.asct_kw=src.asct_kw, 
                    target.cact=src.cact, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cpla=src.cpla, 
                    target.cprj=src.cprj, 
                    target.cprj_cpla_cact_ref_compnr=src.cprj_cpla_cact_ref_compnr, 
                    target.cprj_cpla_ref_compnr=src.cprj_cpla_ref_compnr, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cprj_vers_ref_compnr=src.cprj_vers_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cspa_ref_compnr=src.cspa_ref_compnr, 
                    target.ctng=src.ctng, 
                    target.ctng_ctsr_ref_compnr=src.ctng_ctsr_ref_compnr, 
                    target.ctng_ref_compnr=src.ctng_ref_compnr, 
                    target.ctsr=src.ctsr, 
                    target.dcty=src.dcty, 
                    target.dcty_kw=src.dcty_kw, 
                    target.deleted=src.deleted, 
                    target.delt=src.delt, 
                    target.delt_kw=src.delt_kw, 
                    target.dfet=src.dfet, 
                    target.dfet_kw=src.dfet_kw, 
                    target.dflv=src.dflv, 
                    target.dflv_kw=src.dflv_kw, 
                    target.dsct=src.dsct, 
                    target.dsct_kw=src.dsct_kw, 
                    target.erng=src.erng, 
                    target.erng_ersr_ref_compnr=src.erng_ersr_ref_compnr, 
                    target.erng_ref_compnr=src.erng_ref_compnr, 
                    target.ersr=src.ersr, 
                    target.ests=src.ests, 
                    target.loco=src.loco, 
                    target.mnvf=src.mnvf, 
                    target.mnvf_kw=src.mnvf_kw, 
                    target.mpvw=src.mpvw, 
                    target.mpvw_kw=src.mpvw_kw, 
                    target.ngrp=src.ngrp, 
                    target.ngrp_ests_ref_compnr=src.ngrp_ests_ref_compnr, 
                    target.ngrp_prsr_ref_compnr=src.ngrp_prsr_ref_compnr, 
                    target.ngrp_ref_compnr=src.ngrp_ref_compnr, 
                    target.olvl=src.olvl, 
                    target.potp=src.potp, 
                    target.potp_ref_compnr=src.potp_ref_compnr, 
                    target.prim=src.prim, 
                    target.prim_kw=src.prim_kw, 
                    target.prsr=src.prsr, 
                    target.pung=src.pung, 
                    target.pung_pusr_ref_compnr=src.pung_pusr_ref_compnr, 
                    target.pung_ref_compnr=src.pung_ref_compnr, 
                    target.pusr=src.pusr, 
                    target.rlcr=src.rlcr, 
                    target.rlcr_kw=src.rlcr_kw, 
                    target.rlgn=src.rlgn, 
                    target.rlgn_kw=src.rlgn_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.serr=src.serr, 
                    target.song=src.song, 
                    target.song_ref_compnr=src.song_ref_compnr, 
                    target.song_sosr_ref_compnr=src.song_sosr_ref_compnr, 
                    target.sosr=src.sosr, 
                    target.tgrp=src.tgrp, 
                    target.tgrp_ref_compnr=src.tgrp_ref_compnr, 
                    target.tgrp_tpsr_ref_compnr=src.tgrp_tpsr_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.tprf=src.tprf, 
                    target.tprf_kw=src.tprf_kw, 
                    target.tpsr=src.tpsr, 
                    target.tpte=src.tpte, 
                    target.tpte_ref_compnr=src.tpte_ref_compnr, 
                    target.udac=src.udac, 
                    target.udac_kw=src.udac_kw, 
                    target.udev=src.udev, 
                    target.udev_kw=src.udev_kw, 
                    target.udpl=src.udpl, 
                    target.udpl_kw=src.udpl_kw, 
                    target.udpr=src.udpr, 
                    target.udpr_kw=src.udpr_kw, 
                    target.udsp=src.udsp, 
                    target.udsp_kw=src.udsp_kw, 
                    target.username=src.username, 
                    target.vers=src.vers, 
                    target.whng=src.whng, 
                    target.whng_ref_compnr=src.whng_ref_compnr, 
                    target.whng_whsr_ref_compnr=src.whng_whsr_ref_compnr, 
                    target.whsr=src.whsr, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( aagt, aagt_kw, asct, asct_kw, cact, cofc, cofc_ref_compnr, compnr, cpla, cprj, cprj_cpla_cact_ref_compnr, cprj_cpla_ref_compnr, cprj_ref_compnr, cprj_vers_ref_compnr, cspa, cspa_ref_compnr, ctng, ctng_ctsr_ref_compnr, ctng_ref_compnr, ctsr, dcty, dcty_kw, deleted, delt, delt_kw, dfet, dfet_kw, dflv, dflv_kw, dsct, dsct_kw, erng, erng_ersr_ref_compnr, erng_ref_compnr, ersr, ests, loco, mnvf, mnvf_kw, mpvw, mpvw_kw, ngrp, ngrp_ests_ref_compnr, ngrp_prsr_ref_compnr, ngrp_ref_compnr, olvl, potp, potp_ref_compnr, prim, prim_kw, prsr, pung, pung_pusr_ref_compnr, pung_ref_compnr, pusr, rlcr, rlcr_kw, rlgn, rlgn_kw, sequencenumber, serr, song, song_ref_compnr, song_sosr_ref_compnr, sosr, tgrp, tgrp_ref_compnr, tgrp_tpsr_ref_compnr, timestamp, tprf, tprf_kw, tpsr, tpte, tpte_ref_compnr, udac, udac_kw, udev, udev_kw, udpl, udpl_kw, udpr, udpr_kw, udsp, udsp_kw, username, vers, whng, whng_ref_compnr, whng_whsr_ref_compnr, whsr, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.aagt, 
                    src.aagt_kw, 
                    src.asct, 
                    src.asct_kw, 
                    src.cact, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.cpla, 
                    src.cprj, 
                    src.cprj_cpla_cact_ref_compnr, 
                    src.cprj_cpla_ref_compnr, 
                    src.cprj_ref_compnr, 
                    src.cprj_vers_ref_compnr, 
                    src.cspa, 
                    src.cspa_ref_compnr, 
                    src.ctng, 
                    src.ctng_ctsr_ref_compnr, 
                    src.ctng_ref_compnr, 
                    src.ctsr, 
                    src.dcty, 
                    src.dcty_kw, 
                    src.deleted, 
                    src.delt, 
                    src.delt_kw, 
                    src.dfet, 
                    src.dfet_kw, 
                    src.dflv, 
                    src.dflv_kw, 
                    src.dsct, 
                    src.dsct_kw, 
                    src.erng, 
                    src.erng_ersr_ref_compnr, 
                    src.erng_ref_compnr, 
                    src.ersr, 
                    src.ests, 
                    src.loco, 
                    src.mnvf, 
                    src.mnvf_kw, 
                    src.mpvw, 
                    src.mpvw_kw, 
                    src.ngrp, 
                    src.ngrp_ests_ref_compnr, 
                    src.ngrp_prsr_ref_compnr, 
                    src.ngrp_ref_compnr, 
                    src.olvl, 
                    src.potp, 
                    src.potp_ref_compnr, 
                    src.prim, 
                    src.prim_kw, 
                    src.prsr, 
                    src.pung, 
                    src.pung_pusr_ref_compnr, 
                    src.pung_ref_compnr, 
                    src.pusr, 
                    src.rlcr, 
                    src.rlcr_kw, 
                    src.rlgn, 
                    src.rlgn_kw, 
                    src.sequencenumber, 
                    src.serr, 
                    src.song, 
                    src.song_ref_compnr, 
                    src.song_sosr_ref_compnr, 
                    src.sosr, 
                    src.tgrp, 
                    src.tgrp_ref_compnr, 
                    src.tgrp_tpsr_ref_compnr, 
                    src.timestamp, 
                    src.tprf, 
                    src.tprf_kw, 
                    src.tpsr, 
                    src.tpte, 
                    src.tpte_ref_compnr, 
                    src.udac, 
                    src.udac_kw, 
                    src.udev, 
                    src.udev_kw, 
                    src.udpl, 
                    src.udpl_kw, 
                    src.udpr, 
                    src.udpr_kw, 
                    src.udsp, 
                    src.udsp_kw, 
                    src.username, 
                    src.vers, 
                    src.whng, 
                    src.whng_ref_compnr, 
                    src.whng_whsr_ref_compnr, 
                    src.whsr,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;