create or replace procedure DATAHUB_INTEGRATION.SP_LN_WHINH435()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_WHINH435_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_WHINH435 as target using (SELECT * FROM (SELECT 
            strm.bptc, 
            strm.bptc_ref_compnr, 
            strm.carp, 
            strm.ccty, 
            strm.ccty_ref_compnr, 
            strm.cdec, 
            strm.cdec_ref_compnr, 
            strm.compnr, 
            strm.crdt, 
            strm.crte, 
            strm.crte_ref_compnr, 
            strm.cwun, 
            strm.cwun_ref_compnr, 
            strm.dcdt, 
            strm.delc, 
            strm.delc_ref_compnr, 
            strm.deleted, 
            strm.deln, 
            strm.depc, 
            strm.depc_ref_compnr, 
            strm.dnst, 
            strm.dnst_kw, 
            strm.finp, 
            strm.finp_kw, 
            strm.fnsr, 
            strm.fsyr, 
            strm.grwt, 
            strm.itbp, 
            strm.itbp_ref_compnr, 
            strm.load, 
            strm.load_ref_compnr, 
            strm.manl, 
            strm.manl_kw, 
            strm.motv, 
            strm.motv_ref_compnr, 
            strm.nota, 
            strm.notb, 
            strm.notc, 
            strm.ofbp, 
            strm.ofbp_ref_compnr, 
            strm.prdn, 
            strm.prdt, 
            strm.qpac, 
            strm.sequencenumber, 
            strm.sfad, 
            strm.sfad_ref_compnr, 
            strm.sfco, 
            strm.sfcp, 
            strm.sfty, 
            strm.sfty_kw, 
            strm.shap, 
            strm.site, 
            strm.site_ref_compnr, 
            strm.stad, 
            strm.stad_ref_compnr, 
            strm.stco, 
            strm.stcp, 
            strm.stty, 
            strm.stty_kw, 
            strm.taxp, 
            strm.taxs, 
            strm.timestamp, 
            strm.tsad, 
            strm.tsad_ref_compnr, 
            strm.username, 
            strm.wdep, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.prdn ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_WHINH435 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.prdn=src.prdn) OR (target.prdn IS NULL AND src.prdn IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.bptc=src.bptc, 
                    target.bptc_ref_compnr=src.bptc_ref_compnr, 
                    target.carp=src.carp, 
                    target.ccty=src.ccty, 
                    target.ccty_ref_compnr=src.ccty_ref_compnr, 
                    target.cdec=src.cdec, 
                    target.cdec_ref_compnr=src.cdec_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.crdt=src.crdt, 
                    target.crte=src.crte, 
                    target.crte_ref_compnr=src.crte_ref_compnr, 
                    target.cwun=src.cwun, 
                    target.cwun_ref_compnr=src.cwun_ref_compnr, 
                    target.dcdt=src.dcdt, 
                    target.delc=src.delc, 
                    target.delc_ref_compnr=src.delc_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.deln=src.deln, 
                    target.depc=src.depc, 
                    target.depc_ref_compnr=src.depc_ref_compnr, 
                    target.dnst=src.dnst, 
                    target.dnst_kw=src.dnst_kw, 
                    target.finp=src.finp, 
                    target.finp_kw=src.finp_kw, 
                    target.fnsr=src.fnsr, 
                    target.fsyr=src.fsyr, 
                    target.grwt=src.grwt, 
                    target.itbp=src.itbp, 
                    target.itbp_ref_compnr=src.itbp_ref_compnr, 
                    target.load=src.load, 
                    target.load_ref_compnr=src.load_ref_compnr, 
                    target.manl=src.manl, 
                    target.manl_kw=src.manl_kw, 
                    target.motv=src.motv, 
                    target.motv_ref_compnr=src.motv_ref_compnr, 
                    target.nota=src.nota, 
                    target.notb=src.notb, 
                    target.notc=src.notc, 
                    target.ofbp=src.ofbp, 
                    target.ofbp_ref_compnr=src.ofbp_ref_compnr, 
                    target.prdn=src.prdn, 
                    target.prdt=src.prdt, 
                    target.qpac=src.qpac, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sfad=src.sfad, 
                    target.sfad_ref_compnr=src.sfad_ref_compnr, 
                    target.sfco=src.sfco, 
                    target.sfcp=src.sfcp, 
                    target.sfty=src.sfty, 
                    target.sfty_kw=src.sfty_kw, 
                    target.shap=src.shap, 
                    target.site=src.site, 
                    target.site_ref_compnr=src.site_ref_compnr, 
                    target.stad=src.stad, 
                    target.stad_ref_compnr=src.stad_ref_compnr, 
                    target.stco=src.stco, 
                    target.stcp=src.stcp, 
                    target.stty=src.stty, 
                    target.stty_kw=src.stty_kw, 
                    target.taxp=src.taxp, 
                    target.taxs=src.taxs, 
                    target.timestamp=src.timestamp, 
                    target.tsad=src.tsad, 
                    target.tsad_ref_compnr=src.tsad_ref_compnr, 
                    target.username=src.username, 
                    target.wdep=src.wdep, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    bptc, 
                    bptc_ref_compnr, 
                    carp, 
                    ccty, 
                    ccty_ref_compnr, 
                    cdec, 
                    cdec_ref_compnr, 
                    compnr, 
                    crdt, 
                    crte, 
                    crte_ref_compnr, 
                    cwun, 
                    cwun_ref_compnr, 
                    dcdt, 
                    delc, 
                    delc_ref_compnr, 
                    deleted, 
                    deln, 
                    depc, 
                    depc_ref_compnr, 
                    dnst, 
                    dnst_kw, 
                    finp, 
                    finp_kw, 
                    fnsr, 
                    fsyr, 
                    grwt, 
                    itbp, 
                    itbp_ref_compnr, 
                    load, 
                    load_ref_compnr, 
                    manl, 
                    manl_kw, 
                    motv, 
                    motv_ref_compnr, 
                    nota, 
                    notb, 
                    notc, 
                    ofbp, 
                    ofbp_ref_compnr, 
                    prdn, 
                    prdt, 
                    qpac, 
                    sequencenumber, 
                    sfad, 
                    sfad_ref_compnr, 
                    sfco, 
                    sfcp, 
                    sfty, 
                    sfty_kw, 
                    shap, 
                    site, 
                    site_ref_compnr, 
                    stad, 
                    stad_ref_compnr, 
                    stco, 
                    stcp, 
                    stty, 
                    stty_kw, 
                    taxp, 
                    taxs, 
                    timestamp, 
                    tsad, 
                    tsad_ref_compnr, 
                    username, 
                    wdep, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.bptc, 
                    src.bptc_ref_compnr, 
                    src.carp, 
                    src.ccty, 
                    src.ccty_ref_compnr, 
                    src.cdec, 
                    src.cdec_ref_compnr, 
                    src.compnr, 
                    src.crdt, 
                    src.crte, 
                    src.crte_ref_compnr, 
                    src.cwun, 
                    src.cwun_ref_compnr, 
                    src.dcdt, 
                    src.delc, 
                    src.delc_ref_compnr, 
                    src.deleted, 
                    src.deln, 
                    src.depc, 
                    src.depc_ref_compnr, 
                    src.dnst, 
                    src.dnst_kw, 
                    src.finp, 
                    src.finp_kw, 
                    src.fnsr, 
                    src.fsyr, 
                    src.grwt, 
                    src.itbp, 
                    src.itbp_ref_compnr, 
                    src.load, 
                    src.load_ref_compnr, 
                    src.manl, 
                    src.manl_kw, 
                    src.motv, 
                    src.motv_ref_compnr, 
                    src.nota, 
                    src.notb, 
                    src.notc, 
                    src.ofbp, 
                    src.ofbp_ref_compnr, 
                    src.prdn, 
                    src.prdt, 
                    src.qpac, 
                    src.sequencenumber, 
                    src.sfad, 
                    src.sfad_ref_compnr, 
                    src.sfco, 
                    src.sfcp, 
                    src.sfty, 
                    src.sfty_kw, 
                    src.shap, 
                    src.site, 
                    src.site_ref_compnr, 
                    src.stad, 
                    src.stad_ref_compnr, 
                    src.stco, 
                    src.stcp, 
                    src.stty, 
                    src.stty_kw, 
                    src.taxp, 
                    src.taxs, 
                    src.timestamp, 
                    src.tsad, 
                    src.tsad_ref_compnr, 
                    src.username, 
                    src.wdep,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_WHINH435_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.bptc, 
            strm.bptc_ref_compnr, 
            strm.carp, 
            strm.ccty, 
            strm.ccty_ref_compnr, 
            strm.cdec, 
            strm.cdec_ref_compnr, 
            strm.compnr, 
            strm.crdt, 
            strm.crte, 
            strm.crte_ref_compnr, 
            strm.cwun, 
            strm.cwun_ref_compnr, 
            strm.dcdt, 
            strm.delc, 
            strm.delc_ref_compnr, 
            strm.deleted, 
            strm.deln, 
            strm.depc, 
            strm.depc_ref_compnr, 
            strm.dnst, 
            strm.dnst_kw, 
            strm.finp, 
            strm.finp_kw, 
            strm.fnsr, 
            strm.fsyr, 
            strm.grwt, 
            strm.itbp, 
            strm.itbp_ref_compnr, 
            strm.load, 
            strm.load_ref_compnr, 
            strm.manl, 
            strm.manl_kw, 
            strm.motv, 
            strm.motv_ref_compnr, 
            strm.nota, 
            strm.notb, 
            strm.notc, 
            strm.ofbp, 
            strm.ofbp_ref_compnr, 
            strm.prdn, 
            strm.prdt, 
            strm.qpac, 
            strm.sequencenumber, 
            strm.sfad, 
            strm.sfad_ref_compnr, 
            strm.sfco, 
            strm.sfcp, 
            strm.sfty, 
            strm.sfty_kw, 
            strm.shap, 
            strm.site, 
            strm.site_ref_compnr, 
            strm.stad, 
            strm.stad_ref_compnr, 
            strm.stco, 
            strm.stcp, 
            strm.stty, 
            strm.stty_kw, 
            strm.taxp, 
            strm.taxs, 
            strm.timestamp, 
            strm.tsad, 
            strm.tsad_ref_compnr, 
            strm.username, 
            strm.wdep, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.prdn ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_WHINH435 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.prdn=src.prdn) OR (target.prdn IS NULL AND src.prdn IS NULL)) 
                when matched then update set
                    target.bptc=src.bptc, 
                    target.bptc_ref_compnr=src.bptc_ref_compnr, 
                    target.carp=src.carp, 
                    target.ccty=src.ccty, 
                    target.ccty_ref_compnr=src.ccty_ref_compnr, 
                    target.cdec=src.cdec, 
                    target.cdec_ref_compnr=src.cdec_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.crdt=src.crdt, 
                    target.crte=src.crte, 
                    target.crte_ref_compnr=src.crte_ref_compnr, 
                    target.cwun=src.cwun, 
                    target.cwun_ref_compnr=src.cwun_ref_compnr, 
                    target.dcdt=src.dcdt, 
                    target.delc=src.delc, 
                    target.delc_ref_compnr=src.delc_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.deln=src.deln, 
                    target.depc=src.depc, 
                    target.depc_ref_compnr=src.depc_ref_compnr, 
                    target.dnst=src.dnst, 
                    target.dnst_kw=src.dnst_kw, 
                    target.finp=src.finp, 
                    target.finp_kw=src.finp_kw, 
                    target.fnsr=src.fnsr, 
                    target.fsyr=src.fsyr, 
                    target.grwt=src.grwt, 
                    target.itbp=src.itbp, 
                    target.itbp_ref_compnr=src.itbp_ref_compnr, 
                    target.load=src.load, 
                    target.load_ref_compnr=src.load_ref_compnr, 
                    target.manl=src.manl, 
                    target.manl_kw=src.manl_kw, 
                    target.motv=src.motv, 
                    target.motv_ref_compnr=src.motv_ref_compnr, 
                    target.nota=src.nota, 
                    target.notb=src.notb, 
                    target.notc=src.notc, 
                    target.ofbp=src.ofbp, 
                    target.ofbp_ref_compnr=src.ofbp_ref_compnr, 
                    target.prdn=src.prdn, 
                    target.prdt=src.prdt, 
                    target.qpac=src.qpac, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sfad=src.sfad, 
                    target.sfad_ref_compnr=src.sfad_ref_compnr, 
                    target.sfco=src.sfco, 
                    target.sfcp=src.sfcp, 
                    target.sfty=src.sfty, 
                    target.sfty_kw=src.sfty_kw, 
                    target.shap=src.shap, 
                    target.site=src.site, 
                    target.site_ref_compnr=src.site_ref_compnr, 
                    target.stad=src.stad, 
                    target.stad_ref_compnr=src.stad_ref_compnr, 
                    target.stco=src.stco, 
                    target.stcp=src.stcp, 
                    target.stty=src.stty, 
                    target.stty_kw=src.stty_kw, 
                    target.taxp=src.taxp, 
                    target.taxs=src.taxs, 
                    target.timestamp=src.timestamp, 
                    target.tsad=src.tsad, 
                    target.tsad_ref_compnr=src.tsad_ref_compnr, 
                    target.username=src.username, 
                    target.wdep=src.wdep, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( bptc, bptc_ref_compnr, carp, ccty, ccty_ref_compnr, cdec, cdec_ref_compnr, compnr, crdt, crte, crte_ref_compnr, cwun, cwun_ref_compnr, dcdt, delc, delc_ref_compnr, deleted, deln, depc, depc_ref_compnr, dnst, dnst_kw, finp, finp_kw, fnsr, fsyr, grwt, itbp, itbp_ref_compnr, load, load_ref_compnr, manl, manl_kw, motv, motv_ref_compnr, nota, notb, notc, ofbp, ofbp_ref_compnr, prdn, prdt, qpac, sequencenumber, sfad, sfad_ref_compnr, sfco, sfcp, sfty, sfty_kw, shap, site, site_ref_compnr, stad, stad_ref_compnr, stco, stcp, stty, stty_kw, taxp, taxs, timestamp, tsad, tsad_ref_compnr, username, wdep, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.bptc, 
                    src.bptc_ref_compnr, 
                    src.carp, 
                    src.ccty, 
                    src.ccty_ref_compnr, 
                    src.cdec, 
                    src.cdec_ref_compnr, 
                    src.compnr, 
                    src.crdt, 
                    src.crte, 
                    src.crte_ref_compnr, 
                    src.cwun, 
                    src.cwun_ref_compnr, 
                    src.dcdt, 
                    src.delc, 
                    src.delc_ref_compnr, 
                    src.deleted, 
                    src.deln, 
                    src.depc, 
                    src.depc_ref_compnr, 
                    src.dnst, 
                    src.dnst_kw, 
                    src.finp, 
                    src.finp_kw, 
                    src.fnsr, 
                    src.fsyr, 
                    src.grwt, 
                    src.itbp, 
                    src.itbp_ref_compnr, 
                    src.load, 
                    src.load_ref_compnr, 
                    src.manl, 
                    src.manl_kw, 
                    src.motv, 
                    src.motv_ref_compnr, 
                    src.nota, 
                    src.notb, 
                    src.notc, 
                    src.ofbp, 
                    src.ofbp_ref_compnr, 
                    src.prdn, 
                    src.prdt, 
                    src.qpac, 
                    src.sequencenumber, 
                    src.sfad, 
                    src.sfad_ref_compnr, 
                    src.sfco, 
                    src.sfcp, 
                    src.sfty, 
                    src.sfty_kw, 
                    src.shap, 
                    src.site, 
                    src.site_ref_compnr, 
                    src.stad, 
                    src.stad_ref_compnr, 
                    src.stco, 
                    src.stcp, 
                    src.stty, 
                    src.stty_kw, 
                    src.taxp, 
                    src.taxs, 
                    src.timestamp, 
                    src.tsad, 
                    src.tsad_ref_compnr, 
                    src.username, 
                    src.wdep,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;