create or replace procedure DATAHUB_INTEGRATION.SP_LN_TDPUR200()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TDPUR200_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TDPUR200 as target using (SELECT * FROM (SELECT 
            strm.adep, 
            strm.adep_ref_compnr, 
            strm.adin, 
            strm.aemn, 
            strm.aemn_ref_compnr, 
            strm.cact, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.ccon, 
            strm.ccon_ref_compnr, 
            strm.ccty, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.cnty, 
            strm.cnty_kw, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.conv, 
            strm.conv_kw, 
            strm.cprj, 
            strm.cprj_ref_compnr, 
            strm.cspa, 
            strm.cstl, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.dadr, 
            strm.dadr_ref_compnr, 
            strm.deleted, 
            strm.dldt, 
            strm.logn, 
            strm.ltdt, 
            strm.orig, 
            strm.orig_kw, 
            strm.rcod, 
            strm.rcod_ref_compnr, 
            strm.rdat, 
            strm.rdep, 
            strm.rdep_ref_compnr, 
            strm.refa, 
            strm.refb, 
            strm.remn, 
            strm.remn_ref_compnr, 
            strm.rqno, 
            strm.rqst, 
            strm.rqst_kw, 
            strm.sequencenumber, 
            strm.site, 
            strm.site_ref_compnr, 
            strm.spap, 
            strm.spap_kw, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.urgt, 
            strm.urgt_kw, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.rqno ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDPUR200 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.rqno=src.rqno) OR (target.rqno IS NULL AND src.rqno IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.adep=src.adep, 
                    target.adep_ref_compnr=src.adep_ref_compnr, 
                    target.adin=src.adin, 
                    target.aemn=src.aemn, 
                    target.aemn_ref_compnr=src.aemn_ref_compnr, 
                    target.cact=src.cact, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.ccon=src.ccon, 
                    target.ccon_ref_compnr=src.ccon_ref_compnr, 
                    target.ccty=src.ccty, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.cnty=src.cnty, 
                    target.cnty_kw=src.cnty_kw, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.conv=src.conv, 
                    target.conv_kw=src.conv_kw, 
                    target.cprj=src.cprj, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cstl=src.cstl, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.dadr=src.dadr, 
                    target.dadr_ref_compnr=src.dadr_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dldt=src.dldt, 
                    target.logn=src.logn, 
                    target.ltdt=src.ltdt, 
                    target.orig=src.orig, 
                    target.orig_kw=src.orig_kw, 
                    target.rcod=src.rcod, 
                    target.rcod_ref_compnr=src.rcod_ref_compnr, 
                    target.rdat=src.rdat, 
                    target.rdep=src.rdep, 
                    target.rdep_ref_compnr=src.rdep_ref_compnr, 
                    target.refa=src.refa, 
                    target.refb=src.refb, 
                    target.remn=src.remn, 
                    target.remn_ref_compnr=src.remn_ref_compnr, 
                    target.rqno=src.rqno, 
                    target.rqst=src.rqst, 
                    target.rqst_kw=src.rqst_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.site=src.site, 
                    target.site_ref_compnr=src.site_ref_compnr, 
                    target.spap=src.spap, 
                    target.spap_kw=src.spap_kw, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.urgt=src.urgt, 
                    target.urgt_kw=src.urgt_kw, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    adep, 
                    adep_ref_compnr, 
                    adin, 
                    aemn, 
                    aemn_ref_compnr, 
                    cact, 
                    ccco, 
                    ccco_ref_compnr, 
                    ccon, 
                    ccon_ref_compnr, 
                    ccty, 
                    ccur, 
                    ccur_ref_compnr, 
                    cnty, 
                    cnty_kw, 
                    cofc, 
                    cofc_ref_compnr, 
                    compnr, 
                    conv, 
                    conv_kw, 
                    cprj, 
                    cprj_ref_compnr, 
                    cspa, 
                    cstl, 
                    cwar, 
                    cwar_ref_compnr, 
                    dadr, 
                    dadr_ref_compnr, 
                    deleted, 
                    dldt, 
                    logn, 
                    ltdt, 
                    orig, 
                    orig_kw, 
                    rcod, 
                    rcod_ref_compnr, 
                    rdat, 
                    rdep, 
                    rdep_ref_compnr, 
                    refa, 
                    refb, 
                    remn, 
                    remn_ref_compnr, 
                    rqno, 
                    rqst, 
                    rqst_kw, 
                    sequencenumber, 
                    site, 
                    site_ref_compnr, 
                    spap, 
                    spap_kw, 
                    timestamp, 
                    txta, 
                    txta_ref_compnr, 
                    urgt, 
                    urgt_kw, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.adep, 
                    src.adep_ref_compnr, 
                    src.adin, 
                    src.aemn, 
                    src.aemn_ref_compnr, 
                    src.cact, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.ccon, 
                    src.ccon_ref_compnr, 
                    src.ccty, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.cnty, 
                    src.cnty_kw, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.conv, 
                    src.conv_kw, 
                    src.cprj, 
                    src.cprj_ref_compnr, 
                    src.cspa, 
                    src.cstl, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.dadr, 
                    src.dadr_ref_compnr, 
                    src.deleted, 
                    src.dldt, 
                    src.logn, 
                    src.ltdt, 
                    src.orig, 
                    src.orig_kw, 
                    src.rcod, 
                    src.rcod_ref_compnr, 
                    src.rdat, 
                    src.rdep, 
                    src.rdep_ref_compnr, 
                    src.refa, 
                    src.refb, 
                    src.remn, 
                    src.remn_ref_compnr, 
                    src.rqno, 
                    src.rqst, 
                    src.rqst_kw, 
                    src.sequencenumber, 
                    src.site, 
                    src.site_ref_compnr, 
                    src.spap, 
                    src.spap_kw, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.urgt, 
                    src.urgt_kw, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TDPUR200_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.adep, 
            strm.adep_ref_compnr, 
            strm.adin, 
            strm.aemn, 
            strm.aemn_ref_compnr, 
            strm.cact, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.ccon, 
            strm.ccon_ref_compnr, 
            strm.ccty, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.cnty, 
            strm.cnty_kw, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.conv, 
            strm.conv_kw, 
            strm.cprj, 
            strm.cprj_ref_compnr, 
            strm.cspa, 
            strm.cstl, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.dadr, 
            strm.dadr_ref_compnr, 
            strm.deleted, 
            strm.dldt, 
            strm.logn, 
            strm.ltdt, 
            strm.orig, 
            strm.orig_kw, 
            strm.rcod, 
            strm.rcod_ref_compnr, 
            strm.rdat, 
            strm.rdep, 
            strm.rdep_ref_compnr, 
            strm.refa, 
            strm.refb, 
            strm.remn, 
            strm.remn_ref_compnr, 
            strm.rqno, 
            strm.rqst, 
            strm.rqst_kw, 
            strm.sequencenumber, 
            strm.site, 
            strm.site_ref_compnr, 
            strm.spap, 
            strm.spap_kw, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.urgt, 
            strm.urgt_kw, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.rqno ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDPUR200 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.rqno=src.rqno) OR (target.rqno IS NULL AND src.rqno IS NULL)) 
                when matched then update set
                    target.adep=src.adep, 
                    target.adep_ref_compnr=src.adep_ref_compnr, 
                    target.adin=src.adin, 
                    target.aemn=src.aemn, 
                    target.aemn_ref_compnr=src.aemn_ref_compnr, 
                    target.cact=src.cact, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.ccon=src.ccon, 
                    target.ccon_ref_compnr=src.ccon_ref_compnr, 
                    target.ccty=src.ccty, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.cnty=src.cnty, 
                    target.cnty_kw=src.cnty_kw, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.conv=src.conv, 
                    target.conv_kw=src.conv_kw, 
                    target.cprj=src.cprj, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cstl=src.cstl, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.dadr=src.dadr, 
                    target.dadr_ref_compnr=src.dadr_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dldt=src.dldt, 
                    target.logn=src.logn, 
                    target.ltdt=src.ltdt, 
                    target.orig=src.orig, 
                    target.orig_kw=src.orig_kw, 
                    target.rcod=src.rcod, 
                    target.rcod_ref_compnr=src.rcod_ref_compnr, 
                    target.rdat=src.rdat, 
                    target.rdep=src.rdep, 
                    target.rdep_ref_compnr=src.rdep_ref_compnr, 
                    target.refa=src.refa, 
                    target.refb=src.refb, 
                    target.remn=src.remn, 
                    target.remn_ref_compnr=src.remn_ref_compnr, 
                    target.rqno=src.rqno, 
                    target.rqst=src.rqst, 
                    target.rqst_kw=src.rqst_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.site=src.site, 
                    target.site_ref_compnr=src.site_ref_compnr, 
                    target.spap=src.spap, 
                    target.spap_kw=src.spap_kw, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.urgt=src.urgt, 
                    target.urgt_kw=src.urgt_kw, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( adep, adep_ref_compnr, adin, aemn, aemn_ref_compnr, cact, ccco, ccco_ref_compnr, ccon, ccon_ref_compnr, ccty, ccur, ccur_ref_compnr, cnty, cnty_kw, cofc, cofc_ref_compnr, compnr, conv, conv_kw, cprj, cprj_ref_compnr, cspa, cstl, cwar, cwar_ref_compnr, dadr, dadr_ref_compnr, deleted, dldt, logn, ltdt, orig, orig_kw, rcod, rcod_ref_compnr, rdat, rdep, rdep_ref_compnr, refa, refb, remn, remn_ref_compnr, rqno, rqst, rqst_kw, sequencenumber, site, site_ref_compnr, spap, spap_kw, timestamp, txta, txta_ref_compnr, urgt, urgt_kw, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.adep, 
                    src.adep_ref_compnr, 
                    src.adin, 
                    src.aemn, 
                    src.aemn_ref_compnr, 
                    src.cact, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.ccon, 
                    src.ccon_ref_compnr, 
                    src.ccty, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.cnty, 
                    src.cnty_kw, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.conv, 
                    src.conv_kw, 
                    src.cprj, 
                    src.cprj_ref_compnr, 
                    src.cspa, 
                    src.cstl, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.dadr, 
                    src.dadr_ref_compnr, 
                    src.deleted, 
                    src.dldt, 
                    src.logn, 
                    src.ltdt, 
                    src.orig, 
                    src.orig_kw, 
                    src.rcod, 
                    src.rcod_ref_compnr, 
                    src.rdat, 
                    src.rdep, 
                    src.rdep_ref_compnr, 
                    src.refa, 
                    src.refb, 
                    src.remn, 
                    src.remn_ref_compnr, 
                    src.rqno, 
                    src.rqst, 
                    src.rqst_kw, 
                    src.sequencenumber, 
                    src.site, 
                    src.site_ref_compnr, 
                    src.spap, 
                    src.spap_kw, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.urgt, 
                    src.urgt_kw, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;