create or replace procedure DATAHUB_INTEGRATION.SP_LN_WHINA122()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_WHINA122_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_WHINA122 as target using (SELECT * FROM (SELECT 
            strm.atse, 
            strm.atse_ref_compnr, 
            strm.bfbp, 
            strm.cact, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.clot, 
            strm.compnr, 
            strm.cprj, 
            strm.cprj_ref_compnr, 
            strm.cspa, 
            strm.cstl, 
            strm.cvmo, 
            strm.cvmo_kw, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.deleted, 
            strm.inwp, 
            strm.inwp_kw, 
            strm.item, 
            strm.item_ref_compnr, 
            strm.lgdt, 
            strm.logn, 
            strm.nval, 
            strm.nval_kw, 
            strm.nvba, 
            strm.nvba_kw, 
            strm.nvgr, 
            strm.nvgr_ref_compnr, 
            strm.nwvg, 
            strm.nwvg_kw, 
            strm.orno, 
            strm.oval, 
            strm.oval_kw, 
            strm.ovba, 
            strm.ovba_kw, 
            strm.ovgr, 
            strm.ovgr_ref_compnr, 
            strm.ownr, 
            strm.owns, 
            strm.owns_kw, 
            strm.owvg, 
            strm.owvg_kw, 
            strm.quan, 
            strm.reje, 
            strm.reje_kw, 
            strm.rorg, 
            strm.rorg_kw, 
            strm.rowc, 
            strm.rowc_ref_compnr, 
            strm.rown, 
            strm.rown_ref_compnr, 
            strm.rvdt, 
            strm.rvrs, 
            strm.rvrs_ref_compnr, 
            strm.seqn, 
            strm.sequencenumber, 
            strm.serl, 
            strm.site, 
            strm.site_ref_compnr, 
            strm.tagn, 
            strm.timestamp, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.rorg,
            strm.orno,
            strm.seqn ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_WHINA122 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.rorg=src.rorg) OR (target.rorg IS NULL AND src.rorg IS NULL)) AND
            ((target.orno=src.orno) OR (target.orno IS NULL AND src.orno IS NULL)) AND
            ((target.seqn=src.seqn) OR (target.seqn IS NULL AND src.seqn IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.atse=src.atse, 
                    target.atse_ref_compnr=src.atse_ref_compnr, 
                    target.bfbp=src.bfbp, 
                    target.cact=src.cact, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.clot=src.clot, 
                    target.compnr=src.compnr, 
                    target.cprj=src.cprj, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cstl=src.cstl, 
                    target.cvmo=src.cvmo, 
                    target.cvmo_kw=src.cvmo_kw, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.inwp=src.inwp, 
                    target.inwp_kw=src.inwp_kw, 
                    target.item=src.item, 
                    target.item_ref_compnr=src.item_ref_compnr, 
                    target.lgdt=src.lgdt, 
                    target.logn=src.logn, 
                    target.nval=src.nval, 
                    target.nval_kw=src.nval_kw, 
                    target.nvba=src.nvba, 
                    target.nvba_kw=src.nvba_kw, 
                    target.nvgr=src.nvgr, 
                    target.nvgr_ref_compnr=src.nvgr_ref_compnr, 
                    target.nwvg=src.nwvg, 
                    target.nwvg_kw=src.nwvg_kw, 
                    target.orno=src.orno, 
                    target.oval=src.oval, 
                    target.oval_kw=src.oval_kw, 
                    target.ovba=src.ovba, 
                    target.ovba_kw=src.ovba_kw, 
                    target.ovgr=src.ovgr, 
                    target.ovgr_ref_compnr=src.ovgr_ref_compnr, 
                    target.ownr=src.ownr, 
                    target.owns=src.owns, 
                    target.owns_kw=src.owns_kw, 
                    target.owvg=src.owvg, 
                    target.owvg_kw=src.owvg_kw, 
                    target.quan=src.quan, 
                    target.reje=src.reje, 
                    target.reje_kw=src.reje_kw, 
                    target.rorg=src.rorg, 
                    target.rorg_kw=src.rorg_kw, 
                    target.rowc=src.rowc, 
                    target.rowc_ref_compnr=src.rowc_ref_compnr, 
                    target.rown=src.rown, 
                    target.rown_ref_compnr=src.rown_ref_compnr, 
                    target.rvdt=src.rvdt, 
                    target.rvrs=src.rvrs, 
                    target.rvrs_ref_compnr=src.rvrs_ref_compnr, 
                    target.seqn=src.seqn, 
                    target.sequencenumber=src.sequencenumber, 
                    target.serl=src.serl, 
                    target.site=src.site, 
                    target.site_ref_compnr=src.site_ref_compnr, 
                    target.tagn=src.tagn, 
                    target.timestamp=src.timestamp, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    atse, 
                    atse_ref_compnr, 
                    bfbp, 
                    cact, 
                    ccco, 
                    ccco_ref_compnr, 
                    clot, 
                    compnr, 
                    cprj, 
                    cprj_ref_compnr, 
                    cspa, 
                    cstl, 
                    cvmo, 
                    cvmo_kw, 
                    cwar, 
                    cwar_ref_compnr, 
                    deleted, 
                    inwp, 
                    inwp_kw, 
                    item, 
                    item_ref_compnr, 
                    lgdt, 
                    logn, 
                    nval, 
                    nval_kw, 
                    nvba, 
                    nvba_kw, 
                    nvgr, 
                    nvgr_ref_compnr, 
                    nwvg, 
                    nwvg_kw, 
                    orno, 
                    oval, 
                    oval_kw, 
                    ovba, 
                    ovba_kw, 
                    ovgr, 
                    ovgr_ref_compnr, 
                    ownr, 
                    owns, 
                    owns_kw, 
                    owvg, 
                    owvg_kw, 
                    quan, 
                    reje, 
                    reje_kw, 
                    rorg, 
                    rorg_kw, 
                    rowc, 
                    rowc_ref_compnr, 
                    rown, 
                    rown_ref_compnr, 
                    rvdt, 
                    rvrs, 
                    rvrs_ref_compnr, 
                    seqn, 
                    sequencenumber, 
                    serl, 
                    site, 
                    site_ref_compnr, 
                    tagn, 
                    timestamp, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.atse, 
                    src.atse_ref_compnr, 
                    src.bfbp, 
                    src.cact, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.clot, 
                    src.compnr, 
                    src.cprj, 
                    src.cprj_ref_compnr, 
                    src.cspa, 
                    src.cstl, 
                    src.cvmo, 
                    src.cvmo_kw, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.deleted, 
                    src.inwp, 
                    src.inwp_kw, 
                    src.item, 
                    src.item_ref_compnr, 
                    src.lgdt, 
                    src.logn, 
                    src.nval, 
                    src.nval_kw, 
                    src.nvba, 
                    src.nvba_kw, 
                    src.nvgr, 
                    src.nvgr_ref_compnr, 
                    src.nwvg, 
                    src.nwvg_kw, 
                    src.orno, 
                    src.oval, 
                    src.oval_kw, 
                    src.ovba, 
                    src.ovba_kw, 
                    src.ovgr, 
                    src.ovgr_ref_compnr, 
                    src.ownr, 
                    src.owns, 
                    src.owns_kw, 
                    src.owvg, 
                    src.owvg_kw, 
                    src.quan, 
                    src.reje, 
                    src.reje_kw, 
                    src.rorg, 
                    src.rorg_kw, 
                    src.rowc, 
                    src.rowc_ref_compnr, 
                    src.rown, 
                    src.rown_ref_compnr, 
                    src.rvdt, 
                    src.rvrs, 
                    src.rvrs_ref_compnr, 
                    src.seqn, 
                    src.sequencenumber, 
                    src.serl, 
                    src.site, 
                    src.site_ref_compnr, 
                    src.tagn, 
                    src.timestamp, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_WHINA122_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.atse, 
            strm.atse_ref_compnr, 
            strm.bfbp, 
            strm.cact, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.clot, 
            strm.compnr, 
            strm.cprj, 
            strm.cprj_ref_compnr, 
            strm.cspa, 
            strm.cstl, 
            strm.cvmo, 
            strm.cvmo_kw, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.deleted, 
            strm.inwp, 
            strm.inwp_kw, 
            strm.item, 
            strm.item_ref_compnr, 
            strm.lgdt, 
            strm.logn, 
            strm.nval, 
            strm.nval_kw, 
            strm.nvba, 
            strm.nvba_kw, 
            strm.nvgr, 
            strm.nvgr_ref_compnr, 
            strm.nwvg, 
            strm.nwvg_kw, 
            strm.orno, 
            strm.oval, 
            strm.oval_kw, 
            strm.ovba, 
            strm.ovba_kw, 
            strm.ovgr, 
            strm.ovgr_ref_compnr, 
            strm.ownr, 
            strm.owns, 
            strm.owns_kw, 
            strm.owvg, 
            strm.owvg_kw, 
            strm.quan, 
            strm.reje, 
            strm.reje_kw, 
            strm.rorg, 
            strm.rorg_kw, 
            strm.rowc, 
            strm.rowc_ref_compnr, 
            strm.rown, 
            strm.rown_ref_compnr, 
            strm.rvdt, 
            strm.rvrs, 
            strm.rvrs_ref_compnr, 
            strm.seqn, 
            strm.sequencenumber, 
            strm.serl, 
            strm.site, 
            strm.site_ref_compnr, 
            strm.tagn, 
            strm.timestamp, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.rorg,
            strm.orno,
            strm.seqn ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_WHINA122 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.rorg=src.rorg) OR (target.rorg IS NULL AND src.rorg IS NULL)) AND
            ((target.orno=src.orno) OR (target.orno IS NULL AND src.orno IS NULL)) AND
            ((target.seqn=src.seqn) OR (target.seqn IS NULL AND src.seqn IS NULL)) 
                when matched then update set
                    target.atse=src.atse, 
                    target.atse_ref_compnr=src.atse_ref_compnr, 
                    target.bfbp=src.bfbp, 
                    target.cact=src.cact, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.clot=src.clot, 
                    target.compnr=src.compnr, 
                    target.cprj=src.cprj, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cstl=src.cstl, 
                    target.cvmo=src.cvmo, 
                    target.cvmo_kw=src.cvmo_kw, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.inwp=src.inwp, 
                    target.inwp_kw=src.inwp_kw, 
                    target.item=src.item, 
                    target.item_ref_compnr=src.item_ref_compnr, 
                    target.lgdt=src.lgdt, 
                    target.logn=src.logn, 
                    target.nval=src.nval, 
                    target.nval_kw=src.nval_kw, 
                    target.nvba=src.nvba, 
                    target.nvba_kw=src.nvba_kw, 
                    target.nvgr=src.nvgr, 
                    target.nvgr_ref_compnr=src.nvgr_ref_compnr, 
                    target.nwvg=src.nwvg, 
                    target.nwvg_kw=src.nwvg_kw, 
                    target.orno=src.orno, 
                    target.oval=src.oval, 
                    target.oval_kw=src.oval_kw, 
                    target.ovba=src.ovba, 
                    target.ovba_kw=src.ovba_kw, 
                    target.ovgr=src.ovgr, 
                    target.ovgr_ref_compnr=src.ovgr_ref_compnr, 
                    target.ownr=src.ownr, 
                    target.owns=src.owns, 
                    target.owns_kw=src.owns_kw, 
                    target.owvg=src.owvg, 
                    target.owvg_kw=src.owvg_kw, 
                    target.quan=src.quan, 
                    target.reje=src.reje, 
                    target.reje_kw=src.reje_kw, 
                    target.rorg=src.rorg, 
                    target.rorg_kw=src.rorg_kw, 
                    target.rowc=src.rowc, 
                    target.rowc_ref_compnr=src.rowc_ref_compnr, 
                    target.rown=src.rown, 
                    target.rown_ref_compnr=src.rown_ref_compnr, 
                    target.rvdt=src.rvdt, 
                    target.rvrs=src.rvrs, 
                    target.rvrs_ref_compnr=src.rvrs_ref_compnr, 
                    target.seqn=src.seqn, 
                    target.sequencenumber=src.sequencenumber, 
                    target.serl=src.serl, 
                    target.site=src.site, 
                    target.site_ref_compnr=src.site_ref_compnr, 
                    target.tagn=src.tagn, 
                    target.timestamp=src.timestamp, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( atse, atse_ref_compnr, bfbp, cact, ccco, ccco_ref_compnr, clot, compnr, cprj, cprj_ref_compnr, cspa, cstl, cvmo, cvmo_kw, cwar, cwar_ref_compnr, deleted, inwp, inwp_kw, item, item_ref_compnr, lgdt, logn, nval, nval_kw, nvba, nvba_kw, nvgr, nvgr_ref_compnr, nwvg, nwvg_kw, orno, oval, oval_kw, ovba, ovba_kw, ovgr, ovgr_ref_compnr, ownr, owns, owns_kw, owvg, owvg_kw, quan, reje, reje_kw, rorg, rorg_kw, rowc, rowc_ref_compnr, rown, rown_ref_compnr, rvdt, rvrs, rvrs_ref_compnr, seqn, sequencenumber, serl, site, site_ref_compnr, tagn, timestamp, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.atse, 
                    src.atse_ref_compnr, 
                    src.bfbp, 
                    src.cact, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.clot, 
                    src.compnr, 
                    src.cprj, 
                    src.cprj_ref_compnr, 
                    src.cspa, 
                    src.cstl, 
                    src.cvmo, 
                    src.cvmo_kw, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.deleted, 
                    src.inwp, 
                    src.inwp_kw, 
                    src.item, 
                    src.item_ref_compnr, 
                    src.lgdt, 
                    src.logn, 
                    src.nval, 
                    src.nval_kw, 
                    src.nvba, 
                    src.nvba_kw, 
                    src.nvgr, 
                    src.nvgr_ref_compnr, 
                    src.nwvg, 
                    src.nwvg_kw, 
                    src.orno, 
                    src.oval, 
                    src.oval_kw, 
                    src.ovba, 
                    src.ovba_kw, 
                    src.ovgr, 
                    src.ovgr_ref_compnr, 
                    src.ownr, 
                    src.owns, 
                    src.owns_kw, 
                    src.owvg, 
                    src.owvg_kw, 
                    src.quan, 
                    src.reje, 
                    src.reje_kw, 
                    src.rorg, 
                    src.rorg_kw, 
                    src.rowc, 
                    src.rowc_ref_compnr, 
                    src.rown, 
                    src.rown_ref_compnr, 
                    src.rvdt, 
                    src.rvrs, 
                    src.rvrs_ref_compnr, 
                    src.seqn, 
                    src.sequencenumber, 
                    src.serl, 
                    src.site, 
                    src.site_ref_compnr, 
                    src.tagn, 
                    src.timestamp, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;