CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5PPMOBJECTS_DELETED(
            PPO_CHANGED varchar, 
            PPO_CLASS varchar, 
            PPO_CLASS_ORG varchar, 
            PPO_COSTCODE varchar, 
            PPO_DEACTIVE datetime, 
            PPO_DORMEND datetime, 
            PPO_DORMREUSE varchar, 
            PPO_DORMSTART datetime, 
            PPO_DUE datetime, 
            PPO_DUENONCONFORMITIESONLY varchar, 
            PPO_FIXED varchar, 
            PPO_FREQ numeric(38, 10), 
            PPO_FROMGEOREF varchar, 
            PPO_FROMPOINT numeric(38, 10), 
            PPO_FROMREFDESC varchar, 
            PPO_INCLUDENONCONFORMITIES varchar, 
            PPO_ISSTYPE varchar, 
            PPO_LASTSAVED datetime, 
            PPO_LOCATION varchar, 
            PPO_LOCATION_ORG varchar, 
            PPO_LOCKEDBYSESSION numeric(38, 10), 
            PPO_METER numeric(38, 10), 
            PPO_METER2 numeric(38, 10), 
            PPO_METERDUE numeric(38, 10), 
            PPO_METERDUE2 numeric(38, 10), 
            PPO_METUOM varchar, 
            PPO_METUOM2 varchar, 
            PPO_MRC varchar, 
            PPO_OBJECT varchar, 
            PPO_OBJECT_ORG varchar, 
            PPO_OBRTYPE varchar, 
            PPO_OBTYPE varchar, 
            PPO_ORG varchar, 
            PPO_PACKAGE varchar, 
            PPO_PERFORMONDAY numeric(38, 10), 
            PPO_PERFORMONWEEK varchar, 
            PPO_PERIODUOM varchar, 
            PPO_PERSON varchar, 
            PPO_PK numeric(38, 10), 
            PPO_PPM varchar, 
            PPO_REVISION numeric(38, 10), 
            PPO_ROUTE varchar, 
            PPO_SCHEDGRP varchar, 
            PPO_SET varchar, 
            PPO_SETID numeric(38, 10), 
            PPO_TOGEOREF varchar, 
            PPO_TOPOINT numeric(38, 10), 
            PPO_TOREFDESC varchar, 
            PPO_UDFCHAR01 varchar, 
            PPO_UDFCHAR02 varchar, 
            PPO_UDFCHAR03 varchar, 
            PPO_UDFCHAR04 varchar, 
            PPO_UDFCHAR05 varchar, 
            PPO_UDFCHAR06 varchar, 
            PPO_UDFCHAR07 varchar, 
            PPO_UDFCHAR08 varchar, 
            PPO_UDFCHAR09 varchar, 
            PPO_UDFCHAR10 varchar, 
            PPO_UDFCHAR11 varchar, 
            PPO_UDFCHAR12 varchar, 
            PPO_UDFCHAR13 varchar, 
            PPO_UDFCHAR14 varchar, 
            PPO_UDFCHAR15 varchar, 
            PPO_UDFCHAR16 varchar, 
            PPO_UDFCHAR17 varchar, 
            PPO_UDFCHAR18 varchar, 
            PPO_UDFCHAR19 varchar, 
            PPO_UDFCHAR20 varchar, 
            PPO_UDFCHAR21 varchar, 
            PPO_UDFCHAR22 varchar, 
            PPO_UDFCHAR23 varchar, 
            PPO_UDFCHAR24 varchar, 
            PPO_UDFCHAR25 varchar, 
            PPO_UDFCHAR26 varchar, 
            PPO_UDFCHAR27 varchar, 
            PPO_UDFCHAR28 varchar, 
            PPO_UDFCHAR29 varchar, 
            PPO_UDFCHAR30 varchar, 
            PPO_UDFCHAR31 varchar, 
            PPO_UDFCHAR32 varchar, 
            PPO_UDFCHAR33 varchar, 
            PPO_UDFCHAR34 varchar, 
            PPO_UDFCHAR35 varchar, 
            PPO_UDFCHAR36 varchar, 
            PPO_UDFCHAR37 varchar, 
            PPO_UDFCHAR38 varchar, 
            PPO_UDFCHAR39 varchar, 
            PPO_UDFCHAR40 varchar, 
            PPO_UDFCHAR41 varchar, 
            PPO_UDFCHAR42 varchar, 
            PPO_UDFCHAR43 varchar, 
            PPO_UDFCHAR44 varchar, 
            PPO_UDFCHAR45 varchar, 
            PPO_UDFCHKBOX01 varchar, 
            PPO_UDFCHKBOX02 varchar, 
            PPO_UDFCHKBOX03 varchar, 
            PPO_UDFCHKBOX04 varchar, 
            PPO_UDFCHKBOX05 varchar, 
            PPO_UDFCHKBOX06 varchar, 
            PPO_UDFCHKBOX07 varchar, 
            PPO_UDFCHKBOX08 varchar, 
            PPO_UDFCHKBOX09 varchar, 
            PPO_UDFCHKBOX10 varchar, 
            PPO_UDFDATE01 datetime, 
            PPO_UDFDATE02 datetime, 
            PPO_UDFDATE03 datetime, 
            PPO_UDFDATE04 datetime, 
            PPO_UDFDATE05 datetime, 
            PPO_UDFDATE06 datetime, 
            PPO_UDFDATE07 datetime, 
            PPO_UDFDATE08 datetime, 
            PPO_UDFDATE09 datetime, 
            PPO_UDFDATE10 datetime, 
            PPO_UDFNOTE01 varchar, 
            PPO_UDFNOTE02 varchar, 
            PPO_UDFNUM01 numeric(38, 10), 
            PPO_UDFNUM02 numeric(38, 10), 
            PPO_UDFNUM03 numeric(38, 10), 
            PPO_UDFNUM04 numeric(38, 10), 
            PPO_UDFNUM05 numeric(38, 10), 
            PPO_UDFNUM06 numeric(38, 10), 
            PPO_UDFNUM07 numeric(38, 10), 
            PPO_UDFNUM08 numeric(38, 10), 
            PPO_UDFNUM09 numeric(38, 10), 
            PPO_UDFNUM10 numeric(38, 10), 
            PPO_UPDATECOUNT numeric(38, 10), 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 