CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5REPPARMS_DELETED(
            PMT_BOTTEXT varchar, 
            PMT_DATATYPE varchar, 
            PMT_DEFAULT varchar, 
            PMT_EWSLOVDEF varchar, 
            PMT_FIXED varchar, 
            PMT_FORMAT varchar, 
            PMT_FUNCTION varchar, 
            PMT_LASTSAVED datetime, 
            PMT_LENGTH numeric(38, 10), 
            PMT_LINE numeric(38, 10), 
            PMT_LOVFUNCTION varchar, 
            PMT_MANDATORY varchar, 
            PMT_MEKEY varchar, 
            PMT_OPTIONS numeric(38, 10), 
            PMT_PARAMETER varchar, 
            PMT_PROPERTY varchar, 
            PMT_QUERY varchar, 
            PMT_REMEMBER varchar, 
            PMT_RENTITY varchar, 
            PMT_RTYPE varchar, 
            PMT_TEST varchar, 
            PMT_UPDATECOUNT numeric(38, 10), 
            PMT_UPDATED datetime, 
            PMT_UPPER varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 