CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5COMPANIES_DELETED(
            COM_ACCOUNTCODE varchar, 
            COM_BUYER varchar, 
            COM_CAPACITY numeric(38, 10), 
            COM_CLASS varchar, 
            COM_CLASS_ORG varchar, 
            COM_CODE varchar, 
            COM_CONTACT varchar, 
            COM_COSTCENTER varchar, 
            COM_CREATED datetime, 
            COM_CURR varchar, 
            COM_CUSTOMER varchar, 
            COM_DESC varchar, 
            COM_EDINO varchar, 
            COM_EMAIL varchar, 
            COM_FAX varchar, 
            COM_FOBPOINT varchar, 
            COM_FREIGHTTERMS varchar, 
            COM_GROUPPURCHASINGORG1 varchar, 
            COM_GROUPPURCHASINGORG2 varchar, 
            COM_INTERFACE datetime, 
            COM_IPACCOUNT varchar, 
            COM_IPRESPONSE varchar, 
            COM_IPVENDOR numeric(38, 10), 
            COM_LANG varchar, 
            COM_LASTSAVED datetime, 
            COM_LASTSTATUSUPDATE datetime, 
            COM_LEADTIME numeric(38, 10), 
            COM_MAXORD numeric(38, 10), 
            COM_MINORD numeric(38, 10), 
            COM_MINORITYGROUP varchar, 
            COM_NOTUSED varchar, 
            COM_ORG varchar, 
            COM_OURCONT varchar, 
            COM_PARENT varchar, 
            COM_PARENT_ORG varchar, 
            COM_PAYBYMETHOD varchar, 
            COM_PAYMENTTERMS varchar, 
            COM_PEOPLE varchar, 
            COM_PHONE varchar, 
            COM_PURCHASESITE varchar, 
            COM_SHIPVIA varchar, 
            COM_SOURCECODE varchar, 
            COM_SOURCESYSTEM varchar, 
            COM_STATUS varchar, 
            COM_TAX varchar, 
            COM_TYPE1099 varchar, 
            COM_UDFCHAR01 varchar, 
            COM_UDFCHAR02 varchar, 
            COM_UDFCHAR03 varchar, 
            COM_UDFCHAR04 varchar, 
            COM_UDFCHAR05 varchar, 
            COM_UDFCHAR06 varchar, 
            COM_UDFCHAR07 varchar, 
            COM_UDFCHAR08 varchar, 
            COM_UDFCHAR09 varchar, 
            COM_UDFCHAR10 varchar, 
            COM_UDFCHAR11 varchar, 
            COM_UDFCHAR12 varchar, 
            COM_UDFCHAR13 varchar, 
            COM_UDFCHAR14 varchar, 
            COM_UDFCHAR15 varchar, 
            COM_UDFCHAR16 varchar, 
            COM_UDFCHAR17 varchar, 
            COM_UDFCHAR18 varchar, 
            COM_UDFCHAR19 varchar, 
            COM_UDFCHAR20 varchar, 
            COM_UDFCHAR21 varchar, 
            COM_UDFCHAR22 varchar, 
            COM_UDFCHAR23 varchar, 
            COM_UDFCHAR24 varchar, 
            COM_UDFCHAR25 varchar, 
            COM_UDFCHAR26 varchar, 
            COM_UDFCHAR27 varchar, 
            COM_UDFCHAR28 varchar, 
            COM_UDFCHAR29 varchar, 
            COM_UDFCHAR30 varchar, 
            COM_UDFCHKBOX01 varchar, 
            COM_UDFCHKBOX02 varchar, 
            COM_UDFCHKBOX03 varchar, 
            COM_UDFCHKBOX04 varchar, 
            COM_UDFCHKBOX05 varchar, 
            COM_UDFDATE01 datetime, 
            COM_UDFDATE02 datetime, 
            COM_UDFDATE03 datetime, 
            COM_UDFDATE04 datetime, 
            COM_UDFDATE05 datetime, 
            COM_UDFNUM01 numeric(38, 10), 
            COM_UDFNUM02 numeric(38, 10), 
            COM_UDFNUM03 numeric(38, 10), 
            COM_UDFNUM04 numeric(38, 10), 
            COM_UDFNUM05 numeric(38, 10), 
            COM_UPDATECOUNT numeric(38, 10), 
            COM_UPDATED datetime, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 