CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5STANDWORKS_DELETED(
            STW_CLASS varchar, 
            STW_CLASS_ORG varchar, 
            STW_CODE varchar, 
            STW_CREATED datetime, 
            STW_CREATEDBY varchar, 
            STW_DESC varchar, 
            STW_DURATION numeric(38, 10), 
            STW_JOBTYPE varchar, 
            STW_LASTSAVED datetime, 
            STW_NOTUSED varchar, 
            STW_OBCLASS varchar, 
            STW_OBCLASS_ORG varchar, 
            STW_OBJECT varchar, 
            STW_OBJECT_ORG varchar, 
            STW_OBRTYPE varchar, 
            STW_OBTYPE varchar, 
            STW_ORG varchar, 
            STW_PERMITREVIEWED datetime, 
            STW_PERMITREVIEWEDBY varchar, 
            STW_PERMITREVIEWEDNAME varchar, 
            STW_PERMITREVIEWEDTYPE varchar, 
            STW_PERMITREVIEWREQUIRED datetime, 
            STW_PRIORITY varchar, 
            STW_REQM varchar, 
            STW_SAFETYREVIEWED datetime, 
            STW_SAFETYREVIEWEDBY varchar, 
            STW_SAFETYREVIEWEDNAME varchar, 
            STW_SAFETYREVIEWEDTYPE varchar, 
            STW_SAFETYREVIEWREQUIRED datetime, 
            STW_TYPE varchar, 
            STW_UDFCHAR01 varchar, 
            STW_UDFCHAR02 varchar, 
            STW_UDFCHAR03 varchar, 
            STW_UDFCHAR04 varchar, 
            STW_UDFCHAR05 varchar, 
            STW_UDFCHAR06 varchar, 
            STW_UDFCHAR07 varchar, 
            STW_UDFCHAR08 varchar, 
            STW_UDFCHAR09 varchar, 
            STW_UDFCHAR10 varchar, 
            STW_UDFCHAR11 varchar, 
            STW_UDFCHAR12 varchar, 
            STW_UDFCHAR13 varchar, 
            STW_UDFCHAR14 varchar, 
            STW_UDFCHAR15 varchar, 
            STW_UDFCHAR16 varchar, 
            STW_UDFCHAR17 varchar, 
            STW_UDFCHAR18 varchar, 
            STW_UDFCHAR19 varchar, 
            STW_UDFCHAR20 varchar, 
            STW_UDFCHAR21 varchar, 
            STW_UDFCHAR22 varchar, 
            STW_UDFCHAR23 varchar, 
            STW_UDFCHAR24 varchar, 
            STW_UDFCHAR25 varchar, 
            STW_UDFCHAR26 varchar, 
            STW_UDFCHAR27 varchar, 
            STW_UDFCHAR28 varchar, 
            STW_UDFCHAR29 varchar, 
            STW_UDFCHAR30 varchar, 
            STW_UDFCHAR31 varchar, 
            STW_UDFCHAR32 varchar, 
            STW_UDFCHAR33 varchar, 
            STW_UDFCHAR34 varchar, 
            STW_UDFCHAR35 varchar, 
            STW_UDFCHAR36 varchar, 
            STW_UDFCHAR37 varchar, 
            STW_UDFCHAR38 varchar, 
            STW_UDFCHAR39 varchar, 
            STW_UDFCHAR40 varchar, 
            STW_UDFCHAR41 varchar, 
            STW_UDFCHAR42 varchar, 
            STW_UDFCHAR43 varchar, 
            STW_UDFCHAR44 varchar, 
            STW_UDFCHAR45 varchar, 
            STW_UDFCHAR46 varchar, 
            STW_UDFCHAR47 varchar, 
            STW_UDFCHAR48 varchar, 
            STW_UDFCHAR49 varchar, 
            STW_UDFCHAR50 varchar, 
            STW_UDFCHAR51 varchar, 
            STW_UDFCHAR52 varchar, 
            STW_UDFCHAR53 varchar, 
            STW_UDFCHAR54 varchar, 
            STW_UDFCHAR55 varchar, 
            STW_UDFCHKBOX01 varchar, 
            STW_UDFCHKBOX02 varchar, 
            STW_UDFCHKBOX03 varchar, 
            STW_UDFCHKBOX04 varchar, 
            STW_UDFCHKBOX05 varchar, 
            STW_UDFCHKBOX06 varchar, 
            STW_UDFCHKBOX07 varchar, 
            STW_UDFCHKBOX08 varchar, 
            STW_UDFCHKBOX09 varchar, 
            STW_UDFCHKBOX10 varchar, 
            STW_UDFDATE01 datetime, 
            STW_UDFDATE02 datetime, 
            STW_UDFDATE03 datetime, 
            STW_UDFDATE04 datetime, 
            STW_UDFDATE05 datetime, 
            STW_UDFDATE06 datetime, 
            STW_UDFDATE07 datetime, 
            STW_UDFDATE08 datetime, 
            STW_UDFDATE09 datetime, 
            STW_UDFDATE10 datetime, 
            STW_UDFNOTE01 varchar, 
            STW_UDFNOTE02 varchar, 
            STW_UDFNUM01 numeric(38, 10), 
            STW_UDFNUM02 numeric(38, 10), 
            STW_UDFNUM03 numeric(38, 10), 
            STW_UDFNUM04 numeric(38, 10), 
            STW_UDFNUM05 numeric(38, 10), 
            STW_UDFNUM06 numeric(38, 10), 
            STW_UDFNUM07 numeric(38, 10), 
            STW_UDFNUM08 numeric(38, 10), 
            STW_UDFNUM09 numeric(38, 10), 
            STW_UDFNUM10 numeric(38, 10), 
            STW_UPDATECOUNT numeric(38, 10), 
            STW_UPDATED datetime, 
            STW_UPDATEDBY varchar, 
            STW_WOCLASS varchar, 
            STW_WOCLASS_ORG varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 