CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TSCTM500_DELETED(
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            cwoc varchar, 
            cwoc_ref_compnr integer, 
            cwte varchar, 
            cwte_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            efdt date, 
            exdt date, 
            gwte varchar, 
            nrpe integer, 
            peru integer, 
            peru_kw varchar, 
            sequencenumber integer, 
            term integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            uprd integer, 
            uprd_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 