CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TSCTM450_DELETED(
            acpp_1 numeric(38, 17), 
            acpp_2 numeric(38, 17), 
            acpp_3 numeric(38, 17), 
            cchn integer, 
            cfln integer, 
            compnr integer, 
            csco varchar, 
            csco_cchn_ref_compnr integer, 
            csco_ref_compnr integer, 
            cvdy integer, 
            deleted boolean, 
            esco_1 numeric(38, 17), 
            esco_2 numeric(38, 17), 
            esco_3 numeric(38, 17), 
            esrv numeric(38, 17), 
            esrv_dwhc numeric(38, 17), 
            esrv_homc numeric(38, 17), 
            esrv_refc numeric(38, 17), 
            esrv_rpc1 numeric(38, 17), 
            esrv_rpc2 numeric(38, 17), 
            fspr integer, 
            fsyr integer, 
            nody integer, 
            rcrv numeric(38, 17), 
            rcrv_dwhc numeric(38, 17), 
            rcrv_homc numeric(38, 17), 
            rcrv_refc numeric(38, 17), 
            rcrv_rpc1 numeric(38, 17), 
            rcrv_rpc2 numeric(38, 17), 
            sequencenumber integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 