CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFGLD007_DELETED(
            compnr integer, 
            dacp datetime, 
            dacr datetime, 
            dcmg datetime, 
            deleted boolean, 
            dgld datetime, 
            dint datetime, 
            prno integer, 
            ptyp integer, 
            ptyp_kw varchar, 
            ptyp_year_prno_ref_compnr integer, 
            sacp integer, 
            sacp_kw varchar, 
            sacr integer, 
            sacr_kw varchar, 
            scmg integer, 
            scmg_kw varchar, 
            sequencenumber integer, 
            sgld integer, 
            sgld_kw varchar, 
            sint integer, 
            sint_kw varchar, 
            timestamp datetime, 
            uacp varchar, 
            uacr varchar, 
            ucmg varchar, 
            ugld varchar, 
            uint varchar, 
            username varchar, 
            year integer, 
            year_ref_compnr integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 