CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TIROU002_DELETED(
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            cpcp varchar, 
            cpcp_ref_compnr integer, 
            cwoc varchar, 
            cwoc_ref_compnr integer, 
            deleted boolean, 
            dque numeric(38, 17), 
            dsca object, 
            mccp numeric(38, 17), 
            mcno varchar, 
            mcrt_1 numeric(38, 17), 
            mcrt_2 numeric(38, 17), 
            mcrt_3 numeric(38, 17), 
            mdcp numeric(38, 17), 
            mere integer, 
            mere_kw varchar, 
            mewo varchar, 
            sequencenumber integer, 
            site varchar, 
            site_ref_compnr integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 