CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TSSOC205_DELETED(
            acdu numeric(38, 17), 
            acln integer, 
            actm datetime, 
            actp integer, 
            actp_kw varchar, 
            aftm datetime, 
            astm datetime, 
            atft datetime, 
            atst datetime, 
            cmbb_orno_acln_ref_compnr integer, 
            cmbc_orno_acln_ref_compnr integer, 
            compnr integer, 
            deleted boolean, 
            dltm datetime, 
            emno varchar, 
            emno_ref_compnr integer, 
            esdt datetime, 
            jctm datetime, 
            line integer, 
            ltct datetime, 
            orgn integer, 
            orgn_kw varchar, 
            orno varchar, 
            pftm datetime, 
            pgcn integer, 
            pgdt datetime, 
            pged integer, 
            pged_kw varchar, 
            pgit integer, 
            pgrd integer, 
            pgrd_kw varchar, 
            pstm datetime, 
            ptft datetime, 
            ptst datetime, 
            rejr varchar, 
            rejr_ref_compnr integer, 
            rjtm datetime, 
            sequencenumber integer, 
            stat integer, 
            stat_kw varchar, 
            timestamp datetime, 
            trdi numeric(38, 17), 
            trdi_buln numeric(38, 17), 
            trdu numeric(38, 17), 
            trdu_butm numeric(38, 17), 
            txta integer, 
            txta_ref_compnr integer, 
            uecp integer, 
            uecp_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 