CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFFAM110_DELETED(
            adpa_1 numeric(38, 17), 
            adpa_2 numeric(38, 17), 
            adpa_3 numeric(38, 17), 
            adpc integer, 
            adpc_kw varchar, 
            adpm varchar, 
            adpm_ref_compnr integer, 
            aext varchar, 
            anbr varchar, 
            anbr_aext_ref_compnr integer, 
            book varchar, 
            book_ref_compnr integer, 
            bslv integer, 
            bslv_kw varchar, 
            c263_1 numeric(38, 17), 
            c263_2 numeric(38, 17), 
            c263_3 numeric(38, 17), 
            capi_1 numeric(38, 17), 
            capi_2 numeric(38, 17), 
            capi_3 numeric(38, 17), 
            compnr integer, 
            cost_1 numeric(38, 17), 
            cost_2 numeric(38, 17), 
            cost_3 numeric(38, 17), 
            curd date, 
            deleted boolean, 
            depr_1 numeric(38, 17), 
            depr_2 numeric(38, 17), 
            depr_3 numeric(38, 17), 
            disd date, 
            ecre integer, 
            ecre_kw varchar, 
            freq varchar, 
            freq_ref_compnr integer, 
            fydp numeric(38, 17), 
            gfac_1 numeric(38, 17), 
            gfac_2 numeric(38, 17), 
            gfac_3 numeric(38, 17), 
            indx varchar, 
            indx_ref_compnr integer, 
            itca_1 numeric(38, 17), 
            itca_2 numeric(38, 17), 
            itca_3 numeric(38, 17), 
            last date, 
            life integer, 
            lrev integer, 
            ltad_1 numeric(38, 17), 
            ltad_2 numeric(38, 17), 
            ltad_3 numeric(38, 17), 
            ltar_1 numeric(38, 17), 
            ltar_2 numeric(38, 17), 
            ltar_3 numeric(38, 17), 
            ltdd_1 numeric(38, 17), 
            ltdd_2 numeric(38, 17), 
            ltdd_3 numeric(38, 17), 
            ltdr_1 numeric(38, 17), 
            ltdr_2 numeric(38, 17), 
            ltdr_3 numeric(38, 17), 
            meth varchar, 
            meth_ref_compnr integer, 
            ocst_1 numeric(38, 17), 
            ocst_2 numeric(38, 17), 
            ocst_3 numeric(38, 17), 
            post integer, 
            post_kw varchar, 
            prop varchar, 
            prop_ref_compnr integer, 
            rcst_1 numeric(38, 17), 
            rcst_2 numeric(38, 17), 
            rcst_3 numeric(38, 17), 
            rdpr_1 numeric(38, 17), 
            rdpr_2 numeric(38, 17), 
            rdpr_3 numeric(38, 17), 
            s179_1 numeric(38, 17), 
            s179_2 numeric(38, 17), 
            s179_3 numeric(38, 17), 
            salv_1 numeric(38, 17), 
            salv_2 numeric(38, 17), 
            salv_3 numeric(38, 17), 
            sdpn integer, 
            sequencenumber integer, 
            shft numeric(38, 17), 
            srac integer, 
            srac_kw varchar, 
            stat integer, 
            stat_kw varchar, 
            timestamp datetime, 
            tmth integer, 
            tmth_kw varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            unit integer, 
            username varchar, 
            ytdd_1 numeric(38, 17), 
            ytdd_2 numeric(38, 17), 
            ytdd_3 numeric(38, 17), 
            ytdr_1 numeric(38, 17), 
            ytdr_2 numeric(38, 17), 
            ytdr_3 numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 