CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TIROU003_DELETED(
            compnr integer, 
            cwoc varchar, 
            cwoc_ref_compnr integer, 
            deleted boolean, 
            dsca object, 
            exin varchar, 
            mcno varchar, 
            mcno_ref_compnr integer, 
            mlmc integer, 
            mlmc_kw varchar, 
            mlwc integer, 
            mlwc_kw varchar, 
            seak object, 
            sequencenumber integer, 
            tano varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 