CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPTC127_DELETED(
            amoc numeric(38, 17), 
            bsqn integer, 
            btdt datetime, 
            cact varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            ccit varchar, 
            cocu varchar, 
            cocu_ref_compnr integer, 
            compnr integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            deleted boolean, 
            dfpr numeric(38, 17), 
            effn integer, 
            effn_ref_compnr integer, 
            exep integer, 
            exep_kw varchar, 
            item varchar, 
            item_ref_compnr integer, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            prdt datetime, 
            quan numeric(38, 17), 
            rtcc_1 numeric(38, 17), 
            rtcc_2 numeric(38, 17), 
            rtcc_3 numeric(38, 17), 
            rtfc_1 integer, 
            rtfc_2 integer, 
            rtfc_3 integer, 
            sequencenumber integer, 
            sern integer, 
            shft integer, 
            timestamp datetime, 
            tsrl integer, 
            tsrl_kw varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 