CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFGLD202_DELETED(
            bpid varchar, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            cono integer, 
            deleted boolean, 
            dimx varchar, 
            dtyp integer, 
            duac integer, 
            duac_kw varchar, 
            fcah_1 numeric(38, 17), 
            fcah_2 numeric(38, 17), 
            fcah_3 numeric(38, 17), 
            fcam numeric(38, 17), 
            fdah_1 numeric(38, 17), 
            fdah_2 numeric(38, 17), 
            fdah_3 numeric(38, 17), 
            fdam numeric(38, 17), 
            fqt1 numeric(38, 17), 
            fqt2 numeric(38, 17), 
            leac varchar, 
            ncah_1 numeric(38, 17), 
            ncah_2 numeric(38, 17), 
            ncah_3 numeric(38, 17), 
            ncam numeric(38, 17), 
            ndah_1 numeric(38, 17), 
            ndah_2 numeric(38, 17), 
            ndah_3 numeric(38, 17), 
            ndam numeric(38, 17), 
            nqt1 numeric(38, 17), 
            nqt2 numeric(38, 17), 
            prno integer, 
            ptyp integer, 
            ptyp_kw varchar, 
            sequencenumber integer, 
            timestamp datetime, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 