CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPTC160_DELETED(
            amoc numeric(38, 17), 
            amos numeric(38, 17), 
            btdt datetime, 
            cact varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            cico varchar, 
            cocu varchar, 
            cocu_ref_compnr integer, 
            compnr integer, 
            cona numeric(38, 17), 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            deleted boolean, 
            dfpc integer, 
            dfpc_kw varchar, 
            pric numeric(38, 17), 
            pris numeric(38, 17), 
            quan numeric(38, 17), 
            rtcc_1 numeric(38, 17), 
            rtcc_2 numeric(38, 17), 
            rtcc_3 numeric(38, 17), 
            rtcs_1 numeric(38, 17), 
            rtcs_2 numeric(38, 17), 
            rtcs_3 numeric(38, 17), 
            rtfc_1 integer, 
            rtfc_2 integer, 
            rtfc_3 integer, 
            rtfs_1 integer, 
            rtfs_2 integer, 
            rtfs_3 integer, 
            sacu varchar, 
            sacu_ref_compnr integer, 
            sequencenumber integer, 
            sern integer, 
            stat integer, 
            stat_kw varchar, 
            timestamp datetime, 
            trts integer, 
            trts_kw varchar, 
            tsrl integer, 
            tsrl_kw varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 