CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TCMCS041_DELETED(
            cdec varchar, 
            cdyn integer, 
            cdyn_kw varchar, 
            compnr integer, 
            cptp integer, 
            cptp_kw varchar, 
            crpd integer, 
            crpd_kw varchar, 
            deleted boolean, 
            dsca object, 
            fcba varchar, 
            fcba_ref_compnr integer, 
            potp integer, 
            potp_kw varchar, 
            sequencenumber integer, 
            spec integer, 
            spec_kw varchar, 
            tdgp integer, 
            tdgp_kw varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 