CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFGLD206_DELETED(
            bpid varchar, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            cono integer, 
            deleted boolean, 
            dim1 varchar, 
            dim2 varchar, 
            dim3 varchar, 
            dim4 varchar, 
            dim5 varchar, 
            dim6 varchar, 
            dim7 varchar, 
            dim8 varchar, 
            dim9 varchar, 
            dims varchar, 
            dimx_sgm1 varchar, 
            dimx_sgm2 varchar, 
            dm10 varchar, 
            dm11 varchar, 
            dm12 varchar, 
            duac integer, 
            duac_kw varchar, 
            fobh_1 numeric(38, 17), 
            fobh_2 numeric(38, 17), 
            fobh_3 numeric(38, 17), 
            fobh_dtwc numeric(38, 17), 
            fobh_rfrc numeric(38, 17), 
            ftob numeric(38, 17), 
            leac varchar, 
            nob1 numeric(38, 17), 
            nob2 numeric(38, 17), 
            nobh_1 numeric(38, 17), 
            nobh_2 numeric(38, 17), 
            nobh_3 numeric(38, 17), 
            nobh_dtwc numeric(38, 17), 
            nobh_rfrc numeric(38, 17), 
            ntob numeric(38, 17), 
            olap integer, 
            qob1 numeric(38, 17), 
            qob2 numeric(38, 17), 
            sequencenumber integer, 
            timestamp datetime, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 