CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TIIPD001_DELETED(
            bfcp integer, 
            bfcp_kw varchar, 
            bfep integer, 
            bfep_kw varchar, 
            bfhr integer, 
            bfhr_kw varchar, 
            bomu integer, 
            bomu_kw varchar, 
            cick integer, 
            cick_kw varchar, 
            cncd varchar, 
            coac integer, 
            coac_kw varchar, 
            compnr integer, 
            cpha integer, 
            cpha_kw varchar, 
            deleted boolean, 
            drin integer, 
            drin_kw varchar, 
            dris integer, 
            dris_kw varchar, 
            iima integer, 
            iima_kw varchar, 
            iimf integer, 
            iimf_kw varchar, 
            item varchar, 
            item_ref_compnr integer, 
            iuma integer, 
            iuma_kw varchar, 
            jsst varchar, 
            nsfc integer, 
            nsfc_kw varchar, 
            oltm numeric(38, 17), 
            oltu integer, 
            oltu_kw varchar, 
            oqdr integer, 
            oqdr_kw varchar, 
            pcrp integer, 
            phst integer, 
            phst_kw varchar, 
            repi integer, 
            repi_kw varchar, 
            rgrp varchar, 
            rgrp_ref_compnr integer, 
            runi numeric(38, 17), 
            scdl varchar, 
            scdl_ref_compnr integer, 
            scpf numeric(38, 17), 
            scpq numeric(38, 17), 
            seak object, 
            sequencenumber integer, 
            sfpl varchar, 
            sfpl_ref_compnr integer, 
            smfs integer, 
            smfs_kw varchar, 
            stoi integer, 
            stoi_kw varchar, 
            swoc integer, 
            swoc_kw varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            unom numeric(38, 17), 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 