CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPIN020_DELETED(
            bpcl varchar, 
            bpcl_ref_compnr integer, 
            bptc varchar, 
            bptc_ref_compnr integer, 
            cact varchar, 
            catv numeric(38, 17), 
            ccrs varchar, 
            ccrs_ref_compnr integer, 
            ccty varchar, 
            ccty_cvat_ref_compnr integer, 
            ccty_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            ceno varchar, 
            clos integer, 
            clos_kw varchar, 
            cnln varchar, 
            cnpr varchar, 
            cnpr_cpla_cact_ref_compnr integer, 
            cnpr_cpla_ref_compnr integer, 
            cnpr_cpla_tact_ref_compnr integer, 
            cnpr_cspa_ref_compnr integer, 
            cnpr_ref_compnr integer, 
            compnr integer, 
            cono varchar, 
            cono_cnln_hbnr_cprj_ofbp_ref_compnr integer, 
            cono_cnln_ref_compnr integer, 
            cono_ref_compnr integer, 
            cpay varchar, 
            cpay_ref_compnr integer, 
            cpla varchar, 
            cpra varchar, 
            cprj varchar, 
            cprj_cpra varchar, 
            cprj_cpro varchar, 
            cprj_ref_compnr integer, 
            cpro varchar, 
            cspa varchar, 
            cstv numeric(38, 17), 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            cvat varchar, 
            cvat_ref_compnr integer, 
            cvyn integer, 
            cvyn_kw varchar, 
            deleted boolean, 
            desc object, 
            disc numeric(38, 17), 
            dsca object, 
            exmt integer, 
            exmt_kw varchar, 
            exrs varchar, 
            exrs_ref_compnr integer, 
            fcma integer, 
            fcmp integer, 
            fins integer, 
            fins_kw varchar, 
            hbai numeric(38, 17), 
            hbnr integer, 
            hbpc numeric(38, 17), 
            hbyn integer, 
            hbyn_kw varchar, 
            idca integer, 
            idoc integer, 
            iiaa numeric(38, 17), 
            iiaa_cntc numeric(38, 17), 
            iiaa_dwhc numeric(38, 17), 
            iiaa_homc numeric(38, 17), 
            iiaa_prjc numeric(38, 17), 
            iiaa_refc numeric(38, 17), 
            iiaa_rpc1 numeric(38, 17), 
            iiaa_rpc2 numeric(38, 17), 
            inaa numeric(38, 17), 
            inaa_cntc numeric(38, 17), 
            inaa_dwhc numeric(38, 17), 
            inaa_homc numeric(38, 17), 
            inaa_prjc numeric(38, 17), 
            inaa_refc numeric(38, 17), 
            inaa_rpc1 numeric(38, 17), 
            inaa_rpc2 numeric(38, 17), 
            inia numeric(38, 17), 
            inia_cntc numeric(38, 17), 
            inia_dwhc numeric(38, 17), 
            inia_homc numeric(38, 17), 
            inia_prjc numeric(38, 17), 
            inia_refc numeric(38, 17), 
            inia_rpc1 numeric(38, 17), 
            inia_rpc2 numeric(38, 17), 
            inpo integer, 
            inpr numeric(38, 17), 
            insa numeric(38, 17), 
            insa_cntc numeric(38, 17), 
            insa_dwhc numeric(38, 17), 
            insa_homc numeric(38, 17), 
            insa_prjc numeric(38, 17), 
            insa_refc numeric(38, 17), 
            insa_rpc1 numeric(38, 17), 
            insa_rpc2 numeric(38, 17), 
            invo integer, 
            invo_kw varchar, 
            itpa varchar, 
            ityp varchar, 
            nins integer, 
            nper numeric(38, 17), 
            npoi integer, 
            ofbp varchar, 
            ofbp_ref_compnr integer, 
            paym varchar, 
            peru datetime, 
            pfdt datetime, 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rdat datetime, 
            sequencenumber integer, 
            sidt datetime, 
            tact varchar, 
            tcst integer, 
            tcst_kw varchar, 
            tiaa numeric(38, 17), 
            tiaa_cntc numeric(38, 17), 
            tiaa_dwhc numeric(38, 17), 
            tiaa_homc numeric(38, 17), 
            tiaa_prjc numeric(38, 17), 
            tiaa_refc numeric(38, 17), 
            tiaa_rpc1 numeric(38, 17), 
            tiaa_rpc2 numeric(38, 17), 
            tiia numeric(38, 17), 
            tiia_cntc numeric(38, 17), 
            tiia_dwhc numeric(38, 17), 
            tiia_homc numeric(38, 17), 
            tiia_prjc numeric(38, 17), 
            tiia_refc numeric(38, 17), 
            tiia_rpc1 numeric(38, 17), 
            tiia_rpc2 numeric(38, 17), 
            timestamp datetime, 
            tipo integer, 
            tipr numeric(38, 17), 
            toin integer, 
            toin_kw varchar, 
            trsl integer, 
            trsl_kw varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 