CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TCEMM030_DELETED(
            ccal varchar, 
            ccal_ref_compnr integer, 
            compnr integer, 
            deleted boolean, 
            dfco varchar, 
            dfpo varchar, 
            dsca object, 
            duns integer, 
            euca varchar, 
            euca_ref_compnr integer, 
            eunt varchar, 
            fcmp integer, 
            fcmp_ref_compnr integer, 
            lcmp integer, 
            lcmp_ref_compnr integer, 
            ract varchar, 
            ract_ref_compnr integer, 
            sequencenumber integer, 
            site varchar, 
            site_ref_compnr integer, 
            timestamp datetime, 
            txtn integer, 
            txtn_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 