CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TCCOM161_DELETED(
            cadr varchar, 
            cadr_ref_compnr integer, 
            compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            imcs varchar, 
            ofbp varchar, 
            ofbp_ref_compnr integer, 
            sequencenumber integer, 
            site varchar, 
            site_ref_compnr integer, 
            stbp varchar, 
            stbp_ref_compnr integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 