CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_WHINH210_DELETED(
            acti object, 
            acvt integer, 
            acvt_kw varchar, 
            adin varchar, 
            atse varchar, 
            atse_ref_compnr integer, 
            bflh integer, 
            bflh_kw varchar, 
            bgxc integer, 
            bgxc_kw varchar, 
            blck integer, 
            blck_kw varchar, 
            bpit object, 
            casi varchar, 
            casi_ref_compnr integer, 
            cdck integer, 
            cdck_kw varchar, 
            clot varchar, 
            cmnf varchar, 
            cmnf_ref_compnr integer, 
            comp integer, 
            compnr integer, 
            csvc varchar, 
            csvc_ref_compnr integer, 
            csvl numeric(38, 17), 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            dslo varchar, 
            effn integer, 
            effn_ref_compnr integer, 
            fact varchar, 
            fcco varchar, 
            fcco_ref_compnr integer, 
            fire integer, 
            fire_kw varchar, 
            fmln integer, 
            fmor varchar, 
            fprj varchar, 
            fprj_ref_compnr integer, 
            fshl integer, 
            fshn varchar, 
            fspa varchar, 
            fstl varchar, 
            gefo integer, 
            gefo_kw varchar, 
            gnld varchar, 
            hstd integer, 
            hstd_kw varchar, 
            hstq integer, 
            hstq_kw varchar, 
            insp integer, 
            insp_kw varchar, 
            inup integer, 
            inup_kw varchar, 
            ipay integer, 
            ipay_kw varchar, 
            item varchar, 
            item_atse_ref_compnr integer, 
            item_clot_ref_compnr integer, 
            item_pkdf_ref_compnr integer, 
            item_ref_compnr integer, 
            iubw integer, 
            iubw_kw varchar, 
            kbpr integer, 
            kbpr_kw varchar, 
            lccl varchar, 
            lccl_ref_compnr integer, 
            lsel integer, 
            lsel_kw varchar, 
            lsta integer, 
            lsta_kw varchar, 
            mpnr varchar, 
            ocur varchar, 
            ocur_ref_compnr integer, 
            oorg integer, 
            oorg_kw varchar, 
            oorg_orno_oset_ref_compnr integer, 
            orno varchar, 
            orpr numeric(38, 17), 
            orun varchar, 
            orun_ref_compnr integer, 
            oset integer, 
            ownr varchar, 
            ownr_ref_compnr integer, 
            owns integer, 
            owns_kw varchar, 
            paym integer, 
            paym_kw varchar, 
            pkdf varchar, 
            pkdf_ref_compnr integer, 
            pmsk varchar, 
            pono integer, 
            prdt datetime, 
            prjp integer, 
            prjp_kw varchar, 
            psqp numeric(38, 17), 
            psqu numeric(38, 17), 
            qadi numeric(38, 17), 
            qadp numeric(38, 17), 
            qadv numeric(38, 17), 
            qapp numeric(38, 17), 
            qapr numeric(38, 17), 
            qapu numeric(38, 17), 
            qdep numeric(38, 17), 
            qdes numeric(38, 17), 
            qgip numeric(38, 17), 
            qgit numeric(38, 17), 
            qiip numeric(38, 17), 
            qiit numeric(38, 17), 
            qopu numeric(38, 17), 
            qorc numeric(38, 17), 
            qord numeric(38, 17), 
            qoro numeric(38, 17), 
            qorp numeric(38, 17), 
            qppu numeric(38, 17), 
            qpui numeric(38, 17), 
            qpup numeric(38, 17), 
            qput numeric(38, 17), 
            qrec numeric(38, 17), 
            qrej numeric(38, 17), 
            qrep numeric(38, 17), 
            qrpu numeric(38, 17), 
            qrsc numeric(38, 17), 
            qrsp numeric(38, 17), 
            qtbp numeric(38, 17), 
            qtbr numeric(38, 17), 
            rclo varchar, 
            refe object, 
            revi varchar, 
            rorg integer, 
            rorg_kw varchar, 
            rorn varchar, 
            rowc integer, 
            rowc_ref_compnr integer, 
            rown varchar, 
            rown_ref_compnr integer, 
            rpon integer, 
            rseq integer, 
            seqn integer, 
            sequencenumber integer, 
            serl varchar, 
            sfbp varchar, 
            sfbp_ref_compnr integer, 
            spcn varchar, 
            stag varchar, 
            tact varchar, 
            tcco varchar, 
            tcco_ref_compnr integer, 
            timestamp datetime, 
            tlot varchar, 
            tprj varchar, 
            tprj_ref_compnr integer, 
            tspa varchar, 
            tsrl varchar, 
            tstl varchar, 
            txtn integer, 
            txtn_ref_compnr integer, 
            username varchar, 
            uwop integer, 
            uwop_kw varchar, 
            wmss integer, 
            wmss_kw varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 