CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_WHINA117_DELETED(
            amnt_1 numeric(38, 17), 
            amnt_2 numeric(38, 17), 
            amnt_3 numeric(38, 17), 
            compnr integer, 
            cpcp varchar, 
            cpcp_ref_compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            hour numeric(38, 17), 
            item varchar, 
            item_cwar_trdt_seqn_ref_compnr integer, 
            item_ref_compnr integer, 
            namt_1 numeric(38, 17), 
            namt_2 numeric(38, 17), 
            namt_3 numeric(38, 17), 
            oamt_1 numeric(38, 17), 
            oamt_2 numeric(38, 17), 
            oamt_3 numeric(38, 17), 
            seqn integer, 
            sequencenumber integer, 
            timestamp datetime, 
            trdt datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 