CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_WHINH500_DELETED(
            ccst integer, 
            ccst_kw varchar, 
            cdf_rdte datetime, 
            cdf_rfin integer, 
            cdf_rfin_kw varchar, 
            cdf_rusr varchar, 
            cntn integer, 
            compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            emno varchar, 
            emno_ref_compnr integer, 
            odat datetime, 
            orno varchar, 
            prcc integer, 
            prcc_kw varchar, 
            prnt integer, 
            prnt_kw varchar, 
            rcyn integer, 
            rcyn_kw varchar, 
            redt datetime, 
            refe object, 
            sequencenumber integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 