CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_WHINA113_DELETED(
            amac_1 numeric(38, 17), 
            amac_2 numeric(38, 17), 
            amac_3 numeric(38, 17), 
            amah numeric(38, 17), 
            amnt_1 numeric(38, 17), 
            amnt_2 numeric(38, 17), 
            amnt_3 numeric(38, 17), 
            atmc_1 numeric(38, 17), 
            atmc_2 numeric(38, 17), 
            atmc_3 numeric(38, 17), 
            atmh numeric(38, 17), 
            compnr integer, 
            cpcp varchar, 
            cpcp_ref_compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            deleted boolean, 
            hour numeric(38, 17), 
            inwp integer, 
            inwp_kw varchar, 
            item varchar, 
            item_cwar_trdt_seqn_inwp_ref_compnr integer, 
            item_ref_compnr integer, 
            matc_1 numeric(38, 17), 
            matc_2 numeric(38, 17), 
            matc_3 numeric(38, 17), 
            math numeric(38, 17), 
            mauc_1 numeric(38, 17), 
            mauc_2 numeric(38, 17), 
            mauc_3 numeric(38, 17), 
            mauh numeric(38, 17), 
            seqn integer, 
            sequencenumber integer, 
            timestamp datetime, 
            trdt datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 