CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_WHINH310_DELETED(
            carr varchar, 
            carr_ref_compnr integer, 
            compnr integer, 
            conf integer, 
            conf_kw varchar, 
            crdt datetime, 
            curr varchar, 
            curr_ref_compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            cwun varchar, 
            cwun_ref_compnr integer, 
            deleted boolean, 
            dino object, 
            fval numeric(38, 17), 
            huid varchar, 
            huid_ref_compnr integer, 
            imre object, 
            imrk object, 
            irdt datetime, 
            load varchar, 
            pddt datetime, 
            port varchar, 
            port_ref_compnr integer, 
            rcno varchar, 
            sequencenumber integer, 
            sfbp varchar, 
            sfbp_ref_compnr integer, 
            shda varchar, 
            shda_ref_compnr integer, 
            shdt datetime, 
            shid varchar, 
            stat integer, 
            stat_kw varchar, 
            tcap integer, 
            tcap_kw varchar, 
            tccp integer, 
            tccp_kw varchar, 
            text integer, 
            text_ref_compnr integer, 
            timestamp datetime, 
            trcd varchar, 
            username varchar, 
            wght numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 