create or replace procedure DATAHUB_INTEGRATION.SP_IPS_ASSETMANAGEMENT_FLEET_COMPVEH()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_ASSETMANAGEMENT_FLEET_COMPVEH_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_ASSETMANAGEMENT_FLEET_COMPVEH as target using (SELECT * FROM (SELECT 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.ADDRQUAL, 
            strm.AREA, 
            strm.AVGMONUSG, 
            strm.AVGMONUSGUOM, 
            strm.AXLE, 
            strm.BGTNO, 
            strm.BLDGFLOOR, 
            strm.BLDGROOM, 
            strm.BUDGETKEY, 
            strm.COMPKEY, 
            strm.COMPLEXKEY, 
            strm.CYLINDERS, 
            strm.DATALAKE_DELETED, 
            strm.DISTRICT, 
            strm.DRIVERCLAS, 
            strm.ENGINENO, 
            strm.ENGINETYPE, 
            strm.EXPBY, 
            strm.EXPDATE, 
            strm.EXPECTLIFE, 
            strm.EXPECTLIFEUOM, 
            strm.GVW, 
            strm.GVWUOM, 
            strm.INSTDATE, 
            strm.INTKEY, 
            strm.LICENSE, 
            strm.LOC, 
            strm.MAPNO, 
            strm.MFGDATE, 
            strm.MFGKEY, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MODELNO, 
            strm.MODELYR, 
            strm.MTBF, 
            strm.NOTIRES, 
            strm.OWN, 
            strm.POSITION, 
            strm.PRCLKEY, 
            strm.PURCCOST, 
            strm.PURCDATE, 
            strm.SERNO, 
            strm.SERVSTAT, 
            strm.SITEKEY, 
            strm.SUBAREA, 
            strm.TIRESIZE, 
            strm.TIRETYPE, 
            strm.TRANSMISSN, 
            strm.UNITDESC, 
            strm.UNITID, 
            strm.UNITTYPE, 
            strm.USGAREAKEY, 
            strm.USGDATE, 
            strm.USGTOT, 
            strm.USGTOTUOM, 
            strm.VARIATION_ID, 
            strm.VEHSZ, 
            strm.VEHSZUOM, 
            strm.VIN, 
            strm.WARREXP, 
            strm.WARRUSG, 
            strm.XCOORD, 
            strm.YCOORD, 
            strm.ZCOORD, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.COMPKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_ASSETMANAGEMENT_FLEET_COMPVEH as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.COMPKEY=src.COMPKEY) OR (target.COMPKEY IS NULL AND src.COMPKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.ADDRQUAL=src.ADDRQUAL, 
                    target.AREA=src.AREA, 
                    target.AVGMONUSG=src.AVGMONUSG, 
                    target.AVGMONUSGUOM=src.AVGMONUSGUOM, 
                    target.AXLE=src.AXLE, 
                    target.BGTNO=src.BGTNO, 
                    target.BLDGFLOOR=src.BLDGFLOOR, 
                    target.BLDGROOM=src.BLDGROOM, 
                    target.BUDGETKEY=src.BUDGETKEY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COMPLEXKEY=src.COMPLEXKEY, 
                    target.CYLINDERS=src.CYLINDERS, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DISTRICT=src.DISTRICT, 
                    target.DRIVERCLAS=src.DRIVERCLAS, 
                    target.ENGINENO=src.ENGINENO, 
                    target.ENGINETYPE=src.ENGINETYPE, 
                    target.EXPBY=src.EXPBY, 
                    target.EXPDATE=src.EXPDATE, 
                    target.EXPECTLIFE=src.EXPECTLIFE, 
                    target.EXPECTLIFEUOM=src.EXPECTLIFEUOM, 
                    target.GVW=src.GVW, 
                    target.GVWUOM=src.GVWUOM, 
                    target.INSTDATE=src.INSTDATE, 
                    target.INTKEY=src.INTKEY, 
                    target.LICENSE=src.LICENSE, 
                    target.LOC=src.LOC, 
                    target.MAPNO=src.MAPNO, 
                    target.MFGDATE=src.MFGDATE, 
                    target.MFGKEY=src.MFGKEY, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MODELNO=src.MODELNO, 
                    target.MODELYR=src.MODELYR, 
                    target.MTBF=src.MTBF, 
                    target.NOTIRES=src.NOTIRES, 
                    target.OWN=src.OWN, 
                    target.POSITION=src.POSITION, 
                    target.PRCLKEY=src.PRCLKEY, 
                    target.PURCCOST=src.PURCCOST, 
                    target.PURCDATE=src.PURCDATE, 
                    target.SERNO=src.SERNO, 
                    target.SERVSTAT=src.SERVSTAT, 
                    target.SITEKEY=src.SITEKEY, 
                    target.SUBAREA=src.SUBAREA, 
                    target.TIRESIZE=src.TIRESIZE, 
                    target.TIRETYPE=src.TIRETYPE, 
                    target.TRANSMISSN=src.TRANSMISSN, 
                    target.UNITDESC=src.UNITDESC, 
                    target.UNITID=src.UNITID, 
                    target.UNITTYPE=src.UNITTYPE, 
                    target.USGAREAKEY=src.USGAREAKEY, 
                    target.USGDATE=src.USGDATE, 
                    target.USGTOT=src.USGTOT, 
                    target.USGTOTUOM=src.USGTOTUOM, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.VEHSZ=src.VEHSZ, 
                    target.VEHSZUOM=src.VEHSZUOM, 
                    target.VIN=src.VIN, 
                    target.WARREXP=src.WARREXP, 
                    target.WARRUSG=src.WARRUSG, 
                    target.XCOORD=src.XCOORD, 
                    target.YCOORD=src.YCOORD, 
                    target.ZCOORD=src.ZCOORD, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ADDBY, 
                    ADDDTTM, 
                    ADDRKEY, 
                    ADDRQUAL, 
                    AREA, 
                    AVGMONUSG, 
                    AVGMONUSGUOM, 
                    AXLE, 
                    BGTNO, 
                    BLDGFLOOR, 
                    BLDGROOM, 
                    BUDGETKEY, 
                    COMPKEY, 
                    COMPLEXKEY, 
                    CYLINDERS, 
                    DATALAKE_DELETED, 
                    DISTRICT, 
                    DRIVERCLAS, 
                    ENGINENO, 
                    ENGINETYPE, 
                    EXPBY, 
                    EXPDATE, 
                    EXPECTLIFE, 
                    EXPECTLIFEUOM, 
                    GVW, 
                    GVWUOM, 
                    INSTDATE, 
                    INTKEY, 
                    LICENSE, 
                    LOC, 
                    MAPNO, 
                    MFGDATE, 
                    MFGKEY, 
                    MODBY, 
                    MODDTTM, 
                    MODELNO, 
                    MODELYR, 
                    MTBF, 
                    NOTIRES, 
                    OWN, 
                    POSITION, 
                    PRCLKEY, 
                    PURCCOST, 
                    PURCDATE, 
                    SERNO, 
                    SERVSTAT, 
                    SITEKEY, 
                    SUBAREA, 
                    TIRESIZE, 
                    TIRETYPE, 
                    TRANSMISSN, 
                    UNITDESC, 
                    UNITID, 
                    UNITTYPE, 
                    USGAREAKEY, 
                    USGDATE, 
                    USGTOT, 
                    USGTOTUOM, 
                    VARIATION_ID, 
                    VEHSZ, 
                    VEHSZUOM, 
                    VIN, 
                    WARREXP, 
                    WARRUSG, 
                    XCOORD, 
                    YCOORD, 
                    ZCOORD, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.ADDRQUAL, 
                    src.AREA, 
                    src.AVGMONUSG, 
                    src.AVGMONUSGUOM, 
                    src.AXLE, 
                    src.BGTNO, 
                    src.BLDGFLOOR, 
                    src.BLDGROOM, 
                    src.BUDGETKEY, 
                    src.COMPKEY, 
                    src.COMPLEXKEY, 
                    src.CYLINDERS, 
                    src.DATALAKE_DELETED, 
                    src.DISTRICT, 
                    src.DRIVERCLAS, 
                    src.ENGINENO, 
                    src.ENGINETYPE, 
                    src.EXPBY, 
                    src.EXPDATE, 
                    src.EXPECTLIFE, 
                    src.EXPECTLIFEUOM, 
                    src.GVW, 
                    src.GVWUOM, 
                    src.INSTDATE, 
                    src.INTKEY, 
                    src.LICENSE, 
                    src.LOC, 
                    src.MAPNO, 
                    src.MFGDATE, 
                    src.MFGKEY, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MODELNO, 
                    src.MODELYR, 
                    src.MTBF, 
                    src.NOTIRES, 
                    src.OWN, 
                    src.POSITION, 
                    src.PRCLKEY, 
                    src.PURCCOST, 
                    src.PURCDATE, 
                    src.SERNO, 
                    src.SERVSTAT, 
                    src.SITEKEY, 
                    src.SUBAREA, 
                    src.TIRESIZE, 
                    src.TIRETYPE, 
                    src.TRANSMISSN, 
                    src.UNITDESC, 
                    src.UNITID, 
                    src.UNITTYPE, 
                    src.USGAREAKEY, 
                    src.USGDATE, 
                    src.USGTOT, 
                    src.USGTOTUOM, 
                    src.VARIATION_ID, 
                    src.VEHSZ, 
                    src.VEHSZUOM, 
                    src.VIN, 
                    src.WARREXP, 
                    src.WARRUSG, 
                    src.XCOORD, 
                    src.YCOORD, 
                    src.ZCOORD,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_FLEET_COMPVEH as target using (
                SELECT * FROM (SELECT 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.ADDRQUAL, 
            strm.AREA, 
            strm.AVGMONUSG, 
            strm.AVGMONUSGUOM, 
            strm.AXLE, 
            strm.BGTNO, 
            strm.BLDGFLOOR, 
            strm.BLDGROOM, 
            strm.BUDGETKEY, 
            strm.COMPKEY, 
            strm.COMPLEXKEY, 
            strm.CYLINDERS, 
            strm.DATALAKE_DELETED, 
            strm.DISTRICT, 
            strm.DRIVERCLAS, 
            strm.ENGINENO, 
            strm.ENGINETYPE, 
            strm.EXPBY, 
            strm.EXPDATE, 
            strm.EXPECTLIFE, 
            strm.EXPECTLIFEUOM, 
            strm.GVW, 
            strm.GVWUOM, 
            strm.INSTDATE, 
            strm.INTKEY, 
            strm.LICENSE, 
            strm.LOC, 
            strm.MAPNO, 
            strm.MFGDATE, 
            strm.MFGKEY, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MODELNO, 
            strm.MODELYR, 
            strm.MTBF, 
            strm.NOTIRES, 
            strm.OWN, 
            strm.POSITION, 
            strm.PRCLKEY, 
            strm.PURCCOST, 
            strm.PURCDATE, 
            strm.SERNO, 
            strm.SERVSTAT, 
            strm.SITEKEY, 
            strm.SUBAREA, 
            strm.TIRESIZE, 
            strm.TIRETYPE, 
            strm.TRANSMISSN, 
            strm.UNITDESC, 
            strm.UNITID, 
            strm.UNITTYPE, 
            strm.USGAREAKEY, 
            strm.USGDATE, 
            strm.USGTOT, 
            strm.USGTOTUOM, 
            strm.VARIATION_ID, 
            strm.VEHSZ, 
            strm.VEHSZUOM, 
            strm.VIN, 
            strm.WARREXP, 
            strm.WARRUSG, 
            strm.XCOORD, 
            strm.YCOORD, 
            strm.ZCOORD, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.COMPKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_ASSETMANAGEMENT_FLEET_COMPVEH as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.COMPKEY=src.COMPKEY) OR (target.COMPKEY IS NULL AND src.COMPKEY IS NULL)) 
                when matched then update set
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.ADDRQUAL=src.ADDRQUAL, 
                    target.AREA=src.AREA, 
                    target.AVGMONUSG=src.AVGMONUSG, 
                    target.AVGMONUSGUOM=src.AVGMONUSGUOM, 
                    target.AXLE=src.AXLE, 
                    target.BGTNO=src.BGTNO, 
                    target.BLDGFLOOR=src.BLDGFLOOR, 
                    target.BLDGROOM=src.BLDGROOM, 
                    target.BUDGETKEY=src.BUDGETKEY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COMPLEXKEY=src.COMPLEXKEY, 
                    target.CYLINDERS=src.CYLINDERS, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DISTRICT=src.DISTRICT, 
                    target.DRIVERCLAS=src.DRIVERCLAS, 
                    target.ENGINENO=src.ENGINENO, 
                    target.ENGINETYPE=src.ENGINETYPE, 
                    target.EXPBY=src.EXPBY, 
                    target.EXPDATE=src.EXPDATE, 
                    target.EXPECTLIFE=src.EXPECTLIFE, 
                    target.EXPECTLIFEUOM=src.EXPECTLIFEUOM, 
                    target.GVW=src.GVW, 
                    target.GVWUOM=src.GVWUOM, 
                    target.INSTDATE=src.INSTDATE, 
                    target.INTKEY=src.INTKEY, 
                    target.LICENSE=src.LICENSE, 
                    target.LOC=src.LOC, 
                    target.MAPNO=src.MAPNO, 
                    target.MFGDATE=src.MFGDATE, 
                    target.MFGKEY=src.MFGKEY, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MODELNO=src.MODELNO, 
                    target.MODELYR=src.MODELYR, 
                    target.MTBF=src.MTBF, 
                    target.NOTIRES=src.NOTIRES, 
                    target.OWN=src.OWN, 
                    target.POSITION=src.POSITION, 
                    target.PRCLKEY=src.PRCLKEY, 
                    target.PURCCOST=src.PURCCOST, 
                    target.PURCDATE=src.PURCDATE, 
                    target.SERNO=src.SERNO, 
                    target.SERVSTAT=src.SERVSTAT, 
                    target.SITEKEY=src.SITEKEY, 
                    target.SUBAREA=src.SUBAREA, 
                    target.TIRESIZE=src.TIRESIZE, 
                    target.TIRETYPE=src.TIRETYPE, 
                    target.TRANSMISSN=src.TRANSMISSN, 
                    target.UNITDESC=src.UNITDESC, 
                    target.UNITID=src.UNITID, 
                    target.UNITTYPE=src.UNITTYPE, 
                    target.USGAREAKEY=src.USGAREAKEY, 
                    target.USGDATE=src.USGDATE, 
                    target.USGTOT=src.USGTOT, 
                    target.USGTOTUOM=src.USGTOTUOM, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.VEHSZ=src.VEHSZ, 
                    target.VEHSZUOM=src.VEHSZUOM, 
                    target.VIN=src.VIN, 
                    target.WARREXP=src.WARREXP, 
                    target.WARRUSG=src.WARRUSG, 
                    target.XCOORD=src.XCOORD, 
                    target.YCOORD=src.YCOORD, 
                    target.ZCOORD=src.ZCOORD, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ADDBY, ADDDTTM, ADDRKEY, ADDRQUAL, AREA, AVGMONUSG, AVGMONUSGUOM, AXLE, BGTNO, BLDGFLOOR, BLDGROOM, BUDGETKEY, COMPKEY, COMPLEXKEY, CYLINDERS, DATALAKE_DELETED, DISTRICT, DRIVERCLAS, ENGINENO, ENGINETYPE, EXPBY, EXPDATE, EXPECTLIFE, EXPECTLIFEUOM, GVW, GVWUOM, INSTDATE, INTKEY, LICENSE, LOC, MAPNO, MFGDATE, MFGKEY, MODBY, MODDTTM, MODELNO, MODELYR, MTBF, NOTIRES, OWN, POSITION, PRCLKEY, PURCCOST, PURCDATE, SERNO, SERVSTAT, SITEKEY, SUBAREA, TIRESIZE, TIRETYPE, TRANSMISSN, UNITDESC, UNITID, UNITTYPE, USGAREAKEY, USGDATE, USGTOT, USGTOTUOM, VARIATION_ID, VEHSZ, VEHSZUOM, VIN, WARREXP, WARRUSG, XCOORD, YCOORD, ZCOORD, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.ADDRQUAL, 
                    src.AREA, 
                    src.AVGMONUSG, 
                    src.AVGMONUSGUOM, 
                    src.AXLE, 
                    src.BGTNO, 
                    src.BLDGFLOOR, 
                    src.BLDGROOM, 
                    src.BUDGETKEY, 
                    src.COMPKEY, 
                    src.COMPLEXKEY, 
                    src.CYLINDERS, 
                    src.DATALAKE_DELETED, 
                    src.DISTRICT, 
                    src.DRIVERCLAS, 
                    src.ENGINENO, 
                    src.ENGINETYPE, 
                    src.EXPBY, 
                    src.EXPDATE, 
                    src.EXPECTLIFE, 
                    src.EXPECTLIFEUOM, 
                    src.GVW, 
                    src.GVWUOM, 
                    src.INSTDATE, 
                    src.INTKEY, 
                    src.LICENSE, 
                    src.LOC, 
                    src.MAPNO, 
                    src.MFGDATE, 
                    src.MFGKEY, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MODELNO, 
                    src.MODELYR, 
                    src.MTBF, 
                    src.NOTIRES, 
                    src.OWN, 
                    src.POSITION, 
                    src.PRCLKEY, 
                    src.PURCCOST, 
                    src.PURCDATE, 
                    src.SERNO, 
                    src.SERVSTAT, 
                    src.SITEKEY, 
                    src.SUBAREA, 
                    src.TIRESIZE, 
                    src.TIRETYPE, 
                    src.TRANSMISSN, 
                    src.UNITDESC, 
                    src.UNITID, 
                    src.UNITTYPE, 
                    src.USGAREAKEY, 
                    src.USGDATE, 
                    src.USGTOT, 
                    src.USGTOTUOM, 
                    src.VARIATION_ID, 
                    src.VEHSZ, 
                    src.VEHSZUOM, 
                    src.VIN, 
                    src.WARREXP, 
                    src.WARRUSG, 
                    src.XCOORD, 
                    src.YCOORD, 
                    src.ZCOORD,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;