create or replace procedure DATAHUB_INTEGRATION.SP_IPS_BILLING_MOVEINSETUP()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_BILLING_MOVEINSETUP_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_BILLING_MOVEINSETUP as target using (SELECT * FROM (SELECT 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRSECTORDER, 
            strm.BILLINGSTATUS, 
            strm.CANCELCONFIRMATIONMSGKEY, 
            strm.CANCELLOGTYPE, 
            strm.CANCELREQUESTRESOLUTION, 
            strm.CDRBUILDINGAPPLTYPE, 
            strm.CONFIRMCNTCTINFOSECTORDER, 
            strm.CONTACTSECTORDER, 
            strm.DELETED, 
            strm.EXISTCUSTDEFAULTFLAG, 
            strm.EXISTCUSTPROMPT, 
            strm.FINALIZEACTIVEACCTFLAG, 
            strm.MAXDAYSPASTTOALLOWCANCEL, 
            strm.MAXDAYSPASTTOALLOWMODIFY, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MODIFYCONFIRMATIONMSGKEY, 
            strm.MODIFYLOGTYPE, 
            strm.MODIFYMAXINTFORNEWREQUEST, 
            strm.MOVEINDATEPROMPT, 
            strm.MOVEINDATESECTORDER, 
            strm.MOVEINSETUPKEY, 
            strm.OCCUPANTPROMPT, 
            strm.OPTSERVSECTORDER, 
            strm.PROVSERVSECTORDER, 
            strm.READINGREQUESTRESOLUTION, 
            strm.SEARCHCALLERPROMPT, 
            strm.SEARCHEMAILFLAG, 
            strm.SEARCHEMAILORDER, 
            strm.SEARCHEMAILTITLE, 
            strm.SEARCHFIRSTNAMEFLAG, 
            strm.SEARCHFIRSTNAMEORDER, 
            strm.SEARCHFIRSTNAMETITLE, 
            strm.SEARCHIDFLAG, 
            strm.SEARCHIDORDER, 
            strm.SEARCHIDTITLE, 
            strm.SEARCHLASTNAMEFLAG, 
            strm.SEARCHLASTNAMEORDER, 
            strm.SEARCHLASTNAMETITLE, 
            strm.SEARCHLICENSEFLAG, 
            strm.SEARCHLICENSEORDER, 
            strm.SEARCHLICENSETITLE, 
            strm.SEARCHPHONEFLAG, 
            strm.SEARCHPHONEORDER, 
            strm.SEARCHPHONETITLE, 
            strm.SECONDOWNERMSGKEY, 
            strm.SECONDTENANTMSGKEY, 
            strm.SERVICESSECTORDER, 
            strm.SERVICESTATUS, 
            strm.SHOWADDRALERTSFLAG, 
            strm.SHOWADDRSECTFLAG, 
            strm.SHOWCONFIRMCNTCTINFOFLAG, 
            strm.SHOWCUSTALERTSFLAG, 
            strm.SHOWEXISTCNTCTCOMMFLAG, 
            strm.SHOWEXISTCNTCTSEASADDRFLAG, 
            strm.SHOWEXISTCUSTCOMMFLAG, 
            strm.SHOWEXISTCUSTFIELDSFLAG, 
            strm.SHOWEXISTCUSTPROMPTFLAG, 
            strm.SHOWLOCBYSERVADDRLINKFLAG, 
            strm.SHOWNEWCNTCTCOMMFLAG, 
            strm.SHOWNEWCNTCTSEASADDRFLAG, 
            strm.SHOWNEWCUSTCOMMFLAG, 
            strm.TENANTNOOWNERMSGKEY, 
            strm.VARIATION_ID, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.MOVEINSETUPKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_BILLING_MOVEINSETUP as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.MOVEINSETUPKEY=src.MOVEINSETUPKEY) OR (target.MOVEINSETUPKEY IS NULL AND src.MOVEINSETUPKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRSECTORDER=src.ADDRSECTORDER, 
                    target.BILLINGSTATUS=src.BILLINGSTATUS, 
                    target.CANCELCONFIRMATIONMSGKEY=src.CANCELCONFIRMATIONMSGKEY, 
                    target.CANCELLOGTYPE=src.CANCELLOGTYPE, 
                    target.CANCELREQUESTRESOLUTION=src.CANCELREQUESTRESOLUTION, 
                    target.CDRBUILDINGAPPLTYPE=src.CDRBUILDINGAPPLTYPE, 
                    target.CONFIRMCNTCTINFOSECTORDER=src.CONFIRMCNTCTINFOSECTORDER, 
                    target.CONTACTSECTORDER=src.CONTACTSECTORDER, 
                    target.DELETED=src.DELETED, 
                    target.EXISTCUSTDEFAULTFLAG=src.EXISTCUSTDEFAULTFLAG, 
                    target.EXISTCUSTPROMPT=src.EXISTCUSTPROMPT, 
                    target.FINALIZEACTIVEACCTFLAG=src.FINALIZEACTIVEACCTFLAG, 
                    target.MAXDAYSPASTTOALLOWCANCEL=src.MAXDAYSPASTTOALLOWCANCEL, 
                    target.MAXDAYSPASTTOALLOWMODIFY=src.MAXDAYSPASTTOALLOWMODIFY, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MODIFYCONFIRMATIONMSGKEY=src.MODIFYCONFIRMATIONMSGKEY, 
                    target.MODIFYLOGTYPE=src.MODIFYLOGTYPE, 
                    target.MODIFYMAXINTFORNEWREQUEST=src.MODIFYMAXINTFORNEWREQUEST, 
                    target.MOVEINDATEPROMPT=src.MOVEINDATEPROMPT, 
                    target.MOVEINDATESECTORDER=src.MOVEINDATESECTORDER, 
                    target.MOVEINSETUPKEY=src.MOVEINSETUPKEY, 
                    target.OCCUPANTPROMPT=src.OCCUPANTPROMPT, 
                    target.OPTSERVSECTORDER=src.OPTSERVSECTORDER, 
                    target.PROVSERVSECTORDER=src.PROVSERVSECTORDER, 
                    target.READINGREQUESTRESOLUTION=src.READINGREQUESTRESOLUTION, 
                    target.SEARCHCALLERPROMPT=src.SEARCHCALLERPROMPT, 
                    target.SEARCHEMAILFLAG=src.SEARCHEMAILFLAG, 
                    target.SEARCHEMAILORDER=src.SEARCHEMAILORDER, 
                    target.SEARCHEMAILTITLE=src.SEARCHEMAILTITLE, 
                    target.SEARCHFIRSTNAMEFLAG=src.SEARCHFIRSTNAMEFLAG, 
                    target.SEARCHFIRSTNAMEORDER=src.SEARCHFIRSTNAMEORDER, 
                    target.SEARCHFIRSTNAMETITLE=src.SEARCHFIRSTNAMETITLE, 
                    target.SEARCHIDFLAG=src.SEARCHIDFLAG, 
                    target.SEARCHIDORDER=src.SEARCHIDORDER, 
                    target.SEARCHIDTITLE=src.SEARCHIDTITLE, 
                    target.SEARCHLASTNAMEFLAG=src.SEARCHLASTNAMEFLAG, 
                    target.SEARCHLASTNAMEORDER=src.SEARCHLASTNAMEORDER, 
                    target.SEARCHLASTNAMETITLE=src.SEARCHLASTNAMETITLE, 
                    target.SEARCHLICENSEFLAG=src.SEARCHLICENSEFLAG, 
                    target.SEARCHLICENSEORDER=src.SEARCHLICENSEORDER, 
                    target.SEARCHLICENSETITLE=src.SEARCHLICENSETITLE, 
                    target.SEARCHPHONEFLAG=src.SEARCHPHONEFLAG, 
                    target.SEARCHPHONEORDER=src.SEARCHPHONEORDER, 
                    target.SEARCHPHONETITLE=src.SEARCHPHONETITLE, 
                    target.SECONDOWNERMSGKEY=src.SECONDOWNERMSGKEY, 
                    target.SECONDTENANTMSGKEY=src.SECONDTENANTMSGKEY, 
                    target.SERVICESSECTORDER=src.SERVICESSECTORDER, 
                    target.SERVICESTATUS=src.SERVICESTATUS, 
                    target.SHOWADDRALERTSFLAG=src.SHOWADDRALERTSFLAG, 
                    target.SHOWADDRSECTFLAG=src.SHOWADDRSECTFLAG, 
                    target.SHOWCONFIRMCNTCTINFOFLAG=src.SHOWCONFIRMCNTCTINFOFLAG, 
                    target.SHOWCUSTALERTSFLAG=src.SHOWCUSTALERTSFLAG, 
                    target.SHOWEXISTCNTCTCOMMFLAG=src.SHOWEXISTCNTCTCOMMFLAG, 
                    target.SHOWEXISTCNTCTSEASADDRFLAG=src.SHOWEXISTCNTCTSEASADDRFLAG, 
                    target.SHOWEXISTCUSTCOMMFLAG=src.SHOWEXISTCUSTCOMMFLAG, 
                    target.SHOWEXISTCUSTFIELDSFLAG=src.SHOWEXISTCUSTFIELDSFLAG, 
                    target.SHOWEXISTCUSTPROMPTFLAG=src.SHOWEXISTCUSTPROMPTFLAG, 
                    target.SHOWLOCBYSERVADDRLINKFLAG=src.SHOWLOCBYSERVADDRLINKFLAG, 
                    target.SHOWNEWCNTCTCOMMFLAG=src.SHOWNEWCNTCTCOMMFLAG, 
                    target.SHOWNEWCNTCTSEASADDRFLAG=src.SHOWNEWCNTCTSEASADDRFLAG, 
                    target.SHOWNEWCUSTCOMMFLAG=src.SHOWNEWCUSTCOMMFLAG, 
                    target.TENANTNOOWNERMSGKEY=src.TENANTNOOWNERMSGKEY, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ADDBY, 
                    ADDDTTM, 
                    ADDRSECTORDER, 
                    BILLINGSTATUS, 
                    CANCELCONFIRMATIONMSGKEY, 
                    CANCELLOGTYPE, 
                    CANCELREQUESTRESOLUTION, 
                    CDRBUILDINGAPPLTYPE, 
                    CONFIRMCNTCTINFOSECTORDER, 
                    CONTACTSECTORDER, 
                    DELETED, 
                    EXISTCUSTDEFAULTFLAG, 
                    EXISTCUSTPROMPT, 
                    FINALIZEACTIVEACCTFLAG, 
                    MAXDAYSPASTTOALLOWCANCEL, 
                    MAXDAYSPASTTOALLOWMODIFY, 
                    MODBY, 
                    MODDTTM, 
                    MODIFYCONFIRMATIONMSGKEY, 
                    MODIFYLOGTYPE, 
                    MODIFYMAXINTFORNEWREQUEST, 
                    MOVEINDATEPROMPT, 
                    MOVEINDATESECTORDER, 
                    MOVEINSETUPKEY, 
                    OCCUPANTPROMPT, 
                    OPTSERVSECTORDER, 
                    PROVSERVSECTORDER, 
                    READINGREQUESTRESOLUTION, 
                    SEARCHCALLERPROMPT, 
                    SEARCHEMAILFLAG, 
                    SEARCHEMAILORDER, 
                    SEARCHEMAILTITLE, 
                    SEARCHFIRSTNAMEFLAG, 
                    SEARCHFIRSTNAMEORDER, 
                    SEARCHFIRSTNAMETITLE, 
                    SEARCHIDFLAG, 
                    SEARCHIDORDER, 
                    SEARCHIDTITLE, 
                    SEARCHLASTNAMEFLAG, 
                    SEARCHLASTNAMEORDER, 
                    SEARCHLASTNAMETITLE, 
                    SEARCHLICENSEFLAG, 
                    SEARCHLICENSEORDER, 
                    SEARCHLICENSETITLE, 
                    SEARCHPHONEFLAG, 
                    SEARCHPHONEORDER, 
                    SEARCHPHONETITLE, 
                    SECONDOWNERMSGKEY, 
                    SECONDTENANTMSGKEY, 
                    SERVICESSECTORDER, 
                    SERVICESTATUS, 
                    SHOWADDRALERTSFLAG, 
                    SHOWADDRSECTFLAG, 
                    SHOWCONFIRMCNTCTINFOFLAG, 
                    SHOWCUSTALERTSFLAG, 
                    SHOWEXISTCNTCTCOMMFLAG, 
                    SHOWEXISTCNTCTSEASADDRFLAG, 
                    SHOWEXISTCUSTCOMMFLAG, 
                    SHOWEXISTCUSTFIELDSFLAG, 
                    SHOWEXISTCUSTPROMPTFLAG, 
                    SHOWLOCBYSERVADDRLINKFLAG, 
                    SHOWNEWCNTCTCOMMFLAG, 
                    SHOWNEWCNTCTSEASADDRFLAG, 
                    SHOWNEWCUSTCOMMFLAG, 
                    TENANTNOOWNERMSGKEY, 
                    VARIATION_ID, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRSECTORDER, 
                    src.BILLINGSTATUS, 
                    src.CANCELCONFIRMATIONMSGKEY, 
                    src.CANCELLOGTYPE, 
                    src.CANCELREQUESTRESOLUTION, 
                    src.CDRBUILDINGAPPLTYPE, 
                    src.CONFIRMCNTCTINFOSECTORDER, 
                    src.CONTACTSECTORDER, 
                    src.DELETED, 
                    src.EXISTCUSTDEFAULTFLAG, 
                    src.EXISTCUSTPROMPT, 
                    src.FINALIZEACTIVEACCTFLAG, 
                    src.MAXDAYSPASTTOALLOWCANCEL, 
                    src.MAXDAYSPASTTOALLOWMODIFY, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MODIFYCONFIRMATIONMSGKEY, 
                    src.MODIFYLOGTYPE, 
                    src.MODIFYMAXINTFORNEWREQUEST, 
                    src.MOVEINDATEPROMPT, 
                    src.MOVEINDATESECTORDER, 
                    src.MOVEINSETUPKEY, 
                    src.OCCUPANTPROMPT, 
                    src.OPTSERVSECTORDER, 
                    src.PROVSERVSECTORDER, 
                    src.READINGREQUESTRESOLUTION, 
                    src.SEARCHCALLERPROMPT, 
                    src.SEARCHEMAILFLAG, 
                    src.SEARCHEMAILORDER, 
                    src.SEARCHEMAILTITLE, 
                    src.SEARCHFIRSTNAMEFLAG, 
                    src.SEARCHFIRSTNAMEORDER, 
                    src.SEARCHFIRSTNAMETITLE, 
                    src.SEARCHIDFLAG, 
                    src.SEARCHIDORDER, 
                    src.SEARCHIDTITLE, 
                    src.SEARCHLASTNAMEFLAG, 
                    src.SEARCHLASTNAMEORDER, 
                    src.SEARCHLASTNAMETITLE, 
                    src.SEARCHLICENSEFLAG, 
                    src.SEARCHLICENSEORDER, 
                    src.SEARCHLICENSETITLE, 
                    src.SEARCHPHONEFLAG, 
                    src.SEARCHPHONEORDER, 
                    src.SEARCHPHONETITLE, 
                    src.SECONDOWNERMSGKEY, 
                    src.SECONDTENANTMSGKEY, 
                    src.SERVICESSECTORDER, 
                    src.SERVICESTATUS, 
                    src.SHOWADDRALERTSFLAG, 
                    src.SHOWADDRSECTFLAG, 
                    src.SHOWCONFIRMCNTCTINFOFLAG, 
                    src.SHOWCUSTALERTSFLAG, 
                    src.SHOWEXISTCNTCTCOMMFLAG, 
                    src.SHOWEXISTCNTCTSEASADDRFLAG, 
                    src.SHOWEXISTCUSTCOMMFLAG, 
                    src.SHOWEXISTCUSTFIELDSFLAG, 
                    src.SHOWEXISTCUSTPROMPTFLAG, 
                    src.SHOWLOCBYSERVADDRLINKFLAG, 
                    src.SHOWNEWCNTCTCOMMFLAG, 
                    src.SHOWNEWCNTCTSEASADDRFLAG, 
                    src.SHOWNEWCUSTCOMMFLAG, 
                    src.TENANTNOOWNERMSGKEY, 
                    src.VARIATION_ID,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_MOVEINSETUP as target using (
                SELECT * FROM (SELECT 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRSECTORDER, 
            strm.BILLINGSTATUS, 
            strm.CANCELCONFIRMATIONMSGKEY, 
            strm.CANCELLOGTYPE, 
            strm.CANCELREQUESTRESOLUTION, 
            strm.CDRBUILDINGAPPLTYPE, 
            strm.CONFIRMCNTCTINFOSECTORDER, 
            strm.CONTACTSECTORDER, 
            strm.DELETED, 
            strm.EXISTCUSTDEFAULTFLAG, 
            strm.EXISTCUSTPROMPT, 
            strm.FINALIZEACTIVEACCTFLAG, 
            strm.MAXDAYSPASTTOALLOWCANCEL, 
            strm.MAXDAYSPASTTOALLOWMODIFY, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MODIFYCONFIRMATIONMSGKEY, 
            strm.MODIFYLOGTYPE, 
            strm.MODIFYMAXINTFORNEWREQUEST, 
            strm.MOVEINDATEPROMPT, 
            strm.MOVEINDATESECTORDER, 
            strm.MOVEINSETUPKEY, 
            strm.OCCUPANTPROMPT, 
            strm.OPTSERVSECTORDER, 
            strm.PROVSERVSECTORDER, 
            strm.READINGREQUESTRESOLUTION, 
            strm.SEARCHCALLERPROMPT, 
            strm.SEARCHEMAILFLAG, 
            strm.SEARCHEMAILORDER, 
            strm.SEARCHEMAILTITLE, 
            strm.SEARCHFIRSTNAMEFLAG, 
            strm.SEARCHFIRSTNAMEORDER, 
            strm.SEARCHFIRSTNAMETITLE, 
            strm.SEARCHIDFLAG, 
            strm.SEARCHIDORDER, 
            strm.SEARCHIDTITLE, 
            strm.SEARCHLASTNAMEFLAG, 
            strm.SEARCHLASTNAMEORDER, 
            strm.SEARCHLASTNAMETITLE, 
            strm.SEARCHLICENSEFLAG, 
            strm.SEARCHLICENSEORDER, 
            strm.SEARCHLICENSETITLE, 
            strm.SEARCHPHONEFLAG, 
            strm.SEARCHPHONEORDER, 
            strm.SEARCHPHONETITLE, 
            strm.SECONDOWNERMSGKEY, 
            strm.SECONDTENANTMSGKEY, 
            strm.SERVICESSECTORDER, 
            strm.SERVICESTATUS, 
            strm.SHOWADDRALERTSFLAG, 
            strm.SHOWADDRSECTFLAG, 
            strm.SHOWCONFIRMCNTCTINFOFLAG, 
            strm.SHOWCUSTALERTSFLAG, 
            strm.SHOWEXISTCNTCTCOMMFLAG, 
            strm.SHOWEXISTCNTCTSEASADDRFLAG, 
            strm.SHOWEXISTCUSTCOMMFLAG, 
            strm.SHOWEXISTCUSTFIELDSFLAG, 
            strm.SHOWEXISTCUSTPROMPTFLAG, 
            strm.SHOWLOCBYSERVADDRLINKFLAG, 
            strm.SHOWNEWCNTCTCOMMFLAG, 
            strm.SHOWNEWCNTCTSEASADDRFLAG, 
            strm.SHOWNEWCUSTCOMMFLAG, 
            strm.TENANTNOOWNERMSGKEY, 
            strm.VARIATION_ID, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.MOVEINSETUPKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_BILLING_MOVEINSETUP as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.MOVEINSETUPKEY=src.MOVEINSETUPKEY) OR (target.MOVEINSETUPKEY IS NULL AND src.MOVEINSETUPKEY IS NULL)) 
                when matched then update set
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRSECTORDER=src.ADDRSECTORDER, 
                    target.BILLINGSTATUS=src.BILLINGSTATUS, 
                    target.CANCELCONFIRMATIONMSGKEY=src.CANCELCONFIRMATIONMSGKEY, 
                    target.CANCELLOGTYPE=src.CANCELLOGTYPE, 
                    target.CANCELREQUESTRESOLUTION=src.CANCELREQUESTRESOLUTION, 
                    target.CDRBUILDINGAPPLTYPE=src.CDRBUILDINGAPPLTYPE, 
                    target.CONFIRMCNTCTINFOSECTORDER=src.CONFIRMCNTCTINFOSECTORDER, 
                    target.CONTACTSECTORDER=src.CONTACTSECTORDER, 
                    target.DELETED=src.DELETED, 
                    target.EXISTCUSTDEFAULTFLAG=src.EXISTCUSTDEFAULTFLAG, 
                    target.EXISTCUSTPROMPT=src.EXISTCUSTPROMPT, 
                    target.FINALIZEACTIVEACCTFLAG=src.FINALIZEACTIVEACCTFLAG, 
                    target.MAXDAYSPASTTOALLOWCANCEL=src.MAXDAYSPASTTOALLOWCANCEL, 
                    target.MAXDAYSPASTTOALLOWMODIFY=src.MAXDAYSPASTTOALLOWMODIFY, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MODIFYCONFIRMATIONMSGKEY=src.MODIFYCONFIRMATIONMSGKEY, 
                    target.MODIFYLOGTYPE=src.MODIFYLOGTYPE, 
                    target.MODIFYMAXINTFORNEWREQUEST=src.MODIFYMAXINTFORNEWREQUEST, 
                    target.MOVEINDATEPROMPT=src.MOVEINDATEPROMPT, 
                    target.MOVEINDATESECTORDER=src.MOVEINDATESECTORDER, 
                    target.MOVEINSETUPKEY=src.MOVEINSETUPKEY, 
                    target.OCCUPANTPROMPT=src.OCCUPANTPROMPT, 
                    target.OPTSERVSECTORDER=src.OPTSERVSECTORDER, 
                    target.PROVSERVSECTORDER=src.PROVSERVSECTORDER, 
                    target.READINGREQUESTRESOLUTION=src.READINGREQUESTRESOLUTION, 
                    target.SEARCHCALLERPROMPT=src.SEARCHCALLERPROMPT, 
                    target.SEARCHEMAILFLAG=src.SEARCHEMAILFLAG, 
                    target.SEARCHEMAILORDER=src.SEARCHEMAILORDER, 
                    target.SEARCHEMAILTITLE=src.SEARCHEMAILTITLE, 
                    target.SEARCHFIRSTNAMEFLAG=src.SEARCHFIRSTNAMEFLAG, 
                    target.SEARCHFIRSTNAMEORDER=src.SEARCHFIRSTNAMEORDER, 
                    target.SEARCHFIRSTNAMETITLE=src.SEARCHFIRSTNAMETITLE, 
                    target.SEARCHIDFLAG=src.SEARCHIDFLAG, 
                    target.SEARCHIDORDER=src.SEARCHIDORDER, 
                    target.SEARCHIDTITLE=src.SEARCHIDTITLE, 
                    target.SEARCHLASTNAMEFLAG=src.SEARCHLASTNAMEFLAG, 
                    target.SEARCHLASTNAMEORDER=src.SEARCHLASTNAMEORDER, 
                    target.SEARCHLASTNAMETITLE=src.SEARCHLASTNAMETITLE, 
                    target.SEARCHLICENSEFLAG=src.SEARCHLICENSEFLAG, 
                    target.SEARCHLICENSEORDER=src.SEARCHLICENSEORDER, 
                    target.SEARCHLICENSETITLE=src.SEARCHLICENSETITLE, 
                    target.SEARCHPHONEFLAG=src.SEARCHPHONEFLAG, 
                    target.SEARCHPHONEORDER=src.SEARCHPHONEORDER, 
                    target.SEARCHPHONETITLE=src.SEARCHPHONETITLE, 
                    target.SECONDOWNERMSGKEY=src.SECONDOWNERMSGKEY, 
                    target.SECONDTENANTMSGKEY=src.SECONDTENANTMSGKEY, 
                    target.SERVICESSECTORDER=src.SERVICESSECTORDER, 
                    target.SERVICESTATUS=src.SERVICESTATUS, 
                    target.SHOWADDRALERTSFLAG=src.SHOWADDRALERTSFLAG, 
                    target.SHOWADDRSECTFLAG=src.SHOWADDRSECTFLAG, 
                    target.SHOWCONFIRMCNTCTINFOFLAG=src.SHOWCONFIRMCNTCTINFOFLAG, 
                    target.SHOWCUSTALERTSFLAG=src.SHOWCUSTALERTSFLAG, 
                    target.SHOWEXISTCNTCTCOMMFLAG=src.SHOWEXISTCNTCTCOMMFLAG, 
                    target.SHOWEXISTCNTCTSEASADDRFLAG=src.SHOWEXISTCNTCTSEASADDRFLAG, 
                    target.SHOWEXISTCUSTCOMMFLAG=src.SHOWEXISTCUSTCOMMFLAG, 
                    target.SHOWEXISTCUSTFIELDSFLAG=src.SHOWEXISTCUSTFIELDSFLAG, 
                    target.SHOWEXISTCUSTPROMPTFLAG=src.SHOWEXISTCUSTPROMPTFLAG, 
                    target.SHOWLOCBYSERVADDRLINKFLAG=src.SHOWLOCBYSERVADDRLINKFLAG, 
                    target.SHOWNEWCNTCTCOMMFLAG=src.SHOWNEWCNTCTCOMMFLAG, 
                    target.SHOWNEWCNTCTSEASADDRFLAG=src.SHOWNEWCNTCTSEASADDRFLAG, 
                    target.SHOWNEWCUSTCOMMFLAG=src.SHOWNEWCUSTCOMMFLAG, 
                    target.TENANTNOOWNERMSGKEY=src.TENANTNOOWNERMSGKEY, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ADDBY, ADDDTTM, ADDRSECTORDER, BILLINGSTATUS, CANCELCONFIRMATIONMSGKEY, CANCELLOGTYPE, CANCELREQUESTRESOLUTION, CDRBUILDINGAPPLTYPE, CONFIRMCNTCTINFOSECTORDER, CONTACTSECTORDER, DELETED, EXISTCUSTDEFAULTFLAG, EXISTCUSTPROMPT, FINALIZEACTIVEACCTFLAG, MAXDAYSPASTTOALLOWCANCEL, MAXDAYSPASTTOALLOWMODIFY, MODBY, MODDTTM, MODIFYCONFIRMATIONMSGKEY, MODIFYLOGTYPE, MODIFYMAXINTFORNEWREQUEST, MOVEINDATEPROMPT, MOVEINDATESECTORDER, MOVEINSETUPKEY, OCCUPANTPROMPT, OPTSERVSECTORDER, PROVSERVSECTORDER, READINGREQUESTRESOLUTION, SEARCHCALLERPROMPT, SEARCHEMAILFLAG, SEARCHEMAILORDER, SEARCHEMAILTITLE, SEARCHFIRSTNAMEFLAG, SEARCHFIRSTNAMEORDER, SEARCHFIRSTNAMETITLE, SEARCHIDFLAG, SEARCHIDORDER, SEARCHIDTITLE, SEARCHLASTNAMEFLAG, SEARCHLASTNAMEORDER, SEARCHLASTNAMETITLE, SEARCHLICENSEFLAG, SEARCHLICENSEORDER, SEARCHLICENSETITLE, SEARCHPHONEFLAG, SEARCHPHONEORDER, SEARCHPHONETITLE, SECONDOWNERMSGKEY, SECONDTENANTMSGKEY, SERVICESSECTORDER, SERVICESTATUS, SHOWADDRALERTSFLAG, SHOWADDRSECTFLAG, SHOWCONFIRMCNTCTINFOFLAG, SHOWCUSTALERTSFLAG, SHOWEXISTCNTCTCOMMFLAG, SHOWEXISTCNTCTSEASADDRFLAG, SHOWEXISTCUSTCOMMFLAG, SHOWEXISTCUSTFIELDSFLAG, SHOWEXISTCUSTPROMPTFLAG, SHOWLOCBYSERVADDRLINKFLAG, SHOWNEWCNTCTCOMMFLAG, SHOWNEWCNTCTSEASADDRFLAG, SHOWNEWCUSTCOMMFLAG, TENANTNOOWNERMSGKEY, VARIATION_ID, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRSECTORDER, 
                    src.BILLINGSTATUS, 
                    src.CANCELCONFIRMATIONMSGKEY, 
                    src.CANCELLOGTYPE, 
                    src.CANCELREQUESTRESOLUTION, 
                    src.CDRBUILDINGAPPLTYPE, 
                    src.CONFIRMCNTCTINFOSECTORDER, 
                    src.CONTACTSECTORDER, 
                    src.DELETED, 
                    src.EXISTCUSTDEFAULTFLAG, 
                    src.EXISTCUSTPROMPT, 
                    src.FINALIZEACTIVEACCTFLAG, 
                    src.MAXDAYSPASTTOALLOWCANCEL, 
                    src.MAXDAYSPASTTOALLOWMODIFY, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MODIFYCONFIRMATIONMSGKEY, 
                    src.MODIFYLOGTYPE, 
                    src.MODIFYMAXINTFORNEWREQUEST, 
                    src.MOVEINDATEPROMPT, 
                    src.MOVEINDATESECTORDER, 
                    src.MOVEINSETUPKEY, 
                    src.OCCUPANTPROMPT, 
                    src.OPTSERVSECTORDER, 
                    src.PROVSERVSECTORDER, 
                    src.READINGREQUESTRESOLUTION, 
                    src.SEARCHCALLERPROMPT, 
                    src.SEARCHEMAILFLAG, 
                    src.SEARCHEMAILORDER, 
                    src.SEARCHEMAILTITLE, 
                    src.SEARCHFIRSTNAMEFLAG, 
                    src.SEARCHFIRSTNAMEORDER, 
                    src.SEARCHFIRSTNAMETITLE, 
                    src.SEARCHIDFLAG, 
                    src.SEARCHIDORDER, 
                    src.SEARCHIDTITLE, 
                    src.SEARCHLASTNAMEFLAG, 
                    src.SEARCHLASTNAMEORDER, 
                    src.SEARCHLASTNAMETITLE, 
                    src.SEARCHLICENSEFLAG, 
                    src.SEARCHLICENSEORDER, 
                    src.SEARCHLICENSETITLE, 
                    src.SEARCHPHONEFLAG, 
                    src.SEARCHPHONEORDER, 
                    src.SEARCHPHONETITLE, 
                    src.SECONDOWNERMSGKEY, 
                    src.SECONDTENANTMSGKEY, 
                    src.SERVICESSECTORDER, 
                    src.SERVICESTATUS, 
                    src.SHOWADDRALERTSFLAG, 
                    src.SHOWADDRSECTFLAG, 
                    src.SHOWCONFIRMCNTCTINFOFLAG, 
                    src.SHOWCUSTALERTSFLAG, 
                    src.SHOWEXISTCNTCTCOMMFLAG, 
                    src.SHOWEXISTCNTCTSEASADDRFLAG, 
                    src.SHOWEXISTCUSTCOMMFLAG, 
                    src.SHOWEXISTCUSTFIELDSFLAG, 
                    src.SHOWEXISTCUSTPROMPTFLAG, 
                    src.SHOWLOCBYSERVADDRLINKFLAG, 
                    src.SHOWNEWCNTCTCOMMFLAG, 
                    src.SHOWNEWCNTCTSEASADDRFLAG, 
                    src.SHOWNEWCUSTCOMMFLAG, 
                    src.TENANTNOOWNERMSGKEY, 
                    src.VARIATION_ID,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;