create or replace procedure DATAHUB_INTEGRATION.SP_IPS_WSLASSETSCONFIGURED_XCONTAINMENT()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_WSLASSETSCONFIGURED_XCONTAINMENT_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_WSLASSETSCONFIGURED_XCONTAINMENT as target using (SELECT * FROM (SELECT 
            strm.ACCELDEPREC, 
            strm.ACCELDEPRECDESC, 
            strm.ACQTYPE, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.BOLTDOWN, 
            strm.BUSINESSAREA, 
            strm.CAPACITY, 
            strm.COMPKEY, 
            strm.CONFINEDSPACE, 
            strm.CONSTMETHOD, 
            strm.COSTCENTRE, 
            strm.COVERTYPE, 
            strm.CRITICALITY, 
            strm.DATALAKE_DELETED, 
            strm.DESIGNRESILIENCE, 
            strm.DIAMEXT, 
            strm.DIAMINT, 
            strm.DISCHARGECAP, 
            strm.DISPOSALDESC, 
            strm.DRAWINGNO, 
            strm.DRAWINGNOREF, 
            strm.EXTCOAT, 
            strm.FALLPROTECT, 
            strm.FORDISPOSAL, 
            strm.FUNCAREA, 
            strm.GRDLEVEL, 
            strm.HINGED, 
            strm.INHIBITLEVEL, 
            strm.INTLINING, 
            strm.INVLEVEL, 
            strm.JTTYPE, 
            strm.LIDLEVEL, 
            strm.LINKEDASSET, 
            strm.LOCALITY, 
            strm.LOCKABLE, 
            strm.MAKE, 
            strm.MAXFLOW, 
            strm.MEDIATYPE, 
            strm.MINFLOW, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MODELNO, 
            strm.OVERFLOWLEVEL, 
            strm.OVERFLOWTYPE, 
            strm.PHOTO3D, 
            strm.PRESSURERATING, 
            strm.PROJECTNO, 
            strm.PROJECTWISE, 
            strm.QUAKEDESIGN, 
            strm.RELDATE, 
            strm.RELDEPTH, 
            strm.RELDIA, 
            strm.RELGEOSP, 
            strm.RELMATL, 
            strm.RELOWN, 
            strm.RELSTATUS, 
            strm.REMOVABLE, 
            strm.SAFETYCRITICAL, 
            strm.STIFFRATING, 
            strm.SUBTYPEFEATURES, 
            strm.VARIATION_ID, 
            strm.WARRANTYEND, 
            strm.WARRANTYSTART, 
            strm.XCONTAINMENTKEY, 
            strm.ZONECATCHMENT, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.XCONTAINMENTKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_WSLASSETSCONFIGURED_XCONTAINMENT as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.XCONTAINMENTKEY=src.XCONTAINMENTKEY) OR (target.XCONTAINMENTKEY IS NULL AND src.XCONTAINMENTKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ACCELDEPREC=src.ACCELDEPREC, 
                    target.ACCELDEPRECDESC=src.ACCELDEPRECDESC, 
                    target.ACQTYPE=src.ACQTYPE, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.BOLTDOWN=src.BOLTDOWN, 
                    target.BUSINESSAREA=src.BUSINESSAREA, 
                    target.CAPACITY=src.CAPACITY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.CONFINEDSPACE=src.CONFINEDSPACE, 
                    target.CONSTMETHOD=src.CONSTMETHOD, 
                    target.COSTCENTRE=src.COSTCENTRE, 
                    target.COVERTYPE=src.COVERTYPE, 
                    target.CRITICALITY=src.CRITICALITY, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DESIGNRESILIENCE=src.DESIGNRESILIENCE, 
                    target.DIAMEXT=src.DIAMEXT, 
                    target.DIAMINT=src.DIAMINT, 
                    target.DISCHARGECAP=src.DISCHARGECAP, 
                    target.DISPOSALDESC=src.DISPOSALDESC, 
                    target.DRAWINGNO=src.DRAWINGNO, 
                    target.DRAWINGNOREF=src.DRAWINGNOREF, 
                    target.EXTCOAT=src.EXTCOAT, 
                    target.FALLPROTECT=src.FALLPROTECT, 
                    target.FORDISPOSAL=src.FORDISPOSAL, 
                    target.FUNCAREA=src.FUNCAREA, 
                    target.GRDLEVEL=src.GRDLEVEL, 
                    target.HINGED=src.HINGED, 
                    target.INHIBITLEVEL=src.INHIBITLEVEL, 
                    target.INTLINING=src.INTLINING, 
                    target.INVLEVEL=src.INVLEVEL, 
                    target.JTTYPE=src.JTTYPE, 
                    target.LIDLEVEL=src.LIDLEVEL, 
                    target.LINKEDASSET=src.LINKEDASSET, 
                    target.LOCALITY=src.LOCALITY, 
                    target.LOCKABLE=src.LOCKABLE, 
                    target.MAKE=src.MAKE, 
                    target.MAXFLOW=src.MAXFLOW, 
                    target.MEDIATYPE=src.MEDIATYPE, 
                    target.MINFLOW=src.MINFLOW, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MODELNO=src.MODELNO, 
                    target.OVERFLOWLEVEL=src.OVERFLOWLEVEL, 
                    target.OVERFLOWTYPE=src.OVERFLOWTYPE, 
                    target.PHOTO3D=src.PHOTO3D, 
                    target.PRESSURERATING=src.PRESSURERATING, 
                    target.PROJECTNO=src.PROJECTNO, 
                    target.PROJECTWISE=src.PROJECTWISE, 
                    target.QUAKEDESIGN=src.QUAKEDESIGN, 
                    target.RELDATE=src.RELDATE, 
                    target.RELDEPTH=src.RELDEPTH, 
                    target.RELDIA=src.RELDIA, 
                    target.RELGEOSP=src.RELGEOSP, 
                    target.RELMATL=src.RELMATL, 
                    target.RELOWN=src.RELOWN, 
                    target.RELSTATUS=src.RELSTATUS, 
                    target.REMOVABLE=src.REMOVABLE, 
                    target.SAFETYCRITICAL=src.SAFETYCRITICAL, 
                    target.STIFFRATING=src.STIFFRATING, 
                    target.SUBTYPEFEATURES=src.SUBTYPEFEATURES, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WARRANTYEND=src.WARRANTYEND, 
                    target.WARRANTYSTART=src.WARRANTYSTART, 
                    target.XCONTAINMENTKEY=src.XCONTAINMENTKEY, 
                    target.ZONECATCHMENT=src.ZONECATCHMENT, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ACCELDEPREC, 
                    ACCELDEPRECDESC, 
                    ACQTYPE, 
                    ADDBY, 
                    ADDDTTM, 
                    BOLTDOWN, 
                    BUSINESSAREA, 
                    CAPACITY, 
                    COMPKEY, 
                    CONFINEDSPACE, 
                    CONSTMETHOD, 
                    COSTCENTRE, 
                    COVERTYPE, 
                    CRITICALITY, 
                    DATALAKE_DELETED, 
                    DESIGNRESILIENCE, 
                    DIAMEXT, 
                    DIAMINT, 
                    DISCHARGECAP, 
                    DISPOSALDESC, 
                    DRAWINGNO, 
                    DRAWINGNOREF, 
                    EXTCOAT, 
                    FALLPROTECT, 
                    FORDISPOSAL, 
                    FUNCAREA, 
                    GRDLEVEL, 
                    HINGED, 
                    INHIBITLEVEL, 
                    INTLINING, 
                    INVLEVEL, 
                    JTTYPE, 
                    LIDLEVEL, 
                    LINKEDASSET, 
                    LOCALITY, 
                    LOCKABLE, 
                    MAKE, 
                    MAXFLOW, 
                    MEDIATYPE, 
                    MINFLOW, 
                    MODBY, 
                    MODDTTM, 
                    MODELNO, 
                    OVERFLOWLEVEL, 
                    OVERFLOWTYPE, 
                    PHOTO3D, 
                    PRESSURERATING, 
                    PROJECTNO, 
                    PROJECTWISE, 
                    QUAKEDESIGN, 
                    RELDATE, 
                    RELDEPTH, 
                    RELDIA, 
                    RELGEOSP, 
                    RELMATL, 
                    RELOWN, 
                    RELSTATUS, 
                    REMOVABLE, 
                    SAFETYCRITICAL, 
                    STIFFRATING, 
                    SUBTYPEFEATURES, 
                    VARIATION_ID, 
                    WARRANTYEND, 
                    WARRANTYSTART, 
                    XCONTAINMENTKEY, 
                    ZONECATCHMENT, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ACCELDEPREC, 
                    src.ACCELDEPRECDESC, 
                    src.ACQTYPE, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.BOLTDOWN, 
                    src.BUSINESSAREA, 
                    src.CAPACITY, 
                    src.COMPKEY, 
                    src.CONFINEDSPACE, 
                    src.CONSTMETHOD, 
                    src.COSTCENTRE, 
                    src.COVERTYPE, 
                    src.CRITICALITY, 
                    src.DATALAKE_DELETED, 
                    src.DESIGNRESILIENCE, 
                    src.DIAMEXT, 
                    src.DIAMINT, 
                    src.DISCHARGECAP, 
                    src.DISPOSALDESC, 
                    src.DRAWINGNO, 
                    src.DRAWINGNOREF, 
                    src.EXTCOAT, 
                    src.FALLPROTECT, 
                    src.FORDISPOSAL, 
                    src.FUNCAREA, 
                    src.GRDLEVEL, 
                    src.HINGED, 
                    src.INHIBITLEVEL, 
                    src.INTLINING, 
                    src.INVLEVEL, 
                    src.JTTYPE, 
                    src.LIDLEVEL, 
                    src.LINKEDASSET, 
                    src.LOCALITY, 
                    src.LOCKABLE, 
                    src.MAKE, 
                    src.MAXFLOW, 
                    src.MEDIATYPE, 
                    src.MINFLOW, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MODELNO, 
                    src.OVERFLOWLEVEL, 
                    src.OVERFLOWTYPE, 
                    src.PHOTO3D, 
                    src.PRESSURERATING, 
                    src.PROJECTNO, 
                    src.PROJECTWISE, 
                    src.QUAKEDESIGN, 
                    src.RELDATE, 
                    src.RELDEPTH, 
                    src.RELDIA, 
                    src.RELGEOSP, 
                    src.RELMATL, 
                    src.RELOWN, 
                    src.RELSTATUS, 
                    src.REMOVABLE, 
                    src.SAFETYCRITICAL, 
                    src.STIFFRATING, 
                    src.SUBTYPEFEATURES, 
                    src.VARIATION_ID, 
                    src.WARRANTYEND, 
                    src.WARRANTYSTART, 
                    src.XCONTAINMENTKEY, 
                    src.ZONECATCHMENT,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLASSETSCONFIGURED_XCONTAINMENT as target using (
                SELECT * FROM (SELECT 
            strm.ACCELDEPREC, 
            strm.ACCELDEPRECDESC, 
            strm.ACQTYPE, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.BOLTDOWN, 
            strm.BUSINESSAREA, 
            strm.CAPACITY, 
            strm.COMPKEY, 
            strm.CONFINEDSPACE, 
            strm.CONSTMETHOD, 
            strm.COSTCENTRE, 
            strm.COVERTYPE, 
            strm.CRITICALITY, 
            strm.DATALAKE_DELETED, 
            strm.DESIGNRESILIENCE, 
            strm.DIAMEXT, 
            strm.DIAMINT, 
            strm.DISCHARGECAP, 
            strm.DISPOSALDESC, 
            strm.DRAWINGNO, 
            strm.DRAWINGNOREF, 
            strm.EXTCOAT, 
            strm.FALLPROTECT, 
            strm.FORDISPOSAL, 
            strm.FUNCAREA, 
            strm.GRDLEVEL, 
            strm.HINGED, 
            strm.INHIBITLEVEL, 
            strm.INTLINING, 
            strm.INVLEVEL, 
            strm.JTTYPE, 
            strm.LIDLEVEL, 
            strm.LINKEDASSET, 
            strm.LOCALITY, 
            strm.LOCKABLE, 
            strm.MAKE, 
            strm.MAXFLOW, 
            strm.MEDIATYPE, 
            strm.MINFLOW, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MODELNO, 
            strm.OVERFLOWLEVEL, 
            strm.OVERFLOWTYPE, 
            strm.PHOTO3D, 
            strm.PRESSURERATING, 
            strm.PROJECTNO, 
            strm.PROJECTWISE, 
            strm.QUAKEDESIGN, 
            strm.RELDATE, 
            strm.RELDEPTH, 
            strm.RELDIA, 
            strm.RELGEOSP, 
            strm.RELMATL, 
            strm.RELOWN, 
            strm.RELSTATUS, 
            strm.REMOVABLE, 
            strm.SAFETYCRITICAL, 
            strm.STIFFRATING, 
            strm.SUBTYPEFEATURES, 
            strm.VARIATION_ID, 
            strm.WARRANTYEND, 
            strm.WARRANTYSTART, 
            strm.XCONTAINMENTKEY, 
            strm.ZONECATCHMENT, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.XCONTAINMENTKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_WSLASSETSCONFIGURED_XCONTAINMENT as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.XCONTAINMENTKEY=src.XCONTAINMENTKEY) OR (target.XCONTAINMENTKEY IS NULL AND src.XCONTAINMENTKEY IS NULL)) 
                when matched then update set
                    target.ACCELDEPREC=src.ACCELDEPREC, 
                    target.ACCELDEPRECDESC=src.ACCELDEPRECDESC, 
                    target.ACQTYPE=src.ACQTYPE, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.BOLTDOWN=src.BOLTDOWN, 
                    target.BUSINESSAREA=src.BUSINESSAREA, 
                    target.CAPACITY=src.CAPACITY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.CONFINEDSPACE=src.CONFINEDSPACE, 
                    target.CONSTMETHOD=src.CONSTMETHOD, 
                    target.COSTCENTRE=src.COSTCENTRE, 
                    target.COVERTYPE=src.COVERTYPE, 
                    target.CRITICALITY=src.CRITICALITY, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DESIGNRESILIENCE=src.DESIGNRESILIENCE, 
                    target.DIAMEXT=src.DIAMEXT, 
                    target.DIAMINT=src.DIAMINT, 
                    target.DISCHARGECAP=src.DISCHARGECAP, 
                    target.DISPOSALDESC=src.DISPOSALDESC, 
                    target.DRAWINGNO=src.DRAWINGNO, 
                    target.DRAWINGNOREF=src.DRAWINGNOREF, 
                    target.EXTCOAT=src.EXTCOAT, 
                    target.FALLPROTECT=src.FALLPROTECT, 
                    target.FORDISPOSAL=src.FORDISPOSAL, 
                    target.FUNCAREA=src.FUNCAREA, 
                    target.GRDLEVEL=src.GRDLEVEL, 
                    target.HINGED=src.HINGED, 
                    target.INHIBITLEVEL=src.INHIBITLEVEL, 
                    target.INTLINING=src.INTLINING, 
                    target.INVLEVEL=src.INVLEVEL, 
                    target.JTTYPE=src.JTTYPE, 
                    target.LIDLEVEL=src.LIDLEVEL, 
                    target.LINKEDASSET=src.LINKEDASSET, 
                    target.LOCALITY=src.LOCALITY, 
                    target.LOCKABLE=src.LOCKABLE, 
                    target.MAKE=src.MAKE, 
                    target.MAXFLOW=src.MAXFLOW, 
                    target.MEDIATYPE=src.MEDIATYPE, 
                    target.MINFLOW=src.MINFLOW, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MODELNO=src.MODELNO, 
                    target.OVERFLOWLEVEL=src.OVERFLOWLEVEL, 
                    target.OVERFLOWTYPE=src.OVERFLOWTYPE, 
                    target.PHOTO3D=src.PHOTO3D, 
                    target.PRESSURERATING=src.PRESSURERATING, 
                    target.PROJECTNO=src.PROJECTNO, 
                    target.PROJECTWISE=src.PROJECTWISE, 
                    target.QUAKEDESIGN=src.QUAKEDESIGN, 
                    target.RELDATE=src.RELDATE, 
                    target.RELDEPTH=src.RELDEPTH, 
                    target.RELDIA=src.RELDIA, 
                    target.RELGEOSP=src.RELGEOSP, 
                    target.RELMATL=src.RELMATL, 
                    target.RELOWN=src.RELOWN, 
                    target.RELSTATUS=src.RELSTATUS, 
                    target.REMOVABLE=src.REMOVABLE, 
                    target.SAFETYCRITICAL=src.SAFETYCRITICAL, 
                    target.STIFFRATING=src.STIFFRATING, 
                    target.SUBTYPEFEATURES=src.SUBTYPEFEATURES, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WARRANTYEND=src.WARRANTYEND, 
                    target.WARRANTYSTART=src.WARRANTYSTART, 
                    target.XCONTAINMENTKEY=src.XCONTAINMENTKEY, 
                    target.ZONECATCHMENT=src.ZONECATCHMENT, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ACCELDEPREC, ACCELDEPRECDESC, ACQTYPE, ADDBY, ADDDTTM, BOLTDOWN, BUSINESSAREA, CAPACITY, COMPKEY, CONFINEDSPACE, CONSTMETHOD, COSTCENTRE, COVERTYPE, CRITICALITY, DATALAKE_DELETED, DESIGNRESILIENCE, DIAMEXT, DIAMINT, DISCHARGECAP, DISPOSALDESC, DRAWINGNO, DRAWINGNOREF, EXTCOAT, FALLPROTECT, FORDISPOSAL, FUNCAREA, GRDLEVEL, HINGED, INHIBITLEVEL, INTLINING, INVLEVEL, JTTYPE, LIDLEVEL, LINKEDASSET, LOCALITY, LOCKABLE, MAKE, MAXFLOW, MEDIATYPE, MINFLOW, MODBY, MODDTTM, MODELNO, OVERFLOWLEVEL, OVERFLOWTYPE, PHOTO3D, PRESSURERATING, PROJECTNO, PROJECTWISE, QUAKEDESIGN, RELDATE, RELDEPTH, RELDIA, RELGEOSP, RELMATL, RELOWN, RELSTATUS, REMOVABLE, SAFETYCRITICAL, STIFFRATING, SUBTYPEFEATURES, VARIATION_ID, WARRANTYEND, WARRANTYSTART, XCONTAINMENTKEY, ZONECATCHMENT, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ACCELDEPREC, 
                    src.ACCELDEPRECDESC, 
                    src.ACQTYPE, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.BOLTDOWN, 
                    src.BUSINESSAREA, 
                    src.CAPACITY, 
                    src.COMPKEY, 
                    src.CONFINEDSPACE, 
                    src.CONSTMETHOD, 
                    src.COSTCENTRE, 
                    src.COVERTYPE, 
                    src.CRITICALITY, 
                    src.DATALAKE_DELETED, 
                    src.DESIGNRESILIENCE, 
                    src.DIAMEXT, 
                    src.DIAMINT, 
                    src.DISCHARGECAP, 
                    src.DISPOSALDESC, 
                    src.DRAWINGNO, 
                    src.DRAWINGNOREF, 
                    src.EXTCOAT, 
                    src.FALLPROTECT, 
                    src.FORDISPOSAL, 
                    src.FUNCAREA, 
                    src.GRDLEVEL, 
                    src.HINGED, 
                    src.INHIBITLEVEL, 
                    src.INTLINING, 
                    src.INVLEVEL, 
                    src.JTTYPE, 
                    src.LIDLEVEL, 
                    src.LINKEDASSET, 
                    src.LOCALITY, 
                    src.LOCKABLE, 
                    src.MAKE, 
                    src.MAXFLOW, 
                    src.MEDIATYPE, 
                    src.MINFLOW, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MODELNO, 
                    src.OVERFLOWLEVEL, 
                    src.OVERFLOWTYPE, 
                    src.PHOTO3D, 
                    src.PRESSURERATING, 
                    src.PROJECTNO, 
                    src.PROJECTWISE, 
                    src.QUAKEDESIGN, 
                    src.RELDATE, 
                    src.RELDEPTH, 
                    src.RELDIA, 
                    src.RELGEOSP, 
                    src.RELMATL, 
                    src.RELOWN, 
                    src.RELSTATUS, 
                    src.REMOVABLE, 
                    src.SAFETYCRITICAL, 
                    src.STIFFRATING, 
                    src.SUBTYPEFEATURES, 
                    src.VARIATION_ID, 
                    src.WARRANTYEND, 
                    src.WARRANTYSTART, 
                    src.XCONTAINMENTKEY, 
                    src.ZONECATCHMENT,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;