create or replace procedure DATAHUB_INTEGRATION.SP_IPS_BILLING_BILL()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_BILLING_BILL_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_BILLING_BILL as target using (SELECT * FROM (SELECT 
            strm.ACCOUNTKEY, 
            strm.ACCTBALCALCFLAG, 
            strm.ACTUALAMT, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDR1, 
            strm.ADDR2, 
            strm.ADJAMT, 
            strm.ADJUSTMENTLINEITEMSAMOUNT, 
            strm.ARNGAMT, 
            strm.ARNGPAYAMT, 
            strm.BATCHIDENTIFIER, 
            strm.BILLADJAMT, 
            strm.BILLAMT, 
            strm.BILLDATE, 
            strm.BILLKEY, 
            strm.BILLNO, 
            strm.BILLPERFRDATE, 
            strm.BILLPERTODATE, 
            strm.BILLRUNKEY, 
            strm.BILLTO, 
            strm.BILLTOLINE2, 
            strm.BILLTYPEKEY, 
            strm.BUDGETBILLINGPLANKEY, 
            strm.CALCULATEDFLAG, 
            strm.CARRT, 
            strm.CASSVER, 
            strm.CITY, 
            strm.COLLAMT, 
            strm.COLLKEY, 
            strm.CONAME, 
            strm.CONCCRED, 
            strm.CONCSAPPLFLAG, 
            strm.CORRKEY, 
            strm.COUNTRY, 
            strm.CREATEDDTTM, 
            strm.CREDITFLAG, 
            strm.CUMVARIAMT, 
            strm.CURRAMT, 
            strm.DATALAKE_DELETED, 
            strm.DAYSRDS, 
            strm.DEFERREDPENALTYAMOUNT, 
            strm.DEFERREDPENALTYDATE, 
            strm.DELINQUENTDATE, 
            strm.DEPAMT, 
            strm.DEPDUEAMT, 
            strm.DEPOSITLINEITEMSAMOUNT, 
            strm.DIRECTDEBITRUNKEY, 
            strm.DISCEXPAMT, 
            strm.DISCEXPDATE, 
            strm.DISCOUNTLINEITEMSAMOUNT, 
            strm.DISPAMT, 
            strm.DLNQAMT, 
            strm.DPC, 
            strm.DUEDATE, 
            strm.EARLYPAYORDEFERREDPENALTY, 
            strm.ENTNO, 
            strm.ESTIMATEFLAG, 
            strm.EXCLUSIVEFLAG, 
            strm.EXTRACTDATE, 
            strm.FINALBILLFLAG, 
            strm.INSTNO, 
            strm.INSTTOTAMT, 
            strm.INTAMT, 
            strm.INTERIMFLAG, 
            strm.LIENAMT, 
            strm.LIENKEY, 
            strm.LOT, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.NOBILLFLAG, 
            strm.OUTPUTFLAG, 
            strm.OVERAMT, 
            strm.PAIDDTTM, 
            strm.PAIDSTAT, 
            strm.PAYMENTLINEITEMSAMOUNT, 
            strm.PAYORDER, 
            strm.PENALTYLINEITEMSAMOUNT, 
            strm.PENAMT, 
            strm.PENEXEMPT, 
            strm.POSTEDFLAG, 
            strm.POSTEDTTM, 
            strm.PREVIOUSBILLKEY, 
            strm.PRINCIPALTOTALAMOUNT, 
            strm.PRIORBILLAMT, 
            strm.PROPADDR, 
            strm.REVERSEDBILLKEY, 
            strm.REVERSEFLAG, 
            strm.SETLAMT, 
            strm.SETTLEMENTKEY, 
            strm.STATE, 
            strm.VARIAMT, 
            strm.VARIATION_ID, 
            strm.ZIP, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.BILLKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_BILLING_BILL as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.BILLKEY=src.BILLKEY) OR (target.BILLKEY IS NULL AND src.BILLKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ACCOUNTKEY=src.ACCOUNTKEY, 
                    target.ACCTBALCALCFLAG=src.ACCTBALCALCFLAG, 
                    target.ACTUALAMT=src.ACTUALAMT, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDR1=src.ADDR1, 
                    target.ADDR2=src.ADDR2, 
                    target.ADJAMT=src.ADJAMT, 
                    target.ADJUSTMENTLINEITEMSAMOUNT=src.ADJUSTMENTLINEITEMSAMOUNT, 
                    target.ARNGAMT=src.ARNGAMT, 
                    target.ARNGPAYAMT=src.ARNGPAYAMT, 
                    target.BATCHIDENTIFIER=src.BATCHIDENTIFIER, 
                    target.BILLADJAMT=src.BILLADJAMT, 
                    target.BILLAMT=src.BILLAMT, 
                    target.BILLDATE=src.BILLDATE, 
                    target.BILLKEY=src.BILLKEY, 
                    target.BILLNO=src.BILLNO, 
                    target.BILLPERFRDATE=src.BILLPERFRDATE, 
                    target.BILLPERTODATE=src.BILLPERTODATE, 
                    target.BILLRUNKEY=src.BILLRUNKEY, 
                    target.BILLTO=src.BILLTO, 
                    target.BILLTOLINE2=src.BILLTOLINE2, 
                    target.BILLTYPEKEY=src.BILLTYPEKEY, 
                    target.BUDGETBILLINGPLANKEY=src.BUDGETBILLINGPLANKEY, 
                    target.CALCULATEDFLAG=src.CALCULATEDFLAG, 
                    target.CARRT=src.CARRT, 
                    target.CASSVER=src.CASSVER, 
                    target.CITY=src.CITY, 
                    target.COLLAMT=src.COLLAMT, 
                    target.COLLKEY=src.COLLKEY, 
                    target.CONAME=src.CONAME, 
                    target.CONCCRED=src.CONCCRED, 
                    target.CONCSAPPLFLAG=src.CONCSAPPLFLAG, 
                    target.CORRKEY=src.CORRKEY, 
                    target.COUNTRY=src.COUNTRY, 
                    target.CREATEDDTTM=src.CREATEDDTTM, 
                    target.CREDITFLAG=src.CREDITFLAG, 
                    target.CUMVARIAMT=src.CUMVARIAMT, 
                    target.CURRAMT=src.CURRAMT, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DAYSRDS=src.DAYSRDS, 
                    target.DEFERREDPENALTYAMOUNT=src.DEFERREDPENALTYAMOUNT, 
                    target.DEFERREDPENALTYDATE=src.DEFERREDPENALTYDATE, 
                    target.DELINQUENTDATE=src.DELINQUENTDATE, 
                    target.DEPAMT=src.DEPAMT, 
                    target.DEPDUEAMT=src.DEPDUEAMT, 
                    target.DEPOSITLINEITEMSAMOUNT=src.DEPOSITLINEITEMSAMOUNT, 
                    target.DIRECTDEBITRUNKEY=src.DIRECTDEBITRUNKEY, 
                    target.DISCEXPAMT=src.DISCEXPAMT, 
                    target.DISCEXPDATE=src.DISCEXPDATE, 
                    target.DISCOUNTLINEITEMSAMOUNT=src.DISCOUNTLINEITEMSAMOUNT, 
                    target.DISPAMT=src.DISPAMT, 
                    target.DLNQAMT=src.DLNQAMT, 
                    target.DPC=src.DPC, 
                    target.DUEDATE=src.DUEDATE, 
                    target.EARLYPAYORDEFERREDPENALTY=src.EARLYPAYORDEFERREDPENALTY, 
                    target.ENTNO=src.ENTNO, 
                    target.ESTIMATEFLAG=src.ESTIMATEFLAG, 
                    target.EXCLUSIVEFLAG=src.EXCLUSIVEFLAG, 
                    target.EXTRACTDATE=src.EXTRACTDATE, 
                    target.FINALBILLFLAG=src.FINALBILLFLAG, 
                    target.INSTNO=src.INSTNO, 
                    target.INSTTOTAMT=src.INSTTOTAMT, 
                    target.INTAMT=src.INTAMT, 
                    target.INTERIMFLAG=src.INTERIMFLAG, 
                    target.LIENAMT=src.LIENAMT, 
                    target.LIENKEY=src.LIENKEY, 
                    target.LOT=src.LOT, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.NOBILLFLAG=src.NOBILLFLAG, 
                    target.OUTPUTFLAG=src.OUTPUTFLAG, 
                    target.OVERAMT=src.OVERAMT, 
                    target.PAIDDTTM=src.PAIDDTTM, 
                    target.PAIDSTAT=src.PAIDSTAT, 
                    target.PAYMENTLINEITEMSAMOUNT=src.PAYMENTLINEITEMSAMOUNT, 
                    target.PAYORDER=src.PAYORDER, 
                    target.PENALTYLINEITEMSAMOUNT=src.PENALTYLINEITEMSAMOUNT, 
                    target.PENAMT=src.PENAMT, 
                    target.PENEXEMPT=src.PENEXEMPT, 
                    target.POSTEDFLAG=src.POSTEDFLAG, 
                    target.POSTEDTTM=src.POSTEDTTM, 
                    target.PREVIOUSBILLKEY=src.PREVIOUSBILLKEY, 
                    target.PRINCIPALTOTALAMOUNT=src.PRINCIPALTOTALAMOUNT, 
                    target.PRIORBILLAMT=src.PRIORBILLAMT, 
                    target.PROPADDR=src.PROPADDR, 
                    target.REVERSEDBILLKEY=src.REVERSEDBILLKEY, 
                    target.REVERSEFLAG=src.REVERSEFLAG, 
                    target.SETLAMT=src.SETLAMT, 
                    target.SETTLEMENTKEY=src.SETTLEMENTKEY, 
                    target.STATE=src.STATE, 
                    target.VARIAMT=src.VARIAMT, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.ZIP=src.ZIP, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ACCOUNTKEY, 
                    ACCTBALCALCFLAG, 
                    ACTUALAMT, 
                    ADDBY, 
                    ADDDTTM, 
                    ADDR1, 
                    ADDR2, 
                    ADJAMT, 
                    ADJUSTMENTLINEITEMSAMOUNT, 
                    ARNGAMT, 
                    ARNGPAYAMT, 
                    BATCHIDENTIFIER, 
                    BILLADJAMT, 
                    BILLAMT, 
                    BILLDATE, 
                    BILLKEY, 
                    BILLNO, 
                    BILLPERFRDATE, 
                    BILLPERTODATE, 
                    BILLRUNKEY, 
                    BILLTO, 
                    BILLTOLINE2, 
                    BILLTYPEKEY, 
                    BUDGETBILLINGPLANKEY, 
                    CALCULATEDFLAG, 
                    CARRT, 
                    CASSVER, 
                    CITY, 
                    COLLAMT, 
                    COLLKEY, 
                    CONAME, 
                    CONCCRED, 
                    CONCSAPPLFLAG, 
                    CORRKEY, 
                    COUNTRY, 
                    CREATEDDTTM, 
                    CREDITFLAG, 
                    CUMVARIAMT, 
                    CURRAMT, 
                    DATALAKE_DELETED, 
                    DAYSRDS, 
                    DEFERREDPENALTYAMOUNT, 
                    DEFERREDPENALTYDATE, 
                    DELINQUENTDATE, 
                    DEPAMT, 
                    DEPDUEAMT, 
                    DEPOSITLINEITEMSAMOUNT, 
                    DIRECTDEBITRUNKEY, 
                    DISCEXPAMT, 
                    DISCEXPDATE, 
                    DISCOUNTLINEITEMSAMOUNT, 
                    DISPAMT, 
                    DLNQAMT, 
                    DPC, 
                    DUEDATE, 
                    EARLYPAYORDEFERREDPENALTY, 
                    ENTNO, 
                    ESTIMATEFLAG, 
                    EXCLUSIVEFLAG, 
                    EXTRACTDATE, 
                    FINALBILLFLAG, 
                    INSTNO, 
                    INSTTOTAMT, 
                    INTAMT, 
                    INTERIMFLAG, 
                    LIENAMT, 
                    LIENKEY, 
                    LOT, 
                    MODBY, 
                    MODDTTM, 
                    NOBILLFLAG, 
                    OUTPUTFLAG, 
                    OVERAMT, 
                    PAIDDTTM, 
                    PAIDSTAT, 
                    PAYMENTLINEITEMSAMOUNT, 
                    PAYORDER, 
                    PENALTYLINEITEMSAMOUNT, 
                    PENAMT, 
                    PENEXEMPT, 
                    POSTEDFLAG, 
                    POSTEDTTM, 
                    PREVIOUSBILLKEY, 
                    PRINCIPALTOTALAMOUNT, 
                    PRIORBILLAMT, 
                    PROPADDR, 
                    REVERSEDBILLKEY, 
                    REVERSEFLAG, 
                    SETLAMT, 
                    SETTLEMENTKEY, 
                    STATE, 
                    VARIAMT, 
                    VARIATION_ID, 
                    ZIP, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ACCOUNTKEY, 
                    src.ACCTBALCALCFLAG, 
                    src.ACTUALAMT, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDR1, 
                    src.ADDR2, 
                    src.ADJAMT, 
                    src.ADJUSTMENTLINEITEMSAMOUNT, 
                    src.ARNGAMT, 
                    src.ARNGPAYAMT, 
                    src.BATCHIDENTIFIER, 
                    src.BILLADJAMT, 
                    src.BILLAMT, 
                    src.BILLDATE, 
                    src.BILLKEY, 
                    src.BILLNO, 
                    src.BILLPERFRDATE, 
                    src.BILLPERTODATE, 
                    src.BILLRUNKEY, 
                    src.BILLTO, 
                    src.BILLTOLINE2, 
                    src.BILLTYPEKEY, 
                    src.BUDGETBILLINGPLANKEY, 
                    src.CALCULATEDFLAG, 
                    src.CARRT, 
                    src.CASSVER, 
                    src.CITY, 
                    src.COLLAMT, 
                    src.COLLKEY, 
                    src.CONAME, 
                    src.CONCCRED, 
                    src.CONCSAPPLFLAG, 
                    src.CORRKEY, 
                    src.COUNTRY, 
                    src.CREATEDDTTM, 
                    src.CREDITFLAG, 
                    src.CUMVARIAMT, 
                    src.CURRAMT, 
                    src.DATALAKE_DELETED, 
                    src.DAYSRDS, 
                    src.DEFERREDPENALTYAMOUNT, 
                    src.DEFERREDPENALTYDATE, 
                    src.DELINQUENTDATE, 
                    src.DEPAMT, 
                    src.DEPDUEAMT, 
                    src.DEPOSITLINEITEMSAMOUNT, 
                    src.DIRECTDEBITRUNKEY, 
                    src.DISCEXPAMT, 
                    src.DISCEXPDATE, 
                    src.DISCOUNTLINEITEMSAMOUNT, 
                    src.DISPAMT, 
                    src.DLNQAMT, 
                    src.DPC, 
                    src.DUEDATE, 
                    src.EARLYPAYORDEFERREDPENALTY, 
                    src.ENTNO, 
                    src.ESTIMATEFLAG, 
                    src.EXCLUSIVEFLAG, 
                    src.EXTRACTDATE, 
                    src.FINALBILLFLAG, 
                    src.INSTNO, 
                    src.INSTTOTAMT, 
                    src.INTAMT, 
                    src.INTERIMFLAG, 
                    src.LIENAMT, 
                    src.LIENKEY, 
                    src.LOT, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.NOBILLFLAG, 
                    src.OUTPUTFLAG, 
                    src.OVERAMT, 
                    src.PAIDDTTM, 
                    src.PAIDSTAT, 
                    src.PAYMENTLINEITEMSAMOUNT, 
                    src.PAYORDER, 
                    src.PENALTYLINEITEMSAMOUNT, 
                    src.PENAMT, 
                    src.PENEXEMPT, 
                    src.POSTEDFLAG, 
                    src.POSTEDTTM, 
                    src.PREVIOUSBILLKEY, 
                    src.PRINCIPALTOTALAMOUNT, 
                    src.PRIORBILLAMT, 
                    src.PROPADDR, 
                    src.REVERSEDBILLKEY, 
                    src.REVERSEFLAG, 
                    src.SETLAMT, 
                    src.SETTLEMENTKEY, 
                    src.STATE, 
                    src.VARIAMT, 
                    src.VARIATION_ID, 
                    src.ZIP,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_BILL as target using (
                SELECT * FROM (SELECT 
            strm.ACCOUNTKEY, 
            strm.ACCTBALCALCFLAG, 
            strm.ACTUALAMT, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDR1, 
            strm.ADDR2, 
            strm.ADJAMT, 
            strm.ADJUSTMENTLINEITEMSAMOUNT, 
            strm.ARNGAMT, 
            strm.ARNGPAYAMT, 
            strm.BATCHIDENTIFIER, 
            strm.BILLADJAMT, 
            strm.BILLAMT, 
            strm.BILLDATE, 
            strm.BILLKEY, 
            strm.BILLNO, 
            strm.BILLPERFRDATE, 
            strm.BILLPERTODATE, 
            strm.BILLRUNKEY, 
            strm.BILLTO, 
            strm.BILLTOLINE2, 
            strm.BILLTYPEKEY, 
            strm.BUDGETBILLINGPLANKEY, 
            strm.CALCULATEDFLAG, 
            strm.CARRT, 
            strm.CASSVER, 
            strm.CITY, 
            strm.COLLAMT, 
            strm.COLLKEY, 
            strm.CONAME, 
            strm.CONCCRED, 
            strm.CONCSAPPLFLAG, 
            strm.CORRKEY, 
            strm.COUNTRY, 
            strm.CREATEDDTTM, 
            strm.CREDITFLAG, 
            strm.CUMVARIAMT, 
            strm.CURRAMT, 
            strm.DATALAKE_DELETED, 
            strm.DAYSRDS, 
            strm.DEFERREDPENALTYAMOUNT, 
            strm.DEFERREDPENALTYDATE, 
            strm.DELINQUENTDATE, 
            strm.DEPAMT, 
            strm.DEPDUEAMT, 
            strm.DEPOSITLINEITEMSAMOUNT, 
            strm.DIRECTDEBITRUNKEY, 
            strm.DISCEXPAMT, 
            strm.DISCEXPDATE, 
            strm.DISCOUNTLINEITEMSAMOUNT, 
            strm.DISPAMT, 
            strm.DLNQAMT, 
            strm.DPC, 
            strm.DUEDATE, 
            strm.EARLYPAYORDEFERREDPENALTY, 
            strm.ENTNO, 
            strm.ESTIMATEFLAG, 
            strm.EXCLUSIVEFLAG, 
            strm.EXTRACTDATE, 
            strm.FINALBILLFLAG, 
            strm.INSTNO, 
            strm.INSTTOTAMT, 
            strm.INTAMT, 
            strm.INTERIMFLAG, 
            strm.LIENAMT, 
            strm.LIENKEY, 
            strm.LOT, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.NOBILLFLAG, 
            strm.OUTPUTFLAG, 
            strm.OVERAMT, 
            strm.PAIDDTTM, 
            strm.PAIDSTAT, 
            strm.PAYMENTLINEITEMSAMOUNT, 
            strm.PAYORDER, 
            strm.PENALTYLINEITEMSAMOUNT, 
            strm.PENAMT, 
            strm.PENEXEMPT, 
            strm.POSTEDFLAG, 
            strm.POSTEDTTM, 
            strm.PREVIOUSBILLKEY, 
            strm.PRINCIPALTOTALAMOUNT, 
            strm.PRIORBILLAMT, 
            strm.PROPADDR, 
            strm.REVERSEDBILLKEY, 
            strm.REVERSEFLAG, 
            strm.SETLAMT, 
            strm.SETTLEMENTKEY, 
            strm.STATE, 
            strm.VARIAMT, 
            strm.VARIATION_ID, 
            strm.ZIP, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.BILLKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_BILLING_BILL as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.BILLKEY=src.BILLKEY) OR (target.BILLKEY IS NULL AND src.BILLKEY IS NULL)) 
                when matched then update set
                    target.ACCOUNTKEY=src.ACCOUNTKEY, 
                    target.ACCTBALCALCFLAG=src.ACCTBALCALCFLAG, 
                    target.ACTUALAMT=src.ACTUALAMT, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDR1=src.ADDR1, 
                    target.ADDR2=src.ADDR2, 
                    target.ADJAMT=src.ADJAMT, 
                    target.ADJUSTMENTLINEITEMSAMOUNT=src.ADJUSTMENTLINEITEMSAMOUNT, 
                    target.ARNGAMT=src.ARNGAMT, 
                    target.ARNGPAYAMT=src.ARNGPAYAMT, 
                    target.BATCHIDENTIFIER=src.BATCHIDENTIFIER, 
                    target.BILLADJAMT=src.BILLADJAMT, 
                    target.BILLAMT=src.BILLAMT, 
                    target.BILLDATE=src.BILLDATE, 
                    target.BILLKEY=src.BILLKEY, 
                    target.BILLNO=src.BILLNO, 
                    target.BILLPERFRDATE=src.BILLPERFRDATE, 
                    target.BILLPERTODATE=src.BILLPERTODATE, 
                    target.BILLRUNKEY=src.BILLRUNKEY, 
                    target.BILLTO=src.BILLTO, 
                    target.BILLTOLINE2=src.BILLTOLINE2, 
                    target.BILLTYPEKEY=src.BILLTYPEKEY, 
                    target.BUDGETBILLINGPLANKEY=src.BUDGETBILLINGPLANKEY, 
                    target.CALCULATEDFLAG=src.CALCULATEDFLAG, 
                    target.CARRT=src.CARRT, 
                    target.CASSVER=src.CASSVER, 
                    target.CITY=src.CITY, 
                    target.COLLAMT=src.COLLAMT, 
                    target.COLLKEY=src.COLLKEY, 
                    target.CONAME=src.CONAME, 
                    target.CONCCRED=src.CONCCRED, 
                    target.CONCSAPPLFLAG=src.CONCSAPPLFLAG, 
                    target.CORRKEY=src.CORRKEY, 
                    target.COUNTRY=src.COUNTRY, 
                    target.CREATEDDTTM=src.CREATEDDTTM, 
                    target.CREDITFLAG=src.CREDITFLAG, 
                    target.CUMVARIAMT=src.CUMVARIAMT, 
                    target.CURRAMT=src.CURRAMT, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DAYSRDS=src.DAYSRDS, 
                    target.DEFERREDPENALTYAMOUNT=src.DEFERREDPENALTYAMOUNT, 
                    target.DEFERREDPENALTYDATE=src.DEFERREDPENALTYDATE, 
                    target.DELINQUENTDATE=src.DELINQUENTDATE, 
                    target.DEPAMT=src.DEPAMT, 
                    target.DEPDUEAMT=src.DEPDUEAMT, 
                    target.DEPOSITLINEITEMSAMOUNT=src.DEPOSITLINEITEMSAMOUNT, 
                    target.DIRECTDEBITRUNKEY=src.DIRECTDEBITRUNKEY, 
                    target.DISCEXPAMT=src.DISCEXPAMT, 
                    target.DISCEXPDATE=src.DISCEXPDATE, 
                    target.DISCOUNTLINEITEMSAMOUNT=src.DISCOUNTLINEITEMSAMOUNT, 
                    target.DISPAMT=src.DISPAMT, 
                    target.DLNQAMT=src.DLNQAMT, 
                    target.DPC=src.DPC, 
                    target.DUEDATE=src.DUEDATE, 
                    target.EARLYPAYORDEFERREDPENALTY=src.EARLYPAYORDEFERREDPENALTY, 
                    target.ENTNO=src.ENTNO, 
                    target.ESTIMATEFLAG=src.ESTIMATEFLAG, 
                    target.EXCLUSIVEFLAG=src.EXCLUSIVEFLAG, 
                    target.EXTRACTDATE=src.EXTRACTDATE, 
                    target.FINALBILLFLAG=src.FINALBILLFLAG, 
                    target.INSTNO=src.INSTNO, 
                    target.INSTTOTAMT=src.INSTTOTAMT, 
                    target.INTAMT=src.INTAMT, 
                    target.INTERIMFLAG=src.INTERIMFLAG, 
                    target.LIENAMT=src.LIENAMT, 
                    target.LIENKEY=src.LIENKEY, 
                    target.LOT=src.LOT, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.NOBILLFLAG=src.NOBILLFLAG, 
                    target.OUTPUTFLAG=src.OUTPUTFLAG, 
                    target.OVERAMT=src.OVERAMT, 
                    target.PAIDDTTM=src.PAIDDTTM, 
                    target.PAIDSTAT=src.PAIDSTAT, 
                    target.PAYMENTLINEITEMSAMOUNT=src.PAYMENTLINEITEMSAMOUNT, 
                    target.PAYORDER=src.PAYORDER, 
                    target.PENALTYLINEITEMSAMOUNT=src.PENALTYLINEITEMSAMOUNT, 
                    target.PENAMT=src.PENAMT, 
                    target.PENEXEMPT=src.PENEXEMPT, 
                    target.POSTEDFLAG=src.POSTEDFLAG, 
                    target.POSTEDTTM=src.POSTEDTTM, 
                    target.PREVIOUSBILLKEY=src.PREVIOUSBILLKEY, 
                    target.PRINCIPALTOTALAMOUNT=src.PRINCIPALTOTALAMOUNT, 
                    target.PRIORBILLAMT=src.PRIORBILLAMT, 
                    target.PROPADDR=src.PROPADDR, 
                    target.REVERSEDBILLKEY=src.REVERSEDBILLKEY, 
                    target.REVERSEFLAG=src.REVERSEFLAG, 
                    target.SETLAMT=src.SETLAMT, 
                    target.SETTLEMENTKEY=src.SETTLEMENTKEY, 
                    target.STATE=src.STATE, 
                    target.VARIAMT=src.VARIAMT, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.ZIP=src.ZIP, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ACCOUNTKEY, ACCTBALCALCFLAG, ACTUALAMT, ADDBY, ADDDTTM, ADDR1, ADDR2, ADJAMT, ADJUSTMENTLINEITEMSAMOUNT, ARNGAMT, ARNGPAYAMT, BATCHIDENTIFIER, BILLADJAMT, BILLAMT, BILLDATE, BILLKEY, BILLNO, BILLPERFRDATE, BILLPERTODATE, BILLRUNKEY, BILLTO, BILLTOLINE2, BILLTYPEKEY, BUDGETBILLINGPLANKEY, CALCULATEDFLAG, CARRT, CASSVER, CITY, COLLAMT, COLLKEY, CONAME, CONCCRED, CONCSAPPLFLAG, CORRKEY, COUNTRY, CREATEDDTTM, CREDITFLAG, CUMVARIAMT, CURRAMT, DATALAKE_DELETED, DAYSRDS, DEFERREDPENALTYAMOUNT, DEFERREDPENALTYDATE, DELINQUENTDATE, DEPAMT, DEPDUEAMT, DEPOSITLINEITEMSAMOUNT, DIRECTDEBITRUNKEY, DISCEXPAMT, DISCEXPDATE, DISCOUNTLINEITEMSAMOUNT, DISPAMT, DLNQAMT, DPC, DUEDATE, EARLYPAYORDEFERREDPENALTY, ENTNO, ESTIMATEFLAG, EXCLUSIVEFLAG, EXTRACTDATE, FINALBILLFLAG, INSTNO, INSTTOTAMT, INTAMT, INTERIMFLAG, LIENAMT, LIENKEY, LOT, MODBY, MODDTTM, NOBILLFLAG, OUTPUTFLAG, OVERAMT, PAIDDTTM, PAIDSTAT, PAYMENTLINEITEMSAMOUNT, PAYORDER, PENALTYLINEITEMSAMOUNT, PENAMT, PENEXEMPT, POSTEDFLAG, POSTEDTTM, PREVIOUSBILLKEY, PRINCIPALTOTALAMOUNT, PRIORBILLAMT, PROPADDR, REVERSEDBILLKEY, REVERSEFLAG, SETLAMT, SETTLEMENTKEY, STATE, VARIAMT, VARIATION_ID, ZIP, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ACCOUNTKEY, 
                    src.ACCTBALCALCFLAG, 
                    src.ACTUALAMT, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDR1, 
                    src.ADDR2, 
                    src.ADJAMT, 
                    src.ADJUSTMENTLINEITEMSAMOUNT, 
                    src.ARNGAMT, 
                    src.ARNGPAYAMT, 
                    src.BATCHIDENTIFIER, 
                    src.BILLADJAMT, 
                    src.BILLAMT, 
                    src.BILLDATE, 
                    src.BILLKEY, 
                    src.BILLNO, 
                    src.BILLPERFRDATE, 
                    src.BILLPERTODATE, 
                    src.BILLRUNKEY, 
                    src.BILLTO, 
                    src.BILLTOLINE2, 
                    src.BILLTYPEKEY, 
                    src.BUDGETBILLINGPLANKEY, 
                    src.CALCULATEDFLAG, 
                    src.CARRT, 
                    src.CASSVER, 
                    src.CITY, 
                    src.COLLAMT, 
                    src.COLLKEY, 
                    src.CONAME, 
                    src.CONCCRED, 
                    src.CONCSAPPLFLAG, 
                    src.CORRKEY, 
                    src.COUNTRY, 
                    src.CREATEDDTTM, 
                    src.CREDITFLAG, 
                    src.CUMVARIAMT, 
                    src.CURRAMT, 
                    src.DATALAKE_DELETED, 
                    src.DAYSRDS, 
                    src.DEFERREDPENALTYAMOUNT, 
                    src.DEFERREDPENALTYDATE, 
                    src.DELINQUENTDATE, 
                    src.DEPAMT, 
                    src.DEPDUEAMT, 
                    src.DEPOSITLINEITEMSAMOUNT, 
                    src.DIRECTDEBITRUNKEY, 
                    src.DISCEXPAMT, 
                    src.DISCEXPDATE, 
                    src.DISCOUNTLINEITEMSAMOUNT, 
                    src.DISPAMT, 
                    src.DLNQAMT, 
                    src.DPC, 
                    src.DUEDATE, 
                    src.EARLYPAYORDEFERREDPENALTY, 
                    src.ENTNO, 
                    src.ESTIMATEFLAG, 
                    src.EXCLUSIVEFLAG, 
                    src.EXTRACTDATE, 
                    src.FINALBILLFLAG, 
                    src.INSTNO, 
                    src.INSTTOTAMT, 
                    src.INTAMT, 
                    src.INTERIMFLAG, 
                    src.LIENAMT, 
                    src.LIENKEY, 
                    src.LOT, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.NOBILLFLAG, 
                    src.OUTPUTFLAG, 
                    src.OVERAMT, 
                    src.PAIDDTTM, 
                    src.PAIDSTAT, 
                    src.PAYMENTLINEITEMSAMOUNT, 
                    src.PAYORDER, 
                    src.PENALTYLINEITEMSAMOUNT, 
                    src.PENAMT, 
                    src.PENEXEMPT, 
                    src.POSTEDFLAG, 
                    src.POSTEDTTM, 
                    src.PREVIOUSBILLKEY, 
                    src.PRINCIPALTOTALAMOUNT, 
                    src.PRIORBILLAMT, 
                    src.PROPADDR, 
                    src.REVERSEDBILLKEY, 
                    src.REVERSEFLAG, 
                    src.SETLAMT, 
                    src.SETTLEMENTKEY, 
                    src.STATE, 
                    src.VARIAMT, 
                    src.VARIATION_ID, 
                    src.ZIP,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;