create or replace procedure DATAHUB_INTEGRATION.SP_IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALH()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALH_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALH as target using (SELECT * FROM (SELECT 
            strm.ACCDEPREC, 
            strm.ACCPERIOD, 
            strm.ACQDATE, 
            strm.ACQTYPE, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ASSVALHISTKEY, 
            strm.ASSVALKEY, 
            strm.ASSVALRUNKEY, 
            strm.BACKDATEADJFLAG, 
            strm.BGTKEY, 
            strm.BGTKEY2, 
            strm.BGTKEY3, 
            strm.BGTNO, 
            strm.BOOKID, 
            strm.CAPTLDATE, 
            strm.CAPTLEXP, 
            strm.CATEGORY, 
            strm.CLASS, 
            strm.COMPKEY, 
            strm.COMPTYPE, 
            strm.DATALAKE_DELETED, 
            strm.DEPRECRATE, 
            strm.DEPRECTYPE, 
            strm.DEPRECYTD, 
            strm.DEPRESIDLF, 
            strm.DISJOURNALDATE, 
            strm.DISPBGTKEY, 
            strm.DISPBGTNO, 
            strm.DISPDATE, 
            strm.DISPDESC, 
            strm.DISPVAL, 
            strm.EXPLIFE, 
            strm.INITCOST, 
            strm.INSUREVAL, 
            strm.LINEARFROMFT, 
            strm.LINEARFROMM, 
            strm.LINEARTOFT, 
            strm.LINEARTOM, 
            strm.MAINTEXP, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.PROFITLOSS, 
            strm.RECLNO, 
            strm.RESIDLIFE, 
            strm.RESIDVAL, 
            strm.REVALAMT, 
            strm.ROLLEDBACKFLAG, 
            strm.RWATTRKEY, 
            strm.RWATTRTYPE, 
            strm.TAXVAL, 
            strm.TOBESOLDDATE, 
            strm.TOBESOLDDESC, 
            strm.VALDATE, 
            strm.VARIATION_ID, 
            strm.WRITEDNVAL, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.ASSVALHISTKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALH as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.ASSVALHISTKEY=src.ASSVALHISTKEY) OR (target.ASSVALHISTKEY IS NULL AND src.ASSVALHISTKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ACCDEPREC=src.ACCDEPREC, 
                    target.ACCPERIOD=src.ACCPERIOD, 
                    target.ACQDATE=src.ACQDATE, 
                    target.ACQTYPE=src.ACQTYPE, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ASSVALHISTKEY=src.ASSVALHISTKEY, 
                    target.ASSVALKEY=src.ASSVALKEY, 
                    target.ASSVALRUNKEY=src.ASSVALRUNKEY, 
                    target.BACKDATEADJFLAG=src.BACKDATEADJFLAG, 
                    target.BGTKEY=src.BGTKEY, 
                    target.BGTKEY2=src.BGTKEY2, 
                    target.BGTKEY3=src.BGTKEY3, 
                    target.BGTNO=src.BGTNO, 
                    target.BOOKID=src.BOOKID, 
                    target.CAPTLDATE=src.CAPTLDATE, 
                    target.CAPTLEXP=src.CAPTLEXP, 
                    target.CATEGORY=src.CATEGORY, 
                    target.CLASS=src.CLASS, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COMPTYPE=src.COMPTYPE, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DEPRECRATE=src.DEPRECRATE, 
                    target.DEPRECTYPE=src.DEPRECTYPE, 
                    target.DEPRECYTD=src.DEPRECYTD, 
                    target.DEPRESIDLF=src.DEPRESIDLF, 
                    target.DISJOURNALDATE=src.DISJOURNALDATE, 
                    target.DISPBGTKEY=src.DISPBGTKEY, 
                    target.DISPBGTNO=src.DISPBGTNO, 
                    target.DISPDATE=src.DISPDATE, 
                    target.DISPDESC=src.DISPDESC, 
                    target.DISPVAL=src.DISPVAL, 
                    target.EXPLIFE=src.EXPLIFE, 
                    target.INITCOST=src.INITCOST, 
                    target.INSUREVAL=src.INSUREVAL, 
                    target.LINEARFROMFT=src.LINEARFROMFT, 
                    target.LINEARFROMM=src.LINEARFROMM, 
                    target.LINEARTOFT=src.LINEARTOFT, 
                    target.LINEARTOM=src.LINEARTOM, 
                    target.MAINTEXP=src.MAINTEXP, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.PROFITLOSS=src.PROFITLOSS, 
                    target.RECLNO=src.RECLNO, 
                    target.RESIDLIFE=src.RESIDLIFE, 
                    target.RESIDVAL=src.RESIDVAL, 
                    target.REVALAMT=src.REVALAMT, 
                    target.ROLLEDBACKFLAG=src.ROLLEDBACKFLAG, 
                    target.RWATTRKEY=src.RWATTRKEY, 
                    target.RWATTRTYPE=src.RWATTRTYPE, 
                    target.TAXVAL=src.TAXVAL, 
                    target.TOBESOLDDATE=src.TOBESOLDDATE, 
                    target.TOBESOLDDESC=src.TOBESOLDDESC, 
                    target.VALDATE=src.VALDATE, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WRITEDNVAL=src.WRITEDNVAL, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ACCDEPREC, 
                    ACCPERIOD, 
                    ACQDATE, 
                    ACQTYPE, 
                    ADDBY, 
                    ADDDTTM, 
                    ASSVALHISTKEY, 
                    ASSVALKEY, 
                    ASSVALRUNKEY, 
                    BACKDATEADJFLAG, 
                    BGTKEY, 
                    BGTKEY2, 
                    BGTKEY3, 
                    BGTNO, 
                    BOOKID, 
                    CAPTLDATE, 
                    CAPTLEXP, 
                    CATEGORY, 
                    CLASS, 
                    COMPKEY, 
                    COMPTYPE, 
                    DATALAKE_DELETED, 
                    DEPRECRATE, 
                    DEPRECTYPE, 
                    DEPRECYTD, 
                    DEPRESIDLF, 
                    DISJOURNALDATE, 
                    DISPBGTKEY, 
                    DISPBGTNO, 
                    DISPDATE, 
                    DISPDESC, 
                    DISPVAL, 
                    EXPLIFE, 
                    INITCOST, 
                    INSUREVAL, 
                    LINEARFROMFT, 
                    LINEARFROMM, 
                    LINEARTOFT, 
                    LINEARTOM, 
                    MAINTEXP, 
                    MODBY, 
                    MODDTTM, 
                    PROFITLOSS, 
                    RECLNO, 
                    RESIDLIFE, 
                    RESIDVAL, 
                    REVALAMT, 
                    ROLLEDBACKFLAG, 
                    RWATTRKEY, 
                    RWATTRTYPE, 
                    TAXVAL, 
                    TOBESOLDDATE, 
                    TOBESOLDDESC, 
                    VALDATE, 
                    VARIATION_ID, 
                    WRITEDNVAL, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ACCDEPREC, 
                    src.ACCPERIOD, 
                    src.ACQDATE, 
                    src.ACQTYPE, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ASSVALHISTKEY, 
                    src.ASSVALKEY, 
                    src.ASSVALRUNKEY, 
                    src.BACKDATEADJFLAG, 
                    src.BGTKEY, 
                    src.BGTKEY2, 
                    src.BGTKEY3, 
                    src.BGTNO, 
                    src.BOOKID, 
                    src.CAPTLDATE, 
                    src.CAPTLEXP, 
                    src.CATEGORY, 
                    src.CLASS, 
                    src.COMPKEY, 
                    src.COMPTYPE, 
                    src.DATALAKE_DELETED, 
                    src.DEPRECRATE, 
                    src.DEPRECTYPE, 
                    src.DEPRECYTD, 
                    src.DEPRESIDLF, 
                    src.DISJOURNALDATE, 
                    src.DISPBGTKEY, 
                    src.DISPBGTNO, 
                    src.DISPDATE, 
                    src.DISPDESC, 
                    src.DISPVAL, 
                    src.EXPLIFE, 
                    src.INITCOST, 
                    src.INSUREVAL, 
                    src.LINEARFROMFT, 
                    src.LINEARFROMM, 
                    src.LINEARTOFT, 
                    src.LINEARTOM, 
                    src.MAINTEXP, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.PROFITLOSS, 
                    src.RECLNO, 
                    src.RESIDLIFE, 
                    src.RESIDVAL, 
                    src.REVALAMT, 
                    src.ROLLEDBACKFLAG, 
                    src.RWATTRKEY, 
                    src.RWATTRTYPE, 
                    src.TAXVAL, 
                    src.TOBESOLDDATE, 
                    src.TOBESOLDDESC, 
                    src.VALDATE, 
                    src.VARIATION_ID, 
                    src.WRITEDNVAL,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_ASSETVALUATION_ASSVALH as target using (
                SELECT * FROM (SELECT 
            strm.ACCDEPREC, 
            strm.ACCPERIOD, 
            strm.ACQDATE, 
            strm.ACQTYPE, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ASSVALHISTKEY, 
            strm.ASSVALKEY, 
            strm.ASSVALRUNKEY, 
            strm.BACKDATEADJFLAG, 
            strm.BGTKEY, 
            strm.BGTKEY2, 
            strm.BGTKEY3, 
            strm.BGTNO, 
            strm.BOOKID, 
            strm.CAPTLDATE, 
            strm.CAPTLEXP, 
            strm.CATEGORY, 
            strm.CLASS, 
            strm.COMPKEY, 
            strm.COMPTYPE, 
            strm.DATALAKE_DELETED, 
            strm.DEPRECRATE, 
            strm.DEPRECTYPE, 
            strm.DEPRECYTD, 
            strm.DEPRESIDLF, 
            strm.DISJOURNALDATE, 
            strm.DISPBGTKEY, 
            strm.DISPBGTNO, 
            strm.DISPDATE, 
            strm.DISPDESC, 
            strm.DISPVAL, 
            strm.EXPLIFE, 
            strm.INITCOST, 
            strm.INSUREVAL, 
            strm.LINEARFROMFT, 
            strm.LINEARFROMM, 
            strm.LINEARTOFT, 
            strm.LINEARTOM, 
            strm.MAINTEXP, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.PROFITLOSS, 
            strm.RECLNO, 
            strm.RESIDLIFE, 
            strm.RESIDVAL, 
            strm.REVALAMT, 
            strm.ROLLEDBACKFLAG, 
            strm.RWATTRKEY, 
            strm.RWATTRTYPE, 
            strm.TAXVAL, 
            strm.TOBESOLDDATE, 
            strm.TOBESOLDDESC, 
            strm.VALDATE, 
            strm.VARIATION_ID, 
            strm.WRITEDNVAL, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.ASSVALHISTKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALH as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.ASSVALHISTKEY=src.ASSVALHISTKEY) OR (target.ASSVALHISTKEY IS NULL AND src.ASSVALHISTKEY IS NULL)) 
                when matched then update set
                    target.ACCDEPREC=src.ACCDEPREC, 
                    target.ACCPERIOD=src.ACCPERIOD, 
                    target.ACQDATE=src.ACQDATE, 
                    target.ACQTYPE=src.ACQTYPE, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ASSVALHISTKEY=src.ASSVALHISTKEY, 
                    target.ASSVALKEY=src.ASSVALKEY, 
                    target.ASSVALRUNKEY=src.ASSVALRUNKEY, 
                    target.BACKDATEADJFLAG=src.BACKDATEADJFLAG, 
                    target.BGTKEY=src.BGTKEY, 
                    target.BGTKEY2=src.BGTKEY2, 
                    target.BGTKEY3=src.BGTKEY3, 
                    target.BGTNO=src.BGTNO, 
                    target.BOOKID=src.BOOKID, 
                    target.CAPTLDATE=src.CAPTLDATE, 
                    target.CAPTLEXP=src.CAPTLEXP, 
                    target.CATEGORY=src.CATEGORY, 
                    target.CLASS=src.CLASS, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COMPTYPE=src.COMPTYPE, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DEPRECRATE=src.DEPRECRATE, 
                    target.DEPRECTYPE=src.DEPRECTYPE, 
                    target.DEPRECYTD=src.DEPRECYTD, 
                    target.DEPRESIDLF=src.DEPRESIDLF, 
                    target.DISJOURNALDATE=src.DISJOURNALDATE, 
                    target.DISPBGTKEY=src.DISPBGTKEY, 
                    target.DISPBGTNO=src.DISPBGTNO, 
                    target.DISPDATE=src.DISPDATE, 
                    target.DISPDESC=src.DISPDESC, 
                    target.DISPVAL=src.DISPVAL, 
                    target.EXPLIFE=src.EXPLIFE, 
                    target.INITCOST=src.INITCOST, 
                    target.INSUREVAL=src.INSUREVAL, 
                    target.LINEARFROMFT=src.LINEARFROMFT, 
                    target.LINEARFROMM=src.LINEARFROMM, 
                    target.LINEARTOFT=src.LINEARTOFT, 
                    target.LINEARTOM=src.LINEARTOM, 
                    target.MAINTEXP=src.MAINTEXP, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.PROFITLOSS=src.PROFITLOSS, 
                    target.RECLNO=src.RECLNO, 
                    target.RESIDLIFE=src.RESIDLIFE, 
                    target.RESIDVAL=src.RESIDVAL, 
                    target.REVALAMT=src.REVALAMT, 
                    target.ROLLEDBACKFLAG=src.ROLLEDBACKFLAG, 
                    target.RWATTRKEY=src.RWATTRKEY, 
                    target.RWATTRTYPE=src.RWATTRTYPE, 
                    target.TAXVAL=src.TAXVAL, 
                    target.TOBESOLDDATE=src.TOBESOLDDATE, 
                    target.TOBESOLDDESC=src.TOBESOLDDESC, 
                    target.VALDATE=src.VALDATE, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WRITEDNVAL=src.WRITEDNVAL, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ACCDEPREC, ACCPERIOD, ACQDATE, ACQTYPE, ADDBY, ADDDTTM, ASSVALHISTKEY, ASSVALKEY, ASSVALRUNKEY, BACKDATEADJFLAG, BGTKEY, BGTKEY2, BGTKEY3, BGTNO, BOOKID, CAPTLDATE, CAPTLEXP, CATEGORY, CLASS, COMPKEY, COMPTYPE, DATALAKE_DELETED, DEPRECRATE, DEPRECTYPE, DEPRECYTD, DEPRESIDLF, DISJOURNALDATE, DISPBGTKEY, DISPBGTNO, DISPDATE, DISPDESC, DISPVAL, EXPLIFE, INITCOST, INSUREVAL, LINEARFROMFT, LINEARFROMM, LINEARTOFT, LINEARTOM, MAINTEXP, MODBY, MODDTTM, PROFITLOSS, RECLNO, RESIDLIFE, RESIDVAL, REVALAMT, ROLLEDBACKFLAG, RWATTRKEY, RWATTRTYPE, TAXVAL, TOBESOLDDATE, TOBESOLDDESC, VALDATE, VARIATION_ID, WRITEDNVAL, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ACCDEPREC, 
                    src.ACCPERIOD, 
                    src.ACQDATE, 
                    src.ACQTYPE, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ASSVALHISTKEY, 
                    src.ASSVALKEY, 
                    src.ASSVALRUNKEY, 
                    src.BACKDATEADJFLAG, 
                    src.BGTKEY, 
                    src.BGTKEY2, 
                    src.BGTKEY3, 
                    src.BGTNO, 
                    src.BOOKID, 
                    src.CAPTLDATE, 
                    src.CAPTLEXP, 
                    src.CATEGORY, 
                    src.CLASS, 
                    src.COMPKEY, 
                    src.COMPTYPE, 
                    src.DATALAKE_DELETED, 
                    src.DEPRECRATE, 
                    src.DEPRECTYPE, 
                    src.DEPRECYTD, 
                    src.DEPRESIDLF, 
                    src.DISJOURNALDATE, 
                    src.DISPBGTKEY, 
                    src.DISPBGTNO, 
                    src.DISPDATE, 
                    src.DISPDESC, 
                    src.DISPVAL, 
                    src.EXPLIFE, 
                    src.INITCOST, 
                    src.INSUREVAL, 
                    src.LINEARFROMFT, 
                    src.LINEARFROMM, 
                    src.LINEARTOFT, 
                    src.LINEARTOM, 
                    src.MAINTEXP, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.PROFITLOSS, 
                    src.RECLNO, 
                    src.RESIDLIFE, 
                    src.RESIDVAL, 
                    src.REVALAMT, 
                    src.ROLLEDBACKFLAG, 
                    src.RWATTRKEY, 
                    src.RWATTRTYPE, 
                    src.TAXVAL, 
                    src.TOBESOLDDATE, 
                    src.TOBESOLDDESC, 
                    src.VALDATE, 
                    src.VARIATION_ID, 
                    src.WRITEDNVAL,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;