create or replace procedure DATAHUB_INTEGRATION.SP_IPS_CDR_BUILDING_BLDGAPPL()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_CDR_BUILDING_BLDGAPPL_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_CDR_BUILDING_BLDGAPPL as target using (SELECT * FROM (SELECT 
            strm.ACTLVLTN, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.APBLDGBATCHKEY, 
            strm.APBLDGDEFNKEY, 
            strm.APBLDGKEY, 
            strm.APBLDGPROCESSSTATEKEY, 
            strm.APBY, 
            strm.APDTTM, 
            strm.APKEY, 
            strm.APMODELPROJKEY, 
            strm.APNAME, 
            strm.APNO, 
            strm.BLDGAPPLSTATUS, 
            strm.BLDGAREA, 
            strm.BLDGFLOOR, 
            strm.BLDGROOM, 
            strm.CALCVLTN, 
            strm.CAPACITY, 
            strm.COMPKEY, 
            strm.COOBY, 
            strm.COODTTM, 
            strm.DATALAKE_DELETED, 
            strm.DECLVLTN, 
            strm.EXPDTTM, 
            strm.FINBY, 
            strm.FINDTTM, 
            strm.GROUPKEY, 
            strm.ISSBY, 
            strm.ISSDTTM, 
            strm.LINEARFROMFT, 
            strm.LINEARFROMM, 
            strm.LINEARTOFT, 
            strm.LINEARTOM, 
            strm.LOC, 
            strm.LOCNOTES, 
            strm.LSTACTDTTM, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.NOPAGES, 
            strm.NOPLANS, 
            strm.OCCUPANCYTYPE, 
            strm.PLANREV, 
            strm.PRCLKEY, 
            strm.PRI, 
            strm.PROPERTYCONVEYANCE, 
            strm.PROPERTYCRANEDERRICK, 
            strm.PROPERTYEQUIPMENT, 
            strm.PROPERTYFACADE, 
            strm.PROPERTYMATERIAL, 
            strm.PROPERTYVESSEL, 
            strm.PROPKEY, 
            strm.PROPOCCUPKEY, 
            strm.STAT, 
            strm.TMPCOOBY, 
            strm.TMPCOODTTM, 
            strm.VARIATION_ID, 
            strm.WORKTYPE, 
            strm.XCOORDINATE, 
            strm.YCOORDINATE, 
            strm.ZCOORDINATE, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.APBLDGKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_CDR_BUILDING_BLDGAPPL as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.APBLDGKEY=src.APBLDGKEY) OR (target.APBLDGKEY IS NULL AND src.APBLDGKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ACTLVLTN=src.ACTLVLTN, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.APBLDGBATCHKEY=src.APBLDGBATCHKEY, 
                    target.APBLDGDEFNKEY=src.APBLDGDEFNKEY, 
                    target.APBLDGKEY=src.APBLDGKEY, 
                    target.APBLDGPROCESSSTATEKEY=src.APBLDGPROCESSSTATEKEY, 
                    target.APBY=src.APBY, 
                    target.APDTTM=src.APDTTM, 
                    target.APKEY=src.APKEY, 
                    target.APMODELPROJKEY=src.APMODELPROJKEY, 
                    target.APNAME=src.APNAME, 
                    target.APNO=src.APNO, 
                    target.BLDGAPPLSTATUS=src.BLDGAPPLSTATUS, 
                    target.BLDGAREA=src.BLDGAREA, 
                    target.BLDGFLOOR=src.BLDGFLOOR, 
                    target.BLDGROOM=src.BLDGROOM, 
                    target.CALCVLTN=src.CALCVLTN, 
                    target.CAPACITY=src.CAPACITY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COOBY=src.COOBY, 
                    target.COODTTM=src.COODTTM, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DECLVLTN=src.DECLVLTN, 
                    target.EXPDTTM=src.EXPDTTM, 
                    target.FINBY=src.FINBY, 
                    target.FINDTTM=src.FINDTTM, 
                    target.GROUPKEY=src.GROUPKEY, 
                    target.ISSBY=src.ISSBY, 
                    target.ISSDTTM=src.ISSDTTM, 
                    target.LINEARFROMFT=src.LINEARFROMFT, 
                    target.LINEARFROMM=src.LINEARFROMM, 
                    target.LINEARTOFT=src.LINEARTOFT, 
                    target.LINEARTOM=src.LINEARTOM, 
                    target.LOC=src.LOC, 
                    target.LOCNOTES=src.LOCNOTES, 
                    target.LSTACTDTTM=src.LSTACTDTTM, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.NOPAGES=src.NOPAGES, 
                    target.NOPLANS=src.NOPLANS, 
                    target.OCCUPANCYTYPE=src.OCCUPANCYTYPE, 
                    target.PLANREV=src.PLANREV, 
                    target.PRCLKEY=src.PRCLKEY, 
                    target.PRI=src.PRI, 
                    target.PROPERTYCONVEYANCE=src.PROPERTYCONVEYANCE, 
                    target.PROPERTYCRANEDERRICK=src.PROPERTYCRANEDERRICK, 
                    target.PROPERTYEQUIPMENT=src.PROPERTYEQUIPMENT, 
                    target.PROPERTYFACADE=src.PROPERTYFACADE, 
                    target.PROPERTYMATERIAL=src.PROPERTYMATERIAL, 
                    target.PROPERTYVESSEL=src.PROPERTYVESSEL, 
                    target.PROPKEY=src.PROPKEY, 
                    target.PROPOCCUPKEY=src.PROPOCCUPKEY, 
                    target.STAT=src.STAT, 
                    target.TMPCOOBY=src.TMPCOOBY, 
                    target.TMPCOODTTM=src.TMPCOODTTM, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WORKTYPE=src.WORKTYPE, 
                    target.XCOORDINATE=src.XCOORDINATE, 
                    target.YCOORDINATE=src.YCOORDINATE, 
                    target.ZCOORDINATE=src.ZCOORDINATE, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ACTLVLTN, 
                    ADDBY, 
                    ADDDTTM, 
                    ADDRKEY, 
                    APBLDGBATCHKEY, 
                    APBLDGDEFNKEY, 
                    APBLDGKEY, 
                    APBLDGPROCESSSTATEKEY, 
                    APBY, 
                    APDTTM, 
                    APKEY, 
                    APMODELPROJKEY, 
                    APNAME, 
                    APNO, 
                    BLDGAPPLSTATUS, 
                    BLDGAREA, 
                    BLDGFLOOR, 
                    BLDGROOM, 
                    CALCVLTN, 
                    CAPACITY, 
                    COMPKEY, 
                    COOBY, 
                    COODTTM, 
                    DATALAKE_DELETED, 
                    DECLVLTN, 
                    EXPDTTM, 
                    FINBY, 
                    FINDTTM, 
                    GROUPKEY, 
                    ISSBY, 
                    ISSDTTM, 
                    LINEARFROMFT, 
                    LINEARFROMM, 
                    LINEARTOFT, 
                    LINEARTOM, 
                    LOC, 
                    LOCNOTES, 
                    LSTACTDTTM, 
                    MODBY, 
                    MODDTTM, 
                    NOPAGES, 
                    NOPLANS, 
                    OCCUPANCYTYPE, 
                    PLANREV, 
                    PRCLKEY, 
                    PRI, 
                    PROPERTYCONVEYANCE, 
                    PROPERTYCRANEDERRICK, 
                    PROPERTYEQUIPMENT, 
                    PROPERTYFACADE, 
                    PROPERTYMATERIAL, 
                    PROPERTYVESSEL, 
                    PROPKEY, 
                    PROPOCCUPKEY, 
                    STAT, 
                    TMPCOOBY, 
                    TMPCOODTTM, 
                    VARIATION_ID, 
                    WORKTYPE, 
                    XCOORDINATE, 
                    YCOORDINATE, 
                    ZCOORDINATE, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ACTLVLTN, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.APBLDGBATCHKEY, 
                    src.APBLDGDEFNKEY, 
                    src.APBLDGKEY, 
                    src.APBLDGPROCESSSTATEKEY, 
                    src.APBY, 
                    src.APDTTM, 
                    src.APKEY, 
                    src.APMODELPROJKEY, 
                    src.APNAME, 
                    src.APNO, 
                    src.BLDGAPPLSTATUS, 
                    src.BLDGAREA, 
                    src.BLDGFLOOR, 
                    src.BLDGROOM, 
                    src.CALCVLTN, 
                    src.CAPACITY, 
                    src.COMPKEY, 
                    src.COOBY, 
                    src.COODTTM, 
                    src.DATALAKE_DELETED, 
                    src.DECLVLTN, 
                    src.EXPDTTM, 
                    src.FINBY, 
                    src.FINDTTM, 
                    src.GROUPKEY, 
                    src.ISSBY, 
                    src.ISSDTTM, 
                    src.LINEARFROMFT, 
                    src.LINEARFROMM, 
                    src.LINEARTOFT, 
                    src.LINEARTOM, 
                    src.LOC, 
                    src.LOCNOTES, 
                    src.LSTACTDTTM, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.NOPAGES, 
                    src.NOPLANS, 
                    src.OCCUPANCYTYPE, 
                    src.PLANREV, 
                    src.PRCLKEY, 
                    src.PRI, 
                    src.PROPERTYCONVEYANCE, 
                    src.PROPERTYCRANEDERRICK, 
                    src.PROPERTYEQUIPMENT, 
                    src.PROPERTYFACADE, 
                    src.PROPERTYMATERIAL, 
                    src.PROPERTYVESSEL, 
                    src.PROPKEY, 
                    src.PROPOCCUPKEY, 
                    src.STAT, 
                    src.TMPCOOBY, 
                    src.TMPCOODTTM, 
                    src.VARIATION_ID, 
                    src.WORKTYPE, 
                    src.XCOORDINATE, 
                    src.YCOORDINATE, 
                    src.ZCOORDINATE,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_BUILDING_BLDGAPPL as target using (
                SELECT * FROM (SELECT 
            strm.ACTLVLTN, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.APBLDGBATCHKEY, 
            strm.APBLDGDEFNKEY, 
            strm.APBLDGKEY, 
            strm.APBLDGPROCESSSTATEKEY, 
            strm.APBY, 
            strm.APDTTM, 
            strm.APKEY, 
            strm.APMODELPROJKEY, 
            strm.APNAME, 
            strm.APNO, 
            strm.BLDGAPPLSTATUS, 
            strm.BLDGAREA, 
            strm.BLDGFLOOR, 
            strm.BLDGROOM, 
            strm.CALCVLTN, 
            strm.CAPACITY, 
            strm.COMPKEY, 
            strm.COOBY, 
            strm.COODTTM, 
            strm.DATALAKE_DELETED, 
            strm.DECLVLTN, 
            strm.EXPDTTM, 
            strm.FINBY, 
            strm.FINDTTM, 
            strm.GROUPKEY, 
            strm.ISSBY, 
            strm.ISSDTTM, 
            strm.LINEARFROMFT, 
            strm.LINEARFROMM, 
            strm.LINEARTOFT, 
            strm.LINEARTOM, 
            strm.LOC, 
            strm.LOCNOTES, 
            strm.LSTACTDTTM, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.NOPAGES, 
            strm.NOPLANS, 
            strm.OCCUPANCYTYPE, 
            strm.PLANREV, 
            strm.PRCLKEY, 
            strm.PRI, 
            strm.PROPERTYCONVEYANCE, 
            strm.PROPERTYCRANEDERRICK, 
            strm.PROPERTYEQUIPMENT, 
            strm.PROPERTYFACADE, 
            strm.PROPERTYMATERIAL, 
            strm.PROPERTYVESSEL, 
            strm.PROPKEY, 
            strm.PROPOCCUPKEY, 
            strm.STAT, 
            strm.TMPCOOBY, 
            strm.TMPCOODTTM, 
            strm.VARIATION_ID, 
            strm.WORKTYPE, 
            strm.XCOORDINATE, 
            strm.YCOORDINATE, 
            strm.ZCOORDINATE, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.APBLDGKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_CDR_BUILDING_BLDGAPPL as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.APBLDGKEY=src.APBLDGKEY) OR (target.APBLDGKEY IS NULL AND src.APBLDGKEY IS NULL)) 
                when matched then update set
                    target.ACTLVLTN=src.ACTLVLTN, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.APBLDGBATCHKEY=src.APBLDGBATCHKEY, 
                    target.APBLDGDEFNKEY=src.APBLDGDEFNKEY, 
                    target.APBLDGKEY=src.APBLDGKEY, 
                    target.APBLDGPROCESSSTATEKEY=src.APBLDGPROCESSSTATEKEY, 
                    target.APBY=src.APBY, 
                    target.APDTTM=src.APDTTM, 
                    target.APKEY=src.APKEY, 
                    target.APMODELPROJKEY=src.APMODELPROJKEY, 
                    target.APNAME=src.APNAME, 
                    target.APNO=src.APNO, 
                    target.BLDGAPPLSTATUS=src.BLDGAPPLSTATUS, 
                    target.BLDGAREA=src.BLDGAREA, 
                    target.BLDGFLOOR=src.BLDGFLOOR, 
                    target.BLDGROOM=src.BLDGROOM, 
                    target.CALCVLTN=src.CALCVLTN, 
                    target.CAPACITY=src.CAPACITY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COOBY=src.COOBY, 
                    target.COODTTM=src.COODTTM, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DECLVLTN=src.DECLVLTN, 
                    target.EXPDTTM=src.EXPDTTM, 
                    target.FINBY=src.FINBY, 
                    target.FINDTTM=src.FINDTTM, 
                    target.GROUPKEY=src.GROUPKEY, 
                    target.ISSBY=src.ISSBY, 
                    target.ISSDTTM=src.ISSDTTM, 
                    target.LINEARFROMFT=src.LINEARFROMFT, 
                    target.LINEARFROMM=src.LINEARFROMM, 
                    target.LINEARTOFT=src.LINEARTOFT, 
                    target.LINEARTOM=src.LINEARTOM, 
                    target.LOC=src.LOC, 
                    target.LOCNOTES=src.LOCNOTES, 
                    target.LSTACTDTTM=src.LSTACTDTTM, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.NOPAGES=src.NOPAGES, 
                    target.NOPLANS=src.NOPLANS, 
                    target.OCCUPANCYTYPE=src.OCCUPANCYTYPE, 
                    target.PLANREV=src.PLANREV, 
                    target.PRCLKEY=src.PRCLKEY, 
                    target.PRI=src.PRI, 
                    target.PROPERTYCONVEYANCE=src.PROPERTYCONVEYANCE, 
                    target.PROPERTYCRANEDERRICK=src.PROPERTYCRANEDERRICK, 
                    target.PROPERTYEQUIPMENT=src.PROPERTYEQUIPMENT, 
                    target.PROPERTYFACADE=src.PROPERTYFACADE, 
                    target.PROPERTYMATERIAL=src.PROPERTYMATERIAL, 
                    target.PROPERTYVESSEL=src.PROPERTYVESSEL, 
                    target.PROPKEY=src.PROPKEY, 
                    target.PROPOCCUPKEY=src.PROPOCCUPKEY, 
                    target.STAT=src.STAT, 
                    target.TMPCOOBY=src.TMPCOOBY, 
                    target.TMPCOODTTM=src.TMPCOODTTM, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WORKTYPE=src.WORKTYPE, 
                    target.XCOORDINATE=src.XCOORDINATE, 
                    target.YCOORDINATE=src.YCOORDINATE, 
                    target.ZCOORDINATE=src.ZCOORDINATE, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ACTLVLTN, ADDBY, ADDDTTM, ADDRKEY, APBLDGBATCHKEY, APBLDGDEFNKEY, APBLDGKEY, APBLDGPROCESSSTATEKEY, APBY, APDTTM, APKEY, APMODELPROJKEY, APNAME, APNO, BLDGAPPLSTATUS, BLDGAREA, BLDGFLOOR, BLDGROOM, CALCVLTN, CAPACITY, COMPKEY, COOBY, COODTTM, DATALAKE_DELETED, DECLVLTN, EXPDTTM, FINBY, FINDTTM, GROUPKEY, ISSBY, ISSDTTM, LINEARFROMFT, LINEARFROMM, LINEARTOFT, LINEARTOM, LOC, LOCNOTES, LSTACTDTTM, MODBY, MODDTTM, NOPAGES, NOPLANS, OCCUPANCYTYPE, PLANREV, PRCLKEY, PRI, PROPERTYCONVEYANCE, PROPERTYCRANEDERRICK, PROPERTYEQUIPMENT, PROPERTYFACADE, PROPERTYMATERIAL, PROPERTYVESSEL, PROPKEY, PROPOCCUPKEY, STAT, TMPCOOBY, TMPCOODTTM, VARIATION_ID, WORKTYPE, XCOORDINATE, YCOORDINATE, ZCOORDINATE, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ACTLVLTN, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.APBLDGBATCHKEY, 
                    src.APBLDGDEFNKEY, 
                    src.APBLDGKEY, 
                    src.APBLDGPROCESSSTATEKEY, 
                    src.APBY, 
                    src.APDTTM, 
                    src.APKEY, 
                    src.APMODELPROJKEY, 
                    src.APNAME, 
                    src.APNO, 
                    src.BLDGAPPLSTATUS, 
                    src.BLDGAREA, 
                    src.BLDGFLOOR, 
                    src.BLDGROOM, 
                    src.CALCVLTN, 
                    src.CAPACITY, 
                    src.COMPKEY, 
                    src.COOBY, 
                    src.COODTTM, 
                    src.DATALAKE_DELETED, 
                    src.DECLVLTN, 
                    src.EXPDTTM, 
                    src.FINBY, 
                    src.FINDTTM, 
                    src.GROUPKEY, 
                    src.ISSBY, 
                    src.ISSDTTM, 
                    src.LINEARFROMFT, 
                    src.LINEARFROMM, 
                    src.LINEARTOFT, 
                    src.LINEARTOM, 
                    src.LOC, 
                    src.LOCNOTES, 
                    src.LSTACTDTTM, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.NOPAGES, 
                    src.NOPLANS, 
                    src.OCCUPANCYTYPE, 
                    src.PLANREV, 
                    src.PRCLKEY, 
                    src.PRI, 
                    src.PROPERTYCONVEYANCE, 
                    src.PROPERTYCRANEDERRICK, 
                    src.PROPERTYEQUIPMENT, 
                    src.PROPERTYFACADE, 
                    src.PROPERTYMATERIAL, 
                    src.PROPERTYVESSEL, 
                    src.PROPKEY, 
                    src.PROPOCCUPKEY, 
                    src.STAT, 
                    src.TMPCOOBY, 
                    src.TMPCOODTTM, 
                    src.VARIATION_ID, 
                    src.WORKTYPE, 
                    src.XCOORDINATE, 
                    src.YCOORDINATE, 
                    src.ZCOORDINATE,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;