{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN qmpqm204 Additional Components Failure and Action Details table, Generated 2022-06-15T01:21:04Z from package combination ce01055',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['frac'], type='varchar', alias='frac') }},
        {{ trx_json_extract('src', ['fpon'], type='int', alias='fpon') }},
        {{ trx_json_extract('src', ['acsq'], type='int', alias='acsq') }},
        {{ trx_json_extract('src', ['mlin'], type='int', alias='mlin') }},
        {{ trx_json_extract('src', ['mlin_kw'], type='varchar', alias='mlin_kw') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['cser'], type='varchar', alias='cser') }},
        {{ trx_json_extract('src', ['clot'], type='varchar', alias='clot') }},
        {{ trx_json_extract('src', ['idat'], type='timestamp_ntz', alias='idat') }},
        {{ trx_json_extract('src', ['qnty'], type='float', alias='qnty') }},
        {{ trx_json_extract('src', ['fqua'], type='varchar', alias='fqua') }},
        {{ trx_json_extract('src', ['aitm'], type='varchar', alias='aitm') }},
        {{ trx_json_extract('src', ['acsr'], type='varchar', alias='acsr') }},
        {{ trx_json_extract('src', ['alot'], type='varchar', alias='alot') }},
        {{ trx_json_extract('src', ['aqty'], type='float', alias='aqty') }},
        {{ trx_json_extract('src', ['nlot'], type='varchar', alias='nlot') }},
        {{ trx_json_extract('src', ['aqua'], type='varchar', alias='aqua') }},
        {{ trx_json_extract('src', ['frcd'], type='varchar', alias='frcd') }},
        {{ trx_json_extract('src', ['rfdg'], type='varchar', alias='rfdg') }},
        {{ trx_json_extract('src', ['rptd'], type='int', alias='rptd') }},
        {{ trx_json_extract('src', ['rptd_kw'], type='varchar', alias='rptd_kw') }},
        {{ trx_json_extract('src', ['bdfx'], type='int', alias='bdfx') }},
        {{ trx_json_extract('src', ['bdfx_kw'], type='varchar', alias='bdfx_kw') }},
        {{ trx_json_extract('src', ['frct'], type='varchar', alias='frct') }},
        {{ trx_json_extract('src', ['frst'], type='varchar', alias='frst') }},
        {{ trx_json_extract('src', ['frpt'], type='varchar', alias='frpt') }},
        {{ trx_json_extract('src', ['disa'], type='int', alias='disa') }},
        {{ trx_json_extract('src', ['disa_kw'], type='varchar', alias='disa_kw') }},
        {{ trx_json_extract('src', ['disc'], type='varchar', alias='disc') }},
        {{ trx_json_extract('src', ['disp'], type='int', alias='disp') }},
        {{ trx_json_extract('src', ['disp_kw'], type='varchar', alias='disp_kw') }},
        {{ trx_json_extract('src', ['fcrc'], type='varchar', alias='fcrc') }},
        {{ trx_json_extract('src', ['disr'], type='varchar', alias='disr') }},
        {{ trx_json_extract('src', ['rsbp'], type='varchar', alias='rsbp') }},
        {{ trx_json_extract('src', ['titm'], type='varchar', alias='titm') }},
        {{ trx_json_extract('src', ['racd'], type='varchar', alias='racd') }},
        {{ trx_json_extract('src', ['rpdt'], type='timestamp_ntz', alias='rpdt') }},
        {{ trx_json_extract('src', ['ritm'], type='varchar', alias='ritm') }},
        {{ trx_json_extract('src', ['rcsr'], type='varchar', alias='rcsr') }},
        {{ trx_json_extract('src', ['rlot'], type='varchar', alias='rlot') }},
        {{ trx_json_extract('src', ['rqty'], type='float', alias='rqty') }},
        {{ trx_json_extract('src', ['rqua'], type='varchar', alias='rqua') }},
        {{ trx_json_extract('src', ['dorg'], type='int', alias='dorg') }},
        {{ trx_json_extract('src', ['dorg_kw'], type='varchar', alias='dorg_kw') }},
        {{ trx_json_extract('src', ['dior'], type='varchar', alias='dior') }},
        {{ trx_json_extract('src', ['diln'], type='int', alias='diln') }},
        {{ trx_json_extract('src', ['chfr'], type='varchar', alias='chfr') }},
        {{ trx_json_extract('src', ['stat'], type='int', alias='stat') }},
        {{ trx_json_extract('src', ['stat_kw'], type='varchar', alias='stat_kw') }},
        {{ trx_json_extract('src', ['oimg'], type='varchar', alias='oimg') }},
        {{ trx_json_extract('src', ['nimg'], type='varchar', alias='nimg') }},
        {{ trx_json_extract('src', ['ftxt'], type='int', alias='ftxt') }},
        {{ trx_json_extract('src', ['rtxt'], type='int', alias='rtxt') }},
        {{ trx_json_extract('src', ['adtx'], type='int', alias='adtx') }},
        {{ trx_json_extract('src', ['frac_fpon_ref_compnr'], type='int', alias='frac_fpon_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['fqua_ref_compnr'], type='int', alias='fqua_ref_compnr') }},
        {{ trx_json_extract('src', ['aitm_ref_compnr'], type='int', alias='aitm_ref_compnr') }},
        {{ trx_json_extract('src', ['aqua_ref_compnr'], type='int', alias='aqua_ref_compnr') }},
        {{ trx_json_extract('src', ['frcd_ref_compnr'], type='int', alias='frcd_ref_compnr') }},
        {{ trx_json_extract('src', ['rfdg_ref_compnr'], type='int', alias='rfdg_ref_compnr') }},
        {{ trx_json_extract('src', ['frct_ref_compnr'], type='int', alias='frct_ref_compnr') }},
        {{ trx_json_extract('src', ['frst_ref_compnr'], type='int', alias='frst_ref_compnr') }},
        {{ trx_json_extract('src', ['disc_ref_compnr'], type='int', alias='disc_ref_compnr') }},
        {{ trx_json_extract('src', ['fcrc_ref_compnr'], type='int', alias='fcrc_ref_compnr') }},
        {{ trx_json_extract('src', ['disr_ref_compnr'], type='int', alias='disr_ref_compnr') }},
        {{ trx_json_extract('src', ['rsbp_ref_compnr'], type='int', alias='rsbp_ref_compnr') }},
        {{ trx_json_extract('src', ['titm_ref_compnr'], type='int', alias='titm_ref_compnr') }},
        {{ trx_json_extract('src', ['racd_ref_compnr'], type='int', alias='racd_ref_compnr') }},
        {{ trx_json_extract('src', ['ritm_ref_compnr'], type='int', alias='ritm_ref_compnr') }},
        {{ trx_json_extract('src', ['rqua_ref_compnr'], type='int', alias='rqua_ref_compnr') }},
        {{ trx_json_extract('src', ['ftxt_ref_compnr'], type='int', alias='ftxt_ref_compnr') }},
        {{ trx_json_extract('src', ['rtxt_ref_compnr'], type='int', alias='rtxt_ref_compnr') }},
        {{ trx_json_extract('src', ['adtx_ref_compnr'], type='int', alias='adtx_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_qmpqm204') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'frac', 'fpon', 'acsq']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
