{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN qmptc100 Inspection Orders table, Generated 2022-06-15T01:21:05Z from package combination ce01055',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['iorn'], type='varchar', alias='iorn') }},
        {{ trx_json_extract('src', ['orgn'], type='int', alias='orgn') }},
        {{ trx_json_extract('src', ['orgn_kw'], type='varchar', alias='orgn_kw') }},
        {{ trx_json_extract('src', ['orno'], type='varchar', alias='orno') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['opno'], type='int', alias='opno') }},
        {{ trx_json_extract('src', ['wstt'], type='varchar', alias='wstt') }},
        {{ trx_json_extract('src', ['seqn'], type='int', alias='seqn') }},
        {{ trx_json_extract('src', ['apno'], type='varchar', alias='apno') }},
        {{ trx_json_extract('src', ['apsq'], type='int', alias='apsq') }},
        {{ trx_json_extract('src', ['huid'], type='varchar', alias='huid') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['loca'], type='varchar', alias='loca') }},
        {{ trx_json_extract('src', ['clot'], type='varchar', alias='clot') }},
        {{ trx_json_extract('src', ['date'], type='timestamp_ntz', alias='date') }},
        {{ trx_json_extract('src', ['effn'], type='int', alias='effn') }},
        {{ trx_json_extract('src', ['revi'], type='varchar', alias='revi') }},
        {{ trx_json_extract('src', ['quid'], type='varchar', alias='quid') }},
        {{ trx_json_extract('src', ['vrsn'], type='int', alias='vrsn') }},
        {{ trx_json_extract('src', ['tstg'], type='int', alias='tstg') }},
        {{ trx_json_extract('src', ['tsty'], type='int', alias='tsty') }},
        {{ trx_json_extract('src', ['tsty_kw'], type='varchar', alias='tsty_kw') }},
        {{ trx_json_extract('src', ['freq'], type='float', alias='freq') }},
        {{ trx_json_extract('src', ['cufr'], type='varchar', alias='cufr') }},
        {{ trx_json_extract('src', ['psms'], type='float', alias='psms') }},
        {{ trx_json_extract('src', ['sams'], type='float', alias='sams') }},
        {{ trx_json_extract('src', ['cuss'], type='varchar', alias='cuss') }},
        {{ trx_json_extract('src', ['aqls'], type='int', alias='aqls') }},
        {{ trx_json_extract('src', ['aqls_kw'], type='varchar', alias='aqls_kw') }},
        {{ trx_json_extract('src', ['aqll'], type='float', alias='aqll') }},
        {{ trx_json_extract('src', ['qacc'], type='int', alias='qacc') }},
        {{ trx_json_extract('src', ['qrej'], type='int', alias='qrej') }},
        {{ trx_json_extract('src', ['craq'], type='float', alias='craq') }},
        {{ trx_json_extract('src', ['crac'], type='int', alias='crac') }},
        {{ trx_json_extract('src', ['crrj'], type='int', alias='crrj') }},
        {{ trx_json_extract('src', ['mcaq'], type='float', alias='mcaq') }},
        {{ trx_json_extract('src', ['mcac'], type='int', alias='mcac') }},
        {{ trx_json_extract('src', ['mcrj'], type='int', alias='mcrj') }},
        {{ trx_json_extract('src', ['miaq'], type='float', alias='miaq') }},
        {{ trx_json_extract('src', ['miac'], type='int', alias='miac') }},
        {{ trx_json_extract('src', ['mirj'], type='int', alias='mirj') }},
        {{ trx_json_extract('src', ['saru'], type='varchar', alias='saru') }},
        {{ trx_json_extract('src', ['inss'], type='varchar', alias='inss') }},
        {{ trx_json_extract('src', ['inse'], type='int', alias='inse') }},
        {{ trx_json_extract('src', ['inse_kw'], type='varchar', alias='inse_kw') }},
        {{ trx_json_extract('src', ['ilvl'], type='varchar', alias='ilvl') }},
        {{ trx_json_extract('src', ['sapl'], type='varchar', alias='sapl') }},
        {{ trx_json_extract('src', ['noit'], type='int', alias='noit') }},
        {{ trx_json_extract('src', ['iter'], type='int', alias='iter') }},
        {{ trx_json_extract('src', ['bpid'], type='varchar', alias='bpid') }},
        {{ trx_json_extract('src', ['sklo'], type='int', alias='sklo') }},
        {{ trx_json_extract('src', ['sklo_kw'], type='varchar', alias='sklo_kw') }},
        {{ trx_json_extract('src', ['qtst'], type='float', alias='qtst') }},
        {{ trx_json_extract('src', ['tuni'], type='varchar', alias='tuni') }},
        {{ trx_json_extract('src', ['cvss'], type='float', alias='cvss') }},
        {{ trx_json_extract('src', ['odat'], type='timestamp_ntz', alias='odat') }},
        {{ trx_json_extract('src', ['cdat'], type='timestamp_ntz', alias='cdat') }},
        {{ trx_json_extract('src', ['reio'], type='varchar', alias='reio') }},
        {{ trx_json_extract('src', ['orio'], type='varchar', alias='orio') }},
        {{ trx_json_extract('src', ['ostp'], type='int', alias='ostp') }},
        {{ trx_json_extract('src', ['ostp_kw'], type='varchar', alias='ostp_kw') }},
        {{ trx_json_extract('src', ['pper'], type='float', alias='pper') }},
        {{ trx_json_extract('src', ['acre'], type='int', alias='acre') }},
        {{ trx_json_extract('src', ['acre_kw'], type='varchar', alias='acre_kw') }},
        {{ trx_json_extract('src', ['conr'], type='int', alias='conr') }},
        {{ trx_json_extract('src', ['conr_kw'], type='varchar', alias='conr_kw') }},
        {{ trx_json_extract('src', ['cncd'], type='varchar', alias='cncd') }},
        {{ trx_json_extract('src', ['team'], type='varchar', alias='team') }},
        {{ trx_json_extract('src', ['cwoc'], type='varchar', alias='cwoc') }},
        {{ trx_json_extract('src', ['ownr'], type='varchar', alias='ownr') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['effn_ref_compnr'], type='int', alias='effn_ref_compnr') }},
        {{ trx_json_extract('src', ['quid_vrsn_ref_compnr'], type='int', alias='quid_vrsn_ref_compnr') }},
        {{ trx_json_extract('src', ['cufr_ref_compnr'], type='int', alias='cufr_ref_compnr') }},
        {{ trx_json_extract('src', ['cuss_ref_compnr'], type='int', alias='cuss_ref_compnr') }},
        {{ trx_json_extract('src', ['saru_ref_compnr'], type='int', alias='saru_ref_compnr') }},
        {{ trx_json_extract('src', ['inss_ref_compnr'], type='int', alias='inss_ref_compnr') }},
        {{ trx_json_extract('src', ['ilvl_ref_compnr'], type='int', alias='ilvl_ref_compnr') }},
        {{ trx_json_extract('src', ['sapl_ref_compnr'], type='int', alias='sapl_ref_compnr') }},
        {{ trx_json_extract('src', ['bpid_ref_compnr'], type='int', alias='bpid_ref_compnr') }},
        {{ trx_json_extract('src', ['tuni_ref_compnr'], type='int', alias='tuni_ref_compnr') }},
        {{ trx_json_extract('src', ['reio_ref_compnr'], type='int', alias='reio_ref_compnr') }},
        {{ trx_json_extract('src', ['orio_ref_compnr'], type='int', alias='orio_ref_compnr') }},
        {{ trx_json_extract('src', ['cncd_ref_compnr'], type='int', alias='cncd_ref_compnr') }},
        {{ trx_json_extract('src', ['team_ref_compnr'], type='int', alias='team_ref_compnr') }},
        {{ trx_json_extract('src', ['cwoc_ref_compnr'], type='int', alias='cwoc_ref_compnr') }},
        {{ trx_json_extract('src', ['ownr_ref_compnr'], type='int', alias='ownr_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_qmptc100') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'iorn']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
