{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tccom100 Business Partners table, Generated 2026-04-10T19:41:00Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['bpid'], type='varchar', alias='bpid') }},
        {{ trx_json_extract('src', ['ctit'], type='varchar', alias='ctit') }},
        {{ trx_json_extract('src', ['nama', 'en_US'], type='varchar', alias='nama__en_us') }},
        {{ trx_json_extract('src', ['seak', 'en_US'], type='varchar', alias='seak__en_us') }},
        {{ trx_json_extract('src', ['prbp'], type='varchar', alias='prbp') }},
        {{ trx_json_extract('src', ['prst'], type='int', alias='prst') }},
        {{ trx_json_extract('src', ['prst_kw'], type='varchar', alias='prst_kw') }},
        {{ trx_json_extract('src', ['stdt'], type='timestamp_ntz', alias='stdt') }},
        {{ trx_json_extract('src', ['endt'], type='timestamp_ntz', alias='endt') }},
        {{ trx_json_extract('src', ['clan'], type='varchar', alias='clan') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['sndr'], type='int', alias='sndr') }},
        {{ trx_json_extract('src', ['sndr_kw'], type='varchar', alias='sndr_kw') }},
        {{ trx_json_extract('src', ['edyn'], type='int', alias='edyn') }},
        {{ trx_json_extract('src', ['edyn_kw'], type='varchar', alias='edyn_kw') }},
        {{ trx_json_extract('src', ['fovn'], type='varchar', alias='fovn') }},
        {{ trx_json_extract('src', ['lvdt'], type='timestamp_ntz', alias='lvdt') }},
        {{ trx_json_extract('src', ['inrl'], type='int', alias='inrl') }},
        {{ trx_json_extract('src', ['inrl_kw'], type='varchar', alias='inrl_kw') }},
        {{ trx_json_extract('src', ['iscn'], type='int', alias='iscn') }},
        {{ trx_json_extract('src', ['lgid', 'en_US'], type='varchar', alias='lgid__en_us') }},
        {{ trx_json_extract('src', ['cmid', 'en_US'], type='varchar', alias='cmid__en_us') }},
        {{ trx_json_extract('src', ['bptx'], type='varchar', alias='bptx') }},
        {{ trx_json_extract('src', ['cadr'], type='varchar', alias='cadr') }},
        {{ trx_json_extract('src', ['telp'], type='varchar', alias='telp') }},
        {{ trx_json_extract('src', ['tlcy'], type='varchar', alias='tlcy') }},
        {{ trx_json_extract('src', ['tlci'], type='varchar', alias='tlci') }},
        {{ trx_json_extract('src', ['tlln'], type='varchar', alias='tlln') }},
        {{ trx_json_extract('src', ['tlex'], type='varchar', alias='tlex') }},
        {{ trx_json_extract('src', ['tefx'], type='varchar', alias='tefx') }},
        {{ trx_json_extract('src', ['tfcy'], type='varchar', alias='tfcy') }},
        {{ trx_json_extract('src', ['tfci'], type='varchar', alias='tfci') }},
        {{ trx_json_extract('src', ['tfln'], type='varchar', alias='tfln') }},
        {{ trx_json_extract('src', ['tfex'], type='varchar', alias='tfex') }},
        {{ trx_json_extract('src', ['ccnt'], type='varchar', alias='ccnt') }},
        {{ trx_json_extract('src', ['cint'], type='int', alias='cint') }},
        {{ trx_json_extract('src', ['cint_kw'], type='varchar', alias='cint_kw') }},
        {{ trx_json_extract('src', ['foid'], type='int', alias='foid') }},
        {{ trx_json_extract('src', ['crid'], type='int', alias='crid') }},
        {{ trx_json_extract('src', ['icst'], type='int', alias='icst') }},
        {{ trx_json_extract('src', ['icst_kw'], type='varchar', alias='icst_kw') }},
        {{ trx_json_extract('src', ['icod'], type='int', alias='icod') }},
        {{ trx_json_extract('src', ['icod_kw'], type='varchar', alias='icod_kw') }},
        {{ trx_json_extract('src', ['fact'], type='int', alias='fact') }},
        {{ trx_json_extract('src', ['fact_kw'], type='varchar', alias='fact_kw') }},
        {{ trx_json_extract('src', ['ecmp'], type='int', alias='ecmp') }},
        {{ trx_json_extract('src', ['coff'], type='int', alias='coff') }},
        {{ trx_json_extract('src', ['coff_kw'], type='varchar', alias='coff_kw') }},
        {{ trx_json_extract('src', ['csto'], type='int', alias='csto') }},
        {{ trx_json_extract('src', ['csto_kw'], type='varchar', alias='csto_kw') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['lmdt'], type='timestamp_ntz', alias='lmdt') }},
        {{ trx_json_extract('src', ['lmus'], type='varchar', alias='lmus') }},
        {{ trx_json_extract('src', ['bprl'], type='int', alias='bprl') }},
        {{ trx_json_extract('src', ['bprl_kw'], type='varchar', alias='bprl_kw') }},
        {{ trx_json_extract('src', ['btbv'], type='int', alias='btbv') }},
        {{ trx_json_extract('src', ['btbv_kw'], type='varchar', alias='btbv_kw') }},
        {{ trx_json_extract('src', ['usid'], type='varchar', alias='usid') }},
        {{ trx_json_extract('src', ['clcd'], type='int', alias='clcd') }},
        {{ trx_json_extract('src', ['clcd_kw'], type='varchar', alias='clcd_kw') }},
        {{ trx_json_extract('src', ['cbcl'], type='varchar', alias='cbcl') }},
        {{ trx_json_extract('src', ['beid', 'en_US'], type='varchar', alias='beid__en_us') }},
        {{ trx_json_extract('src', ['inet', 'en_US'], type='varchar', alias='inet__en_us') }},
        {{ trx_json_extract('src', ['imag'], type='varchar', alias='imag') }},
        {{ trx_json_extract('src', ['smt1'], type='int', alias='smt1') }},
        {{ trx_json_extract('src', ['smt1_kw'], type='varchar', alias='smt1_kw') }},
        {{ trx_json_extract('src', ['sml1', 'en_US'], type='varchar', alias='sml1__en_us') }},
        {{ trx_json_extract('src', ['smt2'], type='int', alias='smt2') }},
        {{ trx_json_extract('src', ['smt2_kw'], type='varchar', alias='smt2_kw') }},
        {{ trx_json_extract('src', ['sml2', 'en_US'], type='varchar', alias='sml2__en_us') }},
        {{ trx_json_extract('src', ['smt3'], type='int', alias='smt3') }},
        {{ trx_json_extract('src', ['smt3_kw'], type='varchar', alias='smt3_kw') }},
        {{ trx_json_extract('src', ['sml3', 'en_US'], type='varchar', alias='sml3__en_us') }},
        {{ trx_json_extract('src', ['smt4'], type='int', alias='smt4') }},
        {{ trx_json_extract('src', ['smt4_kw'], type='varchar', alias='smt4_kw') }},
        {{ trx_json_extract('src', ['sml4', 'en_US'], type='varchar', alias='sml4__en_us') }},
        {{ trx_json_extract('src', ['smt5'], type='int', alias='smt5') }},
        {{ trx_json_extract('src', ['smt5_kw'], type='varchar', alias='smt5_kw') }},
        {{ trx_json_extract('src', ['sml5', 'en_US'], type='varchar', alias='sml5__en_us') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['cdf_bsrm'], type='int', alias='cdf_bsrm') }},
        {{ trx_json_extract('src', ['cdf_bsrm_kw'], type='varchar', alias='cdf_bsrm_kw') }},
        {{ trx_json_extract('src', ['cdf_cond'], type='timestamp_ntz', alias='cdf_cond') }},
        {{ trx_json_extract('src', ['cdf_crtl'], type='int', alias='cdf_crtl') }},
        {{ trx_json_extract('src', ['cdf_crtl_kw'], type='varchar', alias='cdf_crtl_kw') }},
        {{ trx_json_extract('src', ['cdf_emno'], type='int', alias='cdf_emno') }},
        {{ trx_json_extract('src', ['cdf_emno_kw'], type='varchar', alias='cdf_emno_kw') }},
        {{ trx_json_extract('src', ['cdf_exdt'], type='timestamp_ntz', alias='cdf_exdt') }},
        {{ trx_json_extract('src', ['cdf_hsst'], type='int', alias='cdf_hsst') }},
        {{ trx_json_extract('src', ['cdf_hsst_kw'], type='varchar', alias='cdf_hsst_kw') }},
        {{ trx_json_extract('src', ['cdf_rrdt'], type='timestamp_ntz', alias='cdf_rrdt') }},
        {{ trx_json_extract('src', ['cdf_wfst'], type='int', alias='cdf_wfst') }},
        {{ trx_json_extract('src', ['cdf_wfst_kw'], type='varchar', alias='cdf_wfst_kw') }},
        {{ trx_json_extract('src', ['ctit_ref_compnr'], type='int', alias='ctit_ref_compnr') }},
        {{ trx_json_extract('src', ['prbp_ref_compnr'], type='int', alias='prbp_ref_compnr') }},
        {{ trx_json_extract('src', ['clan_ref_compnr'], type='int', alias='clan_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['bptx_ref_compnr'], type='int', alias='bptx_ref_compnr') }},
        {{ trx_json_extract('src', ['cadr_ref_compnr'], type='int', alias='cadr_ref_compnr') }},
        {{ trx_json_extract('src', ['ccnt_ref_compnr'], type='int', alias='ccnt_ref_compnr') }},
        {{ trx_json_extract('src', ['cbcl_ref_compnr'], type='int', alias='cbcl_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tccom100') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'bpid']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
