{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tccom112 Invoice-to Business Partners table, Generated 2026-04-10T19:41:02Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['itbp'], type='varchar', alias='itbp') }},
        {{ trx_json_extract('src', ['cofc'], type='varchar', alias='cofc') }},
        {{ trx_json_extract('src', ['itst'], type='int', alias='itst') }},
        {{ trx_json_extract('src', ['itst_kw'], type='varchar', alias='itst_kw') }},
        {{ trx_json_extract('src', ['stdt'], type='timestamp_ntz', alias='stdt') }},
        {{ trx_json_extract('src', ['endt'], type='timestamp_ntz', alias='endt') }},
        {{ trx_json_extract('src', ['clan'], type='varchar', alias='clan') }},
        {{ trx_json_extract('src', ['cbps'], type='varchar', alias='cbps') }},
        {{ trx_json_extract('src', ['cbtp'], type='varchar', alias='cbtp') }},
        {{ trx_json_extract('src', ['cadr'], type='varchar', alias='cadr') }},
        {{ trx_json_extract('src', ['telp'], type='varchar', alias='telp') }},
        {{ trx_json_extract('src', ['tlcy'], type='varchar', alias='tlcy') }},
        {{ trx_json_extract('src', ['tlci'], type='varchar', alias='tlci') }},
        {{ trx_json_extract('src', ['tlln'], type='varchar', alias='tlln') }},
        {{ trx_json_extract('src', ['tlex'], type='varchar', alias='tlex') }},
        {{ trx_json_extract('src', ['tefx'], type='varchar', alias='tefx') }},
        {{ trx_json_extract('src', ['tfcy'], type='varchar', alias='tfcy') }},
        {{ trx_json_extract('src', ['tfci'], type='varchar', alias='tfci') }},
        {{ trx_json_extract('src', ['tfln'], type='varchar', alias='tfln') }},
        {{ trx_json_extract('src', ['tfex'], type='varchar', alias='tfex') }},
        {{ trx_json_extract('src', ['ccnt'], type='varchar', alias='ccnt') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['rtyp'], type='varchar', alias='rtyp') }},
        {{ trx_json_extract('src', ['cfcg'], type='varchar', alias='cfcg') }},
        {{ trx_json_extract('src', ['mstm'], type='varchar', alias='mstm') }},
        {{ trx_json_extract('src', ['chin'], type='int', alias='chin') }},
        {{ trx_json_extract('src', ['chin_kw'], type='varchar', alias='chin_kw') }},
        {{ trx_json_extract('src', ['ncin'], type='int', alias='ncin') }},
        {{ trx_json_extract('src', ['cinm'], type='varchar', alias='cinm') }},
        {{ trx_json_extract('src', ['cidm'], type='varchar', alias='cidm') }},
        {{ trx_json_extract('src', ['mcod'], type='varchar', alias='mcod') }},
        {{ trx_json_extract('src', ['infq'], type='int', alias='infq') }},
        {{ trx_json_extract('src', ['lidt'], type='timestamp_ntz', alias='lidt') }},
        {{ trx_json_extract('src', ['infr'], type='int', alias='infr') }},
        {{ trx_json_extract('src', ['infr_kw'], type='varchar', alias='infr_kw') }},
        {{ trx_json_extract('src', ['adpc'], type='float', alias='adpc') }},
        {{ trx_json_extract('src', ['adam'], type='float', alias='adam') }},
        {{ trx_json_extract('src', ['crat'], type='varchar', alias='crat') }},
        {{ trx_json_extract('src', ['ccra'], type='varchar', alias='ccra') }},
        {{ trx_json_extract('src', ['crbu'], type='varchar', alias='crbu') }},
        {{ trx_json_extract('src', ['crlr'], type='float', alias='crlr') }},
        {{ trx_json_extract('src', ['hcru'], type='float', alias='hcru') }},
        {{ trx_json_extract('src', ['dlcr'], type='timestamp_ntz', alias='dlcr') }},
        {{ trx_json_extract('src', ['clin'], type='float', alias='clin') }},
        {{ trx_json_extract('src', ['ccic'], type='varchar', alias='ccic') }},
        {{ trx_json_extract('src', ['rfci'], type='varchar', alias='rfci') }},
        {{ trx_json_extract('src', ['edci'], type='timestamp_ntz', alias='edci') }},
        {{ trx_json_extract('src', ['tamd'], type='float', alias='tamd') }},
        {{ trx_json_extract('src', ['tpcd'], type='float', alias='tpcd') }},
        {{ trx_json_extract('src', ['cpay'], type='varchar', alias='cpay') }},
        {{ trx_json_extract('src', ['rpay'], type='varchar', alias='rpay') }},
        {{ trx_json_extract('src', ['ccrs'], type='varchar', alias='ccrs') }},
        {{ trx_json_extract('src', ['rcrs'], type='varchar', alias='rcrs') }},
        {{ trx_json_extract('src', ['pfbp'], type='varchar', alias='pfbp') }},
        {{ trx_json_extract('src', ['paym'], type='varchar', alias='paym') }},
        {{ trx_json_extract('src', ['rpym'], type='varchar', alias='rpym') }},
        {{ trx_json_extract('src', ['dim1'], type='varchar', alias='dim1') }},
        {{ trx_json_extract('src', ['dim2'], type='varchar', alias='dim2') }},
        {{ trx_json_extract('src', ['dim3'], type='varchar', alias='dim3') }},
        {{ trx_json_extract('src', ['dim4'], type='varchar', alias='dim4') }},
        {{ trx_json_extract('src', ['dim5'], type='varchar', alias='dim5') }},
        {{ trx_json_extract('src', ['dim6'], type='varchar', alias='dim6') }},
        {{ trx_json_extract('src', ['dim7'], type='varchar', alias='dim7') }},
        {{ trx_json_extract('src', ['dim8'], type='varchar', alias='dim8') }},
        {{ trx_json_extract('src', ['dim9'], type='varchar', alias='dim9') }},
        {{ trx_json_extract('src', ['dm10'], type='varchar', alias='dm10') }},
        {{ trx_json_extract('src', ['dm11'], type='varchar', alias='dm11') }},
        {{ trx_json_extract('src', ['dm12'], type='varchar', alias='dm12') }},
        {{ trx_json_extract('src', ['sirn'], type='varchar', alias='sirn') }},
        {{ trx_json_extract('src', ['ecod'], type='varchar', alias='ecod') }},
        {{ trx_json_extract('src', ['lkst'], type='int', alias='lkst') }},
        {{ trx_json_extract('src', ['lkst_kw'], type='varchar', alias='lkst_kw') }},
        {{ trx_json_extract('src', ['clmt'], type='varchar', alias='clmt') }},
        {{ trx_json_extract('src', ['bpcl'], type='varchar', alias='bpcl') }},
        {{ trx_json_extract('src', ['inpl'], type='varchar', alias='inpl') }},
        {{ trx_json_extract('src', ['seak', 'en_US'], type='varchar', alias='seak__en_us') }},
        {{ trx_json_extract('src', ['cvyn'], type='int', alias='cvyn') }},
        {{ trx_json_extract('src', ['cvyn_kw'], type='varchar', alias='cvyn_kw') }},
        {{ trx_json_extract('src', ['user'], type='varchar', alias='user') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['lmus'], type='varchar', alias='lmus') }},
        {{ trx_json_extract('src', ['lmdt'], type='timestamp_ntz', alias='lmdt') }},
        {{ trx_json_extract('src', ['ircd'], type='varchar', alias='ircd') }},
        {{ trx_json_extract('src', ['bicy'], type='varchar', alias='bicy') }},
        {{ trx_json_extract('src', ['qrbl'], type='int', alias='qrbl') }},
        {{ trx_json_extract('src', ['qrbl_kw'], type='varchar', alias='qrbl_kw') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['itbp_ref_compnr'], type='int', alias='itbp_ref_compnr') }},
        {{ trx_json_extract('src', ['cofc_ref_compnr'], type='int', alias='cofc_ref_compnr') }},
        {{ trx_json_extract('src', ['clan_ref_compnr'], type='int', alias='clan_ref_compnr') }},
        {{ trx_json_extract('src', ['cbps_ref_compnr'], type='int', alias='cbps_ref_compnr') }},
        {{ trx_json_extract('src', ['cbtp_ref_compnr'], type='int', alias='cbtp_ref_compnr') }},
        {{ trx_json_extract('src', ['cadr_ref_compnr'], type='int', alias='cadr_ref_compnr') }},
        {{ trx_json_extract('src', ['ccnt_ref_compnr'], type='int', alias='ccnt_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['rtyp_ref_compnr'], type='int', alias='rtyp_ref_compnr') }},
        {{ trx_json_extract('src', ['cinm_ref_compnr'], type='int', alias='cinm_ref_compnr') }},
        {{ trx_json_extract('src', ['cidm_ref_compnr'], type='int', alias='cidm_ref_compnr') }},
        {{ trx_json_extract('src', ['mcod_ref_compnr'], type='int', alias='mcod_ref_compnr') }},
        {{ trx_json_extract('src', ['crat_ref_compnr'], type='int', alias='crat_ref_compnr') }},
        {{ trx_json_extract('src', ['ccra_ref_compnr'], type='int', alias='ccra_ref_compnr') }},
        {{ trx_json_extract('src', ['ccic_ref_compnr'], type='int', alias='ccic_ref_compnr') }},
        {{ trx_json_extract('src', ['cpay_ref_compnr'], type='int', alias='cpay_ref_compnr') }},
        {{ trx_json_extract('src', ['rpay_ref_compnr'], type='int', alias='rpay_ref_compnr') }},
        {{ trx_json_extract('src', ['ccrs_ref_compnr'], type='int', alias='ccrs_ref_compnr') }},
        {{ trx_json_extract('src', ['rcrs_ref_compnr'], type='int', alias='rcrs_ref_compnr') }},
        {{ trx_json_extract('src', ['pfbp_ref_compnr'], type='int', alias='pfbp_ref_compnr') }},
        {{ trx_json_extract('src', ['clmt_ref_compnr'], type='int', alias='clmt_ref_compnr') }},
        {{ trx_json_extract('src', ['bpcl_ref_compnr'], type='int', alias='bpcl_ref_compnr') }},
        {{ trx_json_extract('src', ['inpl_ref_compnr'], type='int', alias='inpl_ref_compnr') }},
        {{ trx_json_extract('src', ['bicy_ref_compnr'], type='int', alias='bicy_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['cfcg_rcmp'], type='int', alias='cfcg_rcmp') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tccom112') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'itbp', 'cofc']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
