{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tcibd001 Items table, Generated 2026-04-10T19:41:07Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['dsca', 'en_US'], type='varchar', alias='dsca__en_us') }},
        {{ trx_json_extract('src', ['seak', 'en_US'], type='varchar', alias='seak__en_us') }},
        {{ trx_json_extract('src', ['seab', 'en_US'], type='varchar', alias='seab__en_us') }},
        {{ trx_json_extract('src', ['exin'], type='varchar', alias='exin') }},
        {{ trx_json_extract('src', ['imag'], type='varchar', alias='imag') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['lmdt'], type='timestamp_ntz', alias='lmdt') }},
        {{ trx_json_extract('src', ['cood'], type='varchar', alias='cood') }},
        {{ trx_json_extract('src', ['kitm'], type='int', alias='kitm') }},
        {{ trx_json_extract('src', ['kitm_kw'], type='varchar', alias='kitm_kw') }},
        {{ trx_json_extract('src', ['citg'], type='varchar', alias='citg') }},
        {{ trx_json_extract('src', ['itmt'], type='int', alias='itmt') }},
        {{ trx_json_extract('src', ['itmt_kw'], type='varchar', alias='itmt_kw') }},
        {{ trx_json_extract('src', ['dsct'], type='int', alias='dsct') }},
        {{ trx_json_extract('src', ['dsct_kw'], type='varchar', alias='dsct_kw') }},
        {{ trx_json_extract('src', ['osys'], type='int', alias='osys') }},
        {{ trx_json_extract('src', ['osys_kw'], type='varchar', alias='osys_kw') }},
        {{ trx_json_extract('src', ['cuni'], type='varchar', alias='cuni') }},
        {{ trx_json_extract('src', ['rtun'], type='varchar', alias='rtun') }},
        {{ trx_json_extract('src', ['uset'], type='varchar', alias='uset') }},
        {{ trx_json_extract('src', ['ltct'], type='int', alias='ltct') }},
        {{ trx_json_extract('src', ['ltct_kw'], type='varchar', alias='ltct_kw') }},
        {{ trx_json_extract('src', ['seri'], type='int', alias='seri') }},
        {{ trx_json_extract('src', ['seri_kw'], type='varchar', alias='seri_kw') }},
        {{ trx_json_extract('src', ['cnfg'], type='int', alias='cnfg') }},
        {{ trx_json_extract('src', ['cnfg_kw'], type='varchar', alias='cnfg_kw') }},
        {{ trx_json_extract('src', ['repl'], type='int', alias='repl') }},
        {{ trx_json_extract('src', ['repl_kw'], type='varchar', alias='repl_kw') }},
        {{ trx_json_extract('src', ['cprj'], type='varchar', alias='cprj') }},
        {{ trx_json_extract('src', ['cpva'], type='int', alias='cpva') }},
        {{ trx_json_extract('src', ['dfit'], type='varchar', alias='dfit') }},
        {{ trx_json_extract('src', ['stoi'], type='int', alias='stoi') }},
        {{ trx_json_extract('src', ['stoi_kw'], type='varchar', alias='stoi_kw') }},
        {{ trx_json_extract('src', ['opts'], type='int', alias='opts') }},
        {{ trx_json_extract('src', ['cust'], type='int', alias='cust') }},
        {{ trx_json_extract('src', ['cust_kw'], type='varchar', alias='cust_kw') }},
        {{ trx_json_extract('src', ['opol'], type='int', alias='opol') }},
        {{ trx_json_extract('src', ['opol_kw'], type='varchar', alias='opol_kw') }},
        {{ trx_json_extract('src', ['wpcs'], type='int', alias='wpcs') }},
        {{ trx_json_extract('src', ['wpcs_kw'], type='varchar', alias='wpcs_kw') }},
        {{ trx_json_extract('src', ['ccfg'], type='varchar', alias='ccfg') }},
        {{ trx_json_extract('src', ['unef'], type='int', alias='unef') }},
        {{ trx_json_extract('src', ['unef_kw'], type='varchar', alias='unef_kw') }},
        {{ trx_json_extract('src', ['ichg'], type='int', alias='ichg') }},
        {{ trx_json_extract('src', ['ichg_kw'], type='varchar', alias='ichg_kw') }},
        {{ trx_json_extract('src', ['eitm'], type='int', alias='eitm') }},
        {{ trx_json_extract('src', ['eitm_kw'], type='varchar', alias='eitm_kw') }},
        {{ trx_json_extract('src', ['uefs'], type='int', alias='uefs') }},
        {{ trx_json_extract('src', ['uefs_kw'], type='varchar', alias='uefs_kw') }},
        {{ trx_json_extract('src', ['umer'], type='int', alias='umer') }},
        {{ trx_json_extract('src', ['umer_kw'], type='varchar', alias='umer_kw') }},
        {{ trx_json_extract('src', ['chma'], type='int', alias='chma') }},
        {{ trx_json_extract('src', ['chma_kw'], type='varchar', alias='chma_kw') }},
        {{ trx_json_extract('src', ['efco'], type='varchar', alias='efco') }},
        {{ trx_json_extract('src', ['indt'], type='timestamp_ntz', alias='indt') }},
        {{ trx_json_extract('src', ['edco'], type='int', alias='edco') }},
        {{ trx_json_extract('src', ['edco_kw'], type='varchar', alias='edco_kw') }},
        {{ trx_json_extract('src', ['mcoa'], type='int', alias='mcoa') }},
        {{ trx_json_extract('src', ['mcoa_kw'], type='varchar', alias='mcoa_kw') }},
        {{ trx_json_extract('src', ['sayn'], type='int', alias='sayn') }},
        {{ trx_json_extract('src', ['sayn_kw'], type='varchar', alias='sayn_kw') }},
        {{ trx_json_extract('src', ['cont'], type='int', alias='cont') }},
        {{ trx_json_extract('src', ['cont_kw'], type='varchar', alias='cont_kw') }},
        {{ trx_json_extract('src', ['cntr'], type='varchar', alias='cntr') }},
        {{ trx_json_extract('src', ['cpcp'], type='varchar', alias='cpcp') }},
        {{ trx_json_extract('src', ['coeu'], type='int', alias='coeu') }},
        {{ trx_json_extract('src', ['coeu_kw'], type='varchar', alias='coeu_kw') }},
        {{ trx_json_extract('src', ['ppeg'], type='int', alias='ppeg') }},
        {{ trx_json_extract('src', ['ppeg_kw'], type='varchar', alias='ppeg_kw') }},
        {{ trx_json_extract('src', ['ippg'], type='int', alias='ippg') }},
        {{ trx_json_extract('src', ['ippg_kw'], type='varchar', alias='ippg_kw') }},
        {{ trx_json_extract('src', ['ppss'], type='int', alias='ppss') }},
        {{ trx_json_extract('src', ['ppss_kw'], type='varchar', alias='ppss_kw') }},
        {{ trx_json_extract('src', ['elcm'], type='int', alias='elcm') }},
        {{ trx_json_extract('src', ['elcm_kw'], type='varchar', alias='elcm_kw') }},
        {{ trx_json_extract('src', ['elrq'], type='int', alias='elrq') }},
        {{ trx_json_extract('src', ['elrq_kw'], type='varchar', alias='elrq_kw') }},
        {{ trx_json_extract('src', ['dpeg'], type='int', alias='dpeg') }},
        {{ trx_json_extract('src', ['dpeg_kw'], type='varchar', alias='dpeg_kw') }},
        {{ trx_json_extract('src', ['dptp'], type='int', alias='dptp') }},
        {{ trx_json_extract('src', ['dptp_kw'], type='varchar', alias='dptp_kw') }},
        {{ trx_json_extract('src', ['dpuu'], type='int', alias='dpuu') }},
        {{ trx_json_extract('src', ['dpuu_kw'], type='varchar', alias='dpuu_kw') }},
        {{ trx_json_extract('src', ['sgtc'], type='int', alias='sgtc') }},
        {{ trx_json_extract('src', ['sgtc_kw'], type='varchar', alias='sgtc_kw') }},
        {{ trx_json_extract('src', ['lctr'], type='int', alias='lctr') }},
        {{ trx_json_extract('src', ['lctr_kw'], type='varchar', alias='lctr_kw') }},
        {{ trx_json_extract('src', ['cltr'], type='int', alias='cltr') }},
        {{ trx_json_extract('src', ['cltr_kw'], type='varchar', alias='cltr_kw') }},
        {{ trx_json_extract('src', ['srce'], type='int', alias='srce') }},
        {{ trx_json_extract('src', ['srce_kw'], type='varchar', alias='srce_kw') }},
        {{ trx_json_extract('src', ['efpr'], type='int', alias='efpr') }},
        {{ trx_json_extract('src', ['efpr_kw'], type='varchar', alias='efpr_kw') }},
        {{ trx_json_extract('src', ['dscb', 'en_US'], type='varchar', alias='dscb__en_us') }},
        {{ trx_json_extract('src', ['dscc', 'en_US'], type='varchar', alias='dscc__en_us') }},
        {{ trx_json_extract('src', ['dscd', 'en_US'], type='varchar', alias='dscd__en_us') }},
        {{ trx_json_extract('src', ['wght'], type='float', alias='wght') }},
        {{ trx_json_extract('src', ['cwun'], type='varchar', alias='cwun') }},
        {{ trx_json_extract('src', ['ctyp'], type='varchar', alias='ctyp') }},
        {{ trx_json_extract('src', ['cpcl'], type='varchar', alias='cpcl') }},
        {{ trx_json_extract('src', ['cpln'], type='varchar', alias='cpln') }},
        {{ trx_json_extract('src', ['cmnf'], type='varchar', alias='cmnf') }},
        {{ trx_json_extract('src', ['csel'], type='varchar', alias='csel') }},
        {{ trx_json_extract('src', ['csig'], type='varchar', alias='csig') }},
        {{ trx_json_extract('src', ['rdpt'], type='varchar', alias='rdpt') }},
        {{ trx_json_extract('src', ['ctyo'], type='varchar', alias='ctyo') }},
        {{ trx_json_extract('src', ['envc'], type='int', alias='envc') }},
        {{ trx_json_extract('src', ['envc_kw'], type='varchar', alias='envc_kw') }},
        {{ trx_json_extract('src', ['cean'], type='varchar', alias='cean') }},
        {{ trx_json_extract('src', ['ccde'], type='varchar', alias='ccde') }},
        {{ trx_json_extract('src', ['icsi'], type='int', alias='icsi') }},
        {{ trx_json_extract('src', ['icsi_kw'], type='varchar', alias='icsi_kw') }},
        {{ trx_json_extract('src', ['fstk'], type='int', alias='fstk') }},
        {{ trx_json_extract('src', ['fstk_kw'], type='varchar', alias='fstk_kw') }},
        {{ trx_json_extract('src', ['psiu'], type='int', alias='psiu') }},
        {{ trx_json_extract('src', ['psiu_kw'], type='varchar', alias='psiu_kw') }},
        {{ trx_json_extract('src', ['styp'], type='int', alias='styp') }},
        {{ trx_json_extract('src', ['styp_kw'], type='varchar', alias='styp_kw') }},
        {{ trx_json_extract('src', ['subc'], type='int', alias='subc') }},
        {{ trx_json_extract('src', ['subc_kw'], type='varchar', alias='subc_kw') }},
        {{ trx_json_extract('src', ['oktm'], type='int', alias='oktm') }},
        {{ trx_json_extract('src', ['dpcr'], type='int', alias='dpcr') }},
        {{ trx_json_extract('src', ['dpcr_kw'], type='varchar', alias='dpcr_kw') }},
        {{ trx_json_extract('src', ['rvdi'], type='int', alias='rvdi') }},
        {{ trx_json_extract('src', ['rvdi_kw'], type='varchar', alias='rvdi_kw') }},
        {{ trx_json_extract('src', ['rnum'], type='int', alias='rnum') }},
        {{ trx_json_extract('src', ['rnum_kw'], type='varchar', alias='rnum_kw') }},
        {{ trx_json_extract('src', ['mdtp'], type='int', alias='mdtp') }},
        {{ trx_json_extract('src', ['mdtp_kw'], type='varchar', alias='mdtp_kw') }},
        {{ trx_json_extract('src', ['iitv'], type='float', alias='iitv') }},
        {{ trx_json_extract('src', ['iivc'], type='varchar', alias='iivc') }},
        {{ trx_json_extract('src', ['iivu'], type='varchar', alias='iivu') }},
        {{ trx_json_extract('src', ['ivmd'], type='timestamp_ntz', alias='ivmd') }},
        {{ trx_json_extract('src', ['ivbd'], type='int', alias='ivbd') }},
        {{ trx_json_extract('src', ['ivbd_kw'], type='varchar', alias='ivbd_kw') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['cood_ref_compnr'], type='int', alias='cood_ref_compnr') }},
        {{ trx_json_extract('src', ['citg_ref_compnr'], type='int', alias='citg_ref_compnr') }},
        {{ trx_json_extract('src', ['cuni_ref_compnr'], type='int', alias='cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['rtun_ref_compnr'], type='int', alias='rtun_ref_compnr') }},
        {{ trx_json_extract('src', ['uset_cwun_ref_compnr'], type='int', alias='uset_cwun_ref_compnr') }},
        {{ trx_json_extract('src', ['uset_ref_compnr'], type='int', alias='uset_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_ref_compnr'], type='int', alias='cprj_ref_compnr') }},
        {{ trx_json_extract('src', ['dfit_ref_compnr'], type='int', alias='dfit_ref_compnr') }},
        {{ trx_json_extract('src', ['ccfg_ref_compnr'], type='int', alias='ccfg_ref_compnr') }},
        {{ trx_json_extract('src', ['cntr_ref_compnr'], type='int', alias='cntr_ref_compnr') }},
        {{ trx_json_extract('src', ['cpcp_ref_compnr'], type='int', alias='cpcp_ref_compnr') }},
        {{ trx_json_extract('src', ['cwun_ref_compnr'], type='int', alias='cwun_ref_compnr') }},
        {{ trx_json_extract('src', ['ctyp_ref_compnr'], type='int', alias='ctyp_ref_compnr') }},
        {{ trx_json_extract('src', ['cpcl_ref_compnr'], type='int', alias='cpcl_ref_compnr') }},
        {{ trx_json_extract('src', ['cpln_ref_compnr'], type='int', alias='cpln_ref_compnr') }},
        {{ trx_json_extract('src', ['cmnf_ref_compnr'], type='int', alias='cmnf_ref_compnr') }},
        {{ trx_json_extract('src', ['csel_ref_compnr'], type='int', alias='csel_ref_compnr') }},
        {{ trx_json_extract('src', ['csig_ref_compnr'], type='int', alias='csig_ref_compnr') }},
        {{ trx_json_extract('src', ['rdpt_ref_compnr'], type='int', alias='rdpt_ref_compnr') }},
        {{ trx_json_extract('src', ['ctyo_ref_compnr'], type='int', alias='ctyo_ref_compnr') }},
        {{ trx_json_extract('src', ['ccde_ref_compnr'], type='int', alias='ccde_ref_compnr') }},
        {{ trx_json_extract('src', ['iivc_ref_compnr'], type='int', alias='iivc_ref_compnr') }},
        {{ trx_json_extract('src', ['iivu_ref_compnr'], type='int', alias='iivu_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['cpva_rcmp'], type='int', alias='cpva_rcmp') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tcibd001') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'item']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
