{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tdipu001 Item - Purchase table, Generated 2026-04-10T19:41:16Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['seak', 'en_US'], type='varchar', alias='seak__en_us') }},
        {{ trx_json_extract('src', ['cuqi'], type='varchar', alias='cuqi') }},
        {{ trx_json_extract('src', ['cuqp'], type='varchar', alias='cuqp') }},
        {{ trx_json_extract('src', ['rqun'], type='varchar', alias='rqun') }},
        {{ trx_json_extract('src', ['cupp'], type='varchar', alias='cupp') }},
        {{ trx_json_extract('src', ['rpun'], type='varchar', alias='rpun') }},
        {{ trx_json_extract('src', ['cpgp'], type='varchar', alias='cpgp') }},
        {{ trx_json_extract('src', ['csgp'], type='varchar', alias='csgp') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['vtbo'], type='int', alias='vtbo') }},
        {{ trx_json_extract('src', ['vtbo_kw'], type='varchar', alias='vtbo_kw') }},
        {{ trx_json_extract('src', ['prip'], type='float', alias='prip') }},
        {{ trx_json_extract('src', ['rppr'], type='float', alias='rppr') }},
        {{ trx_json_extract('src', ['ispr'], type='float', alias='ispr') }},
        {{ trx_json_extract('src', ['scpr'], type='float', alias='scpr') }},
        {{ trx_json_extract('src', ['sopr'], type='int', alias='sopr') }},
        {{ trx_json_extract('src', ['sopr_kw'], type='varchar', alias='sopr_kw') }},
        {{ trx_json_extract('src', ['sspr'], type='float', alias='sspr') }},
        {{ trx_json_extract('src', ['sops'], type='int', alias='sops') }},
        {{ trx_json_extract('src', ['sops_kw'], type='varchar', alias='sops_kw') }},
        {{ trx_json_extract('src', ['cvat'], type='varchar', alias='cvat') }},
        {{ trx_json_extract('src', ['otbp'], type='varchar', alias='otbp') }},
        {{ trx_json_extract('src', ['buyr'], type='varchar', alias='buyr') }},
        {{ trx_json_extract('src', ['edco'], type='int', alias='edco') }},
        {{ trx_json_extract('src', ['edco_kw'], type='varchar', alias='edco_kw') }},
        {{ trx_json_extract('src', ['mlco'], type='int', alias='mlco') }},
        {{ trx_json_extract('src', ['mlco_kw'], type='varchar', alias='mlco_kw') }},
        {{ trx_json_extract('src', ['rtdp'], type='int', alias='rtdp') }},
        {{ trx_json_extract('src', ['rtdm'], type='int', alias='rtdm') }},
        {{ trx_json_extract('src', ['rtqp'], type='float', alias='rtqp') }},
        {{ trx_json_extract('src', ['rtqm'], type='float', alias='rtqm') }},
        {{ trx_json_extract('src', ['acci'], type='int', alias='acci') }},
        {{ trx_json_extract('src', ['acci_kw'], type='varchar', alias='acci_kw') }},
        {{ trx_json_extract('src', ['mmnf'], type='int', alias='mmnf') }},
        {{ trx_json_extract('src', ['mmnf_kw'], type='varchar', alias='mmnf_kw') }},
        {{ trx_json_extract('src', ['cims'], type='int', alias='cims') }},
        {{ trx_json_extract('src', ['cims_kw'], type='varchar', alias='cims_kw') }},
        {{ trx_json_extract('src', ['lcmp'], type='int', alias='lcmp') }},
        {{ trx_json_extract('src', ['cofc'], type='varchar', alias='cofc') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['retw'], type='int', alias='retw') }},
        {{ trx_json_extract('src', ['retw_kw'], type='varchar', alias='retw_kw') }},
        {{ trx_json_extract('src', ['issp'], type='int', alias='issp') }},
        {{ trx_json_extract('src', ['issp_kw'], type='varchar', alias='issp_kw') }},
        {{ trx_json_extract('src', ['afrb'], type='int', alias='afrb') }},
        {{ trx_json_extract('src', ['afrb_kw'], type='varchar', alias='afrb_kw') }},
        {{ trx_json_extract('src', ['spco'], type='int', alias='spco') }},
        {{ trx_json_extract('src', ['spco_kw'], type='varchar', alias='spco_kw') }},
        {{ trx_json_extract('src', ['vryn'], type='int', alias='vryn') }},
        {{ trx_json_extract('src', ['vryn_kw'], type='varchar', alias='vryn_kw') }},
        {{ trx_json_extract('src', ['suti'], type='float', alias='suti') }},
        {{ trx_json_extract('src', ['sutu'], type='int', alias='sutu') }},
        {{ trx_json_extract('src', ['sutu_kw'], type='varchar', alias='sutu_kw') }},
        {{ trx_json_extract('src', ['qual'], type='int', alias='qual') }},
        {{ trx_json_extract('src', ['qual_kw'], type='varchar', alias='qual_kw') }},
        {{ trx_json_extract('src', ['cncd'], type='varchar', alias='cncd') }},
        {{ trx_json_extract('src', ['hstq'], type='int', alias='hstq') }},
        {{ trx_json_extract('src', ['hstq_kw'], type='varchar', alias='hstq_kw') }},
        {{ trx_json_extract('src', ['hstd'], type='int', alias='hstd') }},
        {{ trx_json_extract('src', ['hstd_kw'], type='varchar', alias='hstd_kw') }},
        {{ trx_json_extract('src', ['casl'], type='int', alias='casl') }},
        {{ trx_json_extract('src', ['casl_kw'], type='varchar', alias='casl_kw') }},
        {{ trx_json_extract('src', ['mpyn'], type='int', alias='mpyn') }},
        {{ trx_json_extract('src', ['mpyn_kw'], type='varchar', alias='mpyn_kw') }},
        {{ trx_json_extract('src', ['mpnr'], type='varchar', alias='mpnr') }},
        {{ trx_json_extract('src', ['cmnf'], type='varchar', alias='cmnf') }},
        {{ trx_json_extract('src', ['rqms'], type='int', alias='rqms') }},
        {{ trx_json_extract('src', ['rqms_kw'], type='varchar', alias='rqms_kw') }},
        {{ trx_json_extract('src', ['rmss'], type='int', alias='rmss') }},
        {{ trx_json_extract('src', ['rmss_kw'], type='varchar', alias='rmss_kw') }},
        {{ trx_json_extract('src', ['scus'], type='int', alias='scus') }},
        {{ trx_json_extract('src', ['scus_kw'], type='varchar', alias='scus_kw') }},
        {{ trx_json_extract('src', ['styp'], type='int', alias='styp') }},
        {{ trx_json_extract('src', ['styp_kw'], type='varchar', alias='styp_kw') }},
        {{ trx_json_extract('src', ['ctyo'], type='varchar', alias='ctyo') }},
        {{ trx_json_extract('src', ['txtp'], type='int', alias='txtp') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['cuqi_ref_compnr'], type='int', alias='cuqi_ref_compnr') }},
        {{ trx_json_extract('src', ['cuqp_ref_compnr'], type='int', alias='cuqp_ref_compnr') }},
        {{ trx_json_extract('src', ['rqun_ref_compnr'], type='int', alias='rqun_ref_compnr') }},
        {{ trx_json_extract('src', ['cupp_ref_compnr'], type='int', alias='cupp_ref_compnr') }},
        {{ trx_json_extract('src', ['rpun_ref_compnr'], type='int', alias='rpun_ref_compnr') }},
        {{ trx_json_extract('src', ['cpgp_ref_compnr'], type='int', alias='cpgp_ref_compnr') }},
        {{ trx_json_extract('src', ['csgp_ref_compnr'], type='int', alias='csgp_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['cvat_ref_compnr'], type='int', alias='cvat_ref_compnr') }},
        {{ trx_json_extract('src', ['otbp_ref_compnr'], type='int', alias='otbp_ref_compnr') }},
        {{ trx_json_extract('src', ['buyr_ref_compnr'], type='int', alias='buyr_ref_compnr') }},
        {{ trx_json_extract('src', ['lcmp_ref_compnr'], type='int', alias='lcmp_ref_compnr') }},
        {{ trx_json_extract('src', ['cofc_ref_compnr'], type='int', alias='cofc_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['mpnr_cmnf_ref_compnr'], type='int', alias='mpnr_cmnf_ref_compnr') }},
        {{ trx_json_extract('src', ['cmnf_ref_compnr'], type='int', alias='cmnf_ref_compnr') }},
        {{ trx_json_extract('src', ['ctyo_ref_compnr'], type='int', alias='ctyo_ref_compnr') }},
        {{ trx_json_extract('src', ['txtp_ref_compnr'], type='int', alias='txtp_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tdipu001') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'item']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
