{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tdpur300 Purchase Contracts table, Generated 2026-04-10T19:41:20Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['cono'], type='varchar', alias='cono') }},
        {{ trx_json_extract('src', ['otbp'], type='varchar', alias='otbp') }},
        {{ trx_json_extract('src', ['otad'], type='varchar', alias='otad') }},
        {{ trx_json_extract('src', ['otcn'], type='varchar', alias='otcn') }},
        {{ trx_json_extract('src', ['sfbp'], type='varchar', alias='sfbp') }},
        {{ trx_json_extract('src', ['sfad'], type='varchar', alias='sfad') }},
        {{ trx_json_extract('src', ['sfcn'], type='varchar', alias='sfcn') }},
        {{ trx_json_extract('src', ['ifbp'], type='varchar', alias='ifbp') }},
        {{ trx_json_extract('src', ['ifad'], type='varchar', alias='ifad') }},
        {{ trx_json_extract('src', ['ifcn'], type='varchar', alias='ifcn') }},
        {{ trx_json_extract('src', ['ptbp'], type='varchar', alias='ptbp') }},
        {{ trx_json_extract('src', ['ptad'], type='varchar', alias='ptad') }},
        {{ trx_json_extract('src', ['ptcn'], type='varchar', alias='ptcn') }},
        {{ trx_json_extract('src', ['cdes', 'en_US'], type='varchar', alias='cdes__en_us') }},
        {{ trx_json_extract('src', ['icyp'], type='int', alias='icyp') }},
        {{ trx_json_extract('src', ['icyp_kw'], type='varchar', alias='icyp_kw') }},
        {{ trx_json_extract('src', ['icap'], type='int', alias='icap') }},
        {{ trx_json_extract('src', ['icap_kw'], type='varchar', alias='icap_kw') }},
        {{ trx_json_extract('src', ['icpr'], type='int', alias='icpr') }},
        {{ trx_json_extract('src', ['icpr_kw'], type='varchar', alias='icpr_kw') }},
        {{ trx_json_extract('src', ['csts'], type='int', alias='csts') }},
        {{ trx_json_extract('src', ['csts_kw'], type='varchar', alias='csts_kw') }},
        {{ trx_json_extract('src', ['lcmp'], type='int', alias='lcmp') }},
        {{ trx_json_extract('src', ['cofc'], type='varchar', alias='cofc') }},
        {{ trx_json_extract('src', ['rcmp'], type='int', alias='rcmp') }},
        {{ trx_json_extract('src', ['rofc'], type='varchar', alias='rofc') }},
        {{ trx_json_extract('src', ['refe', 'en_US'], type='varchar', alias='refe__en_us') }},
        {{ trx_json_extract('src', ['refb', 'en_US'], type='varchar', alias='refb__en_us') }},
        {{ trx_json_extract('src', ['cdat'], type='timestamp_ntz', alias='cdat') }},
        {{ trx_json_extract('src', ['sdat'], type='timestamp_ntz', alias='sdat') }},
        {{ trx_json_extract('src', ['edat'], type='timestamp_ntz', alias='edat') }},
        {{ trx_json_extract('src', ['cpay'], type='varchar', alias='cpay') }},
        {{ trx_json_extract('src', ['rcsi'], type='varchar', alias='rcsi') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['cadr'], type='varchar', alias='cadr') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['ccon'], type='varchar', alias='ccon') }},
        {{ trx_json_extract('src', ['bpcl'], type='varchar', alias='bpcl') }},
        {{ trx_json_extract('src', ['ccrs'], type='varchar', alias='ccrs') }},
        {{ trx_json_extract('src', ['cfrw'], type='varchar', alias='cfrw') }},
        {{ trx_json_extract('src', ['cdec'], type='varchar', alias='cdec') }},
        {{ trx_json_extract('src', ['ptpa'], type='varchar', alias='ptpa') }},
        {{ trx_json_extract('src', ['conf', 'en_US'], type='varchar', alias='conf__en_us') }},
        {{ trx_json_extract('src', ['cotp'], type='varchar', alias='cotp') }},
        {{ trx_json_extract('src', ['nope'], type='int', alias='nope') }},
        {{ trx_json_extract('src', ['ocon'], type='varchar', alias='ocon') }},
        {{ trx_json_extract('src', ['trid'], type='varchar', alias='trid') }},
        {{ trx_json_extract('src', ['chrq'], type='int', alias='chrq') }},
        {{ trx_json_extract('src', ['chrq_kw'], type='varchar', alias='chrq_kw') }},
        {{ trx_json_extract('src', ['revn'], type='int', alias='revn') }},
        {{ trx_json_extract('src', ['crby'], type='varchar', alias='crby') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['srcn'], type='varchar', alias='srcn') }},
        {{ trx_json_extract('src', ['crst'], type='int', alias='crst') }},
        {{ trx_json_extract('src', ['crst_kw'], type='varchar', alias='crst_kw') }},
        {{ trx_json_extract('src', ['crrq'], type='int', alias='crrq') }},
        {{ trx_json_extract('src', ['crrq_kw'], type='varchar', alias='crrq_kw') }},
        {{ trx_json_extract('src', ['crin'], type='int', alias='crin') }},
        {{ trx_json_extract('src', ['crin_kw'], type='varchar', alias='crin_kw') }},
        {{ trx_json_extract('src', ['copc'], type='int', alias='copc') }},
        {{ trx_json_extract('src', ['copc_kw'], type='varchar', alias='copc_kw') }},
        {{ trx_json_extract('src', ['ccty'], type='varchar', alias='ccty') }},
        {{ trx_json_extract('src', ['cvyn'], type='int', alias='cvyn') }},
        {{ trx_json_extract('src', ['cvyn_kw'], type='varchar', alias='cvyn_kw') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['txtb'], type='int', alias='txtb') }},
        {{ trx_json_extract('src', ['txtt'], type='int', alias='txtt') }},
        {{ trx_json_extract('src', ['crht'], type='int', alias='crht') }},
        {{ trx_json_extract('src', ['cdf_aval'], type='float', alias='cdf_aval') }},
        {{ trx_json_extract('src', ['cdf_camt'], type='float', alias='cdf_camt') }},
        {{ trx_json_extract('src', ['cdf_comt'], type='float', alias='cdf_comt') }},
        {{ trx_json_extract('src', ['cdf_conn'], type='varchar', alias='cdf_conn') }},
        {{ trx_json_extract('src', ['cdf_pwno'], type='varchar', alias='cdf_pwno') }},
        {{ trx_json_extract('src', ['cdf_ramt'], type='float', alias='cdf_ramt') }},
        {{ trx_json_extract('src', ['cdf_vval'], type='float', alias='cdf_vval') }},
        {{ trx_json_extract('src', ['otbp_ref_compnr'], type='int', alias='otbp_ref_compnr') }},
        {{ trx_json_extract('src', ['otad_ref_compnr'], type='int', alias='otad_ref_compnr') }},
        {{ trx_json_extract('src', ['otcn_ref_compnr'], type='int', alias='otcn_ref_compnr') }},
        {{ trx_json_extract('src', ['sfbp_ref_compnr'], type='int', alias='sfbp_ref_compnr') }},
        {{ trx_json_extract('src', ['sfad_ref_compnr'], type='int', alias='sfad_ref_compnr') }},
        {{ trx_json_extract('src', ['sfcn_ref_compnr'], type='int', alias='sfcn_ref_compnr') }},
        {{ trx_json_extract('src', ['ifbp_ref_compnr'], type='int', alias='ifbp_ref_compnr') }},
        {{ trx_json_extract('src', ['ifad_ref_compnr'], type='int', alias='ifad_ref_compnr') }},
        {{ trx_json_extract('src', ['ifcn_ref_compnr'], type='int', alias='ifcn_ref_compnr') }},
        {{ trx_json_extract('src', ['ptbp_ref_compnr'], type='int', alias='ptbp_ref_compnr') }},
        {{ trx_json_extract('src', ['ptad_ref_compnr'], type='int', alias='ptad_ref_compnr') }},
        {{ trx_json_extract('src', ['ptcn_ref_compnr'], type='int', alias='ptcn_ref_compnr') }},
        {{ trx_json_extract('src', ['lcmp_ref_compnr'], type='int', alias='lcmp_ref_compnr') }},
        {{ trx_json_extract('src', ['cofc_ref_compnr'], type='int', alias='cofc_ref_compnr') }},
        {{ trx_json_extract('src', ['rcmp_ref_compnr'], type='int', alias='rcmp_ref_compnr') }},
        {{ trx_json_extract('src', ['rofc_ref_compnr'], type='int', alias='rofc_ref_compnr') }},
        {{ trx_json_extract('src', ['cpay_ref_compnr'], type='int', alias='cpay_ref_compnr') }},
        {{ trx_json_extract('src', ['rcsi_ref_compnr'], type='int', alias='rcsi_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['cadr_ref_compnr'], type='int', alias='cadr_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['ccon_ref_compnr'], type='int', alias='ccon_ref_compnr') }},
        {{ trx_json_extract('src', ['bpcl_ref_compnr'], type='int', alias='bpcl_ref_compnr') }},
        {{ trx_json_extract('src', ['ccrs_ref_compnr'], type='int', alias='ccrs_ref_compnr') }},
        {{ trx_json_extract('src', ['cfrw_ref_compnr'], type='int', alias='cfrw_ref_compnr') }},
        {{ trx_json_extract('src', ['cdec_ref_compnr'], type='int', alias='cdec_ref_compnr') }},
        {{ trx_json_extract('src', ['ptpa_ref_compnr'], type='int', alias='ptpa_ref_compnr') }},
        {{ trx_json_extract('src', ['cotp_ref_compnr'], type='int', alias='cotp_ref_compnr') }},
        {{ trx_json_extract('src', ['ocon_ref_compnr'], type='int', alias='ocon_ref_compnr') }},
        {{ trx_json_extract('src', ['trid_ref_compnr'], type='int', alias='trid_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['txtb_ref_compnr'], type='int', alias='txtb_ref_compnr') }},
        {{ trx_json_extract('src', ['txtt_ref_compnr'], type='int', alias='txtt_ref_compnr') }},
        {{ trx_json_extract('src', ['crht_ref_compnr'], type='int', alias='crht_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tdpur300') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'cono']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
