{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tfgld106 Finalized Transactions table, Generated 2026-04-10T19:41:42Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['otyp'], type='varchar', alias='otyp') }},
        {{ trx_json_extract('src', ['odoc'], type='int', alias='odoc') }},
        {{ trx_json_extract('src', ['olin'], type='int', alias='olin') }},
        {{ trx_json_extract('src', ['osrl'], type='int', alias='osrl') }},
        {{ trx_json_extract('src', ['osrn'], type='int', alias='osrn') }},
        {{ trx_json_extract('src', ['ocmp'], type='int', alias='ocmp') }},
        {{ trx_json_extract('src', ['ftyp'], type='varchar', alias='ftyp') }},
        {{ trx_json_extract('src', ['fdoc'], type='int', alias='fdoc') }},
        {{ trx_json_extract('src', ['oyer'], type='int', alias='oyer') }},
        {{ trx_json_extract('src', ['obat'], type='int', alias='obat') }},
        {{ trx_json_extract('src', ['leac'], type='varchar', alias='leac') }},
        {{ trx_json_extract('src', ['dcdt'], type='date', alias='dcdt') }},
        {{ trx_json_extract('src', ['typ1'], type='int', alias='typ1') }},
        {{ trx_json_extract('src', ['dim1'], type='varchar', alias='dim1') }},
        {{ trx_json_extract('src', ['typ2'], type='int', alias='typ2') }},
        {{ trx_json_extract('src', ['dim2'], type='varchar', alias='dim2') }},
        {{ trx_json_extract('src', ['typ3'], type='int', alias='typ3') }},
        {{ trx_json_extract('src', ['dim3'], type='varchar', alias='dim3') }},
        {{ trx_json_extract('src', ['typ4'], type='int', alias='typ4') }},
        {{ trx_json_extract('src', ['dim4'], type='varchar', alias='dim4') }},
        {{ trx_json_extract('src', ['typ5'], type='int', alias='typ5') }},
        {{ trx_json_extract('src', ['dim5'], type='varchar', alias='dim5') }},
        {{ trx_json_extract('src', ['dim6'], type='varchar', alias='dim6') }},
        {{ trx_json_extract('src', ['dim7'], type='varchar', alias='dim7') }},
        {{ trx_json_extract('src', ['dim8'], type='varchar', alias='dim8') }},
        {{ trx_json_extract('src', ['dim9'], type='varchar', alias='dim9') }},
        {{ trx_json_extract('src', ['dm10'], type='varchar', alias='dm10') }},
        {{ trx_json_extract('src', ['dm11'], type='varchar', alias='dm11') }},
        {{ trx_json_extract('src', ['dm12'], type='varchar', alias='dm12') }},
        {{ trx_json_extract('src', ['refr', 'en_US'], type='varchar', alias='refr__en_us') }},
        {{ trx_json_extract('src', ['ref2', 'en_US'], type='varchar', alias='ref2__en_us') }},
        {{ trx_json_extract('src', ['amnt'], type='float', alias='amnt') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['ratd'], type='timestamp_ntz', alias='ratd') }},
        {{ trx_json_extract('src', ['rate_1'], type='float', alias='rate_1') }},
        {{ trx_json_extract('src', ['rate_2'], type='float', alias='rate_2') }},
        {{ trx_json_extract('src', ['rate_3'], type='float', alias='rate_3') }},
        {{ trx_json_extract('src', ['fact_1'], type='int', alias='fact_1') }},
        {{ trx_json_extract('src', ['fact_2'], type='int', alias='fact_2') }},
        {{ trx_json_extract('src', ['fact_3'], type='int', alias='fact_3') }},
        {{ trx_json_extract('src', ['rtyp'], type='varchar', alias='rtyp') }},
        {{ trx_json_extract('src', ['amth_1'], type='float', alias='amth_1') }},
        {{ trx_json_extract('src', ['amth_2'], type='float', alias='amth_2') }},
        {{ trx_json_extract('src', ['amth_3'], type='float', alias='amth_3') }},
        {{ trx_json_extract('src', ['dbcr'], type='int', alias='dbcr') }},
        {{ trx_json_extract('src', ['dbcr_kw'], type='varchar', alias='dbcr_kw') }},
        {{ trx_json_extract('src', ['ccty'], type='varchar', alias='ccty') }},
        {{ trx_json_extract('src', ['cvat'], type='varchar', alias='cvat') }},
        {{ trx_json_extract('src', ['vtyp'], type='int', alias='vtyp') }},
        {{ trx_json_extract('src', ['vtyp_kw'], type='varchar', alias='vtyp_kw') }},
        {{ trx_json_extract('src', ['vlac'], type='varchar', alias='vlac') }},
        {{ trx_json_extract('src', ['vamt'], type='float', alias='vamt') }},
        {{ trx_json_extract('src', ['vamh_1'], type='float', alias='vamh_1') }},
        {{ trx_json_extract('src', ['vamh_2'], type='float', alias='vamh_2') }},
        {{ trx_json_extract('src', ['vamh_3'], type='float', alias='vamh_3') }},
        {{ trx_json_extract('src', ['qty1'], type='float', alias='qty1') }},
        {{ trx_json_extract('src', ['qty2'], type='float', alias='qty2') }},
        {{ trx_json_extract('src', ['fprd'], type='int', alias='fprd') }},
        {{ trx_json_extract('src', ['fyer'], type='int', alias='fyer') }},
        {{ trx_json_extract('src', ['rprd'], type='int', alias='rprd') }},
        {{ trx_json_extract('src', ['ryer'], type='int', alias='ryer') }},
        {{ trx_json_extract('src', ['vprd'], type='int', alias='vprd') }},
        {{ trx_json_extract('src', ['vyer'], type='int', alias='vyer') }},
        {{ trx_json_extract('src', ['bpid'], type='varchar', alias='bpid') }},
        {{ trx_json_extract('src', ['catg'], type='int', alias='catg') }},
        {{ trx_json_extract('src', ['catg_kw'], type='varchar', alias='catg_kw') }},
        {{ trx_json_extract('src', ['user'], type='varchar', alias='user') }},
        {{ trx_json_extract('src', ['date'], type='date', alias='date') }},
        {{ trx_json_extract('src', ['time'], type='int', alias='time') }},
        {{ trx_json_extract('src', ['trun'], type='int', alias='trun') }},
        {{ trx_json_extract('src', ['cont'], type='int', alias='cont') }},
        {{ trx_json_extract('src', ['cont_kw'], type='varchar', alias='cont_kw') }},
        {{ trx_json_extract('src', ['ctyp'], type='varchar', alias='ctyp') }},
        {{ trx_json_extract('src', ['cinv'], type='int', alias='cinv') }},
        {{ trx_json_extract('src', ['clin'], type='int', alias='clin') }},
        {{ trx_json_extract('src', ['cdln'], type='int', alias='cdln') }},
        {{ trx_json_extract('src', ['corn'], type='int', alias='corn') }},
        {{ trx_json_extract('src', ['csrn'], type='int', alias='csrn') }},
        {{ trx_json_extract('src', ['tcsh'], type='int', alias='tcsh') }},
        {{ trx_json_extract('src', ['tcsh_kw'], type='varchar', alias='tcsh_kw') }},
        {{ trx_json_extract('src', ['tran'], type='int', alias='tran') }},
        {{ trx_json_extract('src', ['tran_kw'], type='varchar', alias='tran_kw') }},
        {{ trx_json_extract('src', ['dele'], type='int', alias='dele') }},
        {{ trx_json_extract('src', ['dele_kw'], type='varchar', alias='dele_kw') }},
        {{ trx_json_extract('src', ['intt'], type='int', alias='intt') }},
        {{ trx_json_extract('src', ['intt_kw'], type='varchar', alias='intt_kw') }},
        {{ trx_json_extract('src', ['adty'], type='int', alias='adty') }},
        {{ trx_json_extract('src', ['adty_kw'], type='varchar', alias='adty_kw') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['recl'], type='int', alias='recl') }},
        {{ trx_json_extract('src', ['recl_kw'], type='varchar', alias='recl_kw') }},
        {{ trx_json_extract('src', ['reco'], type='int', alias='reco') }},
        {{ trx_json_extract('src', ['reco_kw'], type='varchar', alias='reco_kw') }},
        {{ trx_json_extract('src', ['recs'], type='int', alias='recs') }},
        {{ trx_json_extract('src', ['cfrs'], type='varchar', alias='cfrs') }},
        {{ trx_json_extract('src', ['secd'], type='varchar', alias='secd') }},
        {{ trx_json_extract('src', ['tedt'], type='date', alias='tedt') }},
        {{ trx_json_extract('src', ['wtsc'], type='int', alias='wtsc') }},
        {{ trx_json_extract('src', ['wtsc_kw'], type='varchar', alias='wtsc_kw') }},
        {{ trx_json_extract('src', ['buex'], type='int', alias='buex') }},
        {{ trx_json_extract('src', ['buex_kw'], type='varchar', alias='buex_kw') }},
        {{ trx_json_extract('src', ['cacc'], type='varchar', alias='cacc') }},
        {{ trx_json_extract('src', ['expd'], type='int', alias='expd') }},
        {{ trx_json_extract('src', ['expd_kw'], type='varchar', alias='expd_kw') }},
        {{ trx_json_extract('src', ['bpri'], type='varchar', alias='bpri') }},
        {{ trx_json_extract('src', ['regc'], type='varchar', alias='regc') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['regc_ref_compnr'], type='int', alias='regc_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tfgld106') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'otyp', 'odoc', 'olin', 'osrl', 'osrn']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
