{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tfgld482 Integration Transactions table, Generated 2026-04-10T19:41:45Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['guid'], type='varchar', alias='guid') }},
        {{ trx_json_extract('src', ['dbcr'], type='int', alias='dbcr') }},
        {{ trx_json_extract('src', ['dbcr_kw'], type='varchar', alias='dbcr_kw') }},
        {{ trx_json_extract('src', ['ocmp'], type='int', alias='ocmp') }},
        {{ trx_json_extract('src', ['idtc'], type='varchar', alias='idtc') }},
        {{ trx_json_extract('src', ['trdt'], type='timestamp_ntz', alias='trdt') }},
        {{ trx_json_extract('src', ['tcmp'], type='int', alias='tcmp') }},
        {{ trx_json_extract('src', ['secd'], type='varchar', alias='secd') }},
        {{ trx_json_extract('src', ['seva'], type='varchar', alias='seva') }},
        {{ trx_json_extract('src', ['rbon'], type='varchar', alias='rbon') }},
        {{ trx_json_extract('src', ['rbid'], type='varchar', alias='rbid') }},
        {{ trx_json_extract('src', ['rpon'], type='int', alias='rpon') }},
        {{ trx_json_extract('src', ['obre'], type='varchar', alias='obre') }},
        {{ trx_json_extract('src', ['buid'], type='varchar', alias='buid') }},
        {{ trx_json_extract('src', ['bpid'], type='varchar', alias='bpid') }},
        {{ trx_json_extract('src', ['ttyp'], type='varchar', alias='ttyp') }},
        {{ trx_json_extract('src', ['docn'], type='int', alias='docn') }},
        {{ trx_json_extract('src', ['btno'], type='int', alias='btno') }},
        {{ trx_json_extract('src', ['lino'], type='int', alias='lino') }},
        {{ trx_json_extract('src', ['sint'], type='int', alias='sint') }},
        {{ trx_json_extract('src', ['sint_kw'], type='varchar', alias='sint_kw') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['crus'], type='varchar', alias='crus') }},
        {{ trx_json_extract('src', ['usgr'], type='varchar', alias='usgr') }},
        {{ trx_json_extract('src', ['pous'], type='varchar', alias='pous') }},
        {{ trx_json_extract('src', ['podt'], type='timestamp_ntz', alias='podt') }},
        {{ trx_json_extract('src', ['prin'], type='int', alias='prin') }},
        {{ trx_json_extract('src', ['prin_kw'], type='varchar', alias='prin_kw') }},
        {{ trx_json_extract('src', ['glcu'], type='int', alias='glcu') }},
        {{ trx_json_extract('src', ['glcu_kw'], type='varchar', alias='glcu_kw') }},
        {{ trx_json_extract('src', ['alam'], type='int', alias='alam') }},
        {{ trx_json_extract('src', ['alam_kw'], type='varchar', alias='alam_kw') }},
        {{ trx_json_extract('src', ['admm'], type='int', alias='admm') }},
        {{ trx_json_extract('src', ['admm_kw'], type='varchar', alias='admm_kw') }},
        {{ trx_json_extract('src', ['fcom'], type='int', alias='fcom') }},
        {{ trx_json_extract('src', ['leac'], type='varchar', alias='leac') }},
        {{ trx_json_extract('src', ['dim1'], type='varchar', alias='dim1') }},
        {{ trx_json_extract('src', ['dim2'], type='varchar', alias='dim2') }},
        {{ trx_json_extract('src', ['dim3'], type='varchar', alias='dim3') }},
        {{ trx_json_extract('src', ['dim4'], type='varchar', alias='dim4') }},
        {{ trx_json_extract('src', ['dim5'], type='varchar', alias='dim5') }},
        {{ trx_json_extract('src', ['dim6'], type='varchar', alias='dim6') }},
        {{ trx_json_extract('src', ['dim7'], type='varchar', alias='dim7') }},
        {{ trx_json_extract('src', ['dim8'], type='varchar', alias='dim8') }},
        {{ trx_json_extract('src', ['dim9'], type='varchar', alias='dim9') }},
        {{ trx_json_extract('src', ['dm10'], type='varchar', alias='dm10') }},
        {{ trx_json_extract('src', ['dm11'], type='varchar', alias='dm11') }},
        {{ trx_json_extract('src', ['dm12'], type='varchar', alias='dm12') }},
        {{ trx_json_extract('src', ['amnt'], type='float', alias='amnt') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['ratd'], type='timestamp_ntz', alias='ratd') }},
        {{ trx_json_extract('src', ['rtyp'], type='varchar', alias='rtyp') }},
        {{ trx_json_extract('src', ['rate_1'], type='float', alias='rate_1') }},
        {{ trx_json_extract('src', ['rate_2'], type='float', alias='rate_2') }},
        {{ trx_json_extract('src', ['rate_3'], type='float', alias='rate_3') }},
        {{ trx_json_extract('src', ['ratf_1'], type='int', alias='ratf_1') }},
        {{ trx_json_extract('src', ['ratf_2'], type='int', alias='ratf_2') }},
        {{ trx_json_extract('src', ['ratf_3'], type='int', alias='ratf_3') }},
        {{ trx_json_extract('src', ['eibc_1'], type='int', alias='eibc_1') }},
        {{ trx_json_extract('src', ['eibc_kw_1'], type='varchar', alias='eibc_kw_1') }},
        {{ trx_json_extract('src', ['eibc_2'], type='int', alias='eibc_2') }},
        {{ trx_json_extract('src', ['eibc_kw_2'], type='varchar', alias='eibc_kw_2') }},
        {{ trx_json_extract('src', ['eibc_3'], type='int', alias='eibc_3') }},
        {{ trx_json_extract('src', ['eibc_kw_3'], type='varchar', alias='eibc_kw_3') }},
        {{ trx_json_extract('src', ['amth_1'], type='float', alias='amth_1') }},
        {{ trx_json_extract('src', ['amth_2'], type='float', alias='amth_2') }},
        {{ trx_json_extract('src', ['amth_3'], type='float', alias='amth_3') }},
        {{ trx_json_extract('src', ['cuni'], type='varchar', alias='cuni') }},
        {{ trx_json_extract('src', ['nuni'], type='float', alias='nuni') }},
        {{ trx_json_extract('src', ['fyer'], type='int', alias='fyer') }},
        {{ trx_json_extract('src', ['fprd'], type='int', alias='fprd') }},
        {{ trx_json_extract('src', ['ryer'], type='int', alias='ryer') }},
        {{ trx_json_extract('src', ['rprd'], type='int', alias='rprd') }},
        {{ trx_json_extract('src', ['tyer'], type='int', alias='tyer') }},
        {{ trx_json_extract('src', ['tprd'], type='int', alias='tprd') }},
        {{ trx_json_extract('src', ['mscd'], type='varchar', alias='mscd') }},
        {{ trx_json_extract('src', ['msvs'], type='int', alias='msvs') }},
        {{ trx_json_extract('src', ['idtc_ref_compnr'], type='int', alias='idtc_ref_compnr') }},
        {{ trx_json_extract('src', ['rbon_ref_compnr'], type='int', alias='rbon_ref_compnr') }},
        {{ trx_json_extract('src', ['usgr_ref_compnr'], type='int', alias='usgr_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['cuni_ref_compnr'], type='int', alias='cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tfgld482') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'guid', 'dbcr']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
