{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN ticst002 Estimated and Actual Hours table, Generated 2026-04-10T19:41:46Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['pdno'], type='varchar', alias='pdno') }},
        {{ trx_json_extract('src', ['opno'], type='int', alias='opno') }},
        {{ trx_json_extract('src', ['tano'], type='varchar', alias='tano') }},
        {{ trx_json_extract('src', ['cwoc'], type='varchar', alias='cwoc') }},
        {{ trx_json_extract('src', ['mcno'], type='varchar', alias='mcno') }},
        {{ trx_json_extract('src', ['oprc'], type='varchar', alias='oprc') }},
        {{ trx_json_extract('src', ['prte'], type='float', alias='prte') }},
        {{ trx_json_extract('src', ['rutm'], type='float', alias='rutm') }},
        {{ trx_json_extract('src', ['sutm'], type='float', alias='sutm') }},
        {{ trx_json_extract('src', ['subr'], type='float', alias='subr') }},
        {{ trx_json_extract('src', ['most'], type='float', alias='most') }},
        {{ trx_json_extract('src', ['mopr'], type='float', alias='mopr') }},
        {{ trx_json_extract('src', ['mcoc'], type='float', alias='mcoc') }},
        {{ trx_json_extract('src', ['nomc'], type='int', alias='nomc') }},
        {{ trx_json_extract('src', ['bpid'], type='varchar', alias='bpid') }},
        {{ trx_json_extract('src', ['qpln'], type='float', alias='qpln') }},
        {{ trx_json_extract('src', ['qcmp'], type='float', alias='qcmp') }},
        {{ trx_json_extract('src', ['qrjc'], type='float', alias='qrjc') }},
        {{ trx_json_extract('src', ['qqar'], type='float', alias='qqar') }},
        {{ trx_json_extract('src', ['cums'], type='float', alias='cums') }},
        {{ trx_json_extract('src', ['scpq'], type='float', alias='scpq') }},
        {{ trx_json_extract('src', ['yldp'], type='float', alias='yldp') }},
        {{ trx_json_extract('src', ['hrem'], type='float', alias='hrem') }},
        {{ trx_json_extract('src', ['hrmc'], type='float', alias='hrmc') }},
        {{ trx_json_extract('src', ['eshm'], type='float', alias='eshm') }},
        {{ trx_json_extract('src', ['eshc'], type='float', alias='eshc') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['wgcs_1'], type='float', alias='wgcs_1') }},
        {{ trx_json_extract('src', ['wgcs_2'], type='float', alias='wgcs_2') }},
        {{ trx_json_extract('src', ['wgcs_3'], type='float', alias='wgcs_3') }},
        {{ trx_json_extract('src', ['mccs_1'], type='float', alias='mccs_1') }},
        {{ trx_json_extract('src', ['mccs_2'], type='float', alias='mccs_2') }},
        {{ trx_json_extract('src', ['mccs_3'], type='float', alias='mccs_3') }},
        {{ trx_json_extract('src', ['ohcs_1'], type='float', alias='ohcs_1') }},
        {{ trx_json_extract('src', ['ohcs_2'], type='float', alias='ohcs_2') }},
        {{ trx_json_extract('src', ['ohcs_3'], type='float', alias='ohcs_3') }},
        {{ trx_json_extract('src', ['sccs_1'], type='float', alias='sccs_1') }},
        {{ trx_json_extract('src', ['sccs_2'], type='float', alias='sccs_2') }},
        {{ trx_json_extract('src', ['sccs_3'], type='float', alias='sccs_3') }},
        {{ trx_json_extract('src', ['ahma'], type='float', alias='ahma') }},
        {{ trx_json_extract('src', ['ahws'], type='float', alias='ahws') }},
        {{ trx_json_extract('src', ['ahwq'], type='float', alias='ahwq') }},
        {{ trx_json_extract('src', ['ahmc'], type='float', alias='ahmc') }},
        {{ trx_json_extract('src', ['ahms'], type='float', alias='ahms') }},
        {{ trx_json_extract('src', ['ahmq'], type='float', alias='ahmq') }},
        {{ trx_json_extract('src', ['ashm'], type='float', alias='ashm') }},
        {{ trx_json_extract('src', ['ashs'], type='float', alias='ashs') }},
        {{ trx_json_extract('src', ['ashq'], type='float', alias='ashq') }},
        {{ trx_json_extract('src', ['ashc'], type='float', alias='ashc') }},
        {{ trx_json_extract('src', ['asms'], type='float', alias='asms') }},
        {{ trx_json_extract('src', ['asmq'], type='float', alias='asmq') }},
        {{ trx_json_extract('src', ['amcc_1'], type='float', alias='amcc_1') }},
        {{ trx_json_extract('src', ['amcc_2'], type='float', alias='amcc_2') }},
        {{ trx_json_extract('src', ['amcc_3'], type='float', alias='amcc_3') }},
        {{ trx_json_extract('src', ['aohc_1'], type='float', alias='aohc_1') }},
        {{ trx_json_extract('src', ['aohc_2'], type='float', alias='aohc_2') }},
        {{ trx_json_extract('src', ['aohc_3'], type='float', alias='aohc_3') }},
        {{ trx_json_extract('src', ['awgc_1'], type='float', alias='awgc_1') }},
        {{ trx_json_extract('src', ['awgc_2'], type='float', alias='awgc_2') }},
        {{ trx_json_extract('src', ['awgc_3'], type='float', alias='awgc_3') }},
        {{ trx_json_extract('src', ['ascc_1'], type='float', alias='ascc_1') }},
        {{ trx_json_extract('src', ['ascc_2'], type='float', alias='ascc_2') }},
        {{ trx_json_extract('src', ['ascc_3'], type='float', alias='ascc_3') }},
        {{ trx_json_extract('src', ['ascq_1'], type='float', alias='ascq_1') }},
        {{ trx_json_extract('src', ['ascq_2'], type='float', alias='ascq_2') }},
        {{ trx_json_extract('src', ['ascq_3'], type='float', alias='ascq_3') }},
        {{ trx_json_extract('src', ['runi'], type='float', alias='runi') }},
        {{ trx_json_extract('src', ['cmdt'], type='timestamp_ntz', alias='cmdt') }},
        {{ trx_json_extract('src', ['pcdt'], type='timestamp_ntz', alias='pcdt') }},
        {{ trx_json_extract('src', ['fdur'], type='int', alias='fdur') }},
        {{ trx_json_extract('src', ['fdur_kw'], type='varchar', alias='fdur_kw') }},
        {{ trx_json_extract('src', ['cowc'], type='varchar', alias='cowc') }},
        {{ trx_json_extract('src', ['frso'], type='int', alias='frso') }},
        {{ trx_json_extract('src', ['frso_kw'], type='varchar', alias='frso_kw') }},
        {{ trx_json_extract('src', ['pdno_ref_compnr'], type='int', alias='pdno_ref_compnr') }},
        {{ trx_json_extract('src', ['cwoc_ref_compnr'], type='int', alias='cwoc_ref_compnr') }},
        {{ trx_json_extract('src', ['oprc_ref_compnr'], type='int', alias='oprc_ref_compnr') }},
        {{ trx_json_extract('src', ['bpid_ref_compnr'], type='int', alias='bpid_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['wgcs_lclc'], type='float', alias='wgcs_lclc') }},
        {{ trx_json_extract('src', ['wgcs_rpc1'], type='float', alias='wgcs_rpc1') }},
        {{ trx_json_extract('src', ['wgcs_rpc2'], type='float', alias='wgcs_rpc2') }},
        {{ trx_json_extract('src', ['wgcs_refc'], type='float', alias='wgcs_refc') }},
        {{ trx_json_extract('src', ['wgcs_dwhc'], type='float', alias='wgcs_dwhc') }},
        {{ trx_json_extract('src', ['mccs_lclc'], type='float', alias='mccs_lclc') }},
        {{ trx_json_extract('src', ['mccs_rpc1'], type='float', alias='mccs_rpc1') }},
        {{ trx_json_extract('src', ['mccs_rpc2'], type='float', alias='mccs_rpc2') }},
        {{ trx_json_extract('src', ['mccs_refc'], type='float', alias='mccs_refc') }},
        {{ trx_json_extract('src', ['mccs_dwhc'], type='float', alias='mccs_dwhc') }},
        {{ trx_json_extract('src', ['ohcs_lclc'], type='float', alias='ohcs_lclc') }},
        {{ trx_json_extract('src', ['ohcs_rpc1'], type='float', alias='ohcs_rpc1') }},
        {{ trx_json_extract('src', ['ohcs_rpc2'], type='float', alias='ohcs_rpc2') }},
        {{ trx_json_extract('src', ['ohcs_refc'], type='float', alias='ohcs_refc') }},
        {{ trx_json_extract('src', ['ohcs_dwhc'], type='float', alias='ohcs_dwhc') }},
        {{ trx_json_extract('src', ['sccs_lclc'], type='float', alias='sccs_lclc') }},
        {{ trx_json_extract('src', ['sccs_rpc1'], type='float', alias='sccs_rpc1') }},
        {{ trx_json_extract('src', ['sccs_rpc2'], type='float', alias='sccs_rpc2') }},
        {{ trx_json_extract('src', ['sccs_refc'], type='float', alias='sccs_refc') }},
        {{ trx_json_extract('src', ['sccs_dwhc'], type='float', alias='sccs_dwhc') }},
        {{ trx_json_extract('src', ['amcc_lclc'], type='float', alias='amcc_lclc') }},
        {{ trx_json_extract('src', ['amcc_rpc1'], type='float', alias='amcc_rpc1') }},
        {{ trx_json_extract('src', ['amcc_rpc2'], type='float', alias='amcc_rpc2') }},
        {{ trx_json_extract('src', ['amcc_refc'], type='float', alias='amcc_refc') }},
        {{ trx_json_extract('src', ['amcc_dwhc'], type='float', alias='amcc_dwhc') }},
        {{ trx_json_extract('src', ['aohc_lclc'], type='float', alias='aohc_lclc') }},
        {{ trx_json_extract('src', ['aohc_rpc1'], type='float', alias='aohc_rpc1') }},
        {{ trx_json_extract('src', ['aohc_rpc2'], type='float', alias='aohc_rpc2') }},
        {{ trx_json_extract('src', ['aohc_refc'], type='float', alias='aohc_refc') }},
        {{ trx_json_extract('src', ['aohc_dwhc'], type='float', alias='aohc_dwhc') }},
        {{ trx_json_extract('src', ['awgc_lclc'], type='float', alias='awgc_lclc') }},
        {{ trx_json_extract('src', ['awgc_rpc1'], type='float', alias='awgc_rpc1') }},
        {{ trx_json_extract('src', ['awgc_rpc2'], type='float', alias='awgc_rpc2') }},
        {{ trx_json_extract('src', ['awgc_refc'], type='float', alias='awgc_refc') }},
        {{ trx_json_extract('src', ['awgc_dwhc'], type='float', alias='awgc_dwhc') }},
        {{ trx_json_extract('src', ['ascc_lclc'], type='float', alias='ascc_lclc') }},
        {{ trx_json_extract('src', ['ascc_rpc1'], type='float', alias='ascc_rpc1') }},
        {{ trx_json_extract('src', ['ascc_rpc2'], type='float', alias='ascc_rpc2') }},
        {{ trx_json_extract('src', ['ascc_refc'], type='float', alias='ascc_refc') }},
        {{ trx_json_extract('src', ['ascc_dwhc'], type='float', alias='ascc_dwhc') }},
        {{ trx_json_extract('src', ['ascq_lclc'], type='float', alias='ascq_lclc') }},
        {{ trx_json_extract('src', ['ascq_rpc1'], type='float', alias='ascq_rpc1') }},
        {{ trx_json_extract('src', ['ascq_rpc2'], type='float', alias='ascq_rpc2') }},
        {{ trx_json_extract('src', ['ascq_refc'], type='float', alias='ascq_refc') }},
        {{ trx_json_extract('src', ['ascq_dwhc'], type='float', alias='ascq_dwhc') }},
        {{ trx_json_extract('src', ['dptm_fcmp'], type='int', alias='dptm_fcmp') }},
        {{ trx_json_extract('src', ['scpq_buar'], type='float', alias='scpq_buar') }},
        {{ trx_json_extract('src', ['scpq_buln'], type='float', alias='scpq_buln') }},
        {{ trx_json_extract('src', ['scpq_bupc'], type='float', alias='scpq_bupc') }},
        {{ trx_json_extract('src', ['scpq_butm'], type='float', alias='scpq_butm') }},
        {{ trx_json_extract('src', ['scpq_buvl'], type='float', alias='scpq_buvl') }},
        {{ trx_json_extract('src', ['scpq_buwg'], type='float', alias='scpq_buwg') }},
        {{ trx_json_extract('src', ['qrjc_buar'], type='float', alias='qrjc_buar') }},
        {{ trx_json_extract('src', ['qrjc_buln'], type='float', alias='qrjc_buln') }},
        {{ trx_json_extract('src', ['qrjc_bupc'], type='float', alias='qrjc_bupc') }},
        {{ trx_json_extract('src', ['qrjc_butm'], type='float', alias='qrjc_butm') }},
        {{ trx_json_extract('src', ['qrjc_buvl'], type='float', alias='qrjc_buvl') }},
        {{ trx_json_extract('src', ['qrjc_buwg'], type='float', alias='qrjc_buwg') }},
        {{ trx_json_extract('src', ['qqar_buar'], type='float', alias='qqar_buar') }},
        {{ trx_json_extract('src', ['qqar_buln'], type='float', alias='qqar_buln') }},
        {{ trx_json_extract('src', ['qqar_bupc'], type='float', alias='qqar_bupc') }},
        {{ trx_json_extract('src', ['qqar_butm'], type='float', alias='qqar_butm') }},
        {{ trx_json_extract('src', ['qqar_buvl'], type='float', alias='qqar_buvl') }},
        {{ trx_json_extract('src', ['qqar_buwg'], type='float', alias='qqar_buwg') }},
        {{ trx_json_extract('src', ['mcno_ref_compnr'], type='int', alias='mcno_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_ticst002') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'pdno', 'opno']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
