{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tppdm001 User Profiles table, Generated 2026-04-10T19:41:52Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['loco'], type='varchar', alias='loco') }},
        {{ trx_json_extract('src', ['udpr'], type='int', alias='udpr') }},
        {{ trx_json_extract('src', ['udpr_kw'], type='varchar', alias='udpr_kw') }},
        {{ trx_json_extract('src', ['cprj'], type='varchar', alias='cprj') }},
        {{ trx_json_extract('src', ['udsp'], type='int', alias='udsp') }},
        {{ trx_json_extract('src', ['udsp_kw'], type='varchar', alias='udsp_kw') }},
        {{ trx_json_extract('src', ['cspa'], type='varchar', alias='cspa') }},
        {{ trx_json_extract('src', ['udpl'], type='int', alias='udpl') }},
        {{ trx_json_extract('src', ['udpl_kw'], type='varchar', alias='udpl_kw') }},
        {{ trx_json_extract('src', ['cpla'], type='varchar', alias='cpla') }},
        {{ trx_json_extract('src', ['udac'], type='int', alias='udac') }},
        {{ trx_json_extract('src', ['udac_kw'], type='varchar', alias='udac_kw') }},
        {{ trx_json_extract('src', ['cact'], type='varchar', alias='cact') }},
        {{ trx_json_extract('src', ['whng'], type='varchar', alias='whng') }},
        {{ trx_json_extract('src', ['whsr'], type='varchar', alias='whsr') }},
        {{ trx_json_extract('src', ['pung'], type='varchar', alias='pung') }},
        {{ trx_json_extract('src', ['pusr'], type='varchar', alias='pusr') }},
        {{ trx_json_extract('src', ['song'], type='varchar', alias='song') }},
        {{ trx_json_extract('src', ['sosr'], type='varchar', alias='sosr') }},
        {{ trx_json_extract('src', ['erng'], type='varchar', alias='erng') }},
        {{ trx_json_extract('src', ['ersr'], type='varchar', alias='ersr') }},
        {{ trx_json_extract('src', ['ctng'], type='varchar', alias='ctng') }},
        {{ trx_json_extract('src', ['ctsr'], type='varchar', alias='ctsr') }},
        {{ trx_json_extract('src', ['ngrp'], type='varchar', alias='ngrp') }},
        {{ trx_json_extract('src', ['prsr'], type='varchar', alias='prsr') }},
        {{ trx_json_extract('src', ['ests'], type='varchar', alias='ests') }},
        {{ trx_json_extract('src', ['serr'], type='varchar', alias='serr') }},
        {{ trx_json_extract('src', ['dsct'], type='int', alias='dsct') }},
        {{ trx_json_extract('src', ['dsct_kw'], type='varchar', alias='dsct_kw') }},
        {{ trx_json_extract('src', ['asct'], type='int', alias='asct') }},
        {{ trx_json_extract('src', ['asct_kw'], type='varchar', alias='asct_kw') }},
        {{ trx_json_extract('src', ['mpvw'], type='int', alias='mpvw') }},
        {{ trx_json_extract('src', ['mpvw_kw'], type='varchar', alias='mpvw_kw') }},
        {{ trx_json_extract('src', ['olvl'], type='int', alias='olvl') }},
        {{ trx_json_extract('src', ['tpte'], type='varchar', alias='tpte') }},
        {{ trx_json_extract('src', ['udev'], type='int', alias='udev') }},
        {{ trx_json_extract('src', ['udev_kw'], type='varchar', alias='udev_kw') }},
        {{ trx_json_extract('src', ['vers'], type='varchar', alias='vers') }},
        {{ trx_json_extract('src', ['tgrp'], type='varchar', alias='tgrp') }},
        {{ trx_json_extract('src', ['tpsr'], type='varchar', alias='tpsr') }},
        {{ trx_json_extract('src', ['dfet'], type='int', alias='dfet') }},
        {{ trx_json_extract('src', ['dfet_kw'], type='varchar', alias='dfet_kw') }},
        {{ trx_json_extract('src', ['dflv'], type='int', alias='dflv') }},
        {{ trx_json_extract('src', ['dflv_kw'], type='varchar', alias='dflv_kw') }},
        {{ trx_json_extract('src', ['dcty'], type='int', alias='dcty') }},
        {{ trx_json_extract('src', ['dcty_kw'], type='varchar', alias='dcty_kw') }},
        {{ trx_json_extract('src', ['prim'], type='int', alias='prim') }},
        {{ trx_json_extract('src', ['prim_kw'], type='varchar', alias='prim_kw') }},
        {{ trx_json_extract('src', ['delt'], type='int', alias='delt') }},
        {{ trx_json_extract('src', ['delt_kw'], type='varchar', alias='delt_kw') }},
        {{ trx_json_extract('src', ['mnvf'], type='int', alias='mnvf') }},
        {{ trx_json_extract('src', ['mnvf_kw'], type='varchar', alias='mnvf_kw') }},
        {{ trx_json_extract('src', ['aagt'], type='int', alias='aagt') }},
        {{ trx_json_extract('src', ['aagt_kw'], type='varchar', alias='aagt_kw') }},
        {{ trx_json_extract('src', ['potp'], type='varchar', alias='potp') }},
        {{ trx_json_extract('src', ['cofc'], type='varchar', alias='cofc') }},
        {{ trx_json_extract('src', ['rlcr'], type='int', alias='rlcr') }},
        {{ trx_json_extract('src', ['rlcr_kw'], type='varchar', alias='rlcr_kw') }},
        {{ trx_json_extract('src', ['rlgn'], type='int', alias='rlgn') }},
        {{ trx_json_extract('src', ['rlgn_kw'], type='varchar', alias='rlgn_kw') }},
        {{ trx_json_extract('src', ['tprf'], type='int', alias='tprf') }},
        {{ trx_json_extract('src', ['tprf_kw'], type='varchar', alias='tprf_kw') }},
        {{ trx_json_extract('src', ['sdnr'], type='varchar', alias='sdnr') }},
        {{ trx_json_extract('src', ['sdsr'], type='varchar', alias='sdsr') }},
        {{ trx_json_extract('src', ['apnr'], type='varchar', alias='apnr') }},
        {{ trx_json_extract('src', ['apsr'], type='varchar', alias='apsr') }},
        {{ trx_json_extract('src', ['prcv'], type='int', alias='prcv') }},
        {{ trx_json_extract('src', ['prcv_kw'], type='varchar', alias='prcv_kw') }},
        {{ trx_json_extract('src', ['svsr'], type='varchar', alias='svsr') }},
        {{ trx_json_extract('src', ['conr'], type='varchar', alias='conr') }},
        {{ trx_json_extract('src', ['cosr'], type='varchar', alias='cosr') }},
        {{ trx_json_extract('src', ['cprj_cpla_cact_ref_compnr'], type='int', alias='cprj_cpla_cact_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_cpla_ref_compnr'], type='int', alias='cprj_cpla_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_vers_ref_compnr'], type='int', alias='cprj_vers_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_ref_compnr'], type='int', alias='cprj_ref_compnr') }},
        {{ trx_json_extract('src', ['cspa_ref_compnr'], type='int', alias='cspa_ref_compnr') }},
        {{ trx_json_extract('src', ['whng_whsr_ref_compnr'], type='int', alias='whng_whsr_ref_compnr') }},
        {{ trx_json_extract('src', ['whng_ref_compnr'], type='int', alias='whng_ref_compnr') }},
        {{ trx_json_extract('src', ['pung_pusr_ref_compnr'], type='int', alias='pung_pusr_ref_compnr') }},
        {{ trx_json_extract('src', ['pung_ref_compnr'], type='int', alias='pung_ref_compnr') }},
        {{ trx_json_extract('src', ['song_sosr_ref_compnr'], type='int', alias='song_sosr_ref_compnr') }},
        {{ trx_json_extract('src', ['song_ref_compnr'], type='int', alias='song_ref_compnr') }},
        {{ trx_json_extract('src', ['erng_ersr_ref_compnr'], type='int', alias='erng_ersr_ref_compnr') }},
        {{ trx_json_extract('src', ['erng_ref_compnr'], type='int', alias='erng_ref_compnr') }},
        {{ trx_json_extract('src', ['ctng_ctsr_ref_compnr'], type='int', alias='ctng_ctsr_ref_compnr') }},
        {{ trx_json_extract('src', ['ctng_ref_compnr'], type='int', alias='ctng_ref_compnr') }},
        {{ trx_json_extract('src', ['ngrp_prsr_ref_compnr'], type='int', alias='ngrp_prsr_ref_compnr') }},
        {{ trx_json_extract('src', ['ngrp_ests_ref_compnr'], type='int', alias='ngrp_ests_ref_compnr') }},
        {{ trx_json_extract('src', ['ngrp_ref_compnr'], type='int', alias='ngrp_ref_compnr') }},
        {{ trx_json_extract('src', ['tpte_ref_compnr'], type='int', alias='tpte_ref_compnr') }},
        {{ trx_json_extract('src', ['tgrp_tpsr_ref_compnr'], type='int', alias='tgrp_tpsr_ref_compnr') }},
        {{ trx_json_extract('src', ['tgrp_ref_compnr'], type='int', alias='tgrp_ref_compnr') }},
        {{ trx_json_extract('src', ['potp_ref_compnr'], type='int', alias='potp_ref_compnr') }},
        {{ trx_json_extract('src', ['cofc_ref_compnr'], type='int', alias='cofc_ref_compnr') }},
        {{ trx_json_extract('src', ['sdnr_ref_compnr'], type='int', alias='sdnr_ref_compnr') }},
        {{ trx_json_extract('src', ['apnr_ref_compnr'], type='int', alias='apnr_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tppdm001') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'loco']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
