{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tppdm635 Project Subcontracting table, Generated 2026-04-10T19:42:01Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['cprj'], type='varchar', alias='cprj') }},
        {{ trx_json_extract('src', ['csub'], type='varchar', alias='csub') }},
        {{ trx_json_extract('src', ['desc', 'en_US'], type='varchar', alias='desc__en_us') }},
        {{ trx_json_extract('src', ['seak', 'en_US'], type='varchar', alias='seak__en_us') }},
        {{ trx_json_extract('src', ['dfsb'], type='varchar', alias='dfsb') }},
        {{ trx_json_extract('src', ['citg'], type='varchar', alias='citg') }},
        {{ trx_json_extract('src', ['csel'], type='varchar', alias='csel') }},
        {{ trx_json_extract('src', ['csig'], type='varchar', alias='csig') }},
        {{ trx_json_extract('src', ['uset'], type='varchar', alias='uset') }},
        {{ trx_json_extract('src', ['cuni'], type='varchar', alias='cuni') }},
        {{ trx_json_extract('src', ['cuti'], type='varchar', alias='cuti') }},
        {{ trx_json_extract('src', ['pric'], type='float', alias='pric') }},
        {{ trx_json_extract('src', ['cccp'], type='varchar', alias='cccp') }},
        {{ trx_json_extract('src', ['prip'], type='float', alias='prip') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['pris'], type='float', alias='pris') }},
        {{ trx_json_extract('src', ['ccsp'], type='varchar', alias='ccsp') }},
        {{ trx_json_extract('src', ['csgp'], type='varchar', alias='csgp') }},
        {{ trx_json_extract('src', ['csgs'], type='varchar', alias='csgs') }},
        {{ trx_json_extract('src', ['dfpc'], type='int', alias='dfpc') }},
        {{ trx_json_extract('src', ['dfpc_kw'], type='varchar', alias='dfpc_kw') }},
        {{ trx_json_extract('src', ['dfpp'], type='int', alias='dfpp') }},
        {{ trx_json_extract('src', ['dfpp_kw'], type='varchar', alias='dfpp_kw') }},
        {{ trx_json_extract('src', ['dfps'], type='int', alias='dfps') }},
        {{ trx_json_extract('src', ['dfps_kw'], type='varchar', alias='dfps_kw') }},
        {{ trx_json_extract('src', ['ltpc'], type='timestamp_ntz', alias='ltpc') }},
        {{ trx_json_extract('src', ['ltpp'], type='timestamp_ntz', alias='ltpp') }},
        {{ trx_json_extract('src', ['ccsb'], type='varchar', alias='ccsb') }},
        {{ trx_json_extract('src', ['ccfu'], type='int', alias='ccfu') }},
        {{ trx_json_extract('src', ['ccfu_kw'], type='varchar', alias='ccfu_kw') }},
        {{ trx_json_extract('src', ['ltps'], type='timestamp_ntz', alias='ltps') }},
        {{ trx_json_extract('src', ['ccco'], type='varchar', alias='ccco') }},
        {{ trx_json_extract('src', ['pwgc'], type='float', alias='pwgc') }},
        {{ trx_json_extract('src', ['dsbc'], type='int', alias='dsbc') }},
        {{ trx_json_extract('src', ['dsbc_kw'], type='varchar', alias='dsbc_kw') }},
        {{ trx_json_extract('src', ['buni'], type='int', alias='buni') }},
        {{ trx_json_extract('src', ['buni_kw'], type='varchar', alias='buni_kw') }},
        {{ trx_json_extract('src', ['cvat'], type='varchar', alias='cvat') }},
        {{ trx_json_extract('src', ['prby'], type='int', alias='prby') }},
        {{ trx_json_extract('src', ['prby_kw'], type='varchar', alias='prby_kw') }},
        {{ trx_json_extract('src', ['srtr'], type='varchar', alias='srtr') }},
        {{ trx_json_extract('src', ['otbp'], type='varchar', alias='otbp') }},
        {{ trx_json_extract('src', ['osys'], type='int', alias='osys') }},
        {{ trx_json_extract('src', ['osys_kw'], type='varchar', alias='osys_kw') }},
        {{ trx_json_extract('src', ['prre'], type='int', alias='prre') }},
        {{ trx_json_extract('src', ['prre_kw'], type='varchar', alias='prre_kw') }},
        {{ trx_json_extract('src', ['cpgp'], type='varchar', alias='cpgp') }},
        {{ trx_json_extract('src', ['cpgs'], type='varchar', alias='cpgs') }},
        {{ trx_json_extract('src', ['cppp'], type='int', alias='cppp') }},
        {{ trx_json_extract('src', ['cppp_kw'], type='varchar', alias='cppp_kw') }},
        {{ trx_json_extract('src', ['oltm'], type='int', alias='oltm') }},
        {{ trx_json_extract('src', ['pcmc_1'], type='float', alias='pcmc_1') }},
        {{ trx_json_extract('src', ['pcmc_2'], type='float', alias='pcmc_2') }},
        {{ trx_json_extract('src', ['pcmc_3'], type='float', alias='pcmc_3') }},
        {{ trx_json_extract('src', ['ppmc_1'], type='float', alias='ppmc_1') }},
        {{ trx_json_extract('src', ['ppmc_2'], type='float', alias='ppmc_2') }},
        {{ trx_json_extract('src', ['ppmc_3'], type='float', alias='ppmc_3') }},
        {{ trx_json_extract('src', ['psmc_1'], type='float', alias='psmc_1') }},
        {{ trx_json_extract('src', ['psmc_2'], type='float', alias='psmc_2') }},
        {{ trx_json_extract('src', ['psmc_3'], type='float', alias='psmc_3') }},
        {{ trx_json_extract('src', ['svat'], type='varchar', alias='svat') }},
        {{ trx_json_extract('src', ['blbl'], type='int', alias='blbl') }},
        {{ trx_json_extract('src', ['blbl_kw'], type='varchar', alias='blbl_kw') }},
        {{ trx_json_extract('src', ['cood'], type='varchar', alias='cood') }},
        {{ trx_json_extract('src', ['ccde'], type='varchar', alias='ccde') }},
        {{ trx_json_extract('src', ['rdpt'], type='varchar', alias='rdpt') }},
        {{ trx_json_extract('src', ['plid'], type='varchar', alias='plid') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['cprj_ref_compnr'], type='int', alias='cprj_ref_compnr') }},
        {{ trx_json_extract('src', ['dfsb_ref_compnr'], type='int', alias='dfsb_ref_compnr') }},
        {{ trx_json_extract('src', ['citg_ref_compnr'], type='int', alias='citg_ref_compnr') }},
        {{ trx_json_extract('src', ['csel_ref_compnr'], type='int', alias='csel_ref_compnr') }},
        {{ trx_json_extract('src', ['csig_ref_compnr'], type='int', alias='csig_ref_compnr') }},
        {{ trx_json_extract('src', ['uset_cuni_ref_compnr'], type='int', alias='uset_cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['uset_ref_compnr'], type='int', alias='uset_ref_compnr') }},
        {{ trx_json_extract('src', ['cuni_ref_compnr'], type='int', alias='cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['cuti_ref_compnr'], type='int', alias='cuti_ref_compnr') }},
        {{ trx_json_extract('src', ['cccp_ref_compnr'], type='int', alias='cccp_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['ccsp_ref_compnr'], type='int', alias='ccsp_ref_compnr') }},
        {{ trx_json_extract('src', ['csgp_ref_compnr'], type='int', alias='csgp_ref_compnr') }},
        {{ trx_json_extract('src', ['csgs_ref_compnr'], type='int', alias='csgs_ref_compnr') }},
        {{ trx_json_extract('src', ['ccco_ref_compnr'], type='int', alias='ccco_ref_compnr') }},
        {{ trx_json_extract('src', ['cvat_ref_compnr'], type='int', alias='cvat_ref_compnr') }},
        {{ trx_json_extract('src', ['srtr_ref_compnr'], type='int', alias='srtr_ref_compnr') }},
        {{ trx_json_extract('src', ['otbp_ref_compnr'], type='int', alias='otbp_ref_compnr') }},
        {{ trx_json_extract('src', ['cpgp_ref_compnr'], type='int', alias='cpgp_ref_compnr') }},
        {{ trx_json_extract('src', ['cpgs_ref_compnr'], type='int', alias='cpgs_ref_compnr') }},
        {{ trx_json_extract('src', ['svat_ref_compnr'], type='int', alias='svat_ref_compnr') }},
        {{ trx_json_extract('src', ['cood_ref_compnr'], type='int', alias='cood_ref_compnr') }},
        {{ trx_json_extract('src', ['ccde_ref_compnr'], type='int', alias='ccde_ref_compnr') }},
        {{ trx_json_extract('src', ['rdpt_ref_compnr'], type='int', alias='rdpt_ref_compnr') }},
        {{ trx_json_extract('src', ['plid_ref_compnr'], type='int', alias='plid_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['csub_rcmp'], type='int', alias='csub_rcmp') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tppdm635') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'cprj', 'csub']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
