{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tpppc271 Subcontracting Costs table, Generated 2026-04-10T19:42:10Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['cprj'], type='varchar', alias='cprj') }},
        {{ trx_json_extract('src', ['csub'], type='varchar', alias='csub') }},
        {{ trx_json_extract('src', ['sern'], type='int', alias='sern') }},
        {{ trx_json_extract('src', ['cspa'], type='varchar', alias='cspa') }},
        {{ trx_json_extract('src', ['cpla'], type='varchar', alias='cpla') }},
        {{ trx_json_extract('src', ['cact'], type='varchar', alias='cact') }},
        {{ trx_json_extract('src', ['ltdt'], type='timestamp_ntz', alias='ltdt') }},
        {{ trx_json_extract('src', ['rgdt'], type='timestamp_ntz', alias='rgdt') }},
        {{ trx_json_extract('src', ['quan'], type='float', alias='quan') }},
        {{ trx_json_extract('src', ['cuni'], type='varchar', alias='cuni') }},
        {{ trx_json_extract('src', ['pric'], type='float', alias='pric') }},
        {{ trx_json_extract('src', ['amoc'], type='float', alias='amoc') }},
        {{ trx_json_extract('src', ['rtcc_1'], type='float', alias='rtcc_1') }},
        {{ trx_json_extract('src', ['rtcc_2'], type='float', alias='rtcc_2') }},
        {{ trx_json_extract('src', ['rtcc_3'], type='float', alias='rtcc_3') }},
        {{ trx_json_extract('src', ['rtfc_1'], type='int', alias='rtfc_1') }},
        {{ trx_json_extract('src', ['rtfc_2'], type='int', alias='rtfc_2') }},
        {{ trx_json_extract('src', ['rtfc_3'], type='int', alias='rtfc_3') }},
        {{ trx_json_extract('src', ['cohd_1'], type='float', alias='cohd_1') }},
        {{ trx_json_extract('src', ['cohd_2'], type='float', alias='cohd_2') }},
        {{ trx_json_extract('src', ['cohd_3'], type='float', alias='cohd_3') }},
        {{ trx_json_extract('src', ['curc'], type='varchar', alias='curc') }},
        {{ trx_json_extract('src', ['pris'], type='float', alias='pris') }},
        {{ trx_json_extract('src', ['amos'], type='float', alias='amos') }},
        {{ trx_json_extract('src', ['rtcs_1'], type='float', alias='rtcs_1') }},
        {{ trx_json_extract('src', ['rtcs_2'], type='float', alias='rtcs_2') }},
        {{ trx_json_extract('src', ['rtcs_3'], type='float', alias='rtcs_3') }},
        {{ trx_json_extract('src', ['rtfs_1'], type='int', alias='rtfs_1') }},
        {{ trx_json_extract('src', ['rtfs_2'], type='int', alias='rtfs_2') }},
        {{ trx_json_extract('src', ['rtfs_3'], type='int', alias='rtfs_3') }},
        {{ trx_json_extract('src', ['curs'], type='varchar', alias='curs') }},
        {{ trx_json_extract('src', ['cdoc', 'en_US'], type='varchar', alias='cdoc__en_us') }},
        {{ trx_json_extract('src', ['desc', 'en_US'], type='varchar', alias='desc__en_us') }},
        {{ trx_json_extract('src', ['cptc'], type='varchar', alias='cptc') }},
        {{ trx_json_extract('src', ['year'], type='int', alias='year') }},
        {{ trx_json_extract('src', ['peri'], type='int', alias='peri') }},
        {{ trx_json_extract('src', ['cptf'], type='varchar', alias='cptf') }},
        {{ trx_json_extract('src', ['fyea'], type='int', alias='fyea') }},
        {{ trx_json_extract('src', ['fper'], type='int', alias='fper') }},
        {{ trx_json_extract('src', ['ryea'], type='int', alias='ryea') }},
        {{ trx_json_extract('src', ['rper'], type='int', alias='rper') }},
        {{ trx_json_extract('src', ['otbp'], type='varchar', alias='otbp') }},
        {{ trx_json_extract('src', ['ifbp'], type='varchar', alias='ifbp') }},
        {{ trx_json_extract('src', ['orno'], type='varchar', alias='orno') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['srnb'], type='int', alias='srnb') }},
        {{ trx_json_extract('src', ['srni'], type='int', alias='srni') }},
        {{ trx_json_extract('src', ['cfpo'], type='int', alias='cfpo') }},
        {{ trx_json_extract('src', ['cfpo_kw'], type='varchar', alias='cfpo_kw') }},
        {{ trx_json_extract('src', ['potf'], type='int', alias='potf') }},
        {{ trx_json_extract('src', ['potf_kw'], type='varchar', alias='potf_kw') }},
        {{ trx_json_extract('src', ['cstl'], type='varchar', alias='cstl') }},
        {{ trx_json_extract('src', ['tetf'], type='int', alias='tetf') }},
        {{ trx_json_extract('src', ['tetf_kw'], type='varchar', alias='tetf_kw') }},
        {{ trx_json_extract('src', ['ccco'], type='varchar', alias='ccco') }},
        {{ trx_json_extract('src', ['ncmp'], type='int', alias='ncmp') }},
        {{ trx_json_extract('src', ['entu'], type='varchar', alias='entu') }},
        {{ trx_json_extract('src', ['ftty'], type='varchar', alias='ftty') }},
        {{ trx_json_extract('src', ['fdoc'], type='int', alias='fdoc') }},
        {{ trx_json_extract('src', ['flin'], type='int', alias='flin') }},
        {{ trx_json_extract('src', ['fsrl'], type='int', alias='fsrl') }},
        {{ trx_json_extract('src', ['ftln'], type='int', alias='ftln') }},
        {{ trx_json_extract('src', ['loco'], type='varchar', alias='loco') }},
        {{ trx_json_extract('src', ['sttl'], type='int', alias='sttl') }},
        {{ trx_json_extract('src', ['sttl_kw'], type='varchar', alias='sttl_kw') }},
        {{ trx_json_extract('src', ['rdat'], type='timestamp_ntz', alias='rdat') }},
        {{ trx_json_extract('src', ['rdas'], type='timestamp_ntz', alias='rdas') }},
        {{ trx_json_extract('src', ['rtyp'], type='varchar', alias='rtyp') }},
        {{ trx_json_extract('src', ['fcrt'], type='int', alias='fcrt') }},
        {{ trx_json_extract('src', ['fcrt_kw'], type='varchar', alias='fcrt_kw') }},
        {{ trx_json_extract('src', ['blbl'], type='int', alias='blbl') }},
        {{ trx_json_extract('src', ['blbl_kw'], type='varchar', alias='blbl_kw') }},
        {{ trx_json_extract('src', ['guid'], type='varchar', alias='guid') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['cdf_sref', 'en_US'], type='varchar', alias='cdf_sref__en_us') }},
        {{ trx_json_extract('src', ['cdf_susr', 'en_US'], type='varchar', alias='cdf_susr__en_us') }},
        {{ trx_json_extract('src', ['cprj_cstl_ref_compnr'], type='int', alias='cprj_cstl_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_cspa_ref_compnr'], type='int', alias='cprj_cspa_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_cpla_cact_ref_compnr'], type='int', alias='cprj_cpla_cact_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_ref_compnr'], type='int', alias='cprj_ref_compnr') }},
        {{ trx_json_extract('src', ['cuni_ref_compnr'], type='int', alias='cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['curc_ref_compnr'], type='int', alias='curc_ref_compnr') }},
        {{ trx_json_extract('src', ['curs_ref_compnr'], type='int', alias='curs_ref_compnr') }},
        {{ trx_json_extract('src', ['cdoc_ref_compnr'], type='int', alias='cdoc_ref_compnr') }},
        {{ trx_json_extract('src', ['cptc_year_peri_ref_compnr'], type='int', alias='cptc_year_peri_ref_compnr') }},
        {{ trx_json_extract('src', ['cptc_ref_compnr'], type='int', alias='cptc_ref_compnr') }},
        {{ trx_json_extract('src', ['cptf_fyea_fper_ref_compnr'], type='int', alias='cptf_fyea_fper_ref_compnr') }},
        {{ trx_json_extract('src', ['cptf_ref_compnr'], type='int', alias='cptf_ref_compnr') }},
        {{ trx_json_extract('src', ['otbp_ref_compnr'], type='int', alias='otbp_ref_compnr') }},
        {{ trx_json_extract('src', ['ifbp_ref_compnr'], type='int', alias='ifbp_ref_compnr') }},
        {{ trx_json_extract('src', ['ccco_ref_compnr'], type='int', alias='ccco_ref_compnr') }},
        {{ trx_json_extract('src', ['rtyp_ref_compnr'], type='int', alias='rtyp_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tpppc271') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'cprj', 'csub', 'sern']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
