{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tpptc120 Material Budget Lines table, Generated 2026-04-10T19:42:21Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['cprj'], type='varchar', alias='cprj') }},
        {{ trx_json_extract('src', ['cspa'], type='varchar', alias='cspa') }},
        {{ trx_json_extract('src', ['sern'], type='int', alias='sern') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['effn'], type='int', alias='effn') }},
        {{ trx_json_extract('src', ['ccco'], type='varchar', alias='ccco') }},
        {{ trx_json_extract('src', ['cstl'], type='varchar', alias='cstl') }},
        {{ trx_json_extract('src', ['leng'], type='float', alias='leng') }},
        {{ trx_json_extract('src', ['widt'], type='float', alias='widt') }},
        {{ trx_json_extract('src', ['noun'], type='int', alias='noun') }},
        {{ trx_json_extract('src', ['quan'], type='float', alias='quan') }},
        {{ trx_json_extract('src', ['cuni'], type='varchar', alias='cuni') }},
        {{ trx_json_extract('src', ['scpf'], type='float', alias='scpf') }},
        {{ trx_json_extract('src', ['clas'], type='varchar', alias='clas') }},
        {{ trx_json_extract('src', ['lcta'], type='float', alias='lcta') }},
        {{ trx_json_extract('src', ['amoc'], type='float', alias='amoc') }},
        {{ trx_json_extract('src', ['cocu'], type='varchar', alias='cocu') }},
        {{ trx_json_extract('src', ['pric'], type='float', alias='pric') }},
        {{ trx_json_extract('src', ['pris'], type='float', alias='pris') }},
        {{ trx_json_extract('src', ['amos'], type='float', alias='amos') }},
        {{ trx_json_extract('src', ['sacu'], type='varchar', alias='sacu') }},
        {{ trx_json_extract('src', ['btdt'], type='timestamp_ntz', alias='btdt') }},
        {{ trx_json_extract('src', ['dfpc'], type='int', alias='dfpc') }},
        {{ trx_json_extract('src', ['dfpc_kw'], type='varchar', alias='dfpc_kw') }},
        {{ trx_json_extract('src', ['stat'], type='int', alias='stat') }},
        {{ trx_json_extract('src', ['stat_kw'], type='varchar', alias='stat_kw') }},
        {{ trx_json_extract('src', ['cpla'], type='varchar', alias='cpla') }},
        {{ trx_json_extract('src', ['cact'], type='varchar', alias='cact') }},
        {{ trx_json_extract('src', ['cpva'], type='int', alias='cpva') }},
        {{ trx_json_extract('src', ['rtcc_1'], type='float', alias='rtcc_1') }},
        {{ trx_json_extract('src', ['rtcc_2'], type='float', alias='rtcc_2') }},
        {{ trx_json_extract('src', ['rtcc_3'], type='float', alias='rtcc_3') }},
        {{ trx_json_extract('src', ['rtfc_1'], type='int', alias='rtfc_1') }},
        {{ trx_json_extract('src', ['rtfc_2'], type='int', alias='rtfc_2') }},
        {{ trx_json_extract('src', ['rtfc_3'], type='int', alias='rtfc_3') }},
        {{ trx_json_extract('src', ['rtcs_1'], type='float', alias='rtcs_1') }},
        {{ trx_json_extract('src', ['rtcs_2'], type='float', alias='rtcs_2') }},
        {{ trx_json_extract('src', ['rtcs_3'], type='float', alias='rtcs_3') }},
        {{ trx_json_extract('src', ['rtfs_1'], type='int', alias='rtfs_1') }},
        {{ trx_json_extract('src', ['rtfs_2'], type='int', alias='rtfs_2') }},
        {{ trx_json_extract('src', ['rtfs_3'], type='int', alias='rtfs_3') }},
        {{ trx_json_extract('src', ['tsrl'], type='int', alias='tsrl') }},
        {{ trx_json_extract('src', ['tsrl_kw'], type='varchar', alias='tsrl_kw') }},
        {{ trx_json_extract('src', ['trts'], type='int', alias='trts') }},
        {{ trx_json_extract('src', ['trts_kw'], type='varchar', alias='trts_kw') }},
        {{ trx_json_extract('src', ['cono'], type='varchar', alias='cono') }},
        {{ trx_json_extract('src', ['cnln'], type='varchar', alias='cnln') }},
        {{ trx_json_extract('src', ['dlvr'], type='int', alias='dlvr') }},
        {{ trx_json_extract('src', ['schd'], type='int', alias='schd') }},
        {{ trx_json_extract('src', ['dbgf'], type='int', alias='dbgf') }},
        {{ trx_json_extract('src', ['dbgf_kw'], type='varchar', alias='dbgf_kw') }},
        {{ trx_json_extract('src', ['cona'], type='float', alias='cona') }},
        {{ trx_json_extract('src', ['otbp'], type='varchar', alias='otbp') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['cprj_cstl_ref_compnr'], type='int', alias='cprj_cstl_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_cpla_cact_ref_compnr'], type='int', alias='cprj_cpla_cact_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_cspa_ref_compnr'], type='int', alias='cprj_cspa_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_cpla_ref_compnr'], type='int', alias='cprj_cpla_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_ref_compnr'], type='int', alias='cprj_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['effn_ref_compnr'], type='int', alias='effn_ref_compnr') }},
        {{ trx_json_extract('src', ['ccco_ref_compnr'], type='int', alias='ccco_ref_compnr') }},
        {{ trx_json_extract('src', ['cuni_ref_compnr'], type='int', alias='cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['clas_ref_compnr'], type='int', alias='clas_ref_compnr') }},
        {{ trx_json_extract('src', ['cocu_ref_compnr'], type='int', alias='cocu_ref_compnr') }},
        {{ trx_json_extract('src', ['sacu_ref_compnr'], type='int', alias='sacu_ref_compnr') }},
        {{ trx_json_extract('src', ['cono_ref_compnr'], type='int', alias='cono_ref_compnr') }},
        {{ trx_json_extract('src', ['otbp_ref_compnr'], type='int', alias='otbp_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tpptc120') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'cprj', 'cspa', 'sern']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
