{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tsbsc100 Installation Group table, Generated 2026-04-10T19:42:28Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['clst'], type='varchar', alias='clst') }},
        {{ trx_json_extract('src', ['desc', 'en_US'], type='varchar', alias='desc__en_us') }},
        {{ trx_json_extract('src', ['sear', 'en_US'], type='varchar', alias='sear__en_us') }},
        {{ trx_json_extract('src', ['exin', 'en_US'], type='varchar', alias='exin__en_us') }},
        {{ trx_json_extract('src', ['ofbp'], type='varchar', alias='ofbp') }},
        {{ trx_json_extract('src', ['ofcn'], type='varchar', alias='ofcn') }},
        {{ trx_json_extract('src', ['ofad'], type='varchar', alias='ofad') }},
        {{ trx_json_extract('src', ['ubbp'], type='varchar', alias='ubbp') }},
        {{ trx_json_extract('src', ['ubad'], type='varchar', alias='ubad') }},
        {{ trx_json_extract('src', ['ubcn'], type='varchar', alias='ubcn') }},
        {{ trx_json_extract('src', ['ubop'], type='varchar', alias='ubop') }},
        {{ trx_json_extract('src', ['ubpc'], type='int', alias='ubpc') }},
        {{ trx_json_extract('src', ['ubpc_kw'], type='varchar', alias='ubpc_kw') }},
        {{ trx_json_extract('src', ['dler'], type='varchar', alias='dler') }},
        {{ trx_json_extract('src', ['dlad'], type='varchar', alias='dlad') }},
        {{ trx_json_extract('src', ['dlcn'], type='varchar', alias='dlcn') }},
        {{ trx_json_extract('src', ['bfbp'], type='varchar', alias='bfbp') }},
        {{ trx_json_extract('src', ['bfad'], type='varchar', alias='bfad') }},
        {{ trx_json_extract('src', ['bfcn'], type='varchar', alias='bfcn') }},
        {{ trx_json_extract('src', ['owtp'], type='int', alias='owtp') }},
        {{ trx_json_extract('src', ['owtp_kw'], type='varchar', alias='owtp_kw') }},
        {{ trx_json_extract('src', ['dbpo'], type='int', alias='dbpo') }},
        {{ trx_json_extract('src', ['dbpo_kw'], type='varchar', alias='dbpo_kw') }},
        {{ trx_json_extract('src', ['lcmp'], type='int', alias='lcmp') }},
        {{ trx_json_extract('src', ['odpt'], type='varchar', alias='odpt') }},
        {{ trx_json_extract('src', ['soff'], type='varchar', alias='soff') }},
        {{ trx_json_extract('src', ['mdpt'], type='varchar', alias='mdpt') }},
        {{ trx_json_extract('src', ['rste'], type='varchar', alias='rste') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['lste'], type='varchar', alias='lste') }},
        {{ trx_json_extract('src', ['lcad'], type='varchar', alias='lcad') }},
        {{ trx_json_extract('src', ['csar'], type='varchar', alias='csar') }},
        {{ trx_json_extract('src', ['trdt'], type='float', alias='trdt') }},
        {{ trx_json_extract('src', ['trtm'], type='float', alias='trtm') }},
        {{ trx_json_extract('src', ['czon'], type='varchar', alias='czon') }},
        {{ trx_json_extract('src', ['ccha'], type='float', alias='ccha') }},
        {{ trx_json_extract('src', ['ccur'], type='varchar', alias='ccur') }},
        {{ trx_json_extract('src', ['cusc'], type='varchar', alias='cusc') }},
        {{ trx_json_extract('src', ['mdnr'], type='varchar', alias='mdnr') }},
        {{ trx_json_extract('src', ['prfa'], type='varchar', alias='prfa') }},
        {{ trx_json_extract('src', ['prfb'], type='varchar', alias='prfb') }},
        {{ trx_json_extract('src', ['prio'], type='int', alias='prio') }},
        {{ trx_json_extract('src', ['ccal'], type='varchar', alias='ccal') }},
        {{ trx_json_extract('src', ['rspe'], type='varchar', alias='rspe') }},
        {{ trx_json_extract('src', ['eftm'], type='timestamp_ntz', alias='eftm') }},
        {{ trx_json_extract('src', ['clrt'], type='varchar', alias='clrt') }},
        {{ trx_json_extract('src', ['ortp'], type='int', alias='ortp') }},
        {{ trx_json_extract('src', ['ortp_kw'], type='varchar', alias='ortp_kw') }},
        {{ trx_json_extract('src', ['srno'], type='varchar', alias='srno') }},
        {{ trx_json_extract('src', ['cnln'], type='varchar', alias='cnln') }},
        {{ trx_json_extract('src', ['spno'], type='int', alias='spno') }},
        {{ trx_json_extract('src', ['sdno'], type='int', alias='sdno') }},
        {{ trx_json_extract('src', ['imag'], type='varchar', alias='imag') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['ofbp_ref_compnr'], type='int', alias='ofbp_ref_compnr') }},
        {{ trx_json_extract('src', ['ofcn_ref_compnr'], type='int', alias='ofcn_ref_compnr') }},
        {{ trx_json_extract('src', ['ofad_ref_compnr'], type='int', alias='ofad_ref_compnr') }},
        {{ trx_json_extract('src', ['ubbp_ref_compnr'], type='int', alias='ubbp_ref_compnr') }},
        {{ trx_json_extract('src', ['ubad_ref_compnr'], type='int', alias='ubad_ref_compnr') }},
        {{ trx_json_extract('src', ['ubcn_ref_compnr'], type='int', alias='ubcn_ref_compnr') }},
        {{ trx_json_extract('src', ['ubop_ref_compnr'], type='int', alias='ubop_ref_compnr') }},
        {{ trx_json_extract('src', ['dler_ref_compnr'], type='int', alias='dler_ref_compnr') }},
        {{ trx_json_extract('src', ['dlad_ref_compnr'], type='int', alias='dlad_ref_compnr') }},
        {{ trx_json_extract('src', ['dlcn_ref_compnr'], type='int', alias='dlcn_ref_compnr') }},
        {{ trx_json_extract('src', ['bfbp_ref_compnr'], type='int', alias='bfbp_ref_compnr') }},
        {{ trx_json_extract('src', ['bfad_ref_compnr'], type='int', alias='bfad_ref_compnr') }},
        {{ trx_json_extract('src', ['bfcn_ref_compnr'], type='int', alias='bfcn_ref_compnr') }},
        {{ trx_json_extract('src', ['lcmp_ref_compnr'], type='int', alias='lcmp_ref_compnr') }},
        {{ trx_json_extract('src', ['odpt_ref_compnr'], type='int', alias='odpt_ref_compnr') }},
        {{ trx_json_extract('src', ['soff_ref_compnr'], type='int', alias='soff_ref_compnr') }},
        {{ trx_json_extract('src', ['mdpt_ref_compnr'], type='int', alias='mdpt_ref_compnr') }},
        {{ trx_json_extract('src', ['rste_ref_compnr'], type='int', alias='rste_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['lste_ref_compnr'], type='int', alias='lste_ref_compnr') }},
        {{ trx_json_extract('src', ['lcad_ref_compnr'], type='int', alias='lcad_ref_compnr') }},
        {{ trx_json_extract('src', ['csar_ref_compnr'], type='int', alias='csar_ref_compnr') }},
        {{ trx_json_extract('src', ['czon_ref_compnr'], type='int', alias='czon_ref_compnr') }},
        {{ trx_json_extract('src', ['ccur_ref_compnr'], type='int', alias='ccur_ref_compnr') }},
        {{ trx_json_extract('src', ['cusc_ref_compnr'], type='int', alias='cusc_ref_compnr') }},
        {{ trx_json_extract('src', ['prfa_ref_compnr'], type='int', alias='prfa_ref_compnr') }},
        {{ trx_json_extract('src', ['prfb_ref_compnr'], type='int', alias='prfb_ref_compnr') }},
        {{ trx_json_extract('src', ['prio_ref_compnr'], type='int', alias='prio_ref_compnr') }},
        {{ trx_json_extract('src', ['ccal_ref_compnr'], type='int', alias='ccal_ref_compnr') }},
        {{ trx_json_extract('src', ['rspe_ref_compnr'], type='int', alias='rspe_ref_compnr') }},
        {{ trx_json_extract('src', ['clrt_ref_compnr'], type='int', alias='clrt_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tsbsc100') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'clst']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
