{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN tssoc210 Service Order Activities table, Generated 2026-04-10T19:42:38Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['orno'], type='varchar', alias='orno') }},
        {{ trx_json_extract('src', ['acln'], type='int', alias='acln') }},
        {{ trx_json_extract('src', ['crac'], type='varchar', alias='crac') }},
        {{ trx_json_extract('src', ['desc', 'en_US'], type='varchar', alias='desc__en_us') }},
        {{ trx_json_extract('src', ['sear', 'en_US'], type='varchar', alias='sear__en_us') }},
        {{ trx_json_extract('src', ['clst'], type='varchar', alias='clst') }},
        {{ trx_json_extract('src', ['lcad'], type='varchar', alias='lcad') }},
        {{ trx_json_extract('src', ['cstp'], type='varchar', alias='cstp') }},
        {{ trx_json_extract('src', ['actg'], type='varchar', alias='actg') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['sern'], type='varchar', alias='sern') }},
        {{ trx_json_extract('src', ['ssta'], type='int', alias='ssta') }},
        {{ trx_json_extract('src', ['ssta_kw'], type='varchar', alias='ssta_kw') }},
        {{ trx_json_extract('src', ['emno'], type='varchar', alias='emno') }},
        {{ trx_json_extract('src', ['ccar'], type='varchar', alias='ccar') }},
        {{ trx_json_extract('src', ['orac'], type='varchar', alias='orac') }},
        {{ trx_json_extract('src', ['oras'], type='int', alias='oras') }},
        {{ trx_json_extract('src', ['ccll'], type='varchar', alias='ccll') }},
        {{ trx_json_extract('src', ['fcon'], type='varchar', alias='fcon') }},
        {{ trx_json_extract('src', ['cprj'], type='varchar', alias='cprj') }},
        {{ trx_json_extract('src', ['cspa'], type='varchar', alias='cspa') }},
        {{ trx_json_extract('src', ['pcac'], type='varchar', alias='pcac') }},
        {{ trx_json_extract('src', ['inby'], type='int', alias='inby') }},
        {{ trx_json_extract('src', ['inby_kw'], type='varchar', alias='inby_kw') }},
        {{ trx_json_extract('src', ['cpor'], type='int', alias='cpor') }},
        {{ trx_json_extract('src', ['cpor_kw'], type='varchar', alias='cpor_kw') }},
        {{ trx_json_extract('src', ['cvtm'], type='timestamp_ntz', alias='cvtm') }},
        {{ trx_json_extract('src', ['crtc'], type='varchar', alias='crtc') }},
        {{ trx_json_extract('src', ['prpr'], type='int', alias='prpr') }},
        {{ trx_json_extract('src', ['cupr'], type='int', alias='cupr') }},
        {{ trx_json_extract('src', ['obpr'], type='int', alias='obpr') }},
        {{ trx_json_extract('src', ['cprl'], type='varchar', alias='cprl') }},
        {{ trx_json_extract('src', ['cstn'], type='varchar', alias='cstn') }},
        {{ trx_json_extract('src', ['asta'], type='int', alias='asta') }},
        {{ trx_json_extract('src', ['asta_kw'], type='varchar', alias='asta_kw') }},
        {{ trx_json_extract('src', ['subc'], type='int', alias='subc') }},
        {{ trx_json_extract('src', ['subc_kw'], type='varchar', alias='subc_kw') }},
        {{ trx_json_extract('src', ['supm'], type='int', alias='supm') }},
        {{ trx_json_extract('src', ['supm_kw'], type='varchar', alias='supm_kw') }},
        {{ trx_json_extract('src', ['crpu'], type='int', alias='crpu') }},
        {{ trx_json_extract('src', ['crpu_kw'], type='varchar', alias='crpu_kw') }},
        {{ trx_json_extract('src', ['bfbp'], type='varchar', alias='bfbp') }},
        {{ trx_json_extract('src', ['sbit'], type='varchar', alias='sbit') }},
        {{ trx_json_extract('src', ['cmea'], type='varchar', alias='cmea') }},
        {{ trx_json_extract('src', ['mepo'], type='varchar', alias='mepo') }},
        {{ trx_json_extract('src', ['cskt'], type='varchar', alias='cskt') }},
        {{ trx_json_extract('src', ['cchl'], type='int', alias='cchl') }},
        {{ trx_json_extract('src', ['pdvl'], type='float', alias='pdvl') }},
        {{ trx_json_extract('src', ['mvln'], type='float', alias='mvln') }},
        {{ trx_json_extract('src', ['mvla'], type='int', alias='mvla') }},
        {{ trx_json_extract('src', ['come'], type='varchar', alias='come') }},
        {{ trx_json_extract('src', ['cova'], type='float', alias='cova') }},
        {{ trx_json_extract('src', ['dbfc'], type='float', alias='dbfc') }},
        {{ trx_json_extract('src', ['acdu'], type='float', alias='acdu') }},
        {{ trx_json_extract('src', ['trdu'], type='float', alias='trdu') }},
        {{ trx_json_extract('src', ['trdi'], type='float', alias='trdi') }},
        {{ trx_json_extract('src', ['rfpt'], type='varchar', alias='rfpt') }},
        {{ trx_json_extract('src', ['adtm'], type='int', alias='adtm') }},
        {{ trx_json_extract('src', ['appo'], type='int', alias='appo') }},
        {{ trx_json_extract('src', ['appo_kw'], type='varchar', alias='appo_kw') }},
        {{ trx_json_extract('src', ['pstm'], type='timestamp_ntz', alias='pstm') }},
        {{ trx_json_extract('src', ['pftm'], type='timestamp_ntz', alias='pftm') }},
        {{ trx_json_extract('src', ['ptst'], type='timestamp_ntz', alias='ptst') }},
        {{ trx_json_extract('src', ['ptft'], type='timestamp_ntz', alias='ptft') }},
        {{ trx_json_extract('src', ['ostm'], type='timestamp_ntz', alias='ostm') }},
        {{ trx_json_extract('src', ['oftm'], type='timestamp_ntz', alias='oftm') }},
        {{ trx_json_extract('src', ['estm'], type='timestamp_ntz', alias='estm') }},
        {{ trx_json_extract('src', ['lftm'], type='timestamp_ntz', alias='lftm') }},
        {{ trx_json_extract('src', ['astm'], type='timestamp_ntz', alias='astm') }},
        {{ trx_json_extract('src', ['aftm'], type='timestamp_ntz', alias='aftm') }},
        {{ trx_json_extract('src', ['csar'], type='varchar', alias='csar') }},
        {{ trx_json_extract('src', ['cctp'], type='varchar', alias='cctp') }},
        {{ trx_json_extract('src', ['csco'], type='varchar', alias='csco') }},
        {{ trx_json_extract('src', ['pmtd'], type='int', alias='pmtd') }},
        {{ trx_json_extract('src', ['pmtd_kw'], type='varchar', alias='pmtd_kw') }},
        {{ trx_json_extract('src', ['pcon'], type='varchar', alias='pcon') }},
        {{ trx_json_extract('src', ['pcch'], type='int', alias='pcch') }},
        {{ trx_json_extract('src', ['pcln'], type='int', alias='pcln') }},
        {{ trx_json_extract('src', ['espr'], type='float', alias='espr') }},
        {{ trx_json_extract('src', ['pris'], type='float', alias='pris') }},
        {{ trx_json_extract('src', ['eaod'], type='float', alias='eaod') }},
        {{ trx_json_extract('src', ['amod'], type='float', alias='amod') }},
        {{ trx_json_extract('src', ['porg'], type='int', alias='porg') }},
        {{ trx_json_extract('src', ['porg_kw'], type='varchar', alias='porg_kw') }},
        {{ trx_json_extract('src', ['vtbo'], type='int', alias='vtbo') }},
        {{ trx_json_extract('src', ['vtbo_kw'], type='varchar', alias='vtbo_kw') }},
        {{ trx_json_extract('src', ['camr'], type='varchar', alias='camr') }},
        {{ trx_json_extract('src', ['caro_1'], type='varchar', alias='caro_1') }},
        {{ trx_json_extract('src', ['caro_2'], type='varchar', alias='caro_2') }},
        {{ trx_json_extract('src', ['caro_3'], type='varchar', alias='caro_3') }},
        {{ trx_json_extract('src', ['caro_4'], type='varchar', alias='caro_4') }},
        {{ trx_json_extract('src', ['caro_5'], type='varchar', alias='caro_5') }},
        {{ trx_json_extract('src', ['caro_6'], type='varchar', alias='caro_6') }},
        {{ trx_json_extract('src', ['caro_7'], type='varchar', alias='caro_7') }},
        {{ trx_json_extract('src', ['caro_8'], type='varchar', alias='caro_8') }},
        {{ trx_json_extract('src', ['caro_9'], type='varchar', alias='caro_9') }},
        {{ trx_json_extract('src', ['caro_10'], type='varchar', alias='caro_10') }},
        {{ trx_json_extract('src', ['orps'], type='int', alias='orps') }},
        {{ trx_json_extract('src', ['cdis'], type='varchar', alias='cdis') }},
        {{ trx_json_extract('src', ['cadt'], type='date', alias='cadt') }},
        {{ trx_json_extract('src', ['wrtp'], type='int', alias='wrtp') }},
        {{ trx_json_extract('src', ['wrtp_kw'], type='varchar', alias='wrtp_kw') }},
        {{ trx_json_extract('src', ['wrty'], type='varchar', alias='wrty') }},
        {{ trx_json_extract('src', ['ains'], type='int', alias='ains') }},
        {{ trx_json_extract('src', ['ains_kw'], type='varchar', alias='ains_kw') }},
        {{ trx_json_extract('src', ['inpl'], type='varchar', alias='inpl') }},
        {{ trx_json_extract('src', ['acdt'], type='timestamp_ntz', alias='acdt') }},
        {{ trx_json_extract('src', ['stbp'], type='varchar', alias='stbp') }},
        {{ trx_json_extract('src', ['stad'], type='varchar', alias='stad') }},
        {{ trx_json_extract('src', ['stcn'], type='varchar', alias='stcn') }},
        {{ trx_json_extract('src', ['smto'], type='int', alias='smto') }},
        {{ trx_json_extract('src', ['smto_kw'], type='varchar', alias='smto_kw') }},
        {{ trx_json_extract('src', ['micn'], type='int', alias='micn') }},
        {{ trx_json_extract('src', ['micn_kw'], type='varchar', alias='micn_kw') }},
        {{ trx_json_extract('src', ['adfa'], type='int', alias='adfa') }},
        {{ trx_json_extract('src', ['adfa_kw'], type='varchar', alias='adfa_kw') }},
        {{ trx_json_extract('src', ['cncd'], type='varchar', alias='cncd') }},
        {{ trx_json_extract('src', ['pbsm'], type='int', alias='pbsm') }},
        {{ trx_json_extract('src', ['pbsm_kw'], type='varchar', alias='pbsm_kw') }},
        {{ trx_json_extract('src', ['docn'], type='varchar', alias='docn') }},
        {{ trx_json_extract('src', ['qtno'], type='varchar', alias='qtno') }},
        {{ trx_json_extract('src', ['revn'], type='int', alias='revn') }},
        {{ trx_json_extract('src', ['qtnl'], type='int', alias='qtnl') }},
        {{ trx_json_extract('src', ['altn'], type='int', alias='altn') }},
        {{ trx_json_extract('src', ['ityn'], type='int', alias='ityn') }},
        {{ trx_json_extract('src', ['ityn_kw'], type='varchar', alias='ityn_kw') }},
        {{ trx_json_extract('src', ['asgd'], type='varchar', alias='asgd') }},
        {{ trx_json_extract('src', ['prac'], type='int', alias='prac') }},
        {{ trx_json_extract('src', ['prac_kw'], type='varchar', alias='prac_kw') }},
        {{ trx_json_extract('src', ['adin'], type='varchar', alias='adin') }},
        {{ trx_json_extract('src', ['rnyn'], type='int', alias='rnyn') }},
        {{ trx_json_extract('src', ['rnyn_kw'], type='varchar', alias='rnyn_kw') }},
        {{ trx_json_extract('src', ['erdt'], type='timestamp_ntz', alias='erdt') }},
        {{ trx_json_extract('src', ['rrqt'], type='int', alias='rrqt') }},
        {{ trx_json_extract('src', ['tmun'], type='int', alias='tmun') }},
        {{ trx_json_extract('src', ['tmun_kw'], type='varchar', alias='tmun_kw') }},
        {{ trx_json_extract('src', ['orqt'], type='int', alias='orqt') }},
        {{ trx_json_extract('src', ['otmn'], type='int', alias='otmn') }},
        {{ trx_json_extract('src', ['otmn_kw'], type='varchar', alias='otmn_kw') }},
        {{ trx_json_extract('src', ['urrp'], type='int', alias='urrp') }},
        {{ trx_json_extract('src', ['urrp_kw'], type='varchar', alias='urrp_kw') }},
        {{ trx_json_extract('src', ['sfad'], type='varchar', alias='sfad') }},
        {{ trx_json_extract('src', ['xrnh'], type='int', alias='xrnh') }},
        {{ trx_json_extract('src', ['xrnh_kw'], type='varchar', alias='xrnh_kw') }},
        {{ trx_json_extract('src', ['xrrt'], type='float', alias='xrrt') }},
        {{ trx_json_extract('src', ['cuxr'], type='varchar', alias='cuxr') }},
        {{ trx_json_extract('src', ['xrcu'], type='varchar', alias='xrcu') }},
        {{ trx_json_extract('src', ['xrsr'], type='varchar', alias='xrsr') }},
        {{ trx_json_extract('src', ['bsch'], type='varchar', alias='bsch') }},
        {{ trx_json_extract('src', ['atbl'], type='int', alias='atbl') }},
        {{ trx_json_extract('src', ['atbl_kw'], type='varchar', alias='atbl_kw') }},
        {{ trx_json_extract('src', ['noun'], type='int', alias='noun') }},
        {{ trx_json_extract('src', ['rown'], type='varchar', alias='rown') }},
        {{ trx_json_extract('src', ['rltm'], type='timestamp_ntz', alias='rltm') }},
        {{ trx_json_extract('src', ['corn', 'en_US'], type='varchar', alias='corn__en_us') }},
        {{ trx_json_extract('src', ['corp', 'en_US'], type='varchar', alias='corp__en_us') }},
        {{ trx_json_extract('src', ['cors', 'en_US'], type='varchar', alias='cors__en_us') }},
        {{ trx_json_extract('src', ['skla'], type='varchar', alias='skla') }},
        {{ trx_json_extract('src', ['sklb'], type='varchar', alias='sklb') }},
        {{ trx_json_extract('src', ['sklc'], type='varchar', alias='sklc') }},
        {{ trx_json_extract('src', ['aivl'], type='float', alias='aivl') }},
        {{ trx_json_extract('src', ['nivl'], type='float', alias='nivl') }},
        {{ trx_json_extract('src', ['advl'], type='float', alias='advl') }},
        {{ trx_json_extract('src', ['atpc'], type='int', alias='atpc') }},
        {{ trx_json_extract('src', ['atpc_kw'], type='varchar', alias='atpc_kw') }},
        {{ trx_json_extract('src', ['atpd'], type='timestamp_ntz', alias='atpd') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['txtb'], type='int', alias='txtb') }},
        {{ trx_json_extract('src', ['txtc'], type='int', alias='txtc') }},
        {{ trx_json_extract('src', ['txtd'], type='int', alias='txtd') }},
        {{ trx_json_extract('src', ['orno_ref_compnr'], type='int', alias='orno_ref_compnr') }},
        {{ trx_json_extract('src', ['crac_ref_compnr'], type='int', alias='crac_ref_compnr') }},
        {{ trx_json_extract('src', ['clst_ref_compnr'], type='int', alias='clst_ref_compnr') }},
        {{ trx_json_extract('src', ['lcad_ref_compnr'], type='int', alias='lcad_ref_compnr') }},
        {{ trx_json_extract('src', ['cstp_ref_compnr'], type='int', alias='cstp_ref_compnr') }},
        {{ trx_json_extract('src', ['actg_ref_compnr'], type='int', alias='actg_ref_compnr') }},
        {{ trx_json_extract('src', ['item_sern_ref_compnr'], type='int', alias='item_sern_ref_compnr') }},
        {{ trx_json_extract('src', ['item_xrsr_ref_compnr'], type='int', alias='item_xrsr_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['emno_ref_compnr'], type='int', alias='emno_ref_compnr') }},
        {{ trx_json_extract('src', ['ccar_ref_compnr'], type='int', alias='ccar_ref_compnr') }},
        {{ trx_json_extract('src', ['ccll_ref_compnr'], type='int', alias='ccll_ref_compnr') }},
        {{ trx_json_extract('src', ['fcon_ref_compnr'], type='int', alias='fcon_ref_compnr') }},
        {{ trx_json_extract('src', ['cprj_ref_compnr'], type='int', alias='cprj_ref_compnr') }},
        {{ trx_json_extract('src', ['crtc_ref_compnr'], type='int', alias='crtc_ref_compnr') }},
        {{ trx_json_extract('src', ['prpr_ref_compnr'], type='int', alias='prpr_ref_compnr') }},
        {{ trx_json_extract('src', ['cupr_ref_compnr'], type='int', alias='cupr_ref_compnr') }},
        {{ trx_json_extract('src', ['obpr_ref_compnr'], type='int', alias='obpr_ref_compnr') }},
        {{ trx_json_extract('src', ['cprl_ref_compnr'], type='int', alias='cprl_ref_compnr') }},
        {{ trx_json_extract('src', ['cstn_ref_compnr'], type='int', alias='cstn_ref_compnr') }},
        {{ trx_json_extract('src', ['bfbp_ref_compnr'], type='int', alias='bfbp_ref_compnr') }},
        {{ trx_json_extract('src', ['sbit_ref_compnr'], type='int', alias='sbit_ref_compnr') }},
        {{ trx_json_extract('src', ['cmea_ref_compnr'], type='int', alias='cmea_ref_compnr') }},
        {{ trx_json_extract('src', ['mepo_ref_compnr'], type='int', alias='mepo_ref_compnr') }},
        {{ trx_json_extract('src', ['cskt_ref_compnr'], type='int', alias='cskt_ref_compnr') }},
        {{ trx_json_extract('src', ['cchl_ref_compnr'], type='int', alias='cchl_ref_compnr') }},
        {{ trx_json_extract('src', ['come_ref_compnr'], type='int', alias='come_ref_compnr') }},
        {{ trx_json_extract('src', ['csar_ref_compnr'], type='int', alias='csar_ref_compnr') }},
        {{ trx_json_extract('src', ['cctp_ref_compnr'], type='int', alias='cctp_ref_compnr') }},
        {{ trx_json_extract('src', ['csco_ref_compnr'], type='int', alias='csco_ref_compnr') }},
        {{ trx_json_extract('src', ['pcon_pcch_ref_compnr'], type='int', alias='pcon_pcch_ref_compnr') }},
        {{ trx_json_extract('src', ['pcon_ref_compnr'], type='int', alias='pcon_ref_compnr') }},
        {{ trx_json_extract('src', ['camr_ref_compnr'], type='int', alias='camr_ref_compnr') }},
        {{ trx_json_extract('src', ['cdis_ref_compnr'], type='int', alias='cdis_ref_compnr') }},
        {{ trx_json_extract('src', ['inpl_ref_compnr'], type='int', alias='inpl_ref_compnr') }},
        {{ trx_json_extract('src', ['stbp_ref_compnr'], type='int', alias='stbp_ref_compnr') }},
        {{ trx_json_extract('src', ['stad_ref_compnr'], type='int', alias='stad_ref_compnr') }},
        {{ trx_json_extract('src', ['stcn_ref_compnr'], type='int', alias='stcn_ref_compnr') }},
        {{ trx_json_extract('src', ['docn_ref_compnr'], type='int', alias='docn_ref_compnr') }},
        {{ trx_json_extract('src', ['qtno_revn_qtnl_altn_ref_compnr'], type='int', alias='qtno_revn_qtnl_altn_ref_compnr') }},
        {{ trx_json_extract('src', ['sfad_ref_compnr'], type='int', alias='sfad_ref_compnr') }},
        {{ trx_json_extract('src', ['cuxr_ref_compnr'], type='int', alias='cuxr_ref_compnr') }},
        {{ trx_json_extract('src', ['xrcu_ref_compnr'], type='int', alias='xrcu_ref_compnr') }},
        {{ trx_json_extract('src', ['bsch_ref_compnr'], type='int', alias='bsch_ref_compnr') }},
        {{ trx_json_extract('src', ['rown_ref_compnr'], type='int', alias='rown_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['txtb_ref_compnr'], type='int', alias='txtb_ref_compnr') }},
        {{ trx_json_extract('src', ['txtc_ref_compnr'], type='int', alias='txtc_ref_compnr') }},
        {{ trx_json_extract('src', ['txtd_ref_compnr'], type='int', alias='txtd_ref_compnr') }},
        {{ trx_json_extract('src', ['trdi_buln'], type='float', alias='trdi_buln') }},
        {{ trx_json_extract('src', ['pris_dwhc'], type='float', alias='pris_dwhc') }},
        {{ trx_json_extract('src', ['pris_homc'], type='float', alias='pris_homc') }},
        {{ trx_json_extract('src', ['pris_rpc1'], type='float', alias='pris_rpc1') }},
        {{ trx_json_extract('src', ['pris_rpc2'], type='float', alias='pris_rpc2') }},
        {{ trx_json_extract('src', ['pris_refc'], type='float', alias='pris_refc') }},
        {{ trx_json_extract('src', ['eaod_dwhc'], type='float', alias='eaod_dwhc') }},
        {{ trx_json_extract('src', ['eaod_homc'], type='float', alias='eaod_homc') }},
        {{ trx_json_extract('src', ['eaod_rpc1'], type='float', alias='eaod_rpc1') }},
        {{ trx_json_extract('src', ['eaod_rpc2'], type='float', alias='eaod_rpc2') }},
        {{ trx_json_extract('src', ['eaod_refc'], type='float', alias='eaod_refc') }},
        {{ trx_json_extract('src', ['amod_dwhc'], type='float', alias='amod_dwhc') }},
        {{ trx_json_extract('src', ['amod_homc'], type='float', alias='amod_homc') }},
        {{ trx_json_extract('src', ['amod_rpc1'], type='float', alias='amod_rpc1') }},
        {{ trx_json_extract('src', ['amod_rpc2'], type='float', alias='amod_rpc2') }},
        {{ trx_json_extract('src', ['amod_refc'], type='float', alias='amod_refc') }},
        {{ trx_json_extract('src', ['espr_dwhc'], type='float', alias='espr_dwhc') }},
        {{ trx_json_extract('src', ['espr_homc'], type='float', alias='espr_homc') }},
        {{ trx_json_extract('src', ['espr_rpc1'], type='float', alias='espr_rpc1') }},
        {{ trx_json_extract('src', ['espr_rpc2'], type='float', alias='espr_rpc2') }},
        {{ trx_json_extract('src', ['espr_refc'], type='float', alias='espr_refc') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_tssoc210') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'orno', 'acln']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
