{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN ttaad200 User Data table, Generated 2026-04-10T19:42:39Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['user'], type='varchar', alias='user') }},
        {{ trx_json_extract('src', ['name', 'en_US'], type='varchar', alias='name__en_us') }},
        {{ trx_json_extract('src', ['uusr'], type='varchar', alias='uusr') }},
        {{ trx_json_extract('src', ['utyp'], type='int', alias='utyp') }},
        {{ trx_json_extract('src', ['utyp_kw'], type='varchar', alias='utyp_kw') }},
        {{ trx_json_extract('src', ['shtp'], type='int', alias='shtp') }},
        {{ trx_json_extract('src', ['shtp_kw'], type='varchar', alias='shtp_kw') }},
        {{ trx_json_extract('src', ['shcm'], type='varchar', alias='shcm') }},
        {{ trx_json_extract('src', ['sttm'], type='int', alias='sttm') }},
        {{ trx_json_extract('src', ['edtm'], type='int', alias='edtm') }},
        {{ trx_json_extract('src', ['hist'], type='int', alias='hist') }},
        {{ trx_json_extract('src', ['hist_kw'], type='varchar', alias='hist_kw') }},
        {{ trx_json_extract('src', ['pwyn'], type='int', alias='pwyn') }},
        {{ trx_json_extract('src', ['pwyn_kw'], type='varchar', alias='pwyn_kw') }},
        {{ trx_json_extract('src', ['pswd'], type='varchar', alias='pswd') }},
        {{ trx_json_extract('src', ['wait'], type='int', alias='wait') }},
        {{ trx_json_extract('src', ['delh'], type='int', alias='delh') }},
        {{ trx_json_extract('src', ['prrt'], type='int', alias='prrt') }},
        {{ trx_json_extract('src', ['uids'], type='int', alias='uids') }},
        {{ trx_json_extract('src', ['uids_kw'], type='varchar', alias='uids_kw') }},
        {{ trx_json_extract('src', ['pacc'], type='varchar', alias='pacc') }},
        {{ trx_json_extract('src', ['comp'], type='int', alias='comp') }},
        {{ trx_json_extract('src', ['clan'], type='varchar', alias='clan') }},
        {{ trx_json_extract('src', ['cpac'], type='varchar', alias='cpac') }},
        {{ trx_json_extract('src', ['cmod'], type='varchar', alias='cmod') }},
        {{ trx_json_extract('src', ['cmen'], type='varchar', alias='cmen') }},
        {{ trx_json_extract('src', ['maxp'], type='int', alias='maxp') }},
        {{ trx_json_extract('src', ['intt'], type='int', alias='intt') }},
        {{ trx_json_extract('src', ['csbn'], type='int', alias='csbn') }},
        {{ trx_json_extract('src', ['csbn_kw'], type='varchar', alias='csbn_kw') }},
        {{ trx_json_extract('src', ['csbh'], type='int', alias='csbh') }},
        {{ trx_json_extract('src', ['csbh_kw'], type='varchar', alias='csbh_kw') }},
        {{ trx_json_extract('src', ['palp'], type='int', alias='palp') }},
        {{ trx_json_extract('src', ['palp_kw'], type='varchar', alias='palp_kw') }},
        {{ trx_json_extract('src', ['loca'], type='varchar', alias='loca') }},
        {{ trx_json_extract('src', ['stpr'], type='int', alias='stpr') }},
        {{ trx_json_extract('src', ['stpr_kw'], type='varchar', alias='stpr_kw') }},
        {{ trx_json_extract('src', ['dskt'], type='varchar', alias='dskt') }},
        {{ trx_json_extract('src', ['stdp'], type='int', alias='stdp') }},
        {{ trx_json_extract('src', ['stdp_kw'], type='varchar', alias='stdp_kw') }},
        {{ trx_json_extract('src', ['tdir'], type='int', alias='tdir') }},
        {{ trx_json_extract('src', ['tdir_kw'], type='varchar', alias='tdir_kw') }},
        {{ trx_json_extract('src', ['apsv'], type='varchar', alias='apsv') }},
        {{ trx_json_extract('src', ['syst'], type='varchar', alias='syst') }},
        {{ trx_json_extract('src', ['s132'], type='int', alias='s132') }},
        {{ trx_json_extract('src', ['s132_kw'], type='varchar', alias='s132_kw') }},
        {{ trx_json_extract('src', ['uoos'], type='int', alias='uoos') }},
        {{ trx_json_extract('src', ['uoos_kw'], type='varchar', alias='uoos_kw') }},
        {{ trx_json_extract('src', ['scdh'], type='int', alias='scdh') }},
        {{ trx_json_extract('src', ['scdh_kw'], type='varchar', alias='scdh_kw') }},
        {{ trx_json_extract('src', ['syst2'], type='varchar', alias='syst2') }},
        {{ trx_json_extract('src', ['crol_1'], type='varchar', alias='crol_1') }},
        {{ trx_json_extract('src', ['crol_2'], type='varchar', alias='crol_2') }},
        {{ trx_json_extract('src', ['crol_3'], type='varchar', alias='crol_3') }},
        {{ trx_json_extract('src', ['crol_4'], type='varchar', alias='crol_4') }},
        {{ trx_json_extract('src', ['crol_5'], type='varchar', alias='crol_5') }},
        {{ trx_json_extract('src', ['crol_6'], type='varchar', alias='crol_6') }},
        {{ trx_json_extract('src', ['tusd'], type='varchar', alias='tusd') }},
        {{ trx_json_extract('src', ['ttxg'], type='varchar', alias='ttxg') }},
        {{ trx_json_extract('src', ['ttxf'], type='varchar', alias='ttxf') }},
        {{ trx_json_extract('src', ['ttxa'], type='varchar', alias='ttxa') }},
        {{ trx_json_extract('src', ['tter'], type='varchar', alias='tter') }},
        {{ trx_json_extract('src', ['tdvc'], type='varchar', alias='tdvc') }},
        {{ trx_json_extract('src', ['tdvp'], type='varchar', alias='tdvp') }},
        {{ trx_json_extract('src', ['tdva'], type='varchar', alias='tdva') }},
        {{ trx_json_extract('src', ['allp'], type='int', alias='allp') }},
        {{ trx_json_extract('src', ['allp_kw'], type='varchar', alias='allp_kw') }},
        {{ trx_json_extract('src', ['apud'], type='int', alias='apud') }},
        {{ trx_json_extract('src', ['apud_kw'], type='varchar', alias='apud_kw') }},
        {{ trx_json_extract('src', ['whlp'], type='varchar', alias='whlp') }},
        {{ trx_json_extract('src', ['phlp', 'en_US'], type='varchar', alias='phlp__en_us') }},
        {{ trx_json_extract('src', ['tlb1'], type='int', alias='tlb1') }},
        {{ trx_json_extract('src', ['tlb1_kw'], type='varchar', alias='tlb1_kw') }},
        {{ trx_json_extract('src', ['tlb2'], type='int', alias='tlb2') }},
        {{ trx_json_extract('src', ['tlb2_kw'], type='varchar', alias='tlb2_kw') }},
        {{ trx_json_extract('src', ['uico'], type='int', alias='uico') }},
        {{ trx_json_extract('src', ['uico_kw'], type='varchar', alias='uico_kw') }},
        {{ trx_json_extract('src', ['wtit', 'en_US'], type='varchar', alias='wtit__en_us') }},
        {{ trx_json_extract('src', ['z_mmode'], type='int', alias='z_mmode') }},
        {{ trx_json_extract('src', ['z_mmode_kw'], type='varchar', alias='z_mmode_kw') }},
        {{ trx_json_extract('src', ['z_pswd'], type='varchar', alias='z_pswd') }},
        {{ trx_json_extract('src', ['za_dlan'], type='varchar', alias='za_dlan') }},
        {{ trx_json_extract('src', ['zb_ssou', 'en_US'], type='varchar', alias='zb_ssou__en_us') }},
        {{ trx_json_extract('src', ['zb_ugsu'], type='int', alias='zb_ugsu') }},
        {{ trx_json_extract('src', ['zb_ugsu_kw'], type='varchar', alias='zb_ugsu_kw') }},
        {{ trx_json_extract('src', ['zc_fcom'], type='int', alias='zc_fcom') }},
        {{ trx_json_extract('src', ['zc_lcom'], type='int', alias='zc_lcom') }},
        {{ trx_json_extract('src', ['zd_idnt'], type='varchar', alias='zd_idnt') }},
        {{ trx_json_extract('src', ['role'], type='varchar', alias='role') }},
        {{ trx_json_extract('src', ['ifsu'], type='int', alias='ifsu') }},
        {{ trx_json_extract('src', ['ifsu_kw'], type='varchar', alias='ifsu_kw') }},
        {{ trx_json_extract('src', ['ifss'], type='int', alias='ifss') }},
        {{ trx_json_extract('src', ['ifss_kw'], type='varchar', alias='ifss_kw') }},
        {{ trx_json_extract('src', ['ifsi', 'en_US'], type='varchar', alias='ifsi__en_us') }},
        {{ trx_json_extract('src', ['mail', 'en_US'], type='varchar', alias='mail__en_us') }},
        {{ trx_json_extract('src', ['mtyp'], type='int', alias='mtyp') }},
        {{ trx_json_extract('src', ['mtyp_kw'], type='varchar', alias='mtyp_kw') }},
        {{ trx_json_extract('src', ['faxn'], type='varchar', alias='faxn') }},
        {{ trx_json_extract('src', ['telx'], type='varchar', alias='telx') }},
        {{ trx_json_extract('src', ['sita'], type='varchar', alias='sita') }},
        {{ trx_json_extract('src', ['smsa'], type='varchar', alias='smsa') }},
        {{ trx_json_extract('src', ['defa'], type='int', alias='defa') }},
        {{ trx_json_extract('src', ['defa_kw'], type='varchar', alias='defa_kw') }},
        {{ trx_json_extract('src', ['tele'], type='varchar', alias='tele') }},
        {{ trx_json_extract('src', ['ucln'], type='int', alias='ucln') }},
        {{ trx_json_extract('src', ['ucln_kw'], type='varchar', alias='ucln_kw') }},
        {{ trx_json_extract('src', ['uspr'], type='varchar', alias='uspr') }},
        {{ trx_json_extract('src', ['uhmd'], type='int', alias='uhmd') }},
        {{ trx_json_extract('src', ['uhmd_kw'], type='varchar', alias='uhmd_kw') }},
        {{ trx_json_extract('src', ['hmdi', 'en_US'], type='varchar', alias='hmdi__en_us') }},
        {{ trx_json_extract('src', ['crdt'], type='timestamp_ntz', alias='crdt') }},
        {{ trx_json_extract('src', ['crus'], type='varchar', alias='crus') }},
        {{ trx_json_extract('src', ['ifsc'], type='varchar', alias='ifsc') }},
        {{ trx_json_extract('src', ['updt'], type='timestamp_ntz', alias='updt') }},
        {{ trx_json_extract('src', ['upus'], type='varchar', alias='upus') }},
        {{ trx_json_extract('src', ['ifsm'], type='varchar', alias='ifsm') }},
        {{ trx_json_extract('src', ['user_role_ref_compnr'], type='int', alias='user_role_ref_compnr') }},
        {{ trx_json_extract('src', ['pacc_ref_compnr'], type='int', alias='pacc_ref_compnr') }},
        {{ trx_json_extract('src', ['comp_ref_compnr'], type='int', alias='comp_ref_compnr') }},
        {{ trx_json_extract('src', ['clan_ref_compnr'], type='int', alias='clan_ref_compnr') }},
        {{ trx_json_extract('src', ['cpac_ref_compnr'], type='int', alias='cpac_ref_compnr') }},
        {{ trx_json_extract('src', ['loca_ref_compnr'], type='int', alias='loca_ref_compnr') }},
        {{ trx_json_extract('src', ['tusd_ref_compnr'], type='int', alias='tusd_ref_compnr') }},
        {{ trx_json_extract('src', ['tdvp_ref_compnr'], type='int', alias='tdvp_ref_compnr') }},
        {{ trx_json_extract('src', ['uspr_ref_compnr'], type='int', alias='uspr_ref_compnr') }},
        {{ trx_json_extract('src', ['tenant'], type='varchar', alias='tenant') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_ttaad200') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'user']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
