{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN txptc904 Change Request Lines table, Generated 2026-04-10T19:42:43Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['creq'], type='varchar', alias='creq') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['rtyp'], type='int', alias='rtyp') }},
        {{ trx_json_extract('src', ['rtyp_kw'], type='varchar', alias='rtyp_kw') }},
        {{ trx_json_extract('src', ['desc', 'en_US'], type='varchar', alias='desc__en_us') }},
        {{ trx_json_extract('src', ['risk'], type='varchar', alias='risk') }},
        {{ trx_json_extract('src', ['cono'], type='varchar', alias='cono') }},
        {{ trx_json_extract('src', ['cnln'], type='int', alias='cnln') }},
        {{ trx_json_extract('src', ['pdat'], type='timestamp_ntz', alias='pdat') }},
        {{ trx_json_extract('src', ['bcav'], type='varchar', alias='bcav') }},
        {{ trx_json_extract('src', ['acti'], type='varchar', alias='acti') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['reqc'], type='int', alias='reqc') }},
        {{ trx_json_extract('src', ['irej'], type='int', alias='irej') }},
        {{ trx_json_extract('src', ['pout'], type='int', alias='pout') }},
        {{ trx_json_extract('src', ['pout_kw'], type='varchar', alias='pout_kw') }},
        {{ trx_json_extract('src', ['cost'], type='int', alias='cost') }},
        {{ trx_json_extract('src', ['cost_kw'], type='varchar', alias='cost_kw') }},
        {{ trx_json_extract('src', ['sche'], type='int', alias='sche') }},
        {{ trx_json_extract('src', ['sche_kw'], type='varchar', alias='sche_kw') }},
        {{ trx_json_extract('src', ['scpe'], type='int', alias='scpe') }},
        {{ trx_json_extract('src', ['scpe_kw'], type='varchar', alias='scpe_kw') }},
        {{ trx_json_extract('src', ['cont'], type='int', alias='cont') }},
        {{ trx_json_extract('src', ['cont_kw'], type='varchar', alias='cont_kw') }},
        {{ trx_json_extract('src', ['camp'], type='int', alias='camp') }},
        {{ trx_json_extract('src', ['camp_kw'], type='varchar', alias='camp_kw') }},
        {{ trx_json_extract('src', ['ipou'], type='int', alias='ipou') }},
        {{ trx_json_extract('src', ['icos'], type='int', alias='icos') }},
        {{ trx_json_extract('src', ['isch'], type='int', alias='isch') }},
        {{ trx_json_extract('src', ['iscp'], type='int', alias='iscp') }},
        {{ trx_json_extract('src', ['icon'], type='int', alias='icon') }},
        {{ trx_json_extract('src', ['iamp'], type='int', alias='iamp') }},
        {{ trx_json_extract('src', ['vamt'], type='float', alias='vamt') }},
        {{ trx_json_extract('src', ['camt'], type='float', alias='camt') }},
        {{ trx_json_extract('src', ['cacc_1'], type='varchar', alias='cacc_1') }},
        {{ trx_json_extract('src', ['cacc_2'], type='varchar', alias='cacc_2') }},
        {{ trx_json_extract('src', ['cacc_3'], type='varchar', alias='cacc_3') }},
        {{ trx_json_extract('src', ['cacc_4'], type='varchar', alias='cacc_4') }},
        {{ trx_json_extract('src', ['cacc_5'], type='varchar', alias='cacc_5') }},
        {{ trx_json_extract('src', ['cacc_6'], type='varchar', alias='cacc_6') }},
        {{ trx_json_extract('src', ['cacc_7'], type='varchar', alias='cacc_7') }},
        {{ trx_json_extract('src', ['cacc_8'], type='varchar', alias='cacc_8') }},
        {{ trx_json_extract('src', ['cacc_9'], type='varchar', alias='cacc_9') }},
        {{ trx_json_extract('src', ['cacc_10'], type='varchar', alias='cacc_10') }},
        {{ trx_json_extract('src', ['ssdt_1'], type='timestamp_ntz', alias='ssdt_1') }},
        {{ trx_json_extract('src', ['ssdt_2'], type='timestamp_ntz', alias='ssdt_2') }},
        {{ trx_json_extract('src', ['ssdt_3'], type='timestamp_ntz', alias='ssdt_3') }},
        {{ trx_json_extract('src', ['ssdt_4'], type='timestamp_ntz', alias='ssdt_4') }},
        {{ trx_json_extract('src', ['ssdt_5'], type='timestamp_ntz', alias='ssdt_5') }},
        {{ trx_json_extract('src', ['ssdt_6'], type='timestamp_ntz', alias='ssdt_6') }},
        {{ trx_json_extract('src', ['ssdt_7'], type='timestamp_ntz', alias='ssdt_7') }},
        {{ trx_json_extract('src', ['ssdt_8'], type='timestamp_ntz', alias='ssdt_8') }},
        {{ trx_json_extract('src', ['ssdt_9'], type='timestamp_ntz', alias='ssdt_9') }},
        {{ trx_json_extract('src', ['ssdt_10'], type='timestamp_ntz', alias='ssdt_10') }},
        {{ trx_json_extract('src', ['sfdt_1'], type='timestamp_ntz', alias='sfdt_1') }},
        {{ trx_json_extract('src', ['sfdt_2'], type='timestamp_ntz', alias='sfdt_2') }},
        {{ trx_json_extract('src', ['sfdt_3'], type='timestamp_ntz', alias='sfdt_3') }},
        {{ trx_json_extract('src', ['sfdt_4'], type='timestamp_ntz', alias='sfdt_4') }},
        {{ trx_json_extract('src', ['sfdt_5'], type='timestamp_ntz', alias='sfdt_5') }},
        {{ trx_json_extract('src', ['sfdt_6'], type='timestamp_ntz', alias='sfdt_6') }},
        {{ trx_json_extract('src', ['sfdt_7'], type='timestamp_ntz', alias='sfdt_7') }},
        {{ trx_json_extract('src', ['sfdt_8'], type='timestamp_ntz', alias='sfdt_8') }},
        {{ trx_json_extract('src', ['sfdt_9'], type='timestamp_ntz', alias='sfdt_9') }},
        {{ trx_json_extract('src', ['sfdt_10'], type='timestamp_ntz', alias='sfdt_10') }},
        {{ trx_json_extract('src', ['rsdt_1'], type='timestamp_ntz', alias='rsdt_1') }},
        {{ trx_json_extract('src', ['rsdt_2'], type='timestamp_ntz', alias='rsdt_2') }},
        {{ trx_json_extract('src', ['rsdt_3'], type='timestamp_ntz', alias='rsdt_3') }},
        {{ trx_json_extract('src', ['rsdt_4'], type='timestamp_ntz', alias='rsdt_4') }},
        {{ trx_json_extract('src', ['rsdt_5'], type='timestamp_ntz', alias='rsdt_5') }},
        {{ trx_json_extract('src', ['rsdt_6'], type='timestamp_ntz', alias='rsdt_6') }},
        {{ trx_json_extract('src', ['rsdt_7'], type='timestamp_ntz', alias='rsdt_7') }},
        {{ trx_json_extract('src', ['rsdt_8'], type='timestamp_ntz', alias='rsdt_8') }},
        {{ trx_json_extract('src', ['rsdt_9'], type='timestamp_ntz', alias='rsdt_9') }},
        {{ trx_json_extract('src', ['rsdt_10'], type='timestamp_ntz', alias='rsdt_10') }},
        {{ trx_json_extract('src', ['rfdt_1'], type='timestamp_ntz', alias='rfdt_1') }},
        {{ trx_json_extract('src', ['rfdt_2'], type='timestamp_ntz', alias='rfdt_2') }},
        {{ trx_json_extract('src', ['rfdt_3'], type='timestamp_ntz', alias='rfdt_3') }},
        {{ trx_json_extract('src', ['rfdt_4'], type='timestamp_ntz', alias='rfdt_4') }},
        {{ trx_json_extract('src', ['rfdt_5'], type='timestamp_ntz', alias='rfdt_5') }},
        {{ trx_json_extract('src', ['rfdt_6'], type='timestamp_ntz', alias='rfdt_6') }},
        {{ trx_json_extract('src', ['rfdt_7'], type='timestamp_ntz', alias='rfdt_7') }},
        {{ trx_json_extract('src', ['rfdt_8'], type='timestamp_ntz', alias='rfdt_8') }},
        {{ trx_json_extract('src', ['rfdt_9'], type='timestamp_ntz', alias='rfdt_9') }},
        {{ trx_json_extract('src', ['rfdt_10'], type='timestamp_ntz', alias='rfdt_10') }},
        {{ trx_json_extract('src', ['actp'], type='int', alias='actp') }},
        {{ trx_json_extract('src', ['actp_kw'], type='varchar', alias='actp_kw') }},
        {{ trx_json_extract('src', ['sact_1'], type='varchar', alias='sact_1') }},
        {{ trx_json_extract('src', ['sact_2'], type='varchar', alias='sact_2') }},
        {{ trx_json_extract('src', ['sact_3'], type='varchar', alias='sact_3') }},
        {{ trx_json_extract('src', ['sact_4'], type='varchar', alias='sact_4') }},
        {{ trx_json_extract('src', ['sact_5'], type='varchar', alias='sact_5') }},
        {{ trx_json_extract('src', ['sact_6'], type='varchar', alias='sact_6') }},
        {{ trx_json_extract('src', ['sact_7'], type='varchar', alias='sact_7') }},
        {{ trx_json_extract('src', ['sact_8'], type='varchar', alias='sact_8') }},
        {{ trx_json_extract('src', ['sact_9'], type='varchar', alias='sact_9') }},
        {{ trx_json_extract('src', ['sact_10'], type='varchar', alias='sact_10') }},
        {{ trx_json_extract('src', ['piba'], type='int', alias='piba') }},
        {{ trx_json_extract('src', ['piba_kw'], type='varchar', alias='piba_kw') }},
        {{ trx_json_extract('src', ['creq_ref_compnr'], type='int', alias='creq_ref_compnr') }},
        {{ trx_json_extract('src', ['risk_ref_compnr'], type='int', alias='risk_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['reqc_ref_compnr'], type='int', alias='reqc_ref_compnr') }},
        {{ trx_json_extract('src', ['irej_ref_compnr'], type='int', alias='irej_ref_compnr') }},
        {{ trx_json_extract('src', ['ipou_ref_compnr'], type='int', alias='ipou_ref_compnr') }},
        {{ trx_json_extract('src', ['icos_ref_compnr'], type='int', alias='icos_ref_compnr') }},
        {{ trx_json_extract('src', ['isch_ref_compnr'], type='int', alias='isch_ref_compnr') }},
        {{ trx_json_extract('src', ['iscp_ref_compnr'], type='int', alias='iscp_ref_compnr') }},
        {{ trx_json_extract('src', ['icon_ref_compnr'], type='int', alias='icon_ref_compnr') }},
        {{ trx_json_extract('src', ['iamp_ref_compnr'], type='int', alias='iamp_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_txptc904') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'creq', 'pono']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
