{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN whinh501 Cycle Counting Order Lines table, Generated 2026-04-10T19:42:51Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['orno'], type='varchar', alias='orno') }},
        {{ trx_json_extract('src', ['cntn'], type='int', alias='cntn') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['rowc'], type='int', alias='rowc') }},
        {{ trx_json_extract('src', ['rown'], type='varchar', alias='rown') }},
        {{ trx_json_extract('src', ['zone'], type='varchar', alias='zone') }},
        {{ trx_json_extract('src', ['strt'], type='varchar', alias='strt') }},
        {{ trx_json_extract('src', ['coln'], type='varchar', alias='coln') }},
        {{ trx_json_extract('src', ['rack'], type='varchar', alias='rack') }},
        {{ trx_json_extract('src', ['loca'], type='varchar', alias='loca') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['atse'], type='varchar', alias='atse') }},
        {{ trx_json_extract('src', ['itag'], type='varchar', alias='itag') }},
        {{ trx_json_extract('src', ['clot'], type='varchar', alias='clot') }},
        {{ trx_json_extract('src', ['idat'], type='timestamp_ntz', alias='idat') }},
        {{ trx_json_extract('src', ['stun'], type='varchar', alias='stun') }},
        {{ trx_json_extract('src', ['pkdf'], type='varchar', alias='pkdf') }},
        {{ trx_json_extract('src', ['huid'], type='varchar', alias='huid') }},
        {{ trx_json_extract('src', ['hupr'], type='int', alias='hupr') }},
        {{ trx_json_extract('src', ['hupr_kw'], type='varchar', alias='hupr_kw') }},
        {{ trx_json_extract('src', ['qstp'], type='float', alias='qstp') }},
        {{ trx_json_extract('src', ['qstr'], type='float', alias='qstr') }},
        {{ trx_json_extract('src', ['qspu'], type='float', alias='qspu') }},
        {{ trx_json_extract('src', ['qcnt'], type='float', alias='qcnt') }},
        {{ trx_json_extract('src', ['qcnr'], type='float', alias='qcnr') }},
        {{ trx_json_extract('src', ['qcpu'], type='float', alias='qcpu') }},
        {{ trx_json_extract('src', ['qvrc'], type='float', alias='qvrc') }},
        {{ trx_json_extract('src', ['qvrr'], type='float', alias='qvrr') }},
        {{ trx_json_extract('src', ['qvpu'], type='float', alias='qvpu') }},
        {{ trx_json_extract('src', ['csts'], type='int', alias='csts') }},
        {{ trx_json_extract('src', ['csts_kw'], type='varchar', alias='csts_kw') }},
        {{ trx_json_extract('src', ['cdat'], type='timestamp_ntz', alias='cdat') }},
        {{ trx_json_extract('src', ['reco'], type='int', alias='reco') }},
        {{ trx_json_extract('src', ['reco_kw'], type='varchar', alias='reco_kw') }},
        {{ trx_json_extract('src', ['uapr'], type='int', alias='uapr') }},
        {{ trx_json_extract('src', ['uapr_kw'], type='varchar', alias='uapr_kw') }},
        {{ trx_json_extract('src', ['adpr'], type='float', alias='adpr') }},
        {{ trx_json_extract('src', ['pric'], type='float', alias='pric') }},
        {{ trx_json_extract('src', ['amnt'], type='float', alias='amnt') }},
        {{ trx_json_extract('src', ['appr'], type='int', alias='appr') }},
        {{ trx_json_extract('src', ['appr_kw'], type='varchar', alias='appr_kw') }},
        {{ trx_json_extract('src', ['cadj'], type='varchar', alias='cadj') }},
        {{ trx_json_extract('src', ['owns'], type='int', alias='owns') }},
        {{ trx_json_extract('src', ['owns_kw'], type='varchar', alias='owns_kw') }},
        {{ trx_json_extract('src', ['ownr'], type='varchar', alias='ownr') }},
        {{ trx_json_extract('src', ['istr'], type='int', alias='istr') }},
        {{ trx_json_extract('src', ['istr_kw'], type='varchar', alias='istr_kw') }},
        {{ trx_json_extract('src', ['ifbp'], type='varchar', alias='ifbp') }},
        {{ trx_json_extract('src', ['iown'], type='int', alias='iown') }},
        {{ trx_json_extract('src', ['iown_kw'], type='varchar', alias='iown_kw') }},
        {{ trx_json_extract('src', ['dpby'], type='int', alias='dpby') }},
        {{ trx_json_extract('src', ['dpby_kw'], type='varchar', alias='dpby_kw') }},
        {{ trx_json_extract('src', ['prcd'], type='int', alias='prcd') }},
        {{ trx_json_extract('src', ['prcd_kw'], type='varchar', alias='prcd_kw') }},
        {{ trx_json_extract('src', ['spcn'], type='varchar', alias='spcn') }},
        {{ trx_json_extract('src', ['nstp'], type='int', alias='nstp') }},
        {{ trx_json_extract('src', ['nstp_kw'], type='varchar', alias='nstp_kw') }},
        {{ trx_json_extract('src', ['txta'], type='int', alias='txta') }},
        {{ trx_json_extract('src', ['orno_cntn_ref_compnr'], type='int', alias='orno_cntn_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_loca_ref_compnr'], type='int', alias='cwar_loca_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['rowc_ref_compnr'], type='int', alias='rowc_ref_compnr') }},
        {{ trx_json_extract('src', ['rown_ref_compnr'], type='int', alias='rown_ref_compnr') }},
        {{ trx_json_extract('src', ['item_clot_ref_compnr'], type='int', alias='item_clot_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['stun_ref_compnr'], type='int', alias='stun_ref_compnr') }},
        {{ trx_json_extract('src', ['pkdf_ref_compnr'], type='int', alias='pkdf_ref_compnr') }},
        {{ trx_json_extract('src', ['huid_ref_compnr'], type='int', alias='huid_ref_compnr') }},
        {{ trx_json_extract('src', ['cadj_ref_compnr'], type='int', alias='cadj_ref_compnr') }},
        {{ trx_json_extract('src', ['ownr_ref_compnr'], type='int', alias='ownr_ref_compnr') }},
        {{ trx_json_extract('src', ['ifbp_ref_compnr'], type='int', alias='ifbp_ref_compnr') }},
        {{ trx_json_extract('src', ['txta_ref_compnr'], type='int', alias='txta_ref_compnr') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_whinh501') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'orno', 'cntn', 'pono']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
