{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN whinh312 Receipt Lines table, Generated 2026-04-10T19:42:49Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['rcno'], type='varchar', alias='rcno') }},
        {{ trx_json_extract('src', ['rcln'], type='int', alias='rcln') }},
        {{ trx_json_extract('src', ['oorg'], type='int', alias='oorg') }},
        {{ trx_json_extract('src', ['oorg_kw'], type='varchar', alias='oorg_kw') }},
        {{ trx_json_extract('src', ['orno'], type='varchar', alias='orno') }},
        {{ trx_json_extract('src', ['oset'], type='int', alias='oset') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['seqn'], type='int', alias='seqn') }},
        {{ trx_json_extract('src', ['sfbp'], type='varchar', alias='sfbp') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['atse'], type='varchar', alias='atse') }},
        {{ trx_json_extract('src', ['itag'], type='varchar', alias='itag') }},
        {{ trx_json_extract('src', ['cmnf'], type='varchar', alias='cmnf') }},
        {{ trx_json_extract('src', ['mpnr'], type='varchar', alias='mpnr') }},
        {{ trx_json_extract('src', ['serl'], type='varchar', alias='serl') }},
        {{ trx_json_extract('src', ['clot'], type='varchar', alias='clot') }},
        {{ trx_json_extract('src', ['effn'], type='int', alias='effn') }},
        {{ trx_json_extract('src', ['rowc'], type='int', alias='rowc') }},
        {{ trx_json_extract('src', ['rown'], type='varchar', alias='rown') }},
        {{ trx_json_extract('src', ['revi'], type='varchar', alias='revi') }},
        {{ trx_json_extract('src', ['idat'], type='timestamp_ntz', alias='idat') }},
        {{ trx_json_extract('src', ['rcun'], type='varchar', alias='rcun') }},
        {{ trx_json_extract('src', ['qrcr'], type='float', alias='qrcr') }},
        {{ trx_json_extract('src', ['qrec'], type='float', alias='qrec') }},
        {{ trx_json_extract('src', ['qrcp'], type='float', alias='qrcp') }},
        {{ trx_json_extract('src', ['qapr'], type='float', alias='qapr') }},
        {{ trx_json_extract('src', ['qapp'], type='float', alias='qapp') }},
        {{ trx_json_extract('src', ['qdes'], type='float', alias='qdes') }},
        {{ trx_json_extract('src', ['qdep'], type='float', alias='qdep') }},
        {{ trx_json_extract('src', ['qrej'], type='float', alias='qrej') }},
        {{ trx_json_extract('src', ['qrpu'], type='float', alias='qrpu') }},
        {{ trx_json_extract('src', ['qrsc'], type='float', alias='qrsc') }},
        {{ trx_json_extract('src', ['qrsp'], type='float', alias='qrsp') }},
        {{ trx_json_extract('src', ['qadv'], type='float', alias='qadv') }},
        {{ trx_json_extract('src', ['qadp'], type='float', alias='qadp') }},
        {{ trx_json_extract('src', ['qput'], type='float', alias='qput') }},
        {{ trx_json_extract('src', ['qpup'], type='float', alias='qpup') }},
        {{ trx_json_extract('src', ['qadi'], type='float', alias='qadi') }},
        {{ trx_json_extract('src', ['qapu'], type='float', alias='qapu') }},
        {{ trx_json_extract('src', ['qpui'], type='float', alias='qpui') }},
        {{ trx_json_extract('src', ['qppu'], type='float', alias='qppu') }},
        {{ trx_json_extract('src', ['psno', 'en_US'], type='varchar', alias='psno__en_us') }},
        {{ trx_json_extract('src', ['psqr'], type='float', alias='psqr') }},
        {{ trx_json_extract('src', ['psqp'], type='float', alias='psqp') }},
        {{ trx_json_extract('src', ['psqu'], type='float', alias='psqu') }},
        {{ trx_json_extract('src', ['psun'], type='varchar', alias='psun') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['rclo'], type='varchar', alias='rclo') }},
        {{ trx_json_extract('src', ['dslo'], type='varchar', alias='dslo') }},
        {{ trx_json_extract('src', ['pkdf'], type='varchar', alias='pkdf') }},
        {{ trx_json_extract('src', ['pmsk'], type='varchar', alias='pmsk') }},
        {{ trx_json_extract('src', ['acti', 'en_US'], type='varchar', alias='acti__en_us') }},
        {{ trx_json_extract('src', ['lsta'], type='int', alias='lsta') }},
        {{ trx_json_extract('src', ['lsta_kw'], type='varchar', alias='lsta_kw') }},
        {{ trx_json_extract('src', ['cmpl'], type='int', alias='cmpl') }},
        {{ trx_json_extract('src', ['cmpl_kw'], type='varchar', alias='cmpl_kw') }},
        {{ trx_json_extract('src', ['fire'], type='int', alias='fire') }},
        {{ trx_json_extract('src', ['fire_kw'], type='varchar', alias='fire_kw') }},
        {{ trx_json_extract('src', ['conf'], type='int', alias='conf') }},
        {{ trx_json_extract('src', ['conf_kw'], type='varchar', alias='conf_kw') }},
        {{ trx_json_extract('src', ['insp'], type='int', alias='insp') }},
        {{ trx_json_extract('src', ['insp_kw'], type='varchar', alias='insp_kw') }},
        {{ trx_json_extract('src', ['cdck'], type='int', alias='cdck') }},
        {{ trx_json_extract('src', ['cdck_kw'], type='varchar', alias='cdck_kw') }},
        {{ trx_json_extract('src', ['cdcr'], type='int', alias='cdcr') }},
        {{ trx_json_extract('src', ['cdcr_kw'], type='varchar', alias='cdcr_kw') }},
        {{ trx_json_extract('src', ['dmse'], type='int', alias='dmse') }},
        {{ trx_json_extract('src', ['dmse_kw'], type='varchar', alias='dmse_kw') }},
        {{ trx_json_extract('src', ['qdms'], type='float', alias='qdms') }},
        {{ trx_json_extract('src', ['arej'], type='int', alias='arej') }},
        {{ trx_json_extract('src', ['arej_kw'], type='varchar', alias='arej_kw') }},
        {{ trx_json_extract('src', ['ardt'], type='timestamp_ntz', alias='ardt') }},
        {{ trx_json_extract('src', ['shdt'], type='timestamp_ntz', alias='shdt') }},
        {{ trx_json_extract('src', ['trdt'], type='timestamp_ntz', alias='trdt') }},
        {{ trx_json_extract('src', ['refe', 'en_US'], type='varchar', alias='refe__en_us') }},
        {{ trx_json_extract('src', ['ksig'], type='varchar', alias='ksig') }},
        {{ trx_json_extract('src', ['ltbp'], type='varchar', alias='ltbp') }},
        {{ trx_json_extract('src', ['exhu'], type='varchar', alias='exhu') }},
        {{ trx_json_extract('src', ['huid'], type='varchar', alias='huid') }},
        {{ trx_json_extract('src', ['hupr'], type='int', alias='hupr') }},
        {{ trx_json_extract('src', ['hupr_kw'], type='varchar', alias='hupr_kw') }},
        {{ trx_json_extract('src', ['shid'], type='varchar', alias='shid') }},
        {{ trx_json_extract('src', ['shsq'], type='int', alias='shsq') }},
        {{ trx_json_extract('src', ['load'], type='varchar', alias='load') }},
        {{ trx_json_extract('src', ['shpm'], type='varchar', alias='shpm') }},
        {{ trx_json_extract('src', ['wght'], type='float', alias='wght') }},
        {{ trx_json_extract('src', ['wtun'], type='varchar', alias='wtun') }},
        {{ trx_json_extract('src', ['cpro', 'en_US'], type='varchar', alias='cpro__en_us') }},
        {{ trx_json_extract('src', ['blck'], type='int', alias='blck') }},
        {{ trx_json_extract('src', ['blck_kw'], type='varchar', alias='blck_kw') }},
        {{ trx_json_extract('src', ['resn'], type='varchar', alias='resn') }},
        {{ trx_json_extract('src', ['logn'], type='varchar', alias='logn') }},
        {{ trx_json_extract('src', ['casi'], type='varchar', alias='casi') }},
        {{ trx_json_extract('src', ['tsrl'], type='varchar', alias='tsrl') }},
        {{ trx_json_extract('src', ['tlot'], type='varchar', alias='tlot') }},
        {{ trx_json_extract('src', ['exrr'], type='varchar', alias='exrr') }},
        {{ trx_json_extract('src', ['spcn'], type='varchar', alias='spcn') }},
        {{ trx_json_extract('src', ['disp'], type='int', alias='disp') }},
        {{ trx_json_extract('src', ['disp_kw'], type='varchar', alias='disp_kw') }},
        {{ trx_json_extract('src', ['bgxc'], type='int', alias='bgxc') }},
        {{ trx_json_extract('src', ['bgxc_kw'], type='varchar', alias='bgxc_kw') }},
        {{ trx_json_extract('src', ['tcst'], type='int', alias='tcst') }},
        {{ trx_json_extract('src', ['tcst_kw'], type='varchar', alias='tcst_kw') }},
        {{ trx_json_extract('src', ['adin'], type='varchar', alias='adin') }},
        {{ trx_json_extract('src', ['csvl'], type='float', alias='csvl') }},
        {{ trx_json_extract('src', ['csvc'], type='varchar', alias='csvc') }},
        {{ trx_json_extract('src', ['rtcf'], type='varchar', alias='rtcf') }},
        {{ trx_json_extract('src', ['circ', 'en_US'], type='varchar', alias='circ__en_us') }},
        {{ trx_json_extract('src', ['imre', 'en_US'], type='varchar', alias='imre__en_us') }},
        {{ trx_json_extract('src', ['irdt'], type='timestamp_ntz', alias='irdt') }},
        {{ trx_json_extract('src', ['imrk', 'en_US'], type='varchar', alias='imrk__en_us') }},
        {{ trx_json_extract('src', ['imag'], type='varchar', alias='imag') }},
        {{ trx_json_extract('src', ['txtn'], type='int', alias='txtn') }},
        {{ trx_json_extract('src', ['itxt'], type='int', alias='itxt') }},
        {{ trx_json_extract('src', ['oorg_orno_pono_seqn_ref_compnr'], type='int', alias='oorg_orno_pono_seqn_ref_compnr') }},
        {{ trx_json_extract('src', ['sfbp_ref_compnr'], type='int', alias='sfbp_ref_compnr') }},
        {{ trx_json_extract('src', ['item_pkdf_ref_compnr'], type='int', alias='item_pkdf_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['atse_ref_compnr'], type='int', alias='atse_ref_compnr') }},
        {{ trx_json_extract('src', ['cmnf_ref_compnr'], type='int', alias='cmnf_ref_compnr') }},
        {{ trx_json_extract('src', ['effn_ref_compnr'], type='int', alias='effn_ref_compnr') }},
        {{ trx_json_extract('src', ['rowc_ref_compnr'], type='int', alias='rowc_ref_compnr') }},
        {{ trx_json_extract('src', ['rown_ref_compnr'], type='int', alias='rown_ref_compnr') }},
        {{ trx_json_extract('src', ['rcun_ref_compnr'], type='int', alias='rcun_ref_compnr') }},
        {{ trx_json_extract('src', ['psun_ref_compnr'], type='int', alias='psun_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_rclo_ref_compnr'], type='int', alias='cwar_rclo_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_dslo_ref_compnr'], type='int', alias='cwar_dslo_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['pkdf_ref_compnr'], type='int', alias='pkdf_ref_compnr') }},
        {{ trx_json_extract('src', ['huid_ref_compnr'], type='int', alias='huid_ref_compnr') }},
        {{ trx_json_extract('src', ['wtun_ref_compnr'], type='int', alias='wtun_ref_compnr') }},
        {{ trx_json_extract('src', ['resn_ref_compnr'], type='int', alias='resn_ref_compnr') }},
        {{ trx_json_extract('src', ['casi_ref_compnr'], type='int', alias='casi_ref_compnr') }},
        {{ trx_json_extract('src', ['csvc_ref_compnr'], type='int', alias='csvc_ref_compnr') }},
        {{ trx_json_extract('src', ['txtn_ref_compnr'], type='int', alias='txtn_ref_compnr') }},
        {{ trx_json_extract('src', ['itxt_ref_compnr'], type='int', alias='itxt_ref_compnr') }},
        {{ trx_json_extract('src', ['conv_buar'], type='float', alias='conv_buar') }},
        {{ trx_json_extract('src', ['conv_buln'], type='float', alias='conv_buln') }},
        {{ trx_json_extract('src', ['conv_buvl'], type='float', alias='conv_buvl') }},
        {{ trx_json_extract('src', ['conv_buwg'], type='float', alias='conv_buwg') }},
        {{ trx_json_extract('src', ['rcam_lclc'], type='float', alias='rcam_lclc') }},
        {{ trx_json_extract('src', ['rcam_rpc1'], type='float', alias='rcam_rpc1') }},
        {{ trx_json_extract('src', ['rcam_rpc2'], type='float', alias='rcam_rpc2') }},
        {{ trx_json_extract('src', ['rcam_rfrc'], type='float', alias='rcam_rfrc') }},
        {{ trx_json_extract('src', ['rcam_dtwc'], type='float', alias='rcam_dtwc') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_whinh312') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'rcno', 'rcln']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
