{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN whinh220 Outbound Order Lines table, Generated 2026-04-10T19:42:48Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['oorg'], type='int', alias='oorg') }},
        {{ trx_json_extract('src', ['oorg_kw'], type='varchar', alias='oorg_kw') }},
        {{ trx_json_extract('src', ['orno'], type='varchar', alias='orno') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['seqn'], type='int', alias='seqn') }},
        {{ trx_json_extract('src', ['oset'], type='int', alias='oset') }},
        {{ trx_json_extract('src', ['comp'], type='int', alias='comp') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['stad'], type='varchar', alias='stad') }},
        {{ trx_json_extract('src', ['dlpt'], type='varchar', alias='dlpt') }},
        {{ trx_json_extract('src', ['acvt'], type='int', alias='acvt') }},
        {{ trx_json_extract('src', ['acvt_kw'], type='varchar', alias='acvt_kw') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['atse'], type='varchar', alias='atse') }},
        {{ trx_json_extract('src', ['dtag'], type='varchar', alias='dtag') }},
        {{ trx_json_extract('src', ['serl'], type='varchar', alias='serl') }},
        {{ trx_json_extract('src', ['ssts'], type='int', alias='ssts') }},
        {{ trx_json_extract('src', ['ssts_kw'], type='varchar', alias='ssts_kw') }},
        {{ trx_json_extract('src', ['lsel'], type='int', alias='lsel') }},
        {{ trx_json_extract('src', ['lsel_kw'], type='varchar', alias='lsel_kw') }},
        {{ trx_json_extract('src', ['clot'], type='varchar', alias='clot') }},
        {{ trx_json_extract('src', ['effn'], type='int', alias='effn') }},
        {{ trx_json_extract('src', ['rowc'], type='int', alias='rowc') }},
        {{ trx_json_extract('src', ['rown'], type='varchar', alias='rown') }},
        {{ trx_json_extract('src', ['revi'], type='varchar', alias='revi') }},
        {{ trx_json_extract('src', ['circ', 'en_US'], type='varchar', alias='circ__en_us') }},
        {{ trx_json_extract('src', ['prio'], type='int', alias='prio') }},
        {{ trx_json_extract('src', ['qoro'], type='float', alias='qoro') }},
        {{ trx_json_extract('src', ['orun'], type='varchar', alias='orun') }},
        {{ trx_json_extract('src', ['ubin'], type='int', alias='ubin') }},
        {{ trx_json_extract('src', ['ubin_kw'], type='varchar', alias='ubin_kw') }},
        {{ trx_json_extract('src', ['hstq'], type='int', alias='hstq') }},
        {{ trx_json_extract('src', ['hstq_kw'], type='varchar', alias='hstq_kw') }},
        {{ trx_json_extract('src', ['qord'], type='float', alias='qord') }},
        {{ trx_json_extract('src', ['qorp'], type='float', alias='qorp') }},
        {{ trx_json_extract('src', ['qlin'], type='float', alias='qlin') }},
        {{ trx_json_extract('src', ['qlip'], type='float', alias='qlip') }},
        {{ trx_json_extract('src', ['qadv'], type='float', alias='qadv') }},
        {{ trx_json_extract('src', ['qadp'], type='float', alias='qadp') }},
        {{ trx_json_extract('src', ['qrel'], type='float', alias='qrel') }},
        {{ trx_json_extract('src', ['qrep'], type='float', alias='qrep') }},
        {{ trx_json_extract('src', ['qpic'], type='float', alias='qpic') }},
        {{ trx_json_extract('src', ['qpip'], type='float', alias='qpip') }},
        {{ trx_json_extract('src', ['qapr'], type='float', alias='qapr') }},
        {{ trx_json_extract('src', ['qapp'], type='float', alias='qapp') }},
        {{ trx_json_extract('src', ['qrej'], type='float', alias='qrej') }},
        {{ trx_json_extract('src', ['qrpu'], type='float', alias='qrpu') }},
        {{ trx_json_extract('src', ['qrsc'], type='float', alias='qrsc') }},
        {{ trx_json_extract('src', ['qrsp'], type='float', alias='qrsp') }},
        {{ trx_json_extract('src', ['qnse'], type='float', alias='qnse') }},
        {{ trx_json_extract('src', ['qnsp'], type='float', alias='qnsp') }},
        {{ trx_json_extract('src', ['qnsh'], type='float', alias='qnsh') }},
        {{ trx_json_extract('src', ['qnpu'], type='float', alias='qnpu') }},
        {{ trx_json_extract('src', ['qshp'], type='float', alias='qshp') }},
        {{ trx_json_extract('src', ['qspu'], type='float', alias='qspu') }},
        {{ trx_json_extract('src', ['qoor'], type='float', alias='qoor') }},
        {{ trx_json_extract('src', ['qoop'], type='float', alias='qoop') }},
        {{ trx_json_extract('src', ['qova'], type='float', alias='qova') }},
        {{ trx_json_extract('src', ['qovp'], type='float', alias='qovp') }},
        {{ trx_json_extract('src', ['qovd'], type='float', alias='qovd') }},
        {{ trx_json_extract('src', ['qopu'], type='float', alias='qopu') }},
        {{ trx_json_extract('src', ['oarq'], type='int', alias='oarq') }},
        {{ trx_json_extract('src', ['oarq_kw'], type='varchar', alias='oarq_kw') }},
        {{ trx_json_extract('src', ['scon'], type='int', alias='scon') }},
        {{ trx_json_extract('src', ['scon_kw'], type='varchar', alias='scon_kw') }},
        {{ trx_json_extract('src', ['qcnl'], type='float', alias='qcnl') }},
        {{ trx_json_extract('src', ['qcnp'], type='float', alias='qcnp') }},
        {{ trx_json_extract('src', ['qscl'], type='float', alias='qscl') }},
        {{ trx_json_extract('src', ['qscp'], type='float', alias='qscp') }},
        {{ trx_json_extract('src', ['fisc'], type='int', alias='fisc') }},
        {{ trx_json_extract('src', ['fisc_kw'], type='varchar', alias='fisc_kw') }},
        {{ trx_json_extract('src', ['pddt'], type='timestamp_ntz', alias='pddt') }},
        {{ trx_json_extract('src', ['prdt'], type='timestamp_ntz', alias='prdt') }},
        {{ trx_json_extract('src', ['addt'], type='timestamp_ntz', alias='addt') }},
        {{ trx_json_extract('src', ['inup'], type='int', alias='inup') }},
        {{ trx_json_extract('src', ['inup_kw'], type='varchar', alias='inup_kw') }},
        {{ trx_json_extract('src', ['bflh'], type='int', alias='bflh') }},
        {{ trx_json_extract('src', ['bflh_kw'], type='varchar', alias='bflh_kw') }},
        {{ trx_json_extract('src', ['rush'], type='int', alias='rush') }},
        {{ trx_json_extract('src', ['rush_kw'], type='varchar', alias='rush_kw') }},
        {{ trx_json_extract('src', ['cdck'], type='int', alias='cdck') }},
        {{ trx_json_extract('src', ['cdck_kw'], type='varchar', alias='cdck_kw') }},
        {{ trx_json_extract('src', ['qreq'], type='float', alias='qreq') }},
        {{ trx_json_extract('src', ['rqpu'], type='float', alias='rqpu') }},
        {{ trx_json_extract('src', ['qcad'], type='float', alias='qcad') }},
        {{ trx_json_extract('src', ['qcap'], type='float', alias='qcap') }},
        {{ trx_json_extract('src', ['qact'], type='float', alias='qact') }},
        {{ trx_json_extract('src', ['qacp'], type='float', alias='qacp') }},
        {{ trx_json_extract('src', ['qpss'], type='float', alias='qpss') }},
        {{ trx_json_extract('src', ['qpsv'], type='float', alias='qpsv') }},
        {{ trx_json_extract('src', ['qpsp'], type='float', alias='qpsp') }},
        {{ trx_json_extract('src', ['qprv'], type='float', alias='qprv') }},
        {{ trx_json_extract('src', ['qprp'], type='float', alias='qprp') }},
        {{ trx_json_extract('src', ['masp'], type='int', alias='masp') }},
        {{ trx_json_extract('src', ['masp_kw'], type='varchar', alias='masp_kw') }},
        {{ trx_json_extract('src', ['shrt'], type='int', alias='shrt') }},
        {{ trx_json_extract('src', ['shrt_kw'], type='varchar', alias='shrt_kw') }},
        {{ trx_json_extract('src', ['blck'], type='int', alias='blck') }},
        {{ trx_json_extract('src', ['blck_kw'], type='varchar', alias='blck_kw') }},
        {{ trx_json_extract('src', ['cncl'], type='int', alias='cncl') }},
        {{ trx_json_extract('src', ['cncl_kw'], type='varchar', alias='cncl_kw') }},
        {{ trx_json_extract('src', ['bcko'], type='int', alias='bcko') }},
        {{ trx_json_extract('src', ['bcko_kw'], type='varchar', alias='bcko_kw') }},
        {{ trx_json_extract('src', ['pkdf'], type='varchar', alias='pkdf') }},
        {{ trx_json_extract('src', ['pkdb'], type='int', alias='pkdb') }},
        {{ trx_json_extract('src', ['pkdb_kw'], type='varchar', alias='pkdb_kw') }},
        {{ trx_json_extract('src', ['iubw'], type='int', alias='iubw') }},
        {{ trx_json_extract('src', ['iubw_kw'], type='varchar', alias='iubw_kw') }},
        {{ trx_json_extract('src', ['gefo'], type='int', alias='gefo') }},
        {{ trx_json_extract('src', ['gefo_kw'], type='varchar', alias='gefo_kw') }},
        {{ trx_json_extract('src', ['fmor'], type='varchar', alias='fmor') }},
        {{ trx_json_extract('src', ['fmln'], type='int', alias='fmln') }},
        {{ trx_json_extract('src', ['ovlp'], type='int', alias='ovlp') }},
        {{ trx_json_extract('src', ['ovlp_kw'], type='varchar', alias='ovlp_kw') }},
        {{ trx_json_extract('src', ['ovfp'], type='int', alias='ovfp') }},
        {{ trx_json_extract('src', ['ovfp_kw'], type='varchar', alias='ovfp_kw') }},
        {{ trx_json_extract('src', ['uwop'], type='int', alias='uwop') }},
        {{ trx_json_extract('src', ['uwop_kw'], type='varchar', alias='uwop_kw') }},
        {{ trx_json_extract('src', ['orpr'], type='float', alias='orpr') }},
        {{ trx_json_extract('src', ['ocur'], type='varchar', alias='ocur') }},
        {{ trx_json_extract('src', ['csvl'], type='float', alias='csvl') }},
        {{ trx_json_extract('src', ['csvc'], type='varchar', alias='csvc') }},
        {{ trx_json_extract('src', ['rorg'], type='int', alias='rorg') }},
        {{ trx_json_extract('src', ['rorg_kw'], type='varchar', alias='rorg_kw') }},
        {{ trx_json_extract('src', ['rorn'], type='varchar', alias='rorn') }},
        {{ trx_json_extract('src', ['rpon'], type='int', alias='rpon') }},
        {{ trx_json_extract('src', ['rseq'], type='int', alias='rseq') }},
        {{ trx_json_extract('src', ['paym'], type='int', alias='paym') }},
        {{ trx_json_extract('src', ['paym_kw'], type='varchar', alias='paym_kw') }},
        {{ trx_json_extract('src', ['ipay'], type='int', alias='ipay') }},
        {{ trx_json_extract('src', ['ipay_kw'], type='varchar', alias='ipay_kw') }},
        {{ trx_json_extract('src', ['owns'], type='int', alias='owns') }},
        {{ trx_json_extract('src', ['owns_kw'], type='varchar', alias='owns_kw') }},
        {{ trx_json_extract('src', ['istr'], type='int', alias='istr') }},
        {{ trx_json_extract('src', ['istr_kw'], type='varchar', alias='istr_kw') }},
        {{ trx_json_extract('src', ['ifbp'], type='varchar', alias='ifbp') }},
        {{ trx_json_extract('src', ['iown'], type='int', alias='iown') }},
        {{ trx_json_extract('src', ['iown_kw'], type='varchar', alias='iown_kw') }},
        {{ trx_json_extract('src', ['huwt'], type='int', alias='huwt') }},
        {{ trx_json_extract('src', ['huwt_kw'], type='varchar', alias='huwt_kw') }},
        {{ trx_json_extract('src', ['fprj'], type='varchar', alias='fprj') }},
        {{ trx_json_extract('src', ['fspa'], type='varchar', alias='fspa') }},
        {{ trx_json_extract('src', ['fact'], type='varchar', alias='fact') }},
        {{ trx_json_extract('src', ['fstl'], type='varchar', alias='fstl') }},
        {{ trx_json_extract('src', ['fcco'], type='varchar', alias='fcco') }},
        {{ trx_json_extract('src', ['tprj'], type='varchar', alias='tprj') }},
        {{ trx_json_extract('src', ['tspa'], type='varchar', alias='tspa') }},
        {{ trx_json_extract('src', ['tact'], type='varchar', alias='tact') }},
        {{ trx_json_extract('src', ['tstl'], type='varchar', alias='tstl') }},
        {{ trx_json_extract('src', ['tcco'], type='varchar', alias='tcco') }},
        {{ trx_json_extract('src', ['prjp'], type='int', alias='prjp') }},
        {{ trx_json_extract('src', ['prjp_kw'], type='varchar', alias='prjp_kw') }},
        {{ trx_json_extract('src', ['acpn'], type='int', alias='acpn') }},
        {{ trx_json_extract('src', ['acpn_kw'], type='varchar', alias='acpn_kw') }},
        {{ trx_json_extract('src', ['spcn'], type='varchar', alias='spcn') }},
        {{ trx_json_extract('src', ['refe', 'en_US'], type='varchar', alias='refe__en_us') }},
        {{ trx_json_extract('src', ['refs', 'en_US'], type='varchar', alias='refs__en_us') }},
        {{ trx_json_extract('src', ['corn', 'en_US'], type='varchar', alias='corn__en_us') }},
        {{ trx_json_extract('src', ['adin'], type='varchar', alias='adin') }},
        {{ trx_json_extract('src', ['casi'], type='varchar', alias='casi') }},
        {{ trx_json_extract('src', ['gnld'], type='varchar', alias='gnld') }},
        {{ trx_json_extract('src', ['bgxc'], type='int', alias='bgxc') }},
        {{ trx_json_extract('src', ['bgxc_kw'], type='varchar', alias='bgxc_kw') }},
        {{ trx_json_extract('src', ['huid'], type='varchar', alias='huid') }},
        {{ trx_json_extract('src', ['iscn'], type='int', alias='iscn') }},
        {{ trx_json_extract('src', ['iscn_kw'], type='varchar', alias='iscn_kw') }},
        {{ trx_json_extract('src', ['imcs'], type='varchar', alias='imcs') }},
        {{ trx_json_extract('src', ['sups'], type='int', alias='sups') }},
        {{ trx_json_extract('src', ['sups_kw'], type='varchar', alias='sups_kw') }},
        {{ trx_json_extract('src', ['wmss'], type='int', alias='wmss') }},
        {{ trx_json_extract('src', ['wmss_kw'], type='varchar', alias='wmss_kw') }},
        {{ trx_json_extract('src', ['lsta'], type='int', alias='lsta') }},
        {{ trx_json_extract('src', ['lsta_kw'], type='varchar', alias='lsta_kw') }},
        {{ trx_json_extract('src', ['exsp'], type='int', alias='exsp') }},
        {{ trx_json_extract('src', ['exsp_kw'], type='varchar', alias='exsp_kw') }},
        {{ trx_json_extract('src', ['txtn'], type='int', alias='txtn') }},
        {{ trx_json_extract('src', ['oorg_orno_oset_ref_compnr'], type='int', alias='oorg_orno_oset_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['stad_dlpt_ref_compnr'], type='int', alias='stad_dlpt_ref_compnr') }},
        {{ trx_json_extract('src', ['item_clot_ref_compnr'], type='int', alias='item_clot_ref_compnr') }},
        {{ trx_json_extract('src', ['item_atse_ref_compnr'], type='int', alias='item_atse_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['atse_ref_compnr'], type='int', alias='atse_ref_compnr') }},
        {{ trx_json_extract('src', ['effn_ref_compnr'], type='int', alias='effn_ref_compnr') }},
        {{ trx_json_extract('src', ['rowc_ref_compnr'], type='int', alias='rowc_ref_compnr') }},
        {{ trx_json_extract('src', ['rown_ref_compnr'], type='int', alias='rown_ref_compnr') }},
        {{ trx_json_extract('src', ['orun_ref_compnr'], type='int', alias='orun_ref_compnr') }},
        {{ trx_json_extract('src', ['pkdf_ref_compnr'], type='int', alias='pkdf_ref_compnr') }},
        {{ trx_json_extract('src', ['ocur_ref_compnr'], type='int', alias='ocur_ref_compnr') }},
        {{ trx_json_extract('src', ['csvc_ref_compnr'], type='int', alias='csvc_ref_compnr') }},
        {{ trx_json_extract('src', ['ifbp_ref_compnr'], type='int', alias='ifbp_ref_compnr') }},
        {{ trx_json_extract('src', ['fprj_ref_compnr'], type='int', alias='fprj_ref_compnr') }},
        {{ trx_json_extract('src', ['fcco_ref_compnr'], type='int', alias='fcco_ref_compnr') }},
        {{ trx_json_extract('src', ['tprj_ref_compnr'], type='int', alias='tprj_ref_compnr') }},
        {{ trx_json_extract('src', ['tcco_ref_compnr'], type='int', alias='tcco_ref_compnr') }},
        {{ trx_json_extract('src', ['casi_ref_compnr'], type='int', alias='casi_ref_compnr') }},
        {{ trx_json_extract('src', ['txtn_ref_compnr'], type='int', alias='txtn_ref_compnr') }},
        {{ trx_json_extract('src', ['conv_buar'], type='float', alias='conv_buar') }},
        {{ trx_json_extract('src', ['conv_buln'], type='float', alias='conv_buln') }},
        {{ trx_json_extract('src', ['conv_buvl'], type='float', alias='conv_buvl') }},
        {{ trx_json_extract('src', ['conv_buwg'], type='float', alias='conv_buwg') }},
        {{ trx_json_extract('src', ['amnt_lclc'], type='float', alias='amnt_lclc') }},
        {{ trx_json_extract('src', ['amnt_rpc1'], type='float', alias='amnt_rpc1') }},
        {{ trx_json_extract('src', ['amnt_rpc2'], type='float', alias='amnt_rpc2') }},
        {{ trx_json_extract('src', ['amnt_rfrc'], type='float', alias='amnt_rfrc') }},
        {{ trx_json_extract('src', ['amnt_dtwc'], type='float', alias='amnt_dtwc') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_whinh220') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'oorg', 'orno', 'pono', 'seqn']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
