{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='LN whinh431 Shipment Lines table, Generated 2026-04-10T19:42:50Z from package combination ce01101',
    tags=['auto-generated', 'ln', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['compnr'], type='int', alias='compnr') }},
        {{ trx_json_extract('src', ['shpm'], type='varchar', alias='shpm') }},
        {{ trx_json_extract('src', ['pono'], type='int', alias='pono') }},
        {{ trx_json_extract('src', ['shst'], type='int', alias='shst') }},
        {{ trx_json_extract('src', ['shst_kw'], type='varchar', alias='shst_kw') }},
        {{ trx_json_extract('src', ['item'], type='varchar', alias='item') }},
        {{ trx_json_extract('src', ['atse'], type='varchar', alias='atse') }},
        {{ trx_json_extract('src', ['sttg'], type='varchar', alias='sttg') }},
        {{ trx_json_extract('src', ['effn'], type='int', alias='effn') }},
        {{ trx_json_extract('src', ['clot'], type='varchar', alias='clot') }},
        {{ trx_json_extract('src', ['rowc'], type='int', alias='rowc') }},
        {{ trx_json_extract('src', ['rown'], type='varchar', alias='rown') }},
        {{ trx_json_extract('src', ['serl'], type='varchar', alias='serl') }},
        {{ trx_json_extract('src', ['idat'], type='timestamp_ntz', alias='idat') }},
        {{ trx_json_extract('src', ['cuni'], type='varchar', alias='cuni') }},
        {{ trx_json_extract('src', ['qadv'], type='float', alias='qadv') }},
        {{ trx_json_extract('src', ['qadp'], type='float', alias='qadp') }},
        {{ trx_json_extract('src', ['qpic'], type='float', alias='qpic') }},
        {{ trx_json_extract('src', ['qppu'], type='float', alias='qppu') }},
        {{ trx_json_extract('src', ['qshp'], type='float', alias='qshp') }},
        {{ trx_json_extract('src', ['qspu'], type='float', alias='qspu') }},
        {{ trx_json_extract('src', ['qnsh'], type='float', alias='qnsh') }},
        {{ trx_json_extract('src', ['qnpu'], type='float', alias='qnpu') }},
        {{ trx_json_extract('src', ['qprv'], type='float', alias='qprv') }},
        {{ trx_json_extract('src', ['qprp'], type='float', alias='qprp') }},
        {{ trx_json_extract('src', ['adjs'], type='int', alias='adjs') }},
        {{ trx_json_extract('src', ['adjs_kw'], type='varchar', alias='adjs_kw') }},
        {{ trx_json_extract('src', ['recd'], type='varchar', alias='recd') }},
        {{ trx_json_extract('src', ['qrcp'], type='float', alias='qrcp') }},
        {{ trx_json_extract('src', ['grwt'], type='float', alias='grwt') }},
        {{ trx_json_extract('src', ['ntwt'], type='float', alias='ntwt') }},
        {{ trx_json_extract('src', ['cwun'], type='varchar', alias='cwun') }},
        {{ trx_json_extract('src', ['pbol'], type='int', alias='pbol') }},
        {{ trx_json_extract('src', ['pbol_kw'], type='varchar', alias='pbol_kw') }},
        {{ trx_json_extract('src', ['bolp'], type='int', alias='bolp') }},
        {{ trx_json_extract('src', ['worg'], type='int', alias='worg') }},
        {{ trx_json_extract('src', ['worg_kw'], type='varchar', alias='worg_kw') }},
        {{ trx_json_extract('src', ['worn'], type='varchar', alias='worn') }},
        {{ trx_json_extract('src', ['wset'], type='int', alias='wset') }},
        {{ trx_json_extract('src', ['wpon'], type='int', alias='wpon') }},
        {{ trx_json_extract('src', ['wseq'], type='int', alias='wseq') }},
        {{ trx_json_extract('src', ['boml'], type='int', alias='boml') }},
        {{ trx_json_extract('src', ['rseq'], type='int', alias='rseq') }},
        {{ trx_json_extract('src', ['pwsq'], type='int', alias='pwsq') }},
        {{ trx_json_extract('src', ['cwar'], type='varchar', alias='cwar') }},
        {{ trx_json_extract('src', ['loca'], type='varchar', alias='loca') }},
        {{ trx_json_extract('src', ['refe', 'en_US'], type='varchar', alias='refe__en_us') }},
        {{ trx_json_extract('src', ['refs', 'en_US'], type='varchar', alias='refs__en_us') }},
        {{ trx_json_extract('src', ['corn', 'en_US'], type='varchar', alias='corn__en_us') }},
        {{ trx_json_extract('src', ['iadj'], type='int', alias='iadj') }},
        {{ trx_json_extract('src', ['iadj_kw'], type='varchar', alias='iadj_kw') }},
        {{ trx_json_extract('src', ['iadt'], type='timestamp_ntz', alias='iadt') }},
        {{ trx_json_extract('src', ['cons'], type='int', alias='cons') }},
        {{ trx_json_extract('src', ['cons_kw'], type='varchar', alias='cons_kw') }},
        {{ trx_json_extract('src', ['pkdf'], type='varchar', alias='pkdf') }},
        {{ trx_json_extract('src', ['sppk'], type='int', alias='sppk') }},
        {{ trx_json_extract('src', ['sppk_kw'], type='varchar', alias='sppk_kw') }},
        {{ trx_json_extract('src', ['serp'], type='int', alias='serp') }},
        {{ trx_json_extract('src', ['serp_kw'], type='varchar', alias='serp_kw') }},
        {{ trx_json_extract('src', ['ttyp'], type='varchar', alias='ttyp') }},
        {{ trx_json_extract('src', ['cinv'], type='int', alias='cinv') }},
        {{ trx_json_extract('src', ['invd'], type='timestamp_ntz', alias='invd') }},
        {{ trx_json_extract('src', ['itrd'], type='timestamp_ntz', alias='itrd') }},
        {{ trx_json_extract('src', ['ilgd'], type='timestamp_ntz', alias='ilgd') }},
        {{ trx_json_extract('src', ['ssqd'], type='int', alias='ssqd') }},
        {{ trx_json_extract('src', ['hupr'], type='int', alias='hupr') }},
        {{ trx_json_extract('src', ['hupr_kw'], type='varchar', alias='hupr_kw') }},
        {{ trx_json_extract('src', ['huid'], type='varchar', alias='huid') }},
        {{ trx_json_extract('src', ['casi'], type='varchar', alias='casi') }},
        {{ trx_json_extract('src', ['pmsk'], type='varchar', alias='pmsk') }},
        {{ trx_json_extract('src', ['acti', 'en_US'], type='varchar', alias='acti__en_us') }},
        {{ trx_json_extract('src', ['manl'], type='int', alias='manl') }},
        {{ trx_json_extract('src', ['manl_kw'], type='varchar', alias='manl_kw') }},
        {{ trx_json_extract('src', ['csvl'], type='float', alias='csvl') }},
        {{ trx_json_extract('src', ['csvc'], type='varchar', alias='csvc') }},
        {{ trx_json_extract('src', ['nspb'], type='int', alias='nspb') }},
        {{ trx_json_extract('src', ['nspb_kw'], type='varchar', alias='nspb_kw') }},
        {{ trx_json_extract('src', ['ctyo'], type='varchar', alias='ctyo') }},
        {{ trx_json_extract('src', ['addc'], type='int', alias='addc') }},
        {{ trx_json_extract('src', ['addc_kw'], type='varchar', alias='addc_kw') }},
        {{ trx_json_extract('src', ['amnt'], type='float', alias='amnt') }},
        {{ trx_json_extract('src', ['stad'], type='varchar', alias='stad') }},
        {{ trx_json_extract('src', ['dlpt'], type='varchar', alias='dlpt') }},
        {{ trx_json_extract('src', ['adin'], type='varchar', alias='adin') }},
        {{ trx_json_extract('src', ['bgxc'], type='int', alias='bgxc') }},
        {{ trx_json_extract('src', ['bgxc_kw'], type='varchar', alias='bgxc_kw') }},
        {{ trx_json_extract('src', ['aclr'], type='int', alias='aclr') }},
        {{ trx_json_extract('src', ['aclr_kw'], type='varchar', alias='aclr_kw') }},
        {{ trx_json_extract('src', ['acfl'], type='int', alias='acfl') }},
        {{ trx_json_extract('src', ['circ', 'en_US'], type='varchar', alias='circ__en_us') }},
        {{ trx_json_extract('src', ['dphu'], type='int', alias='dphu') }},
        {{ trx_json_extract('src', ['dphu_kw'], type='varchar', alias='dphu_kw') }},
        {{ trx_json_extract('src', ['sarq'], type='int', alias='sarq') }},
        {{ trx_json_extract('src', ['sarq_kw'], type='varchar', alias='sarq_kw') }},
        {{ trx_json_extract('src', ['aqty'], type='float', alias='aqty') }},
        {{ trx_json_extract('src', ['darq'], type='int', alias='darq') }},
        {{ trx_json_extract('src', ['darq_kw'], type='varchar', alias='darq_kw') }},
        {{ trx_json_extract('src', ['rqty'], type='float', alias='rqty') }},
        {{ trx_json_extract('src', ['frsm'], type='int', alias='frsm') }},
        {{ trx_json_extract('src', ['frsm_kw'], type='varchar', alias='frsm_kw') }},
        {{ trx_json_extract('src', ['shvl'], type='int', alias='shvl') }},
        {{ trx_json_extract('src', ['shvl_kw'], type='varchar', alias='shvl_kw') }},
        {{ trx_json_extract('src', ['psde'], type='int', alias='psde') }},
        {{ trx_json_extract('src', ['psde_kw'], type='varchar', alias='psde_kw') }},
        {{ trx_json_extract('src', ['hubc'], type='int', alias='hubc') }},
        {{ trx_json_extract('src', ['hubc_kw'], type='varchar', alias='hubc_kw') }},
        {{ trx_json_extract('src', ['fisc'], type='int', alias='fisc') }},
        {{ trx_json_extract('src', ['fisc_kw'], type='varchar', alias='fisc_kw') }},
        {{ trx_json_extract('src', ['tcst'], type='int', alias='tcst') }},
        {{ trx_json_extract('src', ['tcst_kw'], type='varchar', alias='tcst_kw') }},
        {{ trx_json_extract('src', ['exfr'], type='int', alias='exfr') }},
        {{ trx_json_extract('src', ['exfr_kw'], type='varchar', alias='exfr_kw') }},
        {{ trx_json_extract('src', ['imag'], type='varchar', alias='imag') }},
        {{ trx_json_extract('src', ['atxt'], type='int', alias='atxt') }},
        {{ trx_json_extract('src', ['dtxt'], type='int', alias='dtxt') }},
        {{ trx_json_extract('src', ['text'], type='int', alias='text') }},
        {{ trx_json_extract('src', ['shpm_ref_compnr'], type='int', alias='shpm_ref_compnr') }},
        {{ trx_json_extract('src', ['item_clot_ref_compnr'], type='int', alias='item_clot_ref_compnr') }},
        {{ trx_json_extract('src', ['item_ref_compnr'], type='int', alias='item_ref_compnr') }},
        {{ trx_json_extract('src', ['atse_ref_compnr'], type='int', alias='atse_ref_compnr') }},
        {{ trx_json_extract('src', ['effn_ref_compnr'], type='int', alias='effn_ref_compnr') }},
        {{ trx_json_extract('src', ['rowc_ref_compnr'], type='int', alias='rowc_ref_compnr') }},
        {{ trx_json_extract('src', ['rown_ref_compnr'], type='int', alias='rown_ref_compnr') }},
        {{ trx_json_extract('src', ['cuni_ref_compnr'], type='int', alias='cuni_ref_compnr') }},
        {{ trx_json_extract('src', ['recd_ref_compnr'], type='int', alias='recd_ref_compnr') }},
        {{ trx_json_extract('src', ['cwun_ref_compnr'], type='int', alias='cwun_ref_compnr') }},
        {{ trx_json_extract('src', ['worn_wpon_pwsq_ssqd_ref_compnr'], type='int', alias='worn_wpon_pwsq_ssqd_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_loca_ref_compnr'], type='int', alias='cwar_loca_ref_compnr') }},
        {{ trx_json_extract('src', ['cwar_ref_compnr'], type='int', alias='cwar_ref_compnr') }},
        {{ trx_json_extract('src', ['huid_ref_compnr'], type='int', alias='huid_ref_compnr') }},
        {{ trx_json_extract('src', ['casi_ref_compnr'], type='int', alias='casi_ref_compnr') }},
        {{ trx_json_extract('src', ['csvc_ref_compnr'], type='int', alias='csvc_ref_compnr') }},
        {{ trx_json_extract('src', ['ctyo_ref_compnr'], type='int', alias='ctyo_ref_compnr') }},
        {{ trx_json_extract('src', ['stad_dlpt_ref_compnr'], type='int', alias='stad_dlpt_ref_compnr') }},
        {{ trx_json_extract('src', ['stad_ref_compnr'], type='int', alias='stad_ref_compnr') }},
        {{ trx_json_extract('src', ['atxt_ref_compnr'], type='int', alias='atxt_ref_compnr') }},
        {{ trx_json_extract('src', ['dtxt_ref_compnr'], type='int', alias='dtxt_ref_compnr') }},
        {{ trx_json_extract('src', ['text_ref_compnr'], type='int', alias='text_ref_compnr') }},
        {{ trx_json_extract('src', ['conv_buar'], type='float', alias='conv_buar') }},
        {{ trx_json_extract('src', ['conv_buln'], type='float', alias='conv_buln') }},
        {{ trx_json_extract('src', ['conv_buvl'], type='float', alias='conv_buvl') }},
        {{ trx_json_extract('src', ['conv_buwg'], type='float', alias='conv_buwg') }},
        {{ trx_json_extract('src', ['amnt_rpc1'], type='float', alias='amnt_rpc1') }},
        {{ trx_json_extract('src', ['amnt_rpc2'], type='float', alias='amnt_rpc2') }},
        {{ trx_json_extract('src', ['amnt_rfrc'], type='float', alias='amnt_rfrc') }},
        {{ trx_json_extract('src', ['amnt_dtwc'], type='float', alias='amnt_dtwc') }},
        {{ trx_json_extract('src', ['sham_lclc'], type='float', alias='sham_lclc') }},
        {{ trx_json_extract('src', ['sham_rpc1'], type='float', alias='sham_rpc1') }},
        {{ trx_json_extract('src', ['sham_rpc2'], type='float', alias='sham_rpc2') }},
        {{ trx_json_extract('src', ['sham_rfrc'], type='float', alias='sham_rfrc') }},
        {{ trx_json_extract('src', ['sham_dtwc'], type='float', alias='sham_dtwc') }},
        {{ trx_json_extract('src', ['deleted'], type='boolean', alias='deleted') }},
        {{ trx_json_extract('src', ['username'], type='varchar', alias='username') }},
        {{ trx_json_extract('src', ['timestamp'], type='timestamp_ntz', alias='timestamp') }},
        {{ trx_json_extract('src', ['sequencenumber'], type='int', alias='sequencenumber') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_ln', 'ln_whinh431') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['compnr', 'shpm', 'pono']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['sequencenumber']) }}
