create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5STORES()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5STORES_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5STORES as target using (SELECT * FROM (SELECT 
            strm.STR_AUTOAPPVSTATUS, 
            strm.STR_AUTOPOSTATUS, 
            strm.STR_CLASS, 
            strm.STR_CLASS_ORG, 
            strm.STR_CODE, 
            strm.STR_COPY, 
            strm.STR_CREATED, 
            strm.STR_DESC, 
            strm.STR_ENTERPRISELOCATION, 
            strm.STR_FACILITY, 
            strm.STR_FRIDAY, 
            strm.STR_HELDITEMSNONPOTEMPLATE, 
            strm.STR_HELDITEMSPOTEMPLATE, 
            strm.STR_HELDITEMSRECEIPTTEMPLATE, 
            strm.STR_HELDITEMSSTKTRSTEMPLATE, 
            strm.STR_HELDITEMSTOSTKTRSTEMPLATE, 
            strm.STR_HELDITEMSTRSTEMPLATE, 
            strm.STR_INTERNALLEADTIME, 
            strm.STR_ISSUETEMPLATE, 
            strm.STR_LASTSAVED, 
            strm.STR_LASTSTATUSUPDATE, 
            strm.STR_LEADTIME, 
            strm.STR_LOCATION, 
            strm.STR_LOCATION_ORG, 
            strm.STR_LTYPE, 
            strm.STR_MONDAY, 
            strm.STR_NONPOTEMPLATE, 
            strm.STR_NOTUSED, 
            strm.STR_ORG, 
            strm.STR_PARENT, 
            strm.STR_PRICECODE, 
            strm.STR_PRICETYPE, 
            strm.STR_PRINTER, 
            strm.STR_PRINTSERVER, 
            strm.STR_RECEIPTTEMPLATE, 
            strm.STR_RESERVEDPARTBUFFER, 
            strm.STR_SATURDAY, 
            strm.STR_SEGMENTVALUE, 
            strm.STR_STRECEIPTTEMPLATE, 
            strm.STR_SUNDAY, 
            strm.STR_SYSTEM, 
            strm.STR_SYSTEM_ORG, 
            strm.STR_TAX_PARTS, 
            strm.STR_TAX_SERVICES, 
            strm.STR_THURSDAY, 
            strm.STR_TUESDAY, 
            strm.STR_UDFCHAR01, 
            strm.STR_UDFCHAR02, 
            strm.STR_UDFCHAR03, 
            strm.STR_UDFCHAR04, 
            strm.STR_UDFCHAR05, 
            strm.STR_UDFCHAR06, 
            strm.STR_UDFCHAR07, 
            strm.STR_UDFCHAR08, 
            strm.STR_UDFCHAR09, 
            strm.STR_UDFCHAR10, 
            strm.STR_UDFCHAR11, 
            strm.STR_UDFCHAR12, 
            strm.STR_UDFCHAR13, 
            strm.STR_UDFCHAR14, 
            strm.STR_UDFCHAR15, 
            strm.STR_UDFCHAR16, 
            strm.STR_UDFCHAR17, 
            strm.STR_UDFCHAR18, 
            strm.STR_UDFCHAR19, 
            strm.STR_UDFCHAR20, 
            strm.STR_UDFCHAR21, 
            strm.STR_UDFCHAR22, 
            strm.STR_UDFCHAR23, 
            strm.STR_UDFCHAR24, 
            strm.STR_UDFCHAR25, 
            strm.STR_UDFCHAR26, 
            strm.STR_UDFCHAR27, 
            strm.STR_UDFCHAR28, 
            strm.STR_UDFCHAR29, 
            strm.STR_UDFCHAR30, 
            strm.STR_UDFCHKBOX01, 
            strm.STR_UDFCHKBOX02, 
            strm.STR_UDFCHKBOX03, 
            strm.STR_UDFCHKBOX04, 
            strm.STR_UDFCHKBOX05, 
            strm.STR_UDFDATE01, 
            strm.STR_UDFDATE02, 
            strm.STR_UDFDATE03, 
            strm.STR_UDFDATE04, 
            strm.STR_UDFDATE05, 
            strm.STR_UDFNUM01, 
            strm.STR_UDFNUM02, 
            strm.STR_UDFNUM03, 
            strm.STR_UDFNUM04, 
            strm.STR_UDFNUM05, 
            strm.STR_UPDATECOUNT, 
            strm.STR_UPDATED, 
            strm.STR_WARRANTYTEMPLATE, 
            strm.STR_WEDNESDAY, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.STR_CODE ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5STORES as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.STR_CODE=src.STR_CODE) OR (target.STR_CODE IS NULL AND src.STR_CODE IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.STR_AUTOAPPVSTATUS=src.STR_AUTOAPPVSTATUS, 
                    target.STR_AUTOPOSTATUS=src.STR_AUTOPOSTATUS, 
                    target.STR_CLASS=src.STR_CLASS, 
                    target.STR_CLASS_ORG=src.STR_CLASS_ORG, 
                    target.STR_CODE=src.STR_CODE, 
                    target.STR_COPY=src.STR_COPY, 
                    target.STR_CREATED=src.STR_CREATED, 
                    target.STR_DESC=src.STR_DESC, 
                    target.STR_ENTERPRISELOCATION=src.STR_ENTERPRISELOCATION, 
                    target.STR_FACILITY=src.STR_FACILITY, 
                    target.STR_FRIDAY=src.STR_FRIDAY, 
                    target.STR_HELDITEMSNONPOTEMPLATE=src.STR_HELDITEMSNONPOTEMPLATE, 
                    target.STR_HELDITEMSPOTEMPLATE=src.STR_HELDITEMSPOTEMPLATE, 
                    target.STR_HELDITEMSRECEIPTTEMPLATE=src.STR_HELDITEMSRECEIPTTEMPLATE, 
                    target.STR_HELDITEMSSTKTRSTEMPLATE=src.STR_HELDITEMSSTKTRSTEMPLATE, 
                    target.STR_HELDITEMSTOSTKTRSTEMPLATE=src.STR_HELDITEMSTOSTKTRSTEMPLATE, 
                    target.STR_HELDITEMSTRSTEMPLATE=src.STR_HELDITEMSTRSTEMPLATE, 
                    target.STR_INTERNALLEADTIME=src.STR_INTERNALLEADTIME, 
                    target.STR_ISSUETEMPLATE=src.STR_ISSUETEMPLATE, 
                    target.STR_LASTSAVED=src.STR_LASTSAVED, 
                    target.STR_LASTSTATUSUPDATE=src.STR_LASTSTATUSUPDATE, 
                    target.STR_LEADTIME=src.STR_LEADTIME, 
                    target.STR_LOCATION=src.STR_LOCATION, 
                    target.STR_LOCATION_ORG=src.STR_LOCATION_ORG, 
                    target.STR_LTYPE=src.STR_LTYPE, 
                    target.STR_MONDAY=src.STR_MONDAY, 
                    target.STR_NONPOTEMPLATE=src.STR_NONPOTEMPLATE, 
                    target.STR_NOTUSED=src.STR_NOTUSED, 
                    target.STR_ORG=src.STR_ORG, 
                    target.STR_PARENT=src.STR_PARENT, 
                    target.STR_PRICECODE=src.STR_PRICECODE, 
                    target.STR_PRICETYPE=src.STR_PRICETYPE, 
                    target.STR_PRINTER=src.STR_PRINTER, 
                    target.STR_PRINTSERVER=src.STR_PRINTSERVER, 
                    target.STR_RECEIPTTEMPLATE=src.STR_RECEIPTTEMPLATE, 
                    target.STR_RESERVEDPARTBUFFER=src.STR_RESERVEDPARTBUFFER, 
                    target.STR_SATURDAY=src.STR_SATURDAY, 
                    target.STR_SEGMENTVALUE=src.STR_SEGMENTVALUE, 
                    target.STR_STRECEIPTTEMPLATE=src.STR_STRECEIPTTEMPLATE, 
                    target.STR_SUNDAY=src.STR_SUNDAY, 
                    target.STR_SYSTEM=src.STR_SYSTEM, 
                    target.STR_SYSTEM_ORG=src.STR_SYSTEM_ORG, 
                    target.STR_TAX_PARTS=src.STR_TAX_PARTS, 
                    target.STR_TAX_SERVICES=src.STR_TAX_SERVICES, 
                    target.STR_THURSDAY=src.STR_THURSDAY, 
                    target.STR_TUESDAY=src.STR_TUESDAY, 
                    target.STR_UDFCHAR01=src.STR_UDFCHAR01, 
                    target.STR_UDFCHAR02=src.STR_UDFCHAR02, 
                    target.STR_UDFCHAR03=src.STR_UDFCHAR03, 
                    target.STR_UDFCHAR04=src.STR_UDFCHAR04, 
                    target.STR_UDFCHAR05=src.STR_UDFCHAR05, 
                    target.STR_UDFCHAR06=src.STR_UDFCHAR06, 
                    target.STR_UDFCHAR07=src.STR_UDFCHAR07, 
                    target.STR_UDFCHAR08=src.STR_UDFCHAR08, 
                    target.STR_UDFCHAR09=src.STR_UDFCHAR09, 
                    target.STR_UDFCHAR10=src.STR_UDFCHAR10, 
                    target.STR_UDFCHAR11=src.STR_UDFCHAR11, 
                    target.STR_UDFCHAR12=src.STR_UDFCHAR12, 
                    target.STR_UDFCHAR13=src.STR_UDFCHAR13, 
                    target.STR_UDFCHAR14=src.STR_UDFCHAR14, 
                    target.STR_UDFCHAR15=src.STR_UDFCHAR15, 
                    target.STR_UDFCHAR16=src.STR_UDFCHAR16, 
                    target.STR_UDFCHAR17=src.STR_UDFCHAR17, 
                    target.STR_UDFCHAR18=src.STR_UDFCHAR18, 
                    target.STR_UDFCHAR19=src.STR_UDFCHAR19, 
                    target.STR_UDFCHAR20=src.STR_UDFCHAR20, 
                    target.STR_UDFCHAR21=src.STR_UDFCHAR21, 
                    target.STR_UDFCHAR22=src.STR_UDFCHAR22, 
                    target.STR_UDFCHAR23=src.STR_UDFCHAR23, 
                    target.STR_UDFCHAR24=src.STR_UDFCHAR24, 
                    target.STR_UDFCHAR25=src.STR_UDFCHAR25, 
                    target.STR_UDFCHAR26=src.STR_UDFCHAR26, 
                    target.STR_UDFCHAR27=src.STR_UDFCHAR27, 
                    target.STR_UDFCHAR28=src.STR_UDFCHAR28, 
                    target.STR_UDFCHAR29=src.STR_UDFCHAR29, 
                    target.STR_UDFCHAR30=src.STR_UDFCHAR30, 
                    target.STR_UDFCHKBOX01=src.STR_UDFCHKBOX01, 
                    target.STR_UDFCHKBOX02=src.STR_UDFCHKBOX02, 
                    target.STR_UDFCHKBOX03=src.STR_UDFCHKBOX03, 
                    target.STR_UDFCHKBOX04=src.STR_UDFCHKBOX04, 
                    target.STR_UDFCHKBOX05=src.STR_UDFCHKBOX05, 
                    target.STR_UDFDATE01=src.STR_UDFDATE01, 
                    target.STR_UDFDATE02=src.STR_UDFDATE02, 
                    target.STR_UDFDATE03=src.STR_UDFDATE03, 
                    target.STR_UDFDATE04=src.STR_UDFDATE04, 
                    target.STR_UDFDATE05=src.STR_UDFDATE05, 
                    target.STR_UDFNUM01=src.STR_UDFNUM01, 
                    target.STR_UDFNUM02=src.STR_UDFNUM02, 
                    target.STR_UDFNUM03=src.STR_UDFNUM03, 
                    target.STR_UDFNUM04=src.STR_UDFNUM04, 
                    target.STR_UDFNUM05=src.STR_UDFNUM05, 
                    target.STR_UPDATECOUNT=src.STR_UPDATECOUNT, 
                    target.STR_UPDATED=src.STR_UPDATED, 
                    target.STR_WARRANTYTEMPLATE=src.STR_WARRANTYTEMPLATE, 
                    target.STR_WEDNESDAY=src.STR_WEDNESDAY, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    STR_AUTOAPPVSTATUS, 
                    STR_AUTOPOSTATUS, 
                    STR_CLASS, 
                    STR_CLASS_ORG, 
                    STR_CODE, 
                    STR_COPY, 
                    STR_CREATED, 
                    STR_DESC, 
                    STR_ENTERPRISELOCATION, 
                    STR_FACILITY, 
                    STR_FRIDAY, 
                    STR_HELDITEMSNONPOTEMPLATE, 
                    STR_HELDITEMSPOTEMPLATE, 
                    STR_HELDITEMSRECEIPTTEMPLATE, 
                    STR_HELDITEMSSTKTRSTEMPLATE, 
                    STR_HELDITEMSTOSTKTRSTEMPLATE, 
                    STR_HELDITEMSTRSTEMPLATE, 
                    STR_INTERNALLEADTIME, 
                    STR_ISSUETEMPLATE, 
                    STR_LASTSAVED, 
                    STR_LASTSTATUSUPDATE, 
                    STR_LEADTIME, 
                    STR_LOCATION, 
                    STR_LOCATION_ORG, 
                    STR_LTYPE, 
                    STR_MONDAY, 
                    STR_NONPOTEMPLATE, 
                    STR_NOTUSED, 
                    STR_ORG, 
                    STR_PARENT, 
                    STR_PRICECODE, 
                    STR_PRICETYPE, 
                    STR_PRINTER, 
                    STR_PRINTSERVER, 
                    STR_RECEIPTTEMPLATE, 
                    STR_RESERVEDPARTBUFFER, 
                    STR_SATURDAY, 
                    STR_SEGMENTVALUE, 
                    STR_STRECEIPTTEMPLATE, 
                    STR_SUNDAY, 
                    STR_SYSTEM, 
                    STR_SYSTEM_ORG, 
                    STR_TAX_PARTS, 
                    STR_TAX_SERVICES, 
                    STR_THURSDAY, 
                    STR_TUESDAY, 
                    STR_UDFCHAR01, 
                    STR_UDFCHAR02, 
                    STR_UDFCHAR03, 
                    STR_UDFCHAR04, 
                    STR_UDFCHAR05, 
                    STR_UDFCHAR06, 
                    STR_UDFCHAR07, 
                    STR_UDFCHAR08, 
                    STR_UDFCHAR09, 
                    STR_UDFCHAR10, 
                    STR_UDFCHAR11, 
                    STR_UDFCHAR12, 
                    STR_UDFCHAR13, 
                    STR_UDFCHAR14, 
                    STR_UDFCHAR15, 
                    STR_UDFCHAR16, 
                    STR_UDFCHAR17, 
                    STR_UDFCHAR18, 
                    STR_UDFCHAR19, 
                    STR_UDFCHAR20, 
                    STR_UDFCHAR21, 
                    STR_UDFCHAR22, 
                    STR_UDFCHAR23, 
                    STR_UDFCHAR24, 
                    STR_UDFCHAR25, 
                    STR_UDFCHAR26, 
                    STR_UDFCHAR27, 
                    STR_UDFCHAR28, 
                    STR_UDFCHAR29, 
                    STR_UDFCHAR30, 
                    STR_UDFCHKBOX01, 
                    STR_UDFCHKBOX02, 
                    STR_UDFCHKBOX03, 
                    STR_UDFCHKBOX04, 
                    STR_UDFCHKBOX05, 
                    STR_UDFDATE01, 
                    STR_UDFDATE02, 
                    STR_UDFDATE03, 
                    STR_UDFDATE04, 
                    STR_UDFDATE05, 
                    STR_UDFNUM01, 
                    STR_UDFNUM02, 
                    STR_UDFNUM03, 
                    STR_UDFNUM04, 
                    STR_UDFNUM05, 
                    STR_UPDATECOUNT, 
                    STR_UPDATED, 
                    STR_WARRANTYTEMPLATE, 
                    STR_WEDNESDAY, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.STR_AUTOAPPVSTATUS, 
                    src.STR_AUTOPOSTATUS, 
                    src.STR_CLASS, 
                    src.STR_CLASS_ORG, 
                    src.STR_CODE, 
                    src.STR_COPY, 
                    src.STR_CREATED, 
                    src.STR_DESC, 
                    src.STR_ENTERPRISELOCATION, 
                    src.STR_FACILITY, 
                    src.STR_FRIDAY, 
                    src.STR_HELDITEMSNONPOTEMPLATE, 
                    src.STR_HELDITEMSPOTEMPLATE, 
                    src.STR_HELDITEMSRECEIPTTEMPLATE, 
                    src.STR_HELDITEMSSTKTRSTEMPLATE, 
                    src.STR_HELDITEMSTOSTKTRSTEMPLATE, 
                    src.STR_HELDITEMSTRSTEMPLATE, 
                    src.STR_INTERNALLEADTIME, 
                    src.STR_ISSUETEMPLATE, 
                    src.STR_LASTSAVED, 
                    src.STR_LASTSTATUSUPDATE, 
                    src.STR_LEADTIME, 
                    src.STR_LOCATION, 
                    src.STR_LOCATION_ORG, 
                    src.STR_LTYPE, 
                    src.STR_MONDAY, 
                    src.STR_NONPOTEMPLATE, 
                    src.STR_NOTUSED, 
                    src.STR_ORG, 
                    src.STR_PARENT, 
                    src.STR_PRICECODE, 
                    src.STR_PRICETYPE, 
                    src.STR_PRINTER, 
                    src.STR_PRINTSERVER, 
                    src.STR_RECEIPTTEMPLATE, 
                    src.STR_RESERVEDPARTBUFFER, 
                    src.STR_SATURDAY, 
                    src.STR_SEGMENTVALUE, 
                    src.STR_STRECEIPTTEMPLATE, 
                    src.STR_SUNDAY, 
                    src.STR_SYSTEM, 
                    src.STR_SYSTEM_ORG, 
                    src.STR_TAX_PARTS, 
                    src.STR_TAX_SERVICES, 
                    src.STR_THURSDAY, 
                    src.STR_TUESDAY, 
                    src.STR_UDFCHAR01, 
                    src.STR_UDFCHAR02, 
                    src.STR_UDFCHAR03, 
                    src.STR_UDFCHAR04, 
                    src.STR_UDFCHAR05, 
                    src.STR_UDFCHAR06, 
                    src.STR_UDFCHAR07, 
                    src.STR_UDFCHAR08, 
                    src.STR_UDFCHAR09, 
                    src.STR_UDFCHAR10, 
                    src.STR_UDFCHAR11, 
                    src.STR_UDFCHAR12, 
                    src.STR_UDFCHAR13, 
                    src.STR_UDFCHAR14, 
                    src.STR_UDFCHAR15, 
                    src.STR_UDFCHAR16, 
                    src.STR_UDFCHAR17, 
                    src.STR_UDFCHAR18, 
                    src.STR_UDFCHAR19, 
                    src.STR_UDFCHAR20, 
                    src.STR_UDFCHAR21, 
                    src.STR_UDFCHAR22, 
                    src.STR_UDFCHAR23, 
                    src.STR_UDFCHAR24, 
                    src.STR_UDFCHAR25, 
                    src.STR_UDFCHAR26, 
                    src.STR_UDFCHAR27, 
                    src.STR_UDFCHAR28, 
                    src.STR_UDFCHAR29, 
                    src.STR_UDFCHAR30, 
                    src.STR_UDFCHKBOX01, 
                    src.STR_UDFCHKBOX02, 
                    src.STR_UDFCHKBOX03, 
                    src.STR_UDFCHKBOX04, 
                    src.STR_UDFCHKBOX05, 
                    src.STR_UDFDATE01, 
                    src.STR_UDFDATE02, 
                    src.STR_UDFDATE03, 
                    src.STR_UDFDATE04, 
                    src.STR_UDFDATE05, 
                    src.STR_UDFNUM01, 
                    src.STR_UDFNUM02, 
                    src.STR_UDFNUM03, 
                    src.STR_UDFNUM04, 
                    src.STR_UDFNUM05, 
                    src.STR_UPDATECOUNT, 
                    src.STR_UPDATED, 
                    src.STR_WARRANTYTEMPLATE, 
                    src.STR_WEDNESDAY, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5STORES_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.STR_AUTOAPPVSTATUS, 
            strm.STR_AUTOPOSTATUS, 
            strm.STR_CLASS, 
            strm.STR_CLASS_ORG, 
            strm.STR_CODE, 
            strm.STR_COPY, 
            strm.STR_CREATED, 
            strm.STR_DESC, 
            strm.STR_ENTERPRISELOCATION, 
            strm.STR_FACILITY, 
            strm.STR_FRIDAY, 
            strm.STR_HELDITEMSNONPOTEMPLATE, 
            strm.STR_HELDITEMSPOTEMPLATE, 
            strm.STR_HELDITEMSRECEIPTTEMPLATE, 
            strm.STR_HELDITEMSSTKTRSTEMPLATE, 
            strm.STR_HELDITEMSTOSTKTRSTEMPLATE, 
            strm.STR_HELDITEMSTRSTEMPLATE, 
            strm.STR_INTERNALLEADTIME, 
            strm.STR_ISSUETEMPLATE, 
            strm.STR_LASTSAVED, 
            strm.STR_LASTSTATUSUPDATE, 
            strm.STR_LEADTIME, 
            strm.STR_LOCATION, 
            strm.STR_LOCATION_ORG, 
            strm.STR_LTYPE, 
            strm.STR_MONDAY, 
            strm.STR_NONPOTEMPLATE, 
            strm.STR_NOTUSED, 
            strm.STR_ORG, 
            strm.STR_PARENT, 
            strm.STR_PRICECODE, 
            strm.STR_PRICETYPE, 
            strm.STR_PRINTER, 
            strm.STR_PRINTSERVER, 
            strm.STR_RECEIPTTEMPLATE, 
            strm.STR_RESERVEDPARTBUFFER, 
            strm.STR_SATURDAY, 
            strm.STR_SEGMENTVALUE, 
            strm.STR_STRECEIPTTEMPLATE, 
            strm.STR_SUNDAY, 
            strm.STR_SYSTEM, 
            strm.STR_SYSTEM_ORG, 
            strm.STR_TAX_PARTS, 
            strm.STR_TAX_SERVICES, 
            strm.STR_THURSDAY, 
            strm.STR_TUESDAY, 
            strm.STR_UDFCHAR01, 
            strm.STR_UDFCHAR02, 
            strm.STR_UDFCHAR03, 
            strm.STR_UDFCHAR04, 
            strm.STR_UDFCHAR05, 
            strm.STR_UDFCHAR06, 
            strm.STR_UDFCHAR07, 
            strm.STR_UDFCHAR08, 
            strm.STR_UDFCHAR09, 
            strm.STR_UDFCHAR10, 
            strm.STR_UDFCHAR11, 
            strm.STR_UDFCHAR12, 
            strm.STR_UDFCHAR13, 
            strm.STR_UDFCHAR14, 
            strm.STR_UDFCHAR15, 
            strm.STR_UDFCHAR16, 
            strm.STR_UDFCHAR17, 
            strm.STR_UDFCHAR18, 
            strm.STR_UDFCHAR19, 
            strm.STR_UDFCHAR20, 
            strm.STR_UDFCHAR21, 
            strm.STR_UDFCHAR22, 
            strm.STR_UDFCHAR23, 
            strm.STR_UDFCHAR24, 
            strm.STR_UDFCHAR25, 
            strm.STR_UDFCHAR26, 
            strm.STR_UDFCHAR27, 
            strm.STR_UDFCHAR28, 
            strm.STR_UDFCHAR29, 
            strm.STR_UDFCHAR30, 
            strm.STR_UDFCHKBOX01, 
            strm.STR_UDFCHKBOX02, 
            strm.STR_UDFCHKBOX03, 
            strm.STR_UDFCHKBOX04, 
            strm.STR_UDFCHKBOX05, 
            strm.STR_UDFDATE01, 
            strm.STR_UDFDATE02, 
            strm.STR_UDFDATE03, 
            strm.STR_UDFDATE04, 
            strm.STR_UDFDATE05, 
            strm.STR_UDFNUM01, 
            strm.STR_UDFNUM02, 
            strm.STR_UDFNUM03, 
            strm.STR_UDFNUM04, 
            strm.STR_UDFNUM05, 
            strm.STR_UPDATECOUNT, 
            strm.STR_UPDATED, 
            strm.STR_WARRANTYTEMPLATE, 
            strm.STR_WEDNESDAY, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.STR_CODE ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5STORES as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.STR_CODE=src.STR_CODE) OR (target.STR_CODE IS NULL AND src.STR_CODE IS NULL)) 
                when matched then update set
                    target.STR_AUTOAPPVSTATUS=src.STR_AUTOAPPVSTATUS, 
                    target.STR_AUTOPOSTATUS=src.STR_AUTOPOSTATUS, 
                    target.STR_CLASS=src.STR_CLASS, 
                    target.STR_CLASS_ORG=src.STR_CLASS_ORG, 
                    target.STR_CODE=src.STR_CODE, 
                    target.STR_COPY=src.STR_COPY, 
                    target.STR_CREATED=src.STR_CREATED, 
                    target.STR_DESC=src.STR_DESC, 
                    target.STR_ENTERPRISELOCATION=src.STR_ENTERPRISELOCATION, 
                    target.STR_FACILITY=src.STR_FACILITY, 
                    target.STR_FRIDAY=src.STR_FRIDAY, 
                    target.STR_HELDITEMSNONPOTEMPLATE=src.STR_HELDITEMSNONPOTEMPLATE, 
                    target.STR_HELDITEMSPOTEMPLATE=src.STR_HELDITEMSPOTEMPLATE, 
                    target.STR_HELDITEMSRECEIPTTEMPLATE=src.STR_HELDITEMSRECEIPTTEMPLATE, 
                    target.STR_HELDITEMSSTKTRSTEMPLATE=src.STR_HELDITEMSSTKTRSTEMPLATE, 
                    target.STR_HELDITEMSTOSTKTRSTEMPLATE=src.STR_HELDITEMSTOSTKTRSTEMPLATE, 
                    target.STR_HELDITEMSTRSTEMPLATE=src.STR_HELDITEMSTRSTEMPLATE, 
                    target.STR_INTERNALLEADTIME=src.STR_INTERNALLEADTIME, 
                    target.STR_ISSUETEMPLATE=src.STR_ISSUETEMPLATE, 
                    target.STR_LASTSAVED=src.STR_LASTSAVED, 
                    target.STR_LASTSTATUSUPDATE=src.STR_LASTSTATUSUPDATE, 
                    target.STR_LEADTIME=src.STR_LEADTIME, 
                    target.STR_LOCATION=src.STR_LOCATION, 
                    target.STR_LOCATION_ORG=src.STR_LOCATION_ORG, 
                    target.STR_LTYPE=src.STR_LTYPE, 
                    target.STR_MONDAY=src.STR_MONDAY, 
                    target.STR_NONPOTEMPLATE=src.STR_NONPOTEMPLATE, 
                    target.STR_NOTUSED=src.STR_NOTUSED, 
                    target.STR_ORG=src.STR_ORG, 
                    target.STR_PARENT=src.STR_PARENT, 
                    target.STR_PRICECODE=src.STR_PRICECODE, 
                    target.STR_PRICETYPE=src.STR_PRICETYPE, 
                    target.STR_PRINTER=src.STR_PRINTER, 
                    target.STR_PRINTSERVER=src.STR_PRINTSERVER, 
                    target.STR_RECEIPTTEMPLATE=src.STR_RECEIPTTEMPLATE, 
                    target.STR_RESERVEDPARTBUFFER=src.STR_RESERVEDPARTBUFFER, 
                    target.STR_SATURDAY=src.STR_SATURDAY, 
                    target.STR_SEGMENTVALUE=src.STR_SEGMENTVALUE, 
                    target.STR_STRECEIPTTEMPLATE=src.STR_STRECEIPTTEMPLATE, 
                    target.STR_SUNDAY=src.STR_SUNDAY, 
                    target.STR_SYSTEM=src.STR_SYSTEM, 
                    target.STR_SYSTEM_ORG=src.STR_SYSTEM_ORG, 
                    target.STR_TAX_PARTS=src.STR_TAX_PARTS, 
                    target.STR_TAX_SERVICES=src.STR_TAX_SERVICES, 
                    target.STR_THURSDAY=src.STR_THURSDAY, 
                    target.STR_TUESDAY=src.STR_TUESDAY, 
                    target.STR_UDFCHAR01=src.STR_UDFCHAR01, 
                    target.STR_UDFCHAR02=src.STR_UDFCHAR02, 
                    target.STR_UDFCHAR03=src.STR_UDFCHAR03, 
                    target.STR_UDFCHAR04=src.STR_UDFCHAR04, 
                    target.STR_UDFCHAR05=src.STR_UDFCHAR05, 
                    target.STR_UDFCHAR06=src.STR_UDFCHAR06, 
                    target.STR_UDFCHAR07=src.STR_UDFCHAR07, 
                    target.STR_UDFCHAR08=src.STR_UDFCHAR08, 
                    target.STR_UDFCHAR09=src.STR_UDFCHAR09, 
                    target.STR_UDFCHAR10=src.STR_UDFCHAR10, 
                    target.STR_UDFCHAR11=src.STR_UDFCHAR11, 
                    target.STR_UDFCHAR12=src.STR_UDFCHAR12, 
                    target.STR_UDFCHAR13=src.STR_UDFCHAR13, 
                    target.STR_UDFCHAR14=src.STR_UDFCHAR14, 
                    target.STR_UDFCHAR15=src.STR_UDFCHAR15, 
                    target.STR_UDFCHAR16=src.STR_UDFCHAR16, 
                    target.STR_UDFCHAR17=src.STR_UDFCHAR17, 
                    target.STR_UDFCHAR18=src.STR_UDFCHAR18, 
                    target.STR_UDFCHAR19=src.STR_UDFCHAR19, 
                    target.STR_UDFCHAR20=src.STR_UDFCHAR20, 
                    target.STR_UDFCHAR21=src.STR_UDFCHAR21, 
                    target.STR_UDFCHAR22=src.STR_UDFCHAR22, 
                    target.STR_UDFCHAR23=src.STR_UDFCHAR23, 
                    target.STR_UDFCHAR24=src.STR_UDFCHAR24, 
                    target.STR_UDFCHAR25=src.STR_UDFCHAR25, 
                    target.STR_UDFCHAR26=src.STR_UDFCHAR26, 
                    target.STR_UDFCHAR27=src.STR_UDFCHAR27, 
                    target.STR_UDFCHAR28=src.STR_UDFCHAR28, 
                    target.STR_UDFCHAR29=src.STR_UDFCHAR29, 
                    target.STR_UDFCHAR30=src.STR_UDFCHAR30, 
                    target.STR_UDFCHKBOX01=src.STR_UDFCHKBOX01, 
                    target.STR_UDFCHKBOX02=src.STR_UDFCHKBOX02, 
                    target.STR_UDFCHKBOX03=src.STR_UDFCHKBOX03, 
                    target.STR_UDFCHKBOX04=src.STR_UDFCHKBOX04, 
                    target.STR_UDFCHKBOX05=src.STR_UDFCHKBOX05, 
                    target.STR_UDFDATE01=src.STR_UDFDATE01, 
                    target.STR_UDFDATE02=src.STR_UDFDATE02, 
                    target.STR_UDFDATE03=src.STR_UDFDATE03, 
                    target.STR_UDFDATE04=src.STR_UDFDATE04, 
                    target.STR_UDFDATE05=src.STR_UDFDATE05, 
                    target.STR_UDFNUM01=src.STR_UDFNUM01, 
                    target.STR_UDFNUM02=src.STR_UDFNUM02, 
                    target.STR_UDFNUM03=src.STR_UDFNUM03, 
                    target.STR_UDFNUM04=src.STR_UDFNUM04, 
                    target.STR_UDFNUM05=src.STR_UDFNUM05, 
                    target.STR_UPDATECOUNT=src.STR_UPDATECOUNT, 
                    target.STR_UPDATED=src.STR_UPDATED, 
                    target.STR_WARRANTYTEMPLATE=src.STR_WARRANTYTEMPLATE, 
                    target.STR_WEDNESDAY=src.STR_WEDNESDAY, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( STR_AUTOAPPVSTATUS, STR_AUTOPOSTATUS, STR_CLASS, STR_CLASS_ORG, STR_CODE, STR_COPY, STR_CREATED, STR_DESC, STR_ENTERPRISELOCATION, STR_FACILITY, STR_FRIDAY, STR_HELDITEMSNONPOTEMPLATE, STR_HELDITEMSPOTEMPLATE, STR_HELDITEMSRECEIPTTEMPLATE, STR_HELDITEMSSTKTRSTEMPLATE, STR_HELDITEMSTOSTKTRSTEMPLATE, STR_HELDITEMSTRSTEMPLATE, STR_INTERNALLEADTIME, STR_ISSUETEMPLATE, STR_LASTSAVED, STR_LASTSTATUSUPDATE, STR_LEADTIME, STR_LOCATION, STR_LOCATION_ORG, STR_LTYPE, STR_MONDAY, STR_NONPOTEMPLATE, STR_NOTUSED, STR_ORG, STR_PARENT, STR_PRICECODE, STR_PRICETYPE, STR_PRINTER, STR_PRINTSERVER, STR_RECEIPTTEMPLATE, STR_RESERVEDPARTBUFFER, STR_SATURDAY, STR_SEGMENTVALUE, STR_STRECEIPTTEMPLATE, STR_SUNDAY, STR_SYSTEM, STR_SYSTEM_ORG, STR_TAX_PARTS, STR_TAX_SERVICES, STR_THURSDAY, STR_TUESDAY, STR_UDFCHAR01, STR_UDFCHAR02, STR_UDFCHAR03, STR_UDFCHAR04, STR_UDFCHAR05, STR_UDFCHAR06, STR_UDFCHAR07, STR_UDFCHAR08, STR_UDFCHAR09, STR_UDFCHAR10, STR_UDFCHAR11, STR_UDFCHAR12, STR_UDFCHAR13, STR_UDFCHAR14, STR_UDFCHAR15, STR_UDFCHAR16, STR_UDFCHAR17, STR_UDFCHAR18, STR_UDFCHAR19, STR_UDFCHAR20, STR_UDFCHAR21, STR_UDFCHAR22, STR_UDFCHAR23, STR_UDFCHAR24, STR_UDFCHAR25, STR_UDFCHAR26, STR_UDFCHAR27, STR_UDFCHAR28, STR_UDFCHAR29, STR_UDFCHAR30, STR_UDFCHKBOX01, STR_UDFCHKBOX02, STR_UDFCHKBOX03, STR_UDFCHKBOX04, STR_UDFCHKBOX05, STR_UDFDATE01, STR_UDFDATE02, STR_UDFDATE03, STR_UDFDATE04, STR_UDFDATE05, STR_UDFNUM01, STR_UDFNUM02, STR_UDFNUM03, STR_UDFNUM04, STR_UDFNUM05, STR_UPDATECOUNT, STR_UPDATED, STR_WARRANTYTEMPLATE, STR_WEDNESDAY, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.STR_AUTOAPPVSTATUS, 
                    src.STR_AUTOPOSTATUS, 
                    src.STR_CLASS, 
                    src.STR_CLASS_ORG, 
                    src.STR_CODE, 
                    src.STR_COPY, 
                    src.STR_CREATED, 
                    src.STR_DESC, 
                    src.STR_ENTERPRISELOCATION, 
                    src.STR_FACILITY, 
                    src.STR_FRIDAY, 
                    src.STR_HELDITEMSNONPOTEMPLATE, 
                    src.STR_HELDITEMSPOTEMPLATE, 
                    src.STR_HELDITEMSRECEIPTTEMPLATE, 
                    src.STR_HELDITEMSSTKTRSTEMPLATE, 
                    src.STR_HELDITEMSTOSTKTRSTEMPLATE, 
                    src.STR_HELDITEMSTRSTEMPLATE, 
                    src.STR_INTERNALLEADTIME, 
                    src.STR_ISSUETEMPLATE, 
                    src.STR_LASTSAVED, 
                    src.STR_LASTSTATUSUPDATE, 
                    src.STR_LEADTIME, 
                    src.STR_LOCATION, 
                    src.STR_LOCATION_ORG, 
                    src.STR_LTYPE, 
                    src.STR_MONDAY, 
                    src.STR_NONPOTEMPLATE, 
                    src.STR_NOTUSED, 
                    src.STR_ORG, 
                    src.STR_PARENT, 
                    src.STR_PRICECODE, 
                    src.STR_PRICETYPE, 
                    src.STR_PRINTER, 
                    src.STR_PRINTSERVER, 
                    src.STR_RECEIPTTEMPLATE, 
                    src.STR_RESERVEDPARTBUFFER, 
                    src.STR_SATURDAY, 
                    src.STR_SEGMENTVALUE, 
                    src.STR_STRECEIPTTEMPLATE, 
                    src.STR_SUNDAY, 
                    src.STR_SYSTEM, 
                    src.STR_SYSTEM_ORG, 
                    src.STR_TAX_PARTS, 
                    src.STR_TAX_SERVICES, 
                    src.STR_THURSDAY, 
                    src.STR_TUESDAY, 
                    src.STR_UDFCHAR01, 
                    src.STR_UDFCHAR02, 
                    src.STR_UDFCHAR03, 
                    src.STR_UDFCHAR04, 
                    src.STR_UDFCHAR05, 
                    src.STR_UDFCHAR06, 
                    src.STR_UDFCHAR07, 
                    src.STR_UDFCHAR08, 
                    src.STR_UDFCHAR09, 
                    src.STR_UDFCHAR10, 
                    src.STR_UDFCHAR11, 
                    src.STR_UDFCHAR12, 
                    src.STR_UDFCHAR13, 
                    src.STR_UDFCHAR14, 
                    src.STR_UDFCHAR15, 
                    src.STR_UDFCHAR16, 
                    src.STR_UDFCHAR17, 
                    src.STR_UDFCHAR18, 
                    src.STR_UDFCHAR19, 
                    src.STR_UDFCHAR20, 
                    src.STR_UDFCHAR21, 
                    src.STR_UDFCHAR22, 
                    src.STR_UDFCHAR23, 
                    src.STR_UDFCHAR24, 
                    src.STR_UDFCHAR25, 
                    src.STR_UDFCHAR26, 
                    src.STR_UDFCHAR27, 
                    src.STR_UDFCHAR28, 
                    src.STR_UDFCHAR29, 
                    src.STR_UDFCHAR30, 
                    src.STR_UDFCHKBOX01, 
                    src.STR_UDFCHKBOX02, 
                    src.STR_UDFCHKBOX03, 
                    src.STR_UDFCHKBOX04, 
                    src.STR_UDFCHKBOX05, 
                    src.STR_UDFDATE01, 
                    src.STR_UDFDATE02, 
                    src.STR_UDFDATE03, 
                    src.STR_UDFDATE04, 
                    src.STR_UDFDATE05, 
                    src.STR_UDFNUM01, 
                    src.STR_UDFNUM02, 
                    src.STR_UDFNUM03, 
                    src.STR_UDFNUM04, 
                    src.STR_UDFNUM05, 
                    src.STR_UPDATECOUNT, 
                    src.STR_UPDATED, 
                    src.STR_WARRANTYTEMPLATE, 
                    src.STR_WEDNESDAY, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;