create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5OBJECTASPECTS()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5OBJECTASPECTS_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5OBJECTASPECTS as target using (SELECT * FROM (SELECT 
            strm.OBA_ASPECT, 
            strm.OBA_CONFRATING, 
            strm.OBA_FACTOR, 
            strm.OBA_LASTSAVED, 
            strm.OBA_MAX, 
            strm.OBA_MAXEXTR, 
            strm.OBA_MAXFORMULA, 
            strm.OBA_MAXPPM, 
            strm.OBA_MAXSTWO, 
            strm.OBA_MAXTOL, 
            strm.OBA_METHOD, 
            strm.OBA_MIN, 
            strm.OBA_MINEXTR, 
            strm.OBA_MINFORMULA, 
            strm.OBA_MINPPM, 
            strm.OBA_MINSTWO, 
            strm.OBA_MINTOL, 
            strm.OBA_NOMINAL, 
            strm.OBA_OBJECT, 
            strm.OBA_OBJECT_ORG, 
            strm.OBA_OBRTYPE, 
            strm.OBA_OBTYPE, 
            strm.OBA_REPLACEFREQ, 
            strm.OBA_RISK, 
            strm.OBA_UDFCHAR01, 
            strm.OBA_UDFCHAR02, 
            strm.OBA_UDFCHAR03, 
            strm.OBA_UDFCHAR04, 
            strm.OBA_UDFCHAR05, 
            strm.OBA_UDFCHAR06, 
            strm.OBA_UDFCHAR07, 
            strm.OBA_UDFCHAR08, 
            strm.OBA_UDFCHAR09, 
            strm.OBA_UDFCHAR10, 
            strm.OBA_UDFCHAR11, 
            strm.OBA_UDFCHAR12, 
            strm.OBA_UDFCHAR13, 
            strm.OBA_UDFCHAR14, 
            strm.OBA_UDFCHAR15, 
            strm.OBA_UDFCHAR16, 
            strm.OBA_UDFCHAR17, 
            strm.OBA_UDFCHAR18, 
            strm.OBA_UDFCHAR19, 
            strm.OBA_UDFCHAR20, 
            strm.OBA_UDFCHAR21, 
            strm.OBA_UDFCHAR22, 
            strm.OBA_UDFCHAR23, 
            strm.OBA_UDFCHAR24, 
            strm.OBA_UDFCHAR25, 
            strm.OBA_UDFCHAR26, 
            strm.OBA_UDFCHAR27, 
            strm.OBA_UDFCHAR28, 
            strm.OBA_UDFCHAR29, 
            strm.OBA_UDFCHAR30, 
            strm.OBA_UDFCHKBOX01, 
            strm.OBA_UDFCHKBOX02, 
            strm.OBA_UDFCHKBOX03, 
            strm.OBA_UDFCHKBOX04, 
            strm.OBA_UDFCHKBOX05, 
            strm.OBA_UDFDATE01, 
            strm.OBA_UDFDATE02, 
            strm.OBA_UDFDATE03, 
            strm.OBA_UDFDATE04, 
            strm.OBA_UDFDATE05, 
            strm.OBA_UDFNUM01, 
            strm.OBA_UDFNUM02, 
            strm.OBA_UDFNUM03, 
            strm.OBA_UDFNUM04, 
            strm.OBA_UDFNUM05, 
            strm.OBA_UOM, 
            strm.OBA_UPDATECOUNT, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.OBA_OBJECT,
            strm.OBA_OBJECT_ORG,
            strm.OBA_OBTYPE,
            strm.OBA_ASPECT ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5OBJECTASPECTS as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.OBA_OBJECT=src.OBA_OBJECT) OR (target.OBA_OBJECT IS NULL AND src.OBA_OBJECT IS NULL)) AND
            ((target.OBA_OBJECT_ORG=src.OBA_OBJECT_ORG) OR (target.OBA_OBJECT_ORG IS NULL AND src.OBA_OBJECT_ORG IS NULL)) AND
            ((target.OBA_OBTYPE=src.OBA_OBTYPE) OR (target.OBA_OBTYPE IS NULL AND src.OBA_OBTYPE IS NULL)) AND
            ((target.OBA_ASPECT=src.OBA_ASPECT) OR (target.OBA_ASPECT IS NULL AND src.OBA_ASPECT IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.OBA_ASPECT=src.OBA_ASPECT, 
                    target.OBA_CONFRATING=src.OBA_CONFRATING, 
                    target.OBA_FACTOR=src.OBA_FACTOR, 
                    target.OBA_LASTSAVED=src.OBA_LASTSAVED, 
                    target.OBA_MAX=src.OBA_MAX, 
                    target.OBA_MAXEXTR=src.OBA_MAXEXTR, 
                    target.OBA_MAXFORMULA=src.OBA_MAXFORMULA, 
                    target.OBA_MAXPPM=src.OBA_MAXPPM, 
                    target.OBA_MAXSTWO=src.OBA_MAXSTWO, 
                    target.OBA_MAXTOL=src.OBA_MAXTOL, 
                    target.OBA_METHOD=src.OBA_METHOD, 
                    target.OBA_MIN=src.OBA_MIN, 
                    target.OBA_MINEXTR=src.OBA_MINEXTR, 
                    target.OBA_MINFORMULA=src.OBA_MINFORMULA, 
                    target.OBA_MINPPM=src.OBA_MINPPM, 
                    target.OBA_MINSTWO=src.OBA_MINSTWO, 
                    target.OBA_MINTOL=src.OBA_MINTOL, 
                    target.OBA_NOMINAL=src.OBA_NOMINAL, 
                    target.OBA_OBJECT=src.OBA_OBJECT, 
                    target.OBA_OBJECT_ORG=src.OBA_OBJECT_ORG, 
                    target.OBA_OBRTYPE=src.OBA_OBRTYPE, 
                    target.OBA_OBTYPE=src.OBA_OBTYPE, 
                    target.OBA_REPLACEFREQ=src.OBA_REPLACEFREQ, 
                    target.OBA_RISK=src.OBA_RISK, 
                    target.OBA_UDFCHAR01=src.OBA_UDFCHAR01, 
                    target.OBA_UDFCHAR02=src.OBA_UDFCHAR02, 
                    target.OBA_UDFCHAR03=src.OBA_UDFCHAR03, 
                    target.OBA_UDFCHAR04=src.OBA_UDFCHAR04, 
                    target.OBA_UDFCHAR05=src.OBA_UDFCHAR05, 
                    target.OBA_UDFCHAR06=src.OBA_UDFCHAR06, 
                    target.OBA_UDFCHAR07=src.OBA_UDFCHAR07, 
                    target.OBA_UDFCHAR08=src.OBA_UDFCHAR08, 
                    target.OBA_UDFCHAR09=src.OBA_UDFCHAR09, 
                    target.OBA_UDFCHAR10=src.OBA_UDFCHAR10, 
                    target.OBA_UDFCHAR11=src.OBA_UDFCHAR11, 
                    target.OBA_UDFCHAR12=src.OBA_UDFCHAR12, 
                    target.OBA_UDFCHAR13=src.OBA_UDFCHAR13, 
                    target.OBA_UDFCHAR14=src.OBA_UDFCHAR14, 
                    target.OBA_UDFCHAR15=src.OBA_UDFCHAR15, 
                    target.OBA_UDFCHAR16=src.OBA_UDFCHAR16, 
                    target.OBA_UDFCHAR17=src.OBA_UDFCHAR17, 
                    target.OBA_UDFCHAR18=src.OBA_UDFCHAR18, 
                    target.OBA_UDFCHAR19=src.OBA_UDFCHAR19, 
                    target.OBA_UDFCHAR20=src.OBA_UDFCHAR20, 
                    target.OBA_UDFCHAR21=src.OBA_UDFCHAR21, 
                    target.OBA_UDFCHAR22=src.OBA_UDFCHAR22, 
                    target.OBA_UDFCHAR23=src.OBA_UDFCHAR23, 
                    target.OBA_UDFCHAR24=src.OBA_UDFCHAR24, 
                    target.OBA_UDFCHAR25=src.OBA_UDFCHAR25, 
                    target.OBA_UDFCHAR26=src.OBA_UDFCHAR26, 
                    target.OBA_UDFCHAR27=src.OBA_UDFCHAR27, 
                    target.OBA_UDFCHAR28=src.OBA_UDFCHAR28, 
                    target.OBA_UDFCHAR29=src.OBA_UDFCHAR29, 
                    target.OBA_UDFCHAR30=src.OBA_UDFCHAR30, 
                    target.OBA_UDFCHKBOX01=src.OBA_UDFCHKBOX01, 
                    target.OBA_UDFCHKBOX02=src.OBA_UDFCHKBOX02, 
                    target.OBA_UDFCHKBOX03=src.OBA_UDFCHKBOX03, 
                    target.OBA_UDFCHKBOX04=src.OBA_UDFCHKBOX04, 
                    target.OBA_UDFCHKBOX05=src.OBA_UDFCHKBOX05, 
                    target.OBA_UDFDATE01=src.OBA_UDFDATE01, 
                    target.OBA_UDFDATE02=src.OBA_UDFDATE02, 
                    target.OBA_UDFDATE03=src.OBA_UDFDATE03, 
                    target.OBA_UDFDATE04=src.OBA_UDFDATE04, 
                    target.OBA_UDFDATE05=src.OBA_UDFDATE05, 
                    target.OBA_UDFNUM01=src.OBA_UDFNUM01, 
                    target.OBA_UDFNUM02=src.OBA_UDFNUM02, 
                    target.OBA_UDFNUM03=src.OBA_UDFNUM03, 
                    target.OBA_UDFNUM04=src.OBA_UDFNUM04, 
                    target.OBA_UDFNUM05=src.OBA_UDFNUM05, 
                    target.OBA_UOM=src.OBA_UOM, 
                    target.OBA_UPDATECOUNT=src.OBA_UPDATECOUNT, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    OBA_ASPECT, 
                    OBA_CONFRATING, 
                    OBA_FACTOR, 
                    OBA_LASTSAVED, 
                    OBA_MAX, 
                    OBA_MAXEXTR, 
                    OBA_MAXFORMULA, 
                    OBA_MAXPPM, 
                    OBA_MAXSTWO, 
                    OBA_MAXTOL, 
                    OBA_METHOD, 
                    OBA_MIN, 
                    OBA_MINEXTR, 
                    OBA_MINFORMULA, 
                    OBA_MINPPM, 
                    OBA_MINSTWO, 
                    OBA_MINTOL, 
                    OBA_NOMINAL, 
                    OBA_OBJECT, 
                    OBA_OBJECT_ORG, 
                    OBA_OBRTYPE, 
                    OBA_OBTYPE, 
                    OBA_REPLACEFREQ, 
                    OBA_RISK, 
                    OBA_UDFCHAR01, 
                    OBA_UDFCHAR02, 
                    OBA_UDFCHAR03, 
                    OBA_UDFCHAR04, 
                    OBA_UDFCHAR05, 
                    OBA_UDFCHAR06, 
                    OBA_UDFCHAR07, 
                    OBA_UDFCHAR08, 
                    OBA_UDFCHAR09, 
                    OBA_UDFCHAR10, 
                    OBA_UDFCHAR11, 
                    OBA_UDFCHAR12, 
                    OBA_UDFCHAR13, 
                    OBA_UDFCHAR14, 
                    OBA_UDFCHAR15, 
                    OBA_UDFCHAR16, 
                    OBA_UDFCHAR17, 
                    OBA_UDFCHAR18, 
                    OBA_UDFCHAR19, 
                    OBA_UDFCHAR20, 
                    OBA_UDFCHAR21, 
                    OBA_UDFCHAR22, 
                    OBA_UDFCHAR23, 
                    OBA_UDFCHAR24, 
                    OBA_UDFCHAR25, 
                    OBA_UDFCHAR26, 
                    OBA_UDFCHAR27, 
                    OBA_UDFCHAR28, 
                    OBA_UDFCHAR29, 
                    OBA_UDFCHAR30, 
                    OBA_UDFCHKBOX01, 
                    OBA_UDFCHKBOX02, 
                    OBA_UDFCHKBOX03, 
                    OBA_UDFCHKBOX04, 
                    OBA_UDFCHKBOX05, 
                    OBA_UDFDATE01, 
                    OBA_UDFDATE02, 
                    OBA_UDFDATE03, 
                    OBA_UDFDATE04, 
                    OBA_UDFDATE05, 
                    OBA_UDFNUM01, 
                    OBA_UDFNUM02, 
                    OBA_UDFNUM03, 
                    OBA_UDFNUM04, 
                    OBA_UDFNUM05, 
                    OBA_UOM, 
                    OBA_UPDATECOUNT, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.OBA_ASPECT, 
                    src.OBA_CONFRATING, 
                    src.OBA_FACTOR, 
                    src.OBA_LASTSAVED, 
                    src.OBA_MAX, 
                    src.OBA_MAXEXTR, 
                    src.OBA_MAXFORMULA, 
                    src.OBA_MAXPPM, 
                    src.OBA_MAXSTWO, 
                    src.OBA_MAXTOL, 
                    src.OBA_METHOD, 
                    src.OBA_MIN, 
                    src.OBA_MINEXTR, 
                    src.OBA_MINFORMULA, 
                    src.OBA_MINPPM, 
                    src.OBA_MINSTWO, 
                    src.OBA_MINTOL, 
                    src.OBA_NOMINAL, 
                    src.OBA_OBJECT, 
                    src.OBA_OBJECT_ORG, 
                    src.OBA_OBRTYPE, 
                    src.OBA_OBTYPE, 
                    src.OBA_REPLACEFREQ, 
                    src.OBA_RISK, 
                    src.OBA_UDFCHAR01, 
                    src.OBA_UDFCHAR02, 
                    src.OBA_UDFCHAR03, 
                    src.OBA_UDFCHAR04, 
                    src.OBA_UDFCHAR05, 
                    src.OBA_UDFCHAR06, 
                    src.OBA_UDFCHAR07, 
                    src.OBA_UDFCHAR08, 
                    src.OBA_UDFCHAR09, 
                    src.OBA_UDFCHAR10, 
                    src.OBA_UDFCHAR11, 
                    src.OBA_UDFCHAR12, 
                    src.OBA_UDFCHAR13, 
                    src.OBA_UDFCHAR14, 
                    src.OBA_UDFCHAR15, 
                    src.OBA_UDFCHAR16, 
                    src.OBA_UDFCHAR17, 
                    src.OBA_UDFCHAR18, 
                    src.OBA_UDFCHAR19, 
                    src.OBA_UDFCHAR20, 
                    src.OBA_UDFCHAR21, 
                    src.OBA_UDFCHAR22, 
                    src.OBA_UDFCHAR23, 
                    src.OBA_UDFCHAR24, 
                    src.OBA_UDFCHAR25, 
                    src.OBA_UDFCHAR26, 
                    src.OBA_UDFCHAR27, 
                    src.OBA_UDFCHAR28, 
                    src.OBA_UDFCHAR29, 
                    src.OBA_UDFCHAR30, 
                    src.OBA_UDFCHKBOX01, 
                    src.OBA_UDFCHKBOX02, 
                    src.OBA_UDFCHKBOX03, 
                    src.OBA_UDFCHKBOX04, 
                    src.OBA_UDFCHKBOX05, 
                    src.OBA_UDFDATE01, 
                    src.OBA_UDFDATE02, 
                    src.OBA_UDFDATE03, 
                    src.OBA_UDFDATE04, 
                    src.OBA_UDFDATE05, 
                    src.OBA_UDFNUM01, 
                    src.OBA_UDFNUM02, 
                    src.OBA_UDFNUM03, 
                    src.OBA_UDFNUM04, 
                    src.OBA_UDFNUM05, 
                    src.OBA_UOM, 
                    src.OBA_UPDATECOUNT, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5OBJECTASPECTS_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.OBA_ASPECT, 
            strm.OBA_CONFRATING, 
            strm.OBA_FACTOR, 
            strm.OBA_LASTSAVED, 
            strm.OBA_MAX, 
            strm.OBA_MAXEXTR, 
            strm.OBA_MAXFORMULA, 
            strm.OBA_MAXPPM, 
            strm.OBA_MAXSTWO, 
            strm.OBA_MAXTOL, 
            strm.OBA_METHOD, 
            strm.OBA_MIN, 
            strm.OBA_MINEXTR, 
            strm.OBA_MINFORMULA, 
            strm.OBA_MINPPM, 
            strm.OBA_MINSTWO, 
            strm.OBA_MINTOL, 
            strm.OBA_NOMINAL, 
            strm.OBA_OBJECT, 
            strm.OBA_OBJECT_ORG, 
            strm.OBA_OBRTYPE, 
            strm.OBA_OBTYPE, 
            strm.OBA_REPLACEFREQ, 
            strm.OBA_RISK, 
            strm.OBA_UDFCHAR01, 
            strm.OBA_UDFCHAR02, 
            strm.OBA_UDFCHAR03, 
            strm.OBA_UDFCHAR04, 
            strm.OBA_UDFCHAR05, 
            strm.OBA_UDFCHAR06, 
            strm.OBA_UDFCHAR07, 
            strm.OBA_UDFCHAR08, 
            strm.OBA_UDFCHAR09, 
            strm.OBA_UDFCHAR10, 
            strm.OBA_UDFCHAR11, 
            strm.OBA_UDFCHAR12, 
            strm.OBA_UDFCHAR13, 
            strm.OBA_UDFCHAR14, 
            strm.OBA_UDFCHAR15, 
            strm.OBA_UDFCHAR16, 
            strm.OBA_UDFCHAR17, 
            strm.OBA_UDFCHAR18, 
            strm.OBA_UDFCHAR19, 
            strm.OBA_UDFCHAR20, 
            strm.OBA_UDFCHAR21, 
            strm.OBA_UDFCHAR22, 
            strm.OBA_UDFCHAR23, 
            strm.OBA_UDFCHAR24, 
            strm.OBA_UDFCHAR25, 
            strm.OBA_UDFCHAR26, 
            strm.OBA_UDFCHAR27, 
            strm.OBA_UDFCHAR28, 
            strm.OBA_UDFCHAR29, 
            strm.OBA_UDFCHAR30, 
            strm.OBA_UDFCHKBOX01, 
            strm.OBA_UDFCHKBOX02, 
            strm.OBA_UDFCHKBOX03, 
            strm.OBA_UDFCHKBOX04, 
            strm.OBA_UDFCHKBOX05, 
            strm.OBA_UDFDATE01, 
            strm.OBA_UDFDATE02, 
            strm.OBA_UDFDATE03, 
            strm.OBA_UDFDATE04, 
            strm.OBA_UDFDATE05, 
            strm.OBA_UDFNUM01, 
            strm.OBA_UDFNUM02, 
            strm.OBA_UDFNUM03, 
            strm.OBA_UDFNUM04, 
            strm.OBA_UDFNUM05, 
            strm.OBA_UOM, 
            strm.OBA_UPDATECOUNT, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.OBA_OBJECT,
            strm.OBA_OBJECT_ORG,
            strm.OBA_OBTYPE,
            strm.OBA_ASPECT ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5OBJECTASPECTS as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.OBA_OBJECT=src.OBA_OBJECT) OR (target.OBA_OBJECT IS NULL AND src.OBA_OBJECT IS NULL)) AND
            ((target.OBA_OBJECT_ORG=src.OBA_OBJECT_ORG) OR (target.OBA_OBJECT_ORG IS NULL AND src.OBA_OBJECT_ORG IS NULL)) AND
            ((target.OBA_OBTYPE=src.OBA_OBTYPE) OR (target.OBA_OBTYPE IS NULL AND src.OBA_OBTYPE IS NULL)) AND
            ((target.OBA_ASPECT=src.OBA_ASPECT) OR (target.OBA_ASPECT IS NULL AND src.OBA_ASPECT IS NULL)) 
                when matched then update set
                    target.OBA_ASPECT=src.OBA_ASPECT, 
                    target.OBA_CONFRATING=src.OBA_CONFRATING, 
                    target.OBA_FACTOR=src.OBA_FACTOR, 
                    target.OBA_LASTSAVED=src.OBA_LASTSAVED, 
                    target.OBA_MAX=src.OBA_MAX, 
                    target.OBA_MAXEXTR=src.OBA_MAXEXTR, 
                    target.OBA_MAXFORMULA=src.OBA_MAXFORMULA, 
                    target.OBA_MAXPPM=src.OBA_MAXPPM, 
                    target.OBA_MAXSTWO=src.OBA_MAXSTWO, 
                    target.OBA_MAXTOL=src.OBA_MAXTOL, 
                    target.OBA_METHOD=src.OBA_METHOD, 
                    target.OBA_MIN=src.OBA_MIN, 
                    target.OBA_MINEXTR=src.OBA_MINEXTR, 
                    target.OBA_MINFORMULA=src.OBA_MINFORMULA, 
                    target.OBA_MINPPM=src.OBA_MINPPM, 
                    target.OBA_MINSTWO=src.OBA_MINSTWO, 
                    target.OBA_MINTOL=src.OBA_MINTOL, 
                    target.OBA_NOMINAL=src.OBA_NOMINAL, 
                    target.OBA_OBJECT=src.OBA_OBJECT, 
                    target.OBA_OBJECT_ORG=src.OBA_OBJECT_ORG, 
                    target.OBA_OBRTYPE=src.OBA_OBRTYPE, 
                    target.OBA_OBTYPE=src.OBA_OBTYPE, 
                    target.OBA_REPLACEFREQ=src.OBA_REPLACEFREQ, 
                    target.OBA_RISK=src.OBA_RISK, 
                    target.OBA_UDFCHAR01=src.OBA_UDFCHAR01, 
                    target.OBA_UDFCHAR02=src.OBA_UDFCHAR02, 
                    target.OBA_UDFCHAR03=src.OBA_UDFCHAR03, 
                    target.OBA_UDFCHAR04=src.OBA_UDFCHAR04, 
                    target.OBA_UDFCHAR05=src.OBA_UDFCHAR05, 
                    target.OBA_UDFCHAR06=src.OBA_UDFCHAR06, 
                    target.OBA_UDFCHAR07=src.OBA_UDFCHAR07, 
                    target.OBA_UDFCHAR08=src.OBA_UDFCHAR08, 
                    target.OBA_UDFCHAR09=src.OBA_UDFCHAR09, 
                    target.OBA_UDFCHAR10=src.OBA_UDFCHAR10, 
                    target.OBA_UDFCHAR11=src.OBA_UDFCHAR11, 
                    target.OBA_UDFCHAR12=src.OBA_UDFCHAR12, 
                    target.OBA_UDFCHAR13=src.OBA_UDFCHAR13, 
                    target.OBA_UDFCHAR14=src.OBA_UDFCHAR14, 
                    target.OBA_UDFCHAR15=src.OBA_UDFCHAR15, 
                    target.OBA_UDFCHAR16=src.OBA_UDFCHAR16, 
                    target.OBA_UDFCHAR17=src.OBA_UDFCHAR17, 
                    target.OBA_UDFCHAR18=src.OBA_UDFCHAR18, 
                    target.OBA_UDFCHAR19=src.OBA_UDFCHAR19, 
                    target.OBA_UDFCHAR20=src.OBA_UDFCHAR20, 
                    target.OBA_UDFCHAR21=src.OBA_UDFCHAR21, 
                    target.OBA_UDFCHAR22=src.OBA_UDFCHAR22, 
                    target.OBA_UDFCHAR23=src.OBA_UDFCHAR23, 
                    target.OBA_UDFCHAR24=src.OBA_UDFCHAR24, 
                    target.OBA_UDFCHAR25=src.OBA_UDFCHAR25, 
                    target.OBA_UDFCHAR26=src.OBA_UDFCHAR26, 
                    target.OBA_UDFCHAR27=src.OBA_UDFCHAR27, 
                    target.OBA_UDFCHAR28=src.OBA_UDFCHAR28, 
                    target.OBA_UDFCHAR29=src.OBA_UDFCHAR29, 
                    target.OBA_UDFCHAR30=src.OBA_UDFCHAR30, 
                    target.OBA_UDFCHKBOX01=src.OBA_UDFCHKBOX01, 
                    target.OBA_UDFCHKBOX02=src.OBA_UDFCHKBOX02, 
                    target.OBA_UDFCHKBOX03=src.OBA_UDFCHKBOX03, 
                    target.OBA_UDFCHKBOX04=src.OBA_UDFCHKBOX04, 
                    target.OBA_UDFCHKBOX05=src.OBA_UDFCHKBOX05, 
                    target.OBA_UDFDATE01=src.OBA_UDFDATE01, 
                    target.OBA_UDFDATE02=src.OBA_UDFDATE02, 
                    target.OBA_UDFDATE03=src.OBA_UDFDATE03, 
                    target.OBA_UDFDATE04=src.OBA_UDFDATE04, 
                    target.OBA_UDFDATE05=src.OBA_UDFDATE05, 
                    target.OBA_UDFNUM01=src.OBA_UDFNUM01, 
                    target.OBA_UDFNUM02=src.OBA_UDFNUM02, 
                    target.OBA_UDFNUM03=src.OBA_UDFNUM03, 
                    target.OBA_UDFNUM04=src.OBA_UDFNUM04, 
                    target.OBA_UDFNUM05=src.OBA_UDFNUM05, 
                    target.OBA_UOM=src.OBA_UOM, 
                    target.OBA_UPDATECOUNT=src.OBA_UPDATECOUNT, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( OBA_ASPECT, OBA_CONFRATING, OBA_FACTOR, OBA_LASTSAVED, OBA_MAX, OBA_MAXEXTR, OBA_MAXFORMULA, OBA_MAXPPM, OBA_MAXSTWO, OBA_MAXTOL, OBA_METHOD, OBA_MIN, OBA_MINEXTR, OBA_MINFORMULA, OBA_MINPPM, OBA_MINSTWO, OBA_MINTOL, OBA_NOMINAL, OBA_OBJECT, OBA_OBJECT_ORG, OBA_OBRTYPE, OBA_OBTYPE, OBA_REPLACEFREQ, OBA_RISK, OBA_UDFCHAR01, OBA_UDFCHAR02, OBA_UDFCHAR03, OBA_UDFCHAR04, OBA_UDFCHAR05, OBA_UDFCHAR06, OBA_UDFCHAR07, OBA_UDFCHAR08, OBA_UDFCHAR09, OBA_UDFCHAR10, OBA_UDFCHAR11, OBA_UDFCHAR12, OBA_UDFCHAR13, OBA_UDFCHAR14, OBA_UDFCHAR15, OBA_UDFCHAR16, OBA_UDFCHAR17, OBA_UDFCHAR18, OBA_UDFCHAR19, OBA_UDFCHAR20, OBA_UDFCHAR21, OBA_UDFCHAR22, OBA_UDFCHAR23, OBA_UDFCHAR24, OBA_UDFCHAR25, OBA_UDFCHAR26, OBA_UDFCHAR27, OBA_UDFCHAR28, OBA_UDFCHAR29, OBA_UDFCHAR30, OBA_UDFCHKBOX01, OBA_UDFCHKBOX02, OBA_UDFCHKBOX03, OBA_UDFCHKBOX04, OBA_UDFCHKBOX05, OBA_UDFDATE01, OBA_UDFDATE02, OBA_UDFDATE03, OBA_UDFDATE04, OBA_UDFDATE05, OBA_UDFNUM01, OBA_UDFNUM02, OBA_UDFNUM03, OBA_UDFNUM04, OBA_UDFNUM05, OBA_UOM, OBA_UPDATECOUNT, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.OBA_ASPECT, 
                    src.OBA_CONFRATING, 
                    src.OBA_FACTOR, 
                    src.OBA_LASTSAVED, 
                    src.OBA_MAX, 
                    src.OBA_MAXEXTR, 
                    src.OBA_MAXFORMULA, 
                    src.OBA_MAXPPM, 
                    src.OBA_MAXSTWO, 
                    src.OBA_MAXTOL, 
                    src.OBA_METHOD, 
                    src.OBA_MIN, 
                    src.OBA_MINEXTR, 
                    src.OBA_MINFORMULA, 
                    src.OBA_MINPPM, 
                    src.OBA_MINSTWO, 
                    src.OBA_MINTOL, 
                    src.OBA_NOMINAL, 
                    src.OBA_OBJECT, 
                    src.OBA_OBJECT_ORG, 
                    src.OBA_OBRTYPE, 
                    src.OBA_OBTYPE, 
                    src.OBA_REPLACEFREQ, 
                    src.OBA_RISK, 
                    src.OBA_UDFCHAR01, 
                    src.OBA_UDFCHAR02, 
                    src.OBA_UDFCHAR03, 
                    src.OBA_UDFCHAR04, 
                    src.OBA_UDFCHAR05, 
                    src.OBA_UDFCHAR06, 
                    src.OBA_UDFCHAR07, 
                    src.OBA_UDFCHAR08, 
                    src.OBA_UDFCHAR09, 
                    src.OBA_UDFCHAR10, 
                    src.OBA_UDFCHAR11, 
                    src.OBA_UDFCHAR12, 
                    src.OBA_UDFCHAR13, 
                    src.OBA_UDFCHAR14, 
                    src.OBA_UDFCHAR15, 
                    src.OBA_UDFCHAR16, 
                    src.OBA_UDFCHAR17, 
                    src.OBA_UDFCHAR18, 
                    src.OBA_UDFCHAR19, 
                    src.OBA_UDFCHAR20, 
                    src.OBA_UDFCHAR21, 
                    src.OBA_UDFCHAR22, 
                    src.OBA_UDFCHAR23, 
                    src.OBA_UDFCHAR24, 
                    src.OBA_UDFCHAR25, 
                    src.OBA_UDFCHAR26, 
                    src.OBA_UDFCHAR27, 
                    src.OBA_UDFCHAR28, 
                    src.OBA_UDFCHAR29, 
                    src.OBA_UDFCHAR30, 
                    src.OBA_UDFCHKBOX01, 
                    src.OBA_UDFCHKBOX02, 
                    src.OBA_UDFCHKBOX03, 
                    src.OBA_UDFCHKBOX04, 
                    src.OBA_UDFCHKBOX05, 
                    src.OBA_UDFDATE01, 
                    src.OBA_UDFDATE02, 
                    src.OBA_UDFDATE03, 
                    src.OBA_UDFDATE04, 
                    src.OBA_UDFDATE05, 
                    src.OBA_UDFNUM01, 
                    src.OBA_UDFNUM02, 
                    src.OBA_UDFNUM03, 
                    src.OBA_UDFNUM04, 
                    src.OBA_UDFNUM05, 
                    src.OBA_UOM, 
                    src.OBA_UPDATECOUNT, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;