create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5COMPANIES()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5COMPANIES_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5COMPANIES as target using (SELECT * FROM (SELECT 
            strm.COM_ACCOUNTCODE, 
            strm.COM_BUYER, 
            strm.COM_CAPACITY, 
            strm.COM_CLASS, 
            strm.COM_CLASS_ORG, 
            strm.COM_CODE, 
            strm.COM_CONTACT, 
            strm.COM_COSTCENTER, 
            strm.COM_CREATED, 
            strm.COM_CURR, 
            strm.COM_CUSTOMER, 
            strm.COM_DESC, 
            strm.COM_EDINO, 
            strm.COM_EMAIL, 
            strm.COM_FAX, 
            strm.COM_FOBPOINT, 
            strm.COM_FREIGHTTERMS, 
            strm.COM_GROUPPURCHASINGORG1, 
            strm.COM_GROUPPURCHASINGORG2, 
            strm.COM_INTERFACE, 
            strm.COM_IPACCOUNT, 
            strm.COM_IPRESPONSE, 
            strm.COM_IPVENDOR, 
            strm.COM_LANG, 
            strm.COM_LASTSAVED, 
            strm.COM_LASTSTATUSUPDATE, 
            strm.COM_LEADTIME, 
            strm.COM_MAXORD, 
            strm.COM_MINORD, 
            strm.COM_MINORITYGROUP, 
            strm.COM_NOTUSED, 
            strm.COM_ORG, 
            strm.COM_OURCONT, 
            strm.COM_PARENT, 
            strm.COM_PARENT_ORG, 
            strm.COM_PAYBYMETHOD, 
            strm.COM_PAYMENTTERMS, 
            strm.COM_PEOPLE, 
            strm.COM_PHONE, 
            strm.COM_PURCHASESITE, 
            strm.COM_SHIPVIA, 
            strm.COM_SOURCECODE, 
            strm.COM_SOURCESYSTEM, 
            strm.COM_STATUS, 
            strm.COM_TAX, 
            strm.COM_TYPE1099, 
            strm.COM_UDFCHAR01, 
            strm.COM_UDFCHAR02, 
            strm.COM_UDFCHAR03, 
            strm.COM_UDFCHAR04, 
            strm.COM_UDFCHAR05, 
            strm.COM_UDFCHAR06, 
            strm.COM_UDFCHAR07, 
            strm.COM_UDFCHAR08, 
            strm.COM_UDFCHAR09, 
            strm.COM_UDFCHAR10, 
            strm.COM_UDFCHAR11, 
            strm.COM_UDFCHAR12, 
            strm.COM_UDFCHAR13, 
            strm.COM_UDFCHAR14, 
            strm.COM_UDFCHAR15, 
            strm.COM_UDFCHAR16, 
            strm.COM_UDFCHAR17, 
            strm.COM_UDFCHAR18, 
            strm.COM_UDFCHAR19, 
            strm.COM_UDFCHAR20, 
            strm.COM_UDFCHAR21, 
            strm.COM_UDFCHAR22, 
            strm.COM_UDFCHAR23, 
            strm.COM_UDFCHAR24, 
            strm.COM_UDFCHAR25, 
            strm.COM_UDFCHAR26, 
            strm.COM_UDFCHAR27, 
            strm.COM_UDFCHAR28, 
            strm.COM_UDFCHAR29, 
            strm.COM_UDFCHAR30, 
            strm.COM_UDFCHKBOX01, 
            strm.COM_UDFCHKBOX02, 
            strm.COM_UDFCHKBOX03, 
            strm.COM_UDFCHKBOX04, 
            strm.COM_UDFCHKBOX05, 
            strm.COM_UDFDATE01, 
            strm.COM_UDFDATE02, 
            strm.COM_UDFDATE03, 
            strm.COM_UDFDATE04, 
            strm.COM_UDFDATE05, 
            strm.COM_UDFNUM01, 
            strm.COM_UDFNUM02, 
            strm.COM_UDFNUM03, 
            strm.COM_UDFNUM04, 
            strm.COM_UDFNUM05, 
            strm.COM_UPDATECOUNT, 
            strm.COM_UPDATED, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.COM_CODE,
            strm.COM_ORG ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5COMPANIES as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.COM_CODE=src.COM_CODE) OR (target.COM_CODE IS NULL AND src.COM_CODE IS NULL)) AND
            ((target.COM_ORG=src.COM_ORG) OR (target.COM_ORG IS NULL AND src.COM_ORG IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.COM_ACCOUNTCODE=src.COM_ACCOUNTCODE, 
                    target.COM_BUYER=src.COM_BUYER, 
                    target.COM_CAPACITY=src.COM_CAPACITY, 
                    target.COM_CLASS=src.COM_CLASS, 
                    target.COM_CLASS_ORG=src.COM_CLASS_ORG, 
                    target.COM_CODE=src.COM_CODE, 
                    target.COM_CONTACT=src.COM_CONTACT, 
                    target.COM_COSTCENTER=src.COM_COSTCENTER, 
                    target.COM_CREATED=src.COM_CREATED, 
                    target.COM_CURR=src.COM_CURR, 
                    target.COM_CUSTOMER=src.COM_CUSTOMER, 
                    target.COM_DESC=src.COM_DESC, 
                    target.COM_EDINO=src.COM_EDINO, 
                    target.COM_EMAIL=src.COM_EMAIL, 
                    target.COM_FAX=src.COM_FAX, 
                    target.COM_FOBPOINT=src.COM_FOBPOINT, 
                    target.COM_FREIGHTTERMS=src.COM_FREIGHTTERMS, 
                    target.COM_GROUPPURCHASINGORG1=src.COM_GROUPPURCHASINGORG1, 
                    target.COM_GROUPPURCHASINGORG2=src.COM_GROUPPURCHASINGORG2, 
                    target.COM_INTERFACE=src.COM_INTERFACE, 
                    target.COM_IPACCOUNT=src.COM_IPACCOUNT, 
                    target.COM_IPRESPONSE=src.COM_IPRESPONSE, 
                    target.COM_IPVENDOR=src.COM_IPVENDOR, 
                    target.COM_LANG=src.COM_LANG, 
                    target.COM_LASTSAVED=src.COM_LASTSAVED, 
                    target.COM_LASTSTATUSUPDATE=src.COM_LASTSTATUSUPDATE, 
                    target.COM_LEADTIME=src.COM_LEADTIME, 
                    target.COM_MAXORD=src.COM_MAXORD, 
                    target.COM_MINORD=src.COM_MINORD, 
                    target.COM_MINORITYGROUP=src.COM_MINORITYGROUP, 
                    target.COM_NOTUSED=src.COM_NOTUSED, 
                    target.COM_ORG=src.COM_ORG, 
                    target.COM_OURCONT=src.COM_OURCONT, 
                    target.COM_PARENT=src.COM_PARENT, 
                    target.COM_PARENT_ORG=src.COM_PARENT_ORG, 
                    target.COM_PAYBYMETHOD=src.COM_PAYBYMETHOD, 
                    target.COM_PAYMENTTERMS=src.COM_PAYMENTTERMS, 
                    target.COM_PEOPLE=src.COM_PEOPLE, 
                    target.COM_PHONE=src.COM_PHONE, 
                    target.COM_PURCHASESITE=src.COM_PURCHASESITE, 
                    target.COM_SHIPVIA=src.COM_SHIPVIA, 
                    target.COM_SOURCECODE=src.COM_SOURCECODE, 
                    target.COM_SOURCESYSTEM=src.COM_SOURCESYSTEM, 
                    target.COM_STATUS=src.COM_STATUS, 
                    target.COM_TAX=src.COM_TAX, 
                    target.COM_TYPE1099=src.COM_TYPE1099, 
                    target.COM_UDFCHAR01=src.COM_UDFCHAR01, 
                    target.COM_UDFCHAR02=src.COM_UDFCHAR02, 
                    target.COM_UDFCHAR03=src.COM_UDFCHAR03, 
                    target.COM_UDFCHAR04=src.COM_UDFCHAR04, 
                    target.COM_UDFCHAR05=src.COM_UDFCHAR05, 
                    target.COM_UDFCHAR06=src.COM_UDFCHAR06, 
                    target.COM_UDFCHAR07=src.COM_UDFCHAR07, 
                    target.COM_UDFCHAR08=src.COM_UDFCHAR08, 
                    target.COM_UDFCHAR09=src.COM_UDFCHAR09, 
                    target.COM_UDFCHAR10=src.COM_UDFCHAR10, 
                    target.COM_UDFCHAR11=src.COM_UDFCHAR11, 
                    target.COM_UDFCHAR12=src.COM_UDFCHAR12, 
                    target.COM_UDFCHAR13=src.COM_UDFCHAR13, 
                    target.COM_UDFCHAR14=src.COM_UDFCHAR14, 
                    target.COM_UDFCHAR15=src.COM_UDFCHAR15, 
                    target.COM_UDFCHAR16=src.COM_UDFCHAR16, 
                    target.COM_UDFCHAR17=src.COM_UDFCHAR17, 
                    target.COM_UDFCHAR18=src.COM_UDFCHAR18, 
                    target.COM_UDFCHAR19=src.COM_UDFCHAR19, 
                    target.COM_UDFCHAR20=src.COM_UDFCHAR20, 
                    target.COM_UDFCHAR21=src.COM_UDFCHAR21, 
                    target.COM_UDFCHAR22=src.COM_UDFCHAR22, 
                    target.COM_UDFCHAR23=src.COM_UDFCHAR23, 
                    target.COM_UDFCHAR24=src.COM_UDFCHAR24, 
                    target.COM_UDFCHAR25=src.COM_UDFCHAR25, 
                    target.COM_UDFCHAR26=src.COM_UDFCHAR26, 
                    target.COM_UDFCHAR27=src.COM_UDFCHAR27, 
                    target.COM_UDFCHAR28=src.COM_UDFCHAR28, 
                    target.COM_UDFCHAR29=src.COM_UDFCHAR29, 
                    target.COM_UDFCHAR30=src.COM_UDFCHAR30, 
                    target.COM_UDFCHKBOX01=src.COM_UDFCHKBOX01, 
                    target.COM_UDFCHKBOX02=src.COM_UDFCHKBOX02, 
                    target.COM_UDFCHKBOX03=src.COM_UDFCHKBOX03, 
                    target.COM_UDFCHKBOX04=src.COM_UDFCHKBOX04, 
                    target.COM_UDFCHKBOX05=src.COM_UDFCHKBOX05, 
                    target.COM_UDFDATE01=src.COM_UDFDATE01, 
                    target.COM_UDFDATE02=src.COM_UDFDATE02, 
                    target.COM_UDFDATE03=src.COM_UDFDATE03, 
                    target.COM_UDFDATE04=src.COM_UDFDATE04, 
                    target.COM_UDFDATE05=src.COM_UDFDATE05, 
                    target.COM_UDFNUM01=src.COM_UDFNUM01, 
                    target.COM_UDFNUM02=src.COM_UDFNUM02, 
                    target.COM_UDFNUM03=src.COM_UDFNUM03, 
                    target.COM_UDFNUM04=src.COM_UDFNUM04, 
                    target.COM_UDFNUM05=src.COM_UDFNUM05, 
                    target.COM_UPDATECOUNT=src.COM_UPDATECOUNT, 
                    target.COM_UPDATED=src.COM_UPDATED, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    COM_ACCOUNTCODE, 
                    COM_BUYER, 
                    COM_CAPACITY, 
                    COM_CLASS, 
                    COM_CLASS_ORG, 
                    COM_CODE, 
                    COM_CONTACT, 
                    COM_COSTCENTER, 
                    COM_CREATED, 
                    COM_CURR, 
                    COM_CUSTOMER, 
                    COM_DESC, 
                    COM_EDINO, 
                    COM_EMAIL, 
                    COM_FAX, 
                    COM_FOBPOINT, 
                    COM_FREIGHTTERMS, 
                    COM_GROUPPURCHASINGORG1, 
                    COM_GROUPPURCHASINGORG2, 
                    COM_INTERFACE, 
                    COM_IPACCOUNT, 
                    COM_IPRESPONSE, 
                    COM_IPVENDOR, 
                    COM_LANG, 
                    COM_LASTSAVED, 
                    COM_LASTSTATUSUPDATE, 
                    COM_LEADTIME, 
                    COM_MAXORD, 
                    COM_MINORD, 
                    COM_MINORITYGROUP, 
                    COM_NOTUSED, 
                    COM_ORG, 
                    COM_OURCONT, 
                    COM_PARENT, 
                    COM_PARENT_ORG, 
                    COM_PAYBYMETHOD, 
                    COM_PAYMENTTERMS, 
                    COM_PEOPLE, 
                    COM_PHONE, 
                    COM_PURCHASESITE, 
                    COM_SHIPVIA, 
                    COM_SOURCECODE, 
                    COM_SOURCESYSTEM, 
                    COM_STATUS, 
                    COM_TAX, 
                    COM_TYPE1099, 
                    COM_UDFCHAR01, 
                    COM_UDFCHAR02, 
                    COM_UDFCHAR03, 
                    COM_UDFCHAR04, 
                    COM_UDFCHAR05, 
                    COM_UDFCHAR06, 
                    COM_UDFCHAR07, 
                    COM_UDFCHAR08, 
                    COM_UDFCHAR09, 
                    COM_UDFCHAR10, 
                    COM_UDFCHAR11, 
                    COM_UDFCHAR12, 
                    COM_UDFCHAR13, 
                    COM_UDFCHAR14, 
                    COM_UDFCHAR15, 
                    COM_UDFCHAR16, 
                    COM_UDFCHAR17, 
                    COM_UDFCHAR18, 
                    COM_UDFCHAR19, 
                    COM_UDFCHAR20, 
                    COM_UDFCHAR21, 
                    COM_UDFCHAR22, 
                    COM_UDFCHAR23, 
                    COM_UDFCHAR24, 
                    COM_UDFCHAR25, 
                    COM_UDFCHAR26, 
                    COM_UDFCHAR27, 
                    COM_UDFCHAR28, 
                    COM_UDFCHAR29, 
                    COM_UDFCHAR30, 
                    COM_UDFCHKBOX01, 
                    COM_UDFCHKBOX02, 
                    COM_UDFCHKBOX03, 
                    COM_UDFCHKBOX04, 
                    COM_UDFCHKBOX05, 
                    COM_UDFDATE01, 
                    COM_UDFDATE02, 
                    COM_UDFDATE03, 
                    COM_UDFDATE04, 
                    COM_UDFDATE05, 
                    COM_UDFNUM01, 
                    COM_UDFNUM02, 
                    COM_UDFNUM03, 
                    COM_UDFNUM04, 
                    COM_UDFNUM05, 
                    COM_UPDATECOUNT, 
                    COM_UPDATED, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.COM_ACCOUNTCODE, 
                    src.COM_BUYER, 
                    src.COM_CAPACITY, 
                    src.COM_CLASS, 
                    src.COM_CLASS_ORG, 
                    src.COM_CODE, 
                    src.COM_CONTACT, 
                    src.COM_COSTCENTER, 
                    src.COM_CREATED, 
                    src.COM_CURR, 
                    src.COM_CUSTOMER, 
                    src.COM_DESC, 
                    src.COM_EDINO, 
                    src.COM_EMAIL, 
                    src.COM_FAX, 
                    src.COM_FOBPOINT, 
                    src.COM_FREIGHTTERMS, 
                    src.COM_GROUPPURCHASINGORG1, 
                    src.COM_GROUPPURCHASINGORG2, 
                    src.COM_INTERFACE, 
                    src.COM_IPACCOUNT, 
                    src.COM_IPRESPONSE, 
                    src.COM_IPVENDOR, 
                    src.COM_LANG, 
                    src.COM_LASTSAVED, 
                    src.COM_LASTSTATUSUPDATE, 
                    src.COM_LEADTIME, 
                    src.COM_MAXORD, 
                    src.COM_MINORD, 
                    src.COM_MINORITYGROUP, 
                    src.COM_NOTUSED, 
                    src.COM_ORG, 
                    src.COM_OURCONT, 
                    src.COM_PARENT, 
                    src.COM_PARENT_ORG, 
                    src.COM_PAYBYMETHOD, 
                    src.COM_PAYMENTTERMS, 
                    src.COM_PEOPLE, 
                    src.COM_PHONE, 
                    src.COM_PURCHASESITE, 
                    src.COM_SHIPVIA, 
                    src.COM_SOURCECODE, 
                    src.COM_SOURCESYSTEM, 
                    src.COM_STATUS, 
                    src.COM_TAX, 
                    src.COM_TYPE1099, 
                    src.COM_UDFCHAR01, 
                    src.COM_UDFCHAR02, 
                    src.COM_UDFCHAR03, 
                    src.COM_UDFCHAR04, 
                    src.COM_UDFCHAR05, 
                    src.COM_UDFCHAR06, 
                    src.COM_UDFCHAR07, 
                    src.COM_UDFCHAR08, 
                    src.COM_UDFCHAR09, 
                    src.COM_UDFCHAR10, 
                    src.COM_UDFCHAR11, 
                    src.COM_UDFCHAR12, 
                    src.COM_UDFCHAR13, 
                    src.COM_UDFCHAR14, 
                    src.COM_UDFCHAR15, 
                    src.COM_UDFCHAR16, 
                    src.COM_UDFCHAR17, 
                    src.COM_UDFCHAR18, 
                    src.COM_UDFCHAR19, 
                    src.COM_UDFCHAR20, 
                    src.COM_UDFCHAR21, 
                    src.COM_UDFCHAR22, 
                    src.COM_UDFCHAR23, 
                    src.COM_UDFCHAR24, 
                    src.COM_UDFCHAR25, 
                    src.COM_UDFCHAR26, 
                    src.COM_UDFCHAR27, 
                    src.COM_UDFCHAR28, 
                    src.COM_UDFCHAR29, 
                    src.COM_UDFCHAR30, 
                    src.COM_UDFCHKBOX01, 
                    src.COM_UDFCHKBOX02, 
                    src.COM_UDFCHKBOX03, 
                    src.COM_UDFCHKBOX04, 
                    src.COM_UDFCHKBOX05, 
                    src.COM_UDFDATE01, 
                    src.COM_UDFDATE02, 
                    src.COM_UDFDATE03, 
                    src.COM_UDFDATE04, 
                    src.COM_UDFDATE05, 
                    src.COM_UDFNUM01, 
                    src.COM_UDFNUM02, 
                    src.COM_UDFNUM03, 
                    src.COM_UDFNUM04, 
                    src.COM_UDFNUM05, 
                    src.COM_UPDATECOUNT, 
                    src.COM_UPDATED, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5COMPANIES_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.COM_ACCOUNTCODE, 
            strm.COM_BUYER, 
            strm.COM_CAPACITY, 
            strm.COM_CLASS, 
            strm.COM_CLASS_ORG, 
            strm.COM_CODE, 
            strm.COM_CONTACT, 
            strm.COM_COSTCENTER, 
            strm.COM_CREATED, 
            strm.COM_CURR, 
            strm.COM_CUSTOMER, 
            strm.COM_DESC, 
            strm.COM_EDINO, 
            strm.COM_EMAIL, 
            strm.COM_FAX, 
            strm.COM_FOBPOINT, 
            strm.COM_FREIGHTTERMS, 
            strm.COM_GROUPPURCHASINGORG1, 
            strm.COM_GROUPPURCHASINGORG2, 
            strm.COM_INTERFACE, 
            strm.COM_IPACCOUNT, 
            strm.COM_IPRESPONSE, 
            strm.COM_IPVENDOR, 
            strm.COM_LANG, 
            strm.COM_LASTSAVED, 
            strm.COM_LASTSTATUSUPDATE, 
            strm.COM_LEADTIME, 
            strm.COM_MAXORD, 
            strm.COM_MINORD, 
            strm.COM_MINORITYGROUP, 
            strm.COM_NOTUSED, 
            strm.COM_ORG, 
            strm.COM_OURCONT, 
            strm.COM_PARENT, 
            strm.COM_PARENT_ORG, 
            strm.COM_PAYBYMETHOD, 
            strm.COM_PAYMENTTERMS, 
            strm.COM_PEOPLE, 
            strm.COM_PHONE, 
            strm.COM_PURCHASESITE, 
            strm.COM_SHIPVIA, 
            strm.COM_SOURCECODE, 
            strm.COM_SOURCESYSTEM, 
            strm.COM_STATUS, 
            strm.COM_TAX, 
            strm.COM_TYPE1099, 
            strm.COM_UDFCHAR01, 
            strm.COM_UDFCHAR02, 
            strm.COM_UDFCHAR03, 
            strm.COM_UDFCHAR04, 
            strm.COM_UDFCHAR05, 
            strm.COM_UDFCHAR06, 
            strm.COM_UDFCHAR07, 
            strm.COM_UDFCHAR08, 
            strm.COM_UDFCHAR09, 
            strm.COM_UDFCHAR10, 
            strm.COM_UDFCHAR11, 
            strm.COM_UDFCHAR12, 
            strm.COM_UDFCHAR13, 
            strm.COM_UDFCHAR14, 
            strm.COM_UDFCHAR15, 
            strm.COM_UDFCHAR16, 
            strm.COM_UDFCHAR17, 
            strm.COM_UDFCHAR18, 
            strm.COM_UDFCHAR19, 
            strm.COM_UDFCHAR20, 
            strm.COM_UDFCHAR21, 
            strm.COM_UDFCHAR22, 
            strm.COM_UDFCHAR23, 
            strm.COM_UDFCHAR24, 
            strm.COM_UDFCHAR25, 
            strm.COM_UDFCHAR26, 
            strm.COM_UDFCHAR27, 
            strm.COM_UDFCHAR28, 
            strm.COM_UDFCHAR29, 
            strm.COM_UDFCHAR30, 
            strm.COM_UDFCHKBOX01, 
            strm.COM_UDFCHKBOX02, 
            strm.COM_UDFCHKBOX03, 
            strm.COM_UDFCHKBOX04, 
            strm.COM_UDFCHKBOX05, 
            strm.COM_UDFDATE01, 
            strm.COM_UDFDATE02, 
            strm.COM_UDFDATE03, 
            strm.COM_UDFDATE04, 
            strm.COM_UDFDATE05, 
            strm.COM_UDFNUM01, 
            strm.COM_UDFNUM02, 
            strm.COM_UDFNUM03, 
            strm.COM_UDFNUM04, 
            strm.COM_UDFNUM05, 
            strm.COM_UPDATECOUNT, 
            strm.COM_UPDATED, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.COM_CODE,
            strm.COM_ORG ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5COMPANIES as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.COM_CODE=src.COM_CODE) OR (target.COM_CODE IS NULL AND src.COM_CODE IS NULL)) AND
            ((target.COM_ORG=src.COM_ORG) OR (target.COM_ORG IS NULL AND src.COM_ORG IS NULL)) 
                when matched then update set
                    target.COM_ACCOUNTCODE=src.COM_ACCOUNTCODE, 
                    target.COM_BUYER=src.COM_BUYER, 
                    target.COM_CAPACITY=src.COM_CAPACITY, 
                    target.COM_CLASS=src.COM_CLASS, 
                    target.COM_CLASS_ORG=src.COM_CLASS_ORG, 
                    target.COM_CODE=src.COM_CODE, 
                    target.COM_CONTACT=src.COM_CONTACT, 
                    target.COM_COSTCENTER=src.COM_COSTCENTER, 
                    target.COM_CREATED=src.COM_CREATED, 
                    target.COM_CURR=src.COM_CURR, 
                    target.COM_CUSTOMER=src.COM_CUSTOMER, 
                    target.COM_DESC=src.COM_DESC, 
                    target.COM_EDINO=src.COM_EDINO, 
                    target.COM_EMAIL=src.COM_EMAIL, 
                    target.COM_FAX=src.COM_FAX, 
                    target.COM_FOBPOINT=src.COM_FOBPOINT, 
                    target.COM_FREIGHTTERMS=src.COM_FREIGHTTERMS, 
                    target.COM_GROUPPURCHASINGORG1=src.COM_GROUPPURCHASINGORG1, 
                    target.COM_GROUPPURCHASINGORG2=src.COM_GROUPPURCHASINGORG2, 
                    target.COM_INTERFACE=src.COM_INTERFACE, 
                    target.COM_IPACCOUNT=src.COM_IPACCOUNT, 
                    target.COM_IPRESPONSE=src.COM_IPRESPONSE, 
                    target.COM_IPVENDOR=src.COM_IPVENDOR, 
                    target.COM_LANG=src.COM_LANG, 
                    target.COM_LASTSAVED=src.COM_LASTSAVED, 
                    target.COM_LASTSTATUSUPDATE=src.COM_LASTSTATUSUPDATE, 
                    target.COM_LEADTIME=src.COM_LEADTIME, 
                    target.COM_MAXORD=src.COM_MAXORD, 
                    target.COM_MINORD=src.COM_MINORD, 
                    target.COM_MINORITYGROUP=src.COM_MINORITYGROUP, 
                    target.COM_NOTUSED=src.COM_NOTUSED, 
                    target.COM_ORG=src.COM_ORG, 
                    target.COM_OURCONT=src.COM_OURCONT, 
                    target.COM_PARENT=src.COM_PARENT, 
                    target.COM_PARENT_ORG=src.COM_PARENT_ORG, 
                    target.COM_PAYBYMETHOD=src.COM_PAYBYMETHOD, 
                    target.COM_PAYMENTTERMS=src.COM_PAYMENTTERMS, 
                    target.COM_PEOPLE=src.COM_PEOPLE, 
                    target.COM_PHONE=src.COM_PHONE, 
                    target.COM_PURCHASESITE=src.COM_PURCHASESITE, 
                    target.COM_SHIPVIA=src.COM_SHIPVIA, 
                    target.COM_SOURCECODE=src.COM_SOURCECODE, 
                    target.COM_SOURCESYSTEM=src.COM_SOURCESYSTEM, 
                    target.COM_STATUS=src.COM_STATUS, 
                    target.COM_TAX=src.COM_TAX, 
                    target.COM_TYPE1099=src.COM_TYPE1099, 
                    target.COM_UDFCHAR01=src.COM_UDFCHAR01, 
                    target.COM_UDFCHAR02=src.COM_UDFCHAR02, 
                    target.COM_UDFCHAR03=src.COM_UDFCHAR03, 
                    target.COM_UDFCHAR04=src.COM_UDFCHAR04, 
                    target.COM_UDFCHAR05=src.COM_UDFCHAR05, 
                    target.COM_UDFCHAR06=src.COM_UDFCHAR06, 
                    target.COM_UDFCHAR07=src.COM_UDFCHAR07, 
                    target.COM_UDFCHAR08=src.COM_UDFCHAR08, 
                    target.COM_UDFCHAR09=src.COM_UDFCHAR09, 
                    target.COM_UDFCHAR10=src.COM_UDFCHAR10, 
                    target.COM_UDFCHAR11=src.COM_UDFCHAR11, 
                    target.COM_UDFCHAR12=src.COM_UDFCHAR12, 
                    target.COM_UDFCHAR13=src.COM_UDFCHAR13, 
                    target.COM_UDFCHAR14=src.COM_UDFCHAR14, 
                    target.COM_UDFCHAR15=src.COM_UDFCHAR15, 
                    target.COM_UDFCHAR16=src.COM_UDFCHAR16, 
                    target.COM_UDFCHAR17=src.COM_UDFCHAR17, 
                    target.COM_UDFCHAR18=src.COM_UDFCHAR18, 
                    target.COM_UDFCHAR19=src.COM_UDFCHAR19, 
                    target.COM_UDFCHAR20=src.COM_UDFCHAR20, 
                    target.COM_UDFCHAR21=src.COM_UDFCHAR21, 
                    target.COM_UDFCHAR22=src.COM_UDFCHAR22, 
                    target.COM_UDFCHAR23=src.COM_UDFCHAR23, 
                    target.COM_UDFCHAR24=src.COM_UDFCHAR24, 
                    target.COM_UDFCHAR25=src.COM_UDFCHAR25, 
                    target.COM_UDFCHAR26=src.COM_UDFCHAR26, 
                    target.COM_UDFCHAR27=src.COM_UDFCHAR27, 
                    target.COM_UDFCHAR28=src.COM_UDFCHAR28, 
                    target.COM_UDFCHAR29=src.COM_UDFCHAR29, 
                    target.COM_UDFCHAR30=src.COM_UDFCHAR30, 
                    target.COM_UDFCHKBOX01=src.COM_UDFCHKBOX01, 
                    target.COM_UDFCHKBOX02=src.COM_UDFCHKBOX02, 
                    target.COM_UDFCHKBOX03=src.COM_UDFCHKBOX03, 
                    target.COM_UDFCHKBOX04=src.COM_UDFCHKBOX04, 
                    target.COM_UDFCHKBOX05=src.COM_UDFCHKBOX05, 
                    target.COM_UDFDATE01=src.COM_UDFDATE01, 
                    target.COM_UDFDATE02=src.COM_UDFDATE02, 
                    target.COM_UDFDATE03=src.COM_UDFDATE03, 
                    target.COM_UDFDATE04=src.COM_UDFDATE04, 
                    target.COM_UDFDATE05=src.COM_UDFDATE05, 
                    target.COM_UDFNUM01=src.COM_UDFNUM01, 
                    target.COM_UDFNUM02=src.COM_UDFNUM02, 
                    target.COM_UDFNUM03=src.COM_UDFNUM03, 
                    target.COM_UDFNUM04=src.COM_UDFNUM04, 
                    target.COM_UDFNUM05=src.COM_UDFNUM05, 
                    target.COM_UPDATECOUNT=src.COM_UPDATECOUNT, 
                    target.COM_UPDATED=src.COM_UPDATED, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( COM_ACCOUNTCODE, COM_BUYER, COM_CAPACITY, COM_CLASS, COM_CLASS_ORG, COM_CODE, COM_CONTACT, COM_COSTCENTER, COM_CREATED, COM_CURR, COM_CUSTOMER, COM_DESC, COM_EDINO, COM_EMAIL, COM_FAX, COM_FOBPOINT, COM_FREIGHTTERMS, COM_GROUPPURCHASINGORG1, COM_GROUPPURCHASINGORG2, COM_INTERFACE, COM_IPACCOUNT, COM_IPRESPONSE, COM_IPVENDOR, COM_LANG, COM_LASTSAVED, COM_LASTSTATUSUPDATE, COM_LEADTIME, COM_MAXORD, COM_MINORD, COM_MINORITYGROUP, COM_NOTUSED, COM_ORG, COM_OURCONT, COM_PARENT, COM_PARENT_ORG, COM_PAYBYMETHOD, COM_PAYMENTTERMS, COM_PEOPLE, COM_PHONE, COM_PURCHASESITE, COM_SHIPVIA, COM_SOURCECODE, COM_SOURCESYSTEM, COM_STATUS, COM_TAX, COM_TYPE1099, COM_UDFCHAR01, COM_UDFCHAR02, COM_UDFCHAR03, COM_UDFCHAR04, COM_UDFCHAR05, COM_UDFCHAR06, COM_UDFCHAR07, COM_UDFCHAR08, COM_UDFCHAR09, COM_UDFCHAR10, COM_UDFCHAR11, COM_UDFCHAR12, COM_UDFCHAR13, COM_UDFCHAR14, COM_UDFCHAR15, COM_UDFCHAR16, COM_UDFCHAR17, COM_UDFCHAR18, COM_UDFCHAR19, COM_UDFCHAR20, COM_UDFCHAR21, COM_UDFCHAR22, COM_UDFCHAR23, COM_UDFCHAR24, COM_UDFCHAR25, COM_UDFCHAR26, COM_UDFCHAR27, COM_UDFCHAR28, COM_UDFCHAR29, COM_UDFCHAR30, COM_UDFCHKBOX01, COM_UDFCHKBOX02, COM_UDFCHKBOX03, COM_UDFCHKBOX04, COM_UDFCHKBOX05, COM_UDFDATE01, COM_UDFDATE02, COM_UDFDATE03, COM_UDFDATE04, COM_UDFDATE05, COM_UDFNUM01, COM_UDFNUM02, COM_UDFNUM03, COM_UDFNUM04, COM_UDFNUM05, COM_UPDATECOUNT, COM_UPDATED, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.COM_ACCOUNTCODE, 
                    src.COM_BUYER, 
                    src.COM_CAPACITY, 
                    src.COM_CLASS, 
                    src.COM_CLASS_ORG, 
                    src.COM_CODE, 
                    src.COM_CONTACT, 
                    src.COM_COSTCENTER, 
                    src.COM_CREATED, 
                    src.COM_CURR, 
                    src.COM_CUSTOMER, 
                    src.COM_DESC, 
                    src.COM_EDINO, 
                    src.COM_EMAIL, 
                    src.COM_FAX, 
                    src.COM_FOBPOINT, 
                    src.COM_FREIGHTTERMS, 
                    src.COM_GROUPPURCHASINGORG1, 
                    src.COM_GROUPPURCHASINGORG2, 
                    src.COM_INTERFACE, 
                    src.COM_IPACCOUNT, 
                    src.COM_IPRESPONSE, 
                    src.COM_IPVENDOR, 
                    src.COM_LANG, 
                    src.COM_LASTSAVED, 
                    src.COM_LASTSTATUSUPDATE, 
                    src.COM_LEADTIME, 
                    src.COM_MAXORD, 
                    src.COM_MINORD, 
                    src.COM_MINORITYGROUP, 
                    src.COM_NOTUSED, 
                    src.COM_ORG, 
                    src.COM_OURCONT, 
                    src.COM_PARENT, 
                    src.COM_PARENT_ORG, 
                    src.COM_PAYBYMETHOD, 
                    src.COM_PAYMENTTERMS, 
                    src.COM_PEOPLE, 
                    src.COM_PHONE, 
                    src.COM_PURCHASESITE, 
                    src.COM_SHIPVIA, 
                    src.COM_SOURCECODE, 
                    src.COM_SOURCESYSTEM, 
                    src.COM_STATUS, 
                    src.COM_TAX, 
                    src.COM_TYPE1099, 
                    src.COM_UDFCHAR01, 
                    src.COM_UDFCHAR02, 
                    src.COM_UDFCHAR03, 
                    src.COM_UDFCHAR04, 
                    src.COM_UDFCHAR05, 
                    src.COM_UDFCHAR06, 
                    src.COM_UDFCHAR07, 
                    src.COM_UDFCHAR08, 
                    src.COM_UDFCHAR09, 
                    src.COM_UDFCHAR10, 
                    src.COM_UDFCHAR11, 
                    src.COM_UDFCHAR12, 
                    src.COM_UDFCHAR13, 
                    src.COM_UDFCHAR14, 
                    src.COM_UDFCHAR15, 
                    src.COM_UDFCHAR16, 
                    src.COM_UDFCHAR17, 
                    src.COM_UDFCHAR18, 
                    src.COM_UDFCHAR19, 
                    src.COM_UDFCHAR20, 
                    src.COM_UDFCHAR21, 
                    src.COM_UDFCHAR22, 
                    src.COM_UDFCHAR23, 
                    src.COM_UDFCHAR24, 
                    src.COM_UDFCHAR25, 
                    src.COM_UDFCHAR26, 
                    src.COM_UDFCHAR27, 
                    src.COM_UDFCHAR28, 
                    src.COM_UDFCHAR29, 
                    src.COM_UDFCHAR30, 
                    src.COM_UDFCHKBOX01, 
                    src.COM_UDFCHKBOX02, 
                    src.COM_UDFCHKBOX03, 
                    src.COM_UDFCHKBOX04, 
                    src.COM_UDFCHKBOX05, 
                    src.COM_UDFDATE01, 
                    src.COM_UDFDATE02, 
                    src.COM_UDFDATE03, 
                    src.COM_UDFDATE04, 
                    src.COM_UDFDATE05, 
                    src.COM_UDFNUM01, 
                    src.COM_UDFNUM02, 
                    src.COM_UDFNUM03, 
                    src.COM_UDFNUM04, 
                    src.COM_UDFNUM05, 
                    src.COM_UPDATECOUNT, 
                    src.COM_UPDATED, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;