create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5EQUIPMENTRANKINGS()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5EQUIPMENTRANKINGS_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5EQUIPMENTRANKINGS as target using (SELECT * FROM (SELECT 
            strm.EQR_CALCULATIONERROR, 
            strm.EQR_CORRSCOREDATE, 
            strm.EQR_CORRSCOREINDEX, 
            strm.EQR_CORRSCORERANKING, 
            strm.EQR_CORRSCORERANKINGREV, 
            strm.EQR_CORRSCORERANKING_ORG, 
            strm.EQR_CORRSCORESCORE, 
            strm.EQR_CORRSCORESTATUS, 
            strm.EQR_CREATED, 
            strm.EQR_CREATEDBY, 
            strm.EQR_DEFAULT, 
            strm.EQR_LASTSAVED, 
            strm.EQR_LOCKRANKINGVALUES, 
            strm.EQR_NEXTREFRESH, 
            strm.EQR_NOTE, 
            strm.EQR_OBJCODE, 
            strm.EQR_OBJORG, 
            strm.EQR_RANKINGCODE, 
            strm.EQR_RANKINGINDEX, 
            strm.EQR_RANKINGORG, 
            strm.EQR_RANKINGREVISION, 
            strm.EQR_RANKINGSCORE, 
            strm.EQR_REFRESHEVERY, 
            strm.EQR_REFRESHEVERYUNIT, 
            strm.EQR_REFRESHSEQUENCE, 
            strm.EQR_SURVEYLASTUPDATED, 
            strm.EQR_UDFCHAR01, 
            strm.EQR_UDFCHAR02, 
            strm.EQR_UDFCHAR03, 
            strm.EQR_UDFCHAR04, 
            strm.EQR_UDFCHAR05, 
            strm.EQR_UDFCHAR06, 
            strm.EQR_UDFCHAR07, 
            strm.EQR_UDFCHAR08, 
            strm.EQR_UDFCHAR09, 
            strm.EQR_UDFCHAR10, 
            strm.EQR_UDFCHAR11, 
            strm.EQR_UDFCHAR12, 
            strm.EQR_UDFCHAR13, 
            strm.EQR_UDFCHAR14, 
            strm.EQR_UDFCHAR15, 
            strm.EQR_UDFCHAR16, 
            strm.EQR_UDFCHAR17, 
            strm.EQR_UDFCHAR18, 
            strm.EQR_UDFCHAR19, 
            strm.EQR_UDFCHAR20, 
            strm.EQR_UDFCHAR21, 
            strm.EQR_UDFCHAR22, 
            strm.EQR_UDFCHAR23, 
            strm.EQR_UDFCHAR24, 
            strm.EQR_UDFCHAR25, 
            strm.EQR_UDFCHAR26, 
            strm.EQR_UDFCHAR27, 
            strm.EQR_UDFCHAR28, 
            strm.EQR_UDFCHAR29, 
            strm.EQR_UDFCHAR30, 
            strm.EQR_UDFCHKBOX01, 
            strm.EQR_UDFCHKBOX02, 
            strm.EQR_UDFCHKBOX03, 
            strm.EQR_UDFCHKBOX04, 
            strm.EQR_UDFCHKBOX05, 
            strm.EQR_UDFDATE01, 
            strm.EQR_UDFDATE02, 
            strm.EQR_UDFDATE03, 
            strm.EQR_UDFDATE04, 
            strm.EQR_UDFDATE05, 
            strm.EQR_UDFNUM01, 
            strm.EQR_UDFNUM02, 
            strm.EQR_UDFNUM03, 
            strm.EQR_UDFNUM04, 
            strm.EQR_UDFNUM05, 
            strm.EQR_UPDATECOUNT, 
            strm.EQR_UPDATED, 
            strm.EQR_UPDATEDBY, 
            strm.EQR_VALUESLASTCALCULATED, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.EQR_RANKINGCODE,
            strm.EQR_RANKINGORG,
            strm.EQR_RANKINGREVISION,
            strm.EQR_OBJCODE,
            strm.EQR_OBJORG ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5EQUIPMENTRANKINGS as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.EQR_RANKINGCODE=src.EQR_RANKINGCODE) OR (target.EQR_RANKINGCODE IS NULL AND src.EQR_RANKINGCODE IS NULL)) AND
            ((target.EQR_RANKINGORG=src.EQR_RANKINGORG) OR (target.EQR_RANKINGORG IS NULL AND src.EQR_RANKINGORG IS NULL)) AND
            ((target.EQR_RANKINGREVISION=src.EQR_RANKINGREVISION) OR (target.EQR_RANKINGREVISION IS NULL AND src.EQR_RANKINGREVISION IS NULL)) AND
            ((target.EQR_OBJCODE=src.EQR_OBJCODE) OR (target.EQR_OBJCODE IS NULL AND src.EQR_OBJCODE IS NULL)) AND
            ((target.EQR_OBJORG=src.EQR_OBJORG) OR (target.EQR_OBJORG IS NULL AND src.EQR_OBJORG IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.EQR_CALCULATIONERROR=src.EQR_CALCULATIONERROR, 
                    target.EQR_CORRSCOREDATE=src.EQR_CORRSCOREDATE, 
                    target.EQR_CORRSCOREINDEX=src.EQR_CORRSCOREINDEX, 
                    target.EQR_CORRSCORERANKING=src.EQR_CORRSCORERANKING, 
                    target.EQR_CORRSCORERANKINGREV=src.EQR_CORRSCORERANKINGREV, 
                    target.EQR_CORRSCORERANKING_ORG=src.EQR_CORRSCORERANKING_ORG, 
                    target.EQR_CORRSCORESCORE=src.EQR_CORRSCORESCORE, 
                    target.EQR_CORRSCORESTATUS=src.EQR_CORRSCORESTATUS, 
                    target.EQR_CREATED=src.EQR_CREATED, 
                    target.EQR_CREATEDBY=src.EQR_CREATEDBY, 
                    target.EQR_DEFAULT=src.EQR_DEFAULT, 
                    target.EQR_LASTSAVED=src.EQR_LASTSAVED, 
                    target.EQR_LOCKRANKINGVALUES=src.EQR_LOCKRANKINGVALUES, 
                    target.EQR_NEXTREFRESH=src.EQR_NEXTREFRESH, 
                    target.EQR_NOTE=src.EQR_NOTE, 
                    target.EQR_OBJCODE=src.EQR_OBJCODE, 
                    target.EQR_OBJORG=src.EQR_OBJORG, 
                    target.EQR_RANKINGCODE=src.EQR_RANKINGCODE, 
                    target.EQR_RANKINGINDEX=src.EQR_RANKINGINDEX, 
                    target.EQR_RANKINGORG=src.EQR_RANKINGORG, 
                    target.EQR_RANKINGREVISION=src.EQR_RANKINGREVISION, 
                    target.EQR_RANKINGSCORE=src.EQR_RANKINGSCORE, 
                    target.EQR_REFRESHEVERY=src.EQR_REFRESHEVERY, 
                    target.EQR_REFRESHEVERYUNIT=src.EQR_REFRESHEVERYUNIT, 
                    target.EQR_REFRESHSEQUENCE=src.EQR_REFRESHSEQUENCE, 
                    target.EQR_SURVEYLASTUPDATED=src.EQR_SURVEYLASTUPDATED, 
                    target.EQR_UDFCHAR01=src.EQR_UDFCHAR01, 
                    target.EQR_UDFCHAR02=src.EQR_UDFCHAR02, 
                    target.EQR_UDFCHAR03=src.EQR_UDFCHAR03, 
                    target.EQR_UDFCHAR04=src.EQR_UDFCHAR04, 
                    target.EQR_UDFCHAR05=src.EQR_UDFCHAR05, 
                    target.EQR_UDFCHAR06=src.EQR_UDFCHAR06, 
                    target.EQR_UDFCHAR07=src.EQR_UDFCHAR07, 
                    target.EQR_UDFCHAR08=src.EQR_UDFCHAR08, 
                    target.EQR_UDFCHAR09=src.EQR_UDFCHAR09, 
                    target.EQR_UDFCHAR10=src.EQR_UDFCHAR10, 
                    target.EQR_UDFCHAR11=src.EQR_UDFCHAR11, 
                    target.EQR_UDFCHAR12=src.EQR_UDFCHAR12, 
                    target.EQR_UDFCHAR13=src.EQR_UDFCHAR13, 
                    target.EQR_UDFCHAR14=src.EQR_UDFCHAR14, 
                    target.EQR_UDFCHAR15=src.EQR_UDFCHAR15, 
                    target.EQR_UDFCHAR16=src.EQR_UDFCHAR16, 
                    target.EQR_UDFCHAR17=src.EQR_UDFCHAR17, 
                    target.EQR_UDFCHAR18=src.EQR_UDFCHAR18, 
                    target.EQR_UDFCHAR19=src.EQR_UDFCHAR19, 
                    target.EQR_UDFCHAR20=src.EQR_UDFCHAR20, 
                    target.EQR_UDFCHAR21=src.EQR_UDFCHAR21, 
                    target.EQR_UDFCHAR22=src.EQR_UDFCHAR22, 
                    target.EQR_UDFCHAR23=src.EQR_UDFCHAR23, 
                    target.EQR_UDFCHAR24=src.EQR_UDFCHAR24, 
                    target.EQR_UDFCHAR25=src.EQR_UDFCHAR25, 
                    target.EQR_UDFCHAR26=src.EQR_UDFCHAR26, 
                    target.EQR_UDFCHAR27=src.EQR_UDFCHAR27, 
                    target.EQR_UDFCHAR28=src.EQR_UDFCHAR28, 
                    target.EQR_UDFCHAR29=src.EQR_UDFCHAR29, 
                    target.EQR_UDFCHAR30=src.EQR_UDFCHAR30, 
                    target.EQR_UDFCHKBOX01=src.EQR_UDFCHKBOX01, 
                    target.EQR_UDFCHKBOX02=src.EQR_UDFCHKBOX02, 
                    target.EQR_UDFCHKBOX03=src.EQR_UDFCHKBOX03, 
                    target.EQR_UDFCHKBOX04=src.EQR_UDFCHKBOX04, 
                    target.EQR_UDFCHKBOX05=src.EQR_UDFCHKBOX05, 
                    target.EQR_UDFDATE01=src.EQR_UDFDATE01, 
                    target.EQR_UDFDATE02=src.EQR_UDFDATE02, 
                    target.EQR_UDFDATE03=src.EQR_UDFDATE03, 
                    target.EQR_UDFDATE04=src.EQR_UDFDATE04, 
                    target.EQR_UDFDATE05=src.EQR_UDFDATE05, 
                    target.EQR_UDFNUM01=src.EQR_UDFNUM01, 
                    target.EQR_UDFNUM02=src.EQR_UDFNUM02, 
                    target.EQR_UDFNUM03=src.EQR_UDFNUM03, 
                    target.EQR_UDFNUM04=src.EQR_UDFNUM04, 
                    target.EQR_UDFNUM05=src.EQR_UDFNUM05, 
                    target.EQR_UPDATECOUNT=src.EQR_UPDATECOUNT, 
                    target.EQR_UPDATED=src.EQR_UPDATED, 
                    target.EQR_UPDATEDBY=src.EQR_UPDATEDBY, 
                    target.EQR_VALUESLASTCALCULATED=src.EQR_VALUESLASTCALCULATED, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    EQR_CALCULATIONERROR, 
                    EQR_CORRSCOREDATE, 
                    EQR_CORRSCOREINDEX, 
                    EQR_CORRSCORERANKING, 
                    EQR_CORRSCORERANKINGREV, 
                    EQR_CORRSCORERANKING_ORG, 
                    EQR_CORRSCORESCORE, 
                    EQR_CORRSCORESTATUS, 
                    EQR_CREATED, 
                    EQR_CREATEDBY, 
                    EQR_DEFAULT, 
                    EQR_LASTSAVED, 
                    EQR_LOCKRANKINGVALUES, 
                    EQR_NEXTREFRESH, 
                    EQR_NOTE, 
                    EQR_OBJCODE, 
                    EQR_OBJORG, 
                    EQR_RANKINGCODE, 
                    EQR_RANKINGINDEX, 
                    EQR_RANKINGORG, 
                    EQR_RANKINGREVISION, 
                    EQR_RANKINGSCORE, 
                    EQR_REFRESHEVERY, 
                    EQR_REFRESHEVERYUNIT, 
                    EQR_REFRESHSEQUENCE, 
                    EQR_SURVEYLASTUPDATED, 
                    EQR_UDFCHAR01, 
                    EQR_UDFCHAR02, 
                    EQR_UDFCHAR03, 
                    EQR_UDFCHAR04, 
                    EQR_UDFCHAR05, 
                    EQR_UDFCHAR06, 
                    EQR_UDFCHAR07, 
                    EQR_UDFCHAR08, 
                    EQR_UDFCHAR09, 
                    EQR_UDFCHAR10, 
                    EQR_UDFCHAR11, 
                    EQR_UDFCHAR12, 
                    EQR_UDFCHAR13, 
                    EQR_UDFCHAR14, 
                    EQR_UDFCHAR15, 
                    EQR_UDFCHAR16, 
                    EQR_UDFCHAR17, 
                    EQR_UDFCHAR18, 
                    EQR_UDFCHAR19, 
                    EQR_UDFCHAR20, 
                    EQR_UDFCHAR21, 
                    EQR_UDFCHAR22, 
                    EQR_UDFCHAR23, 
                    EQR_UDFCHAR24, 
                    EQR_UDFCHAR25, 
                    EQR_UDFCHAR26, 
                    EQR_UDFCHAR27, 
                    EQR_UDFCHAR28, 
                    EQR_UDFCHAR29, 
                    EQR_UDFCHAR30, 
                    EQR_UDFCHKBOX01, 
                    EQR_UDFCHKBOX02, 
                    EQR_UDFCHKBOX03, 
                    EQR_UDFCHKBOX04, 
                    EQR_UDFCHKBOX05, 
                    EQR_UDFDATE01, 
                    EQR_UDFDATE02, 
                    EQR_UDFDATE03, 
                    EQR_UDFDATE04, 
                    EQR_UDFDATE05, 
                    EQR_UDFNUM01, 
                    EQR_UDFNUM02, 
                    EQR_UDFNUM03, 
                    EQR_UDFNUM04, 
                    EQR_UDFNUM05, 
                    EQR_UPDATECOUNT, 
                    EQR_UPDATED, 
                    EQR_UPDATEDBY, 
                    EQR_VALUESLASTCALCULATED, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.EQR_CALCULATIONERROR, 
                    src.EQR_CORRSCOREDATE, 
                    src.EQR_CORRSCOREINDEX, 
                    src.EQR_CORRSCORERANKING, 
                    src.EQR_CORRSCORERANKINGREV, 
                    src.EQR_CORRSCORERANKING_ORG, 
                    src.EQR_CORRSCORESCORE, 
                    src.EQR_CORRSCORESTATUS, 
                    src.EQR_CREATED, 
                    src.EQR_CREATEDBY, 
                    src.EQR_DEFAULT, 
                    src.EQR_LASTSAVED, 
                    src.EQR_LOCKRANKINGVALUES, 
                    src.EQR_NEXTREFRESH, 
                    src.EQR_NOTE, 
                    src.EQR_OBJCODE, 
                    src.EQR_OBJORG, 
                    src.EQR_RANKINGCODE, 
                    src.EQR_RANKINGINDEX, 
                    src.EQR_RANKINGORG, 
                    src.EQR_RANKINGREVISION, 
                    src.EQR_RANKINGSCORE, 
                    src.EQR_REFRESHEVERY, 
                    src.EQR_REFRESHEVERYUNIT, 
                    src.EQR_REFRESHSEQUENCE, 
                    src.EQR_SURVEYLASTUPDATED, 
                    src.EQR_UDFCHAR01, 
                    src.EQR_UDFCHAR02, 
                    src.EQR_UDFCHAR03, 
                    src.EQR_UDFCHAR04, 
                    src.EQR_UDFCHAR05, 
                    src.EQR_UDFCHAR06, 
                    src.EQR_UDFCHAR07, 
                    src.EQR_UDFCHAR08, 
                    src.EQR_UDFCHAR09, 
                    src.EQR_UDFCHAR10, 
                    src.EQR_UDFCHAR11, 
                    src.EQR_UDFCHAR12, 
                    src.EQR_UDFCHAR13, 
                    src.EQR_UDFCHAR14, 
                    src.EQR_UDFCHAR15, 
                    src.EQR_UDFCHAR16, 
                    src.EQR_UDFCHAR17, 
                    src.EQR_UDFCHAR18, 
                    src.EQR_UDFCHAR19, 
                    src.EQR_UDFCHAR20, 
                    src.EQR_UDFCHAR21, 
                    src.EQR_UDFCHAR22, 
                    src.EQR_UDFCHAR23, 
                    src.EQR_UDFCHAR24, 
                    src.EQR_UDFCHAR25, 
                    src.EQR_UDFCHAR26, 
                    src.EQR_UDFCHAR27, 
                    src.EQR_UDFCHAR28, 
                    src.EQR_UDFCHAR29, 
                    src.EQR_UDFCHAR30, 
                    src.EQR_UDFCHKBOX01, 
                    src.EQR_UDFCHKBOX02, 
                    src.EQR_UDFCHKBOX03, 
                    src.EQR_UDFCHKBOX04, 
                    src.EQR_UDFCHKBOX05, 
                    src.EQR_UDFDATE01, 
                    src.EQR_UDFDATE02, 
                    src.EQR_UDFDATE03, 
                    src.EQR_UDFDATE04, 
                    src.EQR_UDFDATE05, 
                    src.EQR_UDFNUM01, 
                    src.EQR_UDFNUM02, 
                    src.EQR_UDFNUM03, 
                    src.EQR_UDFNUM04, 
                    src.EQR_UDFNUM05, 
                    src.EQR_UPDATECOUNT, 
                    src.EQR_UPDATED, 
                    src.EQR_UPDATEDBY, 
                    src.EQR_VALUESLASTCALCULATED, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5EQUIPMENTRANKINGS_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.EQR_CALCULATIONERROR, 
            strm.EQR_CORRSCOREDATE, 
            strm.EQR_CORRSCOREINDEX, 
            strm.EQR_CORRSCORERANKING, 
            strm.EQR_CORRSCORERANKINGREV, 
            strm.EQR_CORRSCORERANKING_ORG, 
            strm.EQR_CORRSCORESCORE, 
            strm.EQR_CORRSCORESTATUS, 
            strm.EQR_CREATED, 
            strm.EQR_CREATEDBY, 
            strm.EQR_DEFAULT, 
            strm.EQR_LASTSAVED, 
            strm.EQR_LOCKRANKINGVALUES, 
            strm.EQR_NEXTREFRESH, 
            strm.EQR_NOTE, 
            strm.EQR_OBJCODE, 
            strm.EQR_OBJORG, 
            strm.EQR_RANKINGCODE, 
            strm.EQR_RANKINGINDEX, 
            strm.EQR_RANKINGORG, 
            strm.EQR_RANKINGREVISION, 
            strm.EQR_RANKINGSCORE, 
            strm.EQR_REFRESHEVERY, 
            strm.EQR_REFRESHEVERYUNIT, 
            strm.EQR_REFRESHSEQUENCE, 
            strm.EQR_SURVEYLASTUPDATED, 
            strm.EQR_UDFCHAR01, 
            strm.EQR_UDFCHAR02, 
            strm.EQR_UDFCHAR03, 
            strm.EQR_UDFCHAR04, 
            strm.EQR_UDFCHAR05, 
            strm.EQR_UDFCHAR06, 
            strm.EQR_UDFCHAR07, 
            strm.EQR_UDFCHAR08, 
            strm.EQR_UDFCHAR09, 
            strm.EQR_UDFCHAR10, 
            strm.EQR_UDFCHAR11, 
            strm.EQR_UDFCHAR12, 
            strm.EQR_UDFCHAR13, 
            strm.EQR_UDFCHAR14, 
            strm.EQR_UDFCHAR15, 
            strm.EQR_UDFCHAR16, 
            strm.EQR_UDFCHAR17, 
            strm.EQR_UDFCHAR18, 
            strm.EQR_UDFCHAR19, 
            strm.EQR_UDFCHAR20, 
            strm.EQR_UDFCHAR21, 
            strm.EQR_UDFCHAR22, 
            strm.EQR_UDFCHAR23, 
            strm.EQR_UDFCHAR24, 
            strm.EQR_UDFCHAR25, 
            strm.EQR_UDFCHAR26, 
            strm.EQR_UDFCHAR27, 
            strm.EQR_UDFCHAR28, 
            strm.EQR_UDFCHAR29, 
            strm.EQR_UDFCHAR30, 
            strm.EQR_UDFCHKBOX01, 
            strm.EQR_UDFCHKBOX02, 
            strm.EQR_UDFCHKBOX03, 
            strm.EQR_UDFCHKBOX04, 
            strm.EQR_UDFCHKBOX05, 
            strm.EQR_UDFDATE01, 
            strm.EQR_UDFDATE02, 
            strm.EQR_UDFDATE03, 
            strm.EQR_UDFDATE04, 
            strm.EQR_UDFDATE05, 
            strm.EQR_UDFNUM01, 
            strm.EQR_UDFNUM02, 
            strm.EQR_UDFNUM03, 
            strm.EQR_UDFNUM04, 
            strm.EQR_UDFNUM05, 
            strm.EQR_UPDATECOUNT, 
            strm.EQR_UPDATED, 
            strm.EQR_UPDATEDBY, 
            strm.EQR_VALUESLASTCALCULATED, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.EQR_RANKINGCODE,
            strm.EQR_RANKINGORG,
            strm.EQR_RANKINGREVISION,
            strm.EQR_OBJCODE,
            strm.EQR_OBJORG ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5EQUIPMENTRANKINGS as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.EQR_RANKINGCODE=src.EQR_RANKINGCODE) OR (target.EQR_RANKINGCODE IS NULL AND src.EQR_RANKINGCODE IS NULL)) AND
            ((target.EQR_RANKINGORG=src.EQR_RANKINGORG) OR (target.EQR_RANKINGORG IS NULL AND src.EQR_RANKINGORG IS NULL)) AND
            ((target.EQR_RANKINGREVISION=src.EQR_RANKINGREVISION) OR (target.EQR_RANKINGREVISION IS NULL AND src.EQR_RANKINGREVISION IS NULL)) AND
            ((target.EQR_OBJCODE=src.EQR_OBJCODE) OR (target.EQR_OBJCODE IS NULL AND src.EQR_OBJCODE IS NULL)) AND
            ((target.EQR_OBJORG=src.EQR_OBJORG) OR (target.EQR_OBJORG IS NULL AND src.EQR_OBJORG IS NULL)) 
                when matched then update set
                    target.EQR_CALCULATIONERROR=src.EQR_CALCULATIONERROR, 
                    target.EQR_CORRSCOREDATE=src.EQR_CORRSCOREDATE, 
                    target.EQR_CORRSCOREINDEX=src.EQR_CORRSCOREINDEX, 
                    target.EQR_CORRSCORERANKING=src.EQR_CORRSCORERANKING, 
                    target.EQR_CORRSCORERANKINGREV=src.EQR_CORRSCORERANKINGREV, 
                    target.EQR_CORRSCORERANKING_ORG=src.EQR_CORRSCORERANKING_ORG, 
                    target.EQR_CORRSCORESCORE=src.EQR_CORRSCORESCORE, 
                    target.EQR_CORRSCORESTATUS=src.EQR_CORRSCORESTATUS, 
                    target.EQR_CREATED=src.EQR_CREATED, 
                    target.EQR_CREATEDBY=src.EQR_CREATEDBY, 
                    target.EQR_DEFAULT=src.EQR_DEFAULT, 
                    target.EQR_LASTSAVED=src.EQR_LASTSAVED, 
                    target.EQR_LOCKRANKINGVALUES=src.EQR_LOCKRANKINGVALUES, 
                    target.EQR_NEXTREFRESH=src.EQR_NEXTREFRESH, 
                    target.EQR_NOTE=src.EQR_NOTE, 
                    target.EQR_OBJCODE=src.EQR_OBJCODE, 
                    target.EQR_OBJORG=src.EQR_OBJORG, 
                    target.EQR_RANKINGCODE=src.EQR_RANKINGCODE, 
                    target.EQR_RANKINGINDEX=src.EQR_RANKINGINDEX, 
                    target.EQR_RANKINGORG=src.EQR_RANKINGORG, 
                    target.EQR_RANKINGREVISION=src.EQR_RANKINGREVISION, 
                    target.EQR_RANKINGSCORE=src.EQR_RANKINGSCORE, 
                    target.EQR_REFRESHEVERY=src.EQR_REFRESHEVERY, 
                    target.EQR_REFRESHEVERYUNIT=src.EQR_REFRESHEVERYUNIT, 
                    target.EQR_REFRESHSEQUENCE=src.EQR_REFRESHSEQUENCE, 
                    target.EQR_SURVEYLASTUPDATED=src.EQR_SURVEYLASTUPDATED, 
                    target.EQR_UDFCHAR01=src.EQR_UDFCHAR01, 
                    target.EQR_UDFCHAR02=src.EQR_UDFCHAR02, 
                    target.EQR_UDFCHAR03=src.EQR_UDFCHAR03, 
                    target.EQR_UDFCHAR04=src.EQR_UDFCHAR04, 
                    target.EQR_UDFCHAR05=src.EQR_UDFCHAR05, 
                    target.EQR_UDFCHAR06=src.EQR_UDFCHAR06, 
                    target.EQR_UDFCHAR07=src.EQR_UDFCHAR07, 
                    target.EQR_UDFCHAR08=src.EQR_UDFCHAR08, 
                    target.EQR_UDFCHAR09=src.EQR_UDFCHAR09, 
                    target.EQR_UDFCHAR10=src.EQR_UDFCHAR10, 
                    target.EQR_UDFCHAR11=src.EQR_UDFCHAR11, 
                    target.EQR_UDFCHAR12=src.EQR_UDFCHAR12, 
                    target.EQR_UDFCHAR13=src.EQR_UDFCHAR13, 
                    target.EQR_UDFCHAR14=src.EQR_UDFCHAR14, 
                    target.EQR_UDFCHAR15=src.EQR_UDFCHAR15, 
                    target.EQR_UDFCHAR16=src.EQR_UDFCHAR16, 
                    target.EQR_UDFCHAR17=src.EQR_UDFCHAR17, 
                    target.EQR_UDFCHAR18=src.EQR_UDFCHAR18, 
                    target.EQR_UDFCHAR19=src.EQR_UDFCHAR19, 
                    target.EQR_UDFCHAR20=src.EQR_UDFCHAR20, 
                    target.EQR_UDFCHAR21=src.EQR_UDFCHAR21, 
                    target.EQR_UDFCHAR22=src.EQR_UDFCHAR22, 
                    target.EQR_UDFCHAR23=src.EQR_UDFCHAR23, 
                    target.EQR_UDFCHAR24=src.EQR_UDFCHAR24, 
                    target.EQR_UDFCHAR25=src.EQR_UDFCHAR25, 
                    target.EQR_UDFCHAR26=src.EQR_UDFCHAR26, 
                    target.EQR_UDFCHAR27=src.EQR_UDFCHAR27, 
                    target.EQR_UDFCHAR28=src.EQR_UDFCHAR28, 
                    target.EQR_UDFCHAR29=src.EQR_UDFCHAR29, 
                    target.EQR_UDFCHAR30=src.EQR_UDFCHAR30, 
                    target.EQR_UDFCHKBOX01=src.EQR_UDFCHKBOX01, 
                    target.EQR_UDFCHKBOX02=src.EQR_UDFCHKBOX02, 
                    target.EQR_UDFCHKBOX03=src.EQR_UDFCHKBOX03, 
                    target.EQR_UDFCHKBOX04=src.EQR_UDFCHKBOX04, 
                    target.EQR_UDFCHKBOX05=src.EQR_UDFCHKBOX05, 
                    target.EQR_UDFDATE01=src.EQR_UDFDATE01, 
                    target.EQR_UDFDATE02=src.EQR_UDFDATE02, 
                    target.EQR_UDFDATE03=src.EQR_UDFDATE03, 
                    target.EQR_UDFDATE04=src.EQR_UDFDATE04, 
                    target.EQR_UDFDATE05=src.EQR_UDFDATE05, 
                    target.EQR_UDFNUM01=src.EQR_UDFNUM01, 
                    target.EQR_UDFNUM02=src.EQR_UDFNUM02, 
                    target.EQR_UDFNUM03=src.EQR_UDFNUM03, 
                    target.EQR_UDFNUM04=src.EQR_UDFNUM04, 
                    target.EQR_UDFNUM05=src.EQR_UDFNUM05, 
                    target.EQR_UPDATECOUNT=src.EQR_UPDATECOUNT, 
                    target.EQR_UPDATED=src.EQR_UPDATED, 
                    target.EQR_UPDATEDBY=src.EQR_UPDATEDBY, 
                    target.EQR_VALUESLASTCALCULATED=src.EQR_VALUESLASTCALCULATED, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( EQR_CALCULATIONERROR, EQR_CORRSCOREDATE, EQR_CORRSCOREINDEX, EQR_CORRSCORERANKING, EQR_CORRSCORERANKINGREV, EQR_CORRSCORERANKING_ORG, EQR_CORRSCORESCORE, EQR_CORRSCORESTATUS, EQR_CREATED, EQR_CREATEDBY, EQR_DEFAULT, EQR_LASTSAVED, EQR_LOCKRANKINGVALUES, EQR_NEXTREFRESH, EQR_NOTE, EQR_OBJCODE, EQR_OBJORG, EQR_RANKINGCODE, EQR_RANKINGINDEX, EQR_RANKINGORG, EQR_RANKINGREVISION, EQR_RANKINGSCORE, EQR_REFRESHEVERY, EQR_REFRESHEVERYUNIT, EQR_REFRESHSEQUENCE, EQR_SURVEYLASTUPDATED, EQR_UDFCHAR01, EQR_UDFCHAR02, EQR_UDFCHAR03, EQR_UDFCHAR04, EQR_UDFCHAR05, EQR_UDFCHAR06, EQR_UDFCHAR07, EQR_UDFCHAR08, EQR_UDFCHAR09, EQR_UDFCHAR10, EQR_UDFCHAR11, EQR_UDFCHAR12, EQR_UDFCHAR13, EQR_UDFCHAR14, EQR_UDFCHAR15, EQR_UDFCHAR16, EQR_UDFCHAR17, EQR_UDFCHAR18, EQR_UDFCHAR19, EQR_UDFCHAR20, EQR_UDFCHAR21, EQR_UDFCHAR22, EQR_UDFCHAR23, EQR_UDFCHAR24, EQR_UDFCHAR25, EQR_UDFCHAR26, EQR_UDFCHAR27, EQR_UDFCHAR28, EQR_UDFCHAR29, EQR_UDFCHAR30, EQR_UDFCHKBOX01, EQR_UDFCHKBOX02, EQR_UDFCHKBOX03, EQR_UDFCHKBOX04, EQR_UDFCHKBOX05, EQR_UDFDATE01, EQR_UDFDATE02, EQR_UDFDATE03, EQR_UDFDATE04, EQR_UDFDATE05, EQR_UDFNUM01, EQR_UDFNUM02, EQR_UDFNUM03, EQR_UDFNUM04, EQR_UDFNUM05, EQR_UPDATECOUNT, EQR_UPDATED, EQR_UPDATEDBY, EQR_VALUESLASTCALCULATED, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.EQR_CALCULATIONERROR, 
                    src.EQR_CORRSCOREDATE, 
                    src.EQR_CORRSCOREINDEX, 
                    src.EQR_CORRSCORERANKING, 
                    src.EQR_CORRSCORERANKINGREV, 
                    src.EQR_CORRSCORERANKING_ORG, 
                    src.EQR_CORRSCORESCORE, 
                    src.EQR_CORRSCORESTATUS, 
                    src.EQR_CREATED, 
                    src.EQR_CREATEDBY, 
                    src.EQR_DEFAULT, 
                    src.EQR_LASTSAVED, 
                    src.EQR_LOCKRANKINGVALUES, 
                    src.EQR_NEXTREFRESH, 
                    src.EQR_NOTE, 
                    src.EQR_OBJCODE, 
                    src.EQR_OBJORG, 
                    src.EQR_RANKINGCODE, 
                    src.EQR_RANKINGINDEX, 
                    src.EQR_RANKINGORG, 
                    src.EQR_RANKINGREVISION, 
                    src.EQR_RANKINGSCORE, 
                    src.EQR_REFRESHEVERY, 
                    src.EQR_REFRESHEVERYUNIT, 
                    src.EQR_REFRESHSEQUENCE, 
                    src.EQR_SURVEYLASTUPDATED, 
                    src.EQR_UDFCHAR01, 
                    src.EQR_UDFCHAR02, 
                    src.EQR_UDFCHAR03, 
                    src.EQR_UDFCHAR04, 
                    src.EQR_UDFCHAR05, 
                    src.EQR_UDFCHAR06, 
                    src.EQR_UDFCHAR07, 
                    src.EQR_UDFCHAR08, 
                    src.EQR_UDFCHAR09, 
                    src.EQR_UDFCHAR10, 
                    src.EQR_UDFCHAR11, 
                    src.EQR_UDFCHAR12, 
                    src.EQR_UDFCHAR13, 
                    src.EQR_UDFCHAR14, 
                    src.EQR_UDFCHAR15, 
                    src.EQR_UDFCHAR16, 
                    src.EQR_UDFCHAR17, 
                    src.EQR_UDFCHAR18, 
                    src.EQR_UDFCHAR19, 
                    src.EQR_UDFCHAR20, 
                    src.EQR_UDFCHAR21, 
                    src.EQR_UDFCHAR22, 
                    src.EQR_UDFCHAR23, 
                    src.EQR_UDFCHAR24, 
                    src.EQR_UDFCHAR25, 
                    src.EQR_UDFCHAR26, 
                    src.EQR_UDFCHAR27, 
                    src.EQR_UDFCHAR28, 
                    src.EQR_UDFCHAR29, 
                    src.EQR_UDFCHAR30, 
                    src.EQR_UDFCHKBOX01, 
                    src.EQR_UDFCHKBOX02, 
                    src.EQR_UDFCHKBOX03, 
                    src.EQR_UDFCHKBOX04, 
                    src.EQR_UDFCHKBOX05, 
                    src.EQR_UDFDATE01, 
                    src.EQR_UDFDATE02, 
                    src.EQR_UDFDATE03, 
                    src.EQR_UDFDATE04, 
                    src.EQR_UDFDATE05, 
                    src.EQR_UDFNUM01, 
                    src.EQR_UDFNUM02, 
                    src.EQR_UDFNUM03, 
                    src.EQR_UDFNUM04, 
                    src.EQR_UDFNUM05, 
                    src.EQR_UPDATECOUNT, 
                    src.EQR_UPDATED, 
                    src.EQR_UPDATEDBY, 
                    src.EQR_VALUESLASTCALCULATED, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;