create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5BOOKEDHOURS()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5BOOKEDHOURS_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5BOOKEDHOURS as target using (SELECT * FROM (SELECT 
            strm.BOO_ACD, 
            strm.BOO_ACT, 
            strm.BOO_BILLSUBLINE, 
            strm.BOO_CODE, 
            strm.BOO_CORRECTION, 
            strm.BOO_CORRECTIONDATE, 
            strm.BOO_COST, 
            strm.BOO_DATE, 
            strm.BOO_DESC, 
            strm.BOO_ENTERED, 
            strm.BOO_EVENT, 
            strm.BOO_EVTALIAS, 
            strm.BOO_FLEETCHECKED, 
            strm.BOO_FLEETMARKUP, 
            strm.BOO_GLTRANSFER, 
            strm.BOO_GLTRANSFERFLAG, 
            strm.BOO_HOURS, 
            strm.BOO_INVOICE, 
            strm.BOO_INVOICELINE, 
            strm.BOO_INVOICE_ORG, 
            strm.BOO_INVOICE_REVISION, 
            strm.BOO_JECATEGORY, 
            strm.BOO_JESOURCE, 
            strm.BOO_LASTSAVED, 
            strm.BOO_MISC, 
            strm.BOO_MRC, 
            strm.BOO_OCRTYPE, 
            strm.BOO_OCTYPE, 
            strm.BOO_OFF, 
            strm.BOO_ON, 
            strm.BOO_ORDER, 
            strm.BOO_ORDER_ORG, 
            strm.BOO_ORDLINE, 
            strm.BOO_ORIGHOURS, 
            strm.BOO_ORIGTAXAMOUNT, 
            strm.BOO_PERSON, 
            strm.BOO_RATE, 
            strm.BOO_ROUTEPARENT, 
            strm.BOO_ROUTEREC, 
            strm.BOO_ROUTERTYPE, 
            strm.BOO_SPLITHOURS, 
            strm.BOO_TAXAMOUNT, 
            strm.BOO_TRADE, 
            strm.BOO_TRANSCODE, 
            strm.BOO_TRANSGROUP, 
            strm.BOO_TRANSORGID, 
            strm.BOO_UDFCHAR01, 
            strm.BOO_UDFCHAR02, 
            strm.BOO_UDFCHAR03, 
            strm.BOO_UDFCHAR04, 
            strm.BOO_UDFCHAR05, 
            strm.BOO_UDFCHAR06, 
            strm.BOO_UDFCHAR07, 
            strm.BOO_UDFCHAR08, 
            strm.BOO_UDFCHAR09, 
            strm.BOO_UDFCHAR10, 
            strm.BOO_UDFCHAR11, 
            strm.BOO_UDFCHAR12, 
            strm.BOO_UDFCHAR13, 
            strm.BOO_UDFCHAR14, 
            strm.BOO_UDFCHAR15, 
            strm.BOO_UDFCHAR16, 
            strm.BOO_UDFCHAR17, 
            strm.BOO_UDFCHAR18, 
            strm.BOO_UDFCHAR19, 
            strm.BOO_UDFCHAR20, 
            strm.BOO_UDFCHAR21, 
            strm.BOO_UDFCHAR22, 
            strm.BOO_UDFCHAR23, 
            strm.BOO_UDFCHAR24, 
            strm.BOO_UDFCHAR25, 
            strm.BOO_UDFCHAR26, 
            strm.BOO_UDFCHAR27, 
            strm.BOO_UDFCHAR28, 
            strm.BOO_UDFCHAR29, 
            strm.BOO_UDFCHAR30, 
            strm.BOO_UDFCHKBOX01, 
            strm.BOO_UDFCHKBOX02, 
            strm.BOO_UDFCHKBOX03, 
            strm.BOO_UDFCHKBOX04, 
            strm.BOO_UDFCHKBOX05, 
            strm.BOO_UDFDATE01, 
            strm.BOO_UDFDATE02, 
            strm.BOO_UDFDATE03, 
            strm.BOO_UDFDATE04, 
            strm.BOO_UDFDATE05, 
            strm.BOO_UDFNUM01, 
            strm.BOO_UDFNUM02, 
            strm.BOO_UDFNUM03, 
            strm.BOO_UDFNUM04, 
            strm.BOO_UDFNUM05, 
            strm.BOO_UNMATCHEDINVOICE, 
            strm.BOO_UNMATCHEDINVOICELINE, 
            strm.BOO_UNMATCHEDINVOICE_ORG, 
            strm.BOO_UPDATECOUNT, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.BOO_CODE ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5BOOKEDHOURS as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.BOO_CODE=src.BOO_CODE) OR (target.BOO_CODE IS NULL AND src.BOO_CODE IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.BOO_ACD=src.BOO_ACD, 
                    target.BOO_ACT=src.BOO_ACT, 
                    target.BOO_BILLSUBLINE=src.BOO_BILLSUBLINE, 
                    target.BOO_CODE=src.BOO_CODE, 
                    target.BOO_CORRECTION=src.BOO_CORRECTION, 
                    target.BOO_CORRECTIONDATE=src.BOO_CORRECTIONDATE, 
                    target.BOO_COST=src.BOO_COST, 
                    target.BOO_DATE=src.BOO_DATE, 
                    target.BOO_DESC=src.BOO_DESC, 
                    target.BOO_ENTERED=src.BOO_ENTERED, 
                    target.BOO_EVENT=src.BOO_EVENT, 
                    target.BOO_EVTALIAS=src.BOO_EVTALIAS, 
                    target.BOO_FLEETCHECKED=src.BOO_FLEETCHECKED, 
                    target.BOO_FLEETMARKUP=src.BOO_FLEETMARKUP, 
                    target.BOO_GLTRANSFER=src.BOO_GLTRANSFER, 
                    target.BOO_GLTRANSFERFLAG=src.BOO_GLTRANSFERFLAG, 
                    target.BOO_HOURS=src.BOO_HOURS, 
                    target.BOO_INVOICE=src.BOO_INVOICE, 
                    target.BOO_INVOICELINE=src.BOO_INVOICELINE, 
                    target.BOO_INVOICE_ORG=src.BOO_INVOICE_ORG, 
                    target.BOO_INVOICE_REVISION=src.BOO_INVOICE_REVISION, 
                    target.BOO_JECATEGORY=src.BOO_JECATEGORY, 
                    target.BOO_JESOURCE=src.BOO_JESOURCE, 
                    target.BOO_LASTSAVED=src.BOO_LASTSAVED, 
                    target.BOO_MISC=src.BOO_MISC, 
                    target.BOO_MRC=src.BOO_MRC, 
                    target.BOO_OCRTYPE=src.BOO_OCRTYPE, 
                    target.BOO_OCTYPE=src.BOO_OCTYPE, 
                    target.BOO_OFF=src.BOO_OFF, 
                    target.BOO_ON=src.BOO_ON, 
                    target.BOO_ORDER=src.BOO_ORDER, 
                    target.BOO_ORDER_ORG=src.BOO_ORDER_ORG, 
                    target.BOO_ORDLINE=src.BOO_ORDLINE, 
                    target.BOO_ORIGHOURS=src.BOO_ORIGHOURS, 
                    target.BOO_ORIGTAXAMOUNT=src.BOO_ORIGTAXAMOUNT, 
                    target.BOO_PERSON=src.BOO_PERSON, 
                    target.BOO_RATE=src.BOO_RATE, 
                    target.BOO_ROUTEPARENT=src.BOO_ROUTEPARENT, 
                    target.BOO_ROUTEREC=src.BOO_ROUTEREC, 
                    target.BOO_ROUTERTYPE=src.BOO_ROUTERTYPE, 
                    target.BOO_SPLITHOURS=src.BOO_SPLITHOURS, 
                    target.BOO_TAXAMOUNT=src.BOO_TAXAMOUNT, 
                    target.BOO_TRADE=src.BOO_TRADE, 
                    target.BOO_TRANSCODE=src.BOO_TRANSCODE, 
                    target.BOO_TRANSGROUP=src.BOO_TRANSGROUP, 
                    target.BOO_TRANSORGID=src.BOO_TRANSORGID, 
                    target.BOO_UDFCHAR01=src.BOO_UDFCHAR01, 
                    target.BOO_UDFCHAR02=src.BOO_UDFCHAR02, 
                    target.BOO_UDFCHAR03=src.BOO_UDFCHAR03, 
                    target.BOO_UDFCHAR04=src.BOO_UDFCHAR04, 
                    target.BOO_UDFCHAR05=src.BOO_UDFCHAR05, 
                    target.BOO_UDFCHAR06=src.BOO_UDFCHAR06, 
                    target.BOO_UDFCHAR07=src.BOO_UDFCHAR07, 
                    target.BOO_UDFCHAR08=src.BOO_UDFCHAR08, 
                    target.BOO_UDFCHAR09=src.BOO_UDFCHAR09, 
                    target.BOO_UDFCHAR10=src.BOO_UDFCHAR10, 
                    target.BOO_UDFCHAR11=src.BOO_UDFCHAR11, 
                    target.BOO_UDFCHAR12=src.BOO_UDFCHAR12, 
                    target.BOO_UDFCHAR13=src.BOO_UDFCHAR13, 
                    target.BOO_UDFCHAR14=src.BOO_UDFCHAR14, 
                    target.BOO_UDFCHAR15=src.BOO_UDFCHAR15, 
                    target.BOO_UDFCHAR16=src.BOO_UDFCHAR16, 
                    target.BOO_UDFCHAR17=src.BOO_UDFCHAR17, 
                    target.BOO_UDFCHAR18=src.BOO_UDFCHAR18, 
                    target.BOO_UDFCHAR19=src.BOO_UDFCHAR19, 
                    target.BOO_UDFCHAR20=src.BOO_UDFCHAR20, 
                    target.BOO_UDFCHAR21=src.BOO_UDFCHAR21, 
                    target.BOO_UDFCHAR22=src.BOO_UDFCHAR22, 
                    target.BOO_UDFCHAR23=src.BOO_UDFCHAR23, 
                    target.BOO_UDFCHAR24=src.BOO_UDFCHAR24, 
                    target.BOO_UDFCHAR25=src.BOO_UDFCHAR25, 
                    target.BOO_UDFCHAR26=src.BOO_UDFCHAR26, 
                    target.BOO_UDFCHAR27=src.BOO_UDFCHAR27, 
                    target.BOO_UDFCHAR28=src.BOO_UDFCHAR28, 
                    target.BOO_UDFCHAR29=src.BOO_UDFCHAR29, 
                    target.BOO_UDFCHAR30=src.BOO_UDFCHAR30, 
                    target.BOO_UDFCHKBOX01=src.BOO_UDFCHKBOX01, 
                    target.BOO_UDFCHKBOX02=src.BOO_UDFCHKBOX02, 
                    target.BOO_UDFCHKBOX03=src.BOO_UDFCHKBOX03, 
                    target.BOO_UDFCHKBOX04=src.BOO_UDFCHKBOX04, 
                    target.BOO_UDFCHKBOX05=src.BOO_UDFCHKBOX05, 
                    target.BOO_UDFDATE01=src.BOO_UDFDATE01, 
                    target.BOO_UDFDATE02=src.BOO_UDFDATE02, 
                    target.BOO_UDFDATE03=src.BOO_UDFDATE03, 
                    target.BOO_UDFDATE04=src.BOO_UDFDATE04, 
                    target.BOO_UDFDATE05=src.BOO_UDFDATE05, 
                    target.BOO_UDFNUM01=src.BOO_UDFNUM01, 
                    target.BOO_UDFNUM02=src.BOO_UDFNUM02, 
                    target.BOO_UDFNUM03=src.BOO_UDFNUM03, 
                    target.BOO_UDFNUM04=src.BOO_UDFNUM04, 
                    target.BOO_UDFNUM05=src.BOO_UDFNUM05, 
                    target.BOO_UNMATCHEDINVOICE=src.BOO_UNMATCHEDINVOICE, 
                    target.BOO_UNMATCHEDINVOICELINE=src.BOO_UNMATCHEDINVOICELINE, 
                    target.BOO_UNMATCHEDINVOICE_ORG=src.BOO_UNMATCHEDINVOICE_ORG, 
                    target.BOO_UPDATECOUNT=src.BOO_UPDATECOUNT, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    BOO_ACD, 
                    BOO_ACT, 
                    BOO_BILLSUBLINE, 
                    BOO_CODE, 
                    BOO_CORRECTION, 
                    BOO_CORRECTIONDATE, 
                    BOO_COST, 
                    BOO_DATE, 
                    BOO_DESC, 
                    BOO_ENTERED, 
                    BOO_EVENT, 
                    BOO_EVTALIAS, 
                    BOO_FLEETCHECKED, 
                    BOO_FLEETMARKUP, 
                    BOO_GLTRANSFER, 
                    BOO_GLTRANSFERFLAG, 
                    BOO_HOURS, 
                    BOO_INVOICE, 
                    BOO_INVOICELINE, 
                    BOO_INVOICE_ORG, 
                    BOO_INVOICE_REVISION, 
                    BOO_JECATEGORY, 
                    BOO_JESOURCE, 
                    BOO_LASTSAVED, 
                    BOO_MISC, 
                    BOO_MRC, 
                    BOO_OCRTYPE, 
                    BOO_OCTYPE, 
                    BOO_OFF, 
                    BOO_ON, 
                    BOO_ORDER, 
                    BOO_ORDER_ORG, 
                    BOO_ORDLINE, 
                    BOO_ORIGHOURS, 
                    BOO_ORIGTAXAMOUNT, 
                    BOO_PERSON, 
                    BOO_RATE, 
                    BOO_ROUTEPARENT, 
                    BOO_ROUTEREC, 
                    BOO_ROUTERTYPE, 
                    BOO_SPLITHOURS, 
                    BOO_TAXAMOUNT, 
                    BOO_TRADE, 
                    BOO_TRANSCODE, 
                    BOO_TRANSGROUP, 
                    BOO_TRANSORGID, 
                    BOO_UDFCHAR01, 
                    BOO_UDFCHAR02, 
                    BOO_UDFCHAR03, 
                    BOO_UDFCHAR04, 
                    BOO_UDFCHAR05, 
                    BOO_UDFCHAR06, 
                    BOO_UDFCHAR07, 
                    BOO_UDFCHAR08, 
                    BOO_UDFCHAR09, 
                    BOO_UDFCHAR10, 
                    BOO_UDFCHAR11, 
                    BOO_UDFCHAR12, 
                    BOO_UDFCHAR13, 
                    BOO_UDFCHAR14, 
                    BOO_UDFCHAR15, 
                    BOO_UDFCHAR16, 
                    BOO_UDFCHAR17, 
                    BOO_UDFCHAR18, 
                    BOO_UDFCHAR19, 
                    BOO_UDFCHAR20, 
                    BOO_UDFCHAR21, 
                    BOO_UDFCHAR22, 
                    BOO_UDFCHAR23, 
                    BOO_UDFCHAR24, 
                    BOO_UDFCHAR25, 
                    BOO_UDFCHAR26, 
                    BOO_UDFCHAR27, 
                    BOO_UDFCHAR28, 
                    BOO_UDFCHAR29, 
                    BOO_UDFCHAR30, 
                    BOO_UDFCHKBOX01, 
                    BOO_UDFCHKBOX02, 
                    BOO_UDFCHKBOX03, 
                    BOO_UDFCHKBOX04, 
                    BOO_UDFCHKBOX05, 
                    BOO_UDFDATE01, 
                    BOO_UDFDATE02, 
                    BOO_UDFDATE03, 
                    BOO_UDFDATE04, 
                    BOO_UDFDATE05, 
                    BOO_UDFNUM01, 
                    BOO_UDFNUM02, 
                    BOO_UDFNUM03, 
                    BOO_UDFNUM04, 
                    BOO_UDFNUM05, 
                    BOO_UNMATCHEDINVOICE, 
                    BOO_UNMATCHEDINVOICELINE, 
                    BOO_UNMATCHEDINVOICE_ORG, 
                    BOO_UPDATECOUNT, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.BOO_ACD, 
                    src.BOO_ACT, 
                    src.BOO_BILLSUBLINE, 
                    src.BOO_CODE, 
                    src.BOO_CORRECTION, 
                    src.BOO_CORRECTIONDATE, 
                    src.BOO_COST, 
                    src.BOO_DATE, 
                    src.BOO_DESC, 
                    src.BOO_ENTERED, 
                    src.BOO_EVENT, 
                    src.BOO_EVTALIAS, 
                    src.BOO_FLEETCHECKED, 
                    src.BOO_FLEETMARKUP, 
                    src.BOO_GLTRANSFER, 
                    src.BOO_GLTRANSFERFLAG, 
                    src.BOO_HOURS, 
                    src.BOO_INVOICE, 
                    src.BOO_INVOICELINE, 
                    src.BOO_INVOICE_ORG, 
                    src.BOO_INVOICE_REVISION, 
                    src.BOO_JECATEGORY, 
                    src.BOO_JESOURCE, 
                    src.BOO_LASTSAVED, 
                    src.BOO_MISC, 
                    src.BOO_MRC, 
                    src.BOO_OCRTYPE, 
                    src.BOO_OCTYPE, 
                    src.BOO_OFF, 
                    src.BOO_ON, 
                    src.BOO_ORDER, 
                    src.BOO_ORDER_ORG, 
                    src.BOO_ORDLINE, 
                    src.BOO_ORIGHOURS, 
                    src.BOO_ORIGTAXAMOUNT, 
                    src.BOO_PERSON, 
                    src.BOO_RATE, 
                    src.BOO_ROUTEPARENT, 
                    src.BOO_ROUTEREC, 
                    src.BOO_ROUTERTYPE, 
                    src.BOO_SPLITHOURS, 
                    src.BOO_TAXAMOUNT, 
                    src.BOO_TRADE, 
                    src.BOO_TRANSCODE, 
                    src.BOO_TRANSGROUP, 
                    src.BOO_TRANSORGID, 
                    src.BOO_UDFCHAR01, 
                    src.BOO_UDFCHAR02, 
                    src.BOO_UDFCHAR03, 
                    src.BOO_UDFCHAR04, 
                    src.BOO_UDFCHAR05, 
                    src.BOO_UDFCHAR06, 
                    src.BOO_UDFCHAR07, 
                    src.BOO_UDFCHAR08, 
                    src.BOO_UDFCHAR09, 
                    src.BOO_UDFCHAR10, 
                    src.BOO_UDFCHAR11, 
                    src.BOO_UDFCHAR12, 
                    src.BOO_UDFCHAR13, 
                    src.BOO_UDFCHAR14, 
                    src.BOO_UDFCHAR15, 
                    src.BOO_UDFCHAR16, 
                    src.BOO_UDFCHAR17, 
                    src.BOO_UDFCHAR18, 
                    src.BOO_UDFCHAR19, 
                    src.BOO_UDFCHAR20, 
                    src.BOO_UDFCHAR21, 
                    src.BOO_UDFCHAR22, 
                    src.BOO_UDFCHAR23, 
                    src.BOO_UDFCHAR24, 
                    src.BOO_UDFCHAR25, 
                    src.BOO_UDFCHAR26, 
                    src.BOO_UDFCHAR27, 
                    src.BOO_UDFCHAR28, 
                    src.BOO_UDFCHAR29, 
                    src.BOO_UDFCHAR30, 
                    src.BOO_UDFCHKBOX01, 
                    src.BOO_UDFCHKBOX02, 
                    src.BOO_UDFCHKBOX03, 
                    src.BOO_UDFCHKBOX04, 
                    src.BOO_UDFCHKBOX05, 
                    src.BOO_UDFDATE01, 
                    src.BOO_UDFDATE02, 
                    src.BOO_UDFDATE03, 
                    src.BOO_UDFDATE04, 
                    src.BOO_UDFDATE05, 
                    src.BOO_UDFNUM01, 
                    src.BOO_UDFNUM02, 
                    src.BOO_UDFNUM03, 
                    src.BOO_UDFNUM04, 
                    src.BOO_UDFNUM05, 
                    src.BOO_UNMATCHEDINVOICE, 
                    src.BOO_UNMATCHEDINVOICELINE, 
                    src.BOO_UNMATCHEDINVOICE_ORG, 
                    src.BOO_UPDATECOUNT, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5BOOKEDHOURS_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.BOO_ACD, 
            strm.BOO_ACT, 
            strm.BOO_BILLSUBLINE, 
            strm.BOO_CODE, 
            strm.BOO_CORRECTION, 
            strm.BOO_CORRECTIONDATE, 
            strm.BOO_COST, 
            strm.BOO_DATE, 
            strm.BOO_DESC, 
            strm.BOO_ENTERED, 
            strm.BOO_EVENT, 
            strm.BOO_EVTALIAS, 
            strm.BOO_FLEETCHECKED, 
            strm.BOO_FLEETMARKUP, 
            strm.BOO_GLTRANSFER, 
            strm.BOO_GLTRANSFERFLAG, 
            strm.BOO_HOURS, 
            strm.BOO_INVOICE, 
            strm.BOO_INVOICELINE, 
            strm.BOO_INVOICE_ORG, 
            strm.BOO_INVOICE_REVISION, 
            strm.BOO_JECATEGORY, 
            strm.BOO_JESOURCE, 
            strm.BOO_LASTSAVED, 
            strm.BOO_MISC, 
            strm.BOO_MRC, 
            strm.BOO_OCRTYPE, 
            strm.BOO_OCTYPE, 
            strm.BOO_OFF, 
            strm.BOO_ON, 
            strm.BOO_ORDER, 
            strm.BOO_ORDER_ORG, 
            strm.BOO_ORDLINE, 
            strm.BOO_ORIGHOURS, 
            strm.BOO_ORIGTAXAMOUNT, 
            strm.BOO_PERSON, 
            strm.BOO_RATE, 
            strm.BOO_ROUTEPARENT, 
            strm.BOO_ROUTEREC, 
            strm.BOO_ROUTERTYPE, 
            strm.BOO_SPLITHOURS, 
            strm.BOO_TAXAMOUNT, 
            strm.BOO_TRADE, 
            strm.BOO_TRANSCODE, 
            strm.BOO_TRANSGROUP, 
            strm.BOO_TRANSORGID, 
            strm.BOO_UDFCHAR01, 
            strm.BOO_UDFCHAR02, 
            strm.BOO_UDFCHAR03, 
            strm.BOO_UDFCHAR04, 
            strm.BOO_UDFCHAR05, 
            strm.BOO_UDFCHAR06, 
            strm.BOO_UDFCHAR07, 
            strm.BOO_UDFCHAR08, 
            strm.BOO_UDFCHAR09, 
            strm.BOO_UDFCHAR10, 
            strm.BOO_UDFCHAR11, 
            strm.BOO_UDFCHAR12, 
            strm.BOO_UDFCHAR13, 
            strm.BOO_UDFCHAR14, 
            strm.BOO_UDFCHAR15, 
            strm.BOO_UDFCHAR16, 
            strm.BOO_UDFCHAR17, 
            strm.BOO_UDFCHAR18, 
            strm.BOO_UDFCHAR19, 
            strm.BOO_UDFCHAR20, 
            strm.BOO_UDFCHAR21, 
            strm.BOO_UDFCHAR22, 
            strm.BOO_UDFCHAR23, 
            strm.BOO_UDFCHAR24, 
            strm.BOO_UDFCHAR25, 
            strm.BOO_UDFCHAR26, 
            strm.BOO_UDFCHAR27, 
            strm.BOO_UDFCHAR28, 
            strm.BOO_UDFCHAR29, 
            strm.BOO_UDFCHAR30, 
            strm.BOO_UDFCHKBOX01, 
            strm.BOO_UDFCHKBOX02, 
            strm.BOO_UDFCHKBOX03, 
            strm.BOO_UDFCHKBOX04, 
            strm.BOO_UDFCHKBOX05, 
            strm.BOO_UDFDATE01, 
            strm.BOO_UDFDATE02, 
            strm.BOO_UDFDATE03, 
            strm.BOO_UDFDATE04, 
            strm.BOO_UDFDATE05, 
            strm.BOO_UDFNUM01, 
            strm.BOO_UDFNUM02, 
            strm.BOO_UDFNUM03, 
            strm.BOO_UDFNUM04, 
            strm.BOO_UDFNUM05, 
            strm.BOO_UNMATCHEDINVOICE, 
            strm.BOO_UNMATCHEDINVOICELINE, 
            strm.BOO_UNMATCHEDINVOICE_ORG, 
            strm.BOO_UPDATECOUNT, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.BOO_CODE ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5BOOKEDHOURS as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.BOO_CODE=src.BOO_CODE) OR (target.BOO_CODE IS NULL AND src.BOO_CODE IS NULL)) 
                when matched then update set
                    target.BOO_ACD=src.BOO_ACD, 
                    target.BOO_ACT=src.BOO_ACT, 
                    target.BOO_BILLSUBLINE=src.BOO_BILLSUBLINE, 
                    target.BOO_CODE=src.BOO_CODE, 
                    target.BOO_CORRECTION=src.BOO_CORRECTION, 
                    target.BOO_CORRECTIONDATE=src.BOO_CORRECTIONDATE, 
                    target.BOO_COST=src.BOO_COST, 
                    target.BOO_DATE=src.BOO_DATE, 
                    target.BOO_DESC=src.BOO_DESC, 
                    target.BOO_ENTERED=src.BOO_ENTERED, 
                    target.BOO_EVENT=src.BOO_EVENT, 
                    target.BOO_EVTALIAS=src.BOO_EVTALIAS, 
                    target.BOO_FLEETCHECKED=src.BOO_FLEETCHECKED, 
                    target.BOO_FLEETMARKUP=src.BOO_FLEETMARKUP, 
                    target.BOO_GLTRANSFER=src.BOO_GLTRANSFER, 
                    target.BOO_GLTRANSFERFLAG=src.BOO_GLTRANSFERFLAG, 
                    target.BOO_HOURS=src.BOO_HOURS, 
                    target.BOO_INVOICE=src.BOO_INVOICE, 
                    target.BOO_INVOICELINE=src.BOO_INVOICELINE, 
                    target.BOO_INVOICE_ORG=src.BOO_INVOICE_ORG, 
                    target.BOO_INVOICE_REVISION=src.BOO_INVOICE_REVISION, 
                    target.BOO_JECATEGORY=src.BOO_JECATEGORY, 
                    target.BOO_JESOURCE=src.BOO_JESOURCE, 
                    target.BOO_LASTSAVED=src.BOO_LASTSAVED, 
                    target.BOO_MISC=src.BOO_MISC, 
                    target.BOO_MRC=src.BOO_MRC, 
                    target.BOO_OCRTYPE=src.BOO_OCRTYPE, 
                    target.BOO_OCTYPE=src.BOO_OCTYPE, 
                    target.BOO_OFF=src.BOO_OFF, 
                    target.BOO_ON=src.BOO_ON, 
                    target.BOO_ORDER=src.BOO_ORDER, 
                    target.BOO_ORDER_ORG=src.BOO_ORDER_ORG, 
                    target.BOO_ORDLINE=src.BOO_ORDLINE, 
                    target.BOO_ORIGHOURS=src.BOO_ORIGHOURS, 
                    target.BOO_ORIGTAXAMOUNT=src.BOO_ORIGTAXAMOUNT, 
                    target.BOO_PERSON=src.BOO_PERSON, 
                    target.BOO_RATE=src.BOO_RATE, 
                    target.BOO_ROUTEPARENT=src.BOO_ROUTEPARENT, 
                    target.BOO_ROUTEREC=src.BOO_ROUTEREC, 
                    target.BOO_ROUTERTYPE=src.BOO_ROUTERTYPE, 
                    target.BOO_SPLITHOURS=src.BOO_SPLITHOURS, 
                    target.BOO_TAXAMOUNT=src.BOO_TAXAMOUNT, 
                    target.BOO_TRADE=src.BOO_TRADE, 
                    target.BOO_TRANSCODE=src.BOO_TRANSCODE, 
                    target.BOO_TRANSGROUP=src.BOO_TRANSGROUP, 
                    target.BOO_TRANSORGID=src.BOO_TRANSORGID, 
                    target.BOO_UDFCHAR01=src.BOO_UDFCHAR01, 
                    target.BOO_UDFCHAR02=src.BOO_UDFCHAR02, 
                    target.BOO_UDFCHAR03=src.BOO_UDFCHAR03, 
                    target.BOO_UDFCHAR04=src.BOO_UDFCHAR04, 
                    target.BOO_UDFCHAR05=src.BOO_UDFCHAR05, 
                    target.BOO_UDFCHAR06=src.BOO_UDFCHAR06, 
                    target.BOO_UDFCHAR07=src.BOO_UDFCHAR07, 
                    target.BOO_UDFCHAR08=src.BOO_UDFCHAR08, 
                    target.BOO_UDFCHAR09=src.BOO_UDFCHAR09, 
                    target.BOO_UDFCHAR10=src.BOO_UDFCHAR10, 
                    target.BOO_UDFCHAR11=src.BOO_UDFCHAR11, 
                    target.BOO_UDFCHAR12=src.BOO_UDFCHAR12, 
                    target.BOO_UDFCHAR13=src.BOO_UDFCHAR13, 
                    target.BOO_UDFCHAR14=src.BOO_UDFCHAR14, 
                    target.BOO_UDFCHAR15=src.BOO_UDFCHAR15, 
                    target.BOO_UDFCHAR16=src.BOO_UDFCHAR16, 
                    target.BOO_UDFCHAR17=src.BOO_UDFCHAR17, 
                    target.BOO_UDFCHAR18=src.BOO_UDFCHAR18, 
                    target.BOO_UDFCHAR19=src.BOO_UDFCHAR19, 
                    target.BOO_UDFCHAR20=src.BOO_UDFCHAR20, 
                    target.BOO_UDFCHAR21=src.BOO_UDFCHAR21, 
                    target.BOO_UDFCHAR22=src.BOO_UDFCHAR22, 
                    target.BOO_UDFCHAR23=src.BOO_UDFCHAR23, 
                    target.BOO_UDFCHAR24=src.BOO_UDFCHAR24, 
                    target.BOO_UDFCHAR25=src.BOO_UDFCHAR25, 
                    target.BOO_UDFCHAR26=src.BOO_UDFCHAR26, 
                    target.BOO_UDFCHAR27=src.BOO_UDFCHAR27, 
                    target.BOO_UDFCHAR28=src.BOO_UDFCHAR28, 
                    target.BOO_UDFCHAR29=src.BOO_UDFCHAR29, 
                    target.BOO_UDFCHAR30=src.BOO_UDFCHAR30, 
                    target.BOO_UDFCHKBOX01=src.BOO_UDFCHKBOX01, 
                    target.BOO_UDFCHKBOX02=src.BOO_UDFCHKBOX02, 
                    target.BOO_UDFCHKBOX03=src.BOO_UDFCHKBOX03, 
                    target.BOO_UDFCHKBOX04=src.BOO_UDFCHKBOX04, 
                    target.BOO_UDFCHKBOX05=src.BOO_UDFCHKBOX05, 
                    target.BOO_UDFDATE01=src.BOO_UDFDATE01, 
                    target.BOO_UDFDATE02=src.BOO_UDFDATE02, 
                    target.BOO_UDFDATE03=src.BOO_UDFDATE03, 
                    target.BOO_UDFDATE04=src.BOO_UDFDATE04, 
                    target.BOO_UDFDATE05=src.BOO_UDFDATE05, 
                    target.BOO_UDFNUM01=src.BOO_UDFNUM01, 
                    target.BOO_UDFNUM02=src.BOO_UDFNUM02, 
                    target.BOO_UDFNUM03=src.BOO_UDFNUM03, 
                    target.BOO_UDFNUM04=src.BOO_UDFNUM04, 
                    target.BOO_UDFNUM05=src.BOO_UDFNUM05, 
                    target.BOO_UNMATCHEDINVOICE=src.BOO_UNMATCHEDINVOICE, 
                    target.BOO_UNMATCHEDINVOICELINE=src.BOO_UNMATCHEDINVOICELINE, 
                    target.BOO_UNMATCHEDINVOICE_ORG=src.BOO_UNMATCHEDINVOICE_ORG, 
                    target.BOO_UPDATECOUNT=src.BOO_UPDATECOUNT, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( BOO_ACD, BOO_ACT, BOO_BILLSUBLINE, BOO_CODE, BOO_CORRECTION, BOO_CORRECTIONDATE, BOO_COST, BOO_DATE, BOO_DESC, BOO_ENTERED, BOO_EVENT, BOO_EVTALIAS, BOO_FLEETCHECKED, BOO_FLEETMARKUP, BOO_GLTRANSFER, BOO_GLTRANSFERFLAG, BOO_HOURS, BOO_INVOICE, BOO_INVOICELINE, BOO_INVOICE_ORG, BOO_INVOICE_REVISION, BOO_JECATEGORY, BOO_JESOURCE, BOO_LASTSAVED, BOO_MISC, BOO_MRC, BOO_OCRTYPE, BOO_OCTYPE, BOO_OFF, BOO_ON, BOO_ORDER, BOO_ORDER_ORG, BOO_ORDLINE, BOO_ORIGHOURS, BOO_ORIGTAXAMOUNT, BOO_PERSON, BOO_RATE, BOO_ROUTEPARENT, BOO_ROUTEREC, BOO_ROUTERTYPE, BOO_SPLITHOURS, BOO_TAXAMOUNT, BOO_TRADE, BOO_TRANSCODE, BOO_TRANSGROUP, BOO_TRANSORGID, BOO_UDFCHAR01, BOO_UDFCHAR02, BOO_UDFCHAR03, BOO_UDFCHAR04, BOO_UDFCHAR05, BOO_UDFCHAR06, BOO_UDFCHAR07, BOO_UDFCHAR08, BOO_UDFCHAR09, BOO_UDFCHAR10, BOO_UDFCHAR11, BOO_UDFCHAR12, BOO_UDFCHAR13, BOO_UDFCHAR14, BOO_UDFCHAR15, BOO_UDFCHAR16, BOO_UDFCHAR17, BOO_UDFCHAR18, BOO_UDFCHAR19, BOO_UDFCHAR20, BOO_UDFCHAR21, BOO_UDFCHAR22, BOO_UDFCHAR23, BOO_UDFCHAR24, BOO_UDFCHAR25, BOO_UDFCHAR26, BOO_UDFCHAR27, BOO_UDFCHAR28, BOO_UDFCHAR29, BOO_UDFCHAR30, BOO_UDFCHKBOX01, BOO_UDFCHKBOX02, BOO_UDFCHKBOX03, BOO_UDFCHKBOX04, BOO_UDFCHKBOX05, BOO_UDFDATE01, BOO_UDFDATE02, BOO_UDFDATE03, BOO_UDFDATE04, BOO_UDFDATE05, BOO_UDFNUM01, BOO_UDFNUM02, BOO_UDFNUM03, BOO_UDFNUM04, BOO_UDFNUM05, BOO_UNMATCHEDINVOICE, BOO_UNMATCHEDINVOICELINE, BOO_UNMATCHEDINVOICE_ORG, BOO_UPDATECOUNT, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.BOO_ACD, 
                    src.BOO_ACT, 
                    src.BOO_BILLSUBLINE, 
                    src.BOO_CODE, 
                    src.BOO_CORRECTION, 
                    src.BOO_CORRECTIONDATE, 
                    src.BOO_COST, 
                    src.BOO_DATE, 
                    src.BOO_DESC, 
                    src.BOO_ENTERED, 
                    src.BOO_EVENT, 
                    src.BOO_EVTALIAS, 
                    src.BOO_FLEETCHECKED, 
                    src.BOO_FLEETMARKUP, 
                    src.BOO_GLTRANSFER, 
                    src.BOO_GLTRANSFERFLAG, 
                    src.BOO_HOURS, 
                    src.BOO_INVOICE, 
                    src.BOO_INVOICELINE, 
                    src.BOO_INVOICE_ORG, 
                    src.BOO_INVOICE_REVISION, 
                    src.BOO_JECATEGORY, 
                    src.BOO_JESOURCE, 
                    src.BOO_LASTSAVED, 
                    src.BOO_MISC, 
                    src.BOO_MRC, 
                    src.BOO_OCRTYPE, 
                    src.BOO_OCTYPE, 
                    src.BOO_OFF, 
                    src.BOO_ON, 
                    src.BOO_ORDER, 
                    src.BOO_ORDER_ORG, 
                    src.BOO_ORDLINE, 
                    src.BOO_ORIGHOURS, 
                    src.BOO_ORIGTAXAMOUNT, 
                    src.BOO_PERSON, 
                    src.BOO_RATE, 
                    src.BOO_ROUTEPARENT, 
                    src.BOO_ROUTEREC, 
                    src.BOO_ROUTERTYPE, 
                    src.BOO_SPLITHOURS, 
                    src.BOO_TAXAMOUNT, 
                    src.BOO_TRADE, 
                    src.BOO_TRANSCODE, 
                    src.BOO_TRANSGROUP, 
                    src.BOO_TRANSORGID, 
                    src.BOO_UDFCHAR01, 
                    src.BOO_UDFCHAR02, 
                    src.BOO_UDFCHAR03, 
                    src.BOO_UDFCHAR04, 
                    src.BOO_UDFCHAR05, 
                    src.BOO_UDFCHAR06, 
                    src.BOO_UDFCHAR07, 
                    src.BOO_UDFCHAR08, 
                    src.BOO_UDFCHAR09, 
                    src.BOO_UDFCHAR10, 
                    src.BOO_UDFCHAR11, 
                    src.BOO_UDFCHAR12, 
                    src.BOO_UDFCHAR13, 
                    src.BOO_UDFCHAR14, 
                    src.BOO_UDFCHAR15, 
                    src.BOO_UDFCHAR16, 
                    src.BOO_UDFCHAR17, 
                    src.BOO_UDFCHAR18, 
                    src.BOO_UDFCHAR19, 
                    src.BOO_UDFCHAR20, 
                    src.BOO_UDFCHAR21, 
                    src.BOO_UDFCHAR22, 
                    src.BOO_UDFCHAR23, 
                    src.BOO_UDFCHAR24, 
                    src.BOO_UDFCHAR25, 
                    src.BOO_UDFCHAR26, 
                    src.BOO_UDFCHAR27, 
                    src.BOO_UDFCHAR28, 
                    src.BOO_UDFCHAR29, 
                    src.BOO_UDFCHAR30, 
                    src.BOO_UDFCHKBOX01, 
                    src.BOO_UDFCHKBOX02, 
                    src.BOO_UDFCHKBOX03, 
                    src.BOO_UDFCHKBOX04, 
                    src.BOO_UDFCHKBOX05, 
                    src.BOO_UDFDATE01, 
                    src.BOO_UDFDATE02, 
                    src.BOO_UDFDATE03, 
                    src.BOO_UDFDATE04, 
                    src.BOO_UDFDATE05, 
                    src.BOO_UDFNUM01, 
                    src.BOO_UDFNUM02, 
                    src.BOO_UDFNUM03, 
                    src.BOO_UDFNUM04, 
                    src.BOO_UDFNUM05, 
                    src.BOO_UNMATCHEDINVOICE, 
                    src.BOO_UNMATCHEDINVOICELINE, 
                    src.BOO_UNMATCHEDINVOICE_ORG, 
                    src.BOO_UPDATECOUNT, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;