CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5ORDERS(
                "ORD_ACD" numeric(38, 10), 
                "ORD_APPROV" datetime, 
                "ORD_ATTENTIONTO" varchar, 
                "ORD_AUTH" varchar, 
                "ORD_BLANKETORDER" varchar, 
                "ORD_BLANKETRELEASE" numeric(38, 10), 
                "ORD_BUYER" varchar, 
                "ORD_CLASS" varchar, 
                "ORD_CLASS_ORG" varchar, 
                "ORD_CODE" varchar, 
                "ORD_CONTRACT" varchar, 
                "ORD_CONTROLNO" varchar, 
                "ORD_CONVERTTOASN" varchar, 
                "ORD_CREATED" datetime, 
                "ORD_CREDITCARD" numeric(38, 10), 
                "ORD_CURR" varchar, 
                "ORD_DATE" datetime, 
                "ORD_DELADDRESS" varchar, 
                "ORD_DESC" varchar, 
                "ORD_DFLTAUTH" varchar, 
                "ORD_DISCOUNT" numeric(38, 10), 
                "ORD_DISCPERC" numeric(38, 10), 
                "ORD_DUE" datetime, 
                "ORD_EXCH" numeric(38, 10), 
                "ORD_EXCHFROMDUAL" numeric(38, 10), 
                "ORD_EXCHTODUAL" numeric(38, 10), 
                "ORD_FOBPOINT" varchar, 
                "ORD_FREIGHTTERMS" varchar, 
                "ORD_INTERFACE" datetime, 
                "ORD_IPTRANSMITTED" varchar, 
                "ORD_JECATEGORY" varchar, 
                "ORD_JESOURCE" varchar, 
                "ORD_LASTSAVED" datetime, 
                "ORD_LASTSTATUSUPDATE" datetime, 
                "ORD_ORG" varchar, 
                "ORD_ORIGIN" varchar, 
                "ORD_PACKAGETRACKINGNUMBER" varchar, 
                "ORD_PAYBYMETHOD" varchar, 
                "ORD_PAYMENTTERMS" varchar, 
                "ORD_PRICE" numeric(38, 10), 
                "ORD_PRINTED" varchar, 
                "ORD_REVISED" datetime, 
                "ORD_REVISION" numeric(38, 10), 
                "ORD_REVISIONREASON" varchar, 
                "ORD_RSTATUS" varchar, 
                "ORD_RTYPE" varchar, 
                "ORD_SHIPVIA" varchar, 
                "ORD_SOURCECODE" varchar, 
                "ORD_SOURCESYSTEM" varchar, 
                "ORD_STATUS" varchar, 
                "ORD_STORE" varchar, 
                "ORD_SUPPLIER" varchar, 
                "ORD_SUPPLIER_ORG" varchar, 
                "ORD_TYPE" varchar, 
                "ORD_UDFCHAR01" varchar, 
                "ORD_UDFCHAR02" varchar, 
                "ORD_UDFCHAR03" varchar, 
                "ORD_UDFCHAR04" varchar, 
                "ORD_UDFCHAR05" varchar, 
                "ORD_UDFCHAR06" varchar, 
                "ORD_UDFCHAR07" varchar, 
                "ORD_UDFCHAR08" varchar, 
                "ORD_UDFCHAR09" varchar, 
                "ORD_UDFCHAR10" varchar, 
                "ORD_UDFCHAR11" varchar, 
                "ORD_UDFCHAR12" varchar, 
                "ORD_UDFCHAR13" varchar, 
                "ORD_UDFCHAR14" varchar, 
                "ORD_UDFCHAR15" varchar, 
                "ORD_UDFCHAR16" varchar, 
                "ORD_UDFCHAR17" varchar, 
                "ORD_UDFCHAR18" varchar, 
                "ORD_UDFCHAR19" varchar, 
                "ORD_UDFCHAR20" varchar, 
                "ORD_UDFCHAR21" varchar, 
                "ORD_UDFCHAR22" varchar, 
                "ORD_UDFCHAR23" varchar, 
                "ORD_UDFCHAR24" varchar, 
                "ORD_UDFCHAR25" varchar, 
                "ORD_UDFCHAR26" varchar, 
                "ORD_UDFCHAR27" varchar, 
                "ORD_UDFCHAR28" varchar, 
                "ORD_UDFCHAR29" varchar, 
                "ORD_UDFCHAR30" varchar, 
                "ORD_UDFCHKBOX01" varchar, 
                "ORD_UDFCHKBOX02" varchar, 
                "ORD_UDFCHKBOX03" varchar, 
                "ORD_UDFCHKBOX04" varchar, 
                "ORD_UDFCHKBOX05" varchar, 
                "ORD_UDFDATE01" datetime, 
                "ORD_UDFDATE02" datetime, 
                "ORD_UDFDATE03" datetime, 
                "ORD_UDFDATE04" datetime, 
                "ORD_UDFDATE05" datetime, 
                "ORD_UDFNUM01" numeric(38, 10), 
                "ORD_UDFNUM02" numeric(38, 10), 
                "ORD_UDFNUM03" numeric(38, 10), 
                "ORD_UDFNUM04" numeric(38, 10), 
                "ORD_UDFNUM05" numeric(38, 10), 
                "ORD_UPDATECOUNT" numeric(38, 10), 
                "ORD_UPDATED" datetime, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 