CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5CODESTRUCTURE(
                "CSR_CODE" varchar, 
                "CSR_DESC" varchar, 
                "CSR_ENTITY" varchar, 
                "CSR_ICON" varchar, 
                "CSR_ICONPATH" varchar, 
                "CSR_IMAGE" varchar, 
                "CSR_IMPORTANCE" varchar, 
                "CSR_LASTSAVED" datetime, 
                "CSR_MATERIALTYPE" varchar, 
                "CSR_NOTUSED" varchar, 
                "CSR_RENTITY" varchar, 
                "CSR_STRLEVEL1" varchar, 
                "CSR_STRLEVEL2" varchar, 
                "CSR_STRLEVEL3" varchar, 
                "CSR_STRLEVEL4" varchar, 
                "CSR_STRLEVEL5" varchar, 
                "CSR_STRLEVEL6" varchar, 
                "CSR_STRLEVEL7" varchar, 
                "CSR_STRLEVEL8" varchar, 
                "CSR_STRUCTURE" varchar, 
                "CSR_UPDATECOUNT" numeric(38, 10), 
                "CSR_UPDATED" datetime, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 