CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5IESREPOSITORIES(
                "ENS_CODE" varchar, 
                "ENS_DATECREATEDCOL" varchar, 
                "ENS_DATELASTCRAWL" datetime, 
                "ENS_DATEUPDATEDCOL" varchar, 
                "ENS_DESC" varchar, 
                "ENS_INTERESTCENTER" varchar, 
                "ENS_ISINCREMENTAL" varchar, 
                "ENS_ISPOPUP" varchar, 
                "ENS_LASTSAVED" datetime, 
                "ENS_NOTUSED" varchar, 
                "ENS_ORGCOL" varchar, 
                "ENS_TAB" varchar, 
                "ENS_TABLENAME" varchar, 
                "ENS_TABLEPREFIX" varchar, 
                "ENS_THUMBNAIL" varchar, 
                "ENS_UPDATECOUNT" numeric(38, 10), 
                "ENS_USERFUNCTION" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 