CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5PARTS(
                "PAR_ASMLEVEL" varchar, 
                "PAR_AVGPRICE" numeric(38, 10), 
                "PAR_BASEPRICE" numeric(38, 10), 
                "PAR_BUYER" varchar, 
                "PAR_BYASSET" varchar, 
                "PAR_BYLOT" varchar, 
                "PAR_CALSTANDARD" varchar, 
                "PAR_CATEGORY" varchar, 
                "PAR_CLASS" varchar, 
                "PAR_CLASS_ORG" varchar, 
                "PAR_CODE" varchar, 
                "PAR_CODESTRUCTURE" varchar, 
                "PAR_COMMODITY" varchar, 
                "PAR_COMPLEVEL" varchar, 
                "PAR_CONDITION" varchar, 
                "PAR_CONDITIONTPL" varchar, 
                "PAR_CONDITIONTPL_ORG" varchar, 
                "PAR_COREVALUE" numeric(38, 10), 
                "PAR_CREATED" datetime, 
                "PAR_CREATEDBY" varchar, 
                "PAR_DESC" varchar, 
                "PAR_DOCUMOTO_BOOKID" varchar, 
                "PAR_DOCUMOTO_PART" varchar, 
                "PAR_FUGITIVEEMISSIONGAS" varchar, 
                "PAR_IMPORTANCE" varchar, 
                "PAR_INSMETHOD" varchar, 
                "PAR_INSPECT" varchar, 
                "PAR_INTERFACE" datetime, 
                "PAR_KIT" varchar, 
                "PAR_LASTPRICE" numeric(38, 10), 
                "PAR_LASTSAVED" datetime, 
                "PAR_LASTSTATUSUPDATE" datetime, 
                "PAR_LONGDESCRIPTION" varchar, 
                "PAR_MATERIALTYPE" varchar, 
                "PAR_NOTUSED" varchar, 
                "PAR_ORG" varchar, 
                "PAR_PARENTPART" varchar, 
                "PAR_PREFSUP" varchar, 
                "PAR_PREFSUPPRICE" numeric(38, 10), 
                "PAR_PREFSUP_ORG" varchar, 
                "PAR_PREFUOM" varchar, 
                "PAR_PREVENTREORDERS" varchar, 
                "PAR_PROFILEPICTURE" varchar, 
                "PAR_REPAIRABLE" varchar, 
                "PAR_SAFETYREVIEWED" datetime, 
                "PAR_SAFETYREVIEWEDBY" varchar, 
                "PAR_SAFETYREVIEWEDNAME" varchar, 
                "PAR_SAFETYREVIEWEDTYPE" varchar, 
                "PAR_SAFETYREVIEWREQUIRED" datetime, 
                "PAR_SAVEHISTORY" varchar, 
                "PAR_SOURCECODE" varchar, 
                "PAR_SOURCESYSTEM" varchar, 
                "PAR_STDPRICE" numeric(38, 10), 
                "PAR_SUBCOMMODITY" varchar, 
                "PAR_SYSLEVEL" varchar, 
                "PAR_TAX" varchar, 
                "PAR_TOOL" varchar, 
                "PAR_TRACKBYCONDITION" varchar, 
                "PAR_TRACKRTYPE" varchar, 
                "PAR_TRACKTYPE" varchar, 
                "PAR_UDFCHAR01" varchar, 
                "PAR_UDFCHAR02" varchar, 
                "PAR_UDFCHAR03" varchar, 
                "PAR_UDFCHAR04" varchar, 
                "PAR_UDFCHAR05" varchar, 
                "PAR_UDFCHAR06" varchar, 
                "PAR_UDFCHAR07" varchar, 
                "PAR_UDFCHAR08" varchar, 
                "PAR_UDFCHAR09" varchar, 
                "PAR_UDFCHAR10" varchar, 
                "PAR_UDFCHAR11" varchar, 
                "PAR_UDFCHAR12" varchar, 
                "PAR_UDFCHAR13" varchar, 
                "PAR_UDFCHAR14" varchar, 
                "PAR_UDFCHAR15" varchar, 
                "PAR_UDFCHAR16" varchar, 
                "PAR_UDFCHAR17" varchar, 
                "PAR_UDFCHAR18" varchar, 
                "PAR_UDFCHAR19" varchar, 
                "PAR_UDFCHAR20" varchar, 
                "PAR_UDFCHAR21" varchar, 
                "PAR_UDFCHAR22" varchar, 
                "PAR_UDFCHAR23" varchar, 
                "PAR_UDFCHAR24" varchar, 
                "PAR_UDFCHAR25" varchar, 
                "PAR_UDFCHAR26" varchar, 
                "PAR_UDFCHAR27" varchar, 
                "PAR_UDFCHAR28" varchar, 
                "PAR_UDFCHAR29" varchar, 
                "PAR_UDFCHAR30" varchar, 
                "PAR_UDFCHKBOX01" varchar, 
                "PAR_UDFCHKBOX02" varchar, 
                "PAR_UDFCHKBOX03" varchar, 
                "PAR_UDFCHKBOX04" varchar, 
                "PAR_UDFCHKBOX05" varchar, 
                "PAR_UDFDATE01" datetime, 
                "PAR_UDFDATE02" datetime, 
                "PAR_UDFDATE03" datetime, 
                "PAR_UDFDATE04" datetime, 
                "PAR_UDFDATE05" datetime, 
                "PAR_UDFNOTE01" varchar, 
                "PAR_UDFNOTE02" varchar, 
                "PAR_UDFNUM01" numeric(38, 10), 
                "PAR_UDFNUM02" numeric(38, 10), 
                "PAR_UDFNUM03" numeric(38, 10), 
                "PAR_UDFNUM04" numeric(38, 10), 
                "PAR_UDFNUM05" numeric(38, 10), 
                "PAR_UOM" varchar, 
                "PAR_UPDATECOUNT" numeric(38, 10), 
                "PAR_UPDATED" datetime, 
                "PAR_UPDATEDBY" varchar, 
                "PAR_WARDAYS" numeric(38, 10), 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 