CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5POINTS_DELETED(
                "POI_CREATED" datetime, 
                "POI_DESC" varchar, 
                "POI_LASTSAVED" datetime, 
                "POI_OBJECT" varchar, 
                "POI_OBJECT_ORG" varchar, 
                "POI_OBRTYPE" varchar, 
                "POI_OBTYPE" varchar, 
                "POI_POINT" varchar, 
                "POI_POINTTYPE" varchar, 
                "POI_UDFCHAR01" varchar, 
                "POI_UDFCHAR02" varchar, 
                "POI_UDFCHAR03" varchar, 
                "POI_UDFCHAR04" varchar, 
                "POI_UDFCHAR05" varchar, 
                "POI_UDFCHAR06" varchar, 
                "POI_UDFCHAR07" varchar, 
                "POI_UDFCHAR08" varchar, 
                "POI_UDFCHAR09" varchar, 
                "POI_UDFCHAR10" varchar, 
                "POI_UDFCHAR11" varchar, 
                "POI_UDFCHAR12" varchar, 
                "POI_UDFCHAR13" varchar, 
                "POI_UDFCHAR14" varchar, 
                "POI_UDFCHAR15" varchar, 
                "POI_UDFCHAR16" varchar, 
                "POI_UDFCHAR17" varchar, 
                "POI_UDFCHAR18" varchar, 
                "POI_UDFCHAR19" varchar, 
                "POI_UDFCHAR20" varchar, 
                "POI_UDFCHAR21" varchar, 
                "POI_UDFCHAR22" varchar, 
                "POI_UDFCHAR23" varchar, 
                "POI_UDFCHAR24" varchar, 
                "POI_UDFCHAR25" varchar, 
                "POI_UDFCHAR26" varchar, 
                "POI_UDFCHAR27" varchar, 
                "POI_UDFCHAR28" varchar, 
                "POI_UDFCHAR29" varchar, 
                "POI_UDFCHAR30" varchar, 
                "POI_UDFCHKBOX01" varchar, 
                "POI_UDFCHKBOX02" varchar, 
                "POI_UDFCHKBOX03" varchar, 
                "POI_UDFCHKBOX04" varchar, 
                "POI_UDFCHKBOX05" varchar, 
                "POI_UDFDATE01" datetime, 
                "POI_UDFDATE02" datetime, 
                "POI_UDFDATE03" datetime, 
                "POI_UDFDATE04" datetime, 
                "POI_UDFDATE05" datetime, 
                "POI_UDFNUM01" numeric(38, 10), 
                "POI_UDFNUM02" numeric(38, 10), 
                "POI_UDFNUM03" numeric(38, 10), 
                "POI_UDFNUM04" numeric(38, 10), 
                "POI_UDFNUM05" numeric(38, 10), 
                "POI_UPDATECOUNT" numeric(38, 10), 
                "POI_UPDATED" datetime, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 