CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5ENTITIES_DELETED(
                "ENT_ADDATTRIBS" varchar, 
                "ENT_ADDRESSES" varchar, 
                "ENT_ASSPARTS" varchar, 
                "ENT_ASSPERMITS" varchar, 
                "ENT_AUDITS" varchar, 
                "ENT_CAAUDIT" varchar, 
                "ENT_CLASSIF" varchar, 
                "ENT_DOCUMENTS" varchar, 
                "ENT_ENTITY" varchar, 
                "ENT_ERECORD" varchar, 
                "ENT_FREETEXT" varchar, 
                "ENT_FTAUDIT" varchar, 
                "ENT_LASTSAVED" datetime, 
                "ENT_MULTILANG" varchar, 
                "ENT_RENTITY" varchar, 
                "ENT_STATENT" varchar, 
                "ENT_TABLE" varchar, 
                "ENT_TYPENT" varchar, 
                "ENT_UPDATECOUNT" numeric(38, 10), 
                "ENT_UPDATED" datetime, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 