CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5PRECAUTIONS_DELETED(
                "PCA_APPROVED" datetime, 
                "PCA_APPROVEDBY" varchar, 
                "PCA_CLASS" varchar, 
                "PCA_CLASS_ORG" varchar, 
                "PCA_CODE" varchar, 
                "PCA_CREATED" datetime, 
                "PCA_CREATEDBY" varchar, 
                "PCA_DESC" varchar, 
                "PCA_LASTSAVED" datetime, 
                "PCA_NOTUSED" varchar, 
                "PCA_ORG" varchar, 
                "PCA_REQUESTED" datetime, 
                "PCA_REQUESTEDBY" varchar, 
                "PCA_RESPONSIBILITY" varchar, 
                "PCA_REVIEWREQUIRED" datetime, 
                "PCA_REVISION" numeric(38, 10), 
                "PCA_REVISIONREASON" varchar, 
                "PCA_RSTATUS" varchar, 
                "PCA_STATUS" varchar, 
                "PCA_TIMING" varchar, 
                "PCA_UDFCHAR01" varchar, 
                "PCA_UDFCHAR02" varchar, 
                "PCA_UDFCHAR03" varchar, 
                "PCA_UDFCHAR04" varchar, 
                "PCA_UDFCHAR05" varchar, 
                "PCA_UDFCHAR06" varchar, 
                "PCA_UDFCHAR07" varchar, 
                "PCA_UDFCHAR08" varchar, 
                "PCA_UDFCHAR09" varchar, 
                "PCA_UDFCHAR10" varchar, 
                "PCA_UDFCHAR11" varchar, 
                "PCA_UDFCHAR12" varchar, 
                "PCA_UDFCHAR13" varchar, 
                "PCA_UDFCHAR14" varchar, 
                "PCA_UDFCHAR15" varchar, 
                "PCA_UDFCHAR16" varchar, 
                "PCA_UDFCHAR17" varchar, 
                "PCA_UDFCHAR18" varchar, 
                "PCA_UDFCHAR19" varchar, 
                "PCA_UDFCHAR20" varchar, 
                "PCA_UDFCHAR21" varchar, 
                "PCA_UDFCHAR22" varchar, 
                "PCA_UDFCHAR23" varchar, 
                "PCA_UDFCHAR24" varchar, 
                "PCA_UDFCHAR25" varchar, 
                "PCA_UDFCHAR26" varchar, 
                "PCA_UDFCHAR27" varchar, 
                "PCA_UDFCHAR28" varchar, 
                "PCA_UDFCHAR29" varchar, 
                "PCA_UDFCHAR30" varchar, 
                "PCA_UDFCHKBOX01" varchar, 
                "PCA_UDFCHKBOX02" varchar, 
                "PCA_UDFCHKBOX03" varchar, 
                "PCA_UDFCHKBOX04" varchar, 
                "PCA_UDFCHKBOX05" varchar, 
                "PCA_UDFDATE01" datetime, 
                "PCA_UDFDATE02" datetime, 
                "PCA_UDFDATE03" datetime, 
                "PCA_UDFDATE04" datetime, 
                "PCA_UDFDATE05" datetime, 
                "PCA_UDFNUM01" numeric(38, 10), 
                "PCA_UDFNUM02" numeric(38, 10), 
                "PCA_UDFNUM03" numeric(38, 10), 
                "PCA_UDFNUM04" numeric(38, 10), 
                "PCA_UDFNUM05" numeric(38, 10), 
                "PCA_UPDATECOUNT" numeric(38, 10), 
                "PCA_UPDATED" datetime, 
                "PCA_UPDATEDBY" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 