CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5TASKS_DELETED(
                "TSK_ACTIVECHECKLIST" varchar, 
                "TSK_ASMLEVEL" varchar, 
                "TSK_BUYER" varchar, 
                "TSK_CASEMANAGEMENTCHECKLIST" varchar, 
                "TSK_CHECKLISTPERFBYREQ" varchar, 
                "TSK_CHECKLISTREJECTEDWOSTATUS" varchar, 
                "TSK_CHECKLISTREVBYREQ" varchar, 
                "TSK_CLASS" varchar, 
                "TSK_CLASS_ORG" varchar, 
                "TSK_CODE" varchar, 
                "TSK_COMMODITY" varchar, 
                "TSK_COMPLEVEL" varchar, 
                "TSK_COMPLOCATION" varchar, 
                "TSK_CREATED" datetime, 
                "TSK_DEFAULTTAG" varchar, 
                "TSK_DESC" varchar, 
                "TSK_DISCONNECTED_CHKLIST" varchar, 
                "TSK_ENABLEENHANCEDPLANNING" varchar, 
                "TSK_HOURS" numeric(38, 10), 
                "TSK_ISOLATIONMETHOD" varchar, 
                "TSK_JOBPLAN" varchar, 
                "TSK_JOBPLANTYPE" varchar, 
                "TSK_LASTSAVED" datetime, 
                "TSK_MANUFACT" varchar, 
                "TSK_MATLIST" varchar, 
                "TSK_MULTIPLETRADES" varchar, 
                "TSK_NONCONFORMITYCHECKLIST" varchar, 
                "TSK_NOTUSED" varchar, 
                "TSK_OBJCLASS" varchar, 
                "TSK_OBJCLASS_ORG" varchar, 
                "TSK_OBJTYPE" varchar, 
                "TSK_ORG" varchar, 
                "TSK_PERFORMBY2RESP" varchar, 
                "TSK_PERFORMBYRESP" varchar, 
                "TSK_PERFORMEDBYWOSTATUS" varchar, 
                "TSK_PERSONS" numeric(38, 10), 
                "TSK_PLANNINGLEVEL" varchar, 
                "TSK_PLANNINGRECORDSEXIST" varchar, 
                "TSK_PREFSUP" varchar, 
                "TSK_PREFSUP_ORG" varchar, 
                "TSK_PREVENTPERFORMEDBYSIGN" varchar, 
                "TSK_PREVENTREVIEWEDBYSIGN" varchar, 
                "TSK_PRICE" numeric(38, 10), 
                "TSK_REUSABLE" varchar, 
                "TSK_REVIEWEDBYWOSTATUS" varchar, 
                "TSK_REVIEWRESP" varchar, 
                "TSK_REVISION" numeric(38, 10), 
                "TSK_REVRSTATUS" varchar, 
                "TSK_REVSTATUS" varchar, 
                "TSK_RPC" varchar, 
                "TSK_SYSLEVEL" varchar, 
                "TSK_TAGHEADER" varchar, 
                "TSK_TAGLINE1" varchar, 
                "TSK_TAGLINE2" varchar, 
                "TSK_TAGLINE3" varchar, 
                "TSK_TAGLINE4" varchar, 
                "TSK_TPF" varchar, 
                "TSK_TRADE" varchar, 
                "TSK_TYPE" varchar, 
                "TSK_UDFCHAR01" varchar, 
                "TSK_UDFCHAR02" varchar, 
                "TSK_UDFCHAR03" varchar, 
                "TSK_UDFCHAR04" varchar, 
                "TSK_UDFCHAR05" varchar, 
                "TSK_UDFCHAR06" varchar, 
                "TSK_UDFCHAR07" varchar, 
                "TSK_UDFCHAR08" varchar, 
                "TSK_UDFCHAR09" varchar, 
                "TSK_UDFCHAR10" varchar, 
                "TSK_UDFCHAR11" varchar, 
                "TSK_UDFCHAR12" varchar, 
                "TSK_UDFCHAR13" varchar, 
                "TSK_UDFCHAR14" varchar, 
                "TSK_UDFCHAR15" varchar, 
                "TSK_UDFCHAR16" varchar, 
                "TSK_UDFCHAR17" varchar, 
                "TSK_UDFCHAR18" varchar, 
                "TSK_UDFCHAR19" varchar, 
                "TSK_UDFCHAR20" varchar, 
                "TSK_UDFCHAR21" varchar, 
                "TSK_UDFCHAR22" varchar, 
                "TSK_UDFCHAR23" varchar, 
                "TSK_UDFCHAR24" varchar, 
                "TSK_UDFCHAR25" varchar, 
                "TSK_UDFCHAR26" varchar, 
                "TSK_UDFCHAR27" varchar, 
                "TSK_UDFCHAR28" varchar, 
                "TSK_UDFCHAR29" varchar, 
                "TSK_UDFCHAR30" varchar, 
                "TSK_UDFCHKBOX01" varchar, 
                "TSK_UDFCHKBOX02" varchar, 
                "TSK_UDFCHKBOX03" varchar, 
                "TSK_UDFCHKBOX04" varchar, 
                "TSK_UDFCHKBOX05" varchar, 
                "TSK_UDFDATE01" datetime, 
                "TSK_UDFDATE02" datetime, 
                "TSK_UDFDATE03" datetime, 
                "TSK_UDFDATE04" datetime, 
                "TSK_UDFDATE05" datetime, 
                "TSK_UDFNUM01" numeric(38, 10), 
                "TSK_UDFNUM02" numeric(38, 10), 
                "TSK_UDFNUM03" numeric(38, 10), 
                "TSK_UDFNUM04" numeric(38, 10), 
                "TSK_UDFNUM05" numeric(38, 10), 
                "TSK_UOM" varchar, 
                "TSK_UPDATECOUNT" numeric(38, 10), 
                "TSK_UPDATED" datetime, 
                "TSK_VIEWONLYRESP" varchar, 
                "TSK_WAP" varchar, 
                "TSK_WOCLASS" varchar, 
                "TSK_WOCLASS_ORG" varchar, 
                "TSK_WODESC" varchar, 
                "TSK_WOPRIORITY" varchar, 
                "TSK_WORKSPACEMOVES" varchar, 
                "TSK_WOSTATUS" varchar, 
                "TSK_WOTYPE" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 