CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5GRID_DELETED(
                "GRD_ACTIVE" varchar, 
                "GRD_BASEQUERY" varchar, 
                "GRD_BASEQUERY_MULTIORG" varchar, 
                "GRD_BOTFUNCTION" varchar, 
                "GRD_COMMITFLAG" varchar, 
                "GRD_COMPLEX" varchar, 
                "GRD_CUSTOMFIELDCODE" varchar, 
                "GRD_DESC" varchar, 
                "GRD_DISPLAYABLELIST" varchar, 
                "GRD_DISPLAYABLE_MULTIORG" varchar, 
                "GRD_DISTINCT" varchar, 
                "GRD_FILTERABLELIST" varchar, 
                "GRD_FILTERABLE_MULTIORG" varchar, 
                "GRD_GISDATAFILTER" varchar, 
                "GRD_GISWOFIELDMAP" varchar, 
                "GRD_GRIDID" numeric(38, 10), 
                "GRD_GRIDNAME" varchar, 
                "GRD_GRIDTYPE" numeric(38, 10), 
                "GRD_HINTS" varchar, 
                "GRD_KEYFIELDS" varchar, 
                "GRD_KEYFIELDS_MULTIORG" varchar, 
                "GRD_LASTSAVED" datetime, 
                "GRD_MAXGRIDCOST" numeric(38, 10), 
                "GRD_MOBILE" varchar, 
                "GRD_NOSCREENDESIGNER" varchar, 
                "GRD_OPTIMIZERON" varchar, 
                "GRD_ORGCOLNAME" varchar, 
                "GRD_PORTLETFLAG" varchar, 
                "GRD_SECENTITY" varchar, 
                "GRD_SORTABLELIST" varchar, 
                "GRD_SORTABLE_MULTIORG" varchar, 
                "GRD_TAB" varchar, 
                "GRD_UNITS" varchar, 
                "GRD_UPDATECOUNT" numeric(38, 10), 
                "GRD_UPDATED" datetime, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 