CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5DOCKRECEIPTS_DELETED(
                "DCK_CLASS" varchar, 
                "DCK_CLASS_ORG" varchar, 
                "DCK_CODE" varchar, 
                "DCK_CREATED" datetime, 
                "DCK_DESC" varchar, 
                "DCK_DOCKID" varchar, 
                "DCK_FREIGHT" varchar, 
                "DCK_LASTSAVED" datetime, 
                "DCK_LOCATION" varchar, 
                "DCK_MRC" varchar, 
                "DCK_ORDER" varchar, 
                "DCK_ORDER_ORG" varchar, 
                "DCK_ORG" varchar, 
                "DCK_PACKSLIP" varchar, 
                "DCK_RECEIVER" varchar, 
                "DCK_RECVDATE" datetime, 
                "DCK_REFERENCE" varchar, 
                "DCK_RETRIEVEALL" varchar, 
                "DCK_RSTATUS" varchar, 
                "DCK_SHIPVIA" varchar, 
                "DCK_STATUS" varchar, 
                "DCK_SUPPLIER" varchar, 
                "DCK_SUPPLIER_ORG" varchar, 
                "DCK_UPDATECOUNT" numeric(38, 10), 
                "DCK_UPDATED" datetime, 
                "DCK_UPDUSER" varchar, 
                "DCK_USER" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 