CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5ORDREVISIONS_DELETED(
                "ORR_ACD" numeric(38, 10), 
                "ORR_APPROV" datetime, 
                "ORR_ATTENTIONTO" varchar, 
                "ORR_AUTH" varchar, 
                "ORR_BLANKETORDER" varchar, 
                "ORR_BLANKETRELEASE" numeric(38, 10), 
                "ORR_BUYER" varchar, 
                "ORR_CLASS" varchar, 
                "ORR_CLASS_ORG" varchar, 
                "ORR_CONTRACT" varchar, 
                "ORR_CONTROLNO" varchar, 
                "ORR_CREATED" datetime, 
                "ORR_CREDITCARD" numeric(38, 10), 
                "ORR_CURR" varchar, 
                "ORR_DATE" datetime, 
                "ORR_DELADDRESS" varchar, 
                "ORR_DESC" varchar, 
                "ORR_DFLTAUTH" varchar, 
                "ORR_DISCOUNT" numeric(38, 10), 
                "ORR_DISCPERC" numeric(38, 10), 
                "ORR_DUE" datetime, 
                "ORR_EXCH" numeric(38, 10), 
                "ORR_EXCHFROMDUAL" numeric(38, 10), 
                "ORR_EXCHTODUAL" numeric(38, 10), 
                "ORR_FOBPOINT" varchar, 
                "ORR_FREIGHTTERMS" varchar, 
                "ORR_INTERFACE" datetime, 
                "ORR_IPTRANSMITTED" varchar, 
                "ORR_JECATEGORY" varchar, 
                "ORR_JESOURCE" varchar, 
                "ORR_LASTSAVED" datetime, 
                "ORR_LASTSTATUSUPDATE" datetime, 
                "ORR_MAILTOSITE" varchar, 
                "ORR_ORDER" varchar, 
                "ORR_ORDER_ORG" varchar, 
                "ORR_ORIGIN" varchar, 
                "ORR_PACKAGETRACKINGNUMBER" varchar, 
                "ORR_PAYBYMETHOD" varchar, 
                "ORR_PAYMENTTERMS" varchar, 
                "ORR_PRICE" numeric(38, 10), 
                "ORR_PRINTED" varchar, 
                "ORR_REVISED" datetime, 
                "ORR_REVISEDBY" varchar, 
                "ORR_REVISEDORDER" varchar, 
                "ORR_REVISION" numeric(38, 10), 
                "ORR_REVISIONREASON" varchar, 
                "ORR_RSTATUS" varchar, 
                "ORR_RTYPE" varchar, 
                "ORR_SHIPVIA" varchar, 
                "ORR_SOURCECODE" varchar, 
                "ORR_SOURCESYSTEM" varchar, 
                "ORR_STATUS" varchar, 
                "ORR_STORE" varchar, 
                "ORR_SUPPLIER" varchar, 
                "ORR_SUPPLIER_ORG" varchar, 
                "ORR_TYPE" varchar, 
                "ORR_UDFCHAR01" varchar, 
                "ORR_UDFCHAR02" varchar, 
                "ORR_UDFCHAR03" varchar, 
                "ORR_UDFCHAR04" varchar, 
                "ORR_UDFCHAR05" varchar, 
                "ORR_UDFCHAR06" varchar, 
                "ORR_UDFCHAR07" varchar, 
                "ORR_UDFCHAR08" varchar, 
                "ORR_UDFCHAR09" varchar, 
                "ORR_UDFCHAR10" varchar, 
                "ORR_UDFCHAR11" varchar, 
                "ORR_UDFCHAR12" varchar, 
                "ORR_UDFCHAR13" varchar, 
                "ORR_UDFCHAR14" varchar, 
                "ORR_UDFCHAR15" varchar, 
                "ORR_UDFCHAR16" varchar, 
                "ORR_UDFCHAR17" varchar, 
                "ORR_UDFCHAR18" varchar, 
                "ORR_UDFCHAR19" varchar, 
                "ORR_UDFCHAR20" varchar, 
                "ORR_UDFCHAR21" varchar, 
                "ORR_UDFCHAR22" varchar, 
                "ORR_UDFCHAR23" varchar, 
                "ORR_UDFCHAR24" varchar, 
                "ORR_UDFCHAR25" varchar, 
                "ORR_UDFCHAR26" varchar, 
                "ORR_UDFCHAR27" varchar, 
                "ORR_UDFCHAR28" varchar, 
                "ORR_UDFCHAR29" varchar, 
                "ORR_UDFCHAR30" varchar, 
                "ORR_UDFCHKBOX01" varchar, 
                "ORR_UDFCHKBOX02" varchar, 
                "ORR_UDFCHKBOX03" varchar, 
                "ORR_UDFCHKBOX04" varchar, 
                "ORR_UDFCHKBOX05" varchar, 
                "ORR_UDFDATE01" datetime, 
                "ORR_UDFDATE02" datetime, 
                "ORR_UDFDATE03" datetime, 
                "ORR_UDFDATE04" datetime, 
                "ORR_UDFDATE05" datetime, 
                "ORR_UDFNUM01" numeric(38, 10), 
                "ORR_UDFNUM02" numeric(38, 10), 
                "ORR_UDFNUM03" numeric(38, 10), 
                "ORR_UDFNUM04" numeric(38, 10), 
                "ORR_UDFNUM05" numeric(38, 10), 
                "ORR_UPDATECOUNT" numeric(38, 10), 
                "ORR_UPDATED" datetime, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 