CREATE OR REPLACE TABLE TARGET_HISTORY_EAM.EAM_R5UCODES_DELETED(
                "UCO_CATEGORY" varchar, 
                "UCO_CODE" varchar, 
                "UCO_COLOR" varchar, 
                "UCO_CREATED" datetime, 
                "UCO_DESC" varchar, 
                "UCO_ENTITY" varchar, 
                "UCO_GISDISPATCHRANKING" numeric(38, 10), 
                "UCO_ICON" varchar, 
                "UCO_ICONPATH" varchar, 
                "UCO_LASTSAVED" datetime, 
                "UCO_NOTUSED" varchar, 
                "UCO_RCODE" varchar, 
                "UCO_RENTITY" varchar, 
                "UCO_SYSTEM" varchar, 
                "UCO_TEXTCODE" varchar, 
                "UCO_UPDATECOUNT" numeric(38, 10), 
                "UCO_UPDATED" datetime, 
                "UCO_WEIGHT" numeric(38, 10), 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar,
                ETL_IS_DELETED boolean default false
                ); 