CREATE OR REPLACE TASK DATAHUB_LOGGING.TASK_COPY_HISTORY
    SCHEDULE = 'USING CRON 30 8 * * * Pacific/Auckland'
    error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
AS
    CALL DATAHUB_LOGGING.SP_COPY_HISTORY();