CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_ACCOUNTACTIVITY(
            ACCOUNTKEY integer, 
            ACCOUNTSERVICEKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADJUSTMENTKEY integer, 
            APPFEEKEY integer, 
            BILLKEY integer, 
            DATALAKE_DELETED boolean, 
            DEPOSITADJUSTMENTKEY integer, 
            DEPOSITCHARGEKEY integer, 
            LINEITEMKEY integer, 
            LINEITEMSETUPKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            ONEOFFCHARGEKEY integer, 
            PAYMENTKEY integer, 
            PENALTYKEY integer, 
            REFUNDKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 