CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_ASSETMANAGEMENT_WATER_METERREADING(
            ADDBY varchar, 
            ADDDTTM datetime, 
            AUDITFLAG varchar, 
            BLUSAGE numeric(38, 10), 
            BLUSAGECUBICFT numeric(38, 10), 
            COMPKEY integer, 
            CORRFLAG varchar, 
            CUSTPROB integer, 
            CYCLE varchar, 
            DELETED boolean, 
            ESTMFLAG varchar, 
            FIELDNOTES varchar, 
            FINALFLAG varchar, 
            GRPPROJ integer, 
            HIGHBLUSAGE numeric(38, 10), 
            HIGHBLUSAGEINCUBICFEET numeric(38, 10), 
            HIGHREADING numeric(38, 10), 
            HIGHUSAGE numeric(38, 10), 
            HISTKEY integer, 
            INITFLAG varchar, 
            INSPKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NOREADFLAG varchar, 
            PROBBCODEWO integer, 
            PROBCODESRVREQNO integer, 
            PROBLEMCODE varchar, 
            RDRCODESRVREQNO integer, 
            READBY varchar, 
            READDTTM datetime, 
            READERCODE varchar, 
            READERCODEWO integer, 
            READING numeric(38, 10), 
            READINGKEY integer, 
            READREAS varchar, 
            READSRC varchar, 
            READVAL1 varchar, 
            READVAL2 varchar, 
            READVAL3 varchar, 
            READVAL4 varchar, 
            READYFLAG varchar, 
            USAGE numeric(38, 10), 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 