CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALMOVEMENT(
            ACCUMDEPRECPE numeric(38, 10), 
            ACCUMDEPRECPS numeric(38, 10), 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSVALKEY integer, 
            ASSVALMOVEMENTKEY integer, 
            CAPTCOSTCP numeric(38, 10), 
            CURRENTCOSTPE numeric(38, 10), 
            CURRENTCOSTPS numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            DEPRECCP numeric(38, 10), 
            DISPDEPRECWRTNBCKCP numeric(38, 10), 
            DISPOSALSCD numeric(38, 10), 
            EFFECTIVEDTTM datetime, 
            IMPVALPRIORTOREVALPE numeric(38, 10), 
            INITCOSTCP numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            PLONSALECP numeric(38, 10), 
            PROCONDISPCP numeric(38, 10), 
            REVALACCUMDEPRECBGHTTOACCTCP numeric(38, 10), 
            REVALACCUMDEPRECWRTNBCKGROSSCP numeric(38, 10), 
            REVALACCUMDEPRECWRTNBCKNETCP numeric(38, 10), 
            REVALINCDEC numeric(38, 10), 
            VARIATION_ID integer, 
            WDVPE numeric(38, 10), 
            WDVPS numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 