CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_DIRECTDEBITSETUP(
            ACHFORMATFILE varchar, 
            ACHOUTPUTDIRECTORY varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            COMBINEAMOUNT varchar, 
            DATALAKE_DELETED boolean, 
            DIRECTDEBITAMTCRITERIA varchar, 
            DIRECTDEBITCYCLE1DAY integer, 
            DIRECTDEBITCYCLE2DAY integer, 
            DIRECTDEBITCYCLE3DAY integer, 
            DIRECTDEBITCYCLE4DAY integer, 
            DIRECTDEBITCYCLENUMBER integer, 
            DIRECTDEBITSETUPKEY integer, 
            ENABLEOTHERFLAG varchar, 
            FREQUENCYDAYS varchar, 
            FREQUENCYMONTHS varchar, 
            FREQUENCYWEEKS varchar, 
            INCLUDEUNBILLED varchar, 
            MAXIMUMAMOUNT numeric(38, 10), 
            MAXIMUMSUSPENSIONDAY integer, 
            MAXIMUMSUSPENSIONNUMBER integer, 
            MINIMUMAMOUNT numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            PRENOTE varchar, 
            PRENOTEEXTRACTDATEDAYS integer, 
            PRENOTENUMBEROFDAYS integer, 
            REFBALTHRUEXTRDATE varchar, 
            REFRESHEXTRACTAMOUNT varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 