CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLCRM_XMETERREVIEWDP(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPROVALDATE datetime, 
            CHECKREADISCHARGEABLE varchar, 
            COMMENTS varchar, 
            DELETED boolean, 
            ISCHECKREADREQUEST varchar, 
            ISREADAPPROVED varchar, 
            ISREADNOACTION varchar, 
            ISREADREJECTED varchar, 
            MARKASANOMALY varchar, 
            MARKASNOREAD varchar, 
            MARKASREADYTOBILL varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PHOTOREQUIRED varchar, 
            REASSIGNTO varchar, 
            REJECTEDDATE datetime, 
            SERVNO integer, 
            VARIATION_ID integer, 
            XMETERREVIEWDPKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 