CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_METERMANAGEMENT_WATER_READINGIMPORTSETUP(
            ADDBY varchar, 
            ADDDTTM datetime, 
            DELETED boolean, 
            FORCEEXPORTSELECTIONFLAG varchar, 
            IMPEXPDAYS integer, 
            IMPORTDIRPATH varchar, 
            IMPORTFILETEMPLATE varchar, 
            IMPORTRUNNUMBER integer, 
            IMPORTTYPE integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            PROCESSREADYTOBILLFLAG varchar, 
            READINGIMPORTSETUPKEY integer, 
            RECEIVERCODE varchar, 
            REJECTNONEXROUTE varchar, 
            REJECTPRIORMETERREAD varchar, 
            RESOLVESRFLAG varchar, 
            SENDERCODE varchar, 
            SHOWFILEOPENDIALOGFLAG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 