CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSDEPRE(
            ACCDEPREC numeric(38, 10), 
            ACCPERIOD integer, 
            ACQDATE datetime, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSVALDATE datetime, 
            ASSVALKEY integer, 
            ASSVALRUNKEY integer, 
            BACKDATEADJFLAG varchar, 
            BGTKEY integer, 
            BGTNO varchar, 
            CAPTLEXP numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            DEPRECAMT numeric(38, 10), 
            DEPRECDATE datetime, 
            DEPRECKEY integer, 
            DEPRECPERD numeric(38, 10), 
            DEPRECRATE numeric(38, 10), 
            DEPRECTYPE integer, 
            DEPRECYTD numeric(38, 10), 
            DISPSLFLAG varchar, 
            EFFECTIVEDTTM datetime, 
            EXPLIFE numeric(38, 10), 
            JOURNALDATE datetime, 
            MODBY varchar, 
            MODDTTM datetime, 
            PERIODADJDEPREC numeric(38, 10), 
            RECLDEPKEY integer, 
            RECLNO integer, 
            RESIDLIFE numeric(38, 10), 
            RESIDVAL numeric(38, 10), 
            REVALFINALCOST numeric(38, 10), 
            REVALFLAG varchar, 
            TOBESOLDFLAG varchar, 
            VARIATION_ID integer, 
            WRITEDNVAL numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 