CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_LINEITEMRATE(
            ACCOUNTKEY integer, 
            ACCOUNTSERVICEKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESSSERVICEKEY integer, 
            BILLRUNKEY integer, 
            CALCULATIONDETAILKEY integer, 
            DATALAKE_DELETED boolean, 
            DEPOSITCHARGEKEY integer, 
            FIXEDCHGCHARGEDAYS integer, 
            FIXEDCHGFROMDATE datetime, 
            FIXEDCHGNUMBERPERIODS integer, 
            FIXEDCHGPERIODDAYS integer, 
            FIXEDCHGPERIODSINYEAR integer, 
            FIXEDCHGRATEPERPERIOD numeric(38, 10), 
            FIXEDCHGTODATE datetime, 
            LINEITEMKEY integer, 
            LINEITEMRATEKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            ONEOFFCHARGEKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 