CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_PLANNING_PLANPLCONDSTATUS(
            ACCESSID integer, 
            ACTIVE varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLANPLCONDSTATUSKEY integer, 
            CODE varchar, 
            CONDMET varchar, 
            CONDTEXTEDITABLE varchar, 
            DEFERREDMILESTONE varchar, 
            DELETED boolean, 
            EFFDATE datetime, 
            EXCLUDEFROMINHERITANCE varchar, 
            EXPDATE datetime, 
            IGNOREORDERONBLDG varchar, 
            MARKASDELETED varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 