CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_USE_USECONDTYPE(
            ADDBY varchar, 
            ADDCONDFRMLA integer, 
            ADDDTTM datetime, 
            ALERTFLAG varchar, 
            APUSECONDTYPEKEY integer, 
            APUSEDEFNKEY integer, 
            APUSEPROCESSSTATEKEY integer, 
            CONDTYPE varchar, 
            DELETED boolean, 
            DESCRIPT varchar, 
            DPDESC varchar, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            INTERNALONLYFLAG varchar, 
            ISPUBLIC varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PORTALDESCRIPTION varchar, 
            PRECHECK varchar, 
            SHOWINPORTAL varchar, 
            SUPREQD varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 