CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_ACCTNOGENSEG(
            ACCTNOGENSEGKEY integer, 
            ACCTNOGENSETUPKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BUSOBJMON varchar, 
            COUNTOWNERSEPARATEFLAG varchar, 
            CURRENTVALUE integer, 
            CUSTOMVALUE varchar, 
            DATALAKE_DELETED boolean, 
            DISPLAYOWNERAS integer, 
            DISPLAYOWNERASFLAG varchar, 
            LEADINGZEROFLAG varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NODIGITS integer, 
            OWNERINDICATOR varchar, 
            SEGMENTNUMBER integer, 
            SEGMENTTYPE varchar, 
            SEPARATOR varchar, 
            STARTAT integer, 
            TENANTINDICATOR varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 