CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_PLANNING_PLANHEARING(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLICATIONKEY integer, 
            COMMENTS varchar, 
            COMPDTTM datetime, 
            COMPFLAG varchar, 
            DELETED boolean, 
            DOCKETNUM varchar, 
            HEARTYPEKEY integer, 
            LOCATION varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NAME varchar, 
            PLANHEARKEY integer, 
            RECORDBY varchar, 
            RESULT varchar, 
            SCHEDBY varchar, 
            SCHEDDTTM datetime, 
            SCHEDFLAG varchar, 
            STARTDTTM datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 