CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_USE_USEINSPDETAILTYPE(
            ACCESSID integer, 
            ADDBY varchar, 
            ADDCONDFRMLA integer, 
            ADDDTTM datetime, 
            APUSEINSPDTLTYPEKEY integer, 
            APUSEINSPTYPEKEY integer, 
            CLASSNAME varchar, 
            DELETED boolean, 
            DESCRIPT varchar, 
            DISPLAY integer, 
            DISPLAYORDER integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            MODBY varchar, 
            MODDTTM datetime, 
            PAGEPATH varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 