CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_BILLING_PAYMENTARRANGMENT(
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ALLOWWARNED varchar, 
            ARRANGEDAMOUNTLTD numeric(38, 10), 
            ARRANGEDBY varchar, 
            ARRANGEDDTTM datetime, 
            ARRANGEDPAYMENTAMT numeric(38, 10), 
            ARRANGEDTOTALAMT numeric(38, 10), 
            ARRANGEDVSBILLEDPERCENT integer, 
            ARRANGEMENTBALANCE numeric(38, 10), 
            ARRANGEMENTCATEGORY varchar, 
            ARRANGEMENTSTATUS varchar, 
            ARRANGEMENTTEMPLATEKEY integer, 
            ARRANGEMENTTYPE varchar, 
            BILLEDAMOUNTLTD numeric(38, 10), 
            DELETED boolean, 
            DELINQUENTBALANCE numeric(38, 10), 
            DOWNPAYMENTAMT numeric(38, 10), 
            DOWNPAYMENTDUEDTTM datetime, 
            ENDDTTM datetime, 
            FREQUENCY varchar, 
            GUARANTORKEY integer, 
            INCLUDECURRENTFLAG varchar, 
            INCLUDEDEPOSITFLAG varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NUMBEROFPAYMENTS integer, 
            PARENTARRANGEMENTKEY integer, 
            PAYMENTARRANGMENTKEY integer, 
            PAYMENTSAVERAGEDFLAG varchar, 
            PAYMTSONLYEXCEPTFLAG varchar, 
            PAYOLDESTFIRSTFLAG varchar, 
            SENDNOTICESFLAG varchar, 
            STARTDTTM datetime, 
            STATUSDTTM datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 