CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CASHIERING_REGISTERGROUPSETUP(
            ACCESSID integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BMPFILE varchar, 
            CASHLIMITAMT numeric(38, 10), 
            CASHSETUP integer, 
            CHECKSETUP integer, 
            CREDITSETUP integer, 
            DEBITSETUP integer, 
            DELETED boolean, 
            DESCRIPTION varchar, 
            ENDORSE varchar, 
            ESCROWSETUP integer, 
            MISCSETUP integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            RCPTFTR varchar, 
            RCPTHDR varchar, 
            RCPTOMITTX varchar, 
            REGISTERGROUP varchar, 
            REGISTERGROUPSETUPKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 