CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLCRM_XMETERREVIEWGD(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSET integer, 
            COMPAREOPTION integer, 
            COMPAREREASON varchar, 
            COMPAREUSAGE numeric(38, 10), 
            CURRENTBILLABLE numeric(38, 10), 
            CURRENTREAD numeric(38, 10), 
            CURRENTREADDATE datetime, 
            DAILYAVERAGE numeric(38, 10), 
            DELETED boolean, 
            EXCEPTION varchar, 
            FIELDNOTES varchar, 
            HIGH numeric(38, 10), 
            LASTYEARDAILYAVG numeric(38, 10), 
            LASTYEARREAD numeric(38, 10), 
            LOW numeric(38, 10), 
            MODBY varchar, 
            MODDTTM datetime, 
            PREVIOUSREAD numeric(38, 10), 
            READERCODE varchar, 
            READINGCYCLE varchar, 
            READINGIMPORTACTIVITY integer, 
            READINGKEY integer, 
            VARIATION_ID integer, 
            XMETERREVIEWDP integer, 
            XMETERREVIEWGDKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 