CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_USE_USEPROCESSSTATE(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLEXPDATECALCREQD varchar, 
            APUSEDEFNKEY integer, 
            APUSEPROCESSSTATEKEY integer, 
            CODE varchar, 
            COMPLETEDSTATEFLAG varchar, 
            DELETED boolean, 
            DISPLAYORDER integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            INITIALSTATEFLAG varchar, 
            ISPUBLIC varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NEXTSTATEFRMLA integer, 
            NEXTSTATEKEY integer, 
            SETSTATDATE varchar, 
            STAT varchar, 
            STATDATETYPE integer, 
            USEAPPLSTATUS varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 