CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CDR_USE_USEAPPLDETAILTYPE(
            ACCESSID integer, 
            ADDBY varchar, 
            ADDCONDFRMLA integer, 
            ADDDTTM datetime, 
            APUSEAPPLDTLTYPEKEY integer, 
            APUSEDEFNKEY integer, 
            APUSEPROCESSSTATEKEY integer, 
            CLASSNAME varchar, 
            DELETED boolean, 
            DESCRIPT varchar, 
            DISPLAY integer, 
            DISPLAYORDER integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            MODBY varchar, 
            MODDTTM datetime, 
            PAGEPATH varchar, 
            PORTALDETAILPAGEAREA integer, 
            PORTALDETAILPAGEPLACEMENT integer, 
            STARTAPPLFLAG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 