CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_METERMANAGEMENT_WATER_WATERMETERANALYSIS(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESS varchar, 
            ADDRESSKEY integer, 
            ADDRESSKEY1 integer, 
            APPROVE varchar, 
            AUDITFLAG varchar, 
            BATCHKEY integer, 
            COLORASSIGNMENTNEEDED varchar, 
            COMPAREBILLABLE numeric(38, 10), 
            COMPAREESTIMATEDFLAG varchar, 
            COMPAREHIGHBILLABLE numeric(38, 10), 
            COMPAREHIGHREADING numeric(38, 10), 
            COMPAREHIGHUSAGE numeric(38, 10), 
            COMPAREOPTION integer, 
            COMPAREREADING numeric(38, 10), 
            COMPAREREADINGDATE datetime, 
            COMPAREREADINGKEY integer, 
            COMPARETOTALBILLABLEUSAGE numeric(38, 10), 
            COMPARETOTALUSAGE numeric(38, 10), 
            COMPAREUSAGE numeric(38, 10), 
            COMPAREUSAGEREADINGKEYS varchar, 
            CURRENTBILLABLE numeric(38, 10), 
            CURRENTCOMPKEY integer, 
            CURRENTESTIMATEDFLAG varchar, 
            CURRENTFIELDNOTES varchar, 
            CURRENTHIGHBILLABLE numeric(38, 10), 
            CURRENTHIGHREADING numeric(38, 10), 
            CURRENTHIGHUSAGE numeric(38, 10), 
            CURRENTMETERID varchar, 
            CURRENTREADING numeric(38, 10), 
            CURRENTREADINGDATE datetime, 
            CURRENTREADINGKEY integer, 
            CURRENTTOTALBILLABLEUSAGE numeric(38, 10), 
            CURRENTTOTALUSAGE numeric(38, 10), 
            CURRENTUNITTYPE varchar, 
            CURRENTUSAGE numeric(38, 10), 
            CURRENTUSAGEREADINGKEYS varchar, 
            DATALAKE_DELETED boolean, 
            DEFAULTACTION varchar, 
            EXCEPTION varchar, 
            EXCEPTIONTYPE integer, 
            HIGHMULTIPLIER numeric(38, 10), 
            INDEXNO integer, 
            ISPBCODESRVREQRESOLVED varchar, 
            ISPBCODEWORESOLVED varchar, 
            ISPROBLEMCODEEXCEPTION varchar, 
            ISRDCODESRVREQRESOLVED varchar, 
            ISRDCODEWORESOLVED varchar, 
            ISREADERCODEEXCEPTION varchar, 
            ISREADINGAPPROVED varchar, 
            ISREREADRESOLVED varchar, 
            KEYCOLUMN varchar, 
            LOWMULTIPLIER numeric(38, 10), 
            MANUALREVIEWFLAG varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NOREADFLAG varchar, 
            OLDESTACCOUNTKEY integer, 
            OLDESTACCOUNTNO varchar, 
            OTHERACTION varchar, 
            PARENTKEY integer, 
            POSITION integer, 
            PROBLEMCODE varchar, 
            PROBLEMCODEBACKCOLOR varchar, 
            PROBLEMCODESERVICEREQUESTNO integer, 
            PROBLEMCODESERVICEREQUESTTYPE varchar, 
            PROBLEMCODETEXTCOLOR varchar, 
            PROBLEMCODEWORKORDERNO integer, 
            PROBLEMCODEWORKORDERTYPE varchar, 
            READERCODE varchar, 
            READERCODEBACKCOLOR varchar, 
            READERCODESERVICEREQUESTNO integer, 
            READERCODESERVICEREQUESTTYPE varchar, 
            READERCODETEXTCOLOR varchar, 
            READERCODEWORKORDERNO integer, 
            READERCODEWORKORDERTYPE varchar, 
            READINGCOMPKEY integer, 
            READINGCYCLE varchar, 
            READINGMETERID varchar, 
            READINGTYPE integer, 
            READINGUNITTYPE varchar, 
            REREAD varchar, 
            REREADSERVICEREQUESTNO integer, 
            ROUTEID varchar, 
            ROUTEKEY integer, 
            SEQUENCENO integer, 
            SERREQ varchar, 
            USAGEPERCENTAGE numeric(38, 10), 
            VARIATION_ID integer, 
            WATERMETERANALYSISKEY integer, 
            WORKORDER varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 