CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_WSLASSETSCONFIGURED_XCHAMBER(
            ACCELDEPREC varchar, 
            ACCELDEPRECDESC varchar, 
            ACQTYPE varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BOLTDOWN varchar, 
            BUSINESSAREA varchar, 
            COMPKEY integer, 
            CONFINEDSPACE varchar, 
            COSTCENTRE varchar, 
            COVERTYPE varchar, 
            CRITICALITY varchar, 
            DATALAKE_DELETED boolean, 
            DESIGNRESILIENCE varchar, 
            DIAMEXT numeric(38, 10), 
            DIAMINT numeric(38, 10), 
            DISPOSALDESC varchar, 
            DRAWINGNO varchar, 
            DRAWINGNOREF varchar, 
            DROPMH varchar, 
            FALLPROTECT varchar, 
            FORDISPOSAL varchar, 
            FUNCAREA varchar, 
            GRDLEVEL numeric(38, 10), 
            HINGED varchar, 
            INTLINING varchar, 
            INVLEVEL numeric(38, 10), 
            LIDLEVEL numeric(38, 10), 
            LINKEDASSET varchar, 
            LOADRATING numeric(38, 10), 
            LOCALITY varchar, 
            LOCKABLE varchar, 
            MAKE varchar, 
            MEDIATYPE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            OVERFLOWTYPE varchar, 
            PHOTO3D varchar, 
            PROJECTNO varchar, 
            PROJECTWISE varchar, 
            QUAKEDESIGN varchar, 
            RELDATE varchar, 
            RELDEPTH varchar, 
            RELDIA varchar, 
            RELGEOSP varchar, 
            RELMATL varchar, 
            RELOWN varchar, 
            RELSTATUS varchar, 
            REMOVABLE varchar, 
            SAFETYCRITICAL varchar, 
            SUBTYPEFEATURES varchar, 
            VARIATION_ID integer, 
            WARRANTYEND datetime, 
            WARRANTYSTART datetime, 
            XCHAMBERKEY integer, 
            ZONECATCHMENT varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 