CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_CASHIERING_DRAWERGENERATION(
            ADDBY varchar, 
            ADDDTTM datetime, 
            AUTOPOST varchar, 
            BATCHDESC varchar, 
            BATCHGROUP varchar, 
            BATCHSTAT varchar, 
            CASHIER varchar, 
            CASHINAMT numeric(38, 10), 
            CASHLIMITAMT numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            DEFAULTREGISTERGROUPKEY integer, 
            DRWRGENKEY integer, 
            DRWRSTAT varchar, 
            DRWRTYPE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            OBGTNO integer, 
            REGKEY integer, 
            SBGTNO integer, 
            SRC varchar, 
            STARTTM datetime, 
            STOPTM datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 