CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_RESOURCES_RATETABLE_CALCULATIONTABLE(
            ADDBY varchar, 
            ADDDTTM datetime, 
            CALCULATIONTABLEKEY integer, 
            CYCLEDAYS integer, 
            DELETED boolean, 
            FORMULAINPUT numeric(38, 10), 
            FORMULALAST varchar, 
            FORMULANAME varchar, 
            FORMULAOUTPUT numeric(38, 10), 
            FORMULAUSED varchar, 
            MAXIMUMCHARGE numeric(38, 10), 
            MAXIMUMUSED varchar, 
            MINIMUMCHARGE numeric(38, 10), 
            MINIMUMUSED varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PRORATED varchar, 
            RATETABLESETUPKEY integer, 
            USAGEDAYS integer, 
            USEFORPRORATING integer, 
            USEOVERAGE varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 