CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_RESOURCES_JOURNALSUMMARY(
            ACCOUNTINGPERIOD integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            AMOUNT numeric(38, 10), 
            CREDITBUDGETNUMBER integer, 
            DEBITBUDGETNUMBER integer, 
            DELETED boolean, 
            FISCALYEAR integer, 
            FROMDATETIME datetime, 
            JOURNALSUMMARYKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            TODATETIME datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 