CREATE OR REPLACE TABLE DATAHUB_TARGET.IPS_ASSETMANAGEMENT_WATER_COMPHY(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            AUXVALVE varchar, 
            BARRELSIZE numeric(38, 10), 
            BARRELSIZEUOM varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            COLOR varchar, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            DATALAKE_DELETED boolean, 
            DISTRICT varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            FEEDERDIAM numeric(38, 10), 
            FEEDERDIAMUOM varchar, 
            FEEDERLEN numeric(38, 10), 
            FEEDERLENUOM varchar, 
            FEEDERTYPE varchar, 
            GISSTATIC integer, 
            HT numeric(38, 10), 
            HTUOM varchar, 
            INSTDATE datetime, 
            INTKEY integer, 
            LOC varchar, 
            MAINKEY integer, 
            MAPNO varchar, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            OBST varchar, 
            OUTLSZ1 numeric(38, 10), 
            OUTLSZ1UOM varchar, 
            OUTLSZ2 numeric(38, 10), 
            OUTLSZ3 numeric(38, 10), 
            OUTLSZ4 numeric(38, 10), 
            OWN varchar, 
            PACKING varchar, 
            PAINTTYPE varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PRESZONE varchar, 
            SEGKEY integer, 
            SERNO varchar, 
            SERVSTAT varchar, 
            SITEKEY integer, 
            SLKEY integer, 
            SUBAREA varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            VARIATION_ID integer, 
            WVKEY integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 