SELECT REPLACE(TABLE_SCHEMA, 'TARGET_', '') AS "SOURCE",
    MIN(:datebucket(TO_DATE(CREATED))) as "DATE",
    1 AS "COUNT"
FROM WATERLAKE_${var.ENVIRONMENT}.INFORMATION_SCHEMA.TABLES T
WHERE TABLE_TYPE = 'BASE TABLE' 
    AND TABLE_SCHEMA LIKE 'TARGET_%' 
    AND TABLE_SCHEMA NOT LIKE '%HISTORY%'
    AND SOURCE = :source_system
    AND TO_DATE(CREATED) = :daterange
GROUP BY REPLACE(TABLE_SCHEMA, 'TARGET_', '')
UNION ALL
SELECT CASE WHEN TABLE_SCHEMA = 'DATAHUB_TARGET' THEN 'IPS' ELSE REPLACE(TABLE_SCHEMA, 'TARGET_', '') END AS "SOURCE",
    MIN(:datebucket(TO_DATE(CREATED))) as "DATE",    
    1 AS "COUNT"
FROM ${var.ENVIRONMENT}_WCC_DATAWAREHOUSE.INFORMATION_SCHEMA.TABLES T
WHERE TABLE_TYPE = 'BASE TABLE' 
    AND (TABLE_SCHEMA = 'DATAHUB_TARGET' OR TABLE_SCHEMA LIKE 'TARGET_%') 
    AND TABLE_SCHEMA NOT LIKE '%HISTORY%'
    AND SOURCE = :source_system
    AND TO_DATE(CREATED) = :daterange
GROUP BY CASE WHEN TABLE_SCHEMA = 'DATAHUB_TARGET' THEN 'IPS' ELSE REPLACE(TABLE_SCHEMA, 'TARGET_', '') END
