create or replace procedure DATAHUB_INTEGRATION.SP_IPS_CDR_PLANNING_PLANAPPL()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_CDR_PLANNING_PLANAPPL_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_CDR_PLANNING_PLANAPPL as target using (SELECT * FROM (SELECT 
            strm.ACTLVLTN, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.APBY, 
            strm.APDTTM, 
            strm.APKEY, 
            strm.APNO, 
            strm.APPLANDEFNKEY, 
            strm.APPLANKEY, 
            strm.APPLANPROCESSSTATEKEY, 
            strm.APRVBY, 
            strm.APRVDTTM, 
            strm.AREAUM, 
            strm.BILLGRP, 
            strm.BLDGAREA, 
            strm.BLDGFLOOR, 
            strm.BLDGROOM, 
            strm.CALCVLTN, 
            strm.CAPACITY, 
            strm.COMPKEY, 
            strm.COMPVAL, 
            strm.COOBY, 
            strm.COODTTM, 
            strm.DATALAKE_DELETED, 
            strm.DECLVLTN, 
            strm.EXPDTTM, 
            strm.FINBY, 
            strm.FINDTTM, 
            strm.GROUPKEY, 
            strm.LINEARFROMFT, 
            strm.LINEARFROMM, 
            strm.LINEARTOFT, 
            strm.LINEARTOM, 
            strm.LOC, 
            strm.LOCNOTES, 
            strm.LSTACTDTTM, 
            strm.LSTPRNDTTM, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.NOPAGES, 
            strm.NOPLANS, 
            strm.OCCUPANCYTYPE, 
            strm.PHASENO, 
            strm.PLANAPPLSTATUS, 
            strm.PLANREV, 
            strm.PRCLKEY, 
            strm.PRI, 
            strm.PROJNAME, 
            strm.PROPKEY, 
            strm.PROPOCCUPKEY, 
            strm.PRPSTOPDT, 
            strm.PRPSTRTDT, 
            strm.STAT, 
            strm.STATBY, 
            strm.STATDTTM, 
            strm.STATREAS, 
            strm.SUBDIVCODE, 
            strm.SZDESC, 
            strm.TMPCOOBY, 
            strm.TMPCOODTTM, 
            strm.VARIATION_ID, 
            strm.WORKTYPE, 
            strm.XCOORDINATE, 
            strm.YCOORDINATE, 
            strm.ZCOORDINATE, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.APPLANKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_CDR_PLANNING_PLANAPPL as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.APPLANKEY=src.APPLANKEY) OR (target.APPLANKEY IS NULL AND src.APPLANKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ACTLVLTN=src.ACTLVLTN, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.APBY=src.APBY, 
                    target.APDTTM=src.APDTTM, 
                    target.APKEY=src.APKEY, 
                    target.APNO=src.APNO, 
                    target.APPLANDEFNKEY=src.APPLANDEFNKEY, 
                    target.APPLANKEY=src.APPLANKEY, 
                    target.APPLANPROCESSSTATEKEY=src.APPLANPROCESSSTATEKEY, 
                    target.APRVBY=src.APRVBY, 
                    target.APRVDTTM=src.APRVDTTM, 
                    target.AREAUM=src.AREAUM, 
                    target.BILLGRP=src.BILLGRP, 
                    target.BLDGAREA=src.BLDGAREA, 
                    target.BLDGFLOOR=src.BLDGFLOOR, 
                    target.BLDGROOM=src.BLDGROOM, 
                    target.CALCVLTN=src.CALCVLTN, 
                    target.CAPACITY=src.CAPACITY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COMPVAL=src.COMPVAL, 
                    target.COOBY=src.COOBY, 
                    target.COODTTM=src.COODTTM, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DECLVLTN=src.DECLVLTN, 
                    target.EXPDTTM=src.EXPDTTM, 
                    target.FINBY=src.FINBY, 
                    target.FINDTTM=src.FINDTTM, 
                    target.GROUPKEY=src.GROUPKEY, 
                    target.LINEARFROMFT=src.LINEARFROMFT, 
                    target.LINEARFROMM=src.LINEARFROMM, 
                    target.LINEARTOFT=src.LINEARTOFT, 
                    target.LINEARTOM=src.LINEARTOM, 
                    target.LOC=src.LOC, 
                    target.LOCNOTES=src.LOCNOTES, 
                    target.LSTACTDTTM=src.LSTACTDTTM, 
                    target.LSTPRNDTTM=src.LSTPRNDTTM, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.NOPAGES=src.NOPAGES, 
                    target.NOPLANS=src.NOPLANS, 
                    target.OCCUPANCYTYPE=src.OCCUPANCYTYPE, 
                    target.PHASENO=src.PHASENO, 
                    target.PLANAPPLSTATUS=src.PLANAPPLSTATUS, 
                    target.PLANREV=src.PLANREV, 
                    target.PRCLKEY=src.PRCLKEY, 
                    target.PRI=src.PRI, 
                    target.PROJNAME=src.PROJNAME, 
                    target.PROPKEY=src.PROPKEY, 
                    target.PROPOCCUPKEY=src.PROPOCCUPKEY, 
                    target.PRPSTOPDT=src.PRPSTOPDT, 
                    target.PRPSTRTDT=src.PRPSTRTDT, 
                    target.STAT=src.STAT, 
                    target.STATBY=src.STATBY, 
                    target.STATDTTM=src.STATDTTM, 
                    target.STATREAS=src.STATREAS, 
                    target.SUBDIVCODE=src.SUBDIVCODE, 
                    target.SZDESC=src.SZDESC, 
                    target.TMPCOOBY=src.TMPCOOBY, 
                    target.TMPCOODTTM=src.TMPCOODTTM, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WORKTYPE=src.WORKTYPE, 
                    target.XCOORDINATE=src.XCOORDINATE, 
                    target.YCOORDINATE=src.YCOORDINATE, 
                    target.ZCOORDINATE=src.ZCOORDINATE, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ACTLVLTN, 
                    ADDBY, 
                    ADDDTTM, 
                    ADDRKEY, 
                    APBY, 
                    APDTTM, 
                    APKEY, 
                    APNO, 
                    APPLANDEFNKEY, 
                    APPLANKEY, 
                    APPLANPROCESSSTATEKEY, 
                    APRVBY, 
                    APRVDTTM, 
                    AREAUM, 
                    BILLGRP, 
                    BLDGAREA, 
                    BLDGFLOOR, 
                    BLDGROOM, 
                    CALCVLTN, 
                    CAPACITY, 
                    COMPKEY, 
                    COMPVAL, 
                    COOBY, 
                    COODTTM, 
                    DATALAKE_DELETED, 
                    DECLVLTN, 
                    EXPDTTM, 
                    FINBY, 
                    FINDTTM, 
                    GROUPKEY, 
                    LINEARFROMFT, 
                    LINEARFROMM, 
                    LINEARTOFT, 
                    LINEARTOM, 
                    LOC, 
                    LOCNOTES, 
                    LSTACTDTTM, 
                    LSTPRNDTTM, 
                    MODBY, 
                    MODDTTM, 
                    NOPAGES, 
                    NOPLANS, 
                    OCCUPANCYTYPE, 
                    PHASENO, 
                    PLANAPPLSTATUS, 
                    PLANREV, 
                    PRCLKEY, 
                    PRI, 
                    PROJNAME, 
                    PROPKEY, 
                    PROPOCCUPKEY, 
                    PRPSTOPDT, 
                    PRPSTRTDT, 
                    STAT, 
                    STATBY, 
                    STATDTTM, 
                    STATREAS, 
                    SUBDIVCODE, 
                    SZDESC, 
                    TMPCOOBY, 
                    TMPCOODTTM, 
                    VARIATION_ID, 
                    WORKTYPE, 
                    XCOORDINATE, 
                    YCOORDINATE, 
                    ZCOORDINATE, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ACTLVLTN, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.APBY, 
                    src.APDTTM, 
                    src.APKEY, 
                    src.APNO, 
                    src.APPLANDEFNKEY, 
                    src.APPLANKEY, 
                    src.APPLANPROCESSSTATEKEY, 
                    src.APRVBY, 
                    src.APRVDTTM, 
                    src.AREAUM, 
                    src.BILLGRP, 
                    src.BLDGAREA, 
                    src.BLDGFLOOR, 
                    src.BLDGROOM, 
                    src.CALCVLTN, 
                    src.CAPACITY, 
                    src.COMPKEY, 
                    src.COMPVAL, 
                    src.COOBY, 
                    src.COODTTM, 
                    src.DATALAKE_DELETED, 
                    src.DECLVLTN, 
                    src.EXPDTTM, 
                    src.FINBY, 
                    src.FINDTTM, 
                    src.GROUPKEY, 
                    src.LINEARFROMFT, 
                    src.LINEARFROMM, 
                    src.LINEARTOFT, 
                    src.LINEARTOM, 
                    src.LOC, 
                    src.LOCNOTES, 
                    src.LSTACTDTTM, 
                    src.LSTPRNDTTM, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.NOPAGES, 
                    src.NOPLANS, 
                    src.OCCUPANCYTYPE, 
                    src.PHASENO, 
                    src.PLANAPPLSTATUS, 
                    src.PLANREV, 
                    src.PRCLKEY, 
                    src.PRI, 
                    src.PROJNAME, 
                    src.PROPKEY, 
                    src.PROPOCCUPKEY, 
                    src.PRPSTOPDT, 
                    src.PRPSTRTDT, 
                    src.STAT, 
                    src.STATBY, 
                    src.STATDTTM, 
                    src.STATREAS, 
                    src.SUBDIVCODE, 
                    src.SZDESC, 
                    src.TMPCOOBY, 
                    src.TMPCOODTTM, 
                    src.VARIATION_ID, 
                    src.WORKTYPE, 
                    src.XCOORDINATE, 
                    src.YCOORDINATE, 
                    src.ZCOORDINATE,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PLANNING_PLANAPPL as target using (
                SELECT * FROM (SELECT 
            strm.ACTLVLTN, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.APBY, 
            strm.APDTTM, 
            strm.APKEY, 
            strm.APNO, 
            strm.APPLANDEFNKEY, 
            strm.APPLANKEY, 
            strm.APPLANPROCESSSTATEKEY, 
            strm.APRVBY, 
            strm.APRVDTTM, 
            strm.AREAUM, 
            strm.BILLGRP, 
            strm.BLDGAREA, 
            strm.BLDGFLOOR, 
            strm.BLDGROOM, 
            strm.CALCVLTN, 
            strm.CAPACITY, 
            strm.COMPKEY, 
            strm.COMPVAL, 
            strm.COOBY, 
            strm.COODTTM, 
            strm.DATALAKE_DELETED, 
            strm.DECLVLTN, 
            strm.EXPDTTM, 
            strm.FINBY, 
            strm.FINDTTM, 
            strm.GROUPKEY, 
            strm.LINEARFROMFT, 
            strm.LINEARFROMM, 
            strm.LINEARTOFT, 
            strm.LINEARTOM, 
            strm.LOC, 
            strm.LOCNOTES, 
            strm.LSTACTDTTM, 
            strm.LSTPRNDTTM, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.NOPAGES, 
            strm.NOPLANS, 
            strm.OCCUPANCYTYPE, 
            strm.PHASENO, 
            strm.PLANAPPLSTATUS, 
            strm.PLANREV, 
            strm.PRCLKEY, 
            strm.PRI, 
            strm.PROJNAME, 
            strm.PROPKEY, 
            strm.PROPOCCUPKEY, 
            strm.PRPSTOPDT, 
            strm.PRPSTRTDT, 
            strm.STAT, 
            strm.STATBY, 
            strm.STATDTTM, 
            strm.STATREAS, 
            strm.SUBDIVCODE, 
            strm.SZDESC, 
            strm.TMPCOOBY, 
            strm.TMPCOODTTM, 
            strm.VARIATION_ID, 
            strm.WORKTYPE, 
            strm.XCOORDINATE, 
            strm.YCOORDINATE, 
            strm.ZCOORDINATE, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.APPLANKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_CDR_PLANNING_PLANAPPL as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.APPLANKEY=src.APPLANKEY) OR (target.APPLANKEY IS NULL AND src.APPLANKEY IS NULL)) 
                when matched then update set
                    target.ACTLVLTN=src.ACTLVLTN, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.APBY=src.APBY, 
                    target.APDTTM=src.APDTTM, 
                    target.APKEY=src.APKEY, 
                    target.APNO=src.APNO, 
                    target.APPLANDEFNKEY=src.APPLANDEFNKEY, 
                    target.APPLANKEY=src.APPLANKEY, 
                    target.APPLANPROCESSSTATEKEY=src.APPLANPROCESSSTATEKEY, 
                    target.APRVBY=src.APRVBY, 
                    target.APRVDTTM=src.APRVDTTM, 
                    target.AREAUM=src.AREAUM, 
                    target.BILLGRP=src.BILLGRP, 
                    target.BLDGAREA=src.BLDGAREA, 
                    target.BLDGFLOOR=src.BLDGFLOOR, 
                    target.BLDGROOM=src.BLDGROOM, 
                    target.CALCVLTN=src.CALCVLTN, 
                    target.CAPACITY=src.CAPACITY, 
                    target.COMPKEY=src.COMPKEY, 
                    target.COMPVAL=src.COMPVAL, 
                    target.COOBY=src.COOBY, 
                    target.COODTTM=src.COODTTM, 
                    target.DATALAKE_DELETED=src.DATALAKE_DELETED, 
                    target.DECLVLTN=src.DECLVLTN, 
                    target.EXPDTTM=src.EXPDTTM, 
                    target.FINBY=src.FINBY, 
                    target.FINDTTM=src.FINDTTM, 
                    target.GROUPKEY=src.GROUPKEY, 
                    target.LINEARFROMFT=src.LINEARFROMFT, 
                    target.LINEARFROMM=src.LINEARFROMM, 
                    target.LINEARTOFT=src.LINEARTOFT, 
                    target.LINEARTOM=src.LINEARTOM, 
                    target.LOC=src.LOC, 
                    target.LOCNOTES=src.LOCNOTES, 
                    target.LSTACTDTTM=src.LSTACTDTTM, 
                    target.LSTPRNDTTM=src.LSTPRNDTTM, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.NOPAGES=src.NOPAGES, 
                    target.NOPLANS=src.NOPLANS, 
                    target.OCCUPANCYTYPE=src.OCCUPANCYTYPE, 
                    target.PHASENO=src.PHASENO, 
                    target.PLANAPPLSTATUS=src.PLANAPPLSTATUS, 
                    target.PLANREV=src.PLANREV, 
                    target.PRCLKEY=src.PRCLKEY, 
                    target.PRI=src.PRI, 
                    target.PROJNAME=src.PROJNAME, 
                    target.PROPKEY=src.PROPKEY, 
                    target.PROPOCCUPKEY=src.PROPOCCUPKEY, 
                    target.PRPSTOPDT=src.PRPSTOPDT, 
                    target.PRPSTRTDT=src.PRPSTRTDT, 
                    target.STAT=src.STAT, 
                    target.STATBY=src.STATBY, 
                    target.STATDTTM=src.STATDTTM, 
                    target.STATREAS=src.STATREAS, 
                    target.SUBDIVCODE=src.SUBDIVCODE, 
                    target.SZDESC=src.SZDESC, 
                    target.TMPCOOBY=src.TMPCOOBY, 
                    target.TMPCOODTTM=src.TMPCOODTTM, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WORKTYPE=src.WORKTYPE, 
                    target.XCOORDINATE=src.XCOORDINATE, 
                    target.YCOORDINATE=src.YCOORDINATE, 
                    target.ZCOORDINATE=src.ZCOORDINATE, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ACTLVLTN, ADDBY, ADDDTTM, ADDRKEY, APBY, APDTTM, APKEY, APNO, APPLANDEFNKEY, APPLANKEY, APPLANPROCESSSTATEKEY, APRVBY, APRVDTTM, AREAUM, BILLGRP, BLDGAREA, BLDGFLOOR, BLDGROOM, CALCVLTN, CAPACITY, COMPKEY, COMPVAL, COOBY, COODTTM, DATALAKE_DELETED, DECLVLTN, EXPDTTM, FINBY, FINDTTM, GROUPKEY, LINEARFROMFT, LINEARFROMM, LINEARTOFT, LINEARTOM, LOC, LOCNOTES, LSTACTDTTM, LSTPRNDTTM, MODBY, MODDTTM, NOPAGES, NOPLANS, OCCUPANCYTYPE, PHASENO, PLANAPPLSTATUS, PLANREV, PRCLKEY, PRI, PROJNAME, PROPKEY, PROPOCCUPKEY, PRPSTOPDT, PRPSTRTDT, STAT, STATBY, STATDTTM, STATREAS, SUBDIVCODE, SZDESC, TMPCOOBY, TMPCOODTTM, VARIATION_ID, WORKTYPE, XCOORDINATE, YCOORDINATE, ZCOORDINATE, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ACTLVLTN, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.APBY, 
                    src.APDTTM, 
                    src.APKEY, 
                    src.APNO, 
                    src.APPLANDEFNKEY, 
                    src.APPLANKEY, 
                    src.APPLANPROCESSSTATEKEY, 
                    src.APRVBY, 
                    src.APRVDTTM, 
                    src.AREAUM, 
                    src.BILLGRP, 
                    src.BLDGAREA, 
                    src.BLDGFLOOR, 
                    src.BLDGROOM, 
                    src.CALCVLTN, 
                    src.CAPACITY, 
                    src.COMPKEY, 
                    src.COMPVAL, 
                    src.COOBY, 
                    src.COODTTM, 
                    src.DATALAKE_DELETED, 
                    src.DECLVLTN, 
                    src.EXPDTTM, 
                    src.FINBY, 
                    src.FINDTTM, 
                    src.GROUPKEY, 
                    src.LINEARFROMFT, 
                    src.LINEARFROMM, 
                    src.LINEARTOFT, 
                    src.LINEARTOM, 
                    src.LOC, 
                    src.LOCNOTES, 
                    src.LSTACTDTTM, 
                    src.LSTPRNDTTM, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.NOPAGES, 
                    src.NOPLANS, 
                    src.OCCUPANCYTYPE, 
                    src.PHASENO, 
                    src.PLANAPPLSTATUS, 
                    src.PLANREV, 
                    src.PRCLKEY, 
                    src.PRI, 
                    src.PROJNAME, 
                    src.PROPKEY, 
                    src.PROPOCCUPKEY, 
                    src.PRPSTOPDT, 
                    src.PRPSTRTDT, 
                    src.STAT, 
                    src.STATBY, 
                    src.STATDTTM, 
                    src.STATREAS, 
                    src.SUBDIVCODE, 
                    src.SZDESC, 
                    src.TMPCOOBY, 
                    src.TMPCOODTTM, 
                    src.VARIATION_ID, 
                    src.WORKTYPE, 
                    src.XCOORDINATE, 
                    src.YCOORDINATE, 
                    src.ZCOORDINATE,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;