create or replace procedure DATAHUB_INTEGRATION.SP_IPS_BILLING_ACCOUNT()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.IPS_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_IPS_BILLING_ACCOUNT_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  DATAHUB_TARGET.IPS_BILLING_ACCOUNT as target using (SELECT * FROM (SELECT 
            strm.ACCEPTCHECKSFLAG, 
            strm.ACCOUNTKEY, 
            strm.ACCOUNTNUMBER, 
            strm.ACCOUNTSTATUS, 
            strm.ACCOUNTTYPE, 
            strm.ACCTCLASS, 
            strm.ACCTGRP, 
            strm.ACCTSUBGRP, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.AGGREGATEFLAG, 
            strm.AGGREGATEKEY, 
            strm.ALLOWARCHIVEFLAG, 
            strm.ALLOWCHECKOVERRIDESFLAG, 
            strm.ARCHIVETHROUGHDATE, 
            strm.AREA, 
            strm.ARRANGEDFLAG, 
            strm.ASSIGNED, 
            strm.BANKRUPTFLAG, 
            strm.BILLINGCYCLE, 
            strm.BILLPRINTEXCEPTION, 
            strm.BLNGSTAT, 
            strm.BLNGSTDTTM, 
            strm.BUDGETBILLINGDISALLOWED, 
            strm.BUDGETBILLINGFLAG, 
            strm.BUSINESSTYPE, 
            strm.CHARCONSVAL1, 
            strm.CHARCONSVAL2, 
            strm.CHARCONSVAL3, 
            strm.CHARCONSVAL4, 
            strm.CHARCONSVAL5, 
            strm.CHARCONSVAL6, 
            strm.CHARCONSVAL7, 
            strm.CHARCONSVAL8, 
            strm.CLOSEDATE, 
            strm.COLLECTIONSELIGIBLEFLAG, 
            strm.COLLECTIONSFLAG, 
            strm.COLLEXEMPT, 
            strm.COMMENTSKEY, 
            strm.CREDFLAG, 
            strm.CUSTDESC, 
            strm.DELETED, 
            strm.DELINQUENCYEXEMPT, 
            strm.DELINQUENCYEXEMPTFLAG, 
            strm.DELINQUENCYFLAG, 
            strm.DEPPDDATE, 
            strm.DONOTDIRECTDEBIT, 
            strm.ELIGIBLEFORREFUNDFLAG, 
            strm.FINALBILLFLAG, 
            strm.FREQUENCY, 
            strm.IDKEY, 
            strm.INITIATEDBY, 
            strm.INITIATEDDTTM, 
            strm.LEGACYACCOUNTNUMBER, 
            strm.LIENELIGIBLEFLAG, 
            strm.LIENEXEMPT, 
            strm.LIENFLAG, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MOVEDOUTACCOUNTKEY, 
            strm.MOVEINADMINHOLDBY, 
            strm.MOVEINADMINHOLDDTTM, 
            strm.MOVEINADMINHOLDREASON, 
            strm.MOVEINDATE, 
            strm.MOVEINEXCEPTION, 
            strm.MOVEINSTATUS, 
            strm.MOVEOUTADMINHOLDBY, 
            strm.MOVEOUTADMINHOLDDTTM, 
            strm.MOVEOUTADMINHOLDREASON, 
            strm.MOVEOUTDATE, 
            strm.MOVEOUTEXCEPTION, 
            strm.MOVEOUTSTATUS, 
            strm.NOARNG, 
            strm.NOBILL, 
            strm.NODISCONN, 
            strm.NONOTICE, 
            strm.NOTICEDTTM, 
            strm.NUMERICCONSVAL1, 
            strm.NUMERICCONSVAL2, 
            strm.NUMERICCONSVAL3, 
            strm.NUMERICCONSVAL4, 
            strm.NUMERICCONSVAL5, 
            strm.NUMERICCONSVAL6, 
            strm.NUMERICCONSVAL7, 
            strm.NUMERICCONSVAL8, 
            strm.OCCUPANT, 
            strm.ONEOFFCHARGEFLAG, 
            strm.OPENDATE, 
            strm.PARCELKEY, 
            strm.PENEXEMPT, 
            strm.PRESELECTEDFORBILLRUN, 
            strm.PRESELECTEDFORINTERIMBILL, 
            strm.PROPERTYKEY, 
            strm.RESPONSIBILITY, 
            strm.STATBY, 
            strm.STATDTTM, 
            strm.SUSPENDBY, 
            strm.SUSPENDDTTM, 
            strm.SUSPENDFLAG, 
            strm.TAXEXEMPTFALG, 
            strm.TRANSFERREDTO, 
            strm.VARIATION_ID, 
            strm.WRITEOFFELIGIBLEFLAG, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.ACCOUNTKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_BILLING_ACCOUNT as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.ACCOUNTKEY=src.ACCOUNTKEY) OR (target.ACCOUNTKEY IS NULL AND src.ACCOUNTKEY IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.ACCEPTCHECKSFLAG=src.ACCEPTCHECKSFLAG, 
                    target.ACCOUNTKEY=src.ACCOUNTKEY, 
                    target.ACCOUNTNUMBER=src.ACCOUNTNUMBER, 
                    target.ACCOUNTSTATUS=src.ACCOUNTSTATUS, 
                    target.ACCOUNTTYPE=src.ACCOUNTTYPE, 
                    target.ACCTCLASS=src.ACCTCLASS, 
                    target.ACCTGRP=src.ACCTGRP, 
                    target.ACCTSUBGRP=src.ACCTSUBGRP, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.AGGREGATEFLAG=src.AGGREGATEFLAG, 
                    target.AGGREGATEKEY=src.AGGREGATEKEY, 
                    target.ALLOWARCHIVEFLAG=src.ALLOWARCHIVEFLAG, 
                    target.ALLOWCHECKOVERRIDESFLAG=src.ALLOWCHECKOVERRIDESFLAG, 
                    target.ARCHIVETHROUGHDATE=src.ARCHIVETHROUGHDATE, 
                    target.AREA=src.AREA, 
                    target.ARRANGEDFLAG=src.ARRANGEDFLAG, 
                    target.ASSIGNED=src.ASSIGNED, 
                    target.BANKRUPTFLAG=src.BANKRUPTFLAG, 
                    target.BILLINGCYCLE=src.BILLINGCYCLE, 
                    target.BILLPRINTEXCEPTION=src.BILLPRINTEXCEPTION, 
                    target.BLNGSTAT=src.BLNGSTAT, 
                    target.BLNGSTDTTM=src.BLNGSTDTTM, 
                    target.BUDGETBILLINGDISALLOWED=src.BUDGETBILLINGDISALLOWED, 
                    target.BUDGETBILLINGFLAG=src.BUDGETBILLINGFLAG, 
                    target.BUSINESSTYPE=src.BUSINESSTYPE, 
                    target.CHARCONSVAL1=src.CHARCONSVAL1, 
                    target.CHARCONSVAL2=src.CHARCONSVAL2, 
                    target.CHARCONSVAL3=src.CHARCONSVAL3, 
                    target.CHARCONSVAL4=src.CHARCONSVAL4, 
                    target.CHARCONSVAL5=src.CHARCONSVAL5, 
                    target.CHARCONSVAL6=src.CHARCONSVAL6, 
                    target.CHARCONSVAL7=src.CHARCONSVAL7, 
                    target.CHARCONSVAL8=src.CHARCONSVAL8, 
                    target.CLOSEDATE=src.CLOSEDATE, 
                    target.COLLECTIONSELIGIBLEFLAG=src.COLLECTIONSELIGIBLEFLAG, 
                    target.COLLECTIONSFLAG=src.COLLECTIONSFLAG, 
                    target.COLLEXEMPT=src.COLLEXEMPT, 
                    target.COMMENTSKEY=src.COMMENTSKEY, 
                    target.CREDFLAG=src.CREDFLAG, 
                    target.CUSTDESC=src.CUSTDESC, 
                    target.DELETED=src.DELETED, 
                    target.DELINQUENCYEXEMPT=src.DELINQUENCYEXEMPT, 
                    target.DELINQUENCYEXEMPTFLAG=src.DELINQUENCYEXEMPTFLAG, 
                    target.DELINQUENCYFLAG=src.DELINQUENCYFLAG, 
                    target.DEPPDDATE=src.DEPPDDATE, 
                    target.DONOTDIRECTDEBIT=src.DONOTDIRECTDEBIT, 
                    target.ELIGIBLEFORREFUNDFLAG=src.ELIGIBLEFORREFUNDFLAG, 
                    target.FINALBILLFLAG=src.FINALBILLFLAG, 
                    target.FREQUENCY=src.FREQUENCY, 
                    target.IDKEY=src.IDKEY, 
                    target.INITIATEDBY=src.INITIATEDBY, 
                    target.INITIATEDDTTM=src.INITIATEDDTTM, 
                    target.LEGACYACCOUNTNUMBER=src.LEGACYACCOUNTNUMBER, 
                    target.LIENELIGIBLEFLAG=src.LIENELIGIBLEFLAG, 
                    target.LIENEXEMPT=src.LIENEXEMPT, 
                    target.LIENFLAG=src.LIENFLAG, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MOVEDOUTACCOUNTKEY=src.MOVEDOUTACCOUNTKEY, 
                    target.MOVEINADMINHOLDBY=src.MOVEINADMINHOLDBY, 
                    target.MOVEINADMINHOLDDTTM=src.MOVEINADMINHOLDDTTM, 
                    target.MOVEINADMINHOLDREASON=src.MOVEINADMINHOLDREASON, 
                    target.MOVEINDATE=src.MOVEINDATE, 
                    target.MOVEINEXCEPTION=src.MOVEINEXCEPTION, 
                    target.MOVEINSTATUS=src.MOVEINSTATUS, 
                    target.MOVEOUTADMINHOLDBY=src.MOVEOUTADMINHOLDBY, 
                    target.MOVEOUTADMINHOLDDTTM=src.MOVEOUTADMINHOLDDTTM, 
                    target.MOVEOUTADMINHOLDREASON=src.MOVEOUTADMINHOLDREASON, 
                    target.MOVEOUTDATE=src.MOVEOUTDATE, 
                    target.MOVEOUTEXCEPTION=src.MOVEOUTEXCEPTION, 
                    target.MOVEOUTSTATUS=src.MOVEOUTSTATUS, 
                    target.NOARNG=src.NOARNG, 
                    target.NOBILL=src.NOBILL, 
                    target.NODISCONN=src.NODISCONN, 
                    target.NONOTICE=src.NONOTICE, 
                    target.NOTICEDTTM=src.NOTICEDTTM, 
                    target.NUMERICCONSVAL1=src.NUMERICCONSVAL1, 
                    target.NUMERICCONSVAL2=src.NUMERICCONSVAL2, 
                    target.NUMERICCONSVAL3=src.NUMERICCONSVAL3, 
                    target.NUMERICCONSVAL4=src.NUMERICCONSVAL4, 
                    target.NUMERICCONSVAL5=src.NUMERICCONSVAL5, 
                    target.NUMERICCONSVAL6=src.NUMERICCONSVAL6, 
                    target.NUMERICCONSVAL7=src.NUMERICCONSVAL7, 
                    target.NUMERICCONSVAL8=src.NUMERICCONSVAL8, 
                    target.OCCUPANT=src.OCCUPANT, 
                    target.ONEOFFCHARGEFLAG=src.ONEOFFCHARGEFLAG, 
                    target.OPENDATE=src.OPENDATE, 
                    target.PARCELKEY=src.PARCELKEY, 
                    target.PENEXEMPT=src.PENEXEMPT, 
                    target.PRESELECTEDFORBILLRUN=src.PRESELECTEDFORBILLRUN, 
                    target.PRESELECTEDFORINTERIMBILL=src.PRESELECTEDFORINTERIMBILL, 
                    target.PROPERTYKEY=src.PROPERTYKEY, 
                    target.RESPONSIBILITY=src.RESPONSIBILITY, 
                    target.STATBY=src.STATBY, 
                    target.STATDTTM=src.STATDTTM, 
                    target.SUSPENDBY=src.SUSPENDBY, 
                    target.SUSPENDDTTM=src.SUSPENDDTTM, 
                    target.SUSPENDFLAG=src.SUSPENDFLAG, 
                    target.TAXEXEMPTFALG=src.TAXEXEMPTFALG, 
                    target.TRANSFERREDTO=src.TRANSFERREDTO, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WRITEOFFELIGIBLEFLAG=src.WRITEOFFELIGIBLEFLAG, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    ACCEPTCHECKSFLAG, 
                    ACCOUNTKEY, 
                    ACCOUNTNUMBER, 
                    ACCOUNTSTATUS, 
                    ACCOUNTTYPE, 
                    ACCTCLASS, 
                    ACCTGRP, 
                    ACCTSUBGRP, 
                    ADDBY, 
                    ADDDTTM, 
                    ADDRKEY, 
                    AGGREGATEFLAG, 
                    AGGREGATEKEY, 
                    ALLOWARCHIVEFLAG, 
                    ALLOWCHECKOVERRIDESFLAG, 
                    ARCHIVETHROUGHDATE, 
                    AREA, 
                    ARRANGEDFLAG, 
                    ASSIGNED, 
                    BANKRUPTFLAG, 
                    BILLINGCYCLE, 
                    BILLPRINTEXCEPTION, 
                    BLNGSTAT, 
                    BLNGSTDTTM, 
                    BUDGETBILLINGDISALLOWED, 
                    BUDGETBILLINGFLAG, 
                    BUSINESSTYPE, 
                    CHARCONSVAL1, 
                    CHARCONSVAL2, 
                    CHARCONSVAL3, 
                    CHARCONSVAL4, 
                    CHARCONSVAL5, 
                    CHARCONSVAL6, 
                    CHARCONSVAL7, 
                    CHARCONSVAL8, 
                    CLOSEDATE, 
                    COLLECTIONSELIGIBLEFLAG, 
                    COLLECTIONSFLAG, 
                    COLLEXEMPT, 
                    COMMENTSKEY, 
                    CREDFLAG, 
                    CUSTDESC, 
                    DELETED, 
                    DELINQUENCYEXEMPT, 
                    DELINQUENCYEXEMPTFLAG, 
                    DELINQUENCYFLAG, 
                    DEPPDDATE, 
                    DONOTDIRECTDEBIT, 
                    ELIGIBLEFORREFUNDFLAG, 
                    FINALBILLFLAG, 
                    FREQUENCY, 
                    IDKEY, 
                    INITIATEDBY, 
                    INITIATEDDTTM, 
                    LEGACYACCOUNTNUMBER, 
                    LIENELIGIBLEFLAG, 
                    LIENEXEMPT, 
                    LIENFLAG, 
                    MODBY, 
                    MODDTTM, 
                    MOVEDOUTACCOUNTKEY, 
                    MOVEINADMINHOLDBY, 
                    MOVEINADMINHOLDDTTM, 
                    MOVEINADMINHOLDREASON, 
                    MOVEINDATE, 
                    MOVEINEXCEPTION, 
                    MOVEINSTATUS, 
                    MOVEOUTADMINHOLDBY, 
                    MOVEOUTADMINHOLDDTTM, 
                    MOVEOUTADMINHOLDREASON, 
                    MOVEOUTDATE, 
                    MOVEOUTEXCEPTION, 
                    MOVEOUTSTATUS, 
                    NOARNG, 
                    NOBILL, 
                    NODISCONN, 
                    NONOTICE, 
                    NOTICEDTTM, 
                    NUMERICCONSVAL1, 
                    NUMERICCONSVAL2, 
                    NUMERICCONSVAL3, 
                    NUMERICCONSVAL4, 
                    NUMERICCONSVAL5, 
                    NUMERICCONSVAL6, 
                    NUMERICCONSVAL7, 
                    NUMERICCONSVAL8, 
                    OCCUPANT, 
                    ONEOFFCHARGEFLAG, 
                    OPENDATE, 
                    PARCELKEY, 
                    PENEXEMPT, 
                    PRESELECTEDFORBILLRUN, 
                    PRESELECTEDFORINTERIMBILL, 
                    PROPERTYKEY, 
                    RESPONSIBILITY, 
                    STATBY, 
                    STATDTTM, 
                    SUSPENDBY, 
                    SUSPENDDTTM, 
                    SUSPENDFLAG, 
                    TAXEXEMPTFALG, 
                    TRANSFERREDTO, 
                    VARIATION_ID, 
                    WRITEOFFELIGIBLEFLAG, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.ACCEPTCHECKSFLAG, 
                    src.ACCOUNTKEY, 
                    src.ACCOUNTNUMBER, 
                    src.ACCOUNTSTATUS, 
                    src.ACCOUNTTYPE, 
                    src.ACCTCLASS, 
                    src.ACCTGRP, 
                    src.ACCTSUBGRP, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.AGGREGATEFLAG, 
                    src.AGGREGATEKEY, 
                    src.ALLOWARCHIVEFLAG, 
                    src.ALLOWCHECKOVERRIDESFLAG, 
                    src.ARCHIVETHROUGHDATE, 
                    src.AREA, 
                    src.ARRANGEDFLAG, 
                    src.ASSIGNED, 
                    src.BANKRUPTFLAG, 
                    src.BILLINGCYCLE, 
                    src.BILLPRINTEXCEPTION, 
                    src.BLNGSTAT, 
                    src.BLNGSTDTTM, 
                    src.BUDGETBILLINGDISALLOWED, 
                    src.BUDGETBILLINGFLAG, 
                    src.BUSINESSTYPE, 
                    src.CHARCONSVAL1, 
                    src.CHARCONSVAL2, 
                    src.CHARCONSVAL3, 
                    src.CHARCONSVAL4, 
                    src.CHARCONSVAL5, 
                    src.CHARCONSVAL6, 
                    src.CHARCONSVAL7, 
                    src.CHARCONSVAL8, 
                    src.CLOSEDATE, 
                    src.COLLECTIONSELIGIBLEFLAG, 
                    src.COLLECTIONSFLAG, 
                    src.COLLEXEMPT, 
                    src.COMMENTSKEY, 
                    src.CREDFLAG, 
                    src.CUSTDESC, 
                    src.DELETED, 
                    src.DELINQUENCYEXEMPT, 
                    src.DELINQUENCYEXEMPTFLAG, 
                    src.DELINQUENCYFLAG, 
                    src.DEPPDDATE, 
                    src.DONOTDIRECTDEBIT, 
                    src.ELIGIBLEFORREFUNDFLAG, 
                    src.FINALBILLFLAG, 
                    src.FREQUENCY, 
                    src.IDKEY, 
                    src.INITIATEDBY, 
                    src.INITIATEDDTTM, 
                    src.LEGACYACCOUNTNUMBER, 
                    src.LIENELIGIBLEFLAG, 
                    src.LIENEXEMPT, 
                    src.LIENFLAG, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MOVEDOUTACCOUNTKEY, 
                    src.MOVEINADMINHOLDBY, 
                    src.MOVEINADMINHOLDDTTM, 
                    src.MOVEINADMINHOLDREASON, 
                    src.MOVEINDATE, 
                    src.MOVEINEXCEPTION, 
                    src.MOVEINSTATUS, 
                    src.MOVEOUTADMINHOLDBY, 
                    src.MOVEOUTADMINHOLDDTTM, 
                    src.MOVEOUTADMINHOLDREASON, 
                    src.MOVEOUTDATE, 
                    src.MOVEOUTEXCEPTION, 
                    src.MOVEOUTSTATUS, 
                    src.NOARNG, 
                    src.NOBILL, 
                    src.NODISCONN, 
                    src.NONOTICE, 
                    src.NOTICEDTTM, 
                    src.NUMERICCONSVAL1, 
                    src.NUMERICCONSVAL2, 
                    src.NUMERICCONSVAL3, 
                    src.NUMERICCONSVAL4, 
                    src.NUMERICCONSVAL5, 
                    src.NUMERICCONSVAL6, 
                    src.NUMERICCONSVAL7, 
                    src.NUMERICCONSVAL8, 
                    src.OCCUPANT, 
                    src.ONEOFFCHARGEFLAG, 
                    src.OPENDATE, 
                    src.PARCELKEY, 
                    src.PENEXEMPT, 
                    src.PRESELECTEDFORBILLRUN, 
                    src.PRESELECTEDFORINTERIMBILL, 
                    src.PROPERTYKEY, 
                    src.RESPONSIBILITY, 
                    src.STATBY, 
                    src.STATDTTM, 
                    src.SUSPENDBY, 
                    src.SUSPENDDTTM, 
                    src.SUSPENDFLAG, 
                    src.TAXEXEMPTFALG, 
                    src.TRANSFERREDTO, 
                    src.VARIATION_ID, 
                    src.WRITEOFFELIGIBLEFLAG,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_ACCOUNT as target using (
                SELECT * FROM (SELECT 
            strm.ACCEPTCHECKSFLAG, 
            strm.ACCOUNTKEY, 
            strm.ACCOUNTNUMBER, 
            strm.ACCOUNTSTATUS, 
            strm.ACCOUNTTYPE, 
            strm.ACCTCLASS, 
            strm.ACCTGRP, 
            strm.ACCTSUBGRP, 
            strm.ADDBY, 
            strm.ADDDTTM, 
            strm.ADDRKEY, 
            strm.AGGREGATEFLAG, 
            strm.AGGREGATEKEY, 
            strm.ALLOWARCHIVEFLAG, 
            strm.ALLOWCHECKOVERRIDESFLAG, 
            strm.ARCHIVETHROUGHDATE, 
            strm.AREA, 
            strm.ARRANGEDFLAG, 
            strm.ASSIGNED, 
            strm.BANKRUPTFLAG, 
            strm.BILLINGCYCLE, 
            strm.BILLPRINTEXCEPTION, 
            strm.BLNGSTAT, 
            strm.BLNGSTDTTM, 
            strm.BUDGETBILLINGDISALLOWED, 
            strm.BUDGETBILLINGFLAG, 
            strm.BUSINESSTYPE, 
            strm.CHARCONSVAL1, 
            strm.CHARCONSVAL2, 
            strm.CHARCONSVAL3, 
            strm.CHARCONSVAL4, 
            strm.CHARCONSVAL5, 
            strm.CHARCONSVAL6, 
            strm.CHARCONSVAL7, 
            strm.CHARCONSVAL8, 
            strm.CLOSEDATE, 
            strm.COLLECTIONSELIGIBLEFLAG, 
            strm.COLLECTIONSFLAG, 
            strm.COLLEXEMPT, 
            strm.COMMENTSKEY, 
            strm.CREDFLAG, 
            strm.CUSTDESC, 
            strm.DELETED, 
            strm.DELINQUENCYEXEMPT, 
            strm.DELINQUENCYEXEMPTFLAG, 
            strm.DELINQUENCYFLAG, 
            strm.DEPPDDATE, 
            strm.DONOTDIRECTDEBIT, 
            strm.ELIGIBLEFORREFUNDFLAG, 
            strm.FINALBILLFLAG, 
            strm.FREQUENCY, 
            strm.IDKEY, 
            strm.INITIATEDBY, 
            strm.INITIATEDDTTM, 
            strm.LEGACYACCOUNTNUMBER, 
            strm.LIENELIGIBLEFLAG, 
            strm.LIENEXEMPT, 
            strm.LIENFLAG, 
            strm.MODBY, 
            strm.MODDTTM, 
            strm.MOVEDOUTACCOUNTKEY, 
            strm.MOVEINADMINHOLDBY, 
            strm.MOVEINADMINHOLDDTTM, 
            strm.MOVEINADMINHOLDREASON, 
            strm.MOVEINDATE, 
            strm.MOVEINEXCEPTION, 
            strm.MOVEINSTATUS, 
            strm.MOVEOUTADMINHOLDBY, 
            strm.MOVEOUTADMINHOLDDTTM, 
            strm.MOVEOUTADMINHOLDREASON, 
            strm.MOVEOUTDATE, 
            strm.MOVEOUTEXCEPTION, 
            strm.MOVEOUTSTATUS, 
            strm.NOARNG, 
            strm.NOBILL, 
            strm.NODISCONN, 
            strm.NONOTICE, 
            strm.NOTICEDTTM, 
            strm.NUMERICCONSVAL1, 
            strm.NUMERICCONSVAL2, 
            strm.NUMERICCONSVAL3, 
            strm.NUMERICCONSVAL4, 
            strm.NUMERICCONSVAL5, 
            strm.NUMERICCONSVAL6, 
            strm.NUMERICCONSVAL7, 
            strm.NUMERICCONSVAL8, 
            strm.OCCUPANT, 
            strm.ONEOFFCHARGEFLAG, 
            strm.OPENDATE, 
            strm.PARCELKEY, 
            strm.PENEXEMPT, 
            strm.PRESELECTEDFORBILLRUN, 
            strm.PRESELECTEDFORINTERIMBILL, 
            strm.PROPERTYKEY, 
            strm.RESPONSIBILITY, 
            strm.STATBY, 
            strm.STATDTTM, 
            strm.SUSPENDBY, 
            strm.SUSPENDDTTM, 
            strm.SUSPENDFLAG, 
            strm.TAXEXEMPTFALG, 
            strm.TRANSFERREDTO, 
            strm.VARIATION_ID, 
            strm.WRITEOFFELIGIBLEFLAG, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.ACCOUNTKEY ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_IPS_BILLING_ACCOUNT as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.ACCOUNTKEY=src.ACCOUNTKEY) OR (target.ACCOUNTKEY IS NULL AND src.ACCOUNTKEY IS NULL)) 
                when matched then update set
                    target.ACCEPTCHECKSFLAG=src.ACCEPTCHECKSFLAG, 
                    target.ACCOUNTKEY=src.ACCOUNTKEY, 
                    target.ACCOUNTNUMBER=src.ACCOUNTNUMBER, 
                    target.ACCOUNTSTATUS=src.ACCOUNTSTATUS, 
                    target.ACCOUNTTYPE=src.ACCOUNTTYPE, 
                    target.ACCTCLASS=src.ACCTCLASS, 
                    target.ACCTGRP=src.ACCTGRP, 
                    target.ACCTSUBGRP=src.ACCTSUBGRP, 
                    target.ADDBY=src.ADDBY, 
                    target.ADDDTTM=src.ADDDTTM, 
                    target.ADDRKEY=src.ADDRKEY, 
                    target.AGGREGATEFLAG=src.AGGREGATEFLAG, 
                    target.AGGREGATEKEY=src.AGGREGATEKEY, 
                    target.ALLOWARCHIVEFLAG=src.ALLOWARCHIVEFLAG, 
                    target.ALLOWCHECKOVERRIDESFLAG=src.ALLOWCHECKOVERRIDESFLAG, 
                    target.ARCHIVETHROUGHDATE=src.ARCHIVETHROUGHDATE, 
                    target.AREA=src.AREA, 
                    target.ARRANGEDFLAG=src.ARRANGEDFLAG, 
                    target.ASSIGNED=src.ASSIGNED, 
                    target.BANKRUPTFLAG=src.BANKRUPTFLAG, 
                    target.BILLINGCYCLE=src.BILLINGCYCLE, 
                    target.BILLPRINTEXCEPTION=src.BILLPRINTEXCEPTION, 
                    target.BLNGSTAT=src.BLNGSTAT, 
                    target.BLNGSTDTTM=src.BLNGSTDTTM, 
                    target.BUDGETBILLINGDISALLOWED=src.BUDGETBILLINGDISALLOWED, 
                    target.BUDGETBILLINGFLAG=src.BUDGETBILLINGFLAG, 
                    target.BUSINESSTYPE=src.BUSINESSTYPE, 
                    target.CHARCONSVAL1=src.CHARCONSVAL1, 
                    target.CHARCONSVAL2=src.CHARCONSVAL2, 
                    target.CHARCONSVAL3=src.CHARCONSVAL3, 
                    target.CHARCONSVAL4=src.CHARCONSVAL4, 
                    target.CHARCONSVAL5=src.CHARCONSVAL5, 
                    target.CHARCONSVAL6=src.CHARCONSVAL6, 
                    target.CHARCONSVAL7=src.CHARCONSVAL7, 
                    target.CHARCONSVAL8=src.CHARCONSVAL8, 
                    target.CLOSEDATE=src.CLOSEDATE, 
                    target.COLLECTIONSELIGIBLEFLAG=src.COLLECTIONSELIGIBLEFLAG, 
                    target.COLLECTIONSFLAG=src.COLLECTIONSFLAG, 
                    target.COLLEXEMPT=src.COLLEXEMPT, 
                    target.COMMENTSKEY=src.COMMENTSKEY, 
                    target.CREDFLAG=src.CREDFLAG, 
                    target.CUSTDESC=src.CUSTDESC, 
                    target.DELETED=src.DELETED, 
                    target.DELINQUENCYEXEMPT=src.DELINQUENCYEXEMPT, 
                    target.DELINQUENCYEXEMPTFLAG=src.DELINQUENCYEXEMPTFLAG, 
                    target.DELINQUENCYFLAG=src.DELINQUENCYFLAG, 
                    target.DEPPDDATE=src.DEPPDDATE, 
                    target.DONOTDIRECTDEBIT=src.DONOTDIRECTDEBIT, 
                    target.ELIGIBLEFORREFUNDFLAG=src.ELIGIBLEFORREFUNDFLAG, 
                    target.FINALBILLFLAG=src.FINALBILLFLAG, 
                    target.FREQUENCY=src.FREQUENCY, 
                    target.IDKEY=src.IDKEY, 
                    target.INITIATEDBY=src.INITIATEDBY, 
                    target.INITIATEDDTTM=src.INITIATEDDTTM, 
                    target.LEGACYACCOUNTNUMBER=src.LEGACYACCOUNTNUMBER, 
                    target.LIENELIGIBLEFLAG=src.LIENELIGIBLEFLAG, 
                    target.LIENEXEMPT=src.LIENEXEMPT, 
                    target.LIENFLAG=src.LIENFLAG, 
                    target.MODBY=src.MODBY, 
                    target.MODDTTM=src.MODDTTM, 
                    target.MOVEDOUTACCOUNTKEY=src.MOVEDOUTACCOUNTKEY, 
                    target.MOVEINADMINHOLDBY=src.MOVEINADMINHOLDBY, 
                    target.MOVEINADMINHOLDDTTM=src.MOVEINADMINHOLDDTTM, 
                    target.MOVEINADMINHOLDREASON=src.MOVEINADMINHOLDREASON, 
                    target.MOVEINDATE=src.MOVEINDATE, 
                    target.MOVEINEXCEPTION=src.MOVEINEXCEPTION, 
                    target.MOVEINSTATUS=src.MOVEINSTATUS, 
                    target.MOVEOUTADMINHOLDBY=src.MOVEOUTADMINHOLDBY, 
                    target.MOVEOUTADMINHOLDDTTM=src.MOVEOUTADMINHOLDDTTM, 
                    target.MOVEOUTADMINHOLDREASON=src.MOVEOUTADMINHOLDREASON, 
                    target.MOVEOUTDATE=src.MOVEOUTDATE, 
                    target.MOVEOUTEXCEPTION=src.MOVEOUTEXCEPTION, 
                    target.MOVEOUTSTATUS=src.MOVEOUTSTATUS, 
                    target.NOARNG=src.NOARNG, 
                    target.NOBILL=src.NOBILL, 
                    target.NODISCONN=src.NODISCONN, 
                    target.NONOTICE=src.NONOTICE, 
                    target.NOTICEDTTM=src.NOTICEDTTM, 
                    target.NUMERICCONSVAL1=src.NUMERICCONSVAL1, 
                    target.NUMERICCONSVAL2=src.NUMERICCONSVAL2, 
                    target.NUMERICCONSVAL3=src.NUMERICCONSVAL3, 
                    target.NUMERICCONSVAL4=src.NUMERICCONSVAL4, 
                    target.NUMERICCONSVAL5=src.NUMERICCONSVAL5, 
                    target.NUMERICCONSVAL6=src.NUMERICCONSVAL6, 
                    target.NUMERICCONSVAL7=src.NUMERICCONSVAL7, 
                    target.NUMERICCONSVAL8=src.NUMERICCONSVAL8, 
                    target.OCCUPANT=src.OCCUPANT, 
                    target.ONEOFFCHARGEFLAG=src.ONEOFFCHARGEFLAG, 
                    target.OPENDATE=src.OPENDATE, 
                    target.PARCELKEY=src.PARCELKEY, 
                    target.PENEXEMPT=src.PENEXEMPT, 
                    target.PRESELECTEDFORBILLRUN=src.PRESELECTEDFORBILLRUN, 
                    target.PRESELECTEDFORINTERIMBILL=src.PRESELECTEDFORINTERIMBILL, 
                    target.PROPERTYKEY=src.PROPERTYKEY, 
                    target.RESPONSIBILITY=src.RESPONSIBILITY, 
                    target.STATBY=src.STATBY, 
                    target.STATDTTM=src.STATDTTM, 
                    target.SUSPENDBY=src.SUSPENDBY, 
                    target.SUSPENDDTTM=src.SUSPENDDTTM, 
                    target.SUSPENDFLAG=src.SUSPENDFLAG, 
                    target.TAXEXEMPTFALG=src.TAXEXEMPTFALG, 
                    target.TRANSFERREDTO=src.TRANSFERREDTO, 
                    target.VARIATION_ID=src.VARIATION_ID, 
                    target.WRITEOFFELIGIBLEFLAG=src.WRITEOFFELIGIBLEFLAG, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( ACCEPTCHECKSFLAG, ACCOUNTKEY, ACCOUNTNUMBER, ACCOUNTSTATUS, ACCOUNTTYPE, ACCTCLASS, ACCTGRP, ACCTSUBGRP, ADDBY, ADDDTTM, ADDRKEY, AGGREGATEFLAG, AGGREGATEKEY, ALLOWARCHIVEFLAG, ALLOWCHECKOVERRIDESFLAG, ARCHIVETHROUGHDATE, AREA, ARRANGEDFLAG, ASSIGNED, BANKRUPTFLAG, BILLINGCYCLE, BILLPRINTEXCEPTION, BLNGSTAT, BLNGSTDTTM, BUDGETBILLINGDISALLOWED, BUDGETBILLINGFLAG, BUSINESSTYPE, CHARCONSVAL1, CHARCONSVAL2, CHARCONSVAL3, CHARCONSVAL4, CHARCONSVAL5, CHARCONSVAL6, CHARCONSVAL7, CHARCONSVAL8, CLOSEDATE, COLLECTIONSELIGIBLEFLAG, COLLECTIONSFLAG, COLLEXEMPT, COMMENTSKEY, CREDFLAG, CUSTDESC, DELETED, DELINQUENCYEXEMPT, DELINQUENCYEXEMPTFLAG, DELINQUENCYFLAG, DEPPDDATE, DONOTDIRECTDEBIT, ELIGIBLEFORREFUNDFLAG, FINALBILLFLAG, FREQUENCY, IDKEY, INITIATEDBY, INITIATEDDTTM, LEGACYACCOUNTNUMBER, LIENELIGIBLEFLAG, LIENEXEMPT, LIENFLAG, MODBY, MODDTTM, MOVEDOUTACCOUNTKEY, MOVEINADMINHOLDBY, MOVEINADMINHOLDDTTM, MOVEINADMINHOLDREASON, MOVEINDATE, MOVEINEXCEPTION, MOVEINSTATUS, MOVEOUTADMINHOLDBY, MOVEOUTADMINHOLDDTTM, MOVEOUTADMINHOLDREASON, MOVEOUTDATE, MOVEOUTEXCEPTION, MOVEOUTSTATUS, NOARNG, NOBILL, NODISCONN, NONOTICE, NOTICEDTTM, NUMERICCONSVAL1, NUMERICCONSVAL2, NUMERICCONSVAL3, NUMERICCONSVAL4, NUMERICCONSVAL5, NUMERICCONSVAL6, NUMERICCONSVAL7, NUMERICCONSVAL8, OCCUPANT, ONEOFFCHARGEFLAG, OPENDATE, PARCELKEY, PENEXEMPT, PRESELECTEDFORBILLRUN, PRESELECTEDFORINTERIMBILL, PROPERTYKEY, RESPONSIBILITY, STATBY, STATDTTM, SUSPENDBY, SUSPENDDTTM, SUSPENDFLAG, TAXEXEMPTFALG, TRANSFERREDTO, VARIATION_ID, WRITEOFFELIGIBLEFLAG, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.ACCEPTCHECKSFLAG, 
                    src.ACCOUNTKEY, 
                    src.ACCOUNTNUMBER, 
                    src.ACCOUNTSTATUS, 
                    src.ACCOUNTTYPE, 
                    src.ACCTCLASS, 
                    src.ACCTGRP, 
                    src.ACCTSUBGRP, 
                    src.ADDBY, 
                    src.ADDDTTM, 
                    src.ADDRKEY, 
                    src.AGGREGATEFLAG, 
                    src.AGGREGATEKEY, 
                    src.ALLOWARCHIVEFLAG, 
                    src.ALLOWCHECKOVERRIDESFLAG, 
                    src.ARCHIVETHROUGHDATE, 
                    src.AREA, 
                    src.ARRANGEDFLAG, 
                    src.ASSIGNED, 
                    src.BANKRUPTFLAG, 
                    src.BILLINGCYCLE, 
                    src.BILLPRINTEXCEPTION, 
                    src.BLNGSTAT, 
                    src.BLNGSTDTTM, 
                    src.BUDGETBILLINGDISALLOWED, 
                    src.BUDGETBILLINGFLAG, 
                    src.BUSINESSTYPE, 
                    src.CHARCONSVAL1, 
                    src.CHARCONSVAL2, 
                    src.CHARCONSVAL3, 
                    src.CHARCONSVAL4, 
                    src.CHARCONSVAL5, 
                    src.CHARCONSVAL6, 
                    src.CHARCONSVAL7, 
                    src.CHARCONSVAL8, 
                    src.CLOSEDATE, 
                    src.COLLECTIONSELIGIBLEFLAG, 
                    src.COLLECTIONSFLAG, 
                    src.COLLEXEMPT, 
                    src.COMMENTSKEY, 
                    src.CREDFLAG, 
                    src.CUSTDESC, 
                    src.DELETED, 
                    src.DELINQUENCYEXEMPT, 
                    src.DELINQUENCYEXEMPTFLAG, 
                    src.DELINQUENCYFLAG, 
                    src.DEPPDDATE, 
                    src.DONOTDIRECTDEBIT, 
                    src.ELIGIBLEFORREFUNDFLAG, 
                    src.FINALBILLFLAG, 
                    src.FREQUENCY, 
                    src.IDKEY, 
                    src.INITIATEDBY, 
                    src.INITIATEDDTTM, 
                    src.LEGACYACCOUNTNUMBER, 
                    src.LIENELIGIBLEFLAG, 
                    src.LIENEXEMPT, 
                    src.LIENFLAG, 
                    src.MODBY, 
                    src.MODDTTM, 
                    src.MOVEDOUTACCOUNTKEY, 
                    src.MOVEINADMINHOLDBY, 
                    src.MOVEINADMINHOLDDTTM, 
                    src.MOVEINADMINHOLDREASON, 
                    src.MOVEINDATE, 
                    src.MOVEINEXCEPTION, 
                    src.MOVEINSTATUS, 
                    src.MOVEOUTADMINHOLDBY, 
                    src.MOVEOUTADMINHOLDDTTM, 
                    src.MOVEOUTADMINHOLDREASON, 
                    src.MOVEOUTDATE, 
                    src.MOVEOUTEXCEPTION, 
                    src.MOVEOUTSTATUS, 
                    src.NOARNG, 
                    src.NOBILL, 
                    src.NODISCONN, 
                    src.NONOTICE, 
                    src.NOTICEDTTM, 
                    src.NUMERICCONSVAL1, 
                    src.NUMERICCONSVAL2, 
                    src.NUMERICCONSVAL3, 
                    src.NUMERICCONSVAL4, 
                    src.NUMERICCONSVAL5, 
                    src.NUMERICCONSVAL6, 
                    src.NUMERICCONSVAL7, 
                    src.NUMERICCONSVAL8, 
                    src.OCCUPANT, 
                    src.ONEOFFCHARGEFLAG, 
                    src.OPENDATE, 
                    src.PARCELKEY, 
                    src.PENEXEMPT, 
                    src.PRESELECTEDFORBILLRUN, 
                    src.PRESELECTEDFORINTERIMBILL, 
                    src.PROPERTYKEY, 
                    src.RESPONSIBILITY, 
                    src.STATBY, 
                    src.STATDTTM, 
                    src.SUSPENDBY, 
                    src.SUSPENDDTTM, 
                    src.SUSPENDFLAG, 
                    src.TAXEXEMPTFALG, 
                    src.TRANSFERREDTO, 
                    src.VARIATION_ID, 
                    src.WRITEOFFELIGIBLEFLAG,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;