create or replace TRANSIENT TABLE STG_DIM_BILL_RUN (
	BILL_RUN_KEY NUMBER(38,0),
	NUMBER_OF_BILLS_IN_RUN NUMBER(38,0),
	NUMBER_OF_EXCEPTIONS NUMBER(38,0),
	BILL_RUN_POSTED_FLAG VARCHAR(1),
	BILL_RUN_ADDED_DATE TIMESTAMP_NTZ(9),
	BILL_RUN_BILLING_CYCLE VARCHAR(20),
	PRINCIPAL_TOTAL NUMBER(38,4),
	BILLING_PERIOD_FROM_DATE TIMESTAMP_NTZ(9),
	BILLING_PERIOD_TO_DATE TIMESTAMP_NTZ(9),
	BILLING_STATUS VARCHAR(10),
	BILL_RUN_DESCRIPTION VARCHAR(300),
	RUN_TYPE VARCHAR(1),
	TOTAL_NUMBER_OF_BILLS NUMBER(38,0),
	ETL_SOURCE_DATETIME TIMESTAMP_NTZ(9),
	ETL_RECORD_CREATED TIMESTAMP_NTZ(9),
	ETL_RECORD_UPDATED TIMESTAMP_NTZ(9)
);