create or replace procedure DATAHUB_INTEGRATION.SP_LN_TDSLS300()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TDSLS300_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TDSLS300 as target using (SELECT * FROM (SELECT 
            strm.adco, 
            strm.adco_kw, 
            strm.aeco, 
            strm.aeco_kw, 
            strm.bpcl, 
            strm.bpcl_ref_compnr, 
            strm.ccrf, 
            strm.ccrs, 
            strm.ccrs_ref_compnr, 
            strm.ccty, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.cdat, 
            strm.cdec, 
            strm.cdec_ref_compnr, 
            strm.cdes, 
            strm.cfrw, 
            strm.cfrw_ref_compnr, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.cono, 
            strm.corn, 
            strm.cpay, 
            strm.cpay_ref_compnr, 
            strm.crep, 
            strm.crep_ref_compnr, 
            strm.csts, 
            strm.csts_kw, 
            strm.cvyn, 
            strm.cvyn_kw, 
            strm.deleted, 
            strm.edat, 
            strm.hval, 
            strm.hval_kw, 
            strm.icap, 
            strm.icap_kw, 
            strm.icpr, 
            strm.icpr_kw, 
            strm.icyp, 
            strm.icyp_kw, 
            strm.itad, 
            strm.itad_ref_compnr, 
            strm.itbp, 
            strm.itbp_ref_compnr, 
            strm.itcn, 
            strm.itcn_ref_compnr, 
            strm.ocon, 
            strm.ocon_ref_compnr, 
            strm.ofad, 
            strm.ofad_ref_compnr, 
            strm.ofbp, 
            strm.ofbp_ref_compnr, 
            strm.ofcn, 
            strm.ofcn_ref_compnr, 
            strm.osrp, 
            strm.osrp_ref_compnr, 
            strm.paym, 
            strm.pfad, 
            strm.pfad_ref_compnr, 
            strm.pfbp, 
            strm.pfbp_ref_compnr, 
            strm.pfcn, 
            strm.pfcn_ref_compnr, 
            strm.ptpa, 
            strm.ptpa_ref_compnr, 
            strm.refb, 
            strm.refe, 
            strm.rofc, 
            strm.rofc_ref_compnr, 
            strm.sdat, 
            strm.sequencenumber, 
            strm.sotp, 
            strm.sotp_ref_compnr, 
            strm.stad, 
            strm.stad_ref_compnr, 
            strm.stbp, 
            strm.stbp_ref_compnr, 
            strm.stcn, 
            strm.stcn_ref_compnr, 
            strm.timestamp, 
            strm.trid, 
            strm.trid_ref_compnr, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.txtb, 
            strm.txtb_ref_compnr, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.cono ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDSLS300 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.cono=src.cono) OR (target.cono IS NULL AND src.cono IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.adco=src.adco, 
                    target.adco_kw=src.adco_kw, 
                    target.aeco=src.aeco, 
                    target.aeco_kw=src.aeco_kw, 
                    target.bpcl=src.bpcl, 
                    target.bpcl_ref_compnr=src.bpcl_ref_compnr, 
                    target.ccrf=src.ccrf, 
                    target.ccrs=src.ccrs, 
                    target.ccrs_ref_compnr=src.ccrs_ref_compnr, 
                    target.ccty=src.ccty, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.cdat=src.cdat, 
                    target.cdec=src.cdec, 
                    target.cdec_ref_compnr=src.cdec_ref_compnr, 
                    target.cdes=src.cdes, 
                    target.cfrw=src.cfrw, 
                    target.cfrw_ref_compnr=src.cfrw_ref_compnr, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cono=src.cono, 
                    target.corn=src.corn, 
                    target.cpay=src.cpay, 
                    target.cpay_ref_compnr=src.cpay_ref_compnr, 
                    target.crep=src.crep, 
                    target.crep_ref_compnr=src.crep_ref_compnr, 
                    target.csts=src.csts, 
                    target.csts_kw=src.csts_kw, 
                    target.cvyn=src.cvyn, 
                    target.cvyn_kw=src.cvyn_kw, 
                    target.deleted=src.deleted, 
                    target.edat=src.edat, 
                    target.hval=src.hval, 
                    target.hval_kw=src.hval_kw, 
                    target.icap=src.icap, 
                    target.icap_kw=src.icap_kw, 
                    target.icpr=src.icpr, 
                    target.icpr_kw=src.icpr_kw, 
                    target.icyp=src.icyp, 
                    target.icyp_kw=src.icyp_kw, 
                    target.itad=src.itad, 
                    target.itad_ref_compnr=src.itad_ref_compnr, 
                    target.itbp=src.itbp, 
                    target.itbp_ref_compnr=src.itbp_ref_compnr, 
                    target.itcn=src.itcn, 
                    target.itcn_ref_compnr=src.itcn_ref_compnr, 
                    target.ocon=src.ocon, 
                    target.ocon_ref_compnr=src.ocon_ref_compnr, 
                    target.ofad=src.ofad, 
                    target.ofad_ref_compnr=src.ofad_ref_compnr, 
                    target.ofbp=src.ofbp, 
                    target.ofbp_ref_compnr=src.ofbp_ref_compnr, 
                    target.ofcn=src.ofcn, 
                    target.ofcn_ref_compnr=src.ofcn_ref_compnr, 
                    target.osrp=src.osrp, 
                    target.osrp_ref_compnr=src.osrp_ref_compnr, 
                    target.paym=src.paym, 
                    target.pfad=src.pfad, 
                    target.pfad_ref_compnr=src.pfad_ref_compnr, 
                    target.pfbp=src.pfbp, 
                    target.pfbp_ref_compnr=src.pfbp_ref_compnr, 
                    target.pfcn=src.pfcn, 
                    target.pfcn_ref_compnr=src.pfcn_ref_compnr, 
                    target.ptpa=src.ptpa, 
                    target.ptpa_ref_compnr=src.ptpa_ref_compnr, 
                    target.refb=src.refb, 
                    target.refe=src.refe, 
                    target.rofc=src.rofc, 
                    target.rofc_ref_compnr=src.rofc_ref_compnr, 
                    target.sdat=src.sdat, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sotp=src.sotp, 
                    target.sotp_ref_compnr=src.sotp_ref_compnr, 
                    target.stad=src.stad, 
                    target.stad_ref_compnr=src.stad_ref_compnr, 
                    target.stbp=src.stbp, 
                    target.stbp_ref_compnr=src.stbp_ref_compnr, 
                    target.stcn=src.stcn, 
                    target.stcn_ref_compnr=src.stcn_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.trid=src.trid, 
                    target.trid_ref_compnr=src.trid_ref_compnr, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.txtb=src.txtb, 
                    target.txtb_ref_compnr=src.txtb_ref_compnr, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    adco, 
                    adco_kw, 
                    aeco, 
                    aeco_kw, 
                    bpcl, 
                    bpcl_ref_compnr, 
                    ccrf, 
                    ccrs, 
                    ccrs_ref_compnr, 
                    ccty, 
                    ccur, 
                    ccur_ref_compnr, 
                    cdat, 
                    cdec, 
                    cdec_ref_compnr, 
                    cdes, 
                    cfrw, 
                    cfrw_ref_compnr, 
                    cofc, 
                    cofc_ref_compnr, 
                    compnr, 
                    cono, 
                    corn, 
                    cpay, 
                    cpay_ref_compnr, 
                    crep, 
                    crep_ref_compnr, 
                    csts, 
                    csts_kw, 
                    cvyn, 
                    cvyn_kw, 
                    deleted, 
                    edat, 
                    hval, 
                    hval_kw, 
                    icap, 
                    icap_kw, 
                    icpr, 
                    icpr_kw, 
                    icyp, 
                    icyp_kw, 
                    itad, 
                    itad_ref_compnr, 
                    itbp, 
                    itbp_ref_compnr, 
                    itcn, 
                    itcn_ref_compnr, 
                    ocon, 
                    ocon_ref_compnr, 
                    ofad, 
                    ofad_ref_compnr, 
                    ofbp, 
                    ofbp_ref_compnr, 
                    ofcn, 
                    ofcn_ref_compnr, 
                    osrp, 
                    osrp_ref_compnr, 
                    paym, 
                    pfad, 
                    pfad_ref_compnr, 
                    pfbp, 
                    pfbp_ref_compnr, 
                    pfcn, 
                    pfcn_ref_compnr, 
                    ptpa, 
                    ptpa_ref_compnr, 
                    refb, 
                    refe, 
                    rofc, 
                    rofc_ref_compnr, 
                    sdat, 
                    sequencenumber, 
                    sotp, 
                    sotp_ref_compnr, 
                    stad, 
                    stad_ref_compnr, 
                    stbp, 
                    stbp_ref_compnr, 
                    stcn, 
                    stcn_ref_compnr, 
                    timestamp, 
                    trid, 
                    trid_ref_compnr, 
                    txta, 
                    txta_ref_compnr, 
                    txtb, 
                    txtb_ref_compnr, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.adco, 
                    src.adco_kw, 
                    src.aeco, 
                    src.aeco_kw, 
                    src.bpcl, 
                    src.bpcl_ref_compnr, 
                    src.ccrf, 
                    src.ccrs, 
                    src.ccrs_ref_compnr, 
                    src.ccty, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.cdat, 
                    src.cdec, 
                    src.cdec_ref_compnr, 
                    src.cdes, 
                    src.cfrw, 
                    src.cfrw_ref_compnr, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.cono, 
                    src.corn, 
                    src.cpay, 
                    src.cpay_ref_compnr, 
                    src.crep, 
                    src.crep_ref_compnr, 
                    src.csts, 
                    src.csts_kw, 
                    src.cvyn, 
                    src.cvyn_kw, 
                    src.deleted, 
                    src.edat, 
                    src.hval, 
                    src.hval_kw, 
                    src.icap, 
                    src.icap_kw, 
                    src.icpr, 
                    src.icpr_kw, 
                    src.icyp, 
                    src.icyp_kw, 
                    src.itad, 
                    src.itad_ref_compnr, 
                    src.itbp, 
                    src.itbp_ref_compnr, 
                    src.itcn, 
                    src.itcn_ref_compnr, 
                    src.ocon, 
                    src.ocon_ref_compnr, 
                    src.ofad, 
                    src.ofad_ref_compnr, 
                    src.ofbp, 
                    src.ofbp_ref_compnr, 
                    src.ofcn, 
                    src.ofcn_ref_compnr, 
                    src.osrp, 
                    src.osrp_ref_compnr, 
                    src.paym, 
                    src.pfad, 
                    src.pfad_ref_compnr, 
                    src.pfbp, 
                    src.pfbp_ref_compnr, 
                    src.pfcn, 
                    src.pfcn_ref_compnr, 
                    src.ptpa, 
                    src.ptpa_ref_compnr, 
                    src.refb, 
                    src.refe, 
                    src.rofc, 
                    src.rofc_ref_compnr, 
                    src.sdat, 
                    src.sequencenumber, 
                    src.sotp, 
                    src.sotp_ref_compnr, 
                    src.stad, 
                    src.stad_ref_compnr, 
                    src.stbp, 
                    src.stbp_ref_compnr, 
                    src.stcn, 
                    src.stcn_ref_compnr, 
                    src.timestamp, 
                    src.trid, 
                    src.trid_ref_compnr, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.txtb, 
                    src.txtb_ref_compnr, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TDSLS300_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.adco, 
            strm.adco_kw, 
            strm.aeco, 
            strm.aeco_kw, 
            strm.bpcl, 
            strm.bpcl_ref_compnr, 
            strm.ccrf, 
            strm.ccrs, 
            strm.ccrs_ref_compnr, 
            strm.ccty, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.cdat, 
            strm.cdec, 
            strm.cdec_ref_compnr, 
            strm.cdes, 
            strm.cfrw, 
            strm.cfrw_ref_compnr, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.cono, 
            strm.corn, 
            strm.cpay, 
            strm.cpay_ref_compnr, 
            strm.crep, 
            strm.crep_ref_compnr, 
            strm.csts, 
            strm.csts_kw, 
            strm.cvyn, 
            strm.cvyn_kw, 
            strm.deleted, 
            strm.edat, 
            strm.hval, 
            strm.hval_kw, 
            strm.icap, 
            strm.icap_kw, 
            strm.icpr, 
            strm.icpr_kw, 
            strm.icyp, 
            strm.icyp_kw, 
            strm.itad, 
            strm.itad_ref_compnr, 
            strm.itbp, 
            strm.itbp_ref_compnr, 
            strm.itcn, 
            strm.itcn_ref_compnr, 
            strm.ocon, 
            strm.ocon_ref_compnr, 
            strm.ofad, 
            strm.ofad_ref_compnr, 
            strm.ofbp, 
            strm.ofbp_ref_compnr, 
            strm.ofcn, 
            strm.ofcn_ref_compnr, 
            strm.osrp, 
            strm.osrp_ref_compnr, 
            strm.paym, 
            strm.pfad, 
            strm.pfad_ref_compnr, 
            strm.pfbp, 
            strm.pfbp_ref_compnr, 
            strm.pfcn, 
            strm.pfcn_ref_compnr, 
            strm.ptpa, 
            strm.ptpa_ref_compnr, 
            strm.refb, 
            strm.refe, 
            strm.rofc, 
            strm.rofc_ref_compnr, 
            strm.sdat, 
            strm.sequencenumber, 
            strm.sotp, 
            strm.sotp_ref_compnr, 
            strm.stad, 
            strm.stad_ref_compnr, 
            strm.stbp, 
            strm.stbp_ref_compnr, 
            strm.stcn, 
            strm.stcn_ref_compnr, 
            strm.timestamp, 
            strm.trid, 
            strm.trid_ref_compnr, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.txtb, 
            strm.txtb_ref_compnr, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.cono ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDSLS300 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.cono=src.cono) OR (target.cono IS NULL AND src.cono IS NULL)) 
                when matched then update set
                    target.adco=src.adco, 
                    target.adco_kw=src.adco_kw, 
                    target.aeco=src.aeco, 
                    target.aeco_kw=src.aeco_kw, 
                    target.bpcl=src.bpcl, 
                    target.bpcl_ref_compnr=src.bpcl_ref_compnr, 
                    target.ccrf=src.ccrf, 
                    target.ccrs=src.ccrs, 
                    target.ccrs_ref_compnr=src.ccrs_ref_compnr, 
                    target.ccty=src.ccty, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.cdat=src.cdat, 
                    target.cdec=src.cdec, 
                    target.cdec_ref_compnr=src.cdec_ref_compnr, 
                    target.cdes=src.cdes, 
                    target.cfrw=src.cfrw, 
                    target.cfrw_ref_compnr=src.cfrw_ref_compnr, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cono=src.cono, 
                    target.corn=src.corn, 
                    target.cpay=src.cpay, 
                    target.cpay_ref_compnr=src.cpay_ref_compnr, 
                    target.crep=src.crep, 
                    target.crep_ref_compnr=src.crep_ref_compnr, 
                    target.csts=src.csts, 
                    target.csts_kw=src.csts_kw, 
                    target.cvyn=src.cvyn, 
                    target.cvyn_kw=src.cvyn_kw, 
                    target.deleted=src.deleted, 
                    target.edat=src.edat, 
                    target.hval=src.hval, 
                    target.hval_kw=src.hval_kw, 
                    target.icap=src.icap, 
                    target.icap_kw=src.icap_kw, 
                    target.icpr=src.icpr, 
                    target.icpr_kw=src.icpr_kw, 
                    target.icyp=src.icyp, 
                    target.icyp_kw=src.icyp_kw, 
                    target.itad=src.itad, 
                    target.itad_ref_compnr=src.itad_ref_compnr, 
                    target.itbp=src.itbp, 
                    target.itbp_ref_compnr=src.itbp_ref_compnr, 
                    target.itcn=src.itcn, 
                    target.itcn_ref_compnr=src.itcn_ref_compnr, 
                    target.ocon=src.ocon, 
                    target.ocon_ref_compnr=src.ocon_ref_compnr, 
                    target.ofad=src.ofad, 
                    target.ofad_ref_compnr=src.ofad_ref_compnr, 
                    target.ofbp=src.ofbp, 
                    target.ofbp_ref_compnr=src.ofbp_ref_compnr, 
                    target.ofcn=src.ofcn, 
                    target.ofcn_ref_compnr=src.ofcn_ref_compnr, 
                    target.osrp=src.osrp, 
                    target.osrp_ref_compnr=src.osrp_ref_compnr, 
                    target.paym=src.paym, 
                    target.pfad=src.pfad, 
                    target.pfad_ref_compnr=src.pfad_ref_compnr, 
                    target.pfbp=src.pfbp, 
                    target.pfbp_ref_compnr=src.pfbp_ref_compnr, 
                    target.pfcn=src.pfcn, 
                    target.pfcn_ref_compnr=src.pfcn_ref_compnr, 
                    target.ptpa=src.ptpa, 
                    target.ptpa_ref_compnr=src.ptpa_ref_compnr, 
                    target.refb=src.refb, 
                    target.refe=src.refe, 
                    target.rofc=src.rofc, 
                    target.rofc_ref_compnr=src.rofc_ref_compnr, 
                    target.sdat=src.sdat, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sotp=src.sotp, 
                    target.sotp_ref_compnr=src.sotp_ref_compnr, 
                    target.stad=src.stad, 
                    target.stad_ref_compnr=src.stad_ref_compnr, 
                    target.stbp=src.stbp, 
                    target.stbp_ref_compnr=src.stbp_ref_compnr, 
                    target.stcn=src.stcn, 
                    target.stcn_ref_compnr=src.stcn_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.trid=src.trid, 
                    target.trid_ref_compnr=src.trid_ref_compnr, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.txtb=src.txtb, 
                    target.txtb_ref_compnr=src.txtb_ref_compnr, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( adco, adco_kw, aeco, aeco_kw, bpcl, bpcl_ref_compnr, ccrf, ccrs, ccrs_ref_compnr, ccty, ccur, ccur_ref_compnr, cdat, cdec, cdec_ref_compnr, cdes, cfrw, cfrw_ref_compnr, cofc, cofc_ref_compnr, compnr, cono, corn, cpay, cpay_ref_compnr, crep, crep_ref_compnr, csts, csts_kw, cvyn, cvyn_kw, deleted, edat, hval, hval_kw, icap, icap_kw, icpr, icpr_kw, icyp, icyp_kw, itad, itad_ref_compnr, itbp, itbp_ref_compnr, itcn, itcn_ref_compnr, ocon, ocon_ref_compnr, ofad, ofad_ref_compnr, ofbp, ofbp_ref_compnr, ofcn, ofcn_ref_compnr, osrp, osrp_ref_compnr, paym, pfad, pfad_ref_compnr, pfbp, pfbp_ref_compnr, pfcn, pfcn_ref_compnr, ptpa, ptpa_ref_compnr, refb, refe, rofc, rofc_ref_compnr, sdat, sequencenumber, sotp, sotp_ref_compnr, stad, stad_ref_compnr, stbp, stbp_ref_compnr, stcn, stcn_ref_compnr, timestamp, trid, trid_ref_compnr, txta, txta_ref_compnr, txtb, txtb_ref_compnr, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.adco, 
                    src.adco_kw, 
                    src.aeco, 
                    src.aeco_kw, 
                    src.bpcl, 
                    src.bpcl_ref_compnr, 
                    src.ccrf, 
                    src.ccrs, 
                    src.ccrs_ref_compnr, 
                    src.ccty, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.cdat, 
                    src.cdec, 
                    src.cdec_ref_compnr, 
                    src.cdes, 
                    src.cfrw, 
                    src.cfrw_ref_compnr, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.cono, 
                    src.corn, 
                    src.cpay, 
                    src.cpay_ref_compnr, 
                    src.crep, 
                    src.crep_ref_compnr, 
                    src.csts, 
                    src.csts_kw, 
                    src.cvyn, 
                    src.cvyn_kw, 
                    src.deleted, 
                    src.edat, 
                    src.hval, 
                    src.hval_kw, 
                    src.icap, 
                    src.icap_kw, 
                    src.icpr, 
                    src.icpr_kw, 
                    src.icyp, 
                    src.icyp_kw, 
                    src.itad, 
                    src.itad_ref_compnr, 
                    src.itbp, 
                    src.itbp_ref_compnr, 
                    src.itcn, 
                    src.itcn_ref_compnr, 
                    src.ocon, 
                    src.ocon_ref_compnr, 
                    src.ofad, 
                    src.ofad_ref_compnr, 
                    src.ofbp, 
                    src.ofbp_ref_compnr, 
                    src.ofcn, 
                    src.ofcn_ref_compnr, 
                    src.osrp, 
                    src.osrp_ref_compnr, 
                    src.paym, 
                    src.pfad, 
                    src.pfad_ref_compnr, 
                    src.pfbp, 
                    src.pfbp_ref_compnr, 
                    src.pfcn, 
                    src.pfcn_ref_compnr, 
                    src.ptpa, 
                    src.ptpa_ref_compnr, 
                    src.refb, 
                    src.refe, 
                    src.rofc, 
                    src.rofc_ref_compnr, 
                    src.sdat, 
                    src.sequencenumber, 
                    src.sotp, 
                    src.sotp_ref_compnr, 
                    src.stad, 
                    src.stad_ref_compnr, 
                    src.stbp, 
                    src.stbp_ref_compnr, 
                    src.stcn, 
                    src.stcn_ref_compnr, 
                    src.timestamp, 
                    src.trid, 
                    src.trid_ref_compnr, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.txtb, 
                    src.txtb_ref_compnr, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;