create or replace procedure DATAHUB_INTEGRATION.SP_LN_TPPPC000()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TPPPC000_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TPPPC000 as target using (SELECT * FROM (SELECT 
            strm.amoc, 
            strm.amoc_kw, 
            strm.amor, 
            strm.amor_kw, 
            strm.amos, 
            strm.amos_kw, 
            strm.antp, 
            strm.antp_kw, 
            strm.awpp, 
            strm.awpp_kw, 
            strm.casc, 
            strm.casc_ref_compnr, 
            strm.casd, 
            strm.casd_ref_compnr, 
            strm.ccap, 
            strm.ccap_kw, 
            strm.cint, 
            strm.cint_kw, 
            strm.cmif, 
            strm.cmif_kw, 
            strm.compnr, 
            strm.copr, 
            strm.copr_kw, 
            strm.cprp, 
            strm.cprp_kw, 
            strm.cptc, 
            strm.cptc_ref_compnr, 
            strm.cptc_year_peri_ref_compnr, 
            strm.cptf, 
            strm.cptf_ref_compnr, 
            strm.cpth, 
            strm.cpth_hyea_hper_ref_compnr, 
            strm.cpth_ref_compnr, 
            strm.dcic, 
            strm.dcic_ref_compnr, 
            strm.deleted, 
            strm.dequ, 
            strm.dequ_ref_compnr, 
            strm.dfrt, 
            strm.dfrt_ref_compnr, 
            strm.dhlp, 
            strm.dhlp_ref_compnr, 
            strm.ditm, 
            strm.ditm_ref_compnr, 
            strm.dsca, 
            strm.dsub, 
            strm.dsub_ref_compnr, 
            strm.dtrl, 
            strm.dtrl_ref_compnr, 
            strm.expc, 
            strm.expc_kw, 
            strm.hper, 
            strm.hyea, 
            strm.indt, 
            strm.ipcs, 
            strm.ipcs_kw, 
            strm.ipiw, 
            strm.ipiw_kw, 
            strm.lfcm, 
            strm.lfcm_kw, 
            strm.mcpr, 
            strm.mcpr_kw, 
            strm.mfcr, 
            strm.mfcr_kw, 
            strm.pacc, 
            strm.pacc_kw, 
            strm.peri, 
            strm.pfpp, 
            strm.pfpp_kw, 
            strm.pgth, 
            strm.pgth_kw, 
            strm.ppht, 
            strm.ppht_kw, 
            strm.prhr, 
            strm.prhr_kw, 
            strm.qacc, 
            strm.qacc_kw, 
            strm.revr, 
            strm.revr_kw, 
            strm.scev, 
            strm.scev_kw, 
            strm.sequencenumber, 
            strm.text, 
            strm.text_ref_compnr, 
            strm.timestamp, 
            strm.tohc, 
            strm.tohc_kw, 
            strm.tsem, 
            strm.tsem_ref_compnr, 
            strm.tstk, 
            strm.tstk_ref_compnr, 
            strm.upsa, 
            strm.upsa_kw, 
            strm.urcc, 
            strm.urcc_kw, 
            strm.username, 
            strm.year, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.indt ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPPC000 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.indt=src.indt) OR (target.indt IS NULL AND src.indt IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.amoc=src.amoc, 
                    target.amoc_kw=src.amoc_kw, 
                    target.amor=src.amor, 
                    target.amor_kw=src.amor_kw, 
                    target.amos=src.amos, 
                    target.amos_kw=src.amos_kw, 
                    target.antp=src.antp, 
                    target.antp_kw=src.antp_kw, 
                    target.awpp=src.awpp, 
                    target.awpp_kw=src.awpp_kw, 
                    target.casc=src.casc, 
                    target.casc_ref_compnr=src.casc_ref_compnr, 
                    target.casd=src.casd, 
                    target.casd_ref_compnr=src.casd_ref_compnr, 
                    target.ccap=src.ccap, 
                    target.ccap_kw=src.ccap_kw, 
                    target.cint=src.cint, 
                    target.cint_kw=src.cint_kw, 
                    target.cmif=src.cmif, 
                    target.cmif_kw=src.cmif_kw, 
                    target.compnr=src.compnr, 
                    target.copr=src.copr, 
                    target.copr_kw=src.copr_kw, 
                    target.cprp=src.cprp, 
                    target.cprp_kw=src.cprp_kw, 
                    target.cptc=src.cptc, 
                    target.cptc_ref_compnr=src.cptc_ref_compnr, 
                    target.cptc_year_peri_ref_compnr=src.cptc_year_peri_ref_compnr, 
                    target.cptf=src.cptf, 
                    target.cptf_ref_compnr=src.cptf_ref_compnr, 
                    target.cpth=src.cpth, 
                    target.cpth_hyea_hper_ref_compnr=src.cpth_hyea_hper_ref_compnr, 
                    target.cpth_ref_compnr=src.cpth_ref_compnr, 
                    target.dcic=src.dcic, 
                    target.dcic_ref_compnr=src.dcic_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dequ=src.dequ, 
                    target.dequ_ref_compnr=src.dequ_ref_compnr, 
                    target.dfrt=src.dfrt, 
                    target.dfrt_ref_compnr=src.dfrt_ref_compnr, 
                    target.dhlp=src.dhlp, 
                    target.dhlp_ref_compnr=src.dhlp_ref_compnr, 
                    target.ditm=src.ditm, 
                    target.ditm_ref_compnr=src.ditm_ref_compnr, 
                    target.dsca=src.dsca, 
                    target.dsub=src.dsub, 
                    target.dsub_ref_compnr=src.dsub_ref_compnr, 
                    target.dtrl=src.dtrl, 
                    target.dtrl_ref_compnr=src.dtrl_ref_compnr, 
                    target.expc=src.expc, 
                    target.expc_kw=src.expc_kw, 
                    target.hper=src.hper, 
                    target.hyea=src.hyea, 
                    target.indt=src.indt, 
                    target.ipcs=src.ipcs, 
                    target.ipcs_kw=src.ipcs_kw, 
                    target.ipiw=src.ipiw, 
                    target.ipiw_kw=src.ipiw_kw, 
                    target.lfcm=src.lfcm, 
                    target.lfcm_kw=src.lfcm_kw, 
                    target.mcpr=src.mcpr, 
                    target.mcpr_kw=src.mcpr_kw, 
                    target.mfcr=src.mfcr, 
                    target.mfcr_kw=src.mfcr_kw, 
                    target.pacc=src.pacc, 
                    target.pacc_kw=src.pacc_kw, 
                    target.peri=src.peri, 
                    target.pfpp=src.pfpp, 
                    target.pfpp_kw=src.pfpp_kw, 
                    target.pgth=src.pgth, 
                    target.pgth_kw=src.pgth_kw, 
                    target.ppht=src.ppht, 
                    target.ppht_kw=src.ppht_kw, 
                    target.prhr=src.prhr, 
                    target.prhr_kw=src.prhr_kw, 
                    target.qacc=src.qacc, 
                    target.qacc_kw=src.qacc_kw, 
                    target.revr=src.revr, 
                    target.revr_kw=src.revr_kw, 
                    target.scev=src.scev, 
                    target.scev_kw=src.scev_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.text=src.text, 
                    target.text_ref_compnr=src.text_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.tohc=src.tohc, 
                    target.tohc_kw=src.tohc_kw, 
                    target.tsem=src.tsem, 
                    target.tsem_ref_compnr=src.tsem_ref_compnr, 
                    target.tstk=src.tstk, 
                    target.tstk_ref_compnr=src.tstk_ref_compnr, 
                    target.upsa=src.upsa, 
                    target.upsa_kw=src.upsa_kw, 
                    target.urcc=src.urcc, 
                    target.urcc_kw=src.urcc_kw, 
                    target.username=src.username, 
                    target.year=src.year, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    amoc, 
                    amoc_kw, 
                    amor, 
                    amor_kw, 
                    amos, 
                    amos_kw, 
                    antp, 
                    antp_kw, 
                    awpp, 
                    awpp_kw, 
                    casc, 
                    casc_ref_compnr, 
                    casd, 
                    casd_ref_compnr, 
                    ccap, 
                    ccap_kw, 
                    cint, 
                    cint_kw, 
                    cmif, 
                    cmif_kw, 
                    compnr, 
                    copr, 
                    copr_kw, 
                    cprp, 
                    cprp_kw, 
                    cptc, 
                    cptc_ref_compnr, 
                    cptc_year_peri_ref_compnr, 
                    cptf, 
                    cptf_ref_compnr, 
                    cpth, 
                    cpth_hyea_hper_ref_compnr, 
                    cpth_ref_compnr, 
                    dcic, 
                    dcic_ref_compnr, 
                    deleted, 
                    dequ, 
                    dequ_ref_compnr, 
                    dfrt, 
                    dfrt_ref_compnr, 
                    dhlp, 
                    dhlp_ref_compnr, 
                    ditm, 
                    ditm_ref_compnr, 
                    dsca, 
                    dsub, 
                    dsub_ref_compnr, 
                    dtrl, 
                    dtrl_ref_compnr, 
                    expc, 
                    expc_kw, 
                    hper, 
                    hyea, 
                    indt, 
                    ipcs, 
                    ipcs_kw, 
                    ipiw, 
                    ipiw_kw, 
                    lfcm, 
                    lfcm_kw, 
                    mcpr, 
                    mcpr_kw, 
                    mfcr, 
                    mfcr_kw, 
                    pacc, 
                    pacc_kw, 
                    peri, 
                    pfpp, 
                    pfpp_kw, 
                    pgth, 
                    pgth_kw, 
                    ppht, 
                    ppht_kw, 
                    prhr, 
                    prhr_kw, 
                    qacc, 
                    qacc_kw, 
                    revr, 
                    revr_kw, 
                    scev, 
                    scev_kw, 
                    sequencenumber, 
                    text, 
                    text_ref_compnr, 
                    timestamp, 
                    tohc, 
                    tohc_kw, 
                    tsem, 
                    tsem_ref_compnr, 
                    tstk, 
                    tstk_ref_compnr, 
                    upsa, 
                    upsa_kw, 
                    urcc, 
                    urcc_kw, 
                    username, 
                    year, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.amoc, 
                    src.amoc_kw, 
                    src.amor, 
                    src.amor_kw, 
                    src.amos, 
                    src.amos_kw, 
                    src.antp, 
                    src.antp_kw, 
                    src.awpp, 
                    src.awpp_kw, 
                    src.casc, 
                    src.casc_ref_compnr, 
                    src.casd, 
                    src.casd_ref_compnr, 
                    src.ccap, 
                    src.ccap_kw, 
                    src.cint, 
                    src.cint_kw, 
                    src.cmif, 
                    src.cmif_kw, 
                    src.compnr, 
                    src.copr, 
                    src.copr_kw, 
                    src.cprp, 
                    src.cprp_kw, 
                    src.cptc, 
                    src.cptc_ref_compnr, 
                    src.cptc_year_peri_ref_compnr, 
                    src.cptf, 
                    src.cptf_ref_compnr, 
                    src.cpth, 
                    src.cpth_hyea_hper_ref_compnr, 
                    src.cpth_ref_compnr, 
                    src.dcic, 
                    src.dcic_ref_compnr, 
                    src.deleted, 
                    src.dequ, 
                    src.dequ_ref_compnr, 
                    src.dfrt, 
                    src.dfrt_ref_compnr, 
                    src.dhlp, 
                    src.dhlp_ref_compnr, 
                    src.ditm, 
                    src.ditm_ref_compnr, 
                    src.dsca, 
                    src.dsub, 
                    src.dsub_ref_compnr, 
                    src.dtrl, 
                    src.dtrl_ref_compnr, 
                    src.expc, 
                    src.expc_kw, 
                    src.hper, 
                    src.hyea, 
                    src.indt, 
                    src.ipcs, 
                    src.ipcs_kw, 
                    src.ipiw, 
                    src.ipiw_kw, 
                    src.lfcm, 
                    src.lfcm_kw, 
                    src.mcpr, 
                    src.mcpr_kw, 
                    src.mfcr, 
                    src.mfcr_kw, 
                    src.pacc, 
                    src.pacc_kw, 
                    src.peri, 
                    src.pfpp, 
                    src.pfpp_kw, 
                    src.pgth, 
                    src.pgth_kw, 
                    src.ppht, 
                    src.ppht_kw, 
                    src.prhr, 
                    src.prhr_kw, 
                    src.qacc, 
                    src.qacc_kw, 
                    src.revr, 
                    src.revr_kw, 
                    src.scev, 
                    src.scev_kw, 
                    src.sequencenumber, 
                    src.text, 
                    src.text_ref_compnr, 
                    src.timestamp, 
                    src.tohc, 
                    src.tohc_kw, 
                    src.tsem, 
                    src.tsem_ref_compnr, 
                    src.tstk, 
                    src.tstk_ref_compnr, 
                    src.upsa, 
                    src.upsa_kw, 
                    src.urcc, 
                    src.urcc_kw, 
                    src.username, 
                    src.year,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TPPPC000_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.amoc, 
            strm.amoc_kw, 
            strm.amor, 
            strm.amor_kw, 
            strm.amos, 
            strm.amos_kw, 
            strm.antp, 
            strm.antp_kw, 
            strm.awpp, 
            strm.awpp_kw, 
            strm.casc, 
            strm.casc_ref_compnr, 
            strm.casd, 
            strm.casd_ref_compnr, 
            strm.ccap, 
            strm.ccap_kw, 
            strm.cint, 
            strm.cint_kw, 
            strm.cmif, 
            strm.cmif_kw, 
            strm.compnr, 
            strm.copr, 
            strm.copr_kw, 
            strm.cprp, 
            strm.cprp_kw, 
            strm.cptc, 
            strm.cptc_ref_compnr, 
            strm.cptc_year_peri_ref_compnr, 
            strm.cptf, 
            strm.cptf_ref_compnr, 
            strm.cpth, 
            strm.cpth_hyea_hper_ref_compnr, 
            strm.cpth_ref_compnr, 
            strm.dcic, 
            strm.dcic_ref_compnr, 
            strm.deleted, 
            strm.dequ, 
            strm.dequ_ref_compnr, 
            strm.dfrt, 
            strm.dfrt_ref_compnr, 
            strm.dhlp, 
            strm.dhlp_ref_compnr, 
            strm.ditm, 
            strm.ditm_ref_compnr, 
            strm.dsca, 
            strm.dsub, 
            strm.dsub_ref_compnr, 
            strm.dtrl, 
            strm.dtrl_ref_compnr, 
            strm.expc, 
            strm.expc_kw, 
            strm.hper, 
            strm.hyea, 
            strm.indt, 
            strm.ipcs, 
            strm.ipcs_kw, 
            strm.ipiw, 
            strm.ipiw_kw, 
            strm.lfcm, 
            strm.lfcm_kw, 
            strm.mcpr, 
            strm.mcpr_kw, 
            strm.mfcr, 
            strm.mfcr_kw, 
            strm.pacc, 
            strm.pacc_kw, 
            strm.peri, 
            strm.pfpp, 
            strm.pfpp_kw, 
            strm.pgth, 
            strm.pgth_kw, 
            strm.ppht, 
            strm.ppht_kw, 
            strm.prhr, 
            strm.prhr_kw, 
            strm.qacc, 
            strm.qacc_kw, 
            strm.revr, 
            strm.revr_kw, 
            strm.scev, 
            strm.scev_kw, 
            strm.sequencenumber, 
            strm.text, 
            strm.text_ref_compnr, 
            strm.timestamp, 
            strm.tohc, 
            strm.tohc_kw, 
            strm.tsem, 
            strm.tsem_ref_compnr, 
            strm.tstk, 
            strm.tstk_ref_compnr, 
            strm.upsa, 
            strm.upsa_kw, 
            strm.urcc, 
            strm.urcc_kw, 
            strm.username, 
            strm.year, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.indt ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPPC000 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.indt=src.indt) OR (target.indt IS NULL AND src.indt IS NULL)) 
                when matched then update set
                    target.amoc=src.amoc, 
                    target.amoc_kw=src.amoc_kw, 
                    target.amor=src.amor, 
                    target.amor_kw=src.amor_kw, 
                    target.amos=src.amos, 
                    target.amos_kw=src.amos_kw, 
                    target.antp=src.antp, 
                    target.antp_kw=src.antp_kw, 
                    target.awpp=src.awpp, 
                    target.awpp_kw=src.awpp_kw, 
                    target.casc=src.casc, 
                    target.casc_ref_compnr=src.casc_ref_compnr, 
                    target.casd=src.casd, 
                    target.casd_ref_compnr=src.casd_ref_compnr, 
                    target.ccap=src.ccap, 
                    target.ccap_kw=src.ccap_kw, 
                    target.cint=src.cint, 
                    target.cint_kw=src.cint_kw, 
                    target.cmif=src.cmif, 
                    target.cmif_kw=src.cmif_kw, 
                    target.compnr=src.compnr, 
                    target.copr=src.copr, 
                    target.copr_kw=src.copr_kw, 
                    target.cprp=src.cprp, 
                    target.cprp_kw=src.cprp_kw, 
                    target.cptc=src.cptc, 
                    target.cptc_ref_compnr=src.cptc_ref_compnr, 
                    target.cptc_year_peri_ref_compnr=src.cptc_year_peri_ref_compnr, 
                    target.cptf=src.cptf, 
                    target.cptf_ref_compnr=src.cptf_ref_compnr, 
                    target.cpth=src.cpth, 
                    target.cpth_hyea_hper_ref_compnr=src.cpth_hyea_hper_ref_compnr, 
                    target.cpth_ref_compnr=src.cpth_ref_compnr, 
                    target.dcic=src.dcic, 
                    target.dcic_ref_compnr=src.dcic_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dequ=src.dequ, 
                    target.dequ_ref_compnr=src.dequ_ref_compnr, 
                    target.dfrt=src.dfrt, 
                    target.dfrt_ref_compnr=src.dfrt_ref_compnr, 
                    target.dhlp=src.dhlp, 
                    target.dhlp_ref_compnr=src.dhlp_ref_compnr, 
                    target.ditm=src.ditm, 
                    target.ditm_ref_compnr=src.ditm_ref_compnr, 
                    target.dsca=src.dsca, 
                    target.dsub=src.dsub, 
                    target.dsub_ref_compnr=src.dsub_ref_compnr, 
                    target.dtrl=src.dtrl, 
                    target.dtrl_ref_compnr=src.dtrl_ref_compnr, 
                    target.expc=src.expc, 
                    target.expc_kw=src.expc_kw, 
                    target.hper=src.hper, 
                    target.hyea=src.hyea, 
                    target.indt=src.indt, 
                    target.ipcs=src.ipcs, 
                    target.ipcs_kw=src.ipcs_kw, 
                    target.ipiw=src.ipiw, 
                    target.ipiw_kw=src.ipiw_kw, 
                    target.lfcm=src.lfcm, 
                    target.lfcm_kw=src.lfcm_kw, 
                    target.mcpr=src.mcpr, 
                    target.mcpr_kw=src.mcpr_kw, 
                    target.mfcr=src.mfcr, 
                    target.mfcr_kw=src.mfcr_kw, 
                    target.pacc=src.pacc, 
                    target.pacc_kw=src.pacc_kw, 
                    target.peri=src.peri, 
                    target.pfpp=src.pfpp, 
                    target.pfpp_kw=src.pfpp_kw, 
                    target.pgth=src.pgth, 
                    target.pgth_kw=src.pgth_kw, 
                    target.ppht=src.ppht, 
                    target.ppht_kw=src.ppht_kw, 
                    target.prhr=src.prhr, 
                    target.prhr_kw=src.prhr_kw, 
                    target.qacc=src.qacc, 
                    target.qacc_kw=src.qacc_kw, 
                    target.revr=src.revr, 
                    target.revr_kw=src.revr_kw, 
                    target.scev=src.scev, 
                    target.scev_kw=src.scev_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.text=src.text, 
                    target.text_ref_compnr=src.text_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.tohc=src.tohc, 
                    target.tohc_kw=src.tohc_kw, 
                    target.tsem=src.tsem, 
                    target.tsem_ref_compnr=src.tsem_ref_compnr, 
                    target.tstk=src.tstk, 
                    target.tstk_ref_compnr=src.tstk_ref_compnr, 
                    target.upsa=src.upsa, 
                    target.upsa_kw=src.upsa_kw, 
                    target.urcc=src.urcc, 
                    target.urcc_kw=src.urcc_kw, 
                    target.username=src.username, 
                    target.year=src.year, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( amoc, amoc_kw, amor, amor_kw, amos, amos_kw, antp, antp_kw, awpp, awpp_kw, casc, casc_ref_compnr, casd, casd_ref_compnr, ccap, ccap_kw, cint, cint_kw, cmif, cmif_kw, compnr, copr, copr_kw, cprp, cprp_kw, cptc, cptc_ref_compnr, cptc_year_peri_ref_compnr, cptf, cptf_ref_compnr, cpth, cpth_hyea_hper_ref_compnr, cpth_ref_compnr, dcic, dcic_ref_compnr, deleted, dequ, dequ_ref_compnr, dfrt, dfrt_ref_compnr, dhlp, dhlp_ref_compnr, ditm, ditm_ref_compnr, dsca, dsub, dsub_ref_compnr, dtrl, dtrl_ref_compnr, expc, expc_kw, hper, hyea, indt, ipcs, ipcs_kw, ipiw, ipiw_kw, lfcm, lfcm_kw, mcpr, mcpr_kw, mfcr, mfcr_kw, pacc, pacc_kw, peri, pfpp, pfpp_kw, pgth, pgth_kw, ppht, ppht_kw, prhr, prhr_kw, qacc, qacc_kw, revr, revr_kw, scev, scev_kw, sequencenumber, text, text_ref_compnr, timestamp, tohc, tohc_kw, tsem, tsem_ref_compnr, tstk, tstk_ref_compnr, upsa, upsa_kw, urcc, urcc_kw, username, year, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.amoc, 
                    src.amoc_kw, 
                    src.amor, 
                    src.amor_kw, 
                    src.amos, 
                    src.amos_kw, 
                    src.antp, 
                    src.antp_kw, 
                    src.awpp, 
                    src.awpp_kw, 
                    src.casc, 
                    src.casc_ref_compnr, 
                    src.casd, 
                    src.casd_ref_compnr, 
                    src.ccap, 
                    src.ccap_kw, 
                    src.cint, 
                    src.cint_kw, 
                    src.cmif, 
                    src.cmif_kw, 
                    src.compnr, 
                    src.copr, 
                    src.copr_kw, 
                    src.cprp, 
                    src.cprp_kw, 
                    src.cptc, 
                    src.cptc_ref_compnr, 
                    src.cptc_year_peri_ref_compnr, 
                    src.cptf, 
                    src.cptf_ref_compnr, 
                    src.cpth, 
                    src.cpth_hyea_hper_ref_compnr, 
                    src.cpth_ref_compnr, 
                    src.dcic, 
                    src.dcic_ref_compnr, 
                    src.deleted, 
                    src.dequ, 
                    src.dequ_ref_compnr, 
                    src.dfrt, 
                    src.dfrt_ref_compnr, 
                    src.dhlp, 
                    src.dhlp_ref_compnr, 
                    src.ditm, 
                    src.ditm_ref_compnr, 
                    src.dsca, 
                    src.dsub, 
                    src.dsub_ref_compnr, 
                    src.dtrl, 
                    src.dtrl_ref_compnr, 
                    src.expc, 
                    src.expc_kw, 
                    src.hper, 
                    src.hyea, 
                    src.indt, 
                    src.ipcs, 
                    src.ipcs_kw, 
                    src.ipiw, 
                    src.ipiw_kw, 
                    src.lfcm, 
                    src.lfcm_kw, 
                    src.mcpr, 
                    src.mcpr_kw, 
                    src.mfcr, 
                    src.mfcr_kw, 
                    src.pacc, 
                    src.pacc_kw, 
                    src.peri, 
                    src.pfpp, 
                    src.pfpp_kw, 
                    src.pgth, 
                    src.pgth_kw, 
                    src.ppht, 
                    src.ppht_kw, 
                    src.prhr, 
                    src.prhr_kw, 
                    src.qacc, 
                    src.qacc_kw, 
                    src.revr, 
                    src.revr_kw, 
                    src.scev, 
                    src.scev_kw, 
                    src.sequencenumber, 
                    src.text, 
                    src.text_ref_compnr, 
                    src.timestamp, 
                    src.tohc, 
                    src.tohc_kw, 
                    src.tsem, 
                    src.tsem_ref_compnr, 
                    src.tstk, 
                    src.tstk_ref_compnr, 
                    src.upsa, 
                    src.upsa_kw, 
                    src.urcc, 
                    src.urcc_kw, 
                    src.username, 
                    src.year,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;