create or replace procedure DATAHUB_INTEGRATION.SP_LN_TSBSC100()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TSBSC100_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TSBSC100 as target using (SELECT * FROM (SELECT 
            strm.bfad, 
            strm.bfad_ref_compnr, 
            strm.bfbp, 
            strm.bfbp_ref_compnr, 
            strm.bfcn, 
            strm.bfcn_ref_compnr, 
            strm.ccal, 
            strm.ccal_ref_compnr, 
            strm.ccha, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.clrt, 
            strm.clrt_ref_compnr, 
            strm.clst, 
            strm.cnln, 
            strm.compnr, 
            strm.csar, 
            strm.csar_ref_compnr, 
            strm.cusc, 
            strm.cusc_ref_compnr, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.czon, 
            strm.czon_ref_compnr, 
            strm.dbpo, 
            strm.dbpo_kw, 
            strm.deleted, 
            strm.desc, 
            strm.dlad, 
            strm.dlad_ref_compnr, 
            strm.dlcn, 
            strm.dlcn_ref_compnr, 
            strm.dler, 
            strm.dler_ref_compnr, 
            strm.eftm, 
            strm.exin, 
            strm.imag, 
            strm.lcad, 
            strm.lcad_ref_compnr, 
            strm.lcmp, 
            strm.lcmp_ref_compnr, 
            strm.lste, 
            strm.lste_ref_compnr, 
            strm.mdnr, 
            strm.mdpt, 
            strm.mdpt_ref_compnr, 
            strm.odpt, 
            strm.odpt_ref_compnr, 
            strm.ofad, 
            strm.ofad_ref_compnr, 
            strm.ofbp, 
            strm.ofbp_ref_compnr, 
            strm.ofcn, 
            strm.ofcn_ref_compnr, 
            strm.ortp, 
            strm.ortp_kw, 
            strm.owtp, 
            strm.owtp_kw, 
            strm.prfa, 
            strm.prfa_ref_compnr, 
            strm.prfb, 
            strm.prfb_ref_compnr, 
            strm.prio, 
            strm.prio_ref_compnr, 
            strm.rspe, 
            strm.rspe_ref_compnr, 
            strm.rste, 
            strm.rste_ref_compnr, 
            strm.sdno, 
            strm.sear, 
            strm.sequencenumber, 
            strm.soff, 
            strm.soff_ref_compnr, 
            strm.spno, 
            strm.srno, 
            strm.timestamp, 
            strm.trdt, 
            strm.trtm, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.ubad, 
            strm.ubad_ref_compnr, 
            strm.ubbp, 
            strm.ubbp_ref_compnr, 
            strm.ubcn, 
            strm.ubcn_ref_compnr, 
            strm.ubop, 
            strm.ubop_ref_compnr, 
            strm.ubpc, 
            strm.ubpc_kw, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.clst ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TSBSC100 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.clst=src.clst) OR (target.clst IS NULL AND src.clst IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.bfad=src.bfad, 
                    target.bfad_ref_compnr=src.bfad_ref_compnr, 
                    target.bfbp=src.bfbp, 
                    target.bfbp_ref_compnr=src.bfbp_ref_compnr, 
                    target.bfcn=src.bfcn, 
                    target.bfcn_ref_compnr=src.bfcn_ref_compnr, 
                    target.ccal=src.ccal, 
                    target.ccal_ref_compnr=src.ccal_ref_compnr, 
                    target.ccha=src.ccha, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.clrt=src.clrt, 
                    target.clrt_ref_compnr=src.clrt_ref_compnr, 
                    target.clst=src.clst, 
                    target.cnln=src.cnln, 
                    target.compnr=src.compnr, 
                    target.csar=src.csar, 
                    target.csar_ref_compnr=src.csar_ref_compnr, 
                    target.cusc=src.cusc, 
                    target.cusc_ref_compnr=src.cusc_ref_compnr, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.czon=src.czon, 
                    target.czon_ref_compnr=src.czon_ref_compnr, 
                    target.dbpo=src.dbpo, 
                    target.dbpo_kw=src.dbpo_kw, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.dlad=src.dlad, 
                    target.dlad_ref_compnr=src.dlad_ref_compnr, 
                    target.dlcn=src.dlcn, 
                    target.dlcn_ref_compnr=src.dlcn_ref_compnr, 
                    target.dler=src.dler, 
                    target.dler_ref_compnr=src.dler_ref_compnr, 
                    target.eftm=src.eftm, 
                    target.exin=src.exin, 
                    target.imag=src.imag, 
                    target.lcad=src.lcad, 
                    target.lcad_ref_compnr=src.lcad_ref_compnr, 
                    target.lcmp=src.lcmp, 
                    target.lcmp_ref_compnr=src.lcmp_ref_compnr, 
                    target.lste=src.lste, 
                    target.lste_ref_compnr=src.lste_ref_compnr, 
                    target.mdnr=src.mdnr, 
                    target.mdpt=src.mdpt, 
                    target.mdpt_ref_compnr=src.mdpt_ref_compnr, 
                    target.odpt=src.odpt, 
                    target.odpt_ref_compnr=src.odpt_ref_compnr, 
                    target.ofad=src.ofad, 
                    target.ofad_ref_compnr=src.ofad_ref_compnr, 
                    target.ofbp=src.ofbp, 
                    target.ofbp_ref_compnr=src.ofbp_ref_compnr, 
                    target.ofcn=src.ofcn, 
                    target.ofcn_ref_compnr=src.ofcn_ref_compnr, 
                    target.ortp=src.ortp, 
                    target.ortp_kw=src.ortp_kw, 
                    target.owtp=src.owtp, 
                    target.owtp_kw=src.owtp_kw, 
                    target.prfa=src.prfa, 
                    target.prfa_ref_compnr=src.prfa_ref_compnr, 
                    target.prfb=src.prfb, 
                    target.prfb_ref_compnr=src.prfb_ref_compnr, 
                    target.prio=src.prio, 
                    target.prio_ref_compnr=src.prio_ref_compnr, 
                    target.rspe=src.rspe, 
                    target.rspe_ref_compnr=src.rspe_ref_compnr, 
                    target.rste=src.rste, 
                    target.rste_ref_compnr=src.rste_ref_compnr, 
                    target.sdno=src.sdno, 
                    target.sear=src.sear, 
                    target.sequencenumber=src.sequencenumber, 
                    target.soff=src.soff, 
                    target.soff_ref_compnr=src.soff_ref_compnr, 
                    target.spno=src.spno, 
                    target.srno=src.srno, 
                    target.timestamp=src.timestamp, 
                    target.trdt=src.trdt, 
                    target.trtm=src.trtm, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.ubad=src.ubad, 
                    target.ubad_ref_compnr=src.ubad_ref_compnr, 
                    target.ubbp=src.ubbp, 
                    target.ubbp_ref_compnr=src.ubbp_ref_compnr, 
                    target.ubcn=src.ubcn, 
                    target.ubcn_ref_compnr=src.ubcn_ref_compnr, 
                    target.ubop=src.ubop, 
                    target.ubop_ref_compnr=src.ubop_ref_compnr, 
                    target.ubpc=src.ubpc, 
                    target.ubpc_kw=src.ubpc_kw, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    bfad, 
                    bfad_ref_compnr, 
                    bfbp, 
                    bfbp_ref_compnr, 
                    bfcn, 
                    bfcn_ref_compnr, 
                    ccal, 
                    ccal_ref_compnr, 
                    ccha, 
                    ccur, 
                    ccur_ref_compnr, 
                    clrt, 
                    clrt_ref_compnr, 
                    clst, 
                    cnln, 
                    compnr, 
                    csar, 
                    csar_ref_compnr, 
                    cusc, 
                    cusc_ref_compnr, 
                    cwar, 
                    cwar_ref_compnr, 
                    czon, 
                    czon_ref_compnr, 
                    dbpo, 
                    dbpo_kw, 
                    deleted, 
                    desc, 
                    dlad, 
                    dlad_ref_compnr, 
                    dlcn, 
                    dlcn_ref_compnr, 
                    dler, 
                    dler_ref_compnr, 
                    eftm, 
                    exin, 
                    imag, 
                    lcad, 
                    lcad_ref_compnr, 
                    lcmp, 
                    lcmp_ref_compnr, 
                    lste, 
                    lste_ref_compnr, 
                    mdnr, 
                    mdpt, 
                    mdpt_ref_compnr, 
                    odpt, 
                    odpt_ref_compnr, 
                    ofad, 
                    ofad_ref_compnr, 
                    ofbp, 
                    ofbp_ref_compnr, 
                    ofcn, 
                    ofcn_ref_compnr, 
                    ortp, 
                    ortp_kw, 
                    owtp, 
                    owtp_kw, 
                    prfa, 
                    prfa_ref_compnr, 
                    prfb, 
                    prfb_ref_compnr, 
                    prio, 
                    prio_ref_compnr, 
                    rspe, 
                    rspe_ref_compnr, 
                    rste, 
                    rste_ref_compnr, 
                    sdno, 
                    sear, 
                    sequencenumber, 
                    soff, 
                    soff_ref_compnr, 
                    spno, 
                    srno, 
                    timestamp, 
                    trdt, 
                    trtm, 
                    txta, 
                    txta_ref_compnr, 
                    ubad, 
                    ubad_ref_compnr, 
                    ubbp, 
                    ubbp_ref_compnr, 
                    ubcn, 
                    ubcn_ref_compnr, 
                    ubop, 
                    ubop_ref_compnr, 
                    ubpc, 
                    ubpc_kw, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.bfad, 
                    src.bfad_ref_compnr, 
                    src.bfbp, 
                    src.bfbp_ref_compnr, 
                    src.bfcn, 
                    src.bfcn_ref_compnr, 
                    src.ccal, 
                    src.ccal_ref_compnr, 
                    src.ccha, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.clrt, 
                    src.clrt_ref_compnr, 
                    src.clst, 
                    src.cnln, 
                    src.compnr, 
                    src.csar, 
                    src.csar_ref_compnr, 
                    src.cusc, 
                    src.cusc_ref_compnr, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.czon, 
                    src.czon_ref_compnr, 
                    src.dbpo, 
                    src.dbpo_kw, 
                    src.deleted, 
                    src.desc, 
                    src.dlad, 
                    src.dlad_ref_compnr, 
                    src.dlcn, 
                    src.dlcn_ref_compnr, 
                    src.dler, 
                    src.dler_ref_compnr, 
                    src.eftm, 
                    src.exin, 
                    src.imag, 
                    src.lcad, 
                    src.lcad_ref_compnr, 
                    src.lcmp, 
                    src.lcmp_ref_compnr, 
                    src.lste, 
                    src.lste_ref_compnr, 
                    src.mdnr, 
                    src.mdpt, 
                    src.mdpt_ref_compnr, 
                    src.odpt, 
                    src.odpt_ref_compnr, 
                    src.ofad, 
                    src.ofad_ref_compnr, 
                    src.ofbp, 
                    src.ofbp_ref_compnr, 
                    src.ofcn, 
                    src.ofcn_ref_compnr, 
                    src.ortp, 
                    src.ortp_kw, 
                    src.owtp, 
                    src.owtp_kw, 
                    src.prfa, 
                    src.prfa_ref_compnr, 
                    src.prfb, 
                    src.prfb_ref_compnr, 
                    src.prio, 
                    src.prio_ref_compnr, 
                    src.rspe, 
                    src.rspe_ref_compnr, 
                    src.rste, 
                    src.rste_ref_compnr, 
                    src.sdno, 
                    src.sear, 
                    src.sequencenumber, 
                    src.soff, 
                    src.soff_ref_compnr, 
                    src.spno, 
                    src.srno, 
                    src.timestamp, 
                    src.trdt, 
                    src.trtm, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.ubad, 
                    src.ubad_ref_compnr, 
                    src.ubbp, 
                    src.ubbp_ref_compnr, 
                    src.ubcn, 
                    src.ubcn_ref_compnr, 
                    src.ubop, 
                    src.ubop_ref_compnr, 
                    src.ubpc, 
                    src.ubpc_kw, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TSBSC100_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.bfad, 
            strm.bfad_ref_compnr, 
            strm.bfbp, 
            strm.bfbp_ref_compnr, 
            strm.bfcn, 
            strm.bfcn_ref_compnr, 
            strm.ccal, 
            strm.ccal_ref_compnr, 
            strm.ccha, 
            strm.ccur, 
            strm.ccur_ref_compnr, 
            strm.clrt, 
            strm.clrt_ref_compnr, 
            strm.clst, 
            strm.cnln, 
            strm.compnr, 
            strm.csar, 
            strm.csar_ref_compnr, 
            strm.cusc, 
            strm.cusc_ref_compnr, 
            strm.cwar, 
            strm.cwar_ref_compnr, 
            strm.czon, 
            strm.czon_ref_compnr, 
            strm.dbpo, 
            strm.dbpo_kw, 
            strm.deleted, 
            strm.desc, 
            strm.dlad, 
            strm.dlad_ref_compnr, 
            strm.dlcn, 
            strm.dlcn_ref_compnr, 
            strm.dler, 
            strm.dler_ref_compnr, 
            strm.eftm, 
            strm.exin, 
            strm.imag, 
            strm.lcad, 
            strm.lcad_ref_compnr, 
            strm.lcmp, 
            strm.lcmp_ref_compnr, 
            strm.lste, 
            strm.lste_ref_compnr, 
            strm.mdnr, 
            strm.mdpt, 
            strm.mdpt_ref_compnr, 
            strm.odpt, 
            strm.odpt_ref_compnr, 
            strm.ofad, 
            strm.ofad_ref_compnr, 
            strm.ofbp, 
            strm.ofbp_ref_compnr, 
            strm.ofcn, 
            strm.ofcn_ref_compnr, 
            strm.ortp, 
            strm.ortp_kw, 
            strm.owtp, 
            strm.owtp_kw, 
            strm.prfa, 
            strm.prfa_ref_compnr, 
            strm.prfb, 
            strm.prfb_ref_compnr, 
            strm.prio, 
            strm.prio_ref_compnr, 
            strm.rspe, 
            strm.rspe_ref_compnr, 
            strm.rste, 
            strm.rste_ref_compnr, 
            strm.sdno, 
            strm.sear, 
            strm.sequencenumber, 
            strm.soff, 
            strm.soff_ref_compnr, 
            strm.spno, 
            strm.srno, 
            strm.timestamp, 
            strm.trdt, 
            strm.trtm, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.ubad, 
            strm.ubad_ref_compnr, 
            strm.ubbp, 
            strm.ubbp_ref_compnr, 
            strm.ubcn, 
            strm.ubcn_ref_compnr, 
            strm.ubop, 
            strm.ubop_ref_compnr, 
            strm.ubpc, 
            strm.ubpc_kw, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.clst ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TSBSC100 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.clst=src.clst) OR (target.clst IS NULL AND src.clst IS NULL)) 
                when matched then update set
                    target.bfad=src.bfad, 
                    target.bfad_ref_compnr=src.bfad_ref_compnr, 
                    target.bfbp=src.bfbp, 
                    target.bfbp_ref_compnr=src.bfbp_ref_compnr, 
                    target.bfcn=src.bfcn, 
                    target.bfcn_ref_compnr=src.bfcn_ref_compnr, 
                    target.ccal=src.ccal, 
                    target.ccal_ref_compnr=src.ccal_ref_compnr, 
                    target.ccha=src.ccha, 
                    target.ccur=src.ccur, 
                    target.ccur_ref_compnr=src.ccur_ref_compnr, 
                    target.clrt=src.clrt, 
                    target.clrt_ref_compnr=src.clrt_ref_compnr, 
                    target.clst=src.clst, 
                    target.cnln=src.cnln, 
                    target.compnr=src.compnr, 
                    target.csar=src.csar, 
                    target.csar_ref_compnr=src.csar_ref_compnr, 
                    target.cusc=src.cusc, 
                    target.cusc_ref_compnr=src.cusc_ref_compnr, 
                    target.cwar=src.cwar, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.czon=src.czon, 
                    target.czon_ref_compnr=src.czon_ref_compnr, 
                    target.dbpo=src.dbpo, 
                    target.dbpo_kw=src.dbpo_kw, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.dlad=src.dlad, 
                    target.dlad_ref_compnr=src.dlad_ref_compnr, 
                    target.dlcn=src.dlcn, 
                    target.dlcn_ref_compnr=src.dlcn_ref_compnr, 
                    target.dler=src.dler, 
                    target.dler_ref_compnr=src.dler_ref_compnr, 
                    target.eftm=src.eftm, 
                    target.exin=src.exin, 
                    target.imag=src.imag, 
                    target.lcad=src.lcad, 
                    target.lcad_ref_compnr=src.lcad_ref_compnr, 
                    target.lcmp=src.lcmp, 
                    target.lcmp_ref_compnr=src.lcmp_ref_compnr, 
                    target.lste=src.lste, 
                    target.lste_ref_compnr=src.lste_ref_compnr, 
                    target.mdnr=src.mdnr, 
                    target.mdpt=src.mdpt, 
                    target.mdpt_ref_compnr=src.mdpt_ref_compnr, 
                    target.odpt=src.odpt, 
                    target.odpt_ref_compnr=src.odpt_ref_compnr, 
                    target.ofad=src.ofad, 
                    target.ofad_ref_compnr=src.ofad_ref_compnr, 
                    target.ofbp=src.ofbp, 
                    target.ofbp_ref_compnr=src.ofbp_ref_compnr, 
                    target.ofcn=src.ofcn, 
                    target.ofcn_ref_compnr=src.ofcn_ref_compnr, 
                    target.ortp=src.ortp, 
                    target.ortp_kw=src.ortp_kw, 
                    target.owtp=src.owtp, 
                    target.owtp_kw=src.owtp_kw, 
                    target.prfa=src.prfa, 
                    target.prfa_ref_compnr=src.prfa_ref_compnr, 
                    target.prfb=src.prfb, 
                    target.prfb_ref_compnr=src.prfb_ref_compnr, 
                    target.prio=src.prio, 
                    target.prio_ref_compnr=src.prio_ref_compnr, 
                    target.rspe=src.rspe, 
                    target.rspe_ref_compnr=src.rspe_ref_compnr, 
                    target.rste=src.rste, 
                    target.rste_ref_compnr=src.rste_ref_compnr, 
                    target.sdno=src.sdno, 
                    target.sear=src.sear, 
                    target.sequencenumber=src.sequencenumber, 
                    target.soff=src.soff, 
                    target.soff_ref_compnr=src.soff_ref_compnr, 
                    target.spno=src.spno, 
                    target.srno=src.srno, 
                    target.timestamp=src.timestamp, 
                    target.trdt=src.trdt, 
                    target.trtm=src.trtm, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.ubad=src.ubad, 
                    target.ubad_ref_compnr=src.ubad_ref_compnr, 
                    target.ubbp=src.ubbp, 
                    target.ubbp_ref_compnr=src.ubbp_ref_compnr, 
                    target.ubcn=src.ubcn, 
                    target.ubcn_ref_compnr=src.ubcn_ref_compnr, 
                    target.ubop=src.ubop, 
                    target.ubop_ref_compnr=src.ubop_ref_compnr, 
                    target.ubpc=src.ubpc, 
                    target.ubpc_kw=src.ubpc_kw, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( bfad, bfad_ref_compnr, bfbp, bfbp_ref_compnr, bfcn, bfcn_ref_compnr, ccal, ccal_ref_compnr, ccha, ccur, ccur_ref_compnr, clrt, clrt_ref_compnr, clst, cnln, compnr, csar, csar_ref_compnr, cusc, cusc_ref_compnr, cwar, cwar_ref_compnr, czon, czon_ref_compnr, dbpo, dbpo_kw, deleted, desc, dlad, dlad_ref_compnr, dlcn, dlcn_ref_compnr, dler, dler_ref_compnr, eftm, exin, imag, lcad, lcad_ref_compnr, lcmp, lcmp_ref_compnr, lste, lste_ref_compnr, mdnr, mdpt, mdpt_ref_compnr, odpt, odpt_ref_compnr, ofad, ofad_ref_compnr, ofbp, ofbp_ref_compnr, ofcn, ofcn_ref_compnr, ortp, ortp_kw, owtp, owtp_kw, prfa, prfa_ref_compnr, prfb, prfb_ref_compnr, prio, prio_ref_compnr, rspe, rspe_ref_compnr, rste, rste_ref_compnr, sdno, sear, sequencenumber, soff, soff_ref_compnr, spno, srno, timestamp, trdt, trtm, txta, txta_ref_compnr, ubad, ubad_ref_compnr, ubbp, ubbp_ref_compnr, ubcn, ubcn_ref_compnr, ubop, ubop_ref_compnr, ubpc, ubpc_kw, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.bfad, 
                    src.bfad_ref_compnr, 
                    src.bfbp, 
                    src.bfbp_ref_compnr, 
                    src.bfcn, 
                    src.bfcn_ref_compnr, 
                    src.ccal, 
                    src.ccal_ref_compnr, 
                    src.ccha, 
                    src.ccur, 
                    src.ccur_ref_compnr, 
                    src.clrt, 
                    src.clrt_ref_compnr, 
                    src.clst, 
                    src.cnln, 
                    src.compnr, 
                    src.csar, 
                    src.csar_ref_compnr, 
                    src.cusc, 
                    src.cusc_ref_compnr, 
                    src.cwar, 
                    src.cwar_ref_compnr, 
                    src.czon, 
                    src.czon_ref_compnr, 
                    src.dbpo, 
                    src.dbpo_kw, 
                    src.deleted, 
                    src.desc, 
                    src.dlad, 
                    src.dlad_ref_compnr, 
                    src.dlcn, 
                    src.dlcn_ref_compnr, 
                    src.dler, 
                    src.dler_ref_compnr, 
                    src.eftm, 
                    src.exin, 
                    src.imag, 
                    src.lcad, 
                    src.lcad_ref_compnr, 
                    src.lcmp, 
                    src.lcmp_ref_compnr, 
                    src.lste, 
                    src.lste_ref_compnr, 
                    src.mdnr, 
                    src.mdpt, 
                    src.mdpt_ref_compnr, 
                    src.odpt, 
                    src.odpt_ref_compnr, 
                    src.ofad, 
                    src.ofad_ref_compnr, 
                    src.ofbp, 
                    src.ofbp_ref_compnr, 
                    src.ofcn, 
                    src.ofcn_ref_compnr, 
                    src.ortp, 
                    src.ortp_kw, 
                    src.owtp, 
                    src.owtp_kw, 
                    src.prfa, 
                    src.prfa_ref_compnr, 
                    src.prfb, 
                    src.prfb_ref_compnr, 
                    src.prio, 
                    src.prio_ref_compnr, 
                    src.rspe, 
                    src.rspe_ref_compnr, 
                    src.rste, 
                    src.rste_ref_compnr, 
                    src.sdno, 
                    src.sear, 
                    src.sequencenumber, 
                    src.soff, 
                    src.soff_ref_compnr, 
                    src.spno, 
                    src.srno, 
                    src.timestamp, 
                    src.trdt, 
                    src.trtm, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.ubad, 
                    src.ubad_ref_compnr, 
                    src.ubbp, 
                    src.ubbp_ref_compnr, 
                    src.ubcn, 
                    src.ubcn_ref_compnr, 
                    src.ubop, 
                    src.ubop_ref_compnr, 
                    src.ubpc, 
                    src.ubpc_kw, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;