create or replace procedure DATAHUB_INTEGRATION.SP_LN_TFFAM110()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TFFAM110_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TFFAM110 as target using (SELECT * FROM (SELECT 
            strm.adpa_1, 
            strm.adpa_2, 
            strm.adpa_3, 
            strm.adpc, 
            strm.adpc_kw, 
            strm.adpm, 
            strm.adpm_ref_compnr, 
            strm.aext, 
            strm.anbr, 
            strm.anbr_aext_ref_compnr, 
            strm.book, 
            strm.book_ref_compnr, 
            strm.bslv, 
            strm.bslv_kw, 
            strm.c263_1, 
            strm.c263_2, 
            strm.c263_3, 
            strm.capi_1, 
            strm.capi_2, 
            strm.capi_3, 
            strm.compnr, 
            strm.cost_1, 
            strm.cost_2, 
            strm.cost_3, 
            strm.curd, 
            strm.deleted, 
            strm.depr_1, 
            strm.depr_2, 
            strm.depr_3, 
            strm.disd, 
            strm.ecre, 
            strm.ecre_kw, 
            strm.freq, 
            strm.freq_ref_compnr, 
            strm.fydp, 
            strm.gfac_1, 
            strm.gfac_2, 
            strm.gfac_3, 
            strm.indx, 
            strm.indx_ref_compnr, 
            strm.itca_1, 
            strm.itca_2, 
            strm.itca_3, 
            strm.last, 
            strm.life, 
            strm.lrev, 
            strm.ltad_1, 
            strm.ltad_2, 
            strm.ltad_3, 
            strm.ltar_1, 
            strm.ltar_2, 
            strm.ltar_3, 
            strm.ltdd_1, 
            strm.ltdd_2, 
            strm.ltdd_3, 
            strm.ltdr_1, 
            strm.ltdr_2, 
            strm.ltdr_3, 
            strm.meth, 
            strm.meth_ref_compnr, 
            strm.ocst_1, 
            strm.ocst_2, 
            strm.ocst_3, 
            strm.post, 
            strm.post_kw, 
            strm.prop, 
            strm.prop_ref_compnr, 
            strm.rcst_1, 
            strm.rcst_2, 
            strm.rcst_3, 
            strm.rdpr_1, 
            strm.rdpr_2, 
            strm.rdpr_3, 
            strm.s179_1, 
            strm.s179_2, 
            strm.s179_3, 
            strm.salv_1, 
            strm.salv_2, 
            strm.salv_3, 
            strm.sdpn, 
            strm.sequencenumber, 
            strm.shft, 
            strm.srac, 
            strm.srac_kw, 
            strm.stat, 
            strm.stat_kw, 
            strm.timestamp, 
            strm.tmth, 
            strm.tmth_kw, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.unit, 
            strm.username, 
            strm.ytdd_1, 
            strm.ytdd_2, 
            strm.ytdd_3, 
            strm.ytdr_1, 
            strm.ytdr_2, 
            strm.ytdr_3, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.anbr,
            strm.aext,
            strm.book ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFFAM110 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.anbr=src.anbr) OR (target.anbr IS NULL AND src.anbr IS NULL)) AND
            ((target.aext=src.aext) OR (target.aext IS NULL AND src.aext IS NULL)) AND
            ((target.book=src.book) OR (target.book IS NULL AND src.book IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.adpa_1=src.adpa_1, 
                    target.adpa_2=src.adpa_2, 
                    target.adpa_3=src.adpa_3, 
                    target.adpc=src.adpc, 
                    target.adpc_kw=src.adpc_kw, 
                    target.adpm=src.adpm, 
                    target.adpm_ref_compnr=src.adpm_ref_compnr, 
                    target.aext=src.aext, 
                    target.anbr=src.anbr, 
                    target.anbr_aext_ref_compnr=src.anbr_aext_ref_compnr, 
                    target.book=src.book, 
                    target.book_ref_compnr=src.book_ref_compnr, 
                    target.bslv=src.bslv, 
                    target.bslv_kw=src.bslv_kw, 
                    target.c263_1=src.c263_1, 
                    target.c263_2=src.c263_2, 
                    target.c263_3=src.c263_3, 
                    target.capi_1=src.capi_1, 
                    target.capi_2=src.capi_2, 
                    target.capi_3=src.capi_3, 
                    target.compnr=src.compnr, 
                    target.cost_1=src.cost_1, 
                    target.cost_2=src.cost_2, 
                    target.cost_3=src.cost_3, 
                    target.curd=src.curd, 
                    target.deleted=src.deleted, 
                    target.depr_1=src.depr_1, 
                    target.depr_2=src.depr_2, 
                    target.depr_3=src.depr_3, 
                    target.disd=src.disd, 
                    target.ecre=src.ecre, 
                    target.ecre_kw=src.ecre_kw, 
                    target.freq=src.freq, 
                    target.freq_ref_compnr=src.freq_ref_compnr, 
                    target.fydp=src.fydp, 
                    target.gfac_1=src.gfac_1, 
                    target.gfac_2=src.gfac_2, 
                    target.gfac_3=src.gfac_3, 
                    target.indx=src.indx, 
                    target.indx_ref_compnr=src.indx_ref_compnr, 
                    target.itca_1=src.itca_1, 
                    target.itca_2=src.itca_2, 
                    target.itca_3=src.itca_3, 
                    target.last=src.last, 
                    target.life=src.life, 
                    target.lrev=src.lrev, 
                    target.ltad_1=src.ltad_1, 
                    target.ltad_2=src.ltad_2, 
                    target.ltad_3=src.ltad_3, 
                    target.ltar_1=src.ltar_1, 
                    target.ltar_2=src.ltar_2, 
                    target.ltar_3=src.ltar_3, 
                    target.ltdd_1=src.ltdd_1, 
                    target.ltdd_2=src.ltdd_2, 
                    target.ltdd_3=src.ltdd_3, 
                    target.ltdr_1=src.ltdr_1, 
                    target.ltdr_2=src.ltdr_2, 
                    target.ltdr_3=src.ltdr_3, 
                    target.meth=src.meth, 
                    target.meth_ref_compnr=src.meth_ref_compnr, 
                    target.ocst_1=src.ocst_1, 
                    target.ocst_2=src.ocst_2, 
                    target.ocst_3=src.ocst_3, 
                    target.post=src.post, 
                    target.post_kw=src.post_kw, 
                    target.prop=src.prop, 
                    target.prop_ref_compnr=src.prop_ref_compnr, 
                    target.rcst_1=src.rcst_1, 
                    target.rcst_2=src.rcst_2, 
                    target.rcst_3=src.rcst_3, 
                    target.rdpr_1=src.rdpr_1, 
                    target.rdpr_2=src.rdpr_2, 
                    target.rdpr_3=src.rdpr_3, 
                    target.s179_1=src.s179_1, 
                    target.s179_2=src.s179_2, 
                    target.s179_3=src.s179_3, 
                    target.salv_1=src.salv_1, 
                    target.salv_2=src.salv_2, 
                    target.salv_3=src.salv_3, 
                    target.sdpn=src.sdpn, 
                    target.sequencenumber=src.sequencenumber, 
                    target.shft=src.shft, 
                    target.srac=src.srac, 
                    target.srac_kw=src.srac_kw, 
                    target.stat=src.stat, 
                    target.stat_kw=src.stat_kw, 
                    target.timestamp=src.timestamp, 
                    target.tmth=src.tmth, 
                    target.tmth_kw=src.tmth_kw, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.unit=src.unit, 
                    target.username=src.username, 
                    target.ytdd_1=src.ytdd_1, 
                    target.ytdd_2=src.ytdd_2, 
                    target.ytdd_3=src.ytdd_3, 
                    target.ytdr_1=src.ytdr_1, 
                    target.ytdr_2=src.ytdr_2, 
                    target.ytdr_3=src.ytdr_3, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    adpa_1, 
                    adpa_2, 
                    adpa_3, 
                    adpc, 
                    adpc_kw, 
                    adpm, 
                    adpm_ref_compnr, 
                    aext, 
                    anbr, 
                    anbr_aext_ref_compnr, 
                    book, 
                    book_ref_compnr, 
                    bslv, 
                    bslv_kw, 
                    c263_1, 
                    c263_2, 
                    c263_3, 
                    capi_1, 
                    capi_2, 
                    capi_3, 
                    compnr, 
                    cost_1, 
                    cost_2, 
                    cost_3, 
                    curd, 
                    deleted, 
                    depr_1, 
                    depr_2, 
                    depr_3, 
                    disd, 
                    ecre, 
                    ecre_kw, 
                    freq, 
                    freq_ref_compnr, 
                    fydp, 
                    gfac_1, 
                    gfac_2, 
                    gfac_3, 
                    indx, 
                    indx_ref_compnr, 
                    itca_1, 
                    itca_2, 
                    itca_3, 
                    last, 
                    life, 
                    lrev, 
                    ltad_1, 
                    ltad_2, 
                    ltad_3, 
                    ltar_1, 
                    ltar_2, 
                    ltar_3, 
                    ltdd_1, 
                    ltdd_2, 
                    ltdd_3, 
                    ltdr_1, 
                    ltdr_2, 
                    ltdr_3, 
                    meth, 
                    meth_ref_compnr, 
                    ocst_1, 
                    ocst_2, 
                    ocst_3, 
                    post, 
                    post_kw, 
                    prop, 
                    prop_ref_compnr, 
                    rcst_1, 
                    rcst_2, 
                    rcst_3, 
                    rdpr_1, 
                    rdpr_2, 
                    rdpr_3, 
                    s179_1, 
                    s179_2, 
                    s179_3, 
                    salv_1, 
                    salv_2, 
                    salv_3, 
                    sdpn, 
                    sequencenumber, 
                    shft, 
                    srac, 
                    srac_kw, 
                    stat, 
                    stat_kw, 
                    timestamp, 
                    tmth, 
                    tmth_kw, 
                    txta, 
                    txta_ref_compnr, 
                    unit, 
                    username, 
                    ytdd_1, 
                    ytdd_2, 
                    ytdd_3, 
                    ytdr_1, 
                    ytdr_2, 
                    ytdr_3, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.adpa_1, 
                    src.adpa_2, 
                    src.adpa_3, 
                    src.adpc, 
                    src.adpc_kw, 
                    src.adpm, 
                    src.adpm_ref_compnr, 
                    src.aext, 
                    src.anbr, 
                    src.anbr_aext_ref_compnr, 
                    src.book, 
                    src.book_ref_compnr, 
                    src.bslv, 
                    src.bslv_kw, 
                    src.c263_1, 
                    src.c263_2, 
                    src.c263_3, 
                    src.capi_1, 
                    src.capi_2, 
                    src.capi_3, 
                    src.compnr, 
                    src.cost_1, 
                    src.cost_2, 
                    src.cost_3, 
                    src.curd, 
                    src.deleted, 
                    src.depr_1, 
                    src.depr_2, 
                    src.depr_3, 
                    src.disd, 
                    src.ecre, 
                    src.ecre_kw, 
                    src.freq, 
                    src.freq_ref_compnr, 
                    src.fydp, 
                    src.gfac_1, 
                    src.gfac_2, 
                    src.gfac_3, 
                    src.indx, 
                    src.indx_ref_compnr, 
                    src.itca_1, 
                    src.itca_2, 
                    src.itca_3, 
                    src.last, 
                    src.life, 
                    src.lrev, 
                    src.ltad_1, 
                    src.ltad_2, 
                    src.ltad_3, 
                    src.ltar_1, 
                    src.ltar_2, 
                    src.ltar_3, 
                    src.ltdd_1, 
                    src.ltdd_2, 
                    src.ltdd_3, 
                    src.ltdr_1, 
                    src.ltdr_2, 
                    src.ltdr_3, 
                    src.meth, 
                    src.meth_ref_compnr, 
                    src.ocst_1, 
                    src.ocst_2, 
                    src.ocst_3, 
                    src.post, 
                    src.post_kw, 
                    src.prop, 
                    src.prop_ref_compnr, 
                    src.rcst_1, 
                    src.rcst_2, 
                    src.rcst_3, 
                    src.rdpr_1, 
                    src.rdpr_2, 
                    src.rdpr_3, 
                    src.s179_1, 
                    src.s179_2, 
                    src.s179_3, 
                    src.salv_1, 
                    src.salv_2, 
                    src.salv_3, 
                    src.sdpn, 
                    src.sequencenumber, 
                    src.shft, 
                    src.srac, 
                    src.srac_kw, 
                    src.stat, 
                    src.stat_kw, 
                    src.timestamp, 
                    src.tmth, 
                    src.tmth_kw, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.unit, 
                    src.username, 
                    src.ytdd_1, 
                    src.ytdd_2, 
                    src.ytdd_3, 
                    src.ytdr_1, 
                    src.ytdr_2, 
                    src.ytdr_3,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TFFAM110_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.adpa_1, 
            strm.adpa_2, 
            strm.adpa_3, 
            strm.adpc, 
            strm.adpc_kw, 
            strm.adpm, 
            strm.adpm_ref_compnr, 
            strm.aext, 
            strm.anbr, 
            strm.anbr_aext_ref_compnr, 
            strm.book, 
            strm.book_ref_compnr, 
            strm.bslv, 
            strm.bslv_kw, 
            strm.c263_1, 
            strm.c263_2, 
            strm.c263_3, 
            strm.capi_1, 
            strm.capi_2, 
            strm.capi_3, 
            strm.compnr, 
            strm.cost_1, 
            strm.cost_2, 
            strm.cost_3, 
            strm.curd, 
            strm.deleted, 
            strm.depr_1, 
            strm.depr_2, 
            strm.depr_3, 
            strm.disd, 
            strm.ecre, 
            strm.ecre_kw, 
            strm.freq, 
            strm.freq_ref_compnr, 
            strm.fydp, 
            strm.gfac_1, 
            strm.gfac_2, 
            strm.gfac_3, 
            strm.indx, 
            strm.indx_ref_compnr, 
            strm.itca_1, 
            strm.itca_2, 
            strm.itca_3, 
            strm.last, 
            strm.life, 
            strm.lrev, 
            strm.ltad_1, 
            strm.ltad_2, 
            strm.ltad_3, 
            strm.ltar_1, 
            strm.ltar_2, 
            strm.ltar_3, 
            strm.ltdd_1, 
            strm.ltdd_2, 
            strm.ltdd_3, 
            strm.ltdr_1, 
            strm.ltdr_2, 
            strm.ltdr_3, 
            strm.meth, 
            strm.meth_ref_compnr, 
            strm.ocst_1, 
            strm.ocst_2, 
            strm.ocst_3, 
            strm.post, 
            strm.post_kw, 
            strm.prop, 
            strm.prop_ref_compnr, 
            strm.rcst_1, 
            strm.rcst_2, 
            strm.rcst_3, 
            strm.rdpr_1, 
            strm.rdpr_2, 
            strm.rdpr_3, 
            strm.s179_1, 
            strm.s179_2, 
            strm.s179_3, 
            strm.salv_1, 
            strm.salv_2, 
            strm.salv_3, 
            strm.sdpn, 
            strm.sequencenumber, 
            strm.shft, 
            strm.srac, 
            strm.srac_kw, 
            strm.stat, 
            strm.stat_kw, 
            strm.timestamp, 
            strm.tmth, 
            strm.tmth_kw, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.unit, 
            strm.username, 
            strm.ytdd_1, 
            strm.ytdd_2, 
            strm.ytdd_3, 
            strm.ytdr_1, 
            strm.ytdr_2, 
            strm.ytdr_3, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.anbr,
            strm.aext,
            strm.book ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFFAM110 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.anbr=src.anbr) OR (target.anbr IS NULL AND src.anbr IS NULL)) AND
            ((target.aext=src.aext) OR (target.aext IS NULL AND src.aext IS NULL)) AND
            ((target.book=src.book) OR (target.book IS NULL AND src.book IS NULL)) 
                when matched then update set
                    target.adpa_1=src.adpa_1, 
                    target.adpa_2=src.adpa_2, 
                    target.adpa_3=src.adpa_3, 
                    target.adpc=src.adpc, 
                    target.adpc_kw=src.adpc_kw, 
                    target.adpm=src.adpm, 
                    target.adpm_ref_compnr=src.adpm_ref_compnr, 
                    target.aext=src.aext, 
                    target.anbr=src.anbr, 
                    target.anbr_aext_ref_compnr=src.anbr_aext_ref_compnr, 
                    target.book=src.book, 
                    target.book_ref_compnr=src.book_ref_compnr, 
                    target.bslv=src.bslv, 
                    target.bslv_kw=src.bslv_kw, 
                    target.c263_1=src.c263_1, 
                    target.c263_2=src.c263_2, 
                    target.c263_3=src.c263_3, 
                    target.capi_1=src.capi_1, 
                    target.capi_2=src.capi_2, 
                    target.capi_3=src.capi_3, 
                    target.compnr=src.compnr, 
                    target.cost_1=src.cost_1, 
                    target.cost_2=src.cost_2, 
                    target.cost_3=src.cost_3, 
                    target.curd=src.curd, 
                    target.deleted=src.deleted, 
                    target.depr_1=src.depr_1, 
                    target.depr_2=src.depr_2, 
                    target.depr_3=src.depr_3, 
                    target.disd=src.disd, 
                    target.ecre=src.ecre, 
                    target.ecre_kw=src.ecre_kw, 
                    target.freq=src.freq, 
                    target.freq_ref_compnr=src.freq_ref_compnr, 
                    target.fydp=src.fydp, 
                    target.gfac_1=src.gfac_1, 
                    target.gfac_2=src.gfac_2, 
                    target.gfac_3=src.gfac_3, 
                    target.indx=src.indx, 
                    target.indx_ref_compnr=src.indx_ref_compnr, 
                    target.itca_1=src.itca_1, 
                    target.itca_2=src.itca_2, 
                    target.itca_3=src.itca_3, 
                    target.last=src.last, 
                    target.life=src.life, 
                    target.lrev=src.lrev, 
                    target.ltad_1=src.ltad_1, 
                    target.ltad_2=src.ltad_2, 
                    target.ltad_3=src.ltad_3, 
                    target.ltar_1=src.ltar_1, 
                    target.ltar_2=src.ltar_2, 
                    target.ltar_3=src.ltar_3, 
                    target.ltdd_1=src.ltdd_1, 
                    target.ltdd_2=src.ltdd_2, 
                    target.ltdd_3=src.ltdd_3, 
                    target.ltdr_1=src.ltdr_1, 
                    target.ltdr_2=src.ltdr_2, 
                    target.ltdr_3=src.ltdr_3, 
                    target.meth=src.meth, 
                    target.meth_ref_compnr=src.meth_ref_compnr, 
                    target.ocst_1=src.ocst_1, 
                    target.ocst_2=src.ocst_2, 
                    target.ocst_3=src.ocst_3, 
                    target.post=src.post, 
                    target.post_kw=src.post_kw, 
                    target.prop=src.prop, 
                    target.prop_ref_compnr=src.prop_ref_compnr, 
                    target.rcst_1=src.rcst_1, 
                    target.rcst_2=src.rcst_2, 
                    target.rcst_3=src.rcst_3, 
                    target.rdpr_1=src.rdpr_1, 
                    target.rdpr_2=src.rdpr_2, 
                    target.rdpr_3=src.rdpr_3, 
                    target.s179_1=src.s179_1, 
                    target.s179_2=src.s179_2, 
                    target.s179_3=src.s179_3, 
                    target.salv_1=src.salv_1, 
                    target.salv_2=src.salv_2, 
                    target.salv_3=src.salv_3, 
                    target.sdpn=src.sdpn, 
                    target.sequencenumber=src.sequencenumber, 
                    target.shft=src.shft, 
                    target.srac=src.srac, 
                    target.srac_kw=src.srac_kw, 
                    target.stat=src.stat, 
                    target.stat_kw=src.stat_kw, 
                    target.timestamp=src.timestamp, 
                    target.tmth=src.tmth, 
                    target.tmth_kw=src.tmth_kw, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.unit=src.unit, 
                    target.username=src.username, 
                    target.ytdd_1=src.ytdd_1, 
                    target.ytdd_2=src.ytdd_2, 
                    target.ytdd_3=src.ytdd_3, 
                    target.ytdr_1=src.ytdr_1, 
                    target.ytdr_2=src.ytdr_2, 
                    target.ytdr_3=src.ytdr_3, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( adpa_1, adpa_2, adpa_3, adpc, adpc_kw, adpm, adpm_ref_compnr, aext, anbr, anbr_aext_ref_compnr, book, book_ref_compnr, bslv, bslv_kw, c263_1, c263_2, c263_3, capi_1, capi_2, capi_3, compnr, cost_1, cost_2, cost_3, curd, deleted, depr_1, depr_2, depr_3, disd, ecre, ecre_kw, freq, freq_ref_compnr, fydp, gfac_1, gfac_2, gfac_3, indx, indx_ref_compnr, itca_1, itca_2, itca_3, last, life, lrev, ltad_1, ltad_2, ltad_3, ltar_1, ltar_2, ltar_3, ltdd_1, ltdd_2, ltdd_3, ltdr_1, ltdr_2, ltdr_3, meth, meth_ref_compnr, ocst_1, ocst_2, ocst_3, post, post_kw, prop, prop_ref_compnr, rcst_1, rcst_2, rcst_3, rdpr_1, rdpr_2, rdpr_3, s179_1, s179_2, s179_3, salv_1, salv_2, salv_3, sdpn, sequencenumber, shft, srac, srac_kw, stat, stat_kw, timestamp, tmth, tmth_kw, txta, txta_ref_compnr, unit, username, ytdd_1, ytdd_2, ytdd_3, ytdr_1, ytdr_2, ytdr_3, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.adpa_1, 
                    src.adpa_2, 
                    src.adpa_3, 
                    src.adpc, 
                    src.adpc_kw, 
                    src.adpm, 
                    src.adpm_ref_compnr, 
                    src.aext, 
                    src.anbr, 
                    src.anbr_aext_ref_compnr, 
                    src.book, 
                    src.book_ref_compnr, 
                    src.bslv, 
                    src.bslv_kw, 
                    src.c263_1, 
                    src.c263_2, 
                    src.c263_3, 
                    src.capi_1, 
                    src.capi_2, 
                    src.capi_3, 
                    src.compnr, 
                    src.cost_1, 
                    src.cost_2, 
                    src.cost_3, 
                    src.curd, 
                    src.deleted, 
                    src.depr_1, 
                    src.depr_2, 
                    src.depr_3, 
                    src.disd, 
                    src.ecre, 
                    src.ecre_kw, 
                    src.freq, 
                    src.freq_ref_compnr, 
                    src.fydp, 
                    src.gfac_1, 
                    src.gfac_2, 
                    src.gfac_3, 
                    src.indx, 
                    src.indx_ref_compnr, 
                    src.itca_1, 
                    src.itca_2, 
                    src.itca_3, 
                    src.last, 
                    src.life, 
                    src.lrev, 
                    src.ltad_1, 
                    src.ltad_2, 
                    src.ltad_3, 
                    src.ltar_1, 
                    src.ltar_2, 
                    src.ltar_3, 
                    src.ltdd_1, 
                    src.ltdd_2, 
                    src.ltdd_3, 
                    src.ltdr_1, 
                    src.ltdr_2, 
                    src.ltdr_3, 
                    src.meth, 
                    src.meth_ref_compnr, 
                    src.ocst_1, 
                    src.ocst_2, 
                    src.ocst_3, 
                    src.post, 
                    src.post_kw, 
                    src.prop, 
                    src.prop_ref_compnr, 
                    src.rcst_1, 
                    src.rcst_2, 
                    src.rcst_3, 
                    src.rdpr_1, 
                    src.rdpr_2, 
                    src.rdpr_3, 
                    src.s179_1, 
                    src.s179_2, 
                    src.s179_3, 
                    src.salv_1, 
                    src.salv_2, 
                    src.salv_3, 
                    src.sdpn, 
                    src.sequencenumber, 
                    src.shft, 
                    src.srac, 
                    src.srac_kw, 
                    src.stat, 
                    src.stat_kw, 
                    src.timestamp, 
                    src.tmth, 
                    src.tmth_kw, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.unit, 
                    src.username, 
                    src.ytdd_1, 
                    src.ytdd_2, 
                    src.ytdd_3, 
                    src.ytdr_1, 
                    src.ytdr_2, 
                    src.ytdr_3,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;