create or replace procedure DATAHUB_INTEGRATION.SP_LN_TPPPC291()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TPPPC291_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TPPPC291 as target using (SELECT * FROM (SELECT 
            strm.amoc, 
            strm.amos, 
            strm.blbl, 
            strm.blbl_kw, 
            strm.cact, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.cdf_sref, 
            strm.cdf_susr, 
            strm.cdoc, 
            strm.cdoc_ref_compnr, 
            strm.cfpo, 
            strm.cfpo_kw, 
            strm.cico, 
            strm.cohd_1, 
            strm.cohd_2, 
            strm.cohd_3, 
            strm.compnr, 
            strm.cpla, 
            strm.cprj, 
            strm.cprj_cpla_cact_ref_compnr, 
            strm.cprj_cspa_ref_compnr, 
            strm.cprj_cstl_ref_compnr, 
            strm.cprj_ref_compnr, 
            strm.cptc, 
            strm.cptc_ref_compnr, 
            strm.cptc_year_peri_ref_compnr, 
            strm.cptf, 
            strm.cptf_fyea_fper_ref_compnr, 
            strm.cptf_ref_compnr, 
            strm.cpth, 
            strm.cpth_hyea_hper_ref_compnr, 
            strm.cspa, 
            strm.cstl, 
            strm.cuni, 
            strm.cuni_ref_compnr, 
            strm.curc, 
            strm.curc_ref_compnr, 
            strm.curs, 
            strm.curs_ref_compnr, 
            strm.deleted, 
            strm.desc, 
            strm.entu, 
            strm.fcrt, 
            strm.fcrt_kw, 
            strm.fdoc, 
            strm.flin, 
            strm.fper, 
            strm.fsrl, 
            strm.ftln, 
            strm.ftty, 
            strm.fyea, 
            strm.guid, 
            strm.hemn, 
            strm.hemn_ref_compnr, 
            strm.hper, 
            strm.hsrn, 
            strm.hyea, 
            strm.ifbp, 
            strm.ifbp_ref_compnr, 
            strm.loco, 
            strm.ltdt, 
            strm.ncmp, 
            strm.orno, 
            strm.otbp, 
            strm.otbp_ref_compnr, 
            strm.peri, 
            strm.pono, 
            strm.potf, 
            strm.potf_kw, 
            strm.pric, 
            strm.pris, 
            strm.quan, 
            strm.rdas, 
            strm.rdat, 
            strm.rgdt, 
            strm.rper, 
            strm.rtcc_1, 
            strm.rtcc_2, 
            strm.rtcc_3, 
            strm.rtcs_1, 
            strm.rtcs_2, 
            strm.rtcs_3, 
            strm.rtfc_1, 
            strm.rtfc_2, 
            strm.rtfc_3, 
            strm.rtfs_1, 
            strm.rtfs_2, 
            strm.rtfs_3, 
            strm.rtyp, 
            strm.rtyp_ref_compnr, 
            strm.ryea, 
            strm.sequencenumber, 
            strm.sern, 
            strm.srnb, 
            strm.sttl, 
            strm.sttl_kw, 
            strm.teti, 
            strm.teti_kw, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.username, 
            strm.year, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.cprj,
            strm.cico,
            strm.sern ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPPC291 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.cprj=src.cprj) OR (target.cprj IS NULL AND src.cprj IS NULL)) AND
            ((target.cico=src.cico) OR (target.cico IS NULL AND src.cico IS NULL)) AND
            ((target.sern=src.sern) OR (target.sern IS NULL AND src.sern IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.amoc=src.amoc, 
                    target.amos=src.amos, 
                    target.blbl=src.blbl, 
                    target.blbl_kw=src.blbl_kw, 
                    target.cact=src.cact, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.cdf_sref=src.cdf_sref, 
                    target.cdf_susr=src.cdf_susr, 
                    target.cdoc=src.cdoc, 
                    target.cdoc_ref_compnr=src.cdoc_ref_compnr, 
                    target.cfpo=src.cfpo, 
                    target.cfpo_kw=src.cfpo_kw, 
                    target.cico=src.cico, 
                    target.cohd_1=src.cohd_1, 
                    target.cohd_2=src.cohd_2, 
                    target.cohd_3=src.cohd_3, 
                    target.compnr=src.compnr, 
                    target.cpla=src.cpla, 
                    target.cprj=src.cprj, 
                    target.cprj_cpla_cact_ref_compnr=src.cprj_cpla_cact_ref_compnr, 
                    target.cprj_cspa_ref_compnr=src.cprj_cspa_ref_compnr, 
                    target.cprj_cstl_ref_compnr=src.cprj_cstl_ref_compnr, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cptc=src.cptc, 
                    target.cptc_ref_compnr=src.cptc_ref_compnr, 
                    target.cptc_year_peri_ref_compnr=src.cptc_year_peri_ref_compnr, 
                    target.cptf=src.cptf, 
                    target.cptf_fyea_fper_ref_compnr=src.cptf_fyea_fper_ref_compnr, 
                    target.cptf_ref_compnr=src.cptf_ref_compnr, 
                    target.cpth=src.cpth, 
                    target.cpth_hyea_hper_ref_compnr=src.cpth_hyea_hper_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cstl=src.cstl, 
                    target.cuni=src.cuni, 
                    target.cuni_ref_compnr=src.cuni_ref_compnr, 
                    target.curc=src.curc, 
                    target.curc_ref_compnr=src.curc_ref_compnr, 
                    target.curs=src.curs, 
                    target.curs_ref_compnr=src.curs_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.entu=src.entu, 
                    target.fcrt=src.fcrt, 
                    target.fcrt_kw=src.fcrt_kw, 
                    target.fdoc=src.fdoc, 
                    target.flin=src.flin, 
                    target.fper=src.fper, 
                    target.fsrl=src.fsrl, 
                    target.ftln=src.ftln, 
                    target.ftty=src.ftty, 
                    target.fyea=src.fyea, 
                    target.guid=src.guid, 
                    target.hemn=src.hemn, 
                    target.hemn_ref_compnr=src.hemn_ref_compnr, 
                    target.hper=src.hper, 
                    target.hsrn=src.hsrn, 
                    target.hyea=src.hyea, 
                    target.ifbp=src.ifbp, 
                    target.ifbp_ref_compnr=src.ifbp_ref_compnr, 
                    target.loco=src.loco, 
                    target.ltdt=src.ltdt, 
                    target.ncmp=src.ncmp, 
                    target.orno=src.orno, 
                    target.otbp=src.otbp, 
                    target.otbp_ref_compnr=src.otbp_ref_compnr, 
                    target.peri=src.peri, 
                    target.pono=src.pono, 
                    target.potf=src.potf, 
                    target.potf_kw=src.potf_kw, 
                    target.pric=src.pric, 
                    target.pris=src.pris, 
                    target.quan=src.quan, 
                    target.rdas=src.rdas, 
                    target.rdat=src.rdat, 
                    target.rgdt=src.rgdt, 
                    target.rper=src.rper, 
                    target.rtcc_1=src.rtcc_1, 
                    target.rtcc_2=src.rtcc_2, 
                    target.rtcc_3=src.rtcc_3, 
                    target.rtcs_1=src.rtcs_1, 
                    target.rtcs_2=src.rtcs_2, 
                    target.rtcs_3=src.rtcs_3, 
                    target.rtfc_1=src.rtfc_1, 
                    target.rtfc_2=src.rtfc_2, 
                    target.rtfc_3=src.rtfc_3, 
                    target.rtfs_1=src.rtfs_1, 
                    target.rtfs_2=src.rtfs_2, 
                    target.rtfs_3=src.rtfs_3, 
                    target.rtyp=src.rtyp, 
                    target.rtyp_ref_compnr=src.rtyp_ref_compnr, 
                    target.ryea=src.ryea, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sern=src.sern, 
                    target.srnb=src.srnb, 
                    target.sttl=src.sttl, 
                    target.sttl_kw=src.sttl_kw, 
                    target.teti=src.teti, 
                    target.teti_kw=src.teti_kw, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.username=src.username, 
                    target.year=src.year, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    amoc, 
                    amos, 
                    blbl, 
                    blbl_kw, 
                    cact, 
                    ccco, 
                    ccco_ref_compnr, 
                    cdf_sref, 
                    cdf_susr, 
                    cdoc, 
                    cdoc_ref_compnr, 
                    cfpo, 
                    cfpo_kw, 
                    cico, 
                    cohd_1, 
                    cohd_2, 
                    cohd_3, 
                    compnr, 
                    cpla, 
                    cprj, 
                    cprj_cpla_cact_ref_compnr, 
                    cprj_cspa_ref_compnr, 
                    cprj_cstl_ref_compnr, 
                    cprj_ref_compnr, 
                    cptc, 
                    cptc_ref_compnr, 
                    cptc_year_peri_ref_compnr, 
                    cptf, 
                    cptf_fyea_fper_ref_compnr, 
                    cptf_ref_compnr, 
                    cpth, 
                    cpth_hyea_hper_ref_compnr, 
                    cspa, 
                    cstl, 
                    cuni, 
                    cuni_ref_compnr, 
                    curc, 
                    curc_ref_compnr, 
                    curs, 
                    curs_ref_compnr, 
                    deleted, 
                    desc, 
                    entu, 
                    fcrt, 
                    fcrt_kw, 
                    fdoc, 
                    flin, 
                    fper, 
                    fsrl, 
                    ftln, 
                    ftty, 
                    fyea, 
                    guid, 
                    hemn, 
                    hemn_ref_compnr, 
                    hper, 
                    hsrn, 
                    hyea, 
                    ifbp, 
                    ifbp_ref_compnr, 
                    loco, 
                    ltdt, 
                    ncmp, 
                    orno, 
                    otbp, 
                    otbp_ref_compnr, 
                    peri, 
                    pono, 
                    potf, 
                    potf_kw, 
                    pric, 
                    pris, 
                    quan, 
                    rdas, 
                    rdat, 
                    rgdt, 
                    rper, 
                    rtcc_1, 
                    rtcc_2, 
                    rtcc_3, 
                    rtcs_1, 
                    rtcs_2, 
                    rtcs_3, 
                    rtfc_1, 
                    rtfc_2, 
                    rtfc_3, 
                    rtfs_1, 
                    rtfs_2, 
                    rtfs_3, 
                    rtyp, 
                    rtyp_ref_compnr, 
                    ryea, 
                    sequencenumber, 
                    sern, 
                    srnb, 
                    sttl, 
                    sttl_kw, 
                    teti, 
                    teti_kw, 
                    timestamp, 
                    txta, 
                    txta_ref_compnr, 
                    username, 
                    year, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.amoc, 
                    src.amos, 
                    src.blbl, 
                    src.blbl_kw, 
                    src.cact, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.cdf_sref, 
                    src.cdf_susr, 
                    src.cdoc, 
                    src.cdoc_ref_compnr, 
                    src.cfpo, 
                    src.cfpo_kw, 
                    src.cico, 
                    src.cohd_1, 
                    src.cohd_2, 
                    src.cohd_3, 
                    src.compnr, 
                    src.cpla, 
                    src.cprj, 
                    src.cprj_cpla_cact_ref_compnr, 
                    src.cprj_cspa_ref_compnr, 
                    src.cprj_cstl_ref_compnr, 
                    src.cprj_ref_compnr, 
                    src.cptc, 
                    src.cptc_ref_compnr, 
                    src.cptc_year_peri_ref_compnr, 
                    src.cptf, 
                    src.cptf_fyea_fper_ref_compnr, 
                    src.cptf_ref_compnr, 
                    src.cpth, 
                    src.cpth_hyea_hper_ref_compnr, 
                    src.cspa, 
                    src.cstl, 
                    src.cuni, 
                    src.cuni_ref_compnr, 
                    src.curc, 
                    src.curc_ref_compnr, 
                    src.curs, 
                    src.curs_ref_compnr, 
                    src.deleted, 
                    src.desc, 
                    src.entu, 
                    src.fcrt, 
                    src.fcrt_kw, 
                    src.fdoc, 
                    src.flin, 
                    src.fper, 
                    src.fsrl, 
                    src.ftln, 
                    src.ftty, 
                    src.fyea, 
                    src.guid, 
                    src.hemn, 
                    src.hemn_ref_compnr, 
                    src.hper, 
                    src.hsrn, 
                    src.hyea, 
                    src.ifbp, 
                    src.ifbp_ref_compnr, 
                    src.loco, 
                    src.ltdt, 
                    src.ncmp, 
                    src.orno, 
                    src.otbp, 
                    src.otbp_ref_compnr, 
                    src.peri, 
                    src.pono, 
                    src.potf, 
                    src.potf_kw, 
                    src.pric, 
                    src.pris, 
                    src.quan, 
                    src.rdas, 
                    src.rdat, 
                    src.rgdt, 
                    src.rper, 
                    src.rtcc_1, 
                    src.rtcc_2, 
                    src.rtcc_3, 
                    src.rtcs_1, 
                    src.rtcs_2, 
                    src.rtcs_3, 
                    src.rtfc_1, 
                    src.rtfc_2, 
                    src.rtfc_3, 
                    src.rtfs_1, 
                    src.rtfs_2, 
                    src.rtfs_3, 
                    src.rtyp, 
                    src.rtyp_ref_compnr, 
                    src.ryea, 
                    src.sequencenumber, 
                    src.sern, 
                    src.srnb, 
                    src.sttl, 
                    src.sttl_kw, 
                    src.teti, 
                    src.teti_kw, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.username, 
                    src.year,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TPPPC291_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.amoc, 
            strm.amos, 
            strm.blbl, 
            strm.blbl_kw, 
            strm.cact, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.cdf_sref, 
            strm.cdf_susr, 
            strm.cdoc, 
            strm.cdoc_ref_compnr, 
            strm.cfpo, 
            strm.cfpo_kw, 
            strm.cico, 
            strm.cohd_1, 
            strm.cohd_2, 
            strm.cohd_3, 
            strm.compnr, 
            strm.cpla, 
            strm.cprj, 
            strm.cprj_cpla_cact_ref_compnr, 
            strm.cprj_cspa_ref_compnr, 
            strm.cprj_cstl_ref_compnr, 
            strm.cprj_ref_compnr, 
            strm.cptc, 
            strm.cptc_ref_compnr, 
            strm.cptc_year_peri_ref_compnr, 
            strm.cptf, 
            strm.cptf_fyea_fper_ref_compnr, 
            strm.cptf_ref_compnr, 
            strm.cpth, 
            strm.cpth_hyea_hper_ref_compnr, 
            strm.cspa, 
            strm.cstl, 
            strm.cuni, 
            strm.cuni_ref_compnr, 
            strm.curc, 
            strm.curc_ref_compnr, 
            strm.curs, 
            strm.curs_ref_compnr, 
            strm.deleted, 
            strm.desc, 
            strm.entu, 
            strm.fcrt, 
            strm.fcrt_kw, 
            strm.fdoc, 
            strm.flin, 
            strm.fper, 
            strm.fsrl, 
            strm.ftln, 
            strm.ftty, 
            strm.fyea, 
            strm.guid, 
            strm.hemn, 
            strm.hemn_ref_compnr, 
            strm.hper, 
            strm.hsrn, 
            strm.hyea, 
            strm.ifbp, 
            strm.ifbp_ref_compnr, 
            strm.loco, 
            strm.ltdt, 
            strm.ncmp, 
            strm.orno, 
            strm.otbp, 
            strm.otbp_ref_compnr, 
            strm.peri, 
            strm.pono, 
            strm.potf, 
            strm.potf_kw, 
            strm.pric, 
            strm.pris, 
            strm.quan, 
            strm.rdas, 
            strm.rdat, 
            strm.rgdt, 
            strm.rper, 
            strm.rtcc_1, 
            strm.rtcc_2, 
            strm.rtcc_3, 
            strm.rtcs_1, 
            strm.rtcs_2, 
            strm.rtcs_3, 
            strm.rtfc_1, 
            strm.rtfc_2, 
            strm.rtfc_3, 
            strm.rtfs_1, 
            strm.rtfs_2, 
            strm.rtfs_3, 
            strm.rtyp, 
            strm.rtyp_ref_compnr, 
            strm.ryea, 
            strm.sequencenumber, 
            strm.sern, 
            strm.srnb, 
            strm.sttl, 
            strm.sttl_kw, 
            strm.teti, 
            strm.teti_kw, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.username, 
            strm.year, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.cprj,
            strm.cico,
            strm.sern ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPPC291 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.cprj=src.cprj) OR (target.cprj IS NULL AND src.cprj IS NULL)) AND
            ((target.cico=src.cico) OR (target.cico IS NULL AND src.cico IS NULL)) AND
            ((target.sern=src.sern) OR (target.sern IS NULL AND src.sern IS NULL)) 
                when matched then update set
                    target.amoc=src.amoc, 
                    target.amos=src.amos, 
                    target.blbl=src.blbl, 
                    target.blbl_kw=src.blbl_kw, 
                    target.cact=src.cact, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.cdf_sref=src.cdf_sref, 
                    target.cdf_susr=src.cdf_susr, 
                    target.cdoc=src.cdoc, 
                    target.cdoc_ref_compnr=src.cdoc_ref_compnr, 
                    target.cfpo=src.cfpo, 
                    target.cfpo_kw=src.cfpo_kw, 
                    target.cico=src.cico, 
                    target.cohd_1=src.cohd_1, 
                    target.cohd_2=src.cohd_2, 
                    target.cohd_3=src.cohd_3, 
                    target.compnr=src.compnr, 
                    target.cpla=src.cpla, 
                    target.cprj=src.cprj, 
                    target.cprj_cpla_cact_ref_compnr=src.cprj_cpla_cact_ref_compnr, 
                    target.cprj_cspa_ref_compnr=src.cprj_cspa_ref_compnr, 
                    target.cprj_cstl_ref_compnr=src.cprj_cstl_ref_compnr, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cptc=src.cptc, 
                    target.cptc_ref_compnr=src.cptc_ref_compnr, 
                    target.cptc_year_peri_ref_compnr=src.cptc_year_peri_ref_compnr, 
                    target.cptf=src.cptf, 
                    target.cptf_fyea_fper_ref_compnr=src.cptf_fyea_fper_ref_compnr, 
                    target.cptf_ref_compnr=src.cptf_ref_compnr, 
                    target.cpth=src.cpth, 
                    target.cpth_hyea_hper_ref_compnr=src.cpth_hyea_hper_ref_compnr, 
                    target.cspa=src.cspa, 
                    target.cstl=src.cstl, 
                    target.cuni=src.cuni, 
                    target.cuni_ref_compnr=src.cuni_ref_compnr, 
                    target.curc=src.curc, 
                    target.curc_ref_compnr=src.curc_ref_compnr, 
                    target.curs=src.curs, 
                    target.curs_ref_compnr=src.curs_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.entu=src.entu, 
                    target.fcrt=src.fcrt, 
                    target.fcrt_kw=src.fcrt_kw, 
                    target.fdoc=src.fdoc, 
                    target.flin=src.flin, 
                    target.fper=src.fper, 
                    target.fsrl=src.fsrl, 
                    target.ftln=src.ftln, 
                    target.ftty=src.ftty, 
                    target.fyea=src.fyea, 
                    target.guid=src.guid, 
                    target.hemn=src.hemn, 
                    target.hemn_ref_compnr=src.hemn_ref_compnr, 
                    target.hper=src.hper, 
                    target.hsrn=src.hsrn, 
                    target.hyea=src.hyea, 
                    target.ifbp=src.ifbp, 
                    target.ifbp_ref_compnr=src.ifbp_ref_compnr, 
                    target.loco=src.loco, 
                    target.ltdt=src.ltdt, 
                    target.ncmp=src.ncmp, 
                    target.orno=src.orno, 
                    target.otbp=src.otbp, 
                    target.otbp_ref_compnr=src.otbp_ref_compnr, 
                    target.peri=src.peri, 
                    target.pono=src.pono, 
                    target.potf=src.potf, 
                    target.potf_kw=src.potf_kw, 
                    target.pric=src.pric, 
                    target.pris=src.pris, 
                    target.quan=src.quan, 
                    target.rdas=src.rdas, 
                    target.rdat=src.rdat, 
                    target.rgdt=src.rgdt, 
                    target.rper=src.rper, 
                    target.rtcc_1=src.rtcc_1, 
                    target.rtcc_2=src.rtcc_2, 
                    target.rtcc_3=src.rtcc_3, 
                    target.rtcs_1=src.rtcs_1, 
                    target.rtcs_2=src.rtcs_2, 
                    target.rtcs_3=src.rtcs_3, 
                    target.rtfc_1=src.rtfc_1, 
                    target.rtfc_2=src.rtfc_2, 
                    target.rtfc_3=src.rtfc_3, 
                    target.rtfs_1=src.rtfs_1, 
                    target.rtfs_2=src.rtfs_2, 
                    target.rtfs_3=src.rtfs_3, 
                    target.rtyp=src.rtyp, 
                    target.rtyp_ref_compnr=src.rtyp_ref_compnr, 
                    target.ryea=src.ryea, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sern=src.sern, 
                    target.srnb=src.srnb, 
                    target.sttl=src.sttl, 
                    target.sttl_kw=src.sttl_kw, 
                    target.teti=src.teti, 
                    target.teti_kw=src.teti_kw, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.username=src.username, 
                    target.year=src.year, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( amoc, amos, blbl, blbl_kw, cact, ccco, ccco_ref_compnr, cdf_sref, cdf_susr, cdoc, cdoc_ref_compnr, cfpo, cfpo_kw, cico, cohd_1, cohd_2, cohd_3, compnr, cpla, cprj, cprj_cpla_cact_ref_compnr, cprj_cspa_ref_compnr, cprj_cstl_ref_compnr, cprj_ref_compnr, cptc, cptc_ref_compnr, cptc_year_peri_ref_compnr, cptf, cptf_fyea_fper_ref_compnr, cptf_ref_compnr, cpth, cpth_hyea_hper_ref_compnr, cspa, cstl, cuni, cuni_ref_compnr, curc, curc_ref_compnr, curs, curs_ref_compnr, deleted, desc, entu, fcrt, fcrt_kw, fdoc, flin, fper, fsrl, ftln, ftty, fyea, guid, hemn, hemn_ref_compnr, hper, hsrn, hyea, ifbp, ifbp_ref_compnr, loco, ltdt, ncmp, orno, otbp, otbp_ref_compnr, peri, pono, potf, potf_kw, pric, pris, quan, rdas, rdat, rgdt, rper, rtcc_1, rtcc_2, rtcc_3, rtcs_1, rtcs_2, rtcs_3, rtfc_1, rtfc_2, rtfc_3, rtfs_1, rtfs_2, rtfs_3, rtyp, rtyp_ref_compnr, ryea, sequencenumber, sern, srnb, sttl, sttl_kw, teti, teti_kw, timestamp, txta, txta_ref_compnr, username, year, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.amoc, 
                    src.amos, 
                    src.blbl, 
                    src.blbl_kw, 
                    src.cact, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.cdf_sref, 
                    src.cdf_susr, 
                    src.cdoc, 
                    src.cdoc_ref_compnr, 
                    src.cfpo, 
                    src.cfpo_kw, 
                    src.cico, 
                    src.cohd_1, 
                    src.cohd_2, 
                    src.cohd_3, 
                    src.compnr, 
                    src.cpla, 
                    src.cprj, 
                    src.cprj_cpla_cact_ref_compnr, 
                    src.cprj_cspa_ref_compnr, 
                    src.cprj_cstl_ref_compnr, 
                    src.cprj_ref_compnr, 
                    src.cptc, 
                    src.cptc_ref_compnr, 
                    src.cptc_year_peri_ref_compnr, 
                    src.cptf, 
                    src.cptf_fyea_fper_ref_compnr, 
                    src.cptf_ref_compnr, 
                    src.cpth, 
                    src.cpth_hyea_hper_ref_compnr, 
                    src.cspa, 
                    src.cstl, 
                    src.cuni, 
                    src.cuni_ref_compnr, 
                    src.curc, 
                    src.curc_ref_compnr, 
                    src.curs, 
                    src.curs_ref_compnr, 
                    src.deleted, 
                    src.desc, 
                    src.entu, 
                    src.fcrt, 
                    src.fcrt_kw, 
                    src.fdoc, 
                    src.flin, 
                    src.fper, 
                    src.fsrl, 
                    src.ftln, 
                    src.ftty, 
                    src.fyea, 
                    src.guid, 
                    src.hemn, 
                    src.hemn_ref_compnr, 
                    src.hper, 
                    src.hsrn, 
                    src.hyea, 
                    src.ifbp, 
                    src.ifbp_ref_compnr, 
                    src.loco, 
                    src.ltdt, 
                    src.ncmp, 
                    src.orno, 
                    src.otbp, 
                    src.otbp_ref_compnr, 
                    src.peri, 
                    src.pono, 
                    src.potf, 
                    src.potf_kw, 
                    src.pric, 
                    src.pris, 
                    src.quan, 
                    src.rdas, 
                    src.rdat, 
                    src.rgdt, 
                    src.rper, 
                    src.rtcc_1, 
                    src.rtcc_2, 
                    src.rtcc_3, 
                    src.rtcs_1, 
                    src.rtcs_2, 
                    src.rtcs_3, 
                    src.rtfc_1, 
                    src.rtfc_2, 
                    src.rtfc_3, 
                    src.rtfs_1, 
                    src.rtfs_2, 
                    src.rtfs_3, 
                    src.rtyp, 
                    src.rtyp_ref_compnr, 
                    src.ryea, 
                    src.sequencenumber, 
                    src.sern, 
                    src.srnb, 
                    src.sttl, 
                    src.sttl_kw, 
                    src.teti, 
                    src.teti_kw, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.username, 
                    src.year,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;