create or replace procedure DATAHUB_INTEGRATION.SP_LN_TDSLS094()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TDSLS094_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TDSLS094 as target using (SELECT * FROM (SELECT 
            strm.aaps, 
            strm.aaps_kw, 
            strm.aprd, 
            strm.aprd_kw, 
            strm.apur, 
            strm.apur_kw, 
            strm.blcs, 
            strm.cnsi, 
            strm.cnsi_kw, 
            strm.cnsr, 
            strm.cnsr_kw, 
            strm.compnr, 
            strm.coun, 
            strm.coun_kw, 
            strm.cphl, 
            strm.cphl_kw, 
            strm.crdc, 
            strm.crdc_kw, 
            strm.deleted, 
            strm.dsca, 
            strm.efdt, 
            strm.einc, 
            strm.einc_kw, 
            strm.exdt, 
            strm.gmrc, 
            strm.gmrc_kw, 
            strm.incm, 
            strm.incm_kw, 
            strm.mwdl, 
            strm.mwdl_kw, 
            strm.ngsc, 
            strm.ngsc_ref_compnr, 
            strm.ngsc_sesc_ref_compnr, 
            strm.ngso, 
            strm.ngso_ref_compnr, 
            strm.ngso_seso_ref_compnr, 
            strm.ngsq, 
            strm.ngsq_ref_compnr, 
            strm.ngsq_sesq_ref_compnr, 
            strm.pmsk, 
            strm.proc, 
            strm.retb, 
            strm.retb_kw, 
            strm.reto, 
            strm.reto_kw, 
            strm.scon, 
            strm.scon_kw, 
            strm.sdec, 
            strm.sdec_ref_compnr, 
            strm.sequencenumber, 
            strm.sesc, 
            strm.seso, 
            strm.sesq, 
            strm.sotp, 
            strm.spay, 
            strm.spay_ref_compnr, 
            strm.ssoa, 
            strm.ssoa_kw, 
            strm.ssob, 
            strm.ssob_kw, 
            strm.ssoc, 
            strm.ssoc_kw, 
            strm.ssod, 
            strm.ssod_kw, 
            strm.ssoe, 
            strm.ssoe_kw, 
            strm.ssof, 
            strm.ssof_kw, 
            strm.sund, 
            strm.sund_kw, 
            strm.timestamp, 
            strm.udps, 
            strm.udps_kw, 
            strm.upls, 
            strm.upls_kw, 
            strm.upsh, 
            strm.upsh_kw, 
            strm.username, 
            strm.wpal, 
            strm.wpal_kw, 
            strm.wrhp, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.sotp ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDSLS094 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.sotp=src.sotp) OR (target.sotp IS NULL AND src.sotp IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.aaps=src.aaps, 
                    target.aaps_kw=src.aaps_kw, 
                    target.aprd=src.aprd, 
                    target.aprd_kw=src.aprd_kw, 
                    target.apur=src.apur, 
                    target.apur_kw=src.apur_kw, 
                    target.blcs=src.blcs, 
                    target.cnsi=src.cnsi, 
                    target.cnsi_kw=src.cnsi_kw, 
                    target.cnsr=src.cnsr, 
                    target.cnsr_kw=src.cnsr_kw, 
                    target.compnr=src.compnr, 
                    target.coun=src.coun, 
                    target.coun_kw=src.coun_kw, 
                    target.cphl=src.cphl, 
                    target.cphl_kw=src.cphl_kw, 
                    target.crdc=src.crdc, 
                    target.crdc_kw=src.crdc_kw, 
                    target.deleted=src.deleted, 
                    target.dsca=src.dsca, 
                    target.efdt=src.efdt, 
                    target.einc=src.einc, 
                    target.einc_kw=src.einc_kw, 
                    target.exdt=src.exdt, 
                    target.gmrc=src.gmrc, 
                    target.gmrc_kw=src.gmrc_kw, 
                    target.incm=src.incm, 
                    target.incm_kw=src.incm_kw, 
                    target.mwdl=src.mwdl, 
                    target.mwdl_kw=src.mwdl_kw, 
                    target.ngsc=src.ngsc, 
                    target.ngsc_ref_compnr=src.ngsc_ref_compnr, 
                    target.ngsc_sesc_ref_compnr=src.ngsc_sesc_ref_compnr, 
                    target.ngso=src.ngso, 
                    target.ngso_ref_compnr=src.ngso_ref_compnr, 
                    target.ngso_seso_ref_compnr=src.ngso_seso_ref_compnr, 
                    target.ngsq=src.ngsq, 
                    target.ngsq_ref_compnr=src.ngsq_ref_compnr, 
                    target.ngsq_sesq_ref_compnr=src.ngsq_sesq_ref_compnr, 
                    target.pmsk=src.pmsk, 
                    target.proc=src.proc, 
                    target.retb=src.retb, 
                    target.retb_kw=src.retb_kw, 
                    target.reto=src.reto, 
                    target.reto_kw=src.reto_kw, 
                    target.scon=src.scon, 
                    target.scon_kw=src.scon_kw, 
                    target.sdec=src.sdec, 
                    target.sdec_ref_compnr=src.sdec_ref_compnr, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sesc=src.sesc, 
                    target.seso=src.seso, 
                    target.sesq=src.sesq, 
                    target.sotp=src.sotp, 
                    target.spay=src.spay, 
                    target.spay_ref_compnr=src.spay_ref_compnr, 
                    target.ssoa=src.ssoa, 
                    target.ssoa_kw=src.ssoa_kw, 
                    target.ssob=src.ssob, 
                    target.ssob_kw=src.ssob_kw, 
                    target.ssoc=src.ssoc, 
                    target.ssoc_kw=src.ssoc_kw, 
                    target.ssod=src.ssod, 
                    target.ssod_kw=src.ssod_kw, 
                    target.ssoe=src.ssoe, 
                    target.ssoe_kw=src.ssoe_kw, 
                    target.ssof=src.ssof, 
                    target.ssof_kw=src.ssof_kw, 
                    target.sund=src.sund, 
                    target.sund_kw=src.sund_kw, 
                    target.timestamp=src.timestamp, 
                    target.udps=src.udps, 
                    target.udps_kw=src.udps_kw, 
                    target.upls=src.upls, 
                    target.upls_kw=src.upls_kw, 
                    target.upsh=src.upsh, 
                    target.upsh_kw=src.upsh_kw, 
                    target.username=src.username, 
                    target.wpal=src.wpal, 
                    target.wpal_kw=src.wpal_kw, 
                    target.wrhp=src.wrhp, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    aaps, 
                    aaps_kw, 
                    aprd, 
                    aprd_kw, 
                    apur, 
                    apur_kw, 
                    blcs, 
                    cnsi, 
                    cnsi_kw, 
                    cnsr, 
                    cnsr_kw, 
                    compnr, 
                    coun, 
                    coun_kw, 
                    cphl, 
                    cphl_kw, 
                    crdc, 
                    crdc_kw, 
                    deleted, 
                    dsca, 
                    efdt, 
                    einc, 
                    einc_kw, 
                    exdt, 
                    gmrc, 
                    gmrc_kw, 
                    incm, 
                    incm_kw, 
                    mwdl, 
                    mwdl_kw, 
                    ngsc, 
                    ngsc_ref_compnr, 
                    ngsc_sesc_ref_compnr, 
                    ngso, 
                    ngso_ref_compnr, 
                    ngso_seso_ref_compnr, 
                    ngsq, 
                    ngsq_ref_compnr, 
                    ngsq_sesq_ref_compnr, 
                    pmsk, 
                    proc, 
                    retb, 
                    retb_kw, 
                    reto, 
                    reto_kw, 
                    scon, 
                    scon_kw, 
                    sdec, 
                    sdec_ref_compnr, 
                    sequencenumber, 
                    sesc, 
                    seso, 
                    sesq, 
                    sotp, 
                    spay, 
                    spay_ref_compnr, 
                    ssoa, 
                    ssoa_kw, 
                    ssob, 
                    ssob_kw, 
                    ssoc, 
                    ssoc_kw, 
                    ssod, 
                    ssod_kw, 
                    ssoe, 
                    ssoe_kw, 
                    ssof, 
                    ssof_kw, 
                    sund, 
                    sund_kw, 
                    timestamp, 
                    udps, 
                    udps_kw, 
                    upls, 
                    upls_kw, 
                    upsh, 
                    upsh_kw, 
                    username, 
                    wpal, 
                    wpal_kw, 
                    wrhp, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.aaps, 
                    src.aaps_kw, 
                    src.aprd, 
                    src.aprd_kw, 
                    src.apur, 
                    src.apur_kw, 
                    src.blcs, 
                    src.cnsi, 
                    src.cnsi_kw, 
                    src.cnsr, 
                    src.cnsr_kw, 
                    src.compnr, 
                    src.coun, 
                    src.coun_kw, 
                    src.cphl, 
                    src.cphl_kw, 
                    src.crdc, 
                    src.crdc_kw, 
                    src.deleted, 
                    src.dsca, 
                    src.efdt, 
                    src.einc, 
                    src.einc_kw, 
                    src.exdt, 
                    src.gmrc, 
                    src.gmrc_kw, 
                    src.incm, 
                    src.incm_kw, 
                    src.mwdl, 
                    src.mwdl_kw, 
                    src.ngsc, 
                    src.ngsc_ref_compnr, 
                    src.ngsc_sesc_ref_compnr, 
                    src.ngso, 
                    src.ngso_ref_compnr, 
                    src.ngso_seso_ref_compnr, 
                    src.ngsq, 
                    src.ngsq_ref_compnr, 
                    src.ngsq_sesq_ref_compnr, 
                    src.pmsk, 
                    src.proc, 
                    src.retb, 
                    src.retb_kw, 
                    src.reto, 
                    src.reto_kw, 
                    src.scon, 
                    src.scon_kw, 
                    src.sdec, 
                    src.sdec_ref_compnr, 
                    src.sequencenumber, 
                    src.sesc, 
                    src.seso, 
                    src.sesq, 
                    src.sotp, 
                    src.spay, 
                    src.spay_ref_compnr, 
                    src.ssoa, 
                    src.ssoa_kw, 
                    src.ssob, 
                    src.ssob_kw, 
                    src.ssoc, 
                    src.ssoc_kw, 
                    src.ssod, 
                    src.ssod_kw, 
                    src.ssoe, 
                    src.ssoe_kw, 
                    src.ssof, 
                    src.ssof_kw, 
                    src.sund, 
                    src.sund_kw, 
                    src.timestamp, 
                    src.udps, 
                    src.udps_kw, 
                    src.upls, 
                    src.upls_kw, 
                    src.upsh, 
                    src.upsh_kw, 
                    src.username, 
                    src.wpal, 
                    src.wpal_kw, 
                    src.wrhp,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TDSLS094_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.aaps, 
            strm.aaps_kw, 
            strm.aprd, 
            strm.aprd_kw, 
            strm.apur, 
            strm.apur_kw, 
            strm.blcs, 
            strm.cnsi, 
            strm.cnsi_kw, 
            strm.cnsr, 
            strm.cnsr_kw, 
            strm.compnr, 
            strm.coun, 
            strm.coun_kw, 
            strm.cphl, 
            strm.cphl_kw, 
            strm.crdc, 
            strm.crdc_kw, 
            strm.deleted, 
            strm.dsca, 
            strm.efdt, 
            strm.einc, 
            strm.einc_kw, 
            strm.exdt, 
            strm.gmrc, 
            strm.gmrc_kw, 
            strm.incm, 
            strm.incm_kw, 
            strm.mwdl, 
            strm.mwdl_kw, 
            strm.ngsc, 
            strm.ngsc_ref_compnr, 
            strm.ngsc_sesc_ref_compnr, 
            strm.ngso, 
            strm.ngso_ref_compnr, 
            strm.ngso_seso_ref_compnr, 
            strm.ngsq, 
            strm.ngsq_ref_compnr, 
            strm.ngsq_sesq_ref_compnr, 
            strm.pmsk, 
            strm.proc, 
            strm.retb, 
            strm.retb_kw, 
            strm.reto, 
            strm.reto_kw, 
            strm.scon, 
            strm.scon_kw, 
            strm.sdec, 
            strm.sdec_ref_compnr, 
            strm.sequencenumber, 
            strm.sesc, 
            strm.seso, 
            strm.sesq, 
            strm.sotp, 
            strm.spay, 
            strm.spay_ref_compnr, 
            strm.ssoa, 
            strm.ssoa_kw, 
            strm.ssob, 
            strm.ssob_kw, 
            strm.ssoc, 
            strm.ssoc_kw, 
            strm.ssod, 
            strm.ssod_kw, 
            strm.ssoe, 
            strm.ssoe_kw, 
            strm.ssof, 
            strm.ssof_kw, 
            strm.sund, 
            strm.sund_kw, 
            strm.timestamp, 
            strm.udps, 
            strm.udps_kw, 
            strm.upls, 
            strm.upls_kw, 
            strm.upsh, 
            strm.upsh_kw, 
            strm.username, 
            strm.wpal, 
            strm.wpal_kw, 
            strm.wrhp, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.sotp ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TDSLS094 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.sotp=src.sotp) OR (target.sotp IS NULL AND src.sotp IS NULL)) 
                when matched then update set
                    target.aaps=src.aaps, 
                    target.aaps_kw=src.aaps_kw, 
                    target.aprd=src.aprd, 
                    target.aprd_kw=src.aprd_kw, 
                    target.apur=src.apur, 
                    target.apur_kw=src.apur_kw, 
                    target.blcs=src.blcs, 
                    target.cnsi=src.cnsi, 
                    target.cnsi_kw=src.cnsi_kw, 
                    target.cnsr=src.cnsr, 
                    target.cnsr_kw=src.cnsr_kw, 
                    target.compnr=src.compnr, 
                    target.coun=src.coun, 
                    target.coun_kw=src.coun_kw, 
                    target.cphl=src.cphl, 
                    target.cphl_kw=src.cphl_kw, 
                    target.crdc=src.crdc, 
                    target.crdc_kw=src.crdc_kw, 
                    target.deleted=src.deleted, 
                    target.dsca=src.dsca, 
                    target.efdt=src.efdt, 
                    target.einc=src.einc, 
                    target.einc_kw=src.einc_kw, 
                    target.exdt=src.exdt, 
                    target.gmrc=src.gmrc, 
                    target.gmrc_kw=src.gmrc_kw, 
                    target.incm=src.incm, 
                    target.incm_kw=src.incm_kw, 
                    target.mwdl=src.mwdl, 
                    target.mwdl_kw=src.mwdl_kw, 
                    target.ngsc=src.ngsc, 
                    target.ngsc_ref_compnr=src.ngsc_ref_compnr, 
                    target.ngsc_sesc_ref_compnr=src.ngsc_sesc_ref_compnr, 
                    target.ngso=src.ngso, 
                    target.ngso_ref_compnr=src.ngso_ref_compnr, 
                    target.ngso_seso_ref_compnr=src.ngso_seso_ref_compnr, 
                    target.ngsq=src.ngsq, 
                    target.ngsq_ref_compnr=src.ngsq_ref_compnr, 
                    target.ngsq_sesq_ref_compnr=src.ngsq_sesq_ref_compnr, 
                    target.pmsk=src.pmsk, 
                    target.proc=src.proc, 
                    target.retb=src.retb, 
                    target.retb_kw=src.retb_kw, 
                    target.reto=src.reto, 
                    target.reto_kw=src.reto_kw, 
                    target.scon=src.scon, 
                    target.scon_kw=src.scon_kw, 
                    target.sdec=src.sdec, 
                    target.sdec_ref_compnr=src.sdec_ref_compnr, 
                    target.sequencenumber=src.sequencenumber, 
                    target.sesc=src.sesc, 
                    target.seso=src.seso, 
                    target.sesq=src.sesq, 
                    target.sotp=src.sotp, 
                    target.spay=src.spay, 
                    target.spay_ref_compnr=src.spay_ref_compnr, 
                    target.ssoa=src.ssoa, 
                    target.ssoa_kw=src.ssoa_kw, 
                    target.ssob=src.ssob, 
                    target.ssob_kw=src.ssob_kw, 
                    target.ssoc=src.ssoc, 
                    target.ssoc_kw=src.ssoc_kw, 
                    target.ssod=src.ssod, 
                    target.ssod_kw=src.ssod_kw, 
                    target.ssoe=src.ssoe, 
                    target.ssoe_kw=src.ssoe_kw, 
                    target.ssof=src.ssof, 
                    target.ssof_kw=src.ssof_kw, 
                    target.sund=src.sund, 
                    target.sund_kw=src.sund_kw, 
                    target.timestamp=src.timestamp, 
                    target.udps=src.udps, 
                    target.udps_kw=src.udps_kw, 
                    target.upls=src.upls, 
                    target.upls_kw=src.upls_kw, 
                    target.upsh=src.upsh, 
                    target.upsh_kw=src.upsh_kw, 
                    target.username=src.username, 
                    target.wpal=src.wpal, 
                    target.wpal_kw=src.wpal_kw, 
                    target.wrhp=src.wrhp, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( aaps, aaps_kw, aprd, aprd_kw, apur, apur_kw, blcs, cnsi, cnsi_kw, cnsr, cnsr_kw, compnr, coun, coun_kw, cphl, cphl_kw, crdc, crdc_kw, deleted, dsca, efdt, einc, einc_kw, exdt, gmrc, gmrc_kw, incm, incm_kw, mwdl, mwdl_kw, ngsc, ngsc_ref_compnr, ngsc_sesc_ref_compnr, ngso, ngso_ref_compnr, ngso_seso_ref_compnr, ngsq, ngsq_ref_compnr, ngsq_sesq_ref_compnr, pmsk, proc, retb, retb_kw, reto, reto_kw, scon, scon_kw, sdec, sdec_ref_compnr, sequencenumber, sesc, seso, sesq, sotp, spay, spay_ref_compnr, ssoa, ssoa_kw, ssob, ssob_kw, ssoc, ssoc_kw, ssod, ssod_kw, ssoe, ssoe_kw, ssof, ssof_kw, sund, sund_kw, timestamp, udps, udps_kw, upls, upls_kw, upsh, upsh_kw, username, wpal, wpal_kw, wrhp, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.aaps, 
                    src.aaps_kw, 
                    src.aprd, 
                    src.aprd_kw, 
                    src.apur, 
                    src.apur_kw, 
                    src.blcs, 
                    src.cnsi, 
                    src.cnsi_kw, 
                    src.cnsr, 
                    src.cnsr_kw, 
                    src.compnr, 
                    src.coun, 
                    src.coun_kw, 
                    src.cphl, 
                    src.cphl_kw, 
                    src.crdc, 
                    src.crdc_kw, 
                    src.deleted, 
                    src.dsca, 
                    src.efdt, 
                    src.einc, 
                    src.einc_kw, 
                    src.exdt, 
                    src.gmrc, 
                    src.gmrc_kw, 
                    src.incm, 
                    src.incm_kw, 
                    src.mwdl, 
                    src.mwdl_kw, 
                    src.ngsc, 
                    src.ngsc_ref_compnr, 
                    src.ngsc_sesc_ref_compnr, 
                    src.ngso, 
                    src.ngso_ref_compnr, 
                    src.ngso_seso_ref_compnr, 
                    src.ngsq, 
                    src.ngsq_ref_compnr, 
                    src.ngsq_sesq_ref_compnr, 
                    src.pmsk, 
                    src.proc, 
                    src.retb, 
                    src.retb_kw, 
                    src.reto, 
                    src.reto_kw, 
                    src.scon, 
                    src.scon_kw, 
                    src.sdec, 
                    src.sdec_ref_compnr, 
                    src.sequencenumber, 
                    src.sesc, 
                    src.seso, 
                    src.sesq, 
                    src.sotp, 
                    src.spay, 
                    src.spay_ref_compnr, 
                    src.ssoa, 
                    src.ssoa_kw, 
                    src.ssob, 
                    src.ssob_kw, 
                    src.ssoc, 
                    src.ssoc_kw, 
                    src.ssod, 
                    src.ssod_kw, 
                    src.ssoe, 
                    src.ssoe_kw, 
                    src.ssof, 
                    src.ssof_kw, 
                    src.sund, 
                    src.sund_kw, 
                    src.timestamp, 
                    src.udps, 
                    src.udps_kw, 
                    src.upls, 
                    src.upls_kw, 
                    src.upsh, 
                    src.upsh_kw, 
                    src.username, 
                    src.wpal, 
                    src.wpal_kw, 
                    src.wrhp,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;