create or replace procedure DATAHUB_INTEGRATION.SP_LN_WHINH501()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_WHINH501_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_WHINH501 as target using (SELECT * FROM (SELECT 
            strm.adpr, 
            strm.amnt, 
            strm.appr, 
            strm.appr_kw, 
            strm.atse, 
            strm.cadj, 
            strm.cadj_ref_compnr, 
            strm.cdat, 
            strm.clot, 
            strm.cntn, 
            strm.coln, 
            strm.compnr, 
            strm.csts, 
            strm.csts_kw, 
            strm.cwar, 
            strm.cwar_loca_ref_compnr, 
            strm.cwar_ref_compnr, 
            strm.deleted, 
            strm.dpby, 
            strm.dpby_kw, 
            strm.huid, 
            strm.huid_ref_compnr, 
            strm.hupr, 
            strm.hupr_kw, 
            strm.idat, 
            strm.ifbp, 
            strm.ifbp_ref_compnr, 
            strm.iown, 
            strm.iown_kw, 
            strm.istr, 
            strm.istr_kw, 
            strm.itag, 
            strm.item, 
            strm.item_clot_ref_compnr, 
            strm.item_ref_compnr, 
            strm.loca, 
            strm.nstp, 
            strm.nstp_kw, 
            strm.orno, 
            strm.orno_cntn_ref_compnr, 
            strm.ownr, 
            strm.ownr_ref_compnr, 
            strm.owns, 
            strm.owns_kw, 
            strm.pkdf, 
            strm.pkdf_ref_compnr, 
            strm.pono, 
            strm.prcd, 
            strm.prcd_kw, 
            strm.pric, 
            strm.qcnr, 
            strm.qcnt, 
            strm.qcpu, 
            strm.qspu, 
            strm.qstp, 
            strm.qstr, 
            strm.qvpu, 
            strm.qvrc, 
            strm.qvrr, 
            strm.rack, 
            strm.reco, 
            strm.reco_kw, 
            strm.rowc, 
            strm.rowc_ref_compnr, 
            strm.rown, 
            strm.rown_ref_compnr, 
            strm.sequencenumber, 
            strm.spcn, 
            strm.strt, 
            strm.stun, 
            strm.stun_ref_compnr, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.uapr, 
            strm.uapr_kw, 
            strm.username, 
            strm.zone, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.orno,
            strm.cntn,
            strm.pono ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_WHINH501 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.orno=src.orno) OR (target.orno IS NULL AND src.orno IS NULL)) AND
            ((target.cntn=src.cntn) OR (target.cntn IS NULL AND src.cntn IS NULL)) AND
            ((target.pono=src.pono) OR (target.pono IS NULL AND src.pono IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.adpr=src.adpr, 
                    target.amnt=src.amnt, 
                    target.appr=src.appr, 
                    target.appr_kw=src.appr_kw, 
                    target.atse=src.atse, 
                    target.cadj=src.cadj, 
                    target.cadj_ref_compnr=src.cadj_ref_compnr, 
                    target.cdat=src.cdat, 
                    target.clot=src.clot, 
                    target.cntn=src.cntn, 
                    target.coln=src.coln, 
                    target.compnr=src.compnr, 
                    target.csts=src.csts, 
                    target.csts_kw=src.csts_kw, 
                    target.cwar=src.cwar, 
                    target.cwar_loca_ref_compnr=src.cwar_loca_ref_compnr, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dpby=src.dpby, 
                    target.dpby_kw=src.dpby_kw, 
                    target.huid=src.huid, 
                    target.huid_ref_compnr=src.huid_ref_compnr, 
                    target.hupr=src.hupr, 
                    target.hupr_kw=src.hupr_kw, 
                    target.idat=src.idat, 
                    target.ifbp=src.ifbp, 
                    target.ifbp_ref_compnr=src.ifbp_ref_compnr, 
                    target.iown=src.iown, 
                    target.iown_kw=src.iown_kw, 
                    target.istr=src.istr, 
                    target.istr_kw=src.istr_kw, 
                    target.itag=src.itag, 
                    target.item=src.item, 
                    target.item_clot_ref_compnr=src.item_clot_ref_compnr, 
                    target.item_ref_compnr=src.item_ref_compnr, 
                    target.loca=src.loca, 
                    target.nstp=src.nstp, 
                    target.nstp_kw=src.nstp_kw, 
                    target.orno=src.orno, 
                    target.orno_cntn_ref_compnr=src.orno_cntn_ref_compnr, 
                    target.ownr=src.ownr, 
                    target.ownr_ref_compnr=src.ownr_ref_compnr, 
                    target.owns=src.owns, 
                    target.owns_kw=src.owns_kw, 
                    target.pkdf=src.pkdf, 
                    target.pkdf_ref_compnr=src.pkdf_ref_compnr, 
                    target.pono=src.pono, 
                    target.prcd=src.prcd, 
                    target.prcd_kw=src.prcd_kw, 
                    target.pric=src.pric, 
                    target.qcnr=src.qcnr, 
                    target.qcnt=src.qcnt, 
                    target.qcpu=src.qcpu, 
                    target.qspu=src.qspu, 
                    target.qstp=src.qstp, 
                    target.qstr=src.qstr, 
                    target.qvpu=src.qvpu, 
                    target.qvrc=src.qvrc, 
                    target.qvrr=src.qvrr, 
                    target.rack=src.rack, 
                    target.reco=src.reco, 
                    target.reco_kw=src.reco_kw, 
                    target.rowc=src.rowc, 
                    target.rowc_ref_compnr=src.rowc_ref_compnr, 
                    target.rown=src.rown, 
                    target.rown_ref_compnr=src.rown_ref_compnr, 
                    target.sequencenumber=src.sequencenumber, 
                    target.spcn=src.spcn, 
                    target.strt=src.strt, 
                    target.stun=src.stun, 
                    target.stun_ref_compnr=src.stun_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.uapr=src.uapr, 
                    target.uapr_kw=src.uapr_kw, 
                    target.username=src.username, 
                    target.zone=src.zone, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    adpr, 
                    amnt, 
                    appr, 
                    appr_kw, 
                    atse, 
                    cadj, 
                    cadj_ref_compnr, 
                    cdat, 
                    clot, 
                    cntn, 
                    coln, 
                    compnr, 
                    csts, 
                    csts_kw, 
                    cwar, 
                    cwar_loca_ref_compnr, 
                    cwar_ref_compnr, 
                    deleted, 
                    dpby, 
                    dpby_kw, 
                    huid, 
                    huid_ref_compnr, 
                    hupr, 
                    hupr_kw, 
                    idat, 
                    ifbp, 
                    ifbp_ref_compnr, 
                    iown, 
                    iown_kw, 
                    istr, 
                    istr_kw, 
                    itag, 
                    item, 
                    item_clot_ref_compnr, 
                    item_ref_compnr, 
                    loca, 
                    nstp, 
                    nstp_kw, 
                    orno, 
                    orno_cntn_ref_compnr, 
                    ownr, 
                    ownr_ref_compnr, 
                    owns, 
                    owns_kw, 
                    pkdf, 
                    pkdf_ref_compnr, 
                    pono, 
                    prcd, 
                    prcd_kw, 
                    pric, 
                    qcnr, 
                    qcnt, 
                    qcpu, 
                    qspu, 
                    qstp, 
                    qstr, 
                    qvpu, 
                    qvrc, 
                    qvrr, 
                    rack, 
                    reco, 
                    reco_kw, 
                    rowc, 
                    rowc_ref_compnr, 
                    rown, 
                    rown_ref_compnr, 
                    sequencenumber, 
                    spcn, 
                    strt, 
                    stun, 
                    stun_ref_compnr, 
                    timestamp, 
                    txta, 
                    txta_ref_compnr, 
                    uapr, 
                    uapr_kw, 
                    username, 
                    zone, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.adpr, 
                    src.amnt, 
                    src.appr, 
                    src.appr_kw, 
                    src.atse, 
                    src.cadj, 
                    src.cadj_ref_compnr, 
                    src.cdat, 
                    src.clot, 
                    src.cntn, 
                    src.coln, 
                    src.compnr, 
                    src.csts, 
                    src.csts_kw, 
                    src.cwar, 
                    src.cwar_loca_ref_compnr, 
                    src.cwar_ref_compnr, 
                    src.deleted, 
                    src.dpby, 
                    src.dpby_kw, 
                    src.huid, 
                    src.huid_ref_compnr, 
                    src.hupr, 
                    src.hupr_kw, 
                    src.idat, 
                    src.ifbp, 
                    src.ifbp_ref_compnr, 
                    src.iown, 
                    src.iown_kw, 
                    src.istr, 
                    src.istr_kw, 
                    src.itag, 
                    src.item, 
                    src.item_clot_ref_compnr, 
                    src.item_ref_compnr, 
                    src.loca, 
                    src.nstp, 
                    src.nstp_kw, 
                    src.orno, 
                    src.orno_cntn_ref_compnr, 
                    src.ownr, 
                    src.ownr_ref_compnr, 
                    src.owns, 
                    src.owns_kw, 
                    src.pkdf, 
                    src.pkdf_ref_compnr, 
                    src.pono, 
                    src.prcd, 
                    src.prcd_kw, 
                    src.pric, 
                    src.qcnr, 
                    src.qcnt, 
                    src.qcpu, 
                    src.qspu, 
                    src.qstp, 
                    src.qstr, 
                    src.qvpu, 
                    src.qvrc, 
                    src.qvrr, 
                    src.rack, 
                    src.reco, 
                    src.reco_kw, 
                    src.rowc, 
                    src.rowc_ref_compnr, 
                    src.rown, 
                    src.rown_ref_compnr, 
                    src.sequencenumber, 
                    src.spcn, 
                    src.strt, 
                    src.stun, 
                    src.stun_ref_compnr, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.uapr, 
                    src.uapr_kw, 
                    src.username, 
                    src.zone,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_WHINH501_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.adpr, 
            strm.amnt, 
            strm.appr, 
            strm.appr_kw, 
            strm.atse, 
            strm.cadj, 
            strm.cadj_ref_compnr, 
            strm.cdat, 
            strm.clot, 
            strm.cntn, 
            strm.coln, 
            strm.compnr, 
            strm.csts, 
            strm.csts_kw, 
            strm.cwar, 
            strm.cwar_loca_ref_compnr, 
            strm.cwar_ref_compnr, 
            strm.deleted, 
            strm.dpby, 
            strm.dpby_kw, 
            strm.huid, 
            strm.huid_ref_compnr, 
            strm.hupr, 
            strm.hupr_kw, 
            strm.idat, 
            strm.ifbp, 
            strm.ifbp_ref_compnr, 
            strm.iown, 
            strm.iown_kw, 
            strm.istr, 
            strm.istr_kw, 
            strm.itag, 
            strm.item, 
            strm.item_clot_ref_compnr, 
            strm.item_ref_compnr, 
            strm.loca, 
            strm.nstp, 
            strm.nstp_kw, 
            strm.orno, 
            strm.orno_cntn_ref_compnr, 
            strm.ownr, 
            strm.ownr_ref_compnr, 
            strm.owns, 
            strm.owns_kw, 
            strm.pkdf, 
            strm.pkdf_ref_compnr, 
            strm.pono, 
            strm.prcd, 
            strm.prcd_kw, 
            strm.pric, 
            strm.qcnr, 
            strm.qcnt, 
            strm.qcpu, 
            strm.qspu, 
            strm.qstp, 
            strm.qstr, 
            strm.qvpu, 
            strm.qvrc, 
            strm.qvrr, 
            strm.rack, 
            strm.reco, 
            strm.reco_kw, 
            strm.rowc, 
            strm.rowc_ref_compnr, 
            strm.rown, 
            strm.rown_ref_compnr, 
            strm.sequencenumber, 
            strm.spcn, 
            strm.strt, 
            strm.stun, 
            strm.stun_ref_compnr, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.uapr, 
            strm.uapr_kw, 
            strm.username, 
            strm.zone, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.orno,
            strm.cntn,
            strm.pono ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_WHINH501 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.orno=src.orno) OR (target.orno IS NULL AND src.orno IS NULL)) AND
            ((target.cntn=src.cntn) OR (target.cntn IS NULL AND src.cntn IS NULL)) AND
            ((target.pono=src.pono) OR (target.pono IS NULL AND src.pono IS NULL)) 
                when matched then update set
                    target.adpr=src.adpr, 
                    target.amnt=src.amnt, 
                    target.appr=src.appr, 
                    target.appr_kw=src.appr_kw, 
                    target.atse=src.atse, 
                    target.cadj=src.cadj, 
                    target.cadj_ref_compnr=src.cadj_ref_compnr, 
                    target.cdat=src.cdat, 
                    target.clot=src.clot, 
                    target.cntn=src.cntn, 
                    target.coln=src.coln, 
                    target.compnr=src.compnr, 
                    target.csts=src.csts, 
                    target.csts_kw=src.csts_kw, 
                    target.cwar=src.cwar, 
                    target.cwar_loca_ref_compnr=src.cwar_loca_ref_compnr, 
                    target.cwar_ref_compnr=src.cwar_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dpby=src.dpby, 
                    target.dpby_kw=src.dpby_kw, 
                    target.huid=src.huid, 
                    target.huid_ref_compnr=src.huid_ref_compnr, 
                    target.hupr=src.hupr, 
                    target.hupr_kw=src.hupr_kw, 
                    target.idat=src.idat, 
                    target.ifbp=src.ifbp, 
                    target.ifbp_ref_compnr=src.ifbp_ref_compnr, 
                    target.iown=src.iown, 
                    target.iown_kw=src.iown_kw, 
                    target.istr=src.istr, 
                    target.istr_kw=src.istr_kw, 
                    target.itag=src.itag, 
                    target.item=src.item, 
                    target.item_clot_ref_compnr=src.item_clot_ref_compnr, 
                    target.item_ref_compnr=src.item_ref_compnr, 
                    target.loca=src.loca, 
                    target.nstp=src.nstp, 
                    target.nstp_kw=src.nstp_kw, 
                    target.orno=src.orno, 
                    target.orno_cntn_ref_compnr=src.orno_cntn_ref_compnr, 
                    target.ownr=src.ownr, 
                    target.ownr_ref_compnr=src.ownr_ref_compnr, 
                    target.owns=src.owns, 
                    target.owns_kw=src.owns_kw, 
                    target.pkdf=src.pkdf, 
                    target.pkdf_ref_compnr=src.pkdf_ref_compnr, 
                    target.pono=src.pono, 
                    target.prcd=src.prcd, 
                    target.prcd_kw=src.prcd_kw, 
                    target.pric=src.pric, 
                    target.qcnr=src.qcnr, 
                    target.qcnt=src.qcnt, 
                    target.qcpu=src.qcpu, 
                    target.qspu=src.qspu, 
                    target.qstp=src.qstp, 
                    target.qstr=src.qstr, 
                    target.qvpu=src.qvpu, 
                    target.qvrc=src.qvrc, 
                    target.qvrr=src.qvrr, 
                    target.rack=src.rack, 
                    target.reco=src.reco, 
                    target.reco_kw=src.reco_kw, 
                    target.rowc=src.rowc, 
                    target.rowc_ref_compnr=src.rowc_ref_compnr, 
                    target.rown=src.rown, 
                    target.rown_ref_compnr=src.rown_ref_compnr, 
                    target.sequencenumber=src.sequencenumber, 
                    target.spcn=src.spcn, 
                    target.strt=src.strt, 
                    target.stun=src.stun, 
                    target.stun_ref_compnr=src.stun_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.uapr=src.uapr, 
                    target.uapr_kw=src.uapr_kw, 
                    target.username=src.username, 
                    target.zone=src.zone, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( adpr, amnt, appr, appr_kw, atse, cadj, cadj_ref_compnr, cdat, clot, cntn, coln, compnr, csts, csts_kw, cwar, cwar_loca_ref_compnr, cwar_ref_compnr, deleted, dpby, dpby_kw, huid, huid_ref_compnr, hupr, hupr_kw, idat, ifbp, ifbp_ref_compnr, iown, iown_kw, istr, istr_kw, itag, item, item_clot_ref_compnr, item_ref_compnr, loca, nstp, nstp_kw, orno, orno_cntn_ref_compnr, ownr, ownr_ref_compnr, owns, owns_kw, pkdf, pkdf_ref_compnr, pono, prcd, prcd_kw, pric, qcnr, qcnt, qcpu, qspu, qstp, qstr, qvpu, qvrc, qvrr, rack, reco, reco_kw, rowc, rowc_ref_compnr, rown, rown_ref_compnr, sequencenumber, spcn, strt, stun, stun_ref_compnr, timestamp, txta, txta_ref_compnr, uapr, uapr_kw, username, zone, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.adpr, 
                    src.amnt, 
                    src.appr, 
                    src.appr_kw, 
                    src.atse, 
                    src.cadj, 
                    src.cadj_ref_compnr, 
                    src.cdat, 
                    src.clot, 
                    src.cntn, 
                    src.coln, 
                    src.compnr, 
                    src.csts, 
                    src.csts_kw, 
                    src.cwar, 
                    src.cwar_loca_ref_compnr, 
                    src.cwar_ref_compnr, 
                    src.deleted, 
                    src.dpby, 
                    src.dpby_kw, 
                    src.huid, 
                    src.huid_ref_compnr, 
                    src.hupr, 
                    src.hupr_kw, 
                    src.idat, 
                    src.ifbp, 
                    src.ifbp_ref_compnr, 
                    src.iown, 
                    src.iown_kw, 
                    src.istr, 
                    src.istr_kw, 
                    src.itag, 
                    src.item, 
                    src.item_clot_ref_compnr, 
                    src.item_ref_compnr, 
                    src.loca, 
                    src.nstp, 
                    src.nstp_kw, 
                    src.orno, 
                    src.orno_cntn_ref_compnr, 
                    src.ownr, 
                    src.ownr_ref_compnr, 
                    src.owns, 
                    src.owns_kw, 
                    src.pkdf, 
                    src.pkdf_ref_compnr, 
                    src.pono, 
                    src.prcd, 
                    src.prcd_kw, 
                    src.pric, 
                    src.qcnr, 
                    src.qcnt, 
                    src.qcpu, 
                    src.qspu, 
                    src.qstp, 
                    src.qstr, 
                    src.qvpu, 
                    src.qvrc, 
                    src.qvrr, 
                    src.rack, 
                    src.reco, 
                    src.reco_kw, 
                    src.rowc, 
                    src.rowc_ref_compnr, 
                    src.rown, 
                    src.rown_ref_compnr, 
                    src.sequencenumber, 
                    src.spcn, 
                    src.strt, 
                    src.stun, 
                    src.stun_ref_compnr, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.uapr, 
                    src.uapr_kw, 
                    src.username, 
                    src.zone,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;