create or replace procedure DATAHUB_INTEGRATION.SP_LN_TFFAM820()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TFFAM820_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TFFAM820 as target using (SELECT * FROM (SELECT 
            strm.acmc_1, 
            strm.acmc_2, 
            strm.acmc_3, 
            strm.acmz, 
            strm.acmz_kw, 
            strm.apam_1, 
            strm.apam_2, 
            strm.apam_3, 
            strm.apaz, 
            strm.apaz_kw, 
            strm.capi_1, 
            strm.capi_2, 
            strm.capi_3, 
            strm.capz, 
            strm.capz_kw, 
            strm.compnr, 
            strm.cost_1, 
            strm.cost_2, 
            strm.cost_3, 
            strm.cosz, 
            strm.cosz_kw, 
            strm.curr, 
            strm.deleted, 
            strm.itca_1, 
            strm.itca_2, 
            strm.itca_3, 
            strm.itcz, 
            strm.itcz_kw, 
            strm.life, 
            strm.lifz, 
            strm.lifz_kw, 
            strm.ltdd_1, 
            strm.ltdd_2, 
            strm.ltdd_3, 
            strm.ltdz, 
            strm.ltdz_kw, 
            strm.ratd, 
            strm.rate_1, 
            strm.rate_2, 
            strm.rate_3, 
            strm.ratf_1, 
            strm.ratf_2, 
            strm.ratf_3, 
            strm.reas, 
            strm.reas_ref_compnr, 
            strm.revl, 
            strm.revl_kw, 
            strm.rtyp, 
            strm.s179_1, 
            strm.s179_2, 
            strm.s179_3, 
            strm.s17z, 
            strm.s17z_kw, 
            strm.salv_1, 
            strm.salv_2, 
            strm.salv_3, 
            strm.salz, 
            strm.salz_kw, 
            strm.sequencenumber, 
            strm.timestamp, 
            strm.tkey, 
            strm.tkey_ref_compnr, 
            strm.traf, 
            strm.traf_kw, 
            strm.user, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.tkey ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFFAM820 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.tkey=src.tkey) OR (target.tkey IS NULL AND src.tkey IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.acmc_1=src.acmc_1, 
                    target.acmc_2=src.acmc_2, 
                    target.acmc_3=src.acmc_3, 
                    target.acmz=src.acmz, 
                    target.acmz_kw=src.acmz_kw, 
                    target.apam_1=src.apam_1, 
                    target.apam_2=src.apam_2, 
                    target.apam_3=src.apam_3, 
                    target.apaz=src.apaz, 
                    target.apaz_kw=src.apaz_kw, 
                    target.capi_1=src.capi_1, 
                    target.capi_2=src.capi_2, 
                    target.capi_3=src.capi_3, 
                    target.capz=src.capz, 
                    target.capz_kw=src.capz_kw, 
                    target.compnr=src.compnr, 
                    target.cost_1=src.cost_1, 
                    target.cost_2=src.cost_2, 
                    target.cost_3=src.cost_3, 
                    target.cosz=src.cosz, 
                    target.cosz_kw=src.cosz_kw, 
                    target.curr=src.curr, 
                    target.deleted=src.deleted, 
                    target.itca_1=src.itca_1, 
                    target.itca_2=src.itca_2, 
                    target.itca_3=src.itca_3, 
                    target.itcz=src.itcz, 
                    target.itcz_kw=src.itcz_kw, 
                    target.life=src.life, 
                    target.lifz=src.lifz, 
                    target.lifz_kw=src.lifz_kw, 
                    target.ltdd_1=src.ltdd_1, 
                    target.ltdd_2=src.ltdd_2, 
                    target.ltdd_3=src.ltdd_3, 
                    target.ltdz=src.ltdz, 
                    target.ltdz_kw=src.ltdz_kw, 
                    target.ratd=src.ratd, 
                    target.rate_1=src.rate_1, 
                    target.rate_2=src.rate_2, 
                    target.rate_3=src.rate_3, 
                    target.ratf_1=src.ratf_1, 
                    target.ratf_2=src.ratf_2, 
                    target.ratf_3=src.ratf_3, 
                    target.reas=src.reas, 
                    target.reas_ref_compnr=src.reas_ref_compnr, 
                    target.revl=src.revl, 
                    target.revl_kw=src.revl_kw, 
                    target.rtyp=src.rtyp, 
                    target.s179_1=src.s179_1, 
                    target.s179_2=src.s179_2, 
                    target.s179_3=src.s179_3, 
                    target.s17z=src.s17z, 
                    target.s17z_kw=src.s17z_kw, 
                    target.salv_1=src.salv_1, 
                    target.salv_2=src.salv_2, 
                    target.salv_3=src.salv_3, 
                    target.salz=src.salz, 
                    target.salz_kw=src.salz_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.timestamp=src.timestamp, 
                    target.tkey=src.tkey, 
                    target.tkey_ref_compnr=src.tkey_ref_compnr, 
                    target.traf=src.traf, 
                    target.traf_kw=src.traf_kw, 
                    target.user=src.user, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    acmc_1, 
                    acmc_2, 
                    acmc_3, 
                    acmz, 
                    acmz_kw, 
                    apam_1, 
                    apam_2, 
                    apam_3, 
                    apaz, 
                    apaz_kw, 
                    capi_1, 
                    capi_2, 
                    capi_3, 
                    capz, 
                    capz_kw, 
                    compnr, 
                    cost_1, 
                    cost_2, 
                    cost_3, 
                    cosz, 
                    cosz_kw, 
                    curr, 
                    deleted, 
                    itca_1, 
                    itca_2, 
                    itca_3, 
                    itcz, 
                    itcz_kw, 
                    life, 
                    lifz, 
                    lifz_kw, 
                    ltdd_1, 
                    ltdd_2, 
                    ltdd_3, 
                    ltdz, 
                    ltdz_kw, 
                    ratd, 
                    rate_1, 
                    rate_2, 
                    rate_3, 
                    ratf_1, 
                    ratf_2, 
                    ratf_3, 
                    reas, 
                    reas_ref_compnr, 
                    revl, 
                    revl_kw, 
                    rtyp, 
                    s179_1, 
                    s179_2, 
                    s179_3, 
                    s17z, 
                    s17z_kw, 
                    salv_1, 
                    salv_2, 
                    salv_3, 
                    salz, 
                    salz_kw, 
                    sequencenumber, 
                    timestamp, 
                    tkey, 
                    tkey_ref_compnr, 
                    traf, 
                    traf_kw, 
                    user, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.acmc_1, 
                    src.acmc_2, 
                    src.acmc_3, 
                    src.acmz, 
                    src.acmz_kw, 
                    src.apam_1, 
                    src.apam_2, 
                    src.apam_3, 
                    src.apaz, 
                    src.apaz_kw, 
                    src.capi_1, 
                    src.capi_2, 
                    src.capi_3, 
                    src.capz, 
                    src.capz_kw, 
                    src.compnr, 
                    src.cost_1, 
                    src.cost_2, 
                    src.cost_3, 
                    src.cosz, 
                    src.cosz_kw, 
                    src.curr, 
                    src.deleted, 
                    src.itca_1, 
                    src.itca_2, 
                    src.itca_3, 
                    src.itcz, 
                    src.itcz_kw, 
                    src.life, 
                    src.lifz, 
                    src.lifz_kw, 
                    src.ltdd_1, 
                    src.ltdd_2, 
                    src.ltdd_3, 
                    src.ltdz, 
                    src.ltdz_kw, 
                    src.ratd, 
                    src.rate_1, 
                    src.rate_2, 
                    src.rate_3, 
                    src.ratf_1, 
                    src.ratf_2, 
                    src.ratf_3, 
                    src.reas, 
                    src.reas_ref_compnr, 
                    src.revl, 
                    src.revl_kw, 
                    src.rtyp, 
                    src.s179_1, 
                    src.s179_2, 
                    src.s179_3, 
                    src.s17z, 
                    src.s17z_kw, 
                    src.salv_1, 
                    src.salv_2, 
                    src.salv_3, 
                    src.salz, 
                    src.salz_kw, 
                    src.sequencenumber, 
                    src.timestamp, 
                    src.tkey, 
                    src.tkey_ref_compnr, 
                    src.traf, 
                    src.traf_kw, 
                    src.user, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TFFAM820_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.acmc_1, 
            strm.acmc_2, 
            strm.acmc_3, 
            strm.acmz, 
            strm.acmz_kw, 
            strm.apam_1, 
            strm.apam_2, 
            strm.apam_3, 
            strm.apaz, 
            strm.apaz_kw, 
            strm.capi_1, 
            strm.capi_2, 
            strm.capi_3, 
            strm.capz, 
            strm.capz_kw, 
            strm.compnr, 
            strm.cost_1, 
            strm.cost_2, 
            strm.cost_3, 
            strm.cosz, 
            strm.cosz_kw, 
            strm.curr, 
            strm.deleted, 
            strm.itca_1, 
            strm.itca_2, 
            strm.itca_3, 
            strm.itcz, 
            strm.itcz_kw, 
            strm.life, 
            strm.lifz, 
            strm.lifz_kw, 
            strm.ltdd_1, 
            strm.ltdd_2, 
            strm.ltdd_3, 
            strm.ltdz, 
            strm.ltdz_kw, 
            strm.ratd, 
            strm.rate_1, 
            strm.rate_2, 
            strm.rate_3, 
            strm.ratf_1, 
            strm.ratf_2, 
            strm.ratf_3, 
            strm.reas, 
            strm.reas_ref_compnr, 
            strm.revl, 
            strm.revl_kw, 
            strm.rtyp, 
            strm.s179_1, 
            strm.s179_2, 
            strm.s179_3, 
            strm.s17z, 
            strm.s17z_kw, 
            strm.salv_1, 
            strm.salv_2, 
            strm.salv_3, 
            strm.salz, 
            strm.salz_kw, 
            strm.sequencenumber, 
            strm.timestamp, 
            strm.tkey, 
            strm.tkey_ref_compnr, 
            strm.traf, 
            strm.traf_kw, 
            strm.user, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.tkey ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFFAM820 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.tkey=src.tkey) OR (target.tkey IS NULL AND src.tkey IS NULL)) 
                when matched then update set
                    target.acmc_1=src.acmc_1, 
                    target.acmc_2=src.acmc_2, 
                    target.acmc_3=src.acmc_3, 
                    target.acmz=src.acmz, 
                    target.acmz_kw=src.acmz_kw, 
                    target.apam_1=src.apam_1, 
                    target.apam_2=src.apam_2, 
                    target.apam_3=src.apam_3, 
                    target.apaz=src.apaz, 
                    target.apaz_kw=src.apaz_kw, 
                    target.capi_1=src.capi_1, 
                    target.capi_2=src.capi_2, 
                    target.capi_3=src.capi_3, 
                    target.capz=src.capz, 
                    target.capz_kw=src.capz_kw, 
                    target.compnr=src.compnr, 
                    target.cost_1=src.cost_1, 
                    target.cost_2=src.cost_2, 
                    target.cost_3=src.cost_3, 
                    target.cosz=src.cosz, 
                    target.cosz_kw=src.cosz_kw, 
                    target.curr=src.curr, 
                    target.deleted=src.deleted, 
                    target.itca_1=src.itca_1, 
                    target.itca_2=src.itca_2, 
                    target.itca_3=src.itca_3, 
                    target.itcz=src.itcz, 
                    target.itcz_kw=src.itcz_kw, 
                    target.life=src.life, 
                    target.lifz=src.lifz, 
                    target.lifz_kw=src.lifz_kw, 
                    target.ltdd_1=src.ltdd_1, 
                    target.ltdd_2=src.ltdd_2, 
                    target.ltdd_3=src.ltdd_3, 
                    target.ltdz=src.ltdz, 
                    target.ltdz_kw=src.ltdz_kw, 
                    target.ratd=src.ratd, 
                    target.rate_1=src.rate_1, 
                    target.rate_2=src.rate_2, 
                    target.rate_3=src.rate_3, 
                    target.ratf_1=src.ratf_1, 
                    target.ratf_2=src.ratf_2, 
                    target.ratf_3=src.ratf_3, 
                    target.reas=src.reas, 
                    target.reas_ref_compnr=src.reas_ref_compnr, 
                    target.revl=src.revl, 
                    target.revl_kw=src.revl_kw, 
                    target.rtyp=src.rtyp, 
                    target.s179_1=src.s179_1, 
                    target.s179_2=src.s179_2, 
                    target.s179_3=src.s179_3, 
                    target.s17z=src.s17z, 
                    target.s17z_kw=src.s17z_kw, 
                    target.salv_1=src.salv_1, 
                    target.salv_2=src.salv_2, 
                    target.salv_3=src.salv_3, 
                    target.salz=src.salz, 
                    target.salz_kw=src.salz_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.timestamp=src.timestamp, 
                    target.tkey=src.tkey, 
                    target.tkey_ref_compnr=src.tkey_ref_compnr, 
                    target.traf=src.traf, 
                    target.traf_kw=src.traf_kw, 
                    target.user=src.user, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( acmc_1, acmc_2, acmc_3, acmz, acmz_kw, apam_1, apam_2, apam_3, apaz, apaz_kw, capi_1, capi_2, capi_3, capz, capz_kw, compnr, cost_1, cost_2, cost_3, cosz, cosz_kw, curr, deleted, itca_1, itca_2, itca_3, itcz, itcz_kw, life, lifz, lifz_kw, ltdd_1, ltdd_2, ltdd_3, ltdz, ltdz_kw, ratd, rate_1, rate_2, rate_3, ratf_1, ratf_2, ratf_3, reas, reas_ref_compnr, revl, revl_kw, rtyp, s179_1, s179_2, s179_3, s17z, s17z_kw, salv_1, salv_2, salv_3, salz, salz_kw, sequencenumber, timestamp, tkey, tkey_ref_compnr, traf, traf_kw, user, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.acmc_1, 
                    src.acmc_2, 
                    src.acmc_3, 
                    src.acmz, 
                    src.acmz_kw, 
                    src.apam_1, 
                    src.apam_2, 
                    src.apam_3, 
                    src.apaz, 
                    src.apaz_kw, 
                    src.capi_1, 
                    src.capi_2, 
                    src.capi_3, 
                    src.capz, 
                    src.capz_kw, 
                    src.compnr, 
                    src.cost_1, 
                    src.cost_2, 
                    src.cost_3, 
                    src.cosz, 
                    src.cosz_kw, 
                    src.curr, 
                    src.deleted, 
                    src.itca_1, 
                    src.itca_2, 
                    src.itca_3, 
                    src.itcz, 
                    src.itcz_kw, 
                    src.life, 
                    src.lifz, 
                    src.lifz_kw, 
                    src.ltdd_1, 
                    src.ltdd_2, 
                    src.ltdd_3, 
                    src.ltdz, 
                    src.ltdz_kw, 
                    src.ratd, 
                    src.rate_1, 
                    src.rate_2, 
                    src.rate_3, 
                    src.ratf_1, 
                    src.ratf_2, 
                    src.ratf_3, 
                    src.reas, 
                    src.reas_ref_compnr, 
                    src.revl, 
                    src.revl_kw, 
                    src.rtyp, 
                    src.s179_1, 
                    src.s179_2, 
                    src.s179_3, 
                    src.s17z, 
                    src.s17z_kw, 
                    src.salv_1, 
                    src.salv_2, 
                    src.salv_3, 
                    src.salz, 
                    src.salz_kw, 
                    src.sequencenumber, 
                    src.timestamp, 
                    src.tkey, 
                    src.tkey_ref_compnr, 
                    src.traf, 
                    src.traf_kw, 
                    src.user, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;