create or replace procedure DATAHUB_INTEGRATION.SP_LN_TSCTM132()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TSCTM132_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TSCTM132 as target using (SELECT * FROM (SELECT 
            strm.alco_1, 
            strm.alco_2, 
            strm.alco_3, 
            strm.alco_cntc, 
            strm.alco_dwhc, 
            strm.alco_refc, 
            strm.alhr, 
            strm.alhr_butm, 
            strm.alsa, 
            strm.alsa_dwhc, 
            strm.alsa_homc, 
            strm.alsa_refc, 
            strm.alsa_rpc1, 
            strm.alsa_rpc2, 
            strm.amnt, 
            strm.amnt_dwhc, 
            strm.amnt_homc, 
            strm.amnt_refc, 
            strm.amnt_rpc1, 
            strm.amnt_rpc2, 
            strm.camt_1, 
            strm.camt_2, 
            strm.camt_3, 
            strm.camt_cntc, 
            strm.camt_dwhc, 
            strm.camt_refc, 
            strm.ccmp, 
            strm.ccmp_ref_compnr, 
            strm.cctp, 
            strm.cctp_ref_compnr, 
            strm.cfln, 
            strm.chlt, 
            strm.chlt_ref_compnr, 
            strm.clrt, 
            strm.clrt_ref_compnr, 
            strm.compnr, 
            strm.cotp, 
            strm.cotp_kw, 
            strm.cseq, 
            strm.ctsk, 
            strm.ctsk_ref_compnr, 
            strm.deleted, 
            strm.dspc, 
            strm.dspc_kw, 
            strm.eahr, 
            strm.eahr_butm, 
            strm.ealc_1, 
            strm.ealc_2, 
            strm.ealc_3, 
            strm.ealc_cntc, 
            strm.ealc_dwhc, 
            strm.ealc_refc, 
            strm.eals, 
            strm.eals_dwhc, 
            strm.eals_homc, 
            strm.eals_refc, 
            strm.eals_rpc1, 
            strm.eals_rpc2, 
            strm.nrbt, 
            strm.nrhr, 
            strm.nrhr_butm, 
            strm.sequencenumber, 
            strm.spco_1, 
            strm.spco_2, 
            strm.spco_3, 
            strm.spco_cntc, 
            strm.spco_dwhc, 
            strm.spco_refc, 
            strm.sphr, 
            strm.spsa, 
            strm.spsa_dwhc, 
            strm.spsa_homc, 
            strm.spsa_refc, 
            strm.spsa_rpc1, 
            strm.spsa_rpc2, 
            strm.term, 
            strm.term_cfln_cctp_cotp_nrbt_ref_compnr, 
            strm.term_cfln_ref_compnr, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.username, 
            strm.wrac_1, 
            strm.wrac_2, 
            strm.wrac_3, 
            strm.wras, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.term,
            strm.cfln,
            strm.cctp,
            strm.cotp,
            strm.nrbt,
            strm.cseq ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TSCTM132 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.term=src.term) OR (target.term IS NULL AND src.term IS NULL)) AND
            ((target.cfln=src.cfln) OR (target.cfln IS NULL AND src.cfln IS NULL)) AND
            ((target.cctp=src.cctp) OR (target.cctp IS NULL AND src.cctp IS NULL)) AND
            ((target.cotp=src.cotp) OR (target.cotp IS NULL AND src.cotp IS NULL)) AND
            ((target.nrbt=src.nrbt) OR (target.nrbt IS NULL AND src.nrbt IS NULL)) AND
            ((target.cseq=src.cseq) OR (target.cseq IS NULL AND src.cseq IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.alco_1=src.alco_1, 
                    target.alco_2=src.alco_2, 
                    target.alco_3=src.alco_3, 
                    target.alco_cntc=src.alco_cntc, 
                    target.alco_dwhc=src.alco_dwhc, 
                    target.alco_refc=src.alco_refc, 
                    target.alhr=src.alhr, 
                    target.alhr_butm=src.alhr_butm, 
                    target.alsa=src.alsa, 
                    target.alsa_dwhc=src.alsa_dwhc, 
                    target.alsa_homc=src.alsa_homc, 
                    target.alsa_refc=src.alsa_refc, 
                    target.alsa_rpc1=src.alsa_rpc1, 
                    target.alsa_rpc2=src.alsa_rpc2, 
                    target.amnt=src.amnt, 
                    target.amnt_dwhc=src.amnt_dwhc, 
                    target.amnt_homc=src.amnt_homc, 
                    target.amnt_refc=src.amnt_refc, 
                    target.amnt_rpc1=src.amnt_rpc1, 
                    target.amnt_rpc2=src.amnt_rpc2, 
                    target.camt_1=src.camt_1, 
                    target.camt_2=src.camt_2, 
                    target.camt_3=src.camt_3, 
                    target.camt_cntc=src.camt_cntc, 
                    target.camt_dwhc=src.camt_dwhc, 
                    target.camt_refc=src.camt_refc, 
                    target.ccmp=src.ccmp, 
                    target.ccmp_ref_compnr=src.ccmp_ref_compnr, 
                    target.cctp=src.cctp, 
                    target.cctp_ref_compnr=src.cctp_ref_compnr, 
                    target.cfln=src.cfln, 
                    target.chlt=src.chlt, 
                    target.chlt_ref_compnr=src.chlt_ref_compnr, 
                    target.clrt=src.clrt, 
                    target.clrt_ref_compnr=src.clrt_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cotp=src.cotp, 
                    target.cotp_kw=src.cotp_kw, 
                    target.cseq=src.cseq, 
                    target.ctsk=src.ctsk, 
                    target.ctsk_ref_compnr=src.ctsk_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dspc=src.dspc, 
                    target.dspc_kw=src.dspc_kw, 
                    target.eahr=src.eahr, 
                    target.eahr_butm=src.eahr_butm, 
                    target.ealc_1=src.ealc_1, 
                    target.ealc_2=src.ealc_2, 
                    target.ealc_3=src.ealc_3, 
                    target.ealc_cntc=src.ealc_cntc, 
                    target.ealc_dwhc=src.ealc_dwhc, 
                    target.ealc_refc=src.ealc_refc, 
                    target.eals=src.eals, 
                    target.eals_dwhc=src.eals_dwhc, 
                    target.eals_homc=src.eals_homc, 
                    target.eals_refc=src.eals_refc, 
                    target.eals_rpc1=src.eals_rpc1, 
                    target.eals_rpc2=src.eals_rpc2, 
                    target.nrbt=src.nrbt, 
                    target.nrhr=src.nrhr, 
                    target.nrhr_butm=src.nrhr_butm, 
                    target.sequencenumber=src.sequencenumber, 
                    target.spco_1=src.spco_1, 
                    target.spco_2=src.spco_2, 
                    target.spco_3=src.spco_3, 
                    target.spco_cntc=src.spco_cntc, 
                    target.spco_dwhc=src.spco_dwhc, 
                    target.spco_refc=src.spco_refc, 
                    target.sphr=src.sphr, 
                    target.spsa=src.spsa, 
                    target.spsa_dwhc=src.spsa_dwhc, 
                    target.spsa_homc=src.spsa_homc, 
                    target.spsa_refc=src.spsa_refc, 
                    target.spsa_rpc1=src.spsa_rpc1, 
                    target.spsa_rpc2=src.spsa_rpc2, 
                    target.term=src.term, 
                    target.term_cfln_cctp_cotp_nrbt_ref_compnr=src.term_cfln_cctp_cotp_nrbt_ref_compnr, 
                    target.term_cfln_ref_compnr=src.term_cfln_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.username=src.username, 
                    target.wrac_1=src.wrac_1, 
                    target.wrac_2=src.wrac_2, 
                    target.wrac_3=src.wrac_3, 
                    target.wras=src.wras, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    alco_1, 
                    alco_2, 
                    alco_3, 
                    alco_cntc, 
                    alco_dwhc, 
                    alco_refc, 
                    alhr, 
                    alhr_butm, 
                    alsa, 
                    alsa_dwhc, 
                    alsa_homc, 
                    alsa_refc, 
                    alsa_rpc1, 
                    alsa_rpc2, 
                    amnt, 
                    amnt_dwhc, 
                    amnt_homc, 
                    amnt_refc, 
                    amnt_rpc1, 
                    amnt_rpc2, 
                    camt_1, 
                    camt_2, 
                    camt_3, 
                    camt_cntc, 
                    camt_dwhc, 
                    camt_refc, 
                    ccmp, 
                    ccmp_ref_compnr, 
                    cctp, 
                    cctp_ref_compnr, 
                    cfln, 
                    chlt, 
                    chlt_ref_compnr, 
                    clrt, 
                    clrt_ref_compnr, 
                    compnr, 
                    cotp, 
                    cotp_kw, 
                    cseq, 
                    ctsk, 
                    ctsk_ref_compnr, 
                    deleted, 
                    dspc, 
                    dspc_kw, 
                    eahr, 
                    eahr_butm, 
                    ealc_1, 
                    ealc_2, 
                    ealc_3, 
                    ealc_cntc, 
                    ealc_dwhc, 
                    ealc_refc, 
                    eals, 
                    eals_dwhc, 
                    eals_homc, 
                    eals_refc, 
                    eals_rpc1, 
                    eals_rpc2, 
                    nrbt, 
                    nrhr, 
                    nrhr_butm, 
                    sequencenumber, 
                    spco_1, 
                    spco_2, 
                    spco_3, 
                    spco_cntc, 
                    spco_dwhc, 
                    spco_refc, 
                    sphr, 
                    spsa, 
                    spsa_dwhc, 
                    spsa_homc, 
                    spsa_refc, 
                    spsa_rpc1, 
                    spsa_rpc2, 
                    term, 
                    term_cfln_cctp_cotp_nrbt_ref_compnr, 
                    term_cfln_ref_compnr, 
                    timestamp, 
                    txta, 
                    txta_ref_compnr, 
                    username, 
                    wrac_1, 
                    wrac_2, 
                    wrac_3, 
                    wras, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.alco_1, 
                    src.alco_2, 
                    src.alco_3, 
                    src.alco_cntc, 
                    src.alco_dwhc, 
                    src.alco_refc, 
                    src.alhr, 
                    src.alhr_butm, 
                    src.alsa, 
                    src.alsa_dwhc, 
                    src.alsa_homc, 
                    src.alsa_refc, 
                    src.alsa_rpc1, 
                    src.alsa_rpc2, 
                    src.amnt, 
                    src.amnt_dwhc, 
                    src.amnt_homc, 
                    src.amnt_refc, 
                    src.amnt_rpc1, 
                    src.amnt_rpc2, 
                    src.camt_1, 
                    src.camt_2, 
                    src.camt_3, 
                    src.camt_cntc, 
                    src.camt_dwhc, 
                    src.camt_refc, 
                    src.ccmp, 
                    src.ccmp_ref_compnr, 
                    src.cctp, 
                    src.cctp_ref_compnr, 
                    src.cfln, 
                    src.chlt, 
                    src.chlt_ref_compnr, 
                    src.clrt, 
                    src.clrt_ref_compnr, 
                    src.compnr, 
                    src.cotp, 
                    src.cotp_kw, 
                    src.cseq, 
                    src.ctsk, 
                    src.ctsk_ref_compnr, 
                    src.deleted, 
                    src.dspc, 
                    src.dspc_kw, 
                    src.eahr, 
                    src.eahr_butm, 
                    src.ealc_1, 
                    src.ealc_2, 
                    src.ealc_3, 
                    src.ealc_cntc, 
                    src.ealc_dwhc, 
                    src.ealc_refc, 
                    src.eals, 
                    src.eals_dwhc, 
                    src.eals_homc, 
                    src.eals_refc, 
                    src.eals_rpc1, 
                    src.eals_rpc2, 
                    src.nrbt, 
                    src.nrhr, 
                    src.nrhr_butm, 
                    src.sequencenumber, 
                    src.spco_1, 
                    src.spco_2, 
                    src.spco_3, 
                    src.spco_cntc, 
                    src.spco_dwhc, 
                    src.spco_refc, 
                    src.sphr, 
                    src.spsa, 
                    src.spsa_dwhc, 
                    src.spsa_homc, 
                    src.spsa_refc, 
                    src.spsa_rpc1, 
                    src.spsa_rpc2, 
                    src.term, 
                    src.term_cfln_cctp_cotp_nrbt_ref_compnr, 
                    src.term_cfln_ref_compnr, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.username, 
                    src.wrac_1, 
                    src.wrac_2, 
                    src.wrac_3, 
                    src.wras,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TSCTM132_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.alco_1, 
            strm.alco_2, 
            strm.alco_3, 
            strm.alco_cntc, 
            strm.alco_dwhc, 
            strm.alco_refc, 
            strm.alhr, 
            strm.alhr_butm, 
            strm.alsa, 
            strm.alsa_dwhc, 
            strm.alsa_homc, 
            strm.alsa_refc, 
            strm.alsa_rpc1, 
            strm.alsa_rpc2, 
            strm.amnt, 
            strm.amnt_dwhc, 
            strm.amnt_homc, 
            strm.amnt_refc, 
            strm.amnt_rpc1, 
            strm.amnt_rpc2, 
            strm.camt_1, 
            strm.camt_2, 
            strm.camt_3, 
            strm.camt_cntc, 
            strm.camt_dwhc, 
            strm.camt_refc, 
            strm.ccmp, 
            strm.ccmp_ref_compnr, 
            strm.cctp, 
            strm.cctp_ref_compnr, 
            strm.cfln, 
            strm.chlt, 
            strm.chlt_ref_compnr, 
            strm.clrt, 
            strm.clrt_ref_compnr, 
            strm.compnr, 
            strm.cotp, 
            strm.cotp_kw, 
            strm.cseq, 
            strm.ctsk, 
            strm.ctsk_ref_compnr, 
            strm.deleted, 
            strm.dspc, 
            strm.dspc_kw, 
            strm.eahr, 
            strm.eahr_butm, 
            strm.ealc_1, 
            strm.ealc_2, 
            strm.ealc_3, 
            strm.ealc_cntc, 
            strm.ealc_dwhc, 
            strm.ealc_refc, 
            strm.eals, 
            strm.eals_dwhc, 
            strm.eals_homc, 
            strm.eals_refc, 
            strm.eals_rpc1, 
            strm.eals_rpc2, 
            strm.nrbt, 
            strm.nrhr, 
            strm.nrhr_butm, 
            strm.sequencenumber, 
            strm.spco_1, 
            strm.spco_2, 
            strm.spco_3, 
            strm.spco_cntc, 
            strm.spco_dwhc, 
            strm.spco_refc, 
            strm.sphr, 
            strm.spsa, 
            strm.spsa_dwhc, 
            strm.spsa_homc, 
            strm.spsa_refc, 
            strm.spsa_rpc1, 
            strm.spsa_rpc2, 
            strm.term, 
            strm.term_cfln_cctp_cotp_nrbt_ref_compnr, 
            strm.term_cfln_ref_compnr, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.username, 
            strm.wrac_1, 
            strm.wrac_2, 
            strm.wrac_3, 
            strm.wras, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.term,
            strm.cfln,
            strm.cctp,
            strm.cotp,
            strm.nrbt,
            strm.cseq ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TSCTM132 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.term=src.term) OR (target.term IS NULL AND src.term IS NULL)) AND
            ((target.cfln=src.cfln) OR (target.cfln IS NULL AND src.cfln IS NULL)) AND
            ((target.cctp=src.cctp) OR (target.cctp IS NULL AND src.cctp IS NULL)) AND
            ((target.cotp=src.cotp) OR (target.cotp IS NULL AND src.cotp IS NULL)) AND
            ((target.nrbt=src.nrbt) OR (target.nrbt IS NULL AND src.nrbt IS NULL)) AND
            ((target.cseq=src.cseq) OR (target.cseq IS NULL AND src.cseq IS NULL)) 
                when matched then update set
                    target.alco_1=src.alco_1, 
                    target.alco_2=src.alco_2, 
                    target.alco_3=src.alco_3, 
                    target.alco_cntc=src.alco_cntc, 
                    target.alco_dwhc=src.alco_dwhc, 
                    target.alco_refc=src.alco_refc, 
                    target.alhr=src.alhr, 
                    target.alhr_butm=src.alhr_butm, 
                    target.alsa=src.alsa, 
                    target.alsa_dwhc=src.alsa_dwhc, 
                    target.alsa_homc=src.alsa_homc, 
                    target.alsa_refc=src.alsa_refc, 
                    target.alsa_rpc1=src.alsa_rpc1, 
                    target.alsa_rpc2=src.alsa_rpc2, 
                    target.amnt=src.amnt, 
                    target.amnt_dwhc=src.amnt_dwhc, 
                    target.amnt_homc=src.amnt_homc, 
                    target.amnt_refc=src.amnt_refc, 
                    target.amnt_rpc1=src.amnt_rpc1, 
                    target.amnt_rpc2=src.amnt_rpc2, 
                    target.camt_1=src.camt_1, 
                    target.camt_2=src.camt_2, 
                    target.camt_3=src.camt_3, 
                    target.camt_cntc=src.camt_cntc, 
                    target.camt_dwhc=src.camt_dwhc, 
                    target.camt_refc=src.camt_refc, 
                    target.ccmp=src.ccmp, 
                    target.ccmp_ref_compnr=src.ccmp_ref_compnr, 
                    target.cctp=src.cctp, 
                    target.cctp_ref_compnr=src.cctp_ref_compnr, 
                    target.cfln=src.cfln, 
                    target.chlt=src.chlt, 
                    target.chlt_ref_compnr=src.chlt_ref_compnr, 
                    target.clrt=src.clrt, 
                    target.clrt_ref_compnr=src.clrt_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cotp=src.cotp, 
                    target.cotp_kw=src.cotp_kw, 
                    target.cseq=src.cseq, 
                    target.ctsk=src.ctsk, 
                    target.ctsk_ref_compnr=src.ctsk_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.dspc=src.dspc, 
                    target.dspc_kw=src.dspc_kw, 
                    target.eahr=src.eahr, 
                    target.eahr_butm=src.eahr_butm, 
                    target.ealc_1=src.ealc_1, 
                    target.ealc_2=src.ealc_2, 
                    target.ealc_3=src.ealc_3, 
                    target.ealc_cntc=src.ealc_cntc, 
                    target.ealc_dwhc=src.ealc_dwhc, 
                    target.ealc_refc=src.ealc_refc, 
                    target.eals=src.eals, 
                    target.eals_dwhc=src.eals_dwhc, 
                    target.eals_homc=src.eals_homc, 
                    target.eals_refc=src.eals_refc, 
                    target.eals_rpc1=src.eals_rpc1, 
                    target.eals_rpc2=src.eals_rpc2, 
                    target.nrbt=src.nrbt, 
                    target.nrhr=src.nrhr, 
                    target.nrhr_butm=src.nrhr_butm, 
                    target.sequencenumber=src.sequencenumber, 
                    target.spco_1=src.spco_1, 
                    target.spco_2=src.spco_2, 
                    target.spco_3=src.spco_3, 
                    target.spco_cntc=src.spco_cntc, 
                    target.spco_dwhc=src.spco_dwhc, 
                    target.spco_refc=src.spco_refc, 
                    target.sphr=src.sphr, 
                    target.spsa=src.spsa, 
                    target.spsa_dwhc=src.spsa_dwhc, 
                    target.spsa_homc=src.spsa_homc, 
                    target.spsa_refc=src.spsa_refc, 
                    target.spsa_rpc1=src.spsa_rpc1, 
                    target.spsa_rpc2=src.spsa_rpc2, 
                    target.term=src.term, 
                    target.term_cfln_cctp_cotp_nrbt_ref_compnr=src.term_cfln_cctp_cotp_nrbt_ref_compnr, 
                    target.term_cfln_ref_compnr=src.term_cfln_ref_compnr, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.username=src.username, 
                    target.wrac_1=src.wrac_1, 
                    target.wrac_2=src.wrac_2, 
                    target.wrac_3=src.wrac_3, 
                    target.wras=src.wras, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( alco_1, alco_2, alco_3, alco_cntc, alco_dwhc, alco_refc, alhr, alhr_butm, alsa, alsa_dwhc, alsa_homc, alsa_refc, alsa_rpc1, alsa_rpc2, amnt, amnt_dwhc, amnt_homc, amnt_refc, amnt_rpc1, amnt_rpc2, camt_1, camt_2, camt_3, camt_cntc, camt_dwhc, camt_refc, ccmp, ccmp_ref_compnr, cctp, cctp_ref_compnr, cfln, chlt, chlt_ref_compnr, clrt, clrt_ref_compnr, compnr, cotp, cotp_kw, cseq, ctsk, ctsk_ref_compnr, deleted, dspc, dspc_kw, eahr, eahr_butm, ealc_1, ealc_2, ealc_3, ealc_cntc, ealc_dwhc, ealc_refc, eals, eals_dwhc, eals_homc, eals_refc, eals_rpc1, eals_rpc2, nrbt, nrhr, nrhr_butm, sequencenumber, spco_1, spco_2, spco_3, spco_cntc, spco_dwhc, spco_refc, sphr, spsa, spsa_dwhc, spsa_homc, spsa_refc, spsa_rpc1, spsa_rpc2, term, term_cfln_cctp_cotp_nrbt_ref_compnr, term_cfln_ref_compnr, timestamp, txta, txta_ref_compnr, username, wrac_1, wrac_2, wrac_3, wras, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.alco_1, 
                    src.alco_2, 
                    src.alco_3, 
                    src.alco_cntc, 
                    src.alco_dwhc, 
                    src.alco_refc, 
                    src.alhr, 
                    src.alhr_butm, 
                    src.alsa, 
                    src.alsa_dwhc, 
                    src.alsa_homc, 
                    src.alsa_refc, 
                    src.alsa_rpc1, 
                    src.alsa_rpc2, 
                    src.amnt, 
                    src.amnt_dwhc, 
                    src.amnt_homc, 
                    src.amnt_refc, 
                    src.amnt_rpc1, 
                    src.amnt_rpc2, 
                    src.camt_1, 
                    src.camt_2, 
                    src.camt_3, 
                    src.camt_cntc, 
                    src.camt_dwhc, 
                    src.camt_refc, 
                    src.ccmp, 
                    src.ccmp_ref_compnr, 
                    src.cctp, 
                    src.cctp_ref_compnr, 
                    src.cfln, 
                    src.chlt, 
                    src.chlt_ref_compnr, 
                    src.clrt, 
                    src.clrt_ref_compnr, 
                    src.compnr, 
                    src.cotp, 
                    src.cotp_kw, 
                    src.cseq, 
                    src.ctsk, 
                    src.ctsk_ref_compnr, 
                    src.deleted, 
                    src.dspc, 
                    src.dspc_kw, 
                    src.eahr, 
                    src.eahr_butm, 
                    src.ealc_1, 
                    src.ealc_2, 
                    src.ealc_3, 
                    src.ealc_cntc, 
                    src.ealc_dwhc, 
                    src.ealc_refc, 
                    src.eals, 
                    src.eals_dwhc, 
                    src.eals_homc, 
                    src.eals_refc, 
                    src.eals_rpc1, 
                    src.eals_rpc2, 
                    src.nrbt, 
                    src.nrhr, 
                    src.nrhr_butm, 
                    src.sequencenumber, 
                    src.spco_1, 
                    src.spco_2, 
                    src.spco_3, 
                    src.spco_cntc, 
                    src.spco_dwhc, 
                    src.spco_refc, 
                    src.sphr, 
                    src.spsa, 
                    src.spsa_dwhc, 
                    src.spsa_homc, 
                    src.spsa_refc, 
                    src.spsa_rpc1, 
                    src.spsa_rpc2, 
                    src.term, 
                    src.term_cfln_cctp_cotp_nrbt_ref_compnr, 
                    src.term_cfln_ref_compnr, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.username, 
                    src.wrac_1, 
                    src.wrac_2, 
                    src.wrac_3, 
                    src.wras,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;