create or replace procedure DATAHUB_INTEGRATION.SP_LN_TFGLD495()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TFGLD495_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TFGLD495 as target using (SELECT * FROM (SELECT 
            strm.acce, 
            strm.acce_kw, 
            strm.accf, 
            strm.accf_kw, 
            strm.amnt, 
            strm.amth_1, 
            strm.amth_2, 
            strm.amth_3, 
            strm.aobl, 
            strm.aobl_kw, 
            strm.arat_1, 
            strm.arat_2, 
            strm.arat_3, 
            strm.blrf, 
            strm.btno, 
            strm.buid, 
            strm.ccur, 
            strm.compnr, 
            strm.crdt, 
            strm.cuni, 
            strm.dbcr, 
            strm.dbcr_kw, 
            strm.dcdt, 
            strm.deleted, 
            strm.dim1, 
            strm.dim2, 
            strm.dim3, 
            strm.dim4, 
            strm.dim5, 
            strm.dim6, 
            strm.dim7, 
            strm.dim8, 
            strm.dim9, 
            strm.dm10, 
            strm.dm11, 
            strm.dm12, 
            strm.docn, 
            strm.fcom, 
            strm.fprd, 
            strm.fyer, 
            strm.guid, 
            strm.idtc, 
            strm.inad, 
            strm.inad_kw, 
            strm.inic, 
            strm.inic_kw, 
            strm.ktrn, 
            strm.ktrn_kw, 
            strm.lcit, 
            strm.leac, 
            strm.link, 
            strm.lino, 
            strm.nuni, 
            strm.obre, 
            strm.ocmp, 
            strm.odbc, 
            strm.odbc_kw, 
            strm.ogui, 
            strm.podt, 
            strm.proj, 
            strm.rbid, 
            strm.rbon, 
            strm.rce1, 
            strm.rce2, 
            strm.rce3, 
            strm.rce4, 
            strm.rce5, 
            strm.reco, 
            strm.reco_kw, 
            strm.recs, 
            strm.rev1, 
            strm.rev2, 
            strm.rev3, 
            strm.rev4, 
            strm.rev5, 
            strm.rpon, 
            strm.sequencenumber, 
            strm.serl, 
            strm.srno, 
            strm.tdte, 
            strm.timestamp, 
            strm.trdt, 
            strm.ttyp, 
            strm.urat_1, 
            strm.urat_2, 
            strm.urat_3, 
            strm.username, 
            strm.year, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.guid,
            strm.dbcr ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFGLD495 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.guid=src.guid) OR (target.guid IS NULL AND src.guid IS NULL)) AND
            ((target.dbcr=src.dbcr) OR (target.dbcr IS NULL AND src.dbcr IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.acce=src.acce, 
                    target.acce_kw=src.acce_kw, 
                    target.accf=src.accf, 
                    target.accf_kw=src.accf_kw, 
                    target.amnt=src.amnt, 
                    target.amth_1=src.amth_1, 
                    target.amth_2=src.amth_2, 
                    target.amth_3=src.amth_3, 
                    target.aobl=src.aobl, 
                    target.aobl_kw=src.aobl_kw, 
                    target.arat_1=src.arat_1, 
                    target.arat_2=src.arat_2, 
                    target.arat_3=src.arat_3, 
                    target.blrf=src.blrf, 
                    target.btno=src.btno, 
                    target.buid=src.buid, 
                    target.ccur=src.ccur, 
                    target.compnr=src.compnr, 
                    target.crdt=src.crdt, 
                    target.cuni=src.cuni, 
                    target.dbcr=src.dbcr, 
                    target.dbcr_kw=src.dbcr_kw, 
                    target.dcdt=src.dcdt, 
                    target.deleted=src.deleted, 
                    target.dim1=src.dim1, 
                    target.dim2=src.dim2, 
                    target.dim3=src.dim3, 
                    target.dim4=src.dim4, 
                    target.dim5=src.dim5, 
                    target.dim6=src.dim6, 
                    target.dim7=src.dim7, 
                    target.dim8=src.dim8, 
                    target.dim9=src.dim9, 
                    target.dm10=src.dm10, 
                    target.dm11=src.dm11, 
                    target.dm12=src.dm12, 
                    target.docn=src.docn, 
                    target.fcom=src.fcom, 
                    target.fprd=src.fprd, 
                    target.fyer=src.fyer, 
                    target.guid=src.guid, 
                    target.idtc=src.idtc, 
                    target.inad=src.inad, 
                    target.inad_kw=src.inad_kw, 
                    target.inic=src.inic, 
                    target.inic_kw=src.inic_kw, 
                    target.ktrn=src.ktrn, 
                    target.ktrn_kw=src.ktrn_kw, 
                    target.lcit=src.lcit, 
                    target.leac=src.leac, 
                    target.link=src.link, 
                    target.lino=src.lino, 
                    target.nuni=src.nuni, 
                    target.obre=src.obre, 
                    target.ocmp=src.ocmp, 
                    target.odbc=src.odbc, 
                    target.odbc_kw=src.odbc_kw, 
                    target.ogui=src.ogui, 
                    target.podt=src.podt, 
                    target.proj=src.proj, 
                    target.rbid=src.rbid, 
                    target.rbon=src.rbon, 
                    target.rce1=src.rce1, 
                    target.rce2=src.rce2, 
                    target.rce3=src.rce3, 
                    target.rce4=src.rce4, 
                    target.rce5=src.rce5, 
                    target.reco=src.reco, 
                    target.reco_kw=src.reco_kw, 
                    target.recs=src.recs, 
                    target.rev1=src.rev1, 
                    target.rev2=src.rev2, 
                    target.rev3=src.rev3, 
                    target.rev4=src.rev4, 
                    target.rev5=src.rev5, 
                    target.rpon=src.rpon, 
                    target.sequencenumber=src.sequencenumber, 
                    target.serl=src.serl, 
                    target.srno=src.srno, 
                    target.tdte=src.tdte, 
                    target.timestamp=src.timestamp, 
                    target.trdt=src.trdt, 
                    target.ttyp=src.ttyp, 
                    target.urat_1=src.urat_1, 
                    target.urat_2=src.urat_2, 
                    target.urat_3=src.urat_3, 
                    target.username=src.username, 
                    target.year=src.year, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    acce, 
                    acce_kw, 
                    accf, 
                    accf_kw, 
                    amnt, 
                    amth_1, 
                    amth_2, 
                    amth_3, 
                    aobl, 
                    aobl_kw, 
                    arat_1, 
                    arat_2, 
                    arat_3, 
                    blrf, 
                    btno, 
                    buid, 
                    ccur, 
                    compnr, 
                    crdt, 
                    cuni, 
                    dbcr, 
                    dbcr_kw, 
                    dcdt, 
                    deleted, 
                    dim1, 
                    dim2, 
                    dim3, 
                    dim4, 
                    dim5, 
                    dim6, 
                    dim7, 
                    dim8, 
                    dim9, 
                    dm10, 
                    dm11, 
                    dm12, 
                    docn, 
                    fcom, 
                    fprd, 
                    fyer, 
                    guid, 
                    idtc, 
                    inad, 
                    inad_kw, 
                    inic, 
                    inic_kw, 
                    ktrn, 
                    ktrn_kw, 
                    lcit, 
                    leac, 
                    link, 
                    lino, 
                    nuni, 
                    obre, 
                    ocmp, 
                    odbc, 
                    odbc_kw, 
                    ogui, 
                    podt, 
                    proj, 
                    rbid, 
                    rbon, 
                    rce1, 
                    rce2, 
                    rce3, 
                    rce4, 
                    rce5, 
                    reco, 
                    reco_kw, 
                    recs, 
                    rev1, 
                    rev2, 
                    rev3, 
                    rev4, 
                    rev5, 
                    rpon, 
                    sequencenumber, 
                    serl, 
                    srno, 
                    tdte, 
                    timestamp, 
                    trdt, 
                    ttyp, 
                    urat_1, 
                    urat_2, 
                    urat_3, 
                    username, 
                    year, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.acce, 
                    src.acce_kw, 
                    src.accf, 
                    src.accf_kw, 
                    src.amnt, 
                    src.amth_1, 
                    src.amth_2, 
                    src.amth_3, 
                    src.aobl, 
                    src.aobl_kw, 
                    src.arat_1, 
                    src.arat_2, 
                    src.arat_3, 
                    src.blrf, 
                    src.btno, 
                    src.buid, 
                    src.ccur, 
                    src.compnr, 
                    src.crdt, 
                    src.cuni, 
                    src.dbcr, 
                    src.dbcr_kw, 
                    src.dcdt, 
                    src.deleted, 
                    src.dim1, 
                    src.dim2, 
                    src.dim3, 
                    src.dim4, 
                    src.dim5, 
                    src.dim6, 
                    src.dim7, 
                    src.dim8, 
                    src.dim9, 
                    src.dm10, 
                    src.dm11, 
                    src.dm12, 
                    src.docn, 
                    src.fcom, 
                    src.fprd, 
                    src.fyer, 
                    src.guid, 
                    src.idtc, 
                    src.inad, 
                    src.inad_kw, 
                    src.inic, 
                    src.inic_kw, 
                    src.ktrn, 
                    src.ktrn_kw, 
                    src.lcit, 
                    src.leac, 
                    src.link, 
                    src.lino, 
                    src.nuni, 
                    src.obre, 
                    src.ocmp, 
                    src.odbc, 
                    src.odbc_kw, 
                    src.ogui, 
                    src.podt, 
                    src.proj, 
                    src.rbid, 
                    src.rbon, 
                    src.rce1, 
                    src.rce2, 
                    src.rce3, 
                    src.rce4, 
                    src.rce5, 
                    src.reco, 
                    src.reco_kw, 
                    src.recs, 
                    src.rev1, 
                    src.rev2, 
                    src.rev3, 
                    src.rev4, 
                    src.rev5, 
                    src.rpon, 
                    src.sequencenumber, 
                    src.serl, 
                    src.srno, 
                    src.tdte, 
                    src.timestamp, 
                    src.trdt, 
                    src.ttyp, 
                    src.urat_1, 
                    src.urat_2, 
                    src.urat_3, 
                    src.username, 
                    src.year,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TFGLD495_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.acce, 
            strm.acce_kw, 
            strm.accf, 
            strm.accf_kw, 
            strm.amnt, 
            strm.amth_1, 
            strm.amth_2, 
            strm.amth_3, 
            strm.aobl, 
            strm.aobl_kw, 
            strm.arat_1, 
            strm.arat_2, 
            strm.arat_3, 
            strm.blrf, 
            strm.btno, 
            strm.buid, 
            strm.ccur, 
            strm.compnr, 
            strm.crdt, 
            strm.cuni, 
            strm.dbcr, 
            strm.dbcr_kw, 
            strm.dcdt, 
            strm.deleted, 
            strm.dim1, 
            strm.dim2, 
            strm.dim3, 
            strm.dim4, 
            strm.dim5, 
            strm.dim6, 
            strm.dim7, 
            strm.dim8, 
            strm.dim9, 
            strm.dm10, 
            strm.dm11, 
            strm.dm12, 
            strm.docn, 
            strm.fcom, 
            strm.fprd, 
            strm.fyer, 
            strm.guid, 
            strm.idtc, 
            strm.inad, 
            strm.inad_kw, 
            strm.inic, 
            strm.inic_kw, 
            strm.ktrn, 
            strm.ktrn_kw, 
            strm.lcit, 
            strm.leac, 
            strm.link, 
            strm.lino, 
            strm.nuni, 
            strm.obre, 
            strm.ocmp, 
            strm.odbc, 
            strm.odbc_kw, 
            strm.ogui, 
            strm.podt, 
            strm.proj, 
            strm.rbid, 
            strm.rbon, 
            strm.rce1, 
            strm.rce2, 
            strm.rce3, 
            strm.rce4, 
            strm.rce5, 
            strm.reco, 
            strm.reco_kw, 
            strm.recs, 
            strm.rev1, 
            strm.rev2, 
            strm.rev3, 
            strm.rev4, 
            strm.rev5, 
            strm.rpon, 
            strm.sequencenumber, 
            strm.serl, 
            strm.srno, 
            strm.tdte, 
            strm.timestamp, 
            strm.trdt, 
            strm.ttyp, 
            strm.urat_1, 
            strm.urat_2, 
            strm.urat_3, 
            strm.username, 
            strm.year, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.guid,
            strm.dbcr ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFGLD495 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.guid=src.guid) OR (target.guid IS NULL AND src.guid IS NULL)) AND
            ((target.dbcr=src.dbcr) OR (target.dbcr IS NULL AND src.dbcr IS NULL)) 
                when matched then update set
                    target.acce=src.acce, 
                    target.acce_kw=src.acce_kw, 
                    target.accf=src.accf, 
                    target.accf_kw=src.accf_kw, 
                    target.amnt=src.amnt, 
                    target.amth_1=src.amth_1, 
                    target.amth_2=src.amth_2, 
                    target.amth_3=src.amth_3, 
                    target.aobl=src.aobl, 
                    target.aobl_kw=src.aobl_kw, 
                    target.arat_1=src.arat_1, 
                    target.arat_2=src.arat_2, 
                    target.arat_3=src.arat_3, 
                    target.blrf=src.blrf, 
                    target.btno=src.btno, 
                    target.buid=src.buid, 
                    target.ccur=src.ccur, 
                    target.compnr=src.compnr, 
                    target.crdt=src.crdt, 
                    target.cuni=src.cuni, 
                    target.dbcr=src.dbcr, 
                    target.dbcr_kw=src.dbcr_kw, 
                    target.dcdt=src.dcdt, 
                    target.deleted=src.deleted, 
                    target.dim1=src.dim1, 
                    target.dim2=src.dim2, 
                    target.dim3=src.dim3, 
                    target.dim4=src.dim4, 
                    target.dim5=src.dim5, 
                    target.dim6=src.dim6, 
                    target.dim7=src.dim7, 
                    target.dim8=src.dim8, 
                    target.dim9=src.dim9, 
                    target.dm10=src.dm10, 
                    target.dm11=src.dm11, 
                    target.dm12=src.dm12, 
                    target.docn=src.docn, 
                    target.fcom=src.fcom, 
                    target.fprd=src.fprd, 
                    target.fyer=src.fyer, 
                    target.guid=src.guid, 
                    target.idtc=src.idtc, 
                    target.inad=src.inad, 
                    target.inad_kw=src.inad_kw, 
                    target.inic=src.inic, 
                    target.inic_kw=src.inic_kw, 
                    target.ktrn=src.ktrn, 
                    target.ktrn_kw=src.ktrn_kw, 
                    target.lcit=src.lcit, 
                    target.leac=src.leac, 
                    target.link=src.link, 
                    target.lino=src.lino, 
                    target.nuni=src.nuni, 
                    target.obre=src.obre, 
                    target.ocmp=src.ocmp, 
                    target.odbc=src.odbc, 
                    target.odbc_kw=src.odbc_kw, 
                    target.ogui=src.ogui, 
                    target.podt=src.podt, 
                    target.proj=src.proj, 
                    target.rbid=src.rbid, 
                    target.rbon=src.rbon, 
                    target.rce1=src.rce1, 
                    target.rce2=src.rce2, 
                    target.rce3=src.rce3, 
                    target.rce4=src.rce4, 
                    target.rce5=src.rce5, 
                    target.reco=src.reco, 
                    target.reco_kw=src.reco_kw, 
                    target.recs=src.recs, 
                    target.rev1=src.rev1, 
                    target.rev2=src.rev2, 
                    target.rev3=src.rev3, 
                    target.rev4=src.rev4, 
                    target.rev5=src.rev5, 
                    target.rpon=src.rpon, 
                    target.sequencenumber=src.sequencenumber, 
                    target.serl=src.serl, 
                    target.srno=src.srno, 
                    target.tdte=src.tdte, 
                    target.timestamp=src.timestamp, 
                    target.trdt=src.trdt, 
                    target.ttyp=src.ttyp, 
                    target.urat_1=src.urat_1, 
                    target.urat_2=src.urat_2, 
                    target.urat_3=src.urat_3, 
                    target.username=src.username, 
                    target.year=src.year, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( acce, acce_kw, accf, accf_kw, amnt, amth_1, amth_2, amth_3, aobl, aobl_kw, arat_1, arat_2, arat_3, blrf, btno, buid, ccur, compnr, crdt, cuni, dbcr, dbcr_kw, dcdt, deleted, dim1, dim2, dim3, dim4, dim5, dim6, dim7, dim8, dim9, dm10, dm11, dm12, docn, fcom, fprd, fyer, guid, idtc, inad, inad_kw, inic, inic_kw, ktrn, ktrn_kw, lcit, leac, link, lino, nuni, obre, ocmp, odbc, odbc_kw, ogui, podt, proj, rbid, rbon, rce1, rce2, rce3, rce4, rce5, reco, reco_kw, recs, rev1, rev2, rev3, rev4, rev5, rpon, sequencenumber, serl, srno, tdte, timestamp, trdt, ttyp, urat_1, urat_2, urat_3, username, year, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.acce, 
                    src.acce_kw, 
                    src.accf, 
                    src.accf_kw, 
                    src.amnt, 
                    src.amth_1, 
                    src.amth_2, 
                    src.amth_3, 
                    src.aobl, 
                    src.aobl_kw, 
                    src.arat_1, 
                    src.arat_2, 
                    src.arat_3, 
                    src.blrf, 
                    src.btno, 
                    src.buid, 
                    src.ccur, 
                    src.compnr, 
                    src.crdt, 
                    src.cuni, 
                    src.dbcr, 
                    src.dbcr_kw, 
                    src.dcdt, 
                    src.deleted, 
                    src.dim1, 
                    src.dim2, 
                    src.dim3, 
                    src.dim4, 
                    src.dim5, 
                    src.dim6, 
                    src.dim7, 
                    src.dim8, 
                    src.dim9, 
                    src.dm10, 
                    src.dm11, 
                    src.dm12, 
                    src.docn, 
                    src.fcom, 
                    src.fprd, 
                    src.fyer, 
                    src.guid, 
                    src.idtc, 
                    src.inad, 
                    src.inad_kw, 
                    src.inic, 
                    src.inic_kw, 
                    src.ktrn, 
                    src.ktrn_kw, 
                    src.lcit, 
                    src.leac, 
                    src.link, 
                    src.lino, 
                    src.nuni, 
                    src.obre, 
                    src.ocmp, 
                    src.odbc, 
                    src.odbc_kw, 
                    src.ogui, 
                    src.podt, 
                    src.proj, 
                    src.rbid, 
                    src.rbon, 
                    src.rce1, 
                    src.rce2, 
                    src.rce3, 
                    src.rce4, 
                    src.rce5, 
                    src.reco, 
                    src.reco_kw, 
                    src.recs, 
                    src.rev1, 
                    src.rev2, 
                    src.rev3, 
                    src.rev4, 
                    src.rev5, 
                    src.rpon, 
                    src.sequencenumber, 
                    src.serl, 
                    src.srno, 
                    src.tdte, 
                    src.timestamp, 
                    src.trdt, 
                    src.ttyp, 
                    src.urat_1, 
                    src.urat_2, 
                    src.urat_3, 
                    src.username, 
                    src.year,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;