create or replace procedure DATAHUB_INTEGRATION.SP_LN_TPPDM615()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TPPDM615_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TPPDM615 as target using (SELECT * FROM (SELECT 
            strm.blbl, 
            strm.blbl_kw, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.cccr, 
            strm.cccr_ref_compnr, 
            strm.ccfu, 
            strm.ccfu_kw, 
            strm.ccir, 
            strm.ccir_ref_compnr, 
            strm.ccsr, 
            strm.ccsr_ref_compnr, 
            strm.ccts, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.cprj, 
            strm.cprj_ccts, 
            strm.cprj_ref_compnr, 
            strm.cprj_task, 
            strm.ctrg, 
            strm.ctrg_ref_compnr, 
            strm.cuni, 
            strm.cuni_ref_compnr, 
            strm.cvat, 
            strm.cvat_ref_compnr, 
            strm.deleted, 
            strm.desc, 
            strm.dfrc, 
            strm.dfrc_kw, 
            strm.dfri, 
            strm.dfri_kw, 
            strm.dfrs, 
            strm.dfrs_kw, 
            strm.dfts, 
            strm.dfts_ref_compnr, 
            strm.eplf, 
            strm.ltrc, 
            strm.ltri, 
            strm.ltrs, 
            strm.norm, 
            strm.prre, 
            strm.prre_kw, 
            strm.ratc, 
            strm.rati, 
            strm.rats, 
            strm.rcmc_1, 
            strm.rcmc_2, 
            strm.rcmc_3, 
            strm.rfac, 
            strm.rimc_1, 
            strm.rimc_2, 
            strm.rimc_3, 
            strm.rsmc_1, 
            strm.rsmc_2, 
            strm.rsmc_3, 
            strm.seak, 
            strm.sequencenumber, 
            strm.task, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.unrt, 
            strm.unrt_ref_compnr, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.cprj,
            strm.task ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPDM615 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.cprj=src.cprj) OR (target.cprj IS NULL AND src.cprj IS NULL)) AND
            ((target.task=src.task) OR (target.task IS NULL AND src.task IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.blbl=src.blbl, 
                    target.blbl_kw=src.blbl_kw, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.cccr=src.cccr, 
                    target.cccr_ref_compnr=src.cccr_ref_compnr, 
                    target.ccfu=src.ccfu, 
                    target.ccfu_kw=src.ccfu_kw, 
                    target.ccir=src.ccir, 
                    target.ccir_ref_compnr=src.ccir_ref_compnr, 
                    target.ccsr=src.ccsr, 
                    target.ccsr_ref_compnr=src.ccsr_ref_compnr, 
                    target.ccts=src.ccts, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cprj=src.cprj, 
                    target.cprj_ccts=src.cprj_ccts, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cprj_task=src.cprj_task, 
                    target.ctrg=src.ctrg, 
                    target.ctrg_ref_compnr=src.ctrg_ref_compnr, 
                    target.cuni=src.cuni, 
                    target.cuni_ref_compnr=src.cuni_ref_compnr, 
                    target.cvat=src.cvat, 
                    target.cvat_ref_compnr=src.cvat_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.dfrc=src.dfrc, 
                    target.dfrc_kw=src.dfrc_kw, 
                    target.dfri=src.dfri, 
                    target.dfri_kw=src.dfri_kw, 
                    target.dfrs=src.dfrs, 
                    target.dfrs_kw=src.dfrs_kw, 
                    target.dfts=src.dfts, 
                    target.dfts_ref_compnr=src.dfts_ref_compnr, 
                    target.eplf=src.eplf, 
                    target.ltrc=src.ltrc, 
                    target.ltri=src.ltri, 
                    target.ltrs=src.ltrs, 
                    target.norm=src.norm, 
                    target.prre=src.prre, 
                    target.prre_kw=src.prre_kw, 
                    target.ratc=src.ratc, 
                    target.rati=src.rati, 
                    target.rats=src.rats, 
                    target.rcmc_1=src.rcmc_1, 
                    target.rcmc_2=src.rcmc_2, 
                    target.rcmc_3=src.rcmc_3, 
                    target.rfac=src.rfac, 
                    target.rimc_1=src.rimc_1, 
                    target.rimc_2=src.rimc_2, 
                    target.rimc_3=src.rimc_3, 
                    target.rsmc_1=src.rsmc_1, 
                    target.rsmc_2=src.rsmc_2, 
                    target.rsmc_3=src.rsmc_3, 
                    target.seak=src.seak, 
                    target.sequencenumber=src.sequencenumber, 
                    target.task=src.task, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.unrt=src.unrt, 
                    target.unrt_ref_compnr=src.unrt_ref_compnr, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    blbl, 
                    blbl_kw, 
                    ccco, 
                    ccco_ref_compnr, 
                    cccr, 
                    cccr_ref_compnr, 
                    ccfu, 
                    ccfu_kw, 
                    ccir, 
                    ccir_ref_compnr, 
                    ccsr, 
                    ccsr_ref_compnr, 
                    ccts, 
                    cofc, 
                    cofc_ref_compnr, 
                    compnr, 
                    cprj, 
                    cprj_ccts, 
                    cprj_ref_compnr, 
                    cprj_task, 
                    ctrg, 
                    ctrg_ref_compnr, 
                    cuni, 
                    cuni_ref_compnr, 
                    cvat, 
                    cvat_ref_compnr, 
                    deleted, 
                    desc, 
                    dfrc, 
                    dfrc_kw, 
                    dfri, 
                    dfri_kw, 
                    dfrs, 
                    dfrs_kw, 
                    dfts, 
                    dfts_ref_compnr, 
                    eplf, 
                    ltrc, 
                    ltri, 
                    ltrs, 
                    norm, 
                    prre, 
                    prre_kw, 
                    ratc, 
                    rati, 
                    rats, 
                    rcmc_1, 
                    rcmc_2, 
                    rcmc_3, 
                    rfac, 
                    rimc_1, 
                    rimc_2, 
                    rimc_3, 
                    rsmc_1, 
                    rsmc_2, 
                    rsmc_3, 
                    seak, 
                    sequencenumber, 
                    task, 
                    timestamp, 
                    txta, 
                    txta_ref_compnr, 
                    unrt, 
                    unrt_ref_compnr, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.blbl, 
                    src.blbl_kw, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.cccr, 
                    src.cccr_ref_compnr, 
                    src.ccfu, 
                    src.ccfu_kw, 
                    src.ccir, 
                    src.ccir_ref_compnr, 
                    src.ccsr, 
                    src.ccsr_ref_compnr, 
                    src.ccts, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.cprj, 
                    src.cprj_ccts, 
                    src.cprj_ref_compnr, 
                    src.cprj_task, 
                    src.ctrg, 
                    src.ctrg_ref_compnr, 
                    src.cuni, 
                    src.cuni_ref_compnr, 
                    src.cvat, 
                    src.cvat_ref_compnr, 
                    src.deleted, 
                    src.desc, 
                    src.dfrc, 
                    src.dfrc_kw, 
                    src.dfri, 
                    src.dfri_kw, 
                    src.dfrs, 
                    src.dfrs_kw, 
                    src.dfts, 
                    src.dfts_ref_compnr, 
                    src.eplf, 
                    src.ltrc, 
                    src.ltri, 
                    src.ltrs, 
                    src.norm, 
                    src.prre, 
                    src.prre_kw, 
                    src.ratc, 
                    src.rati, 
                    src.rats, 
                    src.rcmc_1, 
                    src.rcmc_2, 
                    src.rcmc_3, 
                    src.rfac, 
                    src.rimc_1, 
                    src.rimc_2, 
                    src.rimc_3, 
                    src.rsmc_1, 
                    src.rsmc_2, 
                    src.rsmc_3, 
                    src.seak, 
                    src.sequencenumber, 
                    src.task, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.unrt, 
                    src.unrt_ref_compnr, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TPPDM615_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.blbl, 
            strm.blbl_kw, 
            strm.ccco, 
            strm.ccco_ref_compnr, 
            strm.cccr, 
            strm.cccr_ref_compnr, 
            strm.ccfu, 
            strm.ccfu_kw, 
            strm.ccir, 
            strm.ccir_ref_compnr, 
            strm.ccsr, 
            strm.ccsr_ref_compnr, 
            strm.ccts, 
            strm.cofc, 
            strm.cofc_ref_compnr, 
            strm.compnr, 
            strm.cprj, 
            strm.cprj_ccts, 
            strm.cprj_ref_compnr, 
            strm.cprj_task, 
            strm.ctrg, 
            strm.ctrg_ref_compnr, 
            strm.cuni, 
            strm.cuni_ref_compnr, 
            strm.cvat, 
            strm.cvat_ref_compnr, 
            strm.deleted, 
            strm.desc, 
            strm.dfrc, 
            strm.dfrc_kw, 
            strm.dfri, 
            strm.dfri_kw, 
            strm.dfrs, 
            strm.dfrs_kw, 
            strm.dfts, 
            strm.dfts_ref_compnr, 
            strm.eplf, 
            strm.ltrc, 
            strm.ltri, 
            strm.ltrs, 
            strm.norm, 
            strm.prre, 
            strm.prre_kw, 
            strm.ratc, 
            strm.rati, 
            strm.rats, 
            strm.rcmc_1, 
            strm.rcmc_2, 
            strm.rcmc_3, 
            strm.rfac, 
            strm.rimc_1, 
            strm.rimc_2, 
            strm.rimc_3, 
            strm.rsmc_1, 
            strm.rsmc_2, 
            strm.rsmc_3, 
            strm.seak, 
            strm.sequencenumber, 
            strm.task, 
            strm.timestamp, 
            strm.txta, 
            strm.txta_ref_compnr, 
            strm.unrt, 
            strm.unrt_ref_compnr, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.cprj,
            strm.task ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TPPDM615 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.cprj=src.cprj) OR (target.cprj IS NULL AND src.cprj IS NULL)) AND
            ((target.task=src.task) OR (target.task IS NULL AND src.task IS NULL)) 
                when matched then update set
                    target.blbl=src.blbl, 
                    target.blbl_kw=src.blbl_kw, 
                    target.ccco=src.ccco, 
                    target.ccco_ref_compnr=src.ccco_ref_compnr, 
                    target.cccr=src.cccr, 
                    target.cccr_ref_compnr=src.cccr_ref_compnr, 
                    target.ccfu=src.ccfu, 
                    target.ccfu_kw=src.ccfu_kw, 
                    target.ccir=src.ccir, 
                    target.ccir_ref_compnr=src.ccir_ref_compnr, 
                    target.ccsr=src.ccsr, 
                    target.ccsr_ref_compnr=src.ccsr_ref_compnr, 
                    target.ccts=src.ccts, 
                    target.cofc=src.cofc, 
                    target.cofc_ref_compnr=src.cofc_ref_compnr, 
                    target.compnr=src.compnr, 
                    target.cprj=src.cprj, 
                    target.cprj_ccts=src.cprj_ccts, 
                    target.cprj_ref_compnr=src.cprj_ref_compnr, 
                    target.cprj_task=src.cprj_task, 
                    target.ctrg=src.ctrg, 
                    target.ctrg_ref_compnr=src.ctrg_ref_compnr, 
                    target.cuni=src.cuni, 
                    target.cuni_ref_compnr=src.cuni_ref_compnr, 
                    target.cvat=src.cvat, 
                    target.cvat_ref_compnr=src.cvat_ref_compnr, 
                    target.deleted=src.deleted, 
                    target.desc=src.desc, 
                    target.dfrc=src.dfrc, 
                    target.dfrc_kw=src.dfrc_kw, 
                    target.dfri=src.dfri, 
                    target.dfri_kw=src.dfri_kw, 
                    target.dfrs=src.dfrs, 
                    target.dfrs_kw=src.dfrs_kw, 
                    target.dfts=src.dfts, 
                    target.dfts_ref_compnr=src.dfts_ref_compnr, 
                    target.eplf=src.eplf, 
                    target.ltrc=src.ltrc, 
                    target.ltri=src.ltri, 
                    target.ltrs=src.ltrs, 
                    target.norm=src.norm, 
                    target.prre=src.prre, 
                    target.prre_kw=src.prre_kw, 
                    target.ratc=src.ratc, 
                    target.rati=src.rati, 
                    target.rats=src.rats, 
                    target.rcmc_1=src.rcmc_1, 
                    target.rcmc_2=src.rcmc_2, 
                    target.rcmc_3=src.rcmc_3, 
                    target.rfac=src.rfac, 
                    target.rimc_1=src.rimc_1, 
                    target.rimc_2=src.rimc_2, 
                    target.rimc_3=src.rimc_3, 
                    target.rsmc_1=src.rsmc_1, 
                    target.rsmc_2=src.rsmc_2, 
                    target.rsmc_3=src.rsmc_3, 
                    target.seak=src.seak, 
                    target.sequencenumber=src.sequencenumber, 
                    target.task=src.task, 
                    target.timestamp=src.timestamp, 
                    target.txta=src.txta, 
                    target.txta_ref_compnr=src.txta_ref_compnr, 
                    target.unrt=src.unrt, 
                    target.unrt_ref_compnr=src.unrt_ref_compnr, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( blbl, blbl_kw, ccco, ccco_ref_compnr, cccr, cccr_ref_compnr, ccfu, ccfu_kw, ccir, ccir_ref_compnr, ccsr, ccsr_ref_compnr, ccts, cofc, cofc_ref_compnr, compnr, cprj, cprj_ccts, cprj_ref_compnr, cprj_task, ctrg, ctrg_ref_compnr, cuni, cuni_ref_compnr, cvat, cvat_ref_compnr, deleted, desc, dfrc, dfrc_kw, dfri, dfri_kw, dfrs, dfrs_kw, dfts, dfts_ref_compnr, eplf, ltrc, ltri, ltrs, norm, prre, prre_kw, ratc, rati, rats, rcmc_1, rcmc_2, rcmc_3, rfac, rimc_1, rimc_2, rimc_3, rsmc_1, rsmc_2, rsmc_3, seak, sequencenumber, task, timestamp, txta, txta_ref_compnr, unrt, unrt_ref_compnr, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.blbl, 
                    src.blbl_kw, 
                    src.ccco, 
                    src.ccco_ref_compnr, 
                    src.cccr, 
                    src.cccr_ref_compnr, 
                    src.ccfu, 
                    src.ccfu_kw, 
                    src.ccir, 
                    src.ccir_ref_compnr, 
                    src.ccsr, 
                    src.ccsr_ref_compnr, 
                    src.ccts, 
                    src.cofc, 
                    src.cofc_ref_compnr, 
                    src.compnr, 
                    src.cprj, 
                    src.cprj_ccts, 
                    src.cprj_ref_compnr, 
                    src.cprj_task, 
                    src.ctrg, 
                    src.ctrg_ref_compnr, 
                    src.cuni, 
                    src.cuni_ref_compnr, 
                    src.cvat, 
                    src.cvat_ref_compnr, 
                    src.deleted, 
                    src.desc, 
                    src.dfrc, 
                    src.dfrc_kw, 
                    src.dfri, 
                    src.dfri_kw, 
                    src.dfrs, 
                    src.dfrs_kw, 
                    src.dfts, 
                    src.dfts_ref_compnr, 
                    src.eplf, 
                    src.ltrc, 
                    src.ltri, 
                    src.ltrs, 
                    src.norm, 
                    src.prre, 
                    src.prre_kw, 
                    src.ratc, 
                    src.rati, 
                    src.rats, 
                    src.rcmc_1, 
                    src.rcmc_2, 
                    src.rcmc_3, 
                    src.rfac, 
                    src.rimc_1, 
                    src.rimc_2, 
                    src.rimc_3, 
                    src.rsmc_1, 
                    src.rsmc_2, 
                    src.rsmc_3, 
                    src.seak, 
                    src.sequencenumber, 
                    src.task, 
                    src.timestamp, 
                    src.txta, 
                    src.txta_ref_compnr, 
                    src.unrt, 
                    src.unrt_ref_compnr, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;