create or replace procedure DATAHUB_INTEGRATION.SP_LN_TFFAM710()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.LN_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_LN_TFFAM710_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_LN.LN_TFFAM710 as target using (SELECT * FROM (SELECT 
            strm.acnp, 
            strm.acnp_kw, 
            strm.bdad, 
            strm.bdad_kw, 
            strm.bnbv, 
            strm.bnbv_kw, 
            strm.calb, 
            strm.calb_kw, 
            strm.capp, 
            strm.capp_kw, 
            strm.compnr, 
            strm.conv, 
            strm.conv_kw, 
            strm.cper, 
            strm.dbpt, 
            strm.deleted, 
            strm.depl, 
            strm.depl_kw, 
            strm.desc, 
            strm.didt, 
            strm.didt_kw, 
            strm.disp, 
            strm.disp_kw, 
            strm.dprc, 
            strm.dprc_kw, 
            strm.face, 
            strm.face_kw, 
            strm.famt, 
            strm.famt_kw, 
            strm.fcal, 
            strm.fcal_kw, 
            strm.fcom, 
            strm.fcom_kw, 
            strm.ffin, 
            strm.ffin_kw, 
            strm.fixa_1, 
            strm.fixa_2, 
            strm.fixa_3, 
            strm.foth, 
            strm.foth_kw, 
            strm.fspe, 
            strm.fspe_kw, 
            strm.fsta, 
            strm.fsta_kw, 
            strm.fstd, 
            strm.fstd_kw, 
            strm.gfac, 
            strm.intr, 
            strm.life, 
            strm.meth, 
            strm.nygf, 
            strm.perc, 
            strm.post, 
            strm.post_kw, 
            strm.rdgf, 
            strm.rndy, 
            strm.rndy_kw, 
            strm.rtty, 
            strm.rtty_kw, 
            strm.sbsv, 
            strm.sbsv_kw, 
            strm.sequencenumber, 
            strm.silp, 
            strm.silp_kw, 
            strm.stcp, 
            strm.stcp_kw, 
            strm.swsl, 
            strm.swsl_kw, 
            strm.taxt, 
            strm.taxt_kw, 
            strm.timestamp, 
            strm.type, 
            strm.type_kw, 
            strm.updt, 
            strm.updt_kw, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.meth ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFFAM710 as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.meth=src.meth) OR (target.meth IS NULL AND src.meth IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.acnp=src.acnp, 
                    target.acnp_kw=src.acnp_kw, 
                    target.bdad=src.bdad, 
                    target.bdad_kw=src.bdad_kw, 
                    target.bnbv=src.bnbv, 
                    target.bnbv_kw=src.bnbv_kw, 
                    target.calb=src.calb, 
                    target.calb_kw=src.calb_kw, 
                    target.capp=src.capp, 
                    target.capp_kw=src.capp_kw, 
                    target.compnr=src.compnr, 
                    target.conv=src.conv, 
                    target.conv_kw=src.conv_kw, 
                    target.cper=src.cper, 
                    target.dbpt=src.dbpt, 
                    target.deleted=src.deleted, 
                    target.depl=src.depl, 
                    target.depl_kw=src.depl_kw, 
                    target.desc=src.desc, 
                    target.didt=src.didt, 
                    target.didt_kw=src.didt_kw, 
                    target.disp=src.disp, 
                    target.disp_kw=src.disp_kw, 
                    target.dprc=src.dprc, 
                    target.dprc_kw=src.dprc_kw, 
                    target.face=src.face, 
                    target.face_kw=src.face_kw, 
                    target.famt=src.famt, 
                    target.famt_kw=src.famt_kw, 
                    target.fcal=src.fcal, 
                    target.fcal_kw=src.fcal_kw, 
                    target.fcom=src.fcom, 
                    target.fcom_kw=src.fcom_kw, 
                    target.ffin=src.ffin, 
                    target.ffin_kw=src.ffin_kw, 
                    target.fixa_1=src.fixa_1, 
                    target.fixa_2=src.fixa_2, 
                    target.fixa_3=src.fixa_3, 
                    target.foth=src.foth, 
                    target.foth_kw=src.foth_kw, 
                    target.fspe=src.fspe, 
                    target.fspe_kw=src.fspe_kw, 
                    target.fsta=src.fsta, 
                    target.fsta_kw=src.fsta_kw, 
                    target.fstd=src.fstd, 
                    target.fstd_kw=src.fstd_kw, 
                    target.gfac=src.gfac, 
                    target.intr=src.intr, 
                    target.life=src.life, 
                    target.meth=src.meth, 
                    target.nygf=src.nygf, 
                    target.perc=src.perc, 
                    target.post=src.post, 
                    target.post_kw=src.post_kw, 
                    target.rdgf=src.rdgf, 
                    target.rndy=src.rndy, 
                    target.rndy_kw=src.rndy_kw, 
                    target.rtty=src.rtty, 
                    target.rtty_kw=src.rtty_kw, 
                    target.sbsv=src.sbsv, 
                    target.sbsv_kw=src.sbsv_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.silp=src.silp, 
                    target.silp_kw=src.silp_kw, 
                    target.stcp=src.stcp, 
                    target.stcp_kw=src.stcp_kw, 
                    target.swsl=src.swsl, 
                    target.swsl_kw=src.swsl_kw, 
                    target.taxt=src.taxt, 
                    target.taxt_kw=src.taxt_kw, 
                    target.timestamp=src.timestamp, 
                    target.type=src.type, 
                    target.type_kw=src.type_kw, 
                    target.updt=src.updt, 
                    target.updt_kw=src.updt_kw, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    acnp, 
                    acnp_kw, 
                    bdad, 
                    bdad_kw, 
                    bnbv, 
                    bnbv_kw, 
                    calb, 
                    calb_kw, 
                    capp, 
                    capp_kw, 
                    compnr, 
                    conv, 
                    conv_kw, 
                    cper, 
                    dbpt, 
                    deleted, 
                    depl, 
                    depl_kw, 
                    desc, 
                    didt, 
                    didt_kw, 
                    disp, 
                    disp_kw, 
                    dprc, 
                    dprc_kw, 
                    face, 
                    face_kw, 
                    famt, 
                    famt_kw, 
                    fcal, 
                    fcal_kw, 
                    fcom, 
                    fcom_kw, 
                    ffin, 
                    ffin_kw, 
                    fixa_1, 
                    fixa_2, 
                    fixa_3, 
                    foth, 
                    foth_kw, 
                    fspe, 
                    fspe_kw, 
                    fsta, 
                    fsta_kw, 
                    fstd, 
                    fstd_kw, 
                    gfac, 
                    intr, 
                    life, 
                    meth, 
                    nygf, 
                    perc, 
                    post, 
                    post_kw, 
                    rdgf, 
                    rndy, 
                    rndy_kw, 
                    rtty, 
                    rtty_kw, 
                    sbsv, 
                    sbsv_kw, 
                    sequencenumber, 
                    silp, 
                    silp_kw, 
                    stcp, 
                    stcp_kw, 
                    swsl, 
                    swsl_kw, 
                    taxt, 
                    taxt_kw, 
                    timestamp, 
                    type, 
                    type_kw, 
                    updt, 
                    updt_kw, 
                    username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.acnp, 
                    src.acnp_kw, 
                    src.bdad, 
                    src.bdad_kw, 
                    src.bnbv, 
                    src.bnbv_kw, 
                    src.calb, 
                    src.calb_kw, 
                    src.capp, 
                    src.capp_kw, 
                    src.compnr, 
                    src.conv, 
                    src.conv_kw, 
                    src.cper, 
                    src.dbpt, 
                    src.deleted, 
                    src.depl, 
                    src.depl_kw, 
                    src.desc, 
                    src.didt, 
                    src.didt_kw, 
                    src.disp, 
                    src.disp_kw, 
                    src.dprc, 
                    src.dprc_kw, 
                    src.face, 
                    src.face_kw, 
                    src.famt, 
                    src.famt_kw, 
                    src.fcal, 
                    src.fcal_kw, 
                    src.fcom, 
                    src.fcom_kw, 
                    src.ffin, 
                    src.ffin_kw, 
                    src.fixa_1, 
                    src.fixa_2, 
                    src.fixa_3, 
                    src.foth, 
                    src.foth_kw, 
                    src.fspe, 
                    src.fspe_kw, 
                    src.fsta, 
                    src.fsta_kw, 
                    src.fstd, 
                    src.fstd_kw, 
                    src.gfac, 
                    src.intr, 
                    src.life, 
                    src.meth, 
                    src.nygf, 
                    src.perc, 
                    src.post, 
                    src.post_kw, 
                    src.rdgf, 
                    src.rndy, 
                    src.rndy_kw, 
                    src.rtty, 
                    src.rtty_kw, 
                    src.sbsv, 
                    src.sbsv_kw, 
                    src.sequencenumber, 
                    src.silp, 
                    src.silp_kw, 
                    src.stcp, 
                    src.stcp_kw, 
                    src.swsl, 
                    src.swsl_kw, 
                    src.taxt, 
                    src.taxt_kw, 
                    src.timestamp, 
                    src.type, 
                    src.type_kw, 
                    src.updt, 
                    src.updt_kw, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_LN.LN_TFFAM710_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.acnp, 
            strm.acnp_kw, 
            strm.bdad, 
            strm.bdad_kw, 
            strm.bnbv, 
            strm.bnbv_kw, 
            strm.calb, 
            strm.calb_kw, 
            strm.capp, 
            strm.capp_kw, 
            strm.compnr, 
            strm.conv, 
            strm.conv_kw, 
            strm.cper, 
            strm.dbpt, 
            strm.deleted, 
            strm.depl, 
            strm.depl_kw, 
            strm.desc, 
            strm.didt, 
            strm.didt_kw, 
            strm.disp, 
            strm.disp_kw, 
            strm.dprc, 
            strm.dprc_kw, 
            strm.face, 
            strm.face_kw, 
            strm.famt, 
            strm.famt_kw, 
            strm.fcal, 
            strm.fcal_kw, 
            strm.fcom, 
            strm.fcom_kw, 
            strm.ffin, 
            strm.ffin_kw, 
            strm.fixa_1, 
            strm.fixa_2, 
            strm.fixa_3, 
            strm.foth, 
            strm.foth_kw, 
            strm.fspe, 
            strm.fspe_kw, 
            strm.fsta, 
            strm.fsta_kw, 
            strm.fstd, 
            strm.fstd_kw, 
            strm.gfac, 
            strm.intr, 
            strm.life, 
            strm.meth, 
            strm.nygf, 
            strm.perc, 
            strm.post, 
            strm.post_kw, 
            strm.rdgf, 
            strm.rndy, 
            strm.rndy_kw, 
            strm.rtty, 
            strm.rtty_kw, 
            strm.sbsv, 
            strm.sbsv_kw, 
            strm.sequencenumber, 
            strm.silp, 
            strm.silp_kw, 
            strm.stcp, 
            strm.stcp_kw, 
            strm.swsl, 
            strm.swsl_kw, 
            strm.taxt, 
            strm.taxt_kw, 
            strm.timestamp, 
            strm.type, 
            strm.type_kw, 
            strm.updt, 
            strm.updt_kw, 
            strm.username, 
            strm.ETL_SEQUENCE_NUMBER,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.compnr,
            strm.meth ORDER BY strm.ETL_SEQUENCE_NUMBER desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_LN_TFFAM710 as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.compnr=src.compnr) OR (target.compnr IS NULL AND src.compnr IS NULL)) AND
            ((target.meth=src.meth) OR (target.meth IS NULL AND src.meth IS NULL)) 
                when matched then update set
                    target.acnp=src.acnp, 
                    target.acnp_kw=src.acnp_kw, 
                    target.bdad=src.bdad, 
                    target.bdad_kw=src.bdad_kw, 
                    target.bnbv=src.bnbv, 
                    target.bnbv_kw=src.bnbv_kw, 
                    target.calb=src.calb, 
                    target.calb_kw=src.calb_kw, 
                    target.capp=src.capp, 
                    target.capp_kw=src.capp_kw, 
                    target.compnr=src.compnr, 
                    target.conv=src.conv, 
                    target.conv_kw=src.conv_kw, 
                    target.cper=src.cper, 
                    target.dbpt=src.dbpt, 
                    target.deleted=src.deleted, 
                    target.depl=src.depl, 
                    target.depl_kw=src.depl_kw, 
                    target.desc=src.desc, 
                    target.didt=src.didt, 
                    target.didt_kw=src.didt_kw, 
                    target.disp=src.disp, 
                    target.disp_kw=src.disp_kw, 
                    target.dprc=src.dprc, 
                    target.dprc_kw=src.dprc_kw, 
                    target.face=src.face, 
                    target.face_kw=src.face_kw, 
                    target.famt=src.famt, 
                    target.famt_kw=src.famt_kw, 
                    target.fcal=src.fcal, 
                    target.fcal_kw=src.fcal_kw, 
                    target.fcom=src.fcom, 
                    target.fcom_kw=src.fcom_kw, 
                    target.ffin=src.ffin, 
                    target.ffin_kw=src.ffin_kw, 
                    target.fixa_1=src.fixa_1, 
                    target.fixa_2=src.fixa_2, 
                    target.fixa_3=src.fixa_3, 
                    target.foth=src.foth, 
                    target.foth_kw=src.foth_kw, 
                    target.fspe=src.fspe, 
                    target.fspe_kw=src.fspe_kw, 
                    target.fsta=src.fsta, 
                    target.fsta_kw=src.fsta_kw, 
                    target.fstd=src.fstd, 
                    target.fstd_kw=src.fstd_kw, 
                    target.gfac=src.gfac, 
                    target.intr=src.intr, 
                    target.life=src.life, 
                    target.meth=src.meth, 
                    target.nygf=src.nygf, 
                    target.perc=src.perc, 
                    target.post=src.post, 
                    target.post_kw=src.post_kw, 
                    target.rdgf=src.rdgf, 
                    target.rndy=src.rndy, 
                    target.rndy_kw=src.rndy_kw, 
                    target.rtty=src.rtty, 
                    target.rtty_kw=src.rtty_kw, 
                    target.sbsv=src.sbsv, 
                    target.sbsv_kw=src.sbsv_kw, 
                    target.sequencenumber=src.sequencenumber, 
                    target.silp=src.silp, 
                    target.silp_kw=src.silp_kw, 
                    target.stcp=src.stcp, 
                    target.stcp_kw=src.stcp_kw, 
                    target.swsl=src.swsl, 
                    target.swsl_kw=src.swsl_kw, 
                    target.taxt=src.taxt, 
                    target.taxt_kw=src.taxt_kw, 
                    target.timestamp=src.timestamp, 
                    target.type=src.type, 
                    target.type_kw=src.type_kw, 
                    target.updt=src.updt, 
                    target.updt_kw=src.updt_kw, 
                    target.username=src.username, 
                    target.ETL_SEQUENCE_NUMBER=src.ETL_SEQUENCE_NUMBER,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( acnp, acnp_kw, bdad, bdad_kw, bnbv, bnbv_kw, calb, calb_kw, capp, capp_kw, compnr, conv, conv_kw, cper, dbpt, deleted, depl, depl_kw, desc, didt, didt_kw, disp, disp_kw, dprc, dprc_kw, face, face_kw, famt, famt_kw, fcal, fcal_kw, fcom, fcom_kw, ffin, ffin_kw, fixa_1, fixa_2, fixa_3, foth, foth_kw, fspe, fspe_kw, fsta, fsta_kw, fstd, fstd_kw, gfac, intr, life, meth, nygf, perc, post, post_kw, rdgf, rndy, rndy_kw, rtty, rtty_kw, sbsv, sbsv_kw, sequencenumber, silp, silp_kw, stcp, stcp_kw, swsl, swsl_kw, taxt, taxt_kw, timestamp, type, type_kw, updt, updt_kw, username, 
                    ETL_SEQUENCE_NUMBER,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.acnp, 
                    src.acnp_kw, 
                    src.bdad, 
                    src.bdad_kw, 
                    src.bnbv, 
                    src.bnbv_kw, 
                    src.calb, 
                    src.calb_kw, 
                    src.capp, 
                    src.capp_kw, 
                    src.compnr, 
                    src.conv, 
                    src.conv_kw, 
                    src.cper, 
                    src.dbpt, 
                    src.deleted, 
                    src.depl, 
                    src.depl_kw, 
                    src.desc, 
                    src.didt, 
                    src.didt_kw, 
                    src.disp, 
                    src.disp_kw, 
                    src.dprc, 
                    src.dprc_kw, 
                    src.face, 
                    src.face_kw, 
                    src.famt, 
                    src.famt_kw, 
                    src.fcal, 
                    src.fcal_kw, 
                    src.fcom, 
                    src.fcom_kw, 
                    src.ffin, 
                    src.ffin_kw, 
                    src.fixa_1, 
                    src.fixa_2, 
                    src.fixa_3, 
                    src.foth, 
                    src.foth_kw, 
                    src.fspe, 
                    src.fspe_kw, 
                    src.fsta, 
                    src.fsta_kw, 
                    src.fstd, 
                    src.fstd_kw, 
                    src.gfac, 
                    src.intr, 
                    src.life, 
                    src.meth, 
                    src.nygf, 
                    src.perc, 
                    src.post, 
                    src.post_kw, 
                    src.rdgf, 
                    src.rndy, 
                    src.rndy_kw, 
                    src.rtty, 
                    src.rtty_kw, 
                    src.sbsv, 
                    src.sbsv_kw, 
                    src.sequencenumber, 
                    src.silp, 
                    src.silp_kw, 
                    src.stcp, 
                    src.stcp_kw, 
                    src.swsl, 
                    src.swsl_kw, 
                    src.taxt, 
                    src.taxt_kw, 
                    src.timestamp, 
                    src.type, 
                    src.type_kw, 
                    src.updt, 
                    src.updt_kw, 
                    src.username,     
                    src.ETL_SEQUENCE_NUMBER,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;