{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='eam_R5COMPANIES',
    tags=['auto-generated', 'eam', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['COM_LASTSAVED'], type='timestamp_ntz', alias='com_lastsaved') }},
        {{ trx_json_extract('src', ['COM_CODE'], type='varchar', alias='com_code') }},
        {{ trx_json_extract('src', ['COM_DESC'], type='varchar', alias='com_desc') }},
        {{ trx_json_extract('src', ['COM_CLASS'], type='varchar', alias='com_class') }},
        {{ trx_json_extract('src', ['COM_CONTACT'], type='varchar', alias='com_contact') }},
        {{ trx_json_extract('src', ['COM_OURCONT'], type='varchar', alias='com_ourcont') }},
        {{ trx_json_extract('src', ['COM_CURR'], type='varchar', alias='com_curr') }},
        {{ trx_json_extract('src', ['COM_LANG'], type='varchar', alias='com_lang') }},
        {{ trx_json_extract('src', ['COM_LEADTIME'], type='float', alias='com_leadtime') }},
        {{ trx_json_extract('src', ['COM_MAXORD'], type='float', alias='com_maxord') }},
        {{ trx_json_extract('src', ['COM_MINORD'], type='float', alias='com_minord') }},
        {{ trx_json_extract('src', ['COM_STATUS'], type='varchar', alias='com_status') }},
        {{ trx_json_extract('src', ['COM_PHONE'], type='varchar', alias='com_phone') }},
        {{ trx_json_extract('src', ['COM_FAX'], type='varchar', alias='com_fax') }},
        {{ trx_json_extract('src', ['COM_BUYER'], type='varchar', alias='com_buyer') }},
        {{ trx_json_extract('src', ['COM_PARENT'], type='varchar', alias='com_parent') }},
        {{ trx_json_extract('src', ['COM_PAYMENTTERMS'], type='varchar', alias='com_paymentterms') }},
        {{ trx_json_extract('src', ['COM_FREIGHTTERMS'], type='varchar', alias='com_freightterms') }},
        {{ trx_json_extract('src', ['COM_SHIPVIA'], type='varchar', alias='com_shipvia') }},
        {{ trx_json_extract('src', ['COM_FOBPOINT'], type='varchar', alias='com_fobpoint') }},
        {{ trx_json_extract('src', ['COM_PURCHASESITE'], type='varchar', alias='com_purchasesite') }},
        {{ trx_json_extract('src', ['COM_MINORITYGROUP'], type='varchar', alias='com_minoritygroup') }},
        {{ trx_json_extract('src', ['COM_EDINO'], type='varchar', alias='com_edino') }},
        {{ trx_json_extract('src', ['COM_SOURCESYSTEM'], type='varchar', alias='com_sourcesystem') }},
        {{ trx_json_extract('src', ['COM_SOURCECODE'], type='varchar', alias='com_sourcecode') }},
        {{ trx_json_extract('src', ['COM_INTERFACE'], type='timestamp_ntz', alias='com_interface') }},
        {{ trx_json_extract('src', ['COM_NOTUSED'], type='varchar', alias='com_notused') }},
        {{ trx_json_extract('src', ['COM_CAPACITY'], type='float', alias='com_capacity') }},
        {{ trx_json_extract('src', ['COM_PEOPLE'], type='varchar', alias='com_people') }},
        {{ trx_json_extract('src', ['COM_ORG'], type='varchar', alias='com_org') }},
        {{ trx_json_extract('src', ['COM_CLASS_ORG'], type='varchar', alias='com_class_org') }},
        {{ trx_json_extract('src', ['COM_PARENT_ORG'], type='varchar', alias='com_parent_org') }},
        {{ trx_json_extract('src', ['COM_EMAIL'], type='varchar', alias='com_email') }},
        {{ trx_json_extract('src', ['COM_IPVENDOR'], type='float', alias='com_ipvendor') }},
        {{ trx_json_extract('src', ['COM_PAYBYMETHOD'], type='varchar', alias='com_paybymethod') }},
        {{ trx_json_extract('src', ['COM_IPACCOUNT'], type='varchar', alias='com_ipaccount') }},
        {{ trx_json_extract('src', ['COM_IPRESPONSE'], type='varchar', alias='com_ipresponse') }},
        {{ trx_json_extract('src', ['COM_UPDATECOUNT'], type='float', alias='com_updatecount') }},
        {{ trx_json_extract('src', ['COM_CREATED'], type='timestamp_ntz', alias='com_created') }},
        {{ trx_json_extract('src', ['COM_UPDATED'], type='timestamp_ntz', alias='com_updated') }},
        {{ trx_json_extract('src', ['COM_LASTSTATUSUPDATE'], type='timestamp_ntz', alias='com_laststatusupdate') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR01'], type='varchar', alias='com_udfchar01') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR02'], type='varchar', alias='com_udfchar02') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR03'], type='varchar', alias='com_udfchar03') }},
        {{ trx_json_extract('src', ['COM_TYPE1099'], type='varchar', alias='com_type1099') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR04'], type='varchar', alias='com_udfchar04') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR05'], type='varchar', alias='com_udfchar05') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR06'], type='varchar', alias='com_udfchar06') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR07'], type='varchar', alias='com_udfchar07') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR08'], type='varchar', alias='com_udfchar08') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR09'], type='varchar', alias='com_udfchar09') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR10'], type='varchar', alias='com_udfchar10') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR11'], type='varchar', alias='com_udfchar11') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR12'], type='varchar', alias='com_udfchar12') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR13'], type='varchar', alias='com_udfchar13') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR14'], type='varchar', alias='com_udfchar14') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR15'], type='varchar', alias='com_udfchar15') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR16'], type='varchar', alias='com_udfchar16') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR17'], type='varchar', alias='com_udfchar17') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR18'], type='varchar', alias='com_udfchar18') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR19'], type='varchar', alias='com_udfchar19') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR20'], type='varchar', alias='com_udfchar20') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR21'], type='varchar', alias='com_udfchar21') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR22'], type='varchar', alias='com_udfchar22') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR23'], type='varchar', alias='com_udfchar23') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR24'], type='varchar', alias='com_udfchar24') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR25'], type='varchar', alias='com_udfchar25') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR26'], type='varchar', alias='com_udfchar26') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR27'], type='varchar', alias='com_udfchar27') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR28'], type='varchar', alias='com_udfchar28') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR29'], type='varchar', alias='com_udfchar29') }},
        {{ trx_json_extract('src', ['COM_UDFCHAR30'], type='varchar', alias='com_udfchar30') }},
        {{ trx_json_extract('src', ['COM_UDFNUM01'], type='float', alias='com_udfnum01') }},
        {{ trx_json_extract('src', ['COM_UDFNUM02'], type='float', alias='com_udfnum02') }},
        {{ trx_json_extract('src', ['COM_UDFNUM03'], type='float', alias='com_udfnum03') }},
        {{ trx_json_extract('src', ['COM_UDFNUM04'], type='float', alias='com_udfnum04') }},
        {{ trx_json_extract('src', ['COM_UDFNUM05'], type='float', alias='com_udfnum05') }},
        {{ trx_json_extract('src', ['COM_UDFDATE01'], type='timestamp_ntz', alias='com_udfdate01') }},
        {{ trx_json_extract('src', ['COM_UDFDATE02'], type='timestamp_ntz', alias='com_udfdate02') }},
        {{ trx_json_extract('src', ['COM_UDFDATE03'], type='timestamp_ntz', alias='com_udfdate03') }},
        {{ trx_json_extract('src', ['COM_UDFDATE04'], type='timestamp_ntz', alias='com_udfdate04') }},
        {{ trx_json_extract('src', ['COM_UDFDATE05'], type='timestamp_ntz', alias='com_udfdate05') }},
        {{ trx_json_extract('src', ['COM_UDFCHKBOX01'], type='varchar', alias='com_udfchkbox01') }},
        {{ trx_json_extract('src', ['COM_UDFCHKBOX02'], type='varchar', alias='com_udfchkbox02') }},
        {{ trx_json_extract('src', ['COM_UDFCHKBOX03'], type='varchar', alias='com_udfchkbox03') }},
        {{ trx_json_extract('src', ['COM_UDFCHKBOX04'], type='varchar', alias='com_udfchkbox04') }},
        {{ trx_json_extract('src', ['COM_COSTCENTER'], type='varchar', alias='com_costcenter') }},
        {{ trx_json_extract('src', ['COM_UDFCHKBOX05'], type='varchar', alias='com_udfchkbox05') }},
        {{ trx_json_extract('src', ['COM_CUSTOMER'], type='varchar', alias='com_customer') }},
        {{ trx_json_extract('src', ['COM_ACCOUNTCODE'], type='varchar', alias='com_accountcode') }},
        {{ trx_json_extract('src', ['COM_TAX'], type='varchar', alias='com_tax') }},
        {{ trx_json_extract('src', ['COM_GROUPPURCHASINGORG1'], type='varchar', alias='com_grouppurchasingorg1') }},
        {{ trx_json_extract('src', ['COM_GROUPPURCHASINGORG2'], type='varchar', alias='com_grouppurchasingorg2') }},
        {{ trx_json_extract('src', ['_DELETED'], type='boolean', alias='_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_eam', 'eam_r5companies') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['com_code', 'com_org']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['com_lastsaved']) }}
