{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='eam_R5DOCKLINES',
    tags=['auto-generated', 'eam', 'stage1']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['DKL_LASTSAVED'], type='timestamp_ntz', alias='dkl_lastsaved') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR01'], type='varchar', alias='dkl_udfchar01') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR02'], type='varchar', alias='dkl_udfchar02') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR03'], type='varchar', alias='dkl_udfchar03') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR04'], type='varchar', alias='dkl_udfchar04') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR05'], type='varchar', alias='dkl_udfchar05') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR06'], type='varchar', alias='dkl_udfchar06') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR07'], type='varchar', alias='dkl_udfchar07') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR08'], type='varchar', alias='dkl_udfchar08') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR09'], type='varchar', alias='dkl_udfchar09') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR10'], type='varchar', alias='dkl_udfchar10') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR11'], type='varchar', alias='dkl_udfchar11') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR12'], type='varchar', alias='dkl_udfchar12') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR13'], type='varchar', alias='dkl_udfchar13') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR14'], type='varchar', alias='dkl_udfchar14') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR15'], type='varchar', alias='dkl_udfchar15') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR16'], type='varchar', alias='dkl_udfchar16') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR17'], type='varchar', alias='dkl_udfchar17') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR18'], type='varchar', alias='dkl_udfchar18') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR19'], type='varchar', alias='dkl_udfchar19') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR20'], type='varchar', alias='dkl_udfchar20') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR21'], type='varchar', alias='dkl_udfchar21') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR22'], type='varchar', alias='dkl_udfchar22') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR23'], type='varchar', alias='dkl_udfchar23') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR24'], type='varchar', alias='dkl_udfchar24') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR25'], type='varchar', alias='dkl_udfchar25') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR26'], type='varchar', alias='dkl_udfchar26') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR27'], type='varchar', alias='dkl_udfchar27') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR28'], type='varchar', alias='dkl_udfchar28') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR29'], type='varchar', alias='dkl_udfchar29') }},
        {{ trx_json_extract('src', ['DKL_UDFCHAR30'], type='varchar', alias='dkl_udfchar30') }},
        {{ trx_json_extract('src', ['DKL_UDFNUM01'], type='float', alias='dkl_udfnum01') }},
        {{ trx_json_extract('src', ['DKL_UDFNUM02'], type='float', alias='dkl_udfnum02') }},
        {{ trx_json_extract('src', ['DKL_UDFNUM03'], type='float', alias='dkl_udfnum03') }},
        {{ trx_json_extract('src', ['DKL_UDFNUM04'], type='float', alias='dkl_udfnum04') }},
        {{ trx_json_extract('src', ['DKL_UDFNUM05'], type='float', alias='dkl_udfnum05') }},
        {{ trx_json_extract('src', ['DKL_UDFDATE01'], type='timestamp_ntz', alias='dkl_udfdate01') }},
        {{ trx_json_extract('src', ['DKL_UDFDATE02'], type='timestamp_ntz', alias='dkl_udfdate02') }},
        {{ trx_json_extract('src', ['DKL_UDFDATE03'], type='timestamp_ntz', alias='dkl_udfdate03') }},
        {{ trx_json_extract('src', ['DKL_UDFDATE04'], type='timestamp_ntz', alias='dkl_udfdate04') }},
        {{ trx_json_extract('src', ['DKL_UDFDATE05'], type='timestamp_ntz', alias='dkl_udfdate05') }},
        {{ trx_json_extract('src', ['DKL_UDFCHKBOX01'], type='varchar', alias='dkl_udfchkbox01') }},
        {{ trx_json_extract('src', ['DKL_UDFCHKBOX02'], type='varchar', alias='dkl_udfchkbox02') }},
        {{ trx_json_extract('src', ['DKL_UDFCHKBOX03'], type='varchar', alias='dkl_udfchkbox03') }},
        {{ trx_json_extract('src', ['DKL_UDFCHKBOX04'], type='varchar', alias='dkl_udfchkbox04') }},
        {{ trx_json_extract('src', ['DKL_UDFCHKBOX05'], type='varchar', alias='dkl_udfchkbox05') }},
        {{ trx_json_extract('src', ['DKL_REPAIRCONDITION'], type='varchar', alias='dkl_repaircondition') }},
        {{ trx_json_extract('src', ['DKL_MOBILEDATEUPDATED'], type='timestamp_ntz', alias='dkl_mobiledateupdated') }},
        {{ trx_json_extract('src', ['DKL_MANUFACTPART'], type='varchar', alias='dkl_manufactpart') }},
        {{ trx_json_extract('src', ['DKL_INSPECT'], type='varchar', alias='dkl_inspect') }},
        {{ trx_json_extract('src', ['DKL_RETNCODE'], type='varchar', alias='dkl_retncode') }},
        {{ trx_json_extract('src', ['DKL_CLASS'], type='varchar', alias='dkl_class') }},
        {{ trx_json_extract('src', ['DKL_CLASS_ORG'], type='varchar', alias='dkl_class_org') }},
        {{ trx_json_extract('src', ['DKL_SCRAPQTY'], type='float', alias='dkl_scrapqty') }},
        {{ trx_json_extract('src', ['DKL_ACD'], type='float', alias='dkl_acd') }},
        {{ trx_json_extract('src', ['DKL_UPDATECOUNT'], type='float', alias='dkl_updatecount') }},
        {{ trx_json_extract('src', ['DKL_REPAIRPRICE'], type='float', alias='dkl_repairprice') }},
        {{ trx_json_extract('src', ['DKL_PERSON'], type='varchar', alias='dkl_person') }},
        {{ trx_json_extract('src', ['DKL_MANUFACTURER'], type='varchar', alias='dkl_manufacturer') }},
        {{ trx_json_extract('src', ['DKL_LINE'], type='float', alias='dkl_line') }},
        {{ trx_json_extract('src', ['DKL_ORDER'], type='varchar', alias='dkl_order') }},
        {{ trx_json_extract('src', ['DKL_ORDLINE'], type='float', alias='dkl_ordline') }},
        {{ trx_json_extract('src', ['DKL_ORDER_ORG'], type='varchar', alias='dkl_order_org') }},
        {{ trx_json_extract('src', ['DKL_PART'], type='varchar', alias='dkl_part') }},
        {{ trx_json_extract('src', ['DKL_PART_ORG'], type='varchar', alias='dkl_part_org') }},
        {{ trx_json_extract('src', ['DKL_LOCATION'], type='varchar', alias='dkl_location') }},
        {{ trx_json_extract('src', ['DKL_INSPSTATUS'], type='varchar', alias='dkl_inspstatus') }},
        {{ trx_json_extract('src', ['DKL_INSPRSTATUS'], type='varchar', alias='dkl_insprstatus') }},
        {{ trx_json_extract('src', ['DKL_LINESTATUS'], type='varchar', alias='dkl_linestatus') }},
        {{ trx_json_extract('src', ['DKL_LINERSTATUS'], type='varchar', alias='dkl_linerstatus') }},
        {{ trx_json_extract('src', ['DKL_COUNTED'], type='varchar', alias='dkl_counted') }},
        {{ trx_json_extract('src', ['DKL_RECVQTY'], type='float', alias='dkl_recvqty') }},
        {{ trx_json_extract('src', ['DKL_COUNTQTY'], type='float', alias='dkl_countqty') }},
        {{ trx_json_extract('src', ['DKL_PRINT'], type='float', alias='dkl_print') }},
        {{ trx_json_extract('src', ['DKL_INSPECTEDQTY'], type='float', alias='dkl_inspectedqty') }},
        {{ trx_json_extract('src', ['DKL_INSPREJQTY'], type='float', alias='dkl_insprejqty') }},
        {{ trx_json_extract('src', ['DKL_REJREASON'], type='varchar', alias='dkl_rejreason') }},
        {{ trx_json_extract('src', ['DKL_INSPECTOR'], type='varchar', alias='dkl_inspector') }},
        {{ trx_json_extract('src', ['DKL_INSPDATE'], type='timestamp_ntz', alias='dkl_inspdate') }},
        {{ trx_json_extract('src', ['DKL_UPDUSER'], type='varchar', alias='dkl_upduser') }},
        {{ trx_json_extract('src', ['DKL_UPDATED'], type='timestamp_ntz', alias='dkl_updated') }},
        {{ trx_json_extract('src', ['DKL_RETNQTY'], type='float', alias='dkl_retnqty') }},
        {{ trx_json_extract('src', ['DKL_BIN'], type='varchar', alias='dkl_bin') }},
        {{ trx_json_extract('src', ['DKL_LOT'], type='varchar', alias='dkl_lot') }},
        {{ trx_json_extract('src', ['DKL_MANLOT'], type='varchar', alias='dkl_manlot') }},
        {{ trx_json_extract('src', ['DKL_MANLOTEXP'], type='timestamp_ntz', alias='dkl_manlotexp') }},
        {{ trx_json_extract('src', ['DKL_DIRECT'], type='varchar', alias='dkl_direct') }},
        {{ trx_json_extract('src', ['DKL_OBTYPE'], type='varchar', alias='dkl_obtype') }},
        {{ trx_json_extract('src', ['DKL_OBRTYPE'], type='varchar', alias='dkl_obrtype') }},
        {{ trx_json_extract('src', ['DKL_OBJECT'], type='varchar', alias='dkl_object') }},
        {{ trx_json_extract('src', ['DKL_DCKCODE'], type='varchar', alias='dkl_dckcode') }},
        {{ trx_json_extract('src', ['DKL_OBJECT_ORG'], type='varchar', alias='dkl_object_org') }},
        {{ trx_json_extract('src', ['DKL_SERIAL'], type='varchar', alias='dkl_serial') }},
        {{ trx_json_extract('src', ['DKL_MRC'], type='varchar', alias='dkl_mrc') }},
        {{ trx_json_extract('src', ['DKL_RECVCODE'], type='varchar', alias='dkl_recvcode') }},
        {{ trx_json_extract('src', ['_DELETED'], type='boolean', alias='_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_eam', 'eam_r5docklines') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['dkl_dckcode', 'dkl_line']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['dkl_lastsaved']) }}
