{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='eam_R5STANDWORKS',
    tags=['auto-generated', 'eam', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['STW_LASTSAVED'], type='timestamp_ntz', alias='stw_lastsaved') }},
        {{ trx_json_extract('src', ['STW_CODE'], type='varchar', alias='stw_code') }},
        {{ trx_json_extract('src', ['STW_DESC'], type='varchar', alias='stw_desc') }},
        {{ trx_json_extract('src', ['STW_CLASS'], type='varchar', alias='stw_class') }},
        {{ trx_json_extract('src', ['STW_OBCLASS'], type='varchar', alias='stw_obclass') }},
        {{ trx_json_extract('src', ['STW_DURATION'], type='float', alias='stw_duration') }},
        {{ trx_json_extract('src', ['STW_JOBTYPE'], type='varchar', alias='stw_jobtype') }},
        {{ trx_json_extract('src', ['STW_PRIORITY'], type='varchar', alias='stw_priority') }},
        {{ trx_json_extract('src', ['STW_OBTYPE'], type='varchar', alias='stw_obtype') }},
        {{ trx_json_extract('src', ['STW_OBRTYPE'], type='varchar', alias='stw_obrtype') }},
        {{ trx_json_extract('src', ['STW_OBJECT'], type='varchar', alias='stw_object') }},
        {{ trx_json_extract('src', ['STW_REQM'], type='varchar', alias='stw_reqm') }},
        {{ trx_json_extract('src', ['STW_ORG'], type='varchar', alias='stw_org') }},
        {{ trx_json_extract('src', ['STW_CLASS_ORG'], type='varchar', alias='stw_class_org') }},
        {{ trx_json_extract('src', ['STW_OBCLASS_ORG'], type='varchar', alias='stw_obclass_org') }},
        {{ trx_json_extract('src', ['STW_OBJECT_ORG'], type='varchar', alias='stw_object_org') }},
        {{ trx_json_extract('src', ['STW_CREATED'], type='timestamp_ntz', alias='stw_created') }},
        {{ trx_json_extract('src', ['STW_CREATEDBY'], type='varchar', alias='stw_createdby') }},
        {{ trx_json_extract('src', ['STW_UPDATED'], type='timestamp_ntz', alias='stw_updated') }},
        {{ trx_json_extract('src', ['STW_UPDATEDBY'], type='varchar', alias='stw_updatedby') }},
        {{ trx_json_extract('src', ['STW_WOCLASS'], type='varchar', alias='stw_woclass') }},
        {{ trx_json_extract('src', ['STW_WOCLASS_ORG'], type='varchar', alias='stw_woclass_org') }},
        {{ trx_json_extract('src', ['STW_UPDATECOUNT'], type='float', alias='stw_updatecount') }},
        {{ trx_json_extract('src', ['STW_NOTUSED'], type='varchar', alias='stw_notused') }},
        {{ trx_json_extract('src', ['STW_TYPE'], type='varchar', alias='stw_type') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR01'], type='varchar', alias='stw_udfchar01') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR02'], type='varchar', alias='stw_udfchar02') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR03'], type='varchar', alias='stw_udfchar03') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR04'], type='varchar', alias='stw_udfchar04') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR05'], type='varchar', alias='stw_udfchar05') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR06'], type='varchar', alias='stw_udfchar06') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR07'], type='varchar', alias='stw_udfchar07') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR08'], type='varchar', alias='stw_udfchar08') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR09'], type='varchar', alias='stw_udfchar09') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR10'], type='varchar', alias='stw_udfchar10') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR11'], type='varchar', alias='stw_udfchar11') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR12'], type='varchar', alias='stw_udfchar12') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR13'], type='varchar', alias='stw_udfchar13') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR14'], type='varchar', alias='stw_udfchar14') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR15'], type='varchar', alias='stw_udfchar15') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR16'], type='varchar', alias='stw_udfchar16') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR17'], type='varchar', alias='stw_udfchar17') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR18'], type='varchar', alias='stw_udfchar18') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR19'], type='varchar', alias='stw_udfchar19') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR20'], type='varchar', alias='stw_udfchar20') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR21'], type='varchar', alias='stw_udfchar21') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR22'], type='varchar', alias='stw_udfchar22') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR23'], type='varchar', alias='stw_udfchar23') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR24'], type='varchar', alias='stw_udfchar24') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR25'], type='varchar', alias='stw_udfchar25') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR26'], type='varchar', alias='stw_udfchar26') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR27'], type='varchar', alias='stw_udfchar27') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR28'], type='varchar', alias='stw_udfchar28') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR29'], type='varchar', alias='stw_udfchar29') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR30'], type='varchar', alias='stw_udfchar30') }},
        {{ trx_json_extract('src', ['STW_UDFNUM01'], type='float', alias='stw_udfnum01') }},
        {{ trx_json_extract('src', ['STW_UDFNUM02'], type='float', alias='stw_udfnum02') }},
        {{ trx_json_extract('src', ['STW_UDFNUM03'], type='float', alias='stw_udfnum03') }},
        {{ trx_json_extract('src', ['STW_UDFNUM04'], type='float', alias='stw_udfnum04') }},
        {{ trx_json_extract('src', ['STW_UDFNUM05'], type='float', alias='stw_udfnum05') }},
        {{ trx_json_extract('src', ['STW_UDFDATE01'], type='timestamp_ntz', alias='stw_udfdate01') }},
        {{ trx_json_extract('src', ['STW_UDFDATE02'], type='timestamp_ntz', alias='stw_udfdate02') }},
        {{ trx_json_extract('src', ['STW_UDFDATE03'], type='timestamp_ntz', alias='stw_udfdate03') }},
        {{ trx_json_extract('src', ['STW_UDFDATE04'], type='timestamp_ntz', alias='stw_udfdate04') }},
        {{ trx_json_extract('src', ['STW_UDFDATE05'], type='timestamp_ntz', alias='stw_udfdate05') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX01'], type='varchar', alias='stw_udfchkbox01') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX02'], type='varchar', alias='stw_udfchkbox02') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX03'], type='varchar', alias='stw_udfchkbox03') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX04'], type='varchar', alias='stw_udfchkbox04') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX05'], type='varchar', alias='stw_udfchkbox05') }},
        {{ trx_json_extract('src', ['STW_SAFETYREVIEWREQUIRED'], type='timestamp_ntz', alias='stw_safetyreviewrequired') }},
        {{ trx_json_extract('src', ['STW_SAFETYREVIEWED'], type='timestamp_ntz', alias='stw_safetyreviewed') }},
        {{ trx_json_extract('src', ['STW_PERMITREVIEWREQUIRED'], type='timestamp_ntz', alias='stw_permitreviewrequired') }},
        {{ trx_json_extract('src', ['STW_SAFETYREVIEWEDBY'], type='varchar', alias='stw_safetyreviewedby') }},
        {{ trx_json_extract('src', ['STW_SAFETYREVIEWEDNAME'], type='varchar', alias='stw_safetyreviewedname') }},
        {{ trx_json_extract('src', ['STW_SAFETYREVIEWEDTYPE'], type='varchar', alias='stw_safetyreviewedtype') }},
        {{ trx_json_extract('src', ['STW_PERMITREVIEWED'], type='timestamp_ntz', alias='stw_permitreviewed') }},
        {{ trx_json_extract('src', ['STW_PERMITREVIEWEDBY'], type='varchar', alias='stw_permitreviewedby') }},
        {{ trx_json_extract('src', ['STW_PERMITREVIEWEDNAME'], type='varchar', alias='stw_permitreviewedname') }},
        {{ trx_json_extract('src', ['STW_PERMITREVIEWEDTYPE'], type='varchar', alias='stw_permitreviewedtype') }},
        {{ trx_json_extract('src', ['STW_UDFNOTE01'], type='varchar', alias='stw_udfnote01') }},
        {{ trx_json_extract('src', ['STW_UDFNOTE02'], type='varchar', alias='stw_udfnote02') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR31'], type='varchar', alias='stw_udfchar31') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR32'], type='varchar', alias='stw_udfchar32') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR33'], type='varchar', alias='stw_udfchar33') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR34'], type='varchar', alias='stw_udfchar34') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR35'], type='varchar', alias='stw_udfchar35') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR36'], type='varchar', alias='stw_udfchar36') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR37'], type='varchar', alias='stw_udfchar37') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR38'], type='varchar', alias='stw_udfchar38') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR39'], type='varchar', alias='stw_udfchar39') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR40'], type='varchar', alias='stw_udfchar40') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR41'], type='varchar', alias='stw_udfchar41') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR42'], type='varchar', alias='stw_udfchar42') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR43'], type='varchar', alias='stw_udfchar43') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR44'], type='varchar', alias='stw_udfchar44') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR45'], type='varchar', alias='stw_udfchar45') }},
        {{ trx_json_extract('src', ['STW_UDFNUM06'], type='float', alias='stw_udfnum06') }},
        {{ trx_json_extract('src', ['STW_UDFNUM07'], type='float', alias='stw_udfnum07') }},
        {{ trx_json_extract('src', ['STW_UDFNUM08'], type='float', alias='stw_udfnum08') }},
        {{ trx_json_extract('src', ['STW_UDFNUM09'], type='float', alias='stw_udfnum09') }},
        {{ trx_json_extract('src', ['STW_UDFNUM10'], type='float', alias='stw_udfnum10') }},
        {{ trx_json_extract('src', ['STW_UDFDATE06'], type='timestamp_ntz', alias='stw_udfdate06') }},
        {{ trx_json_extract('src', ['STW_UDFDATE07'], type='timestamp_ntz', alias='stw_udfdate07') }},
        {{ trx_json_extract('src', ['STW_UDFDATE08'], type='timestamp_ntz', alias='stw_udfdate08') }},
        {{ trx_json_extract('src', ['STW_UDFDATE09'], type='timestamp_ntz', alias='stw_udfdate09') }},
        {{ trx_json_extract('src', ['STW_UDFDATE10'], type='timestamp_ntz', alias='stw_udfdate10') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX06'], type='varchar', alias='stw_udfchkbox06') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX07'], type='varchar', alias='stw_udfchkbox07') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX08'], type='varchar', alias='stw_udfchkbox08') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX09'], type='varchar', alias='stw_udfchkbox09') }},
        {{ trx_json_extract('src', ['STW_UDFCHKBOX10'], type='varchar', alias='stw_udfchkbox10') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR46'], type='varchar', alias='stw_udfchar46') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR47'], type='varchar', alias='stw_udfchar47') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR48'], type='varchar', alias='stw_udfchar48') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR49'], type='varchar', alias='stw_udfchar49') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR50'], type='varchar', alias='stw_udfchar50') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR51'], type='varchar', alias='stw_udfchar51') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR52'], type='varchar', alias='stw_udfchar52') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR53'], type='varchar', alias='stw_udfchar53') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR54'], type='varchar', alias='stw_udfchar54') }},
        {{ trx_json_extract('src', ['STW_UDFCHAR55'], type='varchar', alias='stw_udfchar55') }},
        {{ trx_json_extract('src', ['_DELETED'], type='boolean', alias='_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_eam', 'eam_r5standworks') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['stw_code']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['stw_lastsaved']) }}
