{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='eam_R5TRANSLINES',
    tags=['auto-generated', 'eam', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['TRL_LASTSAVED'], type='timestamp_ntz', alias='trl_lastsaved') }},
        {{ trx_json_extract('src', ['TRL_TRANS'], type='varchar', alias='trl_trans') }},
        {{ trx_json_extract('src', ['TRL_TYPE'], type='varchar', alias='trl_type') }},
        {{ trx_json_extract('src', ['TRL_RTYPE'], type='varchar', alias='trl_rtype') }},
        {{ trx_json_extract('src', ['TRL_LINE'], type='float', alias='trl_line') }},
        {{ trx_json_extract('src', ['TRL_DATE'], type='timestamp_ntz', alias='trl_date') }},
        {{ trx_json_extract('src', ['TRL_COSTCODE'], type='varchar', alias='trl_costcode') }},
        {{ trx_json_extract('src', ['TRL_PROJECT'], type='varchar', alias='trl_project') }},
        {{ trx_json_extract('src', ['TRL_PROJBUD'], type='varchar', alias='trl_projbud') }},
        {{ trx_json_extract('src', ['TRL_EVENT'], type='varchar', alias='trl_event') }},
        {{ trx_json_extract('src', ['TRL_ACT'], type='float', alias='trl_act') }},
        {{ trx_json_extract('src', ['TRL_PART'], type='varchar', alias='trl_part') }},
        {{ trx_json_extract('src', ['TRL_ORDLINE'], type='float', alias='trl_ordline') }},
        {{ trx_json_extract('src', ['TRL_REQLINE'], type='float', alias='trl_reqline') }},
        {{ trx_json_extract('src', ['TRL_OBTYPE'], type='varchar', alias='trl_obtype') }},
        {{ trx_json_extract('src', ['TRL_OBRTYPE'], type='varchar', alias='trl_obrtype') }},
        {{ trx_json_extract('src', ['TRL_OBJECT'], type='varchar', alias='trl_object') }},
        {{ trx_json_extract('src', ['TRL_LOT'], type='varchar', alias='trl_lot') }},
        {{ trx_json_extract('src', ['TRL_BIN'], type='varchar', alias='trl_bin') }},
        {{ trx_json_extract('src', ['TRL_STORE'], type='varchar', alias='trl_store') }},
        {{ trx_json_extract('src', ['TRL_PRICE'], type='float', alias='trl_price') }},
        {{ trx_json_extract('src', ['TRL_QTY'], type='float', alias='trl_qty') }},
        {{ trx_json_extract('src', ['TRL_STOCKPRICE'], type='float', alias='trl_stockprice') }},
        {{ trx_json_extract('src', ['TRL_ORDER'], type='varchar', alias='trl_order') }},
        {{ trx_json_extract('src', ['TRL_REQ'], type='varchar', alias='trl_req') }},
        {{ trx_json_extract('src', ['TRL_MULTIPLY'], type='float', alias='trl_multiply') }},
        {{ trx_json_extract('src', ['TRL_IO'], type='float', alias='trl_io') }},
        {{ trx_json_extract('src', ['TRL_ACD'], type='float', alias='trl_acd') }},
        {{ trx_json_extract('src', ['TRL_GLTRANSFERFLAG'], type='varchar', alias='trl_gltransferflag') }},
        {{ trx_json_extract('src', ['TRL_GLTRANSFER'], type='timestamp_ntz', alias='trl_gltransfer') }},
        {{ trx_json_extract('src', ['TRL_INTERFACE'], type='timestamp_ntz', alias='trl_interface') }},
        {{ trx_json_extract('src', ['TRL_SOURCESYSTEM'], type='varchar', alias='trl_sourcesystem') }},
        {{ trx_json_extract('src', ['TRL_SOURCECODE'], type='varchar', alias='trl_sourcecode') }},
        {{ trx_json_extract('src', ['TRL_CONSIGNMENT'], type='varchar', alias='trl_consignment') }},
        {{ trx_json_extract('src', ['TRL_CONSIGNSUPPLIER'], type='varchar', alias='trl_consignsupplier') }},
        {{ trx_json_extract('src', ['TRL_REJECTREASON'], type='varchar', alias='trl_rejectreason') }},
        {{ trx_json_extract('src', ['TRL_TRANSORGID'], type='float', alias='trl_transorgid') }},
        {{ trx_json_extract('src', ['TRL_TRANSCODE'], type='varchar', alias='trl_transcode') }},
        {{ trx_json_extract('src', ['TRL_TRANSGROUP'], type='float', alias='trl_transgroup') }},
        {{ trx_json_extract('src', ['TRL_WARRANTY'], type='varchar', alias='trl_warranty') }},
        {{ trx_json_extract('src', ['TRL_OBJECT_ORG'], type='varchar', alias='trl_object_org') }},
        {{ trx_json_extract('src', ['TRL_CONSIGNSUPPLIER_ORG'], type='varchar', alias='trl_consignsupplier_org') }},
        {{ trx_json_extract('src', ['TRL_ORDER_ORG'], type='varchar', alias='trl_order_org') }},
        {{ trx_json_extract('src', ['TRL_PART_ORG'], type='varchar', alias='trl_part_org') }},
        {{ trx_json_extract('src', ['TRL_PICKLIST'], type='varchar', alias='trl_picklist') }},
        {{ trx_json_extract('src', ['TRL_DCKCODE'], type='varchar', alias='trl_dckcode') }},
        {{ trx_json_extract('src', ['TRL_DCKLINE'], type='float', alias='trl_dckline') }},
        {{ trx_json_extract('src', ['TRL_ALLOCATE'], type='varchar', alias='trl_allocate') }},
        {{ trx_json_extract('src', ['TRL_REPAIRPRICE'], type='float', alias='trl_repairprice') }},
        {{ trx_json_extract('src', ['TRL_SCRAPQTY'], type='float', alias='trl_scrapqty') }},
        {{ trx_json_extract('src', ['TRL_EVTALIAS'], type='varchar', alias='trl_evtalias') }},
        {{ trx_json_extract('src', ['TRL_PRINTQTY'], type='float', alias='trl_printqty') }},
        {{ trx_json_extract('src', ['TRL_PRICEUPDATE'], type='varchar', alias='trl_priceupdate') }},
        {{ trx_json_extract('src', ['TRL_UPDATECOUNT'], type='float', alias='trl_updatecount') }},
        {{ trx_json_extract('src', ['TRL_ORIGQTY'], type='float', alias='trl_origqty') }},
        {{ trx_json_extract('src', ['TRL_ROUTEREC'], type='varchar', alias='trl_routerec') }},
        {{ trx_json_extract('src', ['TRL_CREATED'], type='timestamp_ntz', alias='trl_created') }},
        {{ trx_json_extract('src', ['TRL_UPDATED'], type='timestamp_ntz', alias='trl_updated') }},
        {{ trx_json_extract('src', ['TRL_NEWMRC'], type='varchar', alias='trl_newmrc') }},
        {{ trx_json_extract('src', ['TRL_NEWCOSTCODE'], type='varchar', alias='trl_newcostcode') }},
        {{ trx_json_extract('src', ['TRL_NEWMANUFACT'], type='varchar', alias='trl_newmanufact') }},
        {{ trx_json_extract('src', ['TRL_AVGPRICE'], type='float', alias='trl_avgprice') }},
        {{ trx_json_extract('src', ['TRL_JECATEGORY'], type='varchar', alias='trl_jecategory') }},
        {{ trx_json_extract('src', ['TRL_JESOURCE'], type='varchar', alias='trl_jesource') }},
        {{ trx_json_extract('src', ['TRL_BILLSUBLINE'], type='varchar', alias='trl_billsubline') }},
        {{ trx_json_extract('src', ['TRL_FLEETCHECKED'], type='varchar', alias='trl_fleetchecked') }},
        {{ trx_json_extract('src', ['TRL_FLEETMARKUP'], type='float', alias='trl_fleetmarkup') }},
        {{ trx_json_extract('src', ['TRL_SPLITTRANS'], type='varchar', alias='trl_splittrans') }},
        {{ trx_json_extract('src', ['TRL_DESC'], type='varchar', alias='trl_desc') }},
        {{ trx_json_extract('src', ['TRL_ATTACHTO'], type='varchar', alias='trl_attachto') }},
        {{ trx_json_extract('src', ['TRL_ATTACHTO_ORG'], type='varchar', alias='trl_attachto_org') }},
        {{ trx_json_extract('src', ['TRL_ATTACH'], type='varchar', alias='trl_attach') }},
        {{ trx_json_extract('src', ['TRL_SCRAPOBJECT'], type='varchar', alias='trl_scrapobject') }},
        {{ trx_json_extract('src', ['TRL_SCRAPOBJECT_ORG'], type='varchar', alias='trl_scrapobject_org') }},
        {{ trx_json_extract('src', ['TRL_MANUFACTURER'], type='varchar', alias='trl_manufacturer') }},
        {{ trx_json_extract('src', ['TRL_MANUFACTPART'], type='varchar', alias='trl_manufactpart') }},
        {{ trx_json_extract('src', ['TRL_LEAK'], type='varchar', alias='trl_leak') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR01'], type='varchar', alias='trl_udfchar01') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR02'], type='varchar', alias='trl_udfchar02') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR03'], type='varchar', alias='trl_udfchar03') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR04'], type='varchar', alias='trl_udfchar04') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR05'], type='varchar', alias='trl_udfchar05') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR06'], type='varchar', alias='trl_udfchar06') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR07'], type='varchar', alias='trl_udfchar07') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR08'], type='varchar', alias='trl_udfchar08') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR09'], type='varchar', alias='trl_udfchar09') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR10'], type='varchar', alias='trl_udfchar10') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR11'], type='varchar', alias='trl_udfchar11') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR12'], type='varchar', alias='trl_udfchar12') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR14'], type='varchar', alias='trl_udfchar14') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR15'], type='varchar', alias='trl_udfchar15') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR16'], type='varchar', alias='trl_udfchar16') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR17'], type='varchar', alias='trl_udfchar17') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR18'], type='varchar', alias='trl_udfchar18') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR19'], type='varchar', alias='trl_udfchar19') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR20'], type='varchar', alias='trl_udfchar20') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR21'], type='varchar', alias='trl_udfchar21') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR22'], type='varchar', alias='trl_udfchar22') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR23'], type='varchar', alias='trl_udfchar23') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR24'], type='varchar', alias='trl_udfchar24') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR25'], type='varchar', alias='trl_udfchar25') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR26'], type='varchar', alias='trl_udfchar26') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR27'], type='varchar', alias='trl_udfchar27') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR28'], type='varchar', alias='trl_udfchar28') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR29'], type='varchar', alias='trl_udfchar29') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR30'], type='varchar', alias='trl_udfchar30') }},
        {{ trx_json_extract('src', ['TRL_UDFNUM01'], type='float', alias='trl_udfnum01') }},
        {{ trx_json_extract('src', ['TRL_UDFNUM02'], type='float', alias='trl_udfnum02') }},
        {{ trx_json_extract('src', ['TRL_UDFNUM03'], type='float', alias='trl_udfnum03') }},
        {{ trx_json_extract('src', ['TRL_UDFNUM04'], type='float', alias='trl_udfnum04') }},
        {{ trx_json_extract('src', ['TRL_UDFNUM05'], type='float', alias='trl_udfnum05') }},
        {{ trx_json_extract('src', ['TRL_UDFDATE01'], type='timestamp_ntz', alias='trl_udfdate01') }},
        {{ trx_json_extract('src', ['TRL_UDFDATE02'], type='timestamp_ntz', alias='trl_udfdate02') }},
        {{ trx_json_extract('src', ['TRL_UDFDATE03'], type='timestamp_ntz', alias='trl_udfdate03') }},
        {{ trx_json_extract('src', ['TRL_UDFDATE04'], type='timestamp_ntz', alias='trl_udfdate04') }},
        {{ trx_json_extract('src', ['TRL_UDFDATE05'], type='timestamp_ntz', alias='trl_udfdate05') }},
        {{ trx_json_extract('src', ['TRL_UDFCHKBOX01'], type='varchar', alias='trl_udfchkbox01') }},
        {{ trx_json_extract('src', ['TRL_UDFCHKBOX02'], type='varchar', alias='trl_udfchkbox02') }},
        {{ trx_json_extract('src', ['TRL_UDFCHKBOX03'], type='varchar', alias='trl_udfchkbox03') }},
        {{ trx_json_extract('src', ['TRL_UDFCHKBOX04'], type='varchar', alias='trl_udfchkbox04') }},
        {{ trx_json_extract('src', ['TRL_UDFCHKBOX05'], type='varchar', alias='trl_udfchkbox05') }},
        {{ trx_json_extract('src', ['TRL_INVOICE'], type='varchar', alias='trl_invoice') }},
        {{ trx_json_extract('src', ['TRL_INVOICE_ORG'], type='varchar', alias='trl_invoice_org') }},
        {{ trx_json_extract('src', ['TRL_INVOICE_REVISION'], type='float', alias='trl_invoice_revision') }},
        {{ trx_json_extract('src', ['TRL_INVOICELINE'], type='float', alias='trl_invoiceline') }},
        {{ trx_json_extract('src', ['TRL_ISSUEDPART'], type='varchar', alias='trl_issuedpart') }},
        {{ trx_json_extract('src', ['TRL_CORERETURNPRINTQTY'], type='float', alias='trl_corereturnprintqty') }},
        {{ trx_json_extract('src', ['TRL_POEXTRACHARGES'], type='float', alias='trl_poextracharges') }},
        {{ trx_json_extract('src', ['TRL_POTAXAMOUNT'], type='float', alias='trl_potaxamount') }},
        {{ trx_json_extract('src', ['TRL_PARTLOCATION'], type='varchar', alias='trl_partlocation') }},
        {{ trx_json_extract('src', ['TRL_SUPPLIER'], type='varchar', alias='trl_supplier') }},
        {{ trx_json_extract('src', ['TRL_SUPPLIER_ORG'], type='varchar', alias='trl_supplier_org') }},
        {{ trx_json_extract('src', ['TRL_PACKAGE'], type='varchar', alias='trl_package') }},
        {{ trx_json_extract('src', ['TRL_HELDITEM'], type='varchar', alias='trl_helditem') }},
        {{ trx_json_extract('src', ['TRL_CALOTHERCOST'], type='float', alias='trl_calothercost') }},
        {{ trx_json_extract('src', ['TRL_TAXJURISDICTION'], type='varchar', alias='trl_taxjurisdiction') }},
        {{ trx_json_extract('src', ['TRL_STOCKTAKE'], type='varchar', alias='trl_stocktake') }},
        {{ trx_json_extract('src', ['TRL_STOCKTAKEACTION'], type='varchar', alias='trl_stocktakeaction') }},
        {{ trx_json_extract('src', ['TRL_RECEIVEREQ'], type='varchar', alias='trl_receivereq') }},
        {{ trx_json_extract('src', ['TRL_UDFCHAR13'], type='varchar', alias='trl_udfchar13') }},
        {{ trx_json_extract('src', ['_DELETED'], type='boolean', alias='_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_eam', 'eam_r5translines') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['trl_trans', 'trl_line']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['trl_lastsaved']) }}
