{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='eam_R5USERS',
    tags=['auto-generated', 'eam', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['USR_LASTSAVED'], type='timestamp_ntz', alias='usr_lastsaved') }},
        {{ trx_json_extract('src', ['USR_CODE'], type='varchar', alias='usr_code') }},
        {{ trx_json_extract('src', ['USR_DESC'], type='varchar', alias='usr_desc') }},
        {{ trx_json_extract('src', ['USR_CLASS'], type='varchar', alias='usr_class') }},
        {{ trx_json_extract('src', ['USR_MRC'], type='varchar', alias='usr_mrc') }},
        {{ trx_json_extract('src', ['USR_SYSMAN'], type='varchar', alias='usr_sysman') }},
        {{ trx_json_extract('src', ['USR_PASSWORD'], type='varchar', alias='usr_password') }},
        {{ trx_json_extract('src', ['USR_LASTFUNC'], type='varchar', alias='usr_lastfunc') }},
        {{ trx_json_extract('src', ['USR_FIRSTFUNC'], type='varchar', alias='usr_firstfunc') }},
        {{ trx_json_extract('src', ['USR_GROUP'], type='varchar', alias='usr_group') }},
        {{ trx_json_extract('src', ['USR_LANG'], type='varchar', alias='usr_lang') }},
        {{ trx_json_extract('src', ['USR_PRINTER'], type='varchar', alias='usr_printer') }},
        {{ trx_json_extract('src', ['USR_EXPPASS'], type='timestamp_ntz', alias='usr_exppass') }},
        {{ trx_json_extract('src', ['USR_EXPUSER'], type='timestamp_ntz', alias='usr_expuser') }},
        {{ trx_json_extract('src', ['USR_FACILITY'], type='varchar', alias='usr_facility') }},
        {{ trx_json_extract('src', ['USR_REQAPPVLIMIT'], type='float', alias='usr_reqappvlimit') }},
        {{ trx_json_extract('src', ['USR_REQAUTHAPPVLIMIT'], type='float', alias='usr_reqauthappvlimit') }},
        {{ trx_json_extract('src', ['USR_BUYER'], type='varchar', alias='usr_buyer') }},
        {{ trx_json_extract('src', ['USR_PORDAPPVLIMIT'], type='float', alias='usr_pordappvlimit') }},
        {{ trx_json_extract('src', ['USR_PORDAUTHAPPVLIMIT'], type='float', alias='usr_pordauthappvlimit') }},
        {{ trx_json_extract('src', ['USR_ROUTER'], type='varchar', alias='usr_router') }},
        {{ trx_json_extract('src', ['USR_DATELOCKED'], type='timestamp_ntz', alias='usr_datelocked') }},
        {{ trx_json_extract('src', ['USR_VIOLATIONS'], type='float', alias='usr_violations') }},
        {{ trx_json_extract('src', ['USR_CLASS_ORG'], type='varchar', alias='usr_class_org') }},
        {{ trx_json_extract('src', ['USR_APPROVER'], type='varchar', alias='usr_approver') }},
        {{ trx_json_extract('src', ['USR_PICAPPVLIMIT'], type='float', alias='usr_picappvlimit') }},
        {{ trx_json_extract('src', ['USR_EMAILADDRESS'], type='varchar', alias='usr_emailaddress') }},
        {{ trx_json_extract('src', ['USR_NOTIFICATIONPREF'], type='varchar', alias='usr_notificationpref') }},
        {{ trx_json_extract('src', ['USR_BROWSER'], type='varchar', alias='usr_browser') }},
        {{ trx_json_extract('src', ['USR_INVAPPVLIMIT'], type='float', alias='usr_invappvlimit') }},
        {{ trx_json_extract('src', ['USR_INVAPPVLIMITNONPO'], type='float', alias='usr_invappvlimitnonpo') }},
        {{ trx_json_extract('src', ['USR_UPDATECOUNT'], type='float', alias='usr_updatecount') }},
        {{ trx_json_extract('src', ['USR_LOGIN'], type='varchar', alias='usr_login') }},
        {{ trx_json_extract('src', ['USR_REQUESTOR'], type='varchar', alias='usr_requestor') }},
        {{ trx_json_extract('src', ['USR_ACTIVE'], type='varchar', alias='usr_active') }},
        {{ trx_json_extract('src', ['USR_LOCALE'], type='varchar', alias='usr_locale') }},
        {{ trx_json_extract('src', ['USR_SUCCESSMSGTIMEOUT'], type='float', alias='usr_successmsgtimeout') }},
        {{ trx_json_extract('src', ['USR_EWSFIRSTFUNC'], type='varchar', alias='usr_ewsfirstfunc') }},
        {{ trx_json_extract('src', ['USR_CREATED'], type='timestamp_ntz', alias='usr_created') }},
        {{ trx_json_extract('src', ['USR_UPDATED'], type='timestamp_ntz', alias='usr_updated') }},
        {{ trx_json_extract('src', ['USR_INBOXTAB'], type='varchar', alias='usr_inboxtab') }},
        {{ trx_json_extract('src', ['USR_MOBILE'], type='varchar', alias='usr_mobile') }},
        {{ trx_json_extract('src', ['USR_CONNECTOR'], type='varchar', alias='usr_connector') }},
        {{ trx_json_extract('src', ['USR_BARCODE'], type='varchar', alias='usr_barcode') }},
        {{ trx_json_extract('src', ['USR_NOTUSED'], type='varchar', alias='usr_notused') }},
        {{ trx_json_extract('src', ['USR_SESSIONTIMEOUT'], type='float', alias='usr_sessiontimeout') }},
        {{ trx_json_extract('src', ['USR_ANALYTICS'], type='varchar', alias='usr_analytics') }},
        {{ trx_json_extract('src', ['USR_PROFESSIONAL'], type='varchar', alias='usr_professional') }},
        {{ trx_json_extract('src', ['USR_CONSUMER'], type='varchar', alias='usr_consumer') }},
        {{ trx_json_extract('src', ['USR_SCREENDESIGNER'], type='varchar', alias='usr_screendesigner') }},
        {{ trx_json_extract('src', ['USR_508'], type='varchar', alias='usr_508') }},
        {{ trx_json_extract('src', ['USR_MOBILEADM'], type='varchar', alias='usr_mobileadm') }},
        {{ trx_json_extract('src', ['USR_EDITDATASPY'], type='varchar', alias='usr_editdataspy') }},
        {{ trx_json_extract('src', ['USR_ADVANCEDFILTERS'], type='varchar', alias='usr_advancedfilters') }},
        {{ trx_json_extract('src', ['USR_EDITOWNCOMMENTS'], type='varchar', alias='usr_editowncomments') }},
        {{ trx_json_extract('src', ['USR_EDITOTHERSCOMMENTS'], type='varchar', alias='usr_editotherscomments') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR01'], type='varchar', alias='usr_udfchar01') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR02'], type='varchar', alias='usr_udfchar02') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR03'], type='varchar', alias='usr_udfchar03') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR04'], type='varchar', alias='usr_udfchar04') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR05'], type='varchar', alias='usr_udfchar05') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR06'], type='varchar', alias='usr_udfchar06') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR07'], type='varchar', alias='usr_udfchar07') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR08'], type='varchar', alias='usr_udfchar08') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR09'], type='varchar', alias='usr_udfchar09') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR10'], type='varchar', alias='usr_udfchar10') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR11'], type='varchar', alias='usr_udfchar11') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR12'], type='varchar', alias='usr_udfchar12') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR13'], type='varchar', alias='usr_udfchar13') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR14'], type='varchar', alias='usr_udfchar14') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR15'], type='varchar', alias='usr_udfchar15') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR16'], type='varchar', alias='usr_udfchar16') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR17'], type='varchar', alias='usr_udfchar17') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR18'], type='varchar', alias='usr_udfchar18') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR19'], type='varchar', alias='usr_udfchar19') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR20'], type='varchar', alias='usr_udfchar20') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR21'], type='varchar', alias='usr_udfchar21') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR22'], type='varchar', alias='usr_udfchar22') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR23'], type='varchar', alias='usr_udfchar23') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR24'], type='varchar', alias='usr_udfchar24') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR25'], type='varchar', alias='usr_udfchar25') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR26'], type='varchar', alias='usr_udfchar26') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR27'], type='varchar', alias='usr_udfchar27') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR28'], type='varchar', alias='usr_udfchar28') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR29'], type='varchar', alias='usr_udfchar29') }},
        {{ trx_json_extract('src', ['USR_UDFCHAR30'], type='varchar', alias='usr_udfchar30') }},
        {{ trx_json_extract('src', ['USR_UDFNUM01'], type='float', alias='usr_udfnum01') }},
        {{ trx_json_extract('src', ['USR_UDFNUM02'], type='float', alias='usr_udfnum02') }},
        {{ trx_json_extract('src', ['USR_UDFNUM03'], type='float', alias='usr_udfnum03') }},
        {{ trx_json_extract('src', ['USR_UDFNUM04'], type='float', alias='usr_udfnum04') }},
        {{ trx_json_extract('src', ['USR_UDFNUM05'], type='float', alias='usr_udfnum05') }},
        {{ trx_json_extract('src', ['USR_UDFDATE01'], type='timestamp_ntz', alias='usr_udfdate01') }},
        {{ trx_json_extract('src', ['USR_UDFDATE02'], type='timestamp_ntz', alias='usr_udfdate02') }},
        {{ trx_json_extract('src', ['USR_UDFDATE03'], type='timestamp_ntz', alias='usr_udfdate03') }},
        {{ trx_json_extract('src', ['USR_UDFDATE04'], type='timestamp_ntz', alias='usr_udfdate04') }},
        {{ trx_json_extract('src', ['USR_UDFDATE05'], type='timestamp_ntz', alias='usr_udfdate05') }},
        {{ trx_json_extract('src', ['USR_UDFCHKBOX01'], type='varchar', alias='usr_udfchkbox01') }},
        {{ trx_json_extract('src', ['USR_UDFCHKBOX02'], type='varchar', alias='usr_udfchkbox02') }},
        {{ trx_json_extract('src', ['USR_UDFCHKBOX03'], type='varchar', alias='usr_udfchkbox03') }},
        {{ trx_json_extract('src', ['USR_UDFCHKBOX04'], type='varchar', alias='usr_udfchkbox04') }},
        {{ trx_json_extract('src', ['USR_UDFCHKBOX05'], type='varchar', alias='usr_udfchkbox05') }},
        {{ trx_json_extract('src', ['USR_ENXUSER'], type='varchar', alias='usr_enxuser') }},
        {{ trx_json_extract('src', ['USR_GLOBALDATASPY'], type='varchar', alias='usr_globaldataspy') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_ORG'], type='varchar', alias='usr_default_org') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_CHART_TYPE'], type='varchar', alias='usr_default_chart_type') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_CHART_PERIOD'], type='varchar', alias='usr_default_chart_period') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_CHART_GROUPBY'], type='varchar', alias='usr_default_chart_groupby') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_CHART_SHOWYEAR'], type='varchar', alias='usr_default_chart_showyear') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_KPI_SIZE'], type='float', alias='usr_default_kpi_size') }},
        {{ trx_json_extract('src', ['USR_EXTERNCODE'], type='varchar', alias='usr_externcode') }},
        {{ trx_json_extract('src', ['USR_CANCELDAILYSCHEDSESSION'], type='varchar', alias='usr_canceldailyschedsession') }},
        {{ trx_json_extract('src', ['USR_SUPPLIER'], type='varchar', alias='usr_supplier') }},
        {{ trx_json_extract('src', ['USR_SUPPLIER_ORG'], type='varchar', alias='usr_supplier_org') }},
        {{ trx_json_extract('src', ['USR_ALLOWSCREENCACHESETUP'], type='varchar', alias='usr_allowscreencachesetup') }},
        {{ trx_json_extract('src', ['USR_ALLOWCREATEIMPORTUTILTEMP'], type='varchar', alias='usr_allowcreateimportutiltemp') }},
        {{ trx_json_extract('src', ['USR_ALLOWVIEWINGAUDITTRAIL'], type='varchar', alias='usr_allowviewingaudittrail') }},
        {{ trx_json_extract('src', ['USR_ENABLESCREENCACHEDECK'], type='varchar', alias='usr_enablescreencachedeck') }},
        {{ trx_json_extract('src', ['USR_ENABLETRANSITIONANIMATIONS'], type='varchar', alias='usr_enabletransitionanimations') }},
        {{ trx_json_extract('src', ['USR_DEFAULT_CHART_STATE'], type='varchar', alias='usr_default_chart_state') }},
        {{ trx_json_extract('src', ['USR_DEFAULTSTORE'], type='varchar', alias='usr_defaultstore') }},
        {{ trx_json_extract('src', ['USR_ALLOWMOBILESETTINGS'], type='varchar', alias='usr_allowmobilesettings') }},
        {{ trx_json_extract('src', ['USR_ARCGIS_USERCODE'], type='varchar', alias='usr_arcgis_usercode') }},
        {{ trx_json_extract('src', ['USR_ARCGIS_PASSWORD'], type='varchar', alias='usr_arcgis_password') }},
        {{ trx_json_extract('src', ['USR_ALLOWVIEWINGPRIVATECASES'], type='varchar', alias='usr_allowviewingprivatecases') }},
        {{ trx_json_extract('src', ['USR_MOBILEFIRSTSCREEN'], type='varchar', alias='usr_mobilefirstscreen') }},
        {{ trx_json_extract('src', ['USR_ALLOWCONTAINSSEARCH'], type='varchar', alias='usr_allowcontainssearch') }},
        {{ trx_json_extract('src', ['USR_ALLOWUPDATEFIELD'], type='varchar', alias='usr_allowupdatefield') }},
        {{ trx_json_extract('src', ['USR_PROFILEPICTURE'], type='varchar', alias='usr_profilepicture') }},
        {{ trx_json_extract('src', ['USR_MOBILEAUTOSYNC'], type='float', alias='usr_mobileautosync') }},
        {{ trx_json_extract('src', ['USR_ENABLEBIOMETRICS'], type='varchar', alias='usr_enablebiometrics') }},
        {{ trx_json_extract('src', ['USR_DUXFIRSTFUNC'], type='varchar', alias='usr_duxfirstfunc') }},
        {{ trx_json_extract('src', ['USR_MOBILEAPP'], type='varchar', alias='usr_mobileapp') }},
        {{ trx_json_extract('src', ['USR_ALLOWMOBILESYNCCONFIG'], type='varchar', alias='usr_allowmobilesyncconfig') }},
        {{ trx_json_extract('src', ['USR_ENABLEMOBILERESTOREUSER'], type='varchar', alias='usr_enablemobilerestoreuser') }},
        {{ trx_json_extract('src', ['USR_PWDRESETLINKGENTIME'], type='timestamp_ntz', alias='usr_pwdresetlinkgentime') }},
        {{ trx_json_extract('src', ['USR_PWDRESETCOUNT'], type='float', alias='usr_pwdresetcount') }},
        {{ trx_json_extract('src', ['_DELETED'], type='boolean', alias='_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_eam', 'eam_r5users') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['usr_code']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['usr_lastsaved']) }}
