{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='dbt_surrogate_key',
    description='eam_R5WOLABORSCHEDPARAMS',
    tags=['auto-generated', 'eam', 'stage2']
) }}

with cte_flattened as (
    select
        {{ trx_json_extract('src', ['WLS_LASTSAVED'], type='timestamp_ntz', alias='wls_lastsaved') }},
        {{ trx_json_extract('src', ['WLS_CODE'], type='varchar', alias='wls_code') }},
        {{ trx_json_extract('src', ['WLS_USER'], type='varchar', alias='wls_user') }},
        {{ trx_json_extract('src', ['WLS_PARAMETER'], type='varchar', alias='wls_parameter') }},
        {{ trx_json_extract('src', ['WLS_DEFPARAM'], type='varchar', alias='wls_defparam') }},
        {{ trx_json_extract('src', ['WLS_SESSIONID'], type='float', alias='wls_sessionid') }},
        {{ trx_json_extract('src', ['WLS_WOSCHEDSTARTDATE'], type='timestamp_ntz', alias='wls_woschedstartdate') }},
        {{ trx_json_extract('src', ['WLS_WOSCHEDENDDATE'], type='timestamp_ntz', alias='wls_woschedenddate') }},
        {{ trx_json_extract('src', ['WLS_CREATED'], type='timestamp_ntz', alias='wls_created') }},
        {{ trx_json_extract('src', ['WLS_EVENT_ORG'], type='varchar', alias='wls_event_org') }},
        {{ trx_json_extract('src', ['WLS_WORKORDER'], type='varchar', alias='wls_workorder') }},
        {{ trx_json_extract('src', ['WLS_WOMRC'], type='varchar', alias='wls_womrc') }},
        {{ trx_json_extract('src', ['WLS_WOPMSCHEDULE'], type='varchar', alias='wls_wopmschedule') }},
        {{ trx_json_extract('src', ['WLS_WOPROJECT'], type='varchar', alias='wls_woproject') }},
        {{ trx_json_extract('src', ['WLS_WOPROJBUD'], type='varchar', alias='wls_woprojbud') }},
        {{ trx_json_extract('src', ['WLS_WOOBJECT'], type='varchar', alias='wls_woobject') }},
        {{ trx_json_extract('src', ['WLS_WOOBJECTORG'], type='varchar', alias='wls_woobjectorg') }},
        {{ trx_json_extract('src', ['WLS_WOLOC'], type='varchar', alias='wls_woloc') }},
        {{ trx_json_extract('src', ['WLS_WOLOCORG'], type='varchar', alias='wls_wolocorg') }},
        {{ trx_json_extract('src', ['WLS_WOJOBTYPE'], type='varchar', alias='wls_wojobtype') }},
        {{ trx_json_extract('src', ['WLS_WOPRIORITY'], type='varchar', alias='wls_wopriority') }},
        {{ trx_json_extract('src', ['WLS_WOSTATUS'], type='varchar', alias='wls_wostatus') }},
        {{ trx_json_extract('src', ['WLS_WOREPORTEDBY'], type='varchar', alias='wls_woreportedby') }},
        {{ trx_json_extract('src', ['WLS_WOASSIGNEDBY'], type='varchar', alias='wls_woassignedby') }},
        {{ trx_json_extract('src', ['WLS_WOASSIGNEDTO'], type='varchar', alias='wls_woassignedto') }},
        {{ trx_json_extract('src', ['WLS_WOCLASS'], type='varchar', alias='wls_woclass') }},
        {{ trx_json_extract('src', ['WLS_WOCLASSORG'], type='varchar', alias='wls_woclassorg') }},
        {{ trx_json_extract('src', ['WLS_WOCRITICALITY'], type='varchar', alias='wls_wocriticality') }},
        {{ trx_json_extract('src', ['WLS_WOSHIFT'], type='varchar', alias='wls_woshift') }},
        {{ trx_json_extract('src', ['WLS_OBJECT'], type='varchar', alias='wls_object') }},
        {{ trx_json_extract('src', ['WLS_OBJORG'], type='varchar', alias='wls_objorg') }},
        {{ trx_json_extract('src', ['WLS_OBJTYPE'], type='varchar', alias='wls_objtype') }},
        {{ trx_json_extract('src', ['WLS_OBJSTATUS'], type='varchar', alias='wls_objstatus') }},
        {{ trx_json_extract('src', ['WLS_OBJCLASS'], type='varchar', alias='wls_objclass') }},
        {{ trx_json_extract('src', ['WLS_OBJCLASSORG'], type='varchar', alias='wls_objclassorg') }},
        {{ trx_json_extract('src', ['WLS_OBJCATEGORY'], type='varchar', alias='wls_objcategory') }},
        {{ trx_json_extract('src', ['WLS_OBJCOSTCODE'], type='varchar', alias='wls_objcostcode') }},
        {{ trx_json_extract('src', ['WLS_OBJMRC'], type='varchar', alias='wls_objmrc') }},
        {{ trx_json_extract('src', ['WLS_OBJPARENT'], type='varchar', alias='wls_objparent') }},
        {{ trx_json_extract('src', ['WLS_OBJPARENTORG'], type='varchar', alias='wls_objparentorg') }},
        {{ trx_json_extract('src', ['WLS_OBJLOC'], type='varchar', alias='wls_objloc') }},
        {{ trx_json_extract('src', ['WLS_OBJLOCORG'], type='varchar', alias='wls_objlocorg') }},
        {{ trx_json_extract('src', ['WLS_ACTTRADE'], type='varchar', alias='wls_acttrade') }},
        {{ trx_json_extract('src', ['WLS_ACTTASK'], type='varchar', alias='wls_acttask') }},
        {{ trx_json_extract('src', ['WLS_ACTSTARTDATE'], type='timestamp_ntz', alias='wls_actstartdate') }},
        {{ trx_json_extract('src', ['WLS_ACTENDDATE'], type='timestamp_ntz', alias='wls_actenddate') }},
        {{ trx_json_extract('src', ['WLS_EMPMRC'], type='varchar', alias='wls_empmrc') }},
        {{ trx_json_extract('src', ['WLS_EMPCLASS'], type='varchar', alias='wls_empclass') }},
        {{ trx_json_extract('src', ['WLS_EMPCLASSORG'], type='varchar', alias='wls_empclassorg') }},
        {{ trx_json_extract('src', ['WLS_EMPTRADE'], type='varchar', alias='wls_emptrade') }},
        {{ trx_json_extract('src', ['WLS_EMPSHIFT'], type='varchar', alias='wls_empshift') }},
        {{ trx_json_extract('src', ['WLS_EMPCREW'], type='varchar', alias='wls_empcrew') }},
        {{ trx_json_extract('src', ['WLS_EMPCREWORG'], type='varchar', alias='wls_empcreworg') }},
        {{ trx_json_extract('src', ['WLS_UNSCHEDCOLOR'], type='varchar', alias='wls_unschedcolor') }},
        {{ trx_json_extract('src', ['WLS_LIGHTLYSCHEDCOLOR'], type='varchar', alias='wls_lightlyschedcolor') }},
        {{ trx_json_extract('src', ['WLS_MODERATELYSCHEDCOLOR'], type='varchar', alias='wls_moderatelyschedcolor') }},
        {{ trx_json_extract('src', ['WLS_FULLYSCHEDCOLOR'], type='varchar', alias='wls_fullyschedcolor') }},
        {{ trx_json_extract('src', ['WLS_OVERSCHEDCOLOR'], type='varchar', alias='wls_overschedcolor') }},
        {{ trx_json_extract('src', ['WLS_THRESHOLDPERCENT'], type='float', alias='wls_thresholdpercent') }},
        {{ trx_json_extract('src', ['WLS_GENAVAILTHROUGH'], type='timestamp_ntz', alias='wls_genavailthrough') }},
        {{ trx_json_extract('src', ['WLS_SCHEDULING'], type='varchar', alias='wls_scheduling') }},
        {{ trx_json_extract('src', ['WLS_SCHEDULINGSTARTDATE'], type='timestamp_ntz', alias='wls_schedulingstartdate') }},
        {{ trx_json_extract('src', ['WLS_UPDATED'], type='timestamp_ntz', alias='wls_updated') }},
        {{ trx_json_extract('src', ['WLS_LISTLASTREFRESHED'], type='timestamp_ntz', alias='wls_listlastrefreshed') }},
        {{ trx_json_extract('src', ['WLS_DATALASTGEN'], type='timestamp_ntz', alias='wls_datalastgen') }},
        {{ trx_json_extract('src', ['WLS_MP'], type='varchar', alias='wls_mp') }},
        {{ trx_json_extract('src', ['WLS_MP_ORG'], type='varchar', alias='wls_mp_org') }},
        {{ trx_json_extract('src', ['WLS_MP_SEQ'], type='float', alias='wls_mp_seq') }},
        {{ trx_json_extract('src', ['WLS_CAMPAIGN'], type='varchar', alias='wls_campaign') }},
        {{ trx_json_extract('src', ['WLS_CAMPAIGN_LINE'], type='float', alias='wls_campaign_line') }},
        {{ trx_json_extract('src', ['WLS_UPDATECOUNT'], type='float', alias='wls_updatecount') }},
        {{ trx_json_extract('src', ['WLS_OBJINCLUDECHILDREN'], type='varchar', alias='wls_objincludechildren') }},
        {{ trx_json_extract('src', ['WLS_ALLOWACTSONDIFFSESSION'], type='varchar', alias='wls_allowactsondiffsession') }},
        {{ trx_json_extract('src', ['WLS_SKIPEQUIPSELECTIONPROCESS'], type='varchar', alias='wls_skipequipselectionprocess') }},
        {{ trx_json_extract('src', ['WLS_MAXCALCPRIORITY'], type='float', alias='wls_maxcalcpriority') }},
        {{ trx_json_extract('src', ['WLS_OPERATIONALSTATUS'], type='varchar', alias='wls_operationalstatus') }},
        {{ trx_json_extract('src', ['WLS_SHIFTSCHEDULING'], type='varchar', alias='wls_shiftscheduling') }},
        {{ trx_json_extract('src', ['WLS_SHIFTSTART'], type='timestamp_ntz', alias='wls_shiftstart') }},
        {{ trx_json_extract('src', ['WLS_SHIFTDURATION'], type='float', alias='wls_shiftduration') }},
        {{ trx_json_extract('src', ['WLS_AUTOSELECTACTIVITY'], type='varchar', alias='wls_autoselectactivity') }},
        {{ trx_json_extract('src', ['WLS_EXCLUDEDURATION'], type='varchar', alias='wls_excludeduration') }},
        {{ trx_json_extract('src', ['WLS_EXCLUDEPEOPLEREQUIRED'], type='varchar', alias='wls_excludepeoplerequired') }},
        {{ trx_json_extract('src', ['WLS_CONSIST'], type='varchar', alias='wls_consist') }},
        {{ trx_json_extract('src', ['_DELETED'], type='boolean', alias='_deleted') }},
        {{ trx_etl_columns() }}
    from {{ source('source_landing_eam', 'eam_r5wolaborschedparams') }}
)

select
    *,
    {{ trx_audit_columns() }},
    {{ trx_audit_surrogate(columns=['wls_code']) }}
from cte_flattened
{% if is_incremental() %}
where etl_load_datetime > (select max(etl_load_datetime) from {{ this }})
{% endif %}
{{ trx_current_state(order_by=['wls_lastsaved']) }}
