CREATE OR REPLACE VIEW DATAHUB_INTEGRATION.VW_STREAM_EAM_R5DOCUMENTS AS
                    SELECT
                        src:"DOC_CODE"::varchar(30) AS DOC_CODE,
                        src:"DOC_DESC"::varchar(80) AS DOC_DESC,
                        src:"DOC_CLASS"::varchar(8) AS DOC_CLASS,
                        src:"DOC_ORIGCODE"::varchar(30) AS DOC_ORIGCODE,
                        src:"DOC_REVNUMBER"::varchar(8) AS DOC_REVNUMBER,
                        src:"DOC_REVISION"::datetime AS DOC_REVISION,
                        src:"DOC_PARENT"::varchar(30) AS DOC_PARENT,
                        src:"DOC_ORIGIN"::varchar(24) AS DOC_ORIGIN,
                        src:"DOC_PAGES"::numeric(38, 10) AS DOC_PAGES,
                        src:"DOC_SIZE"::varchar(4) AS DOC_SIZE,
                        src:"DOC_CABINET"::varchar(12) AS DOC_CABINET,
                        src:"DOC_FILENAME"::varchar(255) AS DOC_FILENAME,
                        src:"DOC_FILETYPE"::varchar(50) AS DOC_FILETYPE,
                        src:"DOC_EXPIR"::datetime AS DOC_EXPIR,
                        src:"DOC_SUPPLIER"::varchar(30) AS DOC_SUPPLIER,
                        src:"DOC_WARSTART"::datetime AS DOC_WARSTART,
                        src:"DOC_WARRANTY"::varchar(1) AS DOC_WARRANTY,
                        src:"DOC_DURATION"::numeric(38, 10) AS DOC_DURATION,
                        src:"DOC_THRESHOLD"::numeric(38, 10) AS DOC_THRESHOLD,
                        src:"DOC_MANUFACTURER"::varchar(24) AS DOC_MANUFACTURER,
                        src:"DOC_ORG"::varchar(15) AS DOC_ORG,
                        src:"DOC_CLASS_ORG"::varchar(15) AS DOC_CLASS_ORG,
                        src:"DOC_SUPPLIER_ORG"::varchar(15) AS DOC_SUPPLIER_ORG,
                        src:"DOC_TYPE"::varchar(4) AS DOC_TYPE,
                        src:"DOC_RTYPE"::varchar(4) AS DOC_RTYPE,
                        src:"DOC_FILESIZE"::numeric(12, 0) AS DOC_FILESIZE,
                        src:"DOC_LOCKUSER"::varchar(255) AS DOC_LOCKUSER,
                        src:"DOC_UPDATECOUNT"::numeric(38, 0) AS DOC_UPDATECOUNT,
                        src:"DOC_LABCHARGE"::numeric(5, 2) AS DOC_LABCHARGE,
                        src:"DOC_MATCHARGE"::numeric(5, 2) AS DOC_MATCHARGE,
                        src:"DOC_HIRCHARGE"::numeric(5, 2) AS DOC_HIRCHARGE,
                        src:"DOC_DMACHARGE"::numeric(5, 2) AS DOC_DMACHARGE,
                        src:"DOC_SERVICECHARGE"::numeric(5, 2) AS DOC_SERVICECHARGE,
                        src:"DOC_TOOLCHARGE"::numeric(5, 2) AS DOC_TOOLCHARGE,
                        src:"DOC_NOTUSED"::varchar(1) AS DOC_NOTUSED,
                        src:"DOC_ORIGFILENAME"::varchar(255) AS DOC_ORIGFILENAME,
                        src:"DOC_UPLOADED"::datetime AS DOC_UPLOADED,
                        src:"DOC_WARRANTYTYPE"::varchar(4) AS DOC_WARRANTYTYPE,
                        src:"DOC_CONTROLNUMBER"::varchar(30) AS DOC_CONTROLNUMBER,
                        src:"DOC_AGREEMENTTYPE"::varchar(4) AS DOC_AGREEMENTTYPE,
                        src:"DOC_ONSITEREPAIR"::varchar(1) AS DOC_ONSITEREPAIR,
                        src:"DOC_LOANERPROVIDED"::varchar(1) AS DOC_LOANERPROVIDED,
                        src:"DOC_RENEWALALERTEMAIL"::varchar(255) AS DOC_RENEWALALERTEMAIL,
                        src:"DOC_STARTDATEBASIS"::varchar(4) AS DOC_STARTDATEBASIS,
                        src:"DOC_FIXEDLABORRATE"::numeric(24, 6) AS DOC_FIXEDLABORRATE,
                        src:"DOC_FIXEDLABORAMOUNT"::numeric(24, 6) AS DOC_FIXEDLABORAMOUNT,
                        src:"DOC_FIXEDSTOCKAMOUNT"::numeric(24, 6) AS DOC_FIXEDSTOCKAMOUNT,
                        src:"DOC_MAXLABORAMOUNT"::numeric(24, 6) AS DOC_MAXLABORAMOUNT,
                        src:"DOC_MAXSTOCKAMOUNT"::numeric(24, 6) AS DOC_MAXSTOCKAMOUNT,
                        src:"DOC_EXCLUDEPMWORKORDER"::varchar(1) AS DOC_EXCLUDEPMWORKORDER,
                        src:"DOC_PARTLISTREQUIRED"::varchar(1) AS DOC_PARTLISTREQUIRED,
                        src:"DOC_RMAREQUIRED"::varchar(1) AS DOC_RMAREQUIRED,
                        src:"DOC_UDFCHAR01"::varchar(80) AS DOC_UDFCHAR01,
                        src:"DOC_UDFCHAR02"::varchar(80) AS DOC_UDFCHAR02,
                        src:"DOC_UDFCHAR03"::varchar(80) AS DOC_UDFCHAR03,
                        src:"DOC_UDFCHAR04"::varchar(80) AS DOC_UDFCHAR04,
                        src:"DOC_UDFCHAR05"::varchar(80) AS DOC_UDFCHAR05,
                        src:"DOC_UDFCHAR06"::varchar(80) AS DOC_UDFCHAR06,
                        src:"DOC_UDFCHAR07"::varchar(80) AS DOC_UDFCHAR07,
                        src:"DOC_UDFCHAR08"::varchar(80) AS DOC_UDFCHAR08,
                        src:"DOC_UDFCHAR09"::varchar(80) AS DOC_UDFCHAR09,
                        src:"DOC_UDFCHAR10"::varchar(80) AS DOC_UDFCHAR10,
                        src:"DOC_UDFCHAR11"::varchar(80) AS DOC_UDFCHAR11,
                        src:"DOC_UDFCHAR12"::varchar(80) AS DOC_UDFCHAR12,
                        src:"DOC_UDFCHAR13"::varchar(80) AS DOC_UDFCHAR13,
                        src:"DOC_UDFCHAR14"::varchar(80) AS DOC_UDFCHAR14,
                        src:"DOC_UDFCHAR15"::varchar(80) AS DOC_UDFCHAR15,
                        src:"DOC_UDFCHAR16"::varchar(80) AS DOC_UDFCHAR16,
                        src:"DOC_UDFCHAR17"::varchar(80) AS DOC_UDFCHAR17,
                        src:"DOC_UDFCHAR18"::varchar(80) AS DOC_UDFCHAR18,
                        src:"DOC_UDFCHAR19"::varchar(80) AS DOC_UDFCHAR19,
                        src:"DOC_UDFCHAR20"::varchar(80) AS DOC_UDFCHAR20,
                        src:"DOC_UDFCHAR21"::varchar(80) AS DOC_UDFCHAR21,
                        src:"DOC_UDFCHAR22"::varchar(80) AS DOC_UDFCHAR22,
                        src:"DOC_UDFCHAR23"::varchar(80) AS DOC_UDFCHAR23,
                        src:"DOC_UDFCHAR24"::varchar(80) AS DOC_UDFCHAR24,
                        src:"DOC_UDFCHAR25"::varchar(80) AS DOC_UDFCHAR25,
                        src:"DOC_UDFCHAR26"::varchar(80) AS DOC_UDFCHAR26,
                        src:"DOC_UDFCHAR27"::varchar(80) AS DOC_UDFCHAR27,
                        src:"DOC_UDFCHAR28"::varchar(80) AS DOC_UDFCHAR28,
                        src:"DOC_UDFCHAR29"::varchar(80) AS DOC_UDFCHAR29,
                        src:"DOC_UDFCHAR30"::varchar(80) AS DOC_UDFCHAR30,
                        src:"DOC_UDFNUM01"::numeric(24, 6) AS DOC_UDFNUM01,
                        src:"DOC_UDFNUM02"::numeric(24, 6) AS DOC_UDFNUM02,
                        src:"DOC_UDFNUM03"::numeric(24, 6) AS DOC_UDFNUM03,
                        src:"DOC_UDFNUM04"::numeric(24, 6) AS DOC_UDFNUM04,
                        src:"DOC_UDFNUM05"::numeric(24, 6) AS DOC_UDFNUM05,
                        src:"DOC_UDFDATE01"::datetime AS DOC_UDFDATE01,
                        src:"DOC_UDFDATE02"::datetime AS DOC_UDFDATE02,
                        src:"DOC_UDFDATE03"::datetime AS DOC_UDFDATE03,
                        src:"DOC_UDFDATE04"::datetime AS DOC_UDFDATE04,
                        src:"DOC_UDFDATE05"::datetime AS DOC_UDFDATE05,
                        src:"DOC_UDFCHKBOX01"::varchar(1) AS DOC_UDFCHKBOX01,
                        src:"DOC_UDFCHKBOX02"::varchar(1) AS DOC_UDFCHKBOX02,
                        src:"DOC_UDFCHKBOX03"::varchar(1) AS DOC_UDFCHKBOX03,
                        src:"DOC_UDFCHKBOX04"::varchar(1) AS DOC_UDFCHKBOX04,
                        src:"DOC_UDFCHKBOX05"::varchar(1) AS DOC_UDFCHKBOX05,
                        src:"DOC_CONTENT"::varchar AS DOC_CONTENT,
                        src:"DOC_IDMTYPE"::varchar(32) AS DOC_IDMTYPE,
                        src:"DOC_TITLE"::varchar(256) AS DOC_TITLE,
                        src:"DOC_DATEEFFECTIVE"::datetime AS DOC_DATEEFFECTIVE,
                        src:"DOC_DATEEXPIRED"::datetime AS DOC_DATEEXPIRED,
                        src:"DOC_LASTSAVED"::datetime AS DOC_LASTSAVED,
                        src:"DOC_ISPROFILEPICTURE"::varchar(1) AS DOC_ISPROFILEPICTURE,
                        src:"DOC_ISMOBILELOG"::varchar(1) AS DOC_ISMOBILELOG
                        ,src:"_LASTSAVED"::datetime as ETL_LASTSAVED,
                        src:"_DELETED"::BOOLEAN as ETL_DELETED,
                        etl_load_datetime,
                       etl_load_metadatafilename
                    FROM DATAHUB_INTEGRATION.STREAM_EAM_R5DOCUMENTS;