CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRBUILD_XBUILDPREQUOTEGD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CUSTOMERREFERENCE, 
        DATALAKE_DELETED, 
        FEE, 
        FEEAMOUNT, 
        FEEQTY, 
        FEEUNIT, 
        FEEVALUE, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDAPPESTDPKEY, 
        XBUILDPREQUOTEGDKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDPREQUOTEGD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CUSTOMERREFERENCE, 
        DATALAKE_DELETED, 
        FEE, 
        FEEAMOUNT, 
        FEEQTY, 
        FEEUNIT, 
        FEEVALUE, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDAPPESTDPKEY, 
        XBUILDPREQUOTEGDKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRBUILD_XBUILDPREQUOTEGD;