CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_WATERTRACKEDREADING AS 
    SELECT 
        ACCOUNTKEY, 
        ACCTSERVICEPOSITIONKEY, 
        ADDBY, 
        ADDDTTM, 
        BILLKEY, 
        BILLTYPEKEY, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        READINGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WATERTRACKEDREADINGKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_WATERTRACKEDREADING
    UNION ALL 
    SELECT 
        ACCOUNTKEY, 
        ACCTSERVICEPOSITIONKEY, 
        ADDBY, 
        ADDDTTM, 
        BILLKEY, 
        BILLTYPEKEY, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        READINGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WATERTRACKEDREADINGKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_WATERTRACKEDREADING;