CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRBUILD_XBUILDINSTWORKGD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        COMPLETEDDATE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        VALUE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WORKITEM, 
        XBUILDINSTALLDPKEY, 
        XBUILDINSTWORKGDKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDINSTWORKGD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        COMPLETEDDATE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        VALUE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WORKITEM, 
        XBUILDINSTALLDPKEY, 
        XBUILDINSTWORKGDKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRBUILD_XBUILDINSTWORKGD;