CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_ASSETMANAGEMENT_SEWER_SEWERDISTRICT AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CODE, 
        DELETED, 
        DESCRIPT, 
        EFFDATE, 
        EXPDATE, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_SEWER_SEWERDISTRICT
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CODE, 
        DELETED, 
        DESCRIPT, 
        EFFDATE, 
        EXPDATE, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_ASSETMANAGEMENT_SEWER_SEWERDISTRICT;