CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRBUILD_XBUILDAPPQUEUECR AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        ALLOCATED, 
        APBLDGKEY, 
        APNO, 
        APTYPE, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        PARENTAPNO, 
        PARENTAPPLICATIONKEY, 
        PARENTAPTYPE, 
        POSTCODE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDAPPQUEUECRKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDAPPQUEUECR
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        ALLOCATED, 
        APBLDGKEY, 
        APNO, 
        APTYPE, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        PARENTAPNO, 
        PARENTAPPLICATIONKEY, 
        PARENTAPTYPE, 
        POSTCODE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDAPPQUEUECRKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRBUILD_XBUILDAPPQUEUECR;