CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_PLANNING_PLANHEARDETAILLOG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        DTLMODBY, 
        DTLMODDTTM, 
        MODBY, 
        MODDTTM, 
        PLANHEARDETAILLOGKEY, 
        PLANHEARDTLKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PLANNING_PLANHEARDETAILLOG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        DTLMODBY, 
        DTLMODDTTM, 
        MODBY, 
        MODDTTM, 
        PLANHEARDETAILLOGKEY, 
        PLANHEARDTLKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_PLANNING_PLANHEARDETAILLOG;