CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_PROJECT_PROJPLCONDLOG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJPLCONDKEY, 
        APPROJPLCONDLOGKEY, 
        CHANGEBY, 
        CHANGEDTTM, 
        CHANGETYPE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        STATUS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PROJECT_PROJPLCONDLOG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJPLCONDKEY, 
        APPROJPLCONDLOGKEY, 
        CHANGEBY, 
        CHANGEDTTM, 
        CHANGETYPE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        STATUS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_PROJECT_PROJPLCONDLOG;