CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_SUSPENDSERVICESETUP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CREDITADJTYPESUKEY, 
        DEBITADJTYPESUKEY, 
        DELETED, 
        LOGTYPE, 
        MODBY, 
        MODDTTM, 
        SUSPENDSERVICESETUPKEYKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_SUSPENDSERVICESETUP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CREDITADJTYPESUKEY, 
        DEBITADJTYPESUKEY, 
        DELETED, 
        LOGTYPE, 
        MODBY, 
        MODDTTM, 
        SUSPENDSERVICESETUPKEYKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_SUSPENDSERVICESETUP;