CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CDR_USE_USEAPPLDETAILLOG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APUSEAPPLDTLKEY, 
        DELETED, 
        DTLMODBY, 
        DTLMODDTTM, 
        MODBY, 
        MODDTTM, 
        USEAPPLDETAILLOGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_USE_USEAPPLDETAILLOG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APUSEAPPLDTLKEY, 
        DELETED, 
        DTLMODBY, 
        DTLMODDTTM, 
        MODBY, 
        MODDTTM, 
        USEAPPLDETAILLOGKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CDR_USE_USEAPPLDETAILLOG;