CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRPROJ_XPROJNETCONQUOTEGD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        QUANTITY, 
        QUOTEITEM, 
        TOTAL, 
        UNITCHARGE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJNETCONQUOTEDPKEY, 
        XPROJNETCONQUOTEGDKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPROJ_XPROJNETCONQUOTEGD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        QUANTITY, 
        QUOTEITEM, 
        TOTAL, 
        UNITCHARGE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJNETCONQUOTEDPKEY, 
        XPROJNETCONQUOTEGDKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRPROJ_XPROJNETCONQUOTEGD;