CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CRM_CUSTLOG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        COMMENTS, 
        CUSTLOGKEY, 
        DATALAKE_DELETED, 
        LOGBY, 
        LOGFRDTTM, 
        LOGTODTTM, 
        LOGTYPE, 
        MODBY, 
        MODDTTM, 
        SERVNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CRM_CUSTLOG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        COMMENTS, 
        CUSTLOGKEY, 
        DATALAKE_DELETED, 
        LOGBY, 
        LOGFRDTTM, 
        LOGTODTTM, 
        LOGTYPE, 
        MODBY, 
        MODDTTM, 
        SERVNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CRM_CUSTLOG;