CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRPROJ_XPROJEPALODGEDP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJAPPLDTLKEY, 
        DELETED, 
        LOT, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJEPALODGEDPKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPROJ_XPROJEPALODGEDP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        APPROJAPPLDTLKEY, 
        DELETED, 
        LOT, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XPROJEPALODGEDPKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRPROJ_XPROJEPALODGEDP;