CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_RESOURCES_FISCALYEAR AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        FISCALYEAR, 
        FISCALYEARKEY, 
        MODBY, 
        MODDTTM, 
        PERIODTYPE, 
        STARTDATE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        YEARENDADJPERIODFLAG, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_FISCALYEAR
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        FISCALYEAR, 
        FISCALYEARKEY, 
        MODBY, 
        MODDTTM, 
        PERIODTYPE, 
        STARTDATE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        YEARENDADJPERIODFLAG, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_RESOURCES_FISCALYEAR;