CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCUSTOMER_XIDENTITYCR AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        EMAIL, 
        IDKEY, 
        MODBY, 
        MODDTTM, 
        SMS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XIDENTITYCRKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCUSTOMER_XIDENTITYCR
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        EMAIL, 
        IDKEY, 
        MODBY, 
        MODDTTM, 
        SMS, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XIDENTITYCRKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCUSTOMER_XIDENTITYCR;