CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCDRBUILD_XBUILDNONDOMAPPGD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        ESTIMATEDAMOUNT, 
        ESTIMATEDFEECODE, 
        ESTIMATEDFEEDESCRIPTION, 
        ESTIMATEDQUANTITY, 
        ESTIMATEDVALUE, 
        INSPECTIONNUMBER, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDFEESDPKEY, 
        XBUILDNONDOMAPPGDKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDNONDOMAPPGD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        ESTIMATEDAMOUNT, 
        ESTIMATEDFEECODE, 
        ESTIMATEDFEEDESCRIPTION, 
        ESTIMATEDQUANTITY, 
        ESTIMATEDVALUE, 
        INSPECTIONNUMBER, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XBUILDFEESDPKEY, 
        XBUILDNONDOMAPPGDKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCDRBUILD_XBUILDNONDOMAPPGD;