CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_PORTAL_PERMISSIONSINROLES AS 
    SELECT 
        ACCESSITEM, 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        ROLE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_PORTAL_PERMISSIONSINROLES
    UNION ALL 
    SELECT 
        ACCESSITEM, 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        ROLE, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_PORTAL_PERMISSIONSINROLES;