CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCRM_XREADINGREVIEWSRDETAILS AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        READINGKEY, 
        SERVNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WATERMETER, 
        XREADINGREVIEWSRDETAILSKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCRM_XREADINGREVIEWSRDETAILS
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        READINGKEY, 
        SERVNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WATERMETER, 
        XREADINGREVIEWSRDETAILSKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCRM_XREADINGREVIEWSRDETAILS;