CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_ASSETMANAGEMENT_WATER_WMAFFC AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WMAFFC, 
        WMKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_WATER_WMAFFC
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        WMAFFC, 
        WMKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_ASSETMANAGEMENT_WATER_WMAFFC;