CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLCRM_XTANKERINFOGD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        KEYISSUEDATE, 
        KEYNUMBER, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XTANKERINFODPKEY, 
        XTANKERINFOGDKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCRM_XTANKERINFOGD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DATALAKE_DELETED, 
        KEYISSUEDATE, 
        KEYNUMBER, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XTANKERINFODPKEY, 
        XTANKERINFOGDKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLCRM_XTANKERINFOGD;