CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALRUNLINKWO AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        ASSVALKEY, 
        ASSVALRUNKEY, 
        COMPLETEDDATETIME, 
        DATALAKE_DELETED, 
        HISTKEY, 
        ISADJUSTMENT, 
        LINKASSVALWOKEY, 
        MODBY, 
        MODDTTM, 
        TOTCOST, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_ASSETVALUATION_ASSVALRUNLINKWO
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        ASSVALKEY, 
        ASSVALRUNKEY, 
        COMPLETEDDATETIME, 
        DATALAKE_DELETED, 
        HISTKEY, 
        ISADJUSTMENT, 
        LINKASSVALWOKEY, 
        MODBY, 
        MODDTTM, 
        TOTCOST, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_ASSETMANAGEMENT_ASSETVALUATION_ASSVALRUNLINKWO;