CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_BILLING_SERVICEFIELD AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DEFAULTVALUE, 
        DELETED, 
        DESCRIPTION, 
        MODBY, 
        MODDTTM, 
        MOVEINPROMPT, 
        MOVEOUTNOTES, 
        SERVICEFIELDKEY, 
        SETVALUEONADDRSERVFLAG, 
        TITLE, 
        VALIDATEVALUEFLAG, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_SERVICEFIELD
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DEFAULTVALUE, 
        DELETED, 
        DESCRIPTION, 
        MODBY, 
        MODDTTM, 
        MOVEINPROMPT, 
        MOVEOUTNOTES, 
        SERVICEFIELDKEY, 
        SETVALUEONADDRSERVFLAG, 
        TITLE, 
        VALIDATEVALUEFLAG, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_BILLING_SERVICEFIELD;