CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_WSLASSETS_XCPLXBUSINESSAREA AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        BUSINESSAREA, 
        COMPKEY, 
        COSTCENTRE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        PROJECTNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XCPLXBUSINESSAREAKEY, 
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLASSETS_XCPLXBUSINESSAREA
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        BUSINESSAREA, 
        COMPKEY, 
        COSTCENTRE, 
        DELETED, 
        MODBY, 
        MODDTTM, 
        PROJECTNO, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        XCPLXBUSINESSAREAKEY, 
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_WSLASSETS_XCPLXBUSINESSAREA;