CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_CRM_CRMLOGTYPE AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CODE, 
        DATALAKE_DELETED, 
        DESCRIPT, 
        DPDISPLAY, 
        EFFDATE, 
        EXPDATE, 
        ISPUBLIC, 
        MODBY, 
        MODDTTM, 
        PORTALDISPLAY, 
        TYPEKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_CRM_CRMLOGTYPE
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CODE, 
        DATALAKE_DELETED, 
        DESCRIPT, 
        DPDISPLAY, 
        EFFDATE, 
        EXPDATE, 
        ISPUBLIC, 
        MODBY, 
        MODDTTM, 
        PORTALDISPLAY, 
        TYPEKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_CRM_CRMLOGTYPE;