CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_METERMANAGEMENT_WATER_USGESTSETUP AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DEFCYCLEROUTERULEGRP, 
        DEFEXCHREMOVERULEGRP, 
        DEFSINGLECYCLERULEGRP, 
        DEFSINGLENONCYCLERULEGRP, 
        DELETED, 
        MAXNUMBEREST, 
        MODBY, 
        MODDTTM, 
        USGESTSETUPKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_METERMANAGEMENT_WATER_USGESTSETUP
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        DEFCYCLEROUTERULEGRP, 
        DEFEXCHREMOVERULEGRP, 
        DEFSINGLECYCLERULEGRP, 
        DEFSINGLENONCYCLERULEGRP, 
        DELETED, 
        MAXNUMBEREST, 
        MODBY, 
        MODDTTM, 
        USGESTSETUPKEY, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_METERMANAGEMENT_WATER_USGESTSETUP;