CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_RESOURCES_JOURNALSUMMARY AS 
    SELECT 
        ACCOUNTINGPERIOD, 
        ADDBY, 
        ADDDTTM, 
        AMOUNT, 
        CREDITBUDGETNUMBER, 
        DEBITBUDGETNUMBER, 
        DELETED, 
        FISCALYEAR, 
        FROMDATETIME, 
        JOURNALSUMMARYKEY, 
        MODBY, 
        MODDTTM, 
        TODATETIME, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_JOURNALSUMMARY
    UNION ALL 
    SELECT 
        ACCOUNTINGPERIOD, 
        ADDBY, 
        ADDDTTM, 
        AMOUNT, 
        CREDITBUDGETNUMBER, 
        DEBITBUDGETNUMBER, 
        DELETED, 
        FISCALYEAR, 
        FROMDATETIME, 
        JOURNALSUMMARYKEY, 
        MODBY, 
        MODDTTM, 
        TODATETIME, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_RESOURCES_JOURNALSUMMARY;