CREATE OR REPLACE VIEW DATAHUB_TARGET_HISTORY.IPS_RESOURCES_MFG AS 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CNTCTKEY, 
        CODE, 
        DELETED, 
        EFFDATE, 
        EXPDATE, 
        MFGKEY, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET_HISTORY.IPS_DELETED_RESOURCES_MFG
    UNION ALL 
    SELECT 
        ADDBY, 
        ADDDTTM, 
        CNTCTKEY, 
        CODE, 
        DELETED, 
        EFFDATE, 
        EXPDATE, 
        MFGKEY, 
        MODBY, 
        MODDTTM, 
        VARIATION_ID, 
        VARIATION_ID AS ETL_SEQUENCE_NUMBER,
        FALSE AS ETL_IS_DELETED,
        ETL_LOAD_DATETIME,
        ETL_LOAD_METADATAFILENAME
    FROM DATAHUB_TARGET.IPS_RESOURCES_MFG;