CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5OBJECTS(
                "OBJ_ACCESSIBLE" varchar, 
                "OBJ_ACD" numeric(38, 10), 
                "OBJ_ALIAS" varchar, 
                "OBJ_ASMLEVEL" varchar, 
                "OBJ_AVAILABILITYRSTATUS" varchar, 
                "OBJ_AVAILABILITYSTATUS" varchar, 
                "OBJ_AVAILABLECAPACITY" numeric(38, 10), 
                "OBJ_BATHCOUNT" numeric(38, 10), 
                "OBJ_BEDCOUNT" numeric(38, 10), 
                "OBJ_BILLABLE" varchar, 
                "OBJ_BILLEVERYPERIOD" numeric(38, 10), 
                "OBJ_BILLEVERYPERIODUOM" varchar, 
                "OBJ_BILLINGCODE" varchar, 
                "OBJ_BILLINGCODE_ORG" varchar, 
                "OBJ_BIN" varchar, 
                "OBJ_BIOMEDICALASSET" varchar, 
                "OBJ_BLACKSWAN" varchar, 
                "OBJ_BLACKSWANCOST" numeric(38, 10), 
                "OBJ_BUILDING" varchar, 
                "OBJ_BUILDMAINTPROGRAM" varchar, 
                "OBJ_CALGROUP" varchar, 
                "OBJ_CALGROUPORG" varchar, 
                "OBJ_CAPACITYCODE" varchar, 
                "OBJ_CAPACITYRATING" numeric(38, 10), 
                "OBJ_CATEGORY" varchar, 
                "OBJ_CGMP" varchar, 
                "OBJ_CHECKLISTFILTER" varchar, 
                "OBJ_CLASS" varchar, 
                "OBJ_CLASS_ORG" varchar, 
                "OBJ_CN" varchar, 
                "OBJ_CODE" varchar, 
                "OBJ_COMMISS" datetime, 
                "OBJ_COMPLEVEL" varchar, 
                "OBJ_COMPLOCATION" varchar, 
                "OBJ_CONDITIONINDEX" varchar, 
                "OBJ_CONDITIONRATING" numeric(38, 10), 
                "OBJ_CONDITIONSCORE" numeric(38, 10), 
                "OBJ_CONFIGAPPROVED" datetime, 
                "OBJ_CONFIGAPPROVEDBY" varchar, 
                "OBJ_CONFIGAUTONUM" varchar, 
                "OBJ_CONFIGCODE" varchar, 
                "OBJ_CONFIGDEFAULTSTATUS" varchar, 
                "OBJ_CONFIGPARENTSEPARATOR" varchar, 
                "OBJ_CONFIGPREFIX" varchar, 
                "OBJ_CONFIGREQUESTED" datetime, 
                "OBJ_CONFIGREQUESTEDBY" varchar, 
                "OBJ_CONFIGREVISION" numeric(38, 10), 
                "OBJ_CONFIGREVISIONREASON" varchar, 
                "OBJ_CONFIGRSTATUS" varchar, 
                "OBJ_CONFIGSEQLENGTH" numeric(38, 10), 
                "OBJ_CONFIGSPECIFIC" varchar, 
                "OBJ_CONFIGSTATUS" varchar, 
                "OBJ_CONFIGSTWO" varchar, 
                "OBJ_CONFIGSUFFIX" varchar, 
                "OBJ_CONFIGTYPE" varchar, 
                "OBJ_CONFIGUSEPARENTCODE" varchar, 
                "OBJ_CONFINEDSPACE" varchar, 
                "OBJ_CONTRACT" varchar, 
                "OBJ_CONTRACTTEMPLATE" varchar, 
                "OBJ_CONTRACTTEMPLATE_ORG" varchar, 
                "OBJ_CORRCONDITIONDATE" datetime, 
                "OBJ_CORRCONDITIONREASON" varchar, 
                "OBJ_CORRCONDITIONSCORE" numeric(38, 10), 
                "OBJ_CORRCONDITIONUSAGE" numeric(38, 10), 
                "OBJ_COSTCODE" varchar, 
                "OBJ_COSTOFNEEDEDREPAIRS" numeric(38, 10), 
                "OBJ_COUNTRY" numeric(38, 10), 
                "OBJ_COVERAGETYPE" varchar, 
                "OBJ_CREATED" datetime, 
                "OBJ_CREATEDBY" varchar, 
                "OBJ_CRITICALITY" varchar, 
                "OBJ_CRITICALITYSCORE" numeric(38, 10), 
                "OBJ_CUSTOMER" varchar, 
                "OBJ_CUSTOMER_ORG" varchar, 
                "OBJ_DEPEND" varchar, 
                "OBJ_DESC" varchar, 
                "OBJ_DESIREDCAPACITY" numeric(38, 10), 
                "OBJ_DEVICERANGEFROM" numeric(38, 10), 
                "OBJ_DEVICERANGETO" numeric(38, 10), 
                "OBJ_DEVICETOLFROM" numeric(38, 10), 
                "OBJ_DEVICETOLTO" numeric(38, 10), 
                "OBJ_DEVICETOLTYPE" varchar, 
                "OBJ_DIRECTION" varchar, 
                "OBJ_DISPOSALTYPE" varchar, 
                "OBJ_DOCUMOTO_BOOKID" varchar, 
                "OBJ_DORMEND" datetime, 
                "OBJ_DORMREUSE" varchar, 
                "OBJ_DORMSTART" datetime, 
                "OBJ_DRIVER" varchar, 
                "OBJ_EFFLOSSPHASEIMBALANCE1" numeric(38, 10), 
                "OBJ_EFFLOSSPHASEIMBALANCE2" numeric(38, 10), 
                "OBJ_EFFLOSSPHASEIMBALANCE3" numeric(38, 10), 
                "OBJ_EFFLOSSPHASEIMBALANCE4" numeric(38, 10), 
                "OBJ_EFFLOSSPHASEIMBALANCE5" numeric(38, 10), 
                "OBJ_ELECSUBMETERINTERVAL" numeric(38, 10), 
                "OBJ_ELECUSAGETHRESHOLD" numeric(38, 10), 
                "OBJ_EMAIL" varchar, 
                "OBJ_ENDUSEFULLIFE" datetime, 
                "OBJ_ENERGYSTARELIGIBLE" varchar, 
                "OBJ_ESIGNATURE" varchar, 
                "OBJ_ESTREVENUE" numeric(38, 10), 
                "OBJ_EXPOSURE" varchar, 
                "OBJ_FACILITY" varchar, 
                "OBJ_FACILITYCONDITIONINDEX" numeric(38, 10), 
                "OBJ_FAILUREPROBPERCENTAGE" numeric(38, 10), 
                "OBJ_FCICALCULATION" varchar, 
                "OBJ_FLEETCUSTOMER" varchar, 
                "OBJ_FLEETCUSTOMER_ORG" varchar, 
                "OBJ_FLOOR" varchar, 
                "OBJ_FLOORAREA" numeric(38, 10), 
                "OBJ_FLOORAREAUOM" varchar, 
                "OBJ_FLOW" varchar, 
                "OBJ_FROMPOINT" numeric(38, 10), 
                "OBJ_FUEL" varchar, 
                "OBJ_GASINDEX" varchar, 
                "OBJ_GEOREF" varchar, 
                "OBJ_GISLAYER" varchar, 
                "OBJ_GISMAP" varchar, 
                "OBJ_GISMAP_ORG" varchar, 
                "OBJ_GISOBJID" numeric(38, 10), 
                "OBJ_GISPROFILE" varchar, 
                "OBJ_GIS_SYNCCOUNT" numeric(38, 10), 
                "OBJ_GIS_UPDATECOUNT" numeric(38, 10), 
                "OBJ_GLTRANSFER" datetime, 
                "OBJ_GLTRANSFERFLAG" varchar, 
                "OBJ_GROUP" varchar, 
                "OBJ_GUESTFIRSTNAME" varchar, 
                "OBJ_GUESTLASTNAME" varchar, 
                "OBJ_GUESTMIDDLENAME" varchar, 
                "OBJ_GUESTPHONENUMBER" varchar, 
                "OBJ_GUESTPROFILEID" numeric(38, 10), 
                "OBJ_GUESTSALUTATION" varchar, 
                "OBJ_HARDWAREVER" varchar, 
                "OBJ_HIPAACONFIDENTIALITY" varchar, 
                "OBJ_IMAGEURL" varchar, 
                "OBJ_INCREMENT" numeric(38, 10), 
                "OBJ_INSPECTIONDIRECTION" varchar, 
                "OBJ_INSTALLDATE" datetime, 
                "OBJ_INSTRUMENT" varchar, 
                "OBJ_INSTRUMENTTYPE" varchar, 
                "OBJ_INTERFACE" datetime, 
                "OBJ_INVENTORYVERIFICATIONDATE" datetime, 
                "OBJ_ISSUEDTO" varchar, 
                "OBJ_JECATEGORY" varchar, 
                "OBJ_JESOURCE" varchar, 
                "OBJ_KEYNUMBER" varchar, 
                "OBJ_KITCHEN" varchar, 
                "OBJ_LASTSAVED" datetime, 
                "OBJ_LASTSTATUSUPDATE" datetime, 
                "OBJ_LATESTINSTALLDATE" datetime, 
                "OBJ_LATESTRECEIPTDATE" datetime, 
                "OBJ_LENGTH" numeric(38, 10), 
                "OBJ_LENGTHUOM" varchar, 
                "OBJ_LINEARCOSTWEIGHT" numeric(38, 10), 
                "OBJ_LINEAROBJTYPE" varchar, 
                "OBJ_LINEARREFPRECISION" numeric(38, 10), 
                "OBJ_LINEARREFUOM" varchar, 
                "OBJ_LINKGISWO" varchar, 
                "OBJ_LIVINGROOM" varchar, 
                "OBJ_LOANEDDEPT" varchar, 
                "OBJ_LOCATION" varchar, 
                "OBJ_LOCATION_ORG" varchar, 
                "OBJ_LOCKOUT" varchar, 
                "OBJ_LOOP" varchar, 
                "OBJ_LOT" varchar, 
                "OBJ_LOTOREVIEWED" datetime, 
                "OBJ_LOTOREVIEWEDBY" varchar, 
                "OBJ_LOTOREVIEWEDNAME" varchar, 
                "OBJ_LOTOREVIEWEDTYPE" varchar, 
                "OBJ_LOTOREVIEWREQUIRED" datetime, 
                "OBJ_LTYPE" varchar, 
                "OBJ_MANAGERPROFILEID" varchar, 
                "OBJ_MANUFACT" varchar, 
                "OBJ_MANUFACTMODEL" varchar, 
                "OBJ_MANUFACTREVNUM" varchar, 
                "OBJ_MARKUPCODE" varchar, 
                "OBJ_MARKUPCODE_ORG" varchar, 
                "OBJ_MAXGUESTCOUNT" varchar, 
                "OBJ_MINPENALTY" numeric(38, 10), 
                "OBJ_MNBDEFINITION" varchar, 
                "OBJ_MRC" varchar, 
                "OBJ_MTBFDAYS" numeric(38, 10), 
                "OBJ_MTBFRATING" numeric(38, 10), 
                "OBJ_MTTRHRS" numeric(38, 10), 
                "OBJ_MTTRRATING" numeric(38, 10), 
                "OBJ_MUBF" numeric(38, 10), 
                "OBJ_MUBFRATING" numeric(38, 10), 
                "OBJ_NONSMOKING" varchar, 
                "OBJ_NOTUSED" varchar, 
                "OBJ_NUMBEROFFAILURES" numeric(38, 10), 
                "OBJ_OBRTYPE" varchar, 
                "OBJ_OBTYPE" varchar, 
                "OBJ_OEMSITE" varchar, 
                "OBJ_OPENBAY" varchar, 
                "OBJ_OPERATIONALRSTATUS" varchar, 
                "OBJ_OPERATIONALSTATUS" varchar, 
                "OBJ_ORDER" varchar, 
                "OBJ_ORDERLINE" numeric(38, 10), 
                "OBJ_ORDER_ORG" varchar, 
                "OBJ_ORG" varchar, 
                "OBJ_ORIGCONFIGCODE" varchar, 
                "OBJ_ORIGCONFIGORG" varchar, 
                "OBJ_ORIGCONFIGREV" numeric(38, 10), 
                "OBJ_ORIGINALINSTALLDATE" datetime, 
                "OBJ_ORIGINALRECEIPTDATE" datetime, 
                "OBJ_ORIGOBJECT" varchar, 
                "OBJ_OUTPUTCALCTYPE" varchar, 
                "OBJ_OUTPUTRANGEFROM" numeric(38, 10), 
                "OBJ_OUTPUTRANGETO" numeric(38, 10), 
                "OBJ_OUTPUTUOM" varchar, 
                "OBJ_OWNERSHIPTYPE" varchar, 
                "OBJ_PARENT" varchar, 
                "OBJ_PARENT_ORG" varchar, 
                "OBJ_PART" varchar, 
                "OBJ_PART_ORG" varchar, 
                "OBJ_PENALTYFACTOR" numeric(38, 10), 
                "OBJ_PERFORMANCE" numeric(38, 10), 
                "OBJ_PERFORMANCEFORMULA" varchar, 
                "OBJ_PERFORMANCEFORMULA_ORG" varchar, 
                "OBJ_PERFORMANCELASTUPDATED" datetime, 
                "OBJ_PERFORMANCEMANAGER" varchar, 
                "OBJ_PERMITREVIEWED" datetime, 
                "OBJ_PERMITREVIEWEDBY" varchar, 
                "OBJ_PERMITREVIEWEDNAME" varchar, 
                "OBJ_PERMITREVIEWEDTYPE" varchar, 
                "OBJ_PERMITREVIEWREQUIRED" datetime, 
                "OBJ_PERSON" varchar, 
                "OBJ_PERSONALPROTECTIVEEQUIP" varchar, 
                "OBJ_PHONENUMBER" varchar, 
                "OBJ_PIDDRAWING" varchar, 
                "OBJ_PIDNO" varchar, 
                "OBJ_PMWODEPT" varchar, 
                "OBJ_POSITION" varchar, 
                "OBJ_POSITION_ORG" varchar, 
                "OBJ_PRECISION" numeric(38, 10), 
                "OBJ_PREVENTEVTCOMP" varchar, 
                "OBJ_PRIMARYSYSTEM" varchar, 
                "OBJ_PRIMARYSYSTEM_ORG" varchar, 
                "OBJ_PRIMARYUOM" varchar, 
                "OBJ_PRIMARYUSE" varchar, 
                "OBJ_PROCESSRANGEFROM" numeric(38, 10), 
                "OBJ_PROCESSRANGETO" numeric(38, 10), 
                "OBJ_PROCESSTOLFROM" numeric(38, 10), 
                "OBJ_PROCESSTOLTO" numeric(38, 10), 
                "OBJ_PRODUCTION" varchar, 
                "OBJ_PROFILE" varchar, 
                "OBJ_PROFILEPICTURE" varchar, 
                "OBJ_PROFILE_ORG" varchar, 
                "OBJ_PTYPE" varchar, 
                "OBJ_PURCHASECOST" numeric(38, 10), 
                "OBJ_PURCHASEDATE" datetime, 
                "OBJ_PURCHASEORDER" varchar, 
                "OBJ_PURCHASINGASSET" varchar, 
                "OBJ_RCMLEVEL" varchar, 
                "OBJ_RECORD" datetime, 
                "OBJ_REGION" varchar, 
                "OBJ_REGION_ORG" varchar, 
                "OBJ_RELIABILITYRANKING" varchar, 
                "OBJ_RELIABILITYRANKINGINDEX" varchar, 
                "OBJ_RELIABILITYRANKINGLOCKED" varchar, 
                "OBJ_RELIABILITYRANKINGREV" numeric(38, 10), 
                "OBJ_RELIABILITYRANKINGSCORE" numeric(38, 10), 
                "OBJ_RELIABILITYRANKING_ORG" varchar, 
                "OBJ_RENTAL" varchar, 
                "OBJ_RENTALTEMPLATE" varchar, 
                "OBJ_RENTALTEMPLATE_ORG" varchar, 
                "OBJ_REPLACEMENTVALUE" numeric(38, 10), 
                "OBJ_RESCALOWNER" varchar, 
                "OBJ_RESCALOWNERLIST" varchar, 
                "OBJ_RESOURCE" varchar, 
                "OBJ_RESOURCEPRESENT" varchar, 
                "OBJ_RISKCONSEQUENCECOST" numeric(38, 10), 
                "OBJ_RISKLEVEL" varchar, 
                "OBJ_RISKPRIORITYINDEX" varchar, 
                "OBJ_ROOMTYPE" varchar, 
                "OBJ_RPN" numeric(38, 10), 
                "OBJ_RRSURVEYLASTUPDATED" datetime, 
                "OBJ_RRVALUESLASTCALCULATED" datetime, 
                "OBJ_RSTATE" varchar, 
                "OBJ_RSTATUS" varchar, 
                "OBJ_SAFETY" varchar, 
                "OBJ_SAFETYREVIEWED" datetime, 
                "OBJ_SAFETYREVIEWEDBY" varchar, 
                "OBJ_SAFETYREVIEWEDNAME" varchar, 
                "OBJ_SAFETYREVIEWEDTYPE" varchar, 
                "OBJ_SAFETYREVIEWREQUIRED" datetime, 
                "OBJ_SCHEMATIC" varchar, 
                "OBJ_SDMPATH" varchar, 
                "OBJ_SDMPRESENT" varchar, 
                "OBJ_SERIALNO" varchar, 
                "OBJ_SERVICELIFE" numeric(38, 10), 
                "OBJ_SERVICELIFEUSAGE" numeric(38, 10), 
                "OBJ_SERVICEPERC" numeric(38, 10), 
                "OBJ_SET" varchar, 
                "OBJ_SOFTWAREVER" varchar, 
                "OBJ_SOLDDATE" datetime, 
                "OBJ_SOP" varchar, 
                "OBJ_SOURCECODE" varchar, 
                "OBJ_SOURCESYSTEM" varchar, 
                "OBJ_SQFOOTAGE" numeric(38, 10), 
                "OBJ_STARTBILLINGPERIOD" datetime, 
                "OBJ_STATE" varchar, 
                "OBJ_STATEMENTOFCOND" varchar, 
                "OBJ_STATUS" varchar, 
                "OBJ_STORE" varchar, 
                "OBJ_SYSLEVEL" varchar, 
                "OBJ_TAG" varchar, 
                "OBJ_TARGETPEAKDEMAND" numeric(38, 10), 
                "OBJ_TARGETPOWERFACTOR" numeric(38, 10), 
                "OBJ_TEMPMONITORED" varchar, 
                "OBJ_TESTPOINTUOM" varchar, 
                "OBJ_TOLERANCE_SIZE" numeric(38, 10), 
                "OBJ_TOPOINT" numeric(38, 10), 
                "OBJ_TRANSFERDATE" datetime, 
                "OBJ_UDFCHAR01" varchar, 
                "OBJ_UDFCHAR02" varchar, 
                "OBJ_UDFCHAR03" varchar, 
                "OBJ_UDFCHAR04" varchar, 
                "OBJ_UDFCHAR05" varchar, 
                "OBJ_UDFCHAR06" varchar, 
                "OBJ_UDFCHAR07" varchar, 
                "OBJ_UDFCHAR08" varchar, 
                "OBJ_UDFCHAR09" varchar, 
                "OBJ_UDFCHAR10" varchar, 
                "OBJ_UDFCHAR11" varchar, 
                "OBJ_UDFCHAR12" varchar, 
                "OBJ_UDFCHAR13" varchar, 
                "OBJ_UDFCHAR14" varchar, 
                "OBJ_UDFCHAR15" varchar, 
                "OBJ_UDFCHAR16" varchar, 
                "OBJ_UDFCHAR17" varchar, 
                "OBJ_UDFCHAR18" varchar, 
                "OBJ_UDFCHAR19" varchar, 
                "OBJ_UDFCHAR20" varchar, 
                "OBJ_UDFCHAR21" varchar, 
                "OBJ_UDFCHAR22" varchar, 
                "OBJ_UDFCHAR23" varchar, 
                "OBJ_UDFCHAR24" varchar, 
                "OBJ_UDFCHAR25" varchar, 
                "OBJ_UDFCHAR26" varchar, 
                "OBJ_UDFCHAR27" varchar, 
                "OBJ_UDFCHAR28" varchar, 
                "OBJ_UDFCHAR29" varchar, 
                "OBJ_UDFCHAR30" varchar, 
                "OBJ_UDFCHAR31" varchar, 
                "OBJ_UDFCHAR32" varchar, 
                "OBJ_UDFCHAR33" varchar, 
                "OBJ_UDFCHAR34" varchar, 
                "OBJ_UDFCHAR35" varchar, 
                "OBJ_UDFCHAR36" varchar, 
                "OBJ_UDFCHAR37" varchar, 
                "OBJ_UDFCHAR38" varchar, 
                "OBJ_UDFCHAR39" varchar, 
                "OBJ_UDFCHAR40" varchar, 
                "OBJ_UDFCHAR41" varchar, 
                "OBJ_UDFCHAR42" varchar, 
                "OBJ_UDFCHAR43" varchar, 
                "OBJ_UDFCHAR44" varchar, 
                "OBJ_UDFCHAR45" varchar, 
                "OBJ_UDFCHKBOX01" varchar, 
                "OBJ_UDFCHKBOX02" varchar, 
                "OBJ_UDFCHKBOX03" varchar, 
                "OBJ_UDFCHKBOX04" varchar, 
                "OBJ_UDFCHKBOX05" varchar, 
                "OBJ_UDFCHKBOX06" varchar, 
                "OBJ_UDFCHKBOX07" varchar, 
                "OBJ_UDFCHKBOX08" varchar, 
                "OBJ_UDFCHKBOX09" varchar, 
                "OBJ_UDFCHKBOX10" varchar, 
                "OBJ_UDFDATE01" datetime, 
                "OBJ_UDFDATE02" datetime, 
                "OBJ_UDFDATE03" datetime, 
                "OBJ_UDFDATE04" datetime, 
                "OBJ_UDFDATE05" datetime, 
                "OBJ_UDFDATE06" datetime, 
                "OBJ_UDFDATE07" datetime, 
                "OBJ_UDFDATE08" datetime, 
                "OBJ_UDFDATE09" datetime, 
                "OBJ_UDFDATE10" datetime, 
                "OBJ_UDFNOTE01" varchar, 
                "OBJ_UDFNOTE02" varchar, 
                "OBJ_UDFNUM01" numeric(38, 10), 
                "OBJ_UDFNUM02" numeric(38, 10), 
                "OBJ_UDFNUM03" numeric(38, 10), 
                "OBJ_UDFNUM04" numeric(38, 10), 
                "OBJ_UDFNUM05" numeric(38, 10), 
                "OBJ_UDFNUM06" numeric(38, 10), 
                "OBJ_UDFNUM07" numeric(38, 10), 
                "OBJ_UDFNUM08" numeric(38, 10), 
                "OBJ_UDFNUM09" numeric(38, 10), 
                "OBJ_UDFNUM10" numeric(38, 10), 
                "OBJ_UMDNSCODE" varchar, 
                "OBJ_UNITTYPE" varchar, 
                "OBJ_UPDATECOUNT" numeric(38, 10), 
                "OBJ_UPDATED" datetime, 
                "OBJ_UPDATEDBY" varchar, 
                "OBJ_USER" varchar, 
                "OBJ_VALUE" numeric(38, 10), 
                "OBJ_VARIABLE1" varchar, 
                "OBJ_VARIABLE2" varchar, 
                "OBJ_VARIABLE3" varchar, 
                "OBJ_VARIABLE4" varchar, 
                "OBJ_VARIABLE5" varchar, 
                "OBJ_VARIABLE6" varchar, 
                "OBJ_VARIABLERATING1" numeric(38, 10), 
                "OBJ_VARIABLERATING2" numeric(38, 10), 
                "OBJ_VARIABLERATING3" numeric(38, 10), 
                "OBJ_VARIABLERATING4" numeric(38, 10), 
                "OBJ_VARIABLERATING5" numeric(38, 10), 
                "OBJ_VARIABLERATING6" numeric(38, 10), 
                "OBJ_VARIABLERESULT1" numeric(38, 10), 
                "OBJ_VARIABLERESULT2" numeric(38, 10), 
                "OBJ_VARIABLERESULT3" numeric(38, 10), 
                "OBJ_VARIABLERESULT4" numeric(38, 10), 
                "OBJ_VARIABLERESULT5" numeric(38, 10), 
                "OBJ_VARIABLERESULT6" numeric(38, 10), 
                "OBJ_VEHICLE" varchar, 
                "OBJ_VEHICLERSTATUS" varchar, 
                "OBJ_VEHICLESTATUS" varchar, 
                "OBJ_VEHICLETYPE" varchar, 
                "OBJ_VENDOR" varchar, 
                "OBJ_VIPSTATUS" varchar, 
                "OBJ_WING" varchar, 
                "OBJ_WITHDRAW" datetime, 
                "OBJ_WODEPT" varchar, 
                "OBJ_WORKSPACE" varchar, 
                "OBJ_XCOORDINATE" numeric(38, 10), 
                "OBJ_XLOCATION" numeric(38, 10), 
                "OBJ_YCOORDINATE" numeric(38, 10), 
                "OBJ_YEARBUILT" numeric(38, 10), 
                "OBJ_YLOCATION" numeric(38, 10), 
                "OBJ_ZCOORDINATE" numeric(38, 10), 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 