CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5BINSTOCK(
                "BIS_BIN" varchar, 
                "BIS_CREATED" datetime, 
                "BIS_CREATEDBY" varchar, 
                "BIS_LASTSAVED" datetime, 
                "BIS_LOT" varchar, 
                "BIS_PART" varchar, 
                "BIS_PART_ORG" varchar, 
                "BIS_QTY" numeric(38, 10), 
                "BIS_REPAIRQTY" numeric(38, 10), 
                "BIS_STORE" varchar, 
                "BIS_UDFCHAR01" varchar, 
                "BIS_UDFCHAR02" varchar, 
                "BIS_UDFCHAR03" varchar, 
                "BIS_UDFCHAR04" varchar, 
                "BIS_UDFCHAR05" varchar, 
                "BIS_UDFCHAR06" varchar, 
                "BIS_UDFCHAR07" varchar, 
                "BIS_UDFCHAR08" varchar, 
                "BIS_UDFCHAR09" varchar, 
                "BIS_UDFCHAR10" varchar, 
                "BIS_UDFCHAR11" varchar, 
                "BIS_UDFCHAR12" varchar, 
                "BIS_UDFCHAR13" varchar, 
                "BIS_UDFCHAR14" varchar, 
                "BIS_UDFCHAR15" varchar, 
                "BIS_UDFCHAR16" varchar, 
                "BIS_UDFCHAR17" varchar, 
                "BIS_UDFCHAR18" varchar, 
                "BIS_UDFCHAR19" varchar, 
                "BIS_UDFCHAR20" varchar, 
                "BIS_UDFCHAR21" varchar, 
                "BIS_UDFCHAR22" varchar, 
                "BIS_UDFCHAR23" varchar, 
                "BIS_UDFCHAR24" varchar, 
                "BIS_UDFCHAR25" varchar, 
                "BIS_UDFCHAR26" varchar, 
                "BIS_UDFCHAR27" varchar, 
                "BIS_UDFCHAR28" varchar, 
                "BIS_UDFCHAR29" varchar, 
                "BIS_UDFCHAR30" varchar, 
                "BIS_UDFCHKBOX01" varchar, 
                "BIS_UDFCHKBOX02" varchar, 
                "BIS_UDFCHKBOX03" varchar, 
                "BIS_UDFCHKBOX04" varchar, 
                "BIS_UDFCHKBOX05" varchar, 
                "BIS_UDFDATE01" datetime, 
                "BIS_UDFDATE02" datetime, 
                "BIS_UDFDATE03" datetime, 
                "BIS_UDFDATE04" datetime, 
                "BIS_UDFDATE05" datetime, 
                "BIS_UDFNUM01" numeric(38, 10), 
                "BIS_UDFNUM02" numeric(38, 10), 
                "BIS_UDFNUM03" numeric(38, 10), 
                "BIS_UDFNUM04" numeric(38, 10), 
                "BIS_UDFNUM05" numeric(38, 10), 
                "BIS_UPDATECOUNT" numeric(38, 10), 
                "BIS_UPDATED" datetime, 
                "BIS_UPDATEDBY" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 