CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5STANDWACTS(
                "WAC_ACT" numeric(38, 10), 
                "WAC_ASMLEVEL" varchar, 
                "WAC_COMPLEVEL" varchar, 
                "WAC_CREATED" datetime, 
                "WAC_DURATION" numeric(38, 10), 
                "WAC_EST" numeric(38, 10), 
                "WAC_HIRE" varchar, 
                "WAC_LABORRTYPE" varchar, 
                "WAC_LABORTYPE" varchar, 
                "WAC_LASTSAVED" datetime, 
                "WAC_MANUFACT" varchar, 
                "WAC_MATLIST" varchar, 
                "WAC_NOTE" varchar, 
                "WAC_PERSONS" numeric(38, 10), 
                "WAC_QTY" numeric(38, 10), 
                "WAC_RPC" varchar, 
                "WAC_SPECIAL" varchar, 
                "WAC_STANDWORK" varchar, 
                "WAC_START" numeric(38, 10), 
                "WAC_SUPPLIER" varchar, 
                "WAC_SUPPLIER_ORG" varchar, 
                "WAC_SYSLEVEL" varchar, 
                "WAC_TASK" varchar, 
                "WAC_TPF" varchar, 
                "WAC_TRADE" varchar, 
                "WAC_UDFCHAR01" varchar, 
                "WAC_UDFCHAR02" varchar, 
                "WAC_UDFCHAR03" varchar, 
                "WAC_UDFCHAR04" varchar, 
                "WAC_UDFCHAR05" varchar, 
                "WAC_UDFCHAR06" varchar, 
                "WAC_UDFCHAR07" varchar, 
                "WAC_UDFCHAR08" varchar, 
                "WAC_UDFCHAR09" varchar, 
                "WAC_UDFCHAR10" varchar, 
                "WAC_UDFCHAR11" varchar, 
                "WAC_UDFCHAR12" varchar, 
                "WAC_UDFCHAR13" varchar, 
                "WAC_UDFCHAR14" varchar, 
                "WAC_UDFCHAR15" varchar, 
                "WAC_UDFCHAR16" varchar, 
                "WAC_UDFCHAR17" varchar, 
                "WAC_UDFCHAR18" varchar, 
                "WAC_UDFCHAR19" varchar, 
                "WAC_UDFCHAR20" varchar, 
                "WAC_UDFCHAR21" varchar, 
                "WAC_UDFCHAR22" varchar, 
                "WAC_UDFCHAR23" varchar, 
                "WAC_UDFCHAR24" varchar, 
                "WAC_UDFCHAR25" varchar, 
                "WAC_UDFCHAR26" varchar, 
                "WAC_UDFCHAR27" varchar, 
                "WAC_UDFCHAR28" varchar, 
                "WAC_UDFCHAR29" varchar, 
                "WAC_UDFCHAR30" varchar, 
                "WAC_UDFCHKBOX01" varchar, 
                "WAC_UDFCHKBOX02" varchar, 
                "WAC_UDFCHKBOX03" varchar, 
                "WAC_UDFCHKBOX04" varchar, 
                "WAC_UDFCHKBOX05" varchar, 
                "WAC_UDFDATE01" datetime, 
                "WAC_UDFDATE02" datetime, 
                "WAC_UDFDATE03" datetime, 
                "WAC_UDFDATE04" datetime, 
                "WAC_UDFDATE05" datetime, 
                "WAC_UDFNOTE01" varchar, 
                "WAC_UDFNOTE02" varchar, 
                "WAC_UDFNUM01" numeric(38, 10), 
                "WAC_UDFNUM02" numeric(38, 10), 
                "WAC_UDFNUM03" numeric(38, 10), 
                "WAC_UDFNUM04" numeric(38, 10), 
                "WAC_UDFNUM05" numeric(38, 10), 
                "WAC_UOM" varchar, 
                "WAC_UPDATECOUNT" numeric(38, 10), 
                "WAC_UPDATED" datetime, 
                "WAC_WAP" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 