CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5WARCOVERAGES(
                "WCV_ACTIVE" varchar, 
                "WCV_CREATED" datetime, 
                "WCV_DURATION" numeric(38, 10), 
                "WCV_EXPIRATION" numeric(38, 10), 
                "WCV_EXPIRATIONDATE" datetime, 
                "WCV_LASTSAVED" datetime, 
                "WCV_NEARTHRESHOLD" numeric(38, 10), 
                "WCV_OBJECT" varchar, 
                "WCV_OBJECT_ORG" varchar, 
                "WCV_OBRTYPE" varchar, 
                "WCV_OBTYPE" varchar, 
                "WCV_RECORDED" datetime, 
                "WCV_SEQNO" numeric(38, 10), 
                "WCV_STARTDATE" datetime, 
                "WCV_STARTUSAGE" numeric(38, 10), 
                "WCV_UOM" varchar, 
                "WCV_UPDATECOUNT" numeric(38, 10), 
                "WCV_UPDATED" datetime, 
                "WCV_USER" varchar, 
                "WCV_WARRANTY" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 