CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5PPMS(
            PPM_CLASS varchar, 
            PPM_CLASS_ORG varchar, 
            PPM_CODE varchar, 
            PPM_DESC varchar, 
            PPM_DURATION numeric(38, 10), 
            PPM_ESTWORKLOAD numeric(38, 10), 
            PPM_FREQ numeric(38, 10), 
            PPM_GENWINDOW numeric(38, 10), 
            PPM_ISSTYPE varchar, 
            PPM_JOBTYPE varchar, 
            PPM_LASTSAVED datetime, 
            PPM_METER numeric(38, 10), 
            PPM_METER2 numeric(38, 10), 
            PPM_METUOM varchar, 
            PPM_METUOM2 varchar, 
            PPM_NEARWINDOW numeric(38, 10), 
            PPM_NESTED varchar, 
            PPM_NESTEDPMSTATUS varchar, 
            PPM_NESTEDTOLMAX numeric(38, 10), 
            PPM_NESTEDTOLMET2MAX numeric(38, 10), 
            PPM_NESTEDTOLMET2MIN numeric(38, 10), 
            PPM_NESTEDTOLMETMAX numeric(38, 10), 
            PPM_NESTEDTOLMETMIN numeric(38, 10), 
            PPM_NESTEDTOLMIN numeric(38, 10), 
            PPM_NOTUSED varchar, 
            PPM_OKWINDOW numeric(38, 10), 
            PPM_ORG varchar, 
            PPM_PACKAGE varchar, 
            PPM_PERFORMONDAY numeric(38, 10), 
            PPM_PERFORMONWEEK varchar, 
            PPM_PERIODUOM varchar, 
            PPM_PERMITREVIEWED datetime, 
            PPM_PERMITREVIEWEDBY varchar, 
            PPM_PERMITREVIEWEDNAME varchar, 
            PPM_PERMITREVIEWEDTYPE varchar, 
            PPM_PERMITREVIEWREQUIRED datetime, 
            PPM_PLAN varchar, 
            PPM_PRIORITY varchar, 
            PPM_PRODPRIORITY varchar, 
            PPM_REQUESTEDENDDATEBUFFER numeric(38, 10), 
            PPM_REQUESTEDSTARTDATEBUFFER numeric(38, 10), 
            PPM_REVISION numeric(38, 10), 
            PPM_REVRSTATUS varchar, 
            PPM_REVSTATUS varchar, 
            PPM_SAFETYREVIEWED datetime, 
            PPM_SAFETYREVIEWEDBY varchar, 
            PPM_SAFETYREVIEWEDNAME varchar, 
            PPM_SAFETYREVIEWEDTYPE varchar, 
            PPM_SAFETYREVIEWREQUIRED datetime, 
            PPM_SCHEDGRP varchar, 
            PPM_SPECIAL varchar, 
            PPM_UDFCHAR01 varchar, 
            PPM_UDFCHAR02 varchar, 
            PPM_UDFCHAR03 varchar, 
            PPM_UDFCHAR04 varchar, 
            PPM_UDFCHAR05 varchar, 
            PPM_UDFCHAR06 varchar, 
            PPM_UDFCHAR07 varchar, 
            PPM_UDFCHAR08 varchar, 
            PPM_UDFCHAR09 varchar, 
            PPM_UDFCHAR10 varchar, 
            PPM_UDFCHAR11 varchar, 
            PPM_UDFCHAR12 varchar, 
            PPM_UDFCHAR13 varchar, 
            PPM_UDFCHAR14 varchar, 
            PPM_UDFCHAR15 varchar, 
            PPM_UDFCHAR16 varchar, 
            PPM_UDFCHAR17 varchar, 
            PPM_UDFCHAR18 varchar, 
            PPM_UDFCHAR19 varchar, 
            PPM_UDFCHAR20 varchar, 
            PPM_UDFCHAR21 varchar, 
            PPM_UDFCHAR22 varchar, 
            PPM_UDFCHAR23 varchar, 
            PPM_UDFCHAR24 varchar, 
            PPM_UDFCHAR25 varchar, 
            PPM_UDFCHAR26 varchar, 
            PPM_UDFCHAR27 varchar, 
            PPM_UDFCHAR28 varchar, 
            PPM_UDFCHAR29 varchar, 
            PPM_UDFCHAR30 varchar, 
            PPM_UDFCHAR31 varchar, 
            PPM_UDFCHAR32 varchar, 
            PPM_UDFCHAR33 varchar, 
            PPM_UDFCHAR34 varchar, 
            PPM_UDFCHAR35 varchar, 
            PPM_UDFCHAR36 varchar, 
            PPM_UDFCHAR37 varchar, 
            PPM_UDFCHAR38 varchar, 
            PPM_UDFCHAR39 varchar, 
            PPM_UDFCHAR40 varchar, 
            PPM_UDFCHAR41 varchar, 
            PPM_UDFCHAR42 varchar, 
            PPM_UDFCHAR43 varchar, 
            PPM_UDFCHAR44 varchar, 
            PPM_UDFCHAR45 varchar, 
            PPM_UDFCHKBOX01 varchar, 
            PPM_UDFCHKBOX02 varchar, 
            PPM_UDFCHKBOX03 varchar, 
            PPM_UDFCHKBOX04 varchar, 
            PPM_UDFCHKBOX05 varchar, 
            PPM_UDFCHKBOX06 varchar, 
            PPM_UDFCHKBOX07 varchar, 
            PPM_UDFCHKBOX08 varchar, 
            PPM_UDFCHKBOX09 varchar, 
            PPM_UDFCHKBOX10 varchar, 
            PPM_UDFDATE01 datetime, 
            PPM_UDFDATE02 datetime, 
            PPM_UDFDATE03 datetime, 
            PPM_UDFDATE04 datetime, 
            PPM_UDFDATE05 datetime, 
            PPM_UDFDATE06 datetime, 
            PPM_UDFDATE07 datetime, 
            PPM_UDFDATE08 datetime, 
            PPM_UDFDATE09 datetime, 
            PPM_UDFDATE10 datetime, 
            PPM_UDFNOTE01 varchar, 
            PPM_UDFNOTE02 varchar, 
            PPM_UDFNUM01 numeric(38, 10), 
            PPM_UDFNUM02 numeric(38, 10), 
            PPM_UDFNUM03 numeric(38, 10), 
            PPM_UDFNUM04 numeric(38, 10), 
            PPM_UDFNUM05 numeric(38, 10), 
            PPM_UDFNUM06 numeric(38, 10), 
            PPM_UDFNUM07 numeric(38, 10), 
            PPM_UDFNUM08 numeric(38, 10), 
            PPM_UDFNUM09 numeric(38, 10), 
            PPM_UDFNUM10 numeric(38, 10), 
            PPM_UPDATECOUNT numeric(38, 10), 
            PPM_WOCLASS varchar, 
            PPM_WOCLASS_ORG varchar, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 