CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5TRADERATES(
            TRR_ACTIVE varchar, 
            TRR_END datetime, 
            TRR_LASTSAVED datetime, 
            TRR_MRC varchar, 
            TRR_NTRATE numeric(38, 10), 
            TRR_OCTYPE varchar, 
            TRR_ORG varchar, 
            TRR_OTRATE numeric(38, 10), 
            TRR_PERSON varchar, 
            TRR_START datetime, 
            TRR_SUPPLIER varchar, 
            TRR_SUPPLIER_ORG varchar, 
            TRR_TAX varchar, 
            TRR_TRADE varchar, 
            TRR_UDFCHAR01 varchar, 
            TRR_UDFCHAR02 varchar, 
            TRR_UDFCHAR03 varchar, 
            TRR_UDFCHAR04 varchar, 
            TRR_UDFCHAR05 varchar, 
            TRR_UDFCHAR06 varchar, 
            TRR_UDFCHAR07 varchar, 
            TRR_UDFCHAR08 varchar, 
            TRR_UDFCHAR09 varchar, 
            TRR_UDFCHAR10 varchar, 
            TRR_UDFCHAR11 varchar, 
            TRR_UDFCHAR12 varchar, 
            TRR_UDFCHAR13 varchar, 
            TRR_UDFCHAR14 varchar, 
            TRR_UDFCHAR15 varchar, 
            TRR_UDFCHAR16 varchar, 
            TRR_UDFCHAR17 varchar, 
            TRR_UDFCHAR18 varchar, 
            TRR_UDFCHAR19 varchar, 
            TRR_UDFCHAR20 varchar, 
            TRR_UDFCHAR21 varchar, 
            TRR_UDFCHAR22 varchar, 
            TRR_UDFCHAR23 varchar, 
            TRR_UDFCHAR24 varchar, 
            TRR_UDFCHAR25 varchar, 
            TRR_UDFCHAR26 varchar, 
            TRR_UDFCHAR27 varchar, 
            TRR_UDFCHAR28 varchar, 
            TRR_UDFCHAR29 varchar, 
            TRR_UDFCHAR30 varchar, 
            TRR_UDFCHKBOX01 varchar, 
            TRR_UDFCHKBOX02 varchar, 
            TRR_UDFCHKBOX03 varchar, 
            TRR_UDFCHKBOX04 varchar, 
            TRR_UDFCHKBOX05 varchar, 
            TRR_UDFDATE01 datetime, 
            TRR_UDFDATE02 datetime, 
            TRR_UDFDATE03 datetime, 
            TRR_UDFDATE04 datetime, 
            TRR_UDFDATE05 datetime, 
            TRR_UDFNUM01 numeric(38, 10), 
            TRR_UDFNUM02 numeric(38, 10), 
            TRR_UDFNUM03 numeric(38, 10), 
            TRR_UDFNUM04 numeric(38, 10), 
            TRR_UDFNUM05 numeric(38, 10), 
            TRR_UPDATECOUNT numeric(38, 10), 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 