CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5JOBPARAM(
                "JPR_DATATYPE" varchar, 
                "JPR_DEFAULT" varchar, 
                "JPR_EWSLOVDEF" varchar, 
                "JPR_FIXED" varchar, 
                "JPR_FORMAT" varchar, 
                "JPR_LASTSAVED" datetime, 
                "JPR_LENGTH" numeric(38, 10), 
                "JPR_LINE" numeric(38, 10), 
                "JPR_LOVFUNCTION" varchar, 
                "JPR_MANDATORY" varchar, 
                "JPR_NAME" varchar, 
                "JPR_OPTIONS" numeric(38, 10), 
                "JPR_PARAMETER" varchar, 
                "JPR_PROPERTY" varchar, 
                "JPR_QUERY" varchar, 
                "JPR_REMEMBER" varchar, 
                "JPR_RENTITY" varchar, 
                "JPR_RTYPE" varchar, 
                "JPR_TEST" varchar, 
                "JPR_UPDATECOUNT" numeric(38, 10), 
                "JPR_UPPER" varchar, 
                "_DELETED" boolean, 
                ETL_DELETED boolean,
                ETL_LASTSAVED datetime, 
                etl_load_datetime timestamp,
                etl_load_metadatafilename varchar
                ); 