CREATE OR REPLACE TABLE TARGET_EAM.EAM_R5EQUIPMENTRANKINGS(
            EQR_CALCULATIONERROR varchar, 
            EQR_CORRSCOREDATE datetime, 
            EQR_CORRSCOREINDEX varchar, 
            EQR_CORRSCORERANKING varchar, 
            EQR_CORRSCORERANKINGREV numeric(38, 10), 
            EQR_CORRSCORERANKING_ORG varchar, 
            EQR_CORRSCORESCORE numeric(38, 10), 
            EQR_CORRSCORESTATUS varchar, 
            EQR_CREATED datetime, 
            EQR_CREATEDBY varchar, 
            EQR_DEFAULT varchar, 
            EQR_LASTSAVED datetime, 
            EQR_LOCKRANKINGVALUES varchar, 
            EQR_NEXTREFRESH datetime, 
            EQR_NOTE varchar, 
            EQR_OBJCODE varchar, 
            EQR_OBJORG varchar, 
            EQR_RANKINGCODE varchar, 
            EQR_RANKINGINDEX varchar, 
            EQR_RANKINGORG varchar, 
            EQR_RANKINGREVISION numeric(38, 10), 
            EQR_RANKINGSCORE numeric(38, 10), 
            EQR_REFRESHEVERY numeric(38, 10), 
            EQR_REFRESHEVERYUNIT varchar, 
            EQR_REFRESHSEQUENCE numeric(38, 10), 
            EQR_SURVEYLASTUPDATED datetime, 
            EQR_UDFCHAR01 varchar, 
            EQR_UDFCHAR02 varchar, 
            EQR_UDFCHAR03 varchar, 
            EQR_UDFCHAR04 varchar, 
            EQR_UDFCHAR05 varchar, 
            EQR_UDFCHAR06 varchar, 
            EQR_UDFCHAR07 varchar, 
            EQR_UDFCHAR08 varchar, 
            EQR_UDFCHAR09 varchar, 
            EQR_UDFCHAR10 varchar, 
            EQR_UDFCHAR11 varchar, 
            EQR_UDFCHAR12 varchar, 
            EQR_UDFCHAR13 varchar, 
            EQR_UDFCHAR14 varchar, 
            EQR_UDFCHAR15 varchar, 
            EQR_UDFCHAR16 varchar, 
            EQR_UDFCHAR17 varchar, 
            EQR_UDFCHAR18 varchar, 
            EQR_UDFCHAR19 varchar, 
            EQR_UDFCHAR20 varchar, 
            EQR_UDFCHAR21 varchar, 
            EQR_UDFCHAR22 varchar, 
            EQR_UDFCHAR23 varchar, 
            EQR_UDFCHAR24 varchar, 
            EQR_UDFCHAR25 varchar, 
            EQR_UDFCHAR26 varchar, 
            EQR_UDFCHAR27 varchar, 
            EQR_UDFCHAR28 varchar, 
            EQR_UDFCHAR29 varchar, 
            EQR_UDFCHAR30 varchar, 
            EQR_UDFCHKBOX01 varchar, 
            EQR_UDFCHKBOX02 varchar, 
            EQR_UDFCHKBOX03 varchar, 
            EQR_UDFCHKBOX04 varchar, 
            EQR_UDFCHKBOX05 varchar, 
            EQR_UDFDATE01 datetime, 
            EQR_UDFDATE02 datetime, 
            EQR_UDFDATE03 datetime, 
            EQR_UDFDATE04 datetime, 
            EQR_UDFDATE05 datetime, 
            EQR_UDFNUM01 numeric(38, 10), 
            EQR_UDFNUM02 numeric(38, 10), 
            EQR_UDFNUM03 numeric(38, 10), 
            EQR_UDFNUM04 numeric(38, 10), 
            EQR_UDFNUM05 numeric(38, 10), 
            EQR_UPDATECOUNT numeric(38, 10), 
            EQR_UPDATED datetime, 
            EQR_UPDATEDBY varchar, 
            EQR_VALUESLASTCALCULATED datetime, 
            _DELETED boolean, 
            ETL_DELETED boolean,
            ETL_LASTSAVED datetime, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar
            ); 