SELECT
    CASE
        WHEN TABLE_SCHEMA = 'DATAHUB_TARGET' THEN 'IPS'
        ELSE REPLACE(TABLE_SCHEMA, 'TARGET_', '')
    END SOURCE,
    COUNT(T.TABLE_NAME) AS "TABLE COUNT"
FROM ${var.ENVIRONMENT}_WCC_DATAWAREHOUSE.INFORMATION_SCHEMA.TABLES T
WHERE TABLE_TYPE = 'BASE TABLE'
    AND (
        TABLE_SCHEMA LIKE 'TARGET_%'
        OR TABLE_SCHEMA = 'DATAHUB_TARGET'
    )
    AND TABLE_SCHEMA NOT LIKE '%HISTORY%'
    AND SOURCE = :source_system
GROUP BY
    CASE
        WHEN TABLE_SCHEMA = 'DATAHUB_TARGET' THEN 'IPS'
        ELSE REPLACE(TABLE_SCHEMA, 'TARGET_', '')
    END
UNION ALL
SELECT
    CASE
        WHEN TABLE_SCHEMA = 'DATAHUB_TARGET' THEN 'IPS'
        ELSE REPLACE(TABLE_SCHEMA, 'TARGET_', '')
    END SOURCE,
    COUNT(T.TABLE_NAME) AS "TABLE COUNT"
FROM WATERLAKE_${var.ENVIRONMENT}.INFORMATION_SCHEMA.TABLES T
WHERE
    TABLE_TYPE = 'BASE TABLE'
    AND (
        TABLE_SCHEMA LIKE 'TARGET_%'
        OR TABLE_SCHEMA = 'DATAHUB_TARGET'
    )
    AND TABLE_SCHEMA NOT LIKE '%HISTORY%'
    AND SOURCE = :source_system
GROUP BY
    CASE
        WHEN TABLE_SCHEMA = 'DATAHUB_TARGET' THEN 'IPS'
        ELSE REPLACE(TABLE_SCHEMA, 'TARGET_', '')
    END