CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_IPS_WSLBILLING_SENDBILLTODELETED
            schedule  = 'USING CRON 0 * * * * UTC'
	        error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
            when
            system$stream_has_data('STREAM_IPS_WSLBILLING_SENDBILLTODELETED')
            as 
            call DATAHUB_INTEGRATION.SP_IPS_WSLBILLING_SENDBILLTODELETED() ;
            alter task DATAHUB_INTEGRATION.TASK_IPS_WSLBILLING_SENDBILLTODELETED resume;