CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_IPS_WSLSERVICEREQUESTCODES_ONEOFFCHARGESCODE
            schedule  = 'USING CRON 0 * * * * UTC'
	        error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
            when
            system$stream_has_data('STREAM_IPS_WSLSERVICEREQUESTCODES_ONEOFFCHARGESCODE')
            as 
            call DATAHUB_INTEGRATION.SP_IPS_WSLSERVICEREQUESTCODES_ONEOFFCHARGESCODE() ;
            alter task DATAHUB_INTEGRATION.TASK_IPS_WSLSERVICEREQUESTCODES_ONEOFFCHARGESCODE resume;