CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_IPS_ASSETMANAGEMENT_AGENCYDEFINED_SUBAREA
            schedule  = 'USING CRON 0 * * * * UTC'
	        error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
            when
            system$stream_has_data('STREAM_IPS_ASSETMANAGEMENT_AGENCYDEFINED_SUBAREA')
            as 
            call DATAHUB_INTEGRATION.SP_IPS_ASSETMANAGEMENT_AGENCYDEFINED_SUBAREA() ;
            alter task DATAHUB_INTEGRATION.TASK_IPS_ASSETMANAGEMENT_AGENCYDEFINED_SUBAREA resume;