CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_IPS_WSLCODESASSETSWATER_WATERMAINTENANCEREGIONS
            schedule  = 'USING CRON 0 * * * * UTC'
	        error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
            when
            system$stream_has_data('STREAM_IPS_WSLCODESASSETSWATER_WATERMAINTENANCEREGIONS')
            as 
            call DATAHUB_INTEGRATION.SP_IPS_WSLCODESASSETSWATER_WATERMAINTENANCEREGIONS() ;
            alter task DATAHUB_INTEGRATION.TASK_IPS_WSLCODESASSETSWATER_WATERMAINTENANCEREGIONS resume;