CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_IPS_ASSETMANAGEMENT_FLEET_FLEETVEHICLETYPE
            schedule  = 'USING CRON 0 * * * * UTC'
	        error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
            when
            system$stream_has_data('STREAM_IPS_ASSETMANAGEMENT_FLEET_FLEETVEHICLETYPE')
            as 
            call DATAHUB_INTEGRATION.SP_IPS_ASSETMANAGEMENT_FLEET_FLEETVEHICLETYPE() ;
            alter task DATAHUB_INTEGRATION.TASK_IPS_ASSETMANAGEMENT_FLEET_FLEETVEHICLETYPE resume;