CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_DEBITSCHEDULE(
            ACCOUNTDIRECTDEBITKEY integer, 
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BILLKEYS varchar, 
            DEBITSCHEDULEKEY integer, 
            DELETED boolean, 
            DIRECTDEBITRUN integer, 
            EXTRACTDATE datetime, 
            LASTEXTRACTDATE datetime, 
            LATESTELIGIBLEBILL integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NEXTEXTRACTDATE datetime, 
            PAYKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 