CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLPORTAL_XWRDD(
            ACCTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            DACTNAME varchar, 
            DDACCTNO varchar, 
            DDACTYPE varchar, 
            DDBANK varchar, 
            DDBRANCH varchar, 
            DDMASKNO varchar, 
            DELETED boolean, 
            EMAIL varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PHONE varchar, 
            SDLDATE datetime, 
            SERVNO integer, 
            VARIATION_ID integer, 
            XWRDDKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 