CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRBUILD_XBUILDAPPCR(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ALLOCATED varchar, 
            APBLDGKEY integer, 
            APTYPE varchar, 
            CONTRACTOR varchar, 
            DELETED boolean, 
            DEVELOPERID varchar, 
            DEVELOPMENTAREA varchar, 
            FLOORAREA varchar, 
            GISLATERAL varchar, 
            IGCZONECODE varchar, 
            MASTERAPNO varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            OWNERROLE varchar, 
            PARENTAPPLICATIONKEY integer, 
            PARENTAPTYPE varchar, 
            RELOCATIONTYPE varchar, 
            RESUBMITWORKREQUEST varchar, 
            VARIATION_ID integer, 
            XBUILDAPPCRKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 