CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_WATER_COMPWV(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            DATALAKE_DELETED boolean, 
            DIR varchar, 
            DISTRICT varchar, 
            ELEV numeric(38, 10), 
            ELEVUOM varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            EXPECTLIFE integer, 
            EXPECTLIFEUOM varchar, 
            GISSTATIC integer, 
            HIGHPRES numeric(38, 10), 
            HIGHPRESUOM varchar, 
            INSTDATE datetime, 
            INTKEY integer, 
            LOC varchar, 
            LOWPRES numeric(38, 10), 
            LOWPRESUOM varchar, 
            MAINKEY integer, 
            MAPNO varchar, 
            MFGDATE datetime, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            MTBF integer, 
            MTBFUOM varchar, 
            NOTURNS varchar, 
            OBST varchar, 
            OPERDPTH numeric(38, 10), 
            OPERDPTHUOM varchar, 
            OWN varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PRESZONE varchar, 
            PURCDATE datetime, 
            SEGKEY integer, 
            SERNO varchar, 
            SERVSTAT varchar, 
            SITEKEY integer, 
            SLKEY integer, 
            SUBAREA varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            USGTOT numeric(38, 10), 
            USGTOTUOM varchar, 
            VALVESTAT varchar, 
            VALVESZ numeric(38, 10), 
            VALVESZUOM varchar, 
            VARIATION_ID integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 