CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_USE_USEREVIEWDETAILTYPE(
            ACCESSID integer, 
            ADDBY varchar, 
            ADDCONDFRMLA integer, 
            ADDDTTM datetime, 
            APUSEREVDTLTYPEKEY integer, 
            APUSEREVIEWTYPEKEY integer, 
            CLASSNAME varchar, 
            DELETED boolean, 
            DESCRIPT varchar, 
            DISPLAY integer, 
            DISPLAYORDER integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            MODBY varchar, 
            MODDTTM datetime, 
            PAGEPATH varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 