CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_USE_USEINSPTYPE(
            ADDBY varchar, 
            ADDCONDFRMLA integer, 
            ADDDTTM datetime, 
            APUSEDEFNKEY integer, 
            APUSEINSPTYPEKEY integer, 
            APUSEPROCESSSTATEKEY integer, 
            ASSGNGRPFRMLA integer, 
            DELETED boolean, 
            DESCRIPT varchar, 
            DPDESC varchar, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            INSPSCHEDCONDFRMLA integer, 
            INSPTYPE varchar, 
            INTERNALONLYFLAG varchar, 
            ISPUBLIC varchar, 
            MAXINSPFEETYPEKEY integer, 
            MAXINSPFRMLA integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            ORD integer, 
            PORTALDESCRIPTION varchar, 
            REINSPFEE integer, 
            REINSPFEEFRMLA integer, 
            SHOWINPORTAL varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 