CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PLANNING_PLANPROCESSSTATE(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPLANDEFNKEY integer, 
            APPLANPROCESSSTATEKEY integer, 
            APPLEXPDATECALCREQD varchar, 
            CODE varchar, 
            COMPLETEDSTATEFLAG varchar, 
            DATALAKE_DELETED boolean, 
            DISPLAYORDER integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            INITIALSTATEFLAG varchar, 
            ISPUBLIC varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NEXTSTATEFRMLA integer, 
            NEXTSTATEKEY integer, 
            PLANAPPLSTATUS varchar, 
            SETSTATDATE varchar, 
            STAT varchar, 
            STATDATETYPE integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 