CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_WATER_COMPWSL(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGKEY integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            CRITSRV varchar, 
            CURBSTOP varchar, 
            DATALAKE_DELETED boolean, 
            DBNO varchar, 
            DIAM numeric(38, 10), 
            DIAMUOM varchar, 
            DISTRICT varchar, 
            EPAID varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            FIRELINE varchar, 
            GISSTATIC integer, 
            INSTDATE datetime, 
            LOC varchar, 
            MAINKEY integer, 
            MAPNO varchar, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NPDESID varchar, 
            OWN varchar, 
            PIPELEN numeric(38, 10), 
            PIPELENUOM varchar, 
            PIPETYPE varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PRESZONE varchar, 
            SEGKEY integer, 
            SERVSTAT varchar, 
            SIC varchar, 
            SITEKEY integer, 
            SRVTYPE varchar, 
            SUBAREA varchar, 
            SURF varchar, 
            TAPADDRKEY integer, 
            TAPLOC varchar, 
            UICID varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            VARIATION_ID integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 