CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLTRADEBILLOUTPUT_TRADEBILLOUTPUTEXT(
            ACCOUNTKEY integer, 
            ACCOUNTNUMBER varchar, 
            ACCTCLASS varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            BARCODEAMOUNT varchar, 
            BARCODECHECKDIGIT varchar, 
            BILLKEY integer, 
            BILLRUNKEY integer, 
            CHECKDIGIT varchar, 
            CUSTOMERREF varchar, 
            DATALAKE_DELETED boolean, 
            DDFLAG varchar, 
            DTLRCT datetime, 
            FILENAME varchar, 
            MICRCHECKDIGIT varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PREVBILLAMT numeric(38, 10), 
            TRADEBILLOUTPUTEXTKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 