CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_PROPERTY_PARCEL(
            ADDBY varchar, 
            ADDDTTM datetime, 
            AREA varchar, 
            ATLASPAGE varchar, 
            BLOCK varchar, 
            COMMELEM numeric(38, 10), 
            COUNTY varchar, 
            CURRPRCL varchar, 
            DELETED boolean, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            LEGALOWNER varchar, 
            LNDPRICETY varchar, 
            LOT varchar, 
            LOTDPTH numeric(38, 10), 
            LOTFRONTAG numeric(38, 10), 
            LOTSHP varchar, 
            LOTSZ numeric(38, 10), 
            LOTUM varchar, 
            MAPNO varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PLANMEDIA varchar, 
            PRCLID varchar, 
            PRCLKEY integer, 
            PRCLNAME varchar, 
            PRCLSTAT varchar, 
            PRCLTYPE varchar, 
            PROPNOTE varchar, 
            RANGE varchar, 
            SECTION varchar, 
            SUBDIV varchar, 
            SUBDIVCODE varchar, 
            SUBOFKEY integer, 
            TOWNSHIP varchar, 
            VARIATION_ID integer, 
            VERSION integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 