CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_WATER_COMPWMN(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            ASBLT varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            CLASS varchar, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            CORRFACTOR numeric(38, 10), 
            DATALAKE_DELETED boolean, 
            DIAM numeric(38, 10), 
            DIAMUOM varchar, 
            DIRFRNODE1 varchar, 
            DIRFRNODE2 varchar, 
            DISTRICT varchar, 
            DPTH numeric(38, 10), 
            DPTHUOM varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            FFACTOR numeric(38, 10), 
            FROSTDPTH numeric(38, 10), 
            FROSTDPTHUOM varchar, 
            GAUGE varchar, 
            GISSTATIC integer, 
            INSTDATE datetime, 
            JTLEN numeric(38, 10), 
            JTLENUOM varchar, 
            JTTYPE varchar, 
            LOC varchar, 
            LOCATOR varchar, 
            MAINCOMP1 integer, 
            MAINCOMP2 integer, 
            MAINKEY1 integer, 
            MAINKEY2 integer, 
            MAPNO varchar, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            OWN varchar, 
            PARLINENO varchar, 
            PIPELEN numeric(38, 10), 
            PIPELENUOM varchar, 
            PIPETYPE varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PRESZONE varchar, 
            SCHED varchar, 
            SEGKEY integer, 
            SEGMENT varchar, 
            SERVSTAT varchar, 
            SITEKEY integer, 
            SOILTYPE varchar, 
            SUBAREA varchar, 
            SURF varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITID2 varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            VARIATION_ID integer, 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 