CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLASSETSCONFIGURED_XRETAINSTRUTURE(
            ACCELDEPREC varchar, 
            ACCELDEPRECDESC varchar, 
            ACQTYPE varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            AREA numeric(38, 10), 
            BUSINESSAREA varchar, 
            CAPACITY numeric(38, 10), 
            COMPKEY integer, 
            CONFINEDSPACE varchar, 
            COSTCENTRE varchar, 
            CRITICALITY varchar, 
            DATALAKE_DELETED boolean, 
            DESIGNRESILIENCE varchar, 
            DISCHARGECAP numeric(38, 10), 
            DISPOSALDESC varchar, 
            DRAWINGNO varchar, 
            DRAWINGNOREF varchar, 
            FORDISPOSAL varchar, 
            FUNCAREA varchar, 
            GRDLEVEL numeric(38, 10), 
            INHIBITLEVEL numeric(38, 10), 
            INSTALLMOUNT varchar, 
            INTLINING varchar, 
            INVLEVEL numeric(38, 10), 
            LINKEDASSET varchar, 
            MAKE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            OVERFLOWLEVEL numeric(38, 10), 
            PHOTO3D varchar, 
            PROJECTNO varchar, 
            PROJECTWISE varchar, 
            QUAKEDESIGN varchar, 
            RELDATE varchar, 
            RELDEPTH varchar, 
            RELDIA varchar, 
            RELGEOSP varchar, 
            RELMATL varchar, 
            RELOWN varchar, 
            RELSTATUS varchar, 
            SAFETYCRITICAL varchar, 
            SPILLWAYTYPE varchar, 
            SUBTYPEFEATURES varchar, 
            VARIATION_ID integer, 
            WARRANTYEND datetime, 
            WARRANTYSTART datetime, 
            XRETAINSTRUTUREKEY integer, 
            ZONECATCHMENT varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 