CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLASSETWATER_XSRRETAILAUDITMETERGD(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            COMPKEY integer, 
            DATALAKE_DELETED boolean, 
            DEACTIVATE varchar, 
            FREQUENCY varchar, 
            HOUSENUMBER varchar, 
            INSTALLEDDATE datetime, 
            METERID varchar, 
            METERLOCATION varchar, 
            METERTYPE varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            NUMBEROFDIALS integer, 
            OLDMETERID varchar, 
            PHONENUMBER varchar, 
            REMOVEDDATE datetime, 
            ROUTEID varchar, 
            SERVNO integer, 
            SMS varchar, 
            STREETNAME varchar, 
            STREETTYPE varchar, 
            SUBURB varchar, 
            UNITNUMBER varchar, 
            VARIATION_ID integer, 
            XSRRETAILAUDITMETERDPKEY integer, 
            XSRRETAILAUDITMETERGDKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 