CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_ACCOUNTDELINQUENCY(
            ACCOUNTDELINQUENCYKEY integer, 
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESSLIENKEY integer, 
            BILLKEY integer, 
            BILLTYPEKEY integer, 
            COLLECTIONSKEY integer, 
            COMMENTS varchar, 
            DATALAKE_DELETED boolean, 
            DELINQUENCYENTRYAMOUNT numeric(38, 10), 
            DELINQUENCYENTRYDATE datetime, 
            DELINQUENCYLEVEL varchar, 
            DELINQUENCYMANAGER varchar, 
            DELINQUENCYOFFICER varchar, 
            DELINQUENTTHROUGHDATE datetime, 
            EXTENSION integer, 
            HOLDFLAG varchar, 
            MILESTONEDUEDATE datetime, 
            MILESTONEENTRYDATE datetime, 
            MILESTONEKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            NEXTMILESTONEDATE datetime, 
            PARCELLIENKEY integer, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 