CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCRM_XRETAILAUDITGD(
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSETKEY integer, 
            BLUSAGEDIFF varchar, 
            DELETED boolean, 
            FIELDNAME varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODIFIEDBYEMPLOYEE varchar, 
            MODIFIEDDATE datetime, 
            NEWBLUSAGE varchar, 
            NEWVALUE varchar, 
            PREVIOUSBLUSAGE varchar, 
            PREVIOUSVALUE varchar, 
            READINGDATE datetime, 
            READINGKEY integer, 
            SOURCEID varchar, 
            VALDIFF varchar, 
            VARIATION_ID integer, 
            XRETAILAUDITDPKEY integer, 
            XRETAILAUDITGDKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 