CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CDR_PROJECT_PROJPROCSTATECHECK(
            ADDBY varchar, 
            ADDDTTM datetime, 
            APPROJPROCESSSTATEKEY integer, 
            APPROJPROCSTATECHKKEY integer, 
            CHECKFRMLA integer, 
            CHECKTITLE varchar, 
            CHECKTYPE integer, 
            DATALAKE_DELETED boolean, 
            DPDESC varchar, 
            EFFDATE datetime, 
            EXCLUDEFROMPENDINGPORTAL varchar, 
            EXPDATE datetime, 
            INTERNALONLYFLAG varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            PORTALDESCRIPTION varchar, 
            SHOWINPORTAL varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 