CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_DELINQUENCYHISTORY(
            ACCOUNTKEY integer, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRESSLIENKEY integer, 
            AUTODECANDRESPAYPOSTDTTM datetime, 
            BILLKEY integer, 
            BILLTYPEKEY integer, 
            COLLECTIONSKEY integer, 
            COLLECTIONSRUNKEY integer, 
            COMMENTS varchar, 
            DELETED boolean, 
            DELINQUENCYENTRYAMOUNT numeric(38, 10), 
            DELINQUENCYENTRYBALANCE numeric(38, 10), 
            DELINQUENCYENTRYDATE datetime, 
            DELINQUENCYHISTORYKEY integer, 
            DELINQUENCYLEVEL varchar, 
            DELINQUENCYMANAGER varchar, 
            DELINQUENCYOFFICER varchar, 
            DELINQUENCYRUNKEY integer, 
            DELINQUENTAMOUNT numeric(38, 10), 
            DELINQUENTTHROUGHDATE datetime, 
            DISPLAYHISTORYRECORD varchar, 
            EXTENSION integer, 
            HOLDFLAG varchar, 
            MILESTONEDUEDATE datetime, 
            MILESTONEENTRYDATE datetime, 
            MILESTONEENTRYREASON varchar, 
            MILESTONEKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            PARCELLIENKEY integer, 
            PROCESSINGRUNKEY integer, 
            RESOLUTION varchar, 
            RESOLVEDBY varchar, 
            RESOLVEDDATE datetime, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 