CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLTRADEBILLOUTPUT_LOADTRADEONEOFFCHARGES(
            ACCOUNTKEY integer, 
            ACCOUNTNUMBER varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            CHARGEAMOUNT varchar, 
            CHARGEDATE varchar, 
            CHARGETYPE varchar, 
            DATALAKE_DELETED boolean, 
            FILEEXTENSION varchar, 
            FILENAME varchar, 
            LINEITEMSETUPKEY integer, 
            LOADTRADEONEOFFCHARGESKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            ONEOFFCHARGEKEY integer, 
            STATUS varchar, 
            STATUSMSG varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 