CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CASHIERING_CASHREGISTER(
            ADDBY varchar, 
            ADDDTTM datetime, 
            CASHSETUP integer, 
            CHECKSETUP integer, 
            CPUSERIAL varchar, 
            CREDITSETUP integer, 
            DEBITSETUP integer, 
            DELETED boolean, 
            EFFDATE datetime, 
            ESCROWSETUP integer, 
            EXPDATE datetime, 
            ISENDORSECHECK varchar, 
            ISPRINTSIGNATURESLIP varchar, 
            ISSHOWRECEIPTAPPLET varchar, 
            ISUSINGREGISTERGROUP varchar, 
            LOC varchar, 
            MACHINENAME varchar, 
            MACID varchar, 
            MISCSETUP integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            PAYMENTTERMINALFORMULAKEY integer, 
            RECEIPTCOPIES integer, 
            REGID varchar, 
            REGISTERGROUPSETUPKEY integer, 
            REGKEY integer, 
            REGTYPE varchar, 
            SCANNERFORMULAKEY integer, 
            SUPERVISOR varchar, 
            VALIDATEMACHINENAME varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 