CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_ASSETMANAGEMENT_FLEET_COMPVEH(
            ADDBY varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            ADDRQUAL varchar, 
            AREA varchar, 
            AVGMONUSG numeric(38, 10), 
            AVGMONUSGUOM varchar, 
            AXLE varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            COMPKEY integer, 
            COMPLEXKEY integer, 
            CYLINDERS integer, 
            DATALAKE_DELETED boolean, 
            DISTRICT varchar, 
            DRIVERCLAS varchar, 
            ENGINENO varchar, 
            ENGINETYPE varchar, 
            EXPBY varchar, 
            EXPDATE datetime, 
            EXPECTLIFE integer, 
            EXPECTLIFEUOM varchar, 
            GVW varchar, 
            GVWUOM varchar, 
            INSTDATE datetime, 
            INTKEY integer, 
            LICENSE varchar, 
            LOC varchar, 
            MAPNO varchar, 
            MFGDATE datetime, 
            MFGKEY integer, 
            MODBY varchar, 
            MODDTTM datetime, 
            MODELNO varchar, 
            MODELYR varchar, 
            MTBF integer, 
            NOTIRES integer, 
            OWN varchar, 
            POSITION integer, 
            PRCLKEY integer, 
            PURCCOST numeric(38, 10), 
            PURCDATE datetime, 
            SERNO varchar, 
            SERVSTAT varchar, 
            SITEKEY integer, 
            SUBAREA varchar, 
            TIRESIZE varchar, 
            TIRETYPE varchar, 
            TRANSMISSN varchar, 
            UNITDESC varchar, 
            UNITID varchar, 
            UNITTYPE varchar, 
            USGAREAKEY integer, 
            USGDATE datetime, 
            USGTOT numeric(38, 10), 
            USGTOTUOM varchar, 
            VARIATION_ID integer, 
            VEHSZ varchar, 
            VEHSZUOM varchar, 
            VIN varchar, 
            WARREXP datetime, 
            WARRUSG numeric(38, 10), 
            XCOORD numeric(38, 10), 
            YCOORD numeric(38, 10), 
            ZCOORD numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 