CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_WSLCDRPLAN_XPLANDPACTIONLISTGD(
            ACTIONNOTES varchar, 
            ACTIONOWNER varchar, 
            ACTIONSTATUS varchar, 
            ACTIONTYPE varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ASSIGNEDT1 varchar, 
            ASSIGNEDTO varchar, 
            COMPLETEDDATE datetime, 
            CREATEDATE datetime, 
            DELETED boolean, 
            DETAILS varchar, 
            DUEDATE datetime, 
            MODBY varchar, 
            MODDTTM datetime, 
            RESPONSIBLE varchar, 
            REVIEWID integer, 
            VARIATION_ID integer, 
            XPLANDPACTIONLISTGDKEY integer, 
            XPLANDPACTIONLISTKEY integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 