CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_CRM_CUSTPROB(
            ACCTKEY integer, 
            ADDBY varchar, 
            ADDBYBASEUSR varchar, 
            ADDBYPORTALUSR varchar, 
            ADDDTTM datetime, 
            ADDRKEY integer, 
            APKEY integer, 
            AREA varchar, 
            ASGNFLAG varchar, 
            ASSETINSPFLAG varchar, 
            BGTNO varchar, 
            BLDGFLOOR integer, 
            BLDGROOM integer, 
            BUDGETKEY integer, 
            CASEFLAG varchar, 
            CLERICDTTM datetime, 
            COMMENTS varchar, 
            COMPKEY integer, 
            CUSTFLAG varchar, 
            DATALAKE_DELETED boolean, 
            DISTFROMFT numeric(38, 10), 
            DISTFROMM numeric(38, 10), 
            DISTRICT varchar, 
            DISTTOFT numeric(38, 10), 
            DISTTOM numeric(38, 10), 
            EMAILNOTICE varchar, 
            IMPACT integer, 
            INCDTDTTM datetime, 
            INSPDAYS integer, 
            INSPDTTM datetime, 
            INSPECTR varchar, 
            INSPFLAG varchar, 
            INSPHRS integer, 
            INSPMINS integer, 
            INWORKFLAG varchar, 
            LOC varchar, 
            LOCNOTES varchar, 
            MAPNO varchar, 
            MOBILE varchar, 
            MOBILEDTTM datetime, 
            MOBILEEMP varchar, 
            MODBY varchar, 
            MODBYBASEUSR varchar, 
            MODBYPORTALUSR varchar, 
            MODDTTM datetime, 
            MOREWORK varchar, 
            OOCFLAG varchar, 
            PRCLKEY integer, 
            PRI varchar, 
            PROB integer, 
            PROBDTTM datetime, 
            PROJ varchar, 
            PROPKEY integer, 
            QTYCALLS integer, 
            REFNO varchar, 
            RESCODE varchar, 
            RESDTTM datetime, 
            RESDUEDTTM datetime, 
            RESFLAG varchar, 
            RESP varchar, 
            SCDCMPDTTM datetime, 
            SCHDUEDTTM datetime, 
            SCHEDDTTM datetime, 
            SERVLINK integer, 
            SERVNO integer, 
            SEVERITY integer, 
            SRC varchar, 
            SRTYPE varchar, 
            STARTDTTM datetime, 
            STDUEDTTM datetime, 
            SUBAREA varchar, 
            SUSPDTTM datetime, 
            TAKENBY varchar, 
            VARIATION_ID integer, 
            WOFLAG varchar, 
            XCOORDINATE numeric(38, 10), 
            YCOORDINATE numeric(38, 10), 
            ZCOORDINATE numeric(38, 10), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 