CREATE OR REPLACE TABLE DATAHUB_TARGET_HISTORY.IPS_DELETED_BILLING_ACCOUNTALERT(
            ACCOUNTALERTKEY integer, 
            ACCOUNTDELINQUENCYKEY integer, 
            ACCOUNTKEY integer, 
            ACCTALERTTYPE varchar, 
            ADDBY varchar, 
            ADDDTTM datetime, 
            ALERTDEFNKEY integer, 
            APPENDEDALERTTEXT varchar, 
            BANKRUPTCYKEY integer, 
            COMMENTS varchar, 
            DATALAKE_DELETED boolean, 
            DELINQUENCYMSALERTKEY integer, 
            EFFDATE datetime, 
            EXPDATE datetime, 
            INITIATEDBY varchar, 
            MODBY varchar, 
            MODDTTM datetime, 
            REASON varchar, 
            RESOLUTION varchar, 
            RESOLVEDBY varchar, 
            VARIATION_ID integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 