create or replace view VW_SM_PORTAL_DAILY(
	IPS_ACCOUNTNUMBER,
	M_METER_TIME,
	M_VALUE,
	IPS_CONSUMPTIONPERCENTAGE
) as
			SELECT 
			i.IPS_ACCOUNTNUMBER
			,concat(s.M_METER_TIME,'#',s.M_UNIT_ID) AS M_METER_TIME
			,M_VALUE*IPS_CONSUMPTIONPERCENTAGE AS M_VALUE
			,IPS_CONSUMPTIONPERCENTAGE
			FROM 
			( select distinct
			  M_UNIT_ID
			  ,M_METER_TIME
			  ,M_VALUE
			 FROM 
			 DATAHUB_TARGET.SM_APSY_SMINF_CUR
			 WHERE M_BILLING =TRUE  AND M_RESOURCE_TYPE ='Water_Flow_Readings_Total_Daily'
			 ) s JOIN DATAHUB_TARGET.VW_IPS_SM_ACCOUNT_UNITID i ON i.IPS_UNITID=s.M_UNIT_ID
			 INNER JOIN (SELECT DISTINCT SMARTMETERID FROM DATAHUB_LANDING.SM_APSY_SMINF_PILOT WHERE READYFORLIVE ='y') pilot ON pilot.SMARTMETERID=s.M_UNIT_ID;