CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_IPS_INF_VALUATION_VALUATION_ASSVALRESERVEGD
            schedule  = 'USING CRON 0 * * * * UTC'
	        error_integration = ${buildvar.env}_NOTIFICATION_INTEGRATION_TASK
            when
            system$stream_has_data('STREAM_IPS_INF_VALUATION_VALUATION_ASSVALRESERVEGD')
            as 
            call DATAHUB_INTEGRATION.SP_IPS_INF_VALUATION_VALUATION_ASSVALRESERVEGD() ;
            alter task DATAHUB_INTEGRATION.TASK_IPS_INF_VALUATION_VALUATION_ASSVALRESERVEGD resume;