
name: 'watercare_acquisition'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  watercare_acquisition:
    curated:
      depm:
        +database: curated # Override
        +materialized: table
        +schema: depm
        p100: # Schema misalignment, src:Value - mixture of numbers/strings typed as float
          +enabled: false
      eam:
        +database: curated # Override
        +materialized: table
        +schema: eam
      ips:
        +database: curated # Override
        +materialized: table
        +schema: ips
      ln:
        +database: curated # Override
        +materialized: table
        +schema: ln
