CREATE OR REPLACE TASK DATAHUB_INTEGRATION.TASK_EAM_U5REQADDRESOURCES
                    schedule  = 'USING CRON 0 4 * * * Pacific/Auckland'
    when
    system$stream_has_data('STREAM_EAM_U5REQADDRESOURCES')
  as 
call EAM_TARGET_MERGE_U5REQADDRESOURCES();
alter task DATAHUB_INTEGRATION.TASK_EAM_U5REQADDRESOURCES resume;
