create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5REPORTFILTERS()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5REPORTFILTERS_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5REPORTFILTERS as target using (SELECT * FROM (SELECT 
            strm.RFI_CHKBOX1, 
            strm.RFI_CHKBOX10, 
            strm.RFI_CHKBOX11, 
            strm.RFI_CHKBOX12, 
            strm.RFI_CHKBOX13, 
            strm.RFI_CHKBOX14, 
            strm.RFI_CHKBOX15, 
            strm.RFI_CHKBOX16, 
            strm.RFI_CHKBOX17, 
            strm.RFI_CHKBOX18, 
            strm.RFI_CHKBOX19, 
            strm.RFI_CHKBOX2, 
            strm.RFI_CHKBOX20, 
            strm.RFI_CHKBOX21, 
            strm.RFI_CHKBOX22, 
            strm.RFI_CHKBOX23, 
            strm.RFI_CHKBOX24, 
            strm.RFI_CHKBOX25, 
            strm.RFI_CHKBOX3, 
            strm.RFI_CHKBOX4, 
            strm.RFI_CHKBOX5, 
            strm.RFI_CHKBOX6, 
            strm.RFI_CHKBOX7, 
            strm.RFI_CHKBOX8, 
            strm.RFI_CHKBOX9, 
            strm.RFI_DEFAULT, 
            strm.RFI_FROMDATE, 
            strm.RFI_FUNC, 
            strm.RFI_GROUPBY, 
            strm.RFI_LASTSAVED, 
            strm.RFI_NAME, 
            strm.RFI_ORDERBY, 
            strm.RFI_ORDERTYPE, 
            strm.RFI_ORG, 
            strm.RFI_PARAM1, 
            strm.RFI_PARAM10, 
            strm.RFI_PARAM11, 
            strm.RFI_PARAM12, 
            strm.RFI_PARAM13, 
            strm.RFI_PARAM14, 
            strm.RFI_PARAM15, 
            strm.RFI_PARAM16, 
            strm.RFI_PARAM17, 
            strm.RFI_PARAM18, 
            strm.RFI_PARAM19, 
            strm.RFI_PARAM2, 
            strm.RFI_PARAM20, 
            strm.RFI_PARAM21, 
            strm.RFI_PARAM22, 
            strm.RFI_PARAM23, 
            strm.RFI_PARAM24, 
            strm.RFI_PARAM25, 
            strm.RFI_PARAM26, 
            strm.RFI_PARAM27, 
            strm.RFI_PARAM28, 
            strm.RFI_PARAM29, 
            strm.RFI_PARAM3, 
            strm.RFI_PARAM30, 
            strm.RFI_PARAM31, 
            strm.RFI_PARAM32, 
            strm.RFI_PARAM33, 
            strm.RFI_PARAM34, 
            strm.RFI_PARAM35, 
            strm.RFI_PARAM36, 
            strm.RFI_PARAM37, 
            strm.RFI_PARAM38, 
            strm.RFI_PARAM39, 
            strm.RFI_PARAM4, 
            strm.RFI_PARAM40, 
            strm.RFI_PARAM5, 
            strm.RFI_PARAM6, 
            strm.RFI_PARAM7, 
            strm.RFI_PARAM8, 
            strm.RFI_PARAM9, 
            strm.RFI_RADIO, 
            strm.RFI_TODATE, 
            strm.RFI_UPDATECOUNT, 
            strm.RFI_UPDATED, 
            strm.RFI_USER, 
            strm.RFI_VISFLDS, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.RFI_USER,
            strm.RFI_FUNC,
            strm.RFI_NAME ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5REPORTFILTERS as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.RFI_USER=src.RFI_USER) OR (target.RFI_USER IS NULL AND src.RFI_USER IS NULL)) AND
            ((target.RFI_FUNC=src.RFI_FUNC) OR (target.RFI_FUNC IS NULL AND src.RFI_FUNC IS NULL)) AND
            ((target.RFI_NAME=src.RFI_NAME) OR (target.RFI_NAME IS NULL AND src.RFI_NAME IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.RFI_CHKBOX1=src.RFI_CHKBOX1, 
                    target.RFI_CHKBOX10=src.RFI_CHKBOX10, 
                    target.RFI_CHKBOX11=src.RFI_CHKBOX11, 
                    target.RFI_CHKBOX12=src.RFI_CHKBOX12, 
                    target.RFI_CHKBOX13=src.RFI_CHKBOX13, 
                    target.RFI_CHKBOX14=src.RFI_CHKBOX14, 
                    target.RFI_CHKBOX15=src.RFI_CHKBOX15, 
                    target.RFI_CHKBOX16=src.RFI_CHKBOX16, 
                    target.RFI_CHKBOX17=src.RFI_CHKBOX17, 
                    target.RFI_CHKBOX18=src.RFI_CHKBOX18, 
                    target.RFI_CHKBOX19=src.RFI_CHKBOX19, 
                    target.RFI_CHKBOX2=src.RFI_CHKBOX2, 
                    target.RFI_CHKBOX20=src.RFI_CHKBOX20, 
                    target.RFI_CHKBOX21=src.RFI_CHKBOX21, 
                    target.RFI_CHKBOX22=src.RFI_CHKBOX22, 
                    target.RFI_CHKBOX23=src.RFI_CHKBOX23, 
                    target.RFI_CHKBOX24=src.RFI_CHKBOX24, 
                    target.RFI_CHKBOX25=src.RFI_CHKBOX25, 
                    target.RFI_CHKBOX3=src.RFI_CHKBOX3, 
                    target.RFI_CHKBOX4=src.RFI_CHKBOX4, 
                    target.RFI_CHKBOX5=src.RFI_CHKBOX5, 
                    target.RFI_CHKBOX6=src.RFI_CHKBOX6, 
                    target.RFI_CHKBOX7=src.RFI_CHKBOX7, 
                    target.RFI_CHKBOX8=src.RFI_CHKBOX8, 
                    target.RFI_CHKBOX9=src.RFI_CHKBOX9, 
                    target.RFI_DEFAULT=src.RFI_DEFAULT, 
                    target.RFI_FROMDATE=src.RFI_FROMDATE, 
                    target.RFI_FUNC=src.RFI_FUNC, 
                    target.RFI_GROUPBY=src.RFI_GROUPBY, 
                    target.RFI_LASTSAVED=src.RFI_LASTSAVED, 
                    target.RFI_NAME=src.RFI_NAME, 
                    target.RFI_ORDERBY=src.RFI_ORDERBY, 
                    target.RFI_ORDERTYPE=src.RFI_ORDERTYPE, 
                    target.RFI_ORG=src.RFI_ORG, 
                    target.RFI_PARAM1=src.RFI_PARAM1, 
                    target.RFI_PARAM10=src.RFI_PARAM10, 
                    target.RFI_PARAM11=src.RFI_PARAM11, 
                    target.RFI_PARAM12=src.RFI_PARAM12, 
                    target.RFI_PARAM13=src.RFI_PARAM13, 
                    target.RFI_PARAM14=src.RFI_PARAM14, 
                    target.RFI_PARAM15=src.RFI_PARAM15, 
                    target.RFI_PARAM16=src.RFI_PARAM16, 
                    target.RFI_PARAM17=src.RFI_PARAM17, 
                    target.RFI_PARAM18=src.RFI_PARAM18, 
                    target.RFI_PARAM19=src.RFI_PARAM19, 
                    target.RFI_PARAM2=src.RFI_PARAM2, 
                    target.RFI_PARAM20=src.RFI_PARAM20, 
                    target.RFI_PARAM21=src.RFI_PARAM21, 
                    target.RFI_PARAM22=src.RFI_PARAM22, 
                    target.RFI_PARAM23=src.RFI_PARAM23, 
                    target.RFI_PARAM24=src.RFI_PARAM24, 
                    target.RFI_PARAM25=src.RFI_PARAM25, 
                    target.RFI_PARAM26=src.RFI_PARAM26, 
                    target.RFI_PARAM27=src.RFI_PARAM27, 
                    target.RFI_PARAM28=src.RFI_PARAM28, 
                    target.RFI_PARAM29=src.RFI_PARAM29, 
                    target.RFI_PARAM3=src.RFI_PARAM3, 
                    target.RFI_PARAM30=src.RFI_PARAM30, 
                    target.RFI_PARAM31=src.RFI_PARAM31, 
                    target.RFI_PARAM32=src.RFI_PARAM32, 
                    target.RFI_PARAM33=src.RFI_PARAM33, 
                    target.RFI_PARAM34=src.RFI_PARAM34, 
                    target.RFI_PARAM35=src.RFI_PARAM35, 
                    target.RFI_PARAM36=src.RFI_PARAM36, 
                    target.RFI_PARAM37=src.RFI_PARAM37, 
                    target.RFI_PARAM38=src.RFI_PARAM38, 
                    target.RFI_PARAM39=src.RFI_PARAM39, 
                    target.RFI_PARAM4=src.RFI_PARAM4, 
                    target.RFI_PARAM40=src.RFI_PARAM40, 
                    target.RFI_PARAM5=src.RFI_PARAM5, 
                    target.RFI_PARAM6=src.RFI_PARAM6, 
                    target.RFI_PARAM7=src.RFI_PARAM7, 
                    target.RFI_PARAM8=src.RFI_PARAM8, 
                    target.RFI_PARAM9=src.RFI_PARAM9, 
                    target.RFI_RADIO=src.RFI_RADIO, 
                    target.RFI_TODATE=src.RFI_TODATE, 
                    target.RFI_UPDATECOUNT=src.RFI_UPDATECOUNT, 
                    target.RFI_UPDATED=src.RFI_UPDATED, 
                    target.RFI_USER=src.RFI_USER, 
                    target.RFI_VISFLDS=src.RFI_VISFLDS, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    RFI_CHKBOX1, 
                    RFI_CHKBOX10, 
                    RFI_CHKBOX11, 
                    RFI_CHKBOX12, 
                    RFI_CHKBOX13, 
                    RFI_CHKBOX14, 
                    RFI_CHKBOX15, 
                    RFI_CHKBOX16, 
                    RFI_CHKBOX17, 
                    RFI_CHKBOX18, 
                    RFI_CHKBOX19, 
                    RFI_CHKBOX2, 
                    RFI_CHKBOX20, 
                    RFI_CHKBOX21, 
                    RFI_CHKBOX22, 
                    RFI_CHKBOX23, 
                    RFI_CHKBOX24, 
                    RFI_CHKBOX25, 
                    RFI_CHKBOX3, 
                    RFI_CHKBOX4, 
                    RFI_CHKBOX5, 
                    RFI_CHKBOX6, 
                    RFI_CHKBOX7, 
                    RFI_CHKBOX8, 
                    RFI_CHKBOX9, 
                    RFI_DEFAULT, 
                    RFI_FROMDATE, 
                    RFI_FUNC, 
                    RFI_GROUPBY, 
                    RFI_LASTSAVED, 
                    RFI_NAME, 
                    RFI_ORDERBY, 
                    RFI_ORDERTYPE, 
                    RFI_ORG, 
                    RFI_PARAM1, 
                    RFI_PARAM10, 
                    RFI_PARAM11, 
                    RFI_PARAM12, 
                    RFI_PARAM13, 
                    RFI_PARAM14, 
                    RFI_PARAM15, 
                    RFI_PARAM16, 
                    RFI_PARAM17, 
                    RFI_PARAM18, 
                    RFI_PARAM19, 
                    RFI_PARAM2, 
                    RFI_PARAM20, 
                    RFI_PARAM21, 
                    RFI_PARAM22, 
                    RFI_PARAM23, 
                    RFI_PARAM24, 
                    RFI_PARAM25, 
                    RFI_PARAM26, 
                    RFI_PARAM27, 
                    RFI_PARAM28, 
                    RFI_PARAM29, 
                    RFI_PARAM3, 
                    RFI_PARAM30, 
                    RFI_PARAM31, 
                    RFI_PARAM32, 
                    RFI_PARAM33, 
                    RFI_PARAM34, 
                    RFI_PARAM35, 
                    RFI_PARAM36, 
                    RFI_PARAM37, 
                    RFI_PARAM38, 
                    RFI_PARAM39, 
                    RFI_PARAM4, 
                    RFI_PARAM40, 
                    RFI_PARAM5, 
                    RFI_PARAM6, 
                    RFI_PARAM7, 
                    RFI_PARAM8, 
                    RFI_PARAM9, 
                    RFI_RADIO, 
                    RFI_TODATE, 
                    RFI_UPDATECOUNT, 
                    RFI_UPDATED, 
                    RFI_USER, 
                    RFI_VISFLDS, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.RFI_CHKBOX1, 
                    src.RFI_CHKBOX10, 
                    src.RFI_CHKBOX11, 
                    src.RFI_CHKBOX12, 
                    src.RFI_CHKBOX13, 
                    src.RFI_CHKBOX14, 
                    src.RFI_CHKBOX15, 
                    src.RFI_CHKBOX16, 
                    src.RFI_CHKBOX17, 
                    src.RFI_CHKBOX18, 
                    src.RFI_CHKBOX19, 
                    src.RFI_CHKBOX2, 
                    src.RFI_CHKBOX20, 
                    src.RFI_CHKBOX21, 
                    src.RFI_CHKBOX22, 
                    src.RFI_CHKBOX23, 
                    src.RFI_CHKBOX24, 
                    src.RFI_CHKBOX25, 
                    src.RFI_CHKBOX3, 
                    src.RFI_CHKBOX4, 
                    src.RFI_CHKBOX5, 
                    src.RFI_CHKBOX6, 
                    src.RFI_CHKBOX7, 
                    src.RFI_CHKBOX8, 
                    src.RFI_CHKBOX9, 
                    src.RFI_DEFAULT, 
                    src.RFI_FROMDATE, 
                    src.RFI_FUNC, 
                    src.RFI_GROUPBY, 
                    src.RFI_LASTSAVED, 
                    src.RFI_NAME, 
                    src.RFI_ORDERBY, 
                    src.RFI_ORDERTYPE, 
                    src.RFI_ORG, 
                    src.RFI_PARAM1, 
                    src.RFI_PARAM10, 
                    src.RFI_PARAM11, 
                    src.RFI_PARAM12, 
                    src.RFI_PARAM13, 
                    src.RFI_PARAM14, 
                    src.RFI_PARAM15, 
                    src.RFI_PARAM16, 
                    src.RFI_PARAM17, 
                    src.RFI_PARAM18, 
                    src.RFI_PARAM19, 
                    src.RFI_PARAM2, 
                    src.RFI_PARAM20, 
                    src.RFI_PARAM21, 
                    src.RFI_PARAM22, 
                    src.RFI_PARAM23, 
                    src.RFI_PARAM24, 
                    src.RFI_PARAM25, 
                    src.RFI_PARAM26, 
                    src.RFI_PARAM27, 
                    src.RFI_PARAM28, 
                    src.RFI_PARAM29, 
                    src.RFI_PARAM3, 
                    src.RFI_PARAM30, 
                    src.RFI_PARAM31, 
                    src.RFI_PARAM32, 
                    src.RFI_PARAM33, 
                    src.RFI_PARAM34, 
                    src.RFI_PARAM35, 
                    src.RFI_PARAM36, 
                    src.RFI_PARAM37, 
                    src.RFI_PARAM38, 
                    src.RFI_PARAM39, 
                    src.RFI_PARAM4, 
                    src.RFI_PARAM40, 
                    src.RFI_PARAM5, 
                    src.RFI_PARAM6, 
                    src.RFI_PARAM7, 
                    src.RFI_PARAM8, 
                    src.RFI_PARAM9, 
                    src.RFI_RADIO, 
                    src.RFI_TODATE, 
                    src.RFI_UPDATECOUNT, 
                    src.RFI_UPDATED, 
                    src.RFI_USER, 
                    src.RFI_VISFLDS, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5REPORTFILTERS_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.RFI_CHKBOX1, 
            strm.RFI_CHKBOX10, 
            strm.RFI_CHKBOX11, 
            strm.RFI_CHKBOX12, 
            strm.RFI_CHKBOX13, 
            strm.RFI_CHKBOX14, 
            strm.RFI_CHKBOX15, 
            strm.RFI_CHKBOX16, 
            strm.RFI_CHKBOX17, 
            strm.RFI_CHKBOX18, 
            strm.RFI_CHKBOX19, 
            strm.RFI_CHKBOX2, 
            strm.RFI_CHKBOX20, 
            strm.RFI_CHKBOX21, 
            strm.RFI_CHKBOX22, 
            strm.RFI_CHKBOX23, 
            strm.RFI_CHKBOX24, 
            strm.RFI_CHKBOX25, 
            strm.RFI_CHKBOX3, 
            strm.RFI_CHKBOX4, 
            strm.RFI_CHKBOX5, 
            strm.RFI_CHKBOX6, 
            strm.RFI_CHKBOX7, 
            strm.RFI_CHKBOX8, 
            strm.RFI_CHKBOX9, 
            strm.RFI_DEFAULT, 
            strm.RFI_FROMDATE, 
            strm.RFI_FUNC, 
            strm.RFI_GROUPBY, 
            strm.RFI_LASTSAVED, 
            strm.RFI_NAME, 
            strm.RFI_ORDERBY, 
            strm.RFI_ORDERTYPE, 
            strm.RFI_ORG, 
            strm.RFI_PARAM1, 
            strm.RFI_PARAM10, 
            strm.RFI_PARAM11, 
            strm.RFI_PARAM12, 
            strm.RFI_PARAM13, 
            strm.RFI_PARAM14, 
            strm.RFI_PARAM15, 
            strm.RFI_PARAM16, 
            strm.RFI_PARAM17, 
            strm.RFI_PARAM18, 
            strm.RFI_PARAM19, 
            strm.RFI_PARAM2, 
            strm.RFI_PARAM20, 
            strm.RFI_PARAM21, 
            strm.RFI_PARAM22, 
            strm.RFI_PARAM23, 
            strm.RFI_PARAM24, 
            strm.RFI_PARAM25, 
            strm.RFI_PARAM26, 
            strm.RFI_PARAM27, 
            strm.RFI_PARAM28, 
            strm.RFI_PARAM29, 
            strm.RFI_PARAM3, 
            strm.RFI_PARAM30, 
            strm.RFI_PARAM31, 
            strm.RFI_PARAM32, 
            strm.RFI_PARAM33, 
            strm.RFI_PARAM34, 
            strm.RFI_PARAM35, 
            strm.RFI_PARAM36, 
            strm.RFI_PARAM37, 
            strm.RFI_PARAM38, 
            strm.RFI_PARAM39, 
            strm.RFI_PARAM4, 
            strm.RFI_PARAM40, 
            strm.RFI_PARAM5, 
            strm.RFI_PARAM6, 
            strm.RFI_PARAM7, 
            strm.RFI_PARAM8, 
            strm.RFI_PARAM9, 
            strm.RFI_RADIO, 
            strm.RFI_TODATE, 
            strm.RFI_UPDATECOUNT, 
            strm.RFI_UPDATED, 
            strm.RFI_USER, 
            strm.RFI_VISFLDS, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.RFI_USER,
            strm.RFI_FUNC,
            strm.RFI_NAME ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5REPORTFILTERS as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.RFI_USER=src.RFI_USER) OR (target.RFI_USER IS NULL AND src.RFI_USER IS NULL)) AND
            ((target.RFI_FUNC=src.RFI_FUNC) OR (target.RFI_FUNC IS NULL AND src.RFI_FUNC IS NULL)) AND
            ((target.RFI_NAME=src.RFI_NAME) OR (target.RFI_NAME IS NULL AND src.RFI_NAME IS NULL)) 
                when matched then update set
                    target.RFI_CHKBOX1=src.RFI_CHKBOX1, 
                    target.RFI_CHKBOX10=src.RFI_CHKBOX10, 
                    target.RFI_CHKBOX11=src.RFI_CHKBOX11, 
                    target.RFI_CHKBOX12=src.RFI_CHKBOX12, 
                    target.RFI_CHKBOX13=src.RFI_CHKBOX13, 
                    target.RFI_CHKBOX14=src.RFI_CHKBOX14, 
                    target.RFI_CHKBOX15=src.RFI_CHKBOX15, 
                    target.RFI_CHKBOX16=src.RFI_CHKBOX16, 
                    target.RFI_CHKBOX17=src.RFI_CHKBOX17, 
                    target.RFI_CHKBOX18=src.RFI_CHKBOX18, 
                    target.RFI_CHKBOX19=src.RFI_CHKBOX19, 
                    target.RFI_CHKBOX2=src.RFI_CHKBOX2, 
                    target.RFI_CHKBOX20=src.RFI_CHKBOX20, 
                    target.RFI_CHKBOX21=src.RFI_CHKBOX21, 
                    target.RFI_CHKBOX22=src.RFI_CHKBOX22, 
                    target.RFI_CHKBOX23=src.RFI_CHKBOX23, 
                    target.RFI_CHKBOX24=src.RFI_CHKBOX24, 
                    target.RFI_CHKBOX25=src.RFI_CHKBOX25, 
                    target.RFI_CHKBOX3=src.RFI_CHKBOX3, 
                    target.RFI_CHKBOX4=src.RFI_CHKBOX4, 
                    target.RFI_CHKBOX5=src.RFI_CHKBOX5, 
                    target.RFI_CHKBOX6=src.RFI_CHKBOX6, 
                    target.RFI_CHKBOX7=src.RFI_CHKBOX7, 
                    target.RFI_CHKBOX8=src.RFI_CHKBOX8, 
                    target.RFI_CHKBOX9=src.RFI_CHKBOX9, 
                    target.RFI_DEFAULT=src.RFI_DEFAULT, 
                    target.RFI_FROMDATE=src.RFI_FROMDATE, 
                    target.RFI_FUNC=src.RFI_FUNC, 
                    target.RFI_GROUPBY=src.RFI_GROUPBY, 
                    target.RFI_LASTSAVED=src.RFI_LASTSAVED, 
                    target.RFI_NAME=src.RFI_NAME, 
                    target.RFI_ORDERBY=src.RFI_ORDERBY, 
                    target.RFI_ORDERTYPE=src.RFI_ORDERTYPE, 
                    target.RFI_ORG=src.RFI_ORG, 
                    target.RFI_PARAM1=src.RFI_PARAM1, 
                    target.RFI_PARAM10=src.RFI_PARAM10, 
                    target.RFI_PARAM11=src.RFI_PARAM11, 
                    target.RFI_PARAM12=src.RFI_PARAM12, 
                    target.RFI_PARAM13=src.RFI_PARAM13, 
                    target.RFI_PARAM14=src.RFI_PARAM14, 
                    target.RFI_PARAM15=src.RFI_PARAM15, 
                    target.RFI_PARAM16=src.RFI_PARAM16, 
                    target.RFI_PARAM17=src.RFI_PARAM17, 
                    target.RFI_PARAM18=src.RFI_PARAM18, 
                    target.RFI_PARAM19=src.RFI_PARAM19, 
                    target.RFI_PARAM2=src.RFI_PARAM2, 
                    target.RFI_PARAM20=src.RFI_PARAM20, 
                    target.RFI_PARAM21=src.RFI_PARAM21, 
                    target.RFI_PARAM22=src.RFI_PARAM22, 
                    target.RFI_PARAM23=src.RFI_PARAM23, 
                    target.RFI_PARAM24=src.RFI_PARAM24, 
                    target.RFI_PARAM25=src.RFI_PARAM25, 
                    target.RFI_PARAM26=src.RFI_PARAM26, 
                    target.RFI_PARAM27=src.RFI_PARAM27, 
                    target.RFI_PARAM28=src.RFI_PARAM28, 
                    target.RFI_PARAM29=src.RFI_PARAM29, 
                    target.RFI_PARAM3=src.RFI_PARAM3, 
                    target.RFI_PARAM30=src.RFI_PARAM30, 
                    target.RFI_PARAM31=src.RFI_PARAM31, 
                    target.RFI_PARAM32=src.RFI_PARAM32, 
                    target.RFI_PARAM33=src.RFI_PARAM33, 
                    target.RFI_PARAM34=src.RFI_PARAM34, 
                    target.RFI_PARAM35=src.RFI_PARAM35, 
                    target.RFI_PARAM36=src.RFI_PARAM36, 
                    target.RFI_PARAM37=src.RFI_PARAM37, 
                    target.RFI_PARAM38=src.RFI_PARAM38, 
                    target.RFI_PARAM39=src.RFI_PARAM39, 
                    target.RFI_PARAM4=src.RFI_PARAM4, 
                    target.RFI_PARAM40=src.RFI_PARAM40, 
                    target.RFI_PARAM5=src.RFI_PARAM5, 
                    target.RFI_PARAM6=src.RFI_PARAM6, 
                    target.RFI_PARAM7=src.RFI_PARAM7, 
                    target.RFI_PARAM8=src.RFI_PARAM8, 
                    target.RFI_PARAM9=src.RFI_PARAM9, 
                    target.RFI_RADIO=src.RFI_RADIO, 
                    target.RFI_TODATE=src.RFI_TODATE, 
                    target.RFI_UPDATECOUNT=src.RFI_UPDATECOUNT, 
                    target.RFI_UPDATED=src.RFI_UPDATED, 
                    target.RFI_USER=src.RFI_USER, 
                    target.RFI_VISFLDS=src.RFI_VISFLDS, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( RFI_CHKBOX1, RFI_CHKBOX10, RFI_CHKBOX11, RFI_CHKBOX12, RFI_CHKBOX13, RFI_CHKBOX14, RFI_CHKBOX15, RFI_CHKBOX16, RFI_CHKBOX17, RFI_CHKBOX18, RFI_CHKBOX19, RFI_CHKBOX2, RFI_CHKBOX20, RFI_CHKBOX21, RFI_CHKBOX22, RFI_CHKBOX23, RFI_CHKBOX24, RFI_CHKBOX25, RFI_CHKBOX3, RFI_CHKBOX4, RFI_CHKBOX5, RFI_CHKBOX6, RFI_CHKBOX7, RFI_CHKBOX8, RFI_CHKBOX9, RFI_DEFAULT, RFI_FROMDATE, RFI_FUNC, RFI_GROUPBY, RFI_LASTSAVED, RFI_NAME, RFI_ORDERBY, RFI_ORDERTYPE, RFI_ORG, RFI_PARAM1, RFI_PARAM10, RFI_PARAM11, RFI_PARAM12, RFI_PARAM13, RFI_PARAM14, RFI_PARAM15, RFI_PARAM16, RFI_PARAM17, RFI_PARAM18, RFI_PARAM19, RFI_PARAM2, RFI_PARAM20, RFI_PARAM21, RFI_PARAM22, RFI_PARAM23, RFI_PARAM24, RFI_PARAM25, RFI_PARAM26, RFI_PARAM27, RFI_PARAM28, RFI_PARAM29, RFI_PARAM3, RFI_PARAM30, RFI_PARAM31, RFI_PARAM32, RFI_PARAM33, RFI_PARAM34, RFI_PARAM35, RFI_PARAM36, RFI_PARAM37, RFI_PARAM38, RFI_PARAM39, RFI_PARAM4, RFI_PARAM40, RFI_PARAM5, RFI_PARAM6, RFI_PARAM7, RFI_PARAM8, RFI_PARAM9, RFI_RADIO, RFI_TODATE, RFI_UPDATECOUNT, RFI_UPDATED, RFI_USER, RFI_VISFLDS, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.RFI_CHKBOX1, 
                    src.RFI_CHKBOX10, 
                    src.RFI_CHKBOX11, 
                    src.RFI_CHKBOX12, 
                    src.RFI_CHKBOX13, 
                    src.RFI_CHKBOX14, 
                    src.RFI_CHKBOX15, 
                    src.RFI_CHKBOX16, 
                    src.RFI_CHKBOX17, 
                    src.RFI_CHKBOX18, 
                    src.RFI_CHKBOX19, 
                    src.RFI_CHKBOX2, 
                    src.RFI_CHKBOX20, 
                    src.RFI_CHKBOX21, 
                    src.RFI_CHKBOX22, 
                    src.RFI_CHKBOX23, 
                    src.RFI_CHKBOX24, 
                    src.RFI_CHKBOX25, 
                    src.RFI_CHKBOX3, 
                    src.RFI_CHKBOX4, 
                    src.RFI_CHKBOX5, 
                    src.RFI_CHKBOX6, 
                    src.RFI_CHKBOX7, 
                    src.RFI_CHKBOX8, 
                    src.RFI_CHKBOX9, 
                    src.RFI_DEFAULT, 
                    src.RFI_FROMDATE, 
                    src.RFI_FUNC, 
                    src.RFI_GROUPBY, 
                    src.RFI_LASTSAVED, 
                    src.RFI_NAME, 
                    src.RFI_ORDERBY, 
                    src.RFI_ORDERTYPE, 
                    src.RFI_ORG, 
                    src.RFI_PARAM1, 
                    src.RFI_PARAM10, 
                    src.RFI_PARAM11, 
                    src.RFI_PARAM12, 
                    src.RFI_PARAM13, 
                    src.RFI_PARAM14, 
                    src.RFI_PARAM15, 
                    src.RFI_PARAM16, 
                    src.RFI_PARAM17, 
                    src.RFI_PARAM18, 
                    src.RFI_PARAM19, 
                    src.RFI_PARAM2, 
                    src.RFI_PARAM20, 
                    src.RFI_PARAM21, 
                    src.RFI_PARAM22, 
                    src.RFI_PARAM23, 
                    src.RFI_PARAM24, 
                    src.RFI_PARAM25, 
                    src.RFI_PARAM26, 
                    src.RFI_PARAM27, 
                    src.RFI_PARAM28, 
                    src.RFI_PARAM29, 
                    src.RFI_PARAM3, 
                    src.RFI_PARAM30, 
                    src.RFI_PARAM31, 
                    src.RFI_PARAM32, 
                    src.RFI_PARAM33, 
                    src.RFI_PARAM34, 
                    src.RFI_PARAM35, 
                    src.RFI_PARAM36, 
                    src.RFI_PARAM37, 
                    src.RFI_PARAM38, 
                    src.RFI_PARAM39, 
                    src.RFI_PARAM4, 
                    src.RFI_PARAM40, 
                    src.RFI_PARAM5, 
                    src.RFI_PARAM6, 
                    src.RFI_PARAM7, 
                    src.RFI_PARAM8, 
                    src.RFI_PARAM9, 
                    src.RFI_RADIO, 
                    src.RFI_TODATE, 
                    src.RFI_UPDATECOUNT, 
                    src.RFI_UPDATED, 
                    src.RFI_USER, 
                    src.RFI_VISFLDS, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;