create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5PRECAUTIONS()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5PRECAUTIONS_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5PRECAUTIONS as target using (SELECT * FROM (SELECT 
            strm.PCA_APPROVED, 
            strm.PCA_APPROVEDBY, 
            strm.PCA_CLASS, 
            strm.PCA_CLASS_ORG, 
            strm.PCA_CODE, 
            strm.PCA_CREATED, 
            strm.PCA_CREATEDBY, 
            strm.PCA_DESC, 
            strm.PCA_LASTSAVED, 
            strm.PCA_NOTUSED, 
            strm.PCA_ORG, 
            strm.PCA_REQUESTED, 
            strm.PCA_REQUESTEDBY, 
            strm.PCA_RESPONSIBILITY, 
            strm.PCA_REVIEWREQUIRED, 
            strm.PCA_REVISION, 
            strm.PCA_REVISIONREASON, 
            strm.PCA_RSTATUS, 
            strm.PCA_STATUS, 
            strm.PCA_TIMING, 
            strm.PCA_UDFCHAR01, 
            strm.PCA_UDFCHAR02, 
            strm.PCA_UDFCHAR03, 
            strm.PCA_UDFCHAR04, 
            strm.PCA_UDFCHAR05, 
            strm.PCA_UDFCHAR06, 
            strm.PCA_UDFCHAR07, 
            strm.PCA_UDFCHAR08, 
            strm.PCA_UDFCHAR09, 
            strm.PCA_UDFCHAR10, 
            strm.PCA_UDFCHAR11, 
            strm.PCA_UDFCHAR12, 
            strm.PCA_UDFCHAR13, 
            strm.PCA_UDFCHAR14, 
            strm.PCA_UDFCHAR15, 
            strm.PCA_UDFCHAR16, 
            strm.PCA_UDFCHAR17, 
            strm.PCA_UDFCHAR18, 
            strm.PCA_UDFCHAR19, 
            strm.PCA_UDFCHAR20, 
            strm.PCA_UDFCHAR21, 
            strm.PCA_UDFCHAR22, 
            strm.PCA_UDFCHAR23, 
            strm.PCA_UDFCHAR24, 
            strm.PCA_UDFCHAR25, 
            strm.PCA_UDFCHAR26, 
            strm.PCA_UDFCHAR27, 
            strm.PCA_UDFCHAR28, 
            strm.PCA_UDFCHAR29, 
            strm.PCA_UDFCHAR30, 
            strm.PCA_UDFCHKBOX01, 
            strm.PCA_UDFCHKBOX02, 
            strm.PCA_UDFCHKBOX03, 
            strm.PCA_UDFCHKBOX04, 
            strm.PCA_UDFCHKBOX05, 
            strm.PCA_UDFDATE01, 
            strm.PCA_UDFDATE02, 
            strm.PCA_UDFDATE03, 
            strm.PCA_UDFDATE04, 
            strm.PCA_UDFDATE05, 
            strm.PCA_UDFNUM01, 
            strm.PCA_UDFNUM02, 
            strm.PCA_UDFNUM03, 
            strm.PCA_UDFNUM04, 
            strm.PCA_UDFNUM05, 
            strm.PCA_UPDATECOUNT, 
            strm.PCA_UPDATED, 
            strm.PCA_UPDATEDBY, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.PCA_CODE,
            strm.PCA_ORG,
            strm.PCA_REVISION ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5PRECAUTIONS as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.PCA_CODE=src.PCA_CODE) OR (target.PCA_CODE IS NULL AND src.PCA_CODE IS NULL)) AND
            ((target.PCA_ORG=src.PCA_ORG) OR (target.PCA_ORG IS NULL AND src.PCA_ORG IS NULL)) AND
            ((target.PCA_REVISION=src.PCA_REVISION) OR (target.PCA_REVISION IS NULL AND src.PCA_REVISION IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.PCA_APPROVED=src.PCA_APPROVED, 
                    target.PCA_APPROVEDBY=src.PCA_APPROVEDBY, 
                    target.PCA_CLASS=src.PCA_CLASS, 
                    target.PCA_CLASS_ORG=src.PCA_CLASS_ORG, 
                    target.PCA_CODE=src.PCA_CODE, 
                    target.PCA_CREATED=src.PCA_CREATED, 
                    target.PCA_CREATEDBY=src.PCA_CREATEDBY, 
                    target.PCA_DESC=src.PCA_DESC, 
                    target.PCA_LASTSAVED=src.PCA_LASTSAVED, 
                    target.PCA_NOTUSED=src.PCA_NOTUSED, 
                    target.PCA_ORG=src.PCA_ORG, 
                    target.PCA_REQUESTED=src.PCA_REQUESTED, 
                    target.PCA_REQUESTEDBY=src.PCA_REQUESTEDBY, 
                    target.PCA_RESPONSIBILITY=src.PCA_RESPONSIBILITY, 
                    target.PCA_REVIEWREQUIRED=src.PCA_REVIEWREQUIRED, 
                    target.PCA_REVISION=src.PCA_REVISION, 
                    target.PCA_REVISIONREASON=src.PCA_REVISIONREASON, 
                    target.PCA_RSTATUS=src.PCA_RSTATUS, 
                    target.PCA_STATUS=src.PCA_STATUS, 
                    target.PCA_TIMING=src.PCA_TIMING, 
                    target.PCA_UDFCHAR01=src.PCA_UDFCHAR01, 
                    target.PCA_UDFCHAR02=src.PCA_UDFCHAR02, 
                    target.PCA_UDFCHAR03=src.PCA_UDFCHAR03, 
                    target.PCA_UDFCHAR04=src.PCA_UDFCHAR04, 
                    target.PCA_UDFCHAR05=src.PCA_UDFCHAR05, 
                    target.PCA_UDFCHAR06=src.PCA_UDFCHAR06, 
                    target.PCA_UDFCHAR07=src.PCA_UDFCHAR07, 
                    target.PCA_UDFCHAR08=src.PCA_UDFCHAR08, 
                    target.PCA_UDFCHAR09=src.PCA_UDFCHAR09, 
                    target.PCA_UDFCHAR10=src.PCA_UDFCHAR10, 
                    target.PCA_UDFCHAR11=src.PCA_UDFCHAR11, 
                    target.PCA_UDFCHAR12=src.PCA_UDFCHAR12, 
                    target.PCA_UDFCHAR13=src.PCA_UDFCHAR13, 
                    target.PCA_UDFCHAR14=src.PCA_UDFCHAR14, 
                    target.PCA_UDFCHAR15=src.PCA_UDFCHAR15, 
                    target.PCA_UDFCHAR16=src.PCA_UDFCHAR16, 
                    target.PCA_UDFCHAR17=src.PCA_UDFCHAR17, 
                    target.PCA_UDFCHAR18=src.PCA_UDFCHAR18, 
                    target.PCA_UDFCHAR19=src.PCA_UDFCHAR19, 
                    target.PCA_UDFCHAR20=src.PCA_UDFCHAR20, 
                    target.PCA_UDFCHAR21=src.PCA_UDFCHAR21, 
                    target.PCA_UDFCHAR22=src.PCA_UDFCHAR22, 
                    target.PCA_UDFCHAR23=src.PCA_UDFCHAR23, 
                    target.PCA_UDFCHAR24=src.PCA_UDFCHAR24, 
                    target.PCA_UDFCHAR25=src.PCA_UDFCHAR25, 
                    target.PCA_UDFCHAR26=src.PCA_UDFCHAR26, 
                    target.PCA_UDFCHAR27=src.PCA_UDFCHAR27, 
                    target.PCA_UDFCHAR28=src.PCA_UDFCHAR28, 
                    target.PCA_UDFCHAR29=src.PCA_UDFCHAR29, 
                    target.PCA_UDFCHAR30=src.PCA_UDFCHAR30, 
                    target.PCA_UDFCHKBOX01=src.PCA_UDFCHKBOX01, 
                    target.PCA_UDFCHKBOX02=src.PCA_UDFCHKBOX02, 
                    target.PCA_UDFCHKBOX03=src.PCA_UDFCHKBOX03, 
                    target.PCA_UDFCHKBOX04=src.PCA_UDFCHKBOX04, 
                    target.PCA_UDFCHKBOX05=src.PCA_UDFCHKBOX05, 
                    target.PCA_UDFDATE01=src.PCA_UDFDATE01, 
                    target.PCA_UDFDATE02=src.PCA_UDFDATE02, 
                    target.PCA_UDFDATE03=src.PCA_UDFDATE03, 
                    target.PCA_UDFDATE04=src.PCA_UDFDATE04, 
                    target.PCA_UDFDATE05=src.PCA_UDFDATE05, 
                    target.PCA_UDFNUM01=src.PCA_UDFNUM01, 
                    target.PCA_UDFNUM02=src.PCA_UDFNUM02, 
                    target.PCA_UDFNUM03=src.PCA_UDFNUM03, 
                    target.PCA_UDFNUM04=src.PCA_UDFNUM04, 
                    target.PCA_UDFNUM05=src.PCA_UDFNUM05, 
                    target.PCA_UPDATECOUNT=src.PCA_UPDATECOUNT, 
                    target.PCA_UPDATED=src.PCA_UPDATED, 
                    target.PCA_UPDATEDBY=src.PCA_UPDATEDBY, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    PCA_APPROVED, 
                    PCA_APPROVEDBY, 
                    PCA_CLASS, 
                    PCA_CLASS_ORG, 
                    PCA_CODE, 
                    PCA_CREATED, 
                    PCA_CREATEDBY, 
                    PCA_DESC, 
                    PCA_LASTSAVED, 
                    PCA_NOTUSED, 
                    PCA_ORG, 
                    PCA_REQUESTED, 
                    PCA_REQUESTEDBY, 
                    PCA_RESPONSIBILITY, 
                    PCA_REVIEWREQUIRED, 
                    PCA_REVISION, 
                    PCA_REVISIONREASON, 
                    PCA_RSTATUS, 
                    PCA_STATUS, 
                    PCA_TIMING, 
                    PCA_UDFCHAR01, 
                    PCA_UDFCHAR02, 
                    PCA_UDFCHAR03, 
                    PCA_UDFCHAR04, 
                    PCA_UDFCHAR05, 
                    PCA_UDFCHAR06, 
                    PCA_UDFCHAR07, 
                    PCA_UDFCHAR08, 
                    PCA_UDFCHAR09, 
                    PCA_UDFCHAR10, 
                    PCA_UDFCHAR11, 
                    PCA_UDFCHAR12, 
                    PCA_UDFCHAR13, 
                    PCA_UDFCHAR14, 
                    PCA_UDFCHAR15, 
                    PCA_UDFCHAR16, 
                    PCA_UDFCHAR17, 
                    PCA_UDFCHAR18, 
                    PCA_UDFCHAR19, 
                    PCA_UDFCHAR20, 
                    PCA_UDFCHAR21, 
                    PCA_UDFCHAR22, 
                    PCA_UDFCHAR23, 
                    PCA_UDFCHAR24, 
                    PCA_UDFCHAR25, 
                    PCA_UDFCHAR26, 
                    PCA_UDFCHAR27, 
                    PCA_UDFCHAR28, 
                    PCA_UDFCHAR29, 
                    PCA_UDFCHAR30, 
                    PCA_UDFCHKBOX01, 
                    PCA_UDFCHKBOX02, 
                    PCA_UDFCHKBOX03, 
                    PCA_UDFCHKBOX04, 
                    PCA_UDFCHKBOX05, 
                    PCA_UDFDATE01, 
                    PCA_UDFDATE02, 
                    PCA_UDFDATE03, 
                    PCA_UDFDATE04, 
                    PCA_UDFDATE05, 
                    PCA_UDFNUM01, 
                    PCA_UDFNUM02, 
                    PCA_UDFNUM03, 
                    PCA_UDFNUM04, 
                    PCA_UDFNUM05, 
                    PCA_UPDATECOUNT, 
                    PCA_UPDATED, 
                    PCA_UPDATEDBY, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.PCA_APPROVED, 
                    src.PCA_APPROVEDBY, 
                    src.PCA_CLASS, 
                    src.PCA_CLASS_ORG, 
                    src.PCA_CODE, 
                    src.PCA_CREATED, 
                    src.PCA_CREATEDBY, 
                    src.PCA_DESC, 
                    src.PCA_LASTSAVED, 
                    src.PCA_NOTUSED, 
                    src.PCA_ORG, 
                    src.PCA_REQUESTED, 
                    src.PCA_REQUESTEDBY, 
                    src.PCA_RESPONSIBILITY, 
                    src.PCA_REVIEWREQUIRED, 
                    src.PCA_REVISION, 
                    src.PCA_REVISIONREASON, 
                    src.PCA_RSTATUS, 
                    src.PCA_STATUS, 
                    src.PCA_TIMING, 
                    src.PCA_UDFCHAR01, 
                    src.PCA_UDFCHAR02, 
                    src.PCA_UDFCHAR03, 
                    src.PCA_UDFCHAR04, 
                    src.PCA_UDFCHAR05, 
                    src.PCA_UDFCHAR06, 
                    src.PCA_UDFCHAR07, 
                    src.PCA_UDFCHAR08, 
                    src.PCA_UDFCHAR09, 
                    src.PCA_UDFCHAR10, 
                    src.PCA_UDFCHAR11, 
                    src.PCA_UDFCHAR12, 
                    src.PCA_UDFCHAR13, 
                    src.PCA_UDFCHAR14, 
                    src.PCA_UDFCHAR15, 
                    src.PCA_UDFCHAR16, 
                    src.PCA_UDFCHAR17, 
                    src.PCA_UDFCHAR18, 
                    src.PCA_UDFCHAR19, 
                    src.PCA_UDFCHAR20, 
                    src.PCA_UDFCHAR21, 
                    src.PCA_UDFCHAR22, 
                    src.PCA_UDFCHAR23, 
                    src.PCA_UDFCHAR24, 
                    src.PCA_UDFCHAR25, 
                    src.PCA_UDFCHAR26, 
                    src.PCA_UDFCHAR27, 
                    src.PCA_UDFCHAR28, 
                    src.PCA_UDFCHAR29, 
                    src.PCA_UDFCHAR30, 
                    src.PCA_UDFCHKBOX01, 
                    src.PCA_UDFCHKBOX02, 
                    src.PCA_UDFCHKBOX03, 
                    src.PCA_UDFCHKBOX04, 
                    src.PCA_UDFCHKBOX05, 
                    src.PCA_UDFDATE01, 
                    src.PCA_UDFDATE02, 
                    src.PCA_UDFDATE03, 
                    src.PCA_UDFDATE04, 
                    src.PCA_UDFDATE05, 
                    src.PCA_UDFNUM01, 
                    src.PCA_UDFNUM02, 
                    src.PCA_UDFNUM03, 
                    src.PCA_UDFNUM04, 
                    src.PCA_UDFNUM05, 
                    src.PCA_UPDATECOUNT, 
                    src.PCA_UPDATED, 
                    src.PCA_UPDATEDBY, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5PRECAUTIONS_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.PCA_APPROVED, 
            strm.PCA_APPROVEDBY, 
            strm.PCA_CLASS, 
            strm.PCA_CLASS_ORG, 
            strm.PCA_CODE, 
            strm.PCA_CREATED, 
            strm.PCA_CREATEDBY, 
            strm.PCA_DESC, 
            strm.PCA_LASTSAVED, 
            strm.PCA_NOTUSED, 
            strm.PCA_ORG, 
            strm.PCA_REQUESTED, 
            strm.PCA_REQUESTEDBY, 
            strm.PCA_RESPONSIBILITY, 
            strm.PCA_REVIEWREQUIRED, 
            strm.PCA_REVISION, 
            strm.PCA_REVISIONREASON, 
            strm.PCA_RSTATUS, 
            strm.PCA_STATUS, 
            strm.PCA_TIMING, 
            strm.PCA_UDFCHAR01, 
            strm.PCA_UDFCHAR02, 
            strm.PCA_UDFCHAR03, 
            strm.PCA_UDFCHAR04, 
            strm.PCA_UDFCHAR05, 
            strm.PCA_UDFCHAR06, 
            strm.PCA_UDFCHAR07, 
            strm.PCA_UDFCHAR08, 
            strm.PCA_UDFCHAR09, 
            strm.PCA_UDFCHAR10, 
            strm.PCA_UDFCHAR11, 
            strm.PCA_UDFCHAR12, 
            strm.PCA_UDFCHAR13, 
            strm.PCA_UDFCHAR14, 
            strm.PCA_UDFCHAR15, 
            strm.PCA_UDFCHAR16, 
            strm.PCA_UDFCHAR17, 
            strm.PCA_UDFCHAR18, 
            strm.PCA_UDFCHAR19, 
            strm.PCA_UDFCHAR20, 
            strm.PCA_UDFCHAR21, 
            strm.PCA_UDFCHAR22, 
            strm.PCA_UDFCHAR23, 
            strm.PCA_UDFCHAR24, 
            strm.PCA_UDFCHAR25, 
            strm.PCA_UDFCHAR26, 
            strm.PCA_UDFCHAR27, 
            strm.PCA_UDFCHAR28, 
            strm.PCA_UDFCHAR29, 
            strm.PCA_UDFCHAR30, 
            strm.PCA_UDFCHKBOX01, 
            strm.PCA_UDFCHKBOX02, 
            strm.PCA_UDFCHKBOX03, 
            strm.PCA_UDFCHKBOX04, 
            strm.PCA_UDFCHKBOX05, 
            strm.PCA_UDFDATE01, 
            strm.PCA_UDFDATE02, 
            strm.PCA_UDFDATE03, 
            strm.PCA_UDFDATE04, 
            strm.PCA_UDFDATE05, 
            strm.PCA_UDFNUM01, 
            strm.PCA_UDFNUM02, 
            strm.PCA_UDFNUM03, 
            strm.PCA_UDFNUM04, 
            strm.PCA_UDFNUM05, 
            strm.PCA_UPDATECOUNT, 
            strm.PCA_UPDATED, 
            strm.PCA_UPDATEDBY, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.PCA_CODE,
            strm.PCA_ORG,
            strm.PCA_REVISION ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5PRECAUTIONS as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.PCA_CODE=src.PCA_CODE) OR (target.PCA_CODE IS NULL AND src.PCA_CODE IS NULL)) AND
            ((target.PCA_ORG=src.PCA_ORG) OR (target.PCA_ORG IS NULL AND src.PCA_ORG IS NULL)) AND
            ((target.PCA_REVISION=src.PCA_REVISION) OR (target.PCA_REVISION IS NULL AND src.PCA_REVISION IS NULL)) 
                when matched then update set
                    target.PCA_APPROVED=src.PCA_APPROVED, 
                    target.PCA_APPROVEDBY=src.PCA_APPROVEDBY, 
                    target.PCA_CLASS=src.PCA_CLASS, 
                    target.PCA_CLASS_ORG=src.PCA_CLASS_ORG, 
                    target.PCA_CODE=src.PCA_CODE, 
                    target.PCA_CREATED=src.PCA_CREATED, 
                    target.PCA_CREATEDBY=src.PCA_CREATEDBY, 
                    target.PCA_DESC=src.PCA_DESC, 
                    target.PCA_LASTSAVED=src.PCA_LASTSAVED, 
                    target.PCA_NOTUSED=src.PCA_NOTUSED, 
                    target.PCA_ORG=src.PCA_ORG, 
                    target.PCA_REQUESTED=src.PCA_REQUESTED, 
                    target.PCA_REQUESTEDBY=src.PCA_REQUESTEDBY, 
                    target.PCA_RESPONSIBILITY=src.PCA_RESPONSIBILITY, 
                    target.PCA_REVIEWREQUIRED=src.PCA_REVIEWREQUIRED, 
                    target.PCA_REVISION=src.PCA_REVISION, 
                    target.PCA_REVISIONREASON=src.PCA_REVISIONREASON, 
                    target.PCA_RSTATUS=src.PCA_RSTATUS, 
                    target.PCA_STATUS=src.PCA_STATUS, 
                    target.PCA_TIMING=src.PCA_TIMING, 
                    target.PCA_UDFCHAR01=src.PCA_UDFCHAR01, 
                    target.PCA_UDFCHAR02=src.PCA_UDFCHAR02, 
                    target.PCA_UDFCHAR03=src.PCA_UDFCHAR03, 
                    target.PCA_UDFCHAR04=src.PCA_UDFCHAR04, 
                    target.PCA_UDFCHAR05=src.PCA_UDFCHAR05, 
                    target.PCA_UDFCHAR06=src.PCA_UDFCHAR06, 
                    target.PCA_UDFCHAR07=src.PCA_UDFCHAR07, 
                    target.PCA_UDFCHAR08=src.PCA_UDFCHAR08, 
                    target.PCA_UDFCHAR09=src.PCA_UDFCHAR09, 
                    target.PCA_UDFCHAR10=src.PCA_UDFCHAR10, 
                    target.PCA_UDFCHAR11=src.PCA_UDFCHAR11, 
                    target.PCA_UDFCHAR12=src.PCA_UDFCHAR12, 
                    target.PCA_UDFCHAR13=src.PCA_UDFCHAR13, 
                    target.PCA_UDFCHAR14=src.PCA_UDFCHAR14, 
                    target.PCA_UDFCHAR15=src.PCA_UDFCHAR15, 
                    target.PCA_UDFCHAR16=src.PCA_UDFCHAR16, 
                    target.PCA_UDFCHAR17=src.PCA_UDFCHAR17, 
                    target.PCA_UDFCHAR18=src.PCA_UDFCHAR18, 
                    target.PCA_UDFCHAR19=src.PCA_UDFCHAR19, 
                    target.PCA_UDFCHAR20=src.PCA_UDFCHAR20, 
                    target.PCA_UDFCHAR21=src.PCA_UDFCHAR21, 
                    target.PCA_UDFCHAR22=src.PCA_UDFCHAR22, 
                    target.PCA_UDFCHAR23=src.PCA_UDFCHAR23, 
                    target.PCA_UDFCHAR24=src.PCA_UDFCHAR24, 
                    target.PCA_UDFCHAR25=src.PCA_UDFCHAR25, 
                    target.PCA_UDFCHAR26=src.PCA_UDFCHAR26, 
                    target.PCA_UDFCHAR27=src.PCA_UDFCHAR27, 
                    target.PCA_UDFCHAR28=src.PCA_UDFCHAR28, 
                    target.PCA_UDFCHAR29=src.PCA_UDFCHAR29, 
                    target.PCA_UDFCHAR30=src.PCA_UDFCHAR30, 
                    target.PCA_UDFCHKBOX01=src.PCA_UDFCHKBOX01, 
                    target.PCA_UDFCHKBOX02=src.PCA_UDFCHKBOX02, 
                    target.PCA_UDFCHKBOX03=src.PCA_UDFCHKBOX03, 
                    target.PCA_UDFCHKBOX04=src.PCA_UDFCHKBOX04, 
                    target.PCA_UDFCHKBOX05=src.PCA_UDFCHKBOX05, 
                    target.PCA_UDFDATE01=src.PCA_UDFDATE01, 
                    target.PCA_UDFDATE02=src.PCA_UDFDATE02, 
                    target.PCA_UDFDATE03=src.PCA_UDFDATE03, 
                    target.PCA_UDFDATE04=src.PCA_UDFDATE04, 
                    target.PCA_UDFDATE05=src.PCA_UDFDATE05, 
                    target.PCA_UDFNUM01=src.PCA_UDFNUM01, 
                    target.PCA_UDFNUM02=src.PCA_UDFNUM02, 
                    target.PCA_UDFNUM03=src.PCA_UDFNUM03, 
                    target.PCA_UDFNUM04=src.PCA_UDFNUM04, 
                    target.PCA_UDFNUM05=src.PCA_UDFNUM05, 
                    target.PCA_UPDATECOUNT=src.PCA_UPDATECOUNT, 
                    target.PCA_UPDATED=src.PCA_UPDATED, 
                    target.PCA_UPDATEDBY=src.PCA_UPDATEDBY, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( PCA_APPROVED, PCA_APPROVEDBY, PCA_CLASS, PCA_CLASS_ORG, PCA_CODE, PCA_CREATED, PCA_CREATEDBY, PCA_DESC, PCA_LASTSAVED, PCA_NOTUSED, PCA_ORG, PCA_REQUESTED, PCA_REQUESTEDBY, PCA_RESPONSIBILITY, PCA_REVIEWREQUIRED, PCA_REVISION, PCA_REVISIONREASON, PCA_RSTATUS, PCA_STATUS, PCA_TIMING, PCA_UDFCHAR01, PCA_UDFCHAR02, PCA_UDFCHAR03, PCA_UDFCHAR04, PCA_UDFCHAR05, PCA_UDFCHAR06, PCA_UDFCHAR07, PCA_UDFCHAR08, PCA_UDFCHAR09, PCA_UDFCHAR10, PCA_UDFCHAR11, PCA_UDFCHAR12, PCA_UDFCHAR13, PCA_UDFCHAR14, PCA_UDFCHAR15, PCA_UDFCHAR16, PCA_UDFCHAR17, PCA_UDFCHAR18, PCA_UDFCHAR19, PCA_UDFCHAR20, PCA_UDFCHAR21, PCA_UDFCHAR22, PCA_UDFCHAR23, PCA_UDFCHAR24, PCA_UDFCHAR25, PCA_UDFCHAR26, PCA_UDFCHAR27, PCA_UDFCHAR28, PCA_UDFCHAR29, PCA_UDFCHAR30, PCA_UDFCHKBOX01, PCA_UDFCHKBOX02, PCA_UDFCHKBOX03, PCA_UDFCHKBOX04, PCA_UDFCHKBOX05, PCA_UDFDATE01, PCA_UDFDATE02, PCA_UDFDATE03, PCA_UDFDATE04, PCA_UDFDATE05, PCA_UDFNUM01, PCA_UDFNUM02, PCA_UDFNUM03, PCA_UDFNUM04, PCA_UDFNUM05, PCA_UPDATECOUNT, PCA_UPDATED, PCA_UPDATEDBY, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.PCA_APPROVED, 
                    src.PCA_APPROVEDBY, 
                    src.PCA_CLASS, 
                    src.PCA_CLASS_ORG, 
                    src.PCA_CODE, 
                    src.PCA_CREATED, 
                    src.PCA_CREATEDBY, 
                    src.PCA_DESC, 
                    src.PCA_LASTSAVED, 
                    src.PCA_NOTUSED, 
                    src.PCA_ORG, 
                    src.PCA_REQUESTED, 
                    src.PCA_REQUESTEDBY, 
                    src.PCA_RESPONSIBILITY, 
                    src.PCA_REVIEWREQUIRED, 
                    src.PCA_REVISION, 
                    src.PCA_REVISIONREASON, 
                    src.PCA_RSTATUS, 
                    src.PCA_STATUS, 
                    src.PCA_TIMING, 
                    src.PCA_UDFCHAR01, 
                    src.PCA_UDFCHAR02, 
                    src.PCA_UDFCHAR03, 
                    src.PCA_UDFCHAR04, 
                    src.PCA_UDFCHAR05, 
                    src.PCA_UDFCHAR06, 
                    src.PCA_UDFCHAR07, 
                    src.PCA_UDFCHAR08, 
                    src.PCA_UDFCHAR09, 
                    src.PCA_UDFCHAR10, 
                    src.PCA_UDFCHAR11, 
                    src.PCA_UDFCHAR12, 
                    src.PCA_UDFCHAR13, 
                    src.PCA_UDFCHAR14, 
                    src.PCA_UDFCHAR15, 
                    src.PCA_UDFCHAR16, 
                    src.PCA_UDFCHAR17, 
                    src.PCA_UDFCHAR18, 
                    src.PCA_UDFCHAR19, 
                    src.PCA_UDFCHAR20, 
                    src.PCA_UDFCHAR21, 
                    src.PCA_UDFCHAR22, 
                    src.PCA_UDFCHAR23, 
                    src.PCA_UDFCHAR24, 
                    src.PCA_UDFCHAR25, 
                    src.PCA_UDFCHAR26, 
                    src.PCA_UDFCHAR27, 
                    src.PCA_UDFCHAR28, 
                    src.PCA_UDFCHAR29, 
                    src.PCA_UDFCHAR30, 
                    src.PCA_UDFCHKBOX01, 
                    src.PCA_UDFCHKBOX02, 
                    src.PCA_UDFCHKBOX03, 
                    src.PCA_UDFCHKBOX04, 
                    src.PCA_UDFCHKBOX05, 
                    src.PCA_UDFDATE01, 
                    src.PCA_UDFDATE02, 
                    src.PCA_UDFDATE03, 
                    src.PCA_UDFDATE04, 
                    src.PCA_UDFDATE05, 
                    src.PCA_UDFNUM01, 
                    src.PCA_UDFNUM02, 
                    src.PCA_UDFNUM03, 
                    src.PCA_UDFNUM04, 
                    src.PCA_UDFNUM05, 
                    src.PCA_UPDATECOUNT, 
                    src.PCA_UPDATED, 
                    src.PCA_UPDATEDBY, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;