create or replace procedure DATAHUB_INTEGRATION.SP_EAM_R5STANDWACTS()
    returns varchar not null
                language javascript
                as
                $$

//  Variables

var result = "";                                    // return status of this proc call
const process_name = Object.keys(this)[0];          // name of currently executing process
var number_of_rows_inserted = 0;                             // track number of rows we have inserted
var number_of_rows_updated = 0;                             // track number of rows we have updated


//  Step 1.

//  Start execution - log start

log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('Insert','" + process_name + "','Running','Started process execution.', 0,0,0);";
snowflake.execute({sqlText: log_sql_command});

snowflake.execute( {sqlText: "begin transaction;"} );
try
    {
        var sql_command = `
                            INSERT INTO LANDING_ERROR.EAM_RAW_ERROR
                            SELECT * FROM LANDING_ERROR.VW_STREAM_EAM_R5STANDWACTS_ERROR`;
    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();
        
        var sql_command = ` 
                            merge into  TARGET_EAM.EAM_R5STANDWACTS as target using (SELECT * FROM (SELECT 
            strm.WAC_ACT, 
            strm.WAC_ASMLEVEL, 
            strm.WAC_COMPLEVEL, 
            strm.WAC_CREATED, 
            strm.WAC_DURATION, 
            strm.WAC_EST, 
            strm.WAC_HIRE, 
            strm.WAC_LABORRTYPE, 
            strm.WAC_LABORTYPE, 
            strm.WAC_LASTSAVED, 
            strm.WAC_MANUFACT, 
            strm.WAC_MATLIST, 
            strm.WAC_NOTE, 
            strm.WAC_PERSONS, 
            strm.WAC_QTY, 
            strm.WAC_RPC, 
            strm.WAC_SPECIAL, 
            strm.WAC_STANDWORK, 
            strm.WAC_START, 
            strm.WAC_SUPPLIER, 
            strm.WAC_SUPPLIER_ORG, 
            strm.WAC_SYSLEVEL, 
            strm.WAC_TASK, 
            strm.WAC_TPF, 
            strm.WAC_TRADE, 
            strm.WAC_UDFCHAR01, 
            strm.WAC_UDFCHAR02, 
            strm.WAC_UDFCHAR03, 
            strm.WAC_UDFCHAR04, 
            strm.WAC_UDFCHAR05, 
            strm.WAC_UDFCHAR06, 
            strm.WAC_UDFCHAR07, 
            strm.WAC_UDFCHAR08, 
            strm.WAC_UDFCHAR09, 
            strm.WAC_UDFCHAR10, 
            strm.WAC_UDFCHAR11, 
            strm.WAC_UDFCHAR12, 
            strm.WAC_UDFCHAR13, 
            strm.WAC_UDFCHAR14, 
            strm.WAC_UDFCHAR15, 
            strm.WAC_UDFCHAR16, 
            strm.WAC_UDFCHAR17, 
            strm.WAC_UDFCHAR18, 
            strm.WAC_UDFCHAR19, 
            strm.WAC_UDFCHAR20, 
            strm.WAC_UDFCHAR21, 
            strm.WAC_UDFCHAR22, 
            strm.WAC_UDFCHAR23, 
            strm.WAC_UDFCHAR24, 
            strm.WAC_UDFCHAR25, 
            strm.WAC_UDFCHAR26, 
            strm.WAC_UDFCHAR27, 
            strm.WAC_UDFCHAR28, 
            strm.WAC_UDFCHAR29, 
            strm.WAC_UDFCHAR30, 
            strm.WAC_UDFCHKBOX01, 
            strm.WAC_UDFCHKBOX02, 
            strm.WAC_UDFCHKBOX03, 
            strm.WAC_UDFCHKBOX04, 
            strm.WAC_UDFCHKBOX05, 
            strm.WAC_UDFDATE01, 
            strm.WAC_UDFDATE02, 
            strm.WAC_UDFDATE03, 
            strm.WAC_UDFDATE04, 
            strm.WAC_UDFDATE05, 
            strm.WAC_UDFNOTE01, 
            strm.WAC_UDFNOTE02, 
            strm.WAC_UDFNUM01, 
            strm.WAC_UDFNUM02, 
            strm.WAC_UDFNUM03, 
            strm.WAC_UDFNUM04, 
            strm.WAC_UDFNUM05, 
            strm.WAC_UOM, 
            strm.WAC_UPDATECOUNT, 
            strm.WAC_UPDATED, 
            strm.WAC_WAP, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.WAC_STANDWORK,
            strm.WAC_ACT ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5STANDWACTS as  strm
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.WAC_STANDWORK=src.WAC_STANDWORK) OR (target.WAC_STANDWORK IS NULL AND src.WAC_STANDWORK IS NULL)) AND
            ((target.WAC_ACT=src.WAC_ACT) OR (target.WAC_ACT IS NULL AND src.WAC_ACT IS NULL)) 
                when matched and src.ETL_DELETED=TRUE THEN DELETE
                when matched then update set
                    target.WAC_ACT=src.WAC_ACT, 
                    target.WAC_ASMLEVEL=src.WAC_ASMLEVEL, 
                    target.WAC_COMPLEVEL=src.WAC_COMPLEVEL, 
                    target.WAC_CREATED=src.WAC_CREATED, 
                    target.WAC_DURATION=src.WAC_DURATION, 
                    target.WAC_EST=src.WAC_EST, 
                    target.WAC_HIRE=src.WAC_HIRE, 
                    target.WAC_LABORRTYPE=src.WAC_LABORRTYPE, 
                    target.WAC_LABORTYPE=src.WAC_LABORTYPE, 
                    target.WAC_LASTSAVED=src.WAC_LASTSAVED, 
                    target.WAC_MANUFACT=src.WAC_MANUFACT, 
                    target.WAC_MATLIST=src.WAC_MATLIST, 
                    target.WAC_NOTE=src.WAC_NOTE, 
                    target.WAC_PERSONS=src.WAC_PERSONS, 
                    target.WAC_QTY=src.WAC_QTY, 
                    target.WAC_RPC=src.WAC_RPC, 
                    target.WAC_SPECIAL=src.WAC_SPECIAL, 
                    target.WAC_STANDWORK=src.WAC_STANDWORK, 
                    target.WAC_START=src.WAC_START, 
                    target.WAC_SUPPLIER=src.WAC_SUPPLIER, 
                    target.WAC_SUPPLIER_ORG=src.WAC_SUPPLIER_ORG, 
                    target.WAC_SYSLEVEL=src.WAC_SYSLEVEL, 
                    target.WAC_TASK=src.WAC_TASK, 
                    target.WAC_TPF=src.WAC_TPF, 
                    target.WAC_TRADE=src.WAC_TRADE, 
                    target.WAC_UDFCHAR01=src.WAC_UDFCHAR01, 
                    target.WAC_UDFCHAR02=src.WAC_UDFCHAR02, 
                    target.WAC_UDFCHAR03=src.WAC_UDFCHAR03, 
                    target.WAC_UDFCHAR04=src.WAC_UDFCHAR04, 
                    target.WAC_UDFCHAR05=src.WAC_UDFCHAR05, 
                    target.WAC_UDFCHAR06=src.WAC_UDFCHAR06, 
                    target.WAC_UDFCHAR07=src.WAC_UDFCHAR07, 
                    target.WAC_UDFCHAR08=src.WAC_UDFCHAR08, 
                    target.WAC_UDFCHAR09=src.WAC_UDFCHAR09, 
                    target.WAC_UDFCHAR10=src.WAC_UDFCHAR10, 
                    target.WAC_UDFCHAR11=src.WAC_UDFCHAR11, 
                    target.WAC_UDFCHAR12=src.WAC_UDFCHAR12, 
                    target.WAC_UDFCHAR13=src.WAC_UDFCHAR13, 
                    target.WAC_UDFCHAR14=src.WAC_UDFCHAR14, 
                    target.WAC_UDFCHAR15=src.WAC_UDFCHAR15, 
                    target.WAC_UDFCHAR16=src.WAC_UDFCHAR16, 
                    target.WAC_UDFCHAR17=src.WAC_UDFCHAR17, 
                    target.WAC_UDFCHAR18=src.WAC_UDFCHAR18, 
                    target.WAC_UDFCHAR19=src.WAC_UDFCHAR19, 
                    target.WAC_UDFCHAR20=src.WAC_UDFCHAR20, 
                    target.WAC_UDFCHAR21=src.WAC_UDFCHAR21, 
                    target.WAC_UDFCHAR22=src.WAC_UDFCHAR22, 
                    target.WAC_UDFCHAR23=src.WAC_UDFCHAR23, 
                    target.WAC_UDFCHAR24=src.WAC_UDFCHAR24, 
                    target.WAC_UDFCHAR25=src.WAC_UDFCHAR25, 
                    target.WAC_UDFCHAR26=src.WAC_UDFCHAR26, 
                    target.WAC_UDFCHAR27=src.WAC_UDFCHAR27, 
                    target.WAC_UDFCHAR28=src.WAC_UDFCHAR28, 
                    target.WAC_UDFCHAR29=src.WAC_UDFCHAR29, 
                    target.WAC_UDFCHAR30=src.WAC_UDFCHAR30, 
                    target.WAC_UDFCHKBOX01=src.WAC_UDFCHKBOX01, 
                    target.WAC_UDFCHKBOX02=src.WAC_UDFCHKBOX02, 
                    target.WAC_UDFCHKBOX03=src.WAC_UDFCHKBOX03, 
                    target.WAC_UDFCHKBOX04=src.WAC_UDFCHKBOX04, 
                    target.WAC_UDFCHKBOX05=src.WAC_UDFCHKBOX05, 
                    target.WAC_UDFDATE01=src.WAC_UDFDATE01, 
                    target.WAC_UDFDATE02=src.WAC_UDFDATE02, 
                    target.WAC_UDFDATE03=src.WAC_UDFDATE03, 
                    target.WAC_UDFDATE04=src.WAC_UDFDATE04, 
                    target.WAC_UDFDATE05=src.WAC_UDFDATE05, 
                    target.WAC_UDFNOTE01=src.WAC_UDFNOTE01, 
                    target.WAC_UDFNOTE02=src.WAC_UDFNOTE02, 
                    target.WAC_UDFNUM01=src.WAC_UDFNUM01, 
                    target.WAC_UDFNUM02=src.WAC_UDFNUM02, 
                    target.WAC_UDFNUM03=src.WAC_UDFNUM03, 
                    target.WAC_UDFNUM04=src.WAC_UDFNUM04, 
                    target.WAC_UDFNUM05=src.WAC_UDFNUM05, 
                    target.WAC_UOM=src.WAC_UOM, 
                    target.WAC_UPDATECOUNT=src.WAC_UPDATECOUNT, 
                    target.WAC_UPDATED=src.WAC_UPDATED, 
                    target.WAC_WAP=src.WAC_WAP, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename
        when not matched and (src.ETL_DELETED=FALSE OR src.ETL_DELETED IS NULL)  then insert ( 
                    WAC_ACT, 
                    WAC_ASMLEVEL, 
                    WAC_COMPLEVEL, 
                    WAC_CREATED, 
                    WAC_DURATION, 
                    WAC_EST, 
                    WAC_HIRE, 
                    WAC_LABORRTYPE, 
                    WAC_LABORTYPE, 
                    WAC_LASTSAVED, 
                    WAC_MANUFACT, 
                    WAC_MATLIST, 
                    WAC_NOTE, 
                    WAC_PERSONS, 
                    WAC_QTY, 
                    WAC_RPC, 
                    WAC_SPECIAL, 
                    WAC_STANDWORK, 
                    WAC_START, 
                    WAC_SUPPLIER, 
                    WAC_SUPPLIER_ORG, 
                    WAC_SYSLEVEL, 
                    WAC_TASK, 
                    WAC_TPF, 
                    WAC_TRADE, 
                    WAC_UDFCHAR01, 
                    WAC_UDFCHAR02, 
                    WAC_UDFCHAR03, 
                    WAC_UDFCHAR04, 
                    WAC_UDFCHAR05, 
                    WAC_UDFCHAR06, 
                    WAC_UDFCHAR07, 
                    WAC_UDFCHAR08, 
                    WAC_UDFCHAR09, 
                    WAC_UDFCHAR10, 
                    WAC_UDFCHAR11, 
                    WAC_UDFCHAR12, 
                    WAC_UDFCHAR13, 
                    WAC_UDFCHAR14, 
                    WAC_UDFCHAR15, 
                    WAC_UDFCHAR16, 
                    WAC_UDFCHAR17, 
                    WAC_UDFCHAR18, 
                    WAC_UDFCHAR19, 
                    WAC_UDFCHAR20, 
                    WAC_UDFCHAR21, 
                    WAC_UDFCHAR22, 
                    WAC_UDFCHAR23, 
                    WAC_UDFCHAR24, 
                    WAC_UDFCHAR25, 
                    WAC_UDFCHAR26, 
                    WAC_UDFCHAR27, 
                    WAC_UDFCHAR28, 
                    WAC_UDFCHAR29, 
                    WAC_UDFCHAR30, 
                    WAC_UDFCHKBOX01, 
                    WAC_UDFCHKBOX02, 
                    WAC_UDFCHKBOX03, 
                    WAC_UDFCHKBOX04, 
                    WAC_UDFCHKBOX05, 
                    WAC_UDFDATE01, 
                    WAC_UDFDATE02, 
                    WAC_UDFDATE03, 
                    WAC_UDFDATE04, 
                    WAC_UDFDATE05, 
                    WAC_UDFNOTE01, 
                    WAC_UDFNOTE02, 
                    WAC_UDFNUM01, 
                    WAC_UDFNUM02, 
                    WAC_UDFNUM03, 
                    WAC_UDFNUM04, 
                    WAC_UDFNUM05, 
                    WAC_UOM, 
                    WAC_UPDATECOUNT, 
                    WAC_UPDATED, 
                    WAC_WAP, 
                    _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename) 
            values (
                    src.WAC_ACT, 
                    src.WAC_ASMLEVEL, 
                    src.WAC_COMPLEVEL, 
                    src.WAC_CREATED, 
                    src.WAC_DURATION, 
                    src.WAC_EST, 
                    src.WAC_HIRE, 
                    src.WAC_LABORRTYPE, 
                    src.WAC_LABORTYPE, 
                    src.WAC_LASTSAVED, 
                    src.WAC_MANUFACT, 
                    src.WAC_MATLIST, 
                    src.WAC_NOTE, 
                    src.WAC_PERSONS, 
                    src.WAC_QTY, 
                    src.WAC_RPC, 
                    src.WAC_SPECIAL, 
                    src.WAC_STANDWORK, 
                    src.WAC_START, 
                    src.WAC_SUPPLIER, 
                    src.WAC_SUPPLIER_ORG, 
                    src.WAC_SYSLEVEL, 
                    src.WAC_TASK, 
                    src.WAC_TPF, 
                    src.WAC_TRADE, 
                    src.WAC_UDFCHAR01, 
                    src.WAC_UDFCHAR02, 
                    src.WAC_UDFCHAR03, 
                    src.WAC_UDFCHAR04, 
                    src.WAC_UDFCHAR05, 
                    src.WAC_UDFCHAR06, 
                    src.WAC_UDFCHAR07, 
                    src.WAC_UDFCHAR08, 
                    src.WAC_UDFCHAR09, 
                    src.WAC_UDFCHAR10, 
                    src.WAC_UDFCHAR11, 
                    src.WAC_UDFCHAR12, 
                    src.WAC_UDFCHAR13, 
                    src.WAC_UDFCHAR14, 
                    src.WAC_UDFCHAR15, 
                    src.WAC_UDFCHAR16, 
                    src.WAC_UDFCHAR17, 
                    src.WAC_UDFCHAR18, 
                    src.WAC_UDFCHAR19, 
                    src.WAC_UDFCHAR20, 
                    src.WAC_UDFCHAR21, 
                    src.WAC_UDFCHAR22, 
                    src.WAC_UDFCHAR23, 
                    src.WAC_UDFCHAR24, 
                    src.WAC_UDFCHAR25, 
                    src.WAC_UDFCHAR26, 
                    src.WAC_UDFCHAR27, 
                    src.WAC_UDFCHAR28, 
                    src.WAC_UDFCHAR29, 
                    src.WAC_UDFCHAR30, 
                    src.WAC_UDFCHKBOX01, 
                    src.WAC_UDFCHKBOX02, 
                    src.WAC_UDFCHKBOX03, 
                    src.WAC_UDFCHKBOX04, 
                    src.WAC_UDFCHKBOX05, 
                    src.WAC_UDFDATE01, 
                    src.WAC_UDFDATE02, 
                    src.WAC_UDFDATE03, 
                    src.WAC_UDFDATE04, 
                    src.WAC_UDFDATE05, 
                    src.WAC_UDFNOTE01, 
                    src.WAC_UDFNOTE02, 
                    src.WAC_UDFNUM01, 
                    src.WAC_UDFNUM02, 
                    src.WAC_UDFNUM03, 
                    src.WAC_UDFNUM04, 
                    src.WAC_UDFNUM05, 
                    src.WAC_UOM, 
                    src.WAC_UPDATECOUNT, 
                    src.WAC_UPDATED, 
                    src.WAC_WAP, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename);`;

    var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
    var rs = sqlStmt.execute();

    snowflake.execute( {sqlText: `merge into TARGET_HISTORY_EAM.EAM_R5STANDWACTS_DELETED as target using (
                SELECT * FROM (SELECT 
            strm.WAC_ACT, 
            strm.WAC_ASMLEVEL, 
            strm.WAC_COMPLEVEL, 
            strm.WAC_CREATED, 
            strm.WAC_DURATION, 
            strm.WAC_EST, 
            strm.WAC_HIRE, 
            strm.WAC_LABORRTYPE, 
            strm.WAC_LABORTYPE, 
            strm.WAC_LASTSAVED, 
            strm.WAC_MANUFACT, 
            strm.WAC_MATLIST, 
            strm.WAC_NOTE, 
            strm.WAC_PERSONS, 
            strm.WAC_QTY, 
            strm.WAC_RPC, 
            strm.WAC_SPECIAL, 
            strm.WAC_STANDWORK, 
            strm.WAC_START, 
            strm.WAC_SUPPLIER, 
            strm.WAC_SUPPLIER_ORG, 
            strm.WAC_SYSLEVEL, 
            strm.WAC_TASK, 
            strm.WAC_TPF, 
            strm.WAC_TRADE, 
            strm.WAC_UDFCHAR01, 
            strm.WAC_UDFCHAR02, 
            strm.WAC_UDFCHAR03, 
            strm.WAC_UDFCHAR04, 
            strm.WAC_UDFCHAR05, 
            strm.WAC_UDFCHAR06, 
            strm.WAC_UDFCHAR07, 
            strm.WAC_UDFCHAR08, 
            strm.WAC_UDFCHAR09, 
            strm.WAC_UDFCHAR10, 
            strm.WAC_UDFCHAR11, 
            strm.WAC_UDFCHAR12, 
            strm.WAC_UDFCHAR13, 
            strm.WAC_UDFCHAR14, 
            strm.WAC_UDFCHAR15, 
            strm.WAC_UDFCHAR16, 
            strm.WAC_UDFCHAR17, 
            strm.WAC_UDFCHAR18, 
            strm.WAC_UDFCHAR19, 
            strm.WAC_UDFCHAR20, 
            strm.WAC_UDFCHAR21, 
            strm.WAC_UDFCHAR22, 
            strm.WAC_UDFCHAR23, 
            strm.WAC_UDFCHAR24, 
            strm.WAC_UDFCHAR25, 
            strm.WAC_UDFCHAR26, 
            strm.WAC_UDFCHAR27, 
            strm.WAC_UDFCHAR28, 
            strm.WAC_UDFCHAR29, 
            strm.WAC_UDFCHAR30, 
            strm.WAC_UDFCHKBOX01, 
            strm.WAC_UDFCHKBOX02, 
            strm.WAC_UDFCHKBOX03, 
            strm.WAC_UDFCHKBOX04, 
            strm.WAC_UDFCHKBOX05, 
            strm.WAC_UDFDATE01, 
            strm.WAC_UDFDATE02, 
            strm.WAC_UDFDATE03, 
            strm.WAC_UDFDATE04, 
            strm.WAC_UDFDATE05, 
            strm.WAC_UDFNOTE01, 
            strm.WAC_UDFNOTE02, 
            strm.WAC_UDFNUM01, 
            strm.WAC_UDFNUM02, 
            strm.WAC_UDFNUM03, 
            strm.WAC_UDFNUM04, 
            strm.WAC_UDFNUM05, 
            strm.WAC_UOM, 
            strm.WAC_UPDATECOUNT, 
            strm.WAC_UPDATED, 
            strm.WAC_WAP, 
            strm._DELETED, 
            strm.ETL_LASTSAVED,
            strm.ETL_DELETED,
            strm.etl_load_datetime,
            strm.etl_load_metadatafilename,
            ROW_NUMBER() OVER (PARTITION BY 
            strm.WAC_STANDWORK,
            strm.WAC_ACT ORDER BY strm.ETL_LASTSAVED desc,IFNULL(TRY_TO_TIMESTAMP(replace(right(replace(lower(etl_load_metadatafilename),'.json'),23),'_','-'), 'yyyy-mm-dd-HH-MI-SS-FF') ,etl_load_datetime) desc) as ROWNUMBER
        FROM DATAHUB_INTEGRATION.VW_STREAM_EAM_R5STANDWACTS as  strm
        WHERE strm.ETL_DELETED=TRUE
                    )   
            WHERE ROWNUMBER=1  
            
                    ) as src on
            ((target.WAC_STANDWORK=src.WAC_STANDWORK) OR (target.WAC_STANDWORK IS NULL AND src.WAC_STANDWORK IS NULL)) AND
            ((target.WAC_ACT=src.WAC_ACT) OR (target.WAC_ACT IS NULL AND src.WAC_ACT IS NULL)) 
                when matched then update set
                    target.WAC_ACT=src.WAC_ACT, 
                    target.WAC_ASMLEVEL=src.WAC_ASMLEVEL, 
                    target.WAC_COMPLEVEL=src.WAC_COMPLEVEL, 
                    target.WAC_CREATED=src.WAC_CREATED, 
                    target.WAC_DURATION=src.WAC_DURATION, 
                    target.WAC_EST=src.WAC_EST, 
                    target.WAC_HIRE=src.WAC_HIRE, 
                    target.WAC_LABORRTYPE=src.WAC_LABORRTYPE, 
                    target.WAC_LABORTYPE=src.WAC_LABORTYPE, 
                    target.WAC_LASTSAVED=src.WAC_LASTSAVED, 
                    target.WAC_MANUFACT=src.WAC_MANUFACT, 
                    target.WAC_MATLIST=src.WAC_MATLIST, 
                    target.WAC_NOTE=src.WAC_NOTE, 
                    target.WAC_PERSONS=src.WAC_PERSONS, 
                    target.WAC_QTY=src.WAC_QTY, 
                    target.WAC_RPC=src.WAC_RPC, 
                    target.WAC_SPECIAL=src.WAC_SPECIAL, 
                    target.WAC_STANDWORK=src.WAC_STANDWORK, 
                    target.WAC_START=src.WAC_START, 
                    target.WAC_SUPPLIER=src.WAC_SUPPLIER, 
                    target.WAC_SUPPLIER_ORG=src.WAC_SUPPLIER_ORG, 
                    target.WAC_SYSLEVEL=src.WAC_SYSLEVEL, 
                    target.WAC_TASK=src.WAC_TASK, 
                    target.WAC_TPF=src.WAC_TPF, 
                    target.WAC_TRADE=src.WAC_TRADE, 
                    target.WAC_UDFCHAR01=src.WAC_UDFCHAR01, 
                    target.WAC_UDFCHAR02=src.WAC_UDFCHAR02, 
                    target.WAC_UDFCHAR03=src.WAC_UDFCHAR03, 
                    target.WAC_UDFCHAR04=src.WAC_UDFCHAR04, 
                    target.WAC_UDFCHAR05=src.WAC_UDFCHAR05, 
                    target.WAC_UDFCHAR06=src.WAC_UDFCHAR06, 
                    target.WAC_UDFCHAR07=src.WAC_UDFCHAR07, 
                    target.WAC_UDFCHAR08=src.WAC_UDFCHAR08, 
                    target.WAC_UDFCHAR09=src.WAC_UDFCHAR09, 
                    target.WAC_UDFCHAR10=src.WAC_UDFCHAR10, 
                    target.WAC_UDFCHAR11=src.WAC_UDFCHAR11, 
                    target.WAC_UDFCHAR12=src.WAC_UDFCHAR12, 
                    target.WAC_UDFCHAR13=src.WAC_UDFCHAR13, 
                    target.WAC_UDFCHAR14=src.WAC_UDFCHAR14, 
                    target.WAC_UDFCHAR15=src.WAC_UDFCHAR15, 
                    target.WAC_UDFCHAR16=src.WAC_UDFCHAR16, 
                    target.WAC_UDFCHAR17=src.WAC_UDFCHAR17, 
                    target.WAC_UDFCHAR18=src.WAC_UDFCHAR18, 
                    target.WAC_UDFCHAR19=src.WAC_UDFCHAR19, 
                    target.WAC_UDFCHAR20=src.WAC_UDFCHAR20, 
                    target.WAC_UDFCHAR21=src.WAC_UDFCHAR21, 
                    target.WAC_UDFCHAR22=src.WAC_UDFCHAR22, 
                    target.WAC_UDFCHAR23=src.WAC_UDFCHAR23, 
                    target.WAC_UDFCHAR24=src.WAC_UDFCHAR24, 
                    target.WAC_UDFCHAR25=src.WAC_UDFCHAR25, 
                    target.WAC_UDFCHAR26=src.WAC_UDFCHAR26, 
                    target.WAC_UDFCHAR27=src.WAC_UDFCHAR27, 
                    target.WAC_UDFCHAR28=src.WAC_UDFCHAR28, 
                    target.WAC_UDFCHAR29=src.WAC_UDFCHAR29, 
                    target.WAC_UDFCHAR30=src.WAC_UDFCHAR30, 
                    target.WAC_UDFCHKBOX01=src.WAC_UDFCHKBOX01, 
                    target.WAC_UDFCHKBOX02=src.WAC_UDFCHKBOX02, 
                    target.WAC_UDFCHKBOX03=src.WAC_UDFCHKBOX03, 
                    target.WAC_UDFCHKBOX04=src.WAC_UDFCHKBOX04, 
                    target.WAC_UDFCHKBOX05=src.WAC_UDFCHKBOX05, 
                    target.WAC_UDFDATE01=src.WAC_UDFDATE01, 
                    target.WAC_UDFDATE02=src.WAC_UDFDATE02, 
                    target.WAC_UDFDATE03=src.WAC_UDFDATE03, 
                    target.WAC_UDFDATE04=src.WAC_UDFDATE04, 
                    target.WAC_UDFDATE05=src.WAC_UDFDATE05, 
                    target.WAC_UDFNOTE01=src.WAC_UDFNOTE01, 
                    target.WAC_UDFNOTE02=src.WAC_UDFNOTE02, 
                    target.WAC_UDFNUM01=src.WAC_UDFNUM01, 
                    target.WAC_UDFNUM02=src.WAC_UDFNUM02, 
                    target.WAC_UDFNUM03=src.WAC_UDFNUM03, 
                    target.WAC_UDFNUM04=src.WAC_UDFNUM04, 
                    target.WAC_UDFNUM05=src.WAC_UDFNUM05, 
                    target.WAC_UOM=src.WAC_UOM, 
                    target.WAC_UPDATECOUNT=src.WAC_UPDATECOUNT, 
                    target.WAC_UPDATED=src.WAC_UPDATED, 
                    target.WAC_WAP=src.WAC_WAP, 
                    target._DELETED=src._DELETED, 
                    target.ETL_LASTSAVED=src.ETL_LASTSAVED,
                    target.etl_load_datetime=CURRENT_TIMESTAMP,
                    target.etl_load_metadatafilename=src.etl_load_metadatafilename,
                    target.ETL_DELETED=src.ETL_DELETED
        when not matched   then insert ( WAC_ACT, WAC_ASMLEVEL, WAC_COMPLEVEL, WAC_CREATED, WAC_DURATION, WAC_EST, WAC_HIRE, WAC_LABORRTYPE, WAC_LABORTYPE, WAC_LASTSAVED, WAC_MANUFACT, WAC_MATLIST, WAC_NOTE, WAC_PERSONS, WAC_QTY, WAC_RPC, WAC_SPECIAL, WAC_STANDWORK, WAC_START, WAC_SUPPLIER, WAC_SUPPLIER_ORG, WAC_SYSLEVEL, WAC_TASK, WAC_TPF, WAC_TRADE, WAC_UDFCHAR01, WAC_UDFCHAR02, WAC_UDFCHAR03, WAC_UDFCHAR04, WAC_UDFCHAR05, WAC_UDFCHAR06, WAC_UDFCHAR07, WAC_UDFCHAR08, WAC_UDFCHAR09, WAC_UDFCHAR10, WAC_UDFCHAR11, WAC_UDFCHAR12, WAC_UDFCHAR13, WAC_UDFCHAR14, WAC_UDFCHAR15, WAC_UDFCHAR16, WAC_UDFCHAR17, WAC_UDFCHAR18, WAC_UDFCHAR19, WAC_UDFCHAR20, WAC_UDFCHAR21, WAC_UDFCHAR22, WAC_UDFCHAR23, WAC_UDFCHAR24, WAC_UDFCHAR25, WAC_UDFCHAR26, WAC_UDFCHAR27, WAC_UDFCHAR28, WAC_UDFCHAR29, WAC_UDFCHAR30, WAC_UDFCHKBOX01, WAC_UDFCHKBOX02, WAC_UDFCHKBOX03, WAC_UDFCHKBOX04, WAC_UDFCHKBOX05, WAC_UDFDATE01, WAC_UDFDATE02, WAC_UDFDATE03, WAC_UDFDATE04, WAC_UDFDATE05, WAC_UDFNOTE01, WAC_UDFNOTE02, WAC_UDFNUM01, WAC_UDFNUM02, WAC_UDFNUM03, WAC_UDFNUM04, WAC_UDFNUM05, WAC_UOM, WAC_UPDATECOUNT, WAC_UPDATED, WAC_WAP, _DELETED, 
                    ETL_LASTSAVED,                       
                    etl_load_datetime,
                    etl_load_metadatafilename,
                    etl_is_deleted,
                    ETL_DELETED) 
            values (
                    src.WAC_ACT, 
                    src.WAC_ASMLEVEL, 
                    src.WAC_COMPLEVEL, 
                    src.WAC_CREATED, 
                    src.WAC_DURATION, 
                    src.WAC_EST, 
                    src.WAC_HIRE, 
                    src.WAC_LABORRTYPE, 
                    src.WAC_LABORTYPE, 
                    src.WAC_LASTSAVED, 
                    src.WAC_MANUFACT, 
                    src.WAC_MATLIST, 
                    src.WAC_NOTE, 
                    src.WAC_PERSONS, 
                    src.WAC_QTY, 
                    src.WAC_RPC, 
                    src.WAC_SPECIAL, 
                    src.WAC_STANDWORK, 
                    src.WAC_START, 
                    src.WAC_SUPPLIER, 
                    src.WAC_SUPPLIER_ORG, 
                    src.WAC_SYSLEVEL, 
                    src.WAC_TASK, 
                    src.WAC_TPF, 
                    src.WAC_TRADE, 
                    src.WAC_UDFCHAR01, 
                    src.WAC_UDFCHAR02, 
                    src.WAC_UDFCHAR03, 
                    src.WAC_UDFCHAR04, 
                    src.WAC_UDFCHAR05, 
                    src.WAC_UDFCHAR06, 
                    src.WAC_UDFCHAR07, 
                    src.WAC_UDFCHAR08, 
                    src.WAC_UDFCHAR09, 
                    src.WAC_UDFCHAR10, 
                    src.WAC_UDFCHAR11, 
                    src.WAC_UDFCHAR12, 
                    src.WAC_UDFCHAR13, 
                    src.WAC_UDFCHAR14, 
                    src.WAC_UDFCHAR15, 
                    src.WAC_UDFCHAR16, 
                    src.WAC_UDFCHAR17, 
                    src.WAC_UDFCHAR18, 
                    src.WAC_UDFCHAR19, 
                    src.WAC_UDFCHAR20, 
                    src.WAC_UDFCHAR21, 
                    src.WAC_UDFCHAR22, 
                    src.WAC_UDFCHAR23, 
                    src.WAC_UDFCHAR24, 
                    src.WAC_UDFCHAR25, 
                    src.WAC_UDFCHAR26, 
                    src.WAC_UDFCHAR27, 
                    src.WAC_UDFCHAR28, 
                    src.WAC_UDFCHAR29, 
                    src.WAC_UDFCHAR30, 
                    src.WAC_UDFCHKBOX01, 
                    src.WAC_UDFCHKBOX02, 
                    src.WAC_UDFCHKBOX03, 
                    src.WAC_UDFCHKBOX04, 
                    src.WAC_UDFCHKBOX05, 
                    src.WAC_UDFDATE01, 
                    src.WAC_UDFDATE02, 
                    src.WAC_UDFDATE03, 
                    src.WAC_UDFDATE04, 
                    src.WAC_UDFDATE05, 
                    src.WAC_UDFNOTE01, 
                    src.WAC_UDFNOTE02, 
                    src.WAC_UDFNUM01, 
                    src.WAC_UDFNUM02, 
                    src.WAC_UDFNUM03, 
                    src.WAC_UDFNUM04, 
                    src.WAC_UDFNUM05, 
                    src.WAC_UOM, 
                    src.WAC_UPDATECOUNT, 
                    src.WAC_UPDATED, 
                    src.WAC_WAP, 
                    src._DELETED,     
                    src.ETL_LASTSAVED,
                    CURRENT_TIMESTAMP,
                    src.etl_load_metadatafilename,
                    case when ETL_DELETED=TRUE then TRUE else FALSE end,
                    ETL_DELETED);
    `
} );

                    
//  Get number of rows inserted
        
        var sqlStmt = snowflake.createStatement( {sqlText:  sql_command} );
        var rs = sqlStmt.execute();
        var number_of_rows_inserted = sqlStmt.getNumRowsInserted();
        var number_of_rows_updated =  sqlStmt.getNumRowsUpdated();
                    

        
    snowflake.execute ({sqlText: "commit"});

    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Success','Completed process execution.', 0 ," + number_of_rows_inserted.toString()+ "," +  number_of_rows_updated.toString() + ");";
    snowflake.execute({sqlText: log_sql_command});

    result = "Success"; 

    }       

    catch (err)  {
        snowflake.execute( {sqlText: "rollback;"} )
        var clean_error_msg = err.message.replace(/[^\w\s]/gi, '');
    //  Create a log entry to say INSERT STATEMENT failed
    
    log_sql_command = "call datahub_logging.sp_etl_log_ingestion_process('UpdateEnd','" + process_name + "','Failed','MERGE Failed. Error:" + err.code.toString()+" : "+ clean_error_msg  + "', 0 ,0,0);";
    snowflake.execute({sqlText: log_sql_command});
        ;
        throw "Failed: " + err.message;   // Return a success/error indicator.
        }
    return result;
    $$;