CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFFAM810_DELETED(
            acmc_1 numeric(38, 17), 
            acmc_2 numeric(38, 17), 
            acmc_3 numeric(38, 17), 
            acmt numeric(38, 17), 
            agrp varchar, 
            agrp_ref_compnr integer, 
            amnt_1 numeric(38, 17), 
            amnt_2 numeric(38, 17), 
            amnt_3 numeric(38, 17), 
            amtt numeric(38, 17), 
            compnr integer, 
            ctgy varchar, 
            ctgy_ref_compnr integer, 
            ctgy_sctg_ref_compnr integer, 
            curr varchar, 
            deleted boolean, 
            jobn integer, 
            ltdd_1 numeric(38, 17), 
            ltdd_2 numeric(38, 17), 
            ltdd_3 numeric(38, 17), 
            ltdr_1 numeric(38, 17), 
            ltdr_2 numeric(38, 17), 
            ltdr_3 numeric(38, 17), 
            ratd datetime, 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rcst_1 numeric(38, 17), 
            rcst_2 numeric(38, 17), 
            rcst_3 numeric(38, 17), 
            reas varchar, 
            reas_ref_compnr integer, 
            rtyp varchar, 
            sctg varchar, 
            sequencenumber integer, 
            tagn object, 
            timestamp datetime, 
            tkey integer, 
            tkey_ref_compnr integer, 
            trid integer, 
            user varchar, 
            username varchar, 
            xaex varchar, 
            xanb varchar, 
            xcom integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 