CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TSMDM105_DELETED(
            artp integer, 
            artp_kw varchar, 
            ccha numeric(38, 17), 
            ccur varchar, 
            ccur_ref_compnr integer, 
            clrt varchar, 
            clrt_ref_compnr integer, 
            cmsa varchar, 
            cmsa_ref_compnr integer, 
            compnr integer, 
            csar varchar, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            cwoc varchar, 
            cwoc_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            dist numeric(38, 17), 
            sequencenumber integer, 
            timestamp datetime, 
            trti numeric(38, 17), 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 