CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFGLD205_DELETED(
            bpid varchar, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            compnr integer, 
            cono integer, 
            deleted boolean, 
            dim1 varchar, 
            dim2 varchar, 
            dim3 varchar, 
            dim4 varchar, 
            dim5 varchar, 
            dim6 varchar, 
            dim7 varchar, 
            dim8 varchar, 
            dim9 varchar, 
            dims varchar, 
            dimx_sgm1 varchar, 
            dimx_sgm2 varchar, 
            dm10 varchar, 
            dm11 varchar, 
            dm12 varchar, 
            duac integer, 
            duac_kw varchar, 
            fcah_1 numeric(38, 17), 
            fcah_2 numeric(38, 17), 
            fcah_3 numeric(38, 17), 
            fcah_dtwc numeric(38, 17), 
            fcah_rfrc numeric(38, 17), 
            fcam numeric(38, 17), 
            fdah_1 numeric(38, 17), 
            fdah_2 numeric(38, 17), 
            fdah_3 numeric(38, 17), 
            fdah_dtwc numeric(38, 17), 
            fdah_rfrc numeric(38, 17), 
            fdam numeric(38, 17), 
            fqt1 numeric(38, 17), 
            fqt2 numeric(38, 17), 
            leac varchar, 
            ncah_1 numeric(38, 17), 
            ncah_2 numeric(38, 17), 
            ncah_3 numeric(38, 17), 
            ncah_dtwc numeric(38, 17), 
            ncah_rfrc numeric(38, 17), 
            ncam numeric(38, 17), 
            ndah_1 numeric(38, 17), 
            ndah_2 numeric(38, 17), 
            ndah_3 numeric(38, 17), 
            ndah_dtwc numeric(38, 17), 
            ndah_rfrc numeric(38, 17), 
            ndam numeric(38, 17), 
            nqt1 numeric(38, 17), 
            nqt2 numeric(38, 17), 
            olap integer, 
            prno integer, 
            ptyp integer, 
            ptyp_kw varchar, 
            sequencenumber integer, 
            timestamp datetime, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 