CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TCMCS060_DELETED(
            cadr varchar, 
            cadr_ref_compnr integer, 
            ccty varchar, 
            ccty_ref_compnr integer, 
            cdis varchar, 
            cdis_ref_compnr integer, 
            cmnf varchar, 
            compnr integer, 
            deleted boolean, 
            dsca object, 
            exdt datetime, 
            indt datetime, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            sequencenumber integer, 
            stat integer, 
            stat_kw varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 