CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TIROU001_DELETED(
            bfem varchar, 
            bfem_ref_compnr integer, 
            bfty integer, 
            bfty_kw varchar, 
            bpid varchar, 
            bpid_ref_compnr integer, 
            ccap integer, 
            ccap_kw varchar, 
            compnr integer, 
            cpgr varchar, 
            crmp integer, 
            crmp_kw varchar, 
            crtf integer, 
            crty integer, 
            crty_kw varchar, 
            ctwc varchar, 
            ctwc_ref_compnr integer, 
            cwoc varchar, 
            cwoc_ref_compnr integer, 
            dcru numeric(38, 17), 
            deleted boolean, 
            dque numeric(38, 17), 
            dsca object, 
            kowc integer, 
            kowc_kw varchar, 
            lbdv varchar, 
            mcgr integer, 
            mcgr_kw varchar, 
            mnwc varchar, 
            mnwc_ref_compnr integer, 
            mvtm numeric(38, 17), 
            nomc numeric(38, 17), 
            noop numeric(38, 17), 
            norp integer, 
            obfu integer, 
            oprc varchar, 
            oprc_ref_compnr integer, 
            pddp varchar, 
            pddp_rcmp integer, 
            pddp_ref_compnr integer, 
            plgr varchar, 
            prin integer, 
            prin_kw varchar, 
            qutm numeric(38, 17), 
            rlbr integer, 
            rlbr_kw varchar, 
            "rows" integer, 
            rows_kw varchar, 
            rprd integer, 
            rprd_kw varchar, 
            rpwc varchar, 
            rpwc_ref_compnr integer, 
            scid integer, 
            scid_kw varchar, 
            sequencenumber integer, 
            site varchar, 
            site_ref_compnr integer, 
            stty integer, 
            stty_kw varchar, 
            swcc integer, 
            swct integer, 
            swct_kw varchar, 
            timestamp datetime, 
            tuni integer, 
            tuni_kw varchar, 
            upcs integer, 
            upcs_kw varchar, 
            usco integer, 
            usco_kw varchar, 
            username varchar, 
            wcpg varchar, 
            wcpg_ref_compnr integer, 
            wcru numeric(38, 17), 
            wipw varchar, 
            wipw_ref_compnr integer, 
            wttm numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 