CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPTC120_DELETED(
            amoc numeric(38, 17), 
            amos numeric(38, 17), 
            btdt datetime, 
            cact varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            clas varchar, 
            clas_ref_compnr integer, 
            cnln varchar, 
            cocu varchar, 
            cocu_ref_compnr integer, 
            compnr integer, 
            cona numeric(38, 17), 
            cono varchar, 
            cono_ref_compnr integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cpva integer, 
            cspa varchar, 
            cstl varchar, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            dbgf integer, 
            dbgf_kw varchar, 
            deleted boolean, 
            dfpc integer, 
            dfpc_kw varchar, 
            dlvr integer, 
            effn integer, 
            effn_ref_compnr integer, 
            item varchar, 
            item_ref_compnr integer, 
            lcta numeric(38, 17), 
            leng numeric(38, 17), 
            noun integer, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            pric numeric(38, 17), 
            pris numeric(38, 17), 
            quan numeric(38, 17), 
            rtcc_1 numeric(38, 17), 
            rtcc_2 numeric(38, 17), 
            rtcc_3 numeric(38, 17), 
            rtcs_1 numeric(38, 17), 
            rtcs_2 numeric(38, 17), 
            rtcs_3 numeric(38, 17), 
            rtfc_1 integer, 
            rtfc_2 integer, 
            rtfc_3 integer, 
            rtfs_1 integer, 
            rtfs_2 integer, 
            rtfs_3 integer, 
            sacu varchar, 
            sacu_ref_compnr integer, 
            schd integer, 
            scpf numeric(38, 17), 
            sequencenumber integer, 
            sern integer, 
            stat integer, 
            stat_kw varchar, 
            timestamp datetime, 
            trts integer, 
            trts_kw varchar, 
            tsrl integer, 
            tsrl_kw varchar, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            widt numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 