CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFACP001_DELETED(
            affi integer, 
            affi_kw varchar, 
            compnr integer, 
            defp varchar, 
            defp_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            fisu varchar, 
            sequencenumber integer, 
            text integer, 
            text_ref_compnr integer, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 