CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TSCTM460_DELETED(
            acco_1 numeric(38, 17), 
            acco_2 numeric(38, 17), 
            acco_3 numeric(38, 17), 
            camt_1 numeric(38, 17), 
            camt_2 numeric(38, 17), 
            camt_3 numeric(38, 17), 
            cchn integer, 
            cfln integer, 
            clrv numeric(38, 17), 
            cmdt datetime, 
            cmur varchar, 
            compnr integer, 
            corv numeric(38, 17), 
            corv_dwhc numeric(38, 17), 
            corv_refc numeric(38, 17), 
            crdt datetime, 
            csco varchar, 
            csco_cchn_ref_compnr integer, 
            csco_ref_compnr integer, 
            deleted boolean, 
            erfa numeric(38, 17), 
            ndrc integer, 
            plpr integer, 
            plyr integer, 
            popr integer, 
            poyr integer, 
            prov numeric(38, 17), 
            rahc_1 numeric(38, 17), 
            rahc_2 numeric(38, 17), 
            rahc_3 numeric(38, 17), 
            ratc_1 numeric(38, 17), 
            ratc_2 numeric(38, 17), 
            ratc_3 numeric(38, 17), 
            ratd datetime, 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rcdt datetime, 
            rcur varchar, 
            rtor integer, 
            rtor_kw varchar, 
            seqn integer, 
            sequencenumber integer, 
            stat integer, 
            stat_kw varchar, 
            timestamp datetime, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 