CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPIN060_DELETED(
            addt datetime, 
            adin varchar, 
            cact varchar, 
            carr varchar, 
            carr_ref_compnr integer, 
            cdec varchar, 
            cdec_ref_compnr integer, 
            citt varchar, 
            citt_ref_compnr integer, 
            cnln varchar, 
            compnr integer, 
            cono varchar, 
            cono_cnln_ref_compnr integer, 
            cono_ref_compnr integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cspa varchar, 
            cstl varchar, 
            cstv numeric(38, 17), 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            cwun varchar, 
            cwun_ref_compnr integer, 
            deleted boolean, 
            disc numeric(38, 17), 
            dlld datetime, 
            dlnt varchar, 
            dlor integer, 
            dlor_kw varchar, 
            dlvr integer, 
            dorg integer, 
            dorg_kw varchar, 
            effn integer, 
            effn_ref_compnr integer, 
            fcmp integer, 
            icmp integer, 
            idln integer, 
            idoc integer, 
            inst varchar, 
            item varchar, 
            item_ref_compnr integer, 
            ityp varchar, 
            ldam numeric(38, 17), 
            link integer, 
            link_kw varchar, 
            lssn varchar, 
            lssn_ref_compnr integer, 
            nins integer, 
            ofbp varchar, 
            ofbp_ref_compnr integer, 
            pcad integer, 
            pcad_kw varchar, 
            pono integer, 
            porg integer, 
            porg_kw varchar, 
            pris numeric(38, 17), 
            prsg varchar, 
            ptpa varchar, 
            ptpa_ref_compnr integer, 
            puni varchar, 
            pupd integer, 
            pupd_kw varchar, 
            qshp numeric(38, 17), 
            rcln integer, 
            rcno varchar, 
            rtor integer, 
            rtor_kw varchar, 
            sacu varchar, 
            samt numeric(38, 17), 
            samt_cntc numeric(38, 17), 
            samt_dwhc numeric(38, 17), 
            samt_homc numeric(38, 17), 
            samt_prjc numeric(38, 17), 
            samt_refc numeric(38, 17), 
            samt_rpc1 numeric(38, 17), 
            samt_rpc2 numeric(38, 17), 
            schd integer, 
            sequencenumber integer, 
            sern integer, 
            sfbp varchar, 
            sfbp_ref_compnr integer, 
            shpm varchar, 
            srvc integer, 
            srvc_kw varchar, 
            stad varchar, 
            stad_ref_compnr integer, 
            stbp varchar, 
            stbp_ref_compnr integer, 
            suni varchar, 
            timestamp datetime, 
            twar varchar, 
            twar_ref_compnr integer, 
            username varchar, 
            wght numeric(38, 17), 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 