CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPPC305_DELETED(
            amhc_1 numeric(38, 17), 
            amhc_2 numeric(38, 17), 
            amhc_3 numeric(38, 17), 
            amor numeric(38, 17), 
            amor_cntc numeric(38, 17), 
            amor_dwhc numeric(38, 17), 
            amor_homc numeric(38, 17), 
            amor_prjc numeric(38, 17), 
            amor_refc numeric(38, 17), 
            amor_rpc1 numeric(38, 17), 
            amor_rpc2 numeric(38, 17), 
            bptc varchar, 
            bptc_ref_compnr integer, 
            cact varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            ccty varchar, 
            ccty_cvat_ref_compnr integer, 
            ccty_ref_compnr integer, 
            ccur varchar, 
            ccur_ref_compnr integer, 
            cdoc object, 
            cdru datetime, 
            cdru_cser_ref_compnr integer, 
            ceno varchar, 
            cnln varchar, 
            cntp integer, 
            cntp_kw varchar, 
            comf integer, 
            comf_kw varchar, 
            compnr integer, 
            cono varchar, 
            cono_cnln_ref_compnr integer, 
            cono_ref_compnr integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cpro varchar, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            cpro varchar, 
            cptc varchar, 
            cptc_ref_compnr integer, 
            cptc_year_peri_ref_compnr integer, 
            cptf varchar, 
            cptf_fyea_fper_ref_compnr integer, 
            cptf_ref_compnr integer, 
            crdf integer, 
            crdf_kw varchar, 
            cser integer, 
            cspa varchar, 
            cstl varchar, 
            cstv numeric(38, 17), 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            cvat varchar, 
            cvat_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            drun datetime, 
            drun_serb_ref_compnr integer, 
            emno varchar, 
            emno_ref_compnr integer, 
            entu varchar, 
            exmt integer, 
            exmt_kw varchar, 
            exrs varchar, 
            exrs_ref_compnr integer, 
            fcmp integer, 
            fcrt integer, 
            fcrt_kw varchar, 
            fdoc integer, 
            flin integer, 
            fper integer, 
            frgd datetime, 
            fsrl integer, 
            ftln integer, 
            ftty varchar, 
            fyea integer, 
            guid varchar, 
            hccr_1 numeric(38, 17), 
            hccr_2 numeric(38, 17), 
            hccr_3 numeric(38, 17), 
            idoc integer, 
            iseq integer, 
            itbp varchar, 
            itbp_ref_compnr integer, 
            item varchar, 
            item_ref_compnr integer, 
            itgd varchar, 
            ityp varchar, 
            koor integer, 
            koor_kw varchar, 
            ltdt datetime, 
            nadv integer, 
            ncmp integer, 
            nins integer, 
            ocmp integer, 
            ofbp varchar, 
            ofbp_ref_compnr integer, 
            orno varchar, 
            peri integer, 
            pono integer, 
            potf integer, 
            potf_kw varchar, 
            prdt datetime, 
            rate_1 numeric(38, 17), 
            rate_2 numeric(38, 17), 
            rate_3 numeric(38, 17), 
            ratf_1 integer, 
            ratf_2 integer, 
            ratf_3 integer, 
            rdat datetime, 
            rest integer, 
            rest_kw varchar, 
            rfcr_1 integer, 
            rfcr_2 integer, 
            rfcr_3 integer, 
            rgdt datetime, 
            rsst integer, 
            rsst_kw varchar, 
            rtcr_1 numeric(38, 17), 
            rtcr_2 numeric(38, 17), 
            rtcr_3 numeric(38, 17), 
            rtyp varchar, 
            rtyp_ref_compnr integer, 
            schd integer, 
            sequencenumber integer, 
            serb integer, 
            sern integer, 
            tetl integer, 
            tetl_kw varchar, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            user varchar, 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 