CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TDPUR456_DELETED(
            afrw varchar, 
            amch numeric(38, 17), 
            amld numeric(38, 17), 
            amod numeric(38, 17), 
            arej integer, 
            arej_kw varchar, 
            asnl object, 
            asno object, 
            bgxc integer, 
            bgxc_kw varchar, 
            citr object, 
            cmnf varchar, 
            cmnf_ref_compnr integer, 
            compnr integer, 
            coop_1 numeric(38, 17), 
            coop_2 numeric(38, 17), 
            coop_3 numeric(38, 17), 
            copr_1 numeric(38, 17), 
            copr_2 numeric(38, 17), 
            copr_3 numeric(38, 17), 
            crej varchar, 
            crej_ref_compnr integer, 
            cuva numeric(38, 17), 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            damt numeric(38, 17), 
            ddte datetime, 
            deleted boolean, 
            deln varchar, 
            dino object, 
            fire integer, 
            fire_kw varchar, 
            ftdt datetime, 
            hisa integer, 
            hisa_kw varchar, 
            ldat datetime, 
            load varchar, 
            logn varchar, 
            lssn varchar, 
            lssn_ref_compnr integer, 
            mpnr varchar, 
            mpnr_cmnf_ref_compnr integer, 
            onpr numeric(38, 17), 
            orno varchar, 
            pono integer, 
            qiap numeric(38, 17), 
            qidl numeric(38, 17), 
            qips numeric(38, 17), 
            qirj numeric(38, 17), 
            qual integer, 
            qual_kw varchar, 
            rarc integer, 
            rarc_kw varchar, 
            rcld datetime, 
            rcno varchar, 
            refa object, 
            revi varchar, 
            rseq integer, 
            rsqn integer, 
            sequencenumber integer, 
            sern integer, 
            shdt datetime, 
            shpm varchar, 
            spcn varchar, 
            sqnb integer, 
            timestamp datetime, 
            trdt datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            wght numeric(38, 17), 
            wtun varchar, 
            wtun_ref_compnr integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 