CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPPC200_DELETED(
            afpy varchar, 
            alin integer, 
            alin_kw varchar, 
            amoc numeric(38, 17), 
            amoc_cntc numeric(38, 17), 
            amoc_dwhc numeric(38, 17), 
            amoc_prjc numeric(38, 17), 
            amoc_refc numeric(38, 17), 
            amos numeric(38, 17), 
            amos_cntc numeric(38, 17), 
            amos_dwhc numeric(38, 17), 
            amos_homc numeric(38, 17), 
            amos_prjc numeric(38, 17), 
            amos_refc numeric(38, 17), 
            amos_rpc1 numeric(38, 17), 
            amos_rpc2 numeric(38, 17), 
            base varchar, 
            base_vrsn_ref_compnr integer, 
            blbl integer, 
            blbl_kw varchar, 
            bona varchar, 
            borf varchar, 
            bpcl varchar, 
            bpcl_ref_compnr integer, 
            bpct varchar, 
            bpct_ref_compnr integer, 
            bprc numeric(38, 17), 
            btxt integer, 
            btxt_ref_compnr integer, 
            bwln integer, 
            bwln_kw varchar, 
            cact varchar, 
            ccco varchar, 
            ccco_ref_compnr integer, 
            ccma varchar, 
            ccma_ref_compnr integer, 
            cdf_sref object, 
            cdf_susr object, 
            cdoc object, 
            cdoc_ref_compnr integer, 
            cdru datetime, 
            cdru_cser_ref_compnr integer, 
            ceno varchar, 
            cequ varchar, 
            chpr numeric(38, 17), 
            cico varchar, 
            clin integer, 
            cnln varchar, 
            cohc_1 numeric(38, 17), 
            cohc_2 numeric(38, 17), 
            cohc_3 numeric(38, 17), 
            cohd_1 numeric(38, 17), 
            cohd_2 numeric(38, 17), 
            cohd_3 numeric(38, 17), 
            comf integer, 
            comf_kw varchar, 
            comm_acts varchar, 
            compnr integer, 
            cono varchar, 
            cono_cnln_ref_compnr integer, 
            coob varchar, 
            cotp integer, 
            cotp_kw varchar, 
            cpla varchar, 
            cprj varchar, 
            cprj_cequ varchar, 
            cprj_cico varchar, 
            cprj_cpla_cact_ref_compnr integer, 
            cprj_cspa_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_csub varchar, 
            cprj_ref_compnr integer, 
            cprj_task varchar, 
            cptc varchar, 
            cptc_ref_compnr integer, 
            cptc_year_peri_ref_compnr integer, 
            cptf varchar, 
            cptf_fyea_fper_ref_compnr integer, 
            cptf_ref_compnr integer, 
            cpth varchar, 
            cser integer, 
            cspa varchar, 
            cstl varchar, 
            csts integer, 
            csts_kw varchar, 
            cstv numeric(38, 17), 
            csub varchar, 
            cuni varchar, 
            cuni_ref_compnr integer, 
            curc varchar, 
            curc_ref_compnr integer, 
            curs varchar, 
            curs_ref_compnr integer, 
            cuti varchar, 
            cuti_ref_compnr integer, 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            cvat varchar, 
            cvat_ref_compnr integer, 
            cwar varchar, 
            cwar_ref_compnr integer, 
            cwgt varchar, 
            cwgt_ref_compnr integer, 
            deleted boolean, 
            desc object, 
            drun datetime, 
            drun_serb_ref_compnr integer, 
            ecom integer, 
            effn integer, 
            effn_ref_compnr integer, 
            efph integer, 
            efph_ref_compnr integer, 
            emno varchar, 
            emno_ref_compnr integer, 
            enid varchar, 
            entu varchar, 
            enty integer, 
            enty_kw varchar, 
            exmt integer, 
            exmt_kw varchar, 
            fcmp integer, 
            fcor integer, 
            fcrt integer, 
            fcrt_kw varchar, 
            fdoc integer, 
            fitr integer, 
            fitr_kw varchar, 
            flin integer, 
            fper integer, 
            frdc datetime, 
            frgd datetime, 
            fsrl integer, 
            ftln integer, 
            ftty varchar, 
            fyea integer, 
            guid varchar, 
            hbnr integer, 
            hbyn integer, 
            hbyn_kw varchar, 
            hper integer, 
            hyea integer, 
            idoc integer, 
            ifbp varchar, 
            ifbp_ref_compnr integer, 
            intc integer, 
            intc_kw varchar, 
            inti integer, 
            inti_kw varchar, 
            invo integer, 
            invo_kw varchar, 
            isln integer, 
            itco integer, 
            item varchar, 
            item_ref_compnr integer, 
            itgd varchar, 
            itln integer, 
            itor varchar, 
            ityp varchar, 
            koor integer, 
            koor_kw varchar, 
            lcln integer, 
            lcor integer, 
            ltdt datetime, 
            ncmp integer, 
            ntbl integer, 
            ntbl_kw varchar, 
            oboi varchar, 
            obon varchar, 
            obor varchar, 
            ocmp integer, 
            ohpr numeric(38, 17), 
            oitm varchar, 
            oitm_ref_compnr integer, 
            oldf integer, 
            oldf_kw varchar, 
            orno varchar, 
            otbp varchar, 
            otbp_ref_compnr integer, 
            ovhd varchar, 
            ovhd_ref_compnr integer, 
            peri integer, 
            phit varchar, 
            phit_ref_compnr integer, 
            pono integer, 
            potf integer, 
            potf_kw varchar, 
            prdt datetime, 
            pric numeric(38, 17), 
            pris numeric(38, 17), 
            pstt integer, 
            pstt_kw varchar, 
            ptyc integer, 
            ptyc_kw varchar, 
            quan numeric(38, 17), 
            quan_base_time numeric(38, 17), 
            quan_buar numeric(38, 17), 
            quan_buln numeric(38, 17), 
            quan_bupc numeric(38, 17), 
            quan_buvl numeric(38, 17), 
            quan_buwg numeric(38, 17), 
            rcln integer, 
            rcno varchar, 
            rcod varchar, 
            rcod_ref_compnr integer, 
            rdas datetime, 
            rdat datetime, 
            reas varchar, 
            reas_ref_compnr integer, 
            retx integer, 
            retx_kw varchar, 
            rgdt datetime, 
            rlin integer, 
            rsqn integer, 
            rtcc_1 numeric(38, 17), 
            rtcc_2 numeric(38, 17), 
            rtcc_3 numeric(38, 17), 
            rtcs_1 numeric(38, 17), 
            rtcs_2 numeric(38, 17), 
            rtcs_3 numeric(38, 17), 
            rtfc_1 integer, 
            rtfc_2 integer, 
            rtfc_3 integer, 
            rtfs_1 integer, 
            rtfs_2 integer, 
            rtfs_3 integer, 
            rttp integer, 
            rttp_kw varchar, 
            rtyp varchar, 
            rtyp_ref_compnr integer, 
            sequencenumber integer, 
            serb integer, 
            serh integer, 
            sern integer, 
            snec integer, 
            spln integer, 
            srnb integer, 
            srni integer, 
            sttl integer, 
            sttl_kw varchar, 
            task varchar, 
            time numeric(38, 17), 
            timestamp datetime, 
            tror integer, 
            tror_kw varchar, 
            trsl integer, 
            trsl_kw varchar, 
            txct varchar, 
            txct_cvat_ref_compnr integer, 
            txct_ref_compnr integer, 
            txta integer, 
            txta_ref_compnr integer, 
            user varchar, 
            username varchar, 
            vrln integer, 
            vrsn integer, 
            xgui varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 