CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TSCTM131_DELETED(
            alco_1 numeric(38, 17), 
            alco_2 numeric(38, 17), 
            alco_3 numeric(38, 17), 
            alco_cntc numeric(38, 17), 
            alco_dwhc numeric(38, 17), 
            alco_refc numeric(38, 17), 
            alqu numeric(38, 17), 
            alqu_buar numeric(38, 17), 
            alqu_buln numeric(38, 17), 
            alqu_bupc numeric(38, 17), 
            alqu_buvl numeric(38, 17), 
            alqu_buwg numeric(38, 17), 
            alqu_invu numeric(38, 17), 
            alsa numeric(38, 17), 
            alsa_dwhc numeric(38, 17), 
            alsa_homc numeric(38, 17), 
            alsa_refc numeric(38, 17), 
            alsa_rpc1 numeric(38, 17), 
            alsa_rpc2 numeric(38, 17), 
            amnt numeric(38, 17), 
            amnt_dwhc numeric(38, 17), 
            amnt_homc numeric(38, 17), 
            amnt_refc numeric(38, 17), 
            amnt_rpc1 numeric(38, 17), 
            amnt_rpc2 numeric(38, 17), 
            camt_1 numeric(38, 17), 
            camt_2 numeric(38, 17), 
            camt_3 numeric(38, 17), 
            camt_cntc numeric(38, 17), 
            camt_dwhc numeric(38, 17), 
            camt_refc numeric(38, 17), 
            ccmp varchar, 
            ccmp_ref_compnr integer, 
            cctp varchar, 
            cctp_ref_compnr integer, 
            cdis_1 varchar, 
            cdis_10 varchar, 
            cdis_11 varchar, 
            cdis_2 varchar, 
            cdis_3 varchar, 
            cdis_4 varchar, 
            cdis_5 varchar, 
            cdis_6 varchar, 
            cdis_7 varchar, 
            cdis_8 varchar, 
            cdis_9 varchar, 
            cfln integer, 
            compnr integer, 
            cotp integer, 
            cotp_kw varchar, 
            cseq integer, 
            csgr varchar, 
            csgr_ref_compnr integer, 
            deleted boolean, 
            disc_1 numeric(38, 17), 
            disc_10 numeric(38, 17), 
            disc_11 numeric(38, 17), 
            disc_2 numeric(38, 17), 
            disc_3 numeric(38, 17), 
            disc_4 numeric(38, 17), 
            disc_5 numeric(38, 17), 
            disc_6 numeric(38, 17), 
            disc_7 numeric(38, 17), 
            disc_8 numeric(38, 17), 
            disc_9 numeric(38, 17), 
            dmde_1 varchar, 
            dmde_10 varchar, 
            dmde_11 varchar, 
            dmde_2 varchar, 
            dmde_3 varchar, 
            dmde_4 varchar, 
            dmde_5 varchar, 
            dmde_6 varchar, 
            dmde_7 varchar, 
            dmde_8 varchar, 
            dmde_9 varchar, 
            dmse_1 integer, 
            dmse_10 integer, 
            dmse_11 integer, 
            dmse_2 integer, 
            dmse_3 integer, 
            dmse_4 integer, 
            dmse_5 integer, 
            dmse_6 integer, 
            dmse_7 integer, 
            dmse_8 integer, 
            dmse_9 integer, 
            dmth_1 integer, 
            dmth_10 integer, 
            dmth_11 integer, 
            dmth_2 integer, 
            dmth_3 integer, 
            dmth_4 integer, 
            dmth_5 integer, 
            dmth_6 integer, 
            dmth_7 integer, 
            dmth_8 integer, 
            dmth_9 integer, 
            dmth_kw_1 varchar, 
            dmth_kw_10 varchar, 
            dmth_kw_11 varchar, 
            dmth_kw_2 varchar, 
            dmth_kw_3 varchar, 
            dmth_kw_4 varchar, 
            dmth_kw_5 varchar, 
            dmth_kw_6 varchar, 
            dmth_kw_7 varchar, 
            dmth_kw_8 varchar, 
            dmth_kw_9 varchar, 
            dmty_1 integer, 
            dmty_10 integer, 
            dmty_11 integer, 
            dmty_2 integer, 
            dmty_3 integer, 
            dmty_4 integer, 
            dmty_5 integer, 
            dmty_6 integer, 
            dmty_7 integer, 
            dmty_8 integer, 
            dmty_9 integer, 
            dmty_kw_1 varchar, 
            dmty_kw_10 varchar, 
            dmty_kw_11 varchar, 
            dmty_kw_2 varchar, 
            dmty_kw_3 varchar, 
            dmty_kw_4 varchar, 
            dmty_kw_5 varchar, 
            dmty_kw_6 varchar, 
            dmty_kw_7 varchar, 
            dmty_kw_8 varchar, 
            dmty_kw_9 varchar, 
            dorg_1 integer, 
            dorg_10 integer, 
            dorg_11 integer, 
            dorg_2 integer, 
            dorg_3 integer, 
            dorg_4 integer, 
            dorg_5 integer, 
            dorg_6 integer, 
            dorg_7 integer, 
            dorg_8 integer, 
            dorg_9 integer, 
            dorg_kw_1 varchar, 
            dorg_kw_10 varchar, 
            dorg_kw_11 varchar, 
            dorg_kw_2 varchar, 
            dorg_kw_3 varchar, 
            dorg_kw_4 varchar, 
            dorg_kw_5 varchar, 
            dorg_kw_6 varchar, 
            dorg_kw_7 varchar, 
            dorg_kw_8 varchar, 
            dorg_kw_9 varchar, 
            dspc integer, 
            dspc_kw varchar, 
            dtrm integer, 
            dtrm_kw varchar, 
            ealc_1 numeric(38, 17), 
            ealc_2 numeric(38, 17), 
            ealc_3 numeric(38, 17), 
            ealc_cntc numeric(38, 17), 
            ealc_dwhc numeric(38, 17), 
            ealc_refc numeric(38, 17), 
            eals numeric(38, 17), 
            eals_dwhc numeric(38, 17), 
            eals_homc numeric(38, 17), 
            eals_refc numeric(38, 17), 
            eals_rpc1 numeric(38, 17), 
            eals_rpc2 numeric(38, 17), 
            eaqu numeric(38, 17), 
            eaqu_buar numeric(38, 17), 
            eaqu_buln numeric(38, 17), 
            eaqu_bupc numeric(38, 17), 
            eaqu_butm numeric(38, 17), 
            eaqu_buvl numeric(38, 17), 
            eaqu_buwg numeric(38, 17), 
            eaqu_invu numeric(38, 17), 
            elgb integer, 
            elgb_kw varchar, 
            item varchar, 
            item_ref_compnr integer, 
            ldam_1 numeric(38, 17), 
            ldam_10 numeric(38, 17), 
            ldam_11 numeric(38, 17), 
            ldam_2 numeric(38, 17), 
            ldam_3 numeric(38, 17), 
            ldam_4 numeric(38, 17), 
            ldam_5 numeric(38, 17), 
            ldam_6 numeric(38, 17), 
            ldam_7 numeric(38, 17), 
            ldam_8 numeric(38, 17), 
            ldam_9 numeric(38, 17), 
            nrbt integer, 
            pmde varchar, 
            pmse integer, 
            porg integer, 
            porg_kw varchar, 
            pric_1 numeric(38, 17), 
            pric_2 numeric(38, 17), 
            pric_3 numeric(38, 17), 
            pris numeric(38, 17), 
            quan numeric(38, 17), 
            quan_buar numeric(38, 17), 
            quan_buln numeric(38, 17), 
            quan_bupc numeric(38, 17), 
            quan_buvl numeric(38, 17), 
            quan_buwg numeric(38, 17), 
            quan_invu numeric(38, 17), 
            sequencenumber integer, 
            spco_1 numeric(38, 17), 
            spco_2 numeric(38, 17), 
            spco_3 numeric(38, 17), 
            spco_cntc numeric(38, 17), 
            spco_dwhc numeric(38, 17), 
            spco_refc numeric(38, 17), 
            spqu numeric(38, 17), 
            spqu_buar numeric(38, 17), 
            spqu_buln numeric(38, 17), 
            spqu_bupc numeric(38, 17), 
            spqu_buvl numeric(38, 17), 
            spqu_buwg numeric(38, 17), 
            spqu_invu numeric(38, 17), 
            spsa numeric(38, 17), 
            spsa_dwhc numeric(38, 17), 
            spsa_homc numeric(38, 17), 
            spsa_refc numeric(38, 17), 
            spsa_rpc1 numeric(38, 17), 
            spsa_rpc2 numeric(38, 17), 
            tcam numeric(38, 17), 
            tcqa numeric(38, 17), 
            term integer, 
            term_cfln_cctp_cotp_nrbt_ref_compnr integer, 
            term_cfln_ref_compnr integer, 
            timestamp datetime, 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 