CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFFAM807_DELETED(
            acct varchar, 
            acqa_1 numeric(38, 17), 
            acqa_2 numeric(38, 17), 
            acqa_3 numeric(38, 17), 
            adja_1 numeric(38, 17), 
            adja_2 numeric(38, 17), 
            adja_3 numeric(38, 17), 
            book varchar, 
            book_ref_compnr integer, 
            comp integer, 
            compnr integer, 
            deleted boolean, 
            depr_1 numeric(38, 17), 
            depr_2 numeric(38, 17), 
            depr_3 numeric(38, 17), 
            dim1 varchar, 
            dim2 varchar, 
            dim3 varchar, 
            dim4 varchar, 
            dim5 varchar, 
            dim6 varchar, 
            dim7 varchar, 
            dim8 varchar, 
            dim9 varchar, 
            dims varchar, 
            disa_1 numeric(38, 17), 
            disa_2 numeric(38, 17), 
            disa_3 numeric(38, 17), 
            dm10 varchar, 
            dm11 varchar, 
            dm12 varchar, 
            idtc varchar, 
            lkey integer, 
            proa_1 numeric(38, 17), 
            proa_2 numeric(38, 17), 
            proa_3 numeric(38, 17), 
            prod integer, 
            rcst_1 numeric(38, 17), 
            rcst_2 numeric(38, 17), 
            rcst_3 numeric(38, 17), 
            rdpr_1 numeric(38, 17), 
            rdpr_2 numeric(38, 17), 
            rdpr_3 numeric(38, 17), 
            sequencenumber integer, 
            timestamp datetime, 
            traa_1 numeric(38, 17), 
            traa_2 numeric(38, 17), 
            traa_3 numeric(38, 17), 
            trct_1 numeric(38, 17), 
            trct_2 numeric(38, 17), 
            trct_3 numeric(38, 17), 
            username varchar, 
            year integer, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 