CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TFACP260_DELETED(
            byer varchar, 
            clus varchar, 
            compnr integer, 
            deleted boolean, 
            idoc integer, 
            ityp varchar, 
            load varchar, 
            loco integer, 
            logd date, 
            logt integer, 
            mess object, 
            orno varchar, 
            otyp integer, 
            otyp_kw varchar, 
            pono integer, 
            sequencenumber integer, 
            shpi varchar, 
            sqnb integer, 
            timestamp datetime, 
            user varchar, 
            username varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 