CREATE OR REPLACE TABLE TARGET_HISTORY_LN.LN_TPPSS200_DELETED(
            acmn varchar, 
            acmn_ref_compnr integer, 
            actp integer, 
            addr varchar, 
            addr_ref_compnr integer, 
            aext varchar, 
            afdt datetime, 
            afrt integer, 
            afrt_kw varchar, 
            anbr varchar, 
            asdt datetime, 
            avtp varchar, 
            avtp_ref_compnr integer, 
            blbl integer, 
            blbl_kw varchar, 
            cact varchar, 
            capa integer, 
            capa_kw varchar, 
            capt integer, 
            capt_kw varchar, 
            ccal varchar, 
            ccat varchar, 
            ccat_ref_compnr integer, 
            cctr integer, 
            cctr_kw varchar, 
            cdf_awip numeric(38, 17), 
            cdf_camt numeric(38, 17), 
            cdf_depm integer, 
            cdf_depm_kw varchar, 
            cdf_uamt numeric(38, 17), 
            cloc varchar, 
            cnsd datetime, 
            cnst integer, 
            cnst_kw varchar, 
            coel varchar, 
            coel_rcmp integer, 
            compnr integer, 
            cpla varchar, 
            cprj varchar, 
            cprj_cloc_ref_compnr integer, 
            cprj_cpla_lact_ref_compnr integer, 
            cprj_cpla_pact_ref_compnr integer, 
            cprj_cpla_ref_compnr integer, 
            cprj_cstl_ref_compnr integer, 
            cprj_ref_compnr integer, 
            creg varchar, 
            creg_ref_compnr integer, 
            csec varchar, 
            csec_ref_compnr integer, 
            cspt integer, 
            cspt_kw varchar, 
            cstg varchar, 
            cstg_ref_compnr integer, 
            cstl varchar, 
            cstv numeric(38, 17), 
            cuni varchar, 
            cuni_ref_compnr integer, 
            cuti varchar, 
            cuti_ref_compnr integer, 
            cuvc varchar, 
            cuvc_ref_compnr integer, 
            ddln datetime, 
            deleted boolean, 
            desc object, 
            dfac varchar, 
            dfac_ref_compnr integer, 
            dura numeric(38, 17), 
            dwar varchar, 
            dwar_ref_compnr integer, 
            efdt datetime, 
            eoid varchar, 
            eoty integer, 
            eoty_kw varchar, 
            esdt datetime, 
            ffhr numeric(38, 17), 
            fref numeric(38, 17), 
            freq numeric(38, 17), 
            glat numeric(38, 17), 
            glon numeric(38, 17), 
            gris integer, 
            hbyn integer, 
            hbyn_kw varchar, 
            lact varchar, 
            levl integer, 
            lfdt datetime, 
            litm varchar, 
            litm_ref_compnr integer, 
            llnr integer, 
            lsdt datetime, 
            lvps integer, 
            lvps_kw varchar, 
            mamt numeric(38, 17), 
            mevl integer, 
            mevl_kw varchar, 
            ohdt datetime, 
            pact varchar, 
            pcom numeric(38, 17), 
            plmc integer, 
            plmp varchar, 
            prin integer, 
            prin_kw varchar, 
            pris numeric(38, 17), 
            prms numeric(38, 17), 
            prnd numeric(38, 17), 
            prsp numeric(38, 17), 
            prss numeric(38, 17), 
            prst numeric(38, 17), 
            pwar varchar, 
            pwar_ref_compnr integer, 
            qans numeric(38, 17), 
            quan numeric(38, 17), 
            qutm numeric(38, 17), 
            rcod varchar, 
            rcod_ref_compnr integer, 
            rdas datetime, 
            rdse datetime, 
            rent integer, 
            rent_kw varchar, 
            rfac varchar, 
            rfsa_1 integer, 
            rfsa_2 integer, 
            rfsa_3 integer, 
            rfse_1 integer, 
            rfse_2 integer, 
            rfse_3 integer, 
            rout varchar, 
            rtsa_1 numeric(38, 17), 
            rtsa_2 numeric(38, 17), 
            rtsa_3 numeric(38, 17), 
            rtse_1 numeric(38, 17), 
            rtse_2 numeric(38, 17), 
            rtse_3 numeric(38, 17), 
            sacu varchar, 
            sacu_ref_compnr integer, 
            scmd integer, 
            scmd_kw varchar, 
            sdch integer, 
            sdch_kw varchar, 
            seak object, 
            secu varchar, 
            secu_ref_compnr integer, 
            sequencenumber integer, 
            setl integer, 
            setl_kw varchar, 
            sfdt datetime, 
            ssdt datetime, 
            stat integer, 
            stat_kw varchar, 
            tact integer, 
            tact_kw varchar, 
            tfhr numeric(38, 17), 
            timestamp datetime, 
            tmud varchar, 
            tmud_ref_compnr integer, 
            totf numeric(38, 17), 
            txta integer, 
            txta_ref_compnr integer, 
            username varchar, 
            wast integer, 
            wast_kw varchar, 
            ETL_DELETED boolean,
            ETL_SEQUENCE_NUMBER integer, 
            etl_load_datetime timestamp,
            etl_load_metadatafilename varchar,
            ETL_IS_DELETED boolean default false
            ); 