create or replace TABLE DATAHUB_STAGING.STG35_IPS_SM_BILLING_OUT_OF_CYCLE (
	REQUEST_TYPE VARCHAR(20),
	UNITID VARCHAR(50),
	SERNO VARCHAR(20),
	UNITID_CLEAN VARCHAR(50),
	COMPKEY NUMBER(38,0),
	ROUTEID VARCHAR(16),
	SCHEDULED_READDATE DATE
);