-- DATAHUB_STAGING.STG60_IPS_SM_BILLING_READKEY definition

create or replace TABLE DATAHUB_STAGING.STG60_IPS_SM_BILLING_READKEY (
	COMPKEY NUMBER(38,0),
	UNITID VARCHAR(50),
	READ_DATE DATE,
	CURRENT_READ_DATE DATE,
	READINGKEY NUMBER(38,0)
);